/**
 * Fully authored reference card for contract tests and coach-authoring guidance.
 * It deliberately remains in review: an exact-match media reviewer and
 * independent publishing reviewer must supply external evidence.
 */
export const PRODUCTION_REFERENCE_CARD_DRAFT = Object.freeze({
  id: 'reference-incline-push-up',
  slug: 'incline-push-up',
  canonicalName: 'Incline Push-Up',
  displayName: 'Incline Push-Up',
  description: 'A horizontal pushing exercise performed with the hands on a stable elevated surface to reduce relative upper-body load while preserving a rigid trunk and controlled shoulder movement.',
  aliases: ['elevated push-up', 'hands-elevated push-up'],
  familyKey: 'horizontal_push',
  schemaVersion: '1.0.0',
  cardVersion: 1,
  status: 'review',
  contentConfidence: 95,
  scoringConfidence: 90,
  mediaConfidence: 20,
  movementPatterns: ['horizontal_push', 'anti_extension'],
  bodyRegions: ['upper_body', 'trunk'],
  requiredEquipment: ['box'],
  optionalEquipment: ['bench'],
  environment: {
    environments: ['indoor', 'outdoor'],
    surface: ['flat', 'non_slip'],
    floorAreaSquareFeet: 20,
    stationCapacity: 2,
    ceilingHeightFeet: 7,
    noiseLevel: 'low',
    privacyRequired: false,
  },
  population: {
    ageMin: 8,
    ageMax: 99,
    trainingAgeMonthsMin: 0,
    athleteCompatibility: 92,
    exclusions: ['acute_wrist_pain', 'acute_shoulder_pain', 'unable_to_support_bodyweight_through_arms'],
    considerations: ['adjust surface height to current pressing strength', 'use neutral-grip handles when wrist extension is not tolerated'],
  },
  anatomy: {
    primaryMuscles: ['pectoralis_major', 'triceps_brachii'],
    secondaryMuscles: ['anterior_deltoid', 'serratus_anterior'],
    stabilizers: ['rectus_abdominis', 'obliques', 'gluteus_maximus', 'rotator_cuff'],
    joints: ['shoulder', 'elbow', 'scapulothoracic', 'wrist'],
    jointActions: ['shoulder_horizontal_adduction', 'elbow_extension', 'scapular_protraction', 'trunk_anti_extension'],
    planes: ['sagittal', 'transverse'],
    laterality: 'bilateral',
  },
  athleteSupport: {
    whyItMatters: 'Builds pressing strength and whole-body control using a height that lets every repetition stay clean.',
    primaryCue: 'Move your chest and hips together.',
    secondaryCues: ['Push the surface away.', 'Finish with long arms without shrugging.'],
    expectedSensations: ['chest and back-of-arm effort', 'abdominal tension', 'shoulder blades moving around the ribs'],
    unexpectedSensations: ['sharp wrist pain', 'pinching at the front or top of the shoulder', 'low-back pressure'],
    painGuidance: 'Stop immediately for sharp, increasing, radiating, or joint pain and tell the coach. Normal muscle effort should settle during rest.',
    selfChecks: ['body remains in one straight line', 'chest reaches the same target each repetition', 'last repetition looks like the first'],
    accessibility: {
      reducedWristExtension: 'Use push-up handles or a stable neutral-grip surface.',
      reducedStrength: 'Raise the hand surface.',
      hearingSupport: 'Use the demonstrated start/stop hand signals.',
      cognitiveSupport: 'Use one cue, a visible chest target, and sets of three.',
    },
    readingLevel: 'plain_language',
    localizationKey: 'exercise.incline_push_up',
    mediaAlternatives: {
      captionsRequired: true,
      transcriptRequired: true,
      stillSequenceRequired: true,
      audioDescriptionRequired: true,
      requiredAngles: ['side', 'front_oblique'],
    },
  },
  coachSupport: {
    observationChecklist: [
      'hands are secure and surface cannot slide',
      'head, ribs, pelvis, and heels move as one unit',
      'elbows track approximately 20-45 degrees from the torso',
      'shoulder blades move without shrugging or winging',
      'range and tempo remain consistent',
    ],
    faultCorrections: [
      { fault: 'hips_sag', likelyCause: 'surface too low or brace not understood', cue: 'zip ribs toward pelvis', regression: 'raise hand surface' },
      { fault: 'shoulder_shrug', likelyCause: 'fatigue or poor finish', cue: 'push the surface away with a long neck', regression: 'reduce reps' },
      { fault: 'short_range', likelyCause: 'target absent or load too high', cue: 'touch the chest target', regression: 'raise hand surface' },
      { fault: 'wrist_discomfort', likelyCause: 'extension intolerance', cue: 'keep pressure through the whole hand', regression: 'use neutral-grip handles' },
    ],
    demonstrationPlan: {
      angles: ['side', 'front_oblique'],
      showCorrectReps: 2,
      showCommonFaults: ['hips_sag', 'shoulder_shrug'],
      comprehensionCheck: 'Ask the athlete to point to the chest target and repeat the stop rule.',
    },
    groupManagement: {
      format: 'stations_or_pairs',
      athletesPerStation: 2,
      coachSightLine: 'side or front-oblique view of trunk and elbows',
      queueRule: 'partner rests and checks body-line while the other works',
      equipmentSharing: 'one stable surface per pair',
    },
    modificationDecisionTree: [
      { when: 'pain_or_neurological_symptoms', action: 'stop_and_escalate' },
      { when: 'body_line_or_range_fails_before_target_reps', action: 'raise_surface_or_reduce_reps' },
      { when: 'target_reps_are_clean_below_rpe_5', action: 'lower_surface_one_step_next_set' },
      { when: 'instructions_not_understood', action: 'use_one_cue_and_three_rep_rehearsal' },
    ],
    cueOptions: {
      external: ['Move your chest to the target.', 'Push the box away.'],
      visual: ['Use a dowel line from head to heel.', 'Mark a consistent chest target.'],
      analogy: ['Move like a solid elevator platform.'],
    },
    doNotUseWhen: [
      'the support surface is unstable or can slide',
      'the athlete cannot bear weight through the hands without pain',
      'pressing fatigue would compromise a later priority skill',
    ],
    incidentPrompt: 'Record pain location, onset, repetition, surface height, immediate action, and whether medical escalation was initiated.',
  },
  supportOperations: {
    issueCategories: ['unsafe', 'unclear_instruction', 'inaccurate', 'duplicate', 'inaccessible', 'broken_media'],
    supportEscalation: {
      safety: 'remove_from_release_and_alert_library_owner',
      brokenMedia: 'quarantine_media_and_schedule_re_review',
      contentQuestion: 'route_to_coaching_content_queue',
    },
    retentionPolicy: {
      athleteFeedbackDays: 365,
      incidentEvidence: 'facility_policy',
      rawFreeTextContainsHealthData: true,
    },
    changeImpactPolicy: {
      safetyChange: 'invalidate_current_release_and_notify_workout_owners',
      instructionChange: 'new_card_version',
      mediaChange: 'invalidate_media_review',
      scoreChange: 'revalidate_saved_templates',
    },
    feedbackPrompts: ['pain', 'difficulty', 'confidence', 'clarity', 'equipment_problem'],
  },
  approvedVideoUrl: null,
  variants: [{
    id: 'reference-incline-push-up-baseline',
    variantKey: 'baseline',
    displayName: 'Incline Push-Up',
    modifierKeys: ['reduce_impact'],
    difficulty: {
      technicalComplexity: 28,
      absoluteLoadDemand: 25,
      coordinationDemand: 24,
      supervisionDemand: 18,
      failureConsequence: 20,
      impact: 5,
      workCapacityDemand: 35,
      baseOverallDifficulty: 28,
    },
    requirements: {
      equipmentQuantityPerStation: { box: 1 },
      spotting: false,
      coachSupervision: 'optional',
    },
    loadProfile: {
      gripDemand: 12,
      spinalLoading: 8,
      eccentricStress: 25,
      landingContactsPerRep: 0,
      externalLoadMethod: 'relative_external',
    },
    fatigueProfile: {
      localMuscleFatigue: 40,
      gripFatigue: 12,
      technicalFatigueSensitivity: 35,
      impactAccumulation: 1,
      recoveryHours: 24,
    },
    programming: {
      trainingStimuli: ['upper_body_strength', 'trunk_control', 'scapular_control'],
      stimulusDose: { minimumEffectiveReps: 8, typicalReps: 18, maximumUsefulReps: 36 },
      weeklyExposure: { minimum: 1, typical: 2, maximum: 4, minimumRecoveryHours: 24 },
      prerequisites: ['pain_free_hand_support', 'stable_elevated_surface', 'understands_stop_command'],
      completionCriteria: ['3_sets_of_10_at_rpe_6_or_less', 'full_range_and_body_line_on_every_rep'],
      sequenceRules: {
        preferredAfter: ['general_warm_up', 'wrist_and_shoulder_access'],
        preferredBefore: ['high_fatigue_pressing', 'conditioning'],
        avoidAfter: ['high_volume_pressing', 'hand_support_fatigue'],
      },
      pairingCompatibility: {
        recommended: ['lower_body_strength', 'low_demand_mobility'],
        acceptable: ['horizontal_pull'],
        incompatible: ['max_effort_upper_body_push'],
      },
      interferenceRules: [
        { stimulus: 'handstand_or_tumbling_priority', action: 'place_after_skill_or_use_low_dose' },
        { stimulus: 'heavy_horizontal_press', action: 'reduce_volume_or_omit' },
      ],
      uncertaintyPolicy: 'Exclude when surface stability, wrist tolerance, or current pressing readiness is unknown.',
    },
    status: 'review',
    profiles: [{
      id: 'reference-incline-push-up-capacity',
      profileKey: 'capacity-strength',
      phaseKey: 'capacity',
      role: 'primary',
      purpose: 'Develop repeatable horizontal pressing strength while preserving trunk and scapular control.',
      phaseSuitability: 94,
      methodologyAlignment: 90,
      objectiveRelevance: { general_athletic_development: 82, strength_priority: 95, default: 75 },
      dosage: { sets: 3, reps: 8, workSeconds: 30, restSeconds: 60, rpe: [5, 7], tempo: '2-1-1' },
      qualityGate: 'Every repetition uses the planned range with head, ribs, pelvis, and heels moving together.',
      stopRules: ['Stop for pain or neurological symptoms.', 'End the set when body line, range, or scapular control changes twice.'],
      coachInstructions: 'Select the lowest stable surface that permits the target range and RPE. Observe from the side or front-oblique angle and adjust height before adding repetitions.',
      athleteInstructions: 'Keep your body long, lower your chest to the target, and push the surface away. Stop and tell your coach if a wrist or shoulder hurts.',
      expectedAdaptation: 'Improved horizontal pressing strength, scapular control, and trunk stiffness.',
      equipmentRequired: ['box'],
      logistics: {
        stationCapacity: 2,
        stationCountMethod: 'ceil_athletes_divided_by_capacity',
        equipmentQuantityPerStation: { box: 1 },
        coachSightLine: 'side_or_front_oblique',
      },
      timeModel: {
        setupSeconds: 30,
        demonstrationSeconds: 30,
        transitionSeconds: 20,
        resetSeconds: 10,
        cleanupSeconds: 15,
      },
      doseScaling: {
        byAge: { '8-11': { reps: [5, 8] }, '12-17': { reps: [6, 10] }, adult: { reps: [6, 12] } },
        byTrainingAge: { novice: { surface: 'higher' }, experienced: { surface: 'lower_as_earned' } },
        byFatigue: { elevated: { setsDelta: -1, surface: 'higher' } },
        byGroupSize: { 'more_than_12': { format: 'paired_stations' } },
        byTime: { 'under_5_minutes': { sets: 2 } },
      },
      measurement: {
        primaryMetric: 'clean_repetitions',
        secondaryMetrics: ['surface_height_inches', 'rpe', 'range_consistency'],
        successDefinition: 'All prescribed repetitions meet the quality gate at target RPE.',
        athleteVisible: true,
      },
      supportPrompts: {
        coachDebrief: ['Was the selected height correct?', 'Which fault appeared first?', 'Was the dose retained or edited?'],
        athleteFeedback: ['Did anything hurt?', 'How hard was the set?', 'Were the instructions clear?'],
      },
      status: 'review',
    }],
  }],
})
