import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { seedCanonicalWaivers } from './seedCanonicalWaivers.js'
import { ensureCoachingBootConstraints } from './ensureCoachingBootConstraints.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

/** Re-run on every boot but superseded by 228; skipping avoids constraint shrink + log noise. */
const BOOT_SUPERSEDED_MIGRATIONS = new Set([
  '104_coaching_skill_phase_infrastructure.sql',
  '111_coaching_output_phase_infrastructure.sql',
  '120_coaching_capacity_phase_infrastructure.sql',
  '128_coaching_control_resilience_phase_infrastructure.sql',
  '196_coaching_kicking_athletes_infrastructure_and_seed.sql',
  '202_coaching_exercise_difficulty_profile.sql',
  '207_coaching_exercise_difficulty_reviewed.sql',
])

const PLATFORM_MIGRATION_LOCK_ID = 884679201

function migrationChecksum(text) {
  let hash = 0
  for (let index = 0; index < text.length; index += 1) {
    hash = (hash * 31 + text.charCodeAt(index)) >>> 0
  }
  return String(hash)
}

export async function initPlatformTables(pool) {
  await ensureCoachingBootConstraints(pool)

  const migrationFiles = [
    '008_member_access_billing_waivers.sql',
    '009_family_identity_cleanup.sql',
    '010_launch_payment_reconciliation.sql',
    '011_coaching_schema_taxonomy_permissions.sql',
    '012_coaching_exercise_library.sql',
    '013_coaching_workout_builder.sql',
    '014_coaching_training_program.sql',
    '015_coaching_challenges.sql',
    '016_coaching_assessments_grading.sql',
    '017_coaching_assignments_sharing.sql',
    '018_coaching_ai.sql',
    '019_coaching_seed_starter_library.sql',
    '020_coaching_workout_minutes.sql',
    '021_coaching_sessions_attendance.sql',
    '022_coaching_periodization_load.sql',
    '023_coaching_engagement.sql',
    '024_coaching_messaging.sql',
    '025_coaching_goals_achievements.sql',
    '026_coaching_thread_scope.sql',
    '027_coaching_form_review.sql',
    '028_coaching_embeddings.sql',
    '029_coaching_video_submission_assign.sql',
    '030_coach_class_scheduling_form.sql',
    '031_coach_assignment_drilldown.sql',
    '037_waiver_types.sql',
    '038_account_invite.sql',
    '039_member_graduation_year.sql',
    '040_email_verification.sql',
    '041_app_user_nullable_email.sql',
    '042_enrollment_receipt_token.sql',
    '043_account_invite_reminders.sql',
    '044_email_deliverability.sql',
    '045_drop_family_member_relationship_label.sql',
    '046_signup_billing_charges.sql',
    '047_stripe_billing_scaffold.sql',
    '048_program_pricing_cost_options.sql',
    '049_multi_class_pass.sql',
    '053_billing_recurring_model.sql',
    '054_billing_anchor_first.sql',
    '055_enrollment_cancel_effective.sql',
    '056_stripe_catalog.sql',
    '057_stripe_pending_enrollment.sql',
    '058_billing_stripe_links.sql',
    '059_facility_portal_config.sql',
    '060_coaching_message_enhancements.sql',
    '061_coaching_message_sender_portal.sql',
    '062_coaching_message_thread_favorite.sql',
    '063_coaching_message_thread_inbox_hide.sql',
    '064_coaching_message_attachments.sql',
    '065_coaching_message_platform_foundation.sql',
    '066_coaching_message_files_alerts.sql',
    '067_coaching_message_collaboration.sql',
    '068_coaching_message_pin_groups.sql',
    '069_coaching_thread_faq_master_list.sql',
    '070_event_calendar_and_rsvp.sql',
    '071_thread_signup_sheets.sql',
    '072_collaboration_panel_lifecycle.sql',
    '073_event_calendar_item_classes.sql',
    '074_member_messaging_create_permissions.sql',
    '075_coaching_tenet_flexibility_mobility.sql',
    '076_coaching_methodology_hiit.sql',
    '077_event_calendar_item_what_to_bring.sql',
    '078_coaching_session_phases.sql',
    '079_coaching_education_content.sql',
    '080_coaching_exercise_programming.sql',
    '081_coaching_exercise_backfill.sql',
    '082_coaching_workout_metadata.sql',
    '083_coaching_validation_rules.sql',
    '084_coaching_training_block.sql',
    '085_coaching_regimen_template.sql',
    '086_coaching_session_templates.sql',
    '087_coaching_phase_order_slot_education.sql',
    '088_archive_orphan_scheduling_forms.sql',
    '089_drop_class_iteration.sql',
    '090_drop_member_program.sql',
    '091_drop_admins_and_trim_roles.sql',
    '092_drop_sport_pricing_default.sql',
    '093_coaching_skill_library.sql',
    '094_coaching_skill_evaluation.sql',
    '095_coaching_exercise_card_v2.sql',
    '096_coaching_prepare_access_subroles.sql',
    '097_coaching_prepare_access_seed.sql',
    '098_coaching_prepare_access_foundation_cards.sql',
    '099_coaching_prepare_access_content_support.sql',
    '100_coaching_prepare_access_upper_body_cards.sql',
    '101_coaching_prepare_access_lower_leg_cards.sql',
    '102_coaching_prepare_access_hip_access_cards.sql',
    '103_coaching_prepare_access_activation_cards.sql',
    '104_coaching_skill_phase_infrastructure.sql',
    '105_coaching_skill_movement_intelligence_seed.sql',
    '106_coaching_skill_shape_cards.sql',
    '107_coaching_skill_tumbling_cards.sql',
    '108_coaching_skill_sprint_cards.sql',
    '109_coaching_skill_balance_cards.sql',
    '110_coaching_skill_perception_cards.sql',
    '111_coaching_output_phase_infrastructure.sql',
    '112_coaching_output_seed.sql',
    '113_coaching_output_acceleration_cards.sql',
    '114_coaching_output_max_velocity_cards.sql',
    '115_coaching_output_elastic_cards.sql',
    '116_coaching_education_dedupe_framework.sql',
    '117_coaching_output_jump_power_cards.sql',
    '118_coaching_output_decel_cod_cards.sql',
    '119_coaching_output_reactive_tumbling_cards.sql',
    '120_coaching_capacity_phase_infrastructure.sql',
    '121_coaching_capacity_seed.sql',
    '122_coaching_capacity_squat_cards.sql',
    '123_coaching_capacity_hinge_cards.sql',
    '124_coaching_capacity_push_cards.sql',
    '125_coaching_capacity_pull_cards.sql',
    '126_coaching_capacity_carry_cards.sql',
    '127_coaching_capacity_tissue_cards.sql',
    '128_coaching_control_resilience_phase_infrastructure.sql',
    '129_coaching_control_resilience_seed.sql',
    '130_coaching_control_landing_cards.sql',
    '131_coaching_control_single_leg_cards.sql',
    '132_coaching_control_trunk_cards.sql',
    '133_coaching_control_scapular_cards.sql',
    '134_coaching_control_slow_eccentric_cards.sql',
    '135_coaching_library_facility_backfill.sql',
    '136_rename_fitness_repeatability_to_sustained_capacity.sql',
    '137_rename_session_phase_labels.sql',
    '138_coaching_programming_library_infrastructure.sql',
    '139_coaching_workout_block_programming_method.sql',
    '141_coaching_programming_library_seed.sql',
    '142_coaching_session_phase_dedupe.sql',
    '143_coaching_exercise_phase_key_constraint_sync.sql',
    '144_coaching_programming_library_facility_backfill.sql',
    '145_coaching_agility_shiftiness_infrastructure_and_seed.sql',
    '146_coaching_agility_shiftiness_cards.sql',
    '147_coaching_speed_sprinters_quick_release_infrastructure_and_seed.sql',
    '148_coaching_speed_sprinters_quick_release_cards.sql',
    '149_coaching_loaded_strength_infrastructure_and_seed.sql',
    '150_coaching_loaded_strength_cards.sql',
    '151_coaching_kettlebell_strength_infrastructure_and_seed.sql',
    '152_coaching_kettlebell_strength_cards.sql',
    '153_coaching_balance_infrastructure_and_seed.sql',
    '154_coaching_balance_cards.sql',
    '155_coaching_bodyweight_strength_infrastructure_and_seed.sql',
    '156_coaching_bodyweight_strength_cards.sql',
    '157_coaching_coordination_infrastructure_and_seed.sql',
    '158_coaching_coordination_cards.sql',
    '159_coaching_core_body_control_infrastructure_and_seed.sql',
    '160_coaching_core_body_control_cards.sql',
    '161_coaching_explosiveness_infrastructure_and_seed.sql',
    '162_coaching_explosiveness_cards.sql',
    '163_coaching_eccentric_negative_training_infrastructure_and_seed.sql',
    '164_coaching_eccentric_negative_training_cards.sql',
    '165_coaching_calisthenics_infrastructure_and_seed.sql',
    '166_coaching_calisthenics_cards.sql',
    '167_coaching_isometrics_infrastructure_and_seed.sql',
    '168_coaching_isometrics_cards.sql',
    '169_coaching_mobility_infrastructure_and_seed.sql',
    '170_coaching_mobility_cards.sql',
    '171_coaching_neural_training_infrastructure_and_seed.sql',
    '172_coaching_neural_training_cards.sql',
    '173_coaching_plyometrics_infrastructure_and_seed.sql',
    '174_coaching_plyometrics_cards.sql',
    '175_coaching_sandbag_nontraditional_strength_infrastructure_and_seed.sql',
    '176_coaching_sandbag_nontraditional_strength_cards.sql',
    '177_coaching_resistance_band_body_resistance_infrastructure_and_seed.sql',
    '178_coaching_resistance_band_body_resistance_cards.sql',
    '179_coaching_exercise_participant_structure.sql',
    '180_coaching_games_library_infrastructure.sql',
    '181_coaching_games_library_migrate_and_seed.sql',
    '182_coaching_games_500_card_catalog.sql',
    '182_coaching_jumping_height_infrastructure_and_seed.sql',
    '183_coaching_jumping_height_cards.sql',
    '184_coaching_jumping_distance_infrastructure_and_seed.sql',
    '185_coaching_jumping_distance_cards.sql',
    '186_coaching_medicine_balls_slam_balls_infrastructure_and_seed.sql',
    '187_coaching_medicine_balls_slam_balls_cards.sql',
    '188_coaching_pairs_exercise_infrastructure_and_seed.sql',
    '189_coaching_pairs_exercise_cards.sql',
    '190_coaching_reaction_time_reduction_infrastructure_and_seed.sql',
    '191_coaching_reaction_time_reduction_cards.sql',
    '192_coaching_wall_balls_infrastructure_and_seed.sql',
    '193_coaching_wall_balls_cards.sql',
    '194_coaching_throwing_athletes_infrastructure_and_seed.sql',
    '195_coaching_throwing_athletes_cards.sql',
    '196_coaching_kicking_athletes_infrastructure_and_seed.sql',
    '197_coaching_kicking_athletes_cards.sql',
    '198_coaching_landmine_exercise_library_infrastructure_and_seed.sql',
    '199_coaching_landmine_exercise_library_cards.sql',
    '200_coaching_rotational_power_infrastructure_and_seed.sql',
    '201_coaching_rotational_power_cards.sql',
    '202_coaching_exercise_difficulty_profile.sql',
    '203_coaching_exercise_youtube_links_batch2.sql',
    '204_coaching_exercise_youtube_links_batch3.sql',
    '253_coaching_legacy_difficulty_compatibility.sql',
    '205_coaching_high_impact_level_3_4_infrastructure_and_seed.sql',
    '206_coaching_high_impact_level_3_4_cards.sql',
    '207_coaching_exercise_difficulty_reviewed.sql',
    '208_coaching_box_jump_infrastructure_and_seed.sql',
    '209_coaching_box_jump_cards.sql',
    '210_coaching_cone_drill_exercise_library_infrastructure_and_seed.sql',
    '211_coaching_cone_drill_exercise_library_cards.sql',
    '212_coaching_ladder_infrastructure_and_seed.sql',
    '213_coaching_ladder_cards.sql',
    '214_coaching_exercise_programming_kind.sql',
    '215_coaching_exercise_difficulty_v2_reviewed.sql',
    '216_coaching_exercise_difficulty_v3_reviewed.sql',
    '217_coaching_exercise_integrated_workout_kind.sql',
    '218_coaching_needs_engine_v2.sql',
    '219_equipment_tag_audit.sql',
    '220_coaching_beginner_explosiveness_capacity.sql',
    '221_coaching_restore_library_seed.sql',
    '222_coaching_sustained_capacity_hiit_fitness.sql',
    '223_coaching_profile_and_sport_cleanup.sql',
    '224_coaching_needs_engine_requirements.sql',
    '225_coaching_needs_engine_template_repair.sql',
    '226_coaching_split_progression_d6_8.sql',
    '227_coaching_restore_and_progression_repair.sql',
    '228_coaching_boot_constraint_canonical.sql',
    '229_coaching_exercise_progression.sql',
    '230_stripe_operations.sql',
    '231_stripe_reconciliation.sql',
    '232_billing_access_recovery.sql',
    '233_enrollment_cancellation_review.sql',
    '234_refund_approval_evidence.sql',
    '235_member_missed_class.sql',
    '236_stripe_dispute_case.sql',
    '240_coaching_canonical_scores_v1.sql',
    '241_coaching_canonical_workout_model_v1.sql',
    '242_coaching_canonical_telemetry_v1.sql',
    '243_coaching_canonical_card_governance_v1.sql',
    '244_coaching_canonical_anatomy_load_v1.sql',
    '245_coaching_canonical_calibration_v1.sql',
    '246_coaching_canonical_card_audit_v1.sql',
    '248_coaching_canonical_operational_support_v1.sql',
    '252_coaching_canonical_identity_resolution_v1.sql',
    '249_billing_admin_action_log.sql',
    '250_stripe_alert_resolution_audit.sql',
    '251_manual_billing_audit.sql',
    '265_coaching_canonical_research_media_v1.sql',
    '266_coaching_canonical_legacy_media_candidates_v1.sql',
    '259_coaching_skill_usag_metadata.sql',
    '279_coaching_skill_individual_kind.sql',
    '260_usag_acro_level_2_5_skill_cards.sql',
    '261_usag_tt_tumbling_compulsory_skill_cards.sql',
    '262_usag_youth_at_compulsory_tumbling_cards.sql',
    '263_usag_youth_at_level_1_2_acro_cards.sql',
    '264_usag_youth_at_level_3_5_acro_cards.sql',
    '267_usag_youth_at_compulsory_pyramid_toss_cards.sql',
    '268_usag_youth_at_optional_running_tumbling_passes.sql',
    '269_usag_youth_at_standing_tumbling_passes.sql',
    '270_usag_youth_at_optional_toss_cards.sql',
    '271_usag_youth_at_optional_pyramid_cards.sql',
    '272_usag_youth_at_optional_acro_cards.sql',
    '273_usag_acro_level_6_compulsory_cards.sql',
    '274_usag_acro_level_7_compulsory_cards.sql',
    '275_usag_acro_level_8_pair_balance_cards.sql',
    '276_usag_acro_level_8_pair_dynamic_cards.sql',
    '277_usag_acro_level_8_group_cards.sql',
    '278_usag_acro_level_2_5_remaining_cards.sql',
    '279_usag_acro_level_9_10_fig_families.sql',
    '280_usag_tt_optional_element_families.sql',
    '281_usag_tt_elite_tumbling_profiles.sql',
    '282_usag_wag_floor_2026_2030_symbol_families.sql',
    '283_usag_wag_compulsory_floor_cards.sql',
    '284_usag_mag_optional_floor_elements.sql',
    '285_usag_mag_compulsory_technical_floor_cards.sql',
    '273_coaching_canonical_exercise_name_aliases.sql',
    '298_coaching_exercise_difficulty_only.sql',
    '299_coaching_single_leg_rdl_identity_consolidation.sql',
    '300_coaching_medicine_ball_identity_consolidation.sql',
    '301_coaching_ball_slam_variant_consolidation.sql',
    '302_coaching_9090_shin_box_identity_consolidation.sql',
    '303_coaching_180_degree_identity_consolidation.sql',
    '304_coaching_physical_difficulty_calibration.sql',
    '305_coaching_exercise_difficulty_model_backfill.sql',
    '306_coaching_45_degree_cut_identity_consolidation.sql',
    '307_coaching_cossack_variant_consolidation.sql',
    '308_coaching_adductor_rockback_variant_consolidation.sql',
    '309_coaching_hang_identity_split_and_consolidation.sql',
    '310_coaching_hanging_leg_raise_identity_consolidation.sql',
    '311_coaching_l_sit_identity_and_hanging_split.sql',
    '312_coaching_support_compression_identity_family.sql',
    '313_coaching_hang_family_structural_completion.sql',
    '314_coaching_hang_family_contract_completion.sql',
    '315_coaching_depth_box_order_identity_consolidation.sql',
    '316_coaching_depth_box_order_family_completion.sql',
    '317_coaching_kneeling_chest_pass_identity_consolidation.sql',
    '318_coaching_kneeling_chest_pass_family_completion.sql',
    '319_coaching_rotational_wall_throw_identity_consolidation.sql',
    '320_coaching_rotational_wall_throw_family_completion.sql',
    '321_coaching_rotational_wall_throw_equipment_taxonomy.sql',
    '322_coaching_shuffle_rotational_throw_identity_consolidation.sql',
    '323_coaching_shuffle_rotational_throw_family_completion.sql',
    '324_coaching_box_jump_single_leg_landing_identity_consolidation.sql',
    '325_coaching_box_jump_single_leg_landing_family_completion.sql',
    '326_coaching_single_leg_lateral_hop_stick_identity_consolidation.sql',
    '327_coaching_single_leg_lateral_hop_stick_family_completion.sql',
    '328_coaching_dead_bug_pullover_identity_consolidation.sql',
    '329_coaching_dead_bug_pullover_family_completion.sql',
    '330_coaching_romanian_deadlift_identity_consolidation.sql',
    '331_coaching_romanian_deadlift_family_completion.sql',
    '332_coaching_front_foot_elevated_split_squat_identity_consolidation.sql',
    '333_coaching_front_foot_elevated_split_squat_family_completion.sql',
    '334_coaching_half_kneeling_single_arm_press_identity_consolidation.sql',
    '335_coaching_half_kneeling_single_arm_press_family_completion.sql',
    '336_coaching_high_similarity_identity_boundaries.sql',
    '337_coaching_overhead_medicine_ball_projection_family_completion.sql',
    '338_coaching_high_similarity_movement_boundaries.sql',
    '339_coaching_high_confidence_implement_identity_consolidation.sql',
    '340_coaching_remaining_high_similarity_identity_adjudication.sql',
    '341_coaching_remaining_identity_boundaries_researched.sql',
    '342_coaching_researched_identity_boundary_card_completion.sql',
    '343_coaching_chest_pass_variant_consolidation_and_tuck_boundary.sql',
    '344_coaching_boundary_relationship_dimension_taxonomy.sql',
    '345_coaching_pallof_press_step_out_identity_consolidation.sql',
    '346_coaching_pallof_press_step_out_family_completion.sql',
    '347_coaching_exercise_skill_metadata_absence.sql',
    '348_coaching_stir_the_pot_identity_consolidation.sql',
    '349_coaching_stir_the_pot_family_completion.sql',
    '350_coaching_exercise_proficiency_metadata_guard.sql',
    '351_coaching_static_control_identity_consolidations.sql',
    '352_coaching_static_control_family_completion.sql',
    '353_coaching_reactive_landing_pogo_identity_consolidations.sql',
    '354_coaching_reactive_landing_pogo_family_completion.sql',
    '355_coaching_score_84_identity_boundaries.sql',
    '356_coaching_drop_depth_falling_start_identity_consolidation.sql',
    '357_coaching_remaining_score_84_identity_boundaries.sql',
    '358_coaching_score_84_variant_identity_consolidations.sql',
    '359_coaching_reactive_cut_hop_cut_identity_boundary.sql',
    '360_coaching_reactive_hop_cut_seated_press_completion.sql',
    '361_coaching_hip_thrust_identity_consolidations.sql',
    '362_coaching_hip_thrust_family_completion.sql',
    '363_coaching_ball_drop_identity_cluster.sql',
    '364_coaching_ball_drop_compound_identity_boundary.sql',
    '365_coaching_ball_drop_chase_catch_completion.sql',
    '366_coaching_alternating_bounds_identity_consolidation.sql',
    '367_coaching_alternating_bounds_family_completion.sql',
    '368_coaching_remaining_alternating_bounds_identity_consolidations.sql',
    '369_coaching_split_squat_identity_cluster.sql',
    '370_coaching_split_squat_family_completion.sql',
    '371_coaching_score_83_identity_boundaries.sql',
    '372_coaching_score_83_variant_identity_consolidations.sql',
    '373_coaching_hamstring_slider_curl_family_completion.sql',
    '374_coaching_exercise_identity_proficiency_metadata_guard.sql',
    '375_coaching_score_82_identity_boundaries.sql',
    '376_coaching_score_82_variant_identity_consolidations.sql',
    '377_coaching_score_81_identity_boundaries.sql',
    '378_coaching_score_81_variant_identity_consolidations.sql',
    '379_coaching_score_80_identity_boundaries.sql',
    '380_coaching_score_80_variant_identity_consolidations.sql',
    '381_coaching_score_79_identity_boundaries.sql',
    '382_coaching_score_79_variant_identity_consolidations.sql',
    '383_coaching_score_78_identity_boundaries.sql',
    '384_coaching_score_78_variant_identity_consolidations.sql',
    '385_coaching_score_77_identity_boundaries.sql',
    '386_coaching_score_77_variant_identity_consolidations.sql',
    '387_coaching_score_76_identity_boundaries.sql',
    '388_coaching_score_76_variant_identity_consolidations.sql',
    '389_coaching_score_75_identity_boundaries.sql',
    '390_coaching_score_75_variant_identity_consolidations.sql',
    '391_coaching_score_74_identity_boundaries.sql',
    '392_coaching_score_74_variant_identity_consolidations.sql',
    '393_coaching_score_73_identity_boundaries.sql',
    '394_coaching_score_73_variant_identity_consolidations.sql',
    '395_coaching_score_72_identity_boundaries.sql',
    '396_coaching_score_72_variant_identity_consolidations.sql',
    '397_coaching_landmine_press_family_completion.sql',
    '398_coaching_one_arm_landmine_base_family_completion.sql',
    '399_stripe_pending_enrollment_setup_mode.sql',
    '400_stripe_pending_enrollment_processing_status.sql',
    '401_coaching_landmine_explosive_press_family_completion.sql',
    '402_coaching_landmine_squat_lunge_family_completion.sql',
    '403_coaching_cossack_squat_family_completion.sql',
    '404_coaching_adductor_rockback_family_completion.sql',
    '405_coaching_recent_family_identity_boundary_closure.sql',
    '406_coaching_remaining_unclassified_identity_queue_closure.sql',
    '407_coaching_backpedal_to_sprint_family_completion.sql',
    '408_coaching_hang_family_research_completion.sql',
    '409_coaching_support_compression_research_completion.sql',
    '410_coaching_hanging_leg_raise_l_sit_research_completion.sql',
    '411_coaching_a_series_sprint_drills_research_completion.sql',
    '412_coaching_ankling_straight_leg_identity_lineage_correction.sql',
    '413_coaching_ankling_straight_leg_research_completion.sql',
    '414_coaching_skipping_fast_leg_identity_preparation.sql',
    '415_coaching_skipping_fast_leg_research_completion.sql',
    '416_coaching_dribble_run_variant_lineage_preparation.sql',
    '417_coaching_dribble_run_research_completion.sql',
    '418_coaching_pogo_dribble_identity_queue_closure.sql',
    '419_coaching_short_acceleration_identity_variant_consolidation.sql',
    '420_coaching_short_acceleration_research_completion.sql',
    '421_coaching_short_acceleration_identity_queue_closure.sql',
    '422_coaching_hill_sprint_acceleration_research_completion.sql',
    '423_coaching_180_wall_ball_identity_resolution.sql',
    '424_coaching_landmine_arc_identity_resolution.sql',
    '425_coaching_ankling_pogo_identity_resolution.sql',
    '426_coaching_opposite_leg_bound_direction_identity_resolution.sql',
    '427_coaching_gymnastics_evaluations.sql',
    '473_gymnastics_evaluation_delivery_and_templates.sql',
    '428_coaching_single_leg_line_hop_identity_quarantine.sql',
    '429_coaching_overhead_press_eccentric_consolidation.sql',
    '430_coaching_kettlebell_strict_press_identity_resolution.sql',
    '431_coaching_line_pogo_identity_completion.sql',
    '432_coaching_quarter_turn_jump_hop_identity_resolution.sql',
    '433_coaching_scoop_toss_forward_rotational_identity_completion.sql',
    '434_coaching_lateral_low_hurdle_stick_identity_completion.sql',
    '435_coaching_rotational_bound_broad_identity_completion.sql',
    '436_coaching_rotational_bound_broad_similarity_closure.sql',
    '437_coaching_single_leg_hop_pogo_identity_completion.sql',
    '438_coaching_single_leg_hop_similarity_and_rebound_quarantine.sql',
    '439_coaching_remaining_identity_queue_quarantine.sql',
    '440_coaching_needs_engine_generation_profile_backfill.sql',
    '441_coaching_box_drop_depth_jump_completion.sql',
    '442_coaching_box_drop_depth_similarity_closure.sql',
    '443_coaching_vertical_jump_foundations_completion.sql',
    '444_coaching_vertical_jump_foundations_audit_hardening.sql',
    '445_coaching_bilateral_horizontal_jump_foundations_completion.sql',
    '446_coaching_drop_landing_stick_foundations_completion.sql',
    '447_coaching_front_loaded_squat_identity_and_family_completion.sql',
    '448_coaching_floor_bridge_identity_and_family_completion.sql',
    '449_coaching_single_leg_romanian_deadlift_family_completion.sql',
    '450_coaching_cossack_squat_audit_completion.sql',
    '451_coaching_floor_press_family_completion.sql',
    '452_coaching_rotational_ball_slam_family_completion.sql',
    '453_coaching_one_arm_row_family_completion.sql',
    '454_coaching_short_acceleration_audit_hardening.sql',
    '455_coaching_push_up_identity_and_family_completion.sql',
    '456_coaching_reverse_lunge_identity_and_family_completion.sql',
    '457_coaching_lateral_lunge_identity_and_family_completion.sql',
    '458_coaching_medicine_ball_shot_put_family_completion.sql',
    '459_coaching_suitcase_carry_family_completion.sql',
    '460_coaching_bent_knee_soleus_raise_family_completion.sql',
    '461_coaching_back_squat_family_completion.sql',
    '462_coaching_box_jump_family_audit_hardening.sql',
    '463_coaching_depth_jump_family_audit_hardening.sql',
    '464_coaching_nordic_hamstring_family_audit_hardening.sql',
    '465_coaching_nordic_reverse_nordic_identity_closure.sql',
    '466_coaching_nordic_hamstring_machine_gate_completion.sql',
    '467_coaching_front_plank_family_audit_hardening.sql',
    '468_coaching_front_plank_similarity_closure.sql',
    '469_coaching_lateral_bound_graph_taxonomy_closure.sql',
    '470_coaching_dead_bug_family_audit_hardening.sql',
    '471_coaching_worlds_greatest_stretch_family_audit_hardening.sql',
    '472_coaching_kettlebell_swing_family_audit_hardening.sql',
  ]

  const migrationClient = typeof pool.connect === 'function' ? await pool.connect() : pool
  try {
    await migrationClient.query(`
      CREATE TABLE IF NOT EXISTS schema_migrations (
        id BIGSERIAL PRIMARY KEY,
        filename TEXT NOT NULL UNIQUE,
        checksum TEXT,
        applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `)
    await migrationClient.query('SELECT pg_advisory_lock($1)', [PLATFORM_MIGRATION_LOCK_ID])
    const appliedResult = await migrationClient.query('SELECT filename FROM schema_migrations')
    const applied = new Set(appliedResult.rows.map((row) => row.filename))

    for (const migrationFile of migrationFiles) {
      if (BOOT_SUPERSEDED_MIGRATIONS.has(migrationFile)) {
        console.log(`[initPlatformTables] Skipping superseded boot migration: ${migrationFile}`)
        continue
      }
      if (applied.has(migrationFile)) {
        console.log(`[initPlatformTables] Already applied: ${migrationFile}`)
        continue
      }
      const migrationPath = path.join(__dirname, '..', 'migrations', migrationFile)
      if (!fs.existsSync(migrationPath)) {
        console.error(`[initPlatformTables] Migration file missing (skipped): ${migrationFile}`)
        continue
      }
      const sql = fs.readFileSync(migrationPath, 'utf8')
      const checksum = migrationChecksum(sql)
      await migrationClient.query('BEGIN')
      try {
        await migrationClient.query(sql)
        await migrationClient.query(
          `INSERT INTO schema_migrations (filename, checksum)
           VALUES ($1, $2)
           ON CONFLICT (filename) DO NOTHING`,
          [migrationFile, checksum],
        )
        await migrationClient.query('COMMIT')
        applied.add(migrationFile)
      } catch (err) {
        await migrationClient.query('ROLLBACK').catch(() => {})
        const msg = String(err.message || err)
        if (/already exists|duplicate key value violates unique constraint/i.test(msg)) {
          console.warn(`[initPlatformTables] Recording existing migration ${migrationFile}:`, msg)
          await migrationClient.query(
            `INSERT INTO schema_migrations (filename, checksum)
             VALUES ($1, $2)
             ON CONFLICT (filename) DO NOTHING`,
            [migrationFile, checksum],
          )
          applied.add(migrationFile)
          continue
        }
        console.error(`[initPlatformTables] Migration ${migrationFile} failed (continuing):`, msg)
      }
    }
  } finally {
    await migrationClient.query('SELECT pg_advisory_unlock($1)', [PLATFORM_MIGRATION_LOCK_ID]).catch(() => {})
    if (migrationClient !== pool && typeof migrationClient.release === 'function') migrationClient.release()
  }

  await seedCanonicalWaivers(pool)

  console.log('✅ Platform access, billing, and waiver tables initialized')
}
