import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
import {monthlyBenefitsFixture} from '../../backend/payroll/testing/monthlyBenefitsFixture.js'
test('admin keeps coverage enrolled with employer funding after employee withdrawal',async({page})=>{
 test.setTimeout(90000);page.setDefaultTimeout(10000);test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const oldDocumentKey=process.env.PAYROLL_DOCUMENT_KEY;process.env.PAYROLL_DOCUMENT_KEY='17'.repeat(32)
 const h=await createHarness()
 try{
 const {api,periods}=await monthlyBenefitsFixture(h),packet=await api('/onboarding',undefined,'GET',200,true)
 await api('/benefits-deduction-authorization/withdraw',{confirmed:true,requestKey:'employer-funded-browser-withdrawal',authorizationRequestKey:packet.benefitsDeduction.saved.requestKey,onboardingCycle:1},'POST',200,true)
 await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'));await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
 await page.setViewportSize({width:390,height:1200});await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'People & onboarding',exact:true}).click()
 const step=page.locator('details').filter({has:page.getByText('Pay, classification & benefits review',{exact:true})});await step.locator('summary').first().click()
 await step.getByLabel('Review evidence / instructions',{exact:true}).fill('Reviewed employer funding and continued group medical enrollment')
 await step.getByLabel('Benefits disposition',{exact:true}).selectOption('ENROLLED_EMPLOYER_FUNDED')
 await step.getByLabel('Benefits effective or eligibility date',{exact:true}).fill('2026-09-10')
 await step.getByRole('textbox',{name:'Benefits explanation for employee',exact:true}).fill('Your group medical coverage continues. The employer pays the full premium.')
 await step.getByLabel('Benefits review evidence',{exact:true}).fill('Synthetic employer funding and excluded group-health verification')
 await step.getByLabel('I verified the benefits disposition, effective date and supporting evidence.',{exact:true}).check()
 const complete=step.getByRole('button',{name:'Verify & complete',exact:true});await expect(complete).toBeDisabled()
 await step.getByRole('checkbox',{name:/The employer assumes every published employee contribution/}).check();await step.getByLabel('I verified the benefits disposition, effective date and supporting evidence.',{exact:true}).check();await complete.click()
 await expect(page.getByRole('status')).toContainText('Step reviewed and completed.')
 const updated=await api('/onboarding',undefined,'GET',200,true);expect(updated.benefitsElection.choice).toBe('ENROLL');expect(updated.benefitsReview.disposition).toBe('ENROLLED_EMPLOYER_FUNDED');expect(updated.benefitsDeduction.required).toBe(false)
 await page.getByRole('button',{name:'Payroll runs',exact:true}).click();await page.getByRole('combobox',{name:'Pay period',exact:true}).selectOption(String(periods[0].id));await page.getByRole('button',{name:'Preview payroll',exact:true}).click()
 const collection=page.getByRole('region',{name:'Monthly benefit deductions',exact:true});await expect(collection).toContainText('Coverage remains enrolled.');await expect(collection).toContainText('Employer funding $575.00/month');await expect(collection).toContainText('$125.00 previously assigned to the employee.');await collection.screenshot({path:'/tmp/payroll-employer-funded-benefits-mobile.png'})

 const run=await api('/runs',{payPeriodId:periods[0].id},'POST',201);await api(`/runs/${run.id}/status`,{status:'REVIEW'},'PATCH');await api(`/runs/${run.id}/status`,{status:'APPROVED'},'PATCH');await api(`/runs/${run.id}/finalize`,{paymentDate:'2026-09-18',paymentConfirmationReference:'SYNTHETIC-FUNDING-REPORT-BROWSER'})
 await page.getByRole('button',{name:'Reports & QuickBooks',exact:true}).click();await page.getByLabel('Report start date',{exact:true}).fill('2026-09-01');await page.getByLabel('Report end date',{exact:true}).fill('2026-09-30');await page.getByRole('button',{name:'Review employer benefit funding',exact:true}).click()
 const report=page.getByRole('region',{name:'Employer benefit funding reconciliation',exact:true});await expect(report).toContainText('$575.00/month');await expect(report).toContainText('already collected this month: $0.00');await expect(report).toContainText(`#${run.id}`);await report.screenshot({path:'/tmp/payroll-employer-funding-report-mobile.png'})
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download employer funding evidence',exact:true}).click();expect((await download).suggestedFilename()).toContain('employer-benefit-funding')

 const invoices=page.getByRole('region',{name:'Carrier invoice reconciliation',exact:true});await invoices.getByLabel('Carrier coverage month',{exact:true}).fill('2026-09');await invoices.getByRole('button',{name:'Load carrier invoices',exact:true}).click();await expect(invoices).toContainText('1 retained employer-funding decisions')
 for(const [label,value] of [['Carrier name','Synthetic Health'],['Carrier invoice number','BROWSER-SEP-26'],['Invoice date','2026-09-01'],['Invoice due date','2026-09-30'],['Invoice total ($)','575.00'],['Carrier document reference','Synthetic September carrier invoice']])await invoices.getByLabel(label,{exact:true}).fill(value)
 await invoices.getByRole('textbox',{name:'Coverage and amount reconciliation',exact:true}).fill('Matched employee medical coverage and dates to the actual carrier invoice; no credits.')
 const retain=invoices.getByRole('button',{name:'Retain carrier invoice reconciliation',exact:true});await expect(retain).toBeDisabled();await invoices.getByRole('checkbox',{name:/I matched the carrier invoice/}).check();await retain.click();await expect(invoices.getByRole('status')).toContainText('Carrier invoice reconciliation retained.')
 await expect(invoices).toContainText('Matches current coverage and payroll evidence');await invoices.getByText('Retained coverage evidence',{exact:true}).click();await expect(invoices).toContainText('Medical · Family · $575.00/month')
 await invoices.getByRole('button',{name:'Revise invoice BROWSER-SEP-26',exact:true}).click();await invoices.getByLabel('Invoice total ($)',{exact:true}).fill('550.00');await invoices.getByRole('textbox',{name:'Coverage and amount reconciliation',exact:true}).fill('Carrier issued a twenty-five dollar adjustment; matched revised invoice and coverage.');await invoices.getByLabel('Employer premium expense ($)',{exact:true}).fill('550.00');await invoices.getByLabel('Employee contributions applied ($)',{exact:true}).fill('0.00');await invoices.getByLabel('Accounting allocation evidence',{exact:true}).fill('Matched employer invoice expense with no employee contribution applied');await invoices.getByRole('checkbox',{name:/I verified the accounting split/}).check();await invoices.getByLabel('Employer premium expense ($)',{exact:true}).fill('549.00');await expect(invoices.getByRole('checkbox',{name:/I verified the accounting split/})).not.toBeChecked();await invoices.getByLabel('Employer premium expense ($)',{exact:true}).fill('550.00');await invoices.getByRole('checkbox',{name:/I verified the accounting split/}).check();await expect(retain).toBeDisabled();await invoices.getByRole('checkbox',{name:/I matched the carrier invoice/}).check();await retain.click();await expect(invoices).toContainText('Revision 2');await expect(invoices).toContainText('Superseded by a later invoice review');await expect(invoices).toContainText('employer expense $550.00; employee contributions $0.00');await invoices.locator('article').first().screenshot({path:'/tmp/payroll-carrier-invoice-mobile.png'})
 await invoices.getByRole('button',{name:'Revise invoice BROWSER-SEP-26',exact:true}).click();await invoices.getByRole('button',{name:'Cancel revision',exact:true}).click();await expect(invoices.getByLabel('Carrier invoice number',{exact:true})).toHaveValue('');await expect(retain).toBeDisabled()

 const latestInvoice=invoices.locator('article').first();await latestInvoice.getByLabel('Attach carrier invoice document',{exact:true}).setInputFiles({name:'carrier-invoice.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a/ZkAAAAASUVORK5CYII=','base64')})
 const documentLink=invoices.getByRole('button',{name:'Download carrier-invoice.png',exact:true});await expect(documentLink).toBeVisible();const documentDownload=page.waitForEvent('download');await documentLink.click();expect((await documentDownload).suggestedFilename()).toBe('carrier-invoice.png');await invoices.locator('article').first().screenshot({path:'/tmp/payroll-carrier-document-mobile.png'})
 }finally{await page.unrouteAll({behavior:'wait'}).catch(()=>{});await page.close().catch(()=>{});await h.close();if(oldDocumentKey===undefined)delete process.env.PAYROLL_DOCUMENT_KEY;else process.env.PAYROLL_DOCUMENT_KEY=oldDocumentKey}
})
