import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
import {hashPayrollToken} from '../../backend/payroll/employeeAuth.js'
test('employee previews leave at the requested date and sees updated balances and employment errors',async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness()
 try{
  const r=await fetch(`${h.url}/api/admin/payroll/employees`,{method:'POST',headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:JSON.stringify({employeeNumber:'LEAVE-PREVIEW-BROWSER',legalFirstName:'Planned',legalLastName:'Leave',hireDate:'2026-01-01',hourlyRateCents:2500})})
  expect(r.status).toBe(201);const e=(await r.json()).data
  await h.pool.query("INSERT INTO payroll_employee_session(facility_id,employee_id,token_hash,expires_at) VALUES(1,$1,$2,now()+interval '1 day')",[e.id,hashPayrollToken('leave-preview-browser')])
  await h.pool.query("INSERT INTO payroll_leave_transaction(facility_id,employee_id,leave_type,transaction_date,minutes,reason) VALUES(1,$1,'PTO','2099-10-01',120,'Synthetic future credit')",[e.id])
  await page.addInitScript(()=>sessionStorage.setItem('vortex_payroll_employee_session_v1','leave-preview-browser'))
  await page.route('**/api/payroll/employee/**',async route=>{const url=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${url.pathname}${url.search}`})})})
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.setViewportSize({width:390,height:1000})
  await page.goto('/tests/support/payroll.html?employee')
  await page.getByRole('button',{name:'Leave & requests',exact:true}).click()
  await page.getByRole('combobox',{name:'Leave type',exact:true}).selectOption('PTO')
  await page.getByLabel('Start date',{exact:true}).fill('2099-09-30')
  await page.getByLabel('End date',{exact:true}).fill('2099-09-30')
  await page.getByLabel('Total hours requested',{exact:true}).fill('1')
  await expect(page.getByText('0.00 hours available from 2099-09-30',{exact:true})).toBeVisible()
  await expect(page.getByText('Requested hours exceed the available balance for these dates.',{exact:true})).toBeVisible()
  await page.getByLabel('End date',{exact:true}).fill('2099-10-01')
  await page.getByLabel('Start date',{exact:true}).fill('2099-10-01')
  await expect(page.getByText('2.00 hours available from 2099-10-01',{exact:true})).toBeVisible()
  await expect(page.getByText('Requested hours exceed the available balance for these dates.',{exact:true})).toHaveCount(0)
  await page.getByText('2.00 hours available from 2099-10-01',{exact:true}).locator('..').screenshot({path:'/tmp/payroll-leave-availability-mobile.png'})
  await page.getByLabel('Start date',{exact:true}).fill('2025-12-31')
  await expect(page.getByText(/Leave dates must fall within one recorded employment period/)).toBeVisible()
  await page.getByRole('combobox',{name:'Request type',exact:true}).selectOption('GENERAL')
  await page.getByRole('textbox',{name:'Details / reason',exact:true}).fill('Synthetic request with a lost response')
  let drop=true
  await page.route('**/api/payroll/employee/requests',async route=>{
   const response=await route.fetch({url:`${h.url}/api/payroll/employee/requests`})
   if(drop){drop=false;await route.abort('failed')}else await route.fulfill({response})
  })
  await page.getByRole('button',{name:'Submit request',exact:true}).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByRole('button',{name:'Submit request',exact:true}).click()
  await expect(page.getByText('Request submitted to your hiring admin.',{exact:true})).toBeVisible()
  expect((await h.pool.query('SELECT COUNT(*)::int n FROM payroll_employee_request WHERE employee_id=$1',[e.id])).rows[0].n).toBe(1)
  for(const day of ['01','02'])await h.pool.query("INSERT INTO payroll_employee_request(facility_id,employee_id,kind,payload) VALUES(1,$1,'LEAVE',$2)",[e.id,{reason:`Admin leave preview ${day}`,startDate:`2099-10-${day}`,endDate:`2099-10-${day}`,leaveType:'PTO',minutes:60}])
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const url=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${url.pathname}${url.search}`})})})
  await page.goto('/tests/support/payroll.html')
  await page.getByRole('button',{name:'Requests & approvals',exact:true}).click()
  const first=page.locator('article').filter({hasText:'Admin leave preview 01'}),second=page.locator('article').filter({hasText:'Admin leave preview 02'})
  await expect(first.getByText('2.00 hours available from 2099-10-01',{exact:true})).toBeVisible()
  await expect(second.getByText('2.00 hours available from 2099-10-02',{exact:true})).toBeVisible()
  await first.getByRole('textbox',{name:'Review note',exact:true}).fill('Synthetic approved paid leave')
  await first.getByRole('button',{name:'Approve request',exact:true}).click()
  await expect(second.getByText('1.00 hours available from 2099-10-02',{exact:true})).toBeVisible()
  await second.getByText('1.00 hours available from 2099-10-02',{exact:true}).locator('..').screenshot({path:'/tmp/payroll-admin-leave-preview-mobile.png'})
  await first.getByRole('textbox',{name:'Approved leave cancellation reason',exact:true}).fill('Employee changed the planned leave date')
  await first.screenshot({path:'/tmp/payroll-approved-leave-cancel-mobile.png'})
  await first.getByRole('button',{name:'Cancel approved leave',exact:true}).click()
  await expect(first.getByText('Cancellation: Employee changed the planned leave date',{exact:true})).toBeVisible()
  await expect(second.getByText('2.00 hours available from 2099-10-02',{exact:true})).toBeVisible()

  expect(errors).toEqual([])
 }finally{await h.close()}
})
