import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
test('admin publishes benefit plans and employee signs specific coverage choices',async({browser})=>{
 test.setTimeout(90000);test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness(),employeeContext=await browser.newContext({viewport:{width:390,height:1100}}),adminContext=await browser.newContext({viewport:{width:1440,height:1000}})
 try{
 const api=async(path:string,body:unknown,method='POST')=>{const r=await fetch(`${h.url}/api/admin/payroll${path}`,{method,headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();expect(r.ok,JSON.stringify(j)).toBeTruthy();return j.data}
 const e=await api('/employees',{employeeNumber:'BENEFITS-BROWSER',legalFirstName:'Benefits',legalLastName:'Browser',hireDate:'2026-08-03',hourlyRateCents:2500})
 const terms='Synthetic benefit plan offering. Published coverage options show employee and employer monthly contributions.'
 await api('/settings',{benefitsText:terms},'PATCH')
 await h.pool.query("UPDATE payroll_employee SET w4_status='COMPLETE',state_withholding_status='COMPLETE' WHERE id=$1",[e.id])
 await h.pool.query("UPDATE payroll_onboarding_task SET status='COMPLETE',response='{\"method\":\"CHECK\"}' WHERE employee_id=$1 AND task_key='PAYMENT'",[e.id])
 await api(`/employees/${e.id}/tax-elections`,{confirmed:true,sourceNote:'Synthetic signed withholding forms',federal:{filingStatus:'SINGLE'},maryland:{filingStatus:'SINGLE',localRate:3.2,exemptions:1}},'PATCH')
 for(const context of [employeeContext,adminContext])for(const prefix of ['admin/payroll','payroll/employee'])await context.route(`**/api/${prefix}/**`,async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
 await adminContext.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
 const invitation=await api(`/employees/${e.id}/invitations`,{email:'benefits-browser@example.test',sendEmail:false})
 const employee=await employeeContext.newPage(),admin=await adminContext.newPage();employee.setDefaultTimeout(15000);admin.setDefaultTimeout(15000)
 const errors:string[]=[];employee.on('pageerror',e=>errors.push(e.message));admin.on('pageerror',e=>errors.push(e.message))
 await admin.goto('/tests/support/payroll.html');await admin.getByRole('button',{name:'Employer setup',exact:true}).click()
 await admin.getByRole('button',{name:'Add benefit plan',exact:true}).click()
 await admin.getByLabel('Plan 1 name',{exact:true}).fill('Medical coverage')
 await admin.getByLabel('Plan 1 terms',{exact:true}).fill('Medical coverage for eligible employees under the reviewed plan document.')
 await admin.getByLabel('Plan 1 option 1 employer monthly cost',{exact:true}).fill('450')
 await admin.getByRole('button',{name:'Add coverage option',exact:true}).click()
 await admin.getByLabel('Plan 1 option 2 label',{exact:true}).fill('Family')
 await admin.getByLabel('Plan 1 option 2 employee monthly cost',{exact:true}).fill('125')
 await admin.getByLabel('Plan 1 option 2 employer monthly cost',{exact:true}).fill('450')
 await admin.getByLabel('Plan 1 option 2 tax treatment',{exact:true}).selectOption('POSTTAX')
 await admin.getByLabel('Plan & rate verification source',{exact:true}).fill('Synthetic medical plan document and rate sheet')
 await admin.getByLabel('I verified the plan terms, coverage options, monthly costs and published tax treatment.',{exact:true}).check()
 await admin.getByRole('button',{name:'Publish benefit plans',exact:true}).click()
 await expect(admin.getByText('Benefit plans published. Existing choices require review when terms change.',{exact:true})).toBeVisible()
 await admin.setViewportSize({width:390,height:1200})
 const catalog=admin.getByRole('heading',{name:'Benefit plans & coverage options',exact:true}).locator('..')
 const bounds=await catalog.boundingBox();expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(390)
 await catalog.screenshot({path:'/tmp/payroll-plan-catalog-mobile.png'})
 await admin.setViewportSize({width:1440,height:1000})
 await employee.goto(`/employee/payroll?invite=${new URL(invitation.inviteUrl).searchParams.get('invite')}`)
 await employee.getByRole('button',{name:'Onboarding',exact:true}).click()
 const employeeStep=employee.locator('details').filter({has:employee.getByText('Pay, classification & benefits review',{exact:true})})
 await employeeStep.locator('summary').first().click()
 await employee.getByLabel('Plan 1 coverage choice',{exact:true}).selectOption({label:'Family — $125.00/month employee cost'})
 await employee.getByLabel('Benefits choice signature',{exact:true}).fill('Benefits Browser')
 await employee.getByLabel('I read the displayed benefits offering and confirm this choice with my typed name.',{exact:true}).check()
 await employee.getByRole('button',{name:'Submit benefits choice',exact:true}).click()
 await expect(employee.getByRole('status')).toHaveText('Benefits choice submitted to your hiring admin.')
 await employeeStep.locator('summary').first().click()
 await expect(employeeStep.getByText('Enrollment requested · Benefits Browser',{exact:true})).toBeVisible()
 const download=employee.waitForEvent('download');await employee.getByRole('button',{name:'Download benefits choice copy',exact:true}).click()
 const stream=await (await download).createReadStream();let copy='';for await(const chunk of stream!)copy+=chunk.toString();expect(copy).toContain('Medical coverage: Family');expect(copy).toContain('employee $125.00/month');expect(copy).toContain('Signed by: Benefits Browser')
 await employeeStep.screenshot({path:'/tmp/payroll-plan-choices-mobile.png'})
 await admin.goto('/tests/support/payroll.html');await admin.getByRole('button',{name:'People & onboarding',exact:true}).click()
 const step=admin.locator('details').filter({has:admin.getByText('Pay, classification & benefits review',{exact:true})});await step.locator('summary').first().click()
 await expect(step.getByText('Enrollment requested · Benefits Browser',{exact:true})).toBeVisible()
 await step.getByLabel('Benefits disposition',{exact:true}).selectOption('ENROLLED')
 await step.getByLabel('Benefits effective or eligibility date',{exact:true}).fill('2026-09-01')
 await step.getByLabel('Benefits explanation for employee',{exact:true}).fill('Your selected family coverage was reviewed and enrollment confirmed.')
 await step.getByLabel('Benefits review evidence',{exact:true}).fill('Synthetic carrier family enrollment confirmation')
 await step.getByLabel('I verified the benefits disposition, effective date and supporting evidence.',{exact:true}).check()
 await step.getByLabel('Review evidence / instructions',{exact:true}).fill('Verified the current signed benefits choice and tax setup')
 await step.getByRole('button',{name:'Verify & complete',exact:true}).click();await expect(admin.getByRole('status')).toHaveText('Step reviewed and completed.')
 await employee.reload();await employee.getByRole('button',{name:'Onboarding',exact:true}).click();await employeeStep.locator('summary').first().click()
 await expect(employeeStep.getByText('Enrollment confirmed · 2026-09-01',{exact:true})).toBeVisible()
 await expect(employeeStep.locator('summary').first()).toContainText('SIGNATURE REQUIRED')
 await employee.getByRole('region',{name:'Benefit deduction authorization',exact:true}).screenshot({path:'/tmp/payroll-deduction-terms-mobile.png'})
 await employee.getByLabel('Deduction authorization signature',{exact:true}).fill('Benefits Browser')
 await employee.getByLabel('I expressly authorize only the wage deductions described in this separate statement.',{exact:true}).check()
 await employee.getByRole('button',{name:'Sign deduction authorization',exact:true}).click()
 await expect(employee.getByRole('status')).toHaveText('Benefit deduction authorization signed and saved.')
 await expect(employee.getByText('Current deduction terms authorized.',{exact:true})).toBeVisible()
 const authorizationDownload=employee.waitForEvent('download');await employee.getByRole('button',{name:'Download deduction authorization',exact:true}).click()
 const authorizationStream=await (await authorizationDownload).createReadStream();let authorizationCopy='';for await(const chunk of authorizationStream!)authorizationCopy+=chunk.toString();expect(authorizationCopy).toContain('Total authorized monthly deduction: $125.00.');expect(authorizationCopy).toContain('Signed by: Benefits Browser')
 await employee.getByRole('region',{name:'Benefit deduction authorization',exact:true}).screenshot({path:'/tmp/payroll-deduction-authorization-mobile.png'})
 await admin.getByRole('button',{name:'Employer setup',exact:true}).click()
 await admin.getByLabel('Plan 1 option 2 employee monthly cost',{exact:true}).fill('150')
 await admin.getByLabel('Plan & rate verification source',{exact:true}).fill('Synthetic revised family contribution rate sheet')
 await admin.getByLabel('I verified the plan terms, coverage options, monthly costs and published tax treatment.',{exact:true}).check()
 await admin.getByRole('button',{name:'Publish benefit plans',exact:true}).click()
 await expect(admin.getByText('Benefit plans published. Existing choices require review when terms change.',{exact:true})).toBeVisible()
 await employee.reload();await employee.getByRole('button',{name:'Onboarding',exact:true}).click();await employeeStep.locator('summary').first().click()
 await expect(employeeStep.getByText('The published benefits terms changed. A new signed choice is required for enrollment or waiver review.',{exact:true})).toBeVisible()
 await expect(employee.getByLabel('I read the displayed benefits offering and confirm this choice with my typed name.',{exact:true})).not.toBeChecked()
 await expect(employee.getByLabel('Plan 1 coverage choice',{exact:true})).toContainText('$150.00/month')
 await employee.getByLabel('I read the displayed benefits offering and confirm this choice with my typed name.',{exact:true}).check()
 await employee.getByRole('button',{name:'Submit benefits choice',exact:true}).click()
 await expect(employee.getByRole('status')).toHaveText('Benefits choice submitted to your hiring admin.')
 await admin.getByRole('button',{name:'People & onboarding',exact:true}).click();await step.locator('summary').first().click()
 await expect(step.locator('summary').first()).toContainText('REVIEW REQUIRED')
 await expect(step).toContainText('employee $150.00/month')
 await step.getByLabel('Review evidence / instructions',{exact:true}).fill('Verified renewed signed choice and revised family contribution')
 await step.getByLabel('I verified the benefits disposition, effective date and supporting evidence.',{exact:true}).check()
 await step.getByRole('button',{name:'Verify & complete',exact:true}).click()
 await expect(admin.getByRole('status')).toHaveText('Step reviewed and completed.')
 await employee.reload();await employee.getByRole('button',{name:'Onboarding',exact:true}).click();await employeeStep.locator('summary').first().click()
 await expect(employeeStep.locator('summary').first()).toContainText('SIGNATURE REQUIRED')
 await expect(employee.getByRole('region',{name:'Benefit deduction authorization',exact:true})).toContainText('Total authorized monthly deduction: $150.00.')
 await expect(employee.getByLabel('I expressly authorize only the wage deductions described in this separate statement.',{exact:true})).not.toBeChecked()
 await employee.getByLabel('Deduction authorization signature',{exact:true}).fill('Benefits Browser')
 await employee.getByLabel('I expressly authorize only the wage deductions described in this separate statement.',{exact:true}).check()
 await employee.getByRole('button',{name:'Sign deduction authorization',exact:true}).click()
 await expect(employee.getByRole('status')).toHaveText('Benefit deduction authorization signed and saved.')
 expect(errors).toEqual([])
 }finally{await employeeContext.close();await adminContext.close();await h.close()}
})
