import {test,expect} from '@playwright/test'
import {carrierRemittanceFixture} from '../../backend/payroll/testing/carrierRemittanceFixture.js'
import {runCarrierRemittanceSweep} from '../../backend/payroll/carrierRemittanceAutomation.js'
test('admin releases exhausted non-sends and separately authorizes a replacement',async({page})=>{
 test.setTimeout(90000);test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const prior=process.env.PAYROLL_DOCUMENT_KEY;process.env.PAYROLL_DOCUMENT_KEY='31'.repeat(32);let sends=0,allowSend=false,loseResponse=true
 const sender=async()=>{sends++;return allowSend?{sent:true,messageId:'synthetic-accepted'}:{sent:false,skipped:true,reason:'category_disabled'}}
 const f=await carrierRemittanceFixture({sender}),{h}=f,sweep=()=>runCarrierRemittanceSweep(h.pool,{facility:1,now:f.now(),sender})
 try{
  await h.pool.query('CREATE TABLE email_delivery(id BIGINT PRIMARY KEY,facility_id BIGINT,recipient_hash TEXT,category TEXT,stream TEXT,template_version TEXT,status TEXT,idempotency_key TEXT,created_at TIMESTAMPTZ,accepted_at TIMESTAMPTZ,bounced_at TIMESTAMPTZ,complained_at TIMESTAMPTZ)')
  for(let i=0;i<3;i++){await sweep();f.setNow(new Date(+f.now()+300001))}
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url()),response=await route.fetch({url:`${h.url}${u.pathname}${u.search}`});if(loseResponse&&u.pathname.endsWith('/release-unsent')&&response.ok()){loseResponse=false;return route.fulfill({status:503,json:{success:false,message:'Synthetic lost release response'}})}await route.fulfill({response})})
  await page.setViewportSize({width:390,height:1200});await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Reports & QuickBooks',exact:true}).click()
  const invoices=page.getByRole('region',{name:'Carrier invoice reconciliation',exact:true});await invoices.getByLabel('Carrier coverage month',{exact:true}).fill('2026-09');await invoices.getByRole('button',{name:'Load carrier invoices',exact:true}).click();await invoices.getByText('Prepare carrier payment',{exact:true}).click();await invoices.getByText('Remittance delivery authorization',{exact:true}).click()
  const panel=invoices.getByRole('region',{name:'Carrier remittance delivery review',exact:true});await panel.getByRole('button',{name:'Load remittance delivery history',exact:true}).click();await expect(panel).toContainText('Notice retries exhausted')
  await panel.getByText('Review notice that never sent',{exact:true}).click();const release=panel.getByRole('region',{name:'Carrier non-send release review',exact:true});await release.getByRole('button',{name:'Check non-send release evidence',exact:true}).click();await expect(release).toContainText('3 retained attempts')
  await release.getByLabel('Non-send investigation and release reference',{exact:true}).fill('Reviewed exhausted non-sends and restored configured delivery before release');await page.clock.fastForward(30001);await expect(release.getByLabel('Non-send investigation and release reference',{exact:true})).toHaveValue('Reviewed exhausted non-sends and restored configured delivery before release');await release.getByRole('checkbox').check()
  await release.getByRole('button',{name:'Release unsent remittance notice',exact:true}).click();await expect(release.getByRole('alert')).toHaveText('Synthetic lost release response');await release.getByRole('button',{name:'Release unsent remittance notice',exact:true}).click();await expect(panel).toContainText('Unsent notice permanently released');expect((await h.pool.query('SELECT * FROM payroll_carrier_remittance_unsent_release')).rowCount).toBe(1);expect(sends).toBe(3)
  await panel.getByRole('button',{name:'Preview delivery notice',exact:true}).click();const authorization=panel.getByRole('group',{name:'Notice to authorize',exact:true});await authorization.getByLabel('Delivery authorization reference',{exact:true}).fill('Separate replacement authorization after reviewed non-send release');await authorization.getByRole('checkbox').check();await authorization.getByRole('button',{name:'Authorize remittance delivery',exact:true}).click();await expect(panel.getByRole('status')).toHaveText('Notice authorization retained.');await expect(panel).toContainText('Notice authorized — pending delivery')
  allowSend=true;await sweep();await page.clock.fastForward(30001);await expect(panel).toContainText('Notice accepted by email provider');expect(sends).toBe(4);await expect(panel.getByText('Review notice that never sent',{exact:true})).toHaveCount(0);await expect(panel).toContainText('Reviewed exhausted non-sends and restored configured delivery before release')
  await panel.screenshot({path:'/tmp/payroll-carrier-remittance-unsent-release-mobile.png'});expect(errors).toEqual([])
 }finally{await page.unrouteAll({behavior:'wait'}).catch(()=>{});await page.close().catch(()=>{});await h.close();if(prior===undefined)delete process.env.PAYROLL_DOCUMENT_KEY;else process.env.PAYROLL_DOCUMENT_KEY=prior}
})
