import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
test('admin completes pay setup after verified elections and renews it when elections change',async({page})=>{
 test.setTimeout(90000);page.setDefaultTimeout(15000)
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness();try{
 const api=async(path:string,body:unknown,status=200,method='POST')=>{const r=await fetch(`${h.url}/api/admin/payroll${path}`,{method,headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:JSON.stringify(body)});expect(r.status).toBe(status);return (await r.json()).data}
 const e=await api('/employees',{employeeNumber:'PAY-SETUP-BROWSER',legalFirstName:'Pay',legalLastName:'Setup',hireDate:'2026-08-03',hourlyRateCents:2500},201)
 await h.pool.query("UPDATE payroll_employee SET w4_status='COMPLETE',state_withholding_status='COMPLETE' WHERE id=$1",[e.id])
 await h.pool.query("UPDATE payroll_onboarding_task SET status='COMPLETE',response='{\"method\":\"CHECK\"}' WHERE employee_id=$1 AND task_key='PAYMENT'",[e.id])
 await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
 await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
 await page.setViewportSize({width:390,height:1200});await page.goto('/tests/support/payroll.html')
 await page.getByRole('button',{name:'People & onboarding',exact:true}).click()
 const step=page.locator('details').filter({has:page.getByText('Pay, classification & benefits review',{exact:true})})
 await step.locator('summary').first().click()
 await step.getByRole('textbox',{name:'Review evidence / instructions',exact:true}).fill('Reviewed the signed tax forms and payment setup')
 await expect(step.getByRole('button',{name:'Verify & complete',exact:true})).toBeDisabled()
 await expect(step.getByText('Save verified employee tax elections in pay settings.',{exact:true})).toBeVisible()
 const elections={confirmed:true,sourceNote:'Synthetic signed tax elections verified for hiring',federal:{filingStatus:'SINGLE'},maryland:{filingStatus:'SINGLE',localRate:3.2,exemptions:1}}
 await api(`/employees/${e.id}/tax-elections`,elections,200,'PATCH')
 await page.getByRole('button',{name:'Refresh checklist',exact:true}).click()
 await expect(page.getByRole('status')).toHaveText('Checklist refreshed.')
 await step.locator('summary').first().click()
 await step.getByRole('textbox',{name:'Review evidence / instructions',exact:true}).fill('Reviewed tax, payment and benefits evidence')
 await step.getByLabel('Benefits disposition',{exact:true}).selectOption('NOT_OFFERED')
 await step.getByLabel('Benefits effective or eligibility date',{exact:true}).fill('2026-08-03')
 await step.getByLabel('Benefits explanation for employee',{exact:true}).fill('No employer benefit plan is offered for this synthetic hire.')
 await step.getByLabel('Benefits review evidence',{exact:true}).fill('Synthetic employer offering verification')
 await step.getByLabel('I verified the benefits disposition, effective date and supporting evidence.',{exact:true}).check()
 await step.getByRole('button',{name:'Verify & complete',exact:true}).click()
 await expect(page.getByRole('status')).toHaveText('Step reviewed and completed.')
 await step.locator('summary').first().click()
 await expect(step.getByText('Employee pay setup: reviewed and current',{exact:true})).toBeVisible()
 await api(`/employees/${e.id}/tax-elections`,{...elections,federal:{filingStatus:'SINGLE',extraWithholdingCents:1000}},200,'PATCH')
 await page.getByRole('button',{name:'Refresh checklist',exact:true}).click()
 await expect(step.locator('summary').first()).toContainText('REVIEW REQUIRED')
 await step.locator('summary').first().click()
 await expect(step.getByText('Employee pay setup: updated review required',{exact:true})).toBeVisible()
 await step.screenshot({path:'/tmp/payroll-pay-setup-mobile.png'})
 await step.getByRole('textbox',{name:'Review evidence / instructions',exact:true}).fill('Reviewed revised additional withholding and current payment election')
 await step.getByLabel('I verified the benefits disposition, effective date and supporting evidence.',{exact:true}).check()
 await step.getByRole('button',{name:'Verify & complete',exact:true}).click()
 await expect(step.getByText('Employee pay setup: reviewed and current',{exact:true})).toBeVisible()
 await expect(page.getByRole('status')).toHaveText('Step reviewed and completed.')
 await api('/settings',{benefitsText:'Updated employer benefits offering: no plan currently offered.'},200,'PATCH')
 await page.getByRole('button',{name:'Refresh checklist',exact:true}).click()
 await expect(step.locator('summary').first()).toContainText('REVIEW REQUIRED')
 await step.locator('summary').first().click()
 await expect(step.getByLabel('I verified the benefits disposition, effective date and supporting evidence.',{exact:true})).not.toBeChecked()
 await step.getByRole('textbox',{name:'Review evidence / instructions',exact:true}).fill('Reviewed the revised employer benefit offering')
 await step.getByLabel('I verified the benefits disposition, effective date and supporting evidence.',{exact:true}).check()
 await step.getByRole('button',{name:'Verify & complete',exact:true}).click()
 await expect(page.getByRole('status')).toHaveText('Step reviewed and completed.')
 await step.screenshot({path:'/tmp/payroll-benefits-admin-mobile.png'})
 const invitation=await api(`/employees/${e.id}/invitations`,{email:'pay-setup-browser@example.test',sendEmail:false},201)
 await page.route('**/api/payroll/employee/**',async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
 await page.goto(`/employee/payroll?invite=${new URL(invitation.inviteUrl).searchParams.get('invite')}`)
 await page.getByRole('button',{name:'Onboarding',exact:true}).click()
 const employeeStep=page.locator('details').filter({has:page.getByText('Pay, classification & benefits review',{exact:true})})
 await employeeStep.locator('summary').first().click()
 await expect(employeeStep.getByText('No employer benefit plan is offered for this synthetic hire.',{exact:true})).toBeVisible()
 await expect(employeeStep).not.toContainText('Synthetic employer offering verification')
 await expect(employeeStep.getByLabel('Benefits review evidence',{exact:true})).toHaveCount(0)
 await employeeStep.screenshot({path:'/tmp/payroll-benefits-employee-mobile.png'})
 }finally{await page.unrouteAll({behavior:'wait'});await page.close();await h.close()}
})
