import {test,expect as baseExpect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
import {monthlyBenefitsFixture} from '../../backend/payroll/testing/monthlyBenefitsFixture.js'
const expect=baseExpect.configure({timeout:20000})
test('I-9 employee draft resumes, retries once and displays all official instructions',async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database');test.setTimeout(120000);page.setDefaultTimeout(15000)
 const oldKey=process.env.PAYROLL_DOCUMENT_KEY;process.env.PAYROLL_DOCUMENT_KEY='67'.repeat(32)
 const h=await createHarness(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 try{
  const {employee}=await monthlyBenefitsFixture(h)
  await page.setViewportSize({width:390,height:950})
  await page.addInitScript(()=>sessionStorage.setItem('vortex_payroll_employee_session_v1','monthly-benefits-session'))
  let lose=true,loseSigning=true
  await page.route('**/api/payroll/employee/**',async route=>{
   const u=new URL(route.request().url()),response=await route.fetch({url:`${h.url}${u.pathname}${u.search}`,maxRetries:route.request().method()==='GET'?2:0})
   if(lose&&u.pathname.endsWith('/i9/draft')&&route.request().method()==='POST'){expect(response.status()).toBe(200);lose=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Synthetic lost I-9 draft response. Retry unchanged.'})});return}
   if(loseSigning&&u.pathname.endsWith('/i9/sign')){expect(response.status()).toBe(200);loseSigning=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Synthetic lost I-9 signing response. Retry unchanged.'})});return}
   await route.fulfill({response})
  })
  const open=async()=>{await page.goto('/tests/support/payroll.html?employee=1');await page.getByRole('button',{name:'Onboarding',exact:true}).click();await page.locator('summary').filter({hasText:'Form I-9 employee section'}).click()}
  await open()
  const panel=page.getByRole('region',{name:'Internal I-9 draft',exact:true}),save=panel.getByRole('button',{name:'Save I-9 draft',exact:true})
  const initialSsn=panel.getByLabel('Social Security number (if provided)',{exact:true}),initialAddress=panel.getByLabel('Street address',{exact:true})
  await expect(initialSsn).toHaveValue('');await expect(initialAddress).toHaveValue('')
  await expect(initialSsn).toHaveAttribute('autocomplete','new-password');await expect(initialSsn).toHaveAttribute('data-bwignore','true');await expect(initialAddress).toHaveAttribute('data-form-type','other')
  await panel.getByLabel('Last name (family name)',{exact:true}).fill('Żółć')
  await panel.getByLabel('Social Security number (if provided)',{exact:true}).fill('123-4')
  await expect(panel.getByRole('combobox',{name:'Did a preparer or translator assist you with Section 1?',exact:true})).toHaveValue('')
  await save.click();await expect(panel.getByRole('alert')).toContainText('Synthetic lost I-9 draft response')
  await save.click();await expect(panel.getByRole('status')).toContainText('I-9 draft saved securely.')
  expect((await h.pool.query('SELECT revision FROM payroll_i9_draft WHERE employee_id=$1',[employee.id])).rows[0].revision).toBe(1)
  await open();await expect(panel.getByLabel('Last name (family name)',{exact:true})).toHaveValue('Żółć')
  await expect(panel.getByLabel('Social Security number (if provided)',{exact:true})).toHaveValue('123-4')
  await panel.getByRole('combobox',{name:'Citizenship or immigration attestation',exact:true}).selectOption('AUTHORIZED_WORKER')
  await panel.getByRole('combobox',{name:'Identifier alternative',exact:true}).selectOption('PASSPORT')
  await panel.getByLabel('Selected identifier number',{exact:true}).fill('SYNTHETIC-PASSPORT')
  await panel.getByLabel('Passport country of issuance',{exact:true}).fill('Example country')
  await panel.getByRole('combobox',{name:'Did a preparer or translator assist you with Section 1?',exact:true}).selectOption('YES')
  const summary=page.locator('summary').filter({hasText:'Form I-9 employee section'});await summary.click();await summary.click()
  await expect(panel.getByLabel('Selected identifier number',{exact:true})).toHaveValue('SYNTHETIC-PASSPORT')
  await save.click();await expect(panel.getByRole('status')).toContainText('I-9 draft saved securely.')
  await open();await expect(panel.getByLabel('Passport country of issuance',{exact:true})).toHaveValue('Example country')
  await expect(panel).toContainText('Each assisting preparer or translator must separately complete and sign Supplement A.')
  await panel.getByRole('button',{name:'Read official I-9 instructions here',exact:true}).click()
  const review=panel.getByRole('region',{name:'Official I-9 instructions page review',exact:true})
  for(let n=1;n<=8;n++){await review.getByRole('button',{name:`Page ${n}`,exact:true}).click();await expect(review.getByRole('status')).toContainText(`Page ${n} of 8 displayed.`)}
  expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true)
  await panel.screenshot({path:'/tmp/payroll-i9-draft-mobile.png'})
  const storage=await page.evaluate(()=>JSON.stringify({session:{...sessionStorage},local:{...localStorage}}));expect(storage).not.toContain('123-4');expect(storage).not.toContain('SYNTHETIC-PASSPORT')
  const task=(await h.pool.query("SELECT status,response FROM payroll_onboarding_task WHERE employee_id=$1 AND task_key='I9'",[employee.id])).rows[0]
  expect(task.status).toBe('OPEN');expect(JSON.stringify(task.response)).not.toContain('SYNTHETIC-PASSPORT')
  expect(JSON.stringify((await h.pool.query("SELECT after_data FROM payroll_audit_log WHERE action='I9_DRAFT_SAVED'")).rows)).not.toContain('123-4')
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`,maxRetries:route.request().method()==='GET'?2:0})})})
  const openAdmin=async()=>{await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'People & onboarding',exact:true}).click();await page.locator('summary').filter({hasText:'Form I-9 employee section'}).click()}
  await openAdmin()
  const admin=page.getByRole('region',{name:'I-9 hiring context',exact:true}),record=admin.getByRole('button',{name:'Record I-9 hiring context',exact:true})
  await expect(record).toBeDisabled()
  await admin.getByLabel('Offer accepted on',{exact:true}).fill('2026-09-01')
  await admin.getByRole('combobox',{name:'Employer and hiring-site E-Verify participation',exact:true}).selectOption('false')
  await admin.getByLabel('Offer and participation verification evidence',{exact:true}).fill('Synthetic accepted offer and hiring-site participation records reviewed.')
  await admin.getByRole('checkbox').check();await record.click()
  await expect(admin.getByRole('status')).toContainText('I-9 hiring context recorded.')
  await openAdmin();await expect(admin.getByLabel('Offer accepted on',{exact:true})).toHaveValue('2026-09-01')
  await expect(admin.getByRole('combobox',{name:'Employer and hiring-site E-Verify participation',exact:true})).toHaveValue('false')
  await admin.locator('summary').click();await expect(admin).toContainText('Revision 1: offer accepted 2026-09-01')
  await expect(admin.getByRole('checkbox')).not.toBeChecked()
  await admin.screenshot({path:'/tmp/payroll-i9-context-admin.png'})
  await open()
  for(const [label,value] of [['First name (given name)','Łukasz'],['Street address','100 Example Street'],['City or town','Bowie'],['State','MD'],['ZIP code','20715'],['Date of birth (YYYY-MM-DD)','2000-01-01'],['Social Security number (if provided)','123456789']])await panel.getByLabel(label,{exact:true}).fill(value)
  await panel.getByRole('combobox',{name:'Citizenship or immigration attestation',exact:true}).selectOption('CITIZEN')
  await panel.getByRole('combobox',{name:'Have you applied for an SSN and are waiting to receive it?',exact:true}).selectOption('NO')
  await panel.getByRole('combobox',{name:'Did a preparer or translator assist you with Section 1?',exact:true}).selectOption('NO')
  const prepare=panel.getByRole('button',{name:'Prepare saved I-9 for review',exact:true});await expect(prepare).toBeDisabled()
  await save.click();await expect(panel.getByRole('status')).toContainText('I-9 draft saved securely.')
  await prepare.click()
  const completed=panel.getByRole('region',{name:'Official I-9 page review',exact:true})
  for(let n=1;n<=4;n++){await completed.getByRole('button',{name:`Page ${n}`,exact:true}).click();await expect(completed.getByRole('status')).toContainText(`Page ${n} of 4 displayed and review visit saved.`)}
  await completed.getByRole('button',{name:'Page 1',exact:true}).click();await expect(completed.getByRole('status')).toContainText('Page 1 of 4 displayed and review visit saved.')
  await completed.screenshot({path:'/tmp/payroll-i9-preview-mobile.png'})
  await expect(panel).toContainText('Unsigned Section 1 preview.');await expect(completed).toContainText('Review your unsigned I-9 Section 1')
  const reviews=await h.pool.query('SELECT id FROM payroll_i9_review WHERE employee_id=$1',[employee.id]);expect(reviews.rowCount).toBe(1)
  expect((await h.pool.query('SELECT * FROM payroll_i9_page_visit WHERE review_id=$1',[reviews.rows[0].id])).rowCount).toBe(4)
  await panel.getByLabel('First name (given name)',{exact:true}).fill('Changed')
  await expect(completed).toHaveCount(0);await expect(prepare).toBeDisabled()
  expect((await h.pool.query("SELECT status FROM payroll_onboarding_task WHERE employee_id=$1 AND task_key='I9'",[employee.id])).rows[0].status).toBe('OPEN')
  await panel.getByLabel('First name (given name)',{exact:true}).fill('Łukasz');await save.click();await expect(panel.getByRole('status')).toContainText('I-9 draft saved securely.');await prepare.click()
  const sign=panel.getByRole('button',{name:'Sign I-9 Section 1',exact:true});await expect(sign).toBeDisabled()
  for(let n=1;n<=4;n++){await completed.getByRole('button',{name:`Page ${n}`,exact:true}).click();await expect(completed.getByRole('status')).toContainText(`Page ${n} of 4 displayed and review visit saved.`)}
  await panel.getByRole('checkbox',{name:'I read this attestation and reviewed all four pages.',exact:false}).check()
  await panel.getByLabel('Employee’s I-9 signature',{exact:true}).fill('Łukasz Żółć')
  await sign.click();await expect(panel.getByRole('alert')).toContainText('Synthetic lost I-9 signing response')
  await sign.click();await expect(page.getByRole('status').filter({hasText:'Your signed I-9 Section 1 was submitted'})).toBeVisible()
  expect((await h.pool.query('SELECT * FROM payroll_i9_submission WHERE employee_id=$1',[employee.id])).rowCount).toBe(1)
  await open();await expect(panel).toHaveCount(0);await page.getByRole('button',{name:'Prepare an I-9 amendment',exact:true}).click();await expect(panel.getByLabel('Social Security number (if provided)',{exact:true})).toHaveValue('')
  await expect(page.getByText('Employee Section 1 signing confirmation',{exact:false})).toBeVisible()
  const step=page.locator('details').filter({has:panel});await expect(step.getByRole('button',{name:'Update submission',exact:true})).toHaveCount(0)
  const download=page.waitForEvent('download');await step.getByRole('button',{name:'Form-I9-Section1-signed.pdf',exact:true}).click();expect((await download).suggestedFilename()).toBe('Form-I9-Section1-signed.pdf')
  await page.getByRole('button',{name:'Close amendment (discards unsaved entries)',exact:true}).click();await expect(panel).toHaveCount(0)
  await page.locator('details').filter({has:page.getByRole('button',{name:'Prepare an I-9 amendment',exact:true})}).screenshot({path:'/tmp/payroll-i9-signed-receipt-mobile.png'})
  await openAdmin();await expect(page.getByRole('button',{name:'Form-I9-Section1-signed.pdf',exact:true})).toBeVisible()
  const adminDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Form-I9-Section1-signed.pdf',exact:true}).click();expect((await adminDownload).suggestedFilename()).toBe('Form-I9-Section1-signed.pdf')
  expect(errors).toEqual([])
 }finally{await page.unrouteAll({behavior:'ignoreErrors'});await page.close();await h.close();if(oldKey===undefined)delete process.env.PAYROLL_DOCUMENT_KEY;else process.env.PAYROLL_DOCUMENT_KEY=oldKey}
})
