import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
test('admin reviews full hiring-boundary week beyond the selected period',async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness()
 try{
  const api=async(path:string,body:unknown)=>{const r=await fetch(`${h.url}/api/admin/payroll${path}`,{method:'POST',headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:JSON.stringify(body)});expect(r.ok).toBeTruthy();return(await r.json()).data}
  const e=await api('/employees',{employeeNumber:'BOUNDARY-BROWSER',legalFirstName:'Boundary',legalLastName:'Browser',hireDate:'2026-08-03',hourlyRateCents:2500})
  await h.pool.query("UPDATE payroll_employee SET employment_status='TERMINATED',termination_date='2026-08-05' WHERE id=$1",[e.id])
  await h.pool.query("UPDATE payroll_employee SET employment_status='ONBOARDING',hire_date='2026-08-07',termination_date=NULL,pay_type='SALARY',annual_salary_cents=5200000 WHERE id=$1",[e.id])
  await api(`/employees/${e.id}/salary-review`,{classification:'NONEXEMPT',fixed40Verified:true,minimumWageVerified:true,minimumWageCents:1500,confirmed:true,source:'Synthetic reviewed current hiring agreement'})
  await h.pool.query("UPDATE payroll_employee SET employment_status='ACTIVE' WHERE id=$1",[e.id])
  await h.pool.query("INSERT INTO payroll_time_entry(facility_id,employee_id,clock_in,clock_out,source,status) VALUES(1,$1,'2026-08-03T12:00Z','2026-08-03T13:00Z','ADMIN','APPROVED'),(1,$1,'2026-08-07T12:00Z',NULL,'ADMIN','UNVERIFIED')",[e.id])
  const period=(await h.pool.query("INSERT INTO payroll_pay_period(facility_id,period_start,period_end,pay_date,frequency) VALUES(1,'2026-08-03','2026-08-05','2026-08-14','SEMIMONTHLY') RETURNING id")).rows[0]
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  let loseSaveResponse=true,loseAuthorizationResponse=true
  await page.route('**/api/admin/payroll/**',async route=>{const url=new URL(route.request().url());const response=await route.fetch({url:`${h.url}${url.pathname}${url.search}`});if(url.pathname.endsWith('/workweek-allocations')&&route.request().method()==='POST'&&loseSaveResponse){loseSaveResponse=false;await route.abort('failed')}else if(url.pathname.endsWith('/workweek-settlement-authorizations')&&route.request().method()==='POST'&&loseAuthorizationResponse){loseAuthorizationResponse=false;await route.abort('failed')}else await route.fulfill({response})})
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Payroll runs',exact:true}).click()
  await page.getByRole('combobox',{name:'Pay period',exact:true}).selectOption(String(period.id));await page.getByRole('button',{name:'Preview payroll',exact:true}).click()
  const review=page.getByRole('region',{name:'Hiring boundary workweek review',exact:true})
  await expect(review.getByText('Approved work: 1.00 hours',{exact:true})).toBeVisible()
  await expect(review.getByText('2026-08-07 · Needs clock/break review · unverified',{exact:true})).toBeVisible()
  await expect(review.getByText(/52,000.00 annual salary/)).toBeVisible()
  await page.getByRole('button',{name:'Save draft snapshot',exact:true}).click();await page.getByRole('button',{name:'Open review',exact:true}).last().click()
  await page.setViewportSize({width:390,height:1200});await review.last().scrollIntoViewIfNeeded()
  await expect(review.last().getByText('Approved work: 1.00 hours',{exact:true})).toBeVisible()
  const bounds=await review.last().boundingBox();expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(390)
  await review.last().screenshot({path:'/tmp/payroll-employment-week-mobile.png'})
  const allocation=review.last().locator('details').filter({has:page.getByText('Preview salary allocation',{exact:true})})
  await allocation.getByText('Preview salary allocation',{exact:true}).click()
  await allocation.getByLabel('Straight-time salary assigned to week ($)',{exact:true}).fill('50')
  await allocation.getByLabel('Salary allocation evidence',{exact:true}).fill('Synthetic documented salary earnings assigned to the workweek')
  await allocation.getByRole('button',{name:'Calculate workweek allocation',exact:true}).click()
  await expect(allocation.getByRole('alert')).toContainText('Resolve the workweek time')
  await h.pool.query("UPDATE payroll_time_entry SET clock_out='2026-08-07T13:00Z',status='APPROVED' WHERE employee_id=$1 AND clock_in='2026-08-07T12:00Z'",[e.id])
  await allocation.getByRole('button',{name:'Calculate workweek allocation',exact:true}).click()
  await expect(allocation.getByRole('status')).toContainText('Worked hours: 2.00')
  await expect(allocation.getByRole('status')).toContainText('Straight-time earnings: $75.00')
  await expect(allocation).toContainText('2026-08-03 · 1.00 hours · straight-time $25.00 · premium $0.00')
  await expect(allocation).toContainText('2026-08-07 · 1.00 hours · straight-time $50.00 · premium $0.00')
  await allocation.getByLabel('Straight-time salary assigned to week ($)',{exact:true}).fill('1')
  await expect(allocation.getByRole('status')).toHaveCount(0)
  await allocation.getByRole('button',{name:'Calculate workweek allocation',exact:true}).click()
  await expect(allocation.getByRole('alert')).toContainText('minimum wage')
  await allocation.getByLabel('Straight-time salary assigned to week ($)',{exact:true}).fill('50')
  await allocation.getByRole('button',{name:'Calculate workweek allocation',exact:true}).click()
  await expect(allocation.getByRole('status')).toContainText('Full-week overtime premium: $0.00')
  await allocation.screenshot({path:'/tmp/payroll-allocation-form-mobile.png'})
  await allocation.getByLabel('Allocation review reason',{exact:true}).fill('Reviewed the full workweek allocation and supporting documents')
  await allocation.getByLabel('I reviewed the complete salary allocation and its supporting workweek evidence.',{exact:true}).check()
  await allocation.getByRole('button',{name:'Save allocation review',exact:true}).click()
  await expect(allocation.getByRole('alert')).toBeVisible()
  await allocation.getByRole('button',{name:'Save allocation review',exact:true}).click()
  await expect(allocation.getByRole('status')).toContainText('Allocation review saved.')
  expect((await h.pool.query("SELECT COUNT(*)::int n FROM payroll_audit_log WHERE action='WORKWEEK_ALLOCATION_REVIEWED'")).rows[0].n).toBe(1)
  await page.reload();await page.getByRole('button',{name:'Payroll runs',exact:true}).click()
  await page.getByRole('combobox',{name:'Pay period',exact:true}).selectOption(String(period.id));await page.getByRole('button',{name:'Preview payroll',exact:true}).click()
  const retained=page.getByRole('region',{name:'Hiring boundary workweek review',exact:true}).first().locator('details')
  await retained.getByText('Preview salary allocation',{exact:true}).click()
  await expect(retained.getByText('Reviewed the full workweek allocation and supporting documents',{exact:true})).toBeVisible()
  await expect(retained.getByText('Straight-time earnings: $75.00 · full-week premium: $0.00',{exact:true})).toBeVisible()
  await retained.screenshot({path:'/tmp/payroll-allocation-history-mobile.png'})
  await expect(page.getByRole('region',{name:'Hiring boundary workweek review',exact:true}).first()).toContainText('Retained allocation: matches current earnings evidence')
  const paymentReview=page.getByRole('region',{name:'Hiring boundary workweek review',exact:true}).first()
  await expect(paymentReview).toContainText('Stored payment evidence reconciles.')
  await expect(paymentReview).toContainText('Unsettled difference — straight-time: $75.00 · premium: $0.00')
  await paymentReview.screenshot({path:'/tmp/payroll-payment-reconciliation-mobile.png'})
  const authorize=paymentReview.getByRole('region',{name:'Workweek settlement authorization',exact:true})
  await expect(authorize.getByRole('button',{name:'Authorize workweek settlement',exact:true})).toBeDisabled()
  await authorize.getByLabel('Settlement review reason',{exact:true}).fill('Reviewed payroll records and confirmed all prior workweek payments are recorded')
  await authorize.getByLabel('All payments for this workweek, including payments outside this system, are recorded.',{exact:true}).check()
  await authorize.getByLabel('I authorize the reviewed unpaid earnings for payroll settlement after current evidence is rechecked.',{exact:true}).check()
  await authorize.getByRole('button',{name:'Authorize workweek settlement',exact:true}).click()
  await expect(authorize.getByRole('alert')).toBeVisible()
  await authorize.getByRole('button',{name:'Authorize workweek settlement',exact:true}).click()
  await expect(authorize.getByRole('status')).toContainText('Settlement authorization saved.')
  expect((await h.pool.query("SELECT COUNT(*)::int n FROM payroll_audit_log WHERE action='WORKWEEK_SETTLEMENT_AUTHORIZED'")).rows[0].n).toBe(1)
  await page.reload();await page.getByRole('button',{name:'Payroll runs',exact:true}).click()
  await page.getByRole('combobox',{name:'Pay period',exact:true}).selectOption(String(period.id));await page.getByRole('button',{name:'Preview payroll',exact:true}).click()
  const authorizedReview=page.getByRole('region',{name:'Hiring boundary workweek review',exact:true}).first()
  await expect(authorizedReview).toContainText('Authorization matches reviewed evidence.')
  const partialEarnings=page.getByRole('region',{name:'Allocated workweek earnings',exact:true}).first()
  await expect(partialEarnings).toContainText('2026-08-03 through 2026-08-05')
  await expect(partialEarnings).toContainText('1.00 worked hours · straight-time wages $25.00')
  await partialEarnings.screenshot({path:'/tmp/payroll-partial-earnings-mobile.png'})
  await authorizedReview.getByRole('region',{name:'Workweek settlement authorization',exact:true}).screenshot({path:'/tmp/payroll-settlement-authorization-mobile.png'})

  await h.pool.query("UPDATE payroll_time_entry SET status='UNVERIFIED' WHERE employee_id=$1 AND clock_in='2026-08-07T12:00Z'",[e.id])
  await page.getByRole('button',{name:'Preview payroll',exact:true}).click()
  const staleReview=page.getByRole('region',{name:'Hiring boundary workweek review',exact:true}).first()
  await expect(staleReview).toContainText('Retained allocation: needs a new review')
  await expect(staleReview).toContainText('Payment evidence needs review.')
  await expect(staleReview).toContainText('Authorization needs a new review.')
  await staleReview.screenshot({path:'/tmp/payroll-allocation-stale-mobile.png'})
  await h.pool.query("UPDATE payroll_time_entry SET status='APPROVED' WHERE employee_id=$1 AND clock_in='2026-08-07T12:00Z'",[e.id])
  await h.pool.query("UPDATE payroll_pay_period SET period_end='2026-08-09' WHERE id=$1",[period.id])
  await page.getByRole('button',{name:'Preview payroll',exact:true}).click()
  const earnings=page.getByRole('region',{name:'Allocated workweek earnings',exact:true}).first()
  await expect(earnings).toContainText('2.00 worked hours · straight-time wages $75.00')
  await expect(earnings).toContainText('0.00 overtime hours · premium $0.00')
  await expect(earnings).toContainText('Combined regular rate: $37.50/hour')
  await earnings.screenshot({path:'/tmp/payroll-authorized-earnings-mobile.png'})
  await h.pool.query("INSERT INTO payroll_time_entry(facility_id,employee_id,clock_in,clock_out,source,status) VALUES(1,$1,'2026-08-10T12:00Z','2026-08-10T13:00Z','ADMIN','APPROVED')",[e.id])
  await h.pool.query("UPDATE payroll_pay_period SET period_end='2026-08-16' WHERE id=$1",[period.id])
  await page.getByRole('button',{name:'Preview payroll',exact:true}).click()
  const ordinary=page.getByRole('region',{name:'Hiring boundary workweek review',exact:true}).first().getByRole('heading',{name:'Boundary Browser · 2026-08-10 through 2026-08-16',exact:true}).locator('..')
  await expect(ordinary).toContainText('Approved work: 1.00 hours')
  await expect(ordinary).toContainText('Retained allocation: not yet recorded')
  await ordinary.screenshot({path:'/tmp/payroll-ordinary-week-mobile.png'})



  expect(errors).toEqual([])
 }finally{await page.unrouteAll({behavior:'wait'});await page.close();await h.close()}
})
