import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
import {correctionPaymentFixture} from '../../backend/payroll/testing/correctionPaymentFixture.js'
for(const openingAccruedMinutes of [0,2250])test(`admin previews correction taxes and target leave with opening accrual ${openingAccruedMinutes}`,async({page})=>{
 test.setTimeout(90000);test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness();try{
 const fixture=await correctionPaymentFixture(h,{openingAccruedMinutes})
 let loseAuthorizationResponse=true
 await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
 await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());if(u.pathname.endsWith('/payroll-correction-authorizations')&&route.request().method()==='POST'&&loseAuthorizationResponse){loseAuthorizationResponse=false;await route.fetch({url:`${h.url}${u.pathname}`});await route.abort('failed');return}await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
 await page.setViewportSize({width:390,height:1400});await page.goto('/tests/support/payroll.html')
 await page.getByRole('button',{name:'Requests & approvals',exact:true}).click()
 const card=page.getByRole('heading',{name:'Split Settlement · TIME CORRECTION',exact:true}).locator('../..')
 await card.getByRole('button',{name:'Review payroll impact',exact:true}).click()
 await card.getByRole('button',{name:'Load retained calculations',exact:true}).click()
 await card.getByRole('button',{name:'Prepare correction payment',exact:true}).click()
 await card.getByLabel('Correction processing payroll',{exact:true}).selectOption({label:'2026-08-16 through 2026-08-31'})
 await expect(card.getByLabel('Correction payment date',{exact:true})).toHaveValue('2026-09-04')
 await card.getByLabel('Correction wage-history source',{exact:true}).fill('Reviewed all synthetic employer and related-employer wage records through payment')
 await card.getByLabel('I verified complete employer and related-employer wage history through this payment date.',{exact:true}).check()
 await card.getByRole('button',{name:'Preview correction taxes',exact:true}).click()
 await expect(card.getByText('Additional take-home pay: $55.80',{exact:true})).toBeVisible()
 await expect(card.getByText('Federal withholding change: $7.50. Maryland withholding change: $5.96.',{exact:true})).toBeVisible()
 await expect(card.getByText(new RegExp(`Current payroll counts 40.00 worked hours and ${openingAccruedMinutes?66:80} earned leave minutes`))).toBeVisible()
 await expect(card.getByText(`Target payroll leave: ${openingAccruedMinutes?'70 → 66':'80 → 80'} minutes. Historical credit change: 4 minutes. Combined credit change: ${openingAccruedMinutes?0:4} minutes.`,{exact:true})).toBeVisible()
 await expect(card.getByText('Processing payroll: 2026-08-16 through 2026-08-31. Payment date: 2026-09-04.',{exact:true})).toBeVisible()
 await card.getByLabel('Payment authorization reason',{exact:true}).fill('Approved the reviewed tax and leave results for this specific correction payment')
 await card.getByLabel('I authorize the reviewed correction for this payroll and payment date.',{exact:true}).check()
 await card.getByRole('button',{name:'Authorize correction payment',exact:true}).click()
 await expect(card.getByRole('alert')).toBeVisible()
 await card.getByRole('button',{name:'Authorize correction payment',exact:true}).click()
 await expect(card.getByText(/Payment authorization #.* retained/)).toBeVisible()
 expect((await h.pool.query("SELECT COUNT(*)::int AS count FROM payroll_audit_log WHERE action='CORRECTION_PAYMENT_AUTHORIZED'")).rows[0].count).toBe(1)
 await page.reload()
 await page.getByRole('button',{name:'Requests & approvals',exact:true}).click()
 await card.getByRole('button',{name:'Review payroll impact',exact:true}).click()
 await card.getByRole('button',{name:'Load payment authorizations',exact:true}).click()
 await expect(card.getByText(/matches current payment evidence/)).toBeVisible()
 await expect(card.getByText('Additional gross: $75.00. Additional take-home: $55.80.',{exact:true})).toBeVisible()
 await h.pool.query("UPDATE payroll_time_entry SET clock_out=clock_out+interval '1 hour' WHERE employee_id=$1 AND clock_in='2026-08-17T12:00Z'",[fixture.e.id])
 await card.getByRole('button',{name:'Load payment authorizations',exact:true}).click()
 await expect(card.getByText(/needs fresh payment evidence/)).toBeVisible()
 await card.screenshot({path:`/tmp/payroll-correction-authorization-${openingAccruedMinutes}.png`})
 }finally{await page.unrouteAll({behavior:'wait'});await page.close();await h.close()}
})
