import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
test('admin creates a salaried hire and employee sees the annual salary in the portal',async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated localhost payroll database')
 const h=await createHarness()
 try{
  const schedule=await fetch(`${h.url}/api/admin/payroll/pay-schedule/configure`,{method:'POST',headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:JSON.stringify({frequency:'WEEKLY',anchorStart:'2026-08-03',paymentLagDays:5,source:'Synthetic published weekly hiring schedule',confirmed:true})});expect(schedule.ok).toBeTruthy()
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  for(const prefix of ['admin/payroll','payroll/employee'])await page.route(`**/api/${prefix}/**`,async route=>{const url=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${url.pathname}${url.search}`})})})
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'People & onboarding',exact:true}).click()
  for(const [label,value] of Object.entries({'Employee number':'SALARY-BROWSER','Hire date':'2026-01-01','Legal first name':'Salary','Legal last name':'Browser','Personal email':'salary-browser@example.test','Job title':'Office manager'}))await page.getByLabel(label,{exact:true}).fill(value)
  await page.getByRole('combobox',{name:'Pay basis',exact:true}).selectOption('SALARY')
  await page.getByLabel('Annual salary',{exact:true}).fill('78000')
  await expect(page.getByLabel('Hourly rate',{exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'Create onboarding record',exact:true}).click()
  await expect(page.getByText(/SALARY-BROWSER · Office manager · \$78,000.00\/year/)).toBeVisible()
  const employee=(await h.pool.query("SELECT * FROM payroll_employee WHERE employee_number='SALARY-BROWSER'")).rows[0]
  expect(employee.pay_type).toBe('SALARY');expect(Number(employee.annual_salary_cents)).toBe(7800000);expect(employee.overtime_classification).toBe('EXEMPT_REVIEW')
  await page.getByRole('button',{name:'Pay setup & leave',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Salary classification review',exact:true})).toBeVisible()
  await page.getByRole('combobox',{name:'Overtime classification',exact:true}).selectOption('EXEMPT')
  await page.getByLabel('Reviewed annual salary ($)',{exact:true}).fill('80000')
  await page.getByLabel('Duties assessment',{exact:true}).fill('Verified independent discretion and judgment on significant office management matters.')
  await page.getByLabel('Classification evidence reference',{exact:true}).fill('Reviewed job description and salary basis agreement')
  for(const name of ['I verified the salary basis agreement and permitted deduction rules.','I verified the actual duties meet the selected exemption test.','I verified applicable Maryland exemption requirements.','I confirm this classification and its supporting evidence.'])await page.getByLabel(name,{exact:true}).check()
  await page.getByRole('button',{name:'Save salary classification',exact:true}).click()
  await expect(page.getByText(/Salary classification saved and audited/)).toBeVisible()
  expect((await h.pool.query('SELECT overtime_classification FROM payroll_employee WHERE id=$1',[employee.id])).rows[0].overtime_classification).toBe('EXEMPT')
  await page.reload();await page.getByRole('button',{name:'Pay setup & leave',exact:true}).click()
  await expect(page.getByText(/Recorded classification: EXEMPT/)).toBeVisible()
  await expect(page.getByLabel('Hourly rate ($)',{exact:true})).toHaveCount(0)
  await page.getByLabel('Phone',{exact:true}).fill('4105550123')
  await page.getByRole('button',{name:'Save employee details',exact:true}).click()
  await expect(page.getByText('Employee details saved and audited.',{exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:1600})
  const salaryCard=page.locator('section').filter({has:page.getByRole('heading',{name:'Salary classification review',exact:true})})
  await salaryCard.scrollIntoViewIfNeeded();await expect(salaryCard).toBeVisible();const bounds=await salaryCard.boundingBox();expect(bounds).not.toBeNull();expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(390);await salaryCard.screenshot({path:'/tmp/payroll-salary-review-mobile.png'})
  const response=await fetch(`${h.url}/api/admin/payroll/employees/${employee.id}/invitations`,{method:'POST',headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:JSON.stringify({email:'salary-browser@example.test',sendEmail:false})});expect(response.ok).toBeTruthy();const invite=(await response.json()).data
  await page.goto(`/tests/support/payroll.html?employee&invite=${new URL(invite.inviteUrl).searchParams.get('invite')}`)
  await expect(page.getByText('Annual salary',{exact:true})).toBeVisible()
  await expect(page.getByText('$80,000.00',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Onboarding',exact:true}).click()
  await page.getByText('Offer & wage notice acknowledgment',{exact:true}).click()
  await expect(page.getByText('Office manager · $80,000.00 per year',{exact:true})).toBeVisible()
  const notice=page.locator('details').filter({has:page.getByText('Offer & wage notice acknowledgment',{exact:true})})
  await expect(notice.getByText(/Weekly; 7-day pay periods anchored on 2026-08-03/)).toBeVisible()
  await notice.getByLabel('Your full name',{exact:true}).fill('Salary Browser')
  await notice.getByRole('checkbox').check()
  await notice.getByRole('button',{name:'Submit for review',exact:true}).click()
  await expect(page.getByText('Step submitted for review.',{exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:1200})
  const header=page.locator('section').filter({has:page.getByRole('heading',{name:'Your work, schedule, and onboarding',exact:true})})
  await header.scrollIntoViewIfNeeded();await expect(header).toBeInViewport({ratio:1});await header.screenshot({path:'/tmp/payroll-salary-portal-mobile.png'})
  expect(errors).toEqual([])
 }finally{await page.unrouteAll({behavior:'wait'});await page.close();await h.close()}
})
