import {hashEmail} from '../../backend/email/emailDeliveryStore.js'
import {refreshW2NoticeQueue} from '../../backend/payroll/w2NoticeQueue.js'
import {refreshW2NoticeDispatch} from '../../backend/payroll/w2NoticeDispatch.js'
import {createRequire} from 'node:module'
import {readFile} from 'node:fs/promises'
const {PDFDocument}=createRequire(new URL('../../backend/package.json',import.meta.url))('pdf-lib')
import {test,expect} from '@playwright/test'
import {randomBytes,generateKeyPairSync,sign} from 'node:crypto'
import {runW2ProviderEventSweep} from '../../backend/payroll/w2NoticeProviderScheduler.js'
import {createHarness} from '../../backend/payroll/testing/harness.js'
import {monthlyBenefitsFixture} from '../../backend/payroll/testing/monthlyBenefitsFixture.js'
for(const providerReturn of [false,true])test(`admin reviews annual inputs with masked identity and clears stale totals after errors (${providerReturn?'PROVIDER':'MANUAL'})`,async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database');test.setTimeout(90000);page.setDefaultTimeout(15000)
 const old=process.env.PAYROLL_DOCUMENT_KEY;process.env.PAYROLL_DOCUMENT_KEY=randomBytes(32).toString('hex');const h=await createHarness()
 try{
 const {api,employee,periods}=await monthlyBenefitsFixture(h)
 const identity={identifier:'123456789',legalName:'Synthetic Annual Employer',firstName:'Monthly',lastName:'Benefits',address:{line1:'123 Test Street',city:'Bowie',state:'MD',postalCode:'20715',country:'US'},reference:'Synthetic verified filing identity source',confirmed:true,expectedRevision:0}
 await api('/filing-identity',identity,'POST',201);await api(`/employees/${employee.id}/filing-identity`,identity,'POST',201)
 await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
 await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
 await page.setViewportSize({width:390,height:1200});await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Reports & QuickBooks',exact:true}).click()
 const view=page.getByRole('region',{name:'Year-end payroll preparation',exact:true}),prepare=view.getByRole('button',{name:'Prepare 2026 payroll inputs',exact:true});await prepare.click();await expect(view).toContainText('No finalized or imported employee payments in 2026.')
 const run=await api('/runs',{payPeriodId:periods[0].id},'POST',201);await api(`/runs/${run.id}/status`,{status:'REVIEW'},'PATCH');await api(`/runs/${run.id}/status`,{status:'APPROVED'},'PATCH');await api(`/runs/${run.id}/finalize`,{paymentDate:'2026-09-18',paymentConfirmationReference:'SYNTHETIC-ANNUAL-PREPARATION'})
 await prepare.click();await expect(view).toContainText('Reviewed qualified overtime: Unavailable')
 const source=(await api('/reports/overtime-review?year=2026')).records[0];await api(`/runs/${run.id}/employees/${employee.id}/overtime-qualification`,{sourceFingerprint:source.sourceFingerprint,expectedReviewId:0,qualifiedPremiumCents:0,flsaStatus:'FLSA_REQUIRED',reference:'Synthetic reviewed overtime qualification',confirmed:true},'POST',201)
 await prepare.click();await expect(view).toContainText('Maryland Central Registration Number missing');await expect(view).not.toContainText('Retained inputs reconcile')
 const current=(await api('/filing-identity')).revision;await api('/filing-identity',{...identity,expectedRevision:current,marylandRegistrationNumber:'01234567'},'POST',201)
 await prepare.click();await expect(view).toContainText('Maryland registration ending 4567');await expect(view).not.toContainText('01234567');await expect(view).toContainText('Retained inputs reconcile — review before form preparation.');await expect(view).toContainText('Federal wage input: $200.00');await expect(view).toContainText('Social Security withholding: $12.40');await expect(view).toContainText('Combined Medicare (W-2 box 6 input) withholding: $2.90');await expect(view).toContainText('Reviewed qualified overtime: $0.00');await expect(view).toContainText('Identifier ending 6789');await expect(view).not.toContainText('123456789');await expect(view).toContainText('Annual review and employee furnishing')
 await expect(view).toContainText('2026-09 · Medical — Family: $125.00 (posttax)');await expect(view).toContainText('They do not establish employer contributions')
 const compensation=view.getByRole('region',{name:'Compensation applicability review',exact:true}),compSave=compensation.getByRole('button',{name:'Save compensation applicability',exact:true}),compEvidence=compensation.getByLabel('Compensation review evidence',{exact:true})
 const retirementChoice=compensation.getByRole('combobox',{name:'Retirement contributions or participation',exact:true})
 for(const option of await compensation.getByRole('combobox').all())await option.selectOption('NOT_APPLICABLE')
 await retirementChoice.selectOption('STANDARD_401K_DEFERRALS');await compEvidence.fill('Synthetic standard 401k scope review without retained deferrals')
 await compensation.getByRole('checkbox',{name:'I reviewed every category against the referenced annual compensation records.',exact:true}).check();await expect(compSave).toBeDisabled()
 await compensation.getByRole('checkbox',{name:/Retirement reporting consists only/}).check()
 await compensation.getByRole('checkbox',{name:'I reviewed every category against the referenced annual compensation records.',exact:true}).check();await expect(compSave).toBeEnabled()
 await compSave.click();await expect(compensation.getByRole('alert')).toContainText('Reconcile standard 401(k) annual employee contributions');await expect(compSave).toBeDisabled()
 await prepare.click();await expect(compensation.getByRole('alert')).toHaveCount(0)
 await expect(compSave).toBeDisabled();const options=compensation.getByRole('combobox');for(let i=0;i<await options.count();i++)await options.nth(i).selectOption('NOT_APPLICABLE');await compEvidence.fill('Synthetic reviewed annual compensation evidence');await compensation.getByRole('checkbox').check();await options.first().selectOption('UNRESOLVED');await expect(compSave).toBeDisabled();await compensation.getByRole('checkbox').check();await compSave.click();await expect(view.getByRole('status')).toHaveText('Compensation applicability saved.');await expect(compensation).toContainText('CURRENT · Compensation review');await expect(compensation).toContainText('Retirement contributions or participation: Unresolved');await expect(options.first()).toHaveValue('')
 for(let i=0;i<await options.count();i++)await options.nth(i).selectOption('NOT_APPLICABLE');await compEvidence.fill('Synthetic replacement compensation evidence');await compensation.getByRole('checkbox').check();await h.pool.query('UPDATE payroll_run_employee SET posttax_deduction_cents=posttax_deduction_cents+1 WHERE payroll_run_id=$1',[run.id]);await compSave.click();await expect(compensation.getByRole('alert')).toContainText('Annual inputs changed');await expect(compSave).toBeDisabled();await prepare.click();await expect(compensation).toContainText('STALE · Compensation review');await h.pool.query('UPDATE payroll_run_employee SET posttax_deduction_cents=posttax_deduction_cents-1 WHERE payroll_run_id=$1',[run.id]);await prepare.click();await page.setViewportSize({width:390,height:2200});await compensation.screenshot({path:'/tmp/payroll-compensation-applicability-mobile.png'});await page.setViewportSize({width:390,height:1200})
 const health=view.getByRole('region',{name:'Employee health-coverage classification',exact:true});await expect(health).toContainText('Record the employer health-reporting determination')
 const reporting=await api('/health-coverage-reporting',{year:2026,disposition:'REPORT',priorYearW2Count:null,expectedRevision:0,reference:'Synthetic employer annual reporting evidence',confirmed:true},'POST',201);await prepare.click()
 const healthChoice=health.getByRole('combobox',{name:'Coverage classification',exact:true}),healthReference=health.getByLabel('Coverage classification evidence',{exact:true}),healthSave=health.getByRole('button',{name:'Save coverage classification',exact:true})
 await healthChoice.selectOption('REPORT');await health.getByLabel('Verified annual reportable cost ($)',{exact:true}).fill('0');await healthReference.fill('Synthetic verified annual coverage cost');await health.getByRole('checkbox').check();await expect(healthSave).toBeDisabled();await health.getByLabel('Verified annual reportable cost ($)',{exact:true}).fill('6900.25');await expect(healthSave).toBeDisabled();await health.getByRole('checkbox').check();await healthSave.click();await expect(view.getByRole('status')).toHaveText('Coverage classification saved.');await expect(health).toContainText('Verified reportable cost: $6900.25')
 await healthChoice.selectOption('NO_APPLICABLE_COVERAGE');await healthReference.fill('Synthetic replacement coverage evidence');await health.getByRole('checkbox').check();await api('/health-coverage-reporting',{year:2026,disposition:'SMALL_EMPLOYER_RELIEF',priorYearW2Count:10,expectedRevision:reporting.revision,reference:'Synthetic revised employer reporting evidence',confirmed:true},'POST',201);await healthSave.click();await expect(health.getByRole('alert')).toContainText('sources changed');await expect(healthSave).toBeDisabled();await prepare.click();await expect(health).toContainText('STALE · Classification');await healthChoice.selectOption('RELIEF_USED');await expect(health.getByLabel('Verified annual reportable cost ($)',{exact:true})).toHaveCount(0);await healthReference.fill('Synthetic verified employee reporting relief');await health.getByRole('checkbox').check();await healthSave.click();await expect(health).toContainText('CURRENT · Classification');await expect(health).toContainText('No reportable amount recorded');await page.setViewportSize({width:390,height:1800});await health.screenshot({path:'/tmp/payroll-employee-health-classification-mobile.png'});await page.setViewportSize({width:390,height:1200})
 await h.pool.query('UPDATE payroll_run_employee SET posttax_deduction_cents=posttax_deduction_cents+1 WHERE payroll_run_id=$1',[run.id]);await prepare.click();await expect(view).toContainText('Contributions unavailable');await expect(view).not.toContainText('Medical — Family: $125.00');await h.pool.query('UPDATE payroll_run_employee SET posttax_deduction_cents=posttax_deduction_cents-1 WHERE payroll_run_id=$1',[run.id]);await prepare.click();await expect(view).toContainText('Medical — Family: $125.00')
 const review=view.getByRole('region',{name:'Annual input review',exact:true}),reference=review.getByLabel('Annual input verification reference',{exact:true}),save=review.getByRole('button',{name:'Save annual input review',exact:true})
 await expect(save).toBeDisabled();await reference.fill('Synthetic annual input evidence reviewed');await review.getByRole('checkbox').check();await reference.fill('Synthetic revised annual input evidence');await expect(save).toBeDisabled();await review.getByRole('checkbox').check();await save.click();await expect(view.getByRole('status')).toHaveText('Annual input review saved.');await expect(review).toContainText('CURRENT · Review');await expect(reference).toHaveValue('')
 await reference.fill('Synthetic second annual input review');await review.getByRole('checkbox').check();await h.pool.query('UPDATE payroll_run_employee SET posttax_deduction_cents=posttax_deduction_cents+1 WHERE payroll_run_id=$1',[run.id]);await save.click();await expect(review.getByRole('alert')).toContainText('Annual inputs changed');await expect(save).toBeDisabled();await prepare.click();await expect(review).toContainText('STALE · Review');await expect(review).toContainText('Resolve source reconciliation issues')
 await h.pool.query('UPDATE payroll_run_employee SET posttax_deduction_cents=posttax_deduction_cents-1 WHERE payroll_run_id=$1',[run.id]);await prepare.click();await reference.fill('Synthetic replacement annual input evidence');await review.getByRole('checkbox').check();await save.click();await expect(review).toContainText('SUPERSEDED · Review');await expect(review).toContainText('CURRENT · Review');await review.screenshot({path:'/tmp/payroll-annual-review-mobile.png'})
 const draft=view.getByRole('region',{name:'W-2 draft mapping',exact:true});await expect(draft).toContainText('Draft unavailable');await expect(draft).toContainText('resolve applicability')
 for(let i=0;i<await options.count();i++)await options.nth(i).selectOption('NOT_APPLICABLE');await options.first().selectOption('EMPLOYER_ONLY_PARTICIPATION');await compEvidence.fill('Synthetic employer-only active retirement evidence');await compensation.getByRole('checkbox').last().check();await expect(compSave).toBeDisabled();await compensation.getByRole('checkbox').first().check();await compensation.getByRole('checkbox').last().check();await compSave.click();await expect(draft).not.toContainText('Draft unavailable');await expect(draft).toContainText('1 · Wages, tips, other compensation$200.00');await expect(draft).toContainText('6 · Medicare tax withheld$2.90');await expect(draft).toContainText('MD registration ending 4567');await expect(draft).toContainText('Retirement plan: Yes');await expect(draft).toContainText('No reportable code amounts');await page.setViewportSize({width:390,height:1800});await draft.screenshot({path:'/tmp/payroll-w2-draft-mobile.png'});await page.setViewportSize({width:390,height:1200})
 const approval=view.getByRole('region',{name:'W-2 approval',exact:true}),approve=approval.getByRole('button',{name:'Approve and retain W-2',exact:true}),approvalEvidence=approval.getByLabel('W-2 approval evidence',{exact:true})
 await expect(approve).toBeDisabled();await approvalEvidence.fill('Synthetic approved W-2 box review');await approval.getByRole('checkbox').check();await approvalEvidence.fill('Synthetic final W-2 review evidence');await expect(approve).toBeDisabled();await approval.getByRole('checkbox').check();await approve.click();await expect(view.getByRole('status')).toHaveText('W-2 approval retained.');await expect(approval).toContainText('CURRENT · W-2 approval');await expect(approvalEvidence).toHaveValue('')
 const downloadButton=approval.getByRole('button',{name:'Download approved employee copies',exact:true})
 const downloaded=page.waitForEvent('download',{timeout:45000});await downloadButton.click();const file=await downloaded;expect(file.suggestedFilename()).toMatch(/^w2-2026-employee-\d+-approval-\d+\.pdf$/);expect(await file.failure()).toBeNull();await expect(downloadButton).toBeEnabled()
 const pdfFailure='**/w2-approval/*/pdf';await page.route(pdfFailure,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Synthetic PDF unavailable'})}));await downloadButton.click();await expect(approval.getByRole('alert')).toHaveText('Synthetic PDF unavailable');await expect(downloadButton).toBeEnabled();await page.unroute(pdfFailure)
 await approval.getByRole('button',{name:/Review portal publication for approval/}).click();const publicationPanel=approval.getByRole('region',{name:/Portal publication for approval/});await expect(publicationPanel).toContainText('The employee must complete current electronic W-2 consent')
 const selfBase=`${h.url}/api/payroll/employee/w2-electronic`,selfHeaders={Authorization:'Bearer monthly-benefits-session','Content-Type':'application/json'},disclosure=(await (await fetch(`${selfBase}/terms`,{headers:selfHeaders})).json()).data
 const check=await fetch(`${selfBase}/proof`,{method:'POST',headers:selfHeaders,body:JSON.stringify({termsFingerprint:disclosure.fingerprint})}),proofId=check.headers.get('x-payroll-proof-id'),accessPdf=await PDFDocument.load(await check.arrayBuffer())
 const consent=await fetch(`${selfBase}/consent`,{method:'POST',headers:selfHeaders,body:JSON.stringify({decision:'CONSENT',confirmed:true,expectedRevision:0,termsFingerprint:disclosure.fingerprint,proofId,code:accessPdf.getForm().getTextField('access-code').getText(),signature:'Synthetic publication browser employee'})});expect(consent.status).toBe(201)
 await publicationPanel.getByRole('button',{name:'Reload publication',exact:true}).click();const publish=publicationPanel.getByRole('button',{name:'Publish employee W-2 copies',exact:true});await expect(publish).toBeDisabled();await publicationPanel.getByLabel('Publication evidence reference',{exact:true}).fill('Synthetic ready for employee portal review');await publicationPanel.getByRole('checkbox').check();await publicationPanel.getByLabel('Publication evidence reference',{exact:true}).fill('Synthetic final publication review evidence');await expect(publish).toBeDisabled();await publicationPanel.getByRole('checkbox').check();await publish.click();await expect(publicationPanel).toContainText('Published · Availability notice pending');await publicationPanel.screenshot({path:'/tmp/payroll-w2-publication-mobile.png'});
 await h.pool.query("UPDATE payroll_employee SET personal_email='synthetic-w2-browser@example.test' WHERE id=$1",[employee.id]);await refreshW2NoticeQueue(h.pool,1);let sends=0;await refreshW2NoticeDispatch(h.pool,1,{sender:async()=>{sends++;return {sent:false,skipped:true,reason:'category_disabled'}}});expect(sends).toBe(1);await publicationPanel.getByRole('button',{name:'Reload publication',exact:true}).click();await expect(publicationPanel).toContainText('Retry planned after');await expect(publicationPanel).toContainText('1 of 3 attempts used');await publicationPanel.screenshot({path:'/tmp/payroll-w2-retry-mobile.png'});const retryTime=(await h.pool.query('SELECT retry_not_before FROM payroll_w2_notice_result ORDER BY id DESC LIMIT 1')).rows[0].retry_not_before;await h.pool.query(await readFile(new URL('../../backend/migrations/044_email_deliverability.sql',import.meta.url),'utf8'));await refreshW2NoticeDispatch(h.pool,1,{now:new Date(retryTime),sender:async message=>{sends++;await h.pool.query("INSERT INTO email_delivery(facility_id,category,stream,template_version,recipient_hash,status,idempotency_key,accepted_at) VALUES(1,'payroll_w2_notice','transactional','w2-notice-2026-v1',$1,'accepted',$2,clock_timestamp())",[hashEmail(message.to),message.idempotencyKey]);throw new Error('Synthetic lost sender response after acceptance')}});expect(sends).toBe(2);await publicationPanel.getByRole('button',{name:'Reload publication',exact:true}).click();await expect(publicationPanel).toContainText('Send outcome needs review');await refreshW2NoticeDispatch(h.pool,1,{sender:async()=>{throw new Error('Unexpected resend')}});await publicationPanel.getByRole('button',{name:'Reload publication',exact:true}).click();await expect(publicationPanel).toContainText('Published · Notice accepted by mail service');await expect(publicationPanel).toContainText('This does not establish inbox delivery or employee access');await expect(publicationPanel).toContainText('Notice attempt history (2)');await publicationPanel.getByText('Notice attempt history (2)',{exact:true}).click();await expect(publicationPanel.locator('li')).toHaveCount(2);await expect(publicationPanel).toContainText('Reconciled from retained mail acceptance');await publicationPanel.screenshot({path:'/tmp/payroll-w2-notice-evidence-mobile.png'});if(providerReturn){
 const delivery=(await h.pool.query("UPDATE email_delivery SET provider='smtp:sendgrid' RETURNING *")).rows[0]
 const pair=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),oldPublicKey=process.env.PAYROLL_SENDGRID_WEBHOOK_PUBLIC_KEY
 process.env.PAYROLL_SENDGRID_WEBHOOK_PUBLIC_KEY=pair.publicKey.export({type:'spki',format:'der'}).toString('base64')
 try{
  const timestamp=String(Math.floor(Date.now()/1000)),body=Buffer.from(JSON.stringify([{event:'bounce',sg_event_id:'synthetic-browser-w2-return',sg_message_id:'synthetic-browser-message',email:'synthetic-w2-browser@example.test',vortex_w2_dispatch:delivery.idempotency_key,timestamp:Number(timestamp)}])+'\r\n')
  const response=await fetch(`${h.url}/api/payroll/providers/sendgrid/events`,{method:'POST',headers:{'Content-Type':'application/json','X-Twilio-Email-Event-Webhook-Timestamp':timestamp,'X-Twilio-Email-Event-Webhook-Signature':sign('sha256',Buffer.concat([Buffer.from(timestamp),body]),pair.privateKey).toString('base64')},body})
  expect(response.status,await response.text()).toBe(202);expect((await runW2ProviderEventSweep(h.pool)).checked).toBe(1)
 }finally{if(oldPublicKey===undefined)delete process.env.PAYROLL_SENDGRID_WEBHOOK_PUBLIC_KEY;else process.env.PAYROLL_SENDGRID_WEBHOOK_PUBLIC_KEY=oldPublicKey}
 await publicationPanel.getByRole('button',{name:'Reload publication',exact:true}).click()
}else{await publicationPanel.getByRole('button',{name:'Record an electronic return',exact:true}).click();const returnForm=publicationPanel.locator('[aria-label="Record electronic notice return"]'),saveReturn=returnForm.getByRole('button',{name:'Save electronic return',exact:true});await expect(saveReturn).toBeDisabled();await returnForm.getByLabel('Returned notice attempt',{exact:true}).selectOption({index:1});await expect.poll(async()=>(await h.pool.query("SELECT clock_timestamp()>=date_trunc('second',max(created_at))+interval '1 second' AS ready FROM payroll_w2_notice_attempt")).rows[0].ready).toBe(true);await returnForm.getByLabel('Actual electronic return time (your local time)',{exact:true}).fill(await page.evaluate(()=>{const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,19).replace(/:00$/,'')}));await returnForm.getByLabel('Electronic return evidence reference',{exact:true}).fill('Synthetic manual electronic return receipt');await returnForm.getByRole('checkbox').check();await returnForm.getByLabel('Electronic return evidence reference',{exact:true}).fill('Synthetic verified manual return receipt');await expect(saveReturn).toBeDisabled();await returnForm.getByRole('checkbox').check();await returnForm.screenshot({path:'/tmp/payroll-w2-manual-return-form-mobile.png'});await saveReturn.click();await expect(returnForm).toHaveCount(0);}await expect(publicationPanel).toContainText('Electronic notice returned');await expect(publicationPanel).toContainText('arrange paper follow-up');await expect(publicationPanel).toContainText('Paper follow-up target:');await expect(publicationPanel).toContainText('within 30 days of return');await publicationPanel.screenshot({path:`/tmp/payroll-w2-${providerReturn?'provider':'manual'}-return-mobile.png`});
 await publicationPanel.getByRole('button',{name:'Correct electronic return evidence',exact:true}).click()
 const correction=publicationPanel.getByRole('group',{name:'Correct electronic return evidence',exact:true}),saveCorrection=correction.getByRole('button',{name:'Save return correction',exact:true})
 await expect(saveCorrection).toBeDisabled();await correction.getByLabel('Return to correct',{exact:true}).selectOption({index:1})
 if(providerReturn)await expect(correction).toContainText('Earliest signed provider return:')
 else await correction.getByLabel('Corrected return time (your local time)',{exact:true}).fill(await page.evaluate(()=>{const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,19)}))
 await correction.getByLabel('Correction evidence reference',{exact:true}).fill('Synthetic browser reviewed correction evidence');await correction.getByRole('checkbox').check();await saveCorrection.click();await expect(correction).toHaveCount(0)
 await publicationPanel.getByText('Notice attempt history (2)',{exact:true}).click();await expect(publicationPanel).toContainText('Original return:');await expect(publicationPanel).toContainText('Synthetic browser reviewed correction evidence');await expect(publicationPanel).toContainText('Electronic notice returned')
 await publicationPanel.screenshot({path:`/tmp/payroll-w2-${providerReturn?'provider':'manual'}-correction-mobile.png`});
 if(!providerReturn){
  await publicationPanel.getByRole('button',{name:'Retract mistaken manual return',exact:true}).click()
  const retraction=publicationPanel.getByRole('group',{name:'Retract mistaken manual return',exact:true}),confirmRetraction=retraction.getByRole('button',{name:'Confirm manual return retraction',exact:true})
  await expect(confirmRetraction).toBeDisabled();await retraction.getByLabel('Mistaken return attempt',{exact:true}).selectOption({index:1});await retraction.getByLabel('Retraction evidence reference',{exact:true}).fill('Synthetic browser reviewed mistaken return evidence');await retraction.getByRole('checkbox').check();await confirmRetraction.click();await expect(retraction).toHaveCount(0)
  await expect(publicationPanel).toContainText('Published · Notice accepted by mail service');await expect(publicationPanel).not.toContainText('Paper follow-up target:');await publicationPanel.getByText('Notice attempt history (2)',{exact:true}).click();await expect(publicationPanel).toContainText('Manual return retracted:');await publicationPanel.screenshot({path:'/tmp/payroll-w2-retraction-mobile.png'})
  for(let cycle=0;cycle<2;cycle++){
   await publicationPanel.getByRole('button',{name:'Record new return after retraction',exact:true}).click()
   const again=publicationPanel.getByRole('group',{name:'Record new return after retraction',exact:true}),saveAgain=again.getByRole('button',{name:'Save new return evidence',exact:true})
   await expect(saveAgain).toBeDisabled();await again.getByLabel('Retracted notice attempt',{exact:true}).selectOption({index:1})
   await again.getByLabel('New return time (your local time)',{exact:true}).fill(await page.evaluate(()=>{const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,19)}))
   await again.getByLabel('New return evidence reference',{exact:true}).fill(`Synthetic browser new return cycle ${cycle}`);await again.getByRole('checkbox').check();await saveAgain.click();await expect(again).toHaveCount(0)
   await expect(publicationPanel).toContainText('Paper follow-up target:');await expect(publicationPanel).toContainText('Electronic notice returned')
   await publicationPanel.getByRole('button',{name:'Retract mistaken manual return',exact:true}).click();await retraction.getByLabel('Mistaken return attempt',{exact:true}).selectOption({index:1});await retraction.getByLabel('Retraction evidence reference',{exact:true}).fill(`Synthetic browser mistaken new return cycle ${cycle}`);await retraction.getByRole('checkbox').check();await confirmRetraction.click();await expect(retraction).toHaveCount(0)
   await expect(publicationPanel).toContainText('Published · Notice accepted by mail service');await expect(publicationPanel).not.toContainText('Paper follow-up target:')
  }
  await publicationPanel.getByText('Notice attempt history (2)',{exact:true}).click();await expect(publicationPanel).toContainText('New return recorded');await expect(publicationPanel).toContainText('Synthetic browser reviewed mistaken return evidence');await expect(publicationPanel).toContainText('Synthetic browser mistaken new return cycle 1')
  expect((await h.pool.query('SELECT * FROM payroll_w2_return_cycle')).rowCount).toBe(4);await publicationPanel.screenshot({path:'/tmp/payroll-w2-return-cycles-mobile.png'});expect(await publicationPanel.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
 }else await expect(publicationPanel.getByRole('button',{name:'Retract mistaken manual return',exact:true})).toHaveCount(0)

await publicationPanel.getByRole('button',{name:'Close publication',exact:true}).click()
 await approval.getByRole('button',{name:/View furnishing for approval/}).click();const furnishing=approval.getByRole('region',{name:/Furnishing for approval/}),recordFurnishing=furnishing.getByRole('button',{name:'Record furnishing event',exact:true});await expect(recordFurnishing).toBeDisabled()
 await expect.poll(async()=>(await h.pool.query("SELECT clock_timestamp()>=date_trunc('second',published_at)+interval '1 second' AS ready FROM payroll_w2_publication ORDER BY id DESC LIMIT 1")).rows[0].ready).toBe(true)
 await furnishing.getByLabel('Actual event',{exact:true}).selectOption('PAPER_MAILED');await furnishing.getByLabel('Event date and time (your local time)',{exact:true}).fill(await page.evaluate(()=>{const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,19).replace(/:00$/,'')}));await furnishing.getByLabel('Furnishing evidence reference',{exact:true}).fill('Synthetic verified mailing to retained employee address');await furnishing.getByRole('checkbox').check();await furnishing.getByLabel('Furnishing evidence reference',{exact:true}).fill('Synthetic final mailing evidence reference');await expect(recordFurnishing).toBeDisabled();await furnishing.getByRole('checkbox').check();const paperResponse=page.waitForResponse(r=>r.url().endsWith('/furnishing')&&r.request().method()==='POST');await recordFurnishing.click();const paperResult=await paperResponse;expect(await paperResult.json()).toMatchObject({success:true});await expect(furnishing.getByRole('status')).toHaveText('Furnishing event recorded.');await expect(furnishing.locator('article')).toContainText('Paper mailed')
 await approval.getByRole('button',{name:/Review portal publication for approval/}).click();await expect(publicationPanel).toContainText('Published · Paper furnishing recorded');await expect(publicationPanel).toContainText('This resolves pending notice follow-up for this packet.');if(providerReturn)await expect(publicationPanel).toContainText('Paper furnishing recorded on time');await publicationPanel.screenshot({path:'/tmp/payroll-w2-paper-fallback-mobile.png'});await publicationPanel.getByRole('button',{name:'Close publication',exact:true}).click()
 await furnishing.getByLabel('Actual event',{exact:true}).selectOption('RETURNED_UNDELIVERABLE');await furnishing.getByLabel('Event date and time (your local time)',{exact:true}).fill(await page.evaluate(()=>{const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,19).replace(/:00$/,'')}));await furnishing.getByLabel('Furnishing evidence reference',{exact:true}).fill('Synthetic undeliverable envelope return');await furnishing.getByRole('checkbox').check();await recordFurnishing.click();await expect(furnishing.locator('article').first()).toContainText('Returned undeliverable');await expect(furnishing).toContainText('The payroll follow-up alert stays open');await page.setViewportSize({width:390,height:2000});await furnishing.screenshot({path:'/tmp/payroll-paper-furnishing-mobile.png'});await page.setViewportSize({width:390,height:1200});await furnishing.getByRole('button',{name:'Close furnishing',exact:true}).click()
 await approvalEvidence.fill('Synthetic replacement W-2 review');await approval.getByRole('checkbox').check();await h.pool.query('UPDATE payroll_run_employee SET posttax_deduction_cents=posttax_deduction_cents+1 WHERE payroll_run_id=$1',[run.id]);await approve.click();await expect(approval.getByRole('alert')).toContainText('W-2 draft changed');await expect(approve).toBeDisabled();await prepare.click();await expect(approval).toContainText('STALE · W-2 approval');await expect(approve).toHaveCount(0);await h.pool.query('UPDATE payroll_run_employee SET posttax_deduction_cents=posttax_deduction_cents-1 WHERE payroll_run_id=$1',[run.id]);await prepare.click();await approvalEvidence.fill('Synthetic replacement approved W-2 evidence');await approval.getByRole('checkbox').check();await approve.click();await expect(approval).toContainText('SUPERSEDED · W-2 approval');await page.setViewportSize({width:390,height:1800});await approval.screenshot({path:'/tmp/payroll-w2-approval-mobile.png'});await page.setViewportSize({width:390,height:1200})
 const newerArticle=approval.locator('article').first(),newerDownload=page.waitForEvent('download',{timeout:45000});await newerArticle.getByRole('button',{name:'Download approved employee copies',exact:true}).click();expect(await (await newerDownload).failure()).toBeNull();await newerArticle.getByRole('button',{name:/View furnishing for approval/}).click()
 const newerFurnishing=newerArticle.getByRole('region',{name:/Furnishing for approval/});await newerFurnishing.getByLabel('Actual event',{exact:true}).selectOption('HAND_DELIVERED');await newerFurnishing.getByLabel('Event date and time (your local time)',{exact:true}).fill(await page.evaluate(()=>{const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,19).replace(/:00$/,'')}));await newerFurnishing.getByLabel('Furnishing evidence reference',{exact:true}).fill('Synthetic replacement employee handoff evidence');await newerFurnishing.getByRole('checkbox').check();await newerFurnishing.getByRole('button',{name:'Record furnishing event',exact:true}).click();await expect(newerFurnishing.getByRole('status')).toHaveText('Furnishing event recorded.');await newerFurnishing.getByRole('button',{name:'Close furnishing',exact:true}).click()
 const olderArticle=approval.locator(':scope > article').last();await olderArticle.getByRole('button',{name:/View furnishing for approval/}).click();const oldFurnishing=olderArticle.getByRole('region',{name:/Furnishing for approval/}),replacement=oldFurnishing.getByRole('region',{name:'Replacement furnishing',exact:true}),linkReplacement=replacement.getByRole('button',{name:'Link replacement furnishing',exact:true});await expect(linkReplacement).toBeDisabled();await replacement.getByLabel('Replacement furnishing evidence',{exact:true}).selectOption({index:1});await replacement.getByLabel('Replacement verification reference',{exact:true}).fill('Synthetic verified replacement resolves old return');await replacement.getByRole('checkbox').check();await replacement.getByLabel('Replacement verification reference',{exact:true}).fill('Synthetic final replacement resolution evidence');await expect(linkReplacement).toBeDisabled();await replacement.getByRole('checkbox').check();await linkReplacement.click();await expect(replacement).toContainText('CURRENT · Replacement packet');await olderArticle.getByRole('button',{name:/Review portal publication for approval/}).click();const replacedPublication=olderArticle.getByRole('region',{name:/Portal publication for approval/});await expect(replacedPublication).toContainText('Published · Paper furnishing recorded');await expect(replacedPublication).toContainText('Verified replacement packet');await replacedPublication.screenshot({path:'/tmp/payroll-w2-replacement-notice-mobile.png'});await replacedPublication.getByRole('button',{name:'Close publication',exact:true}).click();await expect(oldFurnishing).not.toContainText('The payroll follow-up alert stays open');await page.setViewportSize({width:390,height:2000});await replacement.screenshot({path:'/tmp/payroll-return-resolution-mobile.png'});await oldFurnishing.getByRole('button',{name:'Close furnishing',exact:true}).click()
 await page.setViewportSize({width:390,height:2200});await view.screenshot({path:'/tmp/payroll-year-end-preparation-mobile.png'});await page.setViewportSize({width:390,height:1200})
 await h.pool.query('UPDATE payroll_run_employee SET federal_income_tax_cents=NULL WHERE payroll_run_id=$1',[run.id]);await prepare.click();await expect(view).toContainText('Source reconciliation required.');await expect(draft).toContainText('Draft unavailable');await expect(draft).not.toContainText('6 · Medicare tax withheld');await expect(view).toContainText('Federal wage input: Unavailable');await expect(view).toContainText('Federal withholding: Unavailable');await expect(view).toContainText('Combined Medicare (W-2 box 6 input) withholding: Unavailable');await expect(view).not.toContainText('Federal wage input: $200.00')
 const savedButton=review.getByRole('button',{name:/View saved inputs for review/}).first();await savedButton.click();const savedInputs=review.getByRole('region',{name:/Saved inputs for review/});await expect(savedInputs).toContainText('Federal wage input: $200.00');await expect(savedInputs).toContainText('Historical review snapshot');await expect(savedInputs).not.toContainText('123456789');await savedInputs.screenshot({path:'/tmp/payroll-annual-snapshot-mobile.png'});await savedInputs.getByRole('button',{name:'Close saved inputs',exact:true}).click();await expect(savedInputs).toHaveCount(0)
 await page.route('**/api/admin/payroll/employees/*/annual-input-review/*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Synthetic snapshot unavailable'})}));await savedButton.click();await expect(review.getByRole('alert')).toHaveText('Synthetic snapshot unavailable');await expect(savedInputs).toHaveCount(0)
 await page.route('**/api/admin/payroll/reports/year-end-preparation?year=2026',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Synthetic preparation outage'})}))
 await prepare.click();await expect(view.getByRole('alert')).toHaveText('Synthetic preparation outage');await expect(view).not.toContainText('Identifier ending 6789');await expect(view).not.toContainText('Social Security withholding:')
 await page.route('**/api/payroll/employee/**',async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
 await page.addInitScript(()=>sessionStorage.setItem('vortex_payroll_employee_session_v1','monthly-benefits-session'));await page.goto('/tests/support/payroll.html?employee');await page.getByRole('button',{name:'Pay statements',exact:true}).click();const documents=page.getByRole('region',{name:'My W-2 documents',exact:true});await documents.getByRole('button',{name:'Load my W-2 documents',exact:true}).click();await expect(documents).toContainText('2026 W-2 employee copies')
 const employeeDownload=page.waitForEvent('download');await documents.getByRole('button',{name:/Download W-2 document/}).click();const employeeFile=await employeeDownload;expect(await readFile((await employeeFile.path())!)).toEqual(await readFile((await file.path())!));await documents.screenshot({path:'/tmp/payroll-employee-w2-documents-mobile.png'})
 await page.route('**/api/payroll/employee/w2-documents',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Synthetic documents unavailable'})}));await documents.getByRole('button',{name:'Load my W-2 documents',exact:true}).click();await expect(documents.getByRole('alert')).toHaveText('Synthetic documents unavailable');await expect(documents.locator('article')).toHaveCount(0)
 }finally{await page.unrouteAll({behavior:'wait'});await page.close();await h.close();if(old===undefined)delete process.env.PAYROLL_DOCUMENT_KEY;else process.env.PAYROLL_DOCUMENT_KEY=old}
})
