import {test,expect} from '@playwright/test'
import {carrierRemittanceFixture} from '../../backend/payroll/testing/carrierRemittanceFixture.js'
test('admin retains alternate delivery with safe retry and retracts after changed bank evidence',async({page})=>{
 test.setTimeout(90000);test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const prior=process.env.PAYROLL_DOCUMENT_KEY;process.env.PAYROLL_DOCUMENT_KEY='31'.repeat(32)
 const f=await carrierRemittanceFixture(),{h}=f;f.setNow('2026-09-20T12:00:00Z');let loseResponse=true
 try{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url()),response=await route.fetch({url:`${h.url}${u.pathname}${u.search}`});if(loseResponse&&u.pathname.endsWith('/alternate-delivery')&&route.request().method()==='POST'&&response.ok()){loseResponse=false;return route.fulfill({status:503,json:{success:false,message:'Synthetic lost delivery review response'}})}await route.fulfill({response})})
  await page.setViewportSize({width:390,height:1200});await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Reports & QuickBooks',exact:true}).click()
  const invoices=page.getByRole('region',{name:'Carrier invoice reconciliation',exact:true});await invoices.getByLabel('Carrier coverage month',{exact:true}).fill('2026-09');await invoices.getByRole('button',{name:'Load carrier invoices',exact:true}).click();await invoices.getByText('Prepare carrier payment',{exact:true}).click();await invoices.getByText('Alternate remittance delivery',{exact:true}).click()
  const panel=invoices.getByRole('region',{name:'Alternate remittance delivery',exact:true});await panel.getByRole('button',{name:'Review alternate delivery evidence',exact:true}).click();await expect(panel).toContainText('Delivery evidence: NOT RECORDED')
  await panel.getByRole('textbox',{name:'Verified recipient',exact:true}).fill('Carrier remittance team');await panel.getByRole('textbox',{name:'Verified delivery destination',exact:true}).fill('Synthetic carrier portal payment inbox');await panel.getByLabel('Actual delivery time',{exact:true}).fill('2026-09-19T12:00');await panel.getByRole('textbox',{name:'Delivery evidence or retraction reference',exact:true}).fill('Synthetic carrier portal confirmed receipt of exact remittance advice');await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'Retain alternate delivery review',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('Synthetic lost delivery review response');await panel.getByRole('button',{name:'Retain alternate delivery review',exact:true}).click();await expect(panel.getByRole('status')).toContainText('Alternate delivery review retained');expect((await h.pool.query('SELECT * FROM payroll_carrier_alternate_delivery')).rowCount).toBe(1)
  await panel.getByRole('textbox',{name:'Delivery evidence or retraction reference',exact:true}).fill('Draft investigation reference preserved after changed payment evidence')
  await f.returnBank();await page.clock.fastForward(30001);await expect(panel).toContainText('Delivery evidence: EVIDENCE CHANGED');await expect(panel.getByRole('alert')).toContainText('Your draft is preserved');await expect(panel.getByRole('textbox',{name:'Delivery evidence or retraction reference',exact:true})).toHaveValue('Draft investigation reference preserved after changed payment evidence')
  await panel.getByRole('button',{name:'Reload alternate delivery evidence',exact:true}).click();await expect(panel.getByRole('combobox',{name:'Delivery review action',exact:true})).toHaveValue('RETRACT');await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'Retain alternate delivery review',exact:true}).click();await expect(panel).toContainText('Delivery evidence: RETRACTED');await expect(panel.getByRole('button',{name:'Retain alternate delivery review',exact:true})).toHaveCount(0)
  await panel.getByText('Alternate delivery history',{exact:true}).click();await expect(panel).toContainText('Revision 1');await expect(panel).toContainText('Revision 2');await expect(panel).toContainText('Synthetic carrier portal confirmed receipt');await panel.screenshot({path:'/tmp/payroll-carrier-alternate-mobile.png'});expect(errors).toEqual([])
 }finally{await page.unrouteAll({behavior:'wait'}).catch(()=>{});await page.close().catch(()=>{});await h.close();if(prior===undefined)delete process.env.PAYROLL_DOCUMENT_KEY;else process.env.PAYROLL_DOCUMENT_KEY=prior}
})
