import {test,expect} from '@playwright/test'
import {randomBytes,randomUUID} from 'node:crypto'
import {createHarness} from '../../backend/payroll/testing/harness.js'
import {createRetirementSftpServer} from '../../backend/payroll/testing/retirementSftpServer.js'
import {retirementDestinationProvider} from '../../backend/payroll/testing/retirementDestinationProvider.js'
import {retirementReceiptBindingFixture} from '../../backend/payroll/testing/retirementReceiptBindingFixture.js'
import {transferRetirementAllocation,verifyRetirementSftpConnection} from '../../backend/payroll/retirementSftpTransport.js'
test('admin retains receipt location after a lost save and suspends it without credentials',async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated database');test.setTimeout(90000)
 const old=process.env.PAYROLL_DOCUMENT_KEY;process.env.PAYROLL_DOCUMENT_KEY=randomBytes(32).toString('hex')
 const server=await createRetirementSftpServer(),provider=retirementDestinationProvider(),h=await createHarness({paymentFetcher:provider.fetcher,remittanceNow:()=>new Date('2026-09-19T12:00:00Z'),retirementNow:()=>new Date('2026-09-11T12:00:00Z'),retirementSftpVerifier:c=>verifyRetirementSftpConnection(c,server.options),retirementAllocationTransfer:(c,file,options)=>transferRetirementAllocation(c,file,{...server.options,...options})}),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let lost=true
 try{
  const f=await retirementReceiptBindingFixture(h,server.config),auths=server.state.auths
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url()),r=await route.fetch({url:`${h.url}${u.pathname}${u.search}`});if(u.pathname.endsWith('/receipt-binding')&&route.request().method()==='POST'&&r.ok()&&lost){lost=false;await route.fulfill({status:503,json:{success:false,message:'Synthetic lost receipt location response'}})}else await route.fulfill({response:r})})
  await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Employer setup',exact:true}).click();await page.getByRole('button',{name:'Load retirement plan history',exact:true}).click();await page.getByRole('button',{name:'Load allocation delivery history',exact:true}).click()
  const panel=page.getByRole('region',{name:`Retirement receipt location ${f.allocationId}`,exact:true});await panel.getByRole('button',{name:'Load receipt location history',exact:true}).click();await expect(panel).toContainText('Receipt location: REVIEW REQUIRED')
  await panel.getByRole('combobox',{name:'Retained receipt interpretation contract',exact:true}).selectOption(f.bindingBody.contractId);await panel.getByRole('textbox',{name:'Receipt directory',exact:true}).fill(f.bindingBody.directory);await panel.getByRole('textbox',{name:'Receipt CSV filename',exact:true}).fill(f.bindingBody.fileName);await panel.getByRole('textbox',{name:'Receipt location review reference',exact:true}).fill(f.bindingBody.reference)
  await panel.getByRole('checkbox',{name:'I verified this receipt path and retained contract refer to the exact original allocation file and its participant amounts.',exact:true}).check();await panel.getByRole('checkbox',{name:'I confirm this receipt location action and reviewed evidence.',exact:true}).check();await panel.getByRole('button',{name:'Save receipt location',exact:true}).click();await expect(panel).toContainText('Synthetic lost receipt location response');await panel.getByRole('button',{name:'Retry original receipt location action',exact:true}).click();await expect(panel).toContainText('Receipt location: BOUND · revision 1')
  expect((await f.api(f.bindingPath)).history).toHaveLength(1);expect(server.state.auths).toBe(auths)
  await f.api(f.setupPath,{action:'SUSPEND',expectedRevision:1,requestKey:randomUUID(),reference:'Suspend new allocation transmission while retaining original receipt credentials',confirmed:true});await panel.getByRole('button',{name:'Load receipt location history',exact:true}).click();await expect(panel).toContainText('Receipt location: BOUND')
  delete process.env.PAYROLL_DOCUMENT_KEY;await panel.getByRole('combobox',{name:'Receipt location action',exact:true}).selectOption('SUSPEND');await panel.getByRole('textbox',{name:'Receipt location review reference',exact:true}).fill('Suspend receipt interpretation while provider receipt naming is independently reviewed');await panel.getByRole('checkbox',{name:'I confirm this receipt location action and reviewed evidence.',exact:true}).check();await panel.getByRole('button',{name:'Suspend receipt location',exact:true}).click();await expect(panel).toContainText('Receipt location: SUSPENDED · revision 2')
  await page.setViewportSize({width:390,height:1100});await panel.screenshot({path:'/tmp/payroll-retirement-receipt-binding-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(server.state.auths).toBe(auths);expect(errors).toEqual([])
 }finally{try{if(!page.isClosed()){await page.unrouteAll({behavior:'ignoreErrors'});await page.close()}}finally{await h.close();await server.close();if(old===undefined)delete process.env.PAYROLL_DOCUMENT_KEY;else process.env.PAYROLL_DOCUMENT_KEY=old}}
})
