import {test,expect} from '@playwright/test'
import {randomUUID} from 'node:crypto'
import {createHarness} from '../../backend/payroll/testing/harness.js'
import {monthlyBenefitsFixture} from '../../backend/payroll/testing/monthlyBenefitsFixture.js'
test('admin verifies no-pay coverage, recovers review retries and links the current review to an invoice',async({page})=>{
 test.setTimeout(90000);test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness(),{api}=await monthlyBenefitsFixture(h);let loseResponse=true,failInitialRead=true
 try{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());if(failInitialRead&&u.pathname.endsWith('/benefit-coverage')&&route.request().method()==='GET'){failInitialRead=false;return route.fulfill({status:503,json:{success:false,message:'Synthetic initial coverage read failure'}})}const response=await route.fetch({url:`${h.url}${u.pathname}${u.search}`});if(loseResponse&&u.pathname.endsWith('/benefit-coverage')&&route.request().method()==='POST'&&response.ok()){loseResponse=false;return route.fulfill({status:503,json:{success:false,message:'Synthetic lost coverage review response'}})}await route.fulfill({response})})
  await page.setViewportSize({width:390,height:1200});await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Reports & QuickBooks',exact:true}).click()
  const ledger=page.getByRole('region',{name:'Monthly benefit coverage ledger',exact:true});await ledger.getByLabel('Benefit coverage month',{exact:true}).fill('2026-09');await ledger.getByRole('button',{name:'Load monthly coverage',exact:true}).click();await expect(ledger.getByRole('alert')).toHaveText('Synthetic initial coverage read failure');await page.clock.fastForward(30001);await expect(ledger).toContainText('No finalized payroll in this month.');await expect(ledger).toContainText('Monthly Benefits · Medical')
  await ledger.getByLabel('Coverage carrier name',{exact:true}).fill('Synthetic Coverage Carrier');await ledger.getByLabel('Carrier coverage verification reference',{exact:true}).fill('Carrier confirmed active coverage before the first employee paycheck');await ledger.getByRole('checkbox').check();await ledger.getByRole('button',{name:'Retain monthly coverage review',exact:true}).click();await expect(ledger.getByRole('alert')).toHaveText('Synthetic lost coverage review response');await ledger.getByRole('button',{name:'Retain monthly coverage review',exact:true}).click();await expect(ledger.getByRole('status')).toContainText('Monthly carrier coverage review retained');expect((await h.pool.query('SELECT * FROM payroll_benefit_coverage_review')).rowCount).toBe(1)
  await ledger.getByLabel('Carrier coverage verification reference',{exact:true}).fill('Preserved draft for another review after current evidence changes')
  const row=(await api('/benefit-coverage?month=2026-09')).rows[0]
  await api('/benefit-coverage',{month:'2026-09',employeeId:row.employeeId,onboardingCycle:row.onboardingCycle,planId:row.planId,sourceFingerprint:row.sourceFingerprint,expectedRevision:1,disposition:'NOT_COVERED',carrier:'Synthetic Coverage Carrier',reference:'Second admin retained a different carrier verification',confirmed:true,requestKey:randomUUID()})
  await page.clock.fastForward(30001);await expect(ledger.getByRole('alert')).toContainText('Your draft is preserved');await expect(ledger.getByLabel('Carrier coverage verification reference',{exact:true})).toHaveValue('Preserved draft for another review after current evidence changes');await ledger.getByRole('button',{name:'Use current coverage evidence',exact:true}).click();await ledger.getByRole('checkbox').check();await ledger.getByRole('button',{name:'Retain monthly coverage review',exact:true}).click();await expect.poll(async()=>Number((await h.pool.query('SELECT max(revision) AS revision FROM payroll_benefit_coverage_review')).rows[0].revision)).toBe(3)
  const invoices=page.getByRole('region',{name:'Carrier invoice reconciliation',exact:true});await invoices.getByLabel('Carrier coverage month',{exact:true}).fill('2026-09');await invoices.getByRole('button',{name:'Load carrier invoices',exact:true}).click()
  for(const [label,value] of [['Carrier name','Synthetic Coverage Carrier'],['Carrier invoice number','NO-PAY-SEP'],['Invoice date','2026-09-01'],['Invoice due date','2026-09-30'],['Invoice total ($)','575'],['Carrier document reference','Actual synthetic carrier invoice before first employee wages'],['Coverage and amount reconciliation','Verified covered employee and dates without treating absent wages as cancelled coverage']])await invoices.getByLabel(label,{exact:true}).fill(value)
  await invoices.getByRole('checkbox',{name:/Monthly Benefits · Medical · Synthetic Coverage Carrier/}).check();await invoices.getByRole('checkbox',{name:/I matched the carrier invoice to covered employees and dates/}).check();await invoices.getByRole('button',{name:'Retain carrier invoice reconciliation',exact:true}).click();await expect(invoices.getByRole('status')).toHaveText('Carrier invoice reconciliation retained.')
  await invoices.getByText('Retained coverage evidence',{exact:true}).click();await expect(invoices).toContainText('Verified monthly coverage: Monthly Benefits · Medical · 2026-09-01 through 2026-09-30')
  await ledger.getByText('Monthly coverage review history',{exact:true}).click();await expect(ledger).toContainText('Revision 1');await expect(ledger).toContainText('Revision 3');await ledger.screenshot({path:'/tmp/payroll-benefit-coverage-ledger-mobile.png'});expect(errors).toEqual([])
 }finally{await page.unrouteAll({behavior:'wait'}).catch(()=>{});await page.close().catch(()=>{});await h.close()}
})

test('admin can retract coverage and resolve removed enrollment without an unusable form',async({page})=>{
 test.setTimeout(90000);test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness(),{api,employee}=await monthlyBenefitsFixture(h)
 try{
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
  const row=(await api('/benefit-coverage?month=2026-09')).rows[0]
  await api('/benefit-coverage',{month:row.month,employeeId:row.employeeId,onboardingCycle:row.onboardingCycle,planId:row.planId,sourceFingerprint:row.sourceFingerprint,expectedRevision:0,disposition:'COVERED',carrier:'Synthetic Coverage Carrier',coverageStart:'2026-09-01',coverageEnd:'2026-09-30',reference:'Synthetic initial carrier confirmation for retraction',confirmed:true,requestKey:randomUUID()})
  await page.setViewportSize({width:390,height:1000});await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Reports & QuickBooks',exact:true}).click()
  const ledger=page.getByRole('region',{name:'Monthly benefit coverage ledger',exact:true})
  await ledger.getByLabel('Benefit coverage month',{exact:true}).fill('2026-09');await ledger.getByRole('button',{name:'Load monthly coverage',exact:true}).click()
  await ledger.getByLabel('Monthly coverage decision',{exact:true}).selectOption('RETRACTED');await ledger.getByLabel('Carrier coverage verification reference',{exact:true}).fill('Retracting the original review pending corrected carrier evidence');await ledger.getByRole('checkbox').check();await ledger.getByRole('button',{name:'Retain monthly coverage review',exact:true}).click()
  await expect(ledger.getByLabel('Monthly coverage decision',{exact:true})).toHaveValue('COVERED');await expect(ledger.getByLabel('Actual coverage start in this month',{exact:true})).toBeVisible()
  await ledger.getByLabel('Carrier coverage verification reference',{exact:true}).fill('Corrected carrier evidence confirms this month of coverage');await ledger.getByRole('checkbox').check();await ledger.getByRole('button',{name:'Retain monthly coverage review',exact:true}).click();await expect.poll(async()=>Number((await h.pool.query('SELECT max(revision) AS revision FROM payroll_benefit_coverage_review')).rows[0].revision)).toBe(3)
  let packet=await api('/onboarding',undefined,'GET',200,true)
  packet=await api('/benefits-election',{choice:'WAIVE',signature:'Monthly Benefits',confirmed:true,displayedTerms:packet.policy.benefitsText,requestKey:'browser-coverage-waived-election',selections:[{planId:'medical',optionId:'WAIVE'}],onboardingCycle:1},'POST',200,true)
  const task=packet.tasks.find((item:{task_key:string})=>item.task_key==='PAY_REVIEW')
  await api(`/employees/${employee.id}/onboarding/${task.id}/review`,{status:'COMPLETE',note:'Corrected benefits disposition with employee waiver',paySetupFingerprint:packet.paySetup.fingerprint,benefitsReview:{disposition:'WAIVED',effectiveOn:'2026-09-01',summary:'Employee waived offered coverage for this period.',evidenceReference:'Reviewed corrected waiver and carrier records',confirmed:true}})
  await ledger.getByRole('button',{name:'Reload coverage and discard drafts',exact:true}).click();await expect(ledger).toContainText('This plan no longer has a current enrolled hiring decision.');await expect(ledger.getByLabel('Monthly coverage decision',{exact:true})).toHaveValue('RETRACTED');await expect(ledger.getByLabel('Actual coverage start in this month',{exact:true})).toHaveCount(0)
  await ledger.getByLabel('Carrier coverage verification reference',{exact:true}).fill('Retract incorrect monthly evidence following corrected employee waiver');await ledger.getByRole('checkbox').check();await ledger.getByRole('button',{name:'Retain monthly coverage review',exact:true}).click()
  await expect(ledger).toContainText('The earlier monthly review was retracted.');await expect(ledger.getByRole('button',{name:'Retain monthly coverage review',exact:true})).toHaveCount(0)
  await ledger.getByText('Monthly coverage review history',{exact:true}).click();await expect(ledger).toContainText('Revision 4');await expect(ledger).toContainText('Synthetic initial carrier confirmation for retraction');await ledger.screenshot({path:'/tmp/payroll-coverage-retraction-mobile.png'})
 }finally{await page.unrouteAll({behavior:'wait'}).catch(()=>{});await page.close().catch(()=>{});await h.close()}
})
