import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
for(const aggregate of [false,true])test(`admin finalizes a standalone bonus with ${aggregate?'aggregate':'flat'} withholding`,async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness()
 try{
  const api=async(path:string,body:unknown,method='POST')=>{const r=await fetch(`${h.url}/api/admin/payroll${path}`,{method,headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:JSON.stringify(body)});expect(r.ok).toBeTruthy();return (await r.json()).data}
  await api('/settings',{legalBusinessName:'Bonus Browser Fixture',businessAddress:'123 Test Street',businessPhone:'5550100000'},'PATCH')
  await api('/employer-taxes',{futaRatePercent:0.6,mdUiRatePercent:2.6,source:'Synthetic employer notice',confirmed:true},'PATCH')
  const e=await api('/employees',{employeeNumber:'BONUS-BROWSER',legalFirstName:'Former',legalLastName:'Bonus',hireDate:'2026-08-03',hourlyRateCents:2500})
  await h.pool.query("UPDATE payroll_employee SET employment_status='TERMINATED',termination_date='2026-08-08',w4_status='COMPLETE',state_withholding_status='COMPLETE' WHERE id=$1",[e.id])
  await api(`/employees/${e.id}/tax-elections`,{confirmed:true,sourceNote:'Synthetic signed tax elections',federal:{filingStatus:'SINGLE'},maryland:{filingStatus:'SINGLE',localRate:3.2,exemptions:1}},'PATCH')
  const p=(await h.pool.query("INSERT INTO payroll_pay_period(facility_id,period_start,period_end,pay_date,frequency,status) VALUES(1,'2026-08-03','2026-08-09','2026-08-14','WEEKLY','PAID') RETURNING id")).rows[0]
  const original=(await h.pool.query("INSERT INTO payroll_run(facility_id,pay_period_id,status,payment_date,payment_confirmation_reference,calculation_snapshot) VALUES(1,$1,'FINALIZED','2026-08-14','SYNTHETIC-REGULAR-PAY',$2) RETURNING id",[p.id,{employees:[{employeeId:e.id,grossPayCents:aggregate?10000:100000,payItems:[]}]}])).rows[0]
  await h.pool.query('INSERT INTO payroll_run_employee(payroll_run_id,employee_id,regular_pay_cents,federal_income_tax_cents,withholding_verified_at) VALUES($1,$2,$3,$4,now())',[original.id,e.id,aggregate?10000:100000,aggregate?0:10000])
  await api('/runs/preview',{payPeriodId:p.id})
  await h.pool.query("UPDATE payroll_compliance_task SET status='COMPLETE' WHERE facility_id=1")
  if(aggregate)await h.pool.query("INSERT INTO payroll_pay_period(facility_id,period_start,period_end,pay_date,frequency) VALUES(1,'2026-08-10','2026-08-16','2026-08-21','WEEKLY')")
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Payroll runs',exact:true}).click()
  const form=page.getByRole('region',{name:'Standalone annual bonus',exact:true})
  await form.getByRole('combobox',{name:'Bonus employee',exact:true}).selectOption(String(e.id))
  await form.getByRole('combobox',{name:'Bonus processing period',exact:true}).selectOption(String(p.id))
  await form.getByLabel('Bonus payment date',{exact:true}).fill(aggregate?'2026-08-15':'2026-09-09')
  await form.getByLabel('Standalone bonus amount ($)',{exact:true}).fill('100')
  await form.getByLabel('Bonus decision evidence',{exact:true}).fill('Synthetic discretionary bonus without prior promise')
  await form.getByLabel('Complete payment-history evidence',{exact:true}).fill('Synthetic complete employer payment history reconciliation')
  if(aggregate)await form.getByRole('combobox',{name:'Bonus federal withholding method',exact:true}).selectOption('AGGREGATE')
  for(const checkbox of await form.getByRole('checkbox').all())await checkbox.check()
  await form.getByRole('button',{name:'Calculate standalone bonus',exact:true}).click()
  await expect(form.getByText(aggregate?'Bonus net: $82.65':'Bonus net: $60.65',{exact:true})).toBeVisible()
  await expect(form.getByText(aggregate?'Federal withholding: $0.00':'Federal withholding: $22.00',{exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:2200});await form.scrollIntoViewIfNeeded();await expect(form).toBeInViewport({ratio:1});await form.screenshot({path:aggregate?'/tmp/payroll-aggregate-bonus-mobile.png':'/tmp/payroll-standalone-bonus-mobile.png'})
  await form.getByRole('button',{name:'Save standalone bonus draft',exact:true}).click()
  await expect(form.getByRole('status')).toContainText('saved')
  await page.getByRole('row').filter({hasText:'Standalone annual bonus'}).getByRole('button',{name:'Open review',exact:true}).click()
  await page.getByRole('button',{name:'Send to review',exact:true}).click()
  await page.getByRole('button',{name:'Approve run',exact:true}).click()
  await expect(page.getByLabel('Actual payment date',{exact:true})).toBeVisible()
  await page.getByLabel('External payment confirmation',{exact:true}).fill('SYNTHETIC-BONUS-BROWSER-PAYMENT')
  await page.getByRole('button',{name:'Confirm paid & finalize',exact:true}).click()
  await expect(page.getByText('Payroll finalized and employee statements saved.',{exact:true})).toBeVisible()
  expect((await h.pool.query("SELECT status FROM payroll_run WHERE run_kind='OFF_CYCLE_BONUS'")).rows[0].status).toBe('FINALIZED')
  expect(errors).toEqual([])
 }finally{await page.unrouteAll({behavior:'wait'});await page.close();await h.close()}
})

for(const aggregate of [false,true])test(`admin settles earned bonus overtime with ${aggregate?'aggregate':'flat'} withholding`,async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness()
 try{
  const api=async(path:string,body:unknown,method='POST')=>{const r=await fetch(`${h.url}/api/admin/payroll${path}`,{method,headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:JSON.stringify(body)});expect(r.ok).toBeTruthy();return (await r.json()).data}
  await api('/settings',{legalBusinessName:'Bonus Browser Fixture',businessAddress:'123 Test Street',businessPhone:'5550100000'},'PATCH')
  await api('/employer-taxes',{futaRatePercent:0.6,mdUiRatePercent:2.6,source:'Synthetic employer notice',confirmed:true},'PATCH')
  const e=await api('/employees',{employeeNumber:'BONUS-BROWSER',legalFirstName:'Former',legalLastName:'Bonus',hireDate:'2026-08-03',hourlyRateCents:2500})
  await h.pool.query("UPDATE payroll_employee SET employment_status='ACTIVE',w4_status='COMPLETE',state_withholding_status='COMPLETE' WHERE id=$1",[e.id])
  await api(`/employees/${e.id}/tax-elections`,{confirmed:true,sourceNote:'Synthetic signed tax elections',federal:{filingStatus:'SINGLE'},maryland:{filingStatus:'SINGLE',localRate:3.2,exemptions:1}},'PATCH')
  const p=(await h.pool.query("INSERT INTO payroll_pay_period(facility_id,period_start,period_end,pay_date,frequency) VALUES(1,'2026-08-03','2026-08-09','2026-08-14','WEEKLY') RETURNING id")).rows[0]
  for(let i=3;i<=8;i++)await h.pool.query("INSERT INTO payroll_time_entry(facility_id,employee_id,clock_in,clock_out,source,status) VALUES(1,$1,$2,$3,'ADMIN','APPROVED')",[e.id,`2026-08-0${i}T12:00:00Z`,`2026-08-0${i}T22:00:00Z`])
  await api('/runs/preview',{payPeriodId:p.id})
  await h.pool.query("UPDATE payroll_compliance_task SET status='COMPLETE' WHERE facility_id=1")
  const original=await api('/runs',{payPeriodId:p.id})
  await api(`/runs/${original.id}/status`,{status:'REVIEW'},'PATCH')
  await api(`/runs/${original.id}/status`,{status:'APPROVED'},'PATCH')
  await api(`/runs/${original.id}/finalize`,{paymentDate:'2026-08-14',paymentConfirmationReference:'SYNTHETIC-ORIGINAL-WAGES'})
  await h.pool.query("UPDATE payroll_employee SET employment_status='TERMINATED',termination_date='2026-08-08' WHERE id=$1",[e.id])
  await api('/runs/preview',{payPeriodId:p.id})
  await h.pool.query("UPDATE payroll_compliance_task SET status='COMPLETE' WHERE facility_id=1")
  if(aggregate)await h.pool.query("INSERT INTO payroll_pay_period(facility_id,period_start,period_end,pay_date,frequency) VALUES(1,'2026-08-10','2026-08-16','2026-08-21','WEEKLY')")
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Payroll runs',exact:true}).click()
  const form=page.getByRole('region',{name:'Standalone annual bonus',exact:true})
  await form.getByRole('combobox',{name:'Bonus employee',exact:true}).selectOption(String(e.id))
  await form.getByRole('combobox',{name:'Bonus processing period',exact:true}).selectOption(String(p.id))
  await form.getByLabel('Bonus payment date',{exact:true}).fill(aggregate?'2026-08-15':'2026-09-09')
  await form.getByLabel('Standalone bonus amount ($)',{exact:true}).fill('100')
  await form.getByLabel('Bonus decision evidence',{exact:true}).fill('Synthetic promised bonus allocated by earned hours')
  await form.getByLabel('Complete payment-history evidence',{exact:true}).fill('Synthetic complete employer payment history reconciliation')
  await form.getByRole('combobox',{name:'Standalone bonus classification',exact:true}).selectOption('NONDISCRETIONARY')
  await form.getByLabel('Bonus earning start',{exact:true}).fill('2026-08-03')
  await form.getByLabel('Bonus earning end',{exact:true}).fill('2026-08-03')
  await form.getByRole('checkbox',{name:'I verified that allocating this bonus in proportion to earned hours matches its agreement.'}).check()
  await form.getByRole('button',{name:'Calculate bonus overtime',exact:true}).click()
  await expect(form.getByText('Additional bonus overtime: $16.67',{exact:true})).toBeVisible()
  if(aggregate)await form.getByRole('combobox',{name:'Bonus federal withholding method',exact:true}).selectOption('AGGREGATE')
  for(const checkbox of await form.getByRole('checkbox').all())await checkbox.check()
  await form.getByRole('button',{name:'Calculate standalone bonus',exact:true}).click()
  await expect(form.getByText('Bonus gross: $116.67',{exact:true})).toBeVisible()
  await expect(form.getByText('Federal withholding: $25.67',{exact:true})).toBeVisible()
  await expect(form.getByText('Maryland withholding: Needs verified calculation',{exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:2600});await form.scrollIntoViewIfNeeded();await expect(form).toBeInViewport({ratio:1});await form.screenshot({path:aggregate?'/tmp/payroll-aggregate-earned-mobile.png':'/tmp/payroll-earned-standalone-mobile.png'})
  await form.getByRole('button',{name:'Save standalone bonus draft',exact:true}).click()
  await expect(form.getByText(/Bonus run .* saved/)).toBeVisible()
  await page.getByRole('row').filter({hasText:'Standalone annual bonus'}).getByRole('button',{name:'Open review',exact:true}).click()
  await page.getByRole('button',{name:'Send to review',exact:true}).click()
  await page.getByLabel('Federal withholding ($)',{exact:true}).fill('25.67')
  await page.getByLabel('Maryland withholding ($)',{exact:true}).fill('11.00')
  await page.getByLabel('Professional/table source note',{exact:true}).fill('Synthetic professional bonus and overtime worksheet')
  await page.getByRole('checkbox',{name:/I confirm these values came from a payroll professional/}).check()
  await page.getByRole('button',{name:'Record verified withholding',exact:true}).click()
  await page.getByRole('button',{name:'Approve run',exact:true}).click()
  await expect(page.getByLabel('Actual payment date',{exact:true})).toBeVisible()
  await page.getByLabel('External payment confirmation',{exact:true}).fill('SYNTHETIC-BONUS-BROWSER-PAYMENT')
  await page.getByRole('button',{name:'Confirm paid & finalize',exact:true}).click()
  await expect(page.getByText('Payroll finalized and employee statements saved.',{exact:true})).toBeVisible()
  expect((await h.pool.query("SELECT status FROM payroll_run WHERE run_kind='OFF_CYCLE_BONUS'")).rows[0].status).toBe('FINALIZED')
  expect(errors).toEqual([])
 }finally{await page.unrouteAll({behavior:'wait'});await page.close();await h.close()}
})
