import {test,expect} from '@playwright/test'
import {carrierRemittanceReturnFixture} from '../../backend/payroll/testing/carrierRemittanceReturnFixture.js'
test('admin resolves a carrier return, authorizes a replacement and retains both histories',async({page})=>{
 test.setTimeout(90000);test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const prior=process.env.PAYROLL_DOCUMENT_KEY;process.env.PAYROLL_DOCUMENT_KEY='31'.repeat(32)
 const f=await carrierRemittanceReturnFixture(),{h}=f;let loseReviewResponse=true
 try{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url()),response=await route.fetch({url:`${h.url}${u.pathname}${u.search}`});if(loseReviewResponse&&u.pathname.endsWith('/return-review')&&route.request().method()==='POST'&&response.ok()){loseReviewResponse=false;return route.fulfill({status:503,json:{success:false,message:'Synthetic lost review response'}})}await route.fulfill({response})})
  await page.setViewportSize({width:390,height:1200});await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Reports & QuickBooks',exact:true}).click()
  const invoices=page.getByRole('region',{name:'Carrier invoice reconciliation',exact:true});await invoices.getByLabel('Carrier coverage month',{exact:true}).fill('2026-09');await invoices.getByRole('button',{name:'Load carrier invoices',exact:true}).click();await invoices.getByText('Prepare carrier payment',{exact:true}).click();await invoices.getByText('Remittance delivery authorization',{exact:true}).click()
  const panel=invoices.getByRole('region',{name:'Carrier remittance delivery review',exact:true});await panel.getByRole('button',{name:'Load remittance delivery history',exact:true}).click();await expect(panel).toContainText('Notice delivery needs review — provider return')
  await panel.getByText('Review returned notice',{exact:true}).click();const review=panel.getByRole('region',{name:'Carrier returned notice review',exact:true});await review.getByRole('button',{name:'Preview return resolution',exact:true}).click();await expect(review.getByRole('alert')).toContainText('fresh carrier contact review')
  await invoices.getByText('Carrier remittance recipient',{exact:true}).click();const contact=invoices.getByRole('region',{name:'Carrier remittance recipient review',exact:true});await contact.getByRole('button',{name:'Load carrier recipient',exact:true}).click();await contact.getByLabel('Remittance contact email',{exact:true}).fill('corrected@example.test');await contact.getByLabel('Recipient verification reference',{exact:true}).fill('Called carrier after bounce and verified corrected contact request');await contact.getByRole('checkbox').check();await contact.getByRole('button',{name:'Save carrier recipient review',exact:true}).click();await expect(contact.getByRole('status')).toHaveText('Recipient review retained.')
  await review.getByRole('button',{name:'Preview return resolution',exact:true}).click();await expect(review).toContainText('corrected@example.test');await review.getByLabel('Return investigation and carrier request reference',{exact:true}).fill('Carrier confirmed corrected address and requested remittance after investigation')
  await page.clock.fastForward(30001);await expect(review.getByLabel('Return investigation and carrier request reference',{exact:true})).toHaveValue('Carrier confirmed corrected address and requested remittance after investigation')
  await review.getByLabel('The carrier requested remittance delivery to this reviewed address after the return was investigated.',{exact:true}).check();await review.getByLabel('I confirm this return resolution and retire the original notice before a separate replacement authorization.',{exact:true}).check()
  await review.getByRole('button',{name:'Retain return resolution',exact:true}).click();await expect(review.getByRole('alert')).toHaveText('Synthetic lost review response');await review.getByRole('button',{name:'Retain return resolution',exact:true}).click();await expect(panel).toContainText('Original notice retired — replacement review retained');expect((await h.pool.query('SELECT * FROM payroll_carrier_remittance_return_review')).rowCount).toBe(1);expect(f.sent.length).toBe(1)
  await panel.getByRole('button',{name:'Preview delivery notice',exact:true}).click();const authorization=panel.getByRole('group',{name:'Notice to authorize',exact:true});await expect(authorization).toContainText('corrected@example.test');await authorization.getByLabel('Delivery authorization reference',{exact:true}).fill('Reviewed exact replacement remittance notice for corrected carrier contact');await authorization.getByRole('checkbox').check();await authorization.getByRole('button',{name:'Authorize remittance delivery',exact:true}).click()
  await expect(panel.getByRole('status')).toHaveText('Notice authorization retained.');await expect(panel).toContainText('Notice authorized — pending delivery');await f.sweep();await page.clock.fastForward(30001);await expect(panel).toContainText('Notice accepted by email provider');expect(f.sent.length).toBe(2);expect(f.sent[1].to).toBe('corrected@example.test')
  await panel.getByText('Return resolution history',{exact:true}).click();await expect(panel).toContainText('Carrier confirmed corrected address and requested remittance after investigation');await panel.screenshot({path:'/tmp/payroll-carrier-remittance-return-review-mobile.png'});expect(errors).toEqual([])
 }finally{await page.unrouteAll({behavior:'wait'}).catch(()=>{});await page.close().catch(()=>{});await h.close();if(prior===undefined)delete process.env.PAYROLL_DOCUMENT_KEY;else process.env.PAYROLL_DOCUMENT_KEY=prior}
})
