import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
test('admin sees overdue final payroll and opens the matching period',async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness()
 try{
  const r=await fetch(`${h.url}/api/admin/payroll/employees`,{method:'POST',headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:JSON.stringify({employeeNumber:'FINAL-BROWSER',legalFirstName:'Final',legalLastName:'Browser',hireDate:'2026-08-03',hourlyRateCents:2500})});expect(r.status).toBe(201);const e=(await r.json()).data
  await h.pool.query("UPDATE payroll_employee SET employment_status='TERMINATED',termination_date='2026-08-08' WHERE id=$1",[e.id])
  const period=(await h.pool.query("INSERT INTO payroll_pay_period(facility_id,period_start,period_end,pay_date,frequency) VALUES(1,'2026-08-03','2026-08-09','2026-08-14','WEEKLY') RETURNING id")).rows[0]
  await h.pool.query("INSERT INTO payroll_leave_transaction(facility_id,employee_id,leave_type,transaction_date,minutes,reason) VALUES(1,$1,'PTO','2026-08-01',480,'Synthetic accrued vacation')",[e.id])
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const url=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${url.pathname}${url.search}`})})})
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'People & onboarding',exact:true}).click()
  const history=page.getByRole('region',{name:'Employment history',exact:true})
  await expect(history.getByText('2026-08-03 through 2026-08-08',{exact:true})).toBeVisible()
  const review=page.getByRole('region',{name:'Final-period payroll',exact:true})
  await expect(review.getByText('Final-period payroll confirmation is overdue',{exact:true})).toBeVisible()
  await expect(review.getByText('2026-08-14',{exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:1000});await review.scrollIntoViewIfNeeded();await expect(review).toBeInViewport({ratio:1});await review.screenshot({path:'/tmp/payroll-final-pay-mobile.png'})
  await history.scrollIntoViewIfNeeded();await expect(history).toBeInViewport({ratio:1});await history.screenshot({path:'/tmp/payroll-employment-history-mobile.png'})
  const rehire=page.getByRole('region',{name:'Rehire preparation',exact:true})
  await rehire.getByLabel('Proposed rehire date',{exact:true}).fill('2099-09-07')
  await rehire.getByRole('button',{name:'Review rehire records',exact:true}).click()
  await expect(rehire.getByText('The prior final-period payroll has not been finalized.',{exact:true})).toBeVisible()
  await expect(rehire.getByText('$25.00/hour',{exact:true})).toBeVisible()
  await expect(rehire.getByText('PTO: 8 hours',{exact:true})).toBeVisible()
  await expect(rehire.getByText('Retained under this employee identity: 1 employment period and 13 onboarding steps.',{exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:1200});await rehire.scrollIntoViewIfNeeded();await expect(rehire).toBeInViewport({ratio:1});await rehire.screenshot({path:'/tmp/payroll-rehire-review-mobile.png'})
  await rehire.getByLabel('Proposed rehire date',{exact:true}).fill('2099-09-08')
  await expect(rehire.getByRole('status')).toHaveCount(0)
  expect((await h.pool.query('SELECT employment_status FROM payroll_employee WHERE id=$1',[e.id])).rows[0].employment_status).toBe('TERMINATED')
  const payout=page.getByRole('region',{name:'Unused PTO payout',exact:true})
  await payout.getByLabel('PTO minutes to pay out',{exact:true}).fill('450')
  await payout.getByLabel('Reviewed PTO payout rate ($/hour)',{exact:true}).fill('25.55')
  await payout.getByLabel('PTO payout policy evidence',{exact:true}).fill('Synthetic vacation payout policy communicated at hiring')
  await payout.getByLabel('I verified the communicated payout policy and applicable rate.',{exact:true}).check()
  await payout.getByLabel('This pays unused vacation/PTO and is not an attendance bonus.',{exact:true}).check()
  await payout.getByRole('button',{name:'Calculate PTO payout',exact:true}).click()
  await expect(payout.getByText('PTO payout: $191.63',{exact:true})).toBeVisible()
  await expect(payout.getByText('7.5 hours from 8 available hours. Remaining after payout: 0.5 hours.',{exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:1400});await payout.scrollIntoViewIfNeeded();await expect(payout).toBeInViewport({ratio:1});await payout.screenshot({path:'/tmp/payroll-pto-payout-mobile.png'})
  await payout.getByLabel('PTO minutes to pay out',{exact:true}).fill('480');await expect(payout.getByRole('status')).toHaveCount(0)
  expect((await h.pool.query("SELECT SUM(minutes)::int n FROM payroll_leave_transaction WHERE employee_id=$1 AND leave_type='PTO'",[e.id])).rows[0].n).toBe(480)
  await payout.getByLabel('PTO minutes to pay out',{exact:true}).fill('450')
  await payout.getByRole('button',{name:'Calculate PTO payout',exact:true}).click()
  await payout.getByRole('combobox',{name:'PTO payout payroll period',exact:true}).selectOption(String(period.id))
  await payout.getByRole('button',{name:'Reserve PTO payout',exact:true}).click()
  await expect(payout.getByText('7.5 hours · RESERVED',{exact:true})).toBeVisible()
  await expect(review.getByText('450 PTO minutes are reserved for an unpaid payout.',{exact:true})).toBeVisible()
  const held=(await h.pool.query("SELECT id,status FROM payroll_leave_payout WHERE employee_id=$1",[e.id])).rows[0]
  expect(held.status).toBe('RESERVED')
  await review.getByRole('button',{name:'Open final payroll period',exact:true}).click()
  await page.getByRole('button',{name:'Preview payroll',exact:true}).click()
  const payoutCalculation=page.getByRole('region',{name:'PTO payout calculation review',exact:true})
  await expect(payoutCalculation.getByText(`Payout #${held.id} · 7.5 unused PTO hours at $25.55/hour · $191.63`,{exact:true})).toBeVisible()
  await payoutCalculation.scrollIntoViewIfNeeded();await expect(payoutCalculation).toBeInViewport({ratio:1})
  await payoutCalculation.screenshot({path:'/tmp/payroll-pto-calculation-mobile.png'})
  await page.getByRole('button',{name:'People & onboarding',exact:true}).click()

  await payout.getByLabel(`Cancellation reason for payout ${held.id}`,{exact:true}).fill('Synthetic revised separation payment plan')
  await payout.getByRole('button',{name:`Cancel PTO payout ${held.id}`,exact:true}).click()
  await expect(payout.getByText('7.5 hours · CANCELLED',{exact:true})).toBeVisible()
  await expect(review.getByText('450 PTO minutes are reserved for an unpaid payout.',{exact:true})).toHaveCount(0)
  expect((await h.pool.query("SELECT SUM(minutes)::int n FROM payroll_leave_transaction WHERE employee_id=$1 AND leave_type='PTO'",[e.id])).rows[0].n).toBe(480)
  await review.getByRole('button',{name:'Open final payroll period',exact:true}).click()
  await expect(page.getByRole('combobox',{name:'Pay period',exact:true})).toHaveValue(String(period.id))
  expect(errors).toEqual([])
 }finally{await h.close()}
})
