import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
test('admin previews and applies annual carryover once with explicit policy confirmation',async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated localhost payroll database')
 const h=await createHarness()
 try{
  const response=await fetch(`${h.url}/api/admin/payroll/employees`,{method:'POST',headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:JSON.stringify({employeeNumber:'YEAR-BROWSER',legalFirstName:'Annual',legalLastName:'Browser',hireDate:'2025-01-01',hourlyRateCents:2500})});expect(response.ok).toBeTruthy();const employee=(await response.json()).data
  await h.pool.query("INSERT INTO payroll_leave_transaction(facility_id,employee_id,transaction_date,minutes,reason) VALUES(1,$1,'2025-12-01',3000,'Synthetic prior accrual')",[employee.id])
  await h.pool.query("UPDATE payroll_employee SET employment_status='TERMINATED',termination_date='2026-03-31' WHERE id=$1",[employee.id])
  await h.pool.query("UPDATE payroll_employee SET employment_status='ONBOARDING',hire_date='2026-08-03',termination_date=NULL WHERE id=$1",[employee.id])
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const url=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${url.pathname}${url.search}`})})})
  await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Pay setup & leave',exact:true}).click()
  const panel=page.locator('section').filter({has:page.getByRole('heading',{name:'Open annual sick-leave year',exact:true})})
  await panel.getByLabel('Opening year',{exact:true}).fill('2026')
  await panel.getByRole('button',{name:'Preview annual leave opening',exact:true}).click()
  await expect(panel.getByText('January 1 opening balance: 40.00 hours',{exact:true})).toBeVisible()
  await expect(panel.getByRole('button',{name:'Apply annual leave opening',exact:true})).toBeDisabled()
  await panel.getByLabel('Published annual leave policy reference',{exact:true}).fill('Verified published calendar-year carryover policy')
  await panel.getByLabel('I verified the published policy and each carryover reduction or replacement grant shown above.',{exact:true}).check()
  await panel.getByRole('button',{name:'Apply annual leave opening',exact:true}).click()
  await expect(panel.getByText('Leave year 2026 opened and audited.',{exact:true})).toBeVisible()
  expect((await h.pool.query('SELECT SUM(minutes)::int AS n FROM payroll_leave_transaction WHERE employee_id=$1',[employee.id])).rows[0].n).toBe(2400)
  await panel.getByRole('button',{name:'Preview annual leave opening',exact:true}).click()
  await expect(panel.getByRole('alert')).toHaveText('This leave year has already been opened.')
  await page.setViewportSize({width:390,height:1200});await panel.scrollIntoViewIfNeeded();await expect(panel).toBeInViewport({ratio:1});await panel.screenshot({path:'/tmp/payroll-leave-year-mobile.png'})
  const recurring=page.locator('section').filter({has:page.getByRole('heading',{name:'Recurring annual leave policy',exact:true})})
  await recurring.getByText(/Leave year 2026 · opened/).click()
  await expect(recurring.getByText(/Annual Browser · prior 50.00 hours · adjustment -10.00 hours/)).toBeVisible()
  await recurring.getByLabel('First automatic opening year',{exact:true}).fill('2027')
  await recurring.getByLabel('Recurring leave policy reference',{exact:true}).fill('Verified recurring employee leave policy')
  await recurring.getByLabel('Enable automatic annual leave opening',{exact:true}).check()
  await recurring.getByLabel('I verified the published policy and authorize these settings for future annual openings.',{exact:true}).check()
  await recurring.getByRole('button',{name:'Save recurring leave policy',exact:true}).click()
  await expect(recurring.getByText('Recurring annual leave policy saved.',{exact:true})).toBeVisible()
  await page.reload();await page.getByRole('button',{name:'Pay setup & leave',exact:true}).click()
  await expect(recurring.getByText('Saved automation: enabled from 2027',{exact:true})).toBeVisible()
  await expect(recurring.getByLabel('Recurring leave policy reference',{exact:true})).toHaveValue('Verified recurring employee leave policy')
  await recurring.scrollIntoViewIfNeeded();await expect(recurring).toBeInViewport({ratio:1});await recurring.screenshot({path:'/tmp/payroll-recurring-leave-mobile.png'})
 }finally{await h.close()}
})
