import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
test('admin previews and saves a biweekly calendar and sees saved configuration after reload',async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated localhost payroll database')
 const h=await createHarness()
 try{
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const url=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${url.pathname}${url.search}`})})})
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/tests/support/payroll.html')
  await page.getByRole('button',{name:'Employer setup',exact:true}).click()
  await page.getByRole('combobox',{name:'Payroll frequency',exact:true}).selectOption('BIWEEKLY')
  await page.getByLabel('Reference period start',{exact:true}).fill('2026-01-05')
  await page.getByLabel('Calendar days after period end',{exact:true}).fill('5')
  await page.getByRole('button',{name:'Preview pay schedule',exact:true}).click()
  await expect(page.getByRole('button',{name:'Save payroll schedule',exact:true})).toBeDisabled()
  const panel=page.locator('section').filter({has:page.getByRole('heading',{name:'Payroll schedule setup',exact:true})})
  expect(await panel.locator('li').count()).toBeGreaterThanOrEqual(6)
  expect((await h.pool.query('SELECT COUNT(*)::int AS n FROM payroll_pay_period')).rows[0].n).toBe(0)
  await page.getByLabel('Schedule policy or notice reference',{exact:true}).fill('Synthetic published biweekly schedule for browser test')
  await page.getByLabel('I verified these dates against the published employee pay schedule.',{exact:true}).check()
  await page.getByRole('button',{name:'Save payroll schedule',exact:true}).click()
  await expect(page.getByText('Payroll schedule configured.',{exact:true})).toBeVisible()
  const saved=(await h.pool.query('SELECT * FROM payroll_pay_period WHERE facility_id=1')).rows
  expect(saved.length).toBeGreaterThanOrEqual(6);expect(saved.every(p=>p.frequency==='BIWEEKLY')).toBeTruthy()
  await page.reload();await page.getByRole('button',{name:'Employer setup',exact:true}).click()
  await expect(page.getByRole('combobox',{name:'Payroll frequency',exact:true})).toHaveValue('BIWEEKLY')
  await expect(page.getByLabel('Reference period start',{exact:true})).toHaveValue('2026-01-05')
  await expect(page.getByLabel('Calendar days after period end',{exact:true})).toHaveValue('5')
  await page.setViewportSize({width:390,height:844});await panel.screenshot({path:'/tmp/payroll-schedule-setup-mobile.png'})
  expect(errors).toEqual([])
 }finally{await h.close()}
})
test('admin previews a dated change, preserves used history and sees the saved future schedule',async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated localhost payroll database')
 const h=await createHarness()
 try{
  const old=(await h.pool.query("INSERT INTO payroll_pay_period(facility_id,period_start,period_end,pay_date,frequency) VALUES(1,'2097-01-01','2097-01-15','2097-01-20','SEMIMONTHLY') RETURNING id")).rows[0]
  await h.pool.query('INSERT INTO payroll_run(facility_id,pay_period_id) VALUES(1,$1)',[old.id])
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const url=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${url.pathname}${url.search}`})})})
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Employer setup',exact:true}).click()
  const panel=page.locator('section').filter({has:page.getByRole('heading',{name:'Change an existing pay schedule',exact:true})})
  await page.getByLabel('New schedule effective date',{exact:true}).fill('2097-01-10')
  await page.getByRole('button',{name:'Preview schedule change',exact:true}).click()
  await expect(panel.getByRole('alert')).toContainText('splits an existing pay period')
  await page.getByLabel('New schedule effective date',{exact:true}).fill('2097-01-16')
  await page.getByRole('button',{name:'Preview schedule change',exact:true}).click()
  await expect(page.getByRole('button',{name:'Save dated schedule change',exact:true})).toBeDisabled()
  await expect(panel.getByText('2097-01-01 – 2097-01-15 · semimonthly · pays 2097-01-20',{exact:true})).toBeVisible()
  await page.getByLabel('Schedule notice delivered on',{exact:true}).fill('2026-09-01')
  await page.getByLabel('Employee schedule notice reference',{exact:true}).fill('Synthetic employee schedule transition notice')
  await page.getByLabel('I verified employee notice and the old and new payment dates.',{exact:true}).check()
  await page.getByRole('button',{name:'Save dated schedule change',exact:true}).click()
  await expect(page.getByText('Dated payroll schedule change saved.',{exact:true})).toBeVisible()
  expect((await h.pool.query('SELECT COUNT(*)::int AS n FROM payroll_run WHERE pay_period_id=$1',[old.id])).rows[0].n).toBe(1)
  await page.reload();await page.getByRole('button',{name:'Employer setup',exact:true}).click()
  await expect(panel.getByText('2097-01-16 · weekly',{exact:false})).toBeVisible()
  await page.setViewportSize({width:390,height:844});await panel.screenshot({path:'/tmp/payroll-schedule-transition-mobile.png'})
  await panel.getByText('Cancel this future schedule change',{exact:true}).click()
  await page.getByRole('button',{name:'Preview schedule cancellation',exact:true}).click()
  await expect(page.getByRole('button',{name:'Confirm schedule cancellation',exact:true})).toBeDisabled()
  await page.getByLabel('Cancellation notice delivered on',{exact:true}).fill('2026-09-01')
  await page.getByLabel('Cancellation notice delivery reference',{exact:true}).fill('Synthetic cancellation notice delivered to employees')
  await page.getByLabel('I verified delivery of the cancellation notice and the restored pay dates.',{exact:true}).check()
  await page.getByRole('button',{name:'Confirm schedule cancellation',exact:true}).click()
  await expect(panel.getByText('Cancelled · Synthetic cancellation notice delivered to employees',{exact:true})).toBeVisible()
  expect((await h.pool.query("SELECT frequency FROM payroll_pay_period WHERE facility_id=1 AND period_start>='2097-01-16'")).rows.every(p=>p.frequency==='SEMIMONTHLY')).toBeTruthy()
  await page.reload();await page.getByRole('button',{name:'Employer setup',exact:true}).click()
  await expect(panel.getByText('Cancelled · Synthetic cancellation notice delivered to employees',{exact:true})).toBeVisible()
  await panel.screenshot({path:'/tmp/payroll-schedule-cancellation-mobile.png'})
  expect(errors).toEqual([])
 }finally{await h.close()}
})
