import {test,expect} from '@playwright/test'
import {carrierRemittanceFixture} from '../../backend/payroll/testing/carrierRemittanceFixture.js'
import {runCarrierRemittanceSweep} from '../../backend/payroll/carrierRemittanceAutomation.js'
import {hashEmail} from '../../backend/email/emailDeliveryStore.js'
for(const recovered of [false,true])test(`carrier remittance automatically refreshes ${recovered?'recovered uncertain acceptance':'bounded retry and SMTP acceptance'}`,async({page})=>{
 test.setTimeout(90000);page.setDefaultTimeout(15000);test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const prior=process.env.PAYROLL_DOCUMENT_KEY;process.env.PAYROLL_DOCUMENT_KEY='31'.repeat(32);let sends=0,mail:{to:string;idempotencyKey:string}|null=null,failRead=false
 const sender=async(input:{to:string;idempotencyKey:string})=>{sends++;mail=input;if(sends===1)return {sent:false,skipped:true,reason:'cooldown'};if(recovered)throw new Error('Synthetic lost sender result');return {sent:true,messageId:'synthetic-accepted'}}
 const f=await carrierRemittanceFixture({sender}),{h}=f
 try{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'));await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());if(failRead&&u.pathname.endsWith('/remittance-notices')&&route.request().method()==='GET')return route.fulfill({status:503,json:{success:false,message:'Synthetic history read failed'}});await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
  await page.setViewportSize({width:390,height:1200});await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Reports & QuickBooks',exact:true}).click();const invoices=page.getByRole('region',{name:'Carrier invoice reconciliation',exact:true});await invoices.getByLabel('Carrier coverage month',{exact:true}).fill('2026-09');await invoices.getByRole('button',{name:'Load carrier invoices',exact:true}).click();await invoices.getByText('Prepare carrier payment',{exact:true}).click();await invoices.getByText('Remittance delivery authorization',{exact:true}).click();const panel=invoices.getByRole('region',{name:'Carrier remittance delivery review',exact:true});await panel.getByRole('button',{name:'Load remittance delivery history',exact:true}).click();await expect(panel).toContainText('Notice authorized — pending delivery')
  await runCarrierRemittanceSweep(h.pool,{facility:1,now:f.now(),sender});await page.clock.fastForward(30001);await expect(panel).toContainText('Notice not sent — retry pending');await expect(panel.getByRole('button',{name:'Cancel remittance notice',exact:true})).toHaveCount(0);expect(sends).toBe(1)
  f.setNow(new Date(+f.now()+300001));await runCarrierRemittanceSweep(h.pool,{facility:1,now:f.now(),sender});await page.clock.fastForward(30001);await expect(panel).toContainText(recovered?'Notice outcome uncertain — recovery required':'Notice accepted by email provider');expect(sends).toBe(2)
  await panel.getByRole('button',{name:'Process or recover remittance',exact:true}).click();await expect(panel.getByRole('status')).toContainText(recovered?'UNCERTAIN':'SMTP_ACCEPTED');expect(sends).toBe(2)
  if(recovered){
   const attempt=(await h.pool.query('SELECT * FROM payroll_carrier_remittance_attempt ORDER BY id DESC LIMIT 1')).rows[0]
   await h.pool.query('CREATE TABLE email_delivery(id BIGINT,facility_id BIGINT,recipient_hash TEXT,category TEXT,stream TEXT,template_version TEXT,status TEXT,idempotency_key TEXT,created_at TIMESTAMPTZ,accepted_at TIMESTAMPTZ,bounced_at TIMESTAMPTZ,complained_at TIMESTAMPTZ)')
   await h.pool.query("INSERT INTO email_delivery VALUES(1,1,$1,'payroll_carrier_remittance','transactional','carrier-remittance-v1','accepted',$2,$3,$4,NULL,NULL)",[hashEmail(mail!.to),mail!.idempotencyKey,attempt.created_at,new Date(+new Date(attempt.created_at)+1000)])
   f.setNow(new Date(+f.now()+300001));await runCarrierRemittanceSweep(h.pool,{facility:1,now:f.now(),sender});await page.clock.fastForward(30001);await expect(panel).toContainText('Notice accepted by email provider');expect(sends).toBe(2)
  }
  await panel.getByText('Delivery attempt history',{exact:true}).click();await expect(panel).toContainText('NOT_SENT');await expect(panel).toContainText(recovered?'SMTP_ACCEPTED — recovered from delivery evidence':'SMTP_ACCEPTED');await expect(panel).toContainText('SMTP acceptance does not confirm carrier receipt')
  failRead=true;await page.clock.fastForward(30001);await expect(panel.getByRole('alert')).toContainText('Delivery history could not refresh');failRead=false;await page.clock.fastForward(30001);await expect(panel.getByRole('alert')).toHaveCount(0);await panel.locator('article').first().screenshot({path:`/tmp/payroll-carrier-remittance-${recovered?'recovered':'accepted'}-mobile.png`});expect(errors).toEqual([])
 }finally{await page.unrouteAll({behavior:'wait'}).catch(()=>{});await page.close().catch(()=>{});await h.close();if(prior===undefined)delete process.env.PAYROLL_DOCUMENT_KEY;else process.env.PAYROLL_DOCUMENT_KEY=prior}
})
