import { test, expect } from '@playwright/test'
import { createHarness } from '../../backend/payroll/testing/harness.js'

test('accelerated calendar keeps filing and payment evidence separate in the admin workflow',async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated localhost payroll database')
 const h=await createHarness()
 try {
  const api=async(path:string,body:unknown)=>{const response=await fetch(`${h.url}/api/admin/payroll${path}`,{method:'POST',headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:JSON.stringify(body)});const json=await response.json();expect(response.ok,JSON.stringify(json)).toBeTruthy();return json.data}
  const employee=await api('/employees',{employeeNumber:'ACCEL-BROWSER',legalFirstName:'Calendar',legalLastName:'Fixture',hireDate:'2026-01-01',hourlyRateCents:2500})
  const periods=await api('/pay-periods/generate',{year:2026,month:7}),period=periods.find((p:{period_start:string})=>p.period_start.startsWith('2026-07-01'))
  const run=(await h.pool.query("INSERT INTO payroll_run(facility_id,pay_period_id,payment_date,status) VALUES(1,$1,'2026-07-02','FINALIZED') RETURNING id",[period.id])).rows[0]
  await h.pool.query('INSERT INTO payroll_run_employee(payroll_run_id,employee_id,regular_pay_cents,state_income_tax_cents,federal_income_tax_cents) VALUES($1,$2,1000000,70000,0)',[run.id,employee.id])
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  await page.route('**/api/admin/payroll/**',async route=>{const url=new URL(route.request().url());const response=await route.fetch({url:`${h.url}${url.pathname}${url.search}`});await route.fulfill({response})})
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/tests/support/payroll.html')
  await page.getByRole('button',{name:'Compliance',exact:true}).click()
  await page.getByRole('combobox',{name:'Maryland withholding filing category',exact:true}).selectOption('ACCELERATED')
  const monthChoices=page.getByRole('group',{name:'Required Maryland withholding months'})
  for(const checkbox of await monthChoices.getByRole('checkbox').all())await checkbox.uncheck()
  await monthChoices.getByRole('checkbox',{name:'Jul',exact:true}).check()
  await page.getByLabel('Maryland withholding verification source',{exact:true}).fill('Synthetic accelerated employer account notice for July')
  await page.getByLabel('I verified the assigned category, required periods and complete payroll withholding history.',{exact:true}).check()
  await page.getByLabel('These are the agency-approved reporting periods; standard deadlines apply without an extension or special arrangement.',{exact:true}).check()
  await page.getByRole('button',{name:'Verify Maryland withholding schedule',exact:true}).click()
  await expect(page.getByText('Maryland withholding schedule verified.',{exact:true})).toBeVisible()
  const card=page.locator('article').filter({has:page.getByText('MW506M due 2026-07-08',{exact:true})})
  await expect(card).toBeVisible();await expect(card.getByText('Payment: OVERDUE',{exact:true})).toBeVisible()
  await expect(card.getByText('Return: OVERDUE',{exact:true})).toBeVisible()
  await card.getByRole('button',{name:'Prepare return comparison',exact:true}).click()
  await expect(page.getByRole('combobox',{name:'Tax form',exact:true})).toHaveValue('MD_MW506M')
  for(const [label,value] of Object.entries({'Filing period start':'2026-07-01','Filing period end':'2026-07-02','Reported gross wages ($)':'10000.00','Reported tax control total ($)':'700.00'}))await expect(page.getByLabel(label,{exact:true})).toHaveValue(value)
  for(const [label,value] of Object.entries({'Agency accepted date':'2026-07-08','Filing acceptance reference':'SYNTHETIC-ACCEL-BROWSER'}))await page.getByLabel(label,{exact:true}).fill(value)
  await page.getByLabel('I verified agency acceptance and transcribed the return totals.',{exact:true}).check()
  await page.getByRole('button',{name:'Record accepted filing',exact:true}).click()
  await expect(card.getByText('Return: RECORDED',{exact:true})).toBeVisible()
  await expect(card.getByText('Payment: OVERDUE',{exact:true})).toBeVisible()
  await page.getByRole('combobox',{name:'Tax agency / account',exact:true}).selectOption('MD_WITHHOLDING')
  await page.getByRole('combobox',{name:'Tax quarter',exact:true}).selectOption('3')
  for(const [label,value] of Object.entries({'Deposit payment date':'2026-07-09','Deposit amount ($)':'700','Deposit confirmation reference':'SYNTHETIC-ACCEL-PAYMENT'}))await page.getByLabel(label,{exact:true}).fill(value)
  await page.getByLabel('I verified this deposit succeeded against the bank or agency receipt.',{exact:true}).check()
  await page.getByRole('button',{name:'Record deposit receipt',exact:true}).click()
  await expect(card.getByText('Payment: COVERED LATE',{exact:true})).toBeVisible()
  await expect(card.getByText('Return: RECORDED',{exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:844});await card.scrollIntoViewIfNeeded()
  await card.screenshot({path:'/tmp/payroll-accelerated-calendar-mobile.png'})
  const filingRecord=page.locator('article').filter({has:page.getByText('Accepted 2026-07-08 · SYNTHETIC-ACCEL-BROWSER',{exact:true})})
  await filingRecord.getByText('Correct this filing receipt',{exact:true}).click()
  await expect(filingRecord.getByRole('button',{name:'Void local filing receipt',exact:true})).toBeDisabled()
  await filingRecord.getByLabel('Receipt correction reason',{exact:true}).fill('Synthetic test receipt entered against the wrong filing')
  await filingRecord.getByLabel('I am correcting only the local receipt record.',{exact:true}).check()
  await filingRecord.getByRole('button',{name:'Void local filing receipt',exact:true}).click()
  await expect(filingRecord.getByText('VOID',{exact:true})).toBeVisible()
  await expect(card.getByText('Return: OVERDUE',{exact:true})).toBeVisible()
  await expect(card.getByText('Payment: COVERED LATE',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Reports & QuickBooks',exact:true}).click()
  await page.getByLabel('Report start date',{exact:true}).fill('2026-07-01')
  await page.getByLabel('Report end date',{exact:true}).fill('2026-07-31')
  const downloadEvent=page.waitForEvent('download')
  await page.getByRole('button',{name:'Download employee summary',exact:true}).click()
  const download=await downloadEvent
  expect(download.suggestedFilename()).toBe('vortex-employee-payroll-summary-2026-07-01-2026-07-31.csv')
  const stream=await download.createReadStream();let csv=''
  for await(const chunk of stream!)csv+=chunk.toString()
  const lines=csv.trim().split('\r\n'),headers=lines[0].split(','),values=lines[1].split(',')
  expect(lines).toHaveLength(2)
  expect(values[headers.indexOf('Employee #')]).toBe('ACCEL-BROWSER')
  expect(values[headers.indexOf('Finalized gross')]).toBe('10000.00')
  expect(values[headers.indexOf('Maryland withholding')]).toBe('700.00')
  expect(values[headers.indexOf('Payment range start')]).toBe('2026-07-01')
  expect(values[headers.indexOf('Review status')]).toBe('INCOMPLETE FINALIZED TAX RECORDS')
  await page.getByLabel('Report end date',{exact:true}).fill('2026-06-30')
  await expect(page.getByRole('button',{name:'Download employee summary',exact:true})).toBeDisabled()
  expect(errors).toEqual([])
 } finally {await h.close()}
})
