import { test, expect } from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'

test('hire setup, employee onboarding, payroll, statement download and returning sign-in use real APIs', async ({ browser }) => {
 test.setTimeout(180000)
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated local payroll database')
 const priorKey=process.env.PAYROLL_DOCUMENT_KEY;process.env.PAYROLL_DOCUMENT_KEY='b'.repeat(64)
 const h=await createHarness()
 const adminContext = await browser.newContext({viewport:{width:1440,height:1000}})
 await adminContext.addInitScript(() => localStorage.setItem('adminToken','payroll-test-admin'))
 const admin=await adminContext.newPage(), employeeContext=await browser.newContext({viewport:{width:390,height:844}}), employee=await employeeContext.newPage()
 const errors:string[]=[];admin.on('pageerror',e=>errors.push(e.message));employee.on('pageerror',e=>errors.push(e.message))
 try{
 for(const context of [adminContext,employeeContext])for(const prefix of ['admin/payroll','payroll/employee'])await context.route(`**/api/${prefix}/**`,async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
 admin.setDefaultTimeout(15000);employee.setDefaultTimeout(15000)
 await admin.goto('/tests/support/payroll.html')
 await admin.getByRole('button',{name:'Employer setup',exact:true}).click()
 await admin.getByLabel('Legal business name',{exact:true}).fill('Synthetic Payroll Journey')
 await admin.getByLabel('Business address',{exact:true}).fill('123 Test Street, Bowie MD')
 await admin.getByLabel('Business telephone').fill('555-010-1234')
 await admin.getByLabel('Handbook & leave policy').fill('Vortex test handbook. Record all hours worked. Request leave through the payroll portal. Contact your supervisor for emergency procedures.')
 await admin.getByLabel('Benefits eligibility & enrollment instructions',{exact:true}).fill('Synthetic employer-paid benefits package with no employee deduction. Enrollment is subject to eligibility review and carrier confirmation.')
 await admin.getByLabel('First-day instructions & supervisor contact').fill('Arrive at reception and meet your supervisor at 9 AM.')
 await admin.getByRole('button',{name:'Save employer setup'}).click()
 await expect(admin.getByText('Employer setup saved.')).toBeVisible()
 await admin.getByLabel('Effective FUTA rate (%)').fill('0.6')
 await admin.getByLabel('Assigned Maryland UI rate (%)').fill('2.6')
 await admin.getByLabel('Employer tax verification source').fill('Synthetic 2026 rate notice and confirmed FUTA credit.')
 await admin.getByLabel('I verified the 2026 assigned rates', {exact:false}).check()
 await admin.getByRole('button',{name:'Save employer tax rates'}).click()
 await expect(admin.getByText('Employer tax rates saved. Rebuild existing drafts before approval.')).toBeVisible()
 await admin.getByRole('button',{name:'Compliance',exact:true}).click()
 const employerTasks=admin.locator('article').filter({has:admin.getByRole('button',{name:'Confirm complete',exact:true})})
 await expect(employerTasks).toHaveCount(8)
 const employerTaskTitles=await employerTasks.getByRole('heading',{level:3}).allTextContents()
 for(const title of employerTaskTitles){
  const task=admin.locator('article').filter({has:admin.getByRole('heading',{name:title,exact:true})})
  await task.getByLabel(`Completion note for ${title}`,{exact:true}).fill('Synthetic employer setup verification and supporting policy reference.')
  await task.getByRole('button',{name:'Confirm complete',exact:true}).click()
  await expect(task.getByRole('combobox',{name:`Status for ${title}`,exact:true})).toHaveValue('COMPLETE')
 }
 await admin.getByRole('button',{name:'People & onboarding',exact:true}).click()
 const number=`BROWSER-${Date.now()}`,email=`${number.toLowerCase()}@example.test`
 for(const [label,value] of Object.entries({'Employee number':number,'Hire date':'2026-09-10','Legal first name':'Morgan','Legal last name':'Browser','Personal email':email,'Job title':'Instructor','Hourly rate':'25'}))await admin.getByLabel(label,{exact:true}).fill(value)
 await admin.getByRole('button',{name:'Create onboarding record'}).click()
 await expect(admin.getByRole('heading',{name:'Hiring checklist & review'})).toBeVisible()
 await expect(admin.getByRole('button',{name:'Complete onboarding & activate employee'})).toBeDisabled()
 await admin.getByRole('button',{name:'Create link',exact:true}).click()
 const urlField=admin.getByLabel('One-time employee invitation link');await expect(urlField).not.toHaveValue('')
 const invite=new URL(await urlField.inputValue()).searchParams.get('invite')
 await employee.goto(`/employee/payroll?invite=${invite}`)
 await employee.getByRole('button',{name:'Onboarding',exact:true}).click()
 const profile=employee.locator('details').filter({has:employee.locator('summary',{hasText:'Personal details & emergency contact'})})
 for(const [label,value] of Object.entries({'Legal first name':'Morgan','Legal last name':'Browser','Home street address':'2 Test Street','City':'Bowie','State':'MD','ZIP code':'20715','Phone':'5550100201','Emergency contact name':'Taylor','Emergency contact phone':'5550100202','Relationship':'Friend'}))await profile.getByLabel(label,{exact:true}).fill(value)
 await profile.getByRole('button',{name:'Submit for review'}).click()
 await expect(employee.getByRole('status')).toHaveText('Step submitted for review.')
 await employee.screenshot({path:'/tmp/payroll-employee-mobile.png',fullPage:true})
 await admin.reload();await admin.getByRole('button',{name:'People & onboarding',exact:true}).click();await admin.getByRole('button',{name:new RegExp(number)}).click()
 const review=admin.locator('details').filter({has:admin.locator('summary',{hasText:'Personal details & emergency contact'})})
 await expect(review.getByText('2 Test Street',{exact:true})).toBeVisible()
 await review.getByLabel('Review evidence / instructions').fill('Verified legal name and emergency contact details.')
 await review.getByRole('button',{name:'Verify & complete'}).click()
 await expect(review.locator('summary')).toContainText('COMPLETE')
 await admin.screenshot({path:'/tmp/payroll-admin-review.png',fullPage:true})
 await employee.goto('/tests/support/payroll.html?employee=1')
 await employee.getByRole('button',{name:'Onboarding',exact:true}).click()
 for (const title of ['Federal Form W-4','State withholding certificate','Form I-9 employee section','Payment election','Offer & wage notice acknowledgment','Handbook & leave policy acknowledgment','Availability & first-day planning']) {
  const step=employee.locator('details').filter({has:employee.locator('summary',{hasText:title})})
  await step.locator('summary').first().click()
  if (title==='Federal Form W-4') {
   await step.getByLabel('Signed form (PDF, PNG or JPEG; up to 5 MB)').setInputFiles({name:'test-signed-form.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nTest fixture signed form')})
   await expect(employee.getByText('Document securely uploaded. Submit the step when ready.',{exact:true})).toBeVisible()
  } else if (['State withholding certificate','Form I-9 employee section'].includes(title)) await step.getByLabel('Secure provider receipt (if completed with provider)').fill('BROWSER-TEST-RECEIPT')
  else if (title==='Payment election') await step.getByLabel('Payment method').selectOption('CHECK')
  else if (title.includes('acknowledgment')) { await step.getByLabel('Your full name').fill('Morgan Browser');await step.getByRole('checkbox').check() }
  else await step.getByLabel('Availability & first-day questions').fill('Weekday mornings; ready for orientation.')
  await step.getByRole('button',{name:'Submit for review',exact:true}).click()
  await expect(step.locator('summary').first()).toContainText('SUBMITTED')
 }
 const benefitsStep=employee.locator('details').filter({has:employee.getByText('Pay, classification & benefits review',{exact:true})})
 await benefitsStep.locator('summary').first().click()
 await benefitsStep.getByLabel('Your benefits choice',{exact:true}).selectOption('ENROLL')
 await benefitsStep.getByLabel('Benefits choice signature',{exact:true}).fill('Morgan Browser')
 await benefitsStep.getByLabel('I read the displayed benefits offering and confirm this choice with my typed name.',{exact:true}).check()
 await benefitsStep.getByRole('button',{name:'Submit benefits choice',exact:true}).click()
 await expect(employee.getByRole('status')).toHaveText('Benefits choice submitted to your hiring admin.')
 await admin.getByRole('button',{name:'Schedules',exact:true}).click()
 await admin.getByLabel('Starts',{exact:true}).fill('2026-09-10T09:00')
 await admin.getByLabel('Ends',{exact:true}).fill('2026-09-10T13:00')
 await admin.getByRole('button',{name:'Schedule shift',exact:true}).click()
 await expect(admin.getByText('Shift scheduled.',{exact:true})).toBeVisible()
 await admin.getByRole('button',{name:'Edit shift',exact:true}).click()
 await admin.getByLabel('Starts',{exact:true}).fill('2026-09-10T10:00')
 await admin.getByLabel('Ends',{exact:true}).fill('2026-09-10T14:00')
 await admin.getByRole('button',{name:'Save shift changes',exact:true}).click()
 await expect(admin.getByText('Shift updated.',{exact:true})).toBeVisible()
 await admin.getByRole('button',{name:'People & onboarding',exact:true}).click()
 await admin.getByRole('button',{name:new RegExp(number)}).click()
 // Switching back reloads the employee packet after employee submissions.
 await admin.reload();await admin.getByRole('button',{name:'People & onboarding',exact:true}).click();await admin.getByRole('button',{name:new RegExp(number)}).click()
 for (const title of ['Federal Form W-4','State withholding certificate','Form I-9 employee section','Payment election','Offer & wage notice acknowledgment','Handbook & leave policy acknowledgment','Availability & first-day planning','Employer I-9 review','State new-hire report','Pay, classification & benefits review','Role training & safeguarding','First shift & access ready']) {
  if(title==='Pay, classification & benefits review'){
   await admin.getByRole('button',{name:'Pay setup & leave',exact:true}).click()
   await admin.getByLabel('MW507 exemptions',{exact:true}).fill('1')
   await admin.getByLabel('Verification source',{exact:true}).fill('Synthetic signed hiring W-4 and MW507 reviewed with applicable local rate')
   await admin.getByLabel('I verified these values against signed forms',{exact:false}).check()
   await admin.getByRole('button',{name:'Save verified tax elections',exact:true}).click()
   await expect(admin.getByText('Verified elections saved. New payroll drafts calculate withholding automatically.')).toBeVisible()
   await admin.getByRole('button',{name:'People & onboarding',exact:true}).click()
  }
  const step=admin.locator('details').filter({has:admin.locator('summary',{hasText:title})})
  await step.locator('summary').first().click()
  if(title==='Pay, classification & benefits review'){
   await step.getByLabel('Benefits disposition',{exact:true}).selectOption('ENROLLED')
   await step.getByLabel('Benefits effective or eligibility date',{exact:true}).fill('2026-09-01')
   await step.getByLabel('Benefits explanation for employee',{exact:true}).fill('Synthetic employer-paid coverage enrollment was confirmed with no employee deduction.')
   await step.getByLabel('Benefits review evidence',{exact:true}).fill('Synthetic carrier enrollment confirmation for the signed employee choice')
   await step.getByLabel('I verified the benefits disposition, effective date and supporting evidence.',{exact:true}).check()
  }
  await step.getByLabel('Review evidence / instructions').fill('Verified test evidence, signed forms, and orientation setup.')
  await step.getByRole('button',{name:'Verify & complete',exact:true}).click()
  await expect(step.locator('summary').first()).toContainText('COMPLETE')
 }
 await expect(admin.getByRole('button',{name:'Complete onboarding & activate employee'})).toBeEnabled()
 await admin.getByRole('button',{name:'Complete onboarding & activate employee'}).click()
 await expect(admin.getByText('Onboarding complete. Employee activated.',{exact:true})).toBeVisible()
 console.info('Journey: employee activated after all hiring reviews')
 await admin.getByRole('button',{name:'Pay setup & leave',exact:true}).click()
 await admin.getByLabel('New hourly rate ($)',{exact:true}).fill('30.00')
 const futureRate=new Date('2060-01-03T00:00:00Z')
 while(futureRate.getUTCDay()!==1)futureRate.setUTCDate(futureRate.getUTCDate()+1)
 await admin.getByLabel('Effective date',{exact:true}).fill(futureRate.toISOString().slice(0,10))
 await admin.getByLabel('Reason for pay change',{exact:true}).fill('Synthetic future compensation review for browser verification.')
 await admin.getByLabel('Written notice delivered on',{exact:true}).fill((await admin.getByLabel('Written notice delivered on',{exact:true}).getAttribute('max'))!)
 await admin.getByLabel('Written-notice delivery reference',{exact:true}).fill('Synthetic signed wage notice fixture')
 await admin.getByLabel('I confirm this employee received written notice on the recorded date.').check()
 await admin.getByRole('button',{name:'Schedule pay change',exact:true}).click()
 await expect(admin.getByText('Pay change scheduled and available in the employee portal.')).toBeVisible()
 await employee.getByRole('button',{name:'Pay statements',exact:true}).click()
 await employee.getByRole('button',{name:'Acknowledge receipt of pay notice',exact:true}).click()
 await expect(employee.getByText('Receipt recorded. This acknowledgment does not waive any wage rights.')).toBeVisible()
 await employee.screenshot({path:'/tmp/payroll-pay-notice-mobile.png',fullPage:true})
 await admin.getByRole('button',{name:'Cancel scheduled pay change',exact:true}).click()
 await admin.getByLabel('Reason for cancellation',{exact:true}).fill('Correcting the future rate after compensation review.')
 await admin.getByLabel('Cancellation notice delivered on',{exact:true}).fill((await admin.getByLabel('Cancellation notice delivered on',{exact:true}).getAttribute('max'))!)
 await admin.getByLabel('Cancellation notice reference',{exact:true}).fill('Synthetic cancellation notice delivery receipt')
 await admin.getByLabel('I confirm this employee received the written cancellation notice.').check()
 await admin.getByRole('button',{name:'Confirm pay change cancellation',exact:true}).click()
 await expect(admin.getByText('Pay change cancelled. The previous rate continues; schedule a replacement below if needed.')).toBeVisible()
 await employee.reload();await employee.getByRole('button',{name:'Pay statements',exact:true}).click()
 await employee.getByRole('button',{name:'Acknowledge cancellation notice',exact:true}).click()
 await expect(employee.getByText('Cancellation receipt recorded. This acknowledgment does not waive any wage rights.')).toBeVisible()
 await employee.screenshot({path:'/tmp/payroll-cancelled-notice-mobile.png',fullPage:true})
 await admin.getByLabel('New hourly rate ($)',{exact:true}).fill('32.00')
 await admin.getByLabel('Effective date',{exact:true}).fill(futureRate.toISOString().slice(0,10))
 await admin.getByLabel('Reason for pay change',{exact:true}).fill('Corrected future compensation rate for browser verification.')
 await admin.getByLabel('Written notice delivered on',{exact:true}).fill((await admin.getByLabel('Written notice delivered on',{exact:true}).getAttribute('max'))!)
 await admin.getByLabel('Written-notice delivery reference',{exact:true}).fill('Synthetic replacement wage notice fixture')
 await admin.getByLabel('I confirm this employee received written notice on the recorded date.').check()
 await admin.getByRole('button',{name:'Schedule pay change',exact:true}).click()
 await expect(admin.getByText('Pay change scheduled and available in the employee portal.')).toBeVisible()
 await employee.reload();await employee.getByRole('button',{name:'Pay statements',exact:true}).click()
 await employee.getByRole('button',{name:'Acknowledge receipt of pay notice',exact:true}).click()
 await expect(employee.getByText('Receipt recorded. This acknowledgment does not waive any wage rights.')).toBeVisible()



 await employee.getByRole('button',{name:'Home',exact:true}).click()
 await employee.getByLabel('New payroll password').fill('Vortex-Test-Password-2026')
 await employee.getByRole('button',{name:'Save password',exact:true}).click()
 await expect(employee.getByRole('status')).toContainText('Password saved.')
 await employee.getByRole('button',{name:'Sign out',exact:true}).click()
 await employee.getByLabel('Email',{exact:true}).fill(email)
 await employee.getByLabel('Password',{exact:true}).fill('Vortex-Test-Password-2026')
 await employee.getByRole('button',{name:'Sign in to payroll'}).click()
 await expect(employee.getByText('Hi, Morgan')).toBeVisible()
 await employee.getByRole('button',{name:'Leave & requests',exact:true}).click()
 await employee.getByLabel('Request type').selectOption('GENERAL')
 await employee.getByLabel('Details / reason').fill(`Please confirm my orientation time: ${number}`)
 await employee.getByRole('button',{name:'Submit request',exact:true}).click()
 await expect(employee.getByText('Request submitted to your hiring admin.', {exact:true})).toBeVisible()
 await admin.getByRole('button',{name:'Requests & approvals',exact:true}).click()
 const request=admin.locator('article').filter({hasText:`Please confirm my orientation time: ${number}`})
 await request.getByLabel('Review note').fill('Orientation is at 9 AM at reception.')
 await request.getByRole('button',{name:'Approve request'}).click()
 await expect(request).toContainText('APPROVED')
 await admin.getByRole('button',{name:'Pay setup & leave',exact:true}).click()
 await admin.getByLabel('MW507 exemptions',{exact:true}).fill('1')
 await admin.getByLabel('Verification source',{exact:true}).fill('Browser fixture: verified signed W-4 and MW507, resident local rate 3.20%.')
 await admin.getByLabel('I verified these values against signed forms', {exact:false}).check()
 await admin.getByRole('button',{name:'Save verified tax elections'}).click()
 await expect(admin.getByText('Verified elections saved. New payroll drafts calculate withholding automatically.')).toBeVisible()
 await admin.getByRole('button',{name:'Daily time',exact:true}).click()
 await admin.getByLabel('Clock in',{exact:true}).fill('2026-09-10T09:00')
 await admin.getByLabel('Clock out',{exact:true}).fill('2026-09-10T17:00')
 await admin.getByLabel('Evidence/source note').fill('Browser test attendance record: eight hours worked.')
 await admin.getByRole('button',{name:'Add unverified entry'}).click()
 await admin.getByRole('button',{name:'Approve',exact:true}).click()
 await expect(admin.getByText('Time entry approved and audit logged.')).toBeVisible()
 await admin.getByRole('button',{name:'Payroll runs',exact:true}).click()
 await admin.getByLabel('Pay calendar month',{exact:true}).fill('2026-09')
 await admin.getByRole('button',{name:'Generate pay periods',exact:true}).click()
 const periodOption=admin.getByRole('combobox',{name:'Pay period',exact:true}).locator('option').filter({hasText:'Sep 15, 2026'})
 await expect(periodOption).toHaveCount(1)
 await admin.getByRole('combobox',{name:'Pay period',exact:true}).selectOption(await periodOption.getAttribute('value') as string)
 await admin.getByLabel('Payroll payment date',{exact:true}).fill('2026-09-21')
 await admin.getByRole('button',{name:'Preview payroll',exact:true}).click()
 await expect(admin.getByText('0 approval blockers',{exact:true})).toBeVisible()
 await admin.getByRole('button',{name:'Save draft snapshot'}).click()
 await admin.getByRole('button',{name:'Open review'}).click()
 await admin.getByRole('button',{name:'Send to review'}).click()
 await admin.getByRole('button',{name:'Approve run',exact:true}).click()
 await expect(admin.getByLabel('Actual payment date',{exact:true})).toHaveValue('2026-09-21')
 await admin.getByLabel('External payment confirmation').fill('BROWSER-TEST-CHECK-ONLY')
 await admin.getByRole('button',{name:'Confirm paid & finalize'}).click()
 await expect(admin.getByText('Payroll finalized and employee statements saved.')).toBeVisible()
 const paid=(await h.pool.query('SELECT regular_minutes,regular_pay_cents,net_pay_cents FROM payroll_run_employee')).rows
 expect(paid).toHaveLength(1);expect(Number(paid[0].regular_minutes)).toBe(480);expect(Number(paid[0].regular_pay_cents)).toBe(20000);expect(Number(paid[0].net_pay_cents)).toBe(18470)
 console.info('Journey: payroll finalized')
 await admin.screenshot({path:'/tmp/payroll-finalized-browser.png',fullPage:true})
 await admin.getByRole('button',{name:'Compliance',exact:true}).click()
 await admin.getByRole('combobox',{name:'Verified Form 941 deposit schedule',exact:true}).selectOption('MONTHLY')
 await admin.getByLabel('Deposit schedule verification source',{exact:true}).fill('Synthetic IRS lookback review and complete payroll history')
 await admin.getByLabel('I verified this Form 941 employer’s schedule, prior-year next-day status, and complete daily payroll tax history for this year.').check()
 await admin.getByRole('button',{name:'Verify federal deposit schedule',exact:true}).click()
 await expect(admin.getByText('Federal deposit schedule verified. Deadlines recalculated.')).toBeVisible()
 await expect(admin.getByText('Federal deposit due 2026-10-15 · Q3',{exact:true})).toBeVisible()
 await expect(admin.getByText('FUTA payment due 2027-02-01 · Q3–Q4',{exact:true})).toBeVisible()
 await admin.getByRole('heading',{name:'Federal deposit calendar',exact:true}).locator('..').screenshot({path:'/tmp/payroll-federal-deposit-calendar.png'})
 await admin.getByText('FUTA payment due 2027-02-01 · Q3–Q4',{exact:true}).locator('..').screenshot({path:'/tmp/payroll-futa-deadline-card.png'})
 await admin.getByRole('combobox',{name:'First required Maryland UI quarter',exact:true}).selectOption('2')
 await admin.getByLabel('Maryland UI account verification source',{exact:true}).fill('Synthetic BEACON registration and reporting range verification')
 await admin.getByLabel('I verified these reporting quarters and complete wage and unemployment tax history.').check()
 await admin.getByLabel('The standard contributory-employer schedule applies; no payment plan, agency extension or reimbursable-employer arrangement applies.').check()
 await admin.getByRole('button',{name:'Verify Maryland UI reporting',exact:true}).click()
 await expect(admin.getByText('Maryland unemployment reporting verified. Deadlines recalculated.')).toBeVisible()
 await expect(admin.getByText('Maryland UI Q3 due 2026-11-02',{exact:true})).toBeVisible()
 await admin.getByRole('combobox',{name:'Tax quarter',exact:true}).selectOption('3')
 await admin.getByLabel('Deposit payment date',{exact:true}).fill('2026-10-15')
 await admin.getByLabel('Deposit amount ($)',{exact:true}).fill('10.00')
 await admin.getByLabel('Deposit confirmation reference',{exact:true}).fill('BROWSER-EFTPS-TEST-001')
 await admin.getByLabel('I verified this deposit succeeded against the bank or agency receipt.').check()
 await admin.getByRole('button',{name:'Record deposit receipt',exact:true}).click()
 await expect(admin.getByText('Agency deposit receipt recorded. Balances updated.')).toBeVisible()
 const receipt=admin.locator('article').filter({hasText:'BROWSER-EFTPS-TEST-001'})
 await expect(receipt).toContainText('$10.00')
 const taxQuarter=admin.locator('article').filter({has:admin.getByRole('heading',{name:/Q3 · 2026-07-01/})})
 await taxQuarter.getByRole('button',{name:'Prepare IRS 941 comparison',exact:true}).click()
 await admin.getByLabel('Agency accepted date',{exact:true}).fill('2026-10-31')
 await admin.getByLabel('Filing acceptance reference',{exact:true}).fill('BROWSER-941-TEST-001')
 await admin.getByLabel('I verified agency acceptance and transcribed the return totals.').check()
 await admin.getByRole('button',{name:'Record accepted filing',exact:true}).click()
 await expect(admin.locator('article').filter({hasText:'BROWSER-941-TEST-001'})).toContainText('MATCHED')
 const zeroQuarter=admin.locator('article').filter({has:admin.getByRole('heading',{name:/Q2 · 2026-04-01/})})
 await zeroQuarter.getByRole('button',{name:'Prepare MD UI comparison',exact:true}).click()
 await admin.getByLabel('Agency accepted date',{exact:true}).fill('2026-07-31')
 await admin.getByLabel('Filing acceptance reference',{exact:true}).fill('BROWSER-MD-UI-ZERO-REPORT')
 await admin.getByLabel('I verified agency acceptance and transcribed the return totals.').check()
 await admin.getByRole('button',{name:'Record accepted filing',exact:true}).click()
 const mdQuarter=admin.getByText('Maryland UI Q2 due 2026-07-31',{exact:true}).locator('..')
 await expect(mdQuarter).toContainText(/Wage report:\s*RECORDED/)
 await expect(mdQuarter).toContainText('NO TAX DUE')
 await mdQuarter.screenshot({path:'/tmp/payroll-maryland-ui-report-card.png'})

 await admin.getByLabel('Maryland withholding verification source',{exact:true}).fill('Synthetic Maryland Tax Connect quarterly filing notice')
 await admin.getByLabel('I verified the assigned category, required periods and complete payroll withholding history.').check()
 await admin.getByLabel('These are the agency-approved reporting periods; standard deadlines apply without an extension or special arrangement.').check()
 await admin.getByRole('button',{name:'Verify Maryland withholding schedule',exact:true}).click()
 await expect(admin.getByText('Maryland withholding schedule verified.',{exact:true})).toBeVisible()
 await expect(admin.getByText('MW508 annual reconciliation due 2027-02-01',{exact:true})).toBeVisible()
 await admin.getByRole('combobox',{name:'Tax form',exact:true}).selectOption('MD_MW506')
 await admin.getByLabel('Agency accepted date',{exact:true}).fill('2026-07-15')
 await admin.getByLabel('Filing acceptance reference',{exact:true}).fill('BROWSER-MW506-ZERO-REPORT')
 await admin.getByLabel('I verified agency acceptance and transcribed the return totals.').check()
 await admin.getByRole('button',{name:'Record accepted filing',exact:true}).click()
 const withholdingQuarter=admin.getByText('MW506 due 2026-07-15',{exact:true}).locator('..')
 await expect(withholdingQuarter).toContainText(/Return:\s*RECORDED/)
 await expect(withholdingQuarter).toContainText('NO TAX DUE')
 await withholdingQuarter.screenshot({path:'/tmp/payroll-maryland-withholding-card.png'})

 await admin.screenshot({path:'/tmp/payroll-tax-reconciliation.png',fullPage:true})

 await employee.getByRole('button',{name:'Refresh payroll portal',exact:true}).click()
 await employee.getByRole('button',{name:'Pay statements',exact:true}).click()
 const downloadEvent=employee.waitForEvent('download')
 await employee.getByRole('button',{name:'Download itemized pay statement (PDF)'}).click()
 const statementDownload=await downloadEvent
 expect(statementDownload.suggestedFilename()).toMatch(/^pay-statement-\d+\.pdf$/)
 await statementDownload.saveAs('/tmp/payroll-browser-statement.pdf')
 console.info('Journey: employee statement downloaded')
 await admin.getByRole('button',{name:'Pay setup & leave',exact:true}).click()
 await admin.getByRole('combobox',{name:'Leave ledger',exact:true}).selectOption('PTO')
 await admin.getByLabel('Transaction date',{exact:true}).fill('2026-10-01')
 await admin.getByLabel('Minutes',{exact:true}).fill('480')
 await admin.getByLabel('Reason',{exact:true}).fill('Synthetic paid time off opening balance')
 await admin.getByRole('button',{name:'Record leave entry'}).click()
 await expect(admin.getByText('Leave ledger entry recorded and audited.')).toBeVisible()
 await employee.getByRole('button',{name:'Leave & requests',exact:true}).click()
 await employee.getByLabel('Request type').selectOption('LEAVE')
 await employee.getByLabel('Leave type').selectOption('PTO')
 await employee.getByLabel('Start date',{exact:true}).fill('2026-10-15')
 await employee.getByLabel('End date',{exact:true}).fill('2026-10-16')
 await employee.getByLabel('Paid leave hours 2026-10-15',{exact:true}).fill('1')
 await employee.getByLabel('Paid leave hours 2026-10-16',{exact:true}).fill('1')
 await employee.getByLabel('Details / reason').fill(`Two-day paid leave: ${number}`)
 await employee.getByRole('button',{name:'Submit request',exact:true}).click()
 await expect(employee.getByText('Request submitted to your hiring admin.',{exact:true})).toBeVisible()
 await admin.getByRole('button',{name:'Requests & approvals',exact:true}).click()
 const leaveRequest=admin.locator('article').filter({hasText:`Two-day paid leave: ${number}`})
 await leaveRequest.getByLabel('Review note').fill('Approved one paid hour on each date.')
 await leaveRequest.getByRole('button',{name:'Approve request'}).click()
 await expect(leaveRequest).toContainText('APPROVED')
 expect(errors).toEqual([])
 }finally{await adminContext.close();await employeeContext.close();await h.close();if(priorKey===undefined)delete process.env.PAYROLL_DOCUMENT_KEY;else process.env.PAYROLL_DOCUMENT_KEY=priorKey}
})
