import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
for(const aggregate of [false,true])test(`admin pays standalone vacation with ${aggregate?'aggregate':'flat'} federal withholding`,async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness({databaseNow:'2026-09-08T12:00:00.000Z'})
 try{
 const api=async(path:string,body:unknown,status=200,method='POST')=>{const r=await fetch(`${h.url}/api/admin/payroll${path}`,{method,headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();expect(r.status,JSON.stringify(j)).toBe(status);return j.data}
 await api('/settings',{legalBusinessName:'Standalone PTO Fixture',businessAddress:'123 Test Street',businessPhone:'5550100000'},200,'PATCH')
 await api('/employer-taxes',{futaRatePercent:0.6,mdUiRatePercent:2.6,source:'Synthetic employer notice',confirmed:true},200,'PATCH')
 const e=await api('/employees',{employeeNumber:'PTO-OFF-CYCLE',legalFirstName:'Former',legalLastName:'Vacation',hireDate:'2026-08-03',hourlyRateCents:2500},201)
 await h.pool.query("UPDATE payroll_employee SET employment_status='TERMINATED',termination_date='2026-09-05',w4_status='COMPLETE',state_withholding_status='COMPLETE' WHERE id=$1",[e.id])
 await api(`/employees/${e.id}/tax-elections`,{confirmed:true,sourceNote:'Synthetic signed tax elections',federal:{filingStatus:'SINGLE'},maryland:{filingStatus:'SINGLE',localRate:3.2,exemptions:1}},200,'PATCH')
 const p=(await h.pool.query("INSERT INTO payroll_pay_period(facility_id,period_start,period_end,pay_date,frequency,status) VALUES(1,'2026-08-31','2026-09-06','2026-09-08','WEEKLY','PAID') RETURNING id")).rows[0]
 const original=(await h.pool.query("INSERT INTO payroll_run(facility_id,pay_period_id,status,payment_date,payment_confirmation_reference,calculation_snapshot) VALUES(1,$1,'FINALIZED','2026-09-08','SYNTHETIC-REGULAR-PAY',$2) RETURNING id",[p.id,{employees:[{employeeId:e.id,grossPayCents:aggregate?10000:100000,payItems:[]}]}])).rows[0]
 await h.pool.query('INSERT INTO payroll_run_employee(payroll_run_id,employee_id,regular_pay_cents,federal_income_tax_cents,withholding_verified_at) VALUES($1,$2,$3,$4,now())',[original.id,e.id,aggregate?10000:100000,aggregate?0:10000])
 await h.pool.query("INSERT INTO payroll_leave_transaction(facility_id,employee_id,leave_type,transaction_date,minutes,reason) VALUES(1,$1,'PTO','2026-08-08',480,'Synthetic accrued vacation')",[e.id])
 await h.pool.query("UPDATE payroll_compliance_task SET status='COMPLETE' WHERE facility_id=1")
 await h.pool.query("INSERT INTO payroll_pay_period(facility_id,period_start,period_end,pay_date,frequency) VALUES(1,'2026-09-07','2026-09-13','2026-09-18','WEEKLY')")
 await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
 await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'People & onboarding',exact:true}).click()
 const payout=page.getByRole('region',{name:'Unused PTO payout',exact:true})
 await payout.getByLabel('PTO minutes to pay out',{exact:true}).fill('240')
 await payout.getByLabel('Reviewed PTO payout rate ($/hour)',{exact:true}).fill('25')
 await payout.getByLabel('PTO payout policy evidence',{exact:true}).fill('Synthetic communicated unused vacation policy')
 await payout.getByLabel('I verified the communicated payout policy and applicable rate.',{exact:true}).check()
 await payout.getByLabel('This pays unused vacation/PTO and is not an attendance bonus.',{exact:true}).check()
 await payout.getByRole('button',{name:'Calculate PTO payout',exact:true}).click()
 await expect(payout.getByText('PTO payout: $100.00',{exact:true})).toBeVisible()
 await payout.getByRole('combobox',{name:'PTO payment method',exact:true}).selectOption('STANDALONE')
 await payout.getByRole('combobox',{name:'PTO payout payroll period',exact:true}).selectOption(String(p.id))
 await payout.getByRole('button',{name:'Reserve PTO payout',exact:true}).click()
 await expect(payout.getByText('4 hours · RESERVED',{exact:true})).toBeVisible()
 if(aggregate)await payout.getByRole('combobox',{name:'PTO federal withholding method',exact:true}).selectOption('AGGREGATE')
 await payout.getByLabel('PTO payment date',{exact:true}).fill('2026-09-09')
 await payout.getByLabel('PTO payment-history evidence',{exact:true}).fill('Synthetic complete employer payment reconciliation')
 await payout.getByRole('checkbox',{name:'I reconciled complete employer and related-employer payment history for this payment date.',exact:true}).check()
 await page.setViewportSize({width:390,height:2200});await payout.scrollIntoViewIfNeeded();await expect(payout).toBeInViewport({ratio:1});await payout.screenshot({path:aggregate?'/tmp/payroll-aggregate-pto-mobile.png':'/tmp/payroll-standalone-pto-mobile.png'})
 await payout.getByRole('button',{name:'Create standalone PTO payroll',exact:true}).click()
 await expect(payout.getByText(/PTO payroll .* created/)).toBeVisible()
 await page.getByRole('button',{name:'Payroll runs',exact:true}).click()
 await page.getByRole('row').filter({hasText:'Standalone PTO payout'}).getByRole('button',{name:'Open review',exact:true}).click()
 await expect(page.getByText(`Calculated federal withholding: ${aggregate?'$0.00':'$22.00'}`,{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Send to review',exact:true}).click()
 await page.getByLabel('Federal withholding ($)',{exact:true}).fill(aggregate?'0':'22')
 await page.getByLabel('Maryland withholding ($)',{exact:true}).fill('8')
 await page.getByLabel('Professional/table source note',{exact:true}).fill('Synthetic professional vacation withholding worksheet')
 await page.getByRole('checkbox',{name:/I confirm these values came from a payroll professional/}).check()
 await page.getByRole('button',{name:'Record verified withholding',exact:true}).click()
 await page.getByRole('button',{name:'Approve run',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('Resolve all current payroll blockers and withholding before approval.')
 await h.pool.query("UPDATE payroll_compliance_task SET status='COMPLETE' WHERE facility_id=1")
 await page.getByRole('button',{name:'Approve run',exact:true}).click()
 await expect(page.getByLabel('Actual payment date',{exact:true})).toBeVisible()
 await page.getByLabel('External payment confirmation',{exact:true}).fill('SYNTHETIC-PTO-BROWSER-PAYMENT')
 await page.getByRole('button',{name:'Confirm paid & finalize',exact:true}).click()
 await expect(page.getByText('Payroll finalized and employee statements saved.',{exact:true})).toBeVisible()
 expect((await h.pool.query("SELECT SUM(minutes)::int n FROM payroll_leave_transaction WHERE employee_id=$1 AND leave_type='PTO'",[e.id])).rows[0].n).toBe(240)
 expect((await h.pool.query("SELECT status FROM payroll_leave_payout WHERE employee_id=$1",[e.id])).rows[0].status).toBe('PAID')
 expect(errors).toEqual([])
 }finally{await page.unrouteAll({behavior:'wait'});await page.close();await h.close()}
})
