import {runRetirementReplacementSettlementSweep} from '../../backend/payroll/retirementReplacementSettlementAutomation.js'
import {checkRetirementReplacementReceipts} from '../../backend/payroll/retirementReplacementReceiptAutomation.js'
import {runRetirementReplacementBankSweep} from '../../backend/payroll/retirementReplacementBankAutomation.js'
import {retirementReplacementBankProvider} from '../../backend/payroll/testing/retirementReplacementBankProvider.js'
import {runRetirementReplacementAllocationSweep} from '../../backend/payroll/retirementReplacementAutomation.js'
import {retirementReversalAccountingFixture} from '../../backend/payroll/testing/retirementReversalAccountingFixture.js'
import {checkRetirementReceipts} from '../../backend/payroll/retirementReceiptAutomation.js'
import {test,expect,type Page} from '@playwright/test'
import {createHash,randomBytes,randomUUID} from 'node:crypto'
import {createHarness} from '../../backend/payroll/testing/harness.js'
import {createRetirementSftpServer} from '../../backend/payroll/testing/retirementSftpServer.js'
import {retirementBankProvider} from '../../backend/payroll/testing/retirementBankProvider.js'
import {retirementReceiptIntakeFixture} from '../../backend/payroll/testing/retirementReceiptIntakeFixture.js'
import {readRetirementSftpReceipt,transferRetirementAllocation,verifyRetirementSftpConnection} from '../../backend/payroll/retirementSftpTransport.js'
test('admin reviews reversal semantics and automatically reconciles participant reversal receipts',async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated database');test.setTimeout(180000)
 const old=process.env.PAYROLL_DOCUMENT_KEY;process.env.PAYROLL_DOCUMENT_KEY=randomBytes(32).toString('hex')
 let employeePage:Page|undefined
 let remittanceClock='2026-09-19T15:00:00Z'
 let replacementFetcher:null|ReturnType<typeof retirementReplacementBankProvider>['fetcher']=null,qboFetcher=async()=>{throw new Error('No synthetic accounting configured')}
 const server=await createRetirementSftpServer(),provider=retirementBankProvider(),h=await createHarness({quickbooksFetcher:(...args)=>qboFetcher(...args),paymentFetcher:(...args)=>replacementFetcher?replacementFetcher(...args):provider.fetcher(...args),remittanceNow:()=>new Date(remittanceClock),retirementNow:()=>new Date('2026-09-11T12:00:00Z'),retirementReceiptReader:(c,location)=>readRetirementSftpReceipt(c,location,server.options),retirementSftpVerifier:c=>verifyRetirementSftpConnection(c,server.options),retirementAllocationTransfer:(c,file,options)=>transferRetirementAllocation(c,file,{...server.options,...options})}),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 try{
  const f=await retirementReceiptIntakeFixture(h,server.config),accounting=retirementReversalAccountingFixture(h,f);qboFetcher=accounting.fetcher
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
  let loseAuthorization=true
  const authorizationRequests:unknown[]=[]
  await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url()),isApproval=u.pathname.endsWith('/replacement-authorizations')&&route.request().method()==='POST';if(isApproval)authorizationRequests.push(route.request().postDataJSON());const response=await route.fetch({url:`${h.url}${u.pathname}${u.search}`});if(isApproval&&loseAuthorization){loseAuthorization=false;expect(response.ok()).toBe(true);await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Synthetic lost replacement authorization response'})});return}await route.fulfill({response})})
  await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Employer setup',exact:true}).click();await page.getByRole('button',{name:'Load retirement plan history',exact:true}).click()
  const contract=page.getByRole('region',{name:'Retirement receipt contract standard',exact:true});await contract.getByRole('button',{name:'Load receipt contract history',exact:true}).click();await contract.getByText(/Receipt revision 1 · REVIEWED/).click();await contract.getByRole('button',{name:'Edit from receipt revision 1',exact:true}).click()
  await contract.getByRole('textbox',{name:'Provider value for REVERSED (optional)',exact:true}).fill('Reversed credit')
  await contract.getByRole('checkbox',{name:'I verified that the receipt filename and SHA-256 identify the exact original allocation bytes.',exact:true}).check();await contract.getByRole('checkbox',{name:'I verified these amounts are cumulative participant contributions, with separate ordinary and catch-up categories.',exact:true}).check();await contract.getByRole('checkbox',{name:'I verified POSTED means actual participant credit and ACCEPTED means file acceptance only.',exact:true}).check();await contract.getByRole('checkbox',{name:'I confirm this receipt contract action and reviewed specification.',exact:true}).check()
  await expect(contract.getByRole('button',{name:'Save reviewed receipt contract',exact:true})).toBeDisabled()
  await contract.getByRole('checkbox',{name:'I verified REVERSED means the full original participant allocation was reversed with zero remaining credited amounts.',exact:true}).check();await contract.getByRole('checkbox',{name:'I confirm this receipt contract action and reviewed specification.',exact:true}).check();await contract.getByRole('button',{name:'Save reviewed receipt contract',exact:true}).click();await expect(contract).toContainText('Receipt contract: CURRENT · revision 2')
  const saved=(await f.api(f.contractPath)).history[0];expect(saved.contract.participantReversalConfirmed).toBe(true)
  const bound=await f.api(f.bindingPath,{...f.bindingBody,expectedRevision:1,contractId:saved.id,requestKey:randomUUID()});f.bindingId=bound.id
  server.files.set(f.remotePath,f.receipt());await f.api(f.receiptPath,{confirmed:true,bindingId:f.bindingId,requestKey:randomUUID()})
  const bankPath=`/retirement-remittance-authorizations/${f.remittanceId}/dispatch`
  await f.api(bankPath,{action:'SUBMIT',confirmed:true,bankInstructionsReviewed:true,outsideActivityReviewed:true,reference:'Verified separate participant allocation and bank funding instructions'})
  provider.complete();await f.api(bankPath,{action:'RECOVER',confirmed:true});expect((await accounting.prepareOriginal()).status).toBe('SYNCED');provider.returnedCredit();await f.api(bankPath,{action:'RECOVER',confirmed:true})
  await page.getByRole('button',{name:'Load allocation delivery history',exact:true}).click()
  const panel=page.getByRole('region',{name:`Retirement receipt outcomes ${f.allocationId}`,exact:true});await panel.getByRole('button',{name:'Load receipt outcome history',exact:true}).click();await expect(panel).toContainText('Latest retained receipt: POSTED')
  server.files.set(f.remotePath,f.receipt({status:'Reversed credit',recordedAt:'2026-09-24T15:00:00Z',ordinaryPretaxCents:0,ordinaryRothCents:0,catchUpPretaxCents:0,catchUpRothCents:0,totalCents:0}))
  expect((await checkRetirementReceipts(h.pool,1,{reader:(c,r)=>readRetirementSftpReceipt(c,r,server.options),now:new Date(Date.now()+25*3600000),receiptNow:()=>new Date('2026-09-25T15:00:00Z')})).checked).toBe(1)
  await expect(panel).toContainText('Latest retained receipt: REVERSED',{timeout:40000});await expect(panel).toContainText('Provider-reported reversed allocations: $14.00');await expect(panel).toContainText('Earlier receipt: POSTED');await expect(panel).toContainText('Automatic check')
  await expect(panel).not.toContainText('PRIVATE-PARTICIPANT');expect(provider.posts()).toBe(1);expect(server.state.created).toBe(1)
  const assessment=page.getByRole('region',{name:`Contribution reconciliation ${f.remittanceId}`,exact:true})
  await assessment.getByRole('button',{name:'Review contribution reconciliation',exact:true}).click();await expect(assessment).toContainText('Participants: REVERSED');await expect(assessment).toContainText('Confirmed reversed allocations: $14.00');await expect(assessment).toContainText('Replacement review: EVIDENCE REQUIRED')
  expect((await accounting.prepareReturn()).status).toBe('SYNCED')
  await assessment.getByRole('button',{name:'Review contribution reconciliation',exact:true}).click();await expect(assessment).toContainText('Replacement review: EVIDENCE READY');await expect(assessment).toContainText('Assessment: REVIEW REQUIRED')
  const instructions=assessment.getByRole('region',{name:`Replacement contribution instructions ${f.remittanceId}`,exact:true})
  await instructions.getByLabel('Replacement deposit date',{exact:true}).fill('2026-09-29');await instructions.getByLabel('New replacement allocation filename',{exact:true}).fill('reviewed_browser_replacement_2026.csv');await instructions.getByLabel('Replacement provider instruction reference',{exact:true}).fill('Verified actual provider replacement instructions after complete participant reversal')
  await expect(async()=>{await instructions.getByRole('checkbox',{name:'I verified that the provider requires a new allocation, prior allocations were fully reversed, no outside replacement exists, and late correction has been reviewed.',exact:true}).check({timeout:5000})}).toPass({timeout:10000});await instructions.getByRole('button',{name:'Verify replacement contribution instructions',exact:true}).click()
  await expect(instructions).toContainText('Verified instruction preview');await expect(instructions).toContainText('Original withholding date: 2026-09-18');await expect(instructions).toContainText('Replacement deposit: 2026-09-29');expect(server.state.created).toBe(1);expect(provider.posts()).toBe(1)
  const approvals=instructions.getByRole('region',{name:`Replacement authorization history ${f.remittanceId}`,exact:true})
  await approvals.getByRole('checkbox',{name:'I authorize automatic allocation-file delivery and replacement funding under these verified instructions.',exact:true}).check();await approvals.getByRole('button',{name:'Authorize replacement contribution',exact:true}).click();await approvals.getByRole('button',{name:'Retry original replacement authorization',exact:true}).click();await expect(approvals).toContainText('AUTHORIZED — NOT STARTED');expect(authorizationRequests).toHaveLength(2);expect(authorizationRequests[0]).toEqual(authorizationRequests[1])
  await approvals.getByRole('textbox',{name:'Replacement cancellation reason',exact:true}).fill('Recheck the replacement before starting any new allocation or bank payment');await approvals.getByRole('checkbox',{name:'I confirm cancellation before replacement processing starts.',exact:true}).check();await approvals.getByRole('button',{name:'Cancel unstarted replacement',exact:true}).click();await expect(approvals).toContainText('CANCELLED')
  expect((await f.api(`/retirement-remittance-authorizations/${f.remittanceId}/replacement-authorizations`)).history).toHaveLength(1);expect(provider.posts()).toBe(1);expect(server.state.created).toBe(1)
  await instructions.getByLabel('New replacement allocation filename',{exact:true}).fill('reviewed_browser_replacement_second_2026.csv')
  await expect(async()=>{await instructions.getByRole('checkbox',{name:'I verified that the provider requires a new allocation, prior allocations were fully reversed, no outside replacement exists, and late correction has been reviewed.',exact:true}).check({timeout:5000})}).toPass({timeout:10000});await instructions.getByRole('button',{name:'Verify replacement contribution instructions',exact:true}).click();await expect(instructions).toContainText('Verified instruction preview')
  await approvals.getByRole('checkbox',{name:'I authorize automatic allocation-file delivery and replacement funding under these verified instructions.',exact:true}).check();await approvals.getByRole('button',{name:'Authorize replacement contribution',exact:true}).click();await expect(approvals).toContainText('AUTHORIZED — NOT STARTED')
  const automaticOptions={facility:1,fetcher:accounting.fetcher,paymentFetcher:provider.fetcher,reader:(c,r)=>readRetirementSftpReceipt(c,r,server.options),transfer:(c,file,options)=>transferRetirementAllocation(c,file,{...server.options,...options}),dispatchNow:()=>new Date('2026-09-25T15:00:00Z')},automaticStart=new Date(),retainedReceipt=server.files.get(f.remotePath)
  server.files.set(f.remotePath,Buffer.from('changed receipt blocks automatic first submission'))
  expect((await runRetirementReplacementAllocationSweep(h.pool,{...automaticOptions,now:automaticStart})).attempted).toBe(1);expect(server.state.created).toBe(1)
  await approvals.getByRole('button',{name:'Refresh replacement history',exact:true}).click();await expect(approvals).toContainText('BLOCKED')
  server.files.set(f.remotePath,retainedReceipt)
  expect((await runRetirementReplacementAllocationSweep(h.pool,{...automaticOptions,now:new Date(+automaticStart+360000)})).verified).toBe(1)
  await expect(approvals).toContainText('Allocation file: REMOTE FILE VERIFIED',{timeout:40000});await expect(approvals).toContainText('Latest file observation: automatic check');await expect(approvals).toContainText('Automatic replacement file attempts (2)');expect((await h.pool.query("SELECT title FROM payroll_alert WHERE dedupe_key LIKE 'retirement-replacement-file-%'")).rows[0].title).toBe('Replacement allocation requires receipt review');expect(server.state.created).toBe(2);expect(provider.posts()).toBe(1)
  const replacement=(await f.api(`/retirement-remittance-authorizations/${f.remittanceId}/replacement-authorizations`)).history.find(x=>!x.cancelled_at),replacementBank=retirementReplacementBankProvider(provider.fetcher,replacement.id);replacementFetcher=replacementBank.fetcher
  const bankOptions={...automaticOptions,paymentFetcher:replacementBank.fetcher},bankStart=new Date()
  expect((await runRetirementReplacementBankSweep(h.pool,{...bankOptions,now:bankStart})).attempted).toBe(1)
  await approvals.getByRole('button',{name:'Refresh replacement history',exact:true}).click();await expect(approvals).toContainText('Bank payment: UNCERTAIN');await expect(approvals).toContainText('Latest bank observation: automatic check')
  expect((await runRetirementReplacementBankSweep(h.pool,{...bankOptions,now:new Date(+bankStart+360000)})).attempted).toBe(1)
  await approvals.getByRole('button',{name:'Refresh replacement history',exact:true}).click();await expect(approvals).toContainText('Bank payment: SENT');expect(replacementBank.posts()).toBe(1)
  replacementBank.complete();expect((await runRetirementReplacementBankSweep(h.pool,{...bankOptions,now:new Date(+bankStart+720000)})).verified).toBe(1)
  await approvals.getByRole('button',{name:'Refresh replacement history',exact:true}).click();await expect(approvals).toContainText('Settlement: BANK POSTED');await expect(approvals).toContainText('Automatic replacement bank attempts (3)');expect(replacementBank.posts()).toBe(1)
  const receiptLocation=approvals.getByRole('region',{name:`Retirement receipt location ${replacement.id}`,exact:true})
  await receiptLocation.getByRole('button',{name:'Load receipt location history',exact:true}).click();await expect(receiptLocation).toContainText('Original allocation: reviewed_browser_replacement_second_2026.csv')
  await receiptLocation.getByRole('combobox',{name:'Retained receipt interpretation contract',exact:true}).selectOption(saved.id,{timeout:10000});await receiptLocation.getByRole('textbox',{name:'Receipt directory',exact:true}).fill(f.bindingBody.directory);await receiptLocation.getByRole('textbox',{name:'Receipt CSV filename',exact:true}).fill('replacement_participant_receipt.csv');await receiptLocation.getByRole('textbox',{name:'Receipt location review reference',exact:true}).fill('Verified provider receipt for the replacement allocation and exact participant amounts')
  await receiptLocation.getByRole('checkbox',{name:'I verified this receipt path and retained contract refer to the exact original allocation file and its participant amounts.',exact:true}).check();await receiptLocation.getByRole('checkbox',{name:'I confirm this receipt location action and reviewed evidence.',exact:true}).check();await receiptLocation.getByRole('button',{name:'Save receipt location',exact:true}).click();await expect(receiptLocation).toContainText('Receipt location: BOUND · revision 1')
  expect((await f.api(f.bindingPath)).history[0].id).toBe(f.bindingId)
  const replacementReceiptRemote=f.bindingBody.directory+'/replacement_participant_receipt.csv',replacementAllocationBytes=server.files.get(server.config.deliveryDirectory+'/reviewed_browser_replacement_second_2026.csv')
  server.files.set(replacementReceiptRemote,f.receipt({sourceFileName:'reviewed_browser_replacement_second_2026.csv',sourceSha256:createHash('sha256').update(replacementAllocationBytes).digest('hex'),batchId:'Synthetic replacement participant batch',recordedAt:'2026-09-29T15:00:00Z'}));remittanceClock='2026-09-30T15:00:00Z'
  const replacementOutcomes=approvals.getByRole('region',{name:`Retirement receipt outcomes ${replacement.id}`,exact:true})
  await replacementOutcomes.getByRole('button',{name:'Load receipt outcome history',exact:true}).click();await expect(replacementOutcomes).toContainText('Current receipt location: BOUND')
  const receiptCheckStart=new Date(),receiptCheckOptions={reader:(c,r)=>readRetirementSftpReceipt(c,r,server.options),receiptNow:()=>new Date(remittanceClock)}
  expect((await checkRetirementReplacementReceipts(h.pool,1,{...receiptCheckOptions,now:receiptCheckStart})).posted).toBe(1)
  await expect(replacementOutcomes).toContainText('Latest retained receipt: POSTED',{timeout:40000});await expect(replacementOutcomes).toContainText('Automatic check');await expect(replacementOutcomes).toContainText('posted $14.00');await expect(replacementOutcomes).not.toContainText('PRIVATE-PARTICIPANT')
  await approvals.getByRole('button',{name:'Recover replacement bank payment',exact:true}).click();await expect(approvals).toContainText('Settlement: BANK POSTED')
  const replacementAssessment=approvals.getByRole('region',{name:`Replacement reconciliation ${replacement.id}`,exact:true})
  await replacementAssessment.getByRole('button',{name:'Review replacement reconciliation',exact:true}).click();await expect(replacementAssessment).toContainText('Replacement delivery: MATCHED');await expect(replacementAssessment).toContainText('Replacement accounting: REQUIRED');await expect(replacementAssessment).toContainText('Assessment: REVIEW REQUIRED · Case: OPEN');await expect(replacementAssessment).toContainText('Receipt-confirmed participant credit: $14.00');await expect(replacementAssessment).not.toContainText('PRIVATE-PARTICIPANT')
  employeePage=await page.context().newPage();employeePage.on('pageerror',e=>errors.push(e.message));await employeePage.addInitScript(()=>sessionStorage.setItem('vortex_payroll_employee_session_v1','monthly-benefits-session'))
  await employeePage.route('**/api/payroll/employee/**',async route=>{const u=new URL(route.request().url()),r=await route.fetch({url:`${h.url}${u.pathname}${u.search}`});await route.fulfill({response:r})})
  await employeePage.goto('/tests/support/payroll.html?employee=1');await employeePage.getByRole('button',{name:'Pay statements',exact:true}).click()
  const employeeContributions=employeePage.getByRole('region',{name:'My retirement contributions',exact:true})
  await expect(employeeContributions).toContainText('Confirmed replacement credit: $14.00');await expect(employeeContributions).toContainText('Original receipt status: REVIEW REQUIRED');await expect(employeeContributions).toContainText('Your original return case remains open');await expect(employeeContributions).not.toContainText('PRIVATE-PARTICIPANT');await expect(employeeContributions).not.toContainText('Synthetic replacement participant batch')
  const replacementAccounting=approvals.getByRole('region',{name:`Replacement settlement accounting ${replacement.id}`,exact:true})
  await replacementAccounting.getByRole('button',{name:'Prepare replacement accounting preview',exact:true}).click();await expect(replacementAccounting).toContainText('Payroll journal 99 · Return journal 101');await expect(replacementAccounting).toContainText('Debit account 7: $14.00');await expect(replacementAccounting).toContainText('Credit account 8: $14.00')
  await replacementAccounting.getByRole('textbox',{name:'Replacement accounting review reference',exact:true}).fill('Reviewed original return and replacement bank journals with no outside duplicate accounting')
  await replacementAccounting.getByRole('checkbox',{name:'I reviewed these exact journals and outside accounting, found no duplicate entries, and authorize automatic posting.',exact:true}).check()
  await replacementAccounting.getByRole('button',{name:'Authorize replacement accounting',exact:true}).click();await expect(replacementAccounting).toContainText('AUTHORIZED — AWAITING AUTOMATIC POSTING')
  const settlementOptions={facility:1,fetcher:accounting.fetcher,paymentFetcher:replacementBank.fetcher},settlementStart=new Date();accounting.loseNextResponse()
  expect((await runRetirementReplacementSettlementSweep(h.pool,{...settlementOptions,now:settlementStart})).attempted).toBe(1)
  await replacementAccounting.getByRole('button',{name:'Refresh replacement accounting history',exact:true}).click();await expect(replacementAccounting).toContainText('UNCERTAIN');expect(accounting.posts()).toBe(3)
  expect((await runRetirementReplacementSettlementSweep(h.pool,{...settlementOptions,now:new Date(+settlementStart+360000)})).synced).toBe(1)
  await replacementAccounting.getByRole('button',{name:'Refresh replacement accounting history',exact:true}).click();await expect(replacementAccounting).toContainText('SYNCED · Sources VERIFIED');await expect(replacementAccounting).toContainText('Automatic replacement accounting attempts (2)')
  await replacementAssessment.getByRole('button',{name:'Review replacement reconciliation',exact:true}).click();await expect(replacementAssessment).toContainText('Replacement accounting: MATCHED');await expect(replacementAssessment).toContainText('Case: CLOSED');expect(accounting.posts()).toBe(3)
  await employeeContributions.getByRole('button',{name:'Refresh retirement contributions',exact:true}).click();await expect(employeeContributions).toContainText('Replacement accounting: reconciled.');await expect(employeeContributions).toContainText('Your original return case is reconciled.');await expect(employeeContributions).not.toContainText('Your original return case remains open')
  await assessment.getByRole('button',{name:'Review contribution reconciliation',exact:true}).click();await expect(assessment).toContainText('Return case: CLOSED');await expect(assessment).toContainText('Assessment: REPLACEMENT RECONCILED');await expect(instructions).toContainText('The replacement and original return currently reconcile.');await expect(instructions.getByRole('button',{name:'Verify replacement contribution instructions',exact:true})).toBeDisabled()
  const caseHistory=assessment.getByRole('region',{name:'Contribution assessment history',exact:true});await caseHistory.getByRole('button',{name:'Refresh latest contribution history',exact:true}).click();await expect(caseHistory).toContainText('Recorded outcome: REPLACEMENT RECONCILED')
  await employeePage.setViewportSize({width:390,height:1100});await employeeContributions.screenshot({path:'/tmp/payroll-employee-replacement-credit-mobile.png'});expect(await employeePage.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  const postedReplacementJournal=accounting.journal('102');accounting.setJournal('102',null)
  await replacementAccounting.getByRole('button',{name:'Recover replacement journals',exact:true}).click();await expect(replacementAccounting).toContainText('NOT FOUND');expect(accounting.posts()).toBe(3)
  await replacementAssessment.getByRole('button',{name:'Review replacement reconciliation',exact:true}).click();await expect(replacementAssessment).toContainText('Replacement accounting: REVIEW REQUIRED');accounting.setJournal('102',postedReplacementJournal)
  await assessment.getByRole('button',{name:'Review contribution reconciliation',exact:true}).click();await expect(assessment).toContainText('Return case: OPEN');await employeeContributions.getByRole('button',{name:'Refresh retirement contributions',exact:true}).click();await expect(employeeContributions).toContainText('Your original return case remains open');await caseHistory.getByRole('button',{name:'Refresh latest contribution history',exact:true}).click();await expect(caseHistory).toContainText('Recorded outcome: REVIEW REQUIRED');await expect(caseHistory).toContainText('Recorded outcome: REPLACEMENT RECONCILED')
  await replacementAccounting.getByRole('button',{name:'Recover replacement journals',exact:true}).click();await expect(replacementAccounting).toContainText('SYNCED · Sources VERIFIED')
  await assessment.getByRole('button',{name:'Review contribution reconciliation',exact:true}).click();await expect(assessment).toContainText('Return case: CLOSED')
  replacementBank.missing(true);await approvals.getByRole('button',{name:'Recover replacement bank payment',exact:true}).click();await expect(approvals).toContainText('Bank payment: NOT FOUND');expect(replacementBank.posts()).toBe(1)
  await replacementAssessment.getByRole('button',{name:'Review replacement reconciliation',exact:true}).click();await expect(replacementAssessment).toContainText('Bank: UNVERIFIED');await expect(replacementAssessment).toContainText('Replacement delivery: UNVERIFIED')
  await employeeContributions.getByRole('button',{name:'Refresh retirement contributions',exact:true}).click();await expect(employeeContributions).toContainText('Replacement credit needs review.');await expect(employeeContributions).not.toContainText('Confirmed replacement credit: $14.00')
  server.files.delete(replacementReceiptRemote);expect((await checkRetirementReplacementReceipts(h.pool,1,{...receiptCheckOptions,now:new Date(+receiptCheckStart+25*3600000)})).checked).toBe(1);await replacementOutcomes.getByRole('button',{name:'Load receipt outcome history',exact:true}).click();await expect(replacementOutcomes).toContainText('Latest retained receipt: RECEIPT NOT FOUND');await expect(replacementOutcomes).toContainText('Earlier receipt: POSTED');await expect(panel).toContainText('Latest retained receipt: REVERSED');expect(replacementBank.posts()).toBe(1)
  await replacementAssessment.getByRole('button',{name:'Review replacement reconciliation',exact:true}).click();await expect(replacementAssessment).toContainText('Participants: UNVERIFIED');await expect(replacementAssessment).not.toContainText('Receipt-confirmed participant credit: $14.00')
  server.files.delete(server.config.deliveryDirectory+'/reviewed_browser_replacement_second_2026.csv')
  await approvals.getByRole('button',{name:'Recover replacement allocation file',exact:true}).click();await expect(approvals).toContainText('Allocation file: REMOTE FILE NOT FOUND');expect(server.state.created).toBe(2);expect(provider.posts()).toBe(1)

  provider.creditValid(false);await f.api(bankPath,{action:'RECOVER',confirmed:true});await assessment.getByRole('button',{name:'Review contribution reconciliation',exact:true}).click();await expect(assessment).toContainText('Replacement review: EVIDENCE REQUIRED');await expect(assessment).not.toContainText('Confirmed reversed allocations: $14.00');await expect(instructions).not.toContainText('Verified instruction preview');await expect(instructions.getByRole('button',{name:'Verify replacement contribution instructions',exact:true})).toBeDisabled();expect(accounting.posts()).toBe(3)
  await page.setViewportSize({width:390,height:1100});expect(await receiptLocation.evaluate(root=>{const bounds=root.getBoundingClientRect();return [...root.querySelectorAll('button,select,textarea,input')].filter(el=>el.getClientRects().length>0).every(el=>{const r=el.getBoundingClientRect();return r.left>=bounds.left&&r.right<=bounds.right+1})})).toBe(true);await receiptLocation.screenshot({path:'/tmp/payroll-retirement-replacement-receipt-location-mobile.png'});expect(await replacementAccounting.evaluate(root=>root.getBoundingClientRect().width)).toBeGreaterThanOrEqual(280);expect(await receiptLocation.evaluate(root=>root.getBoundingClientRect().width)).toBeGreaterThanOrEqual(280);expect(await replacementAccounting.getByRole('button',{name:'Recover replacement journals',exact:true}).evaluate(root=>root.getBoundingClientRect().height)).toBeGreaterThanOrEqual(44);await replacementAccounting.screenshot({path:'/tmp/payroll-retirement-replacement-accounting-mobile.png'});await assessment.screenshot({path:'/tmp/payroll-retirement-replacement-evidence-mobile.png'});await panel.screenshot({path:'/tmp/payroll-retirement-participant-reversal-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(errors).toEqual([])
 }finally{await employeePage?.close().catch(()=>{});await page.unrouteAll({behavior:'ignoreErrors'}).catch(()=>{});await page.close().catch(()=>{});await h.close();await server.close();if(old===undefined)delete process.env.PAYROLL_DOCUMENT_KEY;else process.env.PAYROLL_DOCUMENT_KEY=old}
})
