import {test,expect} from '@playwright/test'
import {randomUUID} from 'node:crypto'
import {createHarness} from '../../backend/payroll/testing/harness.js'
import {carrierInvoiceHistoryFixture} from '../../backend/payroll/testing/carrierInvoiceHistoryFixture.js'
test('admin reviews, retries, replaces and revokes a carrier remittance recipient internally',async({page})=>{
 test.setTimeout(90000);page.setDefaultTimeout(10000);test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const oldKey=process.env.PAYROLL_DOCUMENT_KEY;process.env.PAYROLL_DOCUMENT_KEY='29'.repeat(32)
 const h=await createHarness();let loseResponse=true,failRead=false
 try{
  const {api,invoice}=await carrierInvoiceHistoryFixture(h),path=`/benefit-carrier-invoices/${invoice.id}/remittance-recipient`,errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'));await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());if(failRead&&u.pathname.endsWith('/remittance-recipient')&&route.request().method()==='GET')return route.fulfill({status:503,json:{success:false,message:'Synthetic recipient read unavailable'}});const response=await route.fetch({url:`${h.url}${u.pathname}${u.search}`});if(loseResponse&&u.pathname.endsWith('/remittance-recipient')&&route.request().method()==='POST'){loseResponse=false;return route.fulfill({status:503,json:{success:false,message:'Synthetic lost review response'}})}await route.fulfill({response})})
  await page.setViewportSize({width:390,height:1200});await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Reports & QuickBooks',exact:true}).click();const invoices=page.getByRole('region',{name:'Carrier invoice reconciliation',exact:true});await invoices.getByLabel('Carrier coverage month',{exact:true}).fill('2026-09');await invoices.getByRole('button',{name:'Load carrier invoices',exact:true}).click();await invoices.getByText('Prepare carrier payment',{exact:true}).click();await invoices.getByText('Carrier remittance recipient',{exact:true}).click()
  const panel=invoices.getByRole('region',{name:'Carrier remittance recipient review',exact:true});await panel.getByRole('button',{name:'Load carrier recipient',exact:true}).click();await expect(panel).toContainText('No reviewed recipient');await panel.getByLabel('Remittance contact name',{exact:true}).fill('Benefits contact');await panel.getByLabel('Remittance contact email',{exact:true}).fill('Advice@EXAMPLE.COM');await panel.getByLabel('Recipient verification reference',{exact:true}).fill('Independent carrier telephone verification for payment advice');await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'Save carrier recipient review',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('Synthetic lost review response');await panel.getByRole('button',{name:'Save carrier recipient review',exact:true}).click();await expect(panel).toContainText('The earlier request was retained.');expect((await api(path)).history.length).toBe(1)
  await panel.getByLabel('Remittance contact email',{exact:true}).fill('draft@example.com');await panel.getByLabel('Recipient verification reference',{exact:true}).fill('Another independently verified recipient contact');await panel.getByRole('checkbox').check();await api(path,{action:'REVIEW',expectedRevision:1,requestKey:randomUUID(),confirmed:true,name:'Other admin contact',email:'other@example.com',reference:'Other admin independently verified the replacement contact'});await panel.getByRole('button',{name:'Save carrier recipient review',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('The carrier recipient changed');await expect(panel.getByLabel('Remittance contact email',{exact:true})).toHaveValue('draft@example.com');await expect(panel.getByRole('button',{name:'Save carrier recipient review',exact:true})).toBeDisabled()
  await panel.getByRole('button',{name:'Reload recipient and replace draft',exact:true}).click();await expect(panel.getByLabel('Remittance contact email',{exact:true})).toHaveValue('other@example.com');await panel.getByLabel('Recipient action',{exact:true}).selectOption('REVOKE');await panel.getByLabel('Recipient verification reference',{exact:true}).fill('Carrier confirmed this recipient should no longer receive advice');await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'Revoke carrier recipient',exact:true}).click();await expect(panel).toContainText('Recipient revoked.');await panel.getByText('Recipient review history',{exact:true}).click();await expect(panel.locator('article')).toHaveCount(3);await expect(panel.locator('article').last()).toContainText('A***@example.com')
  failRead=true;await panel.getByRole('button',{name:'Reload recipient and replace draft',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('Synthetic recipient read unavailable');await expect(panel.getByLabel('Remittance contact name',{exact:true})).toBeDisabled();failRead=false;await panel.getByRole('button',{name:'Reload recipient and replace draft',exact:true}).click();await expect(panel.getByRole('alert')).toHaveCount(0);await expect(panel.getByLabel('Remittance contact name',{exact:true})).toBeEnabled();await panel.screenshot({path:'/tmp/payroll-carrier-recipient-mobile.png'});expect(errors).toEqual([])
 }finally{await page.unrouteAll({behavior:'wait'}).catch(()=>{});await page.close().catch(()=>{});await h.close();if(oldKey===undefined)delete process.env.PAYROLL_DOCUMENT_KEY;else process.env.PAYROLL_DOCUMENT_KEY=oldKey}
})
