import {test,expect} from '@playwright/test'
import {createHarness} from '../../backend/payroll/testing/harness.js'
import {monthlyBenefitsFixture} from '../../backend/payroll/testing/monthlyBenefitsFixture.js'
test('admin collects a monthly benefit contribution and employee statement identifies it once',async({page})=>{
 test.setTimeout(90000);page.setDefaultTimeout(15000);test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness();try{
 const {api,employee,periods}=await monthlyBenefitsFixture(h)
 await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
 for(const prefix of ['admin/payroll','payroll/employee'])await page.route(`**/api/${prefix}/**`,async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
 await page.setViewportSize({width:390,height:1200});await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Payroll runs',exact:true}).click()
 await page.getByRole('combobox',{name:'Pay period',exact:true}).selectOption(String(periods[0].id));await page.getByRole('button',{name:'Preview payroll',exact:true}).click()
 const collection=page.getByRole('region',{name:'Monthly benefit deductions',exact:true})
 await expect(collection.getByText('$125.00 deducted in this payroll.',{exact:true})).toBeVisible()
 await collection.screenshot({path:'/tmp/payroll-monthly-benefit-collection-mobile.png'})
 await page.getByRole('button',{name:'Save draft snapshot',exact:true}).click()
 await page.getByRole('row').filter({hasText:'Sep 18, 2026'}).getByRole('button',{name:'Open review',exact:true}).click()
 await page.getByRole('button',{name:'Send to review',exact:true}).click();await page.getByRole('button',{name:'Approve run',exact:true}).click()
 await page.getByRole('textbox',{name:'External payment confirmation',exact:true}).fill('SYNTHETIC-MONTHLY-BENEFIT-PAYMENT')
 await page.getByRole('button',{name:'Confirm paid & finalize',exact:true}).click();await expect(page.getByText('Payroll finalized and employee statements saved.',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Reports & QuickBooks',exact:true}).click()
 await page.getByRole('button',{name:'Review retained wage bases',exact:true}).click()
 const wageBases=page.getByRole('region',{name:'Retained payroll wage bases',exact:true})
 await expect(wageBases.getByText('Finalized wage bases reconcile.',{exact:true})).toBeVisible()
 await expect(wageBases.getByText('Social Security taxable wages: $200.00',{exact:true})).toBeVisible()
 await expect(wageBases.getByText('Federal wage input: $200.00',{exact:true})).toBeVisible()
 await expect(wageBases.getByText('Maryland wage input: $200.00',{exact:true})).toBeVisible()
 await wageBases.screenshot({path:'/tmp/payroll-wage-bases-mobile.png'})
 const summaryDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download employee summary',exact:true}).click()
 const summaryStream=await (await summaryDownload).createReadStream();let summaryCsv='';for await(const chunk of summaryStream!)summaryCsv+=chunk.toString()
 expect(summaryCsv).toContain('Retained Social Security taxable wages');expect(summaryCsv).toContain('200.00,200.00,0.00,1,RECONCILED FINALIZED WAGE BASES')
 await h.pool.query('UPDATE payroll_run_employee SET social_security_tax_cents=social_security_tax_cents+1,federal_income_tax_cents=federal_income_tax_cents+1 WHERE employee_id=$1',[employee.id])
 await page.getByRole('button',{name:'Review retained wage bases',exact:true}).click()
 await expect(wageBases.getByText('Wage totals unavailable — review required.',{exact:true})).toBeVisible()
 await expect(wageBases).toContainText('posted taxes do not reconcile')
 await expect(wageBases.getByText('Income-tax wage totals unavailable — review required.',{exact:true})).toBeVisible()
 await expect(wageBases.getByText('Federal wage input: $200.00',{exact:true})).toHaveCount(0)
 await expect(wageBases.getByText('Social Security taxable wages: $200.00',{exact:true})).toHaveCount(0)
 await h.pool.query('UPDATE payroll_run_employee SET social_security_tax_cents=social_security_tax_cents-1,federal_income_tax_cents=federal_income_tax_cents-1 WHERE employee_id=$1',[employee.id])
 await page.getByRole('button',{name:'Payroll runs',exact:true}).click()
 await page.getByRole('row').filter({hasText:'Sep 18, 2026'}).getByRole('button',{name:'Open review',exact:true}).click()
 const incomeReview=page.getByRole('region',{name:'Review finalized income-tax wages',exact:true})
 await incomeReview.getByRole('button',{name:'Review income-tax wages',exact:true}).click()
 await expect(incomeReview.getByText('No wage reviews recorded.',{exact:true})).toBeVisible()
 await incomeReview.getByLabel('Federal wages ($)',{exact:true}).fill('200.001')
 await incomeReview.getByLabel('Maryland wages ($)',{exact:true}).fill('199.99')
 await incomeReview.getByLabel('Wage calculation reference',{exact:true}).fill('Synthetic reviewed Maryland wage worksheet')
 await incomeReview.getByRole('checkbox').check()
 await expect(incomeReview.getByRole('button',{name:'Save income-tax wage review',exact:true})).toBeDisabled()
 await incomeReview.getByLabel('Federal wages ($)',{exact:true}).fill('200.00')
 await incomeReview.getByRole('checkbox').check()
 await h.pool.query('UPDATE payroll_run_employee SET federal_income_tax_cents=federal_income_tax_cents+1 WHERE employee_id=$1',[employee.id])
 await incomeReview.getByRole('button',{name:'Save income-tax wage review',exact:true}).click()
 await expect(incomeReview.getByRole('alert')).toContainText('Payroll evidence changed')
 await expect(incomeReview.getByRole('button',{name:'Save income-tax wage review',exact:true})).toHaveCount(0)
 await h.pool.query('UPDATE payroll_run_employee SET federal_income_tax_cents=federal_income_tax_cents-1 WHERE employee_id=$1',[employee.id])
 await incomeReview.getByRole('button',{name:'Review income-tax wages',exact:true}).click()
 await incomeReview.getByLabel('Federal wages ($)',{exact:true}).fill('200.00')
 await incomeReview.getByLabel('Maryland wages ($)',{exact:true}).fill('199.99')
 await incomeReview.getByLabel('Wage calculation reference',{exact:true}).fill('Synthetic reviewed Maryland wage worksheet')
 await incomeReview.getByRole('checkbox').check()
 await incomeReview.getByRole('button',{name:'Save income-tax wage review',exact:true}).click()
 await expect(incomeReview.getByRole('status')).toContainText('Wage review saved.')
 await expect(incomeReview).toContainText('CURRENT · Review')
 await expect(incomeReview).toContainText('Federal $200.00 · Maryland $199.99')
 await incomeReview.screenshot({path:'/tmp/payroll-income-review-mobile.png'})
 await page.getByRole('button',{name:'Reports & QuickBooks',exact:true}).click()
 await page.getByRole('button',{name:'Review retained wage bases',exact:true}).click()
 await expect(wageBases.getByText('RECONCILED INCOME-TAX WAGE BASES (1 reviewed record)',{exact:true})).toBeVisible()
 await expect(wageBases.getByText('Maryland wage input: $199.99',{exact:true})).toBeVisible()
 await h.pool.query('UPDATE payroll_run_employee SET federal_income_tax_cents=federal_income_tax_cents+1 WHERE employee_id=$1',[employee.id])
 await page.getByRole('button',{name:'Review retained wage bases',exact:true}).click()
 await expect(wageBases).toContainText('saved income-tax wage review is stale or inconsistent')
 await expect(wageBases.getByText('Maryland wage input: $199.99',{exact:true})).toHaveCount(0)
 await h.pool.query('UPDATE payroll_run_employee SET federal_income_tax_cents=federal_income_tax_cents-1 WHERE employee_id=$1',[employee.id])
 await page.getByLabel('Report end date',{exact:true}).fill('2025-12-31')
 await expect(wageBases).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Review retained wage bases',exact:true})).toBeDisabled()
 await page.getByLabel('Report start date',{exact:true}).fill('2025-01-01')
 await page.getByRole('button',{name:'Review retained wage bases',exact:true}).click()
 await expect(wageBases.getByText('No finalized or imported employee payments in this range.',{exact:true})).toBeVisible()
 const invitation=await api(`/employees/${employee.id}/invitations`,{email:'monthly-benefits@example.test',sendEmail:false},'POST',201)
 await page.goto(`/employee/payroll?invite=${new URL(invitation.inviteUrl).searchParams.get('invite')}`);await page.getByRole('button',{name:'Pay statements',exact:true}).click()
 const history=page.getByRole('region',{name:'My benefit contributions',exact:true})
 await history.getByLabel('Contribution payment year').fill('2026')
 await expect(history.getByText('Collected in 2026: $125.00',{exact:true})).toBeVisible()
 await expect(history.getByText('Medical · Family',{exact:true})).toBeVisible()
 await expect(history.getByText(`Paid 2026-09-18 · Payroll 1`,{exact:true})).toBeVisible()
 await history.screenshot({path:'/tmp/payroll-employee-benefit-history-mobile.png'})
 await history.getByLabel('Contribution payment year').fill('2025')
 await expect(history.getByText('No finalized benefit contributions in this year.',{exact:true})).toBeVisible()
 await expect(history.getByText('Medical · Family',{exact:true})).toHaveCount(0)
 await history.getByLabel('Contribution payment year').fill('2026')
 await expect(history.getByText('Collected in 2026: $125.00',{exact:true})).toBeVisible()
 await h.pool.query('UPDATE payroll_run_employee SET posttax_deduction_cents=12501 WHERE employee_id=$1',[employee.id])
 await history.getByRole('button',{name:'Refresh contributions',exact:true}).click()
 await expect(history.getByRole('alert')).toHaveText('Your benefit contributions need payroll review. Contact your hiring administrator.')
 await expect(history.getByText('Collected in 2026: $125.00',{exact:true})).toHaveCount(0)
 await h.pool.query('UPDATE payroll_run_employee SET posttax_deduction_cents=12500 WHERE employee_id=$1',[employee.id])
 await history.getByRole('button',{name:'Refresh contributions',exact:true}).click()
 await expect(history.getByText('Collected in 2026: $125.00',{exact:true})).toBeVisible()
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download itemized pay statement (PDF)',exact:true}).click();await (await download).saveAs('/tmp/payroll-monthly-benefit-statement.pdf')
 await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Payroll runs',exact:true}).click()
 await page.getByRole('combobox',{name:'Pay period',exact:true}).selectOption(String(periods[1].id));await page.getByRole('button',{name:'Preview payroll',exact:true}).click()
 await expect(collection).toContainText('No second deduction this month.')
 await collection.screenshot({path:'/tmp/payroll-monthly-benefit-already-collected-mobile.png'})
 }finally{await page.unrouteAll({behavior:'wait'});await page.close();await h.close()}
})

for(const effectiveOn of ['2026-09-10','2026-09-20'])test(`payroll explains reviewed coverage effective ${effectiveOn} and blocks an unreviewed change`,async({page})=>{
 test.skip(!process.env.PAYROLL_TEST_DATABASE_URL,'Requires isolated payroll database')
 const h=await createHarness();try{
 const {api,employee,periods}=await monthlyBenefitsFixture(h)
 let packet=await api('/onboarding',undefined,'GET',200,true)
 packet=await api('/benefits-election',{choice:'WAIVE',signature:'Monthly Benefits',confirmed:true,displayedTerms:packet.policy.benefitsText,requestKey:'monthly-waiver-browser',selections:[{planId:'medical',optionId:'WAIVE'}],onboardingCycle:1},'POST',200,true)
 await page.addInitScript(()=>localStorage.setItem('adminToken','payroll-test-admin'))
 await page.route('**/api/admin/payroll/**',async route=>{const u=new URL(route.request().url());await route.fulfill({response:await route.fetch({url:`${h.url}${u.pathname}${u.search}`})})})
 await page.setViewportSize({width:390,height:1200});await page.goto('/tests/support/payroll.html');await page.getByRole('button',{name:'Payroll runs',exact:true}).click()
 await page.getByRole('combobox',{name:'Pay period',exact:true}).selectOption(String(periods[0].id));await page.getByRole('button',{name:'Preview payroll',exact:true}).click()
 await expect(page.getByText('Review the changed benefit election before removing previously authorized contributions from payroll.',{exact:false})).toBeVisible()
 const task=packet.tasks.find((t:{task_key:string})=>t.task_key==='PAY_REVIEW')
 await api(`/employees/${employee.id}/onboarding/${task.id}/review`,{status:'COMPLETE',note:'Reviewed employee waiver and coverage outcome',paySetupFingerprint:packet.paySetup.fingerprint,benefitsReview:{disposition:'WAIVED',effectiveOn,summary:`Reviewed employee waiver effective ${effectiveOn}.`,evidenceReference:'Synthetic carrier waiver confirmation',confirmed:true}})
 await page.getByRole('button',{name:'Preview payroll',exact:true}).click()
 const collection=page.getByRole('region',{name:'Monthly benefit deductions',exact:true})
 if(effectiveOn==='2026-09-10'){await expect(collection).toContainText('No employee benefit contribution is due under the applicable reviewed coverage.');await expect(collection).toContainText('Effective 2026-09-10 · waived')}else{await expect(collection).toContainText('$125.00 deducted in this payroll.');await expect(collection).toContainText('Retained coverage applies before the change on 2026-09-20')}
 await collection.screenshot({path:`/tmp/payroll-reviewed-benefit-${effectiveOn}-mobile.png`})
 }finally{await page.unrouteAll({behavior:'wait'});await page.close();await h.close()}
})
