import { expect, test, type Page } from '@playwright/test'

// This suite uses the real routes, workflow and UI with explicitly synthetic source/model rows.
// Start tests/support/workoutProgrammingPreviewServer.mjs and opt in; never target a live facility.
test.skip(process.env.VORTEX_PROGRAMMING_SYNTHETIC_PREVIEW !== '1', 'Requires the isolated programming preview server')
test.describe.configure({ mode: 'serial' })
const endpoint = '/api/coach/workout-programming'
const session = (page: Page) => page.getByRole('region', { name: 'Generated programming session' })

test.beforeEach(async ({ page, request }) => {
  const reset = await request.post('/__preview/reset')
  expect(reset.ok()).toBeTruthy()
  await page.goto('/tests/fixtures/workout-programming.html')
  await expect(page.getByText('Local verification · synthetic athletes, library and model responses')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Generate & review session' })).toBeEnabled()
})

async function configureGroup(page: Page) {
  for (const [label, value] of [['Athletes', '15'], ['Youngest age', '12'], ['Oldest age', '14'], ['Coaches', '2'],
    ['Floor area (sq ft)', '2000'], ['Lane length (ft)', '100']]) await page.getByRole('spinbutton', { name: label, exact: true }).fill(value)
  await page.getByLabel('Training experience').selectOption('intermediate')
}

async function generate(page: Page, button = 'Generate & review session') {
  const response = page.waitForResponse((response) => response.url().endsWith(endpoint) && response.request().method() === 'POST')
  await page.getByRole('button', { name: button, exact: true }).click()
  const completed = await response
  expect(completed.status()).toBe(200)
  return (await completed.json()).data
}

async function interpret(page: Page) {
  const response = page.waitForResponse((response) => response.url().endsWith(`${endpoint}/interpret`) && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Preview instruction changes', exact: true }).click()
  const completed = await response
  expect(completed.status()).toBe(200)
  return (await completed.json()).data
}

test('canonical choices, granular controls, generation, saved history and fresh evidence remain coherent', async ({ page, request }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await configureGroup(page)
  await page.getByLabel('Coaching intent', { exact: true }).fill('Preserve movement quality and full explosive recovery.')
  await page.getByRole('checkbox', { name: 'Dumbbell', exact: true }).check()
  await page.getByRole('spinbutton', { name: 'Dumbbell quantity', exact: true }).fill('6')
  await page.getByLabel('Dumbbell preference').selectOption('preferred')
  await page.getByRole('button', { name: 'Add overall priority' }).click()
  await page.getByLabel('Weight', { exact: true }).fill('80')
  await page.getByRole('button', { name: 'Find canonical choices' }).click()
  await expect(page.getByRole('status')).toContainText('10 canonical profile choices loaded')
  const strength = page.locator('details').filter({ has: page.locator('summary', { hasText: /^Strength$/ }) })
  await strength.locator('summary').click()
  await strength.getByLabel('Locked exercises', { exact: false }).selectOption({ index: 0 })
  await strength.getByLabel('Locked methods', { exact: false }).selectOption({ index: 0 })
  const saved = await generate(page)
  await expect(session(page).getByRole('heading', { name: 'Session checks passed' })).toBeVisible()
  await expect(session(page).getByRole('heading', { level: 4 })).toHaveText(['Prepare & Access', 'Explosiveness', 'Strength', 'Capacity / Competition'])
  await expect(session(page).getByText('55:00–60:00', { exact: true })).toBeVisible()
  const state = await (await request.get('/__preview/state')).json()
  expect(state.savedCount).toBe(1)
  expect(state.lastRequest.components).toHaveLength(4)
  expect(state.lastRequest.athletes[0].athleteCount).toBe(15)
  expect(state.lastRequest.equipment.quantities.dumbbell).toBe(6)
  expect(state.lastRequest.equipment.preferred).toEqual(['dumbbell'])
  expect(state.lastRequest.priorities[0].weight).toBe(80)
  expect(state.lastRequest.components.find((component: { key: string }) => component.key === 'strength').lockedExercises).toHaveLength(1)
  const sourceHash = saved.workout.contentHash
  await session(page).getByRole('button', { name: 'Check current evidence' }).click()
  await expect(session(page).getByRole('heading', { name: 'Session checks passed' })).toBeVisible()

  await page.locator('summary').filter({ hasText: /^Saved programming sessions/ }).click()
  await page.getByRole('button', { name: 'Refresh saved sessions' }).click()
  await page.getByRole('button', { name: /Passed when saved/ }).click()
  await expect(session(page).getByRole('heading', { name: 'Saved session · check current evidence' })).toBeVisible()
  await session(page).getByRole('button', { name: 'Use controls for a new session' }).click()
  await expect(page.getByRole('checkbox', { name: 'Bodyweight', exact: true })).toBeChecked()
  await expect(page.getByRole('spinbutton', { name: 'Dumbbell quantity', exact: true })).toHaveValue('6')
  await page.getByRole('button', { name: 'Existing canonical generator', exact: true }).click()
  await page.getByRole('button', { name: 'AI session programming', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Coaching intent', exact: true })).toHaveValue('Preserve movement quality and full explosive recovery.')
  await request.post('/__preview/change-source')
  await session(page).getByRole('button', { name: 'Check current evidence' }).click()
  await expect(session(page).getByRole('heading', { name: 'Coach review needed' })).toBeVisible()
  const reopened = (await (await request.get(`${endpoint}/${saved.persistedWorkoutId}`)).json()).data
  expect(reopened.workout.contentHash).toBe(sourceHash)
  expect(reopened.workout).toEqual(saved.workout)
  expect(errors).toEqual([])
})

test('roster observation selection submits a member-bound source hash through the real reader', async ({ page, request }) => {
  await configureGroup(page)
  await page.locator('summary').filter({ hasText: /^Roster & existing observations/ }).click()
  await page.getByLabel('Group 1 roster', { exact: false }).selectOption(Array.from({ length: 15 }, (_, index) => String(101 + index)))
  await page.getByLabel('Athlete for evidence').selectOption('101')
  await page.getByRole('button', { name: 'Find observations' }).click()
  await page.getByRole('checkbox', { name: /Landing quality · 4 \/ 5/ }).check()
  await expect(page.getByText('1 source observations attached.', { exact: false })).toBeVisible()
  await generate(page)
  await expect(session(page).getByRole('heading', { name: 'Session checks passed' })).toBeVisible()
  await session(page).locator('summary').filter({ hasText: /^Station plan and start times$/ }).first().click()
  await expect(session(page).getByRole('region', { name: 'Station start times' })).toContainText('Fixture athlete 1')
  const state = await (await request.get('/__preview/state')).json()
  const attached = state.lastRequest.athletes[0].evidenceReferences
  expect(attached).toHaveLength(1)
  expect(attached[0]).toMatchObject({ memberId: '101', id: '71', kind: 'skill_progress' })
  const choices = (await (await request.get(`${endpoint}/evidence/101?kind=skill_progress&asOfDate=2026-09-13`)).json()).data
  expect(attached[0].expectedSourceHash).toBe(choices[0].sourceHash)
  expect(attached[0].expectedSourceHash).toMatch(/^[a-f0-9]{64}$/)
})

test('zero-tumbling defaults and cancellation cannot silently create a saved session', async ({ page, request }) => {
  await page.getByRole('button', { name: 'Find canonical choices' }).click()
  await expect(page.getByRole('status')).toContainText('canonical profile choices loaded')
  await configureGroup(page)
  await request.post('/__preview/delay', { data: { milliseconds: 1500 } })
  await page.getByRole('button', { name: 'Generate & review session' }).click()
  await expect(page.getByRole('button', { name: 'Generate & review session' })).toBeDisabled()
  await expect.poll(async () => (await (await request.get('/__preview/state')).json()).inFlight).toBe(1)
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Cancellation requested. Refresh saved sessions')
  await expect.poll(async () => (await (await request.get('/__preview/state')).json()).inFlight).toBe(0)
  expect((await (await request.get('/__preview/state')).json()).savedCount).toBe(0)
  await expect(page.getByRole('button', { name: 'Generate & review session' })).toBeEnabled()
  await request.post('/__preview/delay', { data: { milliseconds: 0 } })
  await generate(page)
  await expect(session(page).getByRole('heading', { name: 'Session checks passed' })).toBeVisible()
})

test('mobile controls and session content fit without horizontal scrolling', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await configureGroup(page)
  await page.getByRole('button', { name: 'Add overall priority' }).click()
  await page.getByRole('button', { name: 'Find canonical choices' }).click()
  await expect(page.getByRole('status')).toContainText('canonical profile choices loaded')
  await page.locator('summary').filter({ hasText: /^Strength$/ }).click()
  await page.getByRole('button', { name: 'Add strength priority' }).click()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await generate(page)
  await expect(session(page).getByRole('heading', { name: 'Session checks passed' })).toBeVisible()
  await session(page).locator('summary').filter({ hasText: /^Station plan and start times$/ }).first().click()
  await expect(session(page).getByRole('region', { name: 'Station start times' })).toContainText('Group 1, athlete 1')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await session(page).getByRole('heading', { name: 'Session checks passed' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/private/tmp/vortex-programming-mobile-session.png' })
})

test('adding Body Control keeps it last and requires readiness evidence before coaching', async ({ page, request }) => {
  await configureGroup(page)
  await page.getByRole('spinbutton', { name: 'Athletic minutes', exact: true }).fill('90')
  await page.getByRole('spinbutton', { name: 'Tumbling minutes', exact: true }).fill('30')
  await expect(page.getByRole('spinbutton', { name: 'Total booked minutes', exact: true })).toHaveValue('120')
  const saved = await generate(page)
  await expect(session(page).getByRole('heading', { name: 'Coach review needed' })).toBeVisible()
  expect(saved.workout.validatedWorkout).toBe(false)
  await expect(session(page).getByRole('status')).toContainText('Attach reviewed observations or choose eligible alternatives')
  const state = await (await request.get('/__preview/state')).json()
  expect(state.lastRequest.components.map((component: { key: string }) => component.key)).toEqual([
    'prepare_and_access', 'explosiveness', 'strength', 'capacity_competition', 'body_control',
  ])
  await expect(session(page).getByRole('heading', { level: 4 }).last()).toHaveText('Body Control / Tumbling')
})

test('coaches revise a selected component with dose edits and locks, then reopen the immutable source', async ({ page, request }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await configureGroup(page)
  const original = await generate(page)
  const source = original.workout.workflow.draft
  const strength = source.activities.filter((activity: { componentKey: string }) => activity.componentKey === 'strength')
  await session(page).getByRole('button', { name: 'Modify this session' }).click()
  const revision = page.getByRole('region', { name: 'Revision controls' })
  for (const name of ['Prepare & Access', 'Explosiveness', 'Capacity / Competition']) await revision.getByRole('checkbox', { name, exact: true }).uncheck()
  await revision.getByRole('button', { name: 'Load revision exercise and method choices' }).click()
  await expect(page.getByRole('status')).toContainText('canonical profile choices loaded')
  await revision.locator('summary').filter({ hasText: /^Strength ·/ }).click()
  await revision.locator('summary').filter({ hasText: strength[0].card.displayName }).click()
  const block = revision.getByRole('group', { name: `Revise ${strength[0].card.displayName}`, exact: true })
  await block.getByRole('checkbox', { name: 'Edit dose', exact: true }).check()
  await block.getByRole('spinbutton', { name: 'Sets', exact: true }).fill('2')
  await block.getByRole('checkbox', { name: 'Lock exercise', exact: true }).check()
  await block.getByRole('checkbox', { name: 'Lock method', exact: true }).check()
  await expect(block.getByLabel('Exercise replacement')).toBeDisabled()
  await expect(block.getByLabel('Exercise replacement')).toHaveValue(strength[0].profile.id)
  await expect(block.getByRole('combobox', { name: 'Programming method', exact: true })).toHaveValue(String(strength[0].method.id))
  await expect(block.getByRole('checkbox', { name: 'Lock dose', exact: true })).toBeDisabled()
  await block.scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/private/tmp/vortex-programming-desktop-revision-block.png' })
  await page.getByRole('textbox', { name: 'Coaching intent', exact: true }).fill('Keep explosive quality. Adjust later work to reflect the reduced strength dose.')
  const revised = await generate(page, 'Review & save revision')
  await expect(session(page).getByRole('heading', { name: 'Session checks passed' })).toBeVisible()
  await expect(session(page).getByLabel('Revision history')).toContainText('Preserved: Explosiveness.')
  await expect(revision).toHaveCount(0)
  expect(revised.persistedWorkoutId).not.toBe(original.persistedWorkoutId)
  expect(revised.workout.workflow.sessionIntent.modification).toMatchObject({ sourceWorkoutId: original.persistedWorkoutId,
    sourceRevision: original.workout.revision, sourceContentHash: original.workout.contentHash, globalControlsChanged: false,
    mutableComponentKeys: ['strength', 'capacity_competition'], preservedComponentKeys: ['explosiveness'] })
  const changed = revised.workout.workflow.draft
  expect(changed.activities.find((activity: { activityId: string }) => activity.activityId === strength[0].activityId).dose.sets).toBe(2)
  expect(changed.activities.filter((activity: { componentKey: string }) => activity.componentKey === 'explosiveness'))
    .toEqual(source.activities.filter((activity: { componentKey: string }) => activity.componentKey === 'explosiveness'))
  expect(changed.preparationDemand.downstreamHash).not.toBe(source.preparationDemand.downstreamHash)
  expect(changed.preparationProposal.downstreamHash).toBe(changed.preparationDemand.downstreamHash)
  const state = await (await request.get('/__preview/state')).json()
  expect(state.savedCount).toBe(2)
  expect(state.lastRequest.modification.blockEdits[0]).toMatchObject({ blockId: strength[0].activityId, dose: { sets: 2 } })
  await session(page).getByRole('button', { name: 'Check current evidence' }).click()
  await expect(session(page).getByRole('heading', { name: 'Session checks passed' })).toBeVisible()
  await session(page).getByRole('button', { name: 'Modify this session' }).click()
  await revision.locator('summary').filter({ hasText: /^Strength ·/ }).click()
  await revision.locator('summary').filter({ hasText: strength[0].card.displayName }).click()
  await expect(block.getByRole('checkbox', { name: 'Lock exercise', exact: true })).toBeChecked()
  await expect(block.getByRole('checkbox', { name: 'Lock method', exact: true })).toBeChecked()
  await expect(block.getByRole('checkbox', { name: 'Edit dose', exact: true })).not.toBeChecked()
  await revision.getByRole('button', { name: 'Cancel revision' }).click()
  await session(page).getByRole('button', { name: 'Open source session' }).click()
  await expect(session(page).getByRole('heading', { name: 'Saved session · check current evidence' })).toBeVisible()
  await expect(session(page).getByLabel('Revision history')).toHaveCount(0)
  expect((await (await request.get(`${endpoint}/${original.persistedWorkoutId}`)).json()).data.workout).toEqual(original.workout)
  expect(errors).toEqual([])
})

test('canonical exercise and method swaps retain block identities through the coach revision form', async ({ page }) => {
  await configureGroup(page)
  const original = await generate(page)
  const strength = original.workout.workflow.draft.activities.filter((activity: { componentKey: string }) => activity.componentKey === 'strength')
  await session(page).getByRole('button', { name: 'Modify this session' }).click()
  const revision = page.getByRole('region', { name: 'Revision controls' })
  await revision.getByRole('button', { name: 'Load revision exercise and method choices' }).click()
  await expect(page.getByRole('status')).toContainText('canonical profile choices loaded')
  await revision.locator('summary').filter({ hasText: /^Strength ·/ }).click()
  expect(strength.length).toBeGreaterThanOrEqual(2)
  for (const [index, activity] of strength.slice(0, 2).entries()) {
    await revision.locator('summary').filter({ hasText: activity.card.displayName }).click()
    const block = revision.getByRole('group', { name: `Revise ${activity.card.displayName}`, exact: true })
    await block.getByLabel('Exercise replacement').selectOption(strength[1 - index].profile.id)
    if (index === 0) await block.getByRole('combobox', { name: 'Programming method', exact: true }).selectOption('9')
  }
  const revised = await generate(page, 'Review & save revision')
  await expect(session(page).getByRole('heading', { name: 'Session checks passed' })).toBeVisible()
  const changed = revised.workout.workflow.draft.activities.find((activity: { activityId: string }) => activity.activityId === strength[0].activityId)
  expect(changed.profile.id).toBe(strength[1].profile.id)
  expect(changed.method.id).toBe('9')
  expect(revised.workout.workflow.draft.activities.find((activity: { activityId: string }) => activity.activityId === strength[1].activityId).profile.id).toBe(strength[0].profile.id)
})

test('mobile revision controls retain locks when changed logistics require review and cancellation creates no revision', async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await configureGroup(page)
  const original = await generate(page)
  await session(page).getByRole('button', { name: 'Modify this session' }).click()
  const revision = page.getByRole('region', { name: 'Revision controls' })
  for (const name of ['Prepare & Access', 'Explosiveness', 'Strength', 'Capacity / Competition']) await revision.getByRole('checkbox', { name, exact: true }).uncheck()
  await expect(page.getByRole('button', { name: 'Review & save revision' })).toBeDisabled()
  await revision.getByRole('checkbox', { name: 'Strength', exact: true }).check()
  await revision.getByRole('button', { name: 'Cancel revision' }).click()
  expect((await (await request.get('/__preview/state')).json()).savedCount).toBe(1)
  await expect(page.getByRole('button', { name: 'Generate & review session' })).toBeEnabled()
  await session(page).getByRole('button', { name: 'Modify this session' }).click()
  const activity = original.workout.workflow.draft.activities.find((entry: { componentKey: string }) => entry.componentKey === 'strength')
  await revision.locator('summary').filter({ hasText: /^Strength ·/ }).click()
  await revision.locator('summary').filter({ hasText: activity.card.displayName }).click()
  const block = revision.getByRole('group', { name: `Revise ${activity.card.displayName}`, exact: true })
  await block.getByRole('checkbox', { name: 'Lock dose', exact: true }).check()
  await block.getByRole('checkbox', { name: 'Lock start, work and recovery times', exact: true }).check()
  await expect(block.getByRole('checkbox', { name: 'Edit dose', exact: true })).toBeDisabled()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await block.scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/private/tmp/vortex-programming-mobile-revision-block.png' })
  await revision.getByRole('heading', { name: 'Revise a saved session' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/private/tmp/vortex-programming-mobile-revision.png' })
  await page.getByRole('spinbutton', { name: 'Athletic minutes', exact: true }).fill('90')
  const revised = await generate(page, 'Review & save revision')
  await expect(session(page).getByRole('heading', { name: 'Coach review needed' })).toBeVisible()
  expect(revised.workout.validatedWorkout).toBe(false)
  expect(revised.workout.workflow.sessionIntent.modification.globalControlsChanged).toBe(true)
  expect(revised.workout.validation.findings.some((finding: { code: string }) => finding.code === 'locked_block_timing_conflict')).toBe(true)
  expect(revised.workout.workflow.draft.activities.find((entry: { activityId: string }) => entry.activityId === activity.activityId).dose).toEqual(activity.dose)
  expect((await (await request.get(`${endpoint}/${original.persistedWorkoutId}`)).json()).data.workout).toEqual(original.workout)
})

test('a natural-language preview changes no controls or saved rows until applied and then runs whole-session generation', async ({ page, request }) => {
  await configureGroup(page)
  await page.getByRole('spinbutton', { name: 'Athletic minutes', exact: true }).fill('90')
  const original = await generate(page)
  await session(page).getByRole('button', { name: 'Modify this session' }).click()
  const instruction = 'Use ages 9–11, 12 athletes, 2 lanes and 60 athletic minutes with no tumbling.'
  await page.getByRole('textbox', { name: 'Coaching intent', exact: true }).fill(instruction)
  await request.post('/__preview/interpretation', { data: { operations: [
    { kind: 'age_range', cohortKey: original.workout.intent.athletes[0].key, ageMin: 9, ageMax: 11 },
    { kind: 'group_size', cohortKey: original.workout.intent.athletes[0].key, athleteCount: 12 },
    { kind: 'logistics', field: 'laneCount', value: 2 }, { kind: 'session_time', athleticMinutes: 60, tumblingMinutes: 0 },
  ] } })
  const proposal = await interpret(page)
  expect(proposal.status).toBe('READY_FOR_REVIEW')
  const preview = page.getByRole('region', { name: 'Instruction preview' })
  await expect(preview.getByText('Athlete group 1: Youngest age', { exact: true })).toBeVisible()
  await expect(page.getByRole('spinbutton', { name: 'Youngest age', exact: true })).toHaveValue('12')
  await expect(page.getByRole('spinbutton', { name: 'Athletic minutes', exact: true })).toHaveValue('90')
  await expect(page.getByRole('button', { name: 'Review & save revision' })).toBeDisabled()
  expect((await (await request.get('/__preview/state')).json()).savedCount).toBe(1)
  await preview.getByRole('heading').scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/private/tmp/vortex-programming-desktop-instruction-preview.png' })
  await preview.getByRole('button', { name: 'Apply proposed controls' }).click()
  await expect(preview).toHaveCount(0)
  for (const [label, value] of [['Youngest age', '9'], ['Oldest age', '11'], ['Athletes', '12'], ['Lanes', '2'], ['Athletic minutes', '60'], ['Total booked minutes', '60']]) {
    await expect(page.getByRole('spinbutton', { name: label, exact: true })).toHaveValue(value)
  }
  await expect(page.getByRole('checkbox', { name: 'Bodyweight', exact: true })).toBeChecked()
  expect((await (await request.get('/__preview/state')).json()).savedCount).toBe(1)
  const revised = await generate(page, 'Review & save revision')
  expect(revised.workout.workflow.sessionIntent.modification.sourceContentHash).toBe(original.workout.contentHash)
  expect(revised.workout.intent.athletes[0]).toMatchObject({ ageMin: 9, ageMax: 11, athleteCount: 12 })
  expect(revised.workout.intent.logistics).toMatchObject({ athleticMinutes: 60, laneCount: 2 })
  expect(revised.workout.intent.instruction).toBe(instruction)
  await expect(session(page).getByRole('heading', { name: 'Session checks passed' })).toBeVisible()
  expect(revised.workout.workflow.qa.critic.status).toBe('PASS')
  expect(revised.workout.workflow.draft.preparationProposal.downstreamHash).toBe(revised.workout.workflow.draft.preparationDemand.downstreamHash)
  const state = await (await request.get('/__preview/state')).json()
  expect(state.savedCount).toBe(2)
  expect(state.interpretationCount).toBe(1)
  expect((await (await request.get(`${endpoint}/${original.persistedWorkoutId}`)).json()).data.workout).toEqual(original.workout)
})

test('mobile clarification, stale previews and choosing current controls cannot overwrite the coach form', async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await configureGroup(page)
  await generate(page)
  await session(page).getByRole('button', { name: 'Modify this session' }).click()
  await page.getByRole('textbox', { name: 'Coaching intent', exact: true }).fill('We only have 60 minutes.')
  await request.post('/__preview/interpretation', { data: { questions: ['Does the 60-minute booking include tumbling?'],
    operations: [{ kind: 'logistics', field: 'laneCount', value: 2 }] } })
  expect((await interpret(page)).status).toBe('NEEDS_COACH_INPUT')
  const preview = page.getByRole('region', { name: 'Instruction preview' })
  await expect(preview).toContainText('Does the 60-minute booking include tumbling?')
  await expect(preview.getByRole('button', { name: 'Apply proposed controls' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Review & save revision' })).toBeDisabled()
  await page.getByRole('textbox', { name: 'Coaching intent', exact: true }).fill('Use 60 athletic minutes, no tumbling, and 2 lanes.')
  await request.post('/__preview/interpretation', { data: { operations: [{ kind: 'session_time', athleticMinutes: 60, tumblingMinutes: 0 }, { kind: 'logistics', field: 'laneCount', value: 2 }] } })
  expect((await interpret(page)).status).toBe('READY_FOR_REVIEW')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await preview.getByRole('heading').scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/private/tmp/vortex-programming-mobile-instruction-preview.png' })
  await page.getByRole('spinbutton', { name: 'Coaches', exact: true }).fill('3')
  await expect(preview.getByRole('status')).toContainText('changed after this preview')
  await expect(preview.getByRole('button', { name: 'Apply proposed controls' })).toBeDisabled()
  await preview.getByRole('button', { name: 'Use current controls instead' }).click()
  await expect(preview).toHaveCount(0)
  await expect(page.getByRole('spinbutton', { name: 'Coaches', exact: true })).toHaveValue('3')
  await expect(page.getByRole('spinbutton', { name: 'Lanes', exact: true })).toHaveValue('3')
  await expect(page.getByRole('button', { name: 'Review & save revision' })).toBeEnabled()
  expect((await (await request.get('/__preview/state')).json()).savedCount).toBe(1)
})

test('instruction previews explain canonical swaps, respect locks and cancel without applying or saving', async ({ page, request }) => {
  await configureGroup(page)
  const original = await generate(page)
  const [first, second] = original.workout.workflow.draft.activities.filter((entry: { componentKey: string }) => entry.componentKey === 'strength')
  await session(page).getByRole('button', { name: 'Modify this session' }).click()
  const revision = page.getByRole('region', { name: 'Revision controls' })
  await revision.locator('summary').filter({ hasText: /^Strength ·/ }).click()
  await revision.locator('summary').filter({ hasText: first.card.displayName }).click()
  const block = revision.getByRole('group', { name: `Revise ${first.card.displayName}`, exact: true })
  await block.getByRole('checkbox', { name: 'Lock dose', exact: true }).check()
  await page.getByRole('textbox', { name: 'Coaching intent', exact: true }).fill('Reduce the first strength exercise to 2 sets.')
  await request.post('/__preview/interpretation', { data: { operations: [{ kind: 'block_dose', blockId: first.activityId, field: 'sets', value: 2 }] } })
  expect((await interpret(page)).status).toBe('NEEDS_COACH_INPUT')
  const preview = page.getByRole('region', { name: 'Instruction preview' })
  await expect(preview).toContainText('dose change contradicts its block lock')
  await expect(block.getByRole('checkbox', { name: 'Lock dose', exact: true })).toBeChecked()
  await preview.getByRole('button', { name: 'Use current controls instead' }).click()
  await block.getByRole('checkbox', { name: 'Lock dose', exact: true }).uncheck()
  await page.getByRole('textbox', { name: 'Coaching intent', exact: true }).fill('Swap the first two strength exercises and use method 9 for the first.')
  await request.post('/__preview/interpretation', { data: { operations: [
    { kind: 'replace_exercise', blockId: first.activityId, deliveryProfileId: second.profile.id },
    { kind: 'replace_exercise', blockId: second.activityId, deliveryProfileId: first.profile.id },
    { kind: 'block_method', blockId: first.activityId, programmingMethodId: '9' },
  ] } })
  expect((await interpret(page)).status).toBe('READY_FOR_REVIEW')
  await expect(preview).toContainText(second.card.displayName)
  await expect(preview).toContainText('strength reviewed method 9')
  expect(await preview.innerText()).not.toMatch(/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/)
  await preview.getByRole('button', { name: 'Apply proposed controls' }).click()
  await page.getByRole('textbox', { name: 'Coaching intent', exact: true }).fill('Review the current controls.')
  await request.post('/__preview/interpretation', { data: { delayMs: 2000 } })
  await page.getByRole('button', { name: 'Preview instruction changes' }).click()
  await expect.poll(async () => (await (await request.get('/__preview/state')).json()).interpretationsInFlight).toBe(1)
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Instruction preview canceled. Your current controls were kept.')
  await expect.poll(async () => (await (await request.get('/__preview/state')).json()).interpretationsInFlight).toBe(0)
  await expect(preview).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Review & save revision' })).toBeEnabled()
  expect((await (await request.get('/__preview/state')).json()).savedCount).toBe(1)
})
