// Seed list of schools. Each entry: [name, level, location]
// level: 'high' | 'middle' | 'elementary'
// location: optional city/area parsed from the source list (null when not provided)

export const SEED_SCHOOLS = [
  // High Schools (Prince George's County - no location provided)
  ['Bowie High', 'high', null],
  ['Charles Herbert Flowers High', 'high', null],
  ['Dr. Henry A. Wise Jr. High', 'high', null],
  ['DuVal High', 'high', null],
  ['Eleanor Roosevelt High', 'high', null],
  ['Fairmont Heights High', 'high', null],
  ['Frederick Douglass High', 'high', null],
  ['Friendly High', 'high', null],
  ['C. Elizabeth Rieg Regional', 'high', null],
  ['Gwynn Park High', 'high', null],
  ['High Point High', 'high', null],
  ['International High School at Langley Park', 'high', null],
  ['International High School at Largo', 'high', null],
  ['James E. Duckworth Regional', 'high', null],
  ['Largo High', 'high', null],
  ['Northwestern High', 'high', null],
  ['Oxon Hill High', 'high', null],
  ['Parkdale High', 'high', null],
  ['Suitland High', 'high', null],
  ['Surrattsville High', 'high', null],
  // High Schools (Anne Arundel County - with location)
  ['Annapolis High School', 'high', 'Annapolis'],
  ['Arundel High School', 'high', 'Gambrills'],
  ['Broadneck High School', 'high', 'Annapolis'],
  ['Chesapeake High School', 'high', 'Pasadena'],
  ['Chesapeake Science Point', 'high', 'Hanover'],
  ['Crofton High School', 'high', 'Gambrills'],
  ['Glen Burnie High School', 'high', 'Glen Burnie'],
  ['Meade Senior High School', 'high', 'Fort Meade'],
  ['North County High School', 'high', 'Glen Burnie'],
  ['Northeast High School', 'high', 'Pasadena'],
  ['Old Mill High School', 'high', 'Millersville'],
  ['Severn Run High School', 'high', 'Severn'],
  ['Severna Park High School', 'high', 'Severna Park'],
  ['South River High School', 'high', 'Edgewater'],
  ['Southern High School', 'high', 'Harwood'],
  // Middle Schools
  ['Annapolis Middle', 'middle', null],
  ['Arundel Middle', 'middle', null],
  ['Brooklyn Park Middle', 'middle', null],
  ['Central Middle', 'middle', null],
  ['Chesapeake Bay Middle', 'middle', null],
  ['Corkran Middle', 'middle', null],
  ['Crofton Middle', 'middle', null],
  ['Lindale Middle', 'middle', null],
  ['MacArthur Middle', 'middle', null],
  ['Magothy River Middle', 'middle', null],
  ['Marley Middle', 'middle', null],
  ['Meade Middle', 'middle', null],
  ['Northeast Middle', 'middle', null],
  ['Old Mill Middle North', 'middle', null],
  ['Old Mill Middle South', 'middle', null],
  ['Severna Park Middle', 'middle', null],
  ['Severn River Middle', 'middle', null],
  ['Southern Middle', 'middle', null],
  // Elementary Schools
  ['Crofton Woods Elementary', 'elementary', null],
]
