-- Seed 50 Prepare / Access movements (card v2 + subrole hierarchy).
-- IDEMPOTENT. Generated by scripts/generate-097-prepare-seed.mjs

-- 1) Insert 49 new exercises
INSERT INTO coaching.exercise (
  facility_id, name, slug, description, sport_id, skill_level, age_min,
  default_sets, default_reps, default_work_seconds, default_rest_seconds, est_seconds_per_set,
  is_published, visibility,
  card_summary, coach_language, athlete_language,
  movement_family, primary_phase_key, phase_subrole, primary_order_slot,
  movement_requirements, coaching_execution
)
SELECT
  (SELECT id FROM public.facility ORDER BY id LIMIT 1),
  d.name, d.slug, d.description,
  (SELECT id FROM coaching.sport WHERE key = 'fitness'),
  d.skill::public.skill_level,
  d.age_min,
  d.sets, d.reps, d.work, d.rest, d.est,
  TRUE, 'facility',
  d.summary, d.coach_lang, d.athlete_lang,
  d.family, 'prepare_access', d.subrole, d.slot,
  d.req::jsonb, d.exec::jsonb
FROM (VALUES
  ('90/90 Breathing with Reach', '9090-breathing-with-reach', 'Supine breathing drill linking ribcage, pelvis, and diaphragm.', 'EARLY_STAGE', 6, 2, NULL, 45, 15, 50, 'Ribcage, pelvis, diaphragm, trunk stack.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your spine for training.', 'Breathing reset', 'mobilize', 'breathing_reset', '{"primary_joint_actions":["spine_rotation","shoulder_flexion"],"primary_tissues":["diaphragm","intercostals"],"breathing_demand":"diaphragmatic","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Supine breathing drill linking ribcage, pelvis, and diaphragm.","setup":["Lie on back in 90/90 hip/knee position","Reach one arm overhead"],"execution_steps":["Inhale into back and sides of ribcage","Exhale fully while reaching longer"],"coach_cues":["Ribs down, pelvis neutral","Long exhale"],"common_faults":["Holding breath","Arching lower back"]}'::jsonb),
  ('Crocodile Breathing', 'crocodile-breathing', 'Prone breathing for posterior expansion and down-regulation.', 'EARLY_STAGE', 6, 2, NULL, 60, 15, 65, 'Diaphragm, posterior expansion, relaxation.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your spine for training.', 'Breathing reset', 'mobilize', 'breathing_reset', '{"primary_joint_actions":["spine_extension"],"primary_tissues":["diaphragm"],"breathing_demand":"diaphragmatic","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Prone breathing for posterior expansion and down-regulation.","setup":["Lie prone, forehead on stacked hands"],"execution_steps":["Breathe into belly pressing floor","Slow nasal inhale, long exhale"],"coach_cues":["Relax jaw and shoulders"],"common_faults":["Shrugging shoulders on inhale"]}'::jsonb),
  ('Full-Body Joint CARs Flow', 'full-body-joint-cars-flow', 'Controlled articular rotations through major joints.', 'BEGINNER', 8, 1, 1, NULL, 0, 180, 'Joint scan, active range, readiness.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your full body for training.', 'Joint scan', 'mobilize', 'joint_scan', '{"primary_joint_actions":["multi_joint"],"primary_tissues":["synovial"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Controlled articular rotations through major joints.","setup":["Stand tall, soft knees"],"execution_steps":["Neck CARs","Shoulder CARs","Hip CARs","Ankle CARs — slow and controlled"],"coach_cues":["No compensation from other joints"],"common_faults":["Rushing","Using momentum"]}'::jsonb),
  ('Neck CARs', 'neck-cars', 'Controlled cervical rotations and nods.', 'EARLY_STAGE', 6, 2, 3, NULL, 10, 30, 'Cervical control, visual orientation.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your spine for training.', 'Joint scan', 'mobilize', 'joint_scan', '{"primary_joint_actions":["cervical_rotation","cervical_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Controlled cervical rotations and nods.","setup":["Seated or standing tall"],"execution_steps":["Slow chin tuck","Draw circles with nose"],"coach_cues":["Small range, no pain"],"common_faults":["Fast jerky motion"]}'::jsonb),
  ('Cat-Cow', 'cat-cow', 'Quadruped spinal flexion and extension.', 'EARLY_STAGE', 4, 2, 8, NULL, 15, 35, 'Spinal flexion/extension, pelvic awareness.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your spine for training.', 'Spinal mobility', 'mobilize', 'spinal_mobility', '{"primary_joint_actions":["spine_flexion","spine_extension"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Quadruped spinal flexion and extension.","setup":["Quadruped, wrists under shoulders"],"execution_steps":["Inhale: drop belly, lift chest (cow)","Exhale: round spine (cat)"],"coach_cues":["Move one segment at a time"],"common_faults":["Only moving at lumbar spine"]}'::jsonb),
  ('Quadruped Spinal Circles', 'quadruped-spinal-circles', 'Segmental spine circles in quadruped.', 'BEGINNER', 8, 2, 4, NULL, 15, 40, 'Segmental spine, lateral flexion, control.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your spine for training.', 'Spinal mobility', 'mobilize', 'spinal_mobility', '{"primary_joint_actions":["spine_rotation","spine_lateral_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Segmental spine circles in quadruped.","setup":["Quadruped neutral spine"],"execution_steps":["Draw small circles with spine","Reverse direction each rep"],"coach_cues":["Keep shoulders quiet"],"common_faults":["Shifting weight side to side excessively"]}'::jsonb),
  ('Quadruped Thread the Needle', 'quadruped-thread-the-needle', 'Quadruped thoracic rotation reach-under.', 'BEGINNER', 6, 2, 6, NULL, 15, 35, 'Thoracic rotation, scapular freedom.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your spine for training.', 'Thoracic rotation', 'mobilize', 'thoracic_rotation', '{"primary_joint_actions":["thoracic_rotation","shoulder_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Quadruped thoracic rotation reach-under.","setup":["Quadruped, one hand behind head"],"execution_steps":["Rotate elbow toward opposite wrist","Follow with eyes"],"coach_cues":["Rotate through mid-back"],"common_faults":["Dumping into lumbar spine"]}'::jsonb),
  ('Side-Lying Open Book', 'side-lying-open-book', 'Side-lying thoracic rotation with knee anchor.', 'BEGINNER', 6, 2, 6, NULL, 15, 35, 'Thoracic rotation, rib mobility.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your spine for training.', 'Thoracic rotation', 'mobilize', 'thoracic_rotation', '{"primary_joint_actions":["thoracic_rotation"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Side-lying thoracic rotation with knee anchor.","setup":["Side-lying, knees bent 90°, arms extended"],"execution_steps":["Open top arm like a book","Follow hand with eyes"],"coach_cues":["Keep knees stacked"],"common_faults":["Rolling hips backward"]}'::jsonb),
  ('Inchworm Walkout', 'inchworm-walkout', 'Standing to plank walkout and return.', 'BEGINNER', 6, 2, 4, NULL, 20, 40, 'Hamstrings, shoulders, trunk, plank access.', 'Use in Prepare / Access (integrate) before higher-intent work.', 'Move with control; this prepares your full body for training.', 'Full-body flow', 'integrate', 'crawl_pattern_prep', '{"primary_joint_actions":["shoulder_flexion","hip_hinge"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Standing to plank walkout and return.","setup":["Stand feet hip-width"],"execution_steps":["Hinge and place hands on floor","Walk out to plank","Walk feet to hands and stand"],"coach_cues":["Soft knees if hamstrings tight"],"common_faults":["Sagging hips in plank"]}'::jsonb),
  ('Wrist Rockers — Palms Down', 'wrist-rockers-palms-down', 'Wrist extension rocking for hand support prep.', 'EARLY_STAGE', 6, 2, 8, NULL, 10, 25, 'Wrist extension for tumbling, crawling, pressing.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your wrist for training.', 'Wrist prep', 'mobilize', 'wrist_prep', '{"primary_joint_actions":["wrist_extension"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Wrist extension rocking for hand support prep.","setup":["Quadruped, fingers forward"],"execution_steps":["Rock forward over wrists","Keep elbows straight"],"coach_cues":["Even pressure through palm"],"common_faults":["Collapsing on pinky side"]}'::jsonb),
  ('Wrist Rockers — Palms Up', 'wrist-rockers-palms-up', 'Wrist flexor-biased rocking.', 'EARLY_STAGE', 6, 2, 8, NULL, 10, 25, 'Wrist flexors, forearms, hand support.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your wrist for training.', 'Wrist prep', 'mobilize', 'wrist_prep', '{"primary_joint_actions":["wrist_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Wrist flexor-biased rocking.","setup":["Quadruped, fingers toward knees"],"execution_steps":["Rock back gently over wrists"],"coach_cues":["Stop before sharp pain"],"common_faults":["Forcing range"]}'::jsonb),
  ('Finger Pulses', 'finger-pulses', 'Hand intrinsic activation with palm lifts.', 'EARLY_STAGE', 6, 2, 10, NULL, 10, 20, 'Hand intrinsic strength, wrist prep (also activates intrinsics).', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your wrist for training.', 'Wrist prep', 'mobilize', 'wrist_prep', '{"primary_joint_actions":["wrist_extension"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Hand intrinsic activation with palm lifts.","setup":["Quadruped, flat palms"],"execution_steps":["Lift fingers and palm while keeping contact"],"coach_cues":["Spread fingers wide"],"common_faults":["Lifting whole hand off floor"]}'::jsonb),
  ('Scapular Push-Up', 'scapular-push-up', 'Protraction/retraction in plank or quadruped.', 'BEGINNER', 8, 2, 10, NULL, 20, 30, 'Serratus anterior, scapular protraction.', 'Use in Prepare / Access (activate) before higher-intent work.', 'Move with control; this prepares your shoulder for training.', 'Scapular activation', 'activate', 'scapular_activation', '{"primary_joint_actions":["scapular_protraction"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Protraction/retraction in plank or quadruped.","setup":["Plank or quadruped"],"execution_steps":["Push floor away (protract)","Allow shoulder blades to come together"],"coach_cues":["Elbows stay straight"],"common_faults":["Bending elbows"]}'::jsonb),
  ('Quadruped Shoulder Circles', 'quadruped-shoulder-circles', 'Shoulder CARs in quadruped.', 'BEGINNER', 8, 2, 5, NULL, 10, 30, 'Shoulder CARs, scapular control.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your shoulder for training.', 'Shoulder mobility', 'mobilize', 'shoulder_mobility', '{"primary_joint_actions":["shoulder_rotation"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Shoulder CARs in quadruped.","setup":["Quadruped, one arm extended"],"execution_steps":["Draw slow circles with arm"],"coach_cues":["Keep trunk still"],"common_faults":["Rotating through spine"]}'::jsonb),
  ('Wall Slides with Lift-Off', 'wall-slides-with-lift-off', 'Wall slide with optional lift-off at top.', 'BEGINNER', 8, 2, 8, NULL, 15, 35, 'Shoulder flexion, thoracic extension, scap control.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your shoulder for training.', 'Shoulder mobility', 'mobilize', 'shoulder_mobility', '{"primary_joint_actions":["shoulder_flexion","scapular_upward_rotation"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Wall slide with optional lift-off at top.","setup":["Back to wall, arms in W"],"execution_steps":["Slide arms up wall","Optional small lift-off at top"],"coach_cues":["Ribs stay down"],"common_faults":["Arching lower back"]}'::jsonb),
  ('Band External Rotation', 'band-external-rotation', 'No-money drill for rotator cuff.', 'BEGINNER', 10, 2, 12, NULL, 20, 30, 'Rotator cuff, shoulder centration.', 'Use in Prepare / Access (activate) before higher-intent work.', 'Move with control; this prepares your shoulder for training.', 'Rotator cuff activation', 'activate', 'rotator_cuff_activation', '{"primary_joint_actions":["shoulder_external_rotation"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"No-money drill for rotator cuff.","setup":["Band at elbow height, elbows at sides"],"execution_steps":["Rotate hands outward","Control return"],"coach_cues":["Elbows pinned to ribs"],"common_faults":["Shrugging shoulders"]}'::jsonb),
  ('Arm Circles', 'arm-circles', 'Standing shoulder circles for range prep.', 'EARLY_STAGE', 4, 2, 10, NULL, 10, 25, 'Shoulder range, neural prep.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your shoulder for training.', 'Shoulder mobility', 'mobilize', 'shoulder_mobility', '{"primary_joint_actions":["shoulder_flexion","shoulder_abduction"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Standing shoulder circles for range prep.","setup":["Stand tall, arms out"],"execution_steps":["Small to large circles","Reverse direction"],"coach_cues":["Relax neck"],"common_faults":["Over-striding with trunk lean"]}'::jsonb),
  ('Bear Crawl Rock-Back', 'bear-crawl-rock-back', 'Bear position rock-back for wrist and hip access.', 'BEGINNER', 6, 2, 6, NULL, 20, 35, 'Wrists, shoulders, hips, trunk.', 'Use in Prepare / Access (integrate) before higher-intent work.', 'Move with control; this prepares your full body for training.', 'Crawl pattern', 'integrate', 'crawl_pattern_prep', '{"primary_joint_actions":["hip_flexion","wrist_extension"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Bear position rock-back for wrist and hip access.","setup":["Quadruped, knees slightly off floor or on floor"],"execution_steps":["Rock hips back toward heels","Return to start"],"coach_cues":["Press through palms"],"common_faults":["Collapsing wrists"]}'::jsonb),
  ('Down Dog to Plank Wave', 'down-dog-to-plank-wave', 'Alternating down dog and plank.', 'BEGINNER', 8, 2, 5, NULL, 20, 40, 'Shoulder flexion, hamstrings, trunk line.', 'Use in Prepare / Access (integrate) before higher-intent work.', 'Move with control; this prepares your full body for training.', 'Shoulder integration', 'integrate', 'crawl_pattern_prep', '{"primary_joint_actions":["shoulder_flexion","hip_hinge"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Alternating down dog and plank.","setup":["Down dog position"],"execution_steps":["Shift forward to plank","Push back to down dog"],"coach_cues":["Long spine both positions"],"common_faults":["Sagging in plank"]}'::jsonb),
  ('Knee-to-Wall Ankle Rockers', 'knee-to-wall-ankle-rockers', 'Wall-assisted dorsiflexion rocks.', 'EARLY_STAGE', 6, 2, 10, NULL, 15, 30, 'Dorsiflexion, squat/landing access.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your ankle for training.', 'Ankle mobility', 'mobilize', 'ankle_mobility', '{"primary_joint_actions":["ankle_dorsiflexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Wall-assisted dorsiflexion rocks.","setup":["Toes 4-5 inches from wall, lunge stance"],"execution_steps":["Drive knee to wall without heel lift","Rock back and repeat"],"coach_cues":["Heel stays down"],"common_faults":["Heel popping up"]}'::jsonb),
  ('Half-Kneeling Ankle Dorsiflexion Pulse', 'half-kneeling-ankle-dorsiflexion-pulse', 'Half-kneeling ankle glide pulses.', 'BEGINNER', 8, 2, 12, NULL, 15, 30, 'Ankle glide, calf-ankle interface.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your ankle for training.', 'Ankle mobility', 'mobilize', 'ankle_mobility', '{"primary_joint_actions":["ankle_dorsiflexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Half-kneeling ankle glide pulses.","setup":["Half-kneeling, front foot flat"],"execution_steps":["Pulse knee forward over toes","Keep heel down"],"coach_cues":["Tibia over foot"],"common_faults":["Foot collapsing inward"]}'::jsonb),
  ('Ankle CARs', 'ankle-cars', 'Controlled articular rotations at ankle.', 'BEGINNER', 8, 2, 5, NULL, 10, 25, 'Ankle control, end-range awareness.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your ankle for training.', 'Ankle mobility', 'mobilize', 'ankle_mobility', '{"primary_joint_actions":["ankle_inversion","ankle_eversion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Controlled articular rotations at ankle.","setup":["Seated or standing, lift foot"],"execution_steps":["Draw slow circles with foot"],"coach_cues":["Isolate ankle"],"common_faults":["Moving knee"]}'::jsonb),
  ('Tibialis Raises', 'tibialis-raises', 'Standing anterior shin raises.', 'BEGINNER', 8, 2, 15, NULL, 20, 30, 'Anterior shin, deceleration prep.', 'Use in Prepare / Access (activate) before higher-intent work.', 'Move with control; this prepares your ankle for training.', 'Foot activation', 'activate', 'foot_activation', '{"primary_joint_actions":["ankle_dorsiflexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Standing anterior shin raises.","setup":["Back to wall, feet flat"],"execution_steps":["Lift toes toward shins","Lower with control"],"coach_cues":["Keep heels down"],"common_faults":["Leaning back excessively"]}'::jsonb),
  ('Calf Raise to Heel Drop', 'calf-raise-to-heel-drop', 'Controlled calf raise and eccentric lower.', 'BEGINNER', 8, 2, 10, NULL, 20, 35, 'Calf-Achilles prep.', 'Use in Prepare / Access (activate) before higher-intent work.', 'Move with control; this prepares your ankle for training.', 'Foot activation', 'activate', 'foot_activation', '{"primary_joint_actions":["ankle_plantarflexion"],"primary_tissues":["achilles","gastrocnemius"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Controlled calf raise and eccentric lower.","setup":["Stand on edge of step or flat ground"],"execution_steps":["Rise onto balls of feet","Lower heels slowly below level if on step"],"coach_cues":["Straight knee line"],"common_faults":["Bouncing at bottom"]}'::jsonb),
  ('Toe Yoga', 'toe-yoga', 'Independent toe lifts for foot control.', 'EARLY_STAGE', 6, 2, 8, NULL, 15, 25, 'Foot intrinsics, arch control.', 'Use in Prepare / Access (activate) before higher-intent work.', 'Move with control; this prepares your ankle for training.', 'Foot activation', 'activate', 'foot_activation', '{"primary_joint_actions":["toe_extension"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Independent toe lifts for foot control.","setup":["Seated or standing"],"execution_steps":["Lift big toe, keep others down","Alternate pattern"],"coach_cues":["Move slowly"],"common_faults":["Curling whole foot"]}'::jsonb),
  ('Short-Foot Drill', 'short-foot-drill', 'Arch doming without toe curl.', 'BEGINNER', 8, 2, 10, NULL, 15, 25, 'Foot tripod, arch stiffness.', 'Use in Prepare / Access (activate) before higher-intent work.', 'Move with control; this prepares your ankle for training.', 'Foot activation', 'activate', 'foot_activation', '{"primary_joint_actions":["foot_supination"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Arch doming without toe curl.","setup":["Single leg balance, foot flat"],"execution_steps":["Shorten foot by pulling ball toward heel","Hold 2-3 seconds"],"coach_cues":["Toes stay long"],"common_faults":["Curling toes under"]}'::jsonb),
  ('Foot Tripod Weight Shifts', 'foot-tripod-weight-shifts', 'Weight shifts through heel, big toe, little toe.', 'BEGINNER', 6, 2, 6, NULL, 15, 30, 'Foot pressure, balance readiness.', 'Use in Prepare / Access (activate) before higher-intent work.', 'Move with control; this prepares your ankle for training.', 'Foot activation', 'activate', 'foot_activation', '{"primary_joint_actions":["ankle_inversion","ankle_eversion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"single_leg","impact_level":0}'::jsonb, '{"movement_description":"Weight shifts through heel, big toe, little toe.","setup":["Single leg stand"],"execution_steps":["Shift weight to heel, then ball, then edges"],"coach_cues":["Quiet upper body"],"common_faults":["Hip hiking"]}'::jsonb),
  ('Low Pogos', 'low-pogos', 'Low-amplitude ankle bounces.', 'BEGINNER', 8, 2, 10, NULL, 30, 25, 'Elastic ankle stiffness, light SSC.', 'Use in Prepare / Access (potentiate bridge) before higher-intent work.', 'Move with control; this prepares your ankle for training.', 'Elastic prep', 'potentiate_bridge', 'low_level_plyo_prep', '{"primary_joint_actions":["ankle_plantarflexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":2}'::jsonb, '{"movement_description":"Low-amplitude ankle bounces.","setup":["Stand tall, soft knees"],"execution_steps":["Small quick bounces off floor","Minimal knee bend"],"coach_cues":["Stiff ankles","Quiet landings"],"common_faults":["Deep squatting between reps"]}'::jsonb),
  ('Jump Rope Easy Bounce', 'jump-rope-easy-bounce', 'Light rope or mimed bounce for rhythm.', 'BEGINNER', 6, 2, NULL, 30, 30, 35, 'Rhythm, foot/ankle temperature.', 'Use in Prepare / Access (raise) before higher-intent work.', 'Move with control; this prepares your full body for training.', 'Rhythm warm-up', 'raise', 'rhythm_warmup', '{"primary_joint_actions":["ankle_plantarflexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":2}'::jsonb, '{"movement_description":"Light rope or mimed bounce for rhythm.","setup":["Hold rope or mime bounce"],"execution_steps":["Easy double-foot bounce","Stay on balls of feet"],"coach_cues":["Relax shoulders"],"common_faults":["Jumping too high"]}'::jsonb),
  ('Walking Knee Hug', 'walking-knee-hug', 'Walk with knee-to-chest pulls.', 'EARLY_STAGE', 4, 2, 10, NULL, 15, 40, 'Hip flexion, single-leg balance.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Hip mobility', 'mobilize', 'hip_mobility', '{"primary_joint_actions":["hip_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"single_leg","impact_level":0}'::jsonb, '{"movement_description":"Walk with knee-to-chest pulls.","setup":["Walk forward"],"execution_steps":["Pull knee to chest","Alternate legs"],"coach_cues":["Stand tall on support leg"],"common_faults":["Rounding back"]}'::jsonb),
  ('Walking Quad Pull', 'walking-quad-pull', 'Walk with standing quad stretch.', 'BEGINNER', 6, 2, 10, NULL, 15, 40, 'Hip extension, quad length, balance.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Hip mobility', 'mobilize', 'hip_mobility', '{"primary_joint_actions":["hip_extension","knee_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"single_leg","impact_level":0}'::jsonb, '{"movement_description":"Walk with standing quad stretch.","setup":["Walk forward"],"execution_steps":["Grab ankle, pull heel to glute","Keep knees together"],"coach_cues":["Tall posture"],"common_faults":["Arching lower back"]}'::jsonb),
  ('Leg Swings Front Back', 'leg-swings-front-back', 'Dynamic hip flexion/extension swings.', 'BEGINNER', 8, 2, 10, NULL, 15, 30, 'Hip flexion/extension.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Hip mobility', 'mobilize', 'hip_mobility', '{"primary_joint_actions":["hip_flexion","hip_extension"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Dynamic hip flexion/extension swings.","setup":["Hold wall for balance"],"execution_steps":["Swing leg forward and back","Stay tall, no trunk lean"],"coach_cues":["Control at end range"],"common_faults":["Throwing leg violently"]}'::jsonb),
  ('Leg Swings Lateral', 'leg-swings-lateral', 'Frontal-plane leg swings.', 'BEGINNER', 8, 2, 10, NULL, 15, 30, 'Hip abduction/adduction.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Hip mobility', 'mobilize', 'hip_mobility', '{"primary_joint_actions":["hip_abduction"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Frontal-plane leg swings.","setup":["Face wall, hand support"],"execution_steps":["Swing leg across and out"],"coach_cues":["Pelvis stays square"],"common_faults":["Rotating trunk"]}'::jsonb),
  ('90/90 Hip Switch', '9090-hip-switch', 'Seated 90/90 hip internal/external rotation switches.', 'BEGINNER', 8, 2, 8, NULL, 20, 45, 'Hip internal/external rotation.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Hip mobility', 'mobilize', 'hip_mobility', '{"primary_joint_actions":["hip_rotation"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Seated 90/90 hip internal/external rotation switches.","setup":["Seated 90/90, hands behind for support"],"execution_steps":["Lift knees and switch sides","Control the transition"],"coach_cues":["Stay tall"],"common_faults":["Using momentum to flop"]}'::jsonb),
  ('Shin Box Switch', 'shin-box-switch', 'Shin box position hip switches.', 'INTERMEDIATE', 10, 2, 6, NULL, 20, 40, 'Hip rotation, trunk control.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Hip mobility', 'mobilize', 'hip_mobility', '{"primary_joint_actions":["hip_rotation"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Shin box position hip switches.","setup":["Shin box seated"],"execution_steps":["Switch legs to opposite 90/90"],"coach_cues":["Hands light on floor"],"common_faults":["Collapsing into one hip"]}'::jsonb),
  ('Shin Box Get-Up', 'shin-box-get-up', 'Rise from shin box to kneeling or standing.', 'INTERMEDIATE', 10, 2, 4, NULL, 30, 45, 'Hip rotation to locomotion.', 'Use in Prepare / Access (integrate) before higher-intent work.', 'Move with control; this prepares your full body for training.', 'Hip integration', 'integrate', 'full_body_flow', '{"primary_joint_actions":["hip_rotation","hip_extension"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Rise from shin box to kneeling or standing.","setup":["Start in shin box"],"execution_steps":["Rotate and extend to half-kneeling","Optional stand"],"coach_cues":["Drive through front foot"],"common_faults":["Using hands to push off floor"]}'::jsonb),
  ('Hip CARs', 'hip-cars', 'Standing or quadruped hip controlled rotations.', 'BEGINNER', 8, 2, 4, NULL, 15, 35, 'Active hip control.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Hip mobility', 'mobilize', 'hip_mobility', '{"primary_joint_actions":["hip_rotation","hip_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Standing or quadruped hip controlled rotations.","setup":["Stand on one leg or quadruped"],"execution_steps":["Draw slow circles with knee"],"coach_cues":["Keep pelvis still"],"common_faults":["Trunk sway"]}'::jsonb),
  ('Adductor Rockback', 'adductor-rockback', 'Half-kneeling adductor stretch rock.', 'BEGINNER', 8, 2, 8, NULL, 15, 35, 'Adductors, groin, hinge.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Hip mobility', 'mobilize', 'hip_mobility', '{"primary_joint_actions":["hip_abduction"],"primary_tissues":["adductors"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Half-kneeling adductor stretch rock.","setup":["Half-kneeling wide stance"],"execution_steps":["Rock toward straight leg side"],"coach_cues":["Flat back"],"common_faults":["Rounding spine"]}'::jsonb),
  ('Frog Rockback', 'frog-rockback', 'Quadruped wide-knee rockback.', 'BEGINNER', 8, 2, 8, NULL, 20, 40, 'Hip abduction, adductor tissue.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Hip mobility', 'mobilize', 'hip_mobility', '{"primary_joint_actions":["hip_abduction"],"primary_tissues":["adductors"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Quadruped wide-knee rockback.","setup":["Quadruped, knees wide"],"execution_steps":["Rock hips back toward heels"],"coach_cues":["Keep spine neutral"],"common_faults":["Collapsing into low back flexion"]}'::jsonb),
  ('Cossack Shift', 'cossack-shift', 'Low-amplitude lateral lunge shift.', 'INTERMEDIATE', 10, 2, 6, NULL, 20, 40, 'Frontal-plane hip/ankle access.', 'Use in Prepare / Access (mobilize) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Hip mobility', 'mobilize', 'hip_mobility', '{"primary_joint_actions":["hip_abduction","ankle_dorsiflexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"single_leg","impact_level":0}'::jsonb, '{"movement_description":"Low-amplitude lateral lunge shift.","setup":["Wide stance, toes forward or slightly out"],"execution_steps":["Shift to one side keeping heel down","Alternate sides"],"coach_cues":["Chest up"],"common_faults":["Heel lifting on bent leg side"]}'::jsonb),
  ('Deep Squat Pry', 'deep-squat-pry', 'Hold deep squat and pry knees open.', 'BEGINNER', 8, 2, NULL, 30, 20, 35, 'Squat bottom, hips, ankles, trunk.', 'Use in Prepare / Access (integrate) before higher-intent work.', 'Move with control; this prepares your full body for training.', 'Squat access', 'integrate', 'squat_to_stand', '{"primary_joint_actions":["hip_flexion","ankle_dorsiflexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Hold deep squat and pry knees open.","setup":["Deep squat, elbows inside knees"],"execution_steps":["Pry knees out with elbows","Breathe and relax into position"],"coach_cues":["Heels down","Chest up"],"common_faults":["Heels lifting","Rounding upper back"]}'::jsonb),
  ('Squat-to-Stand with Reach', 'squat-to-stand-with-reach', 'Deep squat hold to stand with overhead reach.', 'BEGINNER', 6, 2, 6, NULL, 20, 40, 'Hamstrings, squat access, T-spine.', 'Use in Prepare / Access (integrate) before higher-intent work.', 'Move with control; this prepares your full body for training.', 'Squat access', 'integrate', 'squat_to_stand', '{"primary_joint_actions":["hip_flexion","shoulder_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Deep squat hold to stand with overhead reach.","setup":["Hold bottom of squat"],"execution_steps":["Reach arms up as you stand","Return to squat with control"],"coach_cues":["Weight through mid-foot"],"common_faults":["Rolling onto toes"]}'::jsonb),
  ('Lateral Lunge Shift', 'lateral-lunge-shift', 'Side-to-side lateral lunge patterning.', 'BEGINNER', 8, 2, 6, NULL, 20, 40, 'Frontal-plane loading, adductors.', 'Use in Prepare / Access (integrate) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Lunge pattern', 'integrate', 'lunge_pattern_prep', '{"primary_joint_actions":["hip_abduction","knee_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Side-to-side lateral lunge patterning.","setup":["Stand wide"],"execution_steps":["Shift to one side into lateral lunge","Drive back to center"],"coach_cues":["Knee tracks over foot"],"common_faults":["Knee collapsing inward"]}'::jsonb),
  ('Glute Bridge', 'glute-bridge', 'Supine hip extension bridge.', 'EARLY_STAGE', 6, 2, 12, NULL, 20, 35, 'Hip extension, glute activation.', 'Use in Prepare / Access (activate) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Glute activation', 'activate', 'glute_activation', '{"primary_joint_actions":["hip_extension"],"primary_tissues":["glutes"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Supine hip extension bridge.","setup":["Supine, knees bent, feet flat"],"execution_steps":["Drive through heels, lift hips","Squeeze glutes at top"],"coach_cues":["Ribs down","Knees hip-width"],"common_faults":["Over-arching lumbar spine"]}'::jsonb),
  ('Glute Bridge March', 'glute-bridge-march', 'Bridge hold with alternating leg march.', 'BEGINNER', 8, 2, 8, NULL, 25, 40, 'Pelvic control, glute/trunk integration.', 'Use in Prepare / Access (activate) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Glute activation', 'activate', 'glute_activation', '{"primary_joint_actions":["hip_extension","hip_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Bridge hold with alternating leg march.","setup":["Bridge position"],"execution_steps":["Lift one foot without dropping hips","Alternate"],"coach_cues":["Level pelvis"],"common_faults":["Hips dropping on lift"]}'::jsonb),
  ('Dead Bug Heel Tap', 'dead-bug-heel-tap', 'Supine dead bug with heel taps.', 'EARLY_STAGE', 6, 2, 8, NULL, 20, 35, 'Anterior core, rib-pelvis control.', 'Use in Prepare / Access (activate) before higher-intent work.', 'Move with control; this prepares your core for training.', 'Core activation', 'activate', 'core_activation', '{"primary_joint_actions":["hip_flexion","shoulder_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Supine dead bug with heel taps.","setup":["Supine, arms up, knees 90°"],"execution_steps":["Lower heel to floor one side","Return with ribs down"],"coach_cues":["Press low back to floor"],"common_faults":["Lower back arching"]}'::jsonb),
  ('Bird Dog', 'bird-dog', 'Quadruped opposite arm/leg reach.', 'EARLY_STAGE', 6, 2, 6, NULL, 20, 35, 'Cross-body trunk control.', 'Use in Prepare / Access (activate) before higher-intent work.', 'Move with control; this prepares your core for training.', 'Core activation', 'activate', 'core_activation', '{"primary_joint_actions":["hip_extension","shoulder_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"single_leg","impact_level":0}'::jsonb, '{"movement_description":"Quadruped opposite arm/leg reach.","setup":["Quadruped neutral"],"execution_steps":["Reach opposite arm and leg long","Hold 2 seconds"],"coach_cues":["Hips level"],"common_faults":["Rotating or sagging"]}'::jsonb),
  ('Mini-Band Lateral Walk', 'mini-band-lateral-walk', 'Band-resisted lateral steps.', 'BEGINNER', 10, 2, 10, NULL, 25, 35, 'Glute medius, knee tracking.', 'Use in Prepare / Access (activate) before higher-intent work.', 'Move with control; this prepares your hip for training.', 'Glute activation', 'activate', 'glute_activation', '{"primary_joint_actions":["hip_abduction"],"primary_tissues":["glute_med"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Band-resisted lateral steps.","setup":["Band above knees, quarter squat"],"execution_steps":["Step laterally maintaining tension","No feet together"],"coach_cues":["Knees out"],"common_faults":["Standing up between steps"]}'::jsonb),
  ('A-March', 'a-march', 'Marching mechanics with postural emphasis.', 'BEGINNER', 8, 2, 10, NULL, 30, 40, 'Sprint posture, rhythm, neural readiness.', 'Use in Prepare / Access (potentiate bridge) before higher-intent work.', 'Move with control; this prepares your full body for training.', 'Sprint posture prep', 'potentiate_bridge', 'marching_mechanics', '{"primary_joint_actions":["hip_flexion","ankle_dorsiflexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb, '{"movement_description":"Marching mechanics with postural emphasis.","setup":["Stand tall"],"execution_steps":["Drive knee to hip height","Opposite arm swing","Quick ground contact"],"coach_cues":["Tall posture","Toes up"],"common_faults":["Leaning back","Slow lazy steps"]}'::jsonb)
) AS d(name, slug, description, skill, age_min, sets, reps, work, rest, est, summary, coach_lang, athlete_lang, family, subrole, slot, req, exec)
ON CONFLICT (facility_id, slug) DO NOTHING;

-- Fix finger-pulses: wrist_prep slot maps to mobilize (dual subrole — primary mobilize per plan)
UPDATE coaching.exercise SET
  phase_subrole = 'mobilize',
  coach_language = 'Use in Prepare / Access (mobilize) before higher-intent work. Secondary intent: hand intrinsic activation.',
  updated_at = now()
WHERE slug = 'finger-pulses' AND primary_phase_key = 'prepare_access';

-- Update existing World's Greatest Stretch
UPDATE coaching.exercise SET
  card_summary = 'Hip flexor, hamstring, T-spine, lunge pattern.',
  coach_language = 'Use in Prepare / Access (integrate) as a dynamic full-body opener.',
  movement_family = 'Integrated mobility',
  primary_phase_key = 'prepare_access',
  phase_subrole = 'integrate',
  primary_order_slot = 'integrated_mobility',
  movement_requirements = '{"primary_joint_actions":["hip_flexion","thoracic_rotation"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb,
  coaching_execution = '{"movement_description":"Dynamic lunge with thoracic rotation and hamstring stretch.","setup":["Lunge forward, back knee down"],"execution_steps":["Place same-side elbow inside front foot","Rotate and reach sky"],"coach_cues":["Keep back leg long"],"common_faults":["Collapsing forward"]}'::jsonb,
  updated_at = now()
WHERE slug = 'worlds-greatest-stretch';

-- 2) Taxonomy tags
INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'tenet', f.id, 4
FROM (VALUES
  ('9090-breathing-with-reach', 'body_control'),
  ('9090-breathing-with-reach', 'flexibility'),
  ('crocodile-breathing', 'body_control'),
  ('crocodile-breathing', 'flexibility'),
  ('full-body-joint-cars-flow', 'flexibility'),
  ('full-body-joint-cars-flow', 'coordination'),
  ('neck-cars', 'body_control'),
  ('neck-cars', 'coordination'),
  ('cat-cow', 'flexibility'),
  ('cat-cow', 'body_control'),
  ('quadruped-spinal-circles', 'flexibility'),
  ('quadruped-spinal-circles', 'coordination'),
  ('quadruped-thread-the-needle', 'flexibility'),
  ('quadruped-thread-the-needle', 'body_control'),
  ('side-lying-open-book', 'flexibility'),
  ('inchworm-walkout', 'flexibility'),
  ('inchworm-walkout', 'coordination'),
  ('wrist-rockers-palms-down', 'flexibility'),
  ('wrist-rockers-palms-down', 'body_control'),
  ('wrist-rockers-palms-up', 'flexibility'),
  ('finger-pulses', 'strength'),
  ('finger-pulses', 'body_control'),
  ('scapular-push-up', 'body_control'),
  ('scapular-push-up', 'strength'),
  ('quadruped-shoulder-circles', 'flexibility'),
  ('quadruped-shoulder-circles', 'coordination'),
  ('wall-slides-with-lift-off', 'flexibility'),
  ('wall-slides-with-lift-off', 'body_control'),
  ('band-external-rotation', 'strength'),
  ('band-external-rotation', 'body_control'),
  ('arm-circles', 'flexibility'),
  ('arm-circles', 'coordination'),
  ('bear-crawl-rock-back', 'coordination'),
  ('bear-crawl-rock-back', 'body_control'),
  ('down-dog-to-plank-wave', 'flexibility'),
  ('down-dog-to-plank-wave', 'body_control'),
  ('knee-to-wall-ankle-rockers', 'flexibility'),
  ('knee-to-wall-ankle-rockers', 'body_control'),
  ('half-kneeling-ankle-dorsiflexion-pulse', 'flexibility'),
  ('ankle-cars', 'flexibility'),
  ('ankle-cars', 'coordination'),
  ('tibialis-raises', 'strength'),
  ('tibialis-raises', 'body_control'),
  ('calf-raise-to-heel-drop', 'strength'),
  ('calf-raise-to-heel-drop', 'flexibility'),
  ('toe-yoga', 'body_control'),
  ('toe-yoga', 'coordination'),
  ('short-foot-drill', 'body_control'),
  ('short-foot-drill', 'strength'),
  ('foot-tripod-weight-shifts', 'balance'),
  ('foot-tripod-weight-shifts', 'body_control'),
  ('low-pogos', 'explosiveness'),
  ('low-pogos', 'coordination'),
  ('jump-rope-easy-bounce', 'coordination'),
  ('jump-rope-easy-bounce', 'speed'),
  ('walking-knee-hug', 'flexibility'),
  ('walking-knee-hug', 'balance'),
  ('walking-quad-pull', 'flexibility'),
  ('walking-quad-pull', 'balance'),
  ('leg-swings-front-back', 'flexibility'),
  ('leg-swings-front-back', 'coordination'),
  ('leg-swings-lateral', 'flexibility'),
  ('leg-swings-lateral', 'coordination'),
  ('9090-hip-switch', 'flexibility'),
  ('9090-hip-switch', 'body_control'),
  ('shin-box-switch', 'flexibility'),
  ('shin-box-switch', 'coordination'),
  ('shin-box-get-up', 'coordination'),
  ('shin-box-get-up', 'strength'),
  ('hip-cars', 'flexibility'),
  ('hip-cars', 'coordination'),
  ('adductor-rockback', 'flexibility'),
  ('frog-rockback', 'flexibility'),
  ('cossack-shift', 'flexibility'),
  ('cossack-shift', 'balance'),
  ('deep-squat-pry', 'flexibility'),
  ('deep-squat-pry', 'body_control'),
  ('squat-to-stand-with-reach', 'flexibility'),
  ('squat-to-stand-with-reach', 'coordination'),
  ('lateral-lunge-shift', 'flexibility'),
  ('lateral-lunge-shift', 'strength'),
  ('glute-bridge', 'strength'),
  ('glute-bridge', 'body_control'),
  ('glute-bridge-march', 'strength'),
  ('glute-bridge-march', 'body_control'),
  ('dead-bug-heel-tap', 'body_control'),
  ('dead-bug-heel-tap', 'coordination'),
  ('bird-dog', 'body_control'),
  ('bird-dog', 'coordination'),
  ('bird-dog', 'balance'),
  ('mini-band-lateral-walk', 'strength'),
  ('mini-band-lateral-walk', 'body_control'),
  ('a-march', 'speed'),
  ('a-march', 'coordination'),
  ('a-march', 'body_control'),
  ('worlds-greatest-stretch', 'flexibility'),
  ('worlds-greatest-stretch', 'coordination')
) AS v(slug, fkey)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.tenet f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO NOTHING;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'methodology', f.id, 4
FROM (VALUES
  ('9090-breathing-with-reach', 'mobility_flexibility'),
  ('9090-breathing-with-reach', 'core_body_control'),
  ('crocodile-breathing', 'mobility_flexibility'),
  ('full-body-joint-cars-flow', 'mobility_flexibility'),
  ('full-body-joint-cars-flow', 'neural'),
  ('neck-cars', 'mobility_flexibility'),
  ('cat-cow', 'mobility_flexibility'),
  ('quadruped-spinal-circles', 'mobility_flexibility'),
  ('quadruped-spinal-circles', 'core_body_control'),
  ('quadruped-thread-the-needle', 'mobility_flexibility'),
  ('side-lying-open-book', 'mobility_flexibility'),
  ('inchworm-walkout', 'mobility_flexibility'),
  ('inchworm-walkout', 'core_body_control'),
  ('wrist-rockers-palms-down', 'mobility_flexibility'),
  ('wrist-rockers-palms-up', 'mobility_flexibility'),
  ('finger-pulses', 'isometrics'),
  ('finger-pulses', 'core_body_control'),
  ('scapular-push-up', 'core_body_control'),
  ('scapular-push-up', 'isometrics'),
  ('quadruped-shoulder-circles', 'mobility_flexibility'),
  ('wall-slides-with-lift-off', 'mobility_flexibility'),
  ('band-external-rotation', 'resistance_calisthenics'),
  ('band-external-rotation', 'isometrics'),
  ('arm-circles', 'mobility_flexibility'),
  ('arm-circles', 'neural'),
  ('bear-crawl-rock-back', 'mobility_flexibility'),
  ('bear-crawl-rock-back', 'core_body_control'),
  ('down-dog-to-plank-wave', 'mobility_flexibility'),
  ('down-dog-to-plank-wave', 'core_body_control'),
  ('knee-to-wall-ankle-rockers', 'mobility_flexibility'),
  ('half-kneeling-ankle-dorsiflexion-pulse', 'mobility_flexibility'),
  ('ankle-cars', 'mobility_flexibility'),
  ('tibialis-raises', 'isometrics'),
  ('tibialis-raises', 'resistance_calisthenics'),
  ('calf-raise-to-heel-drop', 'eccentric_negative'),
  ('calf-raise-to-heel-drop', 'mobility_flexibility'),
  ('toe-yoga', 'isometrics'),
  ('toe-yoga', 'core_body_control'),
  ('short-foot-drill', 'isometrics'),
  ('foot-tripod-weight-shifts', 'balance_stability'),
  ('low-pogos', 'plyometrics'),
  ('low-pogos', 'neural'),
  ('jump-rope-easy-bounce', 'neural'),
  ('jump-rope-easy-bounce', 'plyometrics'),
  ('walking-knee-hug', 'mobility_flexibility'),
  ('walking-knee-hug', 'balance_stability'),
  ('walking-quad-pull', 'mobility_flexibility'),
  ('leg-swings-front-back', 'mobility_flexibility'),
  ('leg-swings-front-back', 'neural'),
  ('leg-swings-lateral', 'mobility_flexibility'),
  ('9090-hip-switch', 'mobility_flexibility'),
  ('shin-box-switch', 'mobility_flexibility'),
  ('shin-box-switch', 'core_body_control'),
  ('shin-box-get-up', 'mobility_flexibility'),
  ('shin-box-get-up', 'core_body_control'),
  ('hip-cars', 'mobility_flexibility'),
  ('adductor-rockback', 'mobility_flexibility'),
  ('frog-rockback', 'mobility_flexibility'),
  ('cossack-shift', 'mobility_flexibility'),
  ('cossack-shift', 'balance_stability'),
  ('deep-squat-pry', 'mobility_flexibility'),
  ('squat-to-stand-with-reach', 'mobility_flexibility'),
  ('lateral-lunge-shift', 'mobility_flexibility'),
  ('lateral-lunge-shift', 'balance_stability'),
  ('glute-bridge', 'isometrics'),
  ('glute-bridge', 'core_body_control'),
  ('glute-bridge-march', 'core_body_control'),
  ('glute-bridge-march', 'isometrics'),
  ('dead-bug-heel-tap', 'core_body_control'),
  ('dead-bug-heel-tap', 'isometrics'),
  ('bird-dog', 'core_body_control'),
  ('bird-dog', 'balance_stability'),
  ('mini-band-lateral-walk', 'resistance_calisthenics'),
  ('mini-band-lateral-walk', 'balance_stability'),
  ('a-march', 'neural'),
  ('a-march', 'mobility_flexibility'),
  ('worlds-greatest-stretch', 'mobility_flexibility'),
  ('worlds-greatest-stretch', 'core_body_control')
) AS v(slug, fkey)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.methodology f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO NOTHING;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'physiology', f.id, 4
FROM (VALUES
  ('9090-breathing-with-reach', 'control_stability'),
  ('crocodile-breathing', 'control_stability'),
  ('full-body-joint-cars-flow', 'control_stability'),
  ('full-body-joint-cars-flow', 'perception_action_skill'),
  ('neck-cars', 'control_stability'),
  ('cat-cow', 'control_stability'),
  ('quadruped-spinal-circles', 'control_stability'),
  ('quadruped-thread-the-needle', 'control_stability'),
  ('side-lying-open-book', 'control_stability'),
  ('inchworm-walkout', 'control_stability'),
  ('inchworm-walkout', 'force_tissue_capacity'),
  ('wrist-rockers-palms-down', 'control_stability'),
  ('wrist-rockers-palms-up', 'control_stability'),
  ('finger-pulses', 'control_stability'),
  ('scapular-push-up', 'control_stability'),
  ('quadruped-shoulder-circles', 'control_stability'),
  ('wall-slides-with-lift-off', 'control_stability'),
  ('band-external-rotation', 'control_stability'),
  ('arm-circles', 'control_stability'),
  ('bear-crawl-rock-back', 'control_stability'),
  ('bear-crawl-rock-back', 'perception_action_skill'),
  ('down-dog-to-plank-wave', 'control_stability'),
  ('knee-to-wall-ankle-rockers', 'control_stability'),
  ('half-kneeling-ankle-dorsiflexion-pulse', 'control_stability'),
  ('ankle-cars', 'control_stability'),
  ('tibialis-raises', 'control_stability'),
  ('calf-raise-to-heel-drop', 'force_tissue_capacity'),
  ('toe-yoga', 'control_stability'),
  ('short-foot-drill', 'control_stability'),
  ('foot-tripod-weight-shifts', 'control_stability'),
  ('foot-tripod-weight-shifts', 'perception_action_skill'),
  ('low-pogos', 'ssc_stiffness'),
  ('low-pogos', 'neural_output_readiness'),
  ('jump-rope-easy-bounce', 'neural_output_readiness'),
  ('jump-rope-easy-bounce', 'energy_systems_repeatability'),
  ('walking-knee-hug', 'control_stability'),
  ('walking-quad-pull', 'control_stability'),
  ('leg-swings-front-back', 'control_stability'),
  ('leg-swings-lateral', 'control_stability'),
  ('9090-hip-switch', 'control_stability'),
  ('shin-box-switch', 'control_stability'),
  ('shin-box-get-up', 'control_stability'),
  ('shin-box-get-up', 'perception_action_skill'),
  ('hip-cars', 'control_stability'),
  ('adductor-rockback', 'force_tissue_capacity'),
  ('frog-rockback', 'force_tissue_capacity'),
  ('cossack-shift', 'control_stability'),
  ('deep-squat-pry', 'control_stability'),
  ('squat-to-stand-with-reach', 'control_stability'),
  ('lateral-lunge-shift', 'control_stability'),
  ('glute-bridge', 'control_stability'),
  ('glute-bridge', 'force_tissue_capacity'),
  ('glute-bridge-march', 'control_stability'),
  ('dead-bug-heel-tap', 'control_stability'),
  ('bird-dog', 'control_stability'),
  ('bird-dog', 'perception_action_skill'),
  ('mini-band-lateral-walk', 'control_stability'),
  ('a-march', 'neural_output_readiness'),
  ('a-march', 'perception_action_skill'),
  ('worlds-greatest-stretch', 'control_stability'),
  ('worlds-greatest-stretch', 'force_tissue_capacity')
) AS v(slug, fkey)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.physiological_emphasis f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO NOTHING;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'pattern', f.id, 4
FROM (VALUES
  ('9090-breathing-with-reach', 'brace'),
  ('crocodile-breathing', 'brace'),
  ('full-body-joint-cars-flow', 'locomote'),
  ('neck-cars', 'rotate'),
  ('cat-cow', 'brace'),
  ('quadruped-spinal-circles', 'brace'),
  ('quadruped-thread-the-needle', 'rotate'),
  ('side-lying-open-book', 'rotate'),
  ('inchworm-walkout', 'locomote'),
  ('wrist-rockers-palms-down', 'brace'),
  ('wrist-rockers-palms-up', 'brace'),
  ('finger-pulses', 'brace'),
  ('scapular-push-up', 'push'),
  ('quadruped-shoulder-circles', 'rotate'),
  ('wall-slides-with-lift-off', 'push'),
  ('band-external-rotation', 'pull'),
  ('arm-circles', 'rotate'),
  ('bear-crawl-rock-back', 'locomote'),
  ('down-dog-to-plank-wave', 'locomote'),
  ('knee-to-wall-ankle-rockers', 'squat'),
  ('half-kneeling-ankle-dorsiflexion-pulse', 'squat'),
  ('ankle-cars', 'rotate'),
  ('tibialis-raises', 'brace'),
  ('calf-raise-to-heel-drop', 'squat'),
  ('toe-yoga', 'brace'),
  ('short-foot-drill', 'brace'),
  ('foot-tripod-weight-shifts', 'brace'),
  ('low-pogos', 'jump'),
  ('jump-rope-easy-bounce', 'jump'),
  ('walking-knee-hug', 'locomote'),
  ('walking-quad-pull', 'locomote'),
  ('leg-swings-front-back', 'locomote'),
  ('leg-swings-lateral', 'locomote'),
  ('9090-hip-switch', 'rotate'),
  ('shin-box-switch', 'rotate'),
  ('shin-box-get-up', 'locomote'),
  ('hip-cars', 'rotate'),
  ('adductor-rockback', 'hinge'),
  ('frog-rockback', 'squat'),
  ('cossack-shift', 'squat'),
  ('deep-squat-pry', 'squat'),
  ('squat-to-stand-with-reach', 'squat'),
  ('lateral-lunge-shift', 'squat'),
  ('glute-bridge', 'hinge'),
  ('glute-bridge-march', 'hinge'),
  ('dead-bug-heel-tap', 'brace'),
  ('bird-dog', 'brace'),
  ('mini-band-lateral-walk', 'locomote'),
  ('a-march', 'locomote'),
  ('worlds-greatest-stretch', 'locomote')
) AS v(slug, fkey)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.movement_pattern f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO NOTHING;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'equipment', f.id, 4
FROM (VALUES
  ('9090-breathing-with-reach', 'mat'),
  ('crocodile-breathing', 'mat'),
  ('full-body-joint-cars-flow', 'none'),
  ('neck-cars', 'none'),
  ('cat-cow', 'mat'),
  ('quadruped-spinal-circles', 'mat'),
  ('quadruped-thread-the-needle', 'mat'),
  ('side-lying-open-book', 'mat'),
  ('inchworm-walkout', 'none'),
  ('wrist-rockers-palms-down', 'mat'),
  ('wrist-rockers-palms-up', 'mat'),
  ('finger-pulses', 'mat'),
  ('scapular-push-up', 'none'),
  ('quadruped-shoulder-circles', 'mat'),
  ('wall-slides-with-lift-off', 'none'),
  ('band-external-rotation', 'bands'),
  ('arm-circles', 'none'),
  ('bear-crawl-rock-back', 'mat'),
  ('down-dog-to-plank-wave', 'mat'),
  ('knee-to-wall-ankle-rockers', 'none'),
  ('half-kneeling-ankle-dorsiflexion-pulse', 'mat'),
  ('ankle-cars', 'none'),
  ('tibialis-raises', 'none'),
  ('calf-raise-to-heel-drop', 'none'),
  ('toe-yoga', 'none'),
  ('short-foot-drill', 'none'),
  ('foot-tripod-weight-shifts', 'none'),
  ('low-pogos', 'none'),
  ('jump-rope-easy-bounce', 'none'),
  ('walking-knee-hug', 'none'),
  ('walking-quad-pull', 'none'),
  ('leg-swings-front-back', 'none'),
  ('leg-swings-lateral', 'none'),
  ('9090-hip-switch', 'mat'),
  ('shin-box-switch', 'mat'),
  ('shin-box-get-up', 'mat'),
  ('hip-cars', 'none'),
  ('adductor-rockback', 'mat'),
  ('frog-rockback', 'mat'),
  ('cossack-shift', 'none'),
  ('deep-squat-pry', 'none'),
  ('squat-to-stand-with-reach', 'none'),
  ('lateral-lunge-shift', 'none'),
  ('glute-bridge', 'mat'),
  ('glute-bridge-march', 'mat'),
  ('dead-bug-heel-tap', 'mat'),
  ('bird-dog', 'mat'),
  ('mini-band-lateral-walk', 'bands'),
  ('a-march', 'none'),
  ('worlds-greatest-stretch', 'none')
) AS v(slug, fkey)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.equipment f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO NOTHING;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'body_region', f.id, 4
FROM (VALUES
  ('9090-breathing-with-reach', 'spine'),
  ('crocodile-breathing', 'spine'),
  ('full-body-joint-cars-flow', 'full_body'),
  ('neck-cars', 'spine'),
  ('cat-cow', 'spine'),
  ('quadruped-spinal-circles', 'spine'),
  ('quadruped-thread-the-needle', 'spine'),
  ('side-lying-open-book', 'spine'),
  ('inchworm-walkout', 'full_body'),
  ('wrist-rockers-palms-down', 'wrist'),
  ('wrist-rockers-palms-up', 'wrist'),
  ('finger-pulses', 'wrist'),
  ('scapular-push-up', 'shoulder'),
  ('quadruped-shoulder-circles', 'shoulder'),
  ('wall-slides-with-lift-off', 'shoulder'),
  ('band-external-rotation', 'shoulder'),
  ('arm-circles', 'shoulder'),
  ('bear-crawl-rock-back', 'full_body'),
  ('down-dog-to-plank-wave', 'full_body'),
  ('knee-to-wall-ankle-rockers', 'ankle'),
  ('half-kneeling-ankle-dorsiflexion-pulse', 'ankle'),
  ('ankle-cars', 'ankle'),
  ('tibialis-raises', 'ankle'),
  ('calf-raise-to-heel-drop', 'ankle'),
  ('toe-yoga', 'ankle'),
  ('short-foot-drill', 'ankle'),
  ('foot-tripod-weight-shifts', 'ankle'),
  ('low-pogos', 'ankle'),
  ('jump-rope-easy-bounce', 'full_body'),
  ('walking-knee-hug', 'hip'),
  ('walking-quad-pull', 'hip'),
  ('leg-swings-front-back', 'hip'),
  ('leg-swings-lateral', 'hip'),
  ('9090-hip-switch', 'hip'),
  ('shin-box-switch', 'hip'),
  ('shin-box-get-up', 'full_body'),
  ('hip-cars', 'hip'),
  ('adductor-rockback', 'hip'),
  ('frog-rockback', 'hip'),
  ('cossack-shift', 'hip'),
  ('deep-squat-pry', 'full_body'),
  ('squat-to-stand-with-reach', 'full_body'),
  ('lateral-lunge-shift', 'hip'),
  ('glute-bridge', 'hip'),
  ('glute-bridge-march', 'hip'),
  ('dead-bug-heel-tap', 'core'),
  ('bird-dog', 'core'),
  ('mini-band-lateral-walk', 'hip'),
  ('a-march', 'full_body'),
  ('worlds-greatest-stretch', 'full_body')
) AS v(slug, fkey)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.body_region f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO NOTHING;

-- 3) Prepare / Access phase profiles
INSERT INTO coaching.exercise_phase_profile (
  exercise_id, phase_id, fit_weight, role, order_slot, order_index,
  freshness_required, fatigue_sensitivity, fatigue_cost, technical_complexity, impact_level, intensity_ceiling
)
SELECT e.id, sp.id, 5, 'primary', m.slot, pos.order_index,
  FALSE, 1, 1, 2, m.impact, 'low'
FROM (VALUES
  ('9090-breathing-with-reach', 'breathing_reset', 0),
  ('crocodile-breathing', 'breathing_reset', 0),
  ('full-body-joint-cars-flow', 'joint_scan', 0),
  ('neck-cars', 'joint_scan', 0),
  ('cat-cow', 'spinal_mobility', 0),
  ('quadruped-spinal-circles', 'spinal_mobility', 0),
  ('quadruped-thread-the-needle', 'thoracic_rotation', 0),
  ('side-lying-open-book', 'thoracic_rotation', 0),
  ('inchworm-walkout', 'crawl_pattern_prep', 0),
  ('wrist-rockers-palms-down', 'wrist_prep', 0),
  ('wrist-rockers-palms-up', 'wrist_prep', 0),
  ('finger-pulses', 'wrist_prep', 0),
  ('scapular-push-up', 'scapular_activation', 0),
  ('quadruped-shoulder-circles', 'shoulder_mobility', 0),
  ('wall-slides-with-lift-off', 'shoulder_mobility', 0),
  ('band-external-rotation', 'rotator_cuff_activation', 0),
  ('arm-circles', 'shoulder_mobility', 0),
  ('bear-crawl-rock-back', 'crawl_pattern_prep', 0),
  ('down-dog-to-plank-wave', 'crawl_pattern_prep', 0),
  ('knee-to-wall-ankle-rockers', 'ankle_mobility', 0),
  ('half-kneeling-ankle-dorsiflexion-pulse', 'ankle_mobility', 0),
  ('ankle-cars', 'ankle_mobility', 0),
  ('tibialis-raises', 'foot_activation', 0),
  ('calf-raise-to-heel-drop', 'foot_activation', 0),
  ('toe-yoga', 'foot_activation', 0),
  ('short-foot-drill', 'foot_activation', 0),
  ('foot-tripod-weight-shifts', 'foot_activation', 0),
  ('low-pogos', 'low_level_plyo_prep', 2),
  ('jump-rope-easy-bounce', 'rhythm_warmup', 2),
  ('walking-knee-hug', 'hip_mobility', 0),
  ('walking-quad-pull', 'hip_mobility', 0),
  ('leg-swings-front-back', 'hip_mobility', 0),
  ('leg-swings-lateral', 'hip_mobility', 0),
  ('9090-hip-switch', 'hip_mobility', 0),
  ('shin-box-switch', 'hip_mobility', 0),
  ('shin-box-get-up', 'full_body_flow', 0),
  ('hip-cars', 'hip_mobility', 0),
  ('adductor-rockback', 'hip_mobility', 0),
  ('frog-rockback', 'hip_mobility', 0),
  ('cossack-shift', 'hip_mobility', 0),
  ('deep-squat-pry', 'squat_to_stand', 0),
  ('squat-to-stand-with-reach', 'squat_to_stand', 0),
  ('lateral-lunge-shift', 'lunge_pattern_prep', 0),
  ('glute-bridge', 'glute_activation', 0),
  ('glute-bridge-march', 'glute_activation', 0),
  ('dead-bug-heel-tap', 'core_activation', 0),
  ('bird-dog', 'core_activation', 0),
  ('mini-band-lateral-walk', 'glute_activation', 0),
  ('a-march', 'marching_mechanics', 0),
  ('worlds-greatest-stretch', 'integrated_mobility', 0)
) AS m(slug, slot, impact)
JOIN coaching.exercise e ON e.slug = m.slug
JOIN coaching.session_phase sp ON sp.key = 'prepare_access'
JOIN coaching.phase_order_slot pos ON pos.key = m.slot
ON CONFLICT (exercise_id, phase_id) DO UPDATE SET
  role = EXCLUDED.role, order_slot = EXCLUDED.order_slot, fit_weight = EXCLUDED.fit_weight,
  impact_level = EXCLUDED.impact_level, intensity_ceiling = EXCLUDED.intensity_ceiling;

-- 4) Dosage profiles
INSERT INTO coaching.exercise_dosage_profile (
  exercise_id, profile_name, is_default, volume_unit, default_sets, default_reps,
  default_work_seconds, default_rest_seconds, est_seconds_per_set
)
SELECT e.id, 'Default', TRUE, m.unit, m.sets, m.reps, m.work, m.rest, m.est
FROM (VALUES
  ('9090-breathing-with-reach', 'breaths', 2, NULL, 45, 15, 50),
  ('crocodile-breathing', 'breaths', 2, NULL, 60, 15, 65),
  ('full-body-joint-cars-flow', 'reps', 1, 1, NULL, 0, 180),
  ('neck-cars', 'reps', 2, 3, NULL, 10, 30),
  ('cat-cow', 'reps', 2, 8, NULL, 15, 35),
  ('quadruped-spinal-circles', 'reps', 2, 4, NULL, 15, 40),
  ('quadruped-thread-the-needle', 'reps', 2, 6, NULL, 15, 35),
  ('side-lying-open-book', 'reps', 2, 6, NULL, 15, 35),
  ('inchworm-walkout', 'reps', 2, 4, NULL, 20, 40),
  ('wrist-rockers-palms-down', 'reps', 2, 8, NULL, 10, 25),
  ('wrist-rockers-palms-up', 'reps', 2, 8, NULL, 10, 25),
  ('finger-pulses', 'reps', 2, 10, NULL, 10, 20),
  ('scapular-push-up', 'reps', 2, 10, NULL, 20, 30),
  ('quadruped-shoulder-circles', 'reps', 2, 5, NULL, 10, 30),
  ('wall-slides-with-lift-off', 'reps', 2, 8, NULL, 15, 35),
  ('band-external-rotation', 'reps', 2, 12, NULL, 20, 30),
  ('arm-circles', 'reps', 2, 10, NULL, 10, 25),
  ('bear-crawl-rock-back', 'reps', 2, 6, NULL, 20, 35),
  ('down-dog-to-plank-wave', 'reps', 2, 5, NULL, 20, 40),
  ('knee-to-wall-ankle-rockers', 'reps', 2, 10, NULL, 15, 30),
  ('half-kneeling-ankle-dorsiflexion-pulse', 'reps', 2, 12, NULL, 15, 30),
  ('ankle-cars', 'reps', 2, 5, NULL, 10, 25),
  ('tibialis-raises', 'reps', 2, 15, NULL, 20, 30),
  ('calf-raise-to-heel-drop', 'reps', 2, 10, NULL, 20, 35),
  ('toe-yoga', 'reps', 2, 8, NULL, 15, 25),
  ('short-foot-drill', 'reps', 2, 10, NULL, 15, 25),
  ('foot-tripod-weight-shifts', 'reps', 2, 6, NULL, 15, 30),
  ('low-pogos', 'reps', 2, 10, NULL, 30, 25),
  ('jump-rope-easy-bounce', 'seconds', 2, NULL, 30, 30, 35),
  ('walking-knee-hug', 'reps', 2, 10, NULL, 15, 40),
  ('walking-quad-pull', 'reps', 2, 10, NULL, 15, 40),
  ('leg-swings-front-back', 'reps', 2, 10, NULL, 15, 30),
  ('leg-swings-lateral', 'reps', 2, 10, NULL, 15, 30),
  ('9090-hip-switch', 'reps', 2, 8, NULL, 20, 45),
  ('shin-box-switch', 'reps', 2, 6, NULL, 20, 40),
  ('shin-box-get-up', 'reps', 2, 4, NULL, 30, 45),
  ('hip-cars', 'reps', 2, 4, NULL, 15, 35),
  ('adductor-rockback', 'reps', 2, 8, NULL, 15, 35),
  ('frog-rockback', 'reps', 2, 8, NULL, 20, 40),
  ('cossack-shift', 'reps', 2, 6, NULL, 20, 40),
  ('deep-squat-pry', 'seconds', 2, NULL, 30, 20, 35),
  ('squat-to-stand-with-reach', 'reps', 2, 6, NULL, 20, 40),
  ('lateral-lunge-shift', 'reps', 2, 6, NULL, 20, 40),
  ('glute-bridge', 'reps', 2, 12, NULL, 20, 35),
  ('glute-bridge-march', 'reps', 2, 8, NULL, 25, 40),
  ('dead-bug-heel-tap', 'reps', 2, 8, NULL, 20, 35),
  ('bird-dog', 'reps', 2, 6, NULL, 20, 35),
  ('mini-band-lateral-walk', 'reps', 2, 10, NULL, 25, 35),
  ('a-march', 'reps', 2, 10, NULL, 30, 40),
  ('worlds-greatest-stretch', 'reps', 2, 6, NULL, 20, 35)
) AS m(slug, unit, sets, reps, work, rest, est)
JOIN coaching.exercise e ON e.slug = m.slug
WHERE NOT EXISTS (SELECT 1 FROM coaching.exercise_dosage_profile d WHERE d.exercise_id = e.id AND d.profile_name = 'Default');

-- 5) Safety profiles
INSERT INTO coaching.exercise_safety_profile (
  exercise_id, risk_level, impact_level, requires_coach_supervision, readiness_checks
)
SELECT e.id, 1, COALESCE(m.impact, 0), 'none', ARRAY['No acute pain', 'Can maintain posture']
FROM (VALUES
  ('9090-breathing-with-reach', 0),
  ('crocodile-breathing', 0),
  ('full-body-joint-cars-flow', 0),
  ('neck-cars', 0),
  ('cat-cow', 0),
  ('quadruped-spinal-circles', 0),
  ('quadruped-thread-the-needle', 0),
  ('side-lying-open-book', 0),
  ('inchworm-walkout', 0),
  ('wrist-rockers-palms-down', 0),
  ('wrist-rockers-palms-up', 0),
  ('finger-pulses', 0),
  ('scapular-push-up', 0),
  ('quadruped-shoulder-circles', 0),
  ('wall-slides-with-lift-off', 0),
  ('band-external-rotation', 0),
  ('arm-circles', 0),
  ('bear-crawl-rock-back', 0),
  ('down-dog-to-plank-wave', 0),
  ('knee-to-wall-ankle-rockers', 0),
  ('half-kneeling-ankle-dorsiflexion-pulse', 0),
  ('ankle-cars', 0),
  ('tibialis-raises', 0),
  ('calf-raise-to-heel-drop', 0),
  ('toe-yoga', 0),
  ('short-foot-drill', 0),
  ('foot-tripod-weight-shifts', 0),
  ('low-pogos', 2),
  ('jump-rope-easy-bounce', 2),
  ('walking-knee-hug', 0),
  ('walking-quad-pull', 0),
  ('leg-swings-front-back', 0),
  ('leg-swings-lateral', 0),
  ('9090-hip-switch', 0),
  ('shin-box-switch', 0),
  ('shin-box-get-up', 0),
  ('hip-cars', 0),
  ('adductor-rockback', 0),
  ('frog-rockback', 0),
  ('cossack-shift', 0),
  ('deep-squat-pry', 0),
  ('squat-to-stand-with-reach', 0),
  ('lateral-lunge-shift', 0),
  ('glute-bridge', 0),
  ('glute-bridge-march', 0),
  ('dead-bug-heel-tap', 0),
  ('bird-dog', 0),
  ('mini-band-lateral-walk', 0),
  ('a-march', 0),
  ('worlds-greatest-stretch', 0)
) AS m(slug, impact)
JOIN coaching.exercise e ON e.slug = m.slug
WHERE NOT EXISTS (SELECT 1 FROM coaching.exercise_safety_profile s WHERE s.exercise_id = e.id);

UPDATE coaching.exercise_safety_profile s SET
  readiness_checks = ARRAY['Athlete can land quietly', 'No ankle/knee pain'],
  impact_level = 2
FROM coaching.exercise e
WHERE s.exercise_id = e.id AND e.slug IN ('low-pogos', 'jump-rope-easy-bounce');

-- 6) Regimen rules (daily OK for warm-ups)
INSERT INTO coaching.exercise_regimen_rule (
  exercise_id, can_be_daily, weekly_max_frequency, minimum_hours_between_hard_exposures
)
SELECT e.id, TRUE, 7, 0
FROM coaching.exercise e
WHERE e.slug IN ('9090-breathing-with-reach', 'crocodile-breathing', 'full-body-joint-cars-flow', 'neck-cars', 'cat-cow', 'quadruped-spinal-circles', 'quadruped-thread-the-needle', 'side-lying-open-book', 'inchworm-walkout', 'wrist-rockers-palms-down', 'wrist-rockers-palms-up', 'finger-pulses', 'scapular-push-up', 'quadruped-shoulder-circles', 'wall-slides-with-lift-off', 'band-external-rotation', 'arm-circles', 'bear-crawl-rock-back', 'down-dog-to-plank-wave', 'knee-to-wall-ankle-rockers', 'half-kneeling-ankle-dorsiflexion-pulse', 'ankle-cars', 'tibialis-raises', 'calf-raise-to-heel-drop', 'toe-yoga', 'short-foot-drill', 'foot-tripod-weight-shifts', 'low-pogos', 'jump-rope-easy-bounce', 'walking-knee-hug', 'walking-quad-pull', 'leg-swings-front-back', 'leg-swings-lateral', '9090-hip-switch', 'shin-box-switch', 'shin-box-get-up', 'hip-cars', 'adductor-rockback', 'frog-rockback', 'cossack-shift', 'deep-squat-pry', 'squat-to-stand-with-reach', 'lateral-lunge-shift', 'glute-bridge', 'glute-bridge-march', 'dead-bug-heel-tap', 'bird-dog', 'mini-band-lateral-walk', 'a-march', 'worlds-greatest-stretch')
  AND NOT EXISTS (SELECT 1 FROM coaching.exercise_regimen_rule r WHERE r.exercise_id = e.id);

UPDATE coaching.exercise_regimen_rule r SET can_be_daily = TRUE, weekly_max_frequency = 7, minimum_hours_between_hard_exposures = 0
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug IN ('9090-breathing-with-reach', 'crocodile-breathing', 'full-body-joint-cars-flow', 'neck-cars', 'cat-cow', 'quadruped-spinal-circles', 'quadruped-thread-the-needle', 'side-lying-open-book', 'inchworm-walkout', 'wrist-rockers-palms-down', 'wrist-rockers-palms-up', 'finger-pulses', 'scapular-push-up', 'quadruped-shoulder-circles', 'wall-slides-with-lift-off', 'band-external-rotation', 'arm-circles', 'bear-crawl-rock-back', 'down-dog-to-plank-wave', 'knee-to-wall-ankle-rockers', 'half-kneeling-ankle-dorsiflexion-pulse', 'ankle-cars', 'tibialis-raises', 'calf-raise-to-heel-drop', 'toe-yoga', 'short-foot-drill', 'foot-tripod-weight-shifts', 'low-pogos', 'jump-rope-easy-bounce', 'walking-knee-hug', 'walking-quad-pull', 'leg-swings-front-back', 'leg-swings-lateral', '9090-hip-switch', 'shin-box-switch', 'shin-box-get-up', 'hip-cars', 'adductor-rockback', 'frog-rockback', 'cossack-shift', 'deep-squat-pry', 'squat-to-stand-with-reach', 'lateral-lunge-shift', 'glute-bridge', 'glute-bridge-march', 'dead-bug-heel-tap', 'bird-dog', 'mini-band-lateral-walk', 'a-march', 'worlds-greatest-stretch');

-- 7) Scaling cohort rows (6 required cohorts)
INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, complexity_guidance, coach_notes)
SELECT e.id, 'youth_beginner', 'youth beginner', 'baseline', 'Reduce reps or duration for younger or less trained athletes.', 'Use simpler variation if form breaks down.', 'Warm-up dose only — prioritize quality.'
FROM coaching.exercise e
WHERE e.slug IN ('9090-breathing-with-reach', 'crocodile-breathing', 'full-body-joint-cars-flow', 'neck-cars', 'cat-cow', 'quadruped-spinal-circles', 'quadruped-thread-the-needle', 'side-lying-open-book', 'inchworm-walkout', 'wrist-rockers-palms-down', 'wrist-rockers-palms-up', 'finger-pulses', 'scapular-push-up', 'quadruped-shoulder-circles', 'wall-slides-with-lift-off', 'band-external-rotation', 'arm-circles', 'bear-crawl-rock-back', 'down-dog-to-plank-wave', 'knee-to-wall-ankle-rockers', 'half-kneeling-ankle-dorsiflexion-pulse', 'ankle-cars', 'tibialis-raises', 'calf-raise-to-heel-drop', 'toe-yoga', 'short-foot-drill', 'foot-tripod-weight-shifts', 'low-pogos', 'jump-rope-easy-bounce', 'walking-knee-hug', 'walking-quad-pull', 'leg-swings-front-back', 'leg-swings-lateral', '9090-hip-switch', 'shin-box-switch', 'shin-box-get-up', 'hip-cars', 'adductor-rockback', 'frog-rockback', 'cossack-shift', 'deep-squat-pry', 'squat-to-stand-with-reach', 'lateral-lunge-shift', 'glute-bridge', 'glute-bridge-march', 'dead-bug-heel-tap', 'bird-dog', 'mini-band-lateral-walk', 'a-march', 'worlds-greatest-stretch')
  AND NOT EXISTS (SELECT 1 FROM coaching.exercise_scaling_profile sp WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_beginner');

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, complexity_guidance, coach_notes)
SELECT e.id, 'youth_intermediate', 'youth intermediate', 'baseline', 'Reduce reps or duration for younger or less trained athletes.', 'Use simpler variation if form breaks down.', 'Warm-up dose only — prioritize quality.'
FROM coaching.exercise e
WHERE e.slug IN ('9090-breathing-with-reach', 'crocodile-breathing', 'full-body-joint-cars-flow', 'neck-cars', 'cat-cow', 'quadruped-spinal-circles', 'quadruped-thread-the-needle', 'side-lying-open-book', 'inchworm-walkout', 'wrist-rockers-palms-down', 'wrist-rockers-palms-up', 'finger-pulses', 'scapular-push-up', 'quadruped-shoulder-circles', 'wall-slides-with-lift-off', 'band-external-rotation', 'arm-circles', 'bear-crawl-rock-back', 'down-dog-to-plank-wave', 'knee-to-wall-ankle-rockers', 'half-kneeling-ankle-dorsiflexion-pulse', 'ankle-cars', 'tibialis-raises', 'calf-raise-to-heel-drop', 'toe-yoga', 'short-foot-drill', 'foot-tripod-weight-shifts', 'low-pogos', 'jump-rope-easy-bounce', 'walking-knee-hug', 'walking-quad-pull', 'leg-swings-front-back', 'leg-swings-lateral', '9090-hip-switch', 'shin-box-switch', 'shin-box-get-up', 'hip-cars', 'adductor-rockback', 'frog-rockback', 'cossack-shift', 'deep-squat-pry', 'squat-to-stand-with-reach', 'lateral-lunge-shift', 'glute-bridge', 'glute-bridge-march', 'dead-bug-heel-tap', 'bird-dog', 'mini-band-lateral-walk', 'a-march', 'worlds-greatest-stretch')
  AND NOT EXISTS (SELECT 1 FROM coaching.exercise_scaling_profile sp WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_intermediate');

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, complexity_guidance, coach_notes)
SELECT e.id, 'teen', 'teen', 'baseline', 'Reduce reps or duration for younger or less trained athletes.', 'Use simpler variation if form breaks down.', 'Warm-up dose only — prioritize quality.'
FROM coaching.exercise e
WHERE e.slug IN ('9090-breathing-with-reach', 'crocodile-breathing', 'full-body-joint-cars-flow', 'neck-cars', 'cat-cow', 'quadruped-spinal-circles', 'quadruped-thread-the-needle', 'side-lying-open-book', 'inchworm-walkout', 'wrist-rockers-palms-down', 'wrist-rockers-palms-up', 'finger-pulses', 'scapular-push-up', 'quadruped-shoulder-circles', 'wall-slides-with-lift-off', 'band-external-rotation', 'arm-circles', 'bear-crawl-rock-back', 'down-dog-to-plank-wave', 'knee-to-wall-ankle-rockers', 'half-kneeling-ankle-dorsiflexion-pulse', 'ankle-cars', 'tibialis-raises', 'calf-raise-to-heel-drop', 'toe-yoga', 'short-foot-drill', 'foot-tripod-weight-shifts', 'low-pogos', 'jump-rope-easy-bounce', 'walking-knee-hug', 'walking-quad-pull', 'leg-swings-front-back', 'leg-swings-lateral', '9090-hip-switch', 'shin-box-switch', 'shin-box-get-up', 'hip-cars', 'adductor-rockback', 'frog-rockback', 'cossack-shift', 'deep-squat-pry', 'squat-to-stand-with-reach', 'lateral-lunge-shift', 'glute-bridge', 'glute-bridge-march', 'dead-bug-heel-tap', 'bird-dog', 'mini-band-lateral-walk', 'a-march', 'worlds-greatest-stretch')
  AND NOT EXISTS (SELECT 1 FROM coaching.exercise_scaling_profile sp WHERE sp.exercise_id = e.id AND sp.cohort_key = 'teen');

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, complexity_guidance, coach_notes)
SELECT e.id, 'adult_beginner', 'adult beginner', 'baseline', 'Reduce reps or duration for younger or less trained athletes.', 'Use simpler variation if form breaks down.', 'Warm-up dose only — prioritize quality.'
FROM coaching.exercise e
WHERE e.slug IN ('9090-breathing-with-reach', 'crocodile-breathing', 'full-body-joint-cars-flow', 'neck-cars', 'cat-cow', 'quadruped-spinal-circles', 'quadruped-thread-the-needle', 'side-lying-open-book', 'inchworm-walkout', 'wrist-rockers-palms-down', 'wrist-rockers-palms-up', 'finger-pulses', 'scapular-push-up', 'quadruped-shoulder-circles', 'wall-slides-with-lift-off', 'band-external-rotation', 'arm-circles', 'bear-crawl-rock-back', 'down-dog-to-plank-wave', 'knee-to-wall-ankle-rockers', 'half-kneeling-ankle-dorsiflexion-pulse', 'ankle-cars', 'tibialis-raises', 'calf-raise-to-heel-drop', 'toe-yoga', 'short-foot-drill', 'foot-tripod-weight-shifts', 'low-pogos', 'jump-rope-easy-bounce', 'walking-knee-hug', 'walking-quad-pull', 'leg-swings-front-back', 'leg-swings-lateral', '9090-hip-switch', 'shin-box-switch', 'shin-box-get-up', 'hip-cars', 'adductor-rockback', 'frog-rockback', 'cossack-shift', 'deep-squat-pry', 'squat-to-stand-with-reach', 'lateral-lunge-shift', 'glute-bridge', 'glute-bridge-march', 'dead-bug-heel-tap', 'bird-dog', 'mini-band-lateral-walk', 'a-march', 'worlds-greatest-stretch')
  AND NOT EXISTS (SELECT 1 FROM coaching.exercise_scaling_profile sp WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_beginner');

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, complexity_guidance, coach_notes)
SELECT e.id, 'adult_advanced', 'adult advanced', 'baseline', 'Reduce reps or duration for younger or less trained athletes.', 'Use simpler variation if form breaks down.', 'Warm-up dose only — prioritize quality.'
FROM coaching.exercise e
WHERE e.slug IN ('9090-breathing-with-reach', 'crocodile-breathing', 'full-body-joint-cars-flow', 'neck-cars', 'cat-cow', 'quadruped-spinal-circles', 'quadruped-thread-the-needle', 'side-lying-open-book', 'inchworm-walkout', 'wrist-rockers-palms-down', 'wrist-rockers-palms-up', 'finger-pulses', 'scapular-push-up', 'quadruped-shoulder-circles', 'wall-slides-with-lift-off', 'band-external-rotation', 'arm-circles', 'bear-crawl-rock-back', 'down-dog-to-plank-wave', 'knee-to-wall-ankle-rockers', 'half-kneeling-ankle-dorsiflexion-pulse', 'ankle-cars', 'tibialis-raises', 'calf-raise-to-heel-drop', 'toe-yoga', 'short-foot-drill', 'foot-tripod-weight-shifts', 'low-pogos', 'jump-rope-easy-bounce', 'walking-knee-hug', 'walking-quad-pull', 'leg-swings-front-back', 'leg-swings-lateral', '9090-hip-switch', 'shin-box-switch', 'shin-box-get-up', 'hip-cars', 'adductor-rockback', 'frog-rockback', 'cossack-shift', 'deep-squat-pry', 'squat-to-stand-with-reach', 'lateral-lunge-shift', 'glute-bridge', 'glute-bridge-march', 'dead-bug-heel-tap', 'bird-dog', 'mini-band-lateral-walk', 'a-march', 'worlds-greatest-stretch')
  AND NOT EXISTS (SELECT 1 FROM coaching.exercise_scaling_profile sp WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_advanced');

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, complexity_guidance, coach_notes)
SELECT e.id, 'older_adult', 'older adult', 'baseline', 'Reduce reps or duration for younger or less trained athletes.', 'Use simpler variation if form breaks down.', 'Warm-up dose only — prioritize quality.'
FROM coaching.exercise e
WHERE e.slug IN ('9090-breathing-with-reach', 'crocodile-breathing', 'full-body-joint-cars-flow', 'neck-cars', 'cat-cow', 'quadruped-spinal-circles', 'quadruped-thread-the-needle', 'side-lying-open-book', 'inchworm-walkout', 'wrist-rockers-palms-down', 'wrist-rockers-palms-up', 'finger-pulses', 'scapular-push-up', 'quadruped-shoulder-circles', 'wall-slides-with-lift-off', 'band-external-rotation', 'arm-circles', 'bear-crawl-rock-back', 'down-dog-to-plank-wave', 'knee-to-wall-ankle-rockers', 'half-kneeling-ankle-dorsiflexion-pulse', 'ankle-cars', 'tibialis-raises', 'calf-raise-to-heel-drop', 'toe-yoga', 'short-foot-drill', 'foot-tripod-weight-shifts', 'low-pogos', 'jump-rope-easy-bounce', 'walking-knee-hug', 'walking-quad-pull', 'leg-swings-front-back', 'leg-swings-lateral', '9090-hip-switch', 'shin-box-switch', 'shin-box-get-up', 'hip-cars', 'adductor-rockback', 'frog-rockback', 'cossack-shift', 'deep-squat-pry', 'squat-to-stand-with-reach', 'lateral-lunge-shift', 'glute-bridge', 'glute-bridge-march', 'dead-bug-heel-tap', 'bird-dog', 'mini-band-lateral-walk', 'a-march', 'worlds-greatest-stretch')
  AND NOT EXISTS (SELECT 1 FROM coaching.exercise_scaling_profile sp WHERE sp.exercise_id = e.id AND sp.cohort_key = 'older_adult');

-- 8) Why-layer education
INSERT INTO coaching.education_content (
  entity_type, entity_key, entity_id, title, short_summary, what_it_is, why_it_matters,
  why_it_goes_here, programming_guidance, common_misuse, scaling_guidance
)
SELECT
  'exercise', e.slug, e.id, e.name,
  e.card_summary,
  COALESCE(e.description, e.name),
  'Develops movement access and readiness for athletic training.',
  CASE e.phase_subrole
    WHEN 'raise' THEN 'Belongs in Raise — elevates temperature, blood flow, and general readiness without fatigue.'
    WHEN 'mobilize' THEN 'Belongs in Mobilize — opens joint ranges needed for later skill, speed, and strength work.'
    WHEN 'activate' THEN 'Belongs in Activate — wakes stabilizers and primes positions before integrated patterns.'
    WHEN 'integrate' THEN 'Belongs in Integrate — connects joints into whole-body movement chains.'
    WHEN 'potentiate_bridge' THEN 'Belongs in Potentiate Bridge — gently ramps neural intent toward Skill/Output without fatigue.'
    ELSE 'Place in Prepare / Access before higher-intent work.'
  END,
  'Use early in session; scale volume by age and attention. Stop before fatigue.',
  'Do not use as conditioning or max-effort work in the warm-up.',
  'Reduce reps, duration, or range for youth and beginners.'
FROM coaching.exercise e
WHERE e.slug IN ('9090-breathing-with-reach', 'crocodile-breathing', 'full-body-joint-cars-flow', 'neck-cars', 'cat-cow', 'quadruped-spinal-circles', 'quadruped-thread-the-needle', 'side-lying-open-book', 'inchworm-walkout', 'wrist-rockers-palms-down', 'wrist-rockers-palms-up', 'finger-pulses', 'scapular-push-up', 'quadruped-shoulder-circles', 'wall-slides-with-lift-off', 'band-external-rotation', 'arm-circles', 'bear-crawl-rock-back', 'down-dog-to-plank-wave', 'knee-to-wall-ankle-rockers', 'half-kneeling-ankle-dorsiflexion-pulse', 'ankle-cars', 'tibialis-raises', 'calf-raise-to-heel-drop', 'toe-yoga', 'short-foot-drill', 'foot-tripod-weight-shifts', 'low-pogos', 'jump-rope-easy-bounce', 'walking-knee-hug', 'walking-quad-pull', 'leg-swings-front-back', 'leg-swings-lateral', '9090-hip-switch', 'shin-box-switch', 'shin-box-get-up', 'hip-cars', 'adductor-rockback', 'frog-rockback', 'cossack-shift', 'deep-squat-pry', 'squat-to-stand-with-reach', 'lateral-lunge-shift', 'glute-bridge', 'glute-bridge-march', 'dead-bug-heel-tap', 'bird-dog', 'mini-band-lateral-walk', 'a-march', 'worlds-greatest-stretch')
ON CONFLICT (entity_type, entity_key, entity_id) DO UPDATE SET
  title = EXCLUDED.title,
  short_summary = EXCLUDED.short_summary,
  what_it_is = EXCLUDED.what_it_is,
  why_it_goes_here = EXCLUDED.why_it_goes_here,
  programming_guidance = EXCLUDED.programming_guidance,
  common_misuse = EXCLUDED.common_misuse,
  scaling_guidance = EXCLUDED.scaling_guidance,
  updated_at = now();

-- 9) Representative cues
INSERT INTO coaching.exercise_cue (exercise_id, cue_type, body, sort_order)
SELECT e.id, v.cue_type, v.body, v.sort_order
FROM (VALUES
  ('deep-squat-pry', 'cue', 'Keep heels down and chest up in the bottom.', 0),
  ('deep-squat-pry', 'fault', 'Heels lifting off floor.', 1),
  ('glute-bridge', 'cue', 'Drive through heels; ribs down at top.', 0),
  ('glute-bridge', 'fault', 'Over-arching lower back.', 1),
  ('bear-crawl-rock-back', 'cue', 'Press palms; rock hips back with control.', 0),
  ('a-march', 'cue', 'Tall posture; quick sharp knee drive.', 0),
  ('a-march', 'fault', 'Leaning backward.', 1)
) AS v(slug, cue_type, body, sort_order)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_cue c
  WHERE c.exercise_id = e.id AND c.cue_type = v.cue_type AND c.body = v.body
);
