-- Foundation Prepare/Access cards 1–10 (rich card v2 content).
-- IDEMPOTENT. Generated by scripts/generate-098-foundation-cards.mjs

-- New fine slot for hip rotation (card 8)
INSERT INTO coaching.phase_order_slot (key, name, description, phase_id, order_index, freshness_sensitivity, subrole_key)
SELECT 'hip_rotation', 'Hip Rotation', '90/90 switches and seated hip IR/ER access.', sp.id, 119, 1, 'mobilize'
FROM coaching.session_phase sp
WHERE sp.key = 'prepare_access'
ON CONFLICT (key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  phase_id = EXCLUDED.phase_id,
  order_index = EXCLUDED.order_index,
  freshness_sensitivity = EXCLUDED.freshness_sensitivity,
  subrole_key = EXCLUDED.subrole_key;

-- 90/90 Breathing with Reach (9090-breathing-with-reach)
UPDATE coaching.exercise SET
  name = '90/90 Breathing with Reach',
  description = 'Lie on the back with feet on a wall, bench, or box so hips and knees are bent to roughly 90 degrees. Keep the neck neutral. Reach arms toward the ceiling or slightly forward to bring the ribs down. Inhale through the nose, expanding the abdomen and lower ribs. Exhale slowly and fully, letting the ribs soften down without crunching.',
  card_summary = 'Supine breathing reset that stacks ribs over pelvis, restores diaphragmatic breathing, and prepares the trunk for movement.',
  coach_language = 'Primary subrole: Mobilize. Secondary intent: Activate trunk stabilizers. Use as a low-threat reset before higher-intent work.',
  athlete_language = 'Breathe low and wide; long exhale while reaching long.',
  movement_family = 'Breathing reset',
  primary_phase_key = 'prepare_access',
  phase_subrole = 'mobilize',
  primary_order_slot = 'breathing_reset',
  default_sets = 1,
  default_reps = 5,
  default_work_seconds = 45,
  default_rest_seconds = 0,
  est_seconds_per_set = 60,
  movement_requirements = '{"primary_joint_actions":["spine_rotation","shoulder_flexion"],"primary_tissues":["diaphragm","intercostals"],"breathing_demand":"diaphragmatic","balance_demand":"stable","impact_level":0}'::jsonb,
  coaching_execution = '{"movement_description":"Lie on the back with feet on a wall, bench, or box so hips and knees are bent to roughly 90 degrees. Keep the neck neutral. Reach arms toward the ceiling or slightly forward to bring the ribs down. Inhale through the nose, expanding the abdomen and lower ribs. Exhale slowly and fully, letting the ribs soften down without crunching.","setup":["Lie on back with hips and knees at roughly 90 degrees (wall, bench, or box support)","Reach arms toward ceiling or slightly forward","Neck neutral, jaw relaxed"],"execution_steps":["Inhale through nose into abdomen and lower ribs","Exhale slowly and fully while reaching longer","Repeat for prescribed breaths"],"coach_cues":["Ribs down without forcing spinal flexion","Pelvis neutral or slightly posteriorly tilted","Quiet neck and jaw","Long exhale","Breath expands low, wide, and back, not just into the chest"],"common_faults":["Low back arching off the floor","Shoulders shrugging","Athlete crunching instead of exhaling","Breath held during the reach","Feet pressing so hard that hamstrings cramp"]}'::jsonb,
  pairing_logic = '{"pairs_well_before":[],"pairs_well_after":["Crocodile Breathing","Dead Bug","Cat-Cow","Glute Bridge","Hip 90/90 work","Sprint wall drills (if athlete overextends)"],"good_for_sessions":[],"avoid_before":[],"avoid_after":[],"do_not_use_when":["Athlete feels dizzy in supine breathing","Supine position is uncomfortable or contraindicated","The class needs immediate temperature raise and athletes are already moving well"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Functional Movement Systems 90/90 Breathing Position"],"internal_notes":["Best as reset, not a long relaxation block."]}'::jsonb,
  updated_at = now()
WHERE slug = '9090-breathing-with-reach';

UPDATE coaching.exercise_phase_profile p SET
  order_slot = 'breathing_reset',
  order_index = pos.order_index
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'prepare_access'
JOIN coaching.phase_order_slot pos ON pos.key = 'breathing_reset' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = '9090-breathing-with-reach';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'breaths',
  default_sets = 1,
  default_reps = 5,
  default_work_seconds = 45,
  default_rest_seconds = 0,
  est_seconds_per_set = 60,
  default_rpe_min = 1,
  default_rpe_max = 2
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = '9090-breathing-with-reach';

-- Crocodile Breathing (crocodile-breathing)
UPDATE coaching.exercise SET
  name = 'Crocodile Breathing',
  description = 'Lie face down with forehead on stacked hands. Keep shoulders, neck, jaw, and hips relaxed. Inhale through the nose and feel the abdomen press gently into the floor. Exhale slowly through the nose or mouth, allowing the belly to soften.',
  card_summary = 'Prone diaphragmatic breathing drill using floor feedback to teach posterior and abdominal expansion.',
  coach_language = 'Primary subrole: Mobilize. Secondary intent: Activate. Floor feedback teaches posterior expansion.',
  athlete_language = 'Push the floor with your belly on each inhale; stay relaxed in shoulders and neck.',
  movement_family = 'Breathing reset',
  primary_phase_key = 'prepare_access',
  phase_subrole = 'mobilize',
  primary_order_slot = 'breathing_reset',
  default_sets = 1,
  default_reps = 5,
  default_work_seconds = 45,
  default_rest_seconds = 0,
  est_seconds_per_set = 60,
  movement_requirements = '{"primary_joint_actions":["spine_extension"],"primary_tissues":["diaphragm"],"breathing_demand":"diaphragmatic","balance_demand":"stable","impact_level":0}'::jsonb,
  coaching_execution = '{"movement_description":"Lie face down with forehead on stacked hands. Keep shoulders, neck, jaw, and hips relaxed. Inhale through the nose and feel the abdomen press gently into the floor. Exhale slowly through the nose or mouth, allowing the belly to soften.","setup":["Lie prone, forehead on stacked hands","Shoulders and hips relaxed"],"execution_steps":["Inhale — belly presses into floor","Exhale slowly, belly softens","Repeat"],"coach_cues":["Breath moves the floor, not the shoulders","Keep neck relaxed","Slow down the exhale","No forced belly push","Feel 360-degree expansion: front, side, and back"],"common_faults":["Athlete only moving upper chest","Breath holding","Low-back gripping","Neck tension","Too long spent here before a high-energy class"]}'::jsonb,
  pairing_logic = '{"pairs_well_before":[],"pairs_well_after":["Cat-Cow","Quadruped Spinal Circles","Cobra to Child''s Pose Flow","Dead Bug","90/90 Breathing with Reach"],"good_for_sessions":[],"avoid_before":[],"avoid_after":[],"do_not_use_when":["Pregnancy makes prone position inappropriate","Athlete has discomfort lying prone","Time is limited and the class needs more active temperature raise"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Functional Movement Systems Crocodile Breathing"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'crocodile-breathing';

UPDATE coaching.exercise_phase_profile p SET
  order_slot = 'breathing_reset',
  order_index = pos.order_index
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'prepare_access'
JOIN coaching.phase_order_slot pos ON pos.key = 'breathing_reset' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'crocodile-breathing';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'breaths',
  default_sets = 1,
  default_reps = 5,
  default_work_seconds = 45,
  default_rest_seconds = 0,
  est_seconds_per_set = 60,
  default_rpe_min = 1,
  default_rpe_max = 1
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'crocodile-breathing';

-- Full-Body Joint CARs Flow (full-body-joint-cars-flow)
UPDATE coaching.exercise SET
  name = 'Full-Body Joint CARs Flow',
  description = 'Move joint by joint through slow controlled circles: neck, shoulders, elbows, wrists, spine, hips, knees, ankles. The athlete explores available range without pain, compensation, or rushing.',
  card_summary = 'Controlled articular rotation flow used as a joint scan, mobility primer, and readiness check.',
  coach_language = 'Use as a readiness scan — not a workout. Slow, owned range only.',
  athlete_language = 'Move each joint slowly like you are drawing circles in honey.',
  movement_family = 'Joint scan',
  primary_phase_key = 'prepare_access',
  phase_subrole = 'mobilize',
  primary_order_slot = 'joint_scan',
  default_sets = 1,
  default_reps = 3,
  default_work_seconds = 120,
  default_rest_seconds = 0,
  est_seconds_per_set = 120,
  movement_requirements = '{"primary_joint_actions":["multi_joint"],"primary_tissues":["synovial"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb,
  coaching_execution = '{"movement_description":"Move joint by joint through slow controlled circles: neck, shoulders, elbows, wrists, spine, hips, knees, ankles. The athlete explores available range without pain, compensation, or rushing.","setup":["Stand tall, soft knees","Scan head to toe or follow coach sequence"],"execution_steps":["Neck CARs","Shoulder CARs","Elbow and wrist CARs","Spine segments","Hip, knee, ankle CARs — slow and controlled"],"coach_cues":["Move slowly","Own the range","Keep the rest of the body quiet","Avoid pain or pinching","Use the drill as a readiness scan"],"common_faults":["Fast uncontrolled circles","Forcing end range","Compensating through the trunk","Treating CARs as static stretching","Too much time spent on every joint when the session needs specificity"]}'::jsonb,
  pairing_logic = '{"pairs_well_before":[],"pairs_well_after":["90/90 Breathing with Reach","Cat-Cow","Hip CARs","Shoulder CARs","Ankle CARs","A-March"],"good_for_sessions":[],"avoid_before":[],"avoid_after":[],"do_not_use_when":["Athlete uses painful end ranges","Coach needs targeted prep and a full-body scan would waste time","Athlete is hypermobile and needs stability-first activation instead"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["GMB Joint Mobility routine and preparation framework"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'full-body-joint-cars-flow';

UPDATE coaching.exercise_phase_profile p SET
  order_slot = 'joint_scan',
  order_index = pos.order_index
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'prepare_access'
JOIN coaching.phase_order_slot pos ON pos.key = 'joint_scan' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'full-body-joint-cars-flow';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 1,
  default_reps = 3,
  default_work_seconds = 120,
  default_rest_seconds = 0,
  est_seconds_per_set = 120,
  default_rpe_min = 1,
  default_rpe_max = 3
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'full-body-joint-cars-flow';

-- Cat-Cow (cat-cow)
UPDATE coaching.exercise SET
  name = 'Cat-Cow',
  description = 'Start on hands and knees, hands under shoulders and knees under hips. Round the spine by pushing the floor away and tucking the pelvis. Then reverse by gently arching the spine and allowing the chest to move toward the floor. Move slowly.',
  card_summary = 'Quadruped spinal flexion-extension drill for pelvic awareness, spinal segmentation, and low-intensity trunk access.',
  coach_language = 'Initiate from pelvis; link breath to spine motion.',
  athlete_language = 'Round your back like an angry cat, then lift your chest like a happy cow.',
  movement_family = 'Spinal mobility',
  primary_phase_key = 'prepare_access',
  phase_subrole = 'mobilize',
  primary_order_slot = 'spinal_mobility',
  default_sets = 1,
  default_reps = 8,
  default_work_seconds = 45,
  default_rest_seconds = 0,
  est_seconds_per_set = 45,
  movement_requirements = '{"primary_joint_actions":["spine_flexion","spine_extension"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb,
  coaching_execution = '{"movement_description":"Start on hands and knees, hands under shoulders and knees under hips. Round the spine by pushing the floor away and tucking the pelvis. Then reverse by gently arching the spine and allowing the chest to move toward the floor. Move slowly.","setup":["Quadruped, wrists under shoulders, knees under hips","Neutral starting spine"],"execution_steps":["Exhale: round spine (cat), push floor away","Inhale: arch gently (cow), chest toward floor","Repeat slowly"],"coach_cues":["Initiate from pelvis, then spine","Push through the hands during the \"cat\"","Keep elbows straight","Move one segment at a time if possible","Breathe through the motion"],"common_faults":["Bending elbows instead of moving spine","Dumping into low-back extension","Rushing","Neck cranking","Painful end range"]}'::jsonb,
  pairing_logic = '{"pairs_well_before":[],"pairs_well_after":["Crocodile Breathing","Quadruped Spinal Circles","Thread the Needle","Bear Crawl Rock-Back","Dead Bug"],"good_for_sessions":[],"avoid_before":[],"avoid_after":[],"do_not_use_when":["Wrist pain prevents quadruped loading","Acute spinal pain is aggravated by flexion or extension","Athlete needs stability more than mobility that day"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["The Prehab Guys Cat Cow"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'cat-cow';

UPDATE coaching.exercise_phase_profile p SET
  order_slot = 'spinal_mobility',
  order_index = pos.order_index
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'prepare_access'
JOIN coaching.phase_order_slot pos ON pos.key = 'spinal_mobility' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'cat-cow';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 1,
  default_reps = 8,
  default_work_seconds = 45,
  default_rest_seconds = 0,
  est_seconds_per_set = 45,
  default_rpe_min = 1,
  default_rpe_max = 2
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'cat-cow';

-- Quadruped Spinal Circles (quadruped-spinal-circles)
UPDATE coaching.exercise SET
  name = 'Quadruped Spinal Circles',
  description = 'Start on hands and knees. Slowly draw a circle with the spine and pelvis: round, shift to one side, arch, shift to the other side, then repeat. Reverse direction.',
  card_summary = 'Circular spinal mobility drill that explores flexion, extension, lateral flexion, and pelvic control.',
  coach_language = '3D spine motion — slow circles, not head wagging.',
  athlete_language = 'Draw a smooth circle with your back.',
  movement_family = 'Spinal mobility',
  primary_phase_key = 'prepare_access',
  phase_subrole = 'mobilize',
  primary_order_slot = 'spinal_mobility',
  default_sets = 1,
  default_reps = 5,
  default_work_seconds = 45,
  default_rest_seconds = 0,
  est_seconds_per_set = 45,
  movement_requirements = '{"primary_joint_actions":["spine_rotation","spine_lateral_flexion","spine_flexion","spine_extension"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb,
  coaching_execution = '{"movement_description":"Start on hands and knees. Slowly draw a circle with the spine and pelvis: round, shift to one side, arch, shift to the other side, then repeat. Reverse direction.","setup":["Quadruped neutral spine","Hands under shoulders"],"execution_steps":["Draw slow circle: round → side → arch → side","Reverse direction each set or rep block"],"coach_cues":["Slow, smooth circles","Keep shoulders and hips controlled","Find sticky spots without forcing","Breathe continuously","Reverse directions"],"common_faults":["Moving only the head","Dumping into the low back","Collapsing into shoulders","Rushing","Pain or pinching"]}'::jsonb,
  pairing_logic = '{"pairs_well_before":[],"pairs_well_after":["Cat-Cow","Thread the Needle","Down Dog to Plank Wave","Bear Crawl Rock-Back","World''s Greatest Stretch"],"good_for_sessions":[],"avoid_before":[],"avoid_after":[],"do_not_use_when":["Wrist or knee loading is painful","Athlete becomes dizzy with head movement","Acute back pain is aggravated by multi-direction movement"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["GMB Joint Mobility routine"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'quadruped-spinal-circles';

UPDATE coaching.exercise_phase_profile p SET
  order_slot = 'spinal_mobility',
  order_index = pos.order_index
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'prepare_access'
JOIN coaching.phase_order_slot pos ON pos.key = 'spinal_mobility' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'quadruped-spinal-circles';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 1,
  default_reps = 5,
  default_work_seconds = 45,
  default_rest_seconds = 0,
  est_seconds_per_set = 45,
  default_rpe_min = 1,
  default_rpe_max = 2
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'quadruped-spinal-circles';

-- Quadruped Thread the Needle (quadruped-thread-the-needle)
UPDATE coaching.exercise SET
  name = 'Quadruped Thread the Needle',
  description = 'Start on hands and knees. Reach one arm under the body, palm up, letting the shoulder and upper back rotate toward the floor. Then rotate open and reach the arm toward the ceiling. Repeat slowly.',
  card_summary = 'Supported thoracic rotation drill that opens the mid-back and posterior shoulder while limiting low-back compensation.',
  coach_language = 'Rotate through ribs and T-spine; keep hips quiet.',
  athlete_language = 'Thread your arm under, then open to the sky and follow your hand.',
  movement_family = 'Thoracic rotation',
  primary_phase_key = 'prepare_access',
  phase_subrole = 'mobilize',
  primary_order_slot = 'thoracic_rotation',
  default_sets = 1,
  default_reps = 6,
  default_work_seconds = 45,
  default_rest_seconds = 0,
  est_seconds_per_set = 60,
  movement_requirements = '{"primary_joint_actions":["thoracic_rotation","shoulder_flexion"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb,
  coaching_execution = '{"movement_description":"Start on hands and knees. Reach one arm under the body, palm up, letting the shoulder and upper back rotate toward the floor. Then rotate open and reach the arm toward the ceiling. Repeat slowly.","setup":["Quadruped, one hand behind head or ready to thread","Support arm active"],"execution_steps":["Reach under body, palm up, shoulder toward floor","Rotate open, reach to ceiling","Follow with eyes","Repeat other side"],"coach_cues":["Rotate through upper back and ribs","Keep hips relatively quiet","Breathe into the bottom position","Do not jam end range","Keep the support arm active"],"common_faults":["Low back twisting instead of thoracic rotation","Hips shifting side to side","Collapsing into the support shoulder","Neck craning","Forcing painful shoulder range"]}'::jsonb,
  pairing_logic = '{"pairs_well_before":[],"pairs_well_after":["Cat-Cow","Open Book","World''s Greatest Stretch","Wall Slides","Bear Crawl Rock-Back"],"good_for_sessions":[],"avoid_before":[],"avoid_after":[],"do_not_use_when":["Wrist or shoulder loading is painful","Athlete has acute shoulder irritation with cross-body reach","Coach needs more hip-focused prep instead"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Elite Performance Institute Thread the Needle","The Prehab Guys tall plank thread the needle (elevated/knees regression)"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'quadruped-thread-the-needle';

UPDATE coaching.exercise_phase_profile p SET
  order_slot = 'thoracic_rotation',
  order_index = pos.order_index
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'prepare_access'
JOIN coaching.phase_order_slot pos ON pos.key = 'thoracic_rotation' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'quadruped-thread-the-needle';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 1,
  default_reps = 6,
  default_work_seconds = 45,
  default_rest_seconds = 0,
  est_seconds_per_set = 60,
  default_rpe_min = 1,
  default_rpe_max = 3
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'quadruped-thread-the-needle';

-- Side-Lying Open Book (side-lying-open-book)
UPDATE coaching.exercise SET
  name = 'Side-Lying Open Book',
  description = 'Lie on the side with knees bent and stacked. Arms start together in front of the chest. Open the top arm across the body toward the floor behind you while keeping knees stacked. Follow the hand with the eyes, breathe, and return.',
  card_summary = 'Side-lying thoracic rotation drill used to improve ribcage and mid-back motion while the lower body stays supported.',
  coach_language = 'Knees stacked; rotate through ribs, not lumbar spine.',
  athlete_language = 'Open your top arm like a book and follow your hand with your eyes.',
  movement_family = 'Thoracic rotation',
  primary_phase_key = 'prepare_access',
  phase_subrole = 'mobilize',
  primary_order_slot = 'thoracic_rotation',
  default_sets = 1,
  default_reps = 6,
  default_work_seconds = 45,
  default_rest_seconds = 0,
  est_seconds_per_set = 60,
  movement_requirements = '{"primary_joint_actions":["thoracic_rotation"],"primary_tissues":[],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb,
  coaching_execution = '{"movement_description":"Lie on the side with knees bent and stacked. Arms start together in front of the chest. Open the top arm across the body toward the floor behind you while keeping knees stacked. Follow the hand with the eyes, breathe, and return.","setup":["Side-lying, knees bent 90° and stacked","Arms extended together in front"],"execution_steps":["Open top arm like a book","Follow hand with eyes","Exhale into open position","Return with control"],"coach_cues":["Knees stay stacked","Rotate through ribs and upper back","Exhale into the open position","Move slowly","Shoulder stays relaxed"],"common_faults":["Top knee lifting","Low back arching","Forcing the shoulder to the floor","Breath holding","Neck tension"]}'::jsonb,
  pairing_logic = '{"pairs_well_before":[],"pairs_well_after":["Thread the Needle","Wall Slides","World''s Greatest Stretch","Band Pull-Apart","Throwing/rotational prep"],"good_for_sessions":[],"avoid_before":[],"avoid_after":[],"do_not_use_when":["Side-lying causes discomfort","Shoulder pain increases with open-arm position","Athlete cannot keep pelvis controlled"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Elite Performance Institute Thoracic Rotation Open Book","The Prehab Guys thoracic mobility guidance"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'side-lying-open-book';

UPDATE coaching.exercise_phase_profile p SET
  order_slot = 'thoracic_rotation',
  order_index = pos.order_index
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'prepare_access'
JOIN coaching.phase_order_slot pos ON pos.key = 'thoracic_rotation' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'side-lying-open-book';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 1,
  default_reps = 6,
  default_work_seconds = 45,
  default_rest_seconds = 0,
  est_seconds_per_set = 60,
  default_rpe_min = 1,
  default_rpe_max = 2
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'side-lying-open-book';

-- 90/90 Hip Switch (9090-hip-switch)
UPDATE coaching.exercise SET
  name = '90/90 Hip Switch',
  description = 'Sit with both knees bent, one leg in front and one leg to the side/back so both knees form approximate 90-degree angles. Stay tall. Rotate both knees to switch sides. Optionally hinge forward over the front shin before switching.',
  card_summary = 'Seated hip internal/external rotation drill that improves hip access, pelvic control, and rotational mobility.',
  coach_language = 'Tall spine; rotate from hips. Both IR and ER in one drill.',
  athlete_language = 'Switch your legs like a windshield wiper — stay tall and control the landing.',
  movement_family = 'Hip rotation',
  primary_phase_key = 'prepare_access',
  phase_subrole = 'mobilize',
  primary_order_slot = 'hip_rotation',
  default_sets = 1,
  default_reps = 6,
  default_work_seconds = 60,
  default_rest_seconds = 0,
  est_seconds_per_set = 60,
  movement_requirements = '{"primary_joint_actions":["hip_rotation"],"primary_tissues":["hip_capsule"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb,
  coaching_execution = '{"movement_description":"Sit with both knees bent, one leg in front and one leg to the side/back so both knees form approximate 90-degree angles. Stay tall. Rotate both knees to switch sides. Optionally hinge forward over the front shin before switching.","setup":["Seated 90/90, hands behind for support if needed","Tall spine"],"execution_steps":["Optional hinge toward front shin","Lift knees and switch to opposite 90/90","Control landing","Repeat"],"coach_cues":["Tall spine","Rotate from hips, not just feet","Keep control through the switch","Use hands as needed","No knee pain"],"common_faults":["Knees pinching","Slumped posture","Using momentum","Feet sliding too far away","Forcing internal rotation"]}'::jsonb,
  pairing_logic = '{"pairs_well_before":[],"pairs_well_after":["Hip CARs","Shin Box Switch","Deep Squat Pry","Cossack Shift","Glute Bridge"],"good_for_sessions":[],"avoid_before":[],"avoid_after":[],"do_not_use_when":["Knee pain occurs in either hip rotation position","Athlete has hip pinching that worsens with flexion/internal rotation","Athlete cannot control posture at all; regress to supine hip rotations"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["The Prehab Guys 90/90 Hip Switch Stretch"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = '9090-hip-switch';

UPDATE coaching.exercise_phase_profile p SET
  order_slot = 'hip_rotation',
  order_index = pos.order_index
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'prepare_access'
JOIN coaching.phase_order_slot pos ON pos.key = 'hip_rotation' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = '9090-hip-switch';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 1,
  default_reps = 6,
  default_work_seconds = 60,
  default_rest_seconds = 0,
  est_seconds_per_set = 60,
  default_rpe_min = 2,
  default_rpe_max = 4
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = '9090-hip-switch';

-- World's Greatest Stretch (worlds-greatest-stretch)
UPDATE coaching.exercise SET
  name = 'World''s Greatest Stretch',
  description = 'Step into a long lunge. Place both hands inside the front foot. Drop the elbow or chest slightly toward the floor, then rotate the inside arm toward the ceiling. Return hand down. Shift hips back to lengthen the front hamstring, then step forward or switch sides.',
  card_summary = 'Integrated dynamic lunge mobility drill connecting hip flexor length, hamstring access, thoracic rotation, and trunk control.',
  coach_language = 'Dynamic flow — front foot flat, rotate through chest, control the lunge.',
  athlete_language = 'Lunge long, rotate open to the sky, then shift back to stretch the hamstring.',
  movement_family = 'Integrated mobility',
  primary_phase_key = 'prepare_access',
  phase_subrole = 'integrate',
  primary_order_slot = 'integrated_mobility',
  default_sets = 1,
  default_reps = 4,
  default_work_seconds = 60,
  default_rest_seconds = 0,
  est_seconds_per_set = 75,
  movement_requirements = '{"primary_joint_actions":["hip_flexion","hip_extension","thoracic_rotation","shoulder_flexion"],"primary_tissues":["hip_flexors","hamstrings"],"breathing_demand":"nasal","balance_demand":"single_leg","impact_level":0}'::jsonb,
  coaching_execution = '{"movement_description":"Step into a long lunge. Place both hands inside the front foot. Drop the elbow or chest slightly toward the floor, then rotate the inside arm toward the ceiling. Return hand down. Shift hips back to lengthen the front hamstring, then step forward or switch sides.","setup":["Long lunge, back knee down or up per level","Hands inside front foot"],"execution_steps":["Drop elbow/chest toward floor inside front foot","Rotate inside arm to ceiling","Return hand down","Shift hips back for hamstring length","Step or switch sides"],"coach_cues":["Front foot flat","Back leg long","Rotate through chest, not low back only","Control the lunge","Breathe during rotation"],"common_faults":["Front heel lifting","Knee collapsing inward","Low back twisting aggressively","Athlete forcing elbow to floor","Rushing through positions"]}'::jsonb,
  pairing_logic = '{"pairs_well_before":[],"pairs_well_after":["90/90 Hip Switch","Knee-to-Wall Ankle Rocker","Leg Swings","A-March","Low Pogo","Sprint mechanics"],"good_for_sessions":[],"avoid_before":[],"avoid_after":[],"do_not_use_when":["Athlete has acute hip flexor, knee, wrist, or low-back irritation","Athlete cannot stabilize the lunge","Static/passive holding replaces dynamic movement before power work"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Squat University World''s Greatest Stretch","NASM dynamic stretching and multiplanar lunge progressions"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'worlds-greatest-stretch';

UPDATE coaching.exercise_phase_profile p SET
  order_slot = 'integrated_mobility',
  order_index = pos.order_index
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'prepare_access'
JOIN coaching.phase_order_slot pos ON pos.key = 'integrated_mobility' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'worlds-greatest-stretch';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 1,
  default_reps = 4,
  default_work_seconds = 60,
  default_rest_seconds = 0,
  est_seconds_per_set = 75,
  default_rpe_min = 2,
  default_rpe_max = 4
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'worlds-greatest-stretch';

-- Inchworm Walkout (inchworm-walkout)
UPDATE coaching.exercise SET
  name = 'Inchworm Walkout',
  description = 'From standing, hinge forward and place hands on the ground. Walk hands forward into a tall plank. Pause briefly with ribs and pelvis controlled. Walk feet toward hands or hands back toward feet, then stand tall and repeat.',
  card_summary = 'Integrated posterior-chain and shoulder-access drill that links hamstring mobility, plank position, trunk control, and hand-supported movement.',
  coach_language = 'Bridge to integrated control — hinge, plank line, then return.',
  athlete_language = 'Reach down, walk out to a strong plank, walk back, stand tall.',
  movement_family = 'Integrated mobility',
  primary_phase_key = 'prepare_access',
  phase_subrole = 'integrate',
  primary_order_slot = 'integrated_mobility',
  default_sets = 1,
  default_reps = 5,
  default_work_seconds = 60,
  default_rest_seconds = 0,
  est_seconds_per_set = 75,
  movement_requirements = '{"primary_joint_actions":["hip_hinge","shoulder_flexion"],"primary_tissues":["hamstrings"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0}'::jsonb,
  coaching_execution = '{"movement_description":"From standing, hinge forward and place hands on the ground. Walk hands forward into a tall plank. Pause briefly with ribs and pelvis controlled. Walk feet toward hands or hands back toward feet, then stand tall and repeat.","setup":["Stand feet hip-width","Soft knees available if hamstrings tight"],"execution_steps":["Hinge and place hands on floor","Walk hands to tall plank","Brief pause — ribs and pelvis controlled","Walk feet to hands or hands back","Stand tall and repeat"],"coach_cues":["Hinge first","Keep knees soft if needed but avoid collapsing","Plank line: ears, shoulders, ribs, hips, heels","Push the floor away","Move with control"],"common_faults":["Sagging low back in plank","Rushing the walkout","Excessive wrist discomfort","Hamstring stretch becoming painful","Head hanging or neck tension"]}'::jsonb,
  pairing_logic = '{"pairs_well_before":[],"pairs_well_after":["Cat-Cow","Wrist Rockers","Scapular Push-Up","World''s Greatest Stretch","A-March","Low pogo prep"],"good_for_sessions":[],"avoid_before":[],"avoid_after":[],"do_not_use_when":["Wrist pain is present","Athlete cannot hold plank without lumbar sag","Hamstring strain history is irritated by forward fold","You are about to do grip- or wrist-heavy tumbling and the athlete is already fatigued"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["The Prehab Guys Inchworm Walking"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'inchworm-walkout';

UPDATE coaching.exercise_phase_profile p SET
  order_slot = 'integrated_mobility',
  order_index = pos.order_index
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'prepare_access'
JOIN coaching.phase_order_slot pos ON pos.key = 'integrated_mobility' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'inchworm-walkout';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 1,
  default_reps = 5,
  default_work_seconds = 60,
  default_rest_seconds = 0,
  est_seconds_per_set = 75,
  default_rpe_min = 3,
  default_rpe_max = 5
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'inchworm-walkout';

-- Refresh weighted taxonomy tags for foundation cards
DELETE FROM coaching.exercise_tag t
USING coaching.exercise e
WHERE t.exercise_id = e.id
  AND e.slug IN ('9090-breathing-with-reach', 'crocodile-breathing', 'full-body-joint-cars-flow', 'cat-cow', 'quadruped-spinal-circles', 'quadruped-thread-the-needle', 'side-lying-open-book', '9090-hip-switch', 'worlds-greatest-stretch', 'inchworm-walkout')
  AND t.facet_type IN ('tenet', 'methodology', 'physiology', 'pattern', 'equipment', 'body_region');

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'tenet', f.id, v.weight
FROM (VALUES
  ('9090-breathing-with-reach', 'flexibility', 3),
  ('9090-breathing-with-reach', 'body_control', 4),
  ('9090-breathing-with-reach', 'coordination', 2),
  ('crocodile-breathing', 'body_control', 4),
  ('crocodile-breathing', 'flexibility', 2),
  ('full-body-joint-cars-flow', 'flexibility', 4),
  ('full-body-joint-cars-flow', 'coordination', 3),
  ('full-body-joint-cars-flow', 'body_control', 3),
  ('cat-cow', 'flexibility', 4),
  ('cat-cow', 'body_control', 4),
  ('cat-cow', 'coordination', 2),
  ('quadruped-spinal-circles', 'flexibility', 4),
  ('quadruped-spinal-circles', 'coordination', 4),
  ('quadruped-spinal-circles', 'body_control', 4),
  ('quadruped-thread-the-needle', 'flexibility', 4),
  ('quadruped-thread-the-needle', 'coordination', 3),
  ('quadruped-thread-the-needle', 'body_control', 3),
  ('side-lying-open-book', 'flexibility', 4),
  ('side-lying-open-book', 'body_control', 3),
  ('side-lying-open-book', 'coordination', 2),
  ('9090-hip-switch', 'flexibility', 5),
  ('9090-hip-switch', 'balance', 2),
  ('9090-hip-switch', 'coordination', 3),
  ('9090-hip-switch', 'body_control', 3),
  ('worlds-greatest-stretch', 'flexibility', 5),
  ('worlds-greatest-stretch', 'coordination', 3),
  ('worlds-greatest-stretch', 'body_control', 3),
  ('worlds-greatest-stretch', 'balance', 2),
  ('inchworm-walkout', 'flexibility', 4),
  ('inchworm-walkout', 'body_control', 4),
  ('inchworm-walkout', 'coordination', 3),
  ('inchworm-walkout', 'balance', 2)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.tenet f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'methodology', f.id, v.weight
FROM (VALUES
  ('9090-breathing-with-reach', 'mobility_flexibility', 3),
  ('9090-breathing-with-reach', 'core_body_control', 4),
  ('9090-breathing-with-reach', 'neural', 2),
  ('crocodile-breathing', 'mobility_flexibility', 3),
  ('crocodile-breathing', 'core_body_control', 3),
  ('crocodile-breathing', 'neural', 2),
  ('full-body-joint-cars-flow', 'mobility_flexibility', 5),
  ('full-body-joint-cars-flow', 'neural', 2),
  ('cat-cow', 'mobility_flexibility', 5),
  ('cat-cow', 'core_body_control', 2),
  ('quadruped-spinal-circles', 'mobility_flexibility', 5),
  ('quadruped-spinal-circles', 'core_body_control', 2),
  ('quadruped-thread-the-needle', 'mobility_flexibility', 5),
  ('quadruped-thread-the-needle', 'core_body_control', 2),
  ('side-lying-open-book', 'mobility_flexibility', 5),
  ('9090-hip-switch', 'mobility_flexibility', 5),
  ('9090-hip-switch', 'core_body_control', 2),
  ('worlds-greatest-stretch', 'mobility_flexibility', 5),
  ('worlds-greatest-stretch', 'core_body_control', 2),
  ('worlds-greatest-stretch', 'neural', 2),
  ('inchworm-walkout', 'mobility_flexibility', 4),
  ('inchworm-walkout', 'core_body_control', 4),
  ('inchworm-walkout', 'neural', 2)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.methodology f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'physiology', f.id, v.weight
FROM (VALUES
  ('9090-breathing-with-reach', 'neural_output_readiness', 3),
  ('9090-breathing-with-reach', 'control_stability', 4),
  ('crocodile-breathing', 'control_stability', 4),
  ('crocodile-breathing', 'neural_output_readiness', 3),
  ('full-body-joint-cars-flow', 'control_stability', 3),
  ('full-body-joint-cars-flow', 'neural_output_readiness', 3),
  ('cat-cow', 'control_stability', 4),
  ('cat-cow', 'neural_output_readiness', 2),
  ('quadruped-spinal-circles', 'control_stability', 4),
  ('quadruped-spinal-circles', 'perception_action_skill', 2),
  ('quadruped-thread-the-needle', 'control_stability', 4),
  ('quadruped-thread-the-needle', 'perception_action_skill', 2),
  ('side-lying-open-book', 'control_stability', 3),
  ('side-lying-open-book', 'perception_action_skill', 2),
  ('9090-hip-switch', 'control_stability', 4),
  ('9090-hip-switch', 'perception_action_skill', 2),
  ('worlds-greatest-stretch', 'control_stability', 4),
  ('worlds-greatest-stretch', 'neural_output_readiness', 2),
  ('inchworm-walkout', 'control_stability', 4),
  ('inchworm-walkout', 'neural_output_readiness', 3)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.physiological_emphasis f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'pattern', f.id, v.weight
FROM (VALUES
  ('9090-breathing-with-reach', 'brace', 4),
  ('crocodile-breathing', 'brace', 4),
  ('full-body-joint-cars-flow', 'rotate', 4),
  ('full-body-joint-cars-flow', 'brace', 2),
  ('cat-cow', 'brace', 3),
  ('quadruped-spinal-circles', 'rotate', 3),
  ('quadruped-spinal-circles', 'brace', 3),
  ('quadruped-thread-the-needle', 'rotate', 5),
  ('quadruped-thread-the-needle', 'brace', 2),
  ('side-lying-open-book', 'rotate', 5),
  ('9090-hip-switch', 'rotate', 5),
  ('9090-hip-switch', 'squat', 2),
  ('worlds-greatest-stretch', 'locomote', 3),
  ('worlds-greatest-stretch', 'rotate', 4),
  ('worlds-greatest-stretch', 'hinge', 3),
  ('worlds-greatest-stretch', 'squat', 2),
  ('inchworm-walkout', 'hinge', 4),
  ('inchworm-walkout', 'brace', 4),
  ('inchworm-walkout', 'locomote', 3),
  ('inchworm-walkout', 'push', 2)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.movement_pattern f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'equipment', f.id, v.weight
FROM (VALUES
  ('9090-breathing-with-reach', 'none', 5),
  ('9090-breathing-with-reach', 'mat', 2),
  ('crocodile-breathing', 'none', 5),
  ('crocodile-breathing', 'mat', 2),
  ('full-body-joint-cars-flow', 'none', 5),
  ('cat-cow', 'none', 5),
  ('cat-cow', 'mat', 2),
  ('quadruped-spinal-circles', 'none', 5),
  ('quadruped-spinal-circles', 'mat', 2),
  ('quadruped-thread-the-needle', 'none', 5),
  ('quadruped-thread-the-needle', 'mat', 2),
  ('side-lying-open-book', 'none', 5),
  ('side-lying-open-book', 'mat', 2),
  ('9090-hip-switch', 'none', 5),
  ('9090-hip-switch', 'mat', 2),
  ('worlds-greatest-stretch', 'none', 5),
  ('worlds-greatest-stretch', 'mat', 1),
  ('inchworm-walkout', 'none', 5),
  ('inchworm-walkout', 'mat', 1)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.equipment f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'body_region', f.id, v.weight
FROM (VALUES
  ('9090-breathing-with-reach', 'core', 5),
  ('9090-breathing-with-reach', 'spine', 4),
  ('9090-breathing-with-reach', 'hip', 2),
  ('crocodile-breathing', 'core', 5),
  ('crocodile-breathing', 'spine', 3),
  ('full-body-joint-cars-flow', 'full_body', 5),
  ('cat-cow', 'spine', 5),
  ('cat-cow', 'core', 3),
  ('cat-cow', 'shoulder', 2),
  ('cat-cow', 'wrist', 2),
  ('quadruped-spinal-circles', 'spine', 5),
  ('quadruped-spinal-circles', 'core', 3),
  ('quadruped-spinal-circles', 'shoulder', 2),
  ('quadruped-spinal-circles', 'wrist', 2),
  ('quadruped-thread-the-needle', 'spine', 5),
  ('quadruped-thread-the-needle', 'shoulder', 4),
  ('quadruped-thread-the-needle', 'core', 3),
  ('quadruped-thread-the-needle', 'wrist', 2),
  ('side-lying-open-book', 'spine', 5),
  ('side-lying-open-book', 'shoulder', 3),
  ('side-lying-open-book', 'core', 2),
  ('9090-hip-switch', 'hip', 5),
  ('9090-hip-switch', 'spine', 2),
  ('9090-hip-switch', 'knee', 2),
  ('worlds-greatest-stretch', 'hip', 5),
  ('worlds-greatest-stretch', 'spine', 4),
  ('worlds-greatest-stretch', 'ankle', 3),
  ('worlds-greatest-stretch', 'shoulder', 2),
  ('worlds-greatest-stretch', 'core', 3),
  ('inchworm-walkout', 'hip', 4),
  ('inchworm-walkout', 'spine', 3),
  ('inchworm-walkout', 'core', 4),
  ('inchworm-walkout', 'shoulder', 4),
  ('inchworm-walkout', 'wrist', 3)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.body_region f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'youth_beginner' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('9090-breathing-with-reach', 'Use hands on belly/ribs. Make it simple: "fill the balloon, blow out slow."', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', '3–5 slow breaths only; use "belly pushes the floor" cue.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Make it a "joint check game"; 1–2 circles per joint.', 'No gender default change.'),
  ('cat-cow', 'Use animal cues: "angry cat / happy cow."', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Use "draw a circle with your back" cue.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Keep hand on head instead of reaching long.', 'No gender default change.'),
  ('side-lying-open-book', 'Use smaller range and "open the book" cue.', 'No gender default change.'),
  ('9090-hip-switch', 'Allow hands behind body and larger knee angles.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Use hands on blocks or elevated surface.', 'No gender default change.'),
  ('inchworm-walkout', 'Shorten range; walk hands to elevated box.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_beginner';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'youth_beginner', 'youth beginner', 'baseline', v.guidance,
  CASE WHEN 'youth_beginner' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('9090-breathing-with-reach', 'Use hands on belly/ribs. Make it simple: "fill the balloon, blow out slow."', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', '3–5 slow breaths only; use "belly pushes the floor" cue.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Make it a "joint check game"; 1–2 circles per joint.', 'No gender default change.'),
  ('cat-cow', 'Use animal cues: "angry cat / happy cow."', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Use "draw a circle with your back" cue.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Keep hand on head instead of reaching long.', 'No gender default change.'),
  ('side-lying-open-book', 'Use smaller range and "open the book" cue.', 'No gender default change.'),
  ('9090-hip-switch', 'Allow hands behind body and larger knee angles.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Use hands on blocks or elevated surface.', 'No gender default change.'),
  ('inchworm-walkout', 'Shorten range; walk hands to elevated box.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_beginner'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'youth_intermediate' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('9090-breathing-with-reach', 'Add gentle reach and heel pressure into wall.', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', 'Add reach or low cobra transition after breathing.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Add balance challenge: standing ankle/hip CARs with support nearby.', 'No gender default change.'),
  ('cat-cow', 'Add segmental challenge: pelvis first, ribs second, neck last.', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Add smaller controlled circles and reverse direction.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Add reach to ceiling and eyes follow hand.', 'No gender default change.'),
  ('side-lying-open-book', 'Add eyes-follow-hand coordination.', 'No gender default change.'),
  ('9090-hip-switch', 'Add tall posture and slow controlled switch.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Add step-through rhythm.', 'No gender default change.'),
  ('inchworm-walkout', 'Add plank pause or shoulder tap if control is good.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_intermediate';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'youth_intermediate', 'youth intermediate', 'baseline', v.guidance,
  CASE WHEN 'youth_intermediate' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('9090-breathing-with-reach', 'Add gentle reach and heel pressure into wall.', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', 'Add reach or low cobra transition after breathing.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Add balance challenge: standing ankle/hip CARs with support nearby.', 'No gender default change.'),
  ('cat-cow', 'Add segmental challenge: pelvis first, ribs second, neck last.', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Add smaller controlled circles and reverse direction.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Add reach to ceiling and eyes follow hand.', 'No gender default change.'),
  ('side-lying-open-book', 'Add eyes-follow-hand coordination.', 'No gender default change.'),
  ('9090-hip-switch', 'Add tall posture and slow controlled switch.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Add step-through rhythm.', 'No gender default change.'),
  ('inchworm-walkout', 'Add plank pause or shoulder tap if control is good.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_intermediate'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'teen' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('9090-breathing-with-reach', 'Use wall support; 4-second inhale, 6-second exhale.', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', 'Use 5–8 breaths, slow exhale.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Use slow tempo and smaller ranges.', 'No gender default change.'),
  ('cat-cow', 'Reduce range and slow tempo.', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Keep range small and pain-free.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Reduce range and use yoga block or bench for support.', 'No gender default change.'),
  ('side-lying-open-book', 'Place pad/ball between knees to prevent hip compensation.', 'No gender default change.'),
  ('9090-hip-switch', 'Sit on yoga block or mat to reduce hip demand.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Break into two parts: lunge reach, then hamstring shift.', 'No gender default change.'),
  ('inchworm-walkout', 'Bend knees slightly and reduce walkout distance.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'teen';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'teen', 'teen', 'baseline', v.guidance,
  CASE WHEN 'teen' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('9090-breathing-with-reach', 'Use wall support; 4-second inhale, 6-second exhale.', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', 'Use 5–8 breaths, slow exhale.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Use slow tempo and smaller ranges.', 'No gender default change.'),
  ('cat-cow', 'Reduce range and slow tempo.', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Keep range small and pain-free.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Reduce range and use yoga block or bench for support.', 'No gender default change.'),
  ('side-lying-open-book', 'Place pad/ball between knees to prevent hip compensation.', 'No gender default change.'),
  ('9090-hip-switch', 'Sit on yoga block or mat to reduce hip demand.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Break into two parts: lunge reach, then hamstring shift.', 'No gender default change.'),
  ('inchworm-walkout', 'Bend knees slightly and reduce walkout distance.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'teen'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'adult_beginner' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('9090-breathing-with-reach', 'Use wall support; 4-second inhale, 6-second exhale.', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', 'Use 5–8 breaths, slow exhale.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Use slow tempo and smaller ranges.', 'No gender default change.'),
  ('cat-cow', 'Reduce range and slow tempo.', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Keep range small and pain-free.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Reduce range and use yoga block or bench for support.', 'No gender default change.'),
  ('side-lying-open-book', 'Place pad/ball between knees to prevent hip compensation.', 'No gender default change.'),
  ('9090-hip-switch', 'Sit on yoga block or mat to reduce hip demand.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Break into two parts: lunge reach, then hamstring shift.', 'No gender default change.'),
  ('inchworm-walkout', 'Bend knees slightly and reduce walkout distance.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_beginner';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'adult_beginner', 'adult beginner', 'baseline', v.guidance,
  CASE WHEN 'adult_beginner' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('9090-breathing-with-reach', 'Use wall support; 4-second inhale, 6-second exhale.', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', 'Use 5–8 breaths, slow exhale.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Use slow tempo and smaller ranges.', 'No gender default change.'),
  ('cat-cow', 'Reduce range and slow tempo.', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Keep range small and pain-free.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Reduce range and use yoga block or bench for support.', 'No gender default change.'),
  ('side-lying-open-book', 'Place pad/ball between knees to prevent hip compensation.', 'No gender default change.'),
  ('9090-hip-switch', 'Sit on yoga block or mat to reduce hip demand.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Break into two parts: lunge reach, then hamstring shift.', 'No gender default change.'),
  ('inchworm-walkout', 'Bend knees slightly and reduce walkout distance.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_beginner'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'adult_advanced' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('9090-breathing-with-reach', 'Add dead bug arm reach, heel drag, or exhale-to-brace transition.', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', 'Pair with prone shoulder lift-off or cobra wave.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Add controlled end-range pauses.', 'No gender default change.'),
  ('cat-cow', 'Add quadruped spinal wave or transition to beast/bear position.', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Add spinal wave to bear position.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Use tall plank thread the needle or add controlled end-range pause.', 'No gender default change.'),
  ('side-lying-open-book', 'Progress to half-kneeling thoracic rotation or tall plank thread.', 'No gender default change.'),
  ('9090-hip-switch', 'Add no-hands switch, lift-off, or shin-box get-up.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Add continuous walking flow or spider lunge crawl.', 'No gender default change.'),
  ('inchworm-walkout', 'Add push-up, single-leg inchworm, or slow eccentric walkout.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_advanced';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'adult_advanced', 'adult advanced', 'baseline', v.guidance,
  CASE WHEN 'adult_advanced' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('9090-breathing-with-reach', 'Add dead bug arm reach, heel drag, or exhale-to-brace transition.', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', 'Pair with prone shoulder lift-off or cobra wave.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Add controlled end-range pauses.', 'No gender default change.'),
  ('cat-cow', 'Add quadruped spinal wave or transition to beast/bear position.', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Add spinal wave to bear position.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Use tall plank thread the needle or add controlled end-range pause.', 'No gender default change.'),
  ('side-lying-open-book', 'Progress to half-kneeling thoracic rotation or tall plank thread.', 'No gender default change.'),
  ('9090-hip-switch', 'Add no-hands switch, lift-off, or shin-box get-up.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Add continuous walking flow or spider lunge crawl.', 'No gender default change.'),
  ('inchworm-walkout', 'Add push-up, single-leg inchworm, or slow eccentric walkout.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_advanced'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'older_adult' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('9090-breathing-with-reach', 'Use bench/chair support, avoid getting stuck on the floor if mobility is limited.', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', 'Use pillow under chest/head or substitute seated breathing.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Use seated or wall-supported variations.', 'No gender default change.'),
  ('cat-cow', 'Use elevated hands on bench or seated cat-cow.', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Elevate hands or use seated torso circles.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Elevate hands on bench to reduce wrist/knee demand.', 'No gender default change.'),
  ('side-lying-open-book', 'Support head with pillow and reduce range.', 'No gender default change.'),
  ('9090-hip-switch', 'Elevate hips and reduce range.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Elevate hands on bench and reduce lunge depth.', 'No gender default change.'),
  ('inchworm-walkout', 'Use elevated surface or wall walkout.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'older_adult';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'older_adult', 'older adult', 'baseline', v.guidance,
  CASE WHEN 'older_adult' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('9090-breathing-with-reach', 'Use bench/chair support, avoid getting stuck on the floor if mobility is limited.', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', 'Use pillow under chest/head or substitute seated breathing.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Use seated or wall-supported variations.', 'No gender default change.'),
  ('cat-cow', 'Use elevated hands on bench or seated cat-cow.', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Elevate hands or use seated torso circles.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Elevate hands on bench to reduce wrist/knee demand.', 'No gender default change.'),
  ('side-lying-open-book', 'Support head with pillow and reduce range.', 'No gender default change.'),
  ('9090-hip-switch', 'Elevate hips and reduce range.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Elevate hands on bench and reduce lunge depth.', 'No gender default change.'),
  ('inchworm-walkout', 'Use elevated surface or wall walkout.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'older_adult'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'pregnancy_postpartum' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('9090-breathing-with-reach', 'Avoid prolonged supine work after the first trimester unless cleared and comfortable; use side-lying or seated breathing alternative.', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', 'Avoid prone positioning during pregnancy; use side-lying, seated, or quadruped breathing.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Avoid breath-holding and extreme ranges; use comfortable positions.', 'No gender default change.'),
  ('cat-cow', 'Quadruped version is often more comfortable than supine; avoid breath-holding and extreme abdominal pressure.', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Use comfortable quadruped; avoid breath-holding and excessive abdominal pressure.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Use elevated quadruped or side-lying open book if floor position is uncomfortable.', 'No gender default change.'),
  ('side-lying-open-book', 'Use comfortable side-lying setup; avoid prolonged supine, use pillows as needed.', 'No gender default change.'),
  ('9090-hip-switch', 'Use wider setup, avoid deep compression, and use hand support.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Use wider stance, elevated hands, avoid deep compression if uncomfortable.', 'No gender default change.'),
  ('inchworm-walkout', 'Use elevated hands and avoid high abdominal pressure or long plank holds unless cleared.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'pregnancy_postpartum';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'pregnancy_postpartum', 'pregnancy postpartum', 'baseline', v.guidance,
  CASE WHEN 'pregnancy_postpartum' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('9090-breathing-with-reach', 'Avoid prolonged supine work after the first trimester unless cleared and comfortable; use side-lying or seated breathing alternative.', 'No default gender adjustment; scale by trunk control, comfort, pregnancy/postpartum status, and breathing strategy.'),
  ('crocodile-breathing', 'Avoid prone positioning during pregnancy; use side-lying, seated, or quadruped breathing.', 'No male/female default change.'),
  ('full-body-joint-cars-flow', 'Avoid breath-holding and extreme ranges; use comfortable positions.', 'No gender default change.'),
  ('cat-cow', 'Quadruped version is often more comfortable than supine; avoid breath-holding and extreme abdominal pressure.', 'No gender default change.'),
  ('quadruped-spinal-circles', 'Use comfortable quadruped; avoid breath-holding and excessive abdominal pressure.', 'No gender default change.'),
  ('quadruped-thread-the-needle', 'Use elevated quadruped or side-lying open book if floor position is uncomfortable.', 'No gender default change.'),
  ('side-lying-open-book', 'Use comfortable side-lying setup; avoid prolonged supine, use pillows as needed.', 'No gender default change.'),
  ('9090-hip-switch', 'Use wider setup, avoid deep compression, and use hand support.', 'No gender default change; scale by hip anatomy, comfort, and control.'),
  ('worlds-greatest-stretch', 'Use wider stance, elevated hands, avoid deep compression if uncomfortable.', 'No gender default change.'),
  ('inchworm-walkout', 'Use elevated hands and avoid high abdominal pressure or long plank holds unless cleared.', 'No gender default change; scale by trunk control, wrist tolerance, and hamstring range.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'pregnancy_postpartum'
);

-- Why-layer education
INSERT INTO coaching.education_content (
  entity_type, entity_key, entity_id, title, short_summary,
  what_it_is, why_it_works, why_it_matters, why_it_goes_here,
  programming_guidance, common_misuse, scaling_guidance
)
SELECT
  'exercise', e.slug, e.id, e.name, e.card_summary,
  e.description,
  v.why_works,
  'Develops tagged tenets and physiological qualities for athletic development.',
  v.why_here,
  v.best_placement,
  v.misuse,
  v.scale_guidance
FROM (VALUES
  ('9090-breathing-with-reach', 'The 90/90 position gives the athlete a low-threat way to organize the ribcage, pelvis, and diaphragm. It is especially useful when athletes default to chest breathing, rib flare, excessive lumbar extension, or poor trunk bracing. Functional Movement Systems describes the drill as a way to practice diaphragmatic breathing with the hips and knees at 90 degrees and emphasizes slow nasal breathing with a longer exhale.', 'Belongs in Mobilize (breathing_reset) — opens trunk access and down-regulates before mobility or skill work.', 'First 1–3 minutes of session, especially before mobility, tumbling, sprint mechanics, lifting, or athletes who arrive overextended, anxious, or stiff.', 'Do not use as a long relaxation block or substitute for raising temperature when athletes need active warm-up.', 'Scale by trunk control, comfort in supine, and breathing strategy; reduce reps/duration for youth.'),
  ('crocodile-breathing', 'Crocodile breathing places the athlete prone so the floor gives immediate feedback. When they inhale, they should feel the belly and lower ribs expand into the ground rather than lifting the shoulders. Functional Movement Systems describes it as a diaphragmatic breathing exercise performed prone with relaxed chest, arms, and neck.', 'Belongs in Mobilize (breathing_reset) — nervous-system and trunk reset before active prep.', 'Early session, especially for athletes who chest-breathe, brace poorly, rush, or need a low-threat nervous-system reset.', 'Do not spend too long here before a high-energy class that needs temperature raise.', 'Regress to seated breathing for pregnancy or prone discomfort.'),
  ('full-body-joint-cars-flow', 'Joint CARs are useful because they ask the athlete to actively move through available range rather than passively fall into a stretch. GMB''s joint mobility guide frames preparation mobility as a short, light check-in before training, aimed at feeling coordinated, noticing restrictions, and preparing joints for activity rather than turning mobility into a workout.', 'Belongs in Mobilize (joint_scan) — systematic joint-by-joint readiness before specific prep.', 'Early, after breathing or light locomotion.', 'Do not treat CARs as static stretching or spend excessive time when session needs specificity.', 'Reduce joints covered or circle count for youth and beginners.'),
  ('cat-cow', 'Cat-Cow teaches the athlete to move between spinal flexion and extension while linking pelvis, ribs, and breathing. The Prehab Guys describe it as a drill for back and pelvic body awareness that promotes global mobility and comfort moving in and out of spinal flexion and extension.', 'Belongs in Mobilize (spinal_mobility) — foundational spine access before integrated patterns.', 'Early mobility sequence, especially before tumbling, crawling, lifting, or trunk-control work.', 'Do not rush reps or use painful end ranges when athlete needs stability instead.', 'Elevate hands on bench or use seated cat-cow for older adults.'),
  ('quadruped-spinal-circles', 'Cat-Cow is mostly flexion/extension. Spinal circles add lateral movement and blended motion, which is useful because athletes rarely move in clean single-plane patterns. GMB includes quadruped spinal circles in its daily diagnostic mobility sequence and describes the focus as full back mobility.', 'Belongs in Mobilize (spinal_mobility) — adds 3D spine exploration after basic flex/extend.', 'After Cat-Cow or as an alternative when the athlete needs more 3D spine motion.', 'Do not move only the head or dump into lumbar extension.', 'Elevate hands or use seated torso circles for limited wrist/knee tolerance.'),
  ('quadruped-thread-the-needle', 'Thread the Needle gives the athlete a stable quadruped base so the coach can bias thoracic rotation instead of letting the athlete compensate through the hips or low back. Elite Performance Institute describes the drill as a low-load way to loosen the midback and shoulder, improve thoracic rotation, and use daily or in warm-ups for overhead and rotational training.', 'Belongs in Mobilize (thoracic_rotation) — T-spine access before overhead or rotational work.', 'Before tumbling, overhead work, crawling, throwing, rotational drills, or upper-body strength.', 'Do not let lumbar spine twist or force painful shoulder range.', 'Elevate hands on bench for wrist/knee demand reduction.'),
  ('side-lying-open-book', 'The side-lying setup reduces lower-body demand and lets the coach focus on thoracic/rib rotation. This is useful for athletes who over-rotate through the pelvis or low back during standing rotation drills. The Prehab Guys emphasize that thoracic mobility matters for neck, shoulder, low-back, and functional movement, and their thoracic rotation guidance stresses controlling compensation and using breath through rotation.', 'Belongs in Mobilize (thoracic_rotation) — supported T-spine rotation with minimal hip demand.', 'Before tumbling, overhead training, rotational skill, throwing, pressing, crawling, and sprint mechanics.', 'Do not force shoulder to floor or let top knee lift.', 'Support head with pillow; pad between knees for hip control.'),
  ('9090-hip-switch', 'Athletic hips need both external and internal rotation. The 90/90 hip switch exposes both sides in one drill and teaches the athlete to move through hip rotation without collapsing posture. The Prehab Guys describe beginning in a seated 90/90 position, hinging toward the front knee, then rotating the legs to the other side while keeping heels on the ground.', 'Belongs in Mobilize (hip_rotation) — seated IR/ER access before squat, lunge, or sprint prep.', 'Before squatting, lunging, tumbling, sprint mechanics, lateral movement, or rotational training.', 'Do not use momentum to flop between sides or force pinching ranges.', 'Elevate hips on block; widen knee angles for youth.'),
  ('worlds-greatest-stretch', 'This drill is valuable because it integrates several high-need athletic positions: deep lunge, hip extension, hamstring length, thoracic rotation, and shoulder reach. NASM''s dynamic stretching examples include multiplanar lunges with reach as functional flexibility progressions, and Squat University describes the World''s Greatest Stretch as a way to open the hips and thoracic spine.', 'Belongs in Integrate (integrated_mobility) — multi-joint flow after isolated mobility.', 'After basic joint mobility, before sprint mechanics, plyometrics, agility, strength, or tumbling.', 'Do not hold static stretches or rush through positions before power work.', 'Elevate hands on bench; break into lunge reach + hamstring shift for beginners.'),
  ('inchworm-walkout', 'The inchworm is a bridge between mobility and integrated body control. It exposes the hamstrings through a hinge, then asks the athlete to organize shoulders, wrists, ribs, pelvis, and trunk in a plank. The Prehab Guys describe the walking inchworm as reaching toward the floor, walking hands to a high plank, stepping feet toward the hands, and standing back up; they note hamstring stretch and shoulder work as key sensations.', 'Belongs in Integrate (integrated_mobility) — late Prepare/Access bridge before higher-intent work.', 'Late Prepare / Access, after basic spine/hip/shoulder access, before Skill, Output, or Capacity.', 'Do not use before grip/wrist-heavy tumbling if athlete is already fatigued or cannot hold plank.', 'Elevated surface or wall walkout for limited hamstring/wrist tolerance.')
) AS v(slug, why_works, why_here, best_placement, misuse, scale_guidance)
JOIN coaching.exercise e ON e.slug = v.slug
ON CONFLICT (entity_type, entity_key, entity_id) DO UPDATE SET
  title = EXCLUDED.title,
  short_summary = EXCLUDED.short_summary,
  what_it_is = EXCLUDED.what_it_is,
  why_it_works = EXCLUDED.why_it_works,
  why_it_goes_here = EXCLUDED.why_it_goes_here,
  programming_guidance = EXCLUDED.programming_guidance,
  common_misuse = EXCLUDED.common_misuse,
  scaling_guidance = EXCLUDED.scaling_guidance,
  updated_at = now();
