-- Output phase Max-Velocity Exposure cards 11–18 (rich card v2 content).
-- IDEMPOTENT. Generated by scripts/generate-114-output-max-velocity-cards.mjs
-- UPDATE-only on slugs from migration 112. Fine slots seeded in migration 111.

-- Equipment taxonomy for max-velocity tags
INSERT INTO coaching.equipment (key, name, sort_order) VALUES
  ('wickets', 'Wickets', 19),
  ('timing_gates', 'Timing Gates', 20)
ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order;

-- Build-Up Sprint / Stride-Out (build-up-sprint-stride-out)
UPDATE coaching.exercise SET
  name = 'Build-Up Sprint / Stride-Out',
  description = 'Athlete starts from a rolling, two-point, or three-point entry and builds speed progressively through the first half of the rep, then holds max-effort upright mechanics through the stride-out zone. Decelerate under control after the prescribed distance.',
  card_summary = 'Gradual acceleration to upright max-effort stride-out over 20–40 yards — the primary Output entry to upright speed before flying sprints.',
  coach_language = 'Use as the safest Output max-velocity primer — teaches rhythm into top speed without a sudden fly-in. Stop when posture, arm action, or decel quality drops.',
  athlete_language = 'Build smooth, then open it up — tall, quick feet, strike under you, and finish the rep in control.',
  movement_family = 'Max-velocity exposure',
  primary_phase_key = 'output',
  phase_subrole = 'max_velocity_exposure',
  primary_order_slot = 'sprint_exposure',
  default_sets = 1,
  default_reps = 3,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 45,
  movement_requirements = '{"primary_joint_actions":["hip_extension","knee_extension","ankle_plantarflexion"],"primary_tissues":["hamstrings","glutes","calves"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":4,"prerequisites":["a-march","a-skip"]}'::jsonb,
  coaching_execution = '{"movement_description":"Progressive build to upright max-effort stride-out over 20–40 yards, then controlled deceleration.","setup":["Mark 20–40 yard lane with cones or line tape.","Confirm athlete is fresh — no heavy legs or prior max sprint block.","Choose start type (rolling, two-point, or three-point) based on training age.","Define deceleration zone beyond finish cones."],"execution_steps":["Set start with tall posture and clear intent cue.","Accelerate smoothly — do not pop vertical on first steps.","Transition to upright max-effort stride-out through the back half of the rep.","Maintain tall posture, quick ground contacts, and coordinated arm drive.","Decelerate progressively after the finish mark; walk back for full rest."],"breathing_cues":["Relaxed face at the line.","Exhale through the build; stay loose through shoulders."],"coach_cues":["Build, then open.","Tall through the top.","Strike under the hip.","Do not chase volume — chase one clean rep.","Decel under control."],"athlete_cues":["Smooth build.","Open it up.","Stay tall.","Quick feet.","Finish in control."],"common_faults":["Sprinting max from step one instead of building.","Overstriding once upright.","Posture collapsing or sitting back at max speed.","Running past prescribed distance for extra volume.","Poor deceleration or abrupt stop at end of rep."],"stop_signs":["Hamstring tightness or pull sensation.","Velocity clearly drops rep to rep.","Athlete cannot decelerate safely.","Sharp pain in calf, hip, or back."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["A-Skip","Ankling / Dribble March","Straight-Leg Bound March","Two-Point Start Walk-In"],"pairs_well_after":["Flying 10","Flying 20","Wicket Runs"],"good_for_sessions":["sprint_output","max_velocity","speed_development"],"avoid_before":["Heavy squat or RDL block","Prior max-velocity reps in same session","Fitness repeat sprints"],"avoid_after":[],"do_not_use_when":["Hamstring not warmed or prior pull this week","Athlete reports heavy legs or poor sleep","No safe deceleration space","Acute hip flexor or calf pain"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["ALTIS Stride-Out Progressions","SimpliFaster Build-Up Sprint Coaching","Feed the Cats Speed Development"],"internal_notes":["Default Output entry before fly zones; pair with timing only when athlete is advanced."]}'::jsonb,
  updated_at = now()
WHERE slug = 'build-up-sprint-stride-out';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'sprint_exposure',
  order_index = pos.order_index,
  fit_weight = 5,
  freshness_required = TRUE,
  fatigue_sensitivity = 5,
  fatigue_cost = 4,
  technical_complexity = 3,
  impact_level = 4,
  intensity_ceiling = 'high',
  notes = 'Primary sprint exposure. Not a daily drill — allow 48+ hours between true max-velocity blocks for most athletes.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'sprint_exposure' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'build-up-sprint-stride-out';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'sprints',
  default_sets = 1,
  default_reps = 3,
  default_distance = '20-40 yards',
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 45,
  default_rpe_min = 6,
  default_rpe_max = 8,
  session_volume_min = '1 set of 2 build-up sprints',
  session_volume_max = '1 set of 3 build-up sprints'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'build-up-sprint-stride-out';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'build-up-sprint-stride-out';

-- Flying 10 (flying-10)
UPDATE coaching.exercise SET
  name = 'Flying 10',
  description = 'Athlete uses a controlled build-in (15–25 yards) to reach near-max upright velocity, then sprints all-out through a 10-yard fly zone marked by cones or timing gates. Decelerate safely after the fly.',
  card_summary = '15–25 yard build into a 10-yard all-out fly zone — the standard max-velocity exposure rep for timing and upright speed.',
  coach_language = 'Use for true max-velocity exposure with minimal distance — quality over volume. Full rest between reps; stop when fly times or posture degrade.',
  athlete_language = 'Build in smooth, then explode through the 10 — stay tall, quick, and finish the fly clean.',
  movement_family = 'Max-velocity exposure',
  primary_phase_key = 'output',
  phase_subrole = 'max_velocity_exposure',
  primary_order_slot = 'flying_sprint',
  default_sets = 1,
  default_reps = 3,
  default_work_seconds = NULL,
  default_rest_seconds = 180,
  est_seconds_per_set = 35,
  movement_requirements = '{"primary_joint_actions":["hip_extension","knee_extension","ankle_plantarflexion"],"primary_tissues":["hamstrings","glutes","calves"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":4,"prerequisites":["build-up-sprint-stride-out"]}'::jsonb,
  coaching_execution = '{"movement_description":"15–25 yard build into 10-yard all-out fly zone with full recovery between reps.","setup":["Mark build zone (15–25 yards) and 10-yard fly zone with cones or line tape.","Optional timing gates at fly start and finish.","Confirm full recovery lane for deceleration beyond fly.","Athlete fresh — no prior max fly reps in session."],"execution_steps":["Start with rolling or three-point entry into build zone.","Build to near-max upright speed before fly start cone.","Sprint all-out through the 10-yard fly — max intent, max posture.","Maintain tall body, front-side mechanics, and stiff ankle contacts through fly.","Decelerate under control; rest full 3 minutes before next rep."],"breathing_cues":["Relaxed pre-start breath.","Do not hold breath through fly — stay loose in upper body."],"coach_cues":["Hit the fly hot.","Tall and quick.","No reaching — strike under you.","One perfect rep beats three mediocre ones.","Walk back — full rest."],"athlete_cues":["Build.","Fly.","Max intent.","Stay tall.","Finish clean."],"common_faults":["Starting all-out too early in build zone.","Not reaching fly zone at true upright speed.","Overstriding or sitting back in fly.","Cutting fly short or running extra yards for volume.","Insufficient rest turning reps into conditioning."],"stop_signs":["Fly time drops more than ~3% from best rep.","Hamstring grab or sharp posterior chain pain.","Posture breakdown every fly rep.","Athlete rushing rest to finish session faster."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Build-Up Sprint / Stride-Out","A-Skip","Straight-Leg Bound March"],"pairs_well_after":["Flying 20","Sprint-Float-Sprint","Wicket Runs"],"good_for_sessions":["sprint_output","max_velocity","speed_development"],"avoid_before":["Max-effort acceleration block same session","Heavy posterior chain lifting same day","Prior fly reps to fatigue"],"avoid_after":[],"do_not_use_when":["No build-up stride-out prerequisite met","Hamstring not prepared or prior strain","Insufficient recovery time between reps","No deceleration space after fly zone"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["ALTIS Flying Sprint Series","SimpliFaster Fly 10 Programming","Chris Korfist Max-Velocity Timing"],"internal_notes":["Timing gates optional but preferred for advanced athletes; never at expense of posture."]}'::jsonb,
  updated_at = now()
WHERE slug = 'flying-10';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'flying_sprint',
  order_index = pos.order_index,
  fit_weight = 5,
  freshness_required = TRUE,
  fatigue_sensitivity = 5,
  fatigue_cost = 5,
  technical_complexity = 3,
  impact_level = 4,
  intensity_ceiling = 'max',
  notes = 'High neural cost. Minimum ~3 minutes rest between reps. Not compatible with same-day heavy max lower-body lifting for most athletes.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'flying_sprint' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'flying-10';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'sprints',
  default_sets = 1,
  default_reps = 3,
  default_distance = '15-25 yard build + 10 yard fly',
  default_work_seconds = NULL,
  default_rest_seconds = 180,
  est_seconds_per_set = 35,
  default_rpe_min = 8,
  default_rpe_max = 10,
  session_volume_min = '2 fly 10s with full rest',
  session_volume_max = '3 fly 10s with full rest'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'flying-10';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'flying-10';

-- Flying 20 (flying-20)
UPDATE coaching.exercise SET
  name = 'Flying 20',
  description = 'Athlete builds through 20–30 yards, hits near-max upright speed, then maintains all-out intent through a 20-yard fly zone. Higher hamstring and neural demand than fly 10 — use fewer reps and longer rest.',
  card_summary = 'Longer build into a 20-yard all-out fly zone for athletes who tolerate extended max-velocity exposure — lower rep count, longer rest.',
  coach_language = 'Reserve for athletes with solid fly 10 history. Two high-quality reps with 4+ minutes rest — stop at first velocity or posture drop.',
  athlete_language = 'Long build, long fly — stay tall the whole way and do not fade at the end.',
  movement_family = 'Max-velocity exposure',
  primary_phase_key = 'output',
  phase_subrole = 'max_velocity_exposure',
  primary_order_slot = 'flying_sprint',
  default_sets = 1,
  default_reps = 2,
  default_work_seconds = NULL,
  default_rest_seconds = 240,
  est_seconds_per_set = 40,
  movement_requirements = '{"primary_joint_actions":["hip_extension","knee_extension","ankle_plantarflexion"],"primary_tissues":["hamstrings","glutes","calves"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":4,"prerequisites":["flying-10","build-up-sprint-stride-out"]}'::jsonb,
  coaching_execution = '{"movement_description":"20–30 yard build into 20-yard all-out fly with extended rest between reps.","setup":["Mark build zone (20–30 yards) and 20-yard fly with cones or timing gates.","Confirm athlete has clean fly 10 history this mesocycle.","Extended deceleration lane required beyond 20-yard fly.","Minimum 4 minutes rest between reps."],"execution_steps":["Enter build with controlled acceleration — do not burn early.","Reach near-max upright speed at fly start mark.","Maintain all-out intent through entire 20-yard fly without fading posture.","Keep front-side mechanics and arm drive through the back of the fly.","Decelerate progressively; walk back and rest full 4 minutes."],"breathing_cues":["Stay relaxed through build; avoid breath-holding in fly."],"coach_cues":["Do not fade at yard 15.","Stay tall through the back of the fly.","Two perfect reps — then stop.","Hamstring feel OK?","Full rest — no rushing."],"athlete_cues":["Long build.","Long fly.","No fade.","Tall finish.","Rest fully."],"common_faults":["Assigning fly 20 before fly 10 mastery.","Posture collapse in last 5 yards of fly.","Insufficient build length — entering fly below max speed.","Adding a third rep when first two show velocity drop.","Hamstring overreach from weekly fly 20 volume."],"stop_signs":["Hamstring tightness during or after fly.","Clear deceleration of speed through back half of fly.","Posterior chain cramping.","Athlete reports heavy legs before rep."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Flying 10","Build-Up Sprint / Stride-Out","Straight-Leg Bound March"],"pairs_well_after":["Sprint-Float-Sprint","Wicket Runs"],"good_for_sessions":["sprint_output","max_velocity","speed_development"],"avoid_before":["Fly 10 reps to fatigue in same session","Heavy hamstring loading same day"],"avoid_after":[],"do_not_use_when":["Flying 10 not yet clean","Hamstring history or current tightness","Insufficient rest between reps available","Athlete is in high cumulative sprint load week"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["ALTIS Flying 20 Progressions","SimpliFaster Extended Fly Zone Programming"],"internal_notes":["Prerequisite fly 10 should be documented before prescribing fly 20."]}'::jsonb,
  updated_at = now()
WHERE slug = 'flying-20';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'flying_sprint',
  order_index = pos.order_index,
  fit_weight = 4,
  freshness_required = TRUE,
  fatigue_sensitivity = 5,
  fatigue_cost = 5,
  technical_complexity = 4,
  impact_level = 4,
  intensity_ceiling = 'max',
  notes = 'Higher hamstring demand than fly 10. Limit frequency to 1–2 sessions per week for most athletes.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'flying_sprint' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'flying-20';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'sprints',
  default_sets = 1,
  default_reps = 2,
  default_distance = '20-30 yard build + 20 yard fly',
  default_work_seconds = NULL,
  default_rest_seconds = 240,
  est_seconds_per_set = 40,
  default_rpe_min = 8,
  default_rpe_max = 10,
  session_volume_min = '1 fly 20 with full rest',
  session_volume_max = '2 fly 20s with full rest'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'flying-20';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'flying-20';

-- Sprint-Float-Sprint (sprint-float-sprint)
UPDATE coaching.exercise SET
  name = 'Sprint-Float-Sprint',
  description = 'Over a 30–40 yard rep, athlete sprints max through phase 1 (~10 yards), floats at ~85–90% through phase 2 (~10 yards), then re-accelerates to max through phase 3 (~10 yards). Mark phases with cones or line tape.',
  card_summary = 'Three-phase upright rep — max sprint, relaxed float, max sprint again — teaches speed change and rhythm at high velocity without extra fly volume.',
  coach_language = 'Use to teach re-acceleration at max velocity without adding fly rep count. Two reps with full rest — float is NOT a jog recovery.',
  athlete_language = 'Go hard, float fast but relaxed, then go hard again — stay tall through every phase.',
  movement_family = 'Max-velocity exposure',
  primary_phase_key = 'output',
  phase_subrole = 'max_velocity_exposure',
  primary_order_slot = 'speed_change',
  default_sets = 1,
  default_reps = 2,
  default_work_seconds = NULL,
  default_rest_seconds = 240,
  est_seconds_per_set = 40,
  movement_requirements = '{"primary_joint_actions":["hip_extension","knee_extension","ankle_plantarflexion"],"primary_tissues":["hamstrings","glutes","calves"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":4,"prerequisites":["flying-10","build-up-sprint-stride-out"]}'::jsonb,
  coaching_execution = '{"movement_description":"Three-phase rep — max sprint, fast float (~85–90%), max sprint — over ~30–40 yards.","setup":["Mark three ~10-yard zones with cones or line tape.","Brief athlete on float intent — fast but relaxed, not jogging.","Rolling or fly-in entry optional based on lane length.","Full 4-minute rest between reps."],"execution_steps":["Build or start into phase 1 at max upright intent.","At phase 2 marker, float — reduce effort slightly but keep tall posture and quick feet.","At phase 3 marker, re-attack max speed immediately.","Maintain mechanics through final sprint phase.","Decelerate under control; rest full 4 minutes."],"breathing_cues":["Stay loose in float — do not hold breath through phase changes."],"coach_cues":["Float fast, not slow.","Re-attack now.","Posture stays tall in float.","Phase change is a decision, not a brake.","Two reps — quality only."],"athlete_cues":["Hard.","Float.","Hard again.","Stay tall.","No jog."],"common_faults":["Float becomes a slow jog or walk.","Posture collapse during float phase.","Cannot re-accelerate in phase 3.","Using too many reps — turns into conditioning.","Phase markers too close — no time to express each intent."],"stop_signs":["Phase 3 max speed clearly slower than phase 1.","Hamstring tightness on re-acceleration.","Athlete jogs float every rep despite coaching.","Loss of balance or control at phase transitions."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Flying 10","Build-Up Sprint / Stride-Out","Ins-and-Outs"],"pairs_well_after":["Ins-and-Outs","Wicket Runs"],"good_for_sessions":["sprint_output","max_velocity","speed_development"],"avoid_before":["Prior fly reps to fatigue","Fitness tempo runs same session"],"avoid_after":[],"do_not_use_when":["Cannot perform clean fly 10","Athlete jogs every float despite cues","Hamstring not prepared","Insufficient rest between reps"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["ALTIS Sprint-Float-Sprint","SimpliFaster Speed Change at Max Velocity"],"internal_notes":["Coach float as ~85–90% — visually fast, slightly less aggressive arm drive."]}'::jsonb,
  updated_at = now()
WHERE slug = 'sprint-float-sprint';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'speed_change',
  order_index = pos.order_index,
  fit_weight = 4,
  freshness_required = TRUE,
  fatigue_sensitivity = 5,
  fatigue_cost = 5,
  technical_complexity = 4,
  impact_level = 4,
  intensity_ceiling = 'max',
  notes = 'Speed-change neural drill. Float must stay fast — if athlete jogs, regress dose or intent.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'speed_change' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'sprint-float-sprint';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'sprints',
  default_sets = 1,
  default_reps = 2,
  default_distance = '30-40 yards (3 x ~10 yard phases)',
  default_work_seconds = NULL,
  default_rest_seconds = 240,
  est_seconds_per_set = 40,
  default_rpe_min = 8,
  default_rpe_max = 10,
  session_volume_min = '1 sprint-float-sprint with full rest',
  session_volume_max = '2 sprint-float-sprints with full rest'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'sprint-float-sprint';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'sprint-float-sprint';

-- Ins-and-Outs (ins-and-outs)
UPDATE coaching.exercise SET
  name = 'Ins-and-Outs',
  description = 'Athlete alternates between marked "in" zones (max intent) and "out" zones (fast float ~85–90%) over the length of the rep — typically 2–3 in segments. Cones or line tape define zone boundaries.',
  card_summary = 'Alternating in-zone (max) and out-zone (float) segments over 30–40 yards — rhythmic speed change at upright velocity.',
  coach_language = 'Use for rhythmic speed change — ins are max, outs are fast float. Two reps, full rest. Not a shuttle or conditioning drill.',
  athlete_language = 'When you hit the in zone, go max — in the out zone stay fast and tall but breathe a little.',
  movement_family = 'Max-velocity exposure',
  primary_phase_key = 'output',
  phase_subrole = 'max_velocity_exposure',
  primary_order_slot = 'speed_change',
  default_sets = 1,
  default_reps = 2,
  default_work_seconds = NULL,
  default_rest_seconds = 240,
  est_seconds_per_set = 40,
  movement_requirements = '{"primary_joint_actions":["hip_extension","knee_extension","ankle_plantarflexion"],"primary_tissues":["hamstrings","glutes","calves"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":4,"prerequisites":["sprint-float-sprint","flying-10"]}'::jsonb,
  coaching_execution = '{"movement_description":"Alternating max \"in\" zones and fast-float \"out\" zones over 30–40 yards.","setup":["Mark 2–3 in zones (~10 yards) and out zones (~5–10 yards) with cones or tape.","Define verbal or visual cue for in/out transitions.","Fly-in or build entry to reach upright speed before first in zone.","4-minute rest between reps."],"execution_steps":["Build to upright speed approaching first in zone.","Sprint max through each in zone — full intent, tall posture.","Float fast but relaxed through each out zone — no jogging.","Re-attack max immediately at next in zone marker.","Decelerate after final in zone; rest fully before next rep."],"breathing_cues":["Slightly easier breathing in out zones — never stop moving fast."],"coach_cues":["In — go!","Out — stay fast.","In — max again.","No jog in the outs.","Two reps, then done."],"athlete_cues":["In hard.","Out fast.","In hard.","Stay tall.","Finish clean."],"common_faults":["Out zones become slow jogs.","Missing in zone markers — starting max too early or late.","Too many segments turning rep into conditioning.","Posture drop in later in zones.","Using ins-and-outs before fly 10 quality exists."],"stop_signs":["Later in zones clearly slower than first.","Athlete cannot maintain float faster than jog pace.","Hamstring symptoms on re-acceleration.","Dizziness or loss of control at transitions."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Sprint-Float-Sprint","Flying 10","Build-Up Sprint / Stride-Out"],"pairs_well_after":["Wicket Runs","Curved Sprint / Arc Run"],"good_for_sessions":["sprint_output","max_velocity","speed_development"],"avoid_before":["Sprint-float-sprint to fatigue in same session","Team relay or shuttle conditioning"],"avoid_after":[],"do_not_use_when":["Sprint-float-sprint prerequisite not met","Athlete jogs all out zones","Hamstring not prepared","Insufficient lane length for marked zones"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["ALTIS Ins-and-Outs","Tony Holler Speed Change Drills","SimpliFaster In-Zone Out-Zone Sprinting"],"internal_notes":["Visually distinct cone colors for in vs out zones help youth athletes."]}'::jsonb,
  updated_at = now()
WHERE slug = 'ins-and-outs';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'speed_change',
  order_index = pos.order_index,
  fit_weight = 4,
  freshness_required = TRUE,
  fatigue_sensitivity = 5,
  fatigue_cost = 5,
  technical_complexity = 4,
  impact_level = 4,
  intensity_ceiling = 'max',
  notes = 'Segmented speed-change drill. Alternate with sprint-float-sprint across weeks — avoid both heavy in same session.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'speed_change' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'ins-and-outs';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'sprints',
  default_sets = 1,
  default_reps = 2,
  default_distance = '30-40 yards (alternating in/out zones)',
  default_work_seconds = NULL,
  default_rest_seconds = 240,
  est_seconds_per_set = 40,
  default_rpe_min = 8,
  default_rpe_max = 10,
  session_volume_min = '1 ins-and-outs rep with full rest',
  session_volume_max = '2 ins-and-outs reps with full rest'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'ins-and-outs';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'ins-and-outs';

-- Wicket Runs (wicket-runs)
UPDATE coaching.exercise SET
  name = 'Wicket Runs',
  description = 'Athlete sprints through a lane of wickets (mini gates or cones defining stride targets) spaced for the athlete''s height and speed level. Focus is upright posture, quick cadence, and foot strike under the body — not hurdling or bounding.',
  card_summary = 'Upright sprint through spaced wickets (mini gates) that constrain stride length and encourage optimal cadence at near-max velocity.',
  coach_language = 'Use wickets to organize stride frequency at high speed. Three runs with 2-minute rest — spacing must match athlete; do not chase wicket contact at all costs.',
  athlete_language = 'Sprint tall through the gates — quick feet, strike under you, and let the wickets guide your rhythm.',
  movement_family = 'Max-velocity exposure',
  primary_phase_key = 'output',
  phase_subrole = 'max_velocity_exposure',
  primary_order_slot = 'wicket_rhythm',
  default_sets = 1,
  default_reps = 3,
  default_work_seconds = NULL,
  default_rest_seconds = 120,
  est_seconds_per_set = 30,
  movement_requirements = '{"primary_joint_actions":["hip_flexion","hip_extension","ankle_plantarflexion"],"primary_tissues":["calves","hip_flexors","hamstrings"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":4,"prerequisites":["build-up-sprint-stride-out","a-skip"]}'::jsonb,
  coaching_execution = '{"movement_description":"Near-max upright sprint through wicket lane — cadence and foot strike guided by gate spacing.","setup":["Set wickets or cone gates for athlete height/speed (often ~1.5–1.8m spacing to start — adjust individually).","10–20 yard build before wicket zone optional.","6–10 wickets typical for one run.","2-minute rest between runs."],"execution_steps":["Build to near-max speed entering wicket lane.","Sprint upright through wickets — strike under body, not reaching for gates.","Maintain tall posture and quick cadence; wickets guide rhythm.","Do not stutter or hop to hit every gate — adjust spacing if needed.","Decelerate after final wicket; walk back and rest."],"breathing_cues":["Stay relaxed through upper body while legs turn over quickly."],"coach_cues":["Strike under you.","Let wickets come to you.","Tall and quick.","Fix spacing, not the athlete''s jump.","Three clean runs."],"athlete_cues":["Quick feet.","Tall.","Through the gates.","Rhythm.","Stay smooth."],"common_faults":["Wicket spacing too wide — overstriding returns.","Spacing too tight — stutter steps or hopping.","Treating wickets like hurdles to clear.","Submax effort through wickets — should be near-max when prescribed.","Too many runs when cadence degrades."],"stop_signs":["Stutter-stepping every run despite spacing adjustment.","Ankle or shin pain from awkward contacts.","Athlete cannot maintain upright posture through lane.","Cadence slows run to run."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Flying 10","Build-Up Sprint / Stride-Out","A-Skip"],"pairs_well_after":["Mini-Hurdle Sprint Rhythm","Flying 10","Curved Sprint / Arc Run"],"good_for_sessions":["sprint_output","max_velocity","speed_development"],"avoid_before":["Ankling to shin fatigue","Mini-hurdle rhythm to failure same session"],"avoid_after":[],"do_not_use_when":["No wickets or suitable cone gates available","Spacing cannot be adjusted for athlete","Athlete stutter-steps every attempt","Acute shin or ankle pain"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Chris Korfist Wicket Drills","ALTIS Wicket Spacing Progressions","SimpliFaster Wicket Run Coaching"],"internal_notes":["Film first run to set spacing — generic charts often wrong for youth athletes."]}'::jsonb,
  updated_at = now()
WHERE slug = 'wicket-runs';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'wicket_rhythm',
  order_index = pos.order_index,
  fit_weight = 4,
  freshness_required = TRUE,
  fatigue_sensitivity = 4,
  fatigue_cost = 4,
  technical_complexity = 4,
  impact_level = 4,
  intensity_ceiling = 'high',
  notes = 'Rhythm constraint drill. Spacing is individual — film and adjust rather than forcing generic distances.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'wicket_rhythm' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'wicket-runs';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'runs',
  default_sets = 1,
  default_reps = 3,
  default_distance = 'wicket lane ~10-20 yards',
  default_work_seconds = NULL,
  default_rest_seconds = 120,
  est_seconds_per_set = 30,
  default_rpe_min = 7,
  default_rpe_max = 9,
  session_volume_min = '2 wicket runs with adjusted spacing',
  session_volume_max = '3 wicket runs with full rest'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'wicket-runs';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'wicket-runs';

-- Mini-Hurdle Sprint Rhythm (mini-hurdle-sprint-rhythm)
UPDATE coaching.exercise SET
  name = 'Mini-Hurdle Sprint Rhythm',
  description = 'Athlete sprints through a lane of low mini-hurdles (typically 6–12 inches) spaced for quick turnover at near-max upright speed. Hurdles are run through, not jumped — emphasis on rhythm, dorsiflexion, and foot strike under the hip.',
  card_summary = 'Low mini-hurdle sprint rhythm drill that enforces quick cadence and upright foot strike at high speed — distinct from wicket gate spacing.',
  coach_language = 'Use mini-hurdles for cadence and dorsiflexion at speed — not plyometric hurdle hops. Three runs, 90-second rest; lower hurdles than you think.',
  athlete_language = 'Run through the hurdles quick and tall — toe up, light feet, don''t jump them.',
  movement_family = 'Max-velocity exposure',
  primary_phase_key = 'output',
  phase_subrole = 'max_velocity_exposure',
  primary_order_slot = 'wicket_rhythm',
  default_sets = 1,
  default_reps = 3,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 25,
  movement_requirements = '{"primary_joint_actions":["hip_flexion","ankle_dorsiflexion","ankle_plantarflexion"],"primary_tissues":["calves","hip_flexors","feet"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":4,"prerequisites":["wicket-runs","a-skip"]}'::jsonb,
  coaching_execution = '{"movement_description":"Near-max sprint through low mini-hurdle lane — run through, do not jump.","setup":["Set 6–8 low mini-hurdles (6–12 inches) with spacing for athlete cadence.","Optional 10-yard build before hurdle lane.","Confirm hurdles will tip if clipped — safety first.","90-second rest between runs."],"execution_steps":["Build to near-max upright speed entering hurdle lane.","Run through hurdles with quick cadence — toes up, light contacts.","Do not jump or bound over hurdles — stride through them.","Maintain tall posture and arm action through lane.","Decelerate after final hurdle; rest fully."],"breathing_cues":["Stay loose — quick feet should not mean held breath."],"coach_cues":["Run through, not over.","Toe up.","Quick and tall.","Lower the hurdle before widening spacing.","Three runs — stop if you start jumping."],"athlete_cues":["Quick feet.","Through not over.","Toe up.","Tall.","Light steps."],"common_faults":["Hurdles set too high — athlete jumps.","Spacing too wide — overstriding returns.","Spacing too tight — stutter or shuffle.","Using plyometric hop intent instead of sprint rhythm.","Too many runs when form becomes hop-dominant."],"stop_signs":["Athlete jumps every hurdle.","Shin or ankle pain from clipping hurdles.","Stutter-stepping through lane.","Cadence slows significantly run to run."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Wicket Runs","A-Skip","Ankling / Dribble March","Flying 10"],"pairs_well_after":["Flying 10","Curved Sprint / Arc Run"],"good_for_sessions":["sprint_output","max_velocity","speed_development"],"avoid_before":["Hurdle hop plyometric series same session","Shin-fatiguing ankling volume"],"avoid_after":[],"do_not_use_when":["No low mini-hurdles available","Athlete jumps hurdles instead of running through","Acute shin or ankle pain","Hurdles fixed too high to tip safely"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Chris Parno Mini-Hurdle Sprint Rhythm","SimpliFaster Low Hurdle Cadence Drills","ALTIS Rhythm Hurdle Series"],"internal_notes":["Keep hurdles lower than plyometric hurdle hops — different slot and intent."]}'::jsonb,
  updated_at = now()
WHERE slug = 'mini-hurdle-sprint-rhythm';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'wicket_rhythm',
  order_index = pos.order_index,
  fit_weight = 4,
  freshness_required = TRUE,
  fatigue_sensitivity = 4,
  fatigue_cost = 4,
  technical_complexity = 4,
  impact_level = 4,
  intensity_ceiling = 'high',
  notes = 'Rhythm drill with low hurdles — distinct from elastic hurdle hop series in plyometric rudiments.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'wicket_rhythm' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'mini-hurdle-sprint-rhythm';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'runs',
  default_sets = 1,
  default_reps = 3,
  default_distance = 'mini-hurdle lane ~10-15 yards',
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 25,
  default_rpe_min = 7,
  default_rpe_max = 9,
  session_volume_min = '2 mini-hurdle runs',
  session_volume_max = '3 mini-hurdle runs with full rest'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'mini-hurdle-sprint-rhythm';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'mini-hurdle-sprint-rhythm';

-- Curved Sprint / Arc Run (curved-sprint-arc-run)
UPDATE coaching.exercise SET
  name = 'Curved Sprint / Arc Run',
  description = 'Athlete sprints at high intent along a marked curved path (arc run) — typically on a grass field line, cone arc, or lane tape curve with a radius appropriate for the athlete. Maintains upright posture while managing centripetal force and arm action on the curve.',
  card_summary = 'High-speed sprint on a gentle arc or curved path — exposes max velocity with lateral force and posture demands distinct from straight-line fly work.',
  coach_language = 'Use for curved max-speed exposure after straight-line work. Three reps with 90-second rest — gentle radius for beginners; do not curve at max speed on tight circles early.',
  athlete_language = 'Sprint the arc tall — lean into the curve with your whole body, quick feet, and stay smooth.',
  movement_family = 'Max-velocity exposure',
  primary_phase_key = 'output',
  phase_subrole = 'max_velocity_exposure',
  primary_order_slot = 'curved_sprint',
  default_sets = 1,
  default_reps = 3,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 30,
  movement_requirements = '{"primary_joint_actions":["hip_extension","ankle_plantarflexion","hip_adduction"],"primary_tissues":["glutes","calves","hip_stabilizers"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":4,"prerequisites":["flying-10","build-up-sprint-stride-out"]}'::jsonb,
  coaching_execution = '{"movement_description":"High-intent sprint along marked gentle arc — upright posture with appropriate curve lean.","setup":["Mark arc with cones or line tape on grass or track curve.","Choose wide radius for beginners (e.g. 15–20+ meters); tighten only with experience.","Define arc length (~20–30 yards along curve).","90-second rest between reps; alternate directions if prescribed."],"execution_steps":["Build or fly-in to high speed entering arc.","Lean into curve with whole body — not just at ankles.","Maintain quick cadence and foot strike under hip on curve.","Keep eyes up and posture tall through arc exit.","Decelerate safely after arc; rest fully."],"breathing_cues":["Stay relaxed through shoulders on curve — tension slows cadence."],"coach_cues":["Lean the body, not just the ankles.","Quick feet on the curve.","Wide arc first.","Tall through exit.","Three reps each direction max."],"athlete_cues":["Smooth arc.","Lean in.","Quick feet.","Tall exit.","Stay controlled."],"common_faults":["Radius too tight — stutter or brake every step.","Leaning only at ankles instead of whole body.","Slowing to jog through curve.","Using curved sprint before straight fly quality exists.","Too many reps on same-direction curve loading inside leg."],"stop_signs":["Ankle or knee pain on inside/outside leg of curve.","Loss of control or stumbling on arc.","Athlete cannot maintain speed through curve.","Hip or groin symptoms on repeated same-direction reps."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Flying 10","Wicket Runs","Build-Up Sprint / Stride-Out"],"pairs_well_after":["Curved Run to Cut","Reactive Gate Sprint"],"good_for_sessions":["sprint_output","max_velocity","speed_development"],"avoid_before":["Tight COD reps to fatigue before arc sprint","Straight fly reps to exhaustion same session"],"avoid_after":[],"do_not_use_when":["Straight-line fly 10 not yet clean","No space for safe wide arc","Ankle, knee, or groin pain on lateral loading","Wet or uneven surface on curve"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["ALTIS Curved Sprint Progressions","SimpliFaster Arc Run Coaching","Feed the Cats Curve Sprinting"],"internal_notes":["Alternate curve direction across reps to manage lateral asymmetry."]}'::jsonb,
  updated_at = now()
WHERE slug = 'curved-sprint-arc-run';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'curved_sprint',
  order_index = pos.order_index,
  fit_weight = 4,
  freshness_required = TRUE,
  fatigue_sensitivity = 4,
  fatigue_cost = 4,
  technical_complexity = 4,
  impact_level = 4,
  intensity_ceiling = 'high',
  notes = 'Curved max-speed exposure. Alternate turn direction across reps to balance lateral load.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'curved_sprint' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'curved-sprint-arc-run';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'sprints',
  default_sets = 1,
  default_reps = 3,
  default_distance = '20-30 yards along arc',
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 30,
  default_rpe_min = 7,
  default_rpe_max = 9,
  session_volume_min = '2 curved sprints per direction',
  session_volume_max = '3 curved sprints with full rest'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'curved-sprint-arc-run';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'curved-sprint-arc-run';

-- Refresh weighted taxonomy tags for max-velocity cards
DELETE FROM coaching.exercise_tag t
USING coaching.exercise e
WHERE t.exercise_id = e.id
  AND e.slug IN ('build-up-sprint-stride-out', 'flying-10', 'flying-20', 'sprint-float-sprint', 'ins-and-outs', 'wicket-runs', 'mini-hurdle-sprint-rhythm', 'curved-sprint-arc-run')
  AND t.facet_type IN ('tenet', 'methodology', 'physiology', 'pattern', 'equipment', 'body_region');

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'tenet', f.id, v.weight
FROM (VALUES
  ('build-up-sprint-stride-out', 'speed', 5),
  ('build-up-sprint-stride-out', 'explosiveness', 4),
  ('build-up-sprint-stride-out', 'coordination', 4),
  ('build-up-sprint-stride-out', 'body_control', 3),
  ('flying-10', 'speed', 5),
  ('flying-10', 'explosiveness', 5),
  ('flying-10', 'coordination', 3),
  ('flying-10', 'body_control', 3),
  ('flying-20', 'speed', 5),
  ('flying-20', 'explosiveness', 5),
  ('flying-20', 'coordination', 3),
  ('flying-20', 'body_control', 4),
  ('sprint-float-sprint', 'speed', 5),
  ('sprint-float-sprint', 'coordination', 5),
  ('sprint-float-sprint', 'explosiveness', 4),
  ('sprint-float-sprint', 'agility', 2),
  ('ins-and-outs', 'speed', 5),
  ('ins-and-outs', 'coordination', 5),
  ('ins-and-outs', 'explosiveness', 4),
  ('ins-and-outs', 'agility', 2),
  ('wicket-runs', 'speed', 5),
  ('wicket-runs', 'coordination', 5),
  ('wicket-runs', 'body_control', 4),
  ('wicket-runs', 'explosiveness', 3),
  ('mini-hurdle-sprint-rhythm', 'speed', 5),
  ('mini-hurdle-sprint-rhythm', 'coordination', 5),
  ('mini-hurdle-sprint-rhythm', 'body_control', 4),
  ('mini-hurdle-sprint-rhythm', 'explosiveness', 3),
  ('curved-sprint-arc-run', 'speed', 5),
  ('curved-sprint-arc-run', 'coordination', 5),
  ('curved-sprint-arc-run', 'agility', 4),
  ('curved-sprint-arc-run', 'body_control', 4)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.tenet f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'methodology', f.id, v.weight
FROM (VALUES
  ('build-up-sprint-stride-out', 'neural', 5),
  ('build-up-sprint-stride-out', 'plyometrics', 3),
  ('build-up-sprint-stride-out', 'core_body_control', 2),
  ('flying-10', 'neural', 5),
  ('flying-10', 'plyometrics', 4),
  ('flying-20', 'neural', 5),
  ('flying-20', 'plyometrics', 4),
  ('sprint-float-sprint', 'neural', 5),
  ('sprint-float-sprint', 'plyometrics', 3),
  ('ins-and-outs', 'neural', 5),
  ('ins-and-outs', 'plyometrics', 3),
  ('wicket-runs', 'neural', 5),
  ('wicket-runs', 'plyometrics', 3),
  ('wicket-runs', 'core_body_control', 2),
  ('mini-hurdle-sprint-rhythm', 'neural', 5),
  ('mini-hurdle-sprint-rhythm', 'plyometrics', 2),
  ('mini-hurdle-sprint-rhythm', 'core_body_control', 2),
  ('curved-sprint-arc-run', 'neural', 5),
  ('curved-sprint-arc-run', 'plyometrics', 3),
  ('curved-sprint-arc-run', 'balance_stability', 2)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.methodology f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'physiology', f.id, v.weight
FROM (VALUES
  ('build-up-sprint-stride-out', 'neural_output_readiness', 5),
  ('build-up-sprint-stride-out', 'ssc_stiffness', 4),
  ('build-up-sprint-stride-out', 'perception_action_skill', 3),
  ('flying-10', 'neural_output_readiness', 5),
  ('flying-10', 'ssc_stiffness', 4),
  ('flying-10', 'perception_action_skill', 2),
  ('flying-20', 'neural_output_readiness', 5),
  ('flying-20', 'ssc_stiffness', 4),
  ('flying-20', 'perception_action_skill', 2),
  ('sprint-float-sprint', 'neural_output_readiness', 5),
  ('sprint-float-sprint', 'perception_action_skill', 4),
  ('sprint-float-sprint', 'ssc_stiffness', 3),
  ('ins-and-outs', 'neural_output_readiness', 5),
  ('ins-and-outs', 'perception_action_skill', 4),
  ('ins-and-outs', 'ssc_stiffness', 3),
  ('wicket-runs', 'neural_output_readiness', 5),
  ('wicket-runs', 'perception_action_skill', 4),
  ('wicket-runs', 'ssc_stiffness', 4),
  ('mini-hurdle-sprint-rhythm', 'neural_output_readiness', 5),
  ('mini-hurdle-sprint-rhythm', 'perception_action_skill', 4),
  ('mini-hurdle-sprint-rhythm', 'ssc_stiffness', 4),
  ('curved-sprint-arc-run', 'neural_output_readiness', 5),
  ('curved-sprint-arc-run', 'perception_action_skill', 4),
  ('curved-sprint-arc-run', 'ssc_stiffness', 3)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.physiological_emphasis f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'pattern', f.id, v.weight
FROM (VALUES
  ('build-up-sprint-stride-out', 'locomote', 5),
  ('build-up-sprint-stride-out', 'land', 2),
  ('flying-10', 'locomote', 5),
  ('flying-10', 'land', 2),
  ('flying-20', 'locomote', 5),
  ('flying-20', 'land', 2),
  ('sprint-float-sprint', 'locomote', 5),
  ('sprint-float-sprint', 'land', 2),
  ('ins-and-outs', 'locomote', 5),
  ('ins-and-outs', 'land', 2),
  ('wicket-runs', 'locomote', 5),
  ('wicket-runs', 'land', 3),
  ('mini-hurdle-sprint-rhythm', 'locomote', 5),
  ('mini-hurdle-sprint-rhythm', 'land', 3),
  ('curved-sprint-arc-run', 'locomote', 5),
  ('curved-sprint-arc-run', 'land', 3)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.movement_pattern f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'equipment', f.id, v.weight
FROM (VALUES
  ('build-up-sprint-stride-out', 'cones', 4),
  ('build-up-sprint-stride-out', 'none', 3),
  ('build-up-sprint-stride-out', 'line_tape', 2),
  ('flying-10', 'cones', 4),
  ('flying-10', 'timing_gates', 5),
  ('flying-10', 'line_tape', 2),
  ('flying-20', 'cones', 4),
  ('flying-20', 'timing_gates', 5),
  ('flying-20', 'line_tape', 2),
  ('sprint-float-sprint', 'cones', 5),
  ('sprint-float-sprint', 'line_tape', 3),
  ('sprint-float-sprint', 'none', 2),
  ('ins-and-outs', 'cones', 5),
  ('ins-and-outs', 'line_tape', 4),
  ('ins-and-outs', 'none', 2),
  ('wicket-runs', 'wickets', 5),
  ('wicket-runs', 'cones', 3),
  ('wicket-runs', 'none', 1),
  ('mini-hurdle-sprint-rhythm', 'low_hurdles', 5),
  ('mini-hurdle-sprint-rhythm', 'cones', 2),
  ('mini-hurdle-sprint-rhythm', 'none', 1),
  ('curved-sprint-arc-run', 'cones', 5),
  ('curved-sprint-arc-run', 'line_tape', 3),
  ('curved-sprint-arc-run', 'none', 2)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.equipment f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'body_region', f.id, v.weight
FROM (VALUES
  ('build-up-sprint-stride-out', 'full_body', 5),
  ('build-up-sprint-stride-out', 'hamstring', 4),
  ('build-up-sprint-stride-out', 'hip', 4),
  ('build-up-sprint-stride-out', 'ankle', 4),
  ('build-up-sprint-stride-out', 'core', 3),
  ('flying-10', 'full_body', 5),
  ('flying-10', 'hamstring', 5),
  ('flying-10', 'hip', 4),
  ('flying-10', 'ankle', 4),
  ('flying-10', 'core', 3),
  ('flying-20', 'full_body', 5),
  ('flying-20', 'hamstring', 5),
  ('flying-20', 'hip', 4),
  ('flying-20', 'ankle', 4),
  ('flying-20', 'core', 3),
  ('sprint-float-sprint', 'full_body', 5),
  ('sprint-float-sprint', 'hamstring', 4),
  ('sprint-float-sprint', 'hip', 4),
  ('sprint-float-sprint', 'ankle', 4),
  ('sprint-float-sprint', 'core', 3),
  ('ins-and-outs', 'full_body', 5),
  ('ins-and-outs', 'hamstring', 4),
  ('ins-and-outs', 'hip', 4),
  ('ins-and-outs', 'ankle', 4),
  ('ins-and-outs', 'core', 3),
  ('wicket-runs', 'full_body', 5),
  ('wicket-runs', 'hip', 4),
  ('wicket-runs', 'ankle', 5),
  ('wicket-runs', 'hamstring', 3),
  ('wicket-runs', 'core', 3),
  ('mini-hurdle-sprint-rhythm', 'full_body', 5),
  ('mini-hurdle-sprint-rhythm', 'ankle', 5),
  ('mini-hurdle-sprint-rhythm', 'hip', 4),
  ('mini-hurdle-sprint-rhythm', 'knee', 3),
  ('mini-hurdle-sprint-rhythm', 'hamstring', 3),
  ('curved-sprint-arc-run', 'full_body', 5),
  ('curved-sprint-arc-run', 'hip', 4),
  ('curved-sprint-arc-run', 'ankle', 4),
  ('curved-sprint-arc-run', 'core', 4),
  ('curved-sprint-arc-run', 'hamstring', 3)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.body_region f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'youth_beginner' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('build-up-sprint-stride-out', '20-yard submax stride-outs only; coach-led decel.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Submax fly with 15-yard build; no timing pressure.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Do not use — regress to build-up stride-out or submax fly 10.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Two-phase sprint-float at submax only; shorten zones.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'One in/out cycle at submax; coach at each cone.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Submax run-throughs with wide spacing; coach adjusts gates live.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', 'Walk-through then submax run; fewer hurdles.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Submax arc jog first; widen radius before adding speed.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_beginner';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'youth_beginner', 'youth beginner', 'baseline', v.guidance,
  CASE WHEN 'youth_beginner' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('build-up-sprint-stride-out', '20-yard submax stride-outs only; coach-led decel.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Submax fly with 15-yard build; no timing pressure.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Do not use — regress to build-up stride-out or submax fly 10.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Two-phase sprint-float at submax only; shorten zones.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'One in/out cycle at submax; coach at each cone.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Submax run-throughs with wide spacing; coach adjusts gates live.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', 'Walk-through then submax run; fewer hurdles.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Submax arc jog first; widen radius before adding speed.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_beginner'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'youth_intermediate' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('build-up-sprint-stride-out', 'Add one rep or slightly longer fly zone when mechanics stay crisp; still full rest.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Add one rep or slightly longer fly zone when mechanics stay crisp; still full rest.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Fly 15 submax only if fly 10 is established.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Submax all phases before adding max intent in sprint phases.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'Add one rep or slightly longer fly zone when mechanics stay crisp; still full rest.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Reduce wicket count; prioritize clean contacts over speed.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', '6-inch hurdles max; coach at lane side.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Submax curved run before high intent.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_intermediate';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'youth_intermediate', 'youth intermediate', 'baseline', v.guidance,
  CASE WHEN 'youth_intermediate' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('build-up-sprint-stride-out', 'Add one rep or slightly longer fly zone when mechanics stay crisp; still full rest.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Add one rep or slightly longer fly zone when mechanics stay crisp; still full rest.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Fly 15 submax only if fly 10 is established.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Submax all phases before adding max intent in sprint phases.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'Add one rep or slightly longer fly zone when mechanics stay crisp; still full rest.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Reduce wicket count; prioritize clean contacts over speed.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', '6-inch hurdles max; coach at lane side.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Submax curved run before high intent.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_intermediate'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'teen' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('build-up-sprint-stride-out', 'Can progress toward true max intent when hamstring prep and Skill mechanics are solid.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Can use timing gates once build-up stride-outs are consistent.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Fly 20 submax before adding max intent.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Can progress toward true max intent when hamstring prep and Skill mechanics are solid.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'Two in zones submax before max intent.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Can progress toward true max intent when hamstring prep and Skill mechanics are solid.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', 'Can progress toward true max intent when hamstring prep and Skill mechanics are solid.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Can progress toward true max intent when hamstring prep and Skill mechanics are solid.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'teen';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'teen', 'teen', 'baseline', v.guidance,
  CASE WHEN 'teen' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('build-up-sprint-stride-out', 'Can progress toward true max intent when hamstring prep and Skill mechanics are solid.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Can use timing gates once build-up stride-outs are consistent.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Fly 20 submax before adding max intent.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Can progress toward true max intent when hamstring prep and Skill mechanics are solid.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'Two in zones submax before max intent.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Can progress toward true max intent when hamstring prep and Skill mechanics are solid.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', 'Can progress toward true max intent when hamstring prep and Skill mechanics are solid.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Can progress toward true max intent when hamstring prep and Skill mechanics are solid.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'teen'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'adult_beginner' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('build-up-sprint-stride-out', 'Start at 20 yards submax before extending to 30–40 yards.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Start with build-up stride-outs only; shorten fly zones and keep RPE submax until decel is controlled.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Start with build-up stride-outs only; shorten fly zones and keep RPE submax until decel is controlled.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Use submax sprint phases until fly 10 is established.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'Start with build-up stride-outs only; shorten fly zones and keep RPE submax until decel is controlled.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Submax only until build-up stride-out is clean.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', 'Start with build-up stride-outs only; shorten fly zones and keep RPE submax until decel is controlled.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Start with build-up stride-outs only; shorten fly zones and keep RPE submax until decel is controlled.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_beginner';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'adult_beginner', 'adult beginner', 'baseline', v.guidance,
  CASE WHEN 'adult_beginner' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('build-up-sprint-stride-out', 'Start at 20 yards submax before extending to 30–40 yards.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Start with build-up stride-outs only; shorten fly zones and keep RPE submax until decel is controlled.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Start with build-up stride-outs only; shorten fly zones and keep RPE submax until decel is controlled.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Use submax sprint phases until fly 10 is established.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'Start with build-up stride-outs only; shorten fly zones and keep RPE submax until decel is controlled.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Submax only until build-up stride-out is clean.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', 'Start with build-up stride-outs only; shorten fly zones and keep RPE submax until decel is controlled.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Start with build-up stride-outs only; shorten fly zones and keep RPE submax until decel is controlled.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_beginner'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'adult_advanced' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('build-up-sprint-stride-out', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Track best fly time; end set when velocity drops.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_advanced';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'adult_advanced', 'adult advanced', 'baseline', v.guidance,
  CASE WHEN 'adult_advanced' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('build-up-sprint-stride-out', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Track best fly time; end set when velocity drops.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Use timing feedback sparingly; stop set when velocity drops more than ~3% or posture breaks.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_advanced'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'older_adult' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('build-up-sprint-stride-out', 'Reduce distance and max intent; prioritize safe deceleration and straight-line exposure over fly zones.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Reduce distance and max intent; prioritize safe deceleration and straight-line exposure over fly zones.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Generally avoid; prefer build-up stride-out or short fly 10 submax.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Reduce distance and max intent; prioritize safe deceleration and straight-line exposure over fly zones.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'Generally prefer sprint-float-sprint at submax or skip.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Reduce distance and max intent; prioritize safe deceleration and straight-line exposure over fly zones.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', 'Reduce distance and max intent; prioritize safe deceleration and straight-line exposure over fly zones.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Wide radius submax only; skip tight curves.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'older_adult';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'older_adult', 'older adult', 'baseline', v.guidance,
  CASE WHEN 'older_adult' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('build-up-sprint-stride-out', 'Reduce distance and max intent; prioritize safe deceleration and straight-line exposure over fly zones.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Reduce distance and max intent; prioritize safe deceleration and straight-line exposure over fly zones.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Generally avoid; prefer build-up stride-out or short fly 10 submax.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Reduce distance and max intent; prioritize safe deceleration and straight-line exposure over fly zones.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'Generally prefer sprint-float-sprint at submax or skip.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Reduce distance and max intent; prioritize safe deceleration and straight-line exposure over fly zones.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', 'Reduce distance and max intent; prioritize safe deceleration and straight-line exposure over fly zones.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Wide radius submax only; skip tight curves.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'older_adult'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'pregnancy_postpartum' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('build-up-sprint-stride-out', 'Submax stride-outs at moderate intent only if cleared; skip true max effort.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Generally avoid true max-velocity sprinting unless cleared and symptom-free. Prefer build-up stride-outs at moderate intent with extra recovery.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Generally avoid true max-velocity sprinting unless cleared and symptom-free. Prefer build-up stride-outs at moderate intent with extra recovery.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Generally avoid true max-velocity sprinting unless cleared and symptom-free. Prefer build-up stride-outs at moderate intent with extra recovery.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'Generally avoid true max-velocity sprinting unless cleared and symptom-free. Prefer build-up stride-outs at moderate intent with extra recovery.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Generally avoid true max-velocity sprinting unless cleared and symptom-free. Prefer build-up stride-outs at moderate intent with extra recovery.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', 'Generally avoid high-speed hurdle rhythm unless cleared; prefer wicket runs at submax.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Avoid high-speed curved sprinting unless cleared; prefer straight submax work.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'pregnancy_postpartum';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'pregnancy_postpartum', 'pregnancy postpartum', 'baseline', v.guidance,
  CASE WHEN 'pregnancy_postpartum' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('build-up-sprint-stride-out', 'Submax stride-outs at moderate intent only if cleared; skip true max effort.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-10', 'Generally avoid true max-velocity sprinting unless cleared and symptom-free. Prefer build-up stride-outs at moderate intent with extra recovery.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('flying-20', 'Generally avoid true max-velocity sprinting unless cleared and symptom-free. Prefer build-up stride-outs at moderate intent with extra recovery.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('sprint-float-sprint', 'Generally avoid true max-velocity sprinting unless cleared and symptom-free. Prefer build-up stride-outs at moderate intent with extra recovery.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('ins-and-outs', 'Generally avoid true max-velocity sprinting unless cleared and symptom-free. Prefer build-up stride-outs at moderate intent with extra recovery.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('wicket-runs', 'Generally avoid true max-velocity sprinting unless cleared and symptom-free. Prefer build-up stride-outs at moderate intent with extra recovery.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('mini-hurdle-sprint-rhythm', 'Generally avoid high-speed hurdle rhythm unless cleared; prefer wicket runs at submax.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.'),
  ('curved-sprint-arc-run', 'Avoid high-speed curved sprinting unless cleared; prefer straight submax work.', 'No default male/female dosage split. Scale by sprint training age, max-velocity tolerance, hamstring readiness, symptoms, and prior session load.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'pregnancy_postpartum'
);

-- Why-layer education
INSERT INTO coaching.education_content (
  entity_type, entity_key, entity_id, title, short_summary,
  what_it_is, why_it_works, why_it_matters, why_it_goes_here,
  programming_guidance, common_misuse, scaling_guidance
)
SELECT
  'exercise', e.slug, e.id, e.name, e.card_summary,
  e.description,
  v.why_works,
  'Develops tagged tenets and physiological qualities for athletic development.',
  v.why_here,
  v.best_placement,
  v.misuse,
  v.scale_guidance
FROM (VALUES
  ('build-up-sprint-stride-out', 'Build-up stride-outs let the athlete find max upright velocity through a controlled acceleration curve rather than jumping straight to fly zones. Coaches can observe posture rise, foot strike, and arm action while neural demand stays manageable relative to shorter all-out fly reps.', 'Belongs in sprint_exposure (321) — first upright speed expression in Max-Velocity Exposure before flying sprints or rhythm constraints.', 'First max-velocity exposure drill in the block after Skill prep and optional short acceleration work; before flying sprints or speed-change reps.', 'Max-velocity exposure belongs in Output while the athlete is fresh — express upright speed with full recovery between reps. Do not use as a conditioning finisher, repeated tempo runs, warm-up jog, or volume work when speed or posture drops. Quality and neural freshness beat rep count. Do not turn into 10×100 tempo runs or a warm-up lap. One to three crisp reps with full rest.', 'Regress to shorter distance or submax stride-outs; progress to flying 10 once build-up mechanics and decel are consistently clean.'),
  ('flying-10', 'The fly zone isolates upright max velocity without the acceleration noise of the first steps. A 10-yard fly is long enough to express top speed yet short enough to preserve quality and allow full recovery between reps.', 'Belongs in flying_sprint (322) — standard fly-in max-velocity rep after sprint exposure prep.', 'After build-up stride-out when athlete can reach upright posture before the fly zone; early in max-velocity block.', 'Max-velocity exposure belongs in Output while the athlete is fresh — express upright speed with full recovery between reps. Do not use as a conditioning finisher, repeated tempo runs, warm-up jog, or volume work when speed or posture drops. Quality and neural freshness beat rep count. Do not stack 8–10 fly reps or use as a finisher. Two to three reps with 3+ minutes rest.', 'Regress to build-up stride-out or shorten build zone; add timing gates only when mechanics are consistent.'),
  ('flying-20', 'A 20-yard fly extends time at true max velocity, challenging hamstring tolerance and upright posture maintenance longer than fly 10. Useful for field-sport athletes who must sustain top speed briefly — but only when fly 10 quality is already established.', 'Belongs in flying_sprint (322) — advanced fly exposure after fly 10, not a beginner max-velocity entry.', 'After flying 10 when athlete shows clean upright mechanics and needs longer speed endurance at max velocity — not before fly 10 mastery.', 'Max-velocity exposure belongs in Output while the athlete is fresh — express upright speed with full recovery between reps. Do not use as a conditioning finisher, repeated tempo runs, warm-up jog, or volume work when speed or posture drops. Quality and neural freshness beat rep count. Do not assign fly 20 before fly 10 is clean. Two reps max for most athletes — not a volume progression.', 'Regress to flying 10; shorten fly zone to 15 yards for intermediate athletes before full 20-yard fly.'),
  ('sprint-float-sprint', 'Sprint-float-sprint challenges the athlete to downshift speed slightly without losing posture, then re-attack max velocity — a field-sport pattern. It adds neural complexity beyond steady fly reps while keeping total high-speed distance modest.', 'Belongs in speed_change (323) — rhythm and re-acceleration at max velocity, not steady fly exposure.', 'After fly 10 when athlete can hold upright speed and needs speed-change exposure; mid max-velocity block.', 'Max-velocity exposure belongs in Output while the athlete is fresh — express upright speed with full recovery between reps. Do not use as a conditioning finisher, repeated tempo runs, warm-up jog, or volume work when speed or posture drops. Quality and neural freshness beat rep count. Float is not a slow jog or walk — maintain fast upright mechanics. Do not use as a conditioning pyramid.', 'Regress to build-up stride-out; shorten phases or use submax intent in float before full sprint-float-sprint.'),
  ('ins-and-outs', 'Ins-and-outs repeat the speed-change demand across multiple segments, training the athlete to toggle max intent on cue while maintaining upright mechanics in float segments — useful for sports with variable sprint demands.', 'Belongs in speed_change (323) — segmented rhythm alternative to sprint-float-sprint.', 'After sprint-float-sprint or fly 10 when athlete needs segmented speed-change rhythm; alternate with sprint-float-sprint across mesocycle.', 'Max-velocity exposure belongs in Output while the athlete is fresh — express upright speed with full recovery between reps. Do not use as a conditioning finisher, repeated tempo runs, warm-up jog, or volume work when speed or posture drops. Quality and neural freshness beat rep count. Out zones are not recovery jogs. Do not add extra segments for volume or use as a team conditioning relay.', 'Start with two in/out cycles at submax; shorten zones before adding a third in segment.'),
  ('wicket-runs', 'Wickets provide external rhythm cues that encourage optimal stride length and cadence at high velocity without coach constantly shouting "quicker feet." Athletes who overstride at max speed often self-correct when wicket spacing demands shorter, faster contacts.', 'Belongs in wicket_rhythm (324) — upright rhythm constraint at max velocity using wicket spacing.', 'After fly 10 or build-up when athlete needs rhythm constraint at high speed; pairs well before or after straight fly work.', 'Max-velocity exposure belongs in Output while the athlete is fresh — express upright speed with full recovery between reps. Do not use as a conditioning finisher, repeated tempo runs, warm-up jog, or volume work when speed or posture drops. Quality and neural freshness beat rep count. Wickets are not mini-hurdles to jump over. Do not use wrong spacing that forces bounding or stutter steps.', 'Adjust wicket spacing to athlete height and speed; regress to submax run-throughs before max intent.'),
  ('mini-hurdle-sprint-rhythm', 'Mini-hurdles add a visible rhythm target that encourages shorter, quicker strides and dorsiflexed foot strike at high speed. The low height keeps the drill sprint-specific rather than becoming a bounding or hop series.', 'Belongs in wicket_rhythm (324) — hurdle-based rhythm constraint complement to wicket runs.', 'After wicket runs or A-skip when athlete needs low hurdle rhythm constraint; alternate with wicket runs across mesocycle.', 'Max-velocity exposure belongs in Output while the athlete is fresh — express upright speed with full recovery between reps. Do not use as a conditioning finisher, repeated tempo runs, warm-up jog, or volume work when speed or posture drops. Quality and neural freshness beat rep count. Hurdles too high or too far apart turn this into bounding or plyometrics. Do not use as a hop conditioning circuit.', 'Lower hurdle height and tighten spacing before adding speed; regress to wicket runs if athlete jumps hurdles.'),
  ('curved-sprint-arc-run', 'Curved sprinting adds lateral force and whole-body lean demands that straight fly reps do not address — relevant for field sports with arc running patterns. Gentle arcs at high speed train posture and foot strike under centripetal load.', 'Belongs in curved_sprint (325) — arc max-velocity exposure after straight-line fly and rhythm work.', 'Late in max-velocity block when straight-line fly quality is established; sport-specific curved running exposure.', 'Max-velocity exposure belongs in Output while the athlete is fresh — express upright speed with full recovery between reps. Do not use as a conditioning finisher, repeated tempo runs, warm-up jog, or volume work when speed or posture drops. Quality and neural freshness beat rep count. Do not use tight circle sprints as a conditioning finisher. Wide radius, high intent, low rep count.', 'Widen arc radius or reduce speed before tightening curve; regress to straight fly 10 if posture breaks on arc.')
) AS v(slug, why_works, why_here, best_placement, misuse, scale_guidance)
JOIN coaching.exercise e ON e.slug = v.slug
ON CONFLICT (entity_type, entity_key, entity_id) DO UPDATE SET
  title = EXCLUDED.title,
  short_summary = EXCLUDED.short_summary,
  what_it_is = EXCLUDED.what_it_is,
  why_it_works = EXCLUDED.why_it_works,
  why_it_goes_here = EXCLUDED.why_it_goes_here,
  programming_guidance = EXCLUDED.programming_guidance,
  common_misuse = EXCLUDED.common_misuse,
  scaling_guidance = EXCLUDED.scaling_guidance,
  updated_at = now();

-- Max-velocity cluster validation education
INSERT INTO coaching.education_content (
  entity_type, entity_key, entity_id, title, short_summary,
  what_it_is, why_it_matters, programming_guidance, common_misuse
)
VALUES (
  'validation_rule',
  'output_max_velocity_readiness',
  NULL,
  'Max-Velocity Exposure without pre-fatigue',
  'Max-velocity sprinting requires freshness, full rest, short reps, and crisp mechanics — not conditioning circuits, finishers, or warm-up jogs.',
  'Output max-velocity cards express upright sprint speed through build-ups, flying sprints, speed-change drills, wicket rhythm, and curved sprinting.',
  'High-speed sprinting loads hamstrings, calves, Achilles, and neural systems heavily. Poor placement, short rest, or excessive volume turns Output into speed endurance and raises injury risk.',
  'Use Build-Up Sprint first for beginners, Flying 10 before Flying 20, 2+ minute rest on fly sprints, stop when speed or posture drops, and place max-velocity work before Capacity and Fitness.',
  'Do not program max-velocity sprints after conditioning, with short rest, as session finishers, or at volumes that drop speed — regress dose or change phase intent.'
)
ON CONFLICT (entity_type, entity_key, entity_id) DO UPDATE SET
  title = EXCLUDED.title,
  short_summary = EXCLUDED.short_summary,
  what_it_is = EXCLUDED.what_it_is,
  why_it_matters = EXCLUDED.why_it_matters,
  programming_guidance = EXCLUDED.programming_guidance,
  common_misuse = EXCLUDED.common_misuse,
  updated_at = now();
