-- Output phase Reactive Agility & Tumbling Output cards 46–50 (rich card v2 content).
-- IDEMPOTENT. Generated by scripts/generate-119-output-reactive-tumbling-cards.mjs
-- UPDATE-only on slugs from migration 112. Fine slots seeded in migration 111.

-- Equipment taxonomy for reactive/tumbling Output cluster
INSERT INTO coaching.equipment (key, name, sort_order) VALUES
  ('spring_floor', 'Spring Floor', 23)
ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order;

-- Reactive Gate Sprint (reactive-gate-sprint)
UPDATE coaching.exercise SET
  name = 'Reactive Gate Sprint',
  description = 'Set two to four cone gates. Athlete starts in ready stance, reads coach point/color/verbal/hand cue, takes a clean first step, accelerates through the correct gate, and decelerates safely.',
  card_summary = 'High-intent reactive acceleration drill where the athlete responds to a visual, verbal, or spatial cue and sprints through the correct gate.',
  coach_language = 'Use as the simplest high-intensity reactive sprint drill. The athlete must read the cue, choose the gate, take a clean first step, and accelerate.',
  athlete_language = 'Watch the cue, choose the gate, explode through it, and slow down safely.',
  movement_family = 'High-intensity reactive agility & tumbling output',
  primary_phase_key = 'output',
  phase_subrole = 'reactive_agility_tumbling_output',
  primary_order_slot = 'reactive_sprint',
  default_sets = 2,
  default_reps = 3,
  default_work_seconds = NULL,
  default_rest_seconds = 60,
  est_seconds_per_set = 90,
  movement_requirements = '{"primary_joint_actions":["hip_extension","knee_extension","ankle_plantarflexion"],"primary_tissues":["glutes","hamstrings","calves","hip_flexors"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":2,"prerequisites":["coach-point-and-go","gate-reaction-drill","two-point-start-walk-in","sprint-to-stick-deceleration"],"setup_metadata":["reactive_cue_type","gate_count","approach_distance","requires_deceleration_zone","requires_run_out_zone","no_crossing_paths"],"setup_requirements":["safe_sprint_lane","clear_deceleration_zone","no_crossing_paths"],"reactive_output_profile":{"cue_type":"visual | verbal | spatial","complexity":"moderate","exit_type":"sprint_exit","requires_external_cue":true}}'::jsonb,
  coaching_execution = '{"movement_description":"Athlete reads coach cue, identifies correct gate, accelerates through it, and decelerates safely after the gate.","setup":["Create two to four cone gates.","Athlete starts at a central point.","Coach stands in clear view.","Define cue system: point, color, verbal call, hand raise, or coach movement.","Each gate must have a clear run-out and deceleration zone."],"execution_steps":["Athlete sets in ready stance.","Coach gives cue.","Athlete identifies the correct gate.","Athlete takes a clean first step.","Athlete accelerates through the gate.","Athlete decelerates safely after the gate.","Full reset before the next rep."],"breathing_cues":["Stay ready — exhale into the first step without guessing early."],"coach_cues":["Read first.","Do not guess.","First step clean.","Explode through the gate.","Run through, then slow down safely."],"athlete_cues":["See it.","Choose it.","Go.","Through the gate."],"common_faults":["Athlete guesses before cue.","False step delays acceleration.","First step crosses midline.","Gate layout creates crossing paths.","Athlete stops at the gate instead of running through.","Rest is too short and sprint quality drops."],"stop_signs":["Collision risk.","Athlete chooses wrong gate repeatedly.","Knee or ankle pain on first step.","Athlete cannot decelerate after the gate.","Cue complexity overwhelms the athlete."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Partner Chase Acceleration","Mirror Shuffle to Sprint Exit","Ball Drop Sprint Catch","Sport-specific reactive sprinting"],"pairs_well_after":["Gate Reaction Drill","Two-Point Start Walk-In","Falling Start Position Hold","Coach Point-and-Go Drill"],"good_for_sessions":["reactive_output","tumbling_output","agility_output","perception_action"],"avoid_before":["Reactive gate sprinting if athlete cannot decelerate","Full-speed competition if cue recognition is poor","Multiple-athlete layout with crossing paths"],"avoid_after":[],"do_not_use_when":["No safe run-out","No clear cue system","Athlete guesses repeatedly","Athlete cannot stop safely","Group layout creates collision risk"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["NSCA reaction-drill guidance","TrainHeroic reactive-agility cueing resources"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'reactive-gate-sprint';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'reactive_sprint',
  order_index = pos.order_index,
  fit_weight = 5,
  freshness_required = TRUE,
  fatigue_sensitivity = 5,
  fatigue_cost = 4,
  technical_complexity = 5,
  impact_level = 2,
  intensity_ceiling = 'max',
  notes = 'High-intensity reactive sprint. If route is pre-planned, classify as acceleration or COD instead of reactive agility. Supervision: recommended.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'reactive_sprint' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'reactive-gate-sprint';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'attempts',
  default_sets = 2,
  default_reps = 3,
  default_distance = '5-10 yards',
  default_work_seconds = NULL,
  default_rest_seconds = 60,
  est_seconds_per_set = 90,
  default_rpe_min = 7,
  default_rpe_max = 9,
  session_volume_min = '3 reps',
  session_volume_max = '10 reps'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'reactive-gate-sprint';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'reactive-gate-sprint';

-- Mirror Shuffle to Sprint Exit (mirror-shuffle-to-sprint-exit)
UPDATE coaching.exercise SET
  name = 'Mirror Shuffle to Sprint Exit',
  description = 'Two athletes face each other in a short lateral lane. One leads, one mirrors. On coach cue, partner movement, or gate opening, the mirror athlete plants and sprints through an exit gate.',
  card_summary = 'Partner-based reactive agility drill where the athlete mirrors lateral movement, then reacts to a cue or opening and sprints out.',
  coach_language = 'Use after mirror shuffle and lateral shuffle mechanics are clean. This Output version adds a high-intent sprint exit.',
  athlete_language = 'Mirror your partner, stay in your base, then explode through the exit when the cue appears.',
  movement_family = 'High-intensity reactive agility & tumbling output',
  primary_phase_key = 'output',
  phase_subrole = 'reactive_agility_tumbling_output',
  primary_order_slot = 'reactive_agility_output',
  default_sets = 2,
  default_reps = NULL,
  default_work_seconds = 8,
  default_rest_seconds = 45,
  est_seconds_per_set = 75,
  movement_requirements = '{"primary_joint_actions":["hip_abduction","hip_adduction","knee_flexion","ankle_inversion"],"primary_tissues":["glutes","hip_abductors","calves","core"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":3,"prerequisites":["mirror-shuffle-drill","lateral-shuffle-walkthrough","lateral-bound-to-decel-stick"],"setup_metadata":["mirror_lane_width","exit_gate_count","requires_deceleration_zone","no_contact_rule","partner_pairing"],"setup_requirements":["safe_sprint_lane","clear_deceleration_zone","no_crossing_paths"],"reactive_output_profile":{"cue_type":"partner | spatial","complexity":"high","exit_type":"reactive_exit","requires_external_cue":true}}'::jsonb,
  coaching_execution = '{"movement_description":"Leader moves laterally; mirror tracks hips/center mass, then plants and sprints through exit gate on cue.","setup":["Create a 3–5 yard lateral mirror lane.","Create one or two sprint exit gates.","Pair athletes by size, speed, maturity, and control.","Leader and mirror face each other.","No-contact rule is mandatory."],"execution_steps":["Leader moves laterally inside lane.","Mirror athlete tracks the leader.","Athlete maintains base width and posture.","Coach gives exit cue or leader opens exit.","Mirror athlete plants and sprints through the exit gate.","Athlete decelerates safely."],"breathing_cues":["Stay low and breathe steady during mirror — explode on exit."],"coach_cues":["Watch the hips.","Stay in your base.","Do not click your feet.","React to the exit.","Sprint through the gate."],"athlete_cues":["Mirror.","Stay low.","Read.","Exit fast."],"common_faults":["Athlete watches feet instead of hips/center mass.","Feet come together during shuffle.","Leader moves too fast for follower level.","Follower guesses exit.","Athlete crosses feet before sprint exit.","Sprint exit creates collision path."],"stop_signs":["Collision risk.","Knee pain during lateral plant.","Ankle roll risk.","Athlete cannot maintain shuffle base.","Game becomes chaotic or conditioning-based."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Reactive Gate Sprint","Partner Chase Acceleration","Sport-specific defensive agility","Controlled small-sided movement games"],"pairs_well_after":["Mirror Shuffle Drill","Lateral Shuffle Mechanics Walkthrough","Lateral Bound to Decel Stick","Single-Leg Balance Reach Clock"],"good_for_sessions":["reactive_output","tumbling_output","agility_output","perception_action"],"avoid_before":["Sprint exit if mirror base collapses","Competitive chase if spacing is poor","High-intensity COD if lateral plant is unstable"],"avoid_after":[],"do_not_use_when":["No clear lanes","Poor lateral mechanics","Unsafe pairing","Athlete cannot decelerate after exit","Contact behavior appears"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Overtime Athletes mirror drill partner guidance"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'mirror-shuffle-to-sprint-exit';

UPDATE coaching.exercise_phase_profile p SET
  role = 'conditional',
  order_slot = 'reactive_agility_output',
  order_index = pos.order_index,
  fit_weight = 5,
  freshness_required = TRUE,
  fatigue_sensitivity = 5,
  fatigue_cost = 5,
  technical_complexity = 5,
  impact_level = 3,
  intensity_ceiling = 'max',
  notes = 'Very high complexity. Requires lateral mechanics, mirror skill, safe lane spacing, and sprint-exit control. Supervision: required_for_groups.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'reactive_agility_output' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'mirror-shuffle-to-sprint-exit';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'attempts',
  default_sets = 2,
  default_reps = NULL,
  default_distance = NULL,
  default_work_seconds = 8,
  default_rest_seconds = 45,
  est_seconds_per_set = 75,
  default_rpe_min = 6,
  default_rpe_max = 9,
  session_volume_min = '2 rounds per role',
  session_volume_max = '6 rounds per role'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'mirror-shuffle-to-sprint-exit';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'mirror-shuffle-to-sprint-exit';

-- Ball Drop Sprint Catch (ball-drop-sprint-catch)
UPDATE coaching.exercise SET
  name = 'Ball Drop Sprint Catch',
  description = 'Coach or partner holds a tennis ball ahead. Athlete starts several yards away. Coach drops without countdown. Athlete reacts, accelerates, catches within bounce rule, and decelerates safely — no diving.',
  card_summary = 'High-intent object-reaction acceleration drill where the athlete reacts to a dropped ball, sprints, tracks, and catches it before the bounce limit.',
  coach_language = 'Use after the athlete can start, accelerate, track, and stop safely. No diving or reckless catches.',
  athlete_language = 'Watch the ball. When it drops, explode, catch it, and slow down safely.',
  movement_family = 'High-intensity reactive agility & tumbling output',
  primary_phase_key = 'output',
  phase_subrole = 'reactive_agility_tumbling_output',
  primary_order_slot = 'object_reaction_output',
  default_sets = 2,
  default_reps = 3,
  default_work_seconds = NULL,
  default_rest_seconds = 45,
  est_seconds_per_set = 75,
  movement_requirements = '{"primary_joint_actions":["hip_extension","shoulder_flexion","knee_extension"],"primary_tissues":["glutes","hamstrings","calves","core"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":2,"prerequisites":["ball-drop-reaction","two-point-start-to-5-10-yard-sprint","sprint-to-stick-deceleration"],"setup_metadata":["drop_distance","bounce_limit","ball_type","requires_deceleration_zone","reactive_cue_type"],"setup_requirements":["safe_sprint_lane","clear_deceleration_zone"],"reactive_output_profile":{"cue_type":"object","complexity":"moderate","exit_type":"stick","requires_external_cue":true}}'::jsonb,
  coaching_execution = '{"movement_description":"Watch ball, react to drop, sprint to catch within bounce rule, decelerate safely.","setup":["Use tennis ball or reaction ball.","Coach stands 3–8 yards away depending on athlete level.","Athlete starts in two-point, athletic stance, or sport stance.","Clear sprint lane and deceleration area.","Define bounce limit: before first bounce, before second bounce, or after one bounce."],"execution_steps":["Athlete watches the ball.","Coach drops ball without warning.","Athlete reacts to the drop.","Athlete accelerates toward the ball.","Athlete catches the ball within the bounce rule.","Athlete decelerates safely and resets."],"breathing_cues":["Eyes on ball — exhale into catch without lunging forward."],"coach_cues":["Watch the ball.","React to the drop.","First step fast.","Catch under control.","No diving."],"athlete_cues":["See drop.","Go.","Catch.","Stop safe."],"common_faults":["Athlete guesses before the drop.","Coach drops too far for level.","Athlete dives or lunges recklessly.","Athlete catches but cannot stop.","Eyes leave the ball early.","Reps become repeated sprint conditioning."],"stop_signs":["Athlete dives.","Athlete falls.","Knee or ankle pain on start or stop.","No safe lane.","Athlete cannot decelerate after catch."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Reactive Gate Sprint","Partner Chase Acceleration","Object tracking games","Sport-specific reaction sprinting"],"pairs_well_after":["Ball Drop Reaction Drill","Two-Point Start","Falling Start","Arm Action Drill"],"good_for_sessions":["reactive_output","tumbling_output","agility_output","perception_action"],"avoid_before":["Max reps if athlete starts diving","Crowded group setup","Reactive drills if stop control is poor"],"avoid_after":[],"do_not_use_when":["No safe sprint lane","Athlete dives or falls","Poor deceleration","Knee/ankle pain","Coach cannot control spacing"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["NSCA quickness/reaction training ball-drop examples"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'ball-drop-sprint-catch';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'object_reaction_output',
  order_index = pos.order_index,
  fit_weight = 5,
  freshness_required = TRUE,
  fatigue_sensitivity = 5,
  fatigue_cost = 4,
  technical_complexity = 5,
  impact_level = 2,
  intensity_ceiling = 'max',
  notes = 'High-intent object reaction. Distance, bounce limit, and ball type must match athlete level. Supervision: recommended.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'object_reaction_output' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'ball-drop-sprint-catch';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'attempts',
  default_sets = 2,
  default_reps = 3,
  default_distance = NULL,
  default_work_seconds = NULL,
  default_rest_seconds = 45,
  est_seconds_per_set = 75,
  default_rpe_min = 6,
  default_rpe_max = 9,
  session_volume_min = '3 drops',
  session_volume_max = '10 drops'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'ball-drop-sprint-catch';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'ball-drop-sprint-catch';

-- Power Hurdle to Cartwheel / Round-Off Entry (power-hurdle-to-cartwheel-round-off-entry)
UPDATE coaching.exercise SET
  name = 'Power Hurdle to Cartwheel / Round-Off Entry',
  description = 'Athlete performs a powerful hurdle into cartwheel or round-off entry with controlled speed, front-foot under knee, fast arm path, accurate hand contact, and clean turnover.',
  card_summary = 'Explosive tumbling-entry drill that trains hurdle power, weight transfer, front-foot placement, arm path, and entry into cartwheel or round-off mechanics.',
  coach_language = 'Use only after hurdle-to-lunge, cartwheel, and round-off entry mechanics are technically sound. This Output version adds speed and power.',
  athlete_language = 'Power through the hurdle, keep your front foot under you, reach fast, and turn over clean.',
  movement_family = 'High-intensity reactive agility & tumbling output',
  primary_phase_key = 'output',
  phase_subrole = 'reactive_agility_tumbling_output',
  primary_order_slot = 'tumbling_takeoff_output',
  default_sets = 2,
  default_reps = 3,
  default_work_seconds = NULL,
  default_rest_seconds = 60,
  est_seconds_per_set = 90,
  movement_requirements = '{"primary_joint_actions":["shoulder_flexion","hip_flexion","wrist_extension"],"primary_tissues":["shoulders","wrists","core","hip_flexors"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":3,"prerequisites":["hurdle-step-lunge","cartwheel","cartwheel-step-over","cartwheel-finish-lunge","round-off"],"setup_metadata":["tumbling_surface","coach_supervision_required","entry_type","hurdle_target"],"setup_requirements":["mat_or_tumbling_surface","coach_supervision_for_tumbling"],"reactive_output_profile":{"cue_type":"none","complexity":"high","exit_type":"reaccelerate","requires_external_cue":false}}'::jsonb,
  coaching_execution = '{"movement_description":"Power hurdle with front foot under knee, fast reach, accurate hands, cartwheel or round-off entry turnover.","setup":["Use tumbling mat or spring floor.","Confirm prerequisite cartwheel / round-off entry skill.","Mark hurdle and lunge target if needed.","Ensure clear tumbling lane.","Coach supervision required."],"execution_steps":["Athlete starts with controlled approach or step-in.","Perform power hurdle.","Land front foot under knee with body balanced.","Reach arms quickly into entry.","Place hands accurately.","Complete cartwheel or round-off entry progression.","Finish with controlled landing or rebound task as assigned."],"breathing_cues":["Stay tight through hurdle — do not dive forward."],"coach_cues":["Power through the hurdle.","Front foot under knee.","Arms by ears.","Reach short and fast.","Do not dive forward.","Turn over clean."],"athlete_cues":["Hurdle.","Foot under.","Reach.","Fast hands.","Turn over."],"common_faults":["Hurdle too high and floaty.","Front foot reaches too far in front.","Athlete dives forward.","Arms drop before entry.","Hands are placed too far away.","Round-off speed exceeds control."],"stop_signs":["Wrist pain.","Shoulder collapse.","Head/neck risk during entry.","Athlete cannot maintain hand placement.","Landing or rebound is uncontrolled.","Fear or hesitation appears."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Round-Off Rebound / Snap-Down to Stick","Tumbling Output block","Round-off connection prep"],"pairs_well_after":["Hurdle Step to Lunge Shape","Cartwheel Hand-Placement Line Drill","Cartwheel Step-Over","Handstand Line","Round-Off Snap-Down Shape Drill"],"good_for_sessions":["reactive_output","tumbling_output","agility_output","perception_action"],"avoid_before":["Full-power round-off if hurdle is inefficient","Back handspring connection if snap-down or rebound is poor","Tumbling under fatigue"],"avoid_after":[],"do_not_use_when":["No qualified coach","No mat or safe tumbling lane","Cartwheel / round-off prerequisites are not mastered","Wrist or shoulder pain","Athlete dives or loses body control"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Best Darn Gymnastics hurdle guidance","HowToGymnastics round-off entry mechanics"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'power-hurdle-to-cartwheel-round-off-entry';

UPDATE coaching.exercise_phase_profile p SET
  role = 'conditional',
  order_slot = 'tumbling_takeoff_output',
  order_index = pos.order_index,
  fit_weight = 4,
  freshness_required = TRUE,
  fatigue_sensitivity = 5,
  fatigue_cost = 4,
  technical_complexity = 5,
  impact_level = 3,
  intensity_ceiling = 'max',
  notes = 'Explosive tumbling entry. Requires mastered Skill-phase hurdle, cartwheel, hand placement, and round-off prerequisites. Supervision: required.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'tumbling_takeoff_output' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'power-hurdle-to-cartwheel-round-off-entry';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'attempts',
  default_sets = 2,
  default_reps = 3,
  default_distance = NULL,
  default_work_seconds = NULL,
  default_rest_seconds = 60,
  est_seconds_per_set = 90,
  default_rpe_min = 6,
  default_rpe_max = 9,
  session_volume_min = '3 attempts',
  session_volume_max = '10 attempts'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'power-hurdle-to-cartwheel-round-off-entry';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'power-hurdle-to-cartwheel-round-off-entry';

-- Round-Off Rebound / Snap-Down to Stick (round-off-rebound-snap-down-to-stick)
UPDATE coaching.exercise SET
  name = 'Round-Off Rebound / Snap-Down to Stick',
  description = 'Athlete performs round-off or progression emphasizing fast leg closure, strong shoulder push, powerful snap-down, rebound, and controlled stick landing.',
  card_summary = 'Explosive round-off output drill that trains snap-down speed, shoulder block, leg closure, rebound power, and controlled stick landing.',
  coach_language = 'Use only after round-off foundations are mastered. This is the Output expression of round-off snap-down and rebound mechanics.',
  athlete_language = 'Snap your feet together fast, push through your shoulders, rebound tall, and stick strong.',
  movement_family = 'High-intensity reactive agility & tumbling output',
  primary_phase_key = 'output',
  phase_subrole = 'reactive_agility_tumbling_output',
  primary_order_slot = 'tumbling_rebound_output',
  default_sets = 2,
  default_reps = 3,
  default_work_seconds = NULL,
  default_rest_seconds = 75,
  est_seconds_per_set = 105,
  movement_requirements = '{"primary_joint_actions":["shoulder_extension","wrist_extension","hip_extension"],"primary_tissues":["shoulders","wrists","core","calves"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":4,"prerequisites":["cartwheel","cartwheel-step-over","cartwheel-finish-lunge","round-off","power-hurdle-to-cartwheel-round-off-entry","snap-down-to-rebound"],"setup_metadata":["tumbling_surface","coach_supervision_required","rebound_task","stick_required"],"setup_requirements":["mat_or_tumbling_surface","coach_supervision_for_tumbling"],"reactive_output_profile":{"cue_type":"none","complexity":"high","exit_type":"stick","requires_external_cue":false}}'::jsonb,
  coaching_execution = '{"movement_description":"Round-off with fast snap-down, strong block, rebound tall or snap-down to stick per assignment.","setup":["Use mat, spring floor, or appropriate tumbling surface.","Confirm prerequisite cartwheel, handstand line, round-off entry, and snap-down skill.","Clear tumbling lane.","Coach supervision required.","Define whether athlete rebounds, sticks, or rebounds then sticks."],"execution_steps":["Enter with controlled hurdle or step-in.","Place hands accurately.","Push strongly through shoulders.","Snap legs together quickly.","Drive heels down aggressively.","Rebound tall or snap-down to stick based on assignment.","Control final landing."],"breathing_cues":["Stay hollow through snap — rebound tall without piking down."],"coach_cues":["Fast hands.","Strong block.","Snap feet together.","Hollow body.","Rebound tall.","Stick strong."],"athlete_cues":["Block.","Snap.","Rebound.","Stick."],"common_faults":["Slow snap-down.","Bent arms on hand contact.","Feet land apart.","Dead landing with no rebound.","Piking down instead of hollow snap.","Rebound travels uncontrolled.","Athlete connects skills before rebound quality is ready."],"stop_signs":["Wrist pain.","Shoulder collapse.","Neck/head risk.","Landing is uncontrolled.","Knee or ankle pain.","Fear, hesitation, or loss of body tension.","Prerequisite skills are not mastered."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Advanced tumbling connection prep","Round-off rebound assessment","Tumbling Output block"],"pairs_well_after":["Round-Off Snap-Down Shape Drill","Handstand Snap-Down","Cartwheel Finish Lunge Drill","Power Hurdle to Round-Off Entry","Snap-Down to Rebound"],"good_for_sessions":["reactive_output","tumbling_output","agility_output","perception_action"],"avoid_before":["Back handspring connection if rebound is weak or uncontrolled","Tumbling under fatigue","High-volume round-off reps if wrist/shoulder fatigue appears"],"avoid_after":[],"do_not_use_when":["No qualified coach","No safe tumbling surface","Round-off prerequisites not mastered","Wrist or shoulder pain","Poor snap-down or uncontrolled rebound","Landing cannot be stuck"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["HowToGymnastics round-off snap-down and rebound guidance"],"internal_notes":[]}'::jsonb,
  updated_at = now()
WHERE slug = 'round-off-rebound-snap-down-to-stick';

UPDATE coaching.exercise_phase_profile p SET
  role = 'conditional',
  order_slot = 'tumbling_rebound_output',
  order_index = pos.order_index,
  fit_weight = 5,
  freshness_required = TRUE,
  fatigue_sensitivity = 5,
  fatigue_cost = 5,
  technical_complexity = 5,
  impact_level = 4,
  intensity_ceiling = 'max',
  notes = 'Highest tumbling-output card in this phase. Requires round-off prerequisites and landing/rebound control. Supervision: required.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'output'
JOIN coaching.phase_order_slot pos ON pos.key = 'tumbling_rebound_output' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'round-off-rebound-snap-down-to-stick';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'attempts',
  default_sets = 2,
  default_reps = 3,
  default_distance = NULL,
  default_work_seconds = NULL,
  default_rest_seconds = 75,
  est_seconds_per_set = 105,
  default_rpe_min = 7,
  default_rpe_max = 10,
  session_volume_min = '2 attempts',
  session_volume_max = '8 attempts'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'round-off-rebound-snap-down-to-stick';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'round-off-rebound-snap-down-to-stick';

-- Refresh weighted taxonomy tags for reactive / tumbling Output cards
DELETE FROM coaching.exercise_tag t
USING coaching.exercise e
WHERE t.exercise_id = e.id
  AND e.slug IN ('reactive-gate-sprint', 'mirror-shuffle-to-sprint-exit', 'ball-drop-sprint-catch', 'power-hurdle-to-cartwheel-round-off-entry', 'round-off-rebound-snap-down-to-stick')
  AND t.facet_type IN ('tenet', 'methodology', 'physiology', 'pattern', 'equipment', 'body_region');

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'tenet', f.id, v.weight
FROM (VALUES
  ('reactive-gate-sprint', 'speed', 5),
  ('reactive-gate-sprint', 'agility', 5),
  ('reactive-gate-sprint', 'explosiveness', 4),
  ('reactive-gate-sprint', 'coordination', 5),
  ('reactive-gate-sprint', 'body_control', 4),
  ('reactive-gate-sprint', 'balance', 3),
  ('mirror-shuffle-to-sprint-exit', 'agility', 5),
  ('mirror-shuffle-to-sprint-exit', 'speed', 4),
  ('mirror-shuffle-to-sprint-exit', 'explosiveness', 4),
  ('mirror-shuffle-to-sprint-exit', 'coordination', 5),
  ('mirror-shuffle-to-sprint-exit', 'balance', 4),
  ('mirror-shuffle-to-sprint-exit', 'body_control', 5),
  ('ball-drop-sprint-catch', 'speed', 5),
  ('ball-drop-sprint-catch', 'agility', 4),
  ('ball-drop-sprint-catch', 'explosiveness', 5),
  ('ball-drop-sprint-catch', 'coordination', 5),
  ('ball-drop-sprint-catch', 'body_control', 4),
  ('ball-drop-sprint-catch', 'balance', 3),
  ('power-hurdle-to-cartwheel-round-off-entry', 'explosiveness', 5),
  ('power-hurdle-to-cartwheel-round-off-entry', 'coordination', 5),
  ('power-hurdle-to-cartwheel-round-off-entry', 'body_control', 5),
  ('power-hurdle-to-cartwheel-round-off-entry', 'balance', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'speed', 3),
  ('power-hurdle-to-cartwheel-round-off-entry', 'agility', 3),
  ('round-off-rebound-snap-down-to-stick', 'explosiveness', 5),
  ('round-off-rebound-snap-down-to-stick', 'coordination', 5),
  ('round-off-rebound-snap-down-to-stick', 'body_control', 5),
  ('round-off-rebound-snap-down-to-stick', 'balance', 4),
  ('round-off-rebound-snap-down-to-stick', 'speed', 3),
  ('round-off-rebound-snap-down-to-stick', 'strength', 2)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.tenet f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'methodology', f.id, v.weight
FROM (VALUES
  ('reactive-gate-sprint', 'neural', 5),
  ('reactive-gate-sprint', 'balance_stability', 3),
  ('reactive-gate-sprint', 'core_body_control', 2),
  ('mirror-shuffle-to-sprint-exit', 'neural', 5),
  ('mirror-shuffle-to-sprint-exit', 'balance_stability', 4),
  ('mirror-shuffle-to-sprint-exit', 'core_body_control', 3),
  ('mirror-shuffle-to-sprint-exit', 'plyometrics', 1),
  ('ball-drop-sprint-catch', 'neural', 5),
  ('ball-drop-sprint-catch', 'balance_stability', 2),
  ('ball-drop-sprint-catch', 'core_body_control', 2),
  ('power-hurdle-to-cartwheel-round-off-entry', 'plyometrics', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'neural', 5),
  ('power-hurdle-to-cartwheel-round-off-entry', 'core_body_control', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'balance_stability', 4),
  ('round-off-rebound-snap-down-to-stick', 'plyometrics', 5),
  ('round-off-rebound-snap-down-to-stick', 'neural', 5),
  ('round-off-rebound-snap-down-to-stick', 'core_body_control', 5),
  ('round-off-rebound-snap-down-to-stick', 'balance_stability', 4)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.methodology f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'physiology', f.id, v.weight
FROM (VALUES
  ('reactive-gate-sprint', 'perception_action_skill', 5),
  ('reactive-gate-sprint', 'neural_output_readiness', 5),
  ('reactive-gate-sprint', 'control_stability', 4),
  ('reactive-gate-sprint', 'ssc_stiffness', 2),
  ('mirror-shuffle-to-sprint-exit', 'perception_action_skill', 5),
  ('mirror-shuffle-to-sprint-exit', 'neural_output_readiness', 5),
  ('mirror-shuffle-to-sprint-exit', 'control_stability', 5),
  ('mirror-shuffle-to-sprint-exit', 'ssc_stiffness', 2),
  ('ball-drop-sprint-catch', 'perception_action_skill', 5),
  ('ball-drop-sprint-catch', 'neural_output_readiness', 5),
  ('ball-drop-sprint-catch', 'control_stability', 3),
  ('ball-drop-sprint-catch', 'ssc_stiffness', 2),
  ('power-hurdle-to-cartwheel-round-off-entry', 'neural_output_readiness', 5),
  ('power-hurdle-to-cartwheel-round-off-entry', 'perception_action_skill', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'control_stability', 5),
  ('power-hurdle-to-cartwheel-round-off-entry', 'ssc_stiffness', 3),
  ('round-off-rebound-snap-down-to-stick', 'ssc_stiffness', 5),
  ('round-off-rebound-snap-down-to-stick', 'neural_output_readiness', 5),
  ('round-off-rebound-snap-down-to-stick', 'control_stability', 5),
  ('round-off-rebound-snap-down-to-stick', 'perception_action_skill', 4),
  ('round-off-rebound-snap-down-to-stick', 'force_tissue_capacity', 3)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.physiological_emphasis f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'pattern', f.id, v.weight
FROM (VALUES
  ('reactive-gate-sprint', 'locomote', 5),
  ('reactive-gate-sprint', 'land', 2),
  ('reactive-gate-sprint', 'brace', 2),
  ('mirror-shuffle-to-sprint-exit', 'locomote', 5),
  ('mirror-shuffle-to-sprint-exit', 'land', 3),
  ('mirror-shuffle-to-sprint-exit', 'brace', 3),
  ('mirror-shuffle-to-sprint-exit', 'rotate', 1),
  ('ball-drop-sprint-catch', 'locomote', 5),
  ('ball-drop-sprint-catch', 'land', 2),
  ('ball-drop-sprint-catch', 'brace', 2),
  ('power-hurdle-to-cartwheel-round-off-entry', 'locomote', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'jump', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'land', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'invert', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'push', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'rotate', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'brace', 4),
  ('round-off-rebound-snap-down-to-stick', 'invert', 5),
  ('round-off-rebound-snap-down-to-stick', 'push', 5),
  ('round-off-rebound-snap-down-to-stick', 'rotate', 5),
  ('round-off-rebound-snap-down-to-stick', 'jump', 5),
  ('round-off-rebound-snap-down-to-stick', 'land', 5),
  ('round-off-rebound-snap-down-to-stick', 'brace', 5)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.movement_pattern f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'equipment', f.id, v.weight
FROM (VALUES
  ('reactive-gate-sprint', 'cones', 5),
  ('reactive-gate-sprint', 'none', 2),
  ('mirror-shuffle-to-sprint-exit', 'cones', 4),
  ('mirror-shuffle-to-sprint-exit', 'none', 5),
  ('ball-drop-sprint-catch', 'tennis_ball', 5),
  ('ball-drop-sprint-catch', 'reaction_ball', 3),
  ('ball-drop-sprint-catch', 'cones', 2),
  ('power-hurdle-to-cartwheel-round-off-entry', 'mat', 5),
  ('power-hurdle-to-cartwheel-round-off-entry', 'panel_mat', 3),
  ('power-hurdle-to-cartwheel-round-off-entry', 'cones', 2),
  ('round-off-rebound-snap-down-to-stick', 'mat', 5),
  ('round-off-rebound-snap-down-to-stick', 'spring_floor', 4),
  ('round-off-rebound-snap-down-to-stick', 'panel_mat', 2)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.equipment f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'body_region', f.id, v.weight
FROM (VALUES
  ('reactive-gate-sprint', 'ankle', 4),
  ('reactive-gate-sprint', 'knee', 3),
  ('reactive-gate-sprint', 'hip', 5),
  ('reactive-gate-sprint', 'core', 3),
  ('reactive-gate-sprint', 'spine', 2),
  ('mirror-shuffle-to-sprint-exit', 'ankle', 4),
  ('mirror-shuffle-to-sprint-exit', 'knee', 4),
  ('mirror-shuffle-to-sprint-exit', 'hip', 5),
  ('mirror-shuffle-to-sprint-exit', 'core', 4),
  ('mirror-shuffle-to-sprint-exit', 'spine', 2),
  ('ball-drop-sprint-catch', 'ankle', 4),
  ('ball-drop-sprint-catch', 'knee', 3),
  ('ball-drop-sprint-catch', 'hip', 5),
  ('ball-drop-sprint-catch', 'shoulder', 2),
  ('ball-drop-sprint-catch', 'core', 3),
  ('power-hurdle-to-cartwheel-round-off-entry', 'ankle', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'knee', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'hip', 5),
  ('power-hurdle-to-cartwheel-round-off-entry', 'wrist', 4),
  ('power-hurdle-to-cartwheel-round-off-entry', 'shoulder', 5),
  ('power-hurdle-to-cartwheel-round-off-entry', 'core', 5),
  ('power-hurdle-to-cartwheel-round-off-entry', 'spine', 3),
  ('round-off-rebound-snap-down-to-stick', 'ankle', 4),
  ('round-off-rebound-snap-down-to-stick', 'knee', 4),
  ('round-off-rebound-snap-down-to-stick', 'hip', 5),
  ('round-off-rebound-snap-down-to-stick', 'wrist', 5),
  ('round-off-rebound-snap-down-to-stick', 'shoulder', 5),
  ('round-off-rebound-snap-down-to-stick', 'core', 5),
  ('round-off-rebound-snap-down-to-stick', 'spine', 4)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.body_region f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'youth_beginner' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('reactive-gate-sprint', 'Two gates only; step or jog through the gate.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'Mirror shuffle only, no sprint exit.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', 'Short distance, allow one or two bounces, no diving.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Use hurdle-to-lunge freeze, cartwheel step-over, or panel-mat cartwheel.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Do not use as Output; use cartwheel line, cartwheel step-over, and round-off shape drills.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_beginner';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'youth_beginner', 'youth beginner', 'baseline', v.guidance,
  CASE WHEN 'youth_beginner' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('reactive-gate-sprint', 'Two gates only; step or jog through the gate.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'Mirror shuffle only, no sprint exit.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', 'Short distance, allow one or two bounces, no diving.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Use hurdle-to-lunge freeze, cartwheel step-over, or panel-mat cartwheel.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Do not use as Output; use cartwheel line, cartwheel step-over, and round-off shape drills.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_beginner'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'youth_intermediate' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('reactive-gate-sprint', 'Two to three gates, 5-yard sprint, full reset.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'Mirror for 5–8 seconds, then jog exit.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', '3–5 yards, catch before second bounce.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Power hurdle to cartwheel, then hurdle to round-off entry with spot.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Round-off snap-down to stick with coach supervision and mat.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_intermediate';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'youth_intermediate', 'youth intermediate', 'baseline', v.guidance,
  CASE WHEN 'youth_intermediate' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('reactive-gate-sprint', 'Two to three gates, 5-yard sprint, full reset.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'Mirror for 5–8 seconds, then jog exit.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', '3–5 yards, catch before second bounce.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Power hurdle to cartwheel, then hurdle to round-off entry with spot.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Round-off snap-down to stick with coach supervision and mat.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_intermediate'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'teen' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('reactive-gate-sprint', 'Use two gates and controlled deceleration after the gate.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'Controlled mirror and one planned exit gate.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', 'Start close and require safe deceleration.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Keep approach short and focus on hurdle-to-hand placement.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Use handstand snap-down, wall snap-down, or cartwheel-to-snap before full round-off rebound.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'teen';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'teen', 'teen', 'baseline', v.guidance,
  CASE WHEN 'teen' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('reactive-gate-sprint', 'Use two gates and controlled deceleration after the gate.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'Controlled mirror and one planned exit gate.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', 'Start close and require safe deceleration.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Keep approach short and focus on hurdle-to-hand placement.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Use handstand snap-down, wall snap-down, or cartwheel-to-snap before full round-off rebound.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'teen'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'adult_beginner' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('reactive-gate-sprint', 'Use two gates and controlled deceleration after the gate.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'Controlled mirror and one planned exit gate.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', 'Start close and require safe deceleration.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Keep approach short and focus on hurdle-to-hand placement.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Use handstand snap-down, wall snap-down, or cartwheel-to-snap before full round-off rebound.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_beginner';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'adult_beginner', 'adult beginner', 'baseline', v.guidance,
  CASE WHEN 'adult_beginner' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('reactive-gate-sprint', 'Use two gates and controlled deceleration after the gate.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'Controlled mirror and one planned exit gate.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', 'Start close and require safe deceleration.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Keep approach short and focus on hurdle-to-hand placement.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Use handstand snap-down, wall snap-down, or cartwheel-to-snap before full round-off rebound.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_beginner'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'adult_advanced' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('reactive-gate-sprint', 'Add fake cues, delayed cues, competition, or timed gate sprint.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'Add live exit cue, chase element, or sport object.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', 'Add lateral start, prone start, two-ball choice, or first-bounce limit.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Power hurdle to round-off entry with rebound target.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Round-off rebound, round-off to stick, or round-off connection prep with full recovery.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_advanced';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'adult_advanced', 'adult advanced', 'baseline', v.guidance,
  CASE WHEN 'adult_advanced' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('reactive-gate-sprint', 'Add fake cues, delayed cues, competition, or timed gate sprint.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'Add live exit cue, chase element, or sport object.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', 'Add lateral start, prone start, two-ball choice, or first-bounce limit.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Power hurdle to round-off entry with rebound target.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Round-off rebound, round-off to stick, or round-off connection prep with full recovery.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_advanced'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'older_adult' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('reactive-gate-sprint', 'Use point-and-step or low-speed gate response.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'No sprint exit; use slow mirror step drill.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', 'Use bounce-and-catch step reaction, not sprint.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Usually not appropriate unless already trained in gymnastics.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Usually not appropriate unless already trained in gymnastics.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'older_adult';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'older_adult', 'older adult', 'baseline', v.guidance,
  CASE WHEN 'older_adult' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('reactive-gate-sprint', 'Use point-and-step or low-speed gate response.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'No sprint exit; use slow mirror step drill.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', 'Use bounce-and-catch step reaction, not sprint.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Usually not appropriate unless already trained in gymnastics.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Usually not appropriate unless already trained in gymnastics.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'older_adult'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'pregnancy_postpartum' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('reactive-gate-sprint', 'Use low-speed directional response only if appropriate.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'Use slow no-contact mirror only if appropriate.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', 'Use toss/catch or step-to-catch, not sprint-and-dive.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Not recommended due to inversion, impact, and tumbling risk.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Not recommended due to inversion, impact, and tumbling risk.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'pregnancy_postpartum';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'pregnancy_postpartum', 'pregnancy postpartum', 'baseline', v.guidance,
  CASE WHEN 'pregnancy_postpartum' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('reactive-gate-sprint', 'Use low-speed directional response only if appropriate.', 'No default sex-based adjustment. Scale by first-step mechanics, cue processing, braking ability, and confidence.'),
  ('mirror-shuffle-to-sprint-exit', 'Use slow no-contact mirror only if appropriate.', 'No default sex-based adjustment. Pair by size, speed, maturity, and control rather than gender alone.'),
  ('ball-drop-sprint-catch', 'Use toss/catch or step-to-catch, not sprint-and-dive.', 'No default sex-based adjustment. Scale by acceleration, object tracking, stop control, and risk tolerance.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'Not recommended due to inversion, impact, and tumbling risk.', 'No default sex-based adjustment. Scale by tumbling skill, fear, body control, upper-body support, and landing quality.'),
  ('round-off-rebound-snap-down-to-stick', 'Not recommended due to inversion, impact, and tumbling risk.', 'No default sex-based adjustment. Scale by skill mastery, confidence, body control, upper-body support, and landing quality.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'pregnancy_postpartum'
);

-- Why-layer education
INSERT INTO coaching.education_content (
  entity_type, entity_key, entity_id, title, short_summary,
  what_it_is, why_it_works, why_it_matters, why_it_goes_here,
  programming_guidance, common_misuse, scaling_guidance
)
SELECT
  'exercise', e.slug, e.id, e.name, e.card_summary,
  e.description,
  v.why_works,
  'Develops tagged tenets and physiological qualities for athletic development.',
  v.why_here,
  v.best_placement,
  v.misuse,
  v.scale_guidance
FROM (VALUES
  ('reactive-gate-sprint', 'Reactive gate sprints train the athlete to process an external cue and convert it into a high-intent first step and acceleration. NSCA describes reaction drills as requiring athletes to identify a stimulus and respond appropriately using visual, auditory, or sensory cues while maintaining body control and technique.', 'Belongs in reactive_sprint (361) — foundational reactive Output after Skill gate reaction; pre-planned routes belong in acceleration or COD, not reactive agility.', 'Simplest high-intensity reactive sprint drill after gate reaction and deceleration foundations; before partner mirror or object-reaction Output.', 'Reactive and tumbling Output belongs while the athlete is fresh — sharp, explosive, controlled, well-spaced reps with external cues or explosive tumbling tasks. If it becomes chaotic, tired, reckless, or technically sloppy, stop or regress. Do not bury high-complexity Output under fatigue. If the route is pre-planned, classify as acceleration or COD instead of reactive agility.', 'Regress to two gates with step/jog; progress fake cues and timed gate sprints only when deceleration after the gate is controlled.'),
  ('mirror-shuffle-to-sprint-exit', 'The mirror drill creates a live information source because the follower must read the leader''s movement and match it. Adding a sprint exit makes this Output because the athlete must perceive, mirror, and transition into high-intent acceleration — a bridge from reactive agility skill into sport-like speed expression.', 'Belongs in reactive_agility_output (362) — partner read plus sprint breakout after lateral shuffle mechanics.', 'After mirror shuffle and lateral shuffle mechanics are clean; adds high-intent sprint exit to partner reactive work.', 'Reactive and tumbling Output belongs while the athlete is fresh — sharp, explosive, controlled, well-spaced reps with external cues or explosive tumbling tasks. If it becomes chaotic, tired, reckless, or technically sloppy, stop or regress. Do not bury high-complexity Output under fatigue. Do not add sprint exit if mirror base collapses or rounds exceed ~10 seconds before exit.', 'Regress to mirror shuffle only; pair by size, speed, maturity, and control with mandatory no-contact rule.'),
  ('ball-drop-sprint-catch', 'The ball drop gives a clear external object cue. The athlete must watch the object, react to the drop, accelerate, track, coordinate the catch, and decelerate. NSCA includes ball-drop reaction drills in quickness/reaction training examples.', 'Belongs in object_reaction_output (363) — visual tracking plus acceleration reaction at Output intent.', 'After ball-drop reaction Skill and sprint/deceleration foundations; before advanced object-tracking games.', 'Reactive and tumbling Output belongs while the athlete is fresh — sharp, explosive, controlled, well-spaced reps with external cues or explosive tumbling tasks. If it becomes chaotic, tired, reckless, or technically sloppy, stop or regress. Do not bury high-complexity Output under fatigue. No diving. Do not turn repeated drops into sprint conditioning.', 'Start close with generous bounce limits; progress distance and first-bounce limits only when catch and stop stay controlled.'),
  ('power-hurdle-to-cartwheel-round-off-entry', 'The tumbling hurdle sets up weight transfer and balance for the entire pass. Best Darn Gymnastics coaches the front foot to stay under the knee rather than kicking far out in front. HowToGymnastics emphasizes tight core, fast hand placement, strong snap-down, and rebound for round-off quality.', 'Belongs in tumbling_takeoff_output (364) — explosive hurdle entry after Skill tumbling foundations.', 'After hurdle-to-lunge, cartwheel, and round-off entry mechanics are technically sound; before round-off rebound Output.', 'Reactive and tumbling Output belongs while the athlete is fresh — sharp, explosive, controlled, well-spaced reps with external cues or explosive tumbling tasks. If it becomes chaotic, tired, reckless, or technically sloppy, stop or regress. Do not bury high-complexity Output under fatigue. Requires qualified coach, mat, and mastered cartwheel/round-off entry — not max power before control.', 'Regress to hurdle-to-lunge freeze or panel-mat cartwheel; progress power only when hand placement and landing stay clean.'),
  ('round-off-rebound-snap-down-to-stick', 'The round-off converts entry speed and hand-support mechanics into a powerful snap-down and rebound. HowToGymnastics describes the snap-down as the most important part: legs come together quickly, body stays tight in hollow shape, heels drive down aggressively, and rebound builds tumbling power.', 'Belongs in tumbling_rebound_output (365) — highest tumbling-output card after round-off Skill foundations.', 'Final Output tumbling card after round-off foundations and power hurdle entry; highest tumbling-output demand in the phase.', 'Reactive and tumbling Output belongs while the athlete is fresh — sharp, explosive, controlled, well-spaced reps with external cues or explosive tumbling tasks. If it becomes chaotic, tired, reckless, or technically sloppy, stop or regress. Do not bury high-complexity Output under fatigue. Not a beginner round-off drill — Output expression of already-learned mechanics only.', 'Regress to round-off snap-down shape, handstand snap-down, or cartwheel-to-snap before full rebound Output.')
) AS v(slug, why_works, why_here, best_placement, misuse, scale_guidance)
JOIN coaching.exercise e ON e.slug = v.slug
ON CONFLICT (entity_type, entity_key, entity_id) DO UPDATE SET
  title = EXCLUDED.title,
  short_summary = EXCLUDED.short_summary,
  what_it_is = EXCLUDED.what_it_is,
  why_it_works = EXCLUDED.why_it_works,
  why_it_goes_here = EXCLUDED.why_it_goes_here,
  programming_guidance = EXCLUDED.programming_guidance,
  common_misuse = EXCLUDED.common_misuse,
  scaling_guidance = EXCLUDED.scaling_guidance,
  updated_at = now();

-- Reactive / tumbling Output cluster validation education
INSERT INTO coaching.education_content (
  entity_type, entity_key, entity_id, title, short_summary,
  what_it_is, why_it_matters, programming_guidance, common_misuse
)
VALUES (
  'validation_rule',
  'output_reactive_tumbling_readiness',
  NULL,
  'Reactive Agility & Tumbling Output without chaos',
  'High-complexity Output requires freshness, external cues, generous rest, and crisp movement — not tired shuttle games or sloppy tumbling.',
  'Final Output cluster: reactive gate sprints, mirror shuffle-to-sprint exits, ball-drop sprint catches, power hurdle tumbling entry, and round-off rebound snap-down.',
  'Reactive and tumbling Output combines perception-action, high-speed decisions, deceleration, partner/object reaction, and explosive inversion. Fatigue, poor spacing, or missing prerequisites raise collision and landing risk.',
  'Master Skill gate/ball/mirror drills and deceleration first; require safe lanes and decel zones; cap reps (~10); supervise tumbling; stop when plants, catches, or rebound quality drop.',
  'Do not program after conditioning, without external cues, with crossing gate paths, diving on ball drops, or tumbling without mat/coach — regress dose or change phase intent.'
)
ON CONFLICT (entity_type, entity_key, entity_id) DO UPDATE SET
  title = EXCLUDED.title,
  short_summary = EXCLUDED.short_summary,
  what_it_is = EXCLUDED.what_it_is,
  why_it_matters = EXCLUDED.why_it_matters,
  programming_guidance = EXCLUDED.programming_guidance,
  common_misuse = EXCLUDED.common_misuse,
  updated_at = now();
