-- Capacity phase Upper-Body Push Strength cards 19–26 (rich card v2 content).
-- IDEMPOTENT. Generated by scripts/generate-124-capacity-push-cards.mjs
-- UPDATE-only on slugs from migration 121. Fine slots seeded in migration 120.

-- Equipment taxonomy for upper-body push Capacity cluster
INSERT INTO coaching.equipment (key, name, sort_order) VALUES
  ('parallettes', 'Parallettes / Push-Up Handles', 34),
  ('parallel_bars', 'Parallel Bars / Dip Bars', 35)
ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order;

-- Incline Push-Up (incline-push-up)
UPDATE coaching.exercise SET
  name = 'Incline Push-Up',
  description = 'The athlete places hands on a bench or box, sets a braced plank line from head to heel, lowers chest toward the surface under control, and presses back to full elbow extension without sagging or flaring.',
  card_summary = 'Foundational Capacity push regression using an elevated surface to teach plank line, scapular control, and progressive horizontal pressing strength.',
  coach_language = 'Use as the foundational Capacity horizontal push. Progressive overload with full rest — not a warm-up fluff set or circuit finisher. Lower the incline only when every rep stays crisp.',
  athlete_language = 'Hands on the box, strong plank, lower your chest with control, and push the box away to stand tall in your line.',
  movement_family = 'Upper-body push strength',
  primary_phase_key = 'capacity',
  phase_subrole = 'upper_body_push_strength',
  primary_order_slot = 'pushup_regression',
  default_sets = 3,
  default_reps = 8,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 40,
  movement_requirements = '{"primary_joint_actions":["shoulder_horizontal_adduction","shoulder_extension","elbow_extension","scapular_protraction"],"primary_tissues":["pectorals","anterior_deltoid","triceps","serratus_anterior","core"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0,"prerequisites":[],"setup_requirements":["Stable bench or box for incline and pike variations","Dumbbells, kettlebells, or bench as appropriate to variation","Clear floor space for push-up and floor-press patterns","Dip bars or rings at appropriate height for support holds"]}'::jsonb,
  coaching_execution = '{"movement_description":"Hands on elevated surface, braced plank line, controlled descent with elbows at roughly 45°, press to full extension without hip sag or rib flare.","setup":["Select stable bench or box height appropriate to skill.","Hands shoulder-width, fingers spread.","Walk feet back until plank line is straight.","Confirm pain-free range and supervision for youth."],"execution_steps":["Set braced plank — ribs down, glutes on.","Lower chest toward surface under control.","Keep elbows tracking — not flared to 90°.","Press through full hand to return to plank.","Finish with scapular protraction at top.","Rest fully before the next set."],"breathing_cues":["Inhale on descent — exhale through the press without losing brace."],"coach_cues":["Plank line.","Ribs down.","Elbows angle back.","Push the box away.","Control the descent."],"athlete_cues":["Tight core.","Down slow.","Push away.","Stay long."],"common_faults":["Hips sagging or piking.","Rib flare at bottom or top.","Elbows flaring to 90°.","Head dropping toward surface.","Rushing reps with short rest.","Lowering incline before control is earned."],"stop_signs":["Shoulder pinching during descent or press.","Wrist pain limiting hand support.","Cannot maintain plank line.","Sharp anterior shoulder pain.","Neck tension replacing scapular control."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Scapular Push-Up","Wrist Rockers","Wall Slides with Lift-Off","Dead Bug"],"pairs_well_after":["Push-Up","Tempo / Eccentric Push-Up","Dumbbell / Kettlebell Floor Press"],"good_for_sessions":["capacity_upper_body","push_capacity","strength_development"],"avoid_before":["Floor push-up if incline plank line is poor","Loaded bench press before horizontal push competency"],"avoid_after":[],"do_not_use_when":["Shoulder pinching every rep","Wrist pain with hand support","Using as conditioning circuit","Hip sag on every rep"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["NSCA push-up regression progressions","Incline push-up teaching for athletic populations"],"internal_notes":["Validator should confirm incline control before floor push-up or loaded press."]}'::jsonb,
  updated_at = now()
WHERE slug = 'incline-push-up';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'pushup_regression',
  order_index = pos.order_index,
  fit_weight = 5,
  freshness_required = FALSE,
  fatigue_sensitivity = 2,
  fatigue_cost = 2,
  technical_complexity = 2,
  impact_level = 0,
  intensity_ceiling = 'moderate',
  notes = 'Foundational Capacity push regression. Master before floor push-up and loaded horizontal press. Supervision: recommended.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'capacity'
JOIN coaching.phase_order_slot pos ON pos.key = 'pushup_regression' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'incline-push-up';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 3,
  default_reps = 8,
  default_distance = NULL,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  tempo = '2-0-1-0',
  est_seconds_per_set = 40,
  default_rpe_min = 5,
  default_rpe_max = 7,
  session_volume_min = '16 reps',
  session_volume_max = '36 reps'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'incline-push-up';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'incline-push-up';

-- Push-Up (push-up)
UPDATE coaching.exercise SET
  name = 'Push-Up',
  description = 'The athlete assumes a high plank with hands shoulder-width, lowers chest toward the floor under control, and presses back to full extension while maintaining a braced line from head to heel.',
  card_summary = 'Primary Capacity floor push-up that builds horizontal pressing strength, trunk bracing, and scapular control with bodyweight load and full rest.',
  coach_language = 'Use as the primary Capacity horizontal push. Progressive overload with full rest — not max-rep AMRAPs or explosive plyo push-ups. Add load or tempo only when every rep stays crisp.',
  athlete_language = 'Strong plank, lower your chest to the floor with control, and push the ground away to finish tall.',
  movement_family = 'Upper-body push strength',
  primary_phase_key = 'capacity',
  phase_subrole = 'upper_body_push_strength',
  primary_order_slot = 'horizontal_push_strength',
  default_sets = 3,
  default_reps = 8,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 40,
  movement_requirements = '{"primary_joint_actions":["shoulder_horizontal_adduction","shoulder_extension","elbow_extension","scapular_protraction"],"primary_tissues":["pectorals","anterior_deltoid","triceps","serratus_anterior","core"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0,"prerequisites":["incline-push-up"],"setup_requirements":["Stable bench or box for incline and pike variations","Dumbbells, kettlebells, or bench as appropriate to variation","Clear floor space for push-up and floor-press patterns","Dip bars or rings at appropriate height for support holds"]}'::jsonb,
  coaching_execution = '{"movement_description":"High plank, braced trunk, controlled descent to floor or fist-height target, press to full extension with scapular protraction at top.","setup":["Hands shoulder-width, fingers spread.","Feet hip-width, plank line set before first rep.","Optional fist or block target for consistent depth.","Confirm incline push-up competency and pain-free range."],"execution_steps":["Brace ribs down and set glutes on.","Lower chest toward floor under control.","Keep elbows at roughly 45° from torso.","Press through full hand to return to plank.","Finish with shoulder blades protracted — push floor away.","Rest fully between sets."],"breathing_cues":["Inhale on descent — exhale through the sticking point without losing brace."],"coach_cues":["Plank line.","Ribs down.","Elbows back.","Push the floor.","Full extension."],"athlete_cues":["Tight.","Down slow.","Push.","Stay long."],"common_faults":["Hips sagging or piking.","Partial ROM — chest never reaches target depth.","Elbows flaring to 90°.","Head jutting forward.","Scapular winging at top.","Rushing reps with short rest."],"stop_signs":["Shoulder pinching during descent or press.","Wrist pain limiting hand support.","Cannot maintain plank line.","Sharp anterior shoulder or elbow pain.","Low back pain from sagging every rep."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Incline Push-Up","Scapular Push-Up","Dead Bug","Wrist Rockers"],"pairs_well_after":["Tempo / Eccentric Push-Up","Dumbbell / Kettlebell Floor Press","Half-Kneeling Single-Arm Press"],"good_for_sessions":["capacity_upper_body","push_capacity","strength_development"],"avoid_before":["Floor push-up if incline control is poor","Explosive plyo push-up Output in same block if shoulders are pre-fatigued"],"avoid_after":[],"do_not_use_when":["No incline push-up competency","Shoulder pinching every rep","Hip sag on every rep","Used as high-rep conditioning circuit"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["NSCA push-up technique standards","Closed-chain pressing progressions for athletes"],"internal_notes":["Prerequisite incline-push-up should be documented before floor push-up prescription."]}'::jsonb,
  updated_at = now()
WHERE slug = 'push-up';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'horizontal_push_strength',
  order_index = pos.order_index,
  fit_weight = 5,
  freshness_required = FALSE,
  fatigue_sensitivity = 3,
  fatigue_cost = 3,
  technical_complexity = 2,
  impact_level = 0,
  intensity_ceiling = 'high',
  notes = 'Requires incline push-up competency. Primary horizontal push before loaded press and inverted progressions. Supervision: recommended.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'capacity'
JOIN coaching.phase_order_slot pos ON pos.key = 'horizontal_push_strength' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'push-up';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 3,
  default_reps = 8,
  default_distance = NULL,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  tempo = '2-0-1-0',
  est_seconds_per_set = 40,
  default_rpe_min = 6,
  default_rpe_max = 8,
  session_volume_min = '16 reps',
  session_volume_max = '40 reps'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'push-up';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'push-up';

-- Tempo / Eccentric Push-Up (tempo-eccentric-push-up)
UPDATE coaching.exercise SET
  name = 'Tempo / Eccentric Push-Up',
  description = 'The athlete performs a floor or incline push-up with prescribed tempo — typically a 3–4 second lowering, optional pause at bottom, and controlled press — emphasizing eccentric control and full rest between sets.',
  card_summary = 'Capacity tempo and eccentric-emphasis push-up that builds pressing tissue capacity through controlled lowering, pause, or slow eccentric before concentric drive.',
  coach_language = 'Use for eccentric pressing capacity with intentional tempo and full rest. Not a speed push-up, plyometric variation, or Fitness AMRAP.',
  athlete_language = 'Lower yourself slowly, stay tight at the bottom, and push back up with control — no bouncing.',
  movement_family = 'Upper-body push strength',
  primary_phase_key = 'capacity',
  phase_subrole = 'upper_body_push_strength',
  primary_order_slot = 'push_eccentric',
  default_sets = 3,
  default_reps = 6,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 45,
  movement_requirements = '{"primary_joint_actions":["shoulder_horizontal_adduction","shoulder_extension","elbow_extension","scapular_protraction"],"primary_tissues":["pectorals","anterior_deltoid","triceps","serratus_anterior","core"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0,"prerequisites":["push-up"],"setup_requirements":["Stable bench or box for incline and pike variations","Dumbbells, kettlebells, or bench as appropriate to variation","Clear floor space for push-up and floor-press patterns","Dip bars or rings at appropriate height for support holds"]}'::jsonb,
  coaching_execution = '{"movement_description":"Push-up with 3–4 second eccentric, optional 1-second pause at bottom, controlled concentric — no bounce or speed intent.","setup":["Select floor or incline based on push-up competency.","Set tempo prescription before first rep.","Confirm pain-free shoulder and wrist range.","Use fist or block target for consistent bottom position."],"execution_steps":["Set braced plank before descent.","Lower over 3–4 seconds with elbows at 45°.","Pause lightly at bottom without relaxing trunk.","Press to full extension without momentum bounce.","Finish with scapular protraction.","Rest fully between sets — lower rep count than standard push-up."],"breathing_cues":["Brace before descent — controlled exhale through the press."],"coach_cues":["Slow down.","No bounce.","Stay tight at bottom.","Elbows back.","Full rest between sets."],"athlete_cues":["Slow.","Pause.","Push.","Tight."],"common_faults":["Rushing the eccentric.","Bouncing off the floor at bottom.","Hips sagging under eccentric load.","Partial ROM to make tempo easier.","Too many reps with short rest.","Prescribing before floor push-up competency."],"stop_signs":["Shoulder pinching worsens with slow eccentric.","Cannot control 3-second lowering.","Elbow pain under tempo load.","Trunk collapses at bottom pause.","Athlete reports excessive DOMS beyond normal adaptation."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Push-Up","Incline Push-Up","Scapular Push-Up"],"pairs_well_after":["Dumbbell / Kettlebell Floor Press","Pike Push-Up / Box Pike Push-Up"],"good_for_sessions":["capacity_upper_body","push_capacity","strength_development"],"avoid_before":["Tempo push-up before floor push-up is clean","Explosive upper-body Output immediately after heavy eccentric block"],"avoid_after":[],"do_not_use_when":["No push-up competency","Bouncing every rep","Shoulder pinching under slow eccentric","Used as conditioning AMRAP"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Tempo push-up eccentric progressions","Eccentric training dose for upper-body pressing"],"internal_notes":["Prerequisite push-up required. Flag high rep tempo push-ups with short rest."]}'::jsonb,
  updated_at = now()
WHERE slug = 'tempo-eccentric-push-up';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'push_eccentric',
  order_index = pos.order_index,
  fit_weight = 4,
  freshness_required = FALSE,
  fatigue_sensitivity = 4,
  fatigue_cost = 4,
  technical_complexity = 3,
  impact_level = 0,
  intensity_ceiling = 'high',
  notes = 'Requires push-up competency. Lower rep count than standard push-up — eccentric emphasis increases tissue demand. Supervision: recommended.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'capacity'
JOIN coaching.phase_order_slot pos ON pos.key = 'push_eccentric' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'tempo-eccentric-push-up';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 3,
  default_reps = 6,
  default_distance = NULL,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  tempo = '3-1-1-0',
  est_seconds_per_set = 45,
  default_rpe_min = 6,
  default_rpe_max = 8,
  session_volume_min = '12 reps',
  session_volume_max = '24 reps'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'tempo-eccentric-push-up';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'tempo-eccentric-push-up';

-- Dumbbell / Kettlebell Floor Press (dumbbell-kettlebell-floor-press)
UPDATE coaching.exercise SET
  name = 'Dumbbell / Kettlebell Floor Press',
  description = 'The athlete lies supine on the floor, presses dumbbells or kettlebells from chest level to full elbow extension, pauses lightly at floor contact, and lowers under control with braced trunk.',
  card_summary = 'Capacity floor press using dumbbells or kettlebells that builds horizontal pressing strength with reduced shoulder ROM versus bench press and a stable floor reference.',
  coach_language = 'Use for loaded horizontal push with intentional load and full rest. Floor contact limits ROM — not a bench press substitute with bounce or short-rest circuits.',
  athlete_language = 'Lie on your back, press the weights up, touch your upper arms to the floor, and press back up without arching.',
  movement_family = 'Upper-body push strength',
  primary_phase_key = 'capacity',
  phase_subrole = 'upper_body_push_strength',
  primary_order_slot = 'horizontal_push_strength',
  default_sets = 3,
  default_reps = 8,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 40,
  movement_requirements = '{"primary_joint_actions":["shoulder_horizontal_adduction","shoulder_extension","elbow_extension"],"primary_tissues":["pectorals","anterior_deltoid","triceps","core"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0,"prerequisites":["push-up"],"setup_requirements":["Stable bench or box for incline and pike variations","Dumbbells, kettlebells, or bench as appropriate to variation","Clear floor space for push-up and floor-press patterns","Dip bars or rings at appropriate height for support holds","Mat or clear floor space for supine pressing"]}'::jsonb,
  coaching_execution = '{"movement_description":"Supine on floor, dumbbells at chest, press to full extension, upper arms touch floor lightly at bottom, controlled press with braced trunk.","setup":["Select dumbbell or kettlebell load appropriate to skill.","Lie supine with knees bent, feet flat.","Set shoulder blades slightly retracted and down.","Confirm push-up competency and pain-free range."],"execution_steps":["Start weights at chest with wrists stacked over elbows.","Brace trunk — slight posterior pelvic tilt.","Press to full elbow extension.","Lower until upper arms lightly contact floor.","Pause without bouncing off floor.","Rest fully between sets."],"breathing_cues":["Brace before press — exhale through sticking point without losing trunk."],"coach_cues":["Wrists stacked.","Upper arms to floor.","No bounce.","Ribs down.","Control the descent."],"athlete_cues":["Press.","Touch.","No arch.","Tight core."],"common_faults":["Bouncing upper arms off floor.","Excessive lumbar arch.","Elbows flaring to 90°.","Partial ROM — arms never reach floor.","Weights drifting out of line.","Rushing reps with short rest."],"stop_signs":["Shoulder pinching at bottom range.","Sharp anterior shoulder pain.","Cannot control eccentric to floor contact.","Low back pain from arching every rep.","Elbow pain under load."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Push-Up","Incline Push-Up","Dead Bug"],"pairs_well_after":["Dumbbell Bench Press","Half-Kneeling Single-Arm Press"],"good_for_sessions":["capacity_upper_body","push_capacity","strength_development"],"avoid_before":["Floor press before push-up is clean","Bench press same session if shoulder is already fatigued from eccentric work"],"avoid_after":[],"do_not_use_when":["No push-up competency","Shoulder pinching at bottom","Bouncing every rep","Used as conditioning circuit"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Floor press vs bench press ROM and shoulder stress","NSCA dumbbell pressing progressions"],"internal_notes":["Prerequisite push-up required before loaded floor press in youth."]}'::jsonb,
  updated_at = now()
WHERE slug = 'dumbbell-kettlebell-floor-press';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'horizontal_push_strength',
  order_index = pos.order_index,
  fit_weight = 4,
  freshness_required = FALSE,
  fatigue_sensitivity = 3,
  fatigue_cost = 3,
  technical_complexity = 2,
  impact_level = 0,
  intensity_ceiling = 'high',
  notes = 'Requires push-up competency. Bridge to bench press — floor limits ROM for shoulder-friendly loading. Supervision: recommended.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'capacity'
JOIN coaching.phase_order_slot pos ON pos.key = 'horizontal_push_strength' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'dumbbell-kettlebell-floor-press';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 3,
  default_reps = 8,
  default_distance = NULL,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  tempo = '2-0-1-0',
  est_seconds_per_set = 40,
  default_rpe_min = 6,
  default_rpe_max = 8,
  session_volume_min = '16 reps',
  session_volume_max = '36 reps'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'dumbbell-kettlebell-floor-press';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'dumbbell-kettlebell-floor-press';

-- Dumbbell Bench Press (dumbbell-bench-press)
UPDATE coaching.exercise SET
  name = 'Dumbbell Bench Press',
  description = 'The athlete lies on a flat bench with dumbbells at chest level, presses to full extension with controlled path, and lowers under tempo with feet planted and braced trunk.',
  card_summary = 'Capacity dumbbell bench press that builds horizontal pressing strength through full ROM with independent arm demand and trunk stability on a stable bench.',
  coach_language = 'Use for loaded horizontal push with intentional load and full rest. Supervise bench setup — not a max-effort powerlifting bench or Fitness circuit with short rest.',
  athlete_language = 'Feet planted, back braced, press the dumbbells up, lower with control, and keep your shoulders packed.',
  movement_family = 'Upper-body push strength',
  primary_phase_key = 'capacity',
  phase_subrole = 'upper_body_push_strength',
  primary_order_slot = 'horizontal_push_strength',
  default_sets = 3,
  default_reps = 8,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 45,
  movement_requirements = '{"primary_joint_actions":["shoulder_horizontal_adduction","shoulder_extension","elbow_extension"],"primary_tissues":["pectorals","anterior_deltoid","triceps","core"],"breathing_demand":"nasal","balance_demand":"stable","impact_level":0,"prerequisites":["dumbbell-kettlebell-floor-press"],"setup_requirements":["Stable bench or box for incline and pike variations","Dumbbells, kettlebells, or bench as appropriate to variation","Clear floor space for push-up and floor-press patterns","Dip bars or rings at appropriate height for support holds","Stable flat bench with clear dumbbell rack path"]}'::jsonb,
  coaching_execution = '{"movement_description":"Supine on bench, dumbbells at chest, press to full extension with controlled path, lower under tempo with braced trunk and feet planted.","setup":["Select dumbbell load appropriate to skill.","Sit on bench, dumbbells on thighs, lie back safely.","Feet flat, slight arch only — ribs controlled.","Confirm floor press or push-up competency first."],"execution_steps":["Set shoulder blades retracted and down.","Start dumbbells at chest with wrists stacked.","Press to full extension without shrugging.","Lower under control to chest level.","Keep elbows at roughly 45° from torso.","Rerack safely and rest fully between sets."],"breathing_cues":["Brace before press — exhale through sticking point without losing trunk."],"coach_cues":["Feet planted.","Shoulders packed.","Control the path.","No bounce.","Safe rerack."],"athlete_cues":["Plant feet.","Press.","Lower slow.","Pack shoulders."],"common_faults":["Bouncing dumbbells off chest.","Excessive lumbar arch and rib flare.","Elbows flaring to 90°.","Asymmetric pressing path.","Unsafe dumbbell pickup or rerack.","Short rest turning it into conditioning."],"stop_signs":["Shoulder pinching at bottom ROM.","Sharp anterior shoulder pain.","Cannot control eccentric to chest.","Unsafe bench or dumbbell setup.","Elbow pain under load."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Dumbbell / Kettlebell Floor Press","Push-Up","Scapular Push-Up"],"pairs_well_after":["Half-Kneeling Single-Arm Press","Pike Push-Up / Box Pike Push-Up"],"good_for_sessions":["capacity_upper_body","push_capacity","strength_development"],"avoid_before":["Bench press before floor press or push-up is clean","Max tumbling Output if shoulders are pre-fatigued from heavy bench"],"avoid_after":[],"do_not_use_when":["No floor press or push-up competency","Unsafe bench setup","Shoulder pinching at bottom","Used as metcon with short rest"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["NSCA dumbbell bench press technique","DB bench vs barbell for athletic pressing progressions"],"internal_notes":["Prerequisite dumbbell-kettlebell-floor-press recommended before heavy bench in youth."]}'::jsonb,
  updated_at = now()
WHERE slug = 'dumbbell-bench-press';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'horizontal_push_strength',
  order_index = pos.order_index,
  fit_weight = 5,
  freshness_required = FALSE,
  fatigue_sensitivity = 3,
  fatigue_cost = 4,
  technical_complexity = 3,
  impact_level = 0,
  intensity_ceiling = 'high',
  notes = 'Requires floor press or push-up competency. Supervise dumbbell bench setup and rerack. Supervision: recommended.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'capacity'
JOIN coaching.phase_order_slot pos ON pos.key = 'horizontal_push_strength' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'dumbbell-bench-press';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 3,
  default_reps = 8,
  default_distance = NULL,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  tempo = '2-0-1-0',
  est_seconds_per_set = 45,
  default_rpe_min = 6,
  default_rpe_max = 8,
  session_volume_min = '16 reps',
  session_volume_max = '36 reps'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'dumbbell-bench-press';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'dumbbell-bench-press';

-- Half-Kneeling Single-Arm Press (half-kneeling-single-arm-press)
UPDATE coaching.exercise SET
  name = 'Half-Kneeling Single-Arm Press',
  description = 'The athlete assumes a half-kneeling stance, braces trunk against extension and rotation, and presses a dumbbell or kettlebell overhead to full extension without rib flare or lumbar arch.',
  card_summary = 'Capacity half-kneeling single-arm press that builds vertical pressing strength, trunk anti-rotation, and shoulder stability with unilateral load demand.',
  coach_language = 'Use for vertical push with intentional load and full rest. Half-kneeling exposes trunk and shoulder control — not a standing push-press or explosive Output overhead work.',
  athlete_language = 'Half-kneel tall, brace your core, press the weight straight up, and lower under control without leaning back.',
  movement_family = 'Upper-body push strength',
  primary_phase_key = 'capacity',
  phase_subrole = 'upper_body_push_strength',
  primary_order_slot = 'vertical_push_strength',
  default_sets = 3,
  default_reps = 8,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 45,
  movement_requirements = '{"primary_joint_actions":["shoulder_flexion","shoulder_extension","elbow_extension","scapular_upward_rotation"],"primary_tissues":["anterior_deltoid","triceps","serratus_anterior","core","hip_flexors"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":0,"prerequisites":["push-up"],"setup_requirements":["Stable bench or box for incline and pike variations","Dumbbells, kettlebells, or bench as appropriate to variation","Clear floor space for push-up and floor-press patterns","Dip bars or rings at appropriate height for support holds","Mat or pad for kneeling knee comfort"]}'::jsonb,
  coaching_execution = '{"movement_description":"Half-kneeling stance, dumbbell at shoulder, press overhead to full extension without rib flare, lower under control with trunk braced.","setup":["Set half-kneeling — front foot flat, back knee down on pad.","Select dumbbell or kettlebell load appropriate to skill.","Rack weight at shoulder with wrist stacked.","Confirm horizontal push competency and pain-free overhead range."],"execution_steps":["Brace ribs down and glutes on.","Press vertically — biceps by ear at top.","Avoid leaning back or rib flare.","Lower under control to shoulder rack.","Keep hips square — no trunk rotation.","Complete reps per side with full rest between sets."],"breathing_cues":["Brace before press — exhale through top without losing ribs down."],"coach_cues":["Ribs down.","Press straight up.","No lean back.","Hips square.","Control the descent."],"athlete_cues":["Tight core.","Press up.","Stay tall.","No arch."],"common_faults":["Leaning back to finish press.","Rib flare at lockout.","Trunk rotating toward pressing side.","Pressing forward instead of vertical.","Using leg drive from half-kneel.","Short rest alternating arms as conditioning."],"stop_signs":["Shoulder pinching at overhead range.","Sharp anterior shoulder pain.","Low back pain from arching every rep.","Cannot press without lean-back compensation.","Loss of half-kneeling balance every rep."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Push-Up","Wall Slides with Lift-Off","Dead Bug","Half-Kneeling Pallof Hold"],"pairs_well_after":["Pike Push-Up / Box Pike Push-Up","Overhead Carry","Dip Support / Ring Support Hold"],"good_for_sessions":["capacity_upper_body","push_capacity","strength_development"],"avoid_before":["Overhead press if horizontal push base is poor","Handstand Output if shoulders are pre-fatigued from heavy vertical push"],"avoid_after":[],"do_not_use_when":["Shoulder pinching overhead","No push-up competency","Lean-back every rep","Used as push-press or conditioning circuit"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Half-kneeling press for trunk and shoulder integration","NSCA overhead pressing progressions from half-kneel"],"internal_notes":["Prerequisite push-up recommended. Flag lean-back compensation on validator review."]}'::jsonb,
  updated_at = now()
WHERE slug = 'half-kneeling-single-arm-press';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'vertical_push_strength',
  order_index = pos.order_index,
  fit_weight = 5,
  freshness_required = FALSE,
  fatigue_sensitivity = 3,
  fatigue_cost = 3,
  technical_complexity = 3,
  impact_level = 0,
  intensity_ceiling = 'high',
  notes = 'Requires horizontal push competency. Primary vertical push before inverted and support progressions. Supervision: recommended.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'capacity'
JOIN coaching.phase_order_slot pos ON pos.key = 'vertical_push_strength' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'half-kneeling-single-arm-press';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 3,
  default_reps = 8,
  default_distance = NULL,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  tempo = '2-0-1-0',
  est_seconds_per_set = 45,
  default_rpe_min = 6,
  default_rpe_max = 8,
  session_volume_min = '12 reps per side',
  session_volume_max = '32 reps per side'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'half-kneeling-single-arm-press';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'half-kneeling-single-arm-press';

-- Pike Push-Up / Box Pike Push-Up (pike-push-up-box-pike-push-up)
UPDATE coaching.exercise SET
  name = 'Pike Push-Up / Box Pike Push-Up',
  description = 'The athlete sets hips high in pike position — feet on floor or elevated on box — lowers head toward floor or box edge under control, and presses back to pike with braced trunk and active shoulders.',
  card_summary = 'Capacity pike or box-elevated pike push-up that builds inverted pressing strength, shoulder flexion force, and handstand-relevant vertical push demand with controlled reps.',
  coach_language = 'Use for inverted pressing capacity with intentional tempo and full rest. Not a handstand hold, walk, or explosive Output skill drill.',
  athlete_language = 'Hips up, head toward the floor, press the ground away, and stay tight through your shoulders and core.',
  movement_family = 'Upper-body push strength',
  primary_phase_key = 'capacity',
  phase_subrole = 'upper_body_push_strength',
  primary_order_slot = 'inverted_push_strength',
  default_sets = 3,
  default_reps = 8,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  est_seconds_per_set = 45,
  movement_requirements = '{"primary_joint_actions":["shoulder_flexion","shoulder_extension","elbow_flexion","elbow_extension","scapular_upward_rotation"],"primary_tissues":["anterior_deltoid","triceps","serratus_anterior","core","wrist_flexors"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":0,"prerequisites":["push-up"],"setup_requirements":["Stable bench or box for incline and pike variations","Dumbbells, kettlebells, or bench as appropriate to variation","Clear floor space for push-up and floor-press patterns","Dip bars or rings at appropriate height for support holds","Box or bench for feet-elevated pike variation when progressed"]}'::jsonb,
  coaching_execution = '{"movement_description":"Pike position with hips high, controlled descent of head toward floor or box, press back to pike with active shoulders and braced trunk.","setup":["Select floor pike or box feet-elevated pike based on skill.","Hands shoulder-width, fingers spread.","Walk feet in until hips stack over shoulders as tolerated.","Confirm push-up competency and wrist tolerance."],"execution_steps":["Set pike — hips high, ears between arms.","Lower head toward floor or target under control.","Keep elbows tracking — not flaring wide.","Press through hands to return to pike.","Maintain trunk brace — no sag at top.","Rest fully between sets."],"breathing_cues":["Brace before descent — controlled exhale through the press."],"coach_cues":["Hips up.","Head between hands.","Elbows back.","Push the floor.","Stay active in shoulders."],"athlete_cues":["Pike tall.","Down slow.","Press.","Stay tight."],"common_faults":["Hips too low — becomes regular push-up.","Collapsing into forward fold without pressing.","Head landing hard on floor.","Elbows flaring excessively.","Wrist collapsing under load.","Short rest high-rep burnout."],"stop_signs":["Shoulder pinching in inverted position.","Wrist pain limiting hand support.","Neck compression from head hitting floor hard.","Cannot control eccentric descent.","Dizziness or blood-pressure symptoms in inverted position."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Push-Up","Half-Kneeling Single-Arm Press","Wall Slides with Lift-Off","Wrist Rockers"],"pairs_well_after":["Dip Support / Ring Support Hold","Handstand — Skill pattern"],"good_for_sessions":["capacity_upper_body","push_capacity","strength_development"],"avoid_before":["Feet-elevated pike before floor pike control","Handstand Output immediately after heavy pike block if shoulders are fatigued"],"avoid_after":[],"do_not_use_when":["No push-up competency","Wrist or shoulder pinching in pike","Head crashes floor every rep","Used as handstand skill substitute in Output block"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Pike push-up progressions toward handstand push-up","Box pike push-up scaling for athletes"],"internal_notes":["Prerequisite push-up required. Distinguish Capacity pike from Skill handstand work."]}'::jsonb,
  updated_at = now()
WHERE slug = 'pike-push-up-box-pike-push-up';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'inverted_push_strength',
  order_index = pos.order_index,
  fit_weight = 4,
  freshness_required = FALSE,
  fatigue_sensitivity = 4,
  fatigue_cost = 4,
  technical_complexity = 4,
  impact_level = 0,
  intensity_ceiling = 'high',
  notes = 'Requires push-up competency. Inverted demand — supervise ROM and wrist tolerance before feet-elevated progressions. Supervision: recommended.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'capacity'
JOIN coaching.phase_order_slot pos ON pos.key = 'inverted_push_strength' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'pike-push-up-box-pike-push-up';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'reps',
  default_sets = 3,
  default_reps = 8,
  default_distance = NULL,
  default_work_seconds = NULL,
  default_rest_seconds = 90,
  tempo = '2-0-1-0',
  est_seconds_per_set = 45,
  default_rpe_min = 6,
  default_rpe_max = 8,
  session_volume_min = '12 reps',
  session_volume_max = '32 reps'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'pike-push-up-box-pike-push-up';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'pike-push-up-box-pike-push-up';

-- Dip Support / Ring Support Hold (dip-support-ring-support-hold)
UPDATE coaching.exercise SET
  name = 'Dip Support / Ring Support Hold',
  description = 'The athlete jumps or steps to support on parallel bars or rings, locks elbows with shoulders depressed and protracted, holds the top position for prescribed time, and descends under control or steps down safely.',
  card_summary = 'Capacity dip or ring support hold that builds locked-out pressing support strength, shoulder stability, and trunk bracing at the top of the dip position.',
  coach_language = 'Use for support strength with intentional hold time and full rest — not dip eccentrics for high volume, ring swings, or Fitness hold circuits with short rest.',
  athlete_language = 'Jump to support, lock your arms, push the bars away, stay tight, and hold strong without shrugging.',
  movement_family = 'Upper-body push strength',
  primary_phase_key = 'capacity',
  phase_subrole = 'upper_body_push_strength',
  primary_order_slot = 'support_strength',
  default_sets = 3,
  default_reps = NULL,
  default_work_seconds = 10,
  default_rest_seconds = 60,
  est_seconds_per_set = 15,
  movement_requirements = '{"primary_joint_actions":["shoulder_extension","elbow_extension","scapular_depression","scapular_protraction"],"primary_tissues":["triceps","anterior_deltoid","serratus_anterior","core"],"breathing_demand":"nasal","balance_demand":"dynamic","impact_level":0,"prerequisites":["push-up","pike-push-up-box-pike-push-up"],"setup_requirements":["Stable bench or box for incline and pike variations","Dumbbells, kettlebells, or bench as appropriate to variation","Clear floor space for push-up and floor-press patterns","Dip bars or rings at appropriate height for support holds","Stable dip bars or ring setup at appropriate height","Mat or crash pad under rings for safe dismount"]}'::jsonb,
  coaching_execution = '{"movement_description":"Jump or step to top support on bars or rings, lock elbows, depress and protract shoulders, hold prescribed time with braced trunk, dismount safely.","setup":["Set dip bars or rings at height athlete can safely enter support.","Confirm push-up and pike push-up competency.","Review safe jump-to-support and step-down entry.","Place mat under rings if instability is high."],"execution_steps":["Jump or step to support with locked elbows.","Depress shoulders — push bars or rings away.","Ribs down, trunk braced, legs controlled.","Hold prescribed time without shrug or unlock.","Step down or lower under control to safe dismount.","Rest fully before the next hold."],"breathing_cues":["Steady nasal breathing — do not hold breath and lose shoulder position."],"coach_cues":["Lock elbows.","Push down on bars.","Shoulders away from ears.","Ribs down.","Safe dismount."],"athlete_cues":["Lock.","Push down.","Stay tall.","Breathe."],"common_faults":["Shoulders shrugging to ears.","Elbows unlocking during hold.","Ring or bar swing from leg kick.","Turning hold into dip eccentrics for reps.","Prescribing before push-up or pike base.","Short rest between holds like conditioning."],"stop_signs":["Shoulder pinching in support position.","Sharp anterior shoulder or sternum pain.","Cannot achieve locked elbow support.","Excessive ring instability without control.","Dizziness or inability to dismount safely."]}'::jsonb,
  pairing_logic = '{"pairs_well_before":["Push-Up","Pike Push-Up / Box Pike Push-Up","Scapular Push-Up","Wrist Rockers"],"pairs_well_after":["Ring Row / TRX Row","Handstand — Skill pattern","Dip Eccentric — Skill progression"],"good_for_sessions":["capacity_upper_body","push_capacity","strength_development"],"avoid_before":["Support hold before push-up and pike are clean","Ring Output swings immediately after support block if shoulders are fatigued"],"avoid_after":[],"do_not_use_when":["No push-up or pike competency","Shoulder shrugs every hold","Cannot lock elbows","Used as high-rep dip eccentric circuit"]}'::jsonb,
  media_library = '{"demo_video_sources":[],"coaching_articles":[],"clinical_or_sport_science_references":["Dip support hold progressions for rings and bars","Support strength before dip and muscle-up progressions"],"internal_notes":["Prerequisites push-up and pike-push-up-box-pike-push-up. Distinguish Capacity hold from Skill dip eccentrics."]}'::jsonb,
  updated_at = now()
WHERE slug = 'dip-support-ring-support-hold';

UPDATE coaching.exercise_phase_profile p SET
  role = 'primary',
  order_slot = 'support_strength',
  order_index = pos.order_index,
  fit_weight = 4,
  freshness_required = FALSE,
  fatigue_sensitivity = 3,
  fatigue_cost = 3,
  technical_complexity = 3,
  impact_level = 0,
  intensity_ceiling = 'high',
  notes = 'Requires push-up and pike push-up competency. Support hold — not dip eccentric volume. Progress hold time before ring instability. Supervision: recommended.'
FROM coaching.exercise e
JOIN coaching.session_phase sp ON sp.key = 'capacity'
JOIN coaching.phase_order_slot pos ON pos.key = 'support_strength' AND pos.phase_id = sp.id
WHERE p.exercise_id = e.id AND p.phase_id = sp.id AND e.slug = 'dip-support-ring-support-hold';

UPDATE coaching.exercise_dosage_profile d SET
  volume_unit = 'seconds',
  default_sets = 3,
  default_reps = NULL,
  default_distance = NULL,
  default_work_seconds = 10,
  default_rest_seconds = 60,
  tempo = 'isometric_hold',
  est_seconds_per_set = 15,
  default_rpe_min = 6,
  default_rpe_max = 8,
  session_volume_min = '20 seconds total',
  session_volume_max = '60 seconds total'
FROM coaching.exercise e
WHERE d.exercise_id = e.id AND d.profile_name = 'Default' AND e.slug = 'dip-support-ring-support-hold';

UPDATE coaching.exercise_regimen_rule r SET
  can_be_daily = FALSE,
  weekly_max_frequency = CASE WHEN FALSE THEN 7 ELSE r.weekly_max_frequency END
FROM coaching.exercise e
WHERE r.exercise_id = e.id AND e.slug = 'dip-support-ring-support-hold';

-- Refresh weighted taxonomy tags for upper-body push Capacity cards
DELETE FROM coaching.exercise_tag t
USING coaching.exercise e
WHERE t.exercise_id = e.id
  AND e.slug IN ('incline-push-up', 'push-up', 'tempo-eccentric-push-up', 'dumbbell-kettlebell-floor-press', 'dumbbell-bench-press', 'half-kneeling-single-arm-press', 'pike-push-up-box-pike-push-up', 'dip-support-ring-support-hold')
  AND t.facet_type IN ('tenet', 'methodology', 'physiology', 'pattern', 'equipment', 'body_region');

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'tenet', f.id, v.weight
FROM (VALUES
  ('incline-push-up', 'strength', 4),
  ('incline-push-up', 'body_control', 5),
  ('incline-push-up', 'coordination', 3),
  ('incline-push-up', 'balance', 2),
  ('push-up', 'strength', 5),
  ('push-up', 'body_control', 5),
  ('push-up', 'coordination', 3),
  ('push-up', 'balance', 2),
  ('tempo-eccentric-push-up', 'strength', 5),
  ('tempo-eccentric-push-up', 'body_control', 5),
  ('tempo-eccentric-push-up', 'coordination', 3),
  ('dumbbell-kettlebell-floor-press', 'strength', 5),
  ('dumbbell-kettlebell-floor-press', 'body_control', 4),
  ('dumbbell-kettlebell-floor-press', 'coordination', 3),
  ('dumbbell-bench-press', 'strength', 5),
  ('dumbbell-bench-press', 'body_control', 4),
  ('dumbbell-bench-press', 'coordination', 4),
  ('half-kneeling-single-arm-press', 'strength', 5),
  ('half-kneeling-single-arm-press', 'body_control', 5),
  ('half-kneeling-single-arm-press', 'balance', 3),
  ('half-kneeling-single-arm-press', 'coordination', 3),
  ('pike-push-up-box-pike-push-up', 'strength', 5),
  ('pike-push-up-box-pike-push-up', 'body_control', 5),
  ('pike-push-up-box-pike-push-up', 'balance', 4),
  ('pike-push-up-box-pike-push-up', 'coordination', 4),
  ('dip-support-ring-support-hold', 'strength', 5),
  ('dip-support-ring-support-hold', 'body_control', 5),
  ('dip-support-ring-support-hold', 'balance', 4),
  ('dip-support-ring-support-hold', 'coordination', 3)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.tenet f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'methodology', f.id, v.weight
FROM (VALUES
  ('incline-push-up', 'resistance_calisthenics', 5),
  ('incline-push-up', 'core_body_control', 4),
  ('incline-push-up', 'eccentric_negative', 2),
  ('push-up', 'resistance_calisthenics', 5),
  ('push-up', 'core_body_control', 5),
  ('push-up', 'eccentric_negative', 3),
  ('tempo-eccentric-push-up', 'resistance_calisthenics', 5),
  ('tempo-eccentric-push-up', 'eccentric_negative', 5),
  ('tempo-eccentric-push-up', 'core_body_control', 4),
  ('dumbbell-kettlebell-floor-press', 'resistance_calisthenics', 5),
  ('dumbbell-kettlebell-floor-press', 'core_body_control', 3),
  ('dumbbell-bench-press', 'resistance_calisthenics', 5),
  ('dumbbell-bench-press', 'core_body_control', 3),
  ('half-kneeling-single-arm-press', 'resistance_calisthenics', 5),
  ('half-kneeling-single-arm-press', 'core_body_control', 5),
  ('half-kneeling-single-arm-press', 'balance_stability', 3),
  ('pike-push-up-box-pike-push-up', 'resistance_calisthenics', 5),
  ('pike-push-up-box-pike-push-up', 'balance_stability', 4),
  ('pike-push-up-box-pike-push-up', 'core_body_control', 4),
  ('dip-support-ring-support-hold', 'resistance_calisthenics', 5),
  ('dip-support-ring-support-hold', 'isometrics', 4),
  ('dip-support-ring-support-hold', 'balance_stability', 4)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.methodology f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'physiology', f.id, v.weight
FROM (VALUES
  ('incline-push-up', 'force_tissue_capacity', 4),
  ('incline-push-up', 'control_stability', 5),
  ('push-up', 'force_tissue_capacity', 5),
  ('push-up', 'control_stability', 4),
  ('tempo-eccentric-push-up', 'force_tissue_capacity', 5),
  ('tempo-eccentric-push-up', 'control_stability', 4),
  ('dumbbell-kettlebell-floor-press', 'force_tissue_capacity', 5),
  ('dumbbell-kettlebell-floor-press', 'control_stability', 3),
  ('dumbbell-bench-press', 'force_tissue_capacity', 5),
  ('dumbbell-bench-press', 'control_stability', 3),
  ('half-kneeling-single-arm-press', 'force_tissue_capacity', 5),
  ('half-kneeling-single-arm-press', 'control_stability', 5),
  ('pike-push-up-box-pike-push-up', 'force_tissue_capacity', 5),
  ('pike-push-up-box-pike-push-up', 'control_stability', 5),
  ('dip-support-ring-support-hold', 'force_tissue_capacity', 4),
  ('dip-support-ring-support-hold', 'control_stability', 5)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.physiological_emphasis f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'pattern', f.id, v.weight
FROM (VALUES
  ('incline-push-up', 'push', 5),
  ('incline-push-up', 'brace', 4),
  ('push-up', 'push', 5),
  ('push-up', 'brace', 5),
  ('tempo-eccentric-push-up', 'push', 5),
  ('tempo-eccentric-push-up', 'brace', 4),
  ('dumbbell-kettlebell-floor-press', 'push', 5),
  ('dumbbell-kettlebell-floor-press', 'brace', 3),
  ('dumbbell-bench-press', 'push', 5),
  ('dumbbell-bench-press', 'brace', 3),
  ('half-kneeling-single-arm-press', 'push', 5),
  ('half-kneeling-single-arm-press', 'brace', 5),
  ('pike-push-up-box-pike-push-up', 'push', 5),
  ('pike-push-up-box-pike-push-up', 'invert', 4),
  ('pike-push-up-box-pike-push-up', 'brace', 4),
  ('dip-support-ring-support-hold', 'push', 4),
  ('dip-support-ring-support-hold', 'hang', 3),
  ('dip-support-ring-support-hold', 'brace', 4)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.movement_pattern f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'equipment', f.id, v.weight
FROM (VALUES
  ('incline-push-up', 'box', 5),
  ('incline-push-up', 'bench', 4),
  ('incline-push-up', 'none', 2),
  ('push-up', 'none', 5),
  ('push-up', 'mat', 2),
  ('tempo-eccentric-push-up', 'none', 5),
  ('tempo-eccentric-push-up', 'box', 2),
  ('dumbbell-kettlebell-floor-press', 'dumbbell', 5),
  ('dumbbell-kettlebell-floor-press', 'kettlebell', 4),
  ('dumbbell-kettlebell-floor-press', 'mat', 2),
  ('dumbbell-bench-press', 'dumbbell', 5),
  ('dumbbell-bench-press', 'bench', 5),
  ('half-kneeling-single-arm-press', 'dumbbell', 5),
  ('half-kneeling-single-arm-press', 'kettlebell', 4),
  ('half-kneeling-single-arm-press', 'mat', 2),
  ('pike-push-up-box-pike-push-up', 'none', 4),
  ('pike-push-up-box-pike-push-up', 'box', 4),
  ('pike-push-up-box-pike-push-up', 'mat', 2),
  ('dip-support-ring-support-hold', 'rings', 4),
  ('dip-support-ring-support-hold', 'none', 3)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.equipment f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

INSERT INTO coaching.exercise_tag (exercise_id, facet_type, facet_id, weight)
SELECT e.id, 'body_region', f.id, v.weight
FROM (VALUES
  ('incline-push-up', 'shoulder', 5),
  ('incline-push-up', 'chest', 4),
  ('incline-push-up', 'core', 4),
  ('incline-push-up', 'triceps', 3),
  ('incline-push-up', 'wrist', 3),
  ('push-up', 'shoulder', 5),
  ('push-up', 'chest', 5),
  ('push-up', 'triceps', 4),
  ('push-up', 'core', 5),
  ('push-up', 'wrist', 3),
  ('tempo-eccentric-push-up', 'shoulder', 5),
  ('tempo-eccentric-push-up', 'chest', 5),
  ('tempo-eccentric-push-up', 'triceps', 4),
  ('tempo-eccentric-push-up', 'core', 4),
  ('tempo-eccentric-push-up', 'wrist', 3),
  ('dumbbell-kettlebell-floor-press', 'shoulder', 5),
  ('dumbbell-kettlebell-floor-press', 'chest', 5),
  ('dumbbell-kettlebell-floor-press', 'triceps', 4),
  ('dumbbell-kettlebell-floor-press', 'core', 3),
  ('dumbbell-bench-press', 'shoulder', 5),
  ('dumbbell-bench-press', 'chest', 5),
  ('dumbbell-bench-press', 'triceps', 4),
  ('dumbbell-bench-press', 'core', 3),
  ('half-kneeling-single-arm-press', 'shoulder', 5),
  ('half-kneeling-single-arm-press', 'core', 5),
  ('half-kneeling-single-arm-press', 'triceps', 4),
  ('half-kneeling-single-arm-press', 'hip', 3),
  ('pike-push-up-box-pike-push-up', 'shoulder', 5),
  ('pike-push-up-box-pike-push-up', 'core', 4),
  ('pike-push-up-box-pike-push-up', 'triceps', 4),
  ('pike-push-up-box-pike-push-up', 'wrist', 4),
  ('dip-support-ring-support-hold', 'shoulder', 5),
  ('dip-support-ring-support-hold', 'triceps', 5),
  ('dip-support-ring-support-hold', 'core', 4),
  ('dip-support-ring-support-hold', 'wrist', 3)
) AS v(slug, fkey, weight)
JOIN coaching.exercise e ON e.slug = v.slug
JOIN coaching.body_region f ON f.key = v.fkey
ON CONFLICT (exercise_id, facet_type, facet_id) DO UPDATE SET weight = EXCLUDED.weight;

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'youth_beginner' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('incline-push-up', 'Wall push-up or high incline with coach at side.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Incline push-up only — not floor push-up until earned.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Incline eccentric-only push-up with coach — not floor tempo.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Light floor press with coach — not heavy load.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'Floor press only — not bench press until earned.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Tall-kneeling or landmine press regression with coach.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Box pike with hands elevated — not feet-elevated pike.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Feet-assisted bar support hold only with coach.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_beginner';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'youth_beginner', 'youth beginner', 'baseline', v.guidance,
  CASE WHEN 'youth_beginner' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('incline-push-up', 'Wall push-up or high incline with coach at side.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Incline push-up only — not floor push-up until earned.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Incline eccentric-only push-up with coach — not floor tempo.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Light floor press with coach — not heavy load.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'Floor press only — not bench press until earned.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Tall-kneeling or landmine press regression with coach.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Box pike with hands elevated — not feet-elevated pike.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Feet-assisted bar support hold only with coach.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_beginner'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'youth_intermediate' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('incline-push-up', 'Moderate incline, 3 × 6–8 with full rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Floor push-up with coach supervision when incline is clean.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Incline tempo push-up, 3 × 4–6 with full rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Light DB floor press, 3 × 6–8 with full rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'Light DB bench with coach spotting.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Light half-kneeling press when push-up is clean.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Floor pike with shallow ROM and coach supervision.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Parallel bar support, 3 × 8–10 seconds with full rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_intermediate';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'youth_intermediate', 'youth intermediate', 'baseline', v.guidance,
  CASE WHEN 'youth_intermediate' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('incline-push-up', 'Moderate incline, 3 × 6–8 with full rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Floor push-up with coach supervision when incline is clean.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Incline tempo push-up, 3 × 4–6 with full rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Light DB floor press, 3 × 6–8 with full rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'Light DB bench with coach spotting.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Light half-kneeling press when push-up is clean.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Floor pike with shallow ROM and coach supervision.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Parallel bar support, 3 × 8–10 seconds with full rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'youth_intermediate'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'teen' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('incline-push-up', 'Progress to lower incline when plank line stays clean.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Progress reps or add tempo when form stays crisp.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Floor tempo push-up after push-up mastery.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Progress load when push-up and floor press form stay clean.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'DB bench after floor press mastery.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Progress load when trunk stays braced without lean-back.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Progress to feet on box when floor pike is clean.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Full support hold after push-up and pike mastery.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'teen';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'teen', 'teen', 'baseline', v.guidance,
  CASE WHEN 'teen' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('incline-push-up', 'Progress to lower incline when plank line stays clean.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Progress reps or add tempo when form stays crisp.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Floor tempo push-up after push-up mastery.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Progress load when push-up and floor press form stay clean.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'DB bench after floor press mastery.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Progress load when trunk stays braced without lean-back.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Progress to feet on box when floor pike is clean.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Full support hold after push-up and pike mastery.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'teen'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'adult_beginner' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('incline-push-up', 'High incline or wall push-up before floor work.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Incline regression until floor push-up is clean.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Incline tempo or eccentric-only regression.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Light DB floor press before bench press.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'Floor press before full ROM bench.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Tall-kneeling or lighter load before half-kneeling.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Hands-elevated pike or shallow floor pike.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Feet-assisted or shorter hold before full support.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_beginner';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'adult_beginner', 'adult beginner', 'baseline', v.guidance,
  CASE WHEN 'adult_beginner' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('incline-push-up', 'High incline or wall push-up before floor work.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Incline regression until floor push-up is clean.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Incline tempo or eccentric-only regression.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Light DB floor press before bench press.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'Floor press before full ROM bench.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Tall-kneeling or lighter load before half-kneeling.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Hands-elevated pike or shallow floor pike.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Feet-assisted or shorter hold before full support.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_beginner'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'adult_advanced' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('incline-push-up', 'Lower incline or weighted vest progression when earned.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Weighted vest, tempo pause, or floor press progression.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Floor tempo with 4-second eccentric or pause at bottom.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Heavier floor press with tempo pause before bench.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'Heavier DB bench with tempo pause or neutral grip.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Heavier single-arm press with pause at top.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Feet-elevated pike with tempo pause at bottom.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Ring support hold or weighted support progression.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_advanced';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'adult_advanced', 'adult advanced', 'baseline', v.guidance,
  CASE WHEN 'adult_advanced' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('incline-push-up', 'Lower incline or weighted vest progression when earned.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Weighted vest, tempo pause, or floor press progression.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Floor tempo with 4-second eccentric or pause at bottom.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Heavier floor press with tempo pause before bench.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'Heavier DB bench with tempo pause or neutral grip.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Heavier single-arm press with pause at top.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Feet-elevated pike with tempo pause at bottom.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Ring support hold or weighted support progression.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'adult_advanced'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'older_adult' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('incline-push-up', 'Higher incline, conservative reps, generous rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Incline push-up or partial ROM floor push with generous rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Incline tempo with generous rest and reduced reps.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Moderate load floor press with generous rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'Moderate load with spotter and generous rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Seated or tall-kneeling press with conservative load.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Hands-elevated pike with conservative ROM.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Feet-assisted bar support with conservative hold time.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'older_adult';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'older_adult', 'older adult', 'baseline', v.guidance,
  CASE WHEN 'older_adult' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('incline-push-up', 'Higher incline, conservative reps, generous rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Incline push-up or partial ROM floor push with generous rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Incline tempo with generous rest and reduced reps.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Moderate load floor press with generous rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'Moderate load with spotter and generous rest.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Seated or tall-kneeling press with conservative load.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Hands-elevated pike with conservative ROM.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Feet-assisted bar support with conservative hold time.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'older_adult'
);

UPDATE coaching.exercise_scaling_profile sp SET
  load_guidance = v.guidance,
  gender_specific_notes = CASE WHEN 'pregnancy_postpartum' = 'adult_beginner' THEN v.gender_notes ELSE sp.gender_specific_notes END
FROM (VALUES
  ('incline-push-up', 'Elevated surface; avoid deep prone compression if uncomfortable.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Incline or elevated push-up if prone loading is uncomfortable.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Incline tempo if prone floor work is uncomfortable.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Reduce load; monitor supine symptoms — use incline press if needed.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'Reduce load and ROM; use floor press if supine is uncomfortable.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Reduce load and ROM; avoid max overhead intent unless cleared.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Avoid deep inverted loading unless cleared; use hands-elevated regression.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Avoid unsupported ring work unless cleared; use feet-assisted bar support.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE sp.exercise_id = e.id AND sp.cohort_key = 'pregnancy_postpartum';

INSERT INTO coaching.exercise_scaling_profile (exercise_id, cohort_key, label, scale_direction, load_guidance, gender_specific_notes)
SELECT e.id, 'pregnancy_postpartum', 'pregnancy postpartum', 'baseline', v.guidance,
  CASE WHEN 'pregnancy_postpartum' = 'adult_beginner' THEN v.gender_notes ELSE NULL END
FROM (VALUES
  ('incline-push-up', 'Elevated surface; avoid deep prone compression if uncomfortable.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('push-up', 'Incline or elevated push-up if prone loading is uncomfortable.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('tempo-eccentric-push-up', 'Incline tempo if prone floor work is uncomfortable.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-kettlebell-floor-press', 'Reduce load; monitor supine symptoms — use incline press if needed.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dumbbell-bench-press', 'Reduce load and ROM; use floor press if supine is uncomfortable.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('half-kneeling-single-arm-press', 'Reduce load and ROM; avoid max overhead intent unless cleared.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('pike-push-up-box-pike-push-up', 'Avoid deep inverted loading unless cleared; use hands-elevated regression.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.'),
  ('dip-support-ring-support-hold', 'Avoid unsupported ring work unless cleared; use feet-assisted bar support.', 'No default sex-based adjustment. Scale by movement quality, load tolerance, goals, and symptoms rather than gender alone.')
) AS v(slug, guidance, gender_notes)
JOIN coaching.exercise e ON e.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM coaching.exercise_scaling_profile sp
  WHERE sp.exercise_id = e.id AND sp.cohort_key = 'pregnancy_postpartum'
);

-- Why-layer education
INSERT INTO coaching.education_content (
  entity_type, entity_key, entity_id, title, short_summary,
  what_it_is, why_it_works, why_it_matters, why_it_goes_here,
  programming_guidance, common_misuse, scaling_guidance
)
SELECT
  'exercise', e.slug, e.id, e.name, e.card_summary,
  e.description,
  v.why_works,
  'Develops tagged tenets and physiological qualities for athletic development.',
  v.why_here,
  v.best_placement,
  v.misuse,
  v.scale_guidance
FROM (VALUES
  ('incline-push-up', 'Incline push-ups reduce the percentage of body weight on the hands while preserving the closed-chain pressing pattern. They build chest, shoulder, and triceps force capacity with trunk bracing demand relevant to tumbling, vaulting, and hand support without requiring floor push-up competency first.', 'Belongs in pushup_regression (431) — foundational Capacity horizontal push before floor push-up and loaded press work.', 'Primary entry in pushup_regression after Output; before floor push-up, loaded press, or inverted push when horizontal push mechanics are still developing.', 'Upper-body push Capacity builds pressing reserve with controlled load and full rest — not explosive Output pushes or high-rep Fitness circuits. Do not use as high-rep conditioning, allow hip sag every rep, or lower incline before plank line and scapular control are clean.', 'Regress to wall push-up or higher incline; progress to lower incline or floor push-up only when ribs stay down and elbows track. Hypermobility athletes need active serratus and rib control — no passive shoulder hang.'),
  ('push-up', 'The floor push-up loads the entire pressing chain — chest, shoulders, triceps, and trunk stabilizers — in a closed-chain pattern directly relevant to tumbling, vault push-off, and hand support. Capacity intent with tempo and full rest builds tissue reserve without the speed demand of Output plyometric pushes.', 'Belongs in horizontal_push_strength (432) — primary Capacity floor push after incline regression competency.', 'horizontal_push_strength after incline push-up competency; before tempo eccentric, floor press, or inverted push when floor push quality is established.', 'Upper-body push Capacity builds pressing reserve with controlled load and full rest — not explosive Output pushes or high-rep Fitness circuits. Do not rep out to failure with short rest, allow hip sag, or prescribe before incline push-up control is earned.', 'Regress to incline push-up; progress to tempo eccentric, weighted vest, or floor press only when plank line and elbow tracking stay clean. Use 45° elbow angle cue — not flared 90°.'),
  ('tempo-eccentric-push-up', 'Tempo and eccentric-emphasis push-ups increase time under tension on chest, shoulders, and triceps during the lowering phase. This builds tissue capacity and deceleration-relevant pressing strength when dosed conservatively with full rest — distinct from explosive Output push variations.', 'Belongs in push_eccentric (433) — eccentric Capacity push after floor push-up competency.', 'push_eccentric after floor push-up competency; useful when athletes need eccentric pressing strength without adding external load.', 'Upper-body push Capacity builds pressing reserve with controlled load and full rest — not explosive Output pushes or high-rep Fitness circuits. Do not bounce at bottom, rush the eccentric, prescribe before push-up control, or stack high volume before tumbling Output.', 'Regress to incline tempo push-up or eccentric-only to elevated surface; shorten eccentric duration before reducing incline height. Lower rep count than standard push-up.'),
  ('dumbbell-kettlebell-floor-press', 'The floor press limits shoulder extension ROM at the bottom, reducing anterior shoulder stress while still loading chest and triceps. It builds horizontal pressing force capacity with a clear depth reference and is a natural bridge from push-up to bench press progressions.', 'Belongs in horizontal_push_strength (432) — loaded horizontal Capacity push after push-up competency, before bench press.', 'horizontal_push_strength after push-up competency; before dumbbell bench press when athletes need loaded horizontal push with controlled ROM.', 'Upper-body push Capacity builds pressing reserve with controlled load and full rest — not explosive Output pushes or high-rep Fitness circuits. Do not bounce upper arms off floor, arch excessively, or prescribe before push-up control. Not a high-rep burnout set.', 'Regress to lighter load or neutral-grip dumbbells; progress load only when elbows track and trunk stays braced. Use tempo before load jumps.'),
  ('dumbbell-bench-press', 'Dumbbell bench press allows independent arm loading and natural wrist path while building chest, shoulder, and triceps force capacity through full ROM. It progresses horizontal pressing reserve beyond bodyweight and floor press when dosed with tempo and full rest.', 'Belongs in horizontal_push_strength (432) — loaded horizontal Capacity push after floor press or push-up competency.', 'horizontal_push_strength after floor press or push-up competency; primary loaded horizontal push when bench setup is available and shoulder tolerance allows full ROM.', 'Upper-body push Capacity builds pressing reserve with controlled load and full rest — not explosive Output pushes or high-rep Fitness circuits. Do not bounce off chest, use excessive arch, or prescribe before floor press or push-up control. Not a metcon with short rest.', 'Regress to floor press or lighter dumbbells; progress load only when elbows track and trunk stays braced. Use spotter or self-rack safely on heavy sets.'),
  ('half-kneeling-single-arm-press', 'Half-kneeling removes lower-body drive and increases demand on trunk anti-extension and anti-rotation while pressing overhead. It builds vertical pressing force capacity and shoulder stability relevant to handstand, tumbling overhead, and bar path control when progressed from horizontal push competency.', 'Belongs in vertical_push_strength (434) — primary Capacity vertical push after horizontal push base.', 'vertical_push_strength after horizontal push competency; primary vertical push entry before overhead barbell work when anti-extension and shoulder control are priorities.', 'Upper-body push Capacity builds pressing reserve with controlled load and full rest — not explosive Output pushes or high-rep Fitness circuits. Do not lean back to finish reps, use leg drive, or prescribe before push-up control. Not a push-press or jerk pattern.', 'Regress to tall-kneeling or lighter load; shorten ROM before adding weight. Complete all reps one side before switching or alternate by set — be consistent.'),
  ('pike-push-up-box-pike-push-up', 'Pike push-ups increase shoulder flexion demand and shift load toward deltoids and triceps in an inverted pressing angle relevant to handstand push-up progressions. Box elevation adjusts difficulty while preserving Capacity intent with controlled reps and full rest.', 'Belongs in inverted_push_strength (435) — inverted Capacity push after horizontal push base, before dip support and handstand Output.', 'inverted_push_strength after push-up and optional vertical press competency; before dip support or handstand Output when inverted push control is the goal.', 'Upper-body push Capacity builds pressing reserve with controlled load and full rest — not explosive Output pushes or high-rep Fitness circuits. Do not collapse into forward fold without shoulder load, rep out with short rest, or prescribe before push-up control. Not a handstand skill substitute.', 'Regress to box pike with hands elevated or feet on floor with shallow ROM; progress to feet-elevated pike only when head path and shoulder control stay clean. Use tempo before ROM depth increases.'),
  ('dip-support-ring-support-hold', 'Top-of-dip support holds train isometric pressing strength, scapular depression and protraction, and trunk bracing at a position relevant to ring work, bar support, and tumbling hand support. Capacity dosing with short holds and full rest builds support reserve before dynamic dip or ring Output work.', 'Belongs in support_strength (436) — isometric Capacity support after horizontal and inverted push base, before dip eccentrics or ring Output.', 'support_strength after push-up and pike push-up competency; end of push cluster or before dip eccentric progressions when support strength is the limiting factor.', 'Upper-body push Capacity builds pressing reserve with controlled load and full rest — not explosive Output pushes or high-rep Fitness circuits. Do not turn into high-rep dip eccentrics, allow shoulder shrug or elbow unlock, or prescribe before push-up and pike competency. Not a Control isometric in a warm-up circuit.', 'Regress to parallel bar support with feet assisted or shorter hold; progress hold time before adding ring instability. Use 10-second default holds with full rest.')
) AS v(slug, why_works, why_here, best_placement, misuse, scale_guidance)
JOIN coaching.exercise e ON e.slug = v.slug
ON CONFLICT (entity_type, entity_key, entity_id) DO UPDATE SET
  title = EXCLUDED.title,
  short_summary = EXCLUDED.short_summary,
  what_it_is = EXCLUDED.what_it_is,
  why_it_works = EXCLUDED.why_it_works,
  why_it_goes_here = EXCLUDED.why_it_goes_here,
  programming_guidance = EXCLUDED.programming_guidance,
  common_misuse = EXCLUDED.common_misuse,
  scaling_guidance = EXCLUDED.scaling_guidance,
  updated_at = now();

-- Upper-body push Capacity cluster validation education
INSERT INTO coaching.education_content (
  entity_type, entity_key, entity_id, title, short_summary,
  what_it_is, why_it_matters, programming_guidance, common_misuse
)
VALUES (
  'validation_rule',
  'capacity_push_readiness',
  NULL,
  'Upper-Body Push Capacity without stealing hand-support quality',
  'Push Capacity needs intentional load, controlled reps, and full rest — not explosive Output pushes or high-rep Fitness circuits.',
  'Upper-body push cluster: incline push-up, push-up, tempo/eccentric push-up, floor press, dumbbell bench press, half-kneeling single-arm press, pike push-up, and dip/ring support hold.',
  'Pressing strength supports push-ups, crawling, hand support, cartwheels, handstands, dips, rings, and overhead work. Poor placement or wrist/shoulder fatigue reduces tumbling and hand-support skill quality.',
  'Place after Output unless strength-priority; master incline/floor push-up before pike and ring support; regress on wrist/shoulder pain; keep eccentric push volume conservative before hand-support skill.',
  'Do not program high-rep push circuits before handstand/tumbling skill, use pike push-ups without floor push-up competency, or finish sloppy push-up reps for Capacity intent.'
)
ON CONFLICT (entity_type, entity_key, entity_id) DO UPDATE SET
  title = EXCLUDED.title,
  short_summary = EXCLUDED.short_summary,
  what_it_is = EXCLUDED.what_it_is,
  why_it_matters = EXCLUDED.why_it_matters,
  programming_guidance = EXCLUDED.programming_guidance,
  common_misuse = EXCLUDED.common_misuse,
  updated_at = now();
