-- USA Gymnastics Youth Acrobatics & Tumbling compulsory Acro elements,
-- Levels 3-5 (28 cards). Completes the 41-element Level 1-5 Acro inventory.
-- Descriptions and instruction are original summaries; official Code controls.

WITH source_data (
  name, slug, level_name, segment_number, step_number, official_notation,
  description, instructions, athlete_cue, coach_focus,
  prerequisite_slug, next_name, next_slug, source_page
) AS (
  VALUES
    ('A&T L3 Acro 1 — Hand-to-hand Shoulder Stand', 'usag-at-l3-acro-1-shoulder-stand',
      'Youth A&T Level 3', 1, 1, '1-1; FC; H-H; GRD-SHD; VER-VER; 2FT; NO TWIST',
      'One top and one base use full-contact hand-to-hand support to rise from ground to a two-foot vertical shoulder stand without twist.',
      'Base faces front and establishes a stable hand connection. Partners dip together, keep the top close to the base''s center, and finish standing at shoulder level before moving on.',
      'Hold hands, rise close, and finish tall with no turn.',
      'One base starts/catches, full contact remains, both athletes start/end vertical, two-foot shoulder-level finish, no twist, and both groups synchronize.',
      'usag-at-l2-acro-8-cradle-barrel-roll', 'Single-base front support', 'usag-at-l3-acro-2-single-base-front-support', 52),
    ('A&T L3 Acro 2 — Single-base Front Support', 'usag-at-l3-acro-2-single-base-front-support',
      'Youth A&T Level 3', 1, 2, '1-1; FC; SHD-EXT; VER-VER; VER HSUP “I”',
      'From shoulder level, one base extends a vertical top into a straight-body front-support position.',
      'Base stays front-facing and lifts through a stable shoulder line. Top presses actively into the support, joins the legs, and reaches a straight horizontal body before the descent.',
      'Push into the base and stretch one long front-support line.',
      'Single base throughout, shoulder-to-extension height change, front-facing direction, straight “I” front support, full contact, and controlled extension.',
      'usag-at-l3-acro-1-shoulder-stand', 'Front-support dismount', 'usag-at-l3-acro-3-front-support-dismount', 52),
    ('A&T L3 Acro 3 — Single-base Front-support Dismount', 'usag-at-l3-acro-3-front-support-dismount',
      'Youth A&T Level 3', 1, 3, '1-1; FC; EXT-GRD; VER-VER; HSUP “I”-2FT; NO TWIST',
      'One base lowers the top from extended straight front support to a two-foot vertical ground landing without twist.',
      'Begin only after the support line is complete. Base lowers through the top''s center; top remains braced, brings the feet underneath, and finishes upright without turning.',
      'Stay long as you lower, then place both feet under you.',
      'Extended “I” start, single-base full contact, no twist, two-foot landing, upright posture, and segment ends with the top on ground.',
      'usag-at-l3-acro-2-single-base-front-support', 'Half-up shoulder stand', 'usag-at-l3-acro-4-half-up-shoulder-stand', 52),
    ('A&T L3 Acro 4 — Single-base Half-up Shoulder Stand', 'usag-at-l3-acro-4-half-up-shoulder-stand',
      'Youth A&T Level 3', 2, 4, '1-1; FC; H-H; GRD-SHD; VER-VER; 2FT; TWIST 180',
      'One base lifts a hand-connected top from ground to shoulder stand while the top completes a 180° twist.',
      'Base faces left and keeps the hand connection close. Partners coordinate lift and half turn so the top arrives vertical on two feet at shoulder level.',
      'Lift close, turn one half, and stop tall on the shoulders.',
      'One base starts/finishes, full hand-to-hand contact, exact half twist on ascent, left-facing base, and secure two-foot shoulder stand.',
      'usag-at-l3-acro-3-front-support-dismount', 'Shoulder stand to inverted extension', 'usag-at-l3-acro-5-shoulder-to-invert', 52),
    ('A&T L3 Acro 5 — Shoulder Stand to Inverted Extension', 'usag-at-l3-acro-5-shoulder-to-invert',
      'Youth A&T Level 3', 2, 5, '1-2; FC; SHD-EXT; VER-INV NON HS; INV 180',
      'A top transfers from a one-base shoulder stand to two bases at extension, completing a 180° inversion into a non-handstand inverted position.',
      'Starting base controls shoulders while the receiving base establishes hand contact. Lift through center and coordinate the inversion without releasing or drifting.',
      'Stay connected, invert through the middle, and show the extended upside-down shape.',
      'One base starts/two catch, full contact, shoulder-to-extension rise, 180° inversion, inverted non-handstand recognition, and secure finish contacts.',
      'usag-at-l3-acro-4-half-up-shoulder-stand', 'Two-base inverted straight-down', 'usag-at-l3-acro-6-invert-straight-down', 52),
    ('A&T L3 Acro 6 — Two-base Inverted Straight-down', 'usag-at-l3-acro-6-invert-straight-down',
      'Youth A&T Level 3', 2, 6, '2-2; FC; EXT-GRD; INV NON HS-VER; INV 180; NO TWIST',
      'Two bases lower an extended inverted non-handstand top straight through center to a vertical ground landing, completing the inversion without twist.',
      'Keep both shoulder contacts even, lower on one count, and allow the top to rotate through the required inverted pathway so the feet arrive underneath without a lateral turn.',
      'Hold tight, travel straight down the middle, and land over two feet.',
      'Two bases throughout, full contact, extended-to-ground pathway, 180° inversion, no twist on descent, vertical landing, and synchronized segment finish.',
      'usag-at-l3-acro-5-shoulder-to-invert', 'Prep-level liberty', 'usag-at-l3-acro-7-prep-liberty', 52),
    ('A&T L3 Acro 7 — Prep-level Liberty', 'usag-at-l3-acro-7-prep-liberty',
      'Youth A&T Level 3', 3, 7, '3-3; FC; GRD-SHD; VER-VER; 1FT',
      'Three bases lift a top from ground to a one-foot liberty at shoulder-level prep.',
      'Bases build a level single-foot platform and lift together. Top transfers weight over the supporting foot, raises the free leg to liberty, and keeps the chest vertical.',
      'Stand over one foot, lift the liberty, and stay tall.',
      'Three bases start/end, full contact, ground-to-shoulder height, clear one-foot liberty, vertical posture, and matched group timing.',
      'usag-at-l3-acro-6-invert-straight-down', 'Liberty to two-foot prep', 'usag-at-l3-acro-8-lib-to-two-foot', 53),
    ('A&T L3 Acro 8 — Liberty to Two-foot Prep', 'usag-at-l3-acro-8-lib-to-two-foot',
      'Youth A&T Level 3', 3, 8, '3-3; FC; SHD-SHD; VER-VER; 1FT-2FT',
      'At shoulder level, the top transitions from a one-foot liberty to a vertical two-foot prep.',
      'Bases keep the platform level as the top lowers the free foot beside the supporting foot. Weight transfers smoothly and both feet finish evenly loaded.',
      'Lower the free foot softly and stand evenly on two feet.',
      'Shoulder-level position maintained, no release, controlled one-foot-to-two-foot transfer, vertical top line, and no base adjustment.',
      'usag-at-l3-acro-7-prep-liberty', 'Full-twist cradle', 'usag-at-l3-acro-9-full-twist-cradle', 53),
    ('A&T L3 Acro 9 — Prep Full-twist to Cradle', 'usag-at-l3-acro-9-full-twist-cradle',
      'Youth A&T Level 3', 3, 9, '3-3; R; SHD-CRDL; VER-HOZ; 2FT; TWIST 360',
      'Three bases release a two-foot prep top through a 360° twist to a horizontal cradle catch.',
      'Use a shared dip and vertical release. Top stays tight through one full turn, opens to the cradle shape, and waits for a high three-base catch before ground dismount.',
      'Ride up, turn one full, open horizontal, and wait for the catch.',
      'Shoulder-level two-foot start, clear release, exactly 360° twist, horizontal cradle finish, secure three-base catch, and simultaneous groups.',
      'usag-at-l3-acro-8-lib-to-two-foot', 'Toe pitch to prep', 'usag-at-l4-acro-1-toe-pitch-prep', 53),

    ('A&T L4 Acro 1 — Toe Pitch to Prep', 'usag-at-l4-acro-1-toe-pitch-prep',
      'Youth A&T Level 4', 1, 1, '2-2; R; H-F; GRD-SHD; VER-VER; 2FT',
      'Two bases assist and release a toe pitch from ground, catching the top standing on two feet at shoulder level.',
      'Primary base loads the top''s foot in the hands while the front secondary assists the rise. Both release; primary catches the feet and rear secondary catches ankles at primary-base shoulder height.',
      'Drive through the loaded foot, rise vertical, and place both feet for prep.',
      'Correct front and rear secondary roles, visible release, vertical top, two-foot shoulder-level catch, hands/ankles caught securely, and synchronized groups.',
      'usag-at-l3-acro-9-full-twist-cradle', 'Prep pop-off', 'usag-at-l4-acro-2-prep-popoff', 60),
    ('A&T L4 Acro 2 — Prep Pop-off', 'usag-at-l4-acro-2-prep-popoff',
      'Youth A&T Level 4', 1, 2, '2-2; R; SHD-GRD; VER-VER; 2FT',
      'Two bases release a vertical top from shoulder-level prep and catch the top into a two-foot ground landing.',
      'Primary and rear base initiate the pop. Keep lift vertical; primary and front base meet the top for landing support and absorb together.',
      'Pop straight up, stay tall, and land over two feet.',
      'Correct bases initiate and catch, visible release, shoulder-to-ground height, vertical shape, two-foot landing, and no travel.',
      'usag-at-l4-acro-1-toe-pitch-prep', 'Extended straddle front support', 'usag-at-l4-acro-3-extended-straddle-support', 60),
    ('A&T L4 Acro 3 — Extended Straddle Front Support', 'usag-at-l4-acro-3-extended-straddle-support',
      'Youth A&T Level 4', 2, 3, '2-2; FC; GRD-EXT; VER-VER; VER HSUP “S”',
      'Two bases lift a top from ground to an extended vertical hand-support straddle position.',
      'Build the hand platform first, lift through center, and have the top press actively with straight arms while opening an even extended straddle.',
      'Push through the hands, lift the hips, and stretch a wide even straddle.',
      'Two-base full contact, ground-to-extension rise, legal hand support, clear “S” straddle, extended knees/toes, and square structure.',
      'usag-at-l4-acro-2-prep-popoff', 'Straddle support to inversion', 'usag-at-l4-acro-4-straddle-to-invert', 60),
    ('A&T L4 Acro 4 — Straddle Support to Inverted Non-handstand', 'usag-at-l4-acro-4-straddle-to-invert',
      'Youth A&T Level 4', 2, 4, '2-2; FC; EXT-EXT; VER HSUP “S”-INV NON HS; INV 180',
      'At extended level, the top transitions through 180° of inversion from straddle hand support to an inverted non-handstand position.',
      'Bases maintain height and receive the changing contacts while the top closes and rotates through center with body tension.',
      'Stay high, move through the center, and finish the upside-down non-handstand shape.',
      'Extension height maintained, full contact, recognizable straddle start, 180° inversion, clear non-handstand finish, and controlled hand/contact change.',
      'usag-at-l4-acro-3-extended-straddle-support', 'Inverted straight-down', 'usag-at-l4-acro-5-invert-straight-down', 60),
    ('A&T L4 Acro 5 — Extended Invert Straight-down', 'usag-at-l4-acro-5-invert-straight-down',
      'Youth A&T Level 4', 2, 5, '2-2; FC; EXT-GRD; INV NON HS-VER; NO TWIST',
      'Two bases lower the extended inverted top straight through center to a vertical ground landing without twist.',
      'Keep shoulder contacts even and lower at the same speed. Top stays braced, brings feet underneath, and finishes upright between bases.',
      'Stay tight, lower straight, and land between the bases.',
      'Extended inverted start, two-base full contact, centered descent, no twist, vertical ground finish, and safe supported landing.',
      'usag-at-l4-acro-4-straddle-to-invert', 'Extended liberty', 'usag-at-l4-acro-6-extended-liberty', 60),
    ('A&T L4 Acro 6 — Extended Liberty', 'usag-at-l4-acro-6-extended-liberty',
      'Youth A&T Level 4', 3, 6, '3-3; FC; GRD-EXT; VER-VER; 1FT NO FLEX',
      'Three bases lift a top from ground to an extended one-foot liberty with no held-leg flex position.',
      'Bases present a stable single-foot platform and extend together. Top stacks over the support foot, places the free leg in a legal no-flex liberty, and faces left as prescribed.',
      'Stand over one foot, lift the liberty, and reach tall at extension.',
      'Left-facing top, full-contact ground-to-extension rise, one-foot no-flex shape, straight supporting leg, level base structure, and synchronized arrival.',
      'usag-at-l4-acro-5-invert-straight-down', 'Liberty foot-down transition', 'usag-at-l4-acro-7-liberty-foot-down', 60),
    ('A&T L4 Acro 7 — Extended Liberty Foot-down', 'usag-at-l4-acro-7-liberty-foot-down',
      'Youth A&T Level 4', 3, 7, 'Extended liberty: left foot lowers beside right foot',
      'At extension, the top lowers the left free foot beside the right supporting foot while bases maintain the structure.',
      'Keep weight centered over the standing foot until the moving foot reaches the platform. Bases track pressure evenly and avoid dropping height.',
      'Lower the left foot softly and stay tall at extension.',
      'Extension height, controlled left-foot pathway, feet finish side by side, no wobble or base step, and synchronized transition.',
      'usag-at-l4-acro-6-extended-liberty', 'Extended arabesque', 'usag-at-l4-acro-8-extended-arabesque', 60),
    ('A&T L4 Acro 8 — Extended Arabesque', 'usag-at-l4-acro-8-extended-arabesque',
      'Youth A&T Level 4', 3, 8, 'At extension: left leg extends to arabesque',
      'At extended height, the top shifts to the required supporting leg and lengthens the left leg backward into arabesque.',
      'Bases keep the platform quiet as the top transfers weight, lifts the chest, and reaches the free leg long without opening the hips off square.',
      'Lift the chest and reach the left leg long behind you.',
      'Extended level maintained, clear one-leg support, long left-leg arabesque, square hips/shoulders, stable bases, and identical group timing.',
      'usag-at-l4-acro-7-liberty-foot-down', 'No-twist cradle', 'usag-at-l4-acro-9-no-twist-cradle', 60),
    ('A&T L4 Acro 9 — Extended No-twist Cradle', 'usag-at-l4-acro-9-no-twist-cradle',
      'Youth A&T Level 4', 3, 9, '3-3; R; EXT-CRDL; VER-HOZ; 1FT; NO TWIST',
      'Three bases release the top from the one-foot extended position to a horizontal cradle without twist, then quarter-turn the group to front.',
      'Dip together beneath the one-foot top, release vertically, have the top close to the horizontal cradle shape without twisting, catch high, then execute the prescribed group quarter turn.',
      'Ride up with no twist, open to cradle, and wait for the group turn.',
      'One-foot extended start, visible release, no top twist, horizontal cradle catch, secure bases, and quarter turn performed by group after catch.',
      'usag-at-l4-acro-8-extended-arabesque', 'Assisted toe pitch', 'usag-at-l5-acro-1-assisted-toe-pitch', 60),

    ('A&T L5 Acro 1 — Assisted Toe Pitch to Shoulder Stand', 'usag-at-l5-acro-1-assisted-toe-pitch',
      'Youth A&T Level 5', 1, 1, '2-1; R; H-F; GRD-SHD; VER-VER; 2FT',
      'Two bases initiate an assisted toe pitch; after release, one primary base catches the top standing on two feet at shoulder level.',
      'Primary loads the top''s foot while the secondary assists from floor. Coordinate the drive and release so the top rises vertically and places both feet securely in the primary base''s hands.',
      'Drive through the foot, rise tall, and land both feet on the platform.',
      'Two bases start/one catches, correct foot contact, clear release, vertical flight, two-foot shoulder-level finish, and secure primary-base catch.',
      'usag-at-l4-acro-9-no-twist-cradle', 'Back tuck off shoulder level', 'usag-at-l5-acro-2-back-tuck-off', 68),
    ('A&T L5 Acro 2 — Back Tuck off Shoulder Level', 'usag-at-l5-acro-2-back-tuck-off',
      'Youth A&T Level 5', 1, 2, '1-2; R; SHD-GRD; VER-VER; Flip 360 B (Tuck)',
      'The primary base initiates a released 360° backward tucked salto from shoulder level; primary and secondary bases support the ground landing.',
      'Use a vertical platform drive, allow the top to lift before closing to tuck, track rotation without chasing, and meet the opened top high enough to guide a two-foot landing.',
      'Ride up, tuck fast, open to the bases, and land tall.',
      'Shoulder-level vertical start, clear release, complete 360° back tuck, adequate amplitude, primary/secondary landing assistance, and controlled feet-first finish.',
      'usag-at-l5-acro-1-assisted-toe-pitch', 'Single-base straddle hold', 'usag-at-l5-acro-3-single-base-straddle', 68),
    ('A&T L5 Acro 3 — Single-base Extended Straddle Hold', 'usag-at-l5-acro-3-single-base-straddle',
      'Youth A&T Level 5', 2, 3, '1-1; FC; H-H; GRD-EXT; VER-HSUP “S”',
      'One base lifts a hand-connected top from ground to an extended straddle hand-support position.',
      'Base faces left, maintains the hand-to-hand connection, and extends through a stacked shoulder line. Top presses actively and opens to a square, extended straddle.',
      'Push the hands, lift the hips, and stretch the straddle evenly.',
      'Single base, full hand contact, ground-to-extension height, left-facing primary, clear hand-support “S” position, straight legs, and control.',
      'usag-at-l5-acro-2-back-tuck-off', 'Straddle pop-over to inversion', 'usag-at-l5-acro-4-straddle-popover', 68),
    ('A&T L5 Acro 4 — Straddle Pop-over to Inversion', 'usag-at-l5-acro-4-straddle-popover',
      'Youth A&T Level 5', 2, 4, '1-2; FC; EXT-EXT; HSUP “S”-INV NON HS',
      'From a single-base extended straddle hold, the top pops over to an inverted non-handstand position caught by two bases at extension.',
      'Starting base creates lift rather than throwing away; second base receives the changing contact as the top closes and passes through center into the inverted shape.',
      'Push up from the straddle, pass through the middle, and finish tight upside down.',
      'One base starts/two finish, extension height retained, full contact as coded, recognizable straddle start and inverted non-handstand finish, and no drift.',
      'usag-at-l5-acro-3-single-base-straddle', 'Inverted hand switch', 'usag-at-l5-acro-5-invert-hand-switch', 68),
    ('A&T L5 Acro 5 — Extended Inverted Hand Switch', 'usag-at-l5-acro-5-invert-hand-switch',
      'Youth A&T Level 5', 2, 5, '2-1; FC; EXT-EXT; INV NON HS-INV NON HS',
      'At extension in an inverted non-handstand position, one base releases so the top transfers hand contact to the other base''s wrist.',
      'Stabilize the inversion before changing contact. Receiving base presents the wrist; releasing base removes only the coded hand after the top establishes secure pressure.',
      'Freeze the inversion, find the new wrist, then release the old hand.',
      'Extended height and inverted shape maintained, correct first-base release, secure hand-to-wrist transfer, no unplanned contact loss, and synchronized groups.',
      'usag-at-l5-acro-4-straddle-popover', 'Single-base inverted pop-off', 'usag-at-l5-acro-6-invert-popoff', 68),
    ('A&T L5 Acro 6 — Single-base Inverted Pop-off', 'usag-at-l5-acro-6-invert-popoff',
      'Youth A&T Level 5', 2, 6, '1-1; R; EXT-GRD; INV NON HS-VER',
      'One base releases the extended inverted top to a vertical ground landing and assists the landing from the side.',
      'Direct the pop upward and through center. Top maintains tension, rotates feet underneath, and opens to the side-catching base for a controlled landing.',
      'Push away, bring feet under, and meet the side catch tall.',
      'One base starts/catches, clear release, extension-to-ground pathway, inverted-to-vertical rotation, side landing assistance, and stable finish.',
      'usag-at-l5-acro-5-invert-hand-switch', 'Extended liberty', 'usag-at-l5-acro-7-extended-liberty', 68),
    ('A&T L5 Acro 7 — Extended Liberty', 'usag-at-l5-acro-7-extended-liberty',
      'Youth A&T Level 5', 3, 7, '3-3; FC; GRD-EXT; VER-VER; 1FT NO FLEX',
      'Three bases lift a top from ground to a no-flex one-foot liberty at extension facing left.',
      'Build a level platform, extend together, and have the top stack the supporting leg, pelvis, ribs, and head while showing the legal liberty free-leg position.',
      'Stand over one foot and reach tall through the liberty.',
      'Left-facing direction, three-base full contact, extension reached, one-foot no-flex liberty, straight supporting leg, square stable structure, and synchronization.',
      'usag-at-l5-acro-6-invert-popoff', 'Extended liberty foot-down', 'usag-at-l5-acro-8-liberty-foot-down', 68),
    ('A&T L5 Acro 8 — Extended Liberty Foot-down', 'usag-at-l5-acro-8-liberty-foot-down',
      'Youth A&T Level 5', 3, 8, 'Extended liberty: left foot lowers beside right foot',
      'At extension, the top lowers the left free foot beside the right support foot without a height change.',
      'Center weight over the right foot, lower the left foot with control, and finish evenly loaded while bases keep the platform level.',
      'Lower the left foot softly and stay tall.',
      'Extension maintained, correct left-foot movement, feet finish together, stable bases, no extra adjustment, and groups transition together.',
      'usag-at-l5-acro-7-extended-liberty', 'Extended arabesque 60°', 'usag-at-l5-acro-9-extended-arabesque', 68),
    ('A&T L5 Acro 9 — Extended Arabesque 60°', 'usag-at-l5-acro-9-extended-arabesque',
      'Youth A&T Level 5', 3, 9, 'At extension: left leg arabesque, 60° minimum',
      'At extended height, the top reaches the left leg backward into an arabesque of at least 60°.',
      'Transfer weight without dropping the platform, lift the chest, keep hips square, and lengthen the left leg to or above the minimum angle.',
      'Chest up, left leg long, and show at least sixty degrees.',
      'Extension height, correct leg, minimum 60° arabesque, straight knee and pointed foot, square posture, and stable synchronized groups.',
      'usag-at-l5-acro-8-liberty-foot-down', 'Full-down cradle', 'usag-at-l5-acro-10-full-down-cradle', 68),
    ('A&T L5 Acro 10 — Extended Full-down Cradle', 'usag-at-l5-acro-10-full-down-cradle',
      'Youth A&T Level 5', 3, 10, '3-3; R; EXT-CRDL; VER-HOZ; TWIST 360',
      'From a one-foot extended position, three bases release the top through a 360° twist to horizontal cradle, then quarter-turn the group to face front.',
      'Use a unified dip and vertical release off the support foot. Top completes one full twist, opens to horizontal, and waits for a secure cradle catch before the bases perform the quarter turn.',
      'Ride up, twist one full, open horizontal, and wait for the catch.',
      'One-foot extension start, visible release, complete 360°, adequate amplitude, horizontal cradle, secure three-base catch, and group quarter turn after catch.',
      'usag-at-l5-acro-9-extended-arabesque', 'Optional Acro tariff progression', NULL, 68)
),
prepared AS (
  SELECT d.*, jsonb_build_object(
    'governing_body', 'USA Gymnastics',
    'discipline', 'Acrobatics & Tumbling',
    'event', 'Compulsory Acro — segment ' || d.segment_number || ', element ' || d.step_number,
    'program', 'Youth Acrobatics & Tumbling Development Program 2025–2026',
    'official_name', d.name,
    'element_code', d.official_notation,
    'usa_gymnastics_levels', jsonb_build_array(d.level_name),
    'status', 'verified',
    'last_verified', '2026-07-25',
    'athlete_cues', jsonb_build_array(d.athlete_cue, 'Use the official count and keep active partner contact until the coded finish.'),
    'coach_checkpoints', jsonb_build_array(d.coach_focus, 'A segment ends when the top returns to ground; the next begins when the top leaves ground. Both four-athlete groups must synchronize.'),
    'safety_and_readiness', jsonb_build_array(
      'Teach with qualified A&T coaches, appropriate surfaces, and trained spotters.',
      'Verify every base, top, and assist can state the grips, load, release, catch, and emergency plan.',
      'Progress height, release, inversion/twist, and catch independently before full synchronized performance.'
    ),
    'common_faults', jsonb_build_array(
      jsonb_build_object('fault', 'Flexed feet', 'deduction', '−0.1 per occurrence', 'cue', 'Finish through every foot.'),
      jsonb_build_object('fault', 'Bent arms or legs', 'deduction', 'Up to −0.3 per occurrence', 'cue', 'Extend support and flight shapes.'),
      jsonb_build_object('fault', 'Leg/foot separation', 'deduction', 'Up to −0.2 per occurrence', 'cue', 'Join legs unless the code requires another shape.'),
      jsonb_build_object('fault', 'Under/over rotation or insufficient amplitude', 'deduction', 'Up to −0.3 per occurrence for each category', 'cue', 'Match drive and finish rotation before catch.'),
      jsonb_build_object('fault', 'Incorrect body position or insufficient extension', 'deduction', 'Up to −0.2 per occurrence for each category', 'cue', 'Show the coded position clearly.'),
      jsonb_build_object('fault', 'Improper base catch or deviation', 'deduction', 'Up to −0.3 per occurrence for each category', 'cue', 'Catch close, high, square, and centered.'),
      jsonb_build_object('fault', 'Lack of continuity', 'deduction', 'Up to −0.2 per occurrence', 'cue', 'Keep the compulsory count moving.'),
      jsonb_build_object('fault', 'Lack of synchronization', 'deduction', 'Up to −0.3 per occurrence per heat', 'cue', 'Match every dip, release, catch, and finish.'),
      jsonb_build_object('fault', 'Fall', 'deduction', '−0.5 per occurrence', 'cue', 'Protect the catch and complete in control.')
    ),
    'scoring_summary', 'Compulsory Acro starts from 10.0. Complete omission of a special requirement is −2.0; partial completion is −1.0. Wrong mandatory spacing/direction is −0.50. Extra spotting contact is −1.0. Execution deductions apply per occurrence and a fall is −0.5. The official Code and current errata control.',
    'video_briefs', jsonb_build_array(
      jsonb_build_object('title', 'Teach ' || d.name, 'purpose', 'learning',
        'description', 'Decode every notation field, identify roles, and demonstrate grips at ground level. Progress the load and body shape, then release/rotation/catch where applicable, before adding the official segment entry and synchronized second group.'),
      jsonb_build_object('title', d.name || ' — perfect synchronized model', 'purpose', 'model',
        'description', 'Show front, side, and overhead full-speed views plus slow motion. Mark exact contacts, height, body position, rotation, legal release, catch posture, segment boundary, and matched timing.')
    ),
    'next_progressions', jsonb_build_array(jsonb_build_object('name', d.next_name, 'slug', d.next_slug)),
    'sources', jsonb_build_array(jsonb_build_object(
      'title', 'USA Gymnastics Youth Acrobatics & Tumbling Rules & Policies / Code of Points',
      'url', 'https://static.usagym.org/PDFs/gfa/at/25rp_cop.pdf#page=' || d.source_page,
      'organization', 'USA Gymnastics',
      'effective_cycle', '2025–2026',
      'accessed_on', '2026-07-25',
      'note', 'Compulsory Acro notation, element text, and deductions.'
    )),
    'editorial_note', 'Original coaching summary. Official Code, compulsory videos/count sheets, and current errata take precedence.'
  ) AS metadata
  FROM source_data d
)
INSERT INTO coaching.skill (
  facility_id, name, slug, description, instructions, sport_id, skill_level,
  skill_kind, evaluation_mode, execution_max_score, assistance_note,
  is_published, visibility, official_metadata
)
SELECT
  (SELECT id FROM public.facility ORDER BY id LIMIT 1),
  p.name, p.slug, p.description, p.instructions,
  (SELECT id FROM coaching.sport WHERE key = 'gymnastics'),
  CASE WHEN p.level_name = 'Youth A&T Level 3' THEN 'INTERMEDIATE'::public.skill_level ELSE 'ADVANCED'::public.skill_level END,
  'skill', 'execution', 10,
  'Loaded partner element — qualified A&T coaching required',
  TRUE, 'facility', p.metadata
FROM prepared p
WHERE (SELECT id FROM public.facility ORDER BY id LIMIT 1) IS NOT NULL
ON CONFLICT (facility_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  instructions = EXCLUDED.instructions,
  skill_level = EXCLUDED.skill_level,
  assistance_note = EXCLUDED.assistance_note,
  official_metadata = EXCLUDED.official_metadata,
  updated_at = now();

INSERT INTO coaching.skill_prerequisite (skill_id, prerequisite_skill_id, note)
SELECT child.id, parent.id, 'Direct preceding compulsory Acro element or level progression.'
FROM (
  VALUES
    ('usag-at-l3-acro-1-shoulder-stand', 'usag-at-l2-acro-8-cradle-barrel-roll'),
    ('usag-at-l3-acro-2-single-base-front-support', 'usag-at-l3-acro-1-shoulder-stand'),
    ('usag-at-l3-acro-3-front-support-dismount', 'usag-at-l3-acro-2-single-base-front-support'),
    ('usag-at-l3-acro-4-half-up-shoulder-stand', 'usag-at-l3-acro-3-front-support-dismount'),
    ('usag-at-l3-acro-5-shoulder-to-invert', 'usag-at-l3-acro-4-half-up-shoulder-stand'),
    ('usag-at-l3-acro-6-invert-straight-down', 'usag-at-l3-acro-5-shoulder-to-invert'),
    ('usag-at-l3-acro-7-prep-liberty', 'usag-at-l3-acro-6-invert-straight-down'),
    ('usag-at-l3-acro-8-lib-to-two-foot', 'usag-at-l3-acro-7-prep-liberty'),
    ('usag-at-l3-acro-9-full-twist-cradle', 'usag-at-l3-acro-8-lib-to-two-foot'),
    ('usag-at-l4-acro-1-toe-pitch-prep', 'usag-at-l3-acro-9-full-twist-cradle'),
    ('usag-at-l4-acro-2-prep-popoff', 'usag-at-l4-acro-1-toe-pitch-prep'),
    ('usag-at-l4-acro-3-extended-straddle-support', 'usag-at-l4-acro-2-prep-popoff'),
    ('usag-at-l4-acro-4-straddle-to-invert', 'usag-at-l4-acro-3-extended-straddle-support'),
    ('usag-at-l4-acro-5-invert-straight-down', 'usag-at-l4-acro-4-straddle-to-invert'),
    ('usag-at-l4-acro-6-extended-liberty', 'usag-at-l4-acro-5-invert-straight-down'),
    ('usag-at-l4-acro-7-liberty-foot-down', 'usag-at-l4-acro-6-extended-liberty'),
    ('usag-at-l4-acro-8-extended-arabesque', 'usag-at-l4-acro-7-liberty-foot-down'),
    ('usag-at-l4-acro-9-no-twist-cradle', 'usag-at-l4-acro-8-extended-arabesque'),
    ('usag-at-l5-acro-1-assisted-toe-pitch', 'usag-at-l4-acro-9-no-twist-cradle'),
    ('usag-at-l5-acro-2-back-tuck-off', 'usag-at-l5-acro-1-assisted-toe-pitch'),
    ('usag-at-l5-acro-3-single-base-straddle', 'usag-at-l5-acro-2-back-tuck-off'),
    ('usag-at-l5-acro-4-straddle-popover', 'usag-at-l5-acro-3-single-base-straddle'),
    ('usag-at-l5-acro-5-invert-hand-switch', 'usag-at-l5-acro-4-straddle-popover'),
    ('usag-at-l5-acro-6-invert-popoff', 'usag-at-l5-acro-5-invert-hand-switch'),
    ('usag-at-l5-acro-7-extended-liberty', 'usag-at-l5-acro-6-invert-popoff'),
    ('usag-at-l5-acro-8-liberty-foot-down', 'usag-at-l5-acro-7-extended-liberty'),
    ('usag-at-l5-acro-9-extended-arabesque', 'usag-at-l5-acro-8-liberty-foot-down'),
    ('usag-at-l5-acro-10-full-down-cradle', 'usag-at-l5-acro-9-extended-arabesque')
) AS edge(child_slug, parent_slug)
JOIN coaching.skill child ON child.slug = edge.child_slug
JOIN coaching.skill parent ON parent.slug = edge.parent_slug AND parent.facility_id = child.facility_id
ON CONFLICT DO NOTHING;
