-- USA Gymnastics Acrobatic Gymnastics Development Program 2025-2028.
-- Complete Level 6 compulsory pair/group skill boxes, pages 27-31.
-- Short official classifications are factual; coaching prose is original.

WITH source_data (
  slug, discipline, row_number, skill_type, official_name, description,
  instructions, athlete_cue, coach_focus, prerequisite_slug, next_slug, source_page
) AS (
  VALUES
    ('usag-acro-l6-wp-r2-straddle-press-handstand', 'Women''s Pair', 2, 'Balance',
      'Supported straddle press to handstand on kneeling base',
      'The top establishes straddle support on the kneeling base''s thighs or knees, then presses with assistance to a supported handstand held for three seconds.',
      'Base kneels tall and fixes the support points. Top shows the straddle, shifts shoulders over hands, presses without a jump, reaches a stacked handstand, and holds the line for the full count.',
      'Show straddle control, press smoothly, stack, and freeze for three.',
      'Visible starting straddle, continuous press, straight support, stable base posture, vertical finish, and an unambiguous three-second hold.',
      'usag-acro-straddle-on-thighs', 'usag-acro-l7-wp-r3b-straddle-press-handstand', 27),
    ('usag-acro-l6-wp-r3-toe-pitch-jump', 'Women''s Pair', 3, 'Dynamic',
      'Toe pitch straight jump with supported landing',
      'The base pitches from the prescribed toe-pitch contact as the top straightens into a released straight jump and returns to a supported floor landing.',
      'Set one top foot in the base''s hands and top hands on shoulders. Dip together, drive through the pitch, show a stretched flight shape, and reconnect in time for the base to support the landing.',
      'Push together, stretch in flight, and land through the base''s support.',
      'Correct toe-pitch setup, simultaneous drive, visible flight, straight body line, square direction, and active supported landing.',
      'usag-acro-toe-pitch-straight-jump', 'usag-acro-l7-wp-r4a-toe-pitch-jump-floor', 27),
    ('usag-acro-l6-wp-r4-thigh-handstand', 'Women''s Pair', 4, 'Balance',
      'Supported handstand on one-knee base',
      'With the base on one knee, the top performs a handstand on the base''s thigh or knee and holds the supported vertical position for three seconds.',
      'Base creates a level, braced platform and supports the top at hips or legs. Top places hands precisely, drives to vertical without arching, joins the line, and holds for three.',
      'Place, drive, stack, and hold three.',
      'Secure knee/thigh platform, straight arms, controlled entry, vertical alignment, appropriate support, and complete hold count.',
      'usag-acro-supported-handstand-floor', 'usag-acro-l7-wp-r1b-low-handstand', 27),
    ('usag-acro-l6-wp-r6-climb-low-f2h', 'Women''s Pair', 6, 'Balance',
      'Controlled climb to low foot-to-hand',
      'The kneeling base supports under the top''s feet while the top climbs without flight into a controlled low foot-to-hand position.',
      'Agree the stepping order, keep the base''s elbows and trunk braced, place support beneath each foot, and finish with the top balanced over the base''s hands; feet may contact the shoulders.',
      'Climb one step at a time and finish tall over the hands.',
      'No jump or uncontrolled transfer, support under the feet, stable base shoulders, top centered, and clear final control.',
      'usag-acro-low-foot-to-hand', 'usag-acro-l7-wp-r1a-high-position-hold', 27),
    ('usag-acro-l6-wp-r7-supine-hand-balance', 'Women''s Pair', 7, 'Balance',
      'Tuck, pike, or straddle on supine base hands',
      'The supine base supports the top in a recognized tuck, pike, or straddle on straight arms for a three-second static hold.',
      'Base sets shoulders and straight arms vertically. Top mounts with control, fixes the chosen compact or open shape, centers pressure over the base''s hands, and holds three.',
      'Choose one clear shape, balance over the hands, and hold three.',
      'Straight base arms, recognizable top shape, no middle support, still balance, controlled mount/dismount, and full hold.',
      'usag-acro-straddle-on-thighs', 'usag-acro-l7-wp-r1a-high-position-hold', 27),
    ('usag-acro-l6-wp-r8-boost-link-fish-wrap', 'Women''s Pair', 8, 'Dynamic',
      'Boost straight jump linked to fish/wrap lift',
      'A released boost straight jump with supported landing connects immediately to a front- or back-facing fish/wrap lift.',
      'Base supports waist or legs, coordinates the boost with the top''s jump, tracks the straight flight and landing, then moves without pause into the agreed fish/wrap position.',
      'Stretch the boost, reconnect, and flow straight into fish or wrap.',
      'Visible release and flight, safe supported landing, immediate link, secure fish/wrap contacts, and no extra preparation.',
      'usag-acro-t-boost', 'usag-acro-l7-wp-r6a-bird-pitch-wrap', 27),
    ('usag-acro-l6-wp-r10-shoulder-step-down', 'Women''s Pair', 10, 'Dynamic',
      'Shoulder stand step/jump down without release',
      'From standing on the base''s shoulders with leg support, the top takes the base''s hands and steps or jumps forward to the floor while maintaining contact.',
      'Base stabilizes the shoulder platform and transfers to hand contact before descent. Top stays lifted, travels forward between safe arms, and lands while contact is maintained throughout.',
      'Take the hands first, stay connected, and land softly in front.',
      'Stable shoulder stand, continuous hand contact, no release, controlled forward pathway, supported landing, and balanced finish.',
      'usag-acro-stand-on-shoulders', 'usag-acro-l7-wp-r7a-straight-dismount', 27),

    ('usag-acro-l6-mp-r2-supine-stand-hold', 'Men''s Pair', 2, 'Balance',
      'Stand on straight arms of supine base',
      'The top stands on the supine base''s straight arms for three seconds, either holding the base''s feet or unsupported.',
      'Base stacks wrists over shoulders and maintains vertical legs. Top steps into the hands, centers the feet over the base''s shoulders, chooses the supported or unsupported option, and holds three.',
      'Step to center, stand tall, and hold three.',
      'Straight base arms, controlled step-in, top vertical balance, declared support option, no foot adjustment, and full three seconds.',
      'usag-acro-basket-stand', 'usag-acro-l7-mp-r1a-high-position-hold', 28),
    ('usag-acro-l6-mp-r3-thigh-handstand', 'Men''s Pair', 3, 'Balance',
      'Supported handstand on one-knee base',
      'The top performs and holds a supported handstand on the thigh or knee of a one-knee base.',
      'Base braces the lunge/kneel and fixes the hand platform. Top enters with straight arms, stacks hips above shoulders and hands, and holds the supported handstand for three seconds.',
      'Drive to one line and hold three.',
      'Level platform, straight support, controlled entry, vertical alignment, minimal correction, and complete hold.',
      'usag-acro-supported-handstand-floor', 'usag-acro-l7-mp-r1b-low-handstand', 28),
    ('usag-acro-l6-mp-r4-shoulder-step-down', 'Men''s Pair', 4, 'Dynamic',
      'Shoulder stand step/jump down without release',
      'The top descends forward from the base''s shoulders using continuous hand contact and a supported floor landing.',
      'Secure shoulder standing first, connect hands before movement, keep the top''s center forward and close, and maintain contact until both feet control the landing.',
      'Hands first, stay close, land connected.',
      'Stable start, continuous contact, no release, controlled direction, supported landing, and no base collapse.',
      'usag-acro-stand-on-shoulders', 'usag-acro-l7-mp-r7a-straight-dismount', 28),
    ('usag-acro-l6-mp-r6-croc-on-knee-hand', 'Men''s Pair', 6, 'Balance',
      'Croc on supine base knee and hand',
      'The top holds a croc with one hand supported on the base''s bent knee and the other on the base''s hand for three seconds.',
      'Base fixes the knee and straight support arm. Top places hands deliberately, shifts the center over the two support points, extends the croc shape, and holds without walking the hands.',
      'Set both hands, find the balance, extend, and hold three.',
      'Correct mixed support points, locked base structure, recognizable croc, still center, extended legs, and complete hold.',
      'usag-acro-straddle-on-thighs', 'usag-acro-l7-mp-r3b-straddle-to-croc', 28),
    ('usag-acro-l6-mp-r7-toe-pitch-jump', 'Men''s Pair', 7, 'Dynamic',
      'Toe pitch straight jump with supported landing',
      'A coordinated toe pitch produces released straight flight and returns to a base-supported landing.',
      'Build the prescribed toe-pitch contact, dip and drive together, let the top extend through ankles and hips, track flight, and reconnect early enough to support the landing.',
      'Drive, stretch, spot, and land through support.',
      'Correct setup, synchronized pitch, minimal but clear flight, straight line, base tracking, and landing control.',
      'usag-acro-toe-pitch-straight-jump', 'usag-acro-l7-mp-r4a-toe-pitch-jump-floor', 28),
    ('usag-acro-l6-mp-r9-climb-low-f2h', 'Men''s Pair', 9, 'Balance',
      'Controlled climb to low foot-to-hand',
      'The top climbs without flight to low foot-to-hand while the kneeling base supports beneath the feet.',
      'Use a rehearsed step pattern, keep the base trunk upright, place hands under the feet, and settle the top over the contact points with no uncontrolled shoulder standing.',
      'Climb quietly and finish centered.',
      'No flight, correct under-foot support, safe shoulder option, centered top, stable base, and visible control.',
      'usag-acro-low-foot-to-hand', 'usag-acro-l7-mp-r1a-high-position-hold', 28),
    ('usag-acro-l6-mp-r10-supine-hand-balance', 'Men''s Pair', 10, 'Balance',
      'Tuck, pike, or straddle on supine base hands',
      'The top shows a selected tuck, pike, or straddle balance on the supine base''s straight arms for three seconds.',
      'Base sets a vertical arm platform. Top mounts, fixes the chosen body position with pointed feet, centers the balance, and holds the exact count before a controlled exit.',
      'Make the shape obvious and hold it still for three.',
      'Straight support, recognizable shape, centered pressure, no extra support, full hold, and controlled exit.',
      'usag-acro-straddle-on-thighs', 'usag-acro-l7-mp-r1a-high-position-hold', 28),

    ('usag-acro-l6-mxp-r2-supine-stand-hold', 'Mixed Pair', 2, 'Balance',
      'Stand on straight arms of supine base',
      'The top stands for three seconds on the supine base''s straight arms, with the supported or unsupported option.',
      'Base stacks the hands and keeps the leg structure firm. Top steps to the center of the hands, extends vertically, chooses the permitted support, and holds without adjustment.',
      'Step to center, lengthen, and freeze for three.',
      'Straight base arms, controlled mount, vertical top, correct support choice, balance without steps, and complete hold.',
      'usag-acro-basket-stand', 'usag-acro-l7-mxp-r1a-high-position-hold', 29),
    ('usag-acro-l6-mxp-r3-thigh-handstand', 'Mixed Pair', 3, 'Balance',
      'Supported handstand on one-knee base',
      'The top holds a supported handstand on the thigh or knee of a one-knee base.',
      'Base establishes a braced level surface. Top places hands, drives through a controlled inversion, stacks vertically, and holds three while the base supports hips or legs.',
      'Place, push tall, stack, and hold.',
      'Safe base lunge, straight arms, controlled inversion, vertical body line, correct support, and full hold.',
      'usag-acro-supported-handstand-floor', 'usag-acro-l7-mxp-r1b-low-handstand', 29),
    ('usag-acro-l6-mxp-r4-shoulder-step-down', 'Mixed Pair', 4, 'Dynamic',
      'Shoulder stand step/jump down without release',
      'The top travels forward from supported shoulder standing to the floor with continuous hand contact.',
      'Base stabilizes the top''s legs, changes to hand contact, and guides a close forward descent. Top stays connected and absorbs the landing without pulling the base forward.',
      'Connect hands, descend close, and land together.',
      'Stable shoulder position, no release, safe forward pathway, continuous support, controlled landing, and base posture.',
      'usag-acro-stand-on-shoulders', 'usag-acro-l7-mxp-r7a-straight-dismount', 29),
    ('usag-acro-l6-mxp-r6-toe-pitch-jump', 'Mixed Pair', 6, 'Dynamic',
      'Toe pitch straight jump with supported landing',
      'A prescribed toe pitch creates a released straight jump before the base supports the top''s landing.',
      'Set shoulder and foot contacts, coordinate the dip and pitch, show a long straight jump, keep the flight centered, and reconnect for a soft supported landing.',
      'Pitch together, stretch, and land through support.',
      'Correct setup, simultaneous force, visible release, straight shape, centered travel, and supported landing.',
      'usag-acro-toe-pitch-straight-jump', 'usag-acro-l7-mxp-r4a-toe-pitch-jump-floor', 29),
    ('usag-acro-l6-mxp-r7-straddle-press-handstand', 'Mixed Pair', 7, 'Balance',
      'Supported straddle press to handstand on kneeling base',
      'The top presses from straddle on a kneeling base''s thighs or knees into a supported handstand held three seconds.',
      'Show the starting straddle, shift shoulders forward, compress and press with no jump, open to vertical, and maintain the supported handstand for the full count.',
      'Compress, press, stack, and hold three.',
      'Recognizable start, continuous press, straight support, controlled assistance, vertical finish, and complete hold.',
      'usag-acro-straddle-on-thighs', 'usag-acro-l7-mxp-r3b-straddle-press-handstand', 29),
    ('usag-acro-l6-mxp-r9-supine-hand-balance', 'Mixed Pair', 9, 'Balance',
      'Tuck, pike, or straddle on supine base hands',
      'The top balances in a declared tuck, pike, or straddle on the supine base''s straight arms for three seconds.',
      'Base sets straight vertical arms. Top mounts under control, fixes the chosen shape, balances centrally, and holds without shaking or changing position.',
      'Choose the shape, center it, and freeze for three.',
      'Straight arms, unmistakable shape, pointed feet, stable balance, full count, and controlled mount/exit.',
      'usag-acro-straddle-on-thighs', 'usag-acro-l7-mxp-r1a-high-position-hold', 29),
    ('usag-acro-l6-mxp-r10-climb-low-f2h', 'Mixed Pair', 10, 'Balance',
      'Controlled climb to low foot-to-hand',
      'The top climbs into low foot-to-hand with the kneeling base supporting under the feet and showing control.',
      'Rehearse the step sequence, keep the base centered, transfer support beneath each foot, and finish with the top''s hips and shoulders stacked over the hands.',
      'Climb carefully and finish balanced.',
      'No flight, support under feet, stable shoulders, centered top, correct optional shoulder contact, and final control.',
      'usag-acro-low-foot-to-hand', 'usag-acro-l7-mxp-r1a-high-position-hold', 29),

    ('usag-acro-l6-wg-r2-toe-pitch-jump', 'Women''s Group', 2, 'Dynamic',
      'Group toe pitch straight jump with supported landing',
      'The top steps into the group toe-pitch position and is pitched into a released straight jump before the bases support the landing.',
      'Bases establish equal foot contacts and common timing. Top bends and drives with the group, stretches in centered flight, and presents early for a shared landing support.',
      'Load evenly, stretch tall, and land through both bases.',
      'Balanced contacts, synchronized pitch, clear flight, straight top, centered path, and safe shared landing.',
      'usag-acro-toe-pitch-knees-straight-jump', 'usag-acro-l7-wg-r7a-straight-jump-off', 30),
    ('usag-acro-l6-wg-r3-half-column-or-double-table', 'Women''s Group', 3, 'Balance',
      'Half-column or double-table pyramid hold',
      'The group selects either a supported half-column with top on middle shoulders or a stacked double-table with the top balanced on the middle''s knees or thighs; the chosen pyramid holds three seconds.',
      'Assign the option and contacts before building. Stack each tier over its footprint, keep the top shape clear, stop all movement before counting, and hold three.',
      'Build one square option, settle it, and hold three.',
      'Correct option and roles, stable tier stacking, appropriate top shape/contact, no shifting, complete hold, and controlled descent.',
      'usag-acro-column-pyramid-rear-scale', 'usag-acro-l7-wg-r3b-half-column-hold', 30),
    ('usag-acro-l6-wg-r5-basket-lift-chest', 'Women''s Group', 5, 'Balance',
      'Hands-free basket stand lifted to chest height',
      'The top stands hands-free on the basket while the bases lift without release to at least one base''s chest height with straight legs.',
      'Create a level basket, establish the top''s hands-free balance, lift through coordinated legs and arms to the required height, show control, and lower without linking directly onward.',
      'Stand tall, ride the lift, show chest height, and do not link.',
      'Hands-free top, no release, clear chest-height threshold, at least one base with straight legs, stable basket, and no forbidden link.',
      'usag-acro-basket-stand', 'usag-acro-l7-wg-r7a-double-pitch-jump', 30),
    ('usag-acro-l6-wg-r6-basket-quarter-layout-catch', 'Women''s Group', 6, 'Dynamic',
      'Basket quarter-back layout to forearm catch',
      'From standing on the basket, the top performs a quarter-back layout into a controlled forearm catch.',
      'Bases load evenly and project the top with height. Top holds an extended layout through the quarter rotation, spots the catch, and presents a braced horizontal shape to the forearms.',
      'Rise, stretch the quarter layout, and present for the catch.',
      'Even basket, adequate amplitude, unmistakable layout, complete quarter rotation, square top presentation, and secure forearm catch.',
      'usag-acro-basket-stand', 'usag-acro-l7-wg-r4a-layout-link-log-roll', 30),
    ('usag-acro-l6-wg-r7-double-support-shape', 'Women''s Group', 7, 'Balance',
      'Double-support tuck, pike, or straddle on bases',
      'Two bases create a supported 2:1 hand platform while the top holds a chosen tuck, pike, or straddle on their straight arms for three seconds.',
      'Bases align side by side and reinforce the center hands. Top mounts symmetrically, fixes the chosen shape over both supports, and holds still for three.',
      'Center over both bases, show one shape, and hold three.',
      'Correct 2:1 platform, straight base arms, symmetrical top pressure, recognizable shape, no middle assistance, and full hold.',
      'usag-acro-plank-pyramid', 'usag-acro-l7-wg-r1a-straddle-press-handstand', 30),
    ('usag-acro-l6-wg-r9-forearm-catch-log-roll', 'Women''s Group', 9, 'Dynamic',
      'Jump to forearm catch linked to log roll',
      'The top jumps from two feet to a stomach-down forearm catch, then the bases immediately throw a 180- or 360-degree log roll and recatch on stomach or back.',
      'Set the forearm target and jump direction, receive the first catch securely, use an immediate coordinated release, keep the top long through the chosen twist, and recatch high.',
      'Jump to a firm catch, stay long, roll, and present again.',
      'Two-foot jump, secure first catch, immediate link, exact twist, straight horizontal line, synchronized release, and controlled recatch.',
      'usag-acro-fish-wrap-lift', 'usag-acro-l7-wg-r4a-layout-link-log-roll', 30),
    ('usag-acro-l6-wg-r10-thigh-press-handstand', 'Women''s Group', 10, 'Balance',
      'Assisted straddle press to handstand on bases'' thighs',
      'From straddle support on the kneeling bases'' knees or thighs, the top presses with assistance to a handstand held for three seconds.',
      'Bases create level hand contacts and may assist hips or legs. Top shows straddle, compresses into the press, opens to vertical, and holds the final line.',
      'Show the straddle, press together, stack, and hold three.',
      'Stable side-by-side bases, visible press rather than jump, appropriate assistance, straight vertical top, square handstand, and full hold.',
      'usag-acro-handstand-pyramid', 'usag-acro-l7-wg-r1a-straddle-press-handstand', 30),

    ('usag-acro-l6-mg-r2-chair-shoulderstand-pyramid', 'Men''s Group', 2, 'Balance',
      'Chair pyramid with shoulderstand and standing middle',
      'Base 1 supports Base 2 in chair, the top performs a shoulderstand on Base 1, and the middle stands on Base 2''s thighs; the complete pyramid holds three seconds.',
      'Build the chair connection first, add the shoulderstand with fixed hand/leg contacts, place the middle over Base 2''s thighs, then settle all tiers before counting.',
      'Build bottom to top, square every tier, and hold three.',
      'Correct four roles, safe chair support, recognizable shoulderstand, middle vertical control, stable contacts, and complete hold.',
      'usag-acro-column-pyramid-rear-scale', 'usag-acro-l7-mg-r1a-chair-shoulderstand-pyramid', 31),
    ('usag-acro-l6-mg-r3-three-man-basket-layout', 'Men''s Group', 3, 'Dynamic',
      'Three-man basket quarter-back layout to forearm catch',
      'The group pitches the top from a three-man basket through a quarter-back layout to a shared forearm catch.',
      'Three throwers synchronize the load and release. Top rises in a straight layout, completes the quarter turn, and presents square while all designated athletes secure the forearm catch.',
      'Ride the basket up, stretch the quarter, and present square.',
      'Even three-man force, amplitude, straight top, complete rotation, correct catch roles, and controlled absorption.',
      'usag-acro-basket-stand', 'usag-acro-l7-mg-r5b-basket-layout-base-switch', 31),
    ('usag-acro-l6-mg-r5-lunge-shoulder-pyramid', 'Men''s Group', 5, 'Balance',
      'Lunge-thigh and double-shoulder standing pyramid',
      'Two bases lunge side by side, the middle stands on their thighs, and the top stands across the bases'' shoulders while holding the middle for support; the pyramid holds three seconds.',
      'Match base lunge depth, place the middle centrally, establish top foot contacts across shoulders, connect top and middle safely, then stabilize before counting.',
      'Match the lunges, stack the middle and top, and hold three.',
      'Level base thighs, secure middle leg support, correct top shoulder contacts, square alignment, no shifting, and full hold.',
      'usag-acro-column-pyramid-rear-scale', 'usag-acro-l7-mg-r2a-lunge-shoulder-pyramid', 31),
    ('usag-acro-l6-mg-r6-shoulder-quarter-layout', 'Men''s Group', 6, 'Dynamic',
      'Shoulder stand quarter-front layout to forearm catch',
      'The top jumps from standing on the middle''s shoulders through a quarter-front layout to the two bases'' forearm catch.',
      'Middle provides a level shoulder platform and supports the start. Top jumps upward, extends the front-quarter layout, and presents horizontally while the bases track and catch together.',
      'Jump up, stretch the front quarter, and present to both bases.',
      'Stable shoulder start, upward projection, straight layout, complete quarter rotation, square flight, and secure two-base catch.',
      'usag-acro-stand-on-shoulders', 'usag-acro-l7-mg-r5b-basket-layout-base-switch', 31),
    ('usag-acro-l6-mg-r7-paired-toe-pitch-jumps', 'Men''s Group', 7, 'Dynamic',
      'Paired toe pitch straight jumps',
      'The top/base-1 pair and middle/base-2 pair perform the same toe-pitch straight jump simultaneously or in immediate succession, each with supported landing.',
      'Create two safe lanes and identical toe-pitch setups. Match or clearly sequence the common count, show straight released flight, and have each base support their partner''s landing.',
      'Two matching pitches, two straight flights, two controlled landings.',
      'Identical setups, simultaneous or immediate-successive timing, visible release, matching shape/amplitude, safe spacing, and supported landings.',
      'usag-acro-toe-pitch-straight-jump', 'usag-acro-l7-mg-r6a-paired-toe-pitch-jumps', 31),
    ('usag-acro-l6-mg-r9-supported-group-toe-pitch', 'Men''s Group', 9, 'Dynamic',
      'Group toe pitch straight jump with middle support',
      'The top uses a two-base toe-pitch position with the middle supporting the legs, then the group produces a straight jump and supported landing.',
      'Balance both base hand contacts, assign the middle''s leg support, coordinate one dip and release, keep the top straight and centered, and reconnect for landing support.',
      'Load evenly, drive as four, stretch, and land together.',
      'Correct middle support, balanced pitch, synchronized drive, visible flight, straight top, centered direction, and controlled landing.',
      'usag-acro-toe-pitch-knees-straight-jump', 'usag-acro-l7-mg-r3a-three-man-basket-salto', 31)
),
prepared AS (
  SELECT d.*, jsonb_build_object(
    'governing_body', 'USA Gymnastics',
    'discipline', 'Acrobatic Gymnastics',
    'event', 'Level 6 Combined - ' || d.discipline,
    'program', 'Acrobatic Gymnastics Development Program 2025-2028',
    'official_name', d.official_name,
    'official_code', 'Level 6 ' || d.discipline || ' Row ' || d.row_number || 'A',
    'usa_gymnastics_levels', jsonb_build_array('Acro Level 6'),
    'status', 'verified',
    'last_verified', '2026-07-25',
    'athlete_cues', jsonb_build_array(d.athlete_cue, 'Perform the compulsory rows in the published order and finish every position before moving on.'),
    'coach_checkpoints', jsonb_build_array(
      d.coach_focus,
      'The Level 6 combined routine must include one pair/group element from every discipline row plus three simultaneous individual elements: one balance, one flexibility, and one tumbling or agility.'
    ),
    'safety_and_readiness', jsonb_build_array(
      'Use qualified Acro coaching, assigned base/middle/top roles, progressive mats, and a trained spot or catch plan.',
      'Every athlete must own the isolated contacts, body positions, entry, hold, flight, and landing before the full element is connected.',
      'Level placement and published inclusion do not override individual physical, technical, or psychological readiness.'
    ),
    'common_faults', jsonb_build_array(
      jsonb_build_object('fault', 'Missing compulsory row or individual element', 'deduction', '-1.0 SR each', 'cue', 'Audit every row and all three individual categories before competition.'),
      jsonb_build_object('fault', 'All required elements not performed', 'deduction', 'Additional -1.0 SR', 'cue', 'Complete the full published content set.'),
      jsonb_build_object('fault', 'Skill or individual element out of order', 'deduction', '-0.3 DJ', 'cue', 'Rehearse the compulsory sequence exactly.'),
      jsonb_build_object('fault', 'Additional pair/group skill of value', 'deduction', '-1.0 DJ once per exercise', 'cue', 'Use only the required pair/group content.'),
      jsonb_build_object('fault', 'Balance held under three seconds', 'deduction', 'Short-hold DJ penalty; no time value at one second or less', 'cue', 'Settle before beginning the audible count.'),
      jsonb_build_object('fault', 'Technical execution errors', 'deduction', 'Per USA Gymnastics technical-fault tables', 'cue', 'Prioritize alignment, amplitude, extension, stability, and safe catches.'),
      jsonb_build_object('fault', 'No music', 'deduction', '-1.0 CJP', 'cue', 'Verify music and backup playback before the exercise.'),
      jsonb_build_object('fault', 'Exercise exceeds 2:30', 'deduction', '-0.3 CJP', 'cue', 'Time from first movement through final position.')
    ),
    'scoring_summary', 'Level 6 has no difficulty score. Execution starts from 10.0 and Artistry is not applied at this compulsory level under the published formula. Missing-row and content penalties are -1.0 each; out-of-order content is -0.3; short holds, technical faults, music, and time penalties apply. Current Code and errata control.',
    'video_briefs', jsonb_build_array(
      jsonb_build_object('title', 'Teach ' || d.official_name, 'purpose', 'learning',
        'description', 'Identify every role, grip, start height, and landing first. Demonstrate isolated base structure and top shape, then entry, hold or flight, and finish on progressive surfaces from front and side views.'),
      jsonb_build_object('title', d.official_name || ' - ideal Level 6 model', 'purpose', 'model',
        'description', 'Show full speed and slow motion with the official row label. Highlight exact contacts, alignment, amplitude, three-second hold when required, synchronized force, and a stable landing or catch.')
    ),
    'prerequisite_slug', d.prerequisite_slug,
    'next_progressions', CASE WHEN d.next_slug IS NULL THEN '[]'::jsonb ELSE
      jsonb_build_array(jsonb_build_object('name', 'Direct Level 7 progression', 'slug', d.next_slug)) END,
    'sources', jsonb_build_array(jsonb_build_object(
      'title', 'USA Gymnastics Acrobatic Gymnastics Development Program Code of Points 2025-2028',
      'url', 'https://static.usagym.org/PDFs/Acro/Rules/devcop_2528.pdf#page=' || d.source_page,
      'organization', 'USA Gymnastics',
      'effective_cycle', '2025-2028',
      'accessed_on', '2026-07-25',
      'note', 'Level 6 discipline table, official row classification, requirements, and scoring rules.'
    )),
    'editorial_note', 'Original coaching summary. Official wording, diagrams, current errata, and qualified hands-on instruction take precedence.'
  ) AS metadata
  FROM source_data d
)
INSERT INTO coaching.skill (
  facility_id, name, slug, description, instructions, sport_id, skill_level,
  skill_kind, evaluation_mode, execution_max_score, assistance_note,
  is_published, visibility, official_metadata
)
SELECT
  (SELECT id FROM public.facility ORDER BY id LIMIT 1),
  'Acro L6 ' || p.discipline || ' R' || p.row_number || ' - ' || p.official_name,
  p.slug, p.description, p.instructions,
  (SELECT id FROM coaching.sport WHERE key = 'gymnastics'),
  'INTERMEDIATE'::public.skill_level,
  'partner', 'execution', 10,
  p.discipline || ' compulsory ' || lower(p.skill_type) || ' element',
  TRUE, 'facility', p.metadata
FROM prepared p
ON CONFLICT (facility_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  instructions = EXCLUDED.instructions,
  skill_level = EXCLUDED.skill_level,
  assistance_note = EXCLUDED.assistance_note,
  official_metadata = EXCLUDED.official_metadata,
  updated_at = NOW();
