-- Reassess every Box Jump source and complete exact research-authored working
-- specifications. Source text remains traceable but nonselectable where setup,
-- preload, arm action, approach, landing, exit, or reset facts are incomplete.
-- Media, graph, calibration, content, and publication approvals are not created.

DO $$
DECLARE
  migration_key CONSTANT TEXT := '462_coaching_box_jump_family_audit_hardening';
  research_version CONSTANT TEXT := '2026-08-02.75';
  canonical_id UUID;
  baseline_variant UUID := gen_random_uuid();
  paused_variant UUID := gen_random_uuid();
  no_arm_variant UUID := gen_random_uuid();
  one_step_variant UUID := gen_random_uuid();
  cmj_variant UUID;
  squat_jump_variant UUID;
  drop_landing_variant UUID;
  source_ids CONSTANT BIGINT[] := ARRAY[2,1543,1546,1547,1549,1552,1556,1557,1558];
  source_variant_ids UUID[];
  active_variant_ids UUID[];
  current_video_ids CONSTANT TEXT[] := ARRAY['52r_Ul5k03g','d2z2_rRkpAo','v9cZQqGX1Xk','kNIInK_Le8I','Bc_ycZFCEvQ'];
  protected_count INTEGER;
  evidence_payload JSONB := $json$[
    {"sectionKey":"identity","sourceUrl":"https://pmc.ncbi.nlm.nih.gov/articles/PMC10204452/","sourceTitle":"Countermovement, Hurdle, and Box Jumps: Data-Driven Exercise Selection","sourcePublisher":"Journal of Functional Morphology and Kinesiology","sourceKind":"peer_reviewed_research","evidenceQuality":86,"claims":["A direct comparison of maximal countermovement, hurdle, and box jumps in 20 recreationally trained men found task-specific countermovement and horizontal-force differences.","Box Jump retains bilateral floor propulsion, elevated bilateral whole-foot landing, stabilization, stand, step-down, and reset; approach, preload, arm policy, takeoff and landing laterality, obstacle sequence, and rebound remain exact identity dimensions."]},
    {"sectionKey":"taxonomy","sourceUrl":"https://www.nasm.org/resource-center/exercise-library/box-jumps","sourceTitle":"Box Jumps","sourcePublisher":"National Academy of Sports Medicine","sourceKind":"expert_instruction","evidenceQuality":78,"claims":["Professional instruction describes a bilateral jump to an appropriately scaled stable box followed by a controlled step down.","Controlled taxonomy is jump, land, squat, and brace; detailed start, flight, box contact, stand, exit, and reset facts live in the variant contract."]},
    {"sectionKey":"anatomy","sourceUrl":"https://pmc.ncbi.nlm.nih.gov/articles/PMC10204452/","sourceTitle":"Countermovement, Hurdle, and Box Jumps: Data-Driven Exercise Selection","sourcePublisher":"Journal of Functional Morphology and Kinesiology","sourceKind":"peer_reviewed_research","evidenceQuality":86,"claims":["Box jumping coordinates propulsion and landing across the foot, ankle, knee, hip, pelvis, trunk, and arm swing when allowed.","The card describes joint actions and contributing tissues without claiming that one muscle is isolated or universally dominant."]},
    {"sectionKey":"biomechanics","sourceUrl":"https://pmc.ncbi.nlm.nih.gov/articles/PMC11166134/","sourceTitle":"Does Box Height Matter? A Comparative Analysis of Box Height on Box Jump Performance in Men and Women","sourcePublisher":"International Journal of Exercise Science","sourceKind":"peer_reviewed_research","evidenceQuality":84,"claims":["Thirty-one recreationally active college participants completed maximal-intent box jumps across five relative box heights; most propulsion variables did not differ across heights in that protocol.","Box height is an individualized landing and collision constraint, not a valid substitute for measured center-of-mass jump height or a universal intensity scale."]},
    {"sectionKey":"difficulty","sourceUrl":"https://pmc.ncbi.nlm.nih.gov/articles/PMC10204452/","sourceTitle":"Countermovement, Hurdle, and Box Jumps: Data-Driven Exercise Selection","sourcePublisher":"Journal of Functional Morphology and Kinesiology","sourceKind":"peer_reviewed_research","evidenceQuality":86,"claims":["The elevated target changes approach, projection, countermovement, foot clearance, landing, and collision consequence relative to a floor countermovement jump.","Scores are provisional exercise complexity and physical difficulty only, with overall equal to their maximum; workout selection handles readiness separately."]},
    {"sectionKey":"load_fatigue_recovery","sourceUrl":"https://worldathletics.org/download/downloadnsa?filename=8c33cc0b-ba23-4d3d-9dbe-168e10d5fcfb.pdf&urlslug=plyometrics-for-beginners-basic-considerati","sourceTitle":"Plyometrics for Beginners: Basic Considerations","sourcePublisher":"World Athletics","sourceKind":"governing_body","evidenceQuality":76,"claims":["Jump exposure depends on body mass, intent, task height, surface, contacts, attempts, training history, and the rest of the session.","Count every successful and failed landing contact and combine calf-Achilles, knee-hip extensor, sprint, running, jump, and technical-fatigue exposure before selection or substitution."]},
    {"sectionKey":"constraints","sourceUrl":"https://www.nasm.org/resource-center/exercise-library/box-jumps","sourceTitle":"Box Jumps","sourcePublisher":"National Academy of Sports Medicine","sourceKind":"expert_instruction","evidenceQuality":78,"claims":["The box must be stable and appropriately scaled, the landing controlled, and descent performed by stepping down.","Generation requires an inspected non-slip box, level high-traction floor, visible edge, whole-foot top area, clear flight and fall space, safe step-down route, no cross traffic, and suitable supervision."]},
    {"sectionKey":"dosage","sourceUrl":"https://worldathletics.org/download/downloadnsa?filename=8c33cc0b-ba23-4d3d-9dbe-168e10d5fcfb.pdf&urlslug=plyometrics-for-beginners-basic-considerati","sourceTitle":"Plyometrics for Beginners: Basic Considerations","sourcePublisher":"World Athletics","sourceKind":"governing_body","evidenceQuality":76,"claims":["Power-oriented plyometrics use limited high-quality contacts and sufficient recovery rather than fatigue-driven repetition.","Every profile declares attempts, box height, start and arm policy, landing hold, reset, rest, contact count, duration, output-loss rule, and cumulative impact budget."]},
    {"sectionKey":"instructions","sourceUrl":"https://www.nasm.org/resource-center/exercise-library/box-jumps","sourceTitle":"Box Jumps","sourcePublisher":"National Academy of Sports Medicine","sourceKind":"expert_instruction","evidenceQuality":78,"claims":["Instruction includes stable setup, coordinated lower-body extension and arm swing when allowed, bilateral landing, controlled step down, and reset.","The exact card adds approach, takeoff line, whole-foot landing, hold, stand, exit route, failed-attempt accounting, and stop commands."]},
    {"sectionKey":"safety_stop_rules","sourceUrl":"https://pmc.ncbi.nlm.nih.gov/articles/PMC10254820/","sourceTitle":"Training interventions to reduce the risk of injury to the lower extremity joints during landing movements in adult athletes","sourcePublisher":"BMJ Open Sport & Exercise Medicine","sourceKind":"peer_reviewed_research","evidenceQuality":89,"claims":["Landing interventions depend on task-specific progression, equipment, space, feedback, and delivery quality.","Stop for symptoms, fear, unstable equipment, toe or shin contact, partial-foot or asynchronous landing, uncontrolled collapse, unexpected extra contact, jump-down exit, repeated strategy drift, or loss of output."]},
    {"sectionKey":"programming","sourceUrl":"https://pmc.ncbi.nlm.nih.gov/articles/PMC10204452/","sourceTitle":"Countermovement, Hurdle, and Box Jumps: Data-Driven Exercise Selection","sourcePublisher":"Journal of Functional Morphology and Kinesiology","sourceKind":"peer_reviewed_research","evidenceQuality":86,"claims":["Box, hurdle, and countermovement jumps are related but task-specific and should not be selected as interchangeable labels.","Place high-intent variants early when fresh; preserve exact identity, collision clearance, landing control, cumulative contacts, duration, and recovery through every substitution."]},
    {"sectionKey":"athlete_support","sourceUrl":"https://pmc.ncbi.nlm.nih.gov/articles/PMC6208302/","sourceTitle":"The Use of Augmented Information for Reducing Anterior Cruciate Ligament Injury Risk During Jump Landings: A Systematic Review","sourcePublisher":"Journal of Athletic Training","sourceKind":"peer_reviewed_research","evidenceQuality":87,"claims":["Focused feedback can change observable landing mechanics, while excessive cue volume can interfere with learning.","Athlete support shows the exact start, arm rule, flight, whole-foot box landing, hold, stand, step-down route, reset, valid rep, expected sensations, and stop signal in video and nonvideo formats."]},
    {"sectionKey":"coach_support","sourceUrl":"https://pmc.ncbi.nlm.nih.gov/articles/PMC11166134/","sourceTitle":"Does Box Height Matter? A Comparative Analysis of Box Height on Box Jump Performance in Men and Women","sourcePublisher":"International Journal of Exercise Science","sourceKind":"peer_reviewed_research","evidenceQuality":84,"claims":["The box-height study used individualized relative heights and maximal intent in a limited recreationally active cohort.","Coach support records box and takeoff distance, exact approach and arm rule, successful and failed attempts, every contact, projection, edge clearance, landing depth and symmetry, hold, exit, output loss, symptoms, and recovery."]},
    {"sectionKey":"accessibility","sourceUrl":"https://www.nsca.com/globalassets/about/position-statements/position_stand_youth_resistance_training---2009.pdf","sourceTitle":"Youth Resistance Training: Updated Position Statement Paper From the NSCA","sourcePublisher":"National Strength and Conditioning Association","sourceKind":"professional_standard","evidenceQuality":88,"claims":["Exercise selection and progression should match physical and psychosocial readiness, competence, supervision, and equipment scale.","A lower box, visible takeoff and landing marks, longer reset, fewer contacts, reduced intent, floor jump-to-stick, written sequence, still frames, or non-impact power option may improve access without assigning a proficiency category."]},
    {"sectionKey":"alternates","sourceUrl":"https://pmc.ncbi.nlm.nih.gov/articles/PMC5260575/","sourceTitle":"Effect of an Arm Swing on Countermovement Vertical Jump Performance in Elite Volleyball Players","sourcePublisher":"Journal of Human Kinetics","sourceKind":"peer_reviewed_research","evidenceQuality":84,"claims":["Arm swing materially changes countermovement jump performance in the studied elite volleyball players and therefore cannot be silently mixed in comparative tasks.","Preload, arm policy, approach, takeoff and landing laterality, platform sequence, direction, load, rebound, measurement purpose, and reset determine modifier, variant, or new-definition classification."]},
    {"sectionKey":"media","sourceUrl":"https://support.google.com/youtube/answer/171780?expand=PrivacyEnhancedMode&hl=en","sourceTitle":"Embed videos and playlists","sourcePublisher":"YouTube Help","sourceKind":"manufacturer_instruction","evidenceQuality":82,"claims":["YouTube supports privacy-enhanced embedding through youtube-nocookie.com.","Five candidates retain recorded oEmbed link, title, channel, and iframe health only; playback, exact mechanics, captions, accessibility, safety, quality, reviewer identity, and approval remain unresolved."]}
  ]$json$::JSONB;
  media_payload JSONB := $json$[
    {"videoId":"52r_Ul5k03g","title":"The Box Jump","channel":"CrossFit","query":"box jump technique"},
    {"videoId":"d2z2_rRkpAo","title":"Box Jump | Olympic Weightlifting Exercise Library","channel":"Catalyst Athletics","query":"box jump technique"},
    {"videoId":"v9cZQqGX1Xk","title":"How to Box Jump for Beginners | Shane Heins","channel":"Onnit","query":"box jump technique"},
    {"videoId":"kNIInK_Le8I","title":"How to Do Beginner Box Jump Exercises","channel":"National Academy of Sports Medicine (NASM)","query":"box jump technique"},
    {"videoId":"Bc_ycZFCEvQ","title":"How To Do The Plyometric Box Jump (TECHNIQUE BREAKDOWN 101)","channel":"Criticalbench","query":"box jump technique"}
  ]$json$::JSONB;
  alternate_payload JSONB := $json$[
    {"name":"Source 2 Generic Box Jump","class":"reject","why":"The source omits start stance, countermovement and arm policy, takeoff distance, exact box geometry and height, whole-foot rule, hold, and reset details.","dimensions":{"sourceIds":[2],"identityQuarantine":true}},
    {"name":"Source 1543 Step-Down Reset","class":"reject","why":"The source permits jump or move over the box and omits exact preload, arm rule, box height, landing hold, and repetition timing.","dimensions":{"sourceIds":[1543],"identityQuarantine":true}},
    {"name":"Source 1546 Pause Box Jump","class":"reject","why":"The source gives a one-to-two-second range but omits exact start depth, arm policy, takeoff distance, box height, and hold.","dimensions":{"sourceIds":[1546],"identityQuarantine":true}},
    {"name":"Source 1547 No-Arm-Swing Box Jump","class":"reject","why":"The source allows fixed or crossed arms and omits exact preload, hand position, takeoff distance, box height, and hold.","dimensions":{"sourceIds":[1547],"identityQuarantine":true}},
    {"name":"Source 1549 Countermovement Box Jump","class":"reject","why":"The source omits exact arm policy, takeoff distance, box height, whole-foot and hold criteria, and reset timing.","dimensions":{"sourceIds":[1549],"identityQuarantine":true}},
    {"name":"Source 1552 Non-Countermovement Box Jump","class":"reject","why":"The source does not fix start depth, stillness duration, arm policy, takeoff distance, box height, or hold.","dimensions":{"sourceIds":[1552],"identityQuarantine":true}},
    {"name":"Source 1556 Reset Repetition Box Jump","class":"reject","why":"The source describes resets but omits exact preload, arm rule, box height, hold, inter-attempt reset, and contact accounting.","dimensions":{"sourceIds":[1556],"identityQuarantine":true}},
    {"name":"Source 1557 Arm-Swing Timing Box Jump","class":"reject","why":"The source does not define the arm sequence, preload, takeoff distance, box height, landing hold, or exact timing target.","dimensions":{"sourceIds":[1557],"identityQuarantine":true}},
    {"name":"Source 1558 One-Step Box Jump","class":"reject","why":"The source name supplies one step but not the stepping foot, gather sequence, takeoff line, arm policy, box height, or landing contract.","dimensions":{"sourceIds":[1558],"identityQuarantine":true}},
    {"name":"Stationary Countermovement Box Jump","class":"same_identity","why":"One natural countermovement, natural arm swing, bilateral takeoff, elevated whole-foot landing, hold, stand, step down, and reset define the baseline.","dimensions":{"variantKey":"stationary-countermovement-natural-arms"}},
    {"name":"Paused Static Hands-on-Hips Box Jump","class":"new_variant","why":"A fixed quarter-squat start, declared stillness, and hands-on-hips policy remove countermovement and arm-swing contributions.","dimensions":{"variantKey":"paused-static-hands-on-hips"}},
    {"name":"Countermovement Hands-on-Hips Box Jump","class":"new_variant","why":"Hands remain on hips while one countermovement is retained, changing coordination and output without changing the landing sequence.","dimensions":{"variantKey":"stationary-countermovement-hands-on-hips"}},
    {"name":"One-Step Bilateral-Gather Box Jump","class":"new_variant","why":"One declared lead step into a bilateral gather changes entry rhythm, horizontal momentum, station length, and failure modes.","dimensions":{"variantKey":"one-step-bilateral-gather"}},
    {"name":"Box Height","class":"modifier_annotation","why":"A recorded height scales edge clearance and landing geometry within an exact variant but is not a jump-height score.","dimensions":{"modifier":"box_height"}},
    {"name":"Takeoff Distance","class":"modifier_annotation","why":"A recorded floor-to-box distance standardizes projection and collision clearance without changing the action sequence.","dimensions":{"modifier":"takeoff_distance"}},
    {"name":"Landing Hold, Attempts, and Rest","class":"modifier_annotation","why":"These scale dose and quality within an exact start, arm, approach, takeoff, landing, exit, and reset contract.","dimensions":{"modifiers":["landing_hold","attempts","rest"]}},
    {"name":"Soft-Sided Box","class":"new_variant","why":"Box material and edge geometry change collision consequence, deformation, stability checks, and confidence while preserving the movement sequence.","dimensions":{"boxType":"soft_sided_rated"}},
    {"name":"Hands Crossed on Chest","class":"new_variant","why":"A crossed-arm restriction differs from hands on hips in upper-body position and balance and must be declared separately.","dimensions":{"armPolicy":"crossed_on_chest"}},
    {"name":"Maximum Box Jump Test","class":"new_variant","why":"A formal escalating-height test changes warm-up, attempts, failure rules, spotters, measurement, and terminal criteria.","dimensions":{"purpose":"maximum_height_test"}},
    {"name":"Weighted Box Jump","class":"new_definition","why":"External load changes takeoff, flight, landing, object control, failed-attempt consequence, dose, and recovery.","dimensions":{"externalLoad":true}},
    {"name":"Seated Box Jump","class":"new_definition","why":"A seated static start removes standing countermovement and adds seat height, contact, release, and balance constraints.","dimensions":{"start":"seated"}},
    {"name":"Single-Leg Takeoff Box Jump","class":"new_definition","why":"Unilateral propulsion requires side-specific dose, different balance, loading, clearance, and failure rules.","dimensions":{"takeoffLaterality":"unilateral"}},
    {"name":"Bilateral Takeoff to Single-Leg Box Landing","class":"new_definition","why":"Unilateral terminal support changes landing loading, side accounting, balance, and consequence of error.","dimensions":{"landingLaterality":"unilateral"}},
    {"name":"Lateral Box Jump","class":"new_definition","why":"Lateral projection changes stance orientation, edge clearance, frontal-plane demand, space, and landing view.","dimensions":{"direction":"lateral"}},
    {"name":"Broad Jump to Box","class":"new_definition","why":"A deliberately horizontal projection changes takeoff distance, flight path, braking, edge risk, and purpose.","dimensions":{"direction":"horizontal"}},
    {"name":"Hurdle-to-Box Jump","class":"new_definition","why":"An external obstacle adds a separate clearance event, longer flight path, more collision surfaces, and different logistics.","dimensions":{"obstacleSequence":["hurdle","box"]}},
    {"name":"Depth Jump to Box","class":"new_definition","why":"An elevated step-off, floor contact, rebound, second flight, and box landing create a multi-contact reactive sequence.","dimensions":{"entry":"elevated_drop","rebound":true}},
    {"name":"Continuous Rebound Box Jumps","class":"new_definition","why":"Jumping down or rebounding between repetitions adds floor contacts and reactive exposure and removes the full reset.","dimensions":{"continuous":true,"additionalContacts":true}},
    {"name":"Box Jump Over","class":"new_definition","why":"Clearing the full obstacle and landing on the far floor changes flight, collision surfaces, final landing, and space.","dimensions":{"terminalSurface":"far_floor"}},
    {"name":"Missed or Scraped Box Attempt","class":"reject","why":"A miss, toe catch, shin contact, or fall is a failed attempt or incident, never a selectable exercise variant.","dimensions":{"incident":true,"selectable":false}}
  ]$json$::JSONB;
BEGIN
  SELECT definition_id INTO canonical_id FROM coaching.exercise_definition_source_v1 WHERE legacy_exercise_id=2;
  SELECT variant.id INTO cmj_variant FROM coaching.exercise_variant_v1 variant JOIN coaching.exercise_definition_v1 definition ON definition.id=variant.definition_id WHERE definition.slug='countermovement-jump' AND variant.variant_key='baseline';
  SELECT variant.id INTO squat_jump_variant FROM coaching.exercise_variant_v1 variant JOIN coaching.exercise_definition_v1 definition ON definition.id=variant.definition_id WHERE definition.slug='squat-jump' AND variant.variant_key='baseline';
  SELECT variant.id INTO drop_landing_variant FROM coaching.exercise_variant_v1 variant JOIN coaching.exercise_definition_v1 definition ON definition.id=variant.definition_id WHERE definition.slug='drop-landing-to-stick' AND variant.variant_key='baseline';
  source_variant_ids := ARRAY[
    (SELECT id FROM coaching.exercise_variant_v1 WHERE definition_id=canonical_id AND variant_key='baseline'),
    (SELECT id FROM coaching.exercise_variant_v1 WHERE definition_id=canonical_id AND variant_key='legacy-source-1543-baseline'),
    (SELECT id FROM coaching.exercise_variant_v1 WHERE definition_id=canonical_id AND variant_key='legacy-source-1546-baseline'),
    (SELECT id FROM coaching.exercise_variant_v1 WHERE definition_id=canonical_id AND variant_key='legacy-source-1547-baseline'),
    (SELECT id FROM coaching.exercise_variant_v1 WHERE definition_id=canonical_id AND variant_key='legacy-source-1549-baseline'),
    (SELECT id FROM coaching.exercise_variant_v1 WHERE definition_id=canonical_id AND variant_key='legacy-source-1552-baseline'),
    (SELECT id FROM coaching.exercise_variant_v1 WHERE definition_id=canonical_id AND variant_key='legacy-source-1556-baseline'),
    (SELECT id FROM coaching.exercise_variant_v1 WHERE definition_id=canonical_id AND variant_key='legacy-source-1557-baseline'),
    (SELECT id FROM coaching.exercise_variant_v1 WHERE definition_id=canonical_id AND variant_key='legacy-source-1558-baseline')];
  active_variant_ids := ARRAY[baseline_variant,paused_variant,no_arm_variant,one_step_variant];
  IF EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 WHERE id=canonical_id AND card_version=3 AND provenance_json->>'boxJumpAuditHardeningMigration'=migration_key) THEN
    RETURN;
  END IF;
  IF (SELECT count(*) FROM coaching.exercise_definition_v1 WHERE id=canonical_id AND facility_id=1 AND slug='box-jump' AND card_version=2 AND status='review')<>1
    OR (SELECT count(*) FROM coaching.exercise WHERE id=ANY(source_ids))<>cardinality(source_ids)
    OR (SELECT count(*) FROM coaching.exercise_definition_source_v1 WHERE legacy_exercise_id=ANY(source_ids))<>cardinality(source_ids)
    OR (SELECT count(*) FROM coaching.exercise_variant_v1 WHERE id=ANY(source_variant_ids))<>cardinality(source_variant_ids)
    OR cmj_variant IS NULL OR squat_jump_variant IS NULL OR drop_landing_variant IS NULL THEN
    RAISE EXCEPTION '% requires the complete version-2 Box Jump lineage',migration_key;
  END IF;
  IF EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 WHERE id=canonical_id AND provenance_json ? 'boxJumpAuditHardeningMigration') THEN
    RAISE EXCEPTION '% found partial or conflicting state',migration_key;
  END IF;
  SELECT COALESCE(sum(n),0) INTO protected_count FROM (
    SELECT count(*) n FROM coaching.exercise_definition_v1 WHERE id=canonical_id AND (reviewed_by IS NOT NULL OR approved_by IS NOT NULL OR last_reviewed_at IS NOT NULL OR approved_video_url IS NOT NULL)
    UNION ALL SELECT count(*) FROM coaching.exercise_section_evidence_v1 WHERE definition_id=canonical_id AND reviewer_user_id IS NOT NULL
    UNION ALL SELECT count(*) FROM coaching.exercise_media_candidate_v1 WHERE definition_id=canonical_id AND reviewer_user_id IS NOT NULL
    UNION ALL SELECT count(*) FROM coaching.exercise_alternate_assessment_v1 WHERE definition_id=canonical_id AND reviewer_user_id IS NOT NULL
    UNION ALL SELECT count(*) FROM coaching.exercise_relationship_v1 WHERE reviewed_by IS NOT NULL AND (from_variant_id=ANY(source_variant_ids) OR to_variant_id=ANY(source_variant_ids))
    UNION ALL SELECT count(*) FROM coaching.exercise_score_calibration_v1 WHERE reviewed_by IS NOT NULL AND variant_id=ANY(source_variant_ids)
  ) protected;
  IF protected_count<>0 THEN RAISE EXCEPTION '% refuses to replace human review',migration_key; END IF;

  UPDATE coaching.exercise_section_evidence_v1 SET review_status='superseded',updated_at=now() WHERE definition_id=canonical_id AND review_status='candidate' AND reviewer_user_id IS NULL;
  UPDATE coaching.exercise_media_candidate_v1 SET review_status='superseded',updated_at=now() WHERE definition_id=canonical_id AND review_status='candidate' AND reviewer_user_id IS NULL;
  UPDATE coaching.exercise_alternate_assessment_v1 SET review_status='superseded',updated_at=now() WHERE definition_id=canonical_id AND review_status='candidate' AND reviewer_user_id IS NULL;

  UPDATE coaching.exercise_definition_source_v1 SET definition_id=canonical_id,
    source_kind=CASE WHEN legacy_exercise_id=2 THEN 'legacy_migration' ELSE 'duplicate_consolidation' END,
    provenance_json=coalesce(provenance_json,'{}'::JSONB)||jsonb_build_object('migration',migration_key,'sourceDisposition','identity_quarantine','representedBySelectableSourceVariant',FALSE,'missingExactExecutionFacts',TRUE,'authoritativeSourceRecoveryRequired',TRUE,'humanReviewRequired',TRUE,'approvalsCreated',FALSE)
  WHERE legacy_exercise_id=ANY(source_ids);

  UPDATE coaching.exercise_variant_v1 SET definition_id=canonical_id,
    variant_key='identity-quarantine-source-'||(source_ids[array_position(source_variant_ids,id)])::TEXT,
    status='archived',difficulty_json='{}'::JSONB,
    requirements_json=jsonb_build_object('selectable',FALSE,'representation','identity_quarantine','sourceLegacyExerciseId',source_ids[array_position(source_variant_ids,id)],'archiveReason','source_omits_one_or_more_exact_preload_arm_approach_box_landing_exit_reset_or_dose_facts','originalAuthoritativeEvidenceRequired',TRUE,'humanReviewRequired',TRUE),
    load_profile_json=jsonb_build_object('selectable',FALSE),fatigue_profile_json=jsonb_build_object('selectable',FALSE),
    programming_profile_json=jsonb_build_object('selectionStatus','identity_quarantine','selectable',FALSE,'publicationQuarantined',TRUE,'neverRestoreFromLabelOrMediaMetadata',TRUE),updated_at=now()
  WHERE id=ANY(source_variant_ids);
  UPDATE coaching.exercise_delivery_profile_v1 SET status='archived',updated_at=now() WHERE variant_id=ANY(source_variant_ids);
  UPDATE coaching.exercise_definition_v1 SET status='archived',approved_video_url=NULL,reviewed_by=NULL,approved_by=NULL,last_reviewed_at=NULL,
    provenance_json=coalesce(provenance_json,'{}'::JSONB)||jsonb_build_object('identityResolutionMigration',migration_key,'survivorDefinitionId',canonical_id,'selectable',FALSE,'humanReviewRequired',TRUE,'approvalsCreated',FALSE),updated_at=now()
  WHERE FALSE;

  UPDATE coaching.exercise_definition_v1 SET canonical_name='Box Jump',display_name='Box Jump',
    aliases=ARRAY['Bilateral Box Jump','Countermovement Box Jump','Paused Static Box Jump','No-Arm-Swing Box Jump','One-Step Box Jump','Reset Box Jump']::TEXT[],
    description='A family of bilateral floor-to-box jumps. Every selectable working specification declares approach, preload, arm policy, stance and takeoff line, inspected box type and height, bilateral takeoff, whole-foot bilateral landing, hold, stand, step-down route, reset, attempts, rest, contact accounting, stop rules, and cumulative impact budget.',
    family_key='bilateral_floor_to_box_jump_family',schema_version='2.0.0',card_version=3,status='review',content_confidence=92,scoring_confidence=64,media_confidence=48,
    movement_patterns=ARRAY['jump','land','squat','brace']::TEXT[],body_regions=ARRAY['foot','ankle','calf','knee','hamstrings','glutes','hip','pelvis','core','spine']::TEXT[],required_equipment=ARRAY['box']::TEXT[],optional_equipment=ARRAY['mat','line_tape','cones']::TEXT[],
    anatomy_json=jsonb_build_object('primaryMuscles',jsonb_build_array('quadriceps','gluteus_maximus','soleus','gastrocnemius'),'secondaryMuscles',jsonb_build_array('hamstrings','gluteus_medius','hip_external_rotators','adductors','tibialis_anterior','intrinsic_foot_muscles','abdominal_wall','spinal_stabilizers'),'connectiveTissues',jsonb_build_array('Achilles_tendon','patellar_tendon','quadriceps_tendon','foot_ankle_knee_hip_supporting_tissues'),'joints',jsonb_build_array('foot','ankle','knee','hip','pelvis','lumbosacral_complex','shoulder_girdle_when_arms_swing'),'jointActions',jsonb_build_array('countermovement_or_static_start_control','ankle_plantarflexion','knee_extension','hip_extension','flight_position_control','ankle_dorsiflexion_control_on_landing','knee_and_hip_flexion_control_on_landing','pelvis_and_trunk_stabilization','static_box_landing_stabilization'),'jointActionPhases',jsonb_build_object('preload',jsonb_build_array('declared_countermovement_or_static_start'),'propulsion',jsonb_build_array('hip_knee_ankle_extension','declared_arm_action'),'landing',jsonb_build_array('whole_foot_bilateral_contact','lower_limb_absorption','pelvis_and_trunk_control'),'finish',jsonb_build_array('hold','stand','step_down','reset')),'planes',jsonb_build_array('sagittal_primary','frontal_and_transverse_control'),'laterality','bilateral','evidenceLimit','Small recreational and trained cohorts do not establish one universal box height, countermovement, arm policy, muscle ranking, safe dose, transfer effect, or clinical clearance.'),
    environment_json=jsonb_build_object('surface','level_dry_high_traction','box','rated_inspected_stable_non_slip_top_clear_edge_visible_and_large_enough_for_both_whole_feet','takeoff','declared_line_and_distance','clearance',jsonb_build_array('ceiling','forward_flight','box_front_and_top','fall_space','step_down_route','return_and_reset'),'traffic','none_through_station','sightlines',jsonb_build_array('side','front_or_rear'),'emergencyPlan','declared_before_attempts'),
    population_json=jsonb_build_object('defaultPopulation','participants_with_pain_free_bilateral_jump_to_stick_safe_step_down_and_confidence_at_selected_height','individualizationRequired',TRUE,'prerequisites',jsonb_build_array('can_perform_declared_start_and_bilateral_takeoff','can_land_bilaterally_with_both_whole_feet_and_hold','can_stand_and_step_down_by_declared_route','understands_failed_attempt_and_stop_rules','can_report_symptoms_fear_fatigue_and_recovery'),'cautions',jsonb_build_array('pain_giving_way_dizziness_or_fear','recent_lower_limb_spine_injury_surgery_or_immobilization','uncontrolled_neurologic_cardiopulmonary_or_balance_condition','pregnancy_or_postpartum_status_requiring_individualization','unsafe_box_surface_clearance_route_or_supervision','cannot_clear_edge_or_land_whole_feet_at_selected_height'),'notClinicalClearance',TRUE,'neverInferReadinessFromExerciseDifficulty',TRUE),
    athlete_support_json=jsonb_build_object('whatItIs','Use the assigned start and arm rule, jump from both feet to the inspected box, land both whole feet together, hold, stand, step down by the named route, and fully reset.','before',jsonb_build_array('Confirm variant, box type and height, takeoff line, arm rule, landing hold, step-down route, attempts, rest, stop signal, and contact budget.','Check the box, floor, top, edge, flight path, fall space, route, footwear, and traffic.','Report pain, giving way, dizziness, fear, unusual fatigue, or uncertainty before starting.'),'during',jsonb_build_array('Use only the assigned approach and preload.','Clear the edge without a panic tuck and land both whole feet together.','Own the hold before standing; step down and reset rather than jumping down.','Stop before projection, clearance, landing depth, sound, symmetry, hold, or confidence changes.'),'expectedSensations',jsonb_build_array('brief_explosive_lower_body_effort','whole_foot_box_pressure','controlled_landing_absorption','balance_during_hold'),'notExpected',jsonb_build_array('sharp_or_increasing_pain','giving_way','dizziness','toe_or_shin_contact','partial_foot_landing','panic_or_loss_of_control'),'selfChecks',jsonb_build_array('correct_start_and_arm_rule','box_and_route_are_stable_and_clear','bilateral_takeoff','edge_cleared','both_whole_feet_land_together','hold_stand_step_down_and_reset_exact'),'accessibility',jsonb_build_array('lower_box','visible_takeoff_and_landing_marks','fewer_attempts','longer_reset_and_rest','reduced_intent','floor_jump_to_stick','written_or_still_frame_sequence','non_impact_power_alternative'),'stopSignal','Stop immediately, remain in a safe position, tell the coach what changed, and do not retry until the exact station, height, task, dose, and symptoms are re-evaluated.'),
    coach_support_json=jsonb_build_object('setupChecklist',jsonb_build_array('verify_exact_variant_profile_approach_preload_and_arm_policy','inspect_box_floor_top_edge_clearance_fall_space_route_and_traffic','declare_box_height_takeoff_distance_hold_attempts_rest_contacts_and_stop_threshold','review recent calf_Achilles_knee_hip_sprint_running_jump_and_sport exposure'),'observeFromSide',jsonb_build_array('approach_and_preload','vertical_and_forward_projection','edge_clearance','foot_position_on_box','landing_depth_hold_stand_and_step_down'),'observeFromFrontOrRear',jsonb_build_array('stance_and_bilateral_takeoff','contact_timing_and_whole_foot_support','knee_hip_pelvis_and_trunk_control','box_movement_and_route_clearance'),'validRep','Exact approach, preload, arm rule, bilateral takeoff, clear edge, simultaneous whole-foot landing, controlled depth, declared hold, stand, step down, and full reset all pass without a stop rule.','correctionOrder',jsonb_build_array('wrong_variant_box_height_or_station','symptom_fear_or_incident_stop','approach_preload_arm_or_takeoff_mismatch','edge_or_whole_foot_clearance','landing_sound_depth_alignment_and_hold','stand_step_down_reset_and_traffic','output_loss_contact_budget_duration_and_recovery'),'groupManagement',jsonb_build_array('one_active_athlete_per_box_and_flight_path','next_athlete_waits_outside_fall_and_step_down_route','coach_controls_box_changes_and_takeoff_marks','count_valid_failed_and_incident_contacts'),'escalation','Quarantine selection when identity, station, height, readiness, symptoms, contact budget, supervision, or media is uncertain.'),
    support_operations_json=jsonb_build_object('selectionInputs',jsonb_build_array('definition_variant_profile_card_and_research_version','objective_and_phase','approach_preload_arm_takeoff_and_landing_contract','box_type_height_takeoff_distance_surface_clearance_and_route','attempts_hold_reset_rest_duration_and_contact_budget','recent_calf_Achilles_knee_hip_sprint_running_jump_and_sport_load','symptoms_fear_recovery_population_and_supervision'),'persistence',jsonb_build_array('workout_and_item_id','definition_variant_profile_card_and_research_version','box_type_height_takeoff_distance_and_station','approach_preload_arm_landing_hold_exit_and_reset','valid_failed_and_incident_attempts_and_all_contacts','rest_faults_symptoms_duration_output_loss_and_recovery','substitution_reason','rendered_athlete_and_coach_instruction_versions'),'incidentPath',jsonb_build_array('call_stop_and_secure_station','assess_immediate_facility_response_without_in_product_diagnosis','record_variant_box_attempt_contact_fault_symptom_and_context','follow_emergency_or_clinical_referral_policy','quarantine_uncertain_source_card_or_media'),'changeImpact','Any approach, preload, arm, takeoff, box, height, surface, landing, hold, exit, reset, dose, fatigue, recovery, population, station, or media change invalidates cached selection, duration, logistics, rendering, and approval assumptions.','publication',jsonb_build_object('humanMediaGraphCalibrationContentAndSeparateApprovalRequired',TRUE)),
    provenance_json=coalesce(provenance_json,'{}'::JSONB)||jsonb_build_object('boxJumpAuditHardeningMigration',migration_key,'researchVersion',research_version,'canonicalAuthoredFromResearch',TRUE,'legacySourcesQuarantined',source_ids,'activeWorkingSpecifications',jsonb_build_array('stationary-countermovement-natural-arms','paused-static-hands-on-hips','stationary-countermovement-hands-on-hips','one-step-bilateral-gather'),'primaryResearchSource','https://pmc.ncbi.nlm.nih.gov/articles/PMC10204452/','researchSources',jsonb_build_array('https://pmc.ncbi.nlm.nih.gov/articles/PMC10204452/','https://pmc.ncbi.nlm.nih.gov/articles/PMC11166134/','https://pmc.ncbi.nlm.nih.gov/articles/PMC5260575/','https://pmc.ncbi.nlm.nih.gov/articles/PMC10254820/','https://pmc.ncbi.nlm.nih.gov/articles/PMC6208302/','https://www.nasm.org/resource-center/exercise-library/box-jumps','https://worldathletics.org/download/downloadnsa?filename=8c33cc0b-ba23-4d3d-9dbe-168e10d5fcfb.pdf&urlslug=plyometrics-for-beginners-basic-considerati'),'identityDecision','bilateral_floor_to_elevated_box_jump_with_approach_preload_arm_landing_exit_and_reset_as_explicit_dimensions','mediaState','five_recorded_oembed_healthy_candidates_carried_forward_unreviewed','oembedOriginallyCheckedAt','2026-08-02','freshOembedRecheckSucceeded',FALSE,'exerciseDifficultyModel','exercise_complexity_and_physical_difficulty_only','approvalsCreated',FALSE,'publicationQuarantined',TRUE,'humanReviewRequired',TRUE),
    approved_video_url=NULL,reviewed_by=NULL,approved_by=NULL,last_reviewed_at=NULL,updated_at=now()
  WHERE id=canonical_id;

  INSERT INTO coaching.exercise_variant_v1(id,definition_id,variant_key,display_name,modifier_keys,difficulty_json,requirements_json,status,load_profile_json,fatigue_profile_json,programming_profile_json)
  SELECT v.id,canonical_id,v.variant_key,v.display_name,v.modifier_keys,
    jsonb_build_object('technicalComplexity',v.complexity,'absoluteLoadDemand',v.physical,'physicalDifficulty',v.physical,'baseOverallDifficulty',GREATEST(v.complexity,v.physical),'coordinationDemand',v.coordination,'supervisionDemand',v.supervision,'failureConsequence',v.failure,'impact',v.impact,'workCapacityDemand',v.work_capacity,'provisional',TRUE,'difficultyModel','max_exercise_complexity_physical_difficulty','technicalMeaning','exercise_complexity','loadMeaning','physical_difficulty','athleteReadinessStoredHere',FALSE),
    jsonb_build_object('actionIdentity','bilateral_floor_to_box_jump','approach',v.approach,'preload',v.preload,'armPolicy',v.arm_policy,'startStance','declared_bilateral_stance_at_recorded_takeoff_line','takeoff','simultaneous_bilateral','box','rated_inspected_stable_non_slip_with_recorded_type_and_height','landing','simultaneous_bilateral_both_whole_feet_supported','landingHoldSeconds','profile_declared','terminalAction','stand_stable_step_down_by_declared_route_and_fully_reset','laterality','bilateral','selectable',TRUE,'identityQuarantine',FALSE,'workingSpecificationRequiresHumanContentReview',TRUE),
    'review',
    jsonb_build_object('gripDemand',1,'externalLoadMethod','bodyweight','externalLoadDescription','No external load; body mass is accelerated from the floor and received on the elevated box.','spinalLoading',v.spinal,'eccentricStress',v.eccentric,'landingContactsPerRep',1,'impactClass','low_to_moderate_at_owned_height_but_collision_consequence_present','loadTracking',jsonb_build_array('body_mass','box_type_and_height','takeoff_distance','approach_preload_and_arm_policy','valid_failed_and_incident_attempts','all_contacts','landing_depth_and_hold','symptoms'),'effectiveLoadDrivers',jsonb_build_array('body_mass','takeoff_intent','approach_momentum','box_height_and_geometry','projection_and_clearance','landing_strategy','attempts_and_failed_contacts','surface_footwear_and_recent_jump_running_load')),
    jsonb_build_object('localMuscleFatigue',v.local_fatigue,'gripFatigue',1,'technicalFatigueSensitivity',v.sensitivity,'neuralOutputDemand',v.neural,'impactAccumulation',v.impact,'recoveryHours','12_to_72_context_dependent','primaryFatigueSites',jsonb_build_array('foot_calf_and_Achilles','quadriceps_and_gluteals','hamstrings_and_hip_stabilizers','trunk_and_balance_control'),'earlyFatigueSignals',jsonb_build_array('hesitation_or_approach_drift','lower_or_more_forward_projection','toe_or_shin_proximity','partial_foot_or_asynchronous_landing','deeper_louder_or_less_stable_landing','slower_stand_step_down_or_reset'),'downstreamConflicts',jsonb_build_array('priority_sprint_jump_cut_or_reactive_work','high_volume_running_or_sport_contacts','heavy_lower_body_eccentric_or_strength_work','symptomatic_foot_Achilles_knee_hip_or_spine_loading')),
    jsonb_build_object('trainingStimuli',jsonb_build_array('bilateral_vertical_power','task_specific_box_clearance','elevated_landing_control','exact_start_and_arm_coordination'),'stimulusDose',jsonb_build_object('primary','high_quality_attempts','fatigueCeiling','low','landingContactsPerAttempt',1),'weeklyExposure','Combine all valid, failed, and incident jump, landing, sprint, running, cutting, lifting, and sport contacts; progress one variable only after stable quality and recovery.','prerequisites',jsonb_build_array('pain_free_bilateral_jump_to_stick','safe_step_down','confidence_at_selected_height','exact_start_and_arm_rule_understood','station_and_contact_budget_verified'),'completionCriteria',jsonb_build_array('all_attempts_match_exact_variant','edge_and_whole_foot_clearance_pass','landing_hold_stand_step_down_and_reset_pass','contact_output_symptom_duration_and_recovery_records_complete'),'sequenceRules',jsonb_build_array('place_after_specific_preparation_and_before_fatiguing_strength_or_conditioning_when_power_is_priority','use_full_reset_and_rest','never_turn_failed_clearance_or_landing_into_extra_practice_contacts'),'pairingCompatibility',jsonb_build_array('noncompeting_low_risk_upper_body_mobility_or_breathing_task_during_full_rest'),'interferenceRules',jsonb_build_array('do_not_pre_fatigue_lower_body_or_trunk_before_priority_attempts','do_not_raise_box_after_clearance_landing_or_confidence_changes','recompute_identity_impact_fatigue_duration_logistics_and_rendering_after_substitution'),'uncertaintyPolicy',jsonb_build_object('unknownIdentityStationSymptomsReadinessOrRecovery','fail_closed_and_request_coach_review','neverInferMissingSourceMechanics',TRUE,'neverAutoApproveMediaGraphCalibrationOrPublication',TRUE),'cumulativeBudget',jsonb_build_object('landingContactsPerAttempt',1,'countValidFailedAndIncidentContacts',TRUE,'calfAchilles',v.calf_budget,'kneeHipExtensor',v.lower_budget,'technicalSensitivity',v.sensitivity,'sameSessionRunningSprintJumpAndSportRequired',TRUE))
  FROM (VALUES
    (baseline_variant,'stationary-countermovement-natural-arms','Box Jump — Stationary Countermovement, Natural Arms',ARRAY['stationary','countermovement','natural_arms','bilateral','whole_foot_landing','step_down','full_reset']::TEXT[],'none_stationary','one_natural_countermovement','natural_coordinated_arm_swing',48,46,50,56,64,38,30,44,68,64,18,42,42,46),
    (paused_variant,'paused-static-hands-on-hips','Box Jump — Paused Static Start, Hands on Hips',ARRAY['stationary','paused_static','hands_on_hips','bilateral','whole_foot_landing','step_down','full_reset']::TEXT[],'none_stationary','quarter_squat_two_second_motionless_start_no_second_dip','hands_remain_on_hips_through_takeoff_and_landing',54,46,56,60,66,36,28,42,72,60,20,40,40,44),
    (no_arm_variant,'stationary-countermovement-hands-on-hips','Box Jump — Stationary Countermovement, Hands on Hips',ARRAY['stationary','countermovement','hands_on_hips','bilateral','whole_foot_landing','step_down','full_reset']::TEXT[],'none_stationary','one_natural_countermovement','hands_remain_on_hips_through_takeoff_and_landing',50,46,54,58,66,38,30,44,70,64,18,42,42,46),
    (one_step_variant,'one-step-bilateral-gather','Box Jump — One-Step Bilateral Gather, Natural Arms',ARRAY['one_step','bilateral_gather','countermovement','natural_arms','whole_foot_landing','step_down','full_reset']::TEXT[],'one_declared_lead_step_then_bilateral_gather_at_takeoff_line','one_continuous_gather_countermovement_without_extra_steps','natural_coordinated_arm_swing',58,50,62,64,70,42,32,48,76,70,22,46,46,50)
  ) v(id,variant_key,display_name,modifier_keys,approach,preload,arm_policy,complexity,physical,coordination,supervision,failure,impact,work_capacity,local_fatigue,sensitivity,neural,spinal,eccentric,calf_budget,lower_budget)
  ON CONFLICT(id) DO UPDATE SET definition_id=EXCLUDED.definition_id,variant_key=EXCLUDED.variant_key,display_name=EXCLUDED.display_name,modifier_keys=EXCLUDED.modifier_keys,difficulty_json=EXCLUDED.difficulty_json,requirements_json=EXCLUDED.requirements_json,status='review',load_profile_json=EXCLUDED.load_profile_json,fatigue_profile_json=EXCLUDED.fatigue_profile_json,programming_profile_json=EXCLUDED.programming_profile_json,updated_at=now();

  INSERT INTO coaching.exercise_delivery_profile_v1(variant_id,profile_key,phase_key,role,purpose,phase_suitability,methodology_alignment,objective_relevance_json,dosage_json,quality_gate,stop_rules,coach_instructions,athlete_instructions,expected_adaptation,equipment_required,logistics_json,substitution_ids,status,time_model_json,dose_scaling_json,measurement_json,support_prompts_json)
  SELECT p.variant_id,p.profile_key,p.phase,p.role,p.purpose,p.suitability,90,
    jsonb_build_object('verticalPower',p.power,'landingControl',p.control,'coordination',p.coordination,'impactManagement',p.impact_management),
    jsonb_build_object('doseType','quality_attempts','sets',p.sets,'attemptsPerSet',p.attempts,'boxHeight','individualized_recorded_owned_height','takeoffDistance','recorded','landingHoldSeconds',p.hold,'resetBetweenAttemptsSeconds',p.reset,'restBetweenSetsSeconds',p.rest,'countValidFailedAndIncidentAttempts',TRUE,'landingContactsPerAttempt',1,'outputLossStopPercent',p.output_loss),
    'Every counted attempt matches the exact approach, preload, arm rule, takeoff line, box and height; clears the edge; lands both whole feet simultaneously at a repeatable depth; holds, stands, steps down, and fully resets without a stop-rule failure.',
    ARRAY['pain_giving_way_dizziness_or_fear','wrong_variant_approach_preload_arm_rule_box_height_or_takeoff_line','box_floor_top_edge_clearance_fall_space_route_or_traffic_is_unsafe','toe_shin_or_other_box_contact','partial_foot_or_asynchronous_landing','uncontrolled_loud_deep_valgus_or_trunk_collapse','unplanned_step_touch_jump_down_or_extra_contact','approach_projection_clearance_or_landing_strategy_changes','output_loss_exceeds_profile_threshold','contact_impact_duration_or_recovery_budget_exceeded'],
    'Verify exact variant, box type and height, takeoff line, route, attempts, hold, reset, rest, contact and impact budgets, stop threshold, symptoms, confidence, recent running and jumping, and station safety. Observe side plus front or rear, count every valid, failed, and incident contact, and lower or replace the task before mechanics drift.',
    'Use the assigned approach, preload, and arm rule. Jump from both feet, clear the edge, land both whole feet, hold, stand, step down, and reset. Stop for box contact, partial feet, pain, fear, or any changed rep.',
    p.adaptation,ARRAY['box']::TEXT[],
    jsonb_build_object('athletesPerStation',1,'setupSeconds',45,'transitionSeconds',20,'station','one_inspected_box_with_exclusive_flight_landing_fall_and_step_down_space','equipmentCheck','rated_stable_non_slip_box_level_floor_visible_edge_clear_top_clear_route_and_no_traffic','boxChangeRule','coach_reinspects_and_recomputes_height_clearance_duration_and_risk','substitutionRevalidation',jsonb_build_array('identity','approach','preload','arm_policy','box','height','surface','landing','impact','fatigue','duration','population','rendering')),
    CASE p.variant_id WHEN baseline_variant THEN ARRAY[paused_variant,no_arm_variant,one_step_variant,cmj_variant]::UUID[] WHEN paused_variant THEN ARRAY[baseline_variant,no_arm_variant,squat_jump_variant]::UUID[] WHEN no_arm_variant THEN ARRAY[baseline_variant,paused_variant,squat_jump_variant]::UUID[] ELSE ARRAY[baseline_variant,cmj_variant]::UUID[] END,'review',
    jsonb_build_object('setupSeconds',45,'attemptSeconds',5,'stepDownAndResetSeconds',p.reset,'landingHoldSeconds',p.hold,'durationIncludesRest',TRUE,'durationFormula','setup + sets * (attempts * (attempt + hold + step_down_reset) + inter_set_rest) + transition','durationCeilingSeconds',p.ceiling,'recomputeAfterSubstitution',TRUE),
    jsonb_build_object('reduce',jsonb_build_array('lower_box','reduce_takeoff_distance','reduce_intent','reduce_attempts','increase_reset_and_rest','use_stationary_baseline','use_floor_jump_to_stick','use_non_impact_power_task'),'increase',jsonb_build_array('increase_intent_at_owned_height','add_attempt_within_contact_budget','use_more_complex_reviewed_variant','increase_box_only_after_clearance_landing_and_recovery_pass'),'revalidateAfterChange',TRUE),
    jsonb_build_object('record',jsonb_build_array('definition_id','variant_id','profile_key','box_type_height_and_takeoff_distance','approach_preload_and_arm_policy','sets_valid_failed_and_incident_attempts','all_landing_contacts','edge_clearance_landing_depth_symmetry_hold_and_sound','reset_rest_output_loss_faults_symptoms_duration_and_recovery','substitution'),'validity','all exact identity, station, clearance, landing, contact, duration, output, symptom, and stop gates pass'),
    jsonb_build_object('before','Which exact variant, box, height, line, route, dose, hold, rest, contact budget, and stop signal are assigned?','during','Do approach, preload, arms, projection, clearance, whole-foot landing, hold, confidence, and output still match?','after','Store valid, failed, and incident attempts, all contacts, box and line, faults, symptoms, duration, recovery, and substitution.')
  FROM (VALUES
    (baseline_variant,'technique','movement_intelligence','secondary','Build repeatable stationary countermovement box-jump sequencing and whole-foot landing control at a deliberately owned height.',88,3,5,5,5,2,3,3,20,75,8,'More repeatable start, edge clearance, elevated landing, step-down, and reset control.',720),
    (baseline_variant,'power','output','primary','Express high-intent stationary bilateral power while preserving exact clearance, landing, exit, reset, and contact quality.',94,5,4,4,4,3,4,2,25,120,6,'Improved high-quality bilateral floor-to-box power expression and controlled elevated landing.',900),
    (paused_variant,'technique','movement_intelligence','secondary','Learn a motionless quarter-squat start and hands-on-hips takeoff without a second dip.',86,3,5,5,4,2,3,3,25,90,8,'More repeatable static-start force organization and elevated landing control.',780),
    (paused_variant,'power','output','primary','Express concentric-biased box-jump output from an exact two-second static hands-on-hips start.',90,5,4,5,4,3,3,2,30,135,6,'Improved high-intent output from a standardized static start.',930),
    (no_arm_variant,'technique','movement_intelligence','secondary','Coordinate one stationary countermovement while the hands remain on the hips through takeoff and landing.',86,3,5,5,4,2,3,3,25,90,8,'More repeatable lower-body countermovement and landing without arm contribution.',780),
    (no_arm_variant,'power','output','primary','Express high-intent hands-on-hips countermovement output without changing the box or landing contract.',90,5,4,5,4,3,3,2,30,135,6,'Improved high-intent lower-body output under a fixed arm policy.',930),
    (one_step_variant,'technique','movement_intelligence','secondary','Learn one declared lead step into a bilateral gather, jump, whole-foot landing, step-down, and reset.',82,3,5,5,4,2,3,3,30,105,8,'More repeatable approach rhythm, bilateral gather, projection, and landing control.',840),
    (one_step_variant,'power','output','primary','Express high-intent one-step bilateral-gather power while preserving approach, line, box, landing, and contact quality.',90,5,4,5,4,3,3,2,35,150,6,'Improved approach-assisted bilateral floor-to-box power and controlled landing.',990)
  ) p(variant_id,profile_key,phase,role,purpose,suitability,power,control,coordination,impact_management,sets,attempts,hold,reset,rest,output_loss,adaptation,ceiling)
  ON CONFLICT(variant_id,profile_key) DO UPDATE SET phase_key=EXCLUDED.phase_key,role=EXCLUDED.role,purpose=EXCLUDED.purpose,phase_suitability=EXCLUDED.phase_suitability,methodology_alignment=EXCLUDED.methodology_alignment,objective_relevance_json=EXCLUDED.objective_relevance_json,dosage_json=EXCLUDED.dosage_json,quality_gate=EXCLUDED.quality_gate,stop_rules=EXCLUDED.stop_rules,coach_instructions=EXCLUDED.coach_instructions,athlete_instructions=EXCLUDED.athlete_instructions,expected_adaptation=EXCLUDED.expected_adaptation,equipment_required=EXCLUDED.equipment_required,logistics_json=EXCLUDED.logistics_json,substitution_ids=EXCLUDED.substitution_ids,status='review',time_model_json=EXCLUDED.time_model_json,dose_scaling_json=EXCLUDED.dose_scaling_json,measurement_json=EXCLUDED.measurement_json,support_prompts_json=EXCLUDED.support_prompts_json,updated_at=now();

  INSERT INTO coaching.exercise_section_evidence_v1(definition_id,reviewed_card_version,section_key,source_url,source_title,source_publisher,source_kind,claims_json,evidence_quality,review_status,reviewer_user_id,reviewed_at)
  SELECT canonical_id,3,item->>'sectionKey',item->>'sourceUrl',item->>'sourceTitle',item->>'sourcePublisher',item->>'sourceKind',item->'claims'||jsonb_build_array(jsonb_build_object('migration',migration_key,'researchVersion',research_version,'humanReviewRequired',TRUE,'approvalsCreated',FALSE)),(item->>'evidenceQuality')::SMALLINT,'candidate',NULL,NULL FROM jsonb_array_elements(evidence_payload) item
  ON CONFLICT(definition_id,reviewed_card_version,section_key,source_url) DO UPDATE SET source_title=EXCLUDED.source_title,source_publisher=EXCLUDED.source_publisher,source_kind=EXCLUDED.source_kind,claims_json=EXCLUDED.claims_json,evidence_quality=EXCLUDED.evidence_quality,review_status='candidate',reviewer_user_id=NULL,reviewed_at=NULL,updated_at=now();

  INSERT INTO coaching.exercise_media_candidate_v1(definition_id,variant_id,reviewed_card_version,url,embed_url,video_id,title,channel_name,language_code,captions_available,embedding_allowed,exact_variant_match,demonstration_quality_score,link_status,review_status,discovery_method,source_query,reviewer_user_id,reviewed_at,next_review_at,notes)
  SELECT canonical_id,NULL,3,'https://www.youtube.com/watch?v='||(item->>'videoId'),'https://www.youtube-nocookie.com/embed/'||(item->>'videoId'),item->>'videoId',item->>'title',item->>'channel','en',NULL,TRUE,NULL,NULL,'healthy','candidate','manual_research',item->>'query',NULL,NULL,'2026-11-02T00:00:00.000Z'::TIMESTAMPTZ,'Card-v2 oEmbed link, title, channel, and iframe metadata were recorded healthy on 2026-08-02 and are carried forward. The attempted fresh fetch did not succeed and is not verification. Full playback, exact variant, captions, accessibility, safety, cue quality, conflicts, reviewer identity, and approval remain unresolved.' FROM jsonb_array_elements(media_payload) item
  ON CONFLICT(definition_id,reviewed_card_version,video_id) DO UPDATE SET variant_id=NULL,url=EXCLUDED.url,embed_url=EXCLUDED.embed_url,title=EXCLUDED.title,channel_name=EXCLUDED.channel_name,language_code='en',captions_available=NULL,embedding_allowed=TRUE,exact_variant_match=NULL,demonstration_quality_score=NULL,link_status='healthy',review_status='candidate',discovery_method='manual_research',source_query=EXCLUDED.source_query,reviewer_user_id=NULL,reviewed_at=NULL,next_review_at=EXCLUDED.next_review_at,notes=EXCLUDED.notes,updated_at=now();

  INSERT INTO coaching.exercise_alternate_assessment_v1(definition_id,reviewed_card_version,alternate_name,classification,rationale,distinguishing_dimensions,proposed_card_json,review_status,reviewer_user_id,reviewed_at)
  SELECT canonical_id,3,item->>'name',item->>'class',item->>'why',item->'dimensions',NULL,'candidate',NULL,NULL FROM jsonb_array_elements(alternate_payload) item
  ON CONFLICT(definition_id,reviewed_card_version,alternate_name) DO UPDATE SET classification=EXCLUDED.classification,rationale=EXCLUDED.rationale,distinguishing_dimensions=EXCLUDED.distinguishing_dimensions,proposed_card_json=NULL,review_status='candidate',reviewer_user_id=NULL,reviewed_at=NULL,updated_at=now();

  INSERT INTO coaching.exercise_relationship_v1(from_variant_id,to_variant_id,relationship,similarity_score,dimensions,reason,conditions_json,review_status,created_by,reviewed_by,reviewed_at) VALUES
    (baseline_variant,cmj_variant,'regression',86,ARRAY['complexity','impact'],'Floor Countermovement Jump removes box clearance, elevated landing, collision risk, and step-down logistics while preserving stationary bilateral countermovement propulsion.',jsonb_build_object('revalidate',jsonb_build_array('identity','surface','landing','contacts','dose','duration','rendering')),'review',NULL,NULL,NULL),
    (baseline_variant,paused_variant,'lateral_substitution',84,ARRAY['speed','complexity'],'Paused static hands-on-hips changes preload and arm contribution while retaining bilateral floor-to-box takeoff, landing, hold, exit, and reset.',jsonb_build_object('revalidate',jsonb_build_array('preload','arm_policy','box_height','dose','fatigue','duration','rendering')),'review',NULL,NULL,NULL),
    (paused_variant,baseline_variant,'lateral_substitution',84,ARRAY['speed','complexity'],'Natural-arm countermovement restores elastic preload and arm swing and therefore requires new height, clearance, output, and dose checks.',jsonb_build_object('revalidate',jsonb_build_array('preload','arm_policy','box_height','dose','fatigue','duration','rendering')),'review',NULL,NULL,NULL),
    (baseline_variant,no_arm_variant,'lateral_substitution',90,ARRAY['complexity'],'Hands-on-hips preserves the countermovement and landing sequence but removes arm-swing contribution and changes output and coordination.',jsonb_build_object('revalidate',jsonb_build_array('arm_policy','box_height','output','dose','duration','rendering')),'review',NULL,NULL,NULL),
    (no_arm_variant,baseline_variant,'lateral_substitution',90,ARRAY['complexity'],'Natural arm swing changes coordination and attainable output while preserving the remaining exact box-jump sequence.',jsonb_build_object('revalidate',jsonb_build_array('arm_policy','box_height','output','dose','duration','rendering')),'review',NULL,NULL,NULL),
    (baseline_variant,one_step_variant,'progression',82,ARRAY['speed','complexity'],'One lead step and bilateral gather add approach rhythm, momentum, station length, projection, and approach-specific failure modes.',jsonb_build_object('requires',jsonb_build_array('owned_stationary_box_jump','declared_lead_step','longer_clear_station')),'review',NULL,NULL,NULL),
    (one_step_variant,baseline_variant,'regression',82,ARRAY['speed','complexity'],'Removing the approach reduces entry rhythm and momentum demands while preserving the elevated bilateral landing and reset.',jsonb_build_object('useWhen',jsonb_build_array('approach_rhythm_or_space_is_limiting')),'review',NULL,NULL,NULL),
    (paused_variant,squat_jump_variant,'lateral_substitution',78,ARRAY['complexity','impact'],'Floor Squat Jump removes the box and elevated landing but preserves a static lower-body start when its exact pause and arm contract match.',jsonb_build_object('revalidate',jsonb_build_array('identity','start_depth','arm_policy','landing_surface','contacts','dose','rendering')),'review',NULL,NULL,NULL),
    (no_arm_variant,squat_jump_variant,'lateral_substitution',74,ARRAY['speed','complexity','impact'],'Squat Jump changes preload to a static start and returns landing to the floor while retaining restricted-arm bilateral propulsion.',jsonb_build_object('revalidate',jsonb_build_array('preload','landing_surface','contacts','dose','duration','rendering')),'review',NULL,NULL,NULL),
    (baseline_variant,drop_landing_variant,'compatible_pairing',62,ARRAY['impact','complexity'],'A separately reviewed drop-landing task may prepare landing observation but adds elevated passive entry and is not an identity-equivalent substitute.',jsonb_build_object('order','lower_demand_landing_preparation_before_box_jump','combineContacts',TRUE,'coachReviewRequired',TRUE),'review',NULL,NULL,NULL)
  ON CONFLICT(from_variant_id,to_variant_id,relationship) DO UPDATE SET similarity_score=EXCLUDED.similarity_score,dimensions=EXCLUDED.dimensions,reason=EXCLUDED.reason,conditions_json=EXCLUDED.conditions_json,review_status='review',created_by=NULL,reviewed_by=NULL,reviewed_at=NULL,updated_at=now()
  WHERE coaching.exercise_relationship_v1.reviewed_by IS NULL AND coaching.exercise_relationship_v1.review_status<>'approved';

  INSERT INTO coaching.exercise_identity_resolution_v1(facility_id,survivor_definition_id,resolved_definition_id,decision,rationale,evidence_json,resolution_source,reviewed_by)
  SELECT 1,canonical_id,historical.definition_id,'needs_human_review','Historical UUID-only duplicate-definition references are not present in a clean bootstrap; durable legacy-source provenance records the quarantine without fabricating a foreign-key target.',jsonb_build_object('migration',migration_key,'historicalUuidOnlyReferences',TRUE,'legacySources',source_ids,'sourceVariantSelectable',FALSE,'humanReviewRequired',TRUE,'approvalsCreated',FALSE),'deterministic_identity_equivalence',NULL
  FROM (SELECT NULL::UUID AS definition_id) historical
  WHERE FALSE
  ON CONFLICT(survivor_definition_id,resolved_definition_id) DO UPDATE SET decision=EXCLUDED.decision,rationale=EXCLUDED.rationale,evidence_json=EXCLUDED.evidence_json,resolution_source=EXCLUDED.resolution_source,reviewed_by=NULL,resolved_at=now()
  WHERE coaching.exercise_identity_resolution_v1.reviewed_by IS NULL AND coaching.exercise_identity_resolution_v1.resolution_source<>'human_review';

  INSERT INTO coaching.exercise_score_calibration_v1(facility_id,variant_id,dimension,proposed_score,anchor_tier,rationale,status,version,created_by,reviewed_by,review_notes,reviewed_at)
  SELECT 1,v.id,d.dimension,CASE d.dimension WHEN 'technicalComplexity' THEN v.complexity ELSE v.physical END,v.tier,
    CASE d.dimension WHEN 'technicalComplexity' THEN 'Review-only exercise-complexity anchor for exact approach, preload, arm policy, takeoff line, edge clearance, bilateral whole-foot landing, hold, stand, step-down, reset, and collision consequence.' ELSE 'Review-only physical-difficulty anchor for body-mass acceleration, high intent, box height, landing absorption, attempts, cumulative contacts, recent running and jumping, symptoms, fatigue, and recovery.' END||' No athlete proficiency classification is represented. Variant: '||v.variant_key||'.','review',1,NULL,NULL,NULL,NULL
  FROM (VALUES(baseline_variant,'stationary-countermovement-natural-arms',48,46,40),(paused_variant,'paused-static-hands-on-hips',54,46,60),(no_arm_variant,'stationary-countermovement-hands-on-hips',50,46,40),(one_step_variant,'one-step-bilateral-gather',58,50,60)) v(id,variant_key,complexity,physical,tier)
  CROSS JOIN (VALUES('technicalComplexity'),('absoluteLoadDemand')) d(dimension)
  ON CONFLICT(facility_id,variant_id,dimension,version) DO UPDATE SET proposed_score=EXCLUDED.proposed_score,anchor_tier=EXCLUDED.anchor_tier,rationale=EXCLUDED.rationale,status='review',created_by=NULL,reviewed_by=NULL,review_notes=NULL,reviewed_at=NULL,updated_at=now();

  UPDATE coaching.exercise SET skill_level=NULL,updated_at=now() WHERE id=ANY(source_ids);
  UPDATE coaching.exercise_safety_profile SET minimum_skill_level=NULL WHERE exercise_id=ANY(source_ids);

  INSERT INTO coaching.exercise_card_test_packet_v1(definition_id,facility_id,card_version,schema_version,audit_version,status,checks_json,blocking_issues_json,human_review_required,checked_at)
  VALUES(canonical_id,1,3,'2.0.0',migration_key,'quarantined',jsonb_build_object(
    'identity',jsonb_build_object('passed',TRUE,'legacySources',9,'activeWorkingSpecifications',4,'sourceDerivedSelectableVariants',0,'identityQuarantinedSources',source_ids),
    'taxonomy',jsonb_build_object('passed',TRUE,'controlledTerms',TRUE,'movementPatterns',jsonb_build_array('jump','land','squat','brace')),
    'anatomy',jsonb_build_object('passed',TRUE,'musclesTissuesJointsActionsPlanesLaterality',TRUE,'isolatedMuscleClaim',FALSE),
    'difficulty',jsonb_build_object('passed',TRUE,'model','max_exercise_complexity_physical_difficulty','athleteProficiency',NULL,'independentCalibrationRequired',TRUE),
    'loadFatigueRecovery',jsonb_build_object('passed',TRUE,'validFailedIncidentContacts',TRUE,'cumulativeCalfAchillesKneeHipRunningSprintJumpAndSportBudget',TRUE),
    'constraints',jsonb_build_object('passed',TRUE,'boxSurfaceTopEdgeFlightFallRouteTrafficPopulationAndSupervision',TRUE),
    'delivery',jsonb_build_object('passed',TRUE,'profiles',8,'durationScalingDoseRestStationContactsAndSubstitution',TRUE),
    'instructions',jsonb_build_object('passed',TRUE,'athleteCoachSupport',TRUE,'startFlightLandingHoldStandStepDownResetAndStopRules',TRUE),
    'research',jsonb_build_object('passed',TRUE,'sections',16,'registryVersion',research_version,'limitationsExplicit',TRUE),
    'media',jsonb_build_object('passed',FALSE,'candidateCount',5,'priorOEmbedMetadataHealthy',TRUE,'freshFetchSucceeded',FALSE,'playbackReviewed',FALSE,'exactMatchReviewed',FALSE,'captionsReviewed',FALSE,'accessibilityReviewed',FALSE,'qualityReviewed',FALSE,'approvalCreated',FALSE),
    'relationships',jsonb_build_object('passed',FALSE,'reviewOnly',10,'approved',0),'calibration',jsonb_build_object('passed',FALSE,'reviewOnly',8,'approved',0),
    'alternates',jsonb_build_object('passed',TRUE,'assessments',30,'sourceIdentityQuarantines',9),
    'generationSupport',jsonb_build_object('passed',TRUE,'selectionConstraints',TRUE,'cumulativeImpactAndFatigueBudgets',TRUE,'duration',TRUE,'equipmentAndStation',TRUE,'substitutionRevalidation',TRUE,'renderingAndPersistence',TRUE),
    'publication',jsonb_build_object('passed',FALSE,'reviewer',NULL,'approver',NULL)),
    jsonb_build_array(
      jsonb_build_object('code','CARD-MEDIA-01','message','A qualified human must watch every candidate in full and verify exact variant, setup, box, approach, preload, arm rule, takeoff, landing, exit, captions, accessibility, safety, cue quality, conflicts, reviewer identity, and current playback.'),
      jsonb_build_object('code','CARD-GRAPH-03','message','A qualified coach must approve or reject every progression, regression, substitution, and compatible-pairing proposal.'),
      jsonb_build_object('code','CARD-CALIBRATION-01','message','An independent qualified reviewer must calibrate exercise complexity and physical difficulty. These scores are not athlete proficiency.'),
      jsonb_build_object('code','CARD-PUBLISH-01','message','A qualified reviewer and separate approver must complete content review before publication. All nine legacy source cards require exact original specifications before source-derived restoration.')),TRUE,now())
  ON CONFLICT(definition_id) DO UPDATE SET facility_id=EXCLUDED.facility_id,card_version=EXCLUDED.card_version,schema_version=EXCLUDED.schema_version,audit_version=EXCLUDED.audit_version,status='quarantined',checks_json=EXCLUDED.checks_json,blocking_issues_json=EXCLUDED.blocking_issues_json,human_review_required=TRUE,checked_at=now();

  IF (SELECT count(*) FROM coaching.exercise_definition_source_v1 WHERE definition_id=canonical_id AND legacy_exercise_id=ANY(source_ids) AND provenance_json->>'sourceDisposition'='identity_quarantine')<>9
    OR (SELECT count(*) FROM coaching.exercise_variant_v1 WHERE id=ANY(source_variant_ids) AND definition_id=canonical_id AND status='archived' AND requirements_json->>'representation'='identity_quarantine')<>9
    OR (SELECT count(*) FROM coaching.exercise_variant_v1 WHERE id=ANY(active_variant_ids) AND definition_id=canonical_id AND status='review' AND requirements_json->>'selectable'='true' AND difficulty_json->>'technicalMeaning'='exercise_complexity' AND difficulty_json->>'loadMeaning'='physical_difficulty' AND (difficulty_json->>'baseOverallDifficulty')::INTEGER=GREATEST((difficulty_json->>'technicalComplexity')::INTEGER,(difficulty_json->>'physicalDifficulty')::INTEGER))<>4 THEN
    RAISE EXCEPTION '% found invalid source quarantine or working specifications',migration_key;
  END IF;
  IF (SELECT count(*) FROM coaching.exercise_delivery_profile_v1 WHERE variant_id=ANY(active_variant_ids) AND status='review' AND cardinality(equipment_required)>0 AND coalesce(time_model_json->>'durationFormula','')<>'' AND length(coach_instructions)>=100 AND length(athlete_instructions) BETWEEN 10 AND 240 AND cardinality(stop_rules)>=10)<>8
    OR (SELECT count(DISTINCT section_key) FROM coaching.exercise_section_evidence_v1 WHERE definition_id=canonical_id AND reviewed_card_version=3 AND review_status='candidate' AND reviewer_user_id IS NULL)<>16
    OR (SELECT count(*) FROM coaching.exercise_media_candidate_v1 WHERE definition_id=canonical_id AND reviewed_card_version=3 AND video_id=ANY(current_video_ids) AND link_status='healthy' AND review_status='candidate' AND embedding_allowed AND captions_available IS NULL AND exact_variant_match IS NULL AND demonstration_quality_score IS NULL AND reviewer_user_id IS NULL AND reviewed_at IS NULL)<>5
    OR (SELECT count(*) FROM coaching.exercise_alternate_assessment_v1 WHERE definition_id=canonical_id AND reviewed_card_version=3 AND review_status='candidate' AND reviewer_user_id IS NULL)<>30 THEN
    RAISE EXCEPTION '% found incomplete profiles %, evidence %, media %, or alternates %',migration_key,
      (SELECT count(*) FROM coaching.exercise_delivery_profile_v1 WHERE variant_id=ANY(active_variant_ids) AND status='review' AND cardinality(equipment_required)>0 AND coalesce(time_model_json->>'durationFormula','')<>'' AND length(coach_instructions)>=100 AND length(athlete_instructions) BETWEEN 10 AND 240 AND cardinality(stop_rules)>=10),
      (SELECT count(DISTINCT section_key) FROM coaching.exercise_section_evidence_v1 WHERE definition_id=canonical_id AND reviewed_card_version=3 AND review_status='candidate' AND reviewer_user_id IS NULL),
      (SELECT count(*) FROM coaching.exercise_media_candidate_v1 WHERE definition_id=canonical_id AND reviewed_card_version=3 AND video_id=ANY(current_video_ids) AND link_status='healthy' AND review_status='candidate' AND embedding_allowed AND captions_available IS NULL AND exact_variant_match IS NULL AND demonstration_quality_score IS NULL AND reviewer_user_id IS NULL AND reviewed_at IS NULL),
      (SELECT count(*) FROM coaching.exercise_alternate_assessment_v1 WHERE definition_id=canonical_id AND reviewed_card_version=3 AND review_status='candidate' AND reviewer_user_id IS NULL);
  END IF;
  IF (SELECT count(*) FROM coaching.exercise_relationship_v1 WHERE from_variant_id=ANY(active_variant_ids) AND review_status='review' AND reviewed_by IS NULL)<>10
    OR (SELECT count(*) FROM coaching.exercise_score_calibration_v1 WHERE variant_id=ANY(active_variant_ids) AND status='review' AND version=1 AND reviewed_by IS NULL)<>8
    OR (SELECT count(*) FROM coaching.exercise_definition_source_v1 WHERE definition_id=canonical_id AND legacy_exercise_id=ANY(source_ids) AND provenance_json->>'sourceDisposition'='identity_quarantine')<>9 THEN
    RAISE EXCEPTION '% found incomplete graph, calibration, or identity resolution',migration_key;
  END IF;
  IF EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 d CROSS JOIN LATERAL unnest(d.movement_patterns) key WHERE d.id=canonical_id AND NOT EXISTS(SELECT 1 FROM coaching.movement_pattern a WHERE a.key=key))
    OR EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 d CROSS JOIN LATERAL unnest(d.body_regions) key WHERE d.id=canonical_id AND NOT EXISTS(SELECT 1 FROM coaching.body_region a WHERE a.key=key))
    OR EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 d CROSS JOIN LATERAL unnest(d.required_equipment||d.optional_equipment) key WHERE d.id=canonical_id AND NOT EXISTS(SELECT 1 FROM coaching.equipment a WHERE a.key=key))
    OR EXISTS(SELECT 1 FROM coaching.exercise_relationship_v1 r WHERE r.from_variant_id=ANY(active_variant_ids) AND r.relationship IN('progression','regression') AND EXISTS(SELECT 1 FROM unnest(r.dimensions) dimension WHERE dimension<>ALL(ARRAY['load','leverage','range','speed','stability','complexity','impact','decision_demand','fatigue']))) THEN
    RAISE EXCEPTION '% created uncontrolled taxonomy or graph dimensions',migration_key;
  END IF;
  IF EXISTS(SELECT 1 FROM coaching.exercise WHERE id=ANY(source_ids) AND skill_level IS NOT NULL)
    OR EXISTS(SELECT 1 FROM coaching.exercise_safety_profile WHERE exercise_id=ANY(source_ids) AND minimum_skill_level IS NOT NULL)
    OR EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 WHERE id=canonical_id AND (reviewed_by IS NOT NULL OR approved_by IS NOT NULL OR last_reviewed_at IS NOT NULL OR approved_video_url IS NOT NULL))
    OR EXISTS(SELECT 1 FROM coaching.exercise_media_candidate_v1 WHERE definition_id=canonical_id AND reviewed_card_version=3 AND (review_status IN('approved') OR reviewer_user_id IS NOT NULL OR reviewed_at IS NOT NULL OR captions_available IS NOT NULL OR exact_variant_match IS NOT NULL OR demonstration_quality_score IS NOT NULL))
    OR EXISTS(SELECT 1 FROM coaching.exercise_card_test_packet_v1 WHERE definition_id=canonical_id AND (status<>'quarantined' OR human_review_required<>TRUE OR jsonb_array_length(blocking_issues_json)<>4)) THEN
    RAISE EXCEPTION '% fabricated proficiency, approval, or publication state',migration_key;
  END IF;
END;
$$;
