-- Reassess every Nordic Hamstring Curl source, remove an unrelated inherited
-- calf-raise citation, and replace the empty baseline with exact working
-- specifications. Human media, graph, calibration, content, and publication
-- approvals remain quarantined and are never inferred by this migration.

DO $$
DECLARE
  migration_key CONSTANT TEXT := '464_coaching_nordic_hamstring_family_audit_hardening';
  research_version CONSTANT TEXT := '2026-08-02.76';
  canonical_id CONSTANT UUID := '03894b45-360d-444b-a142-6771ce6df7dd';
  source_ids CONSTANT BIGINT[] := ARRAY[4,574,839];
  source_variant_ids CONSTANT UUID[] := ARRAY[
    'd27b89ec-6173-4d4e-b909-b859610626b9'::UUID,
    'a3424503-52f1-4303-8549-1aaa9487091e'::UUID,
    '934fa3fd-a045-4db4-b973-a4b6401038cc'::UUID];
  archived_definition_ids CONSTANT UUID[] := ARRAY[
    '3dc7851c-4551-4296-8108-baa0f4c9e66f'::UUID,
    '77da4d2d-ca77-4e9a-aa47-f159592a232e'::UUID];
  eccentric_variant CONSTANT UUID := '12796771-cd0b-4344-ab3b-e91f579b5473';
  band_variant CONSTANT UUID := 'a4e727f1-6e9b-41d5-aa10-88a9a15a3a2c';
  unassisted_variant CONSTANT UUID := '8d3befd9-33a1-4686-a421-9d766c540df9';
  isometric_variant CONSTANT UUID := 'ee63d821-8e03-4402-b1a5-355705ce43fc';
  active_variant_ids CONSTANT UUID[] := ARRAY[eccentric_variant,band_variant,unassisted_variant,isometric_variant];
  slider_eccentric_variant CONSTANT UUID := '2985c2f2-acfc-46c4-baeb-db578491bcdf';
  slider_full_cycle_variant CONSTANT UUID := '3cb62825-50d0-4464-8415-142d97cc2d3d';
  slider_short_range_variant CONSTANT UUID := '6a655995-f781-45d4-8abc-5dc125e79bc8';
  current_video_ids CONSTANT TEXT[] := ARRAY['_e9vFU9-tkc','6NCN6kOagfY','IiofP9cn_nc','6_WWA3cQF-w','kLE6k4DYgzQ'];
  protected_count INTEGER;
BEGIN
  IF NOT EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 WHERE id=canonical_id AND slug='nordic-hamstring-curl')
    OR (SELECT count(*) FROM coaching.exercise_definition_source_v1 WHERE definition_id=canonical_id AND legacy_exercise_id=ANY(source_ids))<>3
    OR (SELECT count(*) FROM coaching.exercise_variant_v1 WHERE id=ANY(source_variant_ids) AND definition_id=canonical_id)<>3
    OR (SELECT count(*) FROM coaching.exercise_definition_v1 WHERE id=ANY(archived_definition_ids) AND status='archived')<>2
    OR NOT EXISTS(SELECT 1 FROM coaching.exercise_variant_v1 v JOIN coaching.exercise_definition_v1 d ON d.id=v.definition_id WHERE v.id=slider_eccentric_variant AND d.slug='hamstring-slider-curl')
    OR NOT EXISTS(SELECT 1 FROM coaching.exercise_variant_v1 v JOIN coaching.exercise_definition_v1 d ON d.id=v.definition_id WHERE v.id=slider_full_cycle_variant AND d.slug='hamstring-slider-curl')
    OR NOT EXISTS(SELECT 1 FROM coaching.exercise_variant_v1 v JOIN coaching.exercise_definition_v1 d ON d.id=v.definition_id WHERE v.id=slider_short_range_variant AND d.slug='hamstring-slider-curl') THEN
    RAISE EXCEPTION '% prerequisite identity state is missing or drifted',migration_key;
  END IF;
  IF EXISTS(SELECT 1 FROM coaching.exercise_variant_v1 WHERE id=ANY(active_variant_ids) AND definition_id<>canonical_id) THEN
    RAISE EXCEPTION '% working variant UUID is already owned by another definition',migration_key;
  END IF;

  SELECT COALESCE(sum(n),0) INTO protected_count FROM (
    SELECT count(*) n FROM coaching.exercise_definition_v1 WHERE id=canonical_id AND (reviewed_by IS NOT NULL OR approved_by IS NOT NULL OR last_reviewed_at IS NOT NULL)
    UNION ALL SELECT count(*) FROM coaching.exercise_section_evidence_v1 WHERE definition_id=canonical_id AND reviewer_user_id IS NOT NULL
    UNION ALL SELECT count(*) FROM coaching.exercise_media_candidate_v1 WHERE definition_id=canonical_id AND (reviewer_user_id IS NOT NULL OR reviewed_at IS NOT NULL OR review_status IN('approved'))
    UNION ALL SELECT count(*) FROM coaching.exercise_alternate_assessment_v1 WHERE definition_id=canonical_id AND reviewer_user_id IS NOT NULL
    UNION ALL SELECT count(*) FROM coaching.exercise_delivery_profile_v1 WHERE variant_id=ANY(source_variant_ids||active_variant_ids) AND status='approved'
    UNION ALL SELECT count(*) FROM coaching.exercise_relationship_v1 WHERE (from_variant_id=ANY(source_variant_ids||active_variant_ids) OR to_variant_id=ANY(source_variant_ids||active_variant_ids)) AND (reviewed_by IS NOT NULL OR review_status IN('approved'))
    UNION ALL SELECT count(*) FROM coaching.exercise_score_calibration_v1 WHERE variant_id=ANY(source_variant_ids||active_variant_ids) AND (reviewed_by IS NOT NULL OR status='approved')
  ) protected;
  IF protected_count<>0 THEN RAISE EXCEPTION '% refuses to replace human review',migration_key; END IF;

  UPDATE coaching.exercise_section_evidence_v1 SET review_status='superseded',updated_at=now()
  WHERE definition_id=canonical_id AND review_status='candidate' AND reviewer_user_id IS NULL;
  UPDATE coaching.exercise_media_candidate_v1 SET review_status='superseded',updated_at=now()
  WHERE definition_id=canonical_id AND review_status='candidate' AND reviewer_user_id IS NULL;
  UPDATE coaching.exercise_alternate_assessment_v1 SET review_status='superseded',updated_at=now()
  WHERE definition_id=canonical_id AND review_status='candidate' AND reviewer_user_id IS NULL;
  DELETE FROM coaching.exercise_relationship_v1
  WHERE (from_variant_id=ANY(source_variant_ids||active_variant_ids) OR to_variant_id=ANY(source_variant_ids||active_variant_ids))
    AND reviewed_by IS NULL AND review_status<>'approved';
  DELETE FROM coaching.exercise_score_calibration_v1
  WHERE variant_id=ANY(source_variant_ids||active_variant_ids) AND reviewed_by IS NULL AND status<>'approved';

  UPDATE coaching.exercise_definition_source_v1 SET
    source_kind=CASE WHEN legacy_exercise_id=4 THEN 'legacy_migration' ELSE 'duplicate_consolidation' END,
    provenance_json=coalesce(provenance_json,'{}'::JSONB)||jsonb_build_object(
      'migration',migration_key,'sourceDisposition','identity_quarantine','representedBySelectableSourceVariant',FALSE,
      'ambiguity',CASE legacy_exercise_id
        WHEN 4 THEN 'source_only_claims_eccentric_posterior_chain_and_injury_proofing_without_anchor_range_tempo_return_or_dose_contract'
        WHEN 574 THEN 'source_names_assistance_and_concentric_intent_without_assistance_interface_anchor_range_tempo_or_return_contract'
        ELSE 'source_names_owned_angle_and_about_six_seconds_without_support_slope_knee_angle_hip_angle_entry_or_exit_contract' END,
      'invalidPriorCitationRemoved','https://pubmed.ncbi.nlm.nih.gov/38156065/',
      'invalidPriorCitationReason','calf_raise_hypertrophy_study_not_nordic_hamstring_evidence',
      'correctedEvidencePmids',jsonb_build_array('31502142','31644582','30808663','38439779','40991853'),
      'authoritativeSourceRecoveryRequired',TRUE,'humanReviewRequired',TRUE,'approvalsCreated',FALSE)
  WHERE definition_id=canonical_id AND legacy_exercise_id=ANY(source_ids);

  UPDATE coaching.exercise_variant_v1 SET
    variant_key='identity-quarantine-source-'||(source_ids[array_position(source_variant_ids,id)])::TEXT,
    display_name='Nordic Hamstring Identity Quarantine — Source '||(source_ids[array_position(source_variant_ids,id)])::TEXT,
    modifier_keys='{}'::TEXT[],difficulty_json='{}'::JSONB,status='archived',
    requirements_json=jsonb_build_object('selectable',FALSE,'representation','identity_quarantine','sourceLegacyExerciseId',source_ids[array_position(source_variant_ids,id)],'archiveReason','source_omits_required_anchor_contraction_assistance_range_tempo_angle_entry_exit_return_or_dose_identity','originalAuthoritativeEvidenceRequired',TRUE,'humanReviewRequired',TRUE),
    load_profile_json=jsonb_build_object('selectable',FALSE),fatigue_profile_json=jsonb_build_object('selectable',FALSE),
    programming_profile_json=jsonb_build_object('selectionStatus','identity_quarantine','selectable',FALSE,'publicationQuarantined',TRUE,'neverRestoreFromNameMediaOrInvalidCitation',TRUE),updated_at=now()
  WHERE id=ANY(source_variant_ids);
  UPDATE coaching.exercise_delivery_profile_v1 SET status='archived',updated_at=now() WHERE variant_id=ANY(source_variant_ids);
  UPDATE coaching.exercise_definition_v1 SET status='archived',approved_video_url=NULL,reviewed_by=NULL,approved_by=NULL,last_reviewed_at=NULL,
    provenance_json=coalesce(provenance_json,'{}'::JSONB)||jsonb_build_object('nordicAuditHardeningMigration',migration_key,'survivorDefinitionId',canonical_id,'selectable',FALSE,'invalidPriorCitationRemoved','https://pubmed.ncbi.nlm.nih.gov/38156065/','humanReviewRequired',TRUE,'approvalsCreated',FALSE),updated_at=now()
  WHERE id=ANY(archived_definition_ids);

  UPDATE coaching.exercise_definition_v1 SET
    canonical_name='Nordic Hamstring Curl',display_name='Nordic Hamstring Curl',
    aliases=ARRAY['Nordic Curl','Nordic Curls','Nordic Hamstring Exercise','Nordic Hamstring Exercises','Nordic Hamstring Lower','Nordic Hamstring Lowers']::TEXT[],
    description='A bilateral kneeling, ankle-anchored knee-flexor family in which the trunk, pelvis, and thighs remain one controlled line while the knees extend under eccentric hamstring torque, hold at a declared angle, or flex to return. Every selectable variant fixes anchor, support slope, hip position, contraction mode, assistance interface, range, tempo or hold, catch, and return strategy.',
    family_key='kneeling_ankle_anchored_nordic_knee_flexion',schema_version='2.0.0',card_version=2,status='review',
    content_confidence=93,scoring_confidence=65,media_confidence=54,
    movement_patterns=ARRAY['brace']::TEXT[],
    body_regions=ARRAY['hamstrings','knee','hip','pelvis','core','spine','calf','ankle']::TEXT[],
    required_equipment=ARRAY['nordic_bench','mat']::TEXT[],optional_equipment=ARRAY['bands','anchor_point','wedge','line_tape','partner']::TEXT[],
    anatomy_json=jsonb_build_object(
      'primaryMuscles',jsonb_build_array('biceps_femoris_long_head','semitendinosus','semimembranosus'),
      'secondaryMuscles',jsonb_build_array('biceps_femoris_short_head','gastrocnemius','gluteus_maximus','abdominal_wall','spinal_stabilizers'),
      'connectiveTissues',jsonb_build_array('hamstring_tendons','knee_flexor_myotendinous_units','supporting_knee_and_ankle_tissues'),
      'joints',jsonb_build_array('knee','hip','pelvis','lumbosacral_complex','ankle'),
      'jointActions',jsonb_build_array('bilateral_knee_extension_during_eccentric_lowering','bilateral_knee_flexion_during_concentric_return','angle_specific_isometric_knee_flexor_torque','hip_extension_and_pelvis_control','trunk_bracing','ankle_anchor_force_transfer'),
      'jointActionPhases',jsonb_build_object('setup',jsonb_build_array('bilateral_kneeling','rated_bilateral_ankle_anchor','declared_support_slope'),'lower',jsonb_build_array('controlled_knee_extension','isometric_hip_and_trunk_line'),'hold',jsonb_build_array('declared_knee_and_hip_angles_without_visible_motion'),'return',jsonb_build_array('declared_assisted_unassisted_or_unloaded_strategy'),'finish',jsonb_build_array('controlled_kneeling_reset')),
      'planes',jsonb_build_array('sagittal_primary','frontal_and_transverse_control'),
      'laterality',jsonb_build_object('support','bilateral_kneeling','anchor','bilateral','kneeFlexorAction','bilateral','unilateralVersionsRequireSeparateDefinition',TRUE),
      'terminologyGuard','Knees extend during the lowering motion while the knee flexors act eccentrically; do not label the visible lowering joint motion knee flexion.',
      'evidenceLimit','Small acute EMG and kinematic studies do not establish one universal muscle ranking, support slope, joint angle, range, dose, readiness threshold, safety threshold, or clinical effect.'),
    environment_json=jsonb_build_object('surface','level_dry_consistent_high_traction_with_padded_knee_and_hand_catch_zones','anchor','rated_bilateral_symmetric_ankle_restraint_inspected_before_each_user','clearance',jsonb_build_array('forward_lowering_and_catch_arc','hand_catch','band_or_assistance_path','coach_access','safe_exit'),'traffic','none_through_station','bandSafety',jsonb_build_array('rated_high_anchor','inspect_band_and_attachment','upper_torso_below_armpits_only','never_neck_head_or_face','no_bystander_in_recoil_path'),'inclineSafety','Any wedge or inclined lower-leg support must be rigidly secured and its actual angle recorded.'),
    population_json=jsonb_build_object('defaultPopulation','participants_with_pain_free_kneeling_and_individualized_tolerance_for_bilateral_knee_flexor_loading','individualizationRequired',TRUE,'prerequisites',jsonb_build_array('pain_free_kneeling_and_ankle_anchor_contact','can_hold_trunk_pelvis_and_thighs_as_one line','can_use_hands_to_catch_and_exit_on_command','can_report_cramp_pain_fear_fatigue_and_recovery'),'cautions',jsonb_build_array('current_or_recent_hamstring_knee_hip_ankle_or_spine_symptoms','recent_sprinting_change_of_direction_or_high_eccentric_lower_body exposure','unfamiliar_or_high_soreness_response','uncontrolled_neurologic_cardiopulmonary_balance_or_breathing condition','pregnancy_or_postpartum_status_requiring_individualization','unsafe_anchor_padding_band_incline_space_or_supervision'),'notClinicalClearance',TRUE,'injuryReductionEvidenceScope','programmes_including_nordic_exercise_not_a_guarantee_for_this_card_or_individual','neverInferReadinessFromExerciseDifficulty',TRUE),
    athlete_support_json=jsonb_build_object('whatItIs','Kneel with both ankles secured and keep shoulders, hips, and knees in one line while you lower, hold, or return exactly as assigned.','before',jsonb_build_array('Confirm exact variant, anchor, support slope, assistance, range, tempo or hold, catch, return, sets, rest, and stop signal.','Inspect padding, anchor, assistance path, and clear fall space with the coach.','Report pain, cramp, unusual soreness, weakness, fear, or uncertainty before starting.'),'during',jsonb_build_array('Keep hips from folding or leading.','Follow the assigned lower, hold, catch, and return strategy; do not improvise a concentric rep.','Catch with ready hands when assigned and reset completely.','Stop before range, tempo, body line, breathing, or confidence changes.'),'expectedSensations',jsonb_build_array('high_hamstring_tension','controlled_front_of_body_fall','firm_trunk_and_glute support'),'notExpected',jsonb_build_array('sharp_or_increasing_pain','sudden_pull_or_pop','uncontrolled_cramp','knee_or_ankle_pressure','dizziness','band_contact_at_neck_or_face','surprise_fall'),'selfChecks',jsonb_build_array('exact_anchor_and_variant','shoulders_hips_knees_remain_aligned','assigned_tempo_angle_and_range','planned_catch_and_return','full_reset_and_calm_breathing'),'accessibility',jsonb_build_array('shorter_range_target','more_band_assistance','eccentric_catch_reset','fixed_angle_hold','hamstring_slider_curl','longer_rest','fewer_repetitions'),'stopSignal','Stop immediately, catch safely, unload the anchor or band, tell the coach what changed, and do not retry until symptoms, identity, dose, equipment, and recovery are re-evaluated.'),
    coach_support_json=jsonb_build_object('setupChecklist',jsonb_build_array('verify_exact_variant_contraction_assistance_range_tempo_angle_catch_and_return','inspect_bilateral_anchor_knee_padding_hand_catch_surface_band_and_recoil_path','declare_sets_reps_or_hold_seconds_rest_total_eccentric_exposure_and_stop threshold','review_recent_sprint_running_jump_hinge_slider_curl_nordic_and_sport exposure'),'observeFromSide',jsonb_build_array('knee_extension_angle_and_velocity','shoulder_hip_knee_line','hip_flexion_escape','break_point_and_declared_range','catch_hold_return_and_reset'),'observeFromFrontOrRear',jsonb_build_array('symmetric_anchor_and_knee pressure','pelvis_and_trunk_rotation','band_or_assistance alignment','bilateral_effort_and_exit'),'validRep','The exact anchor, support slope, hip position, contraction mode, assistance, range, tempo or hold, catch, return, body line, breathing, symptoms, and reset all pass without a stop rule.','correctionOrder',jsonb_build_array('wrong_variant_or_unsafe_anchor_band_padding_or_space','pain_cramp_fear_dizziness_or_incident_stop','hip_fold_trunk_extension_or_rotation','tempo_range_angle_or_assistance drift','catch_return_or_reset mismatch','dose_duration_and_recovery budget'),'groupManagement',jsonb_build_array('one_active_athlete_per_anchor_and_forward_fall zone','next_athlete_waits_outside_band_and_catch path','coach_controls_anchor_band_and_range changes','record_failed_and_incident_repetitions_as_exposure'),'escalation','Quarantine selection when source identity, anchor, assistance, angle, symptoms, prior exposure, supervision, or recovery is uncertain; this card is not rehabilitation clearance.'),
    support_operations_json=jsonb_build_object('selectionInputs',jsonb_build_array('definition_variant_profile_card_and_research_version','objective_and_session_phase','anchor_support_slope_hip_position_contraction_assistance_range_tempo_hold_catch_and_return','sets_reps_or_seconds_rest_duration_and_total_eccentric exposure','recent_hamstring_sprint_running_jump_hinge_slider_nordic_and_sport load','symptoms_soreness_recovery_population_supervision_and_environment'),'persistence',jsonb_build_array('workout_and_item_id','definition_variant_profile_card_and_research_version','anchor_support_slope_assistance_interface_range_target_tempo_hold_and_return','sets_valid_failed_and_incident_repetitions_or_seconds','body_line_break_point_faults_symptoms_cramp_duration_and recovery','substitution_and_rendered_athlete_coach_instruction versions'),'incidentPath',jsonb_build_array('call_stop_and_help_athlete_catch_and_unload','secure_anchor_band_and_station','record_variant_range_tempo_angle_assistance_rep_fault_symptom_and context','follow_facility_emergency_or_clinical_referral policy','quarantine_uncertain_source_card_or media'),'changeImpact','Any anchor, support slope, hip angle, contraction, assistance interface, range, tempo, hold, catch, return, dose, fatigue, recovery, population, station, or media change invalidates cached selection, duration, logistics, rendering, and approval assumptions.','publication',jsonb_build_object('humanMediaGraphCalibrationContentAndSeparateApprovalRequired',TRUE)),
    provenance_json=coalesce(provenance_json,'{}'::JSONB)-'researchSources'||jsonb_build_object('nordicAuditHardeningMigration',migration_key,'researchVersion',research_version,'canonicalAuthoredFromResearch',TRUE,'legacySourcesQuarantined',source_ids,'activeWorkingSpecifications',jsonb_build_array('eccentric-five-second-catch-reset','band-assisted-declared-range-full-cycle','unassisted-declared-range-full-cycle','incline-30-k30-h0-five-second-hold-catch-reset'),'removedUnrelatedCitation','https://pubmed.ncbi.nlm.nih.gov/38156065/','correctedResearchSources',jsonb_build_array('https://pubmed.ncbi.nlm.nih.gov/31502142/','https://pubmed.ncbi.nlm.nih.gov/31644582/','https://pubmed.ncbi.nlm.nih.gov/30808663/','https://pubmed.ncbi.nlm.nih.gov/38439779/','https://pubmed.ncbi.nlm.nih.gov/40991853/'),'identityDecision','bilateral_kneeling_ankle_anchored_knee_flexor_family_with_exact_contraction_assistance_range_angle_and_return variants','mediaState','five_current_oembed_healthy_candidates_unreviewed','oembedCheckedAt','2026-08-02','exerciseDifficultyModel','exercise_complexity_and_physical_difficulty_only','approvalsCreated',FALSE,'publicationQuarantined',TRUE,'humanReviewRequired',TRUE),
    approved_video_url=NULL,reviewed_by=NULL,approved_by=NULL,last_reviewed_at=NULL,updated_at=now()
  WHERE id=canonical_id;

  INSERT INTO coaching.exercise_variant_v1(id,definition_id,variant_key,display_name,modifier_keys,difficulty_json,requirements_json,status,load_profile_json,fatigue_profile_json,programming_profile_json)
  SELECT v.id,canonical_id,v.variant_key,v.display_name,
    ARRAY['anchor_type','support_slope_degrees','range_target','sets','repetitions_or_hold_seconds','rest_seconds']::TEXT[],
    jsonb_build_object('technicalComplexity',v.complexity,'absoluteLoadDemand',v.physical,'physicalDifficulty',v.physical,'baseOverallDifficulty',GREATEST(v.complexity,v.physical),'coordinationDemand',v.coordination,'supervisionDemand',v.supervision,'failureConsequence',v.failure,'impact',v.impact,'workCapacityDemand',v.work_capacity,'provisional',TRUE,'difficultyModel','max_exercise_complexity_physical_difficulty','technicalMeaning','exercise_complexity','loadMeaning','physical_difficulty','athleteReadinessStoredHere',FALSE),
    jsonb_build_object('actionIdentity','bilateral_kneeling_ankle_anchored_nordic','contractionMode',v.contraction_mode,'assistance',v.assistance,'supportSlope',v.support_slope,'hipPosition',v.hip_position,'range',v.range_contract,'tempoOrHold',v.tempo_hold,'catchStrategy',v.catch_strategy,'returnStrategy',v.return_strategy,'laterality','bilateral','selectable',TRUE,'identityQuarantine',FALSE,'workingSpecificationRequiresHumanContentReview',TRUE),
    'review',
    jsonb_build_object('gripDemand',v.grip,'externalLoadMethod',v.load_method,'externalLoadDescription',v.load_description,'spinalLoading',34,'eccentricStress',v.eccentric_stress,'impactClass','low_but_forward_fall_and_hand_catch_consequence_present','loadTracking',jsonb_build_array('body_mass','anchor_and_support_slope','assistance_type_position_and_resistance','range_target_and_break_point','eccentric_seconds_or_hold_seconds','valid_failed_and_incident_repetitions','symptoms_soreness_and_recovery'),'effectiveLoadDrivers',jsonb_build_array('body_mass_and_segment_lengths','support_slope','knee_and_hip_angles','assistance_curve','range_and_break_point','eccentric_duration','concentric_return_requirement','repetitions','recent_sprinting_running_hinge_and_hamstring work')),
    jsonb_build_object('localMuscleFatigue',v.local_fatigue,'gripFatigue',v.grip,'technicalFatigueSensitivity',v.tech_fatigue,'neuralOutputDemand',v.neural,'impactAccumulation',4,'recoveryHours','24_to_120_context_and_novelty_dependent','primaryFatigueSites',jsonb_build_array('hamstring_knee_flexors','proximal_and_distal_hamstring_tissues','gastrocnemius','gluteal_trunk_and_pelvic stabilizers'),'earlyFatigueSignals',jsonb_build_array('earlier_break_point','faster_lowering','hip_flexion_escape','trunk_extension_or_rotation','asymmetric_anchor pressure','incomplete_return','cramp_or_unusual soreness'),'downstreamConflicts',jsonb_build_array('priority_max_velocity_sprinting_or_change_of_direction','high_volume_running_or_kicking','heavy_hinge_slider_curl_or_other_eccentric hamstring work','symptomatic_hamstring_knee_hip_ankle_or_spine loading')),
    jsonb_build_object('trainingStimuli',v.stimuli,'stimulusDose',jsonb_build_object('primary',v.dose_primary,'fatigueCeiling','low','countFailedAndIncidentExposure',TRUE),'weeklyExposure','Combine every valid, failed, and incident Nordic repetition or hold with sprinting, running, kicking, hinging, slider curls, and other hamstring loading; novelty and soreness alter recovery.','prerequisites',jsonb_build_array('pain_free_kneeling_and_anchor_contact','exact_variant_and_exit_understood','body_line_control_at_assigned_range','recent_exposure_symptoms_and_recovery reviewed'),'completionCriteria',jsonb_build_array('exact_contraction_assistance_range_tempo_or_hold','body_line_and_bilateral_anchor pass','planned_catch_return_and_reset pass','dose_fault_symptom_duration_and_recovery records complete'),'sequenceRules',jsonb_build_array('place_after_specific_preparation','use_before_fatiguing_lower_body_work_when_quality_is priority','avoid_stacking_with_unbudgeted_sprint_or_eccentric exposure','never_extend_sets_to_chase_soreness_or fatigue'),'pairingCompatibility',jsonb_build_array('noncompeting_low_risk_upper_body_mobility_or_breathing_task_during_full rest'),'interferenceRules',jsonb_build_array('do_not_prefatigue_hamstrings_before_quality_nordics','do_not_assume_more_range_or_less_assistance_is_appropriate','recompute_identity_fatigue_duration_logistics_and_rendering_after substitution'),'uncertaintyPolicy',jsonb_build_object('unknownIdentityAnchorSymptomsDoseOrRecovery','fail_closed_and_request_coach_review','neverInferMissingSourceMechanics',TRUE,'neverAutoApproveMediaGraphCalibrationOrPublication',TRUE),'cumulativeBudget',jsonb_build_object('hamstringEccentric',v.eccentric_budget,'kneeFlexorHighTension',v.tension_budget,'technicalSensitivity',v.tech_fatigue,'sameSessionSprintRunningKickingHingeSliderNordicAndSportRequired',TRUE))
  FROM (VALUES
    (eccentric_variant,'eccentric-five-second-catch-reset','Nordic Hamstring — 5-Second Eccentric, Catch and Reset',46,72,48,68,64,8,36,1,'bodyweight','Body mass provides knee-extension leverage; hands catch on the padded surface and fully unload the return.',86,72,58,60,jsonb_build_array('bilateral_eccentric_knee_flexor_loading','five_second_range_control','planned_hand_catch'),'five_second_eccentric_repetitions',82,84,'eccentric_only','none','level_lower_leg_support','hip_neutral_body_line','declared_last_controllable_angle_or_padded_catch_target','five_second_lower','two_hand_padded_catch','hands_and_hip_flexion_fully_unload_return'),
    (band_variant,'band-assisted-declared-range-full-cycle','Nordic Hamstring — Band-Assisted Declared-Range Full Cycle',58,64,62,78,72,6,42,12,'bodyweight_plus_assistance','Body mass is partly offset by a recorded band attached to a rated high anchor and contacting the upper torso below the armpits, never the neck or head.',72,66,62,52,jsonb_build_array('assisted_eccentric_and_concentric_knee_flexor_loading','continuous_declared_range_cycle','assistance_curve_control'),'assisted_full_cycle_repetitions',72,76,'eccentric_and_concentric','rated_high_anchor_band_to_upper_torso_below_armpits','level_lower_leg_support','hip_neutral_body_line','declared_terminal_angle_with_no_hand_contact','controlled_down_and_controlled_up','hands_ready_for_failure_only','band_assisted_knee_flexion_return'),
    (unassisted_variant,'unassisted-declared-range-full-cycle','Nordic Hamstring — Unassisted Declared-Range Full Cycle',58,88,60,82,80,8,46,1,'bodyweight','Body mass is lowered and returned through the recorded range without external assistance or hand contact.',94,84,70,70,jsonb_build_array('unassisted_eccentric_and_concentric_knee_flexor_loading','declared_range_full_cycle','high_relative_strength'),'unassisted_full_cycle_repetitions',94,94,'eccentric_and_concentric','none','level_lower_leg_support','hip_neutral_body_line','declared_terminal_angle_with_no_hand_contact','controlled_down_and_controlled_up','hands_ready_for_failure_only','unassisted_knee_flexion_return'),
    (isometric_variant,'incline-30-k30-h0-five-second-hold-catch-reset','Nordic Hamstring — 30° Incline K30/H0 5-Second Hold',62,76,58,80,72,4,32,1,'bodyweight','Body mass creates angle-specific knee-flexor torque on a rigid 30-degree inclined lower-leg support; the entry and exit are recorded exposures.',82,70,62,62,jsonb_build_array('angle_specific_isometric_knee_flexor_loading','five_second_hold','instrumented_or_visually_standardized_position'),'five_second_angle_specific_holds',78,84,'eccentric_entry_then_isometric_hold','none','rigid_lower_leg_support_inclined_30_degrees','hip_flexion_0_degrees','knee_flexion_30_degrees','five_second_hold','two_hand_padded_catch_after_hold','hands_and_hip_flexion_fully_unload_return')
  ) v(id,variant_key,display_name,complexity,physical,coordination,supervision,failure,impact,work_capacity,grip,load_method,load_description,eccentric_stress,local_fatigue,tech_fatigue,neural,stimuli,dose_primary,eccentric_budget,tension_budget,contraction_mode,assistance,support_slope,hip_position,range_contract,tempo_hold,catch_strategy,return_strategy)
  ON CONFLICT(id) DO UPDATE SET definition_id=EXCLUDED.definition_id,variant_key=EXCLUDED.variant_key,display_name=EXCLUDED.display_name,modifier_keys=EXCLUDED.modifier_keys,difficulty_json=EXCLUDED.difficulty_json,requirements_json=EXCLUDED.requirements_json,status='review',load_profile_json=EXCLUDED.load_profile_json,fatigue_profile_json=EXCLUDED.fatigue_profile_json,programming_profile_json=EXCLUDED.programming_profile_json,updated_at=now();

  INSERT INTO coaching.exercise_delivery_profile_v1(variant_id,profile_key,phase_key,role,purpose,phase_suitability,methodology_alignment,objective_relevance_json,dosage_json,quality_gate,stop_rules,coach_instructions,athlete_instructions,expected_adaptation,equipment_required,logistics_json,substitution_ids,status,time_model_json,dose_scaling_json,measurement_json,support_prompts_json)
  SELECT p.variant_id,p.profile_key,p.phase,p.role,p.purpose,p.suitability,90,
    jsonb_build_object('hamstringStrength',5,'eccentricControl',p.eccentric_relevance,'angleSpecificControl',p.isometric_relevance,'injuryReductionGuarantee',0),
    jsonb_build_object('doseType',p.dose_type,'sets',p.sets,'repetitionsPerSet',p.reps,'holdSeconds',p.hold_seconds,'eccentricSeconds',p.eccentric_seconds,'restBetweenSetsSeconds',p.rest,'rangeTarget','declared_and_recorded','assistance','exact_variant_contract','countValidFailedAndIncidentExposure',TRUE,'repVelocityLossStop','first_meaningful_change_not_fatigue_chasing'),
    'Every counted exposure uses the exact anchor, support slope, hip position, contraction mode, assistance, range, tempo or hold, catch, and return; shoulders, hips, and knees remain one line; breathing, symptoms, and reset pass.',
    ARRAY['sharp_or_increasing_pain_pull_pop_cramp_giving_way_dizziness_or_fear','wrong_variant_anchor_slope_assistance_range_tempo_angle_catch_or_return','anchor_padding_band_wedge_catch_space_or_recoil_path_is_unsafe','band_contacts_neck_head_face_or_shows_damage_or_slippage','hips_fold_lead_or_rotate_or_trunk_extends','lowering_accelerates_or_hold_angle_drifts','unexpected_hand_contact_or_unplanned_concentric_return','earlier_break_point_incomplete_return_or_bilateral_asymmetry','breathing_or_confidence_changes','dose_duration_eccentric_or_recovery_budget_exceeded'],
    p.coach_instructions,p.athlete_instructions,p.adaptation,p.equipment,
    jsonb_build_object('athletesPerStation',1,'setupSeconds',50,'transitionSeconds',25,'station','one_inspected_bilateral_ankle_anchor_with_exclusive_forward_fall_catch_and_assistance path','equipmentCheck','rated_symmetric_anchor_secure_padding_dry_surface_and_any_band_or_wedge_inspected','changeRule','coach_reinspects_and_recomputes_identity_load_fatigue_duration_and risk','substitutionRevalidation',jsonb_build_array('identity','anchor','support_slope','hip_angle','contraction','assistance','range','tempo_or_hold','catch','return','fatigue','duration','population','rendering')),
    CASE p.variant_id WHEN eccentric_variant THEN ARRAY[band_variant,isometric_variant,slider_eccentric_variant]::UUID[] WHEN band_variant THEN ARRAY[eccentric_variant,unassisted_variant,isometric_variant,slider_full_cycle_variant]::UUID[] WHEN unassisted_variant THEN ARRAY[band_variant,eccentric_variant,slider_full_cycle_variant]::UUID[] ELSE ARRAY[eccentric_variant,band_variant,slider_short_range_variant]::UUID[] END,
    'review',jsonb_build_object('setupSeconds',50,'repSeconds',p.rep_seconds,'holdSeconds',p.hold_seconds,'resetSeconds',p.reset,'durationIncludesRest',TRUE,'durationFormula','setup + sets * (repetitions * (rep + hold + reset) + inter_set_rest) + transition','durationCeilingSeconds',p.ceiling,'recomputeAfterSubstitution',TRUE),
    jsonb_build_object('reduce',jsonb_build_array('shorten_range','increase_assistance','reduce_repetitions_or_hold','increase_rest','use_eccentric_catch_reset','use_hamstring_slider_variant'),'increase',jsonb_build_array('increase_range_with_same_contract','reduce_assistance_one_step','add_one_repetition_within_budget','use_unassisted_full_cycle_only_after_review'),'revalidateAfterChange',TRUE),
    jsonb_build_object('record',jsonb_build_array('definition_id','variant_id','profile_key','anchor_support_slope_hip_angle_and_assistance','range_target_tempo_hold_catch_and_return','sets_valid_failed_and_incident_repetitions_or_seconds','break_point_body_line_faults_symptoms_cramp_and hand_contacts','rest_duration_recent_exposure_and recovery','substitution'),'validity','all exact identity, equipment, body-line, dose, symptom, duration, and recovery gates pass'),
    jsonb_build_object('before','Which exact variant, anchor, slope, assistance, range, tempo or hold, catch, return, dose, rest, and stop signal are assigned?','during','Do body line, range, speed or angle, breathing, symptoms, assistance, catch, and return still match?','after','Store every valid, failed, and incident exposure, exact setup, break point, faults, symptoms, duration, recovery, and substitution.')
  FROM (VALUES
    (eccentric_variant,'capacity-strength','capacity','primary','Build bilateral eccentric knee-flexor strength with exact five-second lowering, planned hand catch, and unloaded reset.',94,5,1,'repetitions',3,4,0,5,150,5,45,1120,'Verify a rated symmetric ankle anchor, padded knees and hand-catch zone, exact range target, five-second lower, two-hand catch, fully unloaded return, recent sprint and hamstring exposure, soreness, and total eccentric budget.','Stay long from shoulders to knees. Lower for five seconds, catch with both hands, unload the return, and reset. Stop for pain, cramp, a faster fall, or hip fold.','Improved high-quality bilateral eccentric knee-flexor control through the declared range.',ARRAY['nordic_bench','mat']::TEXT[]),
    (eccentric_variant,'resilience-introduction','resilience','secondary','Introduce low-volume eccentric Nordic exposure without chasing soreness or range.',90,5,1,'repetitions',2,3,0,5,180,5,50,900,'Use a conservative recorded range, rated anchor, ready hand catch, full unloaded reset, and low total exposure. Review novelty, soreness, and upcoming sprint demands before adding any repetition.','Use the short assigned range. Lower for five seconds, catch, unload back to kneeling, and reset. Stop before speed, shape, breathing, or confidence changes.','Improved tolerance and repeatability for a small, controlled eccentric exposure.',ARRAY['nordic_bench','mat']::TEXT[]),
    (band_variant,'capacity-assisted-strength','capacity','primary','Train a controlled eccentric-concentric Nordic cycle through a declared range with a fixed assistance curve.',92,5,1,'repetitions',3,5,0,0,150,6,55,1180,'Inspect the high anchor, band, attachment, recoil path, torso contact below the armpits, ankle anchor, range target, and assistance level. Preserve the same assistance and body line through every down-and-up cycle.','Keep the band below your armpits, stay long, lower and return through the assigned range, and reset. Stop for band slip, pain, cramp, hip fold, or a changed return.','Improved assisted eccentric-concentric knee-flexor strength through a repeatable declared range.',ARRAY['nordic_bench','mat','bands','anchor_point']::TEXT[]),
    (band_variant,'resilience-assisted-control','resilience','secondary','Use higher assistance and low volume to standardize the full-cycle pattern and response.',88,5,1,'repetitions',2,4,0,0,180,6,60,960,'Choose enough assistance to avoid a break-point fall, verify the band never contacts neck or face, keep range conservative, and stop at the first change in speed, line, symptoms, or recovery expectation.','Let the band help. Move down and up smoothly through the short assigned range, keep hips tall, and stop for any slip, pain, cramp, or changed rep.','More repeatable assisted Nordic mechanics with controlled exposure and response.',ARRAY['nordic_bench','mat','bands','anchor_point']::TEXT[]),
    (unassisted_variant,'capacity-relative-strength','capacity','primary','Express unassisted bilateral eccentric-concentric knee-flexor strength through a declared range without hand contact.',94,5,1,'repetitions',3,3,0,0,180,7,60,1160,'Confirm the exact unassisted range was demonstrated without hand contact or hip escape, inspect the anchor and catch zone, cap repetitions, and preserve a failure catch. Do not infer readiness from the difficulty score.','Stay long, lower and return without hands through the assigned range, then reset. Catch safely and end the set if you stall, fold, cramp, or feel pain.','Improved high-relative-strength unassisted Nordic control through the declared range.',ARRAY['nordic_bench','mat']::TEXT[]),
    (unassisted_variant,'resilience-low-volume','resilience','secondary','Retain an already-owned unassisted Nordic pattern with minimal fatigue and full recovery accounting.',82,5,1,'repetitions',2,2,0,0,210,7,70,820,'Use only an already-owned range, never as an introduction. Verify readiness, anchor, catch plan, recent sprint and eccentric load, and upcoming priorities; substitute immediately if the first repetition changes.','Use only your owned range. One smooth down-and-up rep, full reset, full rest. Catch and stop for any stall, hip fold, cramp, pain, or changed confidence.','Maintenance of an already-established unassisted Nordic pattern with low session exposure.',ARRAY['nordic_bench','mat']::TEXT[]),
    (isometric_variant,'resilience-angle-control','resilience','primary','Standardize a five-second K30/H0 isometric hold on a rigid 30-degree lower-leg support, then catch and unload.',92,3,5,'holds',3,2,5,0,150,7,60,1040,'Secure and record the 30-degree lower-leg support, bilateral ankle anchor, hip-neutral line, 30-degree knee-flexion target, five-second hold, hand catch, and unloaded return. Treat entry and exit as exposure.','Lower to the K30/H0 target, hold five seconds without moving, catch with both hands, unload the return, and reset. Stop for drift, cramp, pain, or breath holding.','Improved repeatability of high-tension knee-flexor force at one explicitly standardized position.',ARRAY['nordic_bench','mat','wedge']::TEXT[]),
    (isometric_variant,'capacity-isometric-strength','capacity','secondary','Use fully rested five-second angle-specific holds to develop force at the exact K30/H0 test position.',88,3,5,'holds',3,3,5,0,180,7,65,1280,'Verify actual support and joint angles, safe entry, five-second timing, catch and exit, symptoms, and prior hamstring load. Do not generalize the acute EMG study to a universal best angle or dose.','Reach the exact marked angle, hold five seconds while breathing, catch and unload. End the set if the angle, body line, breathing, or symptoms change.','Improved angle-specific isometric knee-flexor force expression under a standardized protocol.',ARRAY['nordic_bench','mat','wedge']::TEXT[])
  ) p(variant_id,profile_key,phase,role,purpose,suitability,eccentric_relevance,isometric_relevance,dose_type,sets,reps,hold_seconds,eccentric_seconds,rest,rep_seconds,reset,ceiling,coach_instructions,athlete_instructions,adaptation,equipment)
  ON CONFLICT(variant_id,profile_key) DO UPDATE SET phase_key=EXCLUDED.phase_key,role=EXCLUDED.role,purpose=EXCLUDED.purpose,phase_suitability=EXCLUDED.phase_suitability,methodology_alignment=EXCLUDED.methodology_alignment,objective_relevance_json=EXCLUDED.objective_relevance_json,dosage_json=EXCLUDED.dosage_json,quality_gate=EXCLUDED.quality_gate,stop_rules=EXCLUDED.stop_rules,coach_instructions=EXCLUDED.coach_instructions,athlete_instructions=EXCLUDED.athlete_instructions,expected_adaptation=EXCLUDED.expected_adaptation,equipment_required=EXCLUDED.equipment_required,logistics_json=EXCLUDED.logistics_json,substitution_ids=EXCLUDED.substitution_ids,status='review',time_model_json=EXCLUDED.time_model_json,dose_scaling_json=EXCLUDED.dose_scaling_json,measurement_json=EXCLUDED.measurement_json,support_prompts_json=EXCLUDED.support_prompts_json,updated_at=now();

  INSERT INTO coaching.exercise_section_evidence_v1(definition_id,reviewed_card_version,section_key,source_url,source_title,source_publisher,source_kind,claims_json,evidence_quality,review_status,reviewer_user_id,reviewed_at)
  SELECT canonical_id,2,e.section_key,e.source_url,e.source_title,e.source_publisher,'peer_reviewed_research',
    e.claims||jsonb_build_array(jsonb_build_object('migration',migration_key,'researchVersion',research_version,'legacySourcesQuarantined',source_ids,'unrelatedCalfRaiseCitationRemoved',TRUE,'limitations','Evidence does not establish universal identity, technique, dose, readiness, safety, rehabilitation, injury prevention, or publication approval for an individual card.','humanReviewRequired',TRUE,'approvalsCreated',FALSE)),
    e.quality,'candidate',NULL,NULL
  FROM (VALUES
    ('identity','https://pubmed.ncbi.nlm.nih.gov/31644582/','Kinematic and electromyographic analysis of variations in Nordic hamstring exercise','PLOS ONE',84,jsonb_build_array(jsonb_build_object('claim','Support slope and instructed hip angle materially change range, joint torque, and execution, so they are variant dimensions.','sample','18 resistance-trained adults with little or no Nordic experience','limits','acute six-variation study'))),
    ('taxonomy','https://pubmed.ncbi.nlm.nih.gov/31644582/','Kinematic and electromyographic analysis of variations in Nordic hamstring exercise','PLOS ONE',84,jsonb_build_array(jsonb_build_object('claim','Nordic terminology must preserve support slope, hip position, and contraction or return strategy rather than rely on a name.'))),
    ('anatomy','https://pubmed.ncbi.nlm.nih.gov/38439779/','The Effect of Variations in Knee and Hip Angles on Electromyographic Activity of the Hamstrings and Related Muscles During the Nordic Hamstring Exercise','International Journal of Sports Physical Therapy',82,jsonb_build_array(jsonb_build_object('claim','Biceps femoris, semitendinosus, semimembranosus, erector spinae, gluteus maximus, and rectus abdominis activity was measured across angle conditions.','limits','surface EMG does not prove force, adaptation, or universal muscle ranking'))),
    ('biomechanics','https://pubmed.ncbi.nlm.nih.gov/31644582/','Kinematic and electromyographic analysis of variations in Nordic hamstring exercise','PLOS ONE',84,jsonb_build_array(jsonb_build_object('claim','Increasing lower-leg support slope changed achievable range while peak torque was similar in the tested sample.','limits','2D kinematics and acute laboratory task'))),
    ('difficulty','https://pubmed.ncbi.nlm.nih.gov/31644582/','Kinematic and electromyographic analysis of variations in Nordic hamstring exercise','PLOS ONE',84,jsonb_build_array(jsonb_build_object('claim','Range, support slope, hip instruction, assistance, and ability to control the break point inform provisional exercise complexity and physical difficulty.','limits','No validated universal difficulty scale was studied'))),
    ('load_fatigue_recovery','https://pubmed.ncbi.nlm.nih.gov/40991853/','Dose-Response Relationship for Strength Gains From Nordic Hamstring Exercise: A Systematic Review, Meta-Analysis, and Meta-Regression','Journal of Strength and Conditioning Research',90,jsonb_build_array(jsonb_build_object('claim','The review found eccentric strength gains across heterogeneous programmes.','limits','Low to very low certainty and confounding prevent a universal exposure or recovery rule'))),
    ('constraints','https://pubmed.ncbi.nlm.nih.gov/31644582/','Kinematic and electromyographic analysis of variations in Nordic hamstring exercise','PLOS ONE',84,jsonb_build_array(jsonb_build_object('claim','The task depends on fixed lower-leg support and controlled hip position.','limits','The study apparatus does not approve every field anchor, partner, band, or wedge setup'))),
    ('dosage','https://pubmed.ncbi.nlm.nih.gov/40991853/','Dose-Response Relationship for Strength Gains From Nordic Hamstring Exercise: A Systematic Review, Meta-Analysis, and Meta-Regression','Journal of Strength and Conditioning Research',90,jsonb_build_array(jsonb_build_object('claim','Forty-two eligible studies used widely varying weekly repetitions, frequency, and duration; meta-regression did not establish a simple volume-response relation.','limits','Low to very low certainty; reported programme ranges are not a card prescription'))),
    ('instructions','https://pubmed.ncbi.nlm.nih.gov/31644582/','Kinematic and electromyographic analysis of variations in Nordic hamstring exercise','PLOS ONE',84,jsonb_build_array(jsonb_build_object('claim','Execution instructions must state lower-leg slope and hip position because participants could not maintain some higher hip-flexion targets.'))),
    ('safety_stop_rules','https://pubmed.ncbi.nlm.nih.gov/30808663/','Including the Nordic hamstring exercise in injury prevention programmes halves the rate of hamstring injuries: a systematic review and meta-analysis of 8459 athletes','British Journal of Sports Medicine',92,jsonb_build_array(jsonb_build_object('claim','Programmes including the Nordic exercise were associated with lower hamstring injury rates across included studies.','limits','Programme-level association does not make a rep injury-proof, establish clinical clearance, or isolate this exercise from co-interventions'))),
    ('programming','https://pubmed.ncbi.nlm.nih.gov/31502142/','The Effect of Nordic Hamstring Exercise Intervention Volume on Eccentric Strength and Muscle Architecture Adaptations: A Systematic Review and Meta-analyses','Sports Medicine',91,jsonb_build_array(jsonb_build_object('claim','Lower-volume interventions did not appear worse than higher-volume interventions for reviewed strength and architecture outcomes.','limits','Thirteen studies, varied TESTEX quality, and substantial heterogeneity'))),
    ('athlete_support','https://pubmed.ncbi.nlm.nih.gov/31502142/','The Effect of Nordic Hamstring Exercise Intervention Volume on Eccentric Strength and Muscle Architecture Adaptations: A Systematic Review and Meta-analyses','Sports Medicine',91,jsonb_build_array(jsonb_build_object('claim','Progressive, tolerable exposure can support adherence; soreness or symptoms must be reported rather than interpreted as proof of benefit.'))),
    ('coach_support','https://pubmed.ncbi.nlm.nih.gov/31644582/','Kinematic and electromyographic analysis of variations in Nordic hamstring exercise','PLOS ONE',84,jsonb_build_array(jsonb_build_object('claim','Side observation of lower-leg slope, knee angle, hip angle, and range is necessary to distinguish variants and execution drift.'))),
    ('accessibility','https://pubmed.ncbi.nlm.nih.gov/31502142/','The Effect of Nordic Hamstring Exercise Intervention Volume on Eccentric Strength and Muscle Architecture Adaptations: A Systematic Review and Meta-analyses','Sports Medicine',91,jsonb_build_array(jsonb_build_object('claim','Lower programme volume may preserve adaptation while improving practical tolerability.','limits','Does not validate any one assistance interface or individual dose'))),
    ('alternates','https://pubmed.ncbi.nlm.nih.gov/31644582/','Kinematic and electromyographic analysis of variations in Nordic hamstring exercise','PLOS ONE',84,jsonb_build_array(jsonb_build_object('claim','0, 20, and 40 degree lower-leg slopes and multiple hip-flexion instructions were tested as distinct execution conditions.'))),
    ('media','https://pubmed.ncbi.nlm.nih.gov/38439779/','The Effect of Variations in Knee and Hip Angles on Electromyographic Activity of the Hamstrings and Related Muscles During the Nordic Hamstring Exercise','International Journal of Sports Physical Therapy',82,jsonb_build_array(jsonb_build_object('claim','An exact isometric demonstration must visibly establish the 30-degree support, knee and hip angles, five-second hold, anchor, entry, and exit.','limits','A title or thumbnail cannot establish exact match')))
  ) e(section_key,source_url,source_title,source_publisher,quality,claims)
  ON CONFLICT(definition_id,reviewed_card_version,section_key,source_url) DO UPDATE SET source_title=EXCLUDED.source_title,source_publisher=EXCLUDED.source_publisher,source_kind=EXCLUDED.source_kind,claims_json=EXCLUDED.claims_json,evidence_quality=EXCLUDED.evidence_quality,review_status='candidate',reviewer_user_id=NULL,reviewed_at=NULL,updated_at=now();

  INSERT INTO coaching.exercise_media_candidate_v1(definition_id,variant_id,reviewed_card_version,url,embed_url,video_id,title,channel_name,language_code,captions_available,embedding_allowed,exact_variant_match,demonstration_quality_score,link_status,review_status,discovery_method,source_query,reviewer_user_id,reviewed_at,next_review_at,notes)
  SELECT canonical_id,NULL,2,'https://www.youtube.com/watch?v='||m.video_id,'https://www.youtube-nocookie.com/embed/'||m.video_id,m.video_id,m.title,m.channel,'en',NULL,TRUE,NULL,NULL,'healthy','candidate','manual_research','legacy Nordic candidates rechecked through YouTube oEmbed on 2026-08-02',NULL,NULL,'2026-11-02T00:00:00.000Z'::TIMESTAMPTZ,
    'YouTube oEmbed returned current title, channel, thumbnail, and iframe metadata on 2026-08-02. This is link and embed metadata only. Full playback, exact variant, anchor, range, assistance, tempo, angle, catch, return, captions, accessibility, safety, cue quality, conflicts, reviewer identity, and approval remain unresolved.'
  FROM (VALUES
    ('_e9vFU9-tkc','How to Set Up, Perform, & Program Nordic Hamstring Curls (Progressions | Regressions | Alternatives)','E3 Rehab'),
    ('6NCN6kOagfY','How to Do a Nordic Hamstring Curl','The Kneesovertoesguy'),
    ('IiofP9cn_nc','Strength Training for Runners: How To Do The Band Assisted Nordic Hamstring Curl','Stronger Runner'),
    ('6_WWA3cQF-w','How to: Nordic Iso Hold','Core Blend Training'),
    ('kLE6k4DYgzQ','Isometric Nordic Hamstring Curl','Elite Performance Institute')
  ) m(video_id,title,channel)
  ON CONFLICT(definition_id,reviewed_card_version,video_id) DO UPDATE SET variant_id=NULL,url=EXCLUDED.url,embed_url=EXCLUDED.embed_url,title=EXCLUDED.title,channel_name=EXCLUDED.channel_name,language_code='en',captions_available=NULL,embedding_allowed=TRUE,exact_variant_match=NULL,demonstration_quality_score=NULL,link_status='healthy',review_status='candidate',discovery_method='manual_research',source_query=EXCLUDED.source_query,reviewer_user_id=NULL,reviewed_at=NULL,next_review_at=EXCLUDED.next_review_at,notes=EXCLUDED.notes,updated_at=now();

  INSERT INTO coaching.exercise_alternate_assessment_v1(definition_id,reviewed_card_version,alternate_name,classification,rationale,distinguishing_dimensions,proposed_card_json,review_status,reviewer_user_id,reviewed_at)
  SELECT canonical_id,2,a.name,a.classification,a.rationale,a.dimensions,NULL,'candidate',NULL,NULL
  FROM (VALUES
    ('Source 4 Generic Nordic Hamstring Curl','reject','The source supplies an injury-proofing claim and 3 x 6 dose but no exact anchor, range, tempo, catch, return, or population contract.',jsonb_build_object('sourceIds',jsonb_build_array(4),'identityQuarantine',TRUE)),
    ('Source 574 Assisted Nordic Hamstring Curl','reject','The source omits the assistance interface, anchor, range, exact tempo, catch, and return strategy needed for selection.',jsonb_build_object('sourceIds',jsonb_build_array(574),'identityQuarantine',TRUE)),
    ('Source 839 Nordic Hamstring Iso Hold','reject','Owned angle and about six seconds do not identify support slope, knee and hip angles, entry, exit, assistance, or dose.',jsonb_build_object('sourceIds',jsonb_build_array(839),'identityQuarantine',TRUE)),
    ('5-Second Eccentric Catch and Reset','same_identity','Exact eccentric-only working specification with planned hand catch and fully unloaded return.',jsonb_build_object('variantKey','eccentric-five-second-catch-reset')),
    ('Band-Assisted Declared-Range Full Cycle','new_variant','Assistance interface and concentric return materially change loading, range, equipment, logistics, and failure handling.',jsonb_build_object('variantKey','band-assisted-declared-range-full-cycle')),
    ('Unassisted Declared-Range Full Cycle','new_variant','Removing assistance creates a distinct high-relative-strength eccentric-concentric contract.',jsonb_build_object('variantKey','unassisted-declared-range-full-cycle')),
    ('30° Incline K30/H0 5-Second Hold','new_variant','Fixed support, knee, hip, and hold angles create an angle-specific isometric contract with distinct setup and measurement.',jsonb_build_object('variantKey','incline-30-k30-h0-five-second-hold-catch-reset')),
    ('Declared Range Target','modifier_annotation','Terminal knee angle or padded target scales exposure inside one fixed contraction, assistance, tempo, catch, and return contract.',jsonb_build_object('modifier','range_target')),
    ('Eccentric Duration','modifier_annotation','Recorded lowering duration scales time under tension within the eccentric catch-reset identity; changing contraction or return does not.',jsonb_build_object('modifier','eccentric_seconds')),
    ('Band Resistance and Length','modifier_annotation','Band model, pre-stretch, anchor height, and assistance estimate must be recorded; the torso interface remains fixed.',jsonb_build_object('modifiers',jsonb_build_array('band_model','band_length','pre_stretch','anchor_height'))),
    ('Fixed Anchor versus Partner Ankle Hold','modifier_annotation','A partner may only provide the declared bilateral ankle anchor; partner assistance at the torso is a different variant.',jsonb_build_object('modifier','ankle_anchor_provider')),
    ('Sets, Repetitions, Holds, and Rest','modifier_annotation','These scale dose only after identity, range, tempo, assistance, catch, and return are fixed.',jsonb_build_object('modifiers',jsonb_build_array('sets','repetitions','hold_seconds','rest_seconds'))),
    ('20° Inclined Lower-Leg Dynamic Nordic','new_variant','A rigid 20-degree lower-leg support changes achievable range and the force-angle solution.',jsonb_build_object('supportSlopeDegrees',20)),
    ('40° Inclined Lower-Leg Dynamic Nordic','new_variant','A rigid 40-degree lower-leg support changes achievable range and requires separate equipment and calibration.',jsonb_build_object('supportSlopeDegrees',40)),
    ('Hip-Flexed Dynamic Nordic','new_variant','A declared non-neutral hip angle changes hamstring length, torque distribution, body-line criterion, and observation.',jsonb_build_object('hipFlexionDegrees','declared_nonzero')),
    ('Other Fixed-Angle Nordic Isometric','new_variant','Every support-slope, knee-angle, hip-angle, hold, entry, and exit combination needs an exact variant contract.',jsonb_build_object('dimensions',jsonb_build_array('support_slope','knee_angle','hip_angle','hold_seconds','entry','exit'))),
    ('Swiss-Ball-Assisted Nordic','new_variant','A rolling contact aid changes assistance direction, hand use, stability, range, and station logistics.',jsonb_build_object('assistanceInterface','swiss_ball')),
    ('Partner Torso-Assisted Nordic','new_variant','Live torso assistance changes force predictability, communication, contact, staffing, and stop commands.',jsonb_build_object('assistanceInterface','partner_torso_support')),
    ('Cable-Assisted Nordic','new_variant','Cable resistance provides a different assistance curve and attachment system from a band.',jsonb_build_object('assistanceInterface','cable')),
    ('Weighted Nordic Hamstring Curl','new_variant','Added external load changes object placement, failure consequence, torque, catch, dose, and recovery.',jsonb_build_object('externalLoad',TRUE)),
    ('Nordic Break-Point Assessment','new_variant','A formal maximum-angle or break-point test changes warm-up, attempts, measurement validity, stopping, and result persistence.',jsonb_build_object('purpose','break_point_assessment')),
    ('Razor Curl','new_definition','Combined hip extension and knee-flexion motion on a glute-ham apparatus is not the hip-neutral kneeling Nordic contract.',jsonb_build_object('targetDefinition','razor_curl')),
    ('Glute-Ham Raise','new_definition','Apparatus support and combined hip-knee movement create a different action, leverage, and equipment identity.',jsonb_build_object('targetDefinition','glute_ham_raise')),
    ('Reverse Nordic Curl','new_definition','Reverse Nordic loading primarily controls knee flexion with the knee extensors rather than knee extension with the knee flexors.',jsonb_build_object('targetDefinition','reverse_nordic_curl')),
    ('Hamstring Slider Curl','new_definition','Supine hip-supported foot sliding changes orientation, anchor, joint motion, loading, and failure consequence.',jsonb_build_object('targetDefinition','hamstring_slider_curl')),
    ('Single-Leg Nordic','new_definition','Unilateral ankle support and knee-flexor action change laterality, rotation control, side dose, and failure consequence.',jsonb_build_object('laterality','unilateral')),
    ('Isokinetic Dynamometer Knee-Flexor Test','new_definition','A machine-constrained dynamometer protocol measures a different action and apparatus context.',jsonb_build_object('purpose','isokinetic_test')),
    ('Unstable or Unrated Ankle Anchor','reject','An unstable, asymmetric, improvised, or unrated anchor conflicts with the exact bilateral safety specification.',jsonb_build_object('anchor','unsafe','selectable',FALSE)),
    ('Band Around Neck, Head, or Face','reject','Band contact at the neck, head, or face is prohibited; use the exact upper-torso interface or another variant.',jsonb_build_object('bandInterface','prohibited','selectable',FALSE)),
    ('Ballistic Drop or Bounce Nordic','reject','Dropping through the break point or bouncing off the hands removes controlled loading and violates the catch-reset contract.',jsonb_build_object('tempo','ballistic','selectable',FALSE)),
    ('Injury-Proofing Nordic','reject','No exercise makes tissue injury-proof; programme-level injury-rate evidence cannot be converted into an individual guarantee.',jsonb_build_object('claim','injury_proofing','selectable',FALSE))
  ) a(name,classification,rationale,dimensions)
  ON CONFLICT(definition_id,reviewed_card_version,alternate_name) DO UPDATE SET classification=EXCLUDED.classification,rationale=EXCLUDED.rationale,distinguishing_dimensions=EXCLUDED.distinguishing_dimensions,proposed_card_json=NULL,review_status='candidate',reviewer_user_id=NULL,reviewed_at=NULL,updated_at=now();

  INSERT INTO coaching.exercise_relationship_v1(from_variant_id,to_variant_id,relationship,similarity_score,dimensions,reason,conditions_json,review_status,created_by,reviewed_by,reviewed_at) VALUES
    (unassisted_variant,band_variant,'regression',88,ARRAY['load','leverage'],'Band assistance reduces body-mass torque but changes equipment, assistance curve, and station safety.','{"revalidate":["assistance","anchor","range","dose","duration","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (band_variant,unassisted_variant,'progression',88,ARRAY['load','leverage'],'Removing assistance increases physical difficulty and failure consequence; it requires separate review and dose reduction.','{"revalidate":["readiness","range","catch","dose","recovery","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (band_variant,eccentric_variant,'lateral_substitution',82,ARRAY['load','complexity'],'Eccentric catch-reset removes the assisted concentric return but increases unassisted lowering demand.','{"revalidate":["contraction","assistance","catch","return","dose","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (eccentric_variant,band_variant,'lateral_substitution',82,ARRAY['load','complexity'],'Band-assisted full cycle adds a concentric return and assistance system; it is not a silent easier version.','{"revalidate":["contraction","assistance","range","return","station","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (eccentric_variant,slider_eccentric_variant,'regression',78,ARRAY['load','leverage'],'Supine bilateral slider eccentric reduces the long kneeling lever and forward-fall consequence while preserving eccentric knee-flexor emphasis.','{"useWhen":["nordic_anchor_or_long_lever_is_not_appropriate"],"revalidate":["identity","equipment","dose","duration","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (band_variant,slider_full_cycle_variant,'regression',76,ARRAY['load','leverage','complexity'],'Bilateral slider full cycle removes the kneeling forward-fall and band-anchor system while retaining eccentric-concentric knee flexion.','{"revalidate":["identity","orientation","equipment","range","dose","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (unassisted_variant,slider_full_cycle_variant,'regression',74,ARRAY['load','leverage','complexity'],'Bilateral slider full cycle substantially reduces relative strength and failure consequence.','{"revalidate":["identity","load","range","dose","duration","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (isometric_variant,slider_short_range_variant,'regression',70,ARRAY['load','leverage','complexity'],'Short-range slider curl removes the exact inclined high-tension isometric position and forward-fall setup.','{"revalidate":["identity","contraction","angle","equipment","dose","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (isometric_variant,eccentric_variant,'lateral_substitution',76,ARRAY['range','complexity'],'Five-second eccentric catch-reset replaces one fixed-angle hold with continuous range loading.','{"revalidate":["contraction","support_slope","range","tempo","catch","dose","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (eccentric_variant,isometric_variant,'lateral_substitution',76,ARRAY['range','complexity'],'K30/H0 isometric work changes support slope, joint-angle target, timing, entry, and measurement.','{"revalidate":["contraction","support_slope","angles","hold","entry","dose","rendering"]}'::JSONB,'review',NULL,NULL,NULL)
  ON CONFLICT(from_variant_id,to_variant_id,relationship) DO UPDATE SET similarity_score=EXCLUDED.similarity_score,dimensions=EXCLUDED.dimensions,reason=EXCLUDED.reason,conditions_json=EXCLUDED.conditions_json,review_status='review',created_by=NULL,reviewed_by=NULL,reviewed_at=NULL,updated_at=now()
  WHERE coaching.exercise_relationship_v1.reviewed_by IS NULL AND coaching.exercise_relationship_v1.review_status<>'approved';

  INSERT INTO coaching.exercise_score_calibration_v1(facility_id,variant_id,dimension,proposed_score,anchor_tier,rationale,status,version,created_by,reviewed_by,review_notes,reviewed_at)
  SELECT 1,v.id,d.dimension,CASE d.dimension WHEN 'technicalComplexity' THEN v.complexity ELSE v.physical END,v.tier,
    CASE d.dimension WHEN 'technicalComplexity' THEN 'Review-only exercise-complexity anchor for exact anchor, support slope, body line, contraction, assistance, range, tempo or hold, catch, return, breathing, and reset.' ELSE 'Review-only physical-difficulty anchor for body mass and segment lengths, joint angle, assistance, range, eccentric duration, concentric requirement, total exposure, recent hamstring work, symptoms, novelty, and recovery.' END||' No athlete proficiency classification is represented. Variant: '||v.variant_key||'.','review',1,NULL,NULL,NULL,NULL
  FROM (VALUES
    (eccentric_variant,'eccentric-five-second-catch-reset',46,72,80),
    (band_variant,'band-assisted-declared-range-full-cycle',58,64,60),
    (unassisted_variant,'unassisted-declared-range-full-cycle',58,88,80),
    (isometric_variant,'incline-30-k30-h0-five-second-hold-catch-reset',62,76,80)
  ) v(id,variant_key,complexity,physical,tier)
  CROSS JOIN (VALUES('technicalComplexity'),('absoluteLoadDemand')) d(dimension)
  ON CONFLICT(facility_id,variant_id,dimension,version) DO UPDATE SET proposed_score=EXCLUDED.proposed_score,anchor_tier=EXCLUDED.anchor_tier,rationale=EXCLUDED.rationale,status='review',created_by=NULL,reviewed_by=NULL,review_notes=NULL,reviewed_at=NULL,updated_at=now();

  UPDATE coaching.exercise SET skill_level=NULL,updated_at=now() WHERE id=ANY(source_ids);
  UPDATE coaching.exercise_safety_profile SET minimum_skill_level=NULL WHERE exercise_id=ANY(source_ids);

  INSERT INTO coaching.exercise_card_test_packet_v1(definition_id,facility_id,card_version,schema_version,audit_version,status,checks_json,blocking_issues_json,human_review_required,checked_at)
  VALUES(canonical_id,1,2,'2.0.0',migration_key,'quarantined',jsonb_build_object(
    'identity',jsonb_build_object('passed',TRUE,'legacySources',3,'activeWorkingSpecifications',4,'sourceDerivedSelectableVariants',0,'identityQuarantinedSources',source_ids,'invalidCalfRaiseCitationRemoved',TRUE),
    'taxonomy',jsonb_build_object('passed',TRUE,'controlledTerms',TRUE,'movementPatterns',jsonb_build_array('brace')),
    'anatomy',jsonb_build_object('passed',TRUE,'musclesTissuesJointsActionsPlanesAndBilateralLaterality',TRUE,'loweringMotionTerminologyGuard',TRUE),
    'difficulty',jsonb_build_object('passed',TRUE,'model','max_exercise_complexity_physical_difficulty','athleteProficiency',NULL,'independentCalibrationRequired',TRUE),
    'loadFatigueRecovery',jsonb_build_object('passed',TRUE,'cumulativeHamstringEccentricAndHighTensionBudget',TRUE,'validFailedAndIncidentExposure',TRUE,'sameSessionSprintRunningKickingHingeSliderNordicAndSportRequired',TRUE),
    'constraints',jsonb_build_object('passed',TRUE,'anchorPaddingCatchBandInclineSpacePopulationAndSupervision',TRUE),
    'delivery',jsonb_build_object('passed',TRUE,'profiles',8,'durationScalingDoseRestStationAndSubstitution',TRUE),
    'instructions',jsonb_build_object('passed',TRUE,'athleteCoachSupport',TRUE,'anchorContractionAssistanceRangeTempoAngleCatchReturnAndStopRules',TRUE),
    'research',jsonb_build_object('passed',TRUE,'sections',16,'registryVersion',research_version,'currentDoseResponseReviewIncluded',TRUE,'smallAcuteSamplesAndLowCertaintyExplicit',TRUE),
    'media',jsonb_build_object('passed',FALSE,'candidateCount',5,'currentOEmbedMetadataHealthy',TRUE,'playbackReviewed',FALSE,'exactMatchReviewed',FALSE,'captionsReviewed',FALSE,'accessibilityReviewed',FALSE,'qualityReviewed',FALSE,'approvalCreated',FALSE),
    'relationships',jsonb_build_object('passed',FALSE,'reviewOnly',10,'approved',0),
    'calibration',jsonb_build_object('passed',FALSE,'reviewOnly',8,'approved',0),
    'alternates',jsonb_build_object('passed',TRUE,'assessments',31,'sourceIdentityQuarantines',3),
    'generationSupport',jsonb_build_object('passed',TRUE,'selectionConstraints',TRUE,'cumulativeFatigueBudgets',TRUE,'duration',TRUE,'equipmentAndStation',TRUE,'substitutionRevalidation',TRUE,'renderingAndPersistence',TRUE),
    'publication',jsonb_build_object('passed',FALSE,'reviewer',NULL,'approver',NULL)),
    jsonb_build_array(
      jsonb_build_object('code','CARD-MEDIA-01','message','A qualified human must watch every candidate in full and verify exact anchor, support slope, hip and knee angles, contraction, assistance, range, tempo or hold, catch, return, captions, accessibility, safety, cue quality, conflicts, reviewer identity, and current playback.'),
      jsonb_build_object('code','CARD-GRAPH-03','message','A qualified coach must approve or reject every progression, regression, and substitution proposal.'),
      jsonb_build_object('code','CARD-CALIBRATION-01','message','An independent qualified reviewer must calibrate exercise complexity and physical difficulty. These scores are not athlete proficiency.'),
      jsonb_build_object('code','CARD-PUBLISH-01','message','A qualified reviewer and separate approver must complete content review before publication. All three legacy sources require authoritative exact specifications before source-derived restoration.')),TRUE,now())
  ON CONFLICT(definition_id) DO UPDATE SET facility_id=EXCLUDED.facility_id,card_version=EXCLUDED.card_version,schema_version=EXCLUDED.schema_version,audit_version=EXCLUDED.audit_version,status='quarantined',checks_json=EXCLUDED.checks_json,blocking_issues_json=EXCLUDED.blocking_issues_json,human_review_required=TRUE,checked_at=now();

  IF (SELECT count(*) FROM coaching.exercise_definition_source_v1 WHERE definition_id=canonical_id AND legacy_exercise_id=ANY(source_ids) AND provenance_json->>'sourceDisposition'='identity_quarantine' AND provenance_json->>'invalidPriorCitationRemoved'='https://pubmed.ncbi.nlm.nih.gov/38156065/')<>3
    OR (SELECT count(*) FROM coaching.exercise_variant_v1 WHERE id=ANY(source_variant_ids) AND definition_id=canonical_id AND status='archived' AND requirements_json->>'representation'='identity_quarantine')<>3
    OR (SELECT count(*) FROM coaching.exercise_variant_v1 WHERE id=ANY(active_variant_ids) AND definition_id=canonical_id AND status='review' AND requirements_json->>'selectable'='true' AND difficulty_json->>'technicalMeaning'='exercise_complexity' AND difficulty_json->>'loadMeaning'='physical_difficulty' AND (difficulty_json->>'baseOverallDifficulty')::INTEGER=GREATEST((difficulty_json->>'technicalComplexity')::INTEGER,(difficulty_json->>'physicalDifficulty')::INTEGER))<>4 THEN
    RAISE EXCEPTION '% found invalid source quarantine or working specifications',migration_key;
  END IF;
  IF (SELECT count(*) FROM coaching.exercise_delivery_profile_v1 WHERE variant_id=ANY(active_variant_ids) AND status='review' AND cardinality(equipment_required)>0 AND coalesce(time_model_json->>'durationFormula','')<>'' AND length(coach_instructions)>=100 AND length(athlete_instructions) BETWEEN 10 AND 240 AND cardinality(stop_rules)>=10)<>8
    OR (SELECT count(DISTINCT section_key) FROM coaching.exercise_section_evidence_v1 WHERE definition_id=canonical_id AND reviewed_card_version=2 AND review_status='candidate' AND reviewer_user_id IS NULL)<>16
    OR (SELECT count(*) FROM coaching.exercise_media_candidate_v1 WHERE definition_id=canonical_id AND reviewed_card_version=2 AND video_id=ANY(current_video_ids) AND link_status='healthy' AND review_status='candidate' AND embedding_allowed AND captions_available IS NULL AND exact_variant_match IS NULL AND demonstration_quality_score IS NULL AND reviewer_user_id IS NULL AND reviewed_at IS NULL)<>5
    OR (SELECT count(*) FROM coaching.exercise_alternate_assessment_v1 WHERE definition_id=canonical_id AND reviewed_card_version=2 AND review_status='candidate' AND reviewer_user_id IS NULL)<>31 THEN
    RAISE EXCEPTION '% found incomplete profiles, evidence, media, or alternates',migration_key;
  END IF;
  IF (SELECT count(*) FROM coaching.exercise_relationship_v1 WHERE from_variant_id=ANY(active_variant_ids) AND review_status='review' AND reviewed_by IS NULL)<>10
    OR (SELECT count(*) FROM coaching.exercise_score_calibration_v1 WHERE variant_id=ANY(active_variant_ids) AND status='review' AND version=1 AND reviewed_by IS NULL)<>8 THEN
    RAISE EXCEPTION '% found incomplete graph or calibration proposals',migration_key;
  END IF;
  IF EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 d CROSS JOIN LATERAL unnest(d.movement_patterns) key WHERE d.id=canonical_id AND NOT EXISTS(SELECT 1 FROM coaching.movement_pattern a WHERE a.key=key))
    OR EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 d CROSS JOIN LATERAL unnest(d.body_regions) key WHERE d.id=canonical_id AND NOT EXISTS(SELECT 1 FROM coaching.body_region a WHERE a.key=key))
    OR EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 d CROSS JOIN LATERAL unnest(d.required_equipment||d.optional_equipment) key WHERE d.id=canonical_id AND NOT EXISTS(SELECT 1 FROM coaching.equipment a WHERE a.key=key))
    OR EXISTS(SELECT 1 FROM coaching.exercise_relationship_v1 r WHERE r.from_variant_id=ANY(active_variant_ids) AND r.relationship IN('progression','regression') AND EXISTS(SELECT 1 FROM unnest(r.dimensions) dimension WHERE dimension<>ALL(ARRAY['load','leverage','range','speed','stability','complexity','impact','decision_demand','fatigue']))) THEN
    RAISE EXCEPTION '% created uncontrolled taxonomy or graph dimensions',migration_key;
  END IF;
  IF EXISTS(SELECT 1 FROM coaching.exercise WHERE id=ANY(source_ids) AND skill_level IS NOT NULL)
    OR EXISTS(SELECT 1 FROM coaching.exercise_safety_profile WHERE exercise_id=ANY(source_ids) AND minimum_skill_level IS NOT NULL)
    OR EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 WHERE id=canonical_id AND (reviewed_by IS NOT NULL OR approved_by IS NOT NULL OR last_reviewed_at IS NOT NULL OR approved_video_url IS NOT NULL OR coalesce(provenance_json->'researchSources','[]'::JSONB)::TEXT LIKE '%38156065%'))
    OR EXISTS(SELECT 1 FROM coaching.exercise_section_evidence_v1 WHERE definition_id=canonical_id AND reviewed_card_version=2 AND source_url LIKE '%38156065%')
    OR EXISTS(SELECT 1 FROM coaching.exercise_media_candidate_v1 WHERE definition_id=canonical_id AND reviewed_card_version=2 AND (review_status IN('approved') OR reviewer_user_id IS NOT NULL OR reviewed_at IS NOT NULL OR captions_available IS NOT NULL OR exact_variant_match IS NOT NULL OR demonstration_quality_score IS NOT NULL))
    OR EXISTS(SELECT 1 FROM coaching.exercise_card_test_packet_v1 WHERE definition_id=canonical_id AND (status<>'quarantined' OR human_review_required<>TRUE OR jsonb_array_length(blocking_issues_json)<>4)) THEN
    RAISE EXCEPTION '% retained invalid evidence or fabricated proficiency, approval, or publication state',migration_key;
  END IF;
END;
$$;
