-- Consolidate the generic Plank Hold and RKC Plank identities into the stable
-- Front Plank family, remove an unrelated prone-CPR citation, quarantine every
-- underspecified source representation, and add exact review-only working
-- specifications. No human approval is inferred or created.

DO $$
DECLARE
  migration_key CONSTANT TEXT := '467_coaching_front_plank_family_audit_hardening';
  research_version CONSTANT TEXT := '2026-08-02.77';
  canonical_id CONSTANT UUID := '4bffab47-a9c6-483e-ac8f-5c73b9641fd3';
  plank_hold_definition CONSTANT UUID := '7dbba793-cb30-44eb-ab9b-1dba269f630a';
  rkc_definition CONSTANT UUID := 'ae27784c-0275-4176-93b1-4c5607a57bd4';
  prior_long_lever_definition CONSTANT UUID := '431ee982-ec46-4dc6-9c93-b3a223f31f54';
  duplicate_definition_ids CONSTANT UUID[] := ARRAY[plank_hold_definition,rkc_definition];
  affected_definition_ids CONSTANT UUID[] := ARRAY[canonical_id,plank_hold_definition,rkc_definition,prior_long_lever_definition];
  source_ids CONSTANT BIGINT[] := ARRAY[5,240,602,827];
  source_variant_ids CONSTANT UUID[] := ARRAY[
    'ac27561a-22da-4c71-a4df-1a0c31593b28'::UUID,
    '0e79bbda-905c-4149-a134-4db059e69c51'::UUID,
    'd42fc210-0dee-4e3c-bda0-15f127bee0fb'::UUID,
    'a48709a9-6b52-4ae9-a317-a23d484565ac'::UUID];
  standard_variant CONSTANT UUID := '2c3acc90-f991-4763-8748-ae014dcef565';
  long_lever_variant CONSTANT UUID := 'eae5176b-38a1-4e63-9c57-75e1ab869e2a';
  rkc_variant CONSTANT UUID := '5f6b4e90-c024-4e8a-8562-a0ef46fe1033';
  active_variant_ids CONSTANT UUID[] := ARRAY[standard_variant,long_lever_variant,rkc_variant];
  dead_bug_variant CONSTANT UUID := 'b31d3fa0-51e0-46e2-bd21-f112af78ae8f';
  bear_plank_variant CONSTANT UUID := '45876982-41cd-4aef-bc8a-8e8692f594c1';
  current_video_ids CONSTANT TEXT[] := ARRAY['0nqvl7ybiYQ','K2UZq6uq_mY','abv03ZRw9bM','lismOShjHnA','tx8wfSu1C4k'];
  protected_count INTEGER;
BEGIN
  IF NOT EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 WHERE id=canonical_id AND slug='front-plank' AND status<>'archived')
    OR (SELECT count(*) FROM coaching.exercise_definition_v1 WHERE id=ANY(duplicate_definition_ids))<>2
    OR NOT EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 WHERE id=prior_long_lever_definition AND status='archived')
    OR (SELECT count(*) FROM coaching.exercise_definition_source_v1 WHERE legacy_exercise_id=ANY(source_ids))<>4
    OR (SELECT count(*) FROM coaching.exercise_variant_v1 WHERE id=ANY(source_variant_ids))<>4
    OR NOT EXISTS(SELECT 1 FROM coaching.exercise_variant_v1 WHERE id=dead_bug_variant AND status<>'archived')
    OR NOT EXISTS(SELECT 1 FROM coaching.exercise_variant_v1 WHERE id=bear_plank_variant AND status<>'archived') THEN
    RAISE EXCEPTION '% prerequisite Front Plank identity state is missing or drifted',migration_key;
  END IF;
  IF EXISTS(SELECT 1 FROM coaching.exercise_variant_v1 WHERE id=ANY(active_variant_ids) AND definition_id<>canonical_id) THEN
    RAISE EXCEPTION '% working variant UUID is already owned by another definition',migration_key;
  END IF;

  SELECT COALESCE(sum(n),0) INTO protected_count FROM (
    SELECT count(*) n FROM coaching.exercise_definition_v1 WHERE id=ANY(affected_definition_ids) AND (reviewed_by IS NOT NULL OR approved_by IS NOT NULL OR last_reviewed_at IS NOT NULL)
    UNION ALL SELECT count(*) FROM coaching.exercise_section_evidence_v1 WHERE definition_id=ANY(affected_definition_ids) AND reviewer_user_id IS NOT NULL
    UNION ALL SELECT count(*) FROM coaching.exercise_media_candidate_v1 WHERE definition_id=ANY(affected_definition_ids) AND (reviewer_user_id IS NOT NULL OR reviewed_at IS NOT NULL OR review_status IN('approved'))
    UNION ALL SELECT count(*) FROM coaching.exercise_alternate_assessment_v1 WHERE definition_id=ANY(affected_definition_ids) AND reviewer_user_id IS NOT NULL
    UNION ALL SELECT count(*) FROM coaching.exercise_delivery_profile_v1 WHERE variant_id=ANY(source_variant_ids||active_variant_ids) AND status='approved'
    UNION ALL SELECT count(*) FROM coaching.exercise_relationship_v1 WHERE (from_variant_id=ANY(source_variant_ids||active_variant_ids) OR to_variant_id=ANY(source_variant_ids||active_variant_ids)) AND (reviewed_by IS NOT NULL OR review_status IN('approved'))
    UNION ALL SELECT count(*) FROM coaching.exercise_score_calibration_v1 WHERE variant_id=ANY(source_variant_ids||active_variant_ids) AND (reviewed_by IS NOT NULL OR status='approved')
  ) protected;
  IF protected_count<>0 THEN RAISE EXCEPTION '% refuses to replace human review',migration_key; END IF;

  UPDATE coaching.exercise_section_evidence_v1 SET review_status='superseded',updated_at=now()
  WHERE definition_id=ANY(affected_definition_ids) AND review_status='candidate' AND reviewer_user_id IS NULL;
  UPDATE coaching.exercise_media_candidate_v1 SET review_status='superseded',updated_at=now()
  WHERE definition_id=ANY(affected_definition_ids) AND review_status='candidate' AND reviewer_user_id IS NULL;
  UPDATE coaching.exercise_alternate_assessment_v1 SET review_status='superseded',updated_at=now()
  WHERE definition_id=ANY(affected_definition_ids) AND review_status='candidate' AND reviewer_user_id IS NULL;
  DELETE FROM coaching.exercise_relationship_v1
  WHERE (from_variant_id=ANY(source_variant_ids||active_variant_ids) OR to_variant_id=ANY(source_variant_ids||active_variant_ids))
    AND reviewed_by IS NULL AND review_status<>'approved';
  DELETE FROM coaching.exercise_score_calibration_v1
  WHERE variant_id=ANY(source_variant_ids||active_variant_ids) AND reviewed_by IS NULL AND status<>'approved';

  UPDATE coaching.exercise_definition_source_v1 SET
    definition_id=canonical_id,
    source_kind=CASE WHEN legacy_exercise_id=827 THEN 'legacy_migration' ELSE 'duplicate_consolidation' END,
    provenance_json=(coalesce(provenance_json,'{}'::JSONB)-'researchSources')||jsonb_build_object(
      'migration',migration_key,'sourceDisposition','identity_quarantine','representedBySelectableSourceVariant',FALSE,
      'ambiguity',CASE legacy_exercise_id
        WHEN 5 THEN 'generic_plank_hold_omits_upper_support_foot_stance_lever_pelvic_intent_entry_exit_and_quality_terminated_dose'
        WHEN 240 THEN 'title_conflates_standard_and_long_lever_plank_while_omitting_exact_support_distance_pelvic_intent_and_dose_contract'
        WHEN 602 THEN 'rkc_source_names_high_tension_intent_but_omits_exact_support_geometry_tension_ramp_entry_exit_and_quality_terminated_dose'
        ELSE 'front_plank_source_is_forearm_based_but_omits_exact_stance_support_geometry_pelvic_intent_entry_exit_and_workout_level_budget' END,
      'invalidPriorCitationRemoved','https://pubmed.ncbi.nlm.nih.gov/32707142/',
      'invalidPriorCitationReason','prone_cardiopulmonary_resuscitation_review_not_front_plank_exercise_evidence',
      'correctedEvidencePmids',jsonb_build_array('25325773','29861239','35370773','32560185','38668579','27630435'),
      'authoritativeSourceRecoveryRequired',TRUE,'humanReviewRequired',TRUE,'approvalsCreated',FALSE)
  WHERE legacy_exercise_id=ANY(source_ids);

  UPDATE coaching.exercise_variant_v1 SET
    definition_id=canonical_id,
    variant_key='identity-quarantine-source-'||(source_ids[array_position(source_variant_ids,id)])::TEXT,
    display_name='Front Plank Identity Quarantine — Source '||(source_ids[array_position(source_variant_ids,id)])::TEXT,
    modifier_keys='{}'::TEXT[],difficulty_json='{}'::JSONB,status='archived',
    requirements_json=jsonb_build_object('selectable',FALSE,'representation','identity_quarantine','sourceLegacyExerciseId',source_ids[array_position(source_variant_ids,id)],'archiveReason','source_omits_or_conflates_required_support_lever_tension_pelvic_entry_exit_or_dose_identity','originalAuthoritativeEvidenceRequired',TRUE,'humanReviewRequired',TRUE),
    load_profile_json=jsonb_build_object('selectable',FALSE),fatigue_profile_json=jsonb_build_object('selectable',FALSE),
    programming_profile_json=jsonb_build_object('selectionStatus','identity_quarantine','selectable',FALSE,'publicationQuarantined',TRUE,'neverRestoreFromNameMediaOrInvalidCitation',TRUE),updated_at=now()
  WHERE id=ANY(source_variant_ids);
  UPDATE coaching.exercise_delivery_profile_v1 SET status='archived',updated_at=now() WHERE variant_id=ANY(source_variant_ids);

  UPDATE coaching.exercise_definition_v1 SET status='archived',approved_video_url=NULL,reviewed_by=NULL,approved_by=NULL,last_reviewed_at=NULL,
    provenance_json=(coalesce(provenance_json,'{}'::JSONB)-'researchSources')||jsonb_build_object('frontPlankAuditHardeningMigration',migration_key,'survivorDefinitionId',canonical_id,'selectable',FALSE,'invalidPriorCitationRemoved','https://pubmed.ncbi.nlm.nih.gov/32707142/','humanReviewRequired',TRUE,'approvalsCreated',FALSE),updated_at=now()
  WHERE id=ANY(duplicate_definition_ids||ARRAY[prior_long_lever_definition]::UUID[]);

  UPDATE coaching.exercise_identity_resolution_v1 SET
    evidence_json=(coalesce(evidence_json,'{}'::JSONB)-'researchSources')||jsonb_build_object(
      'correctionMigration',migration_key,'invalidPriorCitationRemoved','https://pubmed.ncbi.nlm.nih.gov/32707142/',
      'invalidPriorCitationReason','prone_cardiopulmonary_resuscitation_review_not_front_plank_exercise_evidence',
      'correctedResearchSources',jsonb_build_array('https://pubmed.ncbi.nlm.nih.gov/25325773/'),'humanReviewRequired',TRUE,'approvalsCreated',FALSE),
    reviewed_by=NULL,resolved_at=now()
  WHERE survivor_definition_id=canonical_id AND resolved_definition_id=prior_long_lever_definition;

  INSERT INTO coaching.exercise_identity_resolution_v1(facility_id,survivor_definition_id,resolved_definition_id,decision,rationale,evidence_json,resolution_source,reviewed_by,resolved_at) VALUES
    (1,canonical_id,plank_hold_definition,'duplicate_consolidated','Generic Plank Hold and Front Plank both denote a prone bilateral isometric support resisting trunk extension. The generic source does not supply mechanics that justify a separate identity; exact upper support, lever, pelvic intent, tension intent, stance, hold, rest, and dose are variant dimensions.',jsonb_build_object('migration',migration_key,'identityBoundary','generic_plank_hold_consolidated_into_exact_front_plank_family','variantDimensions',jsonb_build_array('upper_support','lever','pelvic_intent','tension_intent','stance','hold','rest','dose'),'humanReviewRequired',TRUE,'approvalsCreated',FALSE,'decisionScope','identity_and_traceability_only_not_media_graph_calibration_content_or_publication_approval'),'deterministic_exact_identity',NULL,now()),
    (1,canonical_id,rkc_definition,'duplicate_consolidated','RKC Plank retains the same prone bilateral forearm-and-toe anti-extension support identity. Deliberately pulling the elbows toward the toes, full-body irradiation, tension ramp, shorter hold, rest, and dose define a high-tension variant rather than a separate exercise definition.',jsonb_build_object('migration',migration_key,'identityBoundary','rkc_high_tension_intent_is_exact_front_plank_variant','variantDimensions',jsonb_build_array('tension_intent','elbow_to_toe_pull','pelvic_intent','hold','rest','dose'),'directRkcResearchEvidenceFound',FALSE,'humanReviewRequired',TRUE,'approvalsCreated',FALSE,'decisionScope','identity_and_traceability_only_not_media_graph_calibration_content_or_publication_approval'),'deterministic_exact_identity',NULL,now())
  ON CONFLICT(survivor_definition_id,resolved_definition_id) DO UPDATE SET decision=EXCLUDED.decision,rationale=EXCLUDED.rationale,evidence_json=EXCLUDED.evidence_json,resolution_source=EXCLUDED.resolution_source,reviewed_by=NULL,resolved_at=now();

  UPDATE coaching.exercise_definition_v1 SET
    canonical_name='Front Plank',display_name='Front Plank',
    aliases=ARRAY['Forearm Plank','Forearm Planks','Front Planks','Hardstyle Plank','Long Lever Front Plank','Long-Lever Front Plank','Plank','Plank Hold','Plank Holds','Prone Bridge','RKC Plank','RKC Planks']::TEXT[],
    description='A prone bilateral isometric support family in which the body is supported by the forearms and toes while the athlete maintains a declared rib-pelvis shape and resists spinal extension. Every selectable variant fixes upper-support geometry, foot stance, lever, pelvic and tension intent, entry, hold, breathing, exit, and quality-terminated dose.',
    family_key='prone_bilateral_forearm_front_support_isometric_anti_extension',schema_version='2.0.0',card_version=2,status='review',
    content_confidence=92,scoring_confidence=66,media_confidence=54,
    movement_patterns=ARRAY['brace']::TEXT[],body_regions=ARRAY['core','spine','shoulder','elbow','pelvis','hip']::TEXT[],
    required_equipment=ARRAY['mat']::TEXT[],optional_equipment=ARRAY['line_tape','bench','bands']::TEXT[],
    anatomy_json=jsonb_build_object(
      'primaryMuscles',jsonb_build_array('rectus_abdominis','external_oblique','internal_oblique','transversus_abdominis'),
      'secondaryMuscles',jsonb_build_array('serratus_anterior','pectoralis_major','anterior_deltoid','triceps_brachii','gluteus_maximus','quadriceps','spinal_stabilizers'),
      'connectiveTissues',jsonb_build_array('shoulder_and_elbow_supporting_tissues','abdominal_aponeuroses','thoracolumbar_fascia','hip_and_knee_supporting_tissues'),
      'joints',jsonb_build_array('glenohumeral_joint','scapulothoracic_articulation','elbow','spine','lumbosacral_complex','pelvis','hip','knee','ankle'),
      'jointActions',jsonb_build_array('spinal_anti_extension','rib_pelvis_isometric_control','scapular_protraction_and_upward_support','isometric_shoulder_flexion_support','isometric_elbow_flexion_position','isometric_hip_and_knee_extension','ankle_forefoot_support'),
      'jointActionPhases',jsonb_build_object('entry',jsonb_build_array('kneeling_forearm_setup','one_leg_at_a_time_to_toe_support'),'hold',jsonb_build_array('no_intended_joint_motion','declared_rib_pelvis_and_tension_intent','continuous_breathing'),'exit',jsonb_build_array('knees_lower_under_control','forearms_unloaded_without_collapse')),
      'planes',jsonb_build_array('sagittal_anti_extension_primary','frontal_and_transverse_anti_motion_control'),
      'laterality',jsonb_build_object('upperSupport','bilateral_forearms','lowerSupport','bilateral_toes','trunkAction','bilateral_symmetric','unilateralOrMovingVersionsRequireSeparateVariantOrDefinition',TRUE),
      'evidenceLimit','Surface EMG and endurance-test studies do not establish muscle force, adaptation, transfer, one universal posture, dose, readiness threshold, safety threshold, or clinical effect.'),
    environment_json=jsonb_build_object('surface','level_dry_stable_non_slip_padded_forearm_contact','clearance',jsonb_build_array('full_body_length','safe_kneeling_entry_and_exit','coach_side_and_front_view','no_cross_traffic'),'supportMarks','Exact elbow and toe marks are recorded for standard and long-lever variants.','equipmentSafety','Any bench, band, suspension device, or unstable surface creates a different unapproved setup unless an exact variant is authored.'),
    population_json=jsonb_build_object('defaultPopulation','participants_with_pain_free_forearm_toe_support_and_tolerance_for_bracing_while_breathing','individualizationRequired',TRUE,'prerequisites',jsonb_build_array('pain_free_forearm_elbow_shoulder_toe_and_floor_contact','can_enter_and_exit_without_collapse','can_maintain_declared_rib_pelvis_shape_while_breathing','can_report_pain_pressure_dizziness_fatigue_and_uncertainty'),'cautions',jsonb_build_array('current_or_recent_wrist_elbow_shoulder_neck_spine_hip_knee_or_ankle_symptoms','uncontrolled_pressure_breathing_neurologic_cardiopulmonary_or_balance_condition','pregnancy_or_postpartum_status_requiring_individualization','recent_high_volume_push_carry_gymnastics_crawl_or_trunk_training','unsafe_floor_space_padding_or_supervision'),'notClinicalClearance',TRUE,'neverInferReadinessFromExerciseDifficulty',TRUE),
    athlete_support_json=jsonb_build_object('whyItMatters','This drill trains repeatable trunk and shoulder support while you breathe; it is not a test of how long you can tolerate a failing position.','primaryCue','Press the forearms down, keep the assigned rib-pelvis shape, squeeze only as assigned, and breathe until the first position change.','before',jsonb_build_array('Confirm standard, long-lever, or RKC variant, elbow and toe marks, pelvic and tension intent, hold, rest, sets, and stop signal.','Check the mat and clear entry and exit space.','Report pain, pressure symptoms, dizziness, or unusual fatigue before starting.'),'during',jsonb_build_array('Keep both forearms and toes in their marks.','Maintain the assigned shape and tension; do not silently switch variants.','Breathe continuously and stop at the first uncorrected sag, pike, shift, shrug, tremor, or breath lock.'),'expectedSensations',jsonb_build_array('abdominal_wall_tension','shoulder_support_effort','glute_and_quadriceps_tension_matching_the_variant'),'unexpectedSensations',jsonb_build_array('sharp_or_increasing_pain','neck_or_low_back_pressure','numbness_or_tingling','dizziness','pelvic_floor_pressure_or_leakage','breath_lock_or_panic'),'painGuidance','Lower the knees, exit under control, and tell the coach immediately. Do not hold through pain or repeat until setup, symptoms, dose, and substitution are reviewed.','selfChecks',jsonb_build_array('exact_elbow_and_toe_marks','assigned_rib_pelvis_shape','even_forearm_and_toe_pressure','continuous_breathing','quality_terminated_hold_and_controlled_exit'),'accessibility',jsonb_build_array('shorter_hold','more_rest','incline_forearm_support_exact_variant','knee_supported_exact_variant','dead_bug_heel_tap','bear_plank_hold'),'mediaAlternatives',jsonb_build_array('written_setup_and_exit','side_view_still_sequence','coach_live_demonstration','tactile_floor_marks_with_consent'),'stopSignal','Say stop, lower both knees, unload the forearms, report what changed, and do not retry automatically.'),
    coach_support_json=jsonb_build_object('observationChecklist',jsonb_build_array('exact_variant_elbow_toe_marks_and_entry','head_ribs_pelvis_hips_knees_and_ankles_relationship','scapular_and_forearm_pressure','pelvic_and_tension_intent','breathing_and_symptoms','hold_time_quality_termination_and_exit'),'faultCorrections',jsonb_build_object('wrong_variant_or_marks','stop_and_rebuild_exact_station','sag_or_rib_flare','shorten_hold_or_use_supported_variant','pike_or_tension_mismatch','reset_declared_pelvic_and_tension_intent','shoulder_collapse','press_forearms_down_or_regress_support','breath_lock_or_symptom','end_set_and_reassess'),'demonstrationPlan',jsonb_build_array('show_kneeling_setup_and_one_leg_at_a_time_entry','show_side_view_standard_long_lever_and_rkc_differences','show_first_position_break_and_controlled_knee_exit','state_hold_rest_total_budget_and_stop_command'),'groupManagement',jsonb_build_array('one_athlete_per_marked_full_body_lane','coach_views_side_then_front_or_rear','stagger_start_times_for_quality_observation','record_failed_and_early_terminated_seconds_as_exposure'),'modificationDecisionTree',jsonb_build_array('pain_pressure_dizziness_or_neurologic_symptom_stop_and_escalate','wrong_or_unknown_variant_quarantine_selection','position_or_breathing_break_shorten_hold_or_increase_support','shoulder_or_forearm_limit_use_non_forearm_substitution','recompute_duration_fatigue_and_rendering_after_every_change'),'doNotUseWhen',jsonb_build_array('pain_or_pressure_symptoms_are_present','safe_entry_exit_or_continuous_breathing_is_not_available','exact_support_and_variant_cannot_be_verified','session_fatigue_prevents_repeatable_position'),'validHold','Exact support, lever, pelvic and tension intent, breathing, symptoms, time, and controlled exit all pass without a stop rule.'),
    support_operations_json=jsonb_build_object('issueCategories',jsonb_build_array('identity_or_variant_mismatch','unsafe_surface_space_or_support','pain_pressure_dizziness_or_neurologic_symptom','position_breathing_or_tension_failure','dose_duration_fatigue_or_recovery_mismatch','media_or_rendering_mismatch'),'supportEscalation',jsonb_build_array('stop_and_make_station_safe','record_exact_variant_marks_elapsed_and_failed_seconds_fault_symptom_and_context','follow_facility_emergency_or_clinical_referral_policy','quarantine_uncertain_card_variant_media_or_result'),'retentionPolicy','Persist the workout item, definition, variant, profile, card and research version, exact support marks and intent, prescribed and completed seconds, failures, symptoms, substitutions, duration, recovery, and rendered instruction versions under facility policy.','changeImpactPolicy','Any support, lever, pelvic or tension intent, stance, surface, hold, rest, fatigue, population, substitution, media, or instruction change invalidates cached selection, duration, logistics, rendering, and approval assumptions.','feedbackLoop',jsonb_build_array('athlete_reports_symptoms_and_perceived_position_loss','coach_records_observed_first_break_and_correction','support_triages_identity_equipment_content_or_product_issue','future_review_uses_deidentified_aggregate_failures_without_auto_approval'),'selectionInputs',jsonb_build_array('definition_variant_profile_card_and_research_version','objective_and_session_phase','support_geometry_lever_stance_pelvic_and_tension_intent','sets_hold_rest_total_isometric_seconds_and_duration','same_session_push_carry_crawl_gymnastics_trunk_and_shoulder_support_load','symptoms_recovery_population_environment_and_supervision'),'persistence',jsonb_build_array('workout_and_item_id','definition_variant_profile_card_and_research_version','elbow_toe_marks_support_lever_stance_and_intent','prescribed_valid_failed_and_early_terminated_seconds','faults_symptoms_rest_duration_recovery_and_substitution','athlete_and_coach_rendering_versions'),'incidentPath',jsonb_build_array('call_stop_and_lower_knees_under_control','secure_station_and_assess_immediate_help_need','record_exact_setup_elapsed_time_fault_symptom_and_context','follow_facility_emergency_or_clinical_referral_policy','quarantine_uncertain_source_card_or_media'),'changeImpact','Re-run selection, budgets, logistics, duration, substitutions, persistence, and both renderers after any identity, dose, symptom, equipment, or context change.','publication',jsonb_build_object('humanMediaGraphCalibrationContentAndSeparateApprovalRequired',TRUE)),
    provenance_json=(coalesce(provenance_json,'{}'::JSONB)-'researchSources')||jsonb_build_object('frontPlankAuditHardeningMigration',migration_key,'researchVersion',research_version,'canonicalAuthoredFromResearch',TRUE,'legacySourcesQuarantined',source_ids,'activeWorkingSpecifications',jsonb_build_array('stable-floor-forearm-toes-standard','stable-floor-long-lever-posterior-tilt','stable-floor-rkc-high-tension'),'consolidatedDefinitionIds',jsonb_build_array(plank_hold_definition,rkc_definition,prior_long_lever_definition),'removedUnrelatedCitation','https://pubmed.ncbi.nlm.nih.gov/32707142/','correctedResearchSources',jsonb_build_array('https://pubmed.ncbi.nlm.nih.gov/25325773/','https://pubmed.ncbi.nlm.nih.gov/29861239/','https://pubmed.ncbi.nlm.nih.gov/35370773/','https://pubmed.ncbi.nlm.nih.gov/32560185/','https://pubmed.ncbi.nlm.nih.gov/38668579/','https://pubmed.ncbi.nlm.nih.gov/27630435/'),'identityDecision','generic_plank_hold_long_lever_and_rkc_are_exact_variants_inside_the_prone_bilateral_forearm_front_support_family','mediaState','five_current_oembed_healthy_candidates_unreviewed','oembedCheckedAt','2026-08-02','exerciseDifficultyModel','exercise_complexity_and_physical_difficulty_only','approvalsCreated',FALSE,'publicationQuarantined',TRUE,'humanReviewRequired',TRUE),
    approved_video_url=NULL,reviewed_by=NULL,approved_by=NULL,last_reviewed_at=NULL,updated_at=now()
  WHERE id=canonical_id;

  INSERT INTO coaching.exercise_variant_v1(id,definition_id,variant_key,display_name,modifier_keys,difficulty_json,requirements_json,status,load_profile_json,fatigue_profile_json,programming_profile_json)
  SELECT v.id,canonical_id,v.variant_key,v.display_name,
    ARRAY['hold_seconds','rest_seconds','sets','foot_width','elbow_toe_marks']::TEXT[],
    jsonb_build_object('technicalComplexity',v.complexity,'absoluteLoadDemand',v.physical,'physicalDifficulty',v.physical,'baseOverallDifficulty',GREATEST(v.complexity,v.physical),'coordinationDemand',v.coordination,'supervisionDemand',v.supervision,'failureConsequence',v.failure,'impact',1,'workCapacityDemand',v.work_capacity,'provisional',TRUE,'difficultyModel','max_exercise_complexity_physical_difficulty','technicalMeaning','exercise_complexity','loadMeaning','physical_difficulty','athleteReadinessStoredHere',FALSE),
    jsonb_build_object('actionIdentity','prone_bilateral_forearm_toe_isometric_anti_extension','upperSupport','bilateral_forearms_on_stable_floor','elbowPosition',v.elbow_position,'forearmPosition','parallel_shoulder_width','lowerSupport','bilateral_toes','footStance','hip_width_recorded_marks','lever',v.lever,'pelvicIntent',v.pelvic_intent,'tensionIntent',v.tension_intent,'entry','kneeling_forearm_setup_then_one_leg_at_a_time_to_toe_support','hold','profile_declared_seconds_with_continuous_breathing','exit','lower_both_knees_under_control_before_unloading_forearms','selectable',TRUE,'identityQuarantine',FALSE,'workingSpecificationRequiresHumanContentReview',TRUE),
    'review',
    jsonb_build_object('gripDemand',1,'externalLoadMethod','bodyweight','externalLoadDescription','Body mass acts through the recorded forearm-to-toe lever; no external load or unstable support is permitted.','spinalLoading',v.spinal_loading,'eccentricStress',4,'landingContactsPerRep',0,'impactClass','none','loadTracking',jsonb_build_array('body_mass_and_segment_lengths','elbow_toe_and_shoulder_marks','lever_and_pelvic_intent','tension_intent','valid_failed_and_early_terminated_seconds','same_session_trunk_and_shoulder_support_work','symptoms_and_recovery'),'effectiveLoadDrivers',jsonb_build_array('body_mass_and_segment_lengths','support_distance','shoulder_angle','pelvic_position','voluntary_tension','hold_duration','set_count','rest','prior_fatigue')),
    jsonb_build_object('localMuscleFatigue',v.local_fatigue,'gripFatigue',1,'technicalFatigueSensitivity',v.tech_fatigue,'neuralOutputDemand',v.neural,'impactAccumulation',1,'recoveryHours',24,'recoveryWindow','12_to_48_hours_context_load_novelty_and_symptom_dependent','primaryFatigueSites',jsonb_build_array('abdominal_wall','serratus_and_shoulder_support','gluteal_and_quadriceps_tension','forearm_contact_tissues'),'earlyFatigueSignals',jsonb_build_array('lumbar_sag_or_rib_flare','hip_pike_or_pelvic_shift','scapular_collapse_or_shrug','head_position_change','tremor_or_pressure_shift','breath_lock','early_knee_exit'),'downstreamConflicts',jsonb_build_array('priority_gymnastics_hand_support_or_crawling','high_volume_push_or_loaded_carry','heavy_trunk_flexion_extension_or_anti_motion_work','symptomatic_shoulder_elbow_spine_hip_or_pressure loading')),
    jsonb_build_object('trainingStimuli',v.stimuli,'stimulusDose',jsonb_build_object('primary','quality_terminated_isometric_seconds','fatigueCeiling','low_to_moderate','countFailedAndEarlyTerminatedSeconds',TRUE),'weeklyExposure','Combine every valid, failed, and early-terminated second with push-up, carry, crawl, gymnastics support, hollow, anti-motion, and other trunk or shoulder-support work; symptoms and novelty change recovery.','prerequisites',jsonb_build_array('pain_free_forearm_toe_support','exact_variant_marks_and_exit_understood','declared_rib_pelvis_shape_with_continuous_breathing','recent_exposure_symptoms_and_recovery_reviewed'),'completionCriteria',jsonb_build_array('exact_support_lever_pelvic_and_tension_intent','position_and_breathing_pass_for_every_second','controlled_knee_exit','dose_fault_symptom_duration_and_recovery_records_complete'),'sequenceRules',jsonb_build_array('place_after_specific_preparation','use_before_fatiguing_push_carry_crawl_or_trunk_work_when_quality_is_priority','avoid_before_priority_gymnastics_support_if_fatiguing','never_extend_holds_to_chase_shaking_or_failure'),'pairingCompatibility',jsonb_build_array('noncompeting_lower_body_mobility_or_low_demand_breathing_task_during_full_rest'),'interferenceRules',jsonb_build_array('do_not_prefatigue_shoulders_or_trunk_before_quality_holds','do_not_convert_position_control_into_unplanned_endurance_testing','recompute_identity_fatigue_duration_logistics_and_rendering_after_substitution'),'uncertaintyPolicy',jsonb_build_object('unknownVariantSupportSymptomsDoseOrRecovery','fail_closed_and_request_coach_review','neverInferMissingSourceMechanics',TRUE,'neverAutoApproveMediaGraphCalibrationOrPublication',TRUE),'cumulativeBudget',jsonb_build_object('frontPlankIsometricSeconds',v.seconds_budget,'highTensionSeconds',v.high_tension_budget,'shoulderSupportSeconds',v.shoulder_budget,'technicalSensitivity',v.tech_fatigue,'sameSessionPushCarryCrawlGymnasticsTrunkAndShoulderSupportRequired',TRUE))
  FROM (VALUES
    (standard_variant,'stable-floor-forearm-toes-standard','Front Plank — Stable Floor, Forearms and Toes',30,36,28,28,22,48,34,44,26,30,160,0,190,jsonb_build_array('anti_extension_position_control','submaximal_bracing_endurance','shoulder_support_with_breathing'),'elbows_vertically_under_shoulders_at_recorded_marks','standard_forearm_to_toe','neutral_rib_pelvis_stack_without_forced_tuck','submaximal_repeatable_tension'),
    (long_lever_variant,'stable-floor-long-lever-posterior-tilt','Front Plank — Stable Floor, Long Lever and Posterior Tilt',44,58,42,38,30,56,46,66,44,42,110,20,150,jsonb_build_array('long_lever_anti_extension_strength','posterior_pelvic_tilt_control','higher_abdominal_activation_intent'),'elbows_at_individually_declared_and_recorded_mark_anterior_to_shoulders','declared_forward_elbow_long_lever','active_posterior_pelvic_tilt_without_hip_pike','strong_repeatable_tension_below_maximal'),
    (rkc_variant,'stable-floor-rkc-high-tension','Front Plank — Stable Floor, RKC High Tension',40,68,40,42,34,52,50,72,58,66,70,70,120,jsonb_build_array('short_duration_high_tension_anti_extension','full_body_isometric_irradiation','elbow_to_toe_pull_without_motion'),'elbows_vertically_under_shoulders_at_recorded_marks','standard_forearm_to_toe','active_posterior_pelvic_tilt_without_hip_pike','ramp_to_declared_high_tension_pull_elbows_toward_toes_without_motion')
  ) v(id,variant_key,display_name,complexity,physical,coordination,supervision,failure,work_capacity,spinal_loading,local_fatigue,tech_fatigue,neural,seconds_budget,high_tension_budget,shoulder_budget,stimuli,elbow_position,lever,pelvic_intent,tension_intent)
  ON CONFLICT(id) DO UPDATE SET definition_id=EXCLUDED.definition_id,variant_key=EXCLUDED.variant_key,display_name=EXCLUDED.display_name,modifier_keys=EXCLUDED.modifier_keys,difficulty_json=EXCLUDED.difficulty_json,requirements_json=EXCLUDED.requirements_json,status='review',load_profile_json=EXCLUDED.load_profile_json,fatigue_profile_json=EXCLUDED.fatigue_profile_json,programming_profile_json=EXCLUDED.programming_profile_json,updated_at=now();

  INSERT INTO coaching.exercise_delivery_profile_v1(variant_id,profile_key,phase_key,role,purpose,phase_suitability,methodology_alignment,objective_relevance_json,dosage_json,quality_gate,stop_rules,coach_instructions,athlete_instructions,expected_adaptation,equipment_required,logistics_json,substitution_ids,status,time_model_json,dose_scaling_json,measurement_json,support_prompts_json)
  SELECT p.variant_id,p.profile_key,p.phase,p.role,p.purpose,p.suitability,90,
    jsonb_build_object('trunkAntiExtensionControl',5,'shoulderSupport',4,'bracingEndurance',p.endurance_relevance,'highTensionStrength',p.tension_relevance,'athleticTransferGuarantee',0),
    jsonb_build_object('doseType','holds','sets',p.sets,'holdsPerSet',1,'holdSeconds',p.hold_seconds,'restBetweenSetsSeconds',p.rest,'qualityTerminated',TRUE,'countValidFailedAndEarlyTerminatedSeconds',TRUE,'totalPlannedSeconds',p.sets*p.hold_seconds,'sameSessionBudgetRequired',TRUE),
    'Every counted second uses the exact forearm and toe marks, lever, stance, rib-pelvis shape, pelvic and tension intent; forearm pressure, shoulder support, breathing, symptoms, and controlled exit pass.',
    ARRAY['sharp_or_increasing_pain_pressure_numbness_tingling_dizziness_or_fear','wrong_variant_elbow_toe_marks_lever_stance_pelvic_or_tension_intent','mat_floor_space_or_support_is_unstable_slippery_or_obstructed','lumbar_sag_rib_flare_or_head_position_changes','hips_pike_rotate_shift_or_drop','scapulae_collapse_or_shoulders_shrug_and_cannot_correct','forearm_or_toe_pressure_becomes_asymmetric_or_support_moves','breath_lock_pressure_symptom_or_panic_bracing_appears','hold_time_total_isometric_duration_or_fatigue_budget_is_exceeded','controlled_knee_exit_is_not_available'],
    p.coach_instructions,p.athlete_instructions,p.adaptation,ARRAY['mat']::TEXT[],
    jsonb_build_object('athletesPerStation',1,'setupSeconds',30,'transitionSeconds',20,'station','one_marked_stable_full_body_floor_lane_per_athlete','equipmentCheck','dry_non_slip_mat_clear_lane_and_visible_elbow_toe_marks','changeRule','coach_rechecks_identity_and_recomputes_load_fatigue_duration_and_rendering','substitutionRevalidation',jsonb_build_array('identity','support','lever','pelvic_intent','tension_intent','dose','fatigue','duration','population','rendering')),
    CASE p.variant_id WHEN standard_variant THEN ARRAY[long_lever_variant,rkc_variant,dead_bug_variant,bear_plank_variant]::UUID[] WHEN long_lever_variant THEN ARRAY[standard_variant,rkc_variant,dead_bug_variant]::UUID[] ELSE ARRAY[standard_variant,long_lever_variant,dead_bug_variant]::UUID[] END,
    'review',jsonb_build_object('setupSeconds',30,'repSeconds',0,'holdSeconds',p.hold_seconds,'resetSeconds',15,'durationIncludesRest',TRUE,'durationFormula','setup + sets * (hold + controlled_exit_and_reset + inter_set_rest) + transition','durationCeilingSeconds',p.ceiling,'recomputeAfterSubstitution',TRUE),
    jsonb_build_object('reduce',jsonb_build_array('shorten_hold','increase_rest','use_standard_variant','use_exact_incline_or_knee_supported_variant_after_review','use_dead_bug_or_bear_plank_substitution'),'increase',jsonb_build_array('add_five_seconds_within_same_exact_contract','add_one_set_within_cumulative_budget','use_long_lever_or_rkc_only_after_review'),'revalidateAfterChange',TRUE),
    jsonb_build_object('record',jsonb_build_array('definition_id','variant_id','profile_key','elbow_toe_marks_lever_stance_pelvic_and_tension_intent','prescribed_valid_failed_and_early_terminated_seconds','first_position_or_breathing_break','symptoms_rest_duration_recent_exposure_and_recovery','substitution'),'validity','all exact identity, equipment, position, breathing, dose, symptom, duration, and recovery gates pass'),
    jsonb_build_object('before','Which exact variant, elbow and toe marks, pelvic and tension intent, hold, sets, rest, total budget, and stop signal are assigned?','during','Do shape, forearm pressure, breathing, symptoms, time, and tension still match the assigned variant?','after','Store every valid, failed, and early-terminated second, first break, symptom, duration, recovery, and substitution.')
  FROM (VALUES
    (standard_variant,'resilience-position-control','resilience','primary','Build repeatable front-support position and breathing without approaching exhaustion.',94,4,1,2,20,45,520,'Verify standard elbow-under-shoulder and toe marks, hip-width stance, neutral rib-pelvis stack, submaximal tension, breathing, recent support load, and the first-break stop rule.','Use the standard marks. Press down, keep ribs and pelvis stacked, breathe for 20 seconds, then lower both knees before the shape changes.','Improved repeatability of standard forearm-plank position, breathing, and controlled exit.'),
    (standard_variant,'capacity-bracing-endurance','capacity','secondary','Accumulate quality-terminated submaximal front-plank time with full rest and total exposure accounting.',88,5,1,3,30,60,820,'Cap every hold at 30 seconds and stop earlier for the first position or breathing change. Count all attempted seconds with same-session push, carry, crawl, gymnastics, and trunk work.','Hold the standard line and breathe for up to 30 seconds. Lower your knees at the first sag, pike, shoulder collapse, breath lock, or symptom.','Improved submaximal isometric bracing endurance without using failed posture as training volume.'),
    (long_lever_variant,'resilience-long-lever-control','resilience','primary','Introduce a recorded forward-elbow lever and posterior pelvic tilt with low total time.',90,3,3,2,15,60,600,'Mark the individually declared forward elbow position and toe line, verify posterior tilt without a hip pike, preserve continuous breathing, and stop at the first loss of geometry.','Use the marked long lever, tuck the pelvis without lifting the hips, breathe for 15 seconds, and lower your knees at the first position change.','Improved control of a longer anti-extension lever and declared posterior pelvic tilt.'),
    (long_lever_variant,'capacity-long-lever-strength','capacity','primary','Use fully rested long-lever holds as higher-demand isometric anti-extension strength work.',90,3,4,3,20,75,900,'Confirm the forward elbow offset and posterior tilt are repeatable before every set. Do not infer a universal offset or dose from the 19-participant EMG comparison.','Press down at the marked long-lever position, keep the posterior tilt and breathe for up to 20 seconds. End the set before the line changes.','Improved higher-demand long-lever anti-extension force expression under one recorded setup.'),
    (rkc_variant,'resilience-high-tension-introduction','resilience','secondary','Introduce brief declared RKC tension without breath locking or unplanned maximal-duration testing.',84,2,4,3,8,60,580,'Use standard marks, rehearse the elbow-to-toe pull without movement, ramp tension rather than jerking, and end immediately if breathing, pressure, shape, or symptoms change. Direct RKC research evidence is absent.','At the standard marks, squeeze and pull elbows toward toes without moving. Breathe for eight seconds, then lower your knees under control.','More repeatable brief high-tension front-plank intent with controlled breathing and exit.'),
    (rkc_variant,'capacity-high-tension-strength','capacity','primary','Express brief high-tension whole-body isometric bracing with complete recovery between holds.',88,2,5,4,10,75,880,'Verify exact standard support, posterior tilt, glute and quadriceps tension, elbow-to-toe pull, breathing, ten-second cap, full rest, and total high-tension budget. Stop rather than reducing position to finish time.','Build high tension at the standard marks, pull elbows toward toes without motion, breathe for up to ten seconds, and lower your knees before tension or shape changes.','Improved brief high-tension anti-extension force expression without converting the hold into an endurance test.')
  ) p(variant_id,profile_key,phase,role,purpose,suitability,endurance_relevance,tension_relevance,sets,hold_seconds,rest,ceiling,coach_instructions,athlete_instructions,adaptation)
  ON CONFLICT(variant_id,profile_key) DO UPDATE SET phase_key=EXCLUDED.phase_key,role=EXCLUDED.role,purpose=EXCLUDED.purpose,phase_suitability=EXCLUDED.phase_suitability,methodology_alignment=EXCLUDED.methodology_alignment,objective_relevance_json=EXCLUDED.objective_relevance_json,dosage_json=EXCLUDED.dosage_json,quality_gate=EXCLUDED.quality_gate,stop_rules=EXCLUDED.stop_rules,coach_instructions=EXCLUDED.coach_instructions,athlete_instructions=EXCLUDED.athlete_instructions,expected_adaptation=EXCLUDED.expected_adaptation,equipment_required=EXCLUDED.equipment_required,logistics_json=EXCLUDED.logistics_json,substitution_ids=EXCLUDED.substitution_ids,status='review',time_model_json=EXCLUDED.time_model_json,dose_scaling_json=EXCLUDED.dose_scaling_json,measurement_json=EXCLUDED.measurement_json,support_prompts_json=EXCLUDED.support_prompts_json,updated_at=now();

  INSERT INTO coaching.exercise_section_evidence_v1(definition_id,reviewed_card_version,section_key,source_url,source_title,source_publisher,source_kind,claims_json,evidence_quality,review_status,reviewer_user_id,reviewed_at)
  SELECT canonical_id,2,e.section_key,e.source_url,e.source_title,e.source_publisher,'peer_reviewed_research',
    e.claims||jsonb_build_array(jsonb_build_object('migration',migration_key,'researchVersion',research_version,'legacySourcesQuarantined',source_ids,'unrelatedProneCprCitationRemoved',TRUE,'limitations','Evidence does not establish universal identity, posture, dose, readiness, safety, transfer, treatment, or publication approval for an individual card.','humanReviewRequired',TRUE,'approvalsCreated',FALSE)),
    e.quality,'candidate',NULL,NULL
  FROM (VALUES
    ('identity','https://pubmed.ncbi.nlm.nih.gov/25325773/','An electromyographic comparison of a modified version of the plank with a long lever and posterior tilt versus the traditional plank exercise','Sports Biomechanics',84,jsonb_build_array(jsonb_build_object('claim','Traditional, long-lever, posterior-tilt, and combined long-lever posterior-tilt conditions were separately executed.','sample','19 participants performing 30-second bouts in randomized order','limits','acute surface EMG comparison'))),
    ('taxonomy','https://pubmed.ncbi.nlm.nih.gov/25325773/','An electromyographic comparison of a modified version of the plank with a long lever and posterior tilt versus the traditional plank exercise','Sports Biomechanics',84,jsonb_build_array(jsonb_build_object('claim','Lever and pelvic intent must be named rather than treating every front plank label as one executable setup.'))),
    ('anatomy','https://pubmed.ncbi.nlm.nih.gov/35370773/','Core Muscle Activation With Foam Rolling and Static Planks','Frontiers in Physiology',76,jsonb_build_array(jsonb_build_object('claim','Lower abdominal, external oblique, and erector-spinae activity was measured during prone and reverse static planks.','sample','9 recreationally trained adults','limits','small acute EMG study; activation is not force or adaptation'))),
    ('biomechanics','https://pubmed.ncbi.nlm.nih.gov/25325773/','An electromyographic comparison of a modified version of the plank with a long lever and posterior tilt versus the traditional plank exercise','Sports Biomechanics',84,jsonb_build_array(jsonb_build_object('claim','The longer lever contributed more than posterior tilt to the tested abdominal activation differences.','limits','does not define one universal elbow offset or load'))),
    ('difficulty','https://pubmed.ncbi.nlm.nih.gov/25325773/','An electromyographic comparison of a modified version of the plank with a long lever and posterior tilt versus the traditional plank exercise','Sports Biomechanics',84,jsonb_build_array(jsonb_build_object('claim','Support distance and pelvic intent inform provisional exercise complexity and physical difficulty.','limits','No validated universal difficulty scale was studied; RKC scores remain review-only'))),
    ('load_fatigue_recovery','https://pubmed.ncbi.nlm.nih.gov/29861239/','The prone bridge test: Performance, validity, and reliability among older and younger adults','Journal of Bodywork and Movement Therapies',84,jsonb_build_array(jsonb_build_object('claim','Prone-bridge time varies widely and repeated technique failure was part of test termination.','sample','60 younger and 60 older adults','limits','exhaustion-test reliability does not prescribe training holds or recovery'))),
    ('constraints','https://pubmed.ncbi.nlm.nih.gov/38668579/','Comparison of the Electromyography Activity during Exercises with Stable and Unstable Surfaces: A Systematic Review and Meta-Analysis','Sports',91,jsonb_build_array(jsonb_build_object('claim','Stable and unstable support conditions can change muscle activation and therefore cannot be substituted silently.','scope','86 studies and 1783 participants across upper-limb, lower-limb, and core exercises','limits','activation changes do not prove superior outcomes or safety'))),
    ('dosage','https://pubmed.ncbi.nlm.nih.gov/29861239/','The prone bridge test: Performance, validity, and reliability among older and younger adults','Journal of Bodywork and Movement Therapies',84,jsonb_build_array(jsonb_build_object('claim','Maximum prone-bridge duration is a test result, not a universal training dose.','limits','Working holds and rest remain provisional and quality-terminated'))),
    ('instructions','https://pubmed.ncbi.nlm.nih.gov/25325773/','An electromyographic comparison of a modified version of the plank with a long lever and posterior tilt versus the traditional plank exercise','Sports Biomechanics',84,jsonb_build_array(jsonb_build_object('claim','Exact instructions must preserve lever and posterior-tilt condition because both were manipulated.'))),
    ('safety_stop_rules','https://pubmed.ncbi.nlm.nih.gov/29861239/','The prone bridge test: Performance, validity, and reliability among older and younger adults','Journal of Bodywork and Movement Therapies',84,jsonb_build_array(jsonb_build_object('claim','Repeated technique failure terminated the research test.','limits','This does not establish medical clearance; production training stops at the first uncorrected break or symptom'))),
    ('programming','https://pubmed.ncbi.nlm.nih.gov/32560185/','Core Muscle Activity During Physical Fitness Exercises: A Systematic Review','International Journal of Environmental Research and Public Health',90,jsonb_build_array(jsonb_build_object('claim','Core-exercise EMG results vary across muscles and methods.','limits','Method inconsistency and missing evidence prevent claims that a plank is universally best or transfers automatically'))),
    ('athlete_support','https://pubmed.ncbi.nlm.nih.gov/29861239/','The prone bridge test: Performance, validity, and reliability among older and younger adults','Journal of Bodywork and Movement Therapies',84,jsonb_build_array(jsonb_build_object('claim','Age group, body size, activity, and individual performance varied, supporting individualized quality-terminated exposure rather than comparison to a universal time.'))),
    ('coach_support','https://pubmed.ncbi.nlm.nih.gov/25325773/','An electromyographic comparison of a modified version of the plank with a long lever and posterior tilt versus the traditional plank exercise','Sports Biomechanics',84,jsonb_build_array(jsonb_build_object('claim','Side-view observation and recorded support position are needed to distinguish traditional, long-lever, and posterior-tilt conditions.'))),
    ('accessibility','https://pubmed.ncbi.nlm.nih.gov/38668579/','Comparison of the Electromyography Activity during Exercises with Stable and Unstable Surfaces: A Systematic Review and Meta-Analysis','Sports',91,jsonb_build_array(jsonb_build_object('claim','Changing support stability changes the exercise condition; accessibility changes require exact re-authoring rather than silent equivalence.'))),
    ('alternates','https://pubmed.ncbi.nlm.nih.gov/27630435/','Effects of isometric hip movements on electromyographic activities of the trunk muscles during plank exercises','Journal of Physical Therapy Science',74,jsonb_build_array(jsonb_build_object('claim','Added hip-adduction and hip-abduction efforts changed oblique activation versus the traditional plank.','sample','19 healthy male participants','limits','acute EMG does not establish outcomes or universal superiority'))),
    ('media','https://pubmed.ncbi.nlm.nih.gov/25325773/','An electromyographic comparison of a modified version of the plank with a long lever and posterior tilt versus the traditional plank exercise','Sports Biomechanics',84,jsonb_build_array(jsonb_build_object('claim','An exact demonstration must visibly establish support marks, lever, pelvic intent, hold, breathing, and exit.','limits','A title, thumbnail, or oEmbed response cannot establish exact match')))
  ) e(section_key,source_url,source_title,source_publisher,quality,claims)
  ON CONFLICT(definition_id,reviewed_card_version,section_key,source_url) DO UPDATE SET source_title=EXCLUDED.source_title,source_publisher=EXCLUDED.source_publisher,source_kind=EXCLUDED.source_kind,claims_json=EXCLUDED.claims_json,evidence_quality=EXCLUDED.evidence_quality,review_status='candidate',reviewer_user_id=NULL,reviewed_at=NULL,updated_at=now();

  INSERT INTO coaching.exercise_media_candidate_v1(definition_id,variant_id,reviewed_card_version,url,embed_url,video_id,title,channel_name,language_code,captions_available,embedding_allowed,exact_variant_match,demonstration_quality_score,link_status,review_status,discovery_method,source_query,reviewer_user_id,reviewed_at,next_review_at,notes)
  SELECT canonical_id,NULL,2,'https://www.youtube.com/watch?v='||m.video_id,'https://www.youtube-nocookie.com/embed/'||m.video_id,m.video_id,m.title,m.channel,'en',NULL,TRUE,NULL,NULL,'healthy','candidate','manual_research','existing Front Plank candidates rechecked through YouTube oEmbed on 2026-08-02',NULL,NULL,'2026-11-02T00:00:00.000Z'::TIMESTAMPTZ,
    'YouTube oEmbed returned current title, channel, thumbnail, and iframe metadata on 2026-08-02. This proves link and embed metadata only. Full playback, exact variant, support, lever, pelvic and tension intent, hold, entry, exit, captions, accessibility, safety, cue quality, conflicts, reviewer identity, and approval remain unresolved.'
  FROM (VALUES
    ('0nqvl7ybiYQ','ACL Rehab Phase 3 - 25. Front plank','Professeur Étienne Cavaignac'),
    ('K2UZq6uq_mY','Front Plank','Purple Patch Fitness'),
    ('abv03ZRw9bM','Front Plank (Anti-Extension)','Movement As Medicine'),
    ('lismOShjHnA','NEVER DO PLANKS LIKE THIS | 10 Most Common Mistakes','FitnessFAQs'),
    ('tx8wfSu1C4k','Exercise Demo: Front Plank','Balance In Motion')
  ) m(video_id,title,channel)
  ON CONFLICT(definition_id,reviewed_card_version,video_id) DO UPDATE SET variant_id=NULL,url=EXCLUDED.url,embed_url=EXCLUDED.embed_url,title=EXCLUDED.title,channel_name=EXCLUDED.channel_name,language_code='en',captions_available=NULL,embedding_allowed=TRUE,exact_variant_match=NULL,demonstration_quality_score=NULL,link_status='healthy',review_status='candidate',discovery_method=EXCLUDED.discovery_method,source_query=EXCLUDED.source_query,reviewer_user_id=NULL,reviewed_at=NULL,next_review_at=EXCLUDED.next_review_at,notes=EXCLUDED.notes,updated_at=now();

  INSERT INTO coaching.exercise_alternate_assessment_v1(definition_id,reviewed_card_version,alternate_name,classification,rationale,distinguishing_dimensions,proposed_card_json,review_status,reviewer_user_id,reviewed_at)
  SELECT canonical_id,2,a.name,a.classification,a.rationale,a.dimensions,NULL,'candidate',NULL,NULL
  FROM (VALUES
    ('Source 5 Generic Plank Hold','reject','The source does not fix forearm versus hand support, stance, lever, pelvic or tension intent, entry, exit, or a quality-terminated dose.',jsonb_build_object('sourceIds',jsonb_build_array(5),'identityQuarantine',TRUE)),
    ('Source 240 Front Plank / Long-Lever Plank','reject','The source title conflates two variants and does not fix forward elbow offset, pelvic intent, exact hold, or return.',jsonb_build_object('sourceIds',jsonb_build_array(240),'identityQuarantine',TRUE)),
    ('Source 602 RKC Plank','reject','The source names elbow-to-toe pull and high tension but omits complete support geometry, tension ramp, entry, exit, and quality-terminated dose.',jsonb_build_object('sourceIds',jsonb_build_array(602),'identityQuarantine',TRUE)),
    ('Source 827 Front Plank','reject','The source identifies a forearm plank but omits exact stance, marks, pelvic intent, entry, exit, and workout-level exposure accounting.',jsonb_build_object('sourceIds',jsonb_build_array(827),'identityQuarantine',TRUE)),
    ('Stable-Floor Standard Forearm Front Plank','same_identity','Matches the working standard elbow-under-shoulder, forearm-and-toe, neutral rib-pelvis, submaximal-tension contract.',jsonb_build_object('variantKey','stable-floor-forearm-toes-standard')),
    ('Stable-Floor Long-Lever Posterior-Tilt Front Plank','same_identity','Matches the working recorded forward-elbow, posterior-tilt, strong-submaximal-tension contract.',jsonb_build_object('variantKey','stable-floor-long-lever-posterior-tilt')),
    ('Stable-Floor RKC High-Tension Front Plank','same_identity','Matches the working standard-support, posterior-tilt, elbow-to-toe pull, high-tension contract; direct RKC research evidence remains absent.',jsonb_build_object('variantKey','stable-floor-rkc-high-tension')),
    ('Hold Duration','modifier_annotation','Hold seconds scale dose only inside an unchanged support, lever, pelvic, tension, breathing, and exit contract.',jsonb_build_object('modifier','hold_seconds')),
    ('Sets and Rest','modifier_annotation','Sets and rest scale exposure and recovery only after the exact variant is fixed.',jsonb_build_object('modifiers',jsonb_build_array('sets','rest_seconds'))),
    ('Declared Foot Width','modifier_annotation','A small recorded stance change can remain a modifier only when bilateral support and all other identity facts remain fixed.',jsonb_build_object('modifier','foot_width')),
    ('Incline Forearm Front Plank','new_variant','Raising the forearms changes body angle, effective bodyweight moment, support, equipment, entry, and station.',jsonb_build_object('upperSupport','stable_bench_or_box')),
    ('Knee-Supported Forearm Front Plank','new_variant','Knee support shortens the lever and changes contact, load distribution, exit, and pressure points.',jsonb_build_object('lowerSupport','bilateral_knees')),
    ('Tall or High Plank Hold','new_variant','Straight-arm hand support changes wrist and elbow position, shoulder loading, lever, and entry/exit.',jsonb_build_object('upperSupport','bilateral_hands')),
    ('Feet-Elevated Forearm Plank','new_variant','Elevating the feet changes body angle, shoulder load, equipment, failure response, and logistics.',jsonb_build_object('lowerSupport','elevated_feet')),
    ('Externally Loaded Front Plank','new_variant','Added load changes placement, spinal and shoulder loading, failure consequence, spotting, dose, and recovery.',jsonb_build_object('externalLoad',TRUE)),
    ('Hip-Adduction Front Plank','new_variant','Deliberate adduction effort changes force intent and observed abdominal activation; interface and load must be exact.',jsonb_build_object('hipIntent','adduction')),
    ('Hip-Abduction Front Plank','new_variant','Deliberate abduction effort changes force intent, equipment, and activation; it is not a silent cue.',jsonb_build_object('hipIntent','abduction')),
    ('Unstable-Surface Forearm Plank','new_variant','Unstable support changes equipment, muscle activation, balance, failure response, and supervision.',jsonb_build_object('surfaceStability','unstable')),
    ('Suspension Front Plank','new_variant','Suspended hands, forearms, or feet change support compliance, attachment safety, sway, and exit.',jsonb_build_object('support','suspension')),
    ('Body Saw','new_definition','Repeated shoulder and body translation changes the static hold into a dynamic anti-extension cycle.',jsonb_build_object('targetDefinition','body_saw')),
    ('Bear Plank Hold','new_definition','Hands-and-feet quadruped support with knees hovering under hips changes orientation, joint angles, lever, and load distribution.',jsonb_build_object('targetDefinition','bear_plank_hold')),
    ('Side Plank','new_definition','Unilateral lateral support and anti-lateral-flexion loading differ in plane, laterality, anatomy, and failure response.',jsonb_build_object('targetDefinition','side_plank')),
    ('Reverse Plank','new_definition','Supine-facing posterior support changes loaded tissues, shoulder position, hip action, and visual orientation.',jsonb_build_object('targetDefinition','reverse_plank')),
    ('Hollow Body Hold','new_definition','Supine unsupported limb-lever anti-extension removes forearm and toe support and changes failure behavior.',jsonb_build_object('targetDefinition','hollow_body_hold')),
    ('Push-Up','new_definition','Elbow flexion-extension repetitions add dynamic horizontal pressing and a different repetition boundary.',jsonb_build_object('targetDefinition','push_up')),
    ('Plank Shoulder Tap','new_definition','Alternating hand lift and contact add unilateral support, anti-rotation, and repeated motion.',jsonb_build_object('targetDefinition','plank_shoulder_tap')),
    ('Prone Bridge Time-to-Exhaustion Test','new_definition','A maximum-duration assessment changes purpose, familiarization, termination, validity, attempts, and result persistence.',jsonb_build_object('purpose','assessment')),
    ('60-Second Plank Milestone','new_definition','A fixed milestone is an achievement or assessment contract, not an exercise difficulty or universal training dose.',jsonb_build_object('purpose','milestone')),
    ('Unrecorded Slippery or Uneven Support','reject','An unstable or unrecorded surface conflicts with the exact stable-floor support contract.',jsonb_build_object('surface','unsafe_or_unknown','selectable',FALSE)),
    ('Breath-Held Grind Plank','reject','Sustained breath locking or pressure symptoms violate the continuous-breathing and stop contract.',jsonb_build_object('breathing','prohibited','selectable',FALSE)),
    ('Pain-Through Hold','reject','Holding through pain, numbness, pressure symptoms, or dizziness violates stop and escalation rules.',jsonb_build_object('symptomPolicy','prohibited','selectable',FALSE)),
    ('Unplanned Burnout or HIIT Plank','reject','Extending a quality-control hold into unbudgeted failure or conditioning changes dose, fatigue, purpose, and recovery.',jsonb_build_object('purpose','unplanned_fatigue','selectable',FALSE))
  ) a(name,classification,rationale,dimensions)
  ON CONFLICT(definition_id,reviewed_card_version,alternate_name) DO UPDATE SET classification=EXCLUDED.classification,rationale=EXCLUDED.rationale,distinguishing_dimensions=EXCLUDED.distinguishing_dimensions,proposed_card_json=NULL,review_status='candidate',reviewer_user_id=NULL,reviewed_at=NULL,updated_at=now();

  INSERT INTO coaching.exercise_relationship_v1(from_variant_id,to_variant_id,relationship,similarity_score,dimensions,reason,conditions_json,review_status,created_by,reviewed_by,reviewed_at) VALUES
    (standard_variant,long_lever_variant,'progression',90,ARRAY['load','leverage','complexity'],'Moving the elbow marks forward and adding posterior tilt increases effective lever demand and observation complexity.','{"revalidate":["support_marks","lever","pelvic_intent","hold","dose","duration","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (long_lever_variant,standard_variant,'regression',90,ARRAY['load','leverage','complexity'],'Returning elbows under shoulders shortens the lever and removes the required posterior-tilt condition.','{"revalidate":["support_marks","pelvic_intent","hold","dose","duration","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (standard_variant,rkc_variant,'progression',84,ARRAY['load','complexity'],'RKC intent adds posterior tilt, deliberate elbow-to-toe pull, whole-body tension, a shorter cap, and longer recovery.','{"revalidate":["tension_intent","pelvic_intent","breathing","hold","recovery","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (rkc_variant,standard_variant,'regression',84,ARRAY['load','complexity'],'Standard submaximal tension removes the RKC irradiation demand while retaining the same forearm-and-toe support identity.','{"revalidate":["tension_intent","pelvic_intent","hold","dose","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (standard_variant,dead_bug_variant,'regression',76,ARRAY['load','leverage','stability'],'Dead Bug Heel Tap removes prone forearm-and-toe support and reduces shoulder-support demand while retaining trunk anti-extension intent.','{"revalidate":["identity","orientation","limb_motion","dose","duration","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (standard_variant,bear_plank_variant,'regression',74,ARRAY['load','leverage','complexity'],'Bear Plank shortens the trunk lever but changes to hand-and-foot quadruped support with flexed knees.','{"revalidate":["identity","support","joint_angles","dose","duration","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (long_lever_variant,rkc_variant,'lateral_substitution',78,ARRAY['load','leverage','complexity'],'RKC uses a standard lever with higher voluntary tension; it does not preserve the long-lever mechanics.','{"revalidate":["lever","pelvic_intent","tension_intent","hold","recovery","rendering"]}'::JSONB,'review',NULL,NULL,NULL),
    (rkc_variant,long_lever_variant,'lateral_substitution',78,ARRAY['load','leverage','complexity'],'Long-lever work changes support geometry and uses strong submaximal rather than declared high-tension intent.','{"revalidate":["lever","support_marks","tension_intent","hold","recovery","rendering"]}'::JSONB,'review',NULL,NULL,NULL)
  ON CONFLICT(from_variant_id,to_variant_id,relationship) DO UPDATE SET similarity_score=EXCLUDED.similarity_score,dimensions=EXCLUDED.dimensions,reason=EXCLUDED.reason,conditions_json=EXCLUDED.conditions_json,review_status='review',created_by=NULL,reviewed_by=NULL,reviewed_at=NULL,updated_at=now()
  WHERE coaching.exercise_relationship_v1.reviewed_by IS NULL AND coaching.exercise_relationship_v1.review_status<>'approved';

  INSERT INTO coaching.exercise_score_calibration_v1(facility_id,variant_id,dimension,proposed_score,anchor_tier,rationale,status,version,created_by,reviewed_by,review_notes,reviewed_at)
  SELECT 1,v.id,d.dimension,CASE d.dimension WHEN 'technicalComplexity' THEN v.complexity ELSE v.physical END,v.tier,
    CASE d.dimension WHEN 'technicalComplexity' THEN 'Review-only exercise-complexity anchor for exact support marks, lever, stance, rib-pelvis and tension intent, breathing, hold, quality termination, and exit.' ELSE 'Review-only physical-difficulty anchor for body mass and segment lengths, lever, shoulder support, voluntary tension, hold duration, total seconds, prior support load, symptoms, and recovery.' END||' No athlete proficiency classification is represented. Variant: '||v.variant_key||'.','review',1,NULL,NULL,NULL,NULL
  FROM (VALUES
    (standard_variant,'stable-floor-forearm-toes-standard',30,36,40),
    (long_lever_variant,'stable-floor-long-lever-posterior-tilt',44,58,60),
    (rkc_variant,'stable-floor-rkc-high-tension',40,68,60)
  ) v(id,variant_key,complexity,physical,tier)
  CROSS JOIN (VALUES('technicalComplexity'),('absoluteLoadDemand')) d(dimension)
  ON CONFLICT(facility_id,variant_id,dimension,version) DO UPDATE SET proposed_score=EXCLUDED.proposed_score,anchor_tier=EXCLUDED.anchor_tier,rationale=EXCLUDED.rationale,status='review',created_by=NULL,reviewed_by=NULL,review_notes=NULL,reviewed_at=NULL,updated_at=now();

  UPDATE coaching.exercise SET skill_level=NULL,updated_at=now() WHERE id=ANY(source_ids);
  UPDATE coaching.exercise_safety_profile SET minimum_skill_level=NULL WHERE exercise_id=ANY(source_ids);

  INSERT INTO coaching.exercise_card_test_packet_v1(definition_id,facility_id,card_version,schema_version,audit_version,status,checks_json,blocking_issues_json,human_review_required,checked_at)
  VALUES(canonical_id,1,2,'2.0.0',migration_key,'quarantined',jsonb_build_object(
    'identity',jsonb_build_object('passed',TRUE,'legacySources',4,'activeWorkingSpecifications',3,'sourceDerivedSelectableVariants',0,'identityQuarantinedSources',source_ids,'duplicateDefinitionsConsolidated',2,'invalidProneCprCitationRemoved',TRUE),
    'taxonomy',jsonb_build_object('passed',TRUE,'controlledTerms',TRUE,'movementPatterns',jsonb_build_array('brace')),
    'anatomy',jsonb_build_object('passed',TRUE,'musclesTissuesJointsActionsPlanesAndBilateralLaterality',TRUE),
    'difficulty',jsonb_build_object('passed',TRUE,'model','max_exercise_complexity_physical_difficulty','athleteProficiency',NULL,'independentCalibrationRequired',TRUE),
    'loadFatigueRecovery',jsonb_build_object('passed',TRUE,'landingContactsPerRep',0,'cumulativeFrontPlankHighTensionAndShoulderSupportSeconds',TRUE,'validFailedAndEarlyTerminatedExposure',TRUE,'sameSessionPushCarryCrawlGymnasticsTrunkAndShoulderSupportRequired',TRUE),
    'constraints',jsonb_build_object('passed',TRUE,'surfaceMarksSpacePopulationEntryExitAndSupervision',TRUE),
    'delivery',jsonb_build_object('passed',TRUE,'profiles',6,'durationScalingDoseRestStationAndSubstitution',TRUE),
    'instructions',jsonb_build_object('passed',TRUE,'athleteCoachSupport',TRUE,'supportLeverIntentBreathingQualityTerminationAndExit',TRUE),
    'research',jsonb_build_object('passed',TRUE,'sections',16,'registryVersion',research_version,'invalidPriorCitationRemoved',TRUE,'acuteEmgTestingAndTransferLimitsExplicit',TRUE,'directRkcEvidenceAbsentExplicit',TRUE),
    'media',jsonb_build_object('passed',FALSE,'candidateCount',5,'currentOEmbedMetadataHealthy',TRUE,'playbackReviewed',FALSE,'exactMatchReviewed',FALSE,'captionsReviewed',FALSE,'accessibilityReviewed',FALSE,'qualityReviewed',FALSE,'approvalCreated',FALSE),
    'relationships',jsonb_build_object('passed',FALSE,'reviewOnly',8,'approved',0),
    'calibration',jsonb_build_object('passed',FALSE,'reviewOnly',6,'approved',0),
    'alternates',jsonb_build_object('passed',TRUE,'assessments',32,'sourceIdentityQuarantines',4),
    'generationSupport',jsonb_build_object('passed',TRUE,'selectionConstraints',TRUE,'cumulativeFatigueBudgets',TRUE,'duration',TRUE,'equipmentAndStation',TRUE,'substitutionRevalidation',TRUE,'renderingAndPersistence',TRUE),
    'publication',jsonb_build_object('passed',FALSE,'reviewer',NULL,'approver',NULL)),
    jsonb_build_array(
      jsonb_build_object('code','CARD-MEDIA-01','message','A qualified human must watch every candidate in full and verify exact support marks, lever, stance, pelvic and tension intent, entry, hold, breathing, quality termination, exit, captions, accessibility, safety, cue quality, conflicts, reviewer identity, and current playback.'),
      jsonb_build_object('code','CARD-GRAPH-03','message','A qualified coach must approve or reject every progression, regression, and substitution proposal.'),
      jsonb_build_object('code','CARD-CALIBRATION-01','message','An independent qualified reviewer must calibrate exercise complexity and physical difficulty. These scores are not athlete proficiency.'),
      jsonb_build_object('code','CARD-PUBLISH-01','message','A qualified reviewer and separate approver must complete content review before publication. All four legacy sources require authoritative exact specifications before source-derived restoration.')),TRUE,now())
  ON CONFLICT(definition_id) DO UPDATE SET facility_id=EXCLUDED.facility_id,card_version=EXCLUDED.card_version,schema_version=EXCLUDED.schema_version,audit_version=EXCLUDED.audit_version,status='quarantined',checks_json=EXCLUDED.checks_json,blocking_issues_json=EXCLUDED.blocking_issues_json,human_review_required=TRUE,checked_at=now();

  IF (SELECT count(*) FROM coaching.exercise_definition_source_v1 WHERE definition_id=canonical_id AND legacy_exercise_id=ANY(source_ids) AND provenance_json->>'sourceDisposition'='identity_quarantine' AND provenance_json->>'invalidPriorCitationRemoved'='https://pubmed.ncbi.nlm.nih.gov/32707142/')<>4
    OR (SELECT count(*) FROM coaching.exercise_variant_v1 WHERE id=ANY(source_variant_ids) AND definition_id=canonical_id AND status='archived' AND requirements_json->>'representation'='identity_quarantine')<>4
    OR (SELECT count(*) FROM coaching.exercise_variant_v1 WHERE id=ANY(active_variant_ids) AND definition_id=canonical_id AND status='review' AND requirements_json->>'selectable'='true' AND difficulty_json->>'technicalMeaning'='exercise_complexity' AND difficulty_json->>'loadMeaning'='physical_difficulty' AND (difficulty_json->>'baseOverallDifficulty')::INTEGER=GREATEST((difficulty_json->>'technicalComplexity')::INTEGER,(difficulty_json->>'physicalDifficulty')::INTEGER) AND (load_profile_json->>'landingContactsPerRep')::INTEGER=0)<>3
    OR (SELECT count(*) FROM coaching.exercise_definition_v1 WHERE id=ANY(duplicate_definition_ids) AND status='archived')<>2 THEN
    RAISE EXCEPTION '% found invalid consolidation, source quarantine, or working specifications',migration_key;
  END IF;
  IF (SELECT count(*) FROM coaching.exercise_delivery_profile_v1 WHERE variant_id=ANY(active_variant_ids) AND status='review' AND cardinality(equipment_required)>0 AND coalesce(time_model_json->>'durationFormula','')<>'' AND length(coach_instructions)>=100 AND length(athlete_instructions) BETWEEN 10 AND 240 AND cardinality(stop_rules)>=10)<>6
    OR (SELECT count(DISTINCT section_key) FROM coaching.exercise_section_evidence_v1 WHERE definition_id=canonical_id AND reviewed_card_version=2 AND review_status='candidate' AND reviewer_user_id IS NULL)<>16
    OR (SELECT count(*) FROM coaching.exercise_media_candidate_v1 WHERE definition_id=canonical_id AND reviewed_card_version=2 AND video_id=ANY(current_video_ids) AND link_status='healthy' AND review_status='candidate' AND embedding_allowed AND captions_available IS NULL AND exact_variant_match IS NULL AND demonstration_quality_score IS NULL AND reviewer_user_id IS NULL AND reviewed_at IS NULL)<>5
    OR (SELECT count(*) FROM coaching.exercise_alternate_assessment_v1 WHERE definition_id=canonical_id AND reviewed_card_version=2 AND review_status='candidate' AND reviewer_user_id IS NULL)<>32 THEN
    RAISE EXCEPTION '% found incomplete profiles, evidence, media, or alternates',migration_key;
  END IF;
  IF (SELECT count(*) FROM coaching.exercise_relationship_v1 WHERE from_variant_id=ANY(active_variant_ids) AND review_status='review' AND reviewed_by IS NULL)<>8
    OR (SELECT count(*) FROM coaching.exercise_score_calibration_v1 WHERE variant_id=ANY(active_variant_ids) AND status='review' AND version=1 AND reviewed_by IS NULL)<>6
    OR (SELECT count(*) FROM coaching.exercise_identity_resolution_v1 WHERE survivor_definition_id=canonical_id AND resolved_definition_id=ANY(duplicate_definition_ids) AND decision='duplicate_consolidated' AND reviewed_by IS NULL)<>2 THEN
    RAISE EXCEPTION '% found incomplete graph, calibration, or identity decisions',migration_key;
  END IF;
  IF EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 d CROSS JOIN LATERAL unnest(d.movement_patterns) key WHERE d.id=canonical_id AND NOT EXISTS(SELECT 1 FROM coaching.movement_pattern a WHERE a.key=key))
    OR EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 d CROSS JOIN LATERAL unnest(d.body_regions) key WHERE d.id=canonical_id AND NOT EXISTS(SELECT 1 FROM coaching.body_region a WHERE a.key=key))
    OR EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 d CROSS JOIN LATERAL unnest(d.required_equipment||d.optional_equipment) key WHERE d.id=canonical_id AND NOT EXISTS(SELECT 1 FROM coaching.equipment a WHERE a.key=key))
    OR EXISTS(SELECT 1 FROM coaching.exercise_relationship_v1 r WHERE r.from_variant_id=ANY(active_variant_ids) AND r.relationship IN('progression','regression') AND EXISTS(SELECT 1 FROM unnest(r.dimensions) dimension WHERE dimension<>ALL(ARRAY['load','leverage','range','speed','stability','complexity','impact','decision_demand','fatigue']))) THEN
    RAISE EXCEPTION '% created uncontrolled taxonomy or graph dimensions',migration_key;
  END IF;
  IF EXISTS(SELECT 1 FROM coaching.exercise WHERE id=ANY(source_ids) AND skill_level IS NOT NULL)
    OR EXISTS(SELECT 1 FROM coaching.exercise_safety_profile WHERE exercise_id=ANY(source_ids) AND minimum_skill_level IS NOT NULL)
    OR EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 WHERE id=ANY(affected_definition_ids) AND coalesce(provenance_json->'researchSources','[]'::JSONB)::TEXT LIKE '%32707142%')
    OR EXISTS(SELECT 1 FROM coaching.exercise_identity_resolution_v1 WHERE (survivor_definition_id=canonical_id OR resolved_definition_id=canonical_id) AND coalesce(evidence_json->'researchSources','[]'::JSONB)::TEXT LIKE '%32707142%')
    OR EXISTS(SELECT 1 FROM coaching.exercise_definition_v1 WHERE id=canonical_id AND (reviewed_by IS NOT NULL OR approved_by IS NOT NULL OR last_reviewed_at IS NOT NULL OR approved_video_url IS NOT NULL))
    OR EXISTS(SELECT 1 FROM coaching.exercise_section_evidence_v1 WHERE definition_id=canonical_id AND reviewed_card_version=2 AND source_url LIKE '%32707142%')
    OR EXISTS(SELECT 1 FROM coaching.exercise_media_candidate_v1 WHERE definition_id=canonical_id AND reviewed_card_version=2 AND (review_status IN('approved') OR reviewer_user_id IS NOT NULL OR reviewed_at IS NOT NULL OR captions_available IS NOT NULL OR exact_variant_match IS NOT NULL OR demonstration_quality_score IS NOT NULL))
    OR EXISTS(SELECT 1 FROM coaching.exercise_card_test_packet_v1 WHERE definition_id=canonical_id AND (status<>'quarantined' OR human_review_required<>TRUE OR jsonb_array_length(blocking_issues_json)<>4)) THEN
    RAISE EXCEPTION '% retained invalid evidence or fabricated proficiency, approval, or publication state',migration_key;
  END IF;
END;
$$;
