-- Include employer reservations without weakening existing scope and duplicate guards.
CREATE OR REPLACE FUNCTION payroll_validate_retirement_remittance_authorization() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE employer_total NUMERIC; employee_total NUMERIC;
BEGIN
 PERFORM facility_id FROM payroll_settings WHERE facility_id=NEW.facility_id FOR UPDATE;
 IF NOT EXISTS(SELECT 1 FROM payroll_run WHERE id=NEW.run_id AND facility_id=NEW.facility_id AND status='FINALIZED')
 OR NOT EXISTS(SELECT 1 FROM payroll_retirement_plan_revision p WHERE p.id=NEW.plan_revision_id AND p.facility_id=NEW.facility_id AND p.plan_id=NEW.plan_id AND NOT EXISTS(SELECT 1 FROM payroll_retirement_plan_revision n WHERE n.facility_id=p.facility_id AND n.plan_id=p.plan_id AND n.tax_year=p.tax_year AND n.revision>p.revision))
 OR NOT EXISTS(SELECT 1 FROM payroll_retirement_destination d WHERE d.id=NEW.destination_id AND d.facility_id=NEW.facility_id AND d.plan_id=NEW.plan_id AND d.plan_revision_id=NEW.plan_revision_id AND d.connection_id=(SELECT id FROM payroll_payment_connection WHERE facility_id=NEW.facility_id ORDER BY id DESC LIMIT 1) AND NOT EXISTS(SELECT 1 FROM payroll_retirement_destination_suspension s WHERE s.destination_id=d.id) AND NOT EXISTS(SELECT 1 FROM payroll_retirement_destination n WHERE n.facility_id=d.facility_id AND n.plan_id=d.plan_id AND n.revision>d.revision))
 OR NOT EXISTS(SELECT 1 FROM payroll_retirement_allocation_format f WHERE f.id=NEW.format_id AND f.facility_id=NEW.facility_id AND f.plan_id=NEW.plan_id AND f.plan_revision_id=NEW.plan_revision_id AND f.format->>'disposition'='VERIFIED' AND NOT EXISTS(SELECT 1 FROM payroll_retirement_allocation_format n WHERE n.facility_id=f.facility_id AND n.plan_id=f.plan_id AND n.revision>f.revision))
 OR NOT EXISTS(SELECT 1 FROM payroll_retirement_timing_review t WHERE t.id=NEW.timing_id AND t.facility_id=NEW.facility_id AND t.plan_id=NEW.plan_id AND t.plan_revision_id=NEW.plan_revision_id AND t.policy->>'disposition'='REVIEWED' AND t.policy->>'effectiveOn'<=(SELECT payment_date::text FROM payroll_run WHERE id=NEW.run_id) AND NOT EXISTS(SELECT 1 FROM payroll_retirement_timing_review n WHERE n.facility_id=t.facility_id AND n.plan_id=t.plan_id AND n.revision>t.revision AND n.policy->>'effectiveOn'<=(SELECT payment_date::text FROM payroll_run WHERE id=NEW.run_id)))
 THEN RAISE EXCEPTION 'Remittance authorization requires current scoped finalized contributions and configuration.'; END IF;
 SELECT SUM((calculation->>'totalCents')::bigint) INTO employee_total FROM payroll_retirement_run_ledger WHERE facility_id=NEW.facility_id AND run_id=NEW.run_id AND plan_id=NEW.plan_id;
 SELECT COALESCE(SUM(matching_cents::numeric+nonelective_cents),0) INTO employer_total FROM payroll_retirement_employer_run_ledger WHERE facility_id=NEW.facility_id AND run_id=NEW.run_id AND plan_id=NEW.plan_id;
 IF NEW.amount_cents IS DISTINCT FROM employee_total+employer_total THEN RAISE EXCEPTION 'Remittance authorization must match exact employee and employer plan contributions.'; END IF;
 IF employer_total>0 THEN
  IF NOT EXISTS(SELECT 1 FROM payroll_retirement_timing_review WHERE id=NEW.timing_id AND policy->'employerFunding'->>'schedule'='WITH_PAYROLL' AND policy->'employerFunding'->>'confirmed'='true')
   OR NOT EXISTS(SELECT 1 FROM payroll_retirement_allocation_format f WHERE f.id=NEW.format_id AND f.format->'columns' @> '[{"field":"employerMatchingCents"},{"field":"employerNonelectiveCents"}]'::jsonb)
   OR NOT EXISTS(SELECT 1 FROM payroll_retirement_receipt_contract c WHERE c.facility_id=NEW.facility_id AND c.plan_id=NEW.plan_id AND c.plan_revision_id=NEW.plan_revision_id AND c.allocation_format_id=NEW.format_id AND c.disposition='REVIEWED' AND c.contract->>'employerContributionsConfirmed'='true' AND NOT EXISTS(SELECT 1 FROM payroll_retirement_receipt_contract n WHERE n.facility_id=c.facility_id AND n.plan_id=c.plan_id AND n.revision>c.revision))
  THEN RAISE EXCEPTION 'Employer remittance requires current reviewed timing, allocation and receipt contracts.'; END IF;
  IF (NEW.basis->>'amountCents'=NEW.amount_cents::text AND jsonb_typeof(NEW.basis->'allocations')='array') IS NOT TRUE THEN RAISE EXCEPTION 'Employer remittance requires exact retained allocation amounts.'; END IF;
  IF jsonb_array_length(NEW.basis->'allocations')<>(SELECT count(*) FROM payroll_retirement_run_ledger WHERE facility_id=NEW.facility_id AND run_id=NEW.run_id AND plan_id=NEW.plan_id AND ((calculation->>'totalCents')::bigint>0 OR EXISTS(SELECT 1 FROM payroll_retirement_employer_run_ledger e WHERE e.facility_id=NEW.facility_id AND e.run_id=NEW.run_id AND e.plan_id=NEW.plan_id AND e.employee_id=payroll_retirement_run_ledger.employee_id AND e.matching_cents+e.nonelective_cents>0)))
   OR EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.basis->'allocations') a WHERE NOT EXISTS(SELECT 1 FROM payroll_retirement_run_ledger l LEFT JOIN payroll_retirement_employer_run_ledger e ON e.facility_id=l.facility_id AND e.run_id=l.run_id AND e.plan_id=l.plan_id AND e.employee_id=l.employee_id WHERE l.facility_id=NEW.facility_id AND l.run_id=NEW.run_id AND l.plan_id=NEW.plan_id AND a->>'ledgerId'=l.id::text AND a->>'employeeId'=l.employee_id::text AND a->>'planId'=l.plan_id AND a->>'ordinaryPretaxCents'=l.calculation->'ordinary'->>'pretax' AND a->>'ordinaryRothCents'=l.calculation->'ordinary'->>'roth' AND a->>'catchUpPretaxCents'=l.calculation->'catchUp'->>'pretax' AND a->>'catchUpRothCents'=l.calculation->'catchUp'->>'roth' AND a->>'totalCents'=((l.calculation->>'totalCents')::bigint+COALESCE(e.matching_cents,0)+COALESCE(e.nonelective_cents,0))::text))
  THEN RAISE EXCEPTION 'Combined participant allocations must match exact payroll categories and totals.'; END IF;
  IF EXISTS(SELECT 1 FROM payroll_retirement_employer_run_ledger e WHERE e.facility_id=NEW.facility_id AND e.run_id=NEW.run_id AND e.plan_id=NEW.plan_id AND (e.matching_cents+e.nonelective_cents>0 OR EXISTS(SELECT 1 FROM payroll_retirement_run_ledger l WHERE l.facility_id=e.facility_id AND l.run_id=e.run_id AND l.plan_id=e.plan_id AND l.employee_id=e.employee_id AND (l.calculation->>'totalCents')::bigint>0)) AND (SELECT count(*) FROM jsonb_array_elements(NEW.basis->'allocations') a WHERE a->>'employeeId'=e.employee_id::text AND a->>'planId'=e.plan_id AND a->>'employerLedgerId'=e.id::text AND a->>'employerMatchingCents'=e.matching_cents::text AND a->>'employerNonelectiveCents'=e.nonelective_cents::text)<>1) THEN RAISE EXCEPTION 'Employer allocation categories must match retained payroll reservations.'; END IF;
 END IF;
 IF EXISTS(SELECT 1 FROM payroll_retirement_remittance_authorization a WHERE a.facility_id=NEW.facility_id AND a.run_id=NEW.run_id AND a.plan_id=NEW.plan_id AND NOT EXISTS(SELECT 1 FROM payroll_retirement_remittance_cancellation c WHERE c.authorization_id=a.id)) THEN RAISE EXCEPTION 'Retirement contributions are already reserved.'; END IF;
 RETURN NEW;
END $$;
