import {readPayrollSnapshot} from './readPayrollSnapshot.js'
import {historicalReportingRange} from './historicalReportingEvidence.js'
import {reconcileIncomeTaxWageRows} from './incomeTaxWageReconciliation.js'
import {reconcileFicaWageRows} from './ficaWageReconciliation.js'
// Reconciliation totals, not W-2 box calculations. Finalized and imported evidence
// remain separate because imported records do not contain every tax component.
const amounts=['regular_pay_cents','overtime_pay_cents','other_taxable_pay_cents','federal_income_tax_cents','state_income_tax_cents','social_security_tax_cents','medicare_tax_cents','additional_medicare_tax_cents','reimbursement_cents','other_deductions_cents','net_pay_cents','futa_tax_cents','md_ui_tax_cents']
const money=value=>{const cents=BigInt(value??0),negative=cents<0n,absolute=negative?-cents:cents;return `${negative?'-':''}${absolute/100n}.${String(absolute%100n).padStart(2,'0')}`}
// Annual preparation combines independently reviewed imports after reading these native bases.
export async function employeeSummaryCsv(db,facility,start,end,options={}) {
 return readPayrollSnapshot(db,client=>employeeSummaryRows(client,facility,start,end,options))
}
async function employeeSummaryRows(db,facility,start,end,{nativeWageBasesOnly=false}={}) {
 const {rows}=await db.query(`WITH paid AS (
  SELECT re.employee_id,COUNT(*) AS run_count,STRING_AGG(r.id::text,', ' ORDER BY r.id) AS run_ids,
  jsonb_agg(jsonb_build_object('id',re.id,'payroll_run_id',r.id,'facility_id',r.facility_id,'status',r.status,'work_state',pe.work_state,'residence_state',pe.residence_state,'pretax_deduction_cents',re.pretax_deduction_cents,'reviewed_income_basis',(SELECT to_jsonb(v) FROM payroll_income_tax_basis_review v WHERE v.facility_id=r.facility_id AND v.run_employee_id=re.id ORDER BY v.id DESC LIMIT 1),'federal_income_tax_cents',re.federal_income_tax_cents,'state_income_tax_cents',re.state_income_tax_cents,'run_id',r.id,'run_kind',r.run_kind,'payment_date',COALESCE(r.payment_date,p.pay_date),'calculation_snapshot',r.calculation_snapshot,'employee_id',re.employee_id,'statement_snapshot',re.statement_snapshot,'regular_pay_cents',re.regular_pay_cents,'overtime_pay_cents',re.overtime_pay_cents,'other_taxable_pay_cents',re.other_taxable_pay_cents,'social_security_tax_cents',re.social_security_tax_cents,'medicare_tax_cents',re.medicare_tax_cents,'additional_medicare_tax_cents',re.additional_medicare_tax_cents)) AS fica_wage_rows,
  COUNT(*) FILTER(WHERE re.net_pay_cents IS NULL OR re.federal_income_tax_cents IS NULL OR re.state_income_tax_cents IS NULL) AS incomplete_count,
  ${amounts.map(column=>`SUM(COALESCE(re.${column},0)) AS ${column}`).join(',')}
  FROM payroll_run r JOIN payroll_pay_period p ON p.id=r.pay_period_id JOIN payroll_run_employee re ON re.payroll_run_id=r.id JOIN payroll_employee pe ON pe.id=re.employee_id AND pe.facility_id=r.facility_id
  WHERE r.facility_id=$1 AND r.status='FINALIZED' AND COALESCE(r.payment_date,p.pay_date) BETWEEN $2::date AND $3::date GROUP BY re.employee_id
 ), imported AS (
  SELECT employee_id,COUNT(*) AS historical_count,SUM(gross_amount_cents) AS historical_gross,SUM(employee_tax_withheld_cents) AS historical_tax,SUM(net_amount_cents) AS historical_net
  FROM payroll_historical_payment WHERE facility_id=$1 AND payment_date BETWEEN $2::date AND $3::date GROUP BY employee_id
 ) SELECT e.id,e.employee_number,e.legal_first_name,e.legal_last_name,e.employment_status,paid.*,imported.historical_count,imported.historical_gross,imported.historical_tax,imported.historical_net
 FROM payroll_employee e LEFT JOIN paid ON paid.employee_id=e.id LEFT JOIN imported ON imported.employee_id=e.id
 WHERE e.facility_id=$1 AND (paid.employee_id IS NOT NULL OR imported.employee_id IS NOT NULL) ORDER BY e.legal_last_name,e.legal_first_name,e.id`,[facility,start,end])
 const wageBases=reconcileFicaWageRows(rows.flatMap(row=>row.fica_wage_rows||[]))
 const incomeBases=reconcileIncomeTaxWageRows(rows.flatMap(row=>row.fica_wage_rows||[]))
 const imported=new Map()
 if(!nativeWageBasesOnly)for(const row of rows)if(Number(row.historical_count)>0)imported.set(String(row.id),await historicalReportingRange(db,facility,row.id,start,end))
 const importIssues=row=>nativeWageBasesOnly||!Number(row.historical_count)?[]:imported.get(String(row.id))?.totals?[]:['Imported wage bases require reconciliation',...(imported.get(String(row.id))?.issues||[])]
 const sourceReady=(row,basis)=>!!basis||!Number(row.run_count)&&!!imported.get(String(row.id))?.totals
 const importedAmount=(row,key)=>BigInt(imported.get(String(row.id))?.totals?.[key]||0)
 const incomeColumns=row=>{const basis=incomeBases.get(String(row.id)),issues=[...(basis?.issues||[]),...importIssues(row)],complete=sourceReady(row,basis)&&!issues.length;return [complete?money((basis?.federal||0n)+importedAmount(row,'federalWagesCents')):'',complete?money((basis?.maryland||0n)+importedAmount(row,'marylandWagesCents')):'',basis?.verified||0,issues.join('; ')||(!complete?'No retained income-tax wage bases':imported.has(String(row.id))?'RECONCILED NATIVE AND IMPORTED INCOME-TAX WAGE BASES':basis?.reviewed?`RECONCILED INCOME-TAX WAGE BASES (${basis.reviewed} reviewed ${basis.reviewed===1?'record':'records'})`:'RECONCILED INCOME-TAX WAGE BASES')]}
 const basisColumns=row=>{const basis=wageBases.get(String(row.id)),issues=[...(basis?.issues||[]),...importIssues(row)],complete=sourceReady(row,basis)&&!issues.length;return [complete?money((basis?.socialSecurity||0n)+importedAmount(row,'socialSecurityReportedWagesCents')):'',complete?money((basis?.medicare||0n)+importedAmount(row,'medicareWagesCents')):'',complete?money((basis?.additionalMedicare||0n)+importedAmount(row,'additionalMedicareWagesCents')):'',basis?.verified||0,issues.join('; ')||(!complete?'No retained finalized wage bases':imported.has(String(row.id))?'RECONCILED NATIVE AND IMPORTED WAGE BASES':'RECONCILED FINALIZED WAGE BASES')]}
 const importedColumns=row=>{const state=imported.get(String(row.id));return [state?.status||'',state?.reviewId||'',state?.sourceFingerprint||'',state?.paymentCount||0,...['federalWithheldCents','marylandWithheldCents','socialSecurityWithheldCents','medicareWithheldCents','additionalMedicareWithheldCents','qualifiedOvertimePremiumCents'].map(key=>state?.totals?money(state.totals[key]):'')]}

 return [
  ['Payment range start','Payment range end','Employee ID','Employee #','Employee','Current employment status','Finalized run count','Finalized run IDs','Regular pay','Overtime pay','Other taxable pay','Federal withholding','Maryland withholding','Employee Social Security','Employee Medicare','Additional Medicare','Reimbursements','Deductions','Net payments','Employer FUTA','Employer Maryland UI','Finalized gross','Employer Social Security','Employer Medicare','Imported payment count','Imported gross','Imported employee tax','Imported net','Review status','Retained Social Security taxable wages','Retained Medicare taxable wages','Retained Additional Medicare taxable wages','Verified wage-basis records','Wage-basis review','Retained federal income-tax wages','Retained Maryland income-tax wages','Verified income-tax wage records','Income-tax wage review','Imported detail status','Imported detail review ID','Imported detail source fingerprint','Verified imported payments','Imported federal withholding','Imported Maryland withholding','Imported Social Security withholding','Imported regular Medicare withholding','Imported Additional Medicare withholding','Imported qualified overtime premium'],
  ...rows.map(row=>[start,end,row.id,row.employee_number,`${row.legal_first_name} ${row.legal_last_name}`,row.employment_status,row.run_count||0,row.run_ids||'',...amounts.map(column=>money(row[column])),money(BigInt(row.regular_pay_cents||0)+BigInt(row.overtime_pay_cents||0)+BigInt(row.other_taxable_pay_cents||0)),money(row.social_security_tax_cents),money(row.medicare_tax_cents),row.historical_count||0,money(row.historical_gross),money(row.historical_tax),money(row.historical_net),Number(row.incomplete_count)>0?'INCOMPLETE FINALIZED TAX RECORDS':!nativeWageBasesOnly&&Number(row.historical_count)>0?(imported.get(String(row.id))?.totals?'REVIEWED IMPORTED TAX DETAIL — NATIVE AND IMPORTED TAX COLUMNS ARE SEPARATE':'IMPORTED TAX DETAIL REQUIRES RECONCILIATION'):'FINALIZED RECORDS ONLY',...basisColumns(row),...incomeColumns(row),...importedColumns(row)]),
 ]
}
