import {decryptDocument} from './onboarding.js'
const fail=(message,status=409)=>Object.assign(new Error(message),{status})
export async function i9EmployerRecords(db,ctx){
 if(!(await db.query('SELECT id FROM payroll_employee WHERE facility_id=$1 AND id=$2',[ctx.facility,ctx.employee])).rowCount)throw fail('Employee not found.',404)
 const signatures=(await db.query(`SELECT s.*,d.filename,d.content_sha256,t.status AS task_status,t.onboarding_cycle AS current_cycle,t.response AS employer_response,e.status AS employee_status,e.response AS employee_response FROM payroll_i9_employer_signature s JOIN payroll_private_document d ON d.id=s.document_id AND d.facility_id=s.facility_id AND d.employee_id=s.employee_id JOIN payroll_onboarding_task t ON t.id=s.task_id JOIN payroll_onboarding_task e ON e.employee_id=s.employee_id AND e.facility_id=s.facility_id AND e.task_key='I9' WHERE s.facility_id=$1 AND s.employee_id=$2 ORDER BY s.id DESC`,[ctx.facility,ctx.employee])).rows
 const tasks=(await db.query("SELECT t.id,t.task_key,t.status,t.due_date::text AS due_on,t.description,t.source_url,t.completion_note,f.kind AS followup_kind FROM payroll_compliance_task t LEFT JOIN payroll_i9_signature_followup f ON f.compliance_task_id=t.id WHERE t.facility_id=$1 AND t.employee_id=$2 AND (t.task_key LIKE 'I9_DOCUMENT_FOLLOWUP:%' OR t.task_key LIKE 'I9_EVERIFY_CASE:%') ORDER BY t.due_date,t.id",[ctx.facility,ctx.employee])).rows
 const files=(await db.query('SELECT id,filename FROM payroll_private_document WHERE facility_id=$1 AND employee_id=$2',[ctx.facility,ctx.employee])).rows
 const supplements=(await db.query('SELECT s.*,d.filename,d.content_sha256 FROM payroll_i9_supplement_signature s JOIN payroll_private_document d ON d.id=s.document_id WHERE s.facility_id=$1 AND s.employee_id=$2 ORDER BY s.id',[ctx.facility,ctx.employee])).rows.map(row=>{
  const evidence=JSON.parse(decryptDocument(row.encrypted_evidence,`i9-supplement-signature:${ctx.facility}:${ctx.employee}:${row.compliance_task_id}:${row.actor_user_id}`).toString())
  if(evidence.documentSha256!==row.content_sha256||String(evidence.sourceSignatureId)!==String(row.signature_id)||String(evidence.reviewId)!==String(row.review_id))throw fail('Retained Supplement B evidence does not match its signature record.')
  return {signatureId:row.id,sourceSignatureId:row.signature_id,complianceTaskId:row.compliance_task_id,signedAt:row.signed_at,signature:evidence.signature,attestation:evidence.attestation,answers:evidence.answers,examination:evidence.examination,timing:evidence.timing,document:{id:row.document_id,filename:row.filename},copies:evidence.copies.map(copy=>({...copy,filename:files.find(file=>String(file.id)===String(copy.documentId))?.filename||'I9-supplement-copy'}))}
 })
 const records=signatures.map(row=>{
  const retained=JSON.parse(decryptDocument(row.encrypted_signature,`i9-employer-signature:${ctx.facility}:${ctx.employee}:${row.task_id}:${row.onboarding_cycle}:${row.actor_user_id}`).toString())
  if(retained.documentSha256!==row.content_sha256||String(retained.reviewId)!==String(row.review_id)||String(retained.submissionId)!==String(row.submission_id))throw fail('The retained employer evidence does not match its signature record.')
  return {supplements:supplements.filter(s=>String(s.sourceSignatureId)===String(row.id)),signatureId:row.id,onboardingCycle:row.onboarding_cycle,signedAt:row.signed_at,current:row.employee_status==='COMPLETE'&&row.task_status==='COMPLETE'&&row.current_cycle===row.onboarding_cycle&&String(row.employer_response?.i9EmployerSignatureId)===String(row.id)&&String(row.employee_response?.i9SubmissionId)===String(row.submission_id),signature:retained.signature,attestation:retained.attestation,examination:retained.examination,timing:retained.timing,context:retained.context,document:{id:row.document_id,filename:row.filename},copies:retained.copies.map(copy=>({...copy,filename:files.find(file=>String(file.id)===String(copy.documentId))?.filename||'I9-retained-copy'})),followups:tasks.filter(task=>task.task_key===`I9_EVERIFY_CASE:${row.id}`||task.task_key.startsWith(`I9_DOCUMENT_FOLLOWUP:${row.id}:`))}
 })
 await db.query("INSERT INTO payroll_audit_log(facility_id,actor_user_id,action,entity_type,entity_id,after_data) VALUES($1,$2,'I9_EMPLOYER_RECORDS_VIEWED','payroll_employee',$3,$4)",[ctx.facility,ctx.admin,String(ctx.employee),{signatureIds:signatures.map(s=>s.id),supplementSignatureIds:supplements.map(s=>s.signatureId)}])
 return {records}
}
