const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))
export function replacementReceiptHtml(receipt,{generatedAt=new Date()}={}){
 const money=(receipt.amountCents/100).toLocaleString('en-US',{style:'currency',currency:'USD'})
 const rows=[...(receipt.employerName?[['Employer',receipt.employerName]]:[]),['Employee',receipt.employeeName],['Amount',money],['Original pay date',receipt.originalPaymentDate],['Replacement date',receipt.paymentDate],['Bank posted',receipt.bankPostedDates.join(', ')],['Current status',receipt.status==='BANK_CONFIRMED'?'Bank evidence confirmed':'Needs review — later payment evidence changed'],['Destination',receipt.account?`${receipt.account.accountType} ending ${receipt.account.accountLast4}`:'Not recorded'],['Receipt',receipt.id],['Retained',new Date(receipt.createdAt).toISOString()],['Downloaded',generatedAt.toISOString()]]
 return render('Replacement payment receipt',rows,'This receipt records bank evidence for previously reported net pay. Refer to the original pay statement for wages and taxes. Status reflects the evidence available when downloaded; Payroll shows later updates.',receipt.sourceKind==='STOPPED_CHECK'?'Direct-deposit replacement of a stopped check':'')
}
function render(title,rows,note,subtitle=''){
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><style>body{font:16px/1.5 system-ui,sans-serif;color:#172033;margin:0;padding:32px}main{max-width:720px;margin:auto}h1{font-size:26px}dl{display:grid;grid-template-columns:160px 1fr;gap:12px 20px}dt{font-weight:700}dd{margin:0;overflow-wrap:anywhere}.note{border-top:1px solid #cbd5e1;padding-top:20px}@media(max-width:480px){body{padding:20px}dl{grid-template-columns:1fr;gap:4px}dd{margin-bottom:12px}}@media print{body{padding:0}main{max-width:none}}</style></head><body><main><h1>${escape(title)}</h1>${subtitle?`<p>${escape(subtitle)}</p>`:''}<dl>${rows.map(([key,value])=>`<dt>${escape(key)}</dt><dd>${escape(value)}</dd>`).join('')}</dl><p class="note">${escape(note)}</p></main></body></html>`
}
export function checkReceiptHtml(receipt,{generatedAt=new Date()}={}){
 const rows=[['Employer',receipt.employerName||'Not recorded'],['Employee',receipt.employeeName],['Amount',(receipt.amountCents/100).toLocaleString('en-US',{style:'currency',currency:'USD'})],...(receipt.originalPaymentDate?[['Original pay date',receipt.originalPaymentDate]]:[]),['Check date',receipt.paymentDate],['Employer recorded handoff',new Date(receipt.deliveredAt).toISOString()],['Employee acknowledgment',receipt.acknowledgedAt?new Date(receipt.acknowledgedAt).toISOString():'Not recorded'],['Current status',receipt.status==='BANK_CONFIRMED'?'Bank clearance confirmed':receipt.status==='OUTSTANDING'?'Awaiting bank clearance':'Check evidence needs review — contact payroll'],['Bank posted',receipt.bankPostedDates.join(', ')||'Not confirmed'],['Last checked',receipt.observedAt?new Date(receipt.observedAt).toISOString():'Not recorded'],['Receipt',receipt.id],['Downloaded',generatedAt.toISOString()]]
 return render('Check delivery receipt',rows,'This receipt records an employer-reported handoff. Employee acknowledgment records receipt only. Refer to the pay statement for wages and taxes. Status reflects the evidence available when downloaded; Payroll shows later updates.',receipt.sourceKind==='REPLACEMENT_CHECK'?'Replacement check':'')
}
export function sendReplacementReceipt(res,receipt,{check=false}={}){
 res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="payroll-${check?'check':'replacement'}-receipt-${receipt.id}.html"`);res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Security-Policy',"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; sandbox")
 return res.send(check?checkReceiptHtml(receipt):replacementReceiptHtml(receipt))
}
