import type { DisciplinePreparationRoutine, PreparationExercise, PreparationStep } from './types'

const timed = (
  exercise: PreparationExercise,
  dose: string,
  clock: readonly [work: number, recovery: number, transition: number],
  delivery: string,
  effort: string,
  stage: PreparationStep['stage'] = 'base',
): PreparationStep => ({
  exercise,
  dose,
  seconds: clock[0] + clock[1] + clock[2],
  workSeconds: clock[0],
  recoverySeconds: clock[1],
  transitionSeconds: clock[2],
  delivery,
  effort,
  stage,
})

const marchRaise: PreparationExercise = {
  id: 'prepare-locomotion-march-to-easy-jog',
  name: 'March → easy jog in place',
  purposes: ['Raise'],
  equipment: ['Cones marking each athlete’s stationary position'],
  whyHere: 'Raises movement demand without using the short lanes as repeated acceleration-and-turn shuttles; gives the coach an early comfort and breathing check.',
  setup: ['Stand in the middle of the assigned lane, with clear arm room and no person ahead or behind.', 'Establish a comfortable marching rhythm before adding any flight phase.'],
  executionSteps: ['March with relaxed opposite arm and leg action.', 'If comfortable, change gradually to a small, easy jog in place for the prescribed interval.', 'Keep the feet close to their landing position and shoulders relaxed; return to marching to finish.'],
  coachCues: ['Start easy and find a rhythm.', 'Quiet feet; normal breathing.', 'Move on your own spot.'],
  athleteCues: ['I can still speak comfortably.', 'Relax my hands.', 'Keep my steps small.'],
  qualityGates: ['Breathing remains conversational.', 'No progressive heaviness, discomfort or loss of rhythm.', 'The athlete remains inside the assigned space.'],
  commonFaults: ['Starting with high knees or hard running.', 'Stomping to chase a cadence.', 'Drifting into another athlete’s space.'],
  scaling: ['March throughout if jogging is not comfortable.', 'Reduce the knee lift and use a slower rhythm; extend general preparation later if needed.'],
  stopSigns: ['Pain, limping or dizziness.', 'Unusual breathlessness or feeling unwell.', 'Loss of balance or unsafe spacing.'],
}

const ankleCalf: PreparationExercise = {
  id: 'prepare-locomotion-ankle-rock-and-heel-raise',
  name: 'Split-stance ankle rock + controlled heel raise',
  purposes: ['Mobilize', 'Activate'],
  equipment: ['None'],
  whyHere: 'Checks a usable ankle range and introduces controlled calf loading before running contacts.',
  setup: ['Use a short split stance with both feet facing forward.', 'Keep the front heel down for the ankle rocks, then bring the feet parallel for heel raises.'],
  executionSteps: ['Move the front knee forward over the middle toes within a comfortable heel-down range; return without bouncing.', 'Complete the assigned rocks and change sides.', 'With feet parallel, rise through both forefeet, pause briefly, and lower the heels slowly.'],
  coachCues: ['Heel stays heavy on the rock.', 'Knee follows the toes.', 'Rise and lower with control.'],
  athleteCues: ['Keep my whole front foot grounded.', 'Use a comfortable range.', 'Lower quietly.'],
  qualityGates: ['Front heel stays down during rocks.', 'Heel raises remain balanced and controlled.', 'Both sides tolerate the selected range.'],
  commonFaults: ['Rolling the foot inward to gain range.', 'Bouncing into a deep ankle position.', 'Rushing the lowering phase or leaning backward.'],
  scaling: ['Shorten the ankle rock and use a smaller two-foot heel raise.', 'Keep both feet on the ground and transfer weight forward and back if raising the heels is not controlled.'],
  stopSigns: ['Ankle, Achilles or foot pain.', 'Repeated loss of balance.', 'New discomfort that increases with each repetition.'],
}

const splitReach: PreparationExercise = {
  id: 'prepare-locomotion-split-stance-lunge-reach',
  name: 'Short split-stance lunge + opposite-arm reach',
  purposes: ['Mobilize', 'Activate'],
  equipment: ['None'],
  whyHere: 'Accesses a controlled front-leg support position and trailing-hip extension while connecting the trunk and opposite arm.',
  setup: ['Take a short, stable split stance inside the lane, feet on separate tracks.', 'Keep the back heel lifted and choose a depth that does not require support.'],
  executionSteps: ['Lower a little by bending both knees while keeping the front foot planted.', 'Reach the arm opposite the front leg upward only as far as the ribs can remain controlled.', 'Press through the front foot to rise, lower the arm, and complete the assigned repetitions before changing sides.'],
  coachCues: ['Two tracks, not a tightrope.', 'Back hip opens; ribs stay organized.', 'Push the floor to stand.'],
  athleteCues: ['Stay balanced.', 'Reach without leaning back.', 'Keep my front foot heavy.'],
  qualityGates: ['Front knee follows the foot without collapsing inward.', 'The athlete controls both the lowering and rise.', 'Reach does not force back extension or discomfort.'],
  commonFaults: ['Feet placed on one narrow line.', 'Arching the lower back to reach higher.', 'Dropping quickly into the bottom or wobbling out of the stance.'],
  scaling: ['Use a shallower split-stance knee bend with hands on hips.', 'Use a standing split-stance weight shift if a lunge is not controlled.'],
  stopSigns: ['Pain in the knee, hip or back.', 'Repeated loss of balance.', 'Inability to keep the front foot securely planted.'],
}

const hingeReach: PreparationExercise = {
  id: 'prepare-locomotion-hip-hinge-reach',
  name: 'Bodyweight hip hinge + forward reach',
  purposes: ['Mobilize', 'Activate'],
  equipment: ['None'],
  whyHere: 'Checks posterior-chain access and trunk control before front-side mechanics and running contacts.',
  setup: ['Stand with feet hip-width and softly bent knees.', 'Keep a clear arm-length space in front within the assigned lane.'],
  executionSteps: ['Send the hips backward as the torso inclines and arms reach forward for balance.', 'Stop at the range where the spine and foot pressure remain controlled.', 'Push through the floor and bring the hips underneath the trunk to stand without leaning back.'],
  coachCues: ['Hips back; shins quiet.', 'Reach long, not low.', 'Stand tall without arching.'],
  athleteCues: ['Keep my feet planted.', 'Fold at my hips.', 'Return smoothly.'],
  qualityGates: ['Motion comes mainly from the hips.', 'Foot pressure remains balanced.', 'Every repetition returns to a stacked standing position.'],
  commonFaults: ['Turning the hinge into a deep squat.', 'Rounding the back to reach farther.', 'Rocking onto the heels or hyperextending at the top.'],
  scaling: ['Use a smaller hinge with hands on the front hip creases.', 'Remove the arm reach if it disrupts balance.'],
  stopSigns: ['Back, hip or hamstring pain.', 'Loss of foot contact or balance.', 'An uncontrolled catch when returning to standing.'],
}

const lateralShift: PreparationExercise = {
  id: 'prepare-locomotion-lateral-weight-shift',
  name: 'Stationary lateral lunge weight shift',
  purposes: ['Mobilize', 'Activate'],
  equipment: ['None'],
  whyHere: 'Adds a small amount of frontal-plane hip preparation without requiring lateral travel or assuming extra lane width.',
  setup: ['Choose a stance slightly wider than the hips that fits comfortably inside the lane.', 'If lane width cannot accommodate that stance, use the narrow-stance scale.'],
  executionSteps: ['Shift the hips toward one foot as that knee bends and the other leg lengthens.', 'Maintain a grounded foot and return through the middle.', 'Alternate sides at a controlled pace without forcing a deep stretch.'],
  coachCues: ['Shift into the hip.', 'Keep both feet grounded.', 'Own the middle before changing sides.'],
  athleteCues: ['Stay inside my lane.', 'Move smoothly.', 'Use only the range I control.'],
  qualityGates: ['The stance fits inside the marked space.', 'Bent knee tracks with the foot.', 'Both directions are comfortable and controlled.'],
  commonFaults: ['Taking a stance that crosses the lane boundary.', 'Knee dropping inward.', 'Bouncing at end range or tipping the torso sideways.'],
  scaling: ['Use a hip-width side-to-side weight shift with only a small knee bend.', 'Reduce the range or keep the hands on the hips.'],
  stopSigns: ['Groin, hip or knee pain.', 'Foot slipping or loss of balance.', 'Insufficient room for the stance.'],
}

const armSwitch: PreparationExercise = {
  id: 'prepare-sprint-split-stance-arm-switch',
  name: 'Split-stance sprint arm switches',
  purposes: ['Activate', 'Integrate'],
  equipment: ['None'],
  whyHere: 'Introduces purposeful reciprocal arm action while the legs remain quiet, so the coach can correct tension and trunk rotation before the short sprint bridge.',
  setup: ['Take a short split stance with a slight whole-body forward inclination.', 'Keep enough space that hands cannot enter a neighboring lane.'],
  executionSteps: ['Set one arm forward and the other back with comfortable elbow bend.', 'Switch the arms smoothly while keeping the pelvis and ribs quiet.', 'Complete the brief burst, relax completely, and repeat with the other foot forward.'],
  coachCues: ['Drive back; return forward.', 'Hands relaxed, shoulders down.', 'Arms move; trunk stays quiet.'],
  athleteCues: ['Loose hands.', 'Move forward and back.', 'Keep my feet still.'],
  qualityGates: ['Arm action stays controlled and generally forward-backward.', 'Neck and hands remain relaxed.', 'The trunk does not twist to create speed.'],
  commonFaults: ['Shrugging and clenching fists.', 'Throwing the arms across the body.', 'Arching or rocking the torso with every switch.'],
  scaling: ['Stand upright with feet parallel and switch slowly.', 'Shorten the arm travel to a comfortable range.'],
  stopSigns: ['Shoulder, neck or back pain.', 'Loss of stance control.', 'Hands entering another athlete’s space.'],
}

const aMarch: PreparationExercise = {
  id: 'prepare-sprint-a-march',
  name: 'A-march with controlled front-side placement',
  purposes: ['Activate', 'Integrate'],
  equipment: ['Cones at 0 m and 5 m'],
  whyHere: 'Connects single-leg support, opposite-arm action and a deliberate foot placement beneath the body before quicker sprint contacts.',
  setup: ['Begin standing at the lane start; travel only to the 5 m cone if the dose includes travel.', 'Keep the whole lane reserved for the athlete until the walking return is complete.'],
  executionSteps: ['Lift one thigh to a comfortable height while the opposite arm moves forward.', 'Place that foot down beneath the body and transfer onto it without reaching forward.', 'Alternate smoothly. When traveling, stop at the 5 m cone and walk back only after coming fully under control. For the in-place dose, complete the prescribed steps on the spot and finish balanced with both feet down; no walking return is required.'],
  coachCues: ['Tall over the stance leg.', 'Place the foot underneath.', 'Opposite arm and leg work together.'],
  athleteCues: ['Lift, place, switch.', 'Keep my ribs quiet.', 'Walk the reset.'],
  qualityGates: ['Foot placement remains beneath the body.', 'The stance leg and trunk remain controlled.', 'No forced knee height or backward lean.'],
  commonFaults: ['Reaching the foot far ahead.', 'Leaning backward to lift the knee.', 'Holding the breath or turning the drill into a race.'],
  scaling: ['March in place with lower knee lift.', 'Pause briefly with both feet down between steps if balance needs support.'],
  stopSigns: ['Hip or foot pain.', 'Repeated balance loss.', 'Inability to stop and reset within the lane.'],
}

const lowPogo: PreparationExercise = {
  id: 'prepare-sprint-low-pogo',
  name: 'Low two-foot pogo contacts',
  purposes: ['Activate', 'Integrate'],
  equipment: ['None'],
  whyHere: 'Adds a small, counted exposure to quick elastic contacts after controlled ankle and single-leg work.',
  setup: ['Stand hip-width on a clear, level spot in the assigned lane.', 'Keep the bounce very low and count landings rather than duration.'],
  executionSteps: ['Begin with soft knees and a tall, relaxed trunk.', 'Make small two-foot rebounds with feet landing near their starting positions.', 'After the prescribed contacts, absorb the last landing and stop completely.'],
  coachCues: ['Small and quiet.', 'Bounce on your spot.', 'Count contacts; stop at the dose.'],
  athleteCues: ['Stay low.', 'Land where I started.', 'Finish balanced.'],
  qualityGates: ['Contact rhythm stays light and repeatable.', 'No progressive jump height or forward drift.', 'The athlete controls the final stop.'],
  commonFaults: ['Turning the drill into high jumps.', 'Landing with stiff locked knees.', 'Adding contacts to occupy spare time.'],
  scaling: ['Use controlled two-foot heel raises instead of leaving the floor.', 'Reduce to five low contacts when contact quality is uncertain.'],
  stopSigns: ['Achilles, foot or knee pain.', 'Heavy uncontrolled landings.', 'Loss of balance or sliding.'],
}

const dribble: PreparationExercise = {
  id: 'prepare-sprint-low-dribble',
  name: 'Low ankle dribble in place',
  purposes: ['Integrate'],
  equipment: ['None'],
  whyHere: 'Introduces a brief alternating running-contact rhythm with low foot clearance before the short acceleration rehearsal.',
  setup: ['Stand tall on a clear spot in the lane with relaxed arms.', 'Use small foot cycles beneath the body; no travel is needed.'],
  executionSteps: ['Alternate a small lift and placement of the feet underneath the hips.', 'Keep the rhythm quick enough to flow but low enough that the trunk remains quiet.', 'End the short burst by marching, then stand and recover.'],
  coachCues: ['Small circles underneath.', 'Quiet contacts; loose shoulders.', 'Smooth rhythm before faster rhythm.'],
  athleteCues: ['Stay on my spot.', 'Keep the lift small.', 'Relax after the burst.'],
  qualityGates: ['Contacts stay underneath and at a consistent low height.', 'Trunk and head do not bob excessively.', 'The athlete can return to marching without stumbling.'],
  commonFaults: ['Driving into high knees.', 'Pawing far forward or backward.', 'Maintaining the drill after rhythm becomes heavy.'],
  scaling: ['Use a brisk low march with no flight phase.', 'Use one shorter burst, then observe rather than adding repetitions.'],
  stopSigns: ['Pain or asymmetric contact discomfort.', 'Repeated tripping.', 'Contacts becoming uncontrolled despite slowing.'],
  versionNote: 'This is a low-clearance rhythm drill, not a claim that athletes should impose a particular foot strike during normal running.',
}

const startRehearsal: PreparationExercise = {
  id: 'prepare-sprint-two-step-start-rehearsal',
  name: 'Split-start two-step rehearsal + walk to stop',
  purposes: ['Integrate', 'Potentiate Bridge'],
  equipment: ['Cones marking 0 m, 2 m, 3 m and 8 m within the 10 m lane'],
  whyHere: 'Rehearses the start stance, first two push steps and the stopping plan before any increase in intent.',
  setup: ['Set a short split stance at 0 m without blocks or a wall.', 'Reserve 0–2 m for the two steps; walk afterward and stop before 8 m, leaving the final 2 m unused.', 'Verify the athlete can complete the slow version in the available distance before the progression.'],
  executionSteps: ['Incline slightly from the ankles with ribs and pelvis organized.', 'Take two deliberate push steps at an easy rehearsal speed, staying within the first 2 m.', 'Transition to walking, stop well before 8 m, then turn from a standstill and walk back inside the same lane.', 'Switch the lead leg if the dose includes a second repetition.'],
  coachCues: ['Set, push, push.', 'Two steps, then walk.', 'Stop first; turn second.'],
  athleteCues: ['Use a small lean.', 'Keep the first steps controlled.', 'Own my stopping space.'],
  qualityGates: ['Both push steps fit within the marked segment.', 'The athlete transitions smoothly to walking and stops before 8 m.', 'No reaching, stumbling or rushed turn.'],
  commonFaults: ['Falling steeply forward from the start.', 'Taking long bounding steps.', 'Continuing to accelerate into the stopping area.'],
  scaling: ['Rehearse two slow marching push steps from a more upright stance.', 'Use an in-place split-stance weight transfer if the athlete cannot control the travel version.'],
  stopSigns: ['Pain, slipping or loss of balance.', 'Inability to finish the stop before 8 m.', 'A person or object entering the lane.'],
}

const controlledBuild: PreparationExercise = {
  id: 'prepare-sprint-short-build-and-brake',
  name: 'Controlled 2–3 m build + gradual brake',
  purposes: ['Potentiate Bridge'],
  equipment: ['Cones at 0 m, 2 m, 3 m and 8 m within each 10 m lane'],
  whyHere: 'Progresses the rehearsed first-step task by a small amount while retaining enough of the 10 m lane for a gradual, planned stop.',
  setup: ['Mark the end of the build at 3 m and the complete-stop limit at 8 m; keep 8–10 m unused.', 'Begin with a 2 m build and use 3 m only after the athlete demonstrates comfortable braking.', 'If this layout is not sufficient for the athlete, remain with the slower rehearsal.'],
  executionSteps: ['Start from the rehearsed split stance and take controlled, purposeful first steps.', 'End the build by the 2 m or 3 m marker; progressively shorten and soften the following steps.', 'Come to a complete stop before 8 m without planting for a sharp cut.', 'Turn only after stopping and walk back in the same lane; recover fully before another repetition.', 'If the second repetition is prescribed and the first was controlled, use slightly more purposeful intent without pursuing top speed.'],
  coachCues: ['Build ends at the cone.', 'Leave room to slow smoothly.', 'More purposeful only if the stop stays easy.'],
  athleteCues: ['Keep something in reserve.', 'Shorten my steps to slow.', 'Stop, turn, walk.'],
  qualityGates: ['The complete acceleration and braking task fits inside 0–8 m.', 'The athlete finishes upright and balanced with no hard plant.', 'Breathing and coordination settle before any repeat.'],
  commonFaults: ['Treating the lane as a 10 m sprint plus an unmarked run-out.', 'Chasing maximum effort on the second repetition.', 'Braking abruptly or turning while still moving fast.'],
  scaling: ['Keep the build to 2 m at a slower effort and begin slowing earlier.', 'Repeat the two-step marching rehearsal if braking control is uncertain.'],
  stopSigns: ['The athlete approaches 8 m without a controlled stop.', 'Pain, slipping, stumbling or apprehension.', 'Any obstruction in the braking area.'],
  versionNote: 'This constrained start primer does not prepare or test maximal sprint speed. Faster and longer sprinting needs a suitable venue, adequate run-out and further progressive preparation.',
}

const balanceMarch: PreparationExercise = {
  id: 'prepare-running-step-balance',
  name: 'March-to-single-leg balance',
  purposes: ['Activate', 'Integrate'],
  equipment: ['None'],
  whyHere: 'Checks comfortable single-leg support and pelvis control relevant to repeated running steps without adding jump contacts.',
  setup: ['Stand hip-width inside the lane with room for a normal arm swing.', 'Use a modest knee lift and keep the supporting knee soft.'],
  executionSteps: ['Shift onto one leg and lift the other foot just clear of the floor.', 'Pause for two seconds while keeping the trunk comfortably upright.', 'Return the foot quietly, shift sides and repeat with relaxed opposite-arm action.'],
  coachCues: ['Balance over the foot.', 'Pelvis level enough to stay comfortable.', 'Place the foot quietly.'],
  athleteCues: ['Look ahead.', 'Stay tall and relaxed.', 'Reset with both feet if I wobble.'],
  qualityGates: ['Each side controls the short pause.', 'The athlete does not lean far sideways.', 'Foot placement stays comfortable and repeatable.'],
  commonFaults: ['Lifting the knee so high that the trunk leans back.', 'Locking the stance knee.', 'Hopping repeatedly to rescue the balance.'],
  scaling: ['Keep the opposite toes lightly on the floor as a kickstand.', 'Shorten the pause or use a smaller foot lift.'],
  stopSigns: ['Pain in the support leg.', 'Repeated loss of balance despite the scale.', 'Dizziness when standing on one leg.'],
}

const runningMarch: PreparationExercise = {
  id: 'prepare-running-relaxed-march',
  name: 'Relaxed running march',
  purposes: ['Integrate'],
  equipment: ['Cones at 0 m and 5 m when traveling'],
  whyHere: 'Connects relaxed arm rhythm, comfortable step placement and single-leg support without the forceful knee drive used for sprint preparation.',
  setup: ['Begin on a stationary spot or at the 0 m cone as prescribed.', 'Use a natural arm swing and a low, comfortable knee lift.'],
  executionSteps: ['March with smooth opposite arm and leg action and normal breathing.', 'Place each foot under a comfortable support position without deliberately reaching.', 'When traveling, stop after 5 m, turn from a standstill and walk back inside the same lane.'],
  coachCues: ['Easy rhythm, relaxed arms.', 'Comfortable steps underneath.', 'Keep the shoulders soft.'],
  athleteCues: ['Move naturally.', 'No forced high knees.', 'Walk the reset.'],
  qualityGates: ['The athlete can breathe and speak comfortably.', 'Arms and legs coordinate without excess tension.', 'Travel and return stay controlled inside the lane.'],
  commonFaults: ['Exaggerating knee lift or arm drive.', 'Reaching far in front with the foot.', 'Rushing the turn to keep moving.'],
  scaling: ['Remain in place with a lower knee lift.', 'Use a slower walk-like weight transfer with both feet briefly grounded.'],
  stopSigns: ['Pain or altered gait.', 'Loss of balance.', 'Difficulty maintaining safe lane boundaries.'],
}

const easyRhythm: PreparationExercise = {
  id: 'prepare-running-easy-rhythm-interval',
  name: 'Easy jog-in-place rhythm interval',
  purposes: ['Raise', 'Integrate'],
  equipment: ['None'],
  whyHere: 'Extends easy continuous movement after mobility so running preparation emphasizes relaxed repeated contacts rather than explosive starts.',
  setup: ['Use the same clear stationary position in the assigned lane.', 'Start from marching and select a natural, comfortable rhythm.'],
  executionSteps: ['Move from a march into a low, easy jog in place.', 'Allow comfortable foot contact and relaxed arms without prescribing a cadence or foot-strike style.', 'Sustain the prescribed easy interval, then return gradually to marching.'],
  coachCues: ['Easy enough to talk.', 'Relax shoulders and hands.', 'Keep the rhythm comfortable.'],
  athleteCues: ['Small steps on my spot.', 'Breathe normally.', 'March if I need to.'],
  qualityGates: ['The interval stays conversational.', 'Contact sound and rhythm remain consistent.', 'The athlete finishes feeling able to continue easy movement.'],
  commonFaults: ['Increasing speed until the interval becomes conditioning.', 'Forcing a forefoot strike or fixed cadence.', 'Tensing the shoulders as the interval continues.'],
  scaling: ['Use a continuous brisk march for the full interval.', 'Alternate brief easy jogging and marching within the prescribed time.'],
  stopSigns: ['Pain or limping.', 'Dizziness or unusual breathlessness.', 'Progressively heavier, uncontrolled contacts.'],
}

const runRehearsal: PreparationExercise = {
  id: 'prepare-running-rhythm-rehearsal',
  name: 'Running rhythm rehearsal: march → easy jog in place',
  purposes: ['Integrate', 'Potentiate Bridge'],
  equipment: ['Cones marking 0 m, 4 m and 8 m for the following bridge'],
  whyHere: 'Rehearses a relaxed march-to-run transition and confirms an easy effort before introducing short forward travel.',
  setup: ['Stand at the lane start and identify the following drill’s 4 m ease-off point and 8 m stop limit.', 'Brief the stopping and walking-return plan before the rehearsal.'],
  executionSteps: ['March for the prescribed opening interval with relaxed opposite arm action.', 'Transition smoothly into a low, easy jog in place without forcing a higher cadence.', 'Return to a march and confirm normal breathing before the forward-running bridge.'],
  coachCues: ['Same relaxed rhythm as you change gears.', 'Easy, natural contacts.', 'Know where the forward run ends.'],
  athleteCues: ['Stay relaxed.', 'I can speak comfortably.', 'I know the stopping plan.'],
  qualityGates: ['The march-to-jog transition is comfortable and coordinated.', 'The athlete can return smoothly to marching.', 'The athlete understands the full forward travel and return route.'],
  commonFaults: ['Launching into a sprint rhythm.', 'Holding the breath during the transition.', 'Beginning forward travel before the coach checks the lane.'],
  scaling: ['Rehearse a comfortable march-to-brisk-march transition.', 'Keep the following bridge as walking if the easy jog is not controlled.'],
  stopSigns: ['Pain, dizziness or unusual distress.', 'Repeated stumbling or inability to settle the rhythm.', 'Unsafe space for the next task.'],
}

const easyRunBridge: PreparationExercise = {
  id: 'prepare-running-short-easy-run-bridge',
  name: 'Short easy run + walking brake',
  purposes: ['Potentiate Bridge'],
  equipment: ['Cones at 0 m, 4 m and 8 m inside the 10 m lane'],
  whyHere: 'Transfers the rehearsed easy running rhythm into forward travel and tests a smooth, controlled transition back to walking.',
  setup: ['Reserve 0–4 m for easy jogging and 4–8 m for easing to a complete stop; keep 8–10 m unused.', 'Use one athlete per lane and confirm the entire route is clear.', 'Choose a pace slow enough to stop comfortably within the marked area.'],
  executionSteps: ['Start gently and jog with a relaxed natural rhythm only to the 4 m cone.', 'Reduce the pace into walking and come to a complete stop before 8 m.', 'Turn after stopping and walk back in the same lane.', 'If a second pass is prescribed, use a slightly smoother or more settled easy rhythm; do not turn it into a faster sprint.'],
  coachCues: ['Easy forward rhythm.', 'Ease off at 4 m.', 'Stop, turn, walk back.'],
  athleteCues: ['Keep it conversational.', 'Leave room to slow down.', 'Finish ready for more easy running.'],
  qualityGates: ['No rapid acceleration or hard braking.', 'The athlete stops comfortably before 8 m.', 'Running rhythm stays relaxed and repeatable.'],
  commonFaults: ['Sprinting because the distance is short.', 'Running to the end of the lane before trying to stop.', 'Cutting sharply around a cone.'],
  scaling: ['Brisk-walk the 4 m segment and slow-walk to stop.', 'Shorten the jogging segment to 2 m if more stopping space is needed.'],
  stopSigns: ['Pain, limping or loss of balance.', 'Inability to stop by 8 m.', 'Unusual breathlessness or any obstruction in the lane.'],
  versionNote: 'This is an indoor transition check. Longer running, faster intervals or racing require the appropriate venue and a further gradual build to that session’s demands.',
}

const laneSetup = [
  'Use three separate 10 m lanes, one athlete per lane; place cones beside the travel path rather than under the feet.',
  'Keep all movements, braking, standing turns and walking returns inside each 10 m lane. Do not assume space beyond the finish or an external return route.',
  'Confirm that the actual lane width permits each stationary stance and arm action; use the narrower scale where needed.',
] as const

const commonLimits = [
  'The published clock covers one wave of up to three athletes. Additional athletes need repeated waves or a longer booking.',
  'Work time is the available controlled-movement window, not permission to add repetitions. Finish the stated dose, then use remaining time for observation or quiet recovery.',
  'Clock estimates include explanation, setup and resets for a familiar routine. New instruction, cold conditions or an athlete who is not ready require additional preparation time.',
] as const

const sprintExit = [
  'The athlete reports feeling warmer and comfortable and demonstrates controlled ankle, hip and single-leg positions.',
  'First-step rhythm is coordinated and the athlete can complete a smooth stop before 8 m.',
  'No pain, limping, dizziness, unusual distress or unresolved loss of movement control.',
] as const

const runExit = [
  'Easy rhythm remains conversational with relaxed shoulders and comfortable repeatable contacts.',
  'The athlete can move from march to jog and back to walking without pain or loss of balance.',
  'The forward bridge stops comfortably before 8 m and the athlete is ready to continue at an easy effort.',
] as const

export const LOCOMOTION_PREPARATION_ROUTINES: readonly DisciplinePreparationRoutine[] = [
  {
    id: 'access-prepare-sprinting-15', discipline: 'sprinting', title: 'Sprinting', durationMinutes: 15,
    summary: 'The fullest sprint preparation: ankle and hip access, arm action, front-side placement and a small contact dose, followed by a contained start rehearsal and controlled build.',
    purpose: 'Prepare first-step coordination and low-level sprint contacts while preserving enough recovery and stopping room for the three 10 m lanes.',
    equipment: ['Cones or existing floor markers'], setup: laneSetup,
    entryCriteria: ['Athlete can walk and perform basic bodyweight movements comfortably.', 'Coach has checked the surface and marked build and stopping areas before the clock starts.'],
    coverage: ['Progressive temperature raise.', 'Ankle/calf, trailing-hip and posterior-chain access.', 'Frontal-plane hip control and sprint arm coordination.', 'A-march, ten low pogo contacts and two short dribble bursts.', 'Two-step rehearsal followed by controlled 2–3 m builds with protected braking space.'],
    timeBudgetNote: '15:00 total: 11 coached blocks. The longer version adds observable positions and short, separated contact exposures rather than more sprint distance.',
    limitations: [...commonLimits, 'The three lanes cannot accommodate maximal sprinting, flying sprints or a full sprint warm-up. Move to an appropriate venue and add progressive sprint-specific exposures before that work.'],
    exitCriteria: sprintExit,
    progression: 'Begin the next session task only after the controlled stop and readiness checks pass. For faster running elsewhere, first verify adequate distance and run-out, then progressively rehearse the actual sprint distance and intensity.',
    steps: [
      timed(marchRaise, '90 s: 30 s march → 45 s easy jog in place → 15 s march', [90, 15, 15], 'Brief lane ownership during setup; use recovery for the initial comfort and breathing check.', 'Easy, conversational'),
      timed(ankleCalf, '5 ankle rocks per side + 8 two-foot heel raises', [50, 20, 20], 'Demonstrate the heel-down rock; switch sides calmly, then check two controlled heel raises before the remaining dose.', 'Comfortable range; slow loading'),
      timed(splitReach, '4 short lunge-and-reach repetitions per side', [50, 20, 20], 'Complete one side, stand and reset, then change sides; coach checks ribs, knee tracking and stance width.', 'Controlled bodyweight effort'),
      timed(hingeReach, '6 hip hinges with a brief controlled return', [40, 15, 20], 'Coach observes the side view; end the set when the dose is complete and use spare movement time to correct the next starting position.', 'Easy positional rehearsal'),
      timed(lateralShift, '4 controlled weight shifts per side', [40, 15, 20], 'Alternate directions from a stance that fits the lane; narrow the stance immediately if boundaries are tight.', 'Shallow to comfortable range'),
      timed(armSwitch, '2 × 8 s arm-switch bursts, one with each foot forward', [30, 15, 15], 'Reset and relax the hands between bursts; the movement window includes changing stance, not extra bursts.', 'Purposeful but relaxed'),
      timed(aMarch, '2 × 5 m A-march', [35, 20, 20], 'Use short deliberate steps; stop at 5 m and walk back in the same lane before the second pass.', 'Deliberate, no speed target'),
      timed(lowPogo, '1 × 10 low two-foot contacts', [10, 30, 20], 'Count landings and stop at ten; use the rest of the block for the coach to inspect foot/ankle response and demonstrate dribbles.', 'Low bounce; light rhythm'),
      timed(dribble, '2 × 5 s low dribble in place', [20, 35, 20], 'Take a quiet reset between the two brief bursts and preserve the recovery allocation before the start rehearsal.', 'Smooth, slightly quicker rhythm'),
      timed(startRehearsal, '2 repetitions: two controlled push steps inside 2 m; alternate lead legs', [20, 45, 25], 'Walk and stop before 8 m after each repetition; standing turn and walking return are included in recovery. Confirm the braking route before progressing.', 'Easy technique rehearsal', 'rehearsal'),
      timed(controlledBuild, '2 builds: first 2 m, second up to 3 m if controlled; stop before 8 m', [15, 55, 20], 'Allow the full walk-back and quiet recovery between passes; increase intent only if the first stop is comfortable. Finish with a readiness check.', 'First easy; second purposeful submaximal', 'progressive'),
    ],
  },
  {
    id: 'access-prepare-sprinting-10', discipline: 'sprinting', title: 'Sprinting', durationMinutes: 10,
    summary: 'A focused sprint primer preserving ankle/hip access, front-side coordination and a low contact dose before two protected start bridge drills.',
    purpose: 'Prioritize the positions and contact qualities that lead directly into controlled sprint starts while keeping recovery and braking space intact.',
    equipment: ['Cones or existing floor markers'], setup: laneSetup,
    entryCriteria: ['Athlete is familiar with the marching, hinge and low-contact patterns.', 'Comfortable walking and a coach-checked clear lane are required before beginning.'],
    coverage: ['Easy movement raise.', 'Ankle/calf, hip extension and hinge access.', 'A-march plus a small pogo and dribble exposure.', 'Start rehearsal and controlled 2–3 m build.'],
    timeBudgetNote: '10:00 total: 9 blocks. Removes separate arm-switch and lateral-shift blocks while retaining the core positional checks and both final bridge drills.',
    limitations: [...commonLimits, 'This is a start primer in restricted space. Maximal or longer sprinting requires another venue and additional task-specific preparation.'],
    exitCriteria: sprintExit,
    progression: 'Keep the last build controlled and assess the stop. Advance to the day’s sprint task only in a venue with appropriate distance and run-out, using further gradual build-ups.',
    steps: [
      timed(marchRaise, '65 s: 20 s march → 35 s easy jog in place → 10 s march', [65, 10, 15], 'Coach checks movement comfort during the first march and confirms the next ankle stance during setup time.', 'Easy, conversational'),
      timed(ankleCalf, '4 ankle rocks per side + 5 two-foot heel raises', [35, 10, 15], 'Use small controlled ranges and one calm change of stance; finish the dose without filling the block with extra raises.', 'Controlled and comfortable'),
      timed(splitReach, '3 lunge-and-reach repetitions per side', [35, 10, 15], 'Complete one side and reset for the other; maintain front-foot contact and quiet ribs.', 'Easy bodyweight effort'),
      timed(hingeReach, '5 controlled hip hinges', [30, 10, 20], 'Keep this as an observable position check; use setup time to explain the following A-march rather than adding repetitions.', 'Deliberate, no stretch forcing'),
      timed(aMarch, '1 × 5 m A-march + walking return', [25, 15, 20], 'Emphasize opposite arm action within this block because the separate arm drill is omitted.', 'Coordinated and unhurried'),
      timed(lowPogo, '1 × 8 low two-foot contacts', [8, 22, 15], 'Count eight landings, absorb the final contact and recover; substitute heel raises if low contacts are not comfortable.', 'Low amplitude'),
      timed(dribble, '1 × 6 s low dribble in place', [10, 30, 20], 'One short exposure is enough; observe rhythm and use the remaining time for recovery and the start demonstration.', 'Quick enough to flow, not hard'),
      timed(startRehearsal, '2 repetitions: two controlled push steps inside 2 m; alternate lead legs', [20, 35, 20], 'Walk to a stop before 8 m each time and return only after a standing turn; coach checks both lead positions.', 'Easy technique rehearsal', 'rehearsal'),
      timed(controlledBuild, '2 builds: first 2 m, second up to 3 m if controlled; stop before 8 m', [15, 55, 20], 'Protect the full walk-back and recovery; use a second easy repetition if the first stop was less than comfortable.', 'Easy → purposeful submaximal', 'progressive'),
    ],
  },
  {
    id: 'access-prepare-sprinting-5', discipline: 'sprinting', title: 'Sprinting', durationMinutes: 5,
    summary: 'A minimum familiar start primer: easy raise, ankle and hip access, A-march, then one rehearsed start and one controlled short build.',
    purpose: 'Use five minutes for the highest-priority start positions and a clear stopping check without compressing a full contact sequence into less time.',
    equipment: ['Cones or existing floor markers'], setup: laneSetup,
    entryCriteria: ['Use only with athletes who already know the sequence and are comfortable with its movements.', 'Athlete is not cold, stiff, symptomatic or returning after prolonged inactivity; if so, extend preparation rather than enforcing five minutes.'],
    coverage: ['Short easy raise.', 'Ankle/calf and split-stance hip access.', 'Front-side placement with no added jump-contact block.', 'One start rehearsal followed by one controlled 2 m build.'],
    timeBudgetNote: '5:00 total: 6 blocks. Omits separate hinge, lateral, arm, pogo and dribble blocks; preserves explanation, reset and the two final bridge roles.',
    limitations: [...commonLimits, 'Minimum preparation for familiar, already comfortable athletes; it is not a complete warm-up for maximal sprinting.', 'No extra contacts are added to compensate for the shorter duration. Extend time when readiness checks fail.'],
    exitCriteria: sprintExit,
    progression: 'Use the result as a readiness checkpoint. Add preparation if needed and complete further progressive sprint exposures with proper run-out before any fast or long sprint work.',
    steps: [
      timed(marchRaise, '45 s: 15 s march → 20 s easy jog in place → 10 s march', [45, 0, 15], 'Keep the lane and stopping-plan briefing concise for this already familiar group; assess comfort during the movement.', 'Easy, conversational'),
      timed(ankleCalf, '3 ankle rocks per side + 4 two-foot heel raises', [25, 10, 10], 'Move within familiar ranges; omit extra repetitions and retain the short check after the heel raises.', 'Small and controlled'),
      timed(splitReach, '2 lunge-and-reach repetitions per side', [20, 10, 10], 'Coach checks one controlled repetition on each side; use the shallower scale if necessary.', 'Easy bodyweight effort'),
      timed(aMarch, '8 alternating A-march steps in place', [15, 10, 10], 'Integrate opposite arm action and a controlled foot placement; no travel or walking return is needed here.', 'Deliberate rhythm'),
      timed(startRehearsal, '1 repetition: two controlled push steps inside 2 m, then walk to stop', [10, 30, 20], 'Stop before 8 m, turn from a standstill and walk back; review the stop before the final pass.', 'Easy technique rehearsal', 'rehearsal'),
      timed(controlledBuild, '1 controlled 2 m build; gradually stop before 8 m', [10, 35, 15], 'Use only a modest increase from the rehearsal. Recovery includes walking return and the coach’s readiness check; no extra pass.', 'Purposeful but comfortably submaximal', 'progressive'),
    ],
  },
  {
    id: 'access-prepare-running-15', discipline: 'running', title: 'Running', durationMinutes: 15,
    summary: 'An extended easy-rhythm preparation with ankle, hip and single-leg checks, followed by a relaxed running transition and contained forward-running bridge.',
    purpose: 'Prepare comfortable repeated running contacts and efficient relaxed coordination, emphasizing easy sustained movement instead of explosive acceleration.',
    equipment: ['Cones or existing floor markers'], setup: laneSetup,
    entryCriteria: ['Athlete can walk and perform comfortable bodyweight movements without altered gait.', 'The coach has confirmed an appropriate next running venue; the three short lanes are for preparation only.'],
    coverage: ['Longer easy raise plus a second rhythm interval after mobility.', 'Ankle/calf, split-stance hip and hinge access.', 'Frontal-plane hip movement and single-leg balance.', 'Relaxed arm/leg rhythm with no required pogo or sprint-drill contacts.', 'March-to-jog rehearsal followed by two easy forward-running transitions.'],
    timeBudgetNote: '15:00 total: 10 blocks. Extra time supports easy movement, positional observation and rhythm, not a faster finishing effort.',
    limitations: [...commonLimits, 'The 10 m lanes cannot provide continuous forward running. Continue with easy running in a suitable venue; faster intervals or racing need further progressive preparation.'],
    exitCriteria: runExit,
    progression: 'Continue with easy running once a safe venue is available. Gradually approach the planned running task only after rhythm, breathing and comfort remain settled.',
    steps: [
      timed(marchRaise, '120 s: 30 s march → 75 s easy jog in place → 15 s march', [120, 15, 15], 'Allow a conversational rhythm to develop; coach checks comfort before the mobility blocks.', 'Easy, conversational'),
      timed(ankleCalf, '5 ankle rocks per side + 8 two-foot heel raises', [50, 20, 20], 'Check heel-down range and a quiet controlled lowering phase; pause rather than filling spare time with more calf work.', 'Comfortable range; low fatigue'),
      timed(splitReach, '4 short lunge-and-reach repetitions per side', [50, 20, 20], 'Use a range that allows relaxed breathing and a controlled front foot; change sides with a full standing reset.', 'Controlled and easy'),
      timed(hingeReach, '6 bodyweight hip hinges', [40, 15, 20], 'Use the arm reach for balance and observe a smooth return to standing; avoid chasing stretch depth.', 'Deliberate positional work'),
      timed(lateralShift, '4 stationary weight shifts per side', [40, 15, 20], 'Alternate smoothly within a stance that fits the lane; use the narrow shift when space requires it.', 'Comfortable and shallow'),
      timed(balanceMarch, '4 single-leg balances per side, 2 s per pause', [40, 15, 20], 'Alternate sides and reset the feet between holds; coach checks each athlete’s support-leg control.', 'Low effort; balanced'),
      timed(runningMarch, '2 × 5 m relaxed march', [35, 20, 20], 'Stop at 5 m and walk back within the lane; keep arm action relaxed rather than forceful.', 'Natural, easy rhythm'),
      timed(easyRhythm, '50 s easy jog in place → 10 s march', [60, 15, 15], 'Use 50 s of easy jogging and 10 s marching; return to a continuous march sooner if conversational effort is lost.', 'Easy sustained rhythm'),
      timed(runRehearsal, '10 s march → 20 s easy jog in place → 10 s march', [40, 25, 25], 'Demonstrate the next block’s 4 m ease-off point and 8 m stop limit; recover until breathing is relaxed.', 'Easy rehearsal', 'rehearsal'),
      timed(easyRunBridge, '2 passes: easy jog to 4 m, walk and stop before 8 m', [20, 50, 20], 'Standing turns and walking returns fit inside recovery. The second pass should feel smoother and settled, not faster.', 'Comfortable easy running', 'progressive'),
    ],
  },
  {
    id: 'access-prepare-running-10', discipline: 'running', title: 'Running', durationMinutes: 10,
    summary: 'A focused running preparation combining an easy raise with ankle, hip and support-leg checks, then a relaxed rhythm rehearsal and short easy-running bridge.',
    purpose: 'Prepare repeatable comfortable running steps with enough time to check positions and breathing before beginning the main run.',
    equipment: ['Cones or existing floor markers'], setup: laneSetup,
    entryCriteria: ['Athlete knows the basic movements and is comfortable walking.', 'Coach has established lane ownership and a safe venue for the main running session.'],
    coverage: ['Easy continuous raise.', 'Ankle/calf, hip extension and hinge access.', 'Single-leg support and relaxed marching coordination.', 'Easy rhythm rehearsal followed by two contained forward-running passes.'],
    timeBudgetNote: '10:00 total: 8 blocks. Omits the separate lateral block and second general rhythm interval while preserving single-leg support and both finishing bridges.',
    limitations: [...commonLimits, 'Running beyond these short transitions belongs in a suitable venue. Faster intervals and racing require additional gradual running-specific build-up.'],
    exitCriteria: runExit,
    progression: 'Begin the next running segment easily. Progress duration or pace only after the athlete maintains comfortable rhythm and breathing in a venue appropriate to that task.',
    steps: [
      timed(marchRaise, '90 s: 20 s march → 55 s easy jog in place → 15 s march', [90, 15, 15], 'Check conversational effort while the rhythm settles; keep all movement on the stationary spot.', 'Easy and relaxed'),
      timed(ankleCalf, '4 ankle rocks per side + 5 two-foot heel raises', [35, 10, 15], 'Use comfortable controlled ranges and complete the dose once; observe before changing stance.', 'Low effort'),
      timed(splitReach, '3 short lunge-and-reach repetitions per side', [35, 10, 15], 'Keep the stance short enough for balance and the reach small enough for quiet ribs.', 'Comfortable bodyweight effort'),
      timed(hingeReach, '5 controlled hip hinges', [30, 10, 20], 'Observe the return to standing as well as the hinge; setup time introduces the following balance task.', 'Smooth and unhurried'),
      timed(balanceMarch, '3 single-leg balances per side, 2 s per pause', [30, 10, 20], 'Alternate sides with a complete foot reset; choose the toe-touch scale if necessary.', 'Quiet support-leg control'),
      timed(runningMarch, '1 × 5 m relaxed march + walking return', [25, 15, 20], 'Use natural opposite-arm rhythm and an unhurried standing turn.', 'Easy, natural rhythm'),
      timed(runRehearsal, '10 s march → 20 s easy jog in place → 10 s march', [40, 25, 25], 'Reconfirm the 4 m ease-off point and 8 m stop limit before progressing to travel.', 'Easy rehearsal', 'rehearsal'),
      timed(easyRunBridge, '2 passes: easy jog to 4 m, walk and stop before 8 m', [20, 50, 20], 'Recover during the walking return and pause; use the second pass to settle rhythm, not chase speed.', 'Comfortable easy running', 'progressive'),
    ],
  },
  {
    id: 'access-prepare-running-5', discipline: 'running', title: 'Running', durationMinutes: 5,
    summary: 'A minimum familiar running primer emphasizing easy rhythm, ankle and hip access, then one rehearsal and one short forward-running transition.',
    purpose: 'Prepare a comfortable transition into easy running when the athlete is already familiar, moving comfortably and does not need a longer general raise.',
    equipment: ['Cones or existing floor markers'], setup: laneSetup,
    entryCriteria: ['Use with athletes who know the routine and are already moving comfortably.', 'If cold, stiff, symptomatic or uncertain, extend the preparation time before starting the main run.'],
    coverage: ['Brief easy raise.', 'Ankle/calf and split-stance hip access.', 'Relaxed marching coordination without jump contacts.', 'One march-to-jog rehearsal and one easy forward-running pass.'],
    timeBudgetNote: '5:00 total: 6 blocks. Removes separate hinge, lateral and balance blocks and uses one forward pass; no shortened-rest attempt to squeeze in the longer routine.',
    limitations: [...commonLimits, 'This is minimum preparation before easy running, not full preparation for a fast interval session or race.', 'Use additional easy movement if warmth, comfort or rhythm have not settled within five minutes.'],
    exitCriteria: runExit,
    progression: 'Continue with an easy opening running segment in a suitable venue. Add preparation and gradual pace changes before any demanding running task.',
    steps: [
      timed(marchRaise, '60 s: 15 s march → 35 s easy jog in place → 10 s march', [60, 0, 15], 'Use the familiar lane brief and check the athlete’s comfort during the raise.', 'Easy, conversational'),
      timed(ankleCalf, '3 ankle rocks per side + 4 two-foot heel raises', [25, 5, 10], 'Keep the range familiar and finish the dose once; do not accelerate repetitions to add more.', 'Controlled, comfortable'),
      timed(splitReach, '2 short lunge-and-reach repetitions per side', [20, 10, 10], 'Observe one clean repetition on each side before continuing; use the small-range scale as needed.', 'Easy bodyweight effort'),
      timed(runningMarch, '15 s relaxed march in place', [15, 10, 10], 'Use natural opposite-arm rhythm and comfortable knee lift; staying in place removes travel-reset demand.', 'Easy and relaxed'),
      timed(runRehearsal, '5 s march → 10 s easy jog in place → 5 s march', [20, 15, 15], 'Reconfirm the lane’s ease-off and stopping markers; proceed only with settled breathing and coordination.', 'Easy rehearsal', 'rehearsal'),
      timed(easyRunBridge, '1 pass: easy jog to 4 m, walk and stop before 8 m', [10, 35, 15], 'Recovery includes a standing turn, walking return and the readiness check; do not add a second pass.', 'Comfortable easy running', 'progressive'),
    ],
  },
]
