export const OPPORTUNITY_CATEGORIES = [
  'Community events',
  'Youth & family partnerships',
  'Sports venues',
  'Schools & municipalities',
]

export const seedOpportunities = [
  {
    name: 'Frederick Douglass HBCU Football Classic',
    category: 'Community events',
    kind: 'event',
    status: 'new',
    priority: 'high',
    location: 'Rochester Community Sports Complex, Rochester, NY',
    eventDate: '2026-10-03',
    deadline: '2026-08-14',
    contactName: 'Vendor team',
    contactEmail: 'info@fdhbcuclassic.com',
    contactPhone: '',
    websiteUrl: 'https://www.fdhbcuclassic.com/become-a-vendor',
    sourceUrl: 'https://www.fdhbcuclassic.com/become-a-vendor',
    audience: 'Students, families, alumni, community organizations and sports fans',
    supportOffer: 'Run a fast, inclusive movement challenge and offer family athletic-readiness consultations.',
    edgeStrategy: 'Lead with an HBCU-aligned youth opportunity, bring a measurable 3-minute combine, and offer an event-only scholarship drawing.',
    notes: 'Community vendor fee listed at $350; corporate vendor $1,500. Liability insurance may be required.',
  },
  {
    name: 'South Wedge Festival',
    category: 'Community events',
    kind: 'event',
    status: 'new',
    priority: 'high',
    location: 'South Avenue, Rochester, NY',
    eventDate: '2026-08-15',
    deadline: null,
    contactName: 'South Wedge Planning Committee',
    contactEmail: 'info@swpc.org',
    contactPhone: '585-256-1740',
    websiteUrl: 'https://www.swpc.org/events/south-wedge-festival',
    sourceUrl: 'https://www.swpc.org/events/south-wedge-festival',
    audience: 'Neighborhood families, local businesses and festival attendees',
    supportOffer: 'Sponsor a kids movement zone, pet-and-parent warm-up, or short family fitness demonstrations.',
    edgeStrategy: 'Pitch a specific no-power, small-footprint activation and cross-promote nearby businesses before requesting a booth.',
    notes: '2026 sponsor and artist/vendor applications are open.',
  },
  {
    name: 'Great New York State Flea — Back to School',
    category: 'Community events',
    kind: 'event',
    status: 'new',
    priority: 'high',
    location: 'Rochester Public Market, 280 N. Union St., Rochester, NY',
    eventDate: '2026-08-09',
    deadline: null,
    contactName: 'Rochester Public Market office',
    contactEmail: 'pmarket@cityofrochester.gov',
    contactPhone: '585-428-6907',
    websiteUrl: 'https://www.cityofrochester.gov/events/great-new-york-state-flea-public-market-2026',
    sourceUrl: 'https://www.cityofrochester.gov/events/great-new-york-state-flea-public-market-2026',
    audience: 'Families preparing for school and youth-focused community vendors',
    supportOffer: 'Offer free back-to-school movement screens, agility games, and take-home activity cards.',
    edgeStrategy: 'The $40 stall cost makes this ideal for testing a trackable QR offer before buying larger sponsorships.',
    notes: 'Covered outdoor stall; official page lists a low $40 vendor fee.',
  },
  {
    name: 'Rochester Queer Arts Festival',
    category: 'Community events',
    kind: 'event',
    status: 'new',
    priority: 'medium',
    location: 'Village Gate Square, Rochester, NY',
    eventDate: '2026-10-10',
    deadline: null,
    contactName: 'Festival team',
    contactEmail: '',
    contactPhone: '',
    websiteUrl: 'https://www.queerartsfest.com/',
    sourceUrl: 'https://www.queerartsfest.com/',
    audience: 'LGBTQIA+ artists, families, allies and community organizations',
    supportOffer: 'Provide an explicitly inclusive, all-abilities movement station and sponsor youth participation.',
    edgeStrategy: 'Open with accessibility and belonging commitments, then propose a staffed activation rather than logo-only sponsorship.',
    notes: 'Vendor, performer and sponsorship opportunities are listed as open for 2026.',
  },
  {
    name: 'Rotary Sunshine Campus',
    category: 'Youth & family partnerships',
    kind: 'venue',
    status: 'new',
    priority: 'high',
    location: '809 Five Points Road, Rush, NY 14543',
    eventDate: null,
    deadline: null,
    contactName: 'Sunshine Campus',
    contactEmail: '',
    contactPhone: '585-533-2080',
    websiteUrl: 'https://www.sunshinecamp.org/events/',
    sourceUrl: 'https://www.sunshinecamp.org/events/',
    audience: 'Children and young adults with disabilities and city youth',
    supportOffer: 'Donate adaptive movement programming, trained coaches, or a sensory-aware activity station at a 2026 fundraiser.',
    edgeStrategy: 'Start with a service partnership and accessibility plan; document coach training and participant accommodations.',
    notes: 'Multiple 2026 sponsorship events, including an Aug. 13 clays tournament and Oct. 16 Trail Mix 5K.',
  },
  {
    name: 'Paul Louis Arena',
    category: 'Sports venues',
    kind: 'venue',
    status: 'new',
    priority: 'medium',
    location: '1 Boys Club Place, Rochester, NY',
    eventDate: null,
    deadline: null,
    contactName: 'Arena team',
    contactEmail: 'Info@paullouisarena.com',
    contactPhone: '585-325-2216',
    websiteUrl: 'https://www.paullouisarena.com/',
    sourceUrl: 'https://www.paullouisarena.com/',
    audience: 'Youth hockey families, adult leagues and tournament participants',
    supportOffer: 'Provide off-ice speed, balance, mobility and injury-risk-reduction sessions.',
    edgeStrategy: 'Offer a pilot for one youth team with pre/post benchmarks and a revenue share for recurring off-ice clinics.',
    notes: 'Venue publishes youth hockey, tournaments and ice booking opportunities.',
  },
  {
    name: 'ESL Sports Centre',
    category: 'Sports venues',
    kind: 'venue',
    status: 'new',
    priority: 'medium',
    location: '2700 Brighton-Henrietta Townline Road, Rochester, NY 14623',
    eventDate: null,
    deadline: null,
    contactName: 'Venue contact',
    contactEmail: 'rmaluta@eslsportscentre.com',
    contactPhone: '585-424-4625',
    websiteUrl: 'http://www.eslsportscenter.com',
    sourceUrl: 'https://www.filmrochester.org/guide/esl-sports-centre/',
    audience: 'Tournament organizers, athletes and sports families',
    supportOffer: 'Add combine testing, warm-up support, recovery education, or overflow training to tournaments.',
    edgeStrategy: 'Package support as an event-operations upgrade with a one-page footprint, staffing and insurance plan.',
    notes: 'Contact details verified through the Rochester/Finger Lakes Film Commission venue guide.',
  },
  {
    name: 'City of Rochester Recreation & Human Services',
    category: 'Schools & municipalities',
    kind: 'partner',
    status: 'new',
    priority: 'high',
    location: '57 St. Paul Street, Rochester, NY 14604',
    eventDate: null,
    deadline: null,
    contactName: 'Department of Recreation and Human Services',
    contactEmail: '',
    contactPhone: '585-428-6755',
    websiteUrl: 'https://www.cityofrochester.gov/departments/department-recreation-and-human-services-drhs/r-central',
    sourceUrl: 'https://www.cityofrochester.gov/departments/department-recreation-and-human-services-drhs/r-central',
    audience: 'City families, recreation participants, camps and youth leagues',
    supportOffer: 'Pilot a mobile athletic-development clinic at an R-Center or provide coach-led field-day programming.',
    edgeStrategy: 'Propose one neighborhood, one age band, a defined attendance cap and simple outcome reporting to reduce procurement friction.',
    notes: 'R-Central includes programs, camps, leagues and reservable facilities.',
  },
]
