export const OPPORTUNITY_CATEGORIES = [
  'Community events',
  'Youth & family partnerships',
  'Sports venues',
  'Schools & municipalities',
]

// Vortex Athletics is based in Bowie, MD 20715. Keep starter research local to
// Bowie and the immediately relevant Prince George's County service area.
export const seedOpportunities = [
  {
    name: 'City of Bowie Back-to-School Bash',
    category: 'Community events', kind: 'event', status: 'new', priority: 'high',
    location: 'Bowie, MD 20716', eventDate: '2026-08-15', deadline: null,
    contactName: 'City of Bowie', contactEmail: '', contactPhone: '',
    websiteUrl: 'https://www.cityofbowie.org/2318/Back-to-School-Bash',
    sourceUrl: 'https://www.cityofbowie.org/2318/Back-to-School-Bash',
    audience: 'Bowie children ages 4–10 and their parents',
    supportOffer: 'Sponsor a movement station, agility challenge, or family warm-up activity.',
    edgeStrategy: 'Offer a compact, staff-led activation with a QR code for a free trial class.',
    notes: 'Official City of Bowie event listed for August 15, 2026, 10 a.m.–1 p.m.',
  },
  {
    name: 'Bowie International Festival',
    category: 'Community events', kind: 'event', status: 'new', priority: 'high',
    location: 'Bowie, MD 20716', eventDate: '2026-09-12', deadline: null,
    contactName: 'City of Bowie', contactEmail: 'community@cityofbowie.org', contactPhone: '',
    websiteUrl: 'https://www.cityofbowie.org/110/Special-Events',
    sourceUrl: 'https://www.cityofbowie.org/110/Special-Events',
    audience: 'Bowie families, residents, and community organizations',
    supportOffer: 'Provide an inclusive movement activity that celebrates different cultures and abilities.',
    edgeStrategy: 'Lead with accessibility, family participation, and a small-footprint setup.',
    notes: 'Official City of Bowie special-events listing shows the 2026 festival on September 12.',
  },
  {
    name: 'City of Bowie Recreation & Gymnasium Partnerships',
    category: 'Schools & municipalities', kind: 'partner', status: 'new', priority: 'high',
    location: 'Bowie Municipal Gymnasium, Bowie, MD 20716', eventDate: null, deadline: null,
    contactName: 'City of Bowie Recreation', contactEmail: '', contactPhone: '301-809-3078',
    websiteUrl: 'https://www.cityofbowie.org/101/Recreation',
    sourceUrl: 'https://www.cityofbowie.org/104/Gymnasium',
    audience: 'Bowie youth leagues, families, and recreation participants',
    supportOffer: 'Propose clinics, movement screenings, coach education, or seasonal youth programming.',
    edgeStrategy: 'Start with a single pilot clinic and measurable participation outcomes.',
    notes: 'The City lists recreation programming and an organized-sports municipal gymnasium.',
  },
  {
    name: 'Allen Pond Park Youth Sports Activation',
    category: 'Sports venues', kind: 'venue', status: 'new', priority: 'medium',
    location: 'Allen Pond Park, Bowie, MD 20716', eventDate: null, deadline: null,
    contactName: 'City of Bowie Parks', contactEmail: '', contactPhone: '',
    websiteUrl: 'https://www.cityofbowie.org/107/Parks',
    sourceUrl: 'https://www.cityofbowie.org/107/Parks',
    audience: 'Youth sports families and park visitors in Bowie',
    supportOffer: 'Offer a pop-up athletic-readiness challenge, warm-up clinic, or family fitness event.',
    edgeStrategy: 'Coordinate with the City before proposing any activation because park space is scheduled.',
    notes: 'Use the City parks page for current facility and event rules before outreach.',
  },
  {
    name: 'Bowie State University Youth Sports Outreach',
    category: 'Youth & family partnerships', kind: 'partner', status: 'new', priority: 'medium',
    location: 'Bowie State University, Bowie, MD 20715', eventDate: null, deadline: null,
    contactName: 'Bowie State Athletics', contactEmail: '', contactPhone: '',
    websiteUrl: 'https://bsubulldogs.com/',
    sourceUrl: 'https://bsubulldogs.com/',
    audience: 'Prince George’s County youth, families, and student-athletes',
    supportOffer: 'Explore a youth clinic, mentoring session, or athletic testing partnership.',
    edgeStrategy: 'Connect the proposal to Bowie State’s existing community sports outreach work.',
    notes: 'Keep outreach focused on a specific youth-serving clinic or measurable mentorship program.',
  },
  {
    name: 'Prince George’s County Parks Youth Programs',
    category: 'Schools & municipalities', kind: 'partner', status: 'new', priority: 'medium',
    location: 'Bowie / Prince George’s County, MD', eventDate: null, deadline: null,
    contactName: 'M-NCPPC Prince George’s County Parks', contactEmail: '', contactPhone: '',
    websiteUrl: 'https://www.pgparks.com/',
    sourceUrl: 'https://www.pgparks.com/',
    audience: 'County youth, community-center families, and sports participants',
    supportOffer: 'Propose mobile gymnastics, tumbling, athletic-development, or coach-training clinics.',
    edgeStrategy: 'Lead with a low-risk pilot at a Bowie-area community center and a clear attendance cap.',
    notes: 'Confirm current procurement, permits, insurance, and program requirements before outreach.',
  },
]
