import {expect,type Page} from '@playwright/test'
import {nativeI9,nativeEmployerI9} from './nativePayrollJourney'
import {nativeJourneyPreparer} from './nativeJourneyPreparer'

export async function nativeJourneyAmendment(employee:Page,admin:Page,number:string,apiUrl:string,pdf:Buffer){
 await employee.reload()
 await employee.getByRole('button',{name:'Onboarding',exact:true}).click()
 const employeeStep=employee.locator('details').filter({has:employee.locator('summary',{hasText:'Form I-9 employee section'})})
 await employeeStep.locator('summary').first().click()
 await expect(employeeStep).toContainText('To correct this signed form, ask your hiring admin to reopen this step.')
 await admin.reload()
 await admin.getByRole('button',{name:'People & onboarding',exact:true}).click()
 await admin.getByRole('button',{name:new RegExp(number)}).click()
 const reopen=admin.locator('details').filter({has:admin.locator('summary',{hasText:'Form I-9 employee section'})})
 await reopen.locator('summary').first().click()
 await reopen.getByLabel('Review evidence / instructions',{exact:true}).fill('Please correct the synthetic Section 1 address and sign the amended entries.')
 await reopen.getByRole('button',{name:'Request changes',exact:true}).click()
 await expect(reopen.locator('summary').first()).toContainText('CHANGES REQUESTED')
 await employee.reload()
 await employee.getByRole('button',{name:'Onboarding',exact:true}).click()
 await employeeStep.getByRole('button',{name:'Prepare an I-9 amendment',exact:true}).click()
 await nativeI9(employee,true,'3 Corrected Test Street')
 await admin.reload()
 await admin.getByRole('button',{name:'People & onboarding',exact:true}).click()
 await admin.getByRole('button',{name:new RegExp(number)}).click()
 const employer=admin.locator('details').filter({has:admin.locator('summary',{hasText:'Employer I-9 review'})})
 await employer.locator('summary').first().click()
 await expect(employer.locator('summary').first()).not.toContainText('COMPLETE')
 const records=employer.getByRole('region',{name:'Retained employer I-9 evidence',exact:true})
 await expect(records.locator('summary').filter({hasText:'Historical certification'})).toHaveCount(1)
 await expect(records.locator('summary').filter({hasText:'Current certification'})).toHaveCount(0)
 const section=admin.locator('details').filter({has:admin.locator('summary',{hasText:'Form I-9 employee section'})})
 await section.locator('summary').first().click()
 await expect(section.locator('summary').first()).toContainText('SUBMITTED')
 await section.getByLabel('Review evidence / instructions',{exact:true}).fill('Reviewed corrected synthetic employee address and required new preparer certifications.')
 await expect(section.getByRole('button',{name:'Verify & complete',exact:true})).toBeDisabled()
 await nativeJourneyPreparer(admin,apiUrl,2)
 await section.getByRole('button',{name:'Verify & complete',exact:true}).click()
 await expect(section.locator('summary').first()).toContainText('COMPLETE')
 // The current reviewed packet is rebuilt against the new employee submission.
 if(!await employer.evaluate(element=>(element as HTMLDetailsElement).open))await employer.locator('summary').first().click()
 await nativeEmployerI9(admin,pdf,2)
 if(!await employer.evaluate(element=>(element as HTMLDetailsElement).open))await employer.locator('summary').first().click()
 await employer.getByRole('button',{name:'Refresh signed employer evidence',exact:true}).click()
 await expect(records.locator('summary').filter({hasText:'Current certification'})).toHaveCount(1)
 await expect(records.locator('summary').filter({hasText:'Historical certification'})).toHaveCount(1)
 await records.screenshot({path:'/tmp/payroll-native-amendment-history.png'})
}
