import {expect,type Page} from '@playwright/test'

export async function nativeJourneyRehirePayroll(admin:Page,employee:Page){
 await admin.getByRole('button',{name:'Daily time',exact:true}).click()
 await admin.getByLabel('Clock in',{exact:true}).fill('2026-09-16T09:00')
 await admin.getByLabel('Clock out',{exact:true}).fill('2026-09-16T17:00')
 await admin.getByLabel('Evidence/source note').fill('Synthetic eight hours worked after rehire and second native onboarding.')
 await admin.getByRole('button',{name:'Add unverified entry',exact:true}).click()
 await admin.getByRole('button',{name:'Approve',exact:true}).click()
 await expect(admin.getByText('Time entry approved and audit logged.',{exact:true})).toBeVisible()
 await admin.getByRole('button',{name:'Payroll runs',exact:true}).click()
 await admin.getByLabel('Pay calendar month',{exact:true}).fill('2026-10')
 await admin.getByRole('button',{name:'Generate pay periods',exact:true}).click()
 const period=admin.getByRole('combobox',{name:'Pay period',exact:true})
 const option=period.locator('option').filter({hasText:'Sep 30, 2026'})
 await expect(option).toHaveCount(1)
 await period.selectOption((await option.getAttribute('value'))!)
 await admin.getByLabel('Payroll payment date',{exact:true}).fill('2026-10-06')
 await admin.getByRole('button',{name:'Preview payroll',exact:true}).click()
 await expect(admin.getByText('0 approval blockers',{exact:true})).toBeVisible()
 await admin.getByRole('button',{name:'Save draft snapshot',exact:true}).click()
 await admin.getByRole('row').filter({has:admin.getByText('DRAFT',{exact:true})}).getByRole('button',{name:'Open review',exact:true}).click()
 await admin.getByRole('button',{name:'Send to review',exact:true}).click()
 await admin.getByRole('button',{name:'Approve run',exact:true}).click()
 await admin.getByLabel('External payment confirmation').fill('SYNTHETIC-REHIRED-CHECK-ONLY')
 await admin.getByRole('button',{name:'Confirm paid & finalize',exact:true}).click()
 await expect(admin.getByText('Payroll finalized and employee statements saved.',{exact:true})).toBeVisible()
 await employee.getByRole('button',{name:'Refresh payroll portal',exact:true}).click()
 await employee.getByRole('button',{name:'Pay statements',exact:true}).click()
 const statements=employee.getByRole('button',{name:'Download itemized pay statement (PDF)',exact:true})
 await expect(statements).toHaveCount(2)
 const download=employee.waitForEvent('download')
 await statements.first().click()
 await (await download).saveAs('/tmp/payroll-native-rehire-statement.pdf')
 console.info('Journey: post-rehire payroll finalized and second statement downloaded')
}
