import {expect,type Page} from '@playwright/test'

export async function nativeJourneyRehire(admin:Page,employee:Page,email:string,startDate:string,signIn?:()=>Promise<void>){
 await admin.getByRole('button',{name:'Pay setup & leave',exact:true}).click()
 await admin.getByRole('button',{name:'Cancel scheduled pay change',exact:true}).click()
 await admin.getByLabel('Reason for cancellation',{exact:true}).fill('Synthetic separation and rehire review: reconcile the future wage agreement.')
 const notice=admin.getByLabel('Cancellation notice delivered on',{exact:true})
 await notice.fill((await notice.getAttribute('max'))!)
 await admin.getByLabel('Cancellation notice reference',{exact:true}).fill('Synthetic written cancellation delivered before separation')
 await admin.getByLabel('I confirm this employee received the written cancellation notice.').check()
 await admin.getByRole('button',{name:'Confirm pay change cancellation',exact:true}).click()
 await expect(admin.getByText('Pay change cancelled. The previous rate continues; schedule a replacement below if needed.')).toBeVisible()
 await admin.getByRole('combobox',{name:'Employment status',exact:true}).selectOption('TERMINATED')
 await admin.getByRole('button',{name:'Save employee details',exact:true}).click()
 await expect(admin.getByText('Employee details saved and audited.',{exact:true})).toBeVisible()
 await admin.getByRole('button',{name:'People & onboarding',exact:true}).click()
 const rehire=admin.getByRole('region',{name:'Rehire preparation',exact:true})
 await rehire.getByLabel('Proposed rehire date',{exact:true}).fill(startDate)
 await rehire.getByRole('button',{name:'Review rehire records',exact:true}).click()
 await expect(rehire.getByRole('button',{name:'Reopen onboarding',exact:true})).toBeDisabled()
 await rehire.getByLabel('Rehire reason',{exact:true}).fill('Synthetic return to the previously reviewed hourly role.')
 await rehire.getByLabel('Prior obligations and leave policy review reference',{exact:true}).fill('Synthetic review of finalized payroll, current obligations, cancelled future wage agreement and retained leave.')
 await rehire.getByLabel('I confirm the displayed start date, role and compensation terms.',{exact:true}).check()
 await rehire.getByLabel('I reviewed prior wages, corrections, expenses and leave policy, including retaining the displayed balances.',{exact:true}).check()
 await rehire.getByRole('button',{name:'Reopen onboarding',exact:true}).click()
 await expect(admin.getByText('Rehire onboarding opened. Complete fresh submissions and reviews before activation.',{exact:true})).toBeVisible()
 await expect(admin.getByText('0 of 12 steps complete',{exact:true})).toBeVisible()
 await expect(admin.getByRole('button',{name:'Complete onboarding & activate employee',exact:true})).toBeDisabled()
 await admin.locator('summary').filter({hasText:'Employer I-9 review'}).first().click()
 const records=admin.getByRole('region',{name:'Retained employer I-9 evidence',exact:true})
 await expect(records.locator('summary').filter({hasText:'Historical certification'})).toHaveCount(1)
 await expect(records.locator('summary').filter({hasText:'Current certification'})).toHaveCount(0)
 await employee.reload()
 if(signIn)await signIn()
 else{
 await employee.getByLabel('Email',{exact:true}).fill(email)
 await employee.getByLabel('Password',{exact:true}).fill('Vortex-Test-Password-2026')
 await employee.getByRole('button',{name:'Sign in to payroll',exact:true}).click()
 }
 await expect(employee.getByText('Hi, Morgan')).toBeVisible()
 await employee.getByRole('button',{name:'Onboarding',exact:true}).click()
 await expect(employee.getByText('0 of 12 steps complete',{exact:true})).toBeVisible()
 await employee.screenshot({path:'/tmp/payroll-native-rehire-employee.png',fullPage:true})
}
