import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Identity={legalName:string;identifierLast4:string;revision:number;address:{line1:string;line2?:string;city:string;state:string;postalCode:string}}
type Snapshot={year:number;employer:Identity;employee:{employeeName:string;filingIdentity:Identity;runIds:number[];wageInputs:Record<string,string|null>;withholding:Record<string,string|null>;reviewedQualifiedOvertime:string|null;benefitContributions:Array<{month:string;planName:string;optionLabel:string;employeeContribution:string}>|null}}
const money=(value:string|null)=>value===null?'Unavailable':`$${value}`
export default function AnnualReviewSnapshot({employeeId,reviewId}:{employeeId:number;reviewId:string}){
 const [data,setData]=useState<Snapshot|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=async()=>{setData(null);setError('');setBusy(true);try{const response=await adminApiRequest(`/api/admin/payroll/employees/${employeeId}/annual-input-review/${reviewId}`),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to read saved inputs.');setData(json.data.snapshot)}catch(e){setError(e instanceof Error?e.message:'Unable to read saved inputs.')}finally{setBusy(false)}}
 return <div className="mt-2 space-y-2"><button type="button" disabled={busy} onClick={()=>void load()} className="rounded-lg border border-slate-300 px-3 py-2 font-bold disabled:opacity-50">{busy?'Loading saved inputs…':`View saved inputs for review ${reviewId}`}</button>{error?<p role="alert" className="text-red-700">{error}</p>:null}
 {data?<section aria-label={`Saved inputs for review ${reviewId}`} className="space-y-2 rounded-lg border border-slate-200 bg-white p-3"><p className="font-bold">Saved {data.year} inputs · {data.employee.employeeName}</p><p>Historical review snapshot. These values do not change with live payroll and are not an issued tax form.</p>{[data.employer,data.employee.filingIdentity].map((identity,index)=><div key={index}><p className="font-semibold">{index===0?'Employer':'Employee'}: {identity.legalName}</p><p>{identity.address.line1}{identity.address.line2?`, ${identity.address.line2}`:''}, {identity.address.city}, {identity.address.state} {identity.address.postalCode}</p><p>Identifier ending {identity.identifierLast4} · Identity revision {identity.revision}</p></div>)}
 <p>Payroll runs: {data.employee.runIds.join(', ')}</p><dl>{[['federal','Federal'],['maryland','Maryland'],['socialSecurity','Social Security'],['medicare','Medicare']].map(([key,label])=><div key={key}><dt className="inline">{label} wage input: </dt><dd className="inline font-semibold">{money(data.employee.wageInputs[key])}</dd></div>)}{[['federal','Federal'],['maryland','Maryland'],['socialSecurity','Social Security'],['medicare','Medicare'],['additionalMedicare','Additional Medicare'],['combinedMedicare','Combined Medicare']].map(([key,label])=><div key={key}><dt className="inline">{label} withholding: </dt><dd className="inline font-semibold">{money(data.employee.withholding[key])}</dd></div>)}</dl><p>Reviewed qualified overtime: {money(data.employee.reviewedQualifiedOvertime)}</p>
 <p className="font-semibold">Retained employee benefit deductions</p>{data.employee.benefitContributions?.length?data.employee.benefitContributions.map((item,index)=><p key={index}>{item.month} · {item.planName} — {item.optionLabel}: {money(item.employeeContribution)}</p>):<p>No retained deductions in this snapshot.</p>}
 <button type="button" onClick={()=>setData(null)} className="font-semibold underline">Close saved inputs</button></section>:null}</div>
}
