import EarnedBonusPreview from './EarnedBonusPreview'
import {useState} from 'react'
import {payrollApi} from '../../utils/payrollApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
export default function AnnualBonusSetup({employeeId,periods,onChanged}:{employeeId:number;periods:Record<string,unknown>[];onChanged:()=>Promise<void>}){
 const [form,setForm]=useState({requestKey:crypto.randomUUID(),payPeriodId:'',amount:'',name:'Annual bonus',classification:'',source:'',paymentDiscretionVerified:false,amountDiscretionVerified:false,noPriorPromiseVerified:false,confirmed:false})
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const set=(key:keyof typeof form,value:string|boolean)=>setForm(current=>({...current,[key]:value,confirmed:false}))
 return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">Annual bonus</h2><p className="mt-2 text-sm text-slate-600">Record a single annual lump-sum bonus in a regular payroll payment. It applies only to the selected period. Earned or promised bonuses may require additional overtime.</p><form className="mt-4 space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{const data=new FormData(e.currentTarget);if(form.classification==='NONDISCRETIONARY'&&!data.get('allocationFingerprint'))throw new Error('Calculate and review the earned bonus allocation before recording it.');await payrollApi.createBonus(employeeId,{...form,...(form.classification==='NONDISCRETIONARY'?{earnedStart:data.get('earnedStart'),earnedEnd:data.get('earnedEnd'),allocationFingerprint:data.get('allocationFingerprint'),allocationMethod:'PROPORTIONAL_EARNED_HOURS',allocationMethodVerified:true}:{}),payPeriodId:Number(form.payPeriodId),amountCents:Math.round(Number(form.amount)*100),paymentType:'ANNUAL_LUMP_SUM'});await onChanged();setForm(current=>({...current,requestKey:crypto.randomUUID(),confirmed:false}));setMessage('Annual bonus recorded for the selected period. Review its payroll calculation before approval.')}catch(e){setError(e instanceof Error?e.message:'Unable to record bonus')}finally{setBusy(false)}}}>
 <label className="block text-sm font-bold">Bonus pay period<select required className={workforceInput} value={form.payPeriodId} onChange={e=>set('payPeriodId',e.target.value)}><option value="">Choose an open period</option>{periods.filter(p=>p.status==='OPEN').map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.period_start).slice(0,10)} through {String(p.period_end).slice(0,10)}</option>)}</select></label>
 <label className="block text-sm font-bold">Bonus amount ($)<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>set('amount',e.target.value)} className={workforceInput}/></label>
 <label className="block text-sm font-bold">Bonus classification<select required className={workforceInput} value={form.classification} onChange={e=>set('classification',e.target.value)}><option value="">Choose the reviewed classification</option><option value="DISCRETIONARY">Discretionary — no prior promise</option><option value="NONDISCRETIONARY">Earned or promised — include in regular rate</option></select></label>
 {form.classification==='DISCRETIONARY'?<div className="space-y-2">{([['paymentDiscretionVerified','The employer retained discretion whether to pay until at or near the end of the bonus period.'],['amountDiscretionVerified','The employer retained discretion over the amount until at or near the end of the bonus period.'],['noPriorPromiseVerified','There was no prior promise, agreement or expectation of this bonus.']] as const).map(([key,label])=><label className="flex gap-2 text-sm" key={key}><input type="checkbox" checked={form[key]} onChange={e=>set(key,e.target.checked)}/>{label}</label>)}</div>:null}
 {form.classification==='NONDISCRETIONARY'?<EarnedBonusPreview key={`${employeeId}:${form.amount}`} employeeId={employeeId} amount={form.amount} onInvalidated={()=>setForm(current=>({...current,confirmed:false}))}/>:null}
 <label className="block text-sm font-bold">Bonus review evidence<textarea required minLength={20} className={workforceInput} rows={2} value={form.source} onChange={e=>set('source',e.target.value)}/></label>
 <label className="flex gap-2 text-sm"><input required type="checkbox" checked={form.confirmed} onChange={e=>setForm(current=>({...current,confirmed:e.target.checked}))}/>I verified the annual bonus classification and payroll tax treatment.</label>
 <button disabled={busy||!form.confirmed} className={workforceButton}>Record annual bonus</button>
 </form>{error?<p role="alert" className="mt-3 text-red-700">{error}</p>:null}{message?<p role="status" className="mt-3 text-emerald-700">{message}</p>:null}</section>
}
