import {useState} from 'react'
import {adminApiRequest,getApiUrl} from '../../utils/api'
import {getPayrollEmployeeSession} from '../../utils/employeePayrollApi'
type Enrollment={id:string;revision:number;current:boolean;createdAt:string;holderName:string;accountType:string;accountLast4:string;mode:string;status:string;attempts:number;completionBlockedReason:string|null;operations:Array<{id:string;stage:string;attempt:number;status:string;verificationStatus:string|null;observedAt:string|null}>}
type History={items:Enrollment[];nextCursor:number|null}
const stages:Record<string,string>={COUNTERPARTY:'Account holder',ACCOUNT:'Bank account',START:'Verification deposits',COMPLETE:'Deposit amounts'}
export default function BankEnrollmentHistory({employeeId}:{employeeId?:number}){
 const [data,setData]=useState<History|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const path=employeeId?`/api/admin/payroll/employees/${employeeId}/bank-enrollment`:'/api/payroll/employee/bank-enrollment'
 const request=async(suffix:string,body?:unknown)=>{
  const options={method:body?'POST':'GET',...(body?{body:JSON.stringify(body)}:{})}
  const response=employeeId?await adminApiRequest(path+suffix,options):await fetch(getApiUrl()+path+suffix,{...options,headers:{Authorization:`Bearer ${getPayrollEmployeeSession()||''}`,'Content-Type':'application/json'}})
  const json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to review enrollment history.');return json.data
 }
 const load=async(more=false)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{const next:History=await request(`/history${more&&data?.nextCursor?`?beforeRevision=${data.nextCursor}`:''}`);setData(previous=>more&&previous?{...next,items:[...previous.items,...next.items]}:next)}catch(e){setError(e instanceof Error?e.message:'Unable to load enrollment history.')}finally{setBusy(false)}}
 const recover=async(enrollmentId:string,operationId:string)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{const result=await request('/recover',{enrollmentId,operationId});setData(await request('/history'));setNotice(`Status checked: ${(result.verificationStatus||result.status).replaceAll('_',' ')}. Refresh current enrollment before continuing verification or linking.`)}catch(e){setError(e instanceof Error?e.message:'Unable to recover enrollment.')}finally{setBusy(false)}}
 return <section aria-label="Bank enrollment history" className="space-y-3 rounded border p-3"><h3 className="font-bold">Bank enrollment history</h3><p>Review earlier accounts and check saved operations. Status checks do not send deposits or change wage authorization.</p><button type="button" className="font-bold underline" disabled={busy} onClick={()=>void load()}>Review enrollment history</button>{error?<p role="alert" className="text-red-700">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}{data?.items.length===0?<p>No bank enrollments saved.</p>:null}{data?.items.map(item=><article key={item.id} className="space-y-2 rounded border p-3"><p className="font-bold">{item.holderName} · {item.accountType} ending {item.accountLast4}</p><p>{item.current?'Current enrollment':'Previous enrollment'} · {new Date(item.createdAt).toLocaleDateString()} · {item.mode}</p><p>{item.status.replaceAll('_',' ')} · {item.attempts} verification attempts</p>{item.completionBlockedReason?<p>{item.completionBlockedReason==='EXPIRED'?'The verification completion window has expired.':'The verification attempt limit has been reached.'} Status checks remain available.</p>:null}{item.operations.length===0?<p>No provider operations started.</p>:item.operations.map(operation=><div key={operation.id} className="border-t pt-2"><p>{stages[operation.stage]||operation.stage}{operation.stage==='COMPLETE'?` attempt ${operation.attempt}`:''}: {(operation.verificationStatus||operation.status).replaceAll('_',' ')}</p>{operation.observedAt?<p>Last checked {new Date(operation.observedAt).toLocaleString()}</p>:<p>No response retained.</p>}<button type="button" disabled={busy} className="font-bold underline" onClick={()=>void recover(item.id,operation.id)}>Check {stages[operation.stage]?.toLowerCase()||'operation'} status{operation.stage==='COMPLETE'?` ${operation.attempt}`:''}</button></div>)}</article>)}{data?.nextCursor?<button type="button" disabled={busy} className="font-bold underline" onClick={()=>void load(true)}>Load older enrollments</button>:null}</section>
}
