import {useEffect,useId,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Review={id:string;revision:number;created_at:string;review:{disposition:string;carrier:string;reference:string;coverageStart:string|null;coverageEnd:string|null}}
type Row={employeeId:string;employeeName:string;onboardingCycle:number;planId:string;planName:string;month:string;employmentStatus:string;sourceFingerprint:string|null;status:string;employeeCollectedCents:number;payrolls:{runId:number;paymentDate:string}[];decisions:{effectiveOn:string;disposition:string;selection:{optionLabel:string;employeeCostCents:number;employerCostCents:number}|null}[];current:Review|null;history:Review[]}
type Model={month:string;rows:Row[]}
const key=(row:Row)=>`${row.employeeId}:${row.onboardingCycle}:${row.planId}`
const money=(cents:number)=>(cents/100).toLocaleString('en-US',{style:'currency',currency:'USD'})
async function request(path:string,body?:object){const response=await adminApiRequest(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),json=await response.json();if(!response.ok||!json.success)throw Object.assign(new Error(json.message||'Unable to review monthly coverage.'),{status:response.status});return json.data}
function CoverageRow({row,disabled,onBusy,onSaved}:{row:Row;disabled:boolean;onBusy:(busy:boolean)=>void;onSaved:()=>Promise<Model>}){
 const suggestedStart=[`${row.month}-01`,row.decisions.filter(d=>['ENROLLED','ENROLLED_EMPLOYER_FUNDED'].includes(d.disposition)&&d.selection).map(d=>d.effectiveOn).sort()[0]||`${row.month}-01`].sort().at(-1)!
 const id=useId(),[basis,setBasis]=useState(row),[carrier,setCarrier]=useState(row.current?.review.carrier||''),[disposition,setDisposition]=useState('COVERED'),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [start,setStart]=useState(row.current?.review.coverageStart||suggestedStart),[end,setEnd]=useState(row.current?.review.coverageEnd||new Date(Date.UTC(Number(row.month.slice(0,4)),Number(row.month.slice(5)),0)).toISOString().slice(0,10)),pending=useRef<{body:string;key:string}|null>(null)
 const currentDisposition=row.sourceFingerprint?disposition:'RETRACTED'
 const canReview=!!row.sourceFingerprint||!!row.current&&row.current.review.disposition!=='RETRACTED'
 const stale=basis.sourceFingerprint!==row.sourceFingerprint||basis.current?.id!==row.current?.id
 const save=async()=>{setBusy(true);onBusy(true);setError('');try{
  const input={month:basis.month,employeeId:basis.employeeId,onboardingCycle:basis.onboardingCycle,planId:basis.planId,sourceFingerprint:basis.sourceFingerprint,expectedRevision:basis.current?.revision||0,carrier,disposition:currentDisposition,coverageStart:start,coverageEnd:end,reference,confirmed},body=JSON.stringify(input)
  if(pending.current?.body!==body)pending.current={body,key:crypto.randomUUID()}
  await request('/api/admin/payroll/benefit-coverage',{...input,requestKey:pending.current.key});const next=await onSaved(),current=next.rows.find(item=>key(item)===key(row));if(current)setBasis(current);setDisposition('COVERED');setReference('');setConfirmed(false);pending.current=null
 }catch(e){setError(e instanceof Error?e.message:'Unable to retain coverage review.');if(e instanceof Error&&'status' in e&&e.status===409)setConfirmed(false)}finally{setBusy(false);onBusy(false)}}
 return <article className="space-y-3 rounded-lg border p-3"><h4 className="font-bold">{row.employeeName} · {row.planName} · Employment cycle {row.onboardingCycle}</h4><p>{row.employmentStatus} · {row.status.replaceAll('_',' ')}</p>
  <p>{row.payrolls.length?`Finalized payroll: ${row.payrolls.map(pay=>`#${pay.runId} (${pay.paymentDate})`).join(', ')}`:'No finalized payroll in this month.'} Employee contributions collected for this plan: {money(row.employeeCollectedCents)}. These employee/plan totals span employment cycles; do not add them again across cycle rows.</p>
  <p>Enrollment and carrier coverage are separate from wage deductions. No wages or a withdrawn deduction authorization does not cancel insurance or establish an unpaid balance.</p>
  <details><summary className="cursor-pointer font-bold">Retained hiring benefits decisions</summary>{row.decisions.map((decision,index)=><p key={`${decision.effectiveOn}:${index}`}>{decision.effectiveOn} · {decision.disposition.replaceAll('_',' ')}{decision.selection?` · ${decision.selection.optionLabel} · Published employee ${money(decision.selection.employeeCostCents)}/month, employer ${money(decision.selection.employerCostCents)}/month`:''}</p>)}</details>
  {stale?<div role="alert"><p>Coverage evidence or another review changed. Your draft is preserved; review the current facts before saving.</p><button type="button" disabled={disabled||busy} onClick={()=>{setBasis(row);setConfirmed(false)}} className="rounded border px-3 py-2 font-bold">Use current coverage evidence</button></div>:null}
  {error?<p role="alert">{error}</p>:null}
  {!row.sourceFingerprint?<p>{canReview?'This plan no longer has a current enrolled hiring decision. Review the changed hiring record and retract an incorrect monthly review below.':'The earlier monthly review was retracted. Its history remains available. A new coverage review requires a current enrolled hiring decision in People & onboarding.'}</p>:null}
  {canReview?<fieldset disabled={disabled||busy||stale} className="space-y-3"><legend className="font-bold">Verify this month’s carrier coverage</legend>
   <label htmlFor={`${id}-decision`} className="block">Monthly coverage decision</label><select id={`${id}-decision`} value={currentDisposition} onChange={e=>{setDisposition(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2">{row.sourceFingerprint?<><option value="COVERED">Carrier confirms coverage</option><option value="NOT_COVERED">Carrier confirms no coverage</option></>:null}{row.current&&row.current.review.disposition!=='RETRACTED'?<option value="RETRACTED">Retract an incorrect review</option>:null}</select>
   <label htmlFor={`${id}-carrier`} className="block">Coverage carrier name</label><input id={`${id}-carrier`} value={carrier} onChange={e=>{setCarrier(e.target.value);setConfirmed(false)}} maxLength={200} className="block w-full rounded border p-2"/>
   {currentDisposition==='COVERED'?<><label htmlFor={`${id}-start`} className="block">Actual coverage start in this month</label><input id={`${id}-start`} type="date" value={start} onChange={e=>{setStart(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2"/><label htmlFor={`${id}-end`} className="block">Actual coverage end in this month</label><input id={`${id}-end`} type="date" value={end} onChange={e=>{setEnd(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2"/></>:null}
   <label htmlFor={`${id}-reference`} className="block">Carrier coverage verification reference</label><textarea id={`${id}-reference`} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} maxLength={2000} className="block w-full rounded border p-2"/>
   <label htmlFor={`${id}-confirm`} className="flex items-start gap-2"><input id={`${id}-confirm`} type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I verified this month’s actual carrier coverage and retained supporting evidence. This does not authorize payroll deductions or payment.</span></label>
   <button type="button" disabled={!confirmed||carrier.trim().length<2||reference.trim().length<12||!basis.sourceFingerprint&&currentDisposition!=='RETRACTED'} onClick={()=>void save()} className="rounded border px-3 py-2 font-bold">Retain monthly coverage review</button>
  </fieldset>:null}
  {row.history.length?<details><summary className="cursor-pointer font-bold">Monthly coverage review history</summary>{row.history.map(review=><p key={review.id} className="break-words">Revision {review.revision} · {review.review.disposition.replaceAll('_',' ')} · {review.review.carrier} · {review.review.coverageStart&&review.review.coverageEnd?`${review.review.coverageStart} through ${review.review.coverageEnd} · `:''}{review.review.reference} · {new Date(review.created_at).toLocaleString()}</p>)}</details>:null}
 </article>
}
export default function BenefitCoverageLedger(){
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7)),[model,setModel]=useState<Model|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refreshIssue,setRefreshIssue]=useState(''),[message,setMessage]=useState('')
 const [requested,setRequested]=useState(false)
 const path=`/api/admin/payroll/benefit-coverage?${new URLSearchParams({month})}`
 useEffect(()=>{if(!requested||busy)return;let live=true,inFlight=false;const timer=setInterval(()=>{if(inFlight)return;inFlight=true;void request(path).then(data=>{if(live){setModel(data);setRefreshIssue('');setError('')}}).catch(()=>{if(live)setRefreshIssue('Coverage could not refresh. Retained facts may be outdated; automatic refresh will retry.')}).finally(()=>{inFlight=false})},30000);return()=>{live=false;clearInterval(timer)}},[path,busy,requested])
 const load=async()=>{setRequested(true);setBusy(true);setModel(null);setError('');setMessage('');setRefreshIssue('');try{setModel(await request(path))}catch(e){setError(e instanceof Error?e.message:'Unable to load coverage.')}finally{setBusy(false)}}
 const saved=async()=>{const data=await request(path);setModel(data);setRefreshIssue('');setError('');setMessage('Monthly carrier coverage review retained. Reload carrier invoices before matching this evidence.');return data}
 return <section aria-label="Monthly benefit coverage ledger" className="space-y-3 text-sm"><p>Review enrolled employees even before their first paycheck or during a no-pay month. Confirm actual covered dates with the carrier; published premiums are not invoice charges.</p><label className="block font-bold">Benefit coverage month<input type="month" value={month} disabled={busy} onChange={e=>{setMonth(e.target.value);setRequested(false);setModel(null);setMessage('');setError('');setRefreshIssue('')}} className="mt-1 block rounded border p-2"/></label><button type="button" disabled={busy||!month} onClick={()=>void load()} className="rounded border px-3 py-2 font-bold">{model?'Reload coverage and discard drafts':'Load monthly coverage'}</button>
  {error?<p role="alert">{error}</p>:null}{refreshIssue?<p role="alert">{refreshIssue}</p>:null}{message?<p role="status">{message}</p>:null}
  {model&&!model.rows.length?<p>No retained enrolled benefit plans for this month.</p>:null}{model?.rows.map(row=><CoverageRow key={key(row)} row={row} disabled={busy||!!refreshIssue} onBusy={setBusy} onSaved={saved}/>)}</section>
}
