import {useState} from 'react'
import {workforceApi,type BenefitDeductionStatus} from '../../utils/workforceApi'
export default function BenefitsDeductionAuthorization({data,cycle,readOnly,busy,act}:{data:BenefitDeductionStatus;cycle:number;readOnly:boolean;busy:boolean;act:(work:()=>Promise<unknown>,message:string)=>Promise<void>}){
 const [withdrawConfirmed,setWithdrawConfirmed]=useState(false)
 const [signature,setSignature]=useState(''),[confirmed,setConfirmed]=useState(false),[requestKey]=useState(()=>crypto.randomUUID())
 if(!data.required&&!data.saved)return null
 return <section aria-label="Benefit deduction authorization" className="mt-4 space-y-3 rounded-xl border border-slate-200 p-3 text-sm"><h4 className="font-bold">Separate benefit deduction authorization</h4>
 {data.status==='WITHDRAWN'?<p role="status" className="font-semibold text-amber-900">You withdrew this authorization. Further benefit collection requires a new signature. Your admin must review approved payroll; submitted payments and completed deductions are not reversed.</p>:null}
 {data.saved&&data.status==='CURRENT'&&!readOnly?<div className="space-y-2 rounded border p-3"><label className="flex gap-2"><input type="checkbox" checked={withdrawConfirmed} onChange={e=>setWithdrawConfirmed(e.target.checked)}/>I withdraw the displayed benefit deduction authorization. This does not cancel insurance coverage or reverse completed deductions.</label><button type="button" disabled={busy||!withdrawConfirmed} className="font-bold underline disabled:opacity-40" onClick={()=>void act(()=>workforceApi.withdrawBenefitsDeduction({confirmed:withdrawConfirmed,requestKey,authorizationRequestKey:data.saved!.requestKey,onboardingCycle:cycle}),'Deduction authorization withdrawn. Your hiring admin has a review task.')}>Withdraw deduction authorization</button></div>:null}
 {data.required&&data.status!=='CURRENT'?<p className="font-semibold text-amber-900">{data.proposal?'Employee signature required for the current deduction terms.':'Complete the current benefits enrollment review to prepare deduction terms.'}</p>:null}
 {data.saved?<div className="space-y-2"><p>Signed by {data.saved.signature} · {new Date(data.saved.signedAt).toLocaleString()}</p>{data.status==='CURRENT'?<p className="font-semibold text-emerald-800">Current deduction terms authorized.</p>:<p>{data.required?'Retained prior authorization; current terms require review.':'Retained authorization for prior coverage.'}</p>}<details><summary className="cursor-pointer font-bold">Saved deduction authorization</summary><p className="mt-2 whitespace-pre-wrap">{data.saved.proposal.terms}</p></details><button type="button" className="font-bold underline" onClick={()=>{const saved=data.saved!;const url=URL.createObjectURL(new Blob([`${saved.proposal.terms}\n\nSigned by: ${saved.signature}\nSigned at: ${saved.signedAt}\n`],{type:'text/plain;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`benefit-deduction-authorization-${saved.requestKey}.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Download deduction authorization</button></div>:null}
 {data.proposal&&data.status!=='CURRENT'?<><p tabIndex={0} aria-label="Current deduction terms" className="max-h-96 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-3">{data.proposal.terms}</p>{!readOnly?<form className="space-y-3" onSubmit={e=>{e.preventDefault();void act(()=>workforceApi.authorizeBenefitsDeduction({signature,confirmed,requestKey,onboardingCycle:cycle,proposalFingerprint:data.proposal!.fingerprint}),'Benefit deduction authorization signed and saved.')}}><label className="block font-semibold">Deduction authorization signature<input required maxLength={200} value={signature} onChange={e=>{setSignature(e.target.value);setConfirmed(false)}} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="flex items-start gap-2"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I expressly authorize only the wage deductions described in this separate statement.</label><button disabled={busy} className="rounded-xl bg-slate-950 px-4 py-2.5 font-bold text-white disabled:opacity-40">Sign deduction authorization</button></form>:null}</>:null}
 </section>
}
