import {useCallback,useEffect,useId,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Source={fingerprint:string;employeeName:string;paymentDate:string;terminationDate:string;monthlyCents:number;issues:string[];authorization:{signature:string;signedAt:string;proposal?:{terms?:string}}|null;coverage:{planId:string;planName:string;monthlyCents:number;review:{coverageStart:string;coverageEnd:string}|null}[]}
type Model={source:Source;status:string;history:{id:string;revision:number;review:{disposition:string;reference:string};created_at:string}[]}
const money=(cents:number)=>(cents/100).toLocaleString('en-US',{style:'currency',currency:'USD'})
async function request(path:string,body?:string){const r=await adminApiRequest(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body}:undefined),b=await r.json();if(!r.ok||!b.success)throw Object.assign(new Error(b.message||'Unable to review benefit collection.'),{status:r.status});return b.data}
export default function BenefitContinuationReview({employeeId,employeeName,month}:{employeeId:string;employeeName:string;month:string}){
 const id=useId(),path=`/api/admin/payroll/employees/${encodeURIComponent(employeeId)}/benefit-continuation`
 const [date,setDate]=useState(''),[data,setData]=useState<Model|null>(null),[basis,setBasis]=useState<Model|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[reference,setReference]=useState(''),[decision,setDecision]=useState(''),[confirmed,setConfirmed]=useState(false),[pending,setPending]=useState<string|null>(null)
 const read=useCallback(()=>request(`${path}?${new URLSearchParams({paymentDate:date})}`) as Promise<Model>,[path,date])
 const loaded=!!data
 const stale=!!data&&!!basis&&(data.source.fingerprint!==basis.source.fingerprint||data.history[0]?.id!==basis.history[0]?.id)
 const load=async()=>{setBusy(true);setError('');try{const next=await read();setData(next);setBasis(next);setConfirmed(false)}catch(e){setError(e instanceof Error?e.message:'Unable to load collection review.')}finally{setBusy(false)}}
 useEffect(()=>{if(!loaded||busy)return;let live=true,inFlight=false;const timer=setInterval(()=>{if(inFlight)return;inFlight=true;void read().then(next=>{if(live){setData(next);setError('')}}).catch(()=>{if(live)setError('Collection evidence could not refresh. Reload before saving.')}).finally(()=>{inFlight=false})},30000);return()=>{live=false;clearInterval(timer)}},[loaded,busy,read])
 const save=async()=>{if(!basis)return;setBusy(true);setError('');setMessage('');const body=pending||JSON.stringify({paymentDate:basis.source.paymentDate,sourceFingerprint:basis.source.fingerprint,expectedRevision:basis.history[0]?.revision||0,disposition:decision,reference,confirmed,requestKey:crypto.randomUUID()});setPending(body)
  try{await request(path,body);setPending(null);setConfirmed(false);setReference('');setDecision('');setMessage('Dated benefit collection review retained. Recalculate payroll before approval.');const next=await read();setData(next);setBasis(next)}catch(e){setError(e instanceof Error?e.message:'Unable to retain collection review.');if(e instanceof Error&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500){setPending(null);setConfirmed(false);try{setData(await read())}catch{/* Keep the draft and error visible. */}}}finally{setBusy(false)}}
 return <section aria-label={`Separated employee benefit collection ${employeeName}`} className="space-y-3 rounded-lg border border-slate-300 p-3">
  <h4 className="font-bold">Final-pay benefit collection · {employeeName}</h4>
  <p>Review the existing signed monthly deduction for a specific regular payment date. This does not change coverage, create a new employee authorization, collect arrears, or prorate premiums.</p>
  <label htmlFor={`${id}-date`} className="block">Final-pay payment date</label><input id={`${id}-date`} type="date" min={`${month}-01`} max={new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5)),0)).toISOString().slice(0,10)} value={date} disabled={busy||!!pending} onChange={e=>{setDate(e.target.value);setData(null);setBasis(null);setConfirmed(false);setMessage('');setError('')}} className="block rounded border p-2"/>
  <button type="button" disabled={busy||!!pending||!date||!date.startsWith(month)} onClick={()=>void load()} className="rounded border px-3 py-2">Load final-pay collection review</button>
  {error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}
  {pending?<button type="button" disabled={busy} onClick={()=>void save()} className="rounded border px-3 py-2">Retry original collection review</button>:null}
  {data&&basis?<><p>Review status: {data.status.replaceAll('_',' ')}. Separation: {data.source.terminationDate}. Signed monthly total: {money(data.source.monthlyCents)}.</p>
   {data.source.issues.length?<ul role="alert" className="list-disc pl-5">{data.source.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:null}
   {data.source.authorization?<details><summary>Read retained employee deduction authorization</summary><p>Signed by {data.source.authorization.signature} · {new Date(data.source.authorization.signedAt).toLocaleString()}</p><p className="whitespace-pre-wrap break-words">{data.source.authorization.proposal?.terms||'Retained authorization terms need reconciliation.'}</p></details>:null}
   <ul>{data.source.coverage.map(item=><li key={item.planId}>{item.planName}: {money(item.monthlyCents)}{item.review?` · Carrier coverage ${item.review.coverageStart} through ${item.review.coverageEnd}`:' · Carrier evidence required'}</li>)}</ul>
   {stale?<div role="alert"><p>Collection evidence changed. Your draft is preserved; review the current evidence before saving.</p><button type="button" disabled={busy||!!pending} onClick={()=>{setBasis(data);setConfirmed(false)}} className="rounded border px-3 py-2">Use current collection evidence</button></div>:null}
   <fieldset disabled={busy||!!pending||stale||!!error} className="space-y-3"><legend className="font-bold">Administrator collection decision</legend>
    <label htmlFor={`${id}-decision`} className="block">Final-pay collection decision</label><select id={`${id}-decision`} value={decision} onChange={e=>{setDecision(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2"><option value="">Choose decision</option><option value="COLLECT_SIGNED_MONTHLY" disabled={!!data.source.issues.length}>Reviewed signed monthly collection</option><option value="SUSPENDED">Suspend collection pending further review</option></select>
    <label htmlFor={`${id}-reference`} className="block">Final-pay collection review reference</label><textarea id={`${id}-reference`} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} maxLength={2000} className="block w-full rounded border p-2"/>
    <label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I reviewed the separation, actual covered dates, full monthly amount due, employee’s signed authorization and applicable wage-deduction requirements for this payment. This admin decision does not replace employee consent.</span></label>
    <button type="button" disabled={!confirmed||!decision||reference.trim().length<20||decision==='COLLECT_SIGNED_MONTHLY'&&!!data.source.issues.length} onClick={()=>void save()} className="rounded border px-3 py-2">Retain final-pay collection review</button>
   </fieldset>
   {data.history.length?<details><summary>Final-pay collection review history</summary>{data.history.map(row=><p key={row.id} className="break-words">Revision {row.revision} · {row.review.disposition.replaceAll('_',' ')} · {row.review.reference} · {new Date(row.created_at).toLocaleString()}</p>)}</details>:null}
  </>:null}
 </section>
}
