import {useEffect,useId,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type History={can_release:boolean;attempts:{id:number;status:string;message:string;created_at:string}[];journals:{id:string;payload:{TxnDate:string;DocNumber:string};result:{status:string;journalId?:string}|null}[];id:string;reference:string;created_at:string;cancelled_at:string|null;cancellation_reference:string|null;claimed:boolean}
export default function CarrierSettlementAuthorization({paymentId,fingerprint,onSaved}:{paymentId:string;fingerprint?:string;onSaved:()=>void}){
 const inputId=useId(),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(''),[key,setKey]=useState(()=>crypto.randomUUID()),[history,setHistory]=useState<History[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[refreshIssue,setRefreshIssue]=useState('')
 const path=`/api/admin/payroll/carrier-payment-authorizations/${paymentId}/settlement-authorizations`
 const request=async(url:string,body?:object)=>{const r=await adminApiRequest(url,body?{method:'POST',body:JSON.stringify(body)}:undefined),j=await r.json();if(!r.ok)throw new Error(j.message||'Unable to retain settlement review.');return j.data}
 const active=!!history?.some(a=>!a.cancelled_at)
 useEffect(()=>{if(!active||busy)return;let stopped=false,inFlight=false;const timer=setInterval(()=>{if(inFlight)return;inFlight=true;void(async()=>{try{const r=await adminApiRequest(path),j=await r.json();if(!r.ok)throw new Error();if(!stopped){setHistory(j.data.history);setRefreshIssue('')}}catch{if(!stopped)setRefreshIssue('Automatic settlement history refresh failed. Reload history to check its current outcome.')}finally{inFlight=false}})()},30000);return()=>{stopped=true;clearInterval(timer)}},[active,busy,path])
 const load=async()=>setHistory((await request(path)).history)
 const run=async(work:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await work()}catch(e){setError(e instanceof Error?e.message:'Unable to update settlement authorization.')}finally{setBusy(false);setConfirmed('')}}
 return <section aria-label="Carrier settlement authorization" className="space-y-2">
  <button type="button" disabled={busy} onClick={()=>void run(load)} className="rounded-lg border px-3 py-2 font-bold">Load settlement authorization history</button>
  <label htmlFor={inputId} className="block font-bold">Settlement authorization or cancellation reference</label><textarea id={inputId} value={reference} disabled={busy} maxLength={2000} onChange={e=>{setReference(e.target.value);setConfirmed('');setKey(crypto.randomUUID())}} rows={3} className="block w-full rounded-lg border p-2"/>
  {fingerprint?<><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed===fingerprint} disabled={busy} onChange={e=>setConfirmed(e.target.checked?(fingerprint||''):'')}/><span>I authorize automatic posting of the reviewed carrier bank journals and verified that these withdrawals have not been recorded separately.</span></label><button type="button" disabled={busy||confirmed!==fingerprint||reference.trim().length<12} onClick={()=>void run(async()=>{await request(path,{confirmed:true,autoPost:true,fingerprint,requestKey:key,reference});await load();onSaved();setKey(crypto.randomUUID());setMessage('Settlement authorization retained. Posting status is shown in its history.')})} className="rounded-lg bg-slate-900 px-3 py-2 font-bold text-white disabled:opacity-50">Authorize carrier settlement posting</button></>:<p>Review fresh bank settlement evidence before authorizing posting.</p>}
  {refreshIssue?<p role="alert" className="text-amber-800">{refreshIssue}</p>:null}{error?<p role="alert" className="text-red-700">{error}</p>:null}{message?<p role="status">{message}</p>:null}
  {history?<div className="space-y-2">{history.length?history.map(a=><div key={a.id} className="rounded-lg border p-2"><p>{a.cancelled_at?'Settlement authorization cancelled':a.claimed?(a.journals.length&&a.journals.every(j=>j.result?.status==='SYNCED')?'Settlement journals confirmed in QuickBooks':'Settlement posting claimed — recover outcome'):'Settlement authorized — posting not started'}</p><p className="break-words">{a.reference}</p><p>{new Date(a.created_at).toLocaleString()}</p>{a.can_release?<div className="space-y-2"><p>The completed attempt sent no journal-create request. Verify that every journal is still absent before cancelling this attempt.</p><button type="button" disabled={busy||reference.trim().length<12} onClick={()=>void run(async()=>{await request(`/api/admin/payroll/carrier-settlement-authorizations/${a.id}/release-unsent`,{confirmed:true,reference});await load();onSaved();setKey(crypto.randomUUID());setMessage('Proven-unsent settlement cancelled. Review current bank evidence before authorizing again.')})} className="rounded-lg border px-3 py-2 font-bold">Cancel proven-unsent settlement</button></div>:null}{a.journals.map(j=><p key={j.id} className="break-words">{j.payload.TxnDate} · {j.result?.status==='SYNCED'?`QuickBooks journal ${j.result.journalId}`:(j.result?.status||'Outcome pending').replaceAll('_',' ')}</p>)}{a.attempts[0]?<p className="break-words">Last automatic check: {a.attempts[0].message}</p>:null}{!a.cancelled_at?<button type="button" disabled={busy} onClick={()=>void run(async()=>{await request(`/api/admin/payroll/carrier-settlement-authorizations/${a.id}/post`,{confirmed:true,action:a.claimed?'RECOVER':'POST'});await load();onSaved()})} className="rounded-lg border px-3 py-2 font-bold">{a.claimed?'Recover settlement journals':'Post authorized settlement journals'}</button>:null}{a.cancelled_at?<p className="break-words">{a.cancellation_reference}</p>:!a.claimed?<button type="button" disabled={busy||reference.trim().length<12} onClick={()=>void run(async()=>{await request(`/api/admin/payroll/carrier-settlement-authorizations/${a.id}/cancel`,{confirmed:true,reference});await load();onSaved();setMessage('Settlement authorization cancelled before posting.');setKey(crypto.randomUUID())})} className="rounded-lg border px-3 py-2 font-bold">Cancel settlement authorization</button>:null}</div>):<p>No settlement authorizations retained.</p>}</div>:null}
 </section>
}
