import {useCallback,useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Advice={fingerprint:string;subject:string;text:string}
type Record={id:string;revision:number;action:string;createdAt:string;reference:string;channel?:string;recipient?:string;destination?:string;deliveredAt?:string;advice:Advice}
type Model={revision:number;status:string;advice:Advice|null;issue:string|null;history:Record[]}
export default function CarrierAlternateDelivery({paymentId}:{paymentId:string}){
 const [requested,setRequested]=useState(false)
 const [model,setModel]=useState<Model|null>(null),[basis,setBasis]=useState<Model|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refreshIssue,setRefreshIssue]=useState(''),[message,setMessage]=useState('')
 const [action,setAction]=useState('RECORD'),[channel,setChannel]=useState('CARRIER_PORTAL'),[recipient,setRecipient]=useState(''),[destination,setDestination]=useState(''),[deliveredAt,setDeliveredAt]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),pending=useRef<{body:string;key:string}|null>(null)
 const base=`/api/admin/payroll/carrier-payment-authorizations/${paymentId}/alternate-delivery`
 const read=useCallback(async()=>{const response=await adminApiRequest(base),body=await response.json();if(!response.ok||!body.success)throw new Error(body.message||'Unable to load delivery evidence.');return body.data as Model},[base])
 useEffect(()=>{if(!requested||busy)return;let live=true,inFlight=false;const timer=setInterval(()=>{if(inFlight)return;inFlight=true;void read().then(data=>{if(live){setModel(data);setBasis(current=>current??data);setRefreshIssue('');setError('')}}).catch(()=>{if(live)setRefreshIssue('Delivery history could not refresh. Automatic refresh will retry.')}).finally(()=>{inFlight=false})},30000);return()=>{live=false;clearInterval(timer)}},[read,requested,busy])
 const load=async()=>{setRequested(true);setBusy(true);setError('');try{const data=await read();setModel(data);setBasis(data);setConfirmed(false);setRefreshIssue('')}catch(e){setError(e instanceof Error?e.message:'Unable to load delivery history.')}finally{setBusy(false)}}
 const stale=!!basis&&!!model&&(basis.revision!==model.revision||basis.advice?.fingerprint!==model.advice?.fingerprint),selectedAction=model?.advice?action:'RETRACT',canRetract=model?.history[0]?.action==='RECORD'
 const save=async()=>{if(!basis)return;setBusy(true);setError('');setMessage('');try{
  const input={action:selectedAction,expectedRevision:basis.revision,adviceFingerprint:basis.advice?.fingerprint||null,...(selectedAction==='RECORD'?{channel,recipient,destination,deliveredAt:new Date(deliveredAt).toISOString()}:{}),reference,confirmed},serialized=JSON.stringify(input)
  if(pending.current?.body!==serialized)pending.current={body:serialized,key:crypto.randomUUID()}
  const response=await adminApiRequest(base,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,requestKey:pending.current.key})}),body=await response.json();if(!response.ok||!body.success)throw new Error(body.message||'Unable to retain delivery review.')
  const data=await read();setModel(data);setBasis(data);setReference('');setConfirmed(false);setAction('RECORD');pending.current=null;setRefreshIssue('');setMessage('Alternate delivery review retained. Email notices and carrier payment application remain separate.')
 }catch(e){setError(e instanceof Error?e.message:'Unable to retain delivery review.')}finally{setBusy(false)}}
 return <details className="rounded-lg border p-3"><summary className="cursor-pointer font-bold">Alternate remittance delivery</summary><section aria-label="Alternate remittance delivery" className="mt-3 space-y-3 text-sm"><p>Retain evidence that the exact advice was delivered through a carrier portal, postal delivery or in person. A mailing label or upload draft is not proof of delivery. Manage any pending email notice separately.</p><button type="button" disabled={busy} onClick={()=>void load()} className="rounded border px-3 py-2 font-bold">{model?'Reload alternate delivery evidence':'Review alternate delivery evidence'}</button>
 {error?<p role="alert">{error}</p>:null}{refreshIssue?<p role="alert">{refreshIssue}</p>:null}{message?<p role="status">{message}</p>:null}
 {model?<><p>Delivery evidence: {model.status.replaceAll('_',' ')}</p>{model.issue?<p>{model.issue}</p>:null}{stale?<p role="alert">Delivery or bank evidence changed. Your draft is preserved; reload current evidence before saving.</p>:null}
 {model.advice||canRetract?<fieldset disabled={busy||stale||!!refreshIssue} className="space-y-3"><legend className="font-bold">Retain an actual delivery or retract incorrect evidence</legend><label className="block">Delivery review action<select value={selectedAction} onChange={e=>{setAction(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2">{model.advice?<option value="RECORD">Record actual delivery</option>:null}{canRetract?<option value="RETRACT">Retract incorrect delivery evidence</option>:null}</select></label>
 {selectedAction==='RECORD'?<><details><summary className="font-bold">Exact advice for this delivery</summary><p className="whitespace-pre-wrap break-words">{basis?.advice?.text}</p></details><label className="block">Delivery channel<select value={channel} onChange={e=>{setChannel(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2"><option value="CARRIER_PORTAL">Carrier portal receipt</option><option value="POSTAL_DELIVERY">Confirmed postal delivery</option><option value="IN_PERSON">In-person receipt</option></select></label><label className="block">Verified recipient<input value={recipient} onChange={e=>{setRecipient(e.target.value);setConfirmed(false)}} maxLength={200} className="block w-full rounded border p-2"/></label><label className="block">Verified delivery destination<input value={destination} onChange={e=>{setDestination(e.target.value);setConfirmed(false)}} maxLength={1000} className="block w-full rounded border p-2"/></label><label className="block">Actual delivery time<input type="datetime-local" value={deliveredAt} onChange={e=>{setDeliveredAt(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2"/></label></>:null}
 <label className="block">Delivery evidence or retraction reference<textarea value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} maxLength={2000} className="block w-full rounded border p-2"/></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I verified this delivery evidence or retraction against retained records. This does not establish carrier application of funds or change email notices.</span></label><button type="button" disabled={!confirmed||reference.trim().length<12||selectedAction==='RECORD'&&(!deliveredAt||recipient.trim().length<2||destination.trim().length<4)} onClick={()=>void save()} className="rounded border px-3 py-2 font-bold">Retain alternate delivery review</button></fieldset>:null}
 <details><summary className="font-bold">Alternate delivery history</summary>{model.history.length?model.history.map(row=><article key={row.id} className="mt-3 space-y-1 rounded border p-2"><p>Revision {row.revision} · {row.action} · {new Date(row.createdAt).toLocaleString()}</p>{row.channel?<p>{row.channel.replaceAll('_',' ')} · {row.deliveredAt&&new Date(row.deliveredAt).toLocaleString()}</p>:null}<p className="break-words">{row.recipient} {row.destination}</p><p className="break-words">{row.reference}</p><details><summary>Retained advice</summary><p className="whitespace-pre-wrap break-words">{row.advice.text}</p></details></article>):<p>No alternate delivery records.</p>}</details></>:null}</section></details>
}
