import CarrierPremiumAuthorization,{type PremiumAuthorization} from './CarrierPremiumAuthorization'
import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Check={premiumPreview?:{period:{bookCloseDate:string|null};connectionGeneration:number;fingerprint:string;accounts:{id:string;name:string}[];payload:{TxnDate:string;Line:{Amount:number;Description:string;JournalEntryLineDetail:{PostingType:string;AccountRef:{value:string}}}[]}};realmId:string;environment:string;employeeContributionCents:number;deductionAccountId:string|null;journals:{runId:number;journalId:string}[];checkedAt:string}
export default function CarrierAccountingCheck({invoiceId,current,authorizations,onSaved}:{invoiceId:string;current:boolean;authorizations:PremiumAuthorization[];onSaved:()=>Promise<void>}){
 const [expenseAccount,setExpenseAccount]=useState(''),[carrierAccount,setCarrierAccount]=useState('')
 const [result,setResult]=useState<Check|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const check=async(prepareJournal=false)=>{setBusy(true);setError('');setResult(null);try{const response=await adminApiRequest(`/api/admin/payroll/benefit-carrier-invoices/${invoiceId}/accounting-check`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prepareJournal,expenseAccountId:expenseAccount,carrierAccountId:carrierAccount})}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to verify source payroll accounting');setResult(json.data)}catch(e){setError(e instanceof Error?e.message:'Unable to verify source payroll accounting')}finally{setBusy(false)}}
 return <div className="space-y-2 border-t pt-3"><button type="button" disabled={busy||!current} onClick={()=>void check()} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-50">{busy?'Checking payroll accounting…':'Check payroll accounting'}</button><div className="space-y-2"><label className="block font-semibold">Premium expense account ID<input value={expenseAccount} disabled={busy} onChange={e=>{setExpenseAccount(e.target.value);setResult(null)}} className="mt-1 block w-full rounded-lg border p-2"/></label><label className="block font-semibold">Carrier liability account ID<input value={carrierAccount} disabled={busy} onChange={e=>{setCarrierAccount(e.target.value);setResult(null)}} className="mt-1 block w-full rounded-lg border p-2"/></label><button type="button" disabled={busy||!current||!expenseAccount||!carrierAccount} onClick={()=>void check(true)} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-50">Preview premium journal</button></div>{error?<p role="alert" className="text-red-700">{error}</p>:null}{result&&current?<div className="space-y-1"><p>{result.employeeContributionCents?'Source payroll journals verified against QuickBooks.':'This allocation applies no employee contributions.'}</p><p>Company {result.realmId} · {result.environment}</p>{result.deductionAccountId?<p>Deduction liability account {result.deductionAccountId}</p>:null}{result.journals.map(j=><p key={j.runId}>Payroll #{j.runId} · QuickBooks journal {j.journalId}</p>)}<div>{result.premiumPreview?<section aria-label="Carrier premium journal preview" className="space-y-2 rounded-lg bg-slate-50 p-3"><h5 className="font-bold">Premium journal preview · {result.premiumPreview.payload.TxnDate}</h5><p>{result.premiumPreview.period.bookCloseDate?`QuickBooks books closed through ${result.premiumPreview.period.bookCloseDate}; this journal is dated after that close.`:'No book closing date is configured in the verified QuickBooks accounting preferences.'}</p>{result.premiumPreview.payload.Line.map((line,index)=><p key={index}>{line.JournalEntryLineDetail.PostingType} {line.Amount.toLocaleString('en-US',{style:'currency',currency:'USD'})} · {line.Description}<br/>{result.premiumPreview?.accounts.find(a=>a.id===line.JournalEntryLineDetail.AccountRef.value)?.name||'Payroll deduction liability'} (account {line.JournalEntryLineDetail.AccountRef.value})</p>)}<p>Preview only. No journal has been posted.</p></section>:null}</div><p>Checked {new Date(result.checkedAt).toLocaleString()}. This check does not post a premium journal or pay the carrier.</p></div>:null}<CarrierPremiumAuthorization key={result?.premiumPreview?.fingerprint||'no-preview'} invoiceId={invoiceId} fingerprint={current?result?.premiumPreview?.fingerprint:undefined} expenseAccount={expenseAccount} carrierAccount={carrierAccount} history={authorizations} onSaved={onSaved}/></div>
}
