import {useEffect,useId,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Review={id:number;kind:string;created_at:string;details:{reference:string;applicationDate?:string;appliedCents?:number;unappliedCents?:number;documentIds?:string[]}}
type Model={reconciliationCheckFailed:boolean;reconciliationFailures:{id:number;message:string;attempted_at:string}[];reconciliationHistory:{id:number;created_at:string;assessment:{status:string;checks:{key:string;complete:boolean;message:string}[]}}[];reconciliationCheckedAt:string|null;reconciliation:{status:string;checks:{key:string;complete:boolean;message:string}[]};revision:number;status:string;receiptFingerprint:string|null;receiptStatus:string;amountCents:number;paymentDate:string;earliestBankDate:string;history:Review[];documents:{id:string;filename:string}[]}
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100)
const labels:Record<string,string>={UNREVIEWED:'Carrier application has not been reviewed',RETRACTED:'Latest carrier review was retracted',NEEDS_REVIEW:'Carrier application needs review — bank evidence changed',FULLY_APPLIED:'Admin reviewed full application to this invoice',PARTIALLY_APPLIED:'Admin reviewed partial application to this invoice',UNAPPLIED:'Admin reviewed no application to this invoice'}
export default function CarrierApplication({paymentId,receiptStatus,observedAt}:{paymentId:string;receiptStatus:string;observedAt:string}){
 const field=useId(),[model,setModel]=useState<Model|null>(null),[kind,setKind]=useState('REVIEW'),[date,setDate]=useState(''),[amount,setAmount]=useState(''),[reference,setReference]=useState(''),[documents,setDocuments]=useState<string[]>([]),[confirmed,setConfirmed]=useState(''),[key,setKey]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[refreshIssue,setRefreshIssue]=useState(''),[outdated,setOutdated]=useState(false)
 const path=`/api/admin/payroll/carrier-payment-authorizations/${paymentId}/application`,signature=`${model?.revision}:${model?.receiptStatus}:${receiptStatus}:${observedAt}:${kind}`
 const request=async(body?:object)=>{const r=await adminApiRequest(path,body?{method:'POST',body:JSON.stringify(body)}:undefined),j=await r.json();if(!r.ok)throw new Error(j.message||'Unable to review carrier application.');return j.data}
 const loaded=!!model,revision=model?.revision,bankStatus=model?.receiptStatus
 useEffect(()=>{if(!loaded||busy)return;let stopped=false,inFlight=false;const timer=setInterval(()=>{if(inFlight)return;inFlight=true;void(async()=>{try{const r=await adminApiRequest(path),j=await r.json();if(!r.ok)throw new Error();if(stopped)return;if(j.data.revision!==revision){setOutdated(true);setConfirmed('');setRefreshIssue('A newer carrier review is available. Reload the review before saving; your draft is preserved.')}else{setModel(j.data);setRefreshIssue('');if(j.data.receiptStatus!==bankStatus)setConfirmed('')}}catch{if(!stopped)setRefreshIssue('Automatic carrier review refresh failed. Reload to check the latest evidence.')}finally{inFlight=false}})()},30000);return()=>{stopped=true;clearInterval(timer)}},[loaded,busy,path,revision,bankStatus])
 const load=async()=>{setModel(await request());setOutdated(false);setRefreshIssue('')}
 const invalidate=()=>{setConfirmed('');setMessage('');setKey(crypto.randomUUID())}
 const act=async(work:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');setConfirmed('');try{await work()}catch(e){setError(e instanceof Error?e.message:'Unable to retain carrier review.')}finally{setBusy(false)}}
 const status=model?.history[0]?.kind==='REVIEW'&&receiptStatus!=='BANK_CONFIRMED'?'NEEDS_REVIEW':model?.status||'UNREVIEWED'
 const reconciliationChecks=model?.reconciliation.checks.map(c=>({...c,complete:c.complete&&(!['bank','application'].includes(c.key)||receiptStatus==='BANK_CONFIRMED')}))||[]
 return <section aria-label="Carrier application review" className="space-y-3 rounded-lg border p-3">
  <h5 className="font-bold">Carrier application review</h5><p>Record the carrier statement or acknowledgment showing how this payment was applied. Any remainder is not applied to this invoice; explain its disposition in the reference.</p>
  <button type="button" disabled={busy} onClick={()=>void act(load)} className="rounded-lg border px-3 py-2 font-bold">Load carrier application review</button>
  {refreshIssue?<p role="alert" className="text-amber-800">{refreshIssue}</p>:null}{error?<p role="alert" className="text-red-700">{error}</p>:null}{message?<p role="status">{message}</p>:null}
  {model?<><p>{labels[status]}</p><div aria-label="Carrier payment reconciliation" className="space-y-2 rounded-lg border p-2"><h6 className="font-bold">Payment reconciliation</h6>{model.reconciliationCheckFailed?<p role="alert">Automatic reconciliation needs recovery. A failed check has been retained and will retry automatically.</p>:null}<p>{!outdated&&!refreshIssue&&!model.reconciliationCheckFailed&&reconciliationChecks.every(c=>c.complete)?'Retained payment evidence reconciles':'Payment reconciliation remains open'}</p><ul className="list-disc pl-4">{reconciliationChecks.filter(c=>!c.complete).map(c=><li key={c.key}>{c.message}</li>)}</ul><p>This compares the latest retained bank, carrier review and accounting evidence for this payment. It does not close the entire invoice or perform a fresh provider check.</p>{model.reconciliationCheckedAt?<p>Automatically checked {new Date(model.reconciliationCheckedAt).toLocaleString()}</p>:<p>Automatic assessment is pending.</p>}<details><summary className="cursor-pointer font-bold">Reconciliation history</summary>{model.reconciliationHistory.length?model.reconciliationHistory.map(r=><div key={r.id} className="my-2 border-t pt-2"><p>{r.assessment.status==='RECONCILED'?'Evidence reconciled':'Reconciliation open'} · {new Date(r.created_at).toLocaleString()}</p>{r.assessment.checks.filter(c=>!c.complete).map(c=><p key={c.key}>{c.message}</p>)}</div>):<p>No automatic assessment has been retained yet.</p>}{model.reconciliationFailures.map(f=><div key={`failure-${f.id}`} className="my-2 border-t pt-2"><p>Automatic check failed · {new Date(f.attempted_at).toLocaleString()}</p><p>{f.message}</p></div>)}</details></div><p>Payment amount: {money(model.amountCents)}</p><fieldset disabled={busy||outdated} className="space-y-3">
   <label htmlFor={`${field}-kind`} className="block">Carrier review action</label><select id={`${field}-kind`} value={kind} onChange={e=>{setKind(e.target.value);invalidate()}} className="block w-full rounded-lg border p-2"><option value="REVIEW">Record application</option><option value="RETRACT">Retract review</option></select>
   {kind==='REVIEW'?<><label htmlFor={`${field}-date`} className="block">Carrier evidence date</label><input id={`${field}-date`} type="date" value={date} min={model.earliestBankDate} onChange={e=>{setDate(e.target.value);invalidate()}} className="block w-full rounded-lg border p-2"/><label htmlFor={`${field}-amount`} className="block">Amount applied to this invoice ($)</label><input id={`${field}-amount`} inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);invalidate()}} className="block w-full rounded-lg border p-2"/>{model.documents.length?<div><p>Supporting invoice documents (optional)</p>{model.documents.map(d=><label key={d.id} className="flex items-start gap-2"><input type="checkbox" checked={documents.includes(d.id)} onChange={e=>{setDocuments(old=>e.target.checked?[...old,d.id]:old.filter(id=>id!==d.id));invalidate()}}/><span className="break-words">{d.filename}</span></label>)}</div>:<p>You can attach supporting files in the invoice documents panel.</p>}</>:null}
   <label htmlFor={`${field}-reference`} className="block">Carrier application evidence or retraction reason</label><textarea id={`${field}-reference`} rows={3} maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);invalidate()}} className="block w-full rounded-lg border p-2"/>
   <label className="flex items-start gap-2"><input type="checkbox" checked={confirmed===signature} onChange={e=>setConfirmed(e.target.checked?signature:'')}/><span>I independently reviewed the carrier evidence and confirm this application allocation or retraction, including any amount not applied to this invoice.</span></label>
   <button type="button" disabled={confirmed!==signature||reference.trim().length<12||kind==='RETRACT'&&!model.revision||kind==='REVIEW'&&(receiptStatus!=='BANK_CONFIRMED'||model.receiptStatus!=='BANK_CONFIRMED'||!date||!/^\d+(\.\d{1,2})?$/.test(amount))} onClick={()=>void act(async()=>{await request({confirmed:true,kind,expectedRevision:model.revision,requestKey:key,reference,...(kind==='REVIEW'?{receiptFingerprint:model.receiptFingerprint,applicationDate:date,appliedCents:Math.round(Number(amount)*100),documentIds:documents}:{})});await load();setKey(crypto.randomUUID());setMessage('Carrier application review retained.')})} className="rounded-lg bg-slate-900 px-3 py-2 font-bold text-white disabled:opacity-50">Save carrier application review</button>
  </fieldset><h6 className="font-bold">Retained review history</h6><div className="space-y-2">{model.history.map((r,index)=><div key={r.id} className="rounded-lg border p-2"><p>{index===0?'Latest':'Earlier'} review {r.id} · {r.kind==='RETRACT'?'Retracted':`${money(r.details.appliedCents||0)} applied; ${money(r.details.unappliedCents||0)} not applied to this invoice`}</p>{r.details.applicationDate?<p>Carrier evidence date {r.details.applicationDate}</p>:null}<p className="break-words">{r.details.reference}</p>{r.details.documentIds?.length?<p className="break-words">Supporting files: {r.details.documentIds.map(id=>model.documents.find(d=>d.id===id)?.filename||'Retained invoice document').join(', ')}</p>:null}<p>{new Date(r.created_at).toLocaleString()}</p></div>)}</div><p>This retains an admin review of carrier evidence. Payment and accounting closeout require their own matching evidence.</p></>:null}
 </section>
}
