import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
export type CarrierSchedule={id:string;submit_at:string;reference:string;cancelled_at:string|null;attempt:{status:string;message:string}|null}
export default function CarrierPaymentSchedule({authorizationId,claimed,schedules,onSaved}:{authorizationId:string;claimed:boolean;schedules:CarrierSchedule[];onSaved:()=>Promise<void>}){
 const [when,setWhen]=useState(''),[reference,setReference]=useState(''),[key,setKey]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const active=schedules.find(s=>!s.cancelled_at)
 const save=async(cancel=false)=>{setBusy(true);setError('');try{if(reference.trim().length<12)throw new Error('Provide the schedule decision reference.');const submitAt=cancel?undefined:new Date(when).toISOString();const r=await adminApiRequest(`/api/admin/payroll/carrier-payment-authorizations/${authorizationId}/schedule${cancel?'/cancel':''}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:true,reference,requestKey:key,submitAt,scheduleId:active?.id})}),j=await r.json();if(!r.ok)throw new Error(j.message||'Unable to retain schedule.');await onSaved();setKey(crypto.randomUUID())}catch(e){setError(e instanceof Error?e.message:'Unable to retain schedule.')}finally{setBusy(false)}}
 return <section aria-label="Carrier submission schedule" className="space-y-2 rounded-lg border p-3">
  <h6 className="font-bold">Scheduled submission</h6>
  {!claimed?<fieldset disabled={busy} className="space-y-2">{!active?<><p>Choose a future bank business day before the payment date. The time below uses your browser’s local timezone.</p><label className="block font-bold">Carrier submission time<input type="datetime-local" value={when} onChange={e=>{setWhen(e.target.value);setKey(crypto.randomUUID())}} className="mt-1 block w-full rounded-lg border p-2"/></label>{when&&Number.isFinite(new Date(when).getTime())?<p>{new Date(when).toString()}</p>:null}</>:null}<label className="block font-bold">Schedule decision reference<input value={reference} maxLength={2000} onChange={e=>{setReference(e.target.value);setKey(crypto.randomUUID())}} className="mt-1 block w-full rounded-lg border p-2"/></label><button type="button" disabled={reference.trim().length<12||!active&&!when} onClick={()=>void save(!!active)} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-50">{active?'Cancel scheduled carrier submission':'Schedule carrier submission'}</button></fieldset>:null}
  {schedules.map(s=><div key={s.id} className="space-y-1"><p>{s.cancelled_at?'Schedule cancelled':claimed?'Schedule dispatch claimed':'Scheduled submission'} · {new Date(s.submit_at).toLocaleString()}</p><p className="break-words">{s.reference}</p>{s.attempt?<p className="break-words">{s.attempt.message}</p>:null}</div>)}
  {error?<p role="alert" className="text-red-700">{error}</p>:null}
 </section>
}
