import CarrierRemittanceRecipient from './CarrierRemittanceRecipient'
import CarrierInvoiceHistory from './CarrierInvoiceHistory'
import CarrierPaymentReceipt,{type CarrierReceipt} from './CarrierPaymentReceipt'
import CarrierSettlementPreview from './CarrierSettlementPreview'
import CarrierPaymentSchedule,{type CarrierSchedule} from './CarrierPaymentSchedule'
import {useEffect,useId,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Preview={fingerprint:string;reservations:{reservedCents:number;availableCents:number};invoiceNumber:string;invoiceRevision:number;amountCents:number;paymentDate:string;premiumJournalId:string;realmId:string;environment:string;liabilityAccount:{id:string;name:string};destination:{holderName:string;accountType:string;accountLast4:string;mode:string}}
type InvoiceBalance={assessmentHistory:{id:number;created_at:string;assessment:{status:string;invoiceAmountCents:number;reconciledCents:number}}[];latestCheck:{status:string;message:string|null;checked_at:string}|null;failedChecks:{id:number;message:string;checked_at:string}[];invoiceRevision:number;historical:boolean;status:string;invoiceAmountCents:number;authorizedCents:number;bankConfirmedCents:number;appliedCents:number;reconciledCents:number;unreservedCents:number|null;remainingToApplyCents:number|null;issues:string[];payments:{id:string;amountCents:number;paymentDate:string;issues:string[]}[]}
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100)
const paymentState=(r:{status:string;settlementStatus?:string}|null)=>r?.settlementStatus==='BANK_POSTED'?'Bank settlement verified — review accounting below':({PROVIDER_APPROVED:'Provider approved',AWAITING_PROVIDER_APPROVAL:'Awaiting provider approval',PROCESSING:'Processing',SENT:'Sent — settlement pending',COMPLETED:'Provider completed — verify bank settlement',UNCERTAIN:'Outcome uncertain — recover payment',RECOVERY_UNAVAILABLE:'Recovery configuration unavailable — review required',NOT_FOUND:'Payment not found — review dispatch',RETURNED:'Payment returned — review required',CANCELLED:'Provider cancelled — review required',FAILED:'Provider failed — review required'}[r?.status||'']||'Dispatch claimed — recover payment')
export default function CarrierPaymentPreview({invoiceId,amountCents,current}:{invoiceId:string;amountCents:number;current:boolean}){
 const referenceId=useId(),[invoiceBalance,setInvoiceBalance]=useState<InvoiceBalance|null>(null)
 const [reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[outside,setOutside]=useState(false),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID()),[history,setHistory]=useState<{receipt:CarrierReceipt|null;schedules:CarrierSchedule[]|null;claimed:boolean;result:{status:string;settlementStatus?:string;dateMatches?:boolean}|null;id:string;amount_cents:string;preview:Preview;reference:string;cancelled_at:string|null;cancellation_reference:string|null}[]|null>(null),[cancelRefs,setCancelRefs]=useState<Record<string,string>>({}),[message,setMessage]=useState('')
 const [amount,setAmount]=useState((amountCents/100).toFixed(2)),[date,setDate]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const hasClaimed=!!history?.some(row=>(row.claimed||row.schedules?.some(s=>!s.cancelled_at))&&!row.cancelled_at)
 const [refreshIssue,setRefreshIssue]=useState(''),[historyRequested,setHistoryRequested]=useState(false)
 useEffect(()=>{
  if(!historyRequested||busy)return
  let cancelled=false,inFlight=false
  const timer=setInterval(()=>{if(inFlight)return;inFlight=true;void(async()=>{try{const r=await adminApiRequest(`/api/admin/payroll/benefit-carrier-invoices/${invoiceId}/payment-authorizations`),j=await r.json();if(!r.ok)throw new Error();if(!cancelled){setHistory(j.data.history);setInvoiceBalance(j.data.invoiceBalance);setRefreshIssue('')}}catch{if(!cancelled)setRefreshIssue('Automatic payment status refresh failed. Reload payment history to check the latest outcome.')}finally{inFlight=false}})()},30000)
  return()=>{cancelled=true;clearInterval(timer)}
 },[invoiceId,historyRequested,busy])
 const request=async(path:string,body?:object)=>{const r=await adminApiRequest(`/api/admin/payroll${path}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),j=await r.json();if(!r.ok)throw new Error(j.message||'Unable to update payment review.');return j.data}
 const loadHistory=async()=>{const data=await request(`/benefit-carrier-invoices/${invoiceId}/payment-authorizations`);setHistory(data.history);setInvoiceBalance(data.invoiceBalance);setRefreshIssue('')}
 const act=async(work:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await work()}catch(e){setError(e instanceof Error?e.message:'Unable to retain payment review.')}finally{setBusy(false)}}
 const refreshHistory=()=>{setHistoryRequested(true);return act(async()=>{try{await loadHistory()}catch{setRefreshIssue('Payment history could not be refreshed. Retry or wait for automatic recovery before relying on this balance.')}})}
 const review=async()=>{setBusy(true);setError('');setMessage('');setConfirmed(false);setOutside(false);setRequestKey(crypto.randomUUID());setPreview(null);try{if(!/^\d+(\.\d{1,2})?$/.test(amount))throw new Error('Enter a positive payment amount with at most two decimal places.');const response=await adminApiRequest(`/api/admin/payroll/benefit-carrier-invoices/${invoiceId}/payment-preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amountCents:Math.round(Number(amount)*100),paymentDate:date})}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to review invoice payment.');setPreview(json.data)}catch(e){setError(e instanceof Error?e.message:'Unable to review invoice payment.')}finally{setBusy(false)}}
 return <details onToggle={e=>{if(e.currentTarget.open&&history===null&&!busy)void refreshHistory()}} className="rounded-lg border p-3"><summary className="cursor-pointer font-bold">Prepare carrier payment</summary><section aria-label="Carrier invoice payment review" className="mt-3 space-y-3">
  {hasClaimed?<p>Claimed payments are checked automatically every five minutes; verified bank settlements are rechecked daily. This history refreshes automatically.</p>:null}{refreshIssue?<p role="status" className="text-amber-900">{refreshIssue}</p>:null}
  {invoiceBalance?<section aria-label="Current carrier invoice balance" className="space-y-2 rounded-lg border p-3"><h5 className="font-bold">Current invoice payment balance · Revision {invoiceBalance.invoiceRevision}</h5>{invoiceBalance.historical?<p>This is the current revision balance; the payment history below belongs to the selected earlier revision.</p>:null}<p>{refreshIssue||invoiceBalance.latestCheck?.status==='FAILED'?'Refresh invoice evidence before relying on this balance':invoiceBalance.status==='RECONCILED'?'Invoice payments reconcile':'Invoice payments remain open'}</p><dl className="space-y-1">{[['Invoice total',invoiceBalance.invoiceAmountCents],['Payment authorizations reserved',invoiceBalance.authorizedCents],['Matching bank settlement',invoiceBalance.bankConfirmedCents],['Carrier-reviewed application',invoiceBalance.appliedCents],['Fully reconciled payments',invoiceBalance.reconciledCents],['Available for new authorization',invoiceBalance.unreservedCents],['Not yet supported by application evidence',invoiceBalance.remainingToApplyCents]].map(([label,value])=><div key={String(label)}><dt className="font-semibold">{label}</dt><dd>{value===null?'Review required':money(Number(value))}</dd></div>)}</dl>{invoiceBalance.issues.map(issue=><p key={issue}>{issue}</p>)}{invoiceBalance.payments.some(p=>p.issues.length)?<details><summary className="cursor-pointer font-bold">Outstanding payment steps</summary>{invoiceBalance.payments.filter(p=>p.issues.length).map(p=><div key={p.id} className="my-2 border-t pt-2"><p>{money(p.amountCents)} · {p.paymentDate}</p><ul className="list-disc pl-4">{p.issues.map(issue=><li key={issue}>{issue}</li>)}</ul></div>)}</details>:null}{invoiceBalance.latestCheck?<p>Invoice automatically checked {new Date(invoiceBalance.latestCheck.checked_at).toLocaleString()}{invoiceBalance.latestCheck.status==='FAILED'?` · ${invoiceBalance.latestCheck.message}`:''}</p>:<p>Automatic invoice assessment is pending.</p>}<details><summary className="cursor-pointer font-bold">Recent invoice history</summary>{invoiceBalance.assessmentHistory.length?invoiceBalance.assessmentHistory.map(a=><div key={a.id} className="my-2 border-t pt-2"><p>{a.assessment.status==='RECONCILED'?'Invoice evidence reconciled':'Invoice evidence open'} · {new Date(a.created_at).toLocaleString()}</p><p>{money(a.assessment.reconciledCents)} reconciled of {money(a.assessment.invoiceAmountCents)}</p></div>):<p>No invoice assessment retained yet.</p>}{invoiceBalance.failedChecks.map(c=><div key={`failed-${c.id}`} className="my-2 border-t pt-2"><p>Invoice check failed · {new Date(c.checked_at).toLocaleString()}</p><p>{c.message}</p></div>)}</details><p>Totals use retained bank, carrier review and accounting evidence. An authorization is a reservation; missing application evidence is not a verified amount due. Outside payments, credits and refunds require separate reconciliation.</p></section>:null}
  <CarrierInvoiceHistory key={invoiceId} invoiceId={invoiceId}/>
 <CarrierRemittanceRecipient key={`recipient:${invoiceId}`} invoiceId={invoiceId}/>
  <p>Check the posted invoice liability and reviewed business destination before preparing a payment. This review does not reserve an amount, authorize payment, or send money.</p>
  <fieldset disabled={busy||!current} className="space-y-3">
   <label className="block font-bold">Proposed carrier payment ($)<input inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setPreview(null);setConfirmed(false);setOutside(false)}} className="mt-1 block w-full rounded-lg border p-2"/></label>
   <label className="block font-bold">Proposed carrier payment date<input type="date" value={date} onChange={e=>{setDate(e.target.value);setPreview(null);setConfirmed(false);setOutside(false)}} className="mt-1 block w-full rounded-lg border p-2"/></label>
   <button type="button" disabled={!amount||!date} onClick={()=>void review()} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-50">Review invoice payment</button>
  </fieldset>
  {!current?<p>Refresh the current invoice reconciliation before reviewing payment.</p>:null}
  {error?<p role="alert" className="text-red-700">{error}</p>:null}
  {preview&&current?<div role="status" className="space-y-2 rounded-lg bg-slate-50 p-3"><p>Payment review only · Invoice {preview.invoiceNumber} · Revision {preview.invoiceRevision}</p><p>{(preview.amountCents/100).toLocaleString('en-US',{style:'currency',currency:'USD'})} · {preview.paymentDate}</p><p className="break-words">{preview.destination.holderName} · {preview.destination.accountType} ending {preview.destination.accountLast4} · {preview.destination.mode}</p><p>Verified premium journal {preview.premiumJournalId} · QuickBooks company {preview.realmId} ({preview.environment})</p><p className="break-words">Liability: {preview.liabilityAccount.name}</p><p>Reserved {(preview.reservations.reservedCents/100).toFixed(2)} USD; available {(preview.reservations.availableCents/100).toFixed(2)} USD within this invoice.</p><fieldset disabled={busy} className="space-y-3"><label htmlFor={referenceId} className="block font-bold">Payment authorization evidence</label><textarea id={referenceId} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false);setOutside(false)}} maxLength={2000} className="mt-1 block w-full rounded-lg border p-2"/><label className="flex items-start gap-2"><input type="checkbox" checked={outside} onChange={e=>setOutside(e.target.checked)}/><span>I verified that no outside payments, credits, refunds or pending payment instructions exist for this invoice. All payment activity is in these retained authorizations.</span></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I authorize this reviewed amount, date, business destination and funding account.</span></label><button type="button" disabled={!confirmed||!outside||reference.trim().length<12} onClick={()=>void act(async()=>{await request(`/benefit-carrier-invoices/${invoiceId}/payment-authorizations`,{amountCents:preview.amountCents,paymentDate:preview.paymentDate,fingerprint:preview.fingerprint,requestKey,reference,confirmed,outsideActivityReviewed:outside});setPreview(null);setConfirmed(false);setOutside(false);await loadHistory();setMessage('Payment authorization retained and amount reserved. No payment was sent.')})} className="rounded-lg bg-slate-900 px-3 py-2 font-bold text-white disabled:opacity-50">Retain payment authorization</button></fieldset><p>Outside payment or credit reconciliation must be completed before authorizing if this confirmation is not true. Submission requires a future bank business day; provider acceptance does not prove settlement.</p></div>:null}
 <button type="button" disabled={busy} onClick={()=>void refreshHistory()} className="rounded-lg border px-3 py-2 font-bold">Load payment authorization history</button>
 {message?<p role="status">{message}</p>:null}
 {history?<div className="space-y-2">{history.length?history.map(row=><div key={row.id} className="space-y-2 rounded-lg border p-3"><p>{row.cancelled_at?'Payment authorization cancelled':row.claimed?paymentState(row.result):'Payment authorized — not submitted'} · {(Number(row.amount_cents)/100).toFixed(2)} USD · {row.preview.paymentDate}</p><p className="break-words">{row.preview.destination.holderName} · ending {row.preview.destination.accountLast4}</p><p className="break-words">{row.reference}</p>{row.receipt?<CarrierPaymentReceipt receipt={row.receipt}/>:null}{row.result?.dateMatches===false?<p>Provider payment date differs from the authorized date. Review required.</p>:null}{row.cancelled_at?<p className="break-words">{row.cancellation_reference}</p>:<>{row.claimed?<CarrierSettlementPreview key={`${row.id}:${JSON.stringify(row.result)}`} authorizationId={row.id}/>:null}<CarrierPaymentSchedule authorizationId={row.id} claimed={row.claimed} schedules={row.schedules||[]} onSaved={loadHistory}/><button type="button" disabled={busy||!row.claimed&&!!row.schedules?.some(s=>!s.cancelled_at)} onClick={()=>void act(async()=>{await request(`/carrier-payment-authorizations/${row.id}/dispatch`,{action:row.claimed?'RECOVER':'SUBMIT',confirmed:true});setPreview(null);await loadHistory()})} className="rounded-lg border px-3 py-2 font-bold">{row.claimed?'Recover carrier payment':'Submit authorized carrier payment'}</button>{!row.claimed?<><label className="block font-bold">Payment cancellation reason<input disabled={busy} value={cancelRefs[row.id]||''} onChange={e=>setCancelRefs(v=>({...v,[row.id]:e.target.value}))} className="mt-1 block w-full rounded-lg border p-2"/></label><button type="button" disabled={busy||(cancelRefs[row.id]||'').trim().length<12} onClick={()=>void act(async()=>{await request(`/carrier-payment-authorizations/${row.id}/cancel`,{confirmed:true,reference:cancelRefs[row.id]});setPreview(null);await loadHistory();setMessage('Payment authorization cancelled and reservation released.')})} className="rounded-lg border px-3 py-2 font-bold">Cancel payment authorization</button></>:<p>Dispatch is claimed. Keep this amount reserved while recovering the provider outcome.</p>}</>}</div>):<p>No payment authorizations retained.</p>}</div>:null}
 </section></details>
}
