import CheckReplacementAuthorization from './CheckReplacementAuthorization'
import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Review={replacementDate:string;taxTreatment:string;reference:string;taxReference:string}
type Plan={status:string;issues:string[];canReview:boolean;fingerprint:string;revision:number;amountCents:number;originalPaymentDate:string;deliveryDate:string|null;method:string|null;runStatus:string;history:Array<{id:number;review:Review;current:boolean}>}
export default function CheckReplacementReview({base}:{base:string}){
 const [plan,setPlan]=useState<Plan|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[date,setDate]=useState(''),[tax,setTax]=useState('CORRECTION_REQUIRED'),[reference,setReference]=useState(''),[taxReference,setTaxReference]=useState(''),[confirmed,setConfirmed]=useState(false)
 const request=async(body?:Record<string,unknown>)=>{const response=await adminApiRequest(`${base}/replacement-review`,body?{method:'POST',body:JSON.stringify(body)}:undefined),result=await response.json();if(!response.ok)throw new Error(result.message||'Unable to review check replacement.');return result.data}
 const load=async()=>{const data=await request() as Plan;setPlan(data);const saved=data.history[0]?.review;setDate(saved?.replacementDate||data.originalPaymentDate);setTax(saved?.taxTreatment||'CORRECTION_REQUIRED');setReference(saved?.reference||'');setTaxReference(saved?.taxReference||'');setConfirmed(false)}
 const act=async(save=false)=>{setBusy(true);setError('');try{if(save&&plan)await request({fingerprint:plan.fingerprint,expectedRevision:plan.revision,replacementDate:date,taxTreatment:tax,reference,taxReference,confirmed,noOtherPaymentConfirmed:confirmed});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to retain replacement review.')}finally{setBusy(false)}}
 return <section aria-label="Stopped check replacement review" className="space-y-3 rounded border p-3"><h6 className="font-bold">Review replacement of this check</h6><p>Retain the unpaid amount and reporting decision before authorizing another payment.</p><button type="button" disabled={busy} className="font-bold underline" onClick={()=>void act()}>Review stopped check replacement</button>{error?<p role="alert">{error}</p>:null}{plan?<><p>{plan.status.replaceAll('_',' ')}</p><p>Original net: {(plan.amountCents/100).toLocaleString('en-US',{style:'currency',currency:'USD'})}<br/>Original date: {plan.originalPaymentDate}<br/>Payroll: {plan.runStatus}<br/>Current payment choice: {plan.method||'Review needed'}<br/>Handoff: {plan.deliveryDate||'Not recorded'}</p>{plan.issues.map(issue=><p key={issue} className="text-red-700">{issue}</p>)}<fieldset disabled={busy||!plan.canReview} className="space-y-2"><legend className="font-semibold">Unpaid-wage and tax review</legend><label className="block">Proposed replacement date<input type="date" value={date} onChange={e=>{setDate(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2"/></label><label className="block">Check replacement tax treatment<select value={tax} onChange={e=>{setTax(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2"><option value="CORRECTION_REQUIRED">Correction required</option><option value="ORIGINAL_PAYROLL_RETAINED">Keep original payroll reporting</option></select></label><label className="block">Unpaid check review reference<input value={reference} maxLength={1000} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2"/></label><label className="block">Check tax review reference<input value={taxReference} maxLength={1000} onChange={e=>{setTaxReference(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2"/></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the full unpaid amount, verified no other payment was made, and confirmed the reporting treatment.</label><button type="button" disabled={!confirmed||!date||reference.trim().length<12||taxReference.trim().length<12} className="font-bold underline disabled:opacity-50" onClick={()=>void act(true)}>Save check replacement review</button></fieldset><p>This review does not send a replacement or change reported wages.</p>{plan.history.length?<details><summary>Retained check replacement reviews</summary>{plan.history.map(h=><p key={h.id}>Review {h.id}: {h.review.replacementDate} · {h.review.taxTreatment.replaceAll('_',' ')}{h.current?' · Current':''}</p>)}</details>:null}<CheckReplacementAuthorization key={plan.revision} base={base}/></>:null}</section>
}
