import CheckEvidenceHistory from './CheckEvidenceHistory'
import CheckStopRetry from './CheckStopRetry'
import CheckCancellation from './CheckCancellation'
import CheckReplacementReview from './CheckReplacementReview'
import {useCallback,useEffect,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Plan={status:string;issues:string[];fingerprint:string;amountCents:number;paymentDate:string;payeeName:string|null;expiryDays:number}
type Issue={hasCancellation?:boolean;preflightStatus?:'READY_TO_CANCEL'|'RECOVERY_REQUIRED'|null;id:string;status:string;amountCents:number;paymentDate:string}
type Delivery={status:string;reference:string|null}
export default function CheckIssuanceReview({runId,batchId,employeeId,employeeName,onChanged}:{runId:number;batchId:string;employeeId:number;employeeName:string;onChanged?:()=>Promise<void>}){
 const [plan,setPlan]=useState<Plan|null>(null),[issue,setIssue]=useState<Issue|null>(null),[delivery,setDelivery]=useState<Delivery|null>(null),[retained,setRetained]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[handoff,setHandoff]=useState(false),[downloaded,setDownloaded]=useState(false),[stop,setStop]=useState<{id:string;status:string;blocking:boolean;releasedAt:string|null;canContinueNoSend:boolean;canContinue:boolean;observationId:string}|null>(null),[stopReference,setStopReference]=useState(''),[stopConfirmed,setStopConfirmed]=useState(false)
 const base=`/api/admin/payroll/runs/${runId}/payment-authorization/${batchId}/checks/${employeeId}`
 const json=useCallback(async(suffix:string,body?:Record<string,unknown>)=>{const response=await adminApiRequest(`${base}${suffix}`,body?{method:'POST',body:JSON.stringify(body)}:undefined),result=await response.json();if(!response.ok)throw new Error(result.message);return result.data},[base])
 const existing=useCallback(async()=>{const value=await json('/issue') as Issue|null;if(!value)return {issue:null,delivery:null,retained:false,stop:null};const [d,p,st]=await Promise.all([json('/delivery'),json('/document'),json('/stop')]);return {issue:value,delivery:d as Delivery,retained:p.status==='RETAINED',stop:st as {id:string;status:string;blocking:boolean;releasedAt:string|null;canContinueNoSend:boolean;canContinue:boolean;observationId:string}|null}},[json])
 const apply=useCallback((s:Awaited<ReturnType<typeof existing>>)=>{setIssue(s.issue);setDelivery(s.delivery);setRetained(s.retained);setStop(s.stop)},[])
 useEffect(()=>{let active=true;void existing().then(s=>{if(active)apply(s)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[existing,apply])
 useEffect(()=>{
  if(busy||reference||confirmed||handoff||stopReference||stopConfirmed||!issue)return
  let active=true,pending=false
  const timer=setInterval(()=>{if(document.visibilityState!=='visible'||pending)return;pending=true;void existing().then(s=>{if(active){if(JSON.stringify(s.issue)!==JSON.stringify(issue))setNotice('Check status updated automatically.');apply(s);setError('')}}).catch(()=>{if(active){setStop(s=>s?{...s,canContinueNoSend:false,canContinue:false}:s);setStopConfirmed(false);setError('Automatic status refresh is unavailable. Recover check status to retry.')}}).finally(()=>{pending=false})},30000)
  return()=>{active=false;clearInterval(timer)}
 },[busy,reference,confirmed,handoff,stopReference,stopConfirmed,issue,existing,apply])
 const review=async()=>{setBusy(true);setPlan(null);setError('');setConfirmed(false);try{const s=await existing();apply(s);if(!s.issue)setPlan(await json('/plan'))}catch(e){setStop(s=>s?{...s,canContinueNoSend:false,canContinue:false}:s);setStopConfirmed(false);setError(e instanceof Error?e.message:'Unable to prepare this check.')}finally{setBusy(false)}}
 const act=async(kind:'SUBMIT'|'RECOVER'|'RETAIN'|'DELIVER')=>{setBusy(true);setError('');setNotice('');try{
  if(kind==='SUBMIT'){await json('/issue',{action:kind,fingerprint:plan?.fingerprint,reference,confirmed,noPriorPaymentConfirmed:confirmed});setPlan(null)}
  else if(kind==='RECOVER'){if(stop)await json('/stop',{action:'RECOVER'});await json('/issue',{action:kind})}
  else if(kind==='RETAIN')await json('/document',{action:kind})
  else await json('/delivery',{confirmed:handoff,deliveredInPerson:handoff,amountCents:issue?.amountCents,paymentDate:issue?.paymentDate,reference})
  const current=await existing();apply(current);setReference('');setNotice(kind==='DELIVER'?'Printed check delivery retained.':'Check progress updated.');if(kind==='SUBMIT'||kind==='DELIVER'||(kind==='RECOVER'&&current.issue?.preflightStatus)||(kind==='RETAIN'&&delivery?.status==='DELIVERY_RETAINED'))await onChanged?.()
 }catch(e){setError(e instanceof Error?e.message:'Unable to update this check.')}finally{setBusy(false);setConfirmed(false);setHandoff(false)}}
 const download=async()=>{setBusy(true);setError('');setDownloaded(false);setHandoff(false);try{const response=await adminApiRequest(`${base}/document`,{method:'POST',body:JSON.stringify({action:'DOWNLOAD'})});if(!response.ok){const result=await response.json();throw new Error(result.message)}const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=`payroll-check-${runId}-${employeeId}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setDownloaded(true);setNotice('Check downloaded. Print it and hand it to the employee before recording delivery.')}catch(e){setError(e instanceof Error?e.message:'Unable to download this check.')}finally{setBusy(false)}}
 const requestStop=async()=>{setBusy(true);setError('');try{await json('/stop',{action:stop?'RECOVER':'SUBMIT',reference:stopReference,confirmed:stopConfirmed,stopPaymentsEnabled:stopConfirmed});await json('/issue',{action:'RECOVER'});apply(await existing());setStopReference('');setDownloaded(false);setHandoff(false);setNotice('Stop status retained. Review unpaid wages before any replacement.')}catch(e){setStop(s=>s?{...s,canContinueNoSend:false,canContinue:false}:s);setError(e instanceof Error?e.message:'Unable to confirm the check stop.')}finally{setBusy(false);setStopConfirmed(false)}}
 useEffect(()=>{setStopConfirmed(false)},[stop?.observationId])
 const releaseStop=async()=>{setBusy(true);setError('');try{await json('/stop/release',{reference:stopReference,confirmed:stopConfirmed,originalCheckAvailable:stopConfirmed,expectedObservationId:stop?.observationId});await json('/issue',{action:'RECOVER'});apply(await existing());setStopReference('');setNotice('Original-check continuation retained. No replacement payment was created.')}catch(e){setStop(s=>s?{...s,canContinueNoSend:false,canContinue:false}:s);setError(e instanceof Error?e.message:'Unable to resume the original check.')}finally{setBusy(false);setStopConfirmed(false)}}
 const money=(n:number)=>(n/100).toLocaleString('en-US',{style:'currency',currency:'USD'})
 return <section aria-label={`Check issuance review ${employeeName}`} aria-busy={busy} className="space-y-3 rounded border p-3">
  <h5 className="font-bold">Check payment · {employeeName}</h5><button type="button" disabled={busy} onClick={()=>void review()} className="font-bold underline">Review check issuance</button>
  {error?<p role="alert" className="text-red-700">{error}</p>:null}{notice?<p className="text-emerald-800">{notice}</p>:null}
  {plan&&!issue?<><p role="status">{plan.status.replaceAll('_',' ')}</p><p>{money(plan.amountCents)} · {plan.paymentDate}</p><p>Payee: {plan.payeeName||'Recipient setup required'} · Expires after {plan.expiryDays} days</p>{plan.issues.length?<ul className="list-disc space-y-1 pl-5">{plan.issues.map(i=><li key={i}>{i}</li>)}</ul>:<fieldset disabled={busy} className="space-y-2"><legend className="font-semibold">Issue the reviewed check</legend><label className="block">Check issuance reference<input maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2"/></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm no payment has already been issued for these wages and authorize this check.</label><button type="button" disabled={!confirmed||reference.trim().length<12} className="rounded bg-slate-900 p-2 font-bold text-white disabled:opacity-50" onClick={()=>void act('SUBMIT')}>Issue payroll check</button></fieldset>}</>:null}
  {issue?<><p role="status">Check status: {issue.status.replaceAll('_',' ')}</p>{issue.preflightStatus?<p>{issue.preflightStatus==='READY_TO_CANCEL'?'No provider check was created. Fresh recovery confirms it was not found. Review cancellation of this payment authorization, then void and rebuild payroll.':'Check submission stopped before provider creation. Recover check status to verify cancellation eligibility.'}</p>:null}{issue.preflightStatus==='READY_TO_CANCEL'&&onChanged?<button type="button" disabled={busy} className="font-bold underline" onClick={()=>void onChanged()}>Refresh cancellation eligibility</button>:null}<p>{money(issue.amountCents)} · {issue.paymentDate}</p>{issue.hasCancellation||['AWAITING_PROVIDER_APPROVAL','PROVIDER_APPROVED','CANCELLED'].includes(issue.status)?<CheckCancellation runId={runId} batchId={batchId} employeeId={employeeId} onChanged={onChanged}/>:null}<button type="button" disabled={busy} className="font-bold underline" onClick={()=>void act('RECOVER')}>Recover check status</button>
   {stop?<div className="space-y-2 rounded border p-2"><p>Stop request: {stop.status.replaceAll('_',' ')}</p><p>{stop.blocking?'Printing and delivery are blocked. Resolve the stopped or uncertain check and unpaid wages before replacement.':'The reviewed original check may continue. No replacement payment was authorized.'}</p>{stop.releasedAt?<p>Original-check review retained: {new Date(stop.releasedAt).toLocaleString()}</p>:null}<button type="button" disabled={busy} className="font-bold underline" onClick={()=>void requestStop()}>Recover check stop</button>{!stop.releasedAt&&stop.canContinue?<fieldset disabled={busy||issue.status!=='SENT'} className="space-y-2"><legend className="font-semibold">Continue the original check</legend>{stop.canContinueNoSend?<p>The stop was not transmitted and fresh recovery found no bank-stop action. Continue only the recovered original check.</p>:null}<label className="block">Original check recovery reference<input maxLength={2000} value={stopReference} onChange={e=>{setStopReference(e.target.value);setStopConfirmed(false)}} className="block w-full rounded border p-2"/></label><label className="flex items-start gap-2"><input type="checkbox" checked={stopConfirmed} onChange={e=>setStopConfirmed(e.target.checked)}/>I recovered the original check, no replacement was issued, and I authorize continuing that check.</label><button type="button" disabled={!stopConfirmed||stopReference.trim().length<12} className="font-bold underline disabled:opacity-50" onClick={()=>void releaseStop()}>Continue original check</button></fieldset>:null}</div>:issue.status==='SENT'?<details><summary>Lost check or stop payment</summary><fieldset disabled={busy} className="space-y-2"><legend className="font-semibold">Request a bank stop</legend><p>A request is not confirmation that the bank stopped the check.</p><label className="block">Check stop review reference<input maxLength={2000} value={stopReference} onChange={e=>{setStopReference(e.target.value);setStopConfirmed(false)}} className="block w-full rounded border p-2"/></label><label className="flex items-start gap-2"><input type="checkbox" checked={stopConfirmed} onChange={e=>setStopConfirmed(e.target.checked)}/>I verified this bank supports stop-payment actions and authorize stopping this check.</label><button type="button" disabled={!stopConfirmed||stopReference.trim().length<12} className="font-bold underline disabled:opacity-50" onClick={()=>void requestStop()}>Request check stop</button></fieldset></details>:null}
   {stop?<CheckStopRetry base={base} onChanged={review}/>:null}
   <CheckEvidenceHistory base={base}/>
   {stop&&issue.status==='STOPPED'?<CheckReplacementReview base={base}/>:null}
   <button type="button" disabled={busy||!!stop?.blocking||issue.status!=='SENT'} className="block font-bold underline disabled:opacity-50" onClick={()=>void act('RETAIN')}>{retained?'Refresh check document':'Retain check document'}</button>
   {delivery?.status==='DELIVERY_RETAINED'?<p>Printed check delivery retained · {delivery.reference}</p>:<><button type="button" disabled={busy||!!stop?.blocking||!retained||issue.status!=='SENT'} className="block font-bold underline disabled:opacity-50" onClick={()=>void download()}>Download printable check</button>
   <fieldset disabled={busy||!!stop?.blocking||!downloaded} className="space-y-2"><legend className="font-semibold">Confirm printed check handoff</legend><label className="block">Printed check delivery reference<input maxLength={200} value={reference} onChange={e=>{setReference(e.target.value);setHandoff(false)}} className="block w-full rounded border p-2"/></label><label className="flex items-start gap-2"><input type="checkbox" checked={handoff} onChange={e=>setHandoff(e.target.checked)}/>I printed this retained check and handed it to this employee today.</label><button type="button" disabled={!handoff||reference.trim().length<12} className="rounded bg-slate-900 p-2 font-bold text-white disabled:opacity-50" onClick={()=>void act('DELIVER')}>Record check delivery</button></fieldset></>}
  </>:null}
 </section>
}
