import ReceiptDownload from './ReceiptDownload'
import {useEffect,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
import {employeePayrollApi,type CheckReceipt} from '../../utils/employeePayrollApi'
export default function CheckReceipts({runId}:{runId?:number}){
 const [rows,setRows]=useState<CheckReceipt[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[confirmed,setConfirmed]=useState(''),[saving,setSaving]=useState(false)
 useEffect(()=>{let active=true;setLoading(true);setError('');setRows([])
  const load=async()=>{if(runId===undefined)return employeePayrollApi.checkReceipts();const response=await adminApiRequest(`/api/admin/payroll/runs/${runId}/check-receipts`),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to load check receipts.');return json.data as CheckReceipt[]}
  void load().then(data=>{if(active)setRows(data)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to load check receipts.')}).finally(()=>{if(active)setLoading(false)})
  return()=>{active=false}
 },[runId,revision])
 useEffect(()=>{if(loading||confirmed||saving)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')setRevision(value=>value+1)},30000);return()=>clearInterval(timer)},[loading,confirmed,saving])
 const acknowledge=async(id:string)=>{if(saving||confirmed!==id)return;setSaving(true);setError('');try{const saved=await employeePayrollApi.acknowledgeCheckReceipt(id);setRows(current=>current.map(row=>row.id===id?{...row,acknowledgedAt:saved.acknowledgedAt}:row));setConfirmed('')}catch(e){setError(e instanceof Error?e.message:'Unable to acknowledge this check.')}finally{setSaving(false)}}
 return <section aria-label="Check delivery receipts" className="space-y-3 rounded-xl border p-4"><h3 className="font-bold">Check delivery receipts</h3><p>These receipts show employer-recorded check handoffs. Refer to the pay statement for wages and taxes.</p><button type="button" disabled={loading||saving||!!confirmed} className="font-bold underline" onClick={()=>setRevision(value=>value+1)}>Refresh check receipts</button>{error?<p role="alert">{error}</p>:null}{loading?<p role="status">Loading check receipts…</p>:!rows.length?<p>No check handoffs recorded yet.</p>:rows.map(row=><article key={row.id} className="space-y-2 rounded border p-3"><h4 className="font-bold">{row.employeeName} · {(row.amountCents/100).toLocaleString('en-US',{style:'currency',currency:'USD'})}</h4>{row.sourceKind==='REPLACEMENT_CHECK'?<p>Replacement check · Original pay date: {row.originalPaymentDate}</p>:null}<p>Pay date: {row.paymentDate}<br/>Employer recorded handoff: {new Date(row.deliveredAt).toLocaleString()}</p><p role="status">{row.status==='BANK_CONFIRMED'?'Bank clearance confirmed':row.status==='OUTSTANDING'?'Awaiting bank clearance':'Check evidence needs review — contact payroll'}</p>{row.bankPostedDates.length?<p>Bank posted: {row.bankPostedDates.join(', ')}</p>:null}{row.observedAt?<p className="text-sm">Last checked: {new Date(row.observedAt).toLocaleString()}</p>:null}<p className="break-all text-sm">Receipt: {row.id}</p><ReceiptDownload id={row.id} runId={runId} check/>{row.acknowledgedAt?<p>Employee acknowledged receipt: {new Date(row.acknowledgedAt).toLocaleString()}</p>:runId===undefined?<fieldset disabled={loading||saving} className="space-y-2"><legend className="font-semibold">Optional receipt acknowledgment</legend><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed===row.id} onChange={e=>setConfirmed(e.target.checked?row.id:'')}/>I received this check for {(row.amountCents/100).toLocaleString('en-US',{style:'currency',currency:'USD'})} dated {row.paymentDate}.</label><button type="button" disabled={confirmed!==row.id} onClick={()=>void acknowledge(row.id)} className="font-bold underline disabled:opacity-50">Acknowledge check receipt</button><p className="text-sm">This records receipt only. It does not confirm the amount is correct or waive a payroll question.</p></fieldset>:<p>Employee acknowledgment not recorded.</p>}</article>)}</section>
}
