import {useCallback,useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Review={historyBlock:boolean;canRetry:boolean;canRenew:boolean;currentReleaseId:string|null;continuations:{id:string;reference:string;createdAt:string}[];retryKind:'NOT_TRANSMITTED'|'FAILED_ACTION'|null;observationId:string;retries:{id:string;reference:string;createdAt:string}[]}
export default function CheckStopRetry({base,onChanged}:{base:string;onChanged:()=>Promise<void>}){
 const [data,setData]=useState<Review|null>(null),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const revision=useRef(0)
 const read=useCallback(async()=>{const current=++revision.current;try{const response=await adminApiRequest(`${base}/stop`),json=await response.json();if(current!==revision.current)return undefined;if(!response.ok)throw new Error(json.message||'Unable to review stop retry.');return json.data as Review|null}catch(e){if(current!==revision.current)return undefined;throw e}},[base])
 const invalidate=()=>{setData(d=>d?{...d,canRetry:false,canRenew:false}:null);setConfirmed(false)}
 useEffect(()=>{let active=true;void read().then(d=>{if(active&&d!==undefined)setData(d)}).catch(e=>{if(active){setError(e.message);setData(d=>d?{...d,canRetry:false,canRenew:false}:null)}});return()=>{active=false}},[read])
 useEffect(()=>{setConfirmed(false)},[data?.observationId,data?.currentReleaseId])
 useEffect(()=>{if(busy||reference||confirmed)return;let active=true,pending=false;const timer=setInterval(()=>{if(pending||document.visibilityState!=='visible')return;pending=true;void read().then(d=>{if(active&&d!==undefined){setData(d);setError('')}}).catch(()=>{if(active){setError('Automatic stop retry review is unavailable. Refresh before reviewing another request.');setData(d=>d?{...d,canRetry:false,canRenew:false}:null)}}).finally(()=>{pending=false})},30000);return()=>{active=false;clearInterval(timer)}},[busy,reference,confirmed,read])
 const refresh=async()=>{setBusy(true);setError('');try{const d=await read();if(d!==undefined)setData(d)}catch(e){setError(e instanceof Error?e.message:'Unable to refresh stop retry.');invalidate()}finally{setBusy(false);setConfirmed(false)}}
 const retry=async()=>{if(busy)return;revision.current++;setBusy(true);setError('');try{const response=await adminApiRequest(`${base}/stop`,{method:'POST',body:JSON.stringify({action:data?.canRenew?'RENEW':'RETRY',expectedReleaseId:data?.currentReleaseId,expectedObservationId:data?.observationId,reference,confirmed,originalCheckUnavailable:confirmed,stopPaymentsEnabled:confirmed})}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to retain stop retry.');const d=await read();if(d!==undefined)setData(d);setReference('');setConfirmed(false);await onChanged()}catch(e){setError(e instanceof Error?e.message:'Unable to retain stop retry.');invalidate()}finally{setBusy(false)}}
 return <section aria-label="Failed check stop retry" className="space-y-2 rounded border p-3"><h6 className="font-bold">{data?.canRenew?'Request a renewed bank stop':'Retry a failed bank stop'}</h6><button type="button" disabled={busy} className="font-bold underline" onClick={()=>void refresh()}>Refresh stop retry review</button>{error?<p role="alert" className="text-red-700">{error}</p>:null}{data&&(data.canRetry||data.canRenew)?<fieldset disabled={busy} className="space-y-2"><legend className="font-semibold">Review another stop request</legend><p>{data.canRenew?'An earlier review allowed the original check to continue.':data.retryKind==='NOT_TRANSMITTED'?'This attempt stopped before transmission, and fresh recovery found no new bank-stop action.':'The previous stop failed or was cancelled.'} Review another attempt if the original check is unavailable. Wages remain reserved until bank-stop and replacement evidence are complete.</p><label className="block">Stop retry reference<input className="block w-full rounded border p-2" value={reference} maxLength={2000} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>The original check is unavailable, this bank supports stop actions, and I authorize another stop request.</label><button type="button" disabled={!confirmed||reference.trim().length<12} className="rounded bg-slate-900 p-2 font-bold text-white disabled:opacity-50" onClick={()=>void retry()}>{data.canRenew?'Request renewed bank stop':'Retry bank stop'}</button></fieldset>:<p>{data?.historyBlock?'Earlier paid, stopped or conflicting check evidence prevents continuing this original or requesting another stop.':'Recover the current stop to review eligibility. An uncertain or pending request must be recovered before another attempt.'}</p>}{data?.retries?.length?<details><summary>Stop retry history</summary><ol>{data.retries.map(r=><li key={r.id} className="break-words">{new Date(r.createdAt).toLocaleString()} · {r.reference}</li>)}</ol></details>:null}{data?.continuations?.length?<details><summary>Original-check continuation history</summary><ol>{data.continuations.map(r=><li key={r.id} className="break-words">{new Date(r.createdAt).toLocaleString()} · {r.reference}</li>)}</ol></details>:null}</section>
}
