import { useCallback, useEffect, useState } from 'react'
import { workforceApi, type PayRateData } from '../../utils/workforceApi'
import { workforceButton, workforceInput } from './OnboardingWorkspace'

const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100)
const day=(value:string)=>value.slice(0,10)
export default function CompensationHistory({employeeId,canSchedule=false,onChanged}:{employeeId?:number;canSchedule?:boolean;onChanged?:()=>Promise<void>}) {
 const [data,setData]=useState<PayRateData|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const [form,setForm]=useState({hourlyRate:'',effectiveOn:'',reason:'',noticeDeliveredOn:'',noticeReference:'',noticeConfirmed:false})
 const [cancelId,setCancelId]=useState<number|null>(null),[cancelForm,setCancelForm]=useState({reason:'',noticeDeliveredOn:'',noticeReference:'',noticeConfirmed:false})
 const load=useCallback(async()=>{const next=await workforceApi.payRates(employeeId);setData(next)},[employeeId])
 useEffect(()=>{let live=true;workforceApi.payRates(employeeId).then(next=>{if(live)setData(next)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[employeeId])
 return <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Pay rates & notices</h2><p className="mt-2 text-sm text-slate-600">{data?.currentRateCents!=null?`Current rate: ${money(data.currentRateCents)}/hour. `:''}Each workday uses its effective rate. Previously finalized statements keep their original amounts.</p>
 {error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}{notice?<p role="status" className="mt-3 text-sm text-emerald-700">{notice}</p>:null}
 {!data&&!error?<p className="mt-3 text-sm">Loading compensation…</p>:null}
 <div className="mt-4 space-y-3">{data?.rates.map(rate=><article key={rate.id} className="rounded-xl border border-slate-200 p-4"><p className="font-bold">{money(rate.hourly_rate_cents)}/hour · Effective {day(rate.effective_on)}{rate.cancelled_at?' · Cancelled':day(rate.effective_on)>data.today?' · Scheduled':''}</p><p className="mt-1 text-sm text-slate-600">{rate.reason}</p>{rate.notice_delivered_on?<><p className="mt-2 text-xs text-slate-500">Written notice delivered {day(rate.notice_delivered_on)} · {rate.notice_reference}</p><p className="mt-1 text-xs text-slate-500">{rate.acknowledged_at?`Receipt acknowledged ${day(rate.acknowledged_at)}`:'Receipt not yet acknowledged'}</p>{!employeeId&&!rate.acknowledged_at&&!rate.cancelled_at?<button type="button" disabled={busy} className={`${workforceButton} mt-3`} onClick={async()=>{setBusy(true);setError('');try{await workforceApi.acknowledgePayRate(rate.id);await load();setNotice('Receipt recorded. This acknowledgment does not waive any wage rights.')}catch(e){setError(e instanceof Error?e.message:'Unable to acknowledge')}finally{setBusy(false)}}}>Acknowledge receipt of pay notice</button>:null}</>:null}
 {rate.cancelled_at?<div className="mt-3 rounded-lg bg-amber-50 p-3 text-sm"><p className="font-bold">Cancelled {day(rate.cancelled_at)} — this rate will not take effect.</p><p className="mt-1">{rate.cancellation_reason}</p><p className="mt-1 text-xs">Cancellation notice delivered {day(rate.cancellation_notice_delivered_on||'')} · {rate.cancellation_notice_reference}</p><p className="mt-1 text-xs">{rate.cancellation_acknowledged_at?`Cancellation receipt acknowledged ${day(rate.cancellation_acknowledged_at)}`:'Cancellation receipt not yet acknowledged'}</p>{!employeeId&&!rate.cancellation_acknowledged_at?<button type="button" disabled={busy} className={`${workforceButton} mt-3`} onClick={async()=>{setBusy(true);setError('');try{await workforceApi.acknowledgePayRate(rate.id,true);await load();setNotice('Cancellation receipt recorded. This acknowledgment does not waive any wage rights.')}catch(e){setError(e instanceof Error?e.message:'Unable to acknowledge cancellation')}finally{setBusy(false)}}}>Acknowledge cancellation notice</button>:null}</div>:null}
 {employeeId&&canSchedule&&rate.notice_delivered_on&&!rate.cancelled_at&&day(rate.effective_on)>data.today&&rate.id===data.rates.find(r=>!r.cancelled_at)?.id?<button type="button" disabled={busy} className={`${workforceButton} mt-3`} onClick={()=>{setCancelId(rate.id);setError('');setNotice('')}}>Cancel scheduled pay change</button>:null}
 </article>)}</div>
 {employeeId&&cancelId&&data?<form className="mt-5 grid gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{await workforceApi.cancelPayRate(employeeId,cancelId,cancelForm);await load();await onChanged?.();setCancelId(null);setCancelForm({reason:'',noticeDeliveredOn:'',noticeReference:'',noticeConfirmed:false});setNotice('Pay change cancelled. The previous rate continues; schedule a replacement below if needed.')}catch(e){setError(e instanceof Error?e.message:'Unable to cancel pay change')}finally{setBusy(false)}}}>
 <h3 className="font-black sm:col-span-2">Cancel future rate</h3><p className="text-sm sm:col-span-2">The prior rate continues. The original notice and this cancellation remain visible to the employee. Cancelling an increase requires advance written notice under the same timing rule as a decrease.</p>
 <label className="text-sm font-bold sm:col-span-2">Reason for cancellation<textarea required minLength={12} className={workforceInput} value={cancelForm.reason} onChange={e=>setCancelForm(f=>({...f,reason:e.target.value}))}/></label>
 <label className="text-sm font-bold">Cancellation notice delivered on<input type="date" required max={data.today} className={workforceInput} value={cancelForm.noticeDeliveredOn} onChange={e=>setCancelForm(f=>({...f,noticeDeliveredOn:e.target.value}))}/></label>
 <label className="text-sm font-bold">Cancellation notice reference<input required minLength={12} className={workforceInput} value={cancelForm.noticeReference} onChange={e=>setCancelForm(f=>({...f,noticeReference:e.target.value}))}/></label>
 <label className="flex items-start gap-2 text-sm sm:col-span-2"><input type="checkbox" required checked={cancelForm.noticeConfirmed} onChange={e=>setCancelForm(f=>({...f,noticeConfirmed:e.target.checked}))}/>I confirm this employee received the written cancellation notice.</label>
 <button disabled={busy} className={workforceButton}>Confirm pay change cancellation</button><button type="button" disabled={busy} className={workforceButton} onClick={()=>setCancelId(null)}>Keep scheduled change</button>
 </form>:null}
 {employeeId&&canSchedule&&data?<form className="mt-5 grid gap-3 border-t border-slate-200 pt-5 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{await workforceApi.schedulePayRate(employeeId,{...form,hourlyRateCents:Math.round(Number(form.hourlyRate)*100)});await load();await onChanged?.();setForm({hourlyRate:'',effectiveOn:'',reason:'',noticeDeliveredOn:'',noticeReference:'',noticeConfirmed:false});setNotice('Pay change scheduled and available in the employee portal.')}catch(e){setError(e instanceof Error?e.message:'Unable to schedule pay change')}finally{setBusy(false)}}}>
 <h3 className="font-black sm:col-span-2">Schedule pay change</h3><p className="text-sm text-slate-600 sm:col-span-2">Changes start on a future date after the last scheduled rate. Midweek changes use a verified weighted overtime calculation for that workweek before payroll approval. Decreases require a full pay period of advance written notice (16 days for semimonthly payroll).</p>
 <label className="text-sm font-bold">New hourly rate ($)<input className={workforceInput} type="number" required min="0.01" step="0.01" value={form.hourlyRate} onChange={e=>setForm(f=>({...f,hourlyRate:e.target.value}))}/></label>
 <label className="text-sm font-bold">Effective date<input className={workforceInput} type="date" required min={data.today} value={form.effectiveOn} onChange={e=>setForm(f=>({...f,effectiveOn:e.target.value}))}/></label>
 <label className="text-sm font-bold sm:col-span-2">Reason for pay change<textarea className={workforceInput} required minLength={12} value={form.reason} onChange={e=>setForm(f=>({...f,reason:e.target.value}))}/></label>
 <label className="text-sm font-bold">Written notice delivered on<input className={workforceInput} type="date" required max={data.today} value={form.noticeDeliveredOn} onChange={e=>setForm(f=>({...f,noticeDeliveredOn:e.target.value}))}/></label>
 <label className="text-sm font-bold">Written-notice delivery reference<input className={workforceInput} required minLength={12} placeholder="Signed letter or delivery receipt reference" value={form.noticeReference} onChange={e=>setForm(f=>({...f,noticeReference:e.target.value}))}/></label>
 <label className="flex items-start gap-2 text-sm sm:col-span-2"><input className="mt-1" type="checkbox" required checked={form.noticeConfirmed} onChange={e=>setForm(f=>({...f,noticeConfirmed:e.target.checked}))}/>I confirm this employee received written notice on the recorded date.</label><button disabled={busy} className={workforceButton}>Schedule pay change</button>
 </form>:null}</section>
}
