import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
export type ApplicabilityHistory={id:string;categories:Record<string,string>;reference:string;created_by:string;created_at:string;status:string}
const retirementDecision:Record<string,string>={EMPLOYER_ONLY_PARTICIPATION:'Active participant — employer funding only',STANDARD_401K_DEFERRALS:'Reconciled internal standard 401(k) employee deferrals'}
const decisions:Record<string,string>={NOT_APPLICABLE:'Not applicable',APPLICABLE:'Applicable — reporting treatment required',UNRESOLVED:'Unresolved'}
export default function CompensationApplicability({employeeId,sourceFingerprint,ready,categories,history,onSaved}:{employeeId:number;sourceFingerprint:string;ready:boolean;categories:Record<string,string>;history:ApplicabilityHistory[];onSaved:()=>Promise<void>}){
 const [retirementConfirmed,setRetirementConfirmed]=useState(false)
 const [answers,setAnswers]=useState<Record<string,string>>({}),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[stale,setStale]=useState(false),[error,setError]=useState('')
 const valid=ready&&!busy&&!stale&&confirmed&&Object.keys(categories).length>0&&Object.keys(categories).every(key=>!!decisions[answers[key]]||(key==='retirement'&&!!retirementDecision[answers[key]]&&retirementConfirmed))&&reference.trim().length>=12&&!Array.from(reference).some(c=>c.charCodeAt(0)<32||c.charCodeAt(0)===127)
 const save=async()=>{if(!valid)return;setBusy(true);setError('');try{const response=await adminApiRequest(`/api/admin/payroll/employees/${employeeId}/compensation-applicability`,{method:'POST',body:JSON.stringify({year:2026,sourceFingerprint,expectedRevision:Number(history[0]?.id||0),categories:answers,reference,confirmed,retirementEmployerOnlyConfirmed:retirementConfirmed,retirementStandard401kConfirmed:retirementConfirmed})}),json=await response.json();if(!response.ok){if(response.status===409){setStale(true);setConfirmed(false)}throw new Error(json.message||'Unable to save compensation review.')}await onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to save compensation review.')}finally{setBusy(false)}}
 const input='mt-1 block w-full rounded-lg border border-slate-300 bg-white p-2 font-normal'
 return <section aria-label="Compensation applicability review" className="space-y-3 border-t border-slate-200 pt-3"><h5 className="font-bold">Compensation applicability review</h5><p>Review each category for 2026. Applicable items still require detailed reporting treatment; recording this review does not approve tax forms.</p>{error?<p role="alert" className="text-red-700">{error}</p>:null}{ready?<fieldset disabled={busy||stale} className="space-y-3">{Object.entries(categories).map(([key,label])=><label key={key} className="block font-semibold">{label}<select aria-label={label} value={answers[key]||''} onChange={e=>{setAnswers(old=>({...old,[key]:e.target.value}));setConfirmed(false);setRetirementConfirmed(false)}} className={input}><option value="">Choose reviewed applicability</option>{Object.entries({...decisions,...(key==='retirement'?retirementDecision:{})}).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>)}{answers.retirement==='EMPLOYER_ONLY_PARTICIPATION'?<label className="flex items-start gap-2"><input type="checkbox" checked={retirementConfirmed} onChange={e=>{setRetirementConfirmed(e.target.checked);setConfirmed(false)}}/>The plan records establish active participation for box 13, with employer funding or defined-benefit eligibility only. There are no employee deferrals, Roth or after-tax contributions, distributions, make-up contributions, or other retirement amounts requiring W-2 reporting.</label>:null}{answers.retirement==='STANDARD_401K_DEFERRALS'?<label className="flex items-start gap-2"><input type="checkbox" checked={retirementConfirmed} onChange={e=>{setRetirementConfirmed(e.target.checked);setConfirmed(false)}}/>Retirement reporting consists only of the reconciled internal standard 401(k) employee deferrals. There are no other retirement amounts, prior-year make-up contributions, corrections, or reporting adjustments.</label>:null}<label className="block font-semibold">Compensation review evidence<input autoComplete="off" maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} className={input}/></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed every category against the referenced annual compensation records.</label><button type="button" disabled={!valid} onClick={()=>void save()} className="rounded-lg bg-slate-900 px-3 py-2 font-bold text-white disabled:opacity-50">Save compensation applicability</button></fieldset>:<p className="text-amber-900">Reconcile annual payroll inputs before reviewing compensation applicability.</p>}
 {stale?<p className="text-amber-900">Refresh annual preparation before reviewing again.</p>:null}<h6 className="font-bold">Compensation review history</h6>{history.length?history.map(item=><article key={item.id} className="space-y-2 rounded-lg bg-slate-50 p-3"><p className="font-semibold">{item.status} · Compensation review {item.id}</p><ul className="space-y-1">{Object.entries(categories).map(([key,label])=><li key={key}>{label}: {decisions[item.categories[key]]||(key==='retirement'&&retirementDecision[item.categories[key]]?retirementDecision[item.categories[key]]:'Unresolved')}</li>)}</ul><p className="break-words">{item.reference}</p><p className="text-xs text-slate-500">Reviewer {item.created_by} · {new Date(item.created_at).toLocaleString()}</p></article>):<p>No compensation applicability review recorded.</p>}</section>
}
