import {useRef,useState} from 'react'
import {payrollApi} from '../../utils/payrollApi'
import {workforceApi} from '../../utils/workforceApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
const money=(v:number)=>(v/100).toLocaleString('en-US',{style:'currency',currency:'USD'})
export default function CorrectionPaymentPreview({requestId,calculationId}:{requestId:number;calculationId:number}){
 const [periods,setPeriods]=useState<Array<Record<string,unknown>>|null>(null),[periodId,setPeriodId]=useState(''),[paymentDate,setPaymentDate]=useState('')
 const [source,setSource]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [result,setResult]=useState<Awaited<ReturnType<typeof workforceApi.correctionPaymentPreview>>|null>(null)
 const reference=useRef({key:'',id:''})
 const [reason,setReason]=useState(''),[authorized,setAuthorized]=useState(false),[saved,setSaved]=useState<number|null>(null)
 const invalidate=()=>{setResult(null);setConfirmed(false);setAuthorized(false);setSaved(null)}
 return <div className="mt-3 space-y-2 border-t pt-3">
 <button type="button" className={workforceButton} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setPeriods((await payrollApi.dashboard()).payPeriods)}catch(e){setError(e instanceof Error?e.message:'Unable to load payroll periods.')}finally{setBusy(false)}}}>Prepare correction payment</button>
 {error?<p role="alert" className="text-red-700">{error}</p>:null}
 {periods?<form className="space-y-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setResult(null);setAuthorized(false);setSaved(null);try{setResult(await workforceApi.correctionPaymentPreview(requestId,{calculationId,payPeriodId:Number(periodId),paymentDate,historyCompleteConfirmed:confirmed,historySource:source}))}catch(e){setError(e instanceof Error?e.message:'Unable to preview correction payment.')}finally{setBusy(false)}}}><fieldset disabled={busy} className="space-y-2"><p>Add the correction to a later regular payroll. This preview does not schedule or pay it.</p><label className="block">Correction processing payroll<select required aria-label="Correction processing payroll" className={workforceInput} value={periodId} onChange={e=>{invalidate();setPeriodId(e.target.value);const p=periods.find(p=>String(p.id)===e.target.value);setPaymentDate(p?String(p.pay_date).slice(0,10):'')}}><option value="">Choose a later payroll</option>{periods.filter(p=>p.status!=='VOID').map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.period_start).slice(0,10)} through {String(p.period_end).slice(0,10)}</option>)}</select></label><label className="block">Correction payment date<input type="date" required className={workforceInput} value={paymentDate} onChange={e=>{invalidate();setPaymentDate(e.target.value)}}/></label><label className="block">Correction wage-history source<textarea required minLength={20} maxLength={2000} className={workforceInput} value={source} onChange={e=>{invalidate();setSource(e.target.value)}}/></label><label className="flex gap-2"><input type="checkbox" required checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);setResult(null);setSaved(null);setAuthorized(false)}}/>I verified complete employer and related-employer wage history through this payment date.</label><button className={workforceButton}>Preview correction taxes</button></fieldset></form>:null}
 {result?<div role="status" className="space-y-2"><p>Processing payroll: {result.periodStart} through {result.periodEnd}. Payment date: {result.paymentDate}.</p><p className="font-bold">Additional take-home pay: {money(result.delta.netPayCents)}</p><p>Additional gross: {money(result.delta.grossPayCents)}</p><p>Prior-period correction: {money(result.priorWageCorrectionCents)}. Target-period wage change: {money(result.currentWageReclassificationCents)}.</p><p>Target regular hours: {(result.targetHours.before.regularMinutes/60).toFixed(2)} → {(result.targetHours.after.regularMinutes/60).toFixed(2)}. Target overtime hours: {(result.targetHours.before.overtimeMinutes/60).toFixed(2)} → {(result.targetHours.after.overtimeMinutes/60).toFixed(2)}.</p><p>Federal withholding change: {money(result.delta.federalIncomeTaxCents)}. Maryland withholding change: {money(result.delta.stateIncomeTaxCents)}.</p><p>Employee FICA change: {money(result.delta.socialSecurityTaxCents+result.delta.medicareTaxCents+result.delta.additionalMedicareTaxCents)}.</p><p>Employer tax change: {money(result.delta.employerSocialSecurityTaxCents+result.delta.employerMedicareTaxCents+result.delta.futaTaxCents+result.delta.mdUiTaxCents)}.</p><p>Combined payroll gross: {money(result.after.grossPayCents)}. Combined take-home pay: {money(result.after.netPayCents)}.</p><p>Current payroll counts {(result.currentWorkedMinutes/60).toFixed(2)} worked hours and {result.currentLeaveAccrualMinutes} earned leave minutes. The preview includes the corrected leave context.</p><p>Target payroll leave: {result.targetLeave.before.accrualMinutes} → {result.targetLeave.after.accrualMinutes} minutes. Historical credit change: {result.correctionLeave.creditDifferenceMinutes} minutes. Combined credit change: {result.targetLeave.combinedCreditDifferenceMinutes} minutes.</p><p>All leave changes remain unapplied.</p><p>{saved?'Payment authorization retained. Settlement is still required.':'Preview only. Payment authorization and settlement are still required.'}</p></div>:null}
 {result&&!saved?<form className="space-y-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const body={...result.input,fingerprint:result.fingerprint,reason,confirmed:authorized},key=JSON.stringify(body);if(reference.current.key!==key)reference.current={key,id:crypto.randomUUID()};try{const r=await workforceApi.authorizeCorrectionPayment(requestId,{...body,requestKey:reference.current.id});setSaved(r.id)}catch(e){setError(e instanceof Error?e.message:'Unable to save payment authorization.')}finally{setBusy(false)}}}><fieldset disabled={busy} className="space-y-2"><label className="block">Payment authorization reason<textarea required minLength={20} maxLength={2000} className={workforceInput} value={reason} onChange={e=>{setReason(e.target.value);setAuthorized(false)}}/></label><label className="flex gap-2"><input required type="checkbox" checked={authorized} onChange={e=>setAuthorized(e.target.checked)}/>I authorize the reviewed correction for this payroll and payment date.</label><button className={workforceButton}>Authorize correction payment</button></fieldset></form>:null}
 {saved?<p role="status">Payment authorization #{saved} retained. Settlement remains required.</p>:null}
 </div>
}
