import {useCallback,useEffect,useState} from 'react'
import {getApiUrl} from '../../utils/api'
import {getPayrollEmployeeSession} from '../../utils/employeePayrollApi'
import W4PdfReview from './W4PdfReview'
type Proposal={fingerprint:string;planName:string;optionLabel:string;monthlyCents:number;effectiveOn:string;effectiveThrough:string;electionDeadline:string;employeeExplanation:string;employeeTerms:string;electionChangesTerms:string;terms:string;disclosureId:string;documentSha256:string;documentPages:number}
type Plan={planId:string;planName:string;onboardingCycle:number;offers:Proposal[];issues:string[];history:{id:string;revision:number;onboarding_cycle:number;election:{action:string;signature:string;signedAt:string;proposal:Proposal}}[]}
async function call(path:string,body?:string){const r=await fetch(`${getApiUrl()}/api/payroll/employee${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${getPayrollEmployeeSession()||''}`,...(body?{'Content-Type':'application/json'}:{})},body});if(!r.ok){const b=await r.json().catch(()=>({}));throw Object.assign(new Error(b.message||'Unable to load your health election.'),{status:r.status})}return r}
async function pdf(path:string,expectedHash:string){const bytes=new Uint8Array(await(await call(path)).arrayBuffer()),digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');if(digest!==expectedHash)throw new Error('The disclosure does not match your election. Refresh before signing.');let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary)}
function Election({plan,readIssue,onSaved,readOnly}:{plan:Plan;readIssue:boolean;onSaved:()=>Promise<void>;readOnly:boolean}){
 const path=`/health-plans/${encodeURIComponent(plan.planId)}/election`
 const [basis,setBasis]=useState<{proposal:Proposal;revision:number}|null>(null),[document,setDocument]=useState<{base64:string;proposal:Proposal;historical:boolean}|null>(null),[action,setAction]=useState(''),[signature,setSignature]=useState(''),[checks,setChecks]=useState({disclosure:false,rules:false,signature:false}),[busy,setBusy]=useState(false),[pending,setPending]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const revision=plan.history.find(row=>row.onboarding_cycle===plan.onboardingCycle)?.revision||0
 const stale=!!basis&&(!plan.offers.some(p=>p.fingerprint===basis.proposal.fingerprint)||basis.revision!==revision)
 const reset=()=>setChecks({disclosure:false,rules:false,signature:false})
 const begin=async(proposal:Proposal)=>{setBusy(true);setError('');setNotice('');setBasis({proposal,revision});setDocument(null);reset();try{const base64=await pdf(`/health-plans/${encodeURIComponent(plan.planId)}/disclosure/document?${new URLSearchParams({effectiveOn:proposal.effectiveOn,disclosureId:proposal.disclosureId})}`,proposal.documentSha256);setDocument({base64,proposal,historical:false})}catch(e){setError(e instanceof Error?e.message:'Unable to open disclosure.')}finally{setBusy(false)}}
 const history=async(row:Plan['history'][number])=>{setBusy(true);setError('');reset();try{const base64=await pdf(`${path}/${row.id}/document`,row.election.proposal.documentSha256);setDocument({base64,proposal:row.election.proposal,historical:true})}catch(e){setError(e instanceof Error?e.message:'Unable to open retained disclosure.')}finally{setBusy(false)}}
 const save=async()=>{if(!basis)return;setBusy(true);setError('');setNotice('');const body=pending||JSON.stringify({requestKey:crypto.randomUUID(),expectedRevision:basis.revision,proposalFingerprint:basis.proposal.fingerprint,action,signature,confirmed:checks.signature,disclosureConfirmed:checks.disclosure,electionRulesConfirmed:checks.rules});setPending(body)
  try{await call(path,body);setPending(null);setBasis(null);reset();setNotice('Your signed health election was retained. Payroll will recheck eligibility and authorization before collecting premiums.');await onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to retain your election.');if(e instanceof Error&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500){setPending(null);reset();try{await onSaved()}catch{/* Keep the signed draft visible for review. */}}}finally{setBusy(false)}}
 const currentPdf=!!basis&&!!document&&!document.historical&&document.proposal.fingerprint===basis.proposal.fingerprint
 const disabled=busy||!!pending||stale||readIssue||readOnly
 return <article aria-label={`Health election ${plan.planName}`} className="min-w-0 space-y-3 rounded-xl border p-3">
  <h4 className="font-bold">{plan.planName}</h4>{plan.issues.map(issue=><p role="alert" key={issue}>{issue}</p>)}
  {!plan.offers.length?<p>No unsigned election window is currently available. Your retained choices appear below.</p>:null}
  {plan.offers.map(proposal=><button type="button" key={proposal.fingerprint} disabled={busy||!!pending||readIssue||readOnly} onClick={()=>void begin(proposal)} className="rounded border px-3 py-2">Review health election starting {proposal.effectiveOn}</button>)}
  {error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}
  {stale?<p role="alert">Your health election terms or history changed. Your draft is preserved. Review the current election before signing.</p>:null}
  {document?<W4PdfReview key={`${document.proposal.fingerprint}-${document.historical}`} pdfBase64={document.base64} formName="health plan disclosure" pageCount={document.proposal.documentPages} editionLabel="" official={false} reviewTitle={document.historical?'Your retained health plan disclosure':'Read your health plan disclosure'}/>:null}
  {basis?<><div className="space-y-2 whitespace-pre-wrap break-words"><p>{basis.proposal.optionLabel} · ${(basis.proposal.monthlyCents/100).toFixed(2)} per month</p><p>Effective {basis.proposal.effectiveOn} through {basis.proposal.effectiveThrough}. Sign by {basis.proposal.electionDeadline}.</p><p>{basis.proposal.employeeExplanation}</p><p>{basis.proposal.employeeTerms}</p><p>{basis.proposal.electionChangesTerms}</p><p>{basis.proposal.terms}</p></div>
   <fieldset disabled={disabled} className="space-y-3"><legend className="font-bold">My health salary-reduction election</legend>
    <label className="block">Health election choice<select aria-label="Health election choice" value={action} onChange={e=>{setAction(e.target.value);reset()}} className="block w-full rounded border p-2"><option value="">Choose your election</option><option value="ELECT">Elect pretax salary reduction</option><option value="DECLINE">Decline this election</option></select></label>
    <label className="block">Health election signature<input value={signature} maxLength={200} onChange={e=>{setSignature(e.target.value);reset()}} className="block w-full rounded border p-2"/></label>
    <label className="flex items-start gap-2"><input type="checkbox" checked={checks.disclosure} disabled={!currentPdf} onChange={e=>setChecks({...checks,disclosure:e.target.checked})}/><span>I read the complete health plan disclosure and the terms shown here.</span></label>
    <label className="flex items-start gap-2"><input type="checkbox" checked={checks.rules} onChange={e=>setChecks({...checks,rules:e.target.checked})}/><span>I understand the election period and the plan rules governing later changes.</span></label>
    <label className="flex items-start gap-2"><input type="checkbox" checked={checks.signature} onChange={e=>setChecks({...checks,signature:e.target.checked})}/><span>I confirm my election with my typed name as my electronic signature.</span></label>
    <button type="button" disabled={!currentPdf||!action||signature.trim().length<2||!Object.values(checks).every(Boolean)} onClick={()=>void save()} className="rounded border px-3 py-2 font-bold">Sign health election</button>
   </fieldset></>:null}
  {pending?<button type="button" disabled={busy||readOnly} onClick={()=>void save()} className="rounded border px-3 py-2">Retry original health election</button>:null}
  {plan.history.length?<details><summary>My signed health election history</summary>{plan.history.map(row=><div key={row.id} className="my-3 space-y-2 whitespace-pre-wrap break-words"><p>Revision {row.revision} · hiring cycle {row.onboarding_cycle} · {row.election.action==='ELECT'?'Elected salary reduction':'Declined election'}</p><p>Signed by {row.election.signature} · {row.election.signedAt}</p><p>{row.election.proposal.terms}</p><button type="button" disabled={busy||!!pending} onClick={()=>void history(row)} className="font-semibold underline">Read signed disclosure · revision {row.revision} · cycle {row.onboarding_cycle}</button></div>)}</details>:null}
 </article>
}
export default function EmployeeHealthElection({readOnly=false}:{readOnly?:boolean}){
 const [plans,setPlans]=useState<Plan[]>([]),[error,setError]=useState(''),[loaded,setLoaded]=useState(false)
 const read=useCallback(async()=>{const r=await call('/health-elections'),body=await r.json();return body.data.plans as Plan[]},[])
 const refresh=async()=>{try{setPlans(await read());setLoaded(true);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to refresh health elections.')}}
 useEffect(()=>{let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const next=await read();if(live){setPlans(next);setLoaded(true);setError('')}}catch(e){if(live)setError(e instanceof Error?e.message:'Unable to load health elections.')}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[read])
 return <section aria-label="My pretax health elections" className="min-w-0 space-y-3 rounded-xl border bg-white p-3 text-sm"><h3 className="text-lg font-bold">My pretax health elections</h3><p>Read your plan disclosure and sign your salary-reduction choice here. Your hiring administrator reviews eligibility and election dates.</p><button type="button" onClick={()=>void refresh()} className="rounded border px-3 py-2">Refresh health elections</button>{error?<p role="alert">{error}</p>:null}{loaded&&!plans.length?<p>No pretax health coverage or retained health election is available yet.</p>:null}{plans.map(plan=><Election key={plan.planId} plan={plan} readIssue={!!error} onSaved={refresh} readOnly={readOnly}/>)}</section>
}
