import CompensationHistory from './CompensationHistory'
import { useState } from 'react'
import { payrollApi, type PayrollEmployee } from '../../utils/payrollApi'
import { workforceInput, workforceButton } from './OnboardingWorkspace'
export default function EmployeePaySettings({employee,onChanged}:{employee:PayrollEmployee;onChanged:()=>Promise<void>}) {
 const [form,setForm]=useState({preferredName:employee.preferredName,jobTitle:employee.jobTitle,personalEmail:employee.personalEmail,phone:employee.phone,primaryWorkLocation:employee.primaryWorkLocation,hourlyRate:(Number(employee.hourlyRateCents)/100).toFixed(2),employmentStatus:employee.employmentStatus,notes:employee.notes})
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const set=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}))
 return <><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Employee pay & work details</h2><p className="mt-2 text-sm text-slate-600">{employee.legalFirstName} {employee.legalLastName} · {employee.employeeNumber}</p>{error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}{notice?<p role="status" className="mt-3 text-sm text-emerald-700">{notice}</p>:null}<form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await payrollApi.updateEmployee(employee.id,{...form,...(employee.employmentStatus==='ONBOARDING'&&employee.payType==='HOURLY'?{hourlyRateCents:Math.round(Number(form.hourlyRate)*100)}:{})});await onChanged();setNotice('Employee details saved and audited.')}catch(e){setError(e instanceof Error?e.message:'Unable to save employee')}finally{setBusy(false)}}}>
 {([['preferredName','Preferred name'],['jobTitle','Job title'],['personalEmail','Email'],['phone','Phone'],['primaryWorkLocation','Work location'],['hourlyRate','Hourly rate ($)']] as const).filter(([key])=>key!=='hourlyRate'||employee.payType==='HOURLY').map(([key,label])=><label key={key} className="text-sm font-bold">{label}<input disabled={(key==='hourlyRate'&&employee.employmentStatus!=='ONBOARDING')||(key==='jobTitle'&&employee.payType==='SALARY'&&!!employee.salaryReview)} required={['jobTitle','personalEmail','hourlyRate'].includes(key)} type={key==='hourlyRate'?'number':key==='personalEmail'?'email':'text'} min={key==='hourlyRate'?'0.01':undefined} step={key==='hourlyRate'?'0.01':undefined} value={form[key]} onChange={e=>set(key,e.target.value)} className={workforceInput}/></label>)}
 <label className="text-sm font-bold">Employment status<select value={form.employmentStatus} onChange={e=>set('employmentStatus',e.target.value)} className={workforceInput}><option value="ONBOARDING" disabled={employee.employmentStatus!=='ONBOARDING'}>Onboarding</option><option value="ACTIVE" disabled={employee.employmentStatus==='ONBOARDING'}>Active</option><option value="LEAVE">On leave</option><option value="TERMINATED">Terminated</option></select></label><label className="text-sm font-bold sm:col-span-2">Administrative notes<textarea rows={3} value={form.notes} onChange={e=>set('notes',e.target.value)} className={workforceInput} placeholder="Role or pay-change context; no identity or bank numbers" /></label><p className="text-xs text-slate-500 sm:col-span-2">Initial rates can be edited during onboarding before any time is recorded. After activation, use Schedule pay change below.</p><button disabled={busy} className={workforceButton}>Save employee details</button></form></section>{employee.payType==='HOURLY'?<CompensationHistory employeeId={employee.id} canSchedule={['ACTIVE','LEAVE'].includes(employee.employmentStatus)} onChanged={onChanged}/>:null}</>
}
