import {useEffect,useRef,useState} from 'react'
import {employeePayrollApi,type RetirementEmployeePlan,type RetirementProposal} from '../../utils/employeePayrollApi'
const inputClass='mt-1 block w-full rounded-lg border border-slate-300 p-2'
const units=(value:string)=>{if(!/^\d+(\.\d{1,2})?$/.test(value))throw new Error('Use nonnegative amounts with no more than two decimal places.');const [whole,fraction='']=value.split('.'),n=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(n))throw new Error('Contribution amount is too large.');return n}
export function RetirementElectionHistory({plan}:{plan:RetirementEmployeePlan}){
 return <div className="space-y-2">{plan.history.map(row=><details key={row.id} className="rounded border p-3"><summary>Election revision {row.revision} · {row.election.action==='DECLINE'?'Declined / stopped election':'Contributions elected'} · {row.election.effectiveOn}</summary><p>Employment cycle {row.onboardingCycle} · Signed by {row.election.signature} on {new Date(row.createdAt).toLocaleString()}</p>{row.election.action==='ELECT'?<p>Pretax: {(row.election.pretax/100).toFixed(2)}{row.election.method==='PERCENTAGE'?'%':' dollars per regular payroll'} · Roth: {(row.election.roth/100).toFixed(2)}{row.election.method==='PERCENTAGE'?'%':' dollars per regular payroll'}</p>:null}<p>Signed choice retained. Regular payroll checks its effective date, plan review and contribution limits. Your pay statement shows completed deductions; this election does not confirm provider receipt.</p><p className="whitespace-pre-wrap break-words">Signed terms: {row.election.proposal.employeeTerms}</p></details>)}</div>
}
function ElectionForm({plan,onSaved,onBusy,readIssue}:{plan:RetirementEmployeePlan;onSaved:()=>Promise<void>;onBusy:(busy:boolean)=>void;readIssue:boolean}){
 const [basis,setBasis]=useState<{proposal:RetirementProposal;revision:number}|null>(null),[action,setAction]=useState(''),[method,setMethod]=useState(''),[pretax,setPretax]=useState('0'),[roth,setRoth]=useState('0'),[date,setDate]=useState(''),[signature,setSignature]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),pending=useRef<{body:string;key:string}|null>(null)
 const stale=!basis||basis.proposal.fingerprint!==plan.proposal?.fingerprint||basis.revision!==(plan.history[0]?.revision||0)
 const begin=()=>{if(!plan.proposal)return;setBasis({proposal:plan.proposal,revision:plan.history[0]?.revision||0});setDate(plan.proposal.earliestEffectiveOn);if(!plan.proposal.allowsPretax)setPretax('0');if(!plan.proposal.allowsRoth)setRoth('0');if(!plan.proposal.methods.includes(method))setMethod('');setConfirmed(false);setError('');setMessage('');pending.current=null}
 const save=async(retry=false)=>{setBusy(true);onBusy(true);setError('');setMessage('');try{
  const input=retry&&pending.current?JSON.parse(pending.current.body):{expectedRevision:basis?.revision,proposalFingerprint:basis?.proposal.fingerprint,action,method,pretax:action==='DECLINE'?0:units(pretax),roth:action==='DECLINE'?0:units(roth),effectiveOn:date,signature,confirmed},body=JSON.stringify(input)
  if(pending.current?.body!==body)pending.current={body,key:crypto.randomUUID()}
  await employeePayrollApi.saveRetirementElection(plan.planId,{...input,requestKey:pending.current.key});await onSaved();pending.current=null;setBasis(null);setConfirmed(false);setMessage('Your signed choice was retained. Payroll processing setup is still pending.')
 }catch(e){setError(e instanceof Error?e.message:'Unable to save your election.')}finally{setBusy(false);onBusy(false)}}
 const proposal=basis?.proposal
 return <article className="space-y-3 rounded-xl border p-4"><h4 className="font-bold">{plan.planName}</h4><p>{plan.explanation}</p>{plan.proposal?<button type="button" disabled={busy||readIssue} onClick={begin} className="rounded border px-3 py-2">Review current election terms</button>:null}{error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}{basis&&stale?<p role="alert">Your election terms or history changed. Your draft is preserved. Review the current terms before signing.</p>:null}
 {proposal?<><div className="space-y-2 whitespace-pre-wrap break-words"><p>{proposal.employeeTerms}</p><p>{proposal.employeeExplanation}</p><p>Eligibility: {proposal.eligibilityTerms}</p><p>Eligible compensation: {proposal.compensationTerms}</p><p>Earliest effective date: {proposal.earliestEffectiveOn}. This choice will not change already approved payroll.</p></div><fieldset disabled={busy||stale||readIssue} className="space-y-3"><legend className="font-bold">My retirement election</legend><label className="block">Retirement election choice<select className={inputClass} value={action} onChange={e=>{setAction(e.target.value);setConfirmed(false)}}><option value="">Choose an election</option><option value="ELECT">Elect or change contributions</option><option value="DECLINE">Decline or stop this election</option></select></label>
 {action==='ELECT'?<><label className="block">Contribution method<select className={inputClass} value={method} onChange={e=>{setMethod(e.target.value);setConfirmed(false)}}><option value="">Choose a permitted method</option>{proposal.methods.map(value=><option key={value} value={value}>{value==='PERCENTAGE'?'Percentage of eligible compensation':'Fixed dollars per regular payroll'}</option>)}</select></label>{proposal.allowsPretax?<label className="block">Pretax contribution {method==='PERCENTAGE'?'(%)':'($)'}<input className={inputClass} inputMode="decimal" value={pretax} onChange={e=>{setPretax(e.target.value);setConfirmed(false)}}/></label>:null}{proposal.allowsRoth?<label className="block">Roth contribution {method==='PERCENTAGE'?'(%)':'($)'}<input className={inputClass} inputMode="decimal" value={roth} onChange={e=>{setRoth(e.target.value);setConfirmed(false)}}/></label>:null}</>:null}
 <label className="block">Election effective date<input type="date" min={proposal.earliestEffectiveOn} value={date} onChange={e=>{setDate(e.target.value);setConfirmed(false)}} className={inputClass}/></label><label className="block">Retirement election signature<input value={signature} maxLength={200} onChange={e=>{setSignature(e.target.value);setConfirmed(false)}} className={inputClass}/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I read these terms and confirm this retirement choice with my typed name.</label><button type="button" disabled={!confirmed} onClick={()=>void save()} className="rounded border px-3 py-2 font-bold">Sign retirement election</button></fieldset></>:null}
 {pending.current?<button type="button" disabled={busy} onClick={()=>void save(true)} className="rounded border px-3 py-2">Retry original signed election</button>:null}<RetirementElectionHistory plan={plan}/></article>
}
export default function EmployeeRetirement(){
 const [plans,setPlans]=useState<RetirementEmployeePlan[]>([]),[loaded,setLoaded]=useState(false),[issue,setIssue]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0)
 const reload=async()=>{const data=await employeePayrollApi.retirement();setPlans(data.plans);setLoaded(true);setIssue('')}
 useEffect(()=>{if(busy)return;let live=true,inFlight=false;const read=async()=>{if(inFlight)return;inFlight=true;try{const data=await employeePayrollApi.retirement();if(live){setPlans(data.plans);setLoaded(true);setIssue('')}}catch(e){if(live)setIssue(e instanceof Error?e.message:'Unable to load your retirement information.')}finally{inFlight=false}};void read();const timer=setInterval(()=>void read(),30000);return()=>{live=false;clearInterval(timer)}},[busy,refresh])
 return <section aria-label="My retirement elections" className="space-y-3 rounded-2xl border bg-white p-5 text-sm"><h3 className="text-lg font-black">My retirement elections</h3><p>Review eligibility, sign your choice and keep its history here. Contribution processing and provider enrollment require completed payroll setup.</p><button type="button" disabled={busy} onClick={()=>setRefresh(value=>value+1)} className="rounded border px-3 py-2">Refresh retirement elections</button>{issue?<p role="alert">{issue} Automatic refresh will retry.</p>:null}{loaded&&!plans.length?<p>Your hiring administrator has not retained a retirement eligibility review for you yet.</p>:null}{plans.map(plan=><ElectionForm key={plan.planId} plan={plan} onSaved={reload} onBusy={setBusy} readIssue={!!issue}/>)}</section>
}
