import {useState} from 'react'
import {getApiUrl} from '../../utils/api'
import {getPayrollEmployeeSession} from '../../utils/employeePayrollApi'
type Data={destinationId:number;status:string;canAuthorize?:boolean;fingerprint?:string;terms?:{employer:string;account:{holderName:string;accountType:string;accountLast4:string;mode:string};authorization:string;choice:string;withdrawal:string};history:Array<{id:string;decision:string;created_at:string;receipt:unknown}>}
const request=(body?:unknown)=>fetch(`${getApiUrl()}/api/payroll/employee/payment-authorization`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${getPayrollEmployeeSession()||''}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined})
export default function EmployeePaymentAuthorization(){
 const [data,setData]=useState<Data|null>(null),[signature,setSignature]=useState(''),[confirmed,setConfirmed]=useState(false),[withdraw,setWithdraw]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=async()=>{setData(null);setSignature('');setConfirmed(false);setWithdraw(false);setBusy(true);setError('');try{const response=await request(),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to load authorization.');setData(json.data)}catch(e){setError(e instanceof Error?e.message:'Unable to load authorization.')}finally{setBusy(false)}}
 const save=async(decision:'AUTHORIZE'|'WITHDRAW')=>{if(!data||busy||(decision==='AUTHORIZE'?!confirmed:!withdraw))return;setBusy(true);setError('');setMessage('');try{const response=await request({destinationId:data.destinationId,expectedRevision:Number(data.history[0]?.id||0),decision,signature,fingerprint:data.fingerprint,confirmed:true}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to save authorization.');await load();setMessage(decision==='AUTHORIZE'?'Direct-deposit authorization recorded. This does not mean a payment has been sent.':'Authorization withdrawn for payments not yet submitted.')}catch(e){setData(null);setError(e instanceof Error?e.message:'Unable to save authorization.')}finally{setConfirmed(false);setWithdraw(false);setBusy(false)}}
 const download=(record:Data['history'][number])=>{const url=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'text/plain'})),link=document.createElement('a');link.href=url;link.download=`direct-deposit-authorization-${record.id}.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section aria-label="Your direct deposit authorization" className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Your direct deposit authorization</h2><button type="button" disabled={busy} className="font-bold underline" onClick={()=>void load()}>Review direct deposit account</button>{error?<p role="alert" className="text-red-700">{error}</p>:null}{message?<p role="status">{message}</p>:null}{data?<><p>{data.status.replaceAll('_',' ')}</p>{data.terms?<><p>{data.terms.employer} · {data.terms.account.holderName} · {data.terms.account.accountType} ending {data.terms.account.accountLast4} · {data.terms.account.mode}</p><p>{data.terms.authorization}</p><p>{data.terms.choice}</p><p>{data.terms.withdrawal}</p>{data.canAuthorize?<fieldset disabled={busy} className="space-y-3"><legend className="font-bold">Authorize this account</legend><label className="block">Your name as signature<input className="block w-full rounded border p-2" maxLength={200} value={signature} onChange={e=>{setSignature(e.target.value);setConfirmed(false)}} /></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} />I reviewed this account and agree to the authorization above.</label><button type="button" disabled={!confirmed||signature.trim().length<2} className="rounded bg-slate-900 p-2 font-bold text-white disabled:opacity-50" onClick={()=>void save('AUTHORIZE')}>Authorize direct deposit</button></fieldset>:null}<fieldset disabled={busy} className="space-y-2"><legend className="font-bold">Withdraw authorization</legend><label className="flex gap-2"><input type="checkbox" checked={withdraw} onChange={e=>setWithdraw(e.target.checked)} />Stop using this account for payments not yet submitted.</label><button type="button" disabled={!withdraw} className="font-bold underline" onClick={()=>void save('WITHDRAW')}>Withdraw direct deposit authorization</button></fieldset></>:<p>Payroll has not linked a bank account for review.</p>}<h3 className="font-bold">Authorization history</h3>{data.history.map(record=><p key={record.id}>{record.decision} · {new Date(record.created_at).toLocaleString()} · <button className="underline" type="button" onClick={()=>download(record)}>Download confirmation {record.id}</button></p>)}</>:null}</section>
}
