import {useState} from 'react'
import {employeePayrollApi,type EmployeeFilingIdentity} from '../../utils/employeePayrollApi'
export default function EmployeeFilingIdentityReview(){
 const [identity,setIdentity]=useState<EmployeeFilingIdentity|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=async()=>{setIdentity(null);setLoaded(false);setBusy(true);setConfirmed(false);setError('');setMessage('');try{setIdentity(await employeePayrollApi.filingIdentity());setLoaded(true)}catch(e){setError(e instanceof Error?e.message:'Unable to load filing details.')}finally{setBusy(false)}}
 const review=async(decision:string)=>{if(!identity||!confirmed)return;setBusy(true);setError('');try{await employeePayrollApi.reviewFilingIdentity(identity.revision,decision);await load();setMessage(decision==='CONFIRMED'?'Your review was saved.':'Correction requested. Contact your hiring administrator to provide the corrected details securely.')}catch(e){setIdentity(null);setLoaded(false);setConfirmed(false);setError(e instanceof Error?e.message:'Unable to save your review.')}finally{setBusy(false)}}
 return <section aria-label="My filing identity" className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5 text-sm"><h2 className="text-lg font-bold">My filing identity</h2><p>Review the legal name, mailing address and identifier ending held for your tax documents. Your full identifier is hidden.</p>
 <button type="button" disabled={busy} onClick={()=>void load()} className="rounded-lg border border-slate-300 px-3 py-2 font-bold disabled:opacity-50">{busy?'Working…':'Review my filing details'}</button>
 {error?<p role="alert" className="text-red-700">{error}</p>:null}{message?<p role="status" className="text-emerald-800">{message}</p>:null}
 {loaded&&!identity?<p>Your hiring administrator has not recorded a filing identity yet.</p>:null}
 {identity?<><div className="space-y-1 rounded-lg bg-slate-50 p-3"><p className="font-bold">{[identity.firstName,identity.middleName,identity.lastName,identity.suffix].filter(Boolean).join(' ')}</p><p>{identity.address.line1}</p>{identity.address.line2?<p>{identity.address.line2}</p>:null}<p>{identity.address.city}, {identity.address.state} {identity.address.postalCode}</p><p>Identifier ending {identity.identifierLast4}</p><p>Revision {identity.revision}</p></div>
 <p>{identity.review?.decision==='CONFIRMED'?'You confirmed the displayed details.':identity.review?.decision==='CORRECTION_REQUESTED'?'You requested a correction. Contact your hiring administrator.':'Please review these details.'}</p>
 <label className="flex items-start gap-2"><input type="checkbox" disabled={busy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the name, address and identifier ending shown above.</label>
 <div className="flex flex-wrap gap-2"><button type="button" disabled={busy||!confirmed} onClick={()=>void review('CONFIRMED')} className="rounded-lg bg-slate-900 px-3 py-2 font-bold text-white disabled:opacity-50">These details are correct</button><button type="button" disabled={busy||!confirmed} onClick={()=>void review('CORRECTION_REQUESTED')} className="rounded-lg border border-slate-300 px-3 py-2 font-bold disabled:opacity-50">Request a correction</button></div></>:null}</section>
}
