import {useState} from 'react'
import {workforceApi,type BenefitsElection,type BenefitPlan} from '../../utils/workforceApi'
const input='mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm'
export default function EmployeeBenefitsChoice({saved,policy,plans,cycle,readOnly,busy,act}:{saved:BenefitsElection|null;policy:string;plans:BenefitPlan[];cycle:number;readOnly:boolean;busy:boolean;act:(work:()=>Promise<unknown>,message:string)=>Promise<void>}){
 const [choice,setChoice]=useState(saved?.choice||''),[signature,setSignature]=useState(saved?.signature||''),[confirmed,setConfirmed]=useState(false),[requestKey]=useState(()=>crypto.randomUUID())
 const [selections,setSelections]=useState(()=>plans.map(p=>({planId:p.id,optionId:saved?.selections?.find(s=>s.planId===p.id)?.optionId||''})))
 const selectedChoice=plans.length?(selections.some(s=>s.optionId&&s.optionId!=='WAIVE')?'ENROLL':'WAIVE'):choice
 const selectionText=(s:NonNullable<BenefitsElection['selections']>[number])=>`${s.planName}: ${s.optionId==='WAIVE'?'Declined':`${s.optionLabel} — employee $${(Number(s.employeeCostCents)/100).toFixed(2)}/month; employer $${(Number(s.employerCostCents)/100).toFixed(2)}/month (${s.taxTreatment?.toLowerCase().replaceAll('_',' ')})`}`
 const current=saved?.policyTerms===policy
 return <section aria-label="Employee benefits choice" className="mt-4 space-y-3 rounded-xl border border-slate-200 p-3 text-sm">
  <h4 className="font-bold">Employee benefits choice</h4>
  {saved?<div className="space-y-2"><p className="font-semibold">{saved.choice==='ENROLL'?'Enrollment requested':'Offered benefits declined'} · {saved.signature}</p><p>Submitted {new Date(saved.submittedAt).toLocaleString()}</p>{saved.selections?.map(s=><p key={s.planId}>{selectionText(s)}</p>)}{!current?<p className="text-amber-900">The published benefits terms changed. A new signed choice is required for enrollment or waiver review.</p>:null}<details><summary className="cursor-pointer font-semibold">Terms saved with this choice</summary><p className="mt-2 whitespace-pre-wrap">{saved.policyTerms}</p></details><button type="button" className="font-bold underline" onClick={()=>{const text=`Benefits choice: ${saved.choice==='ENROLL'?'Enrollment requested':'Offered benefits declined'}\nSigned by: ${saved.signature}\nSubmitted: ${saved.submittedAt}\nOnboarding cycle: ${cycle}\n${saved.selections?.map(selectionText).join('\n')||''}\n\n${saved.policyTerms}\n\nThis is the saved employee choice. Eligibility and coverage are reviewed separately.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`benefits-choice-${saved.submissionId}.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Download benefits choice copy</button></div>:<p>No signed employee choice has been submitted.</p>}
  {!readOnly&&policy?<form className="space-y-3" onSubmit={e=>{e.preventDefault();void act(()=>workforceApi.benefitsElection({choice:selectedChoice,selections,signature,confirmed,displayedTerms:policy,requestKey,onboardingCycle:cycle}),'Benefits choice submitted to your hiring admin.')}}>
   <p className="max-h-80 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-3">{policy}</p>
   <p>Your choice applies to the offering described above. Your hiring admin reviews eligibility and confirms enrollment; submitting does not start or cancel coverage.</p>
   {plans.length?plans.map((p,index)=><div key={p.id}><h5 className="font-bold">{p.name}</h5><p className="whitespace-pre-wrap">{p.description}</p><label className="block font-semibold">Coverage choice<select aria-label={`Plan ${index+1} coverage choice`} required className={input} value={selections.find(s=>s.planId===p.id)?.optionId||''} onChange={e=>{setSelections(previous=>previous.map(s=>s.planId===p.id?{...s,optionId:e.target.value}:s));setConfirmed(false)}}><option value="">Choose coverage or decline</option><option value="WAIVE">Decline this plan</option>{p.options.map(o=><option key={o.id} value={o.id}>{o.label} — ${(o.employeeCostCents/100).toFixed(2)}/month employee cost</option>)}</select></label></div>):<label className="block font-semibold">Your benefits choice<select aria-label="Your benefits choice" className={input} required value={choice} onChange={e=>{setChoice(e.target.value);setConfirmed(false)}}><option value="">Choose an option</option><option value="ENROLL">Request enrollment in the offered benefits</option><option value="WAIVE">Decline the offered benefits</option></select></label>}
   <label className="block font-semibold">Benefits choice signature<input className={input} maxLength={200} required value={signature} onChange={e=>{setSignature(e.target.value);setConfirmed(false)}}/></label>
   <label className="flex items-start gap-2"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I read the displayed benefits offering and confirm this choice with my typed name.</label>
   <button disabled={busy} className="rounded-xl bg-slate-950 px-4 py-2.5 font-bold text-white disabled:opacity-40">Submit benefits choice</button>
  </form>:!readOnly?<p>Your hiring admin must publish the benefits offering before you can submit a choice.</p>:null}
 </section>
}
