import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
export type HealthClassificationHistory={id:string;disposition:string;reportable_cost_cents:string|null;reference:string;created_by:string;created_at:string;status:string}
const labels:Record<string,string>={REPORT:'Report verified coverage cost',RELIEF_USED:'Use employer reporting relief',NO_APPLICABLE_COVERAGE:'No applicable coverage',UNRESOLVED:'Classification unresolved'}
const money=(value:string)=>{const cents=BigInt(value);return `$${cents/100n}.${String(cents%100n).padStart(2,'0')}`}
export default function EmployeeHealthClassification({employeeId,sourceFingerprint,ready,determination,history,onSaved}:{employeeId:number;sourceFingerprint:string;ready:boolean;determination?:{id:string;disposition:string};history:HealthClassificationHistory[];onSaved:()=>Promise<void>}){
 const [disposition,setDisposition]=useState(''),[amount,setAmount]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[stale,setStale]=useState(false),[error,setError]=useState('')
 const parts=amount.split('.'),cents=/^\d+(\.\d{1,2})?$/.test(amount)?Number(parts[0])*100+Number((parts[1]||'').padEnd(2,'0')):NaN
 const valid=ready&&!!determination&&!busy&&!stale&&confirmed&&!!labels[disposition]&&(disposition==='UNRESOLVED'||determination.disposition!=='UNRESOLVED')&&(disposition!=='RELIEF_USED'||determination.disposition==='SMALL_EMPLOYER_RELIEF')&&(disposition!=='REPORT'||Number.isSafeInteger(cents)&&cents>0)&&reference.trim().length>=12&&!Array.from(reference).some(c=>c.charCodeAt(0)<32||c.charCodeAt(0)===127)
 const save=async()=>{if(!valid||!determination)return;setBusy(true);setError('');try{const response=await adminApiRequest(`/api/admin/payroll/employees/${employeeId}/health-coverage-classification`,{method:'POST',body:JSON.stringify({year:2026,determinationId:Number(determination.id),sourceFingerprint,expectedRevision:Number(history[0]?.id||0),disposition,reportableCostCents:disposition==='REPORT'?cents:null,reference,confirmed})}),json=await response.json();if(!response.ok){if(response.status===409){setStale(true);setConfirmed(false)}throw new Error(json.message||'Unable to save coverage classification.')}await onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to save coverage classification.')}finally{setBusy(false)}}
 const input='mt-1 block w-full rounded-lg border border-slate-300 bg-white p-2 font-normal'
 return <section aria-label="Employee health-coverage classification" className="space-y-3 border-t border-slate-200 pt-3"><h5 className="font-bold">Employee health-coverage classification</h5><p>Review annual reportable coverage cost from verified coverage records. Employee deductions and current monthly prices do not establish this amount.</p>{error?<p role="alert" className="text-red-700">{error}</p>:null}
 {!determination?<p className="text-amber-900">Record the employer health-reporting determination in Employer setup, then refresh annual preparation.</p>:!ready?<p className="text-amber-900">Reconcile annual payroll inputs before classifying coverage.</p>:<fieldset disabled={busy||stale} className="space-y-3"><p>Employer determination: {determination.disposition==='REPORT'?'Report applicable costs':determination.disposition==='SMALL_EMPLOYER_RELIEF'?'Small-employer relief':'Unresolved'} · Revision {determination.id}</p><label className="block font-semibold">Coverage classification<select value={disposition} onChange={e=>{setDisposition(e.target.value);setAmount('');setConfirmed(false)}} className={input}><option value="">Choose reviewed classification</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key} disabled={key!=='UNRESOLVED'&&determination.disposition==='UNRESOLVED'||key==='RELIEF_USED'&&determination.disposition!=='SMALL_EMPLOYER_RELIEF'}>{label}</option>)}</select></label>{disposition==='REPORT'?<label className="block font-semibold">Verified annual reportable cost ($)<input inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setConfirmed(false)}} className={input}/></label>:null}<label className="block font-semibold">Coverage classification evidence<input autoComplete="off" maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} className={input}/></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified the annual coverage classification and any reportable cost against the referenced evidence.</label><button type="button" disabled={!valid} onClick={()=>void save()} className="rounded-lg bg-slate-900 px-3 py-2 font-bold text-white disabled:opacity-50">Save coverage classification</button></fieldset>}
 {stale?<p className="text-amber-900">Refresh annual preparation before reviewing again.</p>:null}<h6 className="font-bold">Coverage classification history</h6>{history.length?history.map(item=><article key={item.id} className="space-y-1 rounded-lg bg-slate-50 p-3"><p>{item.status} · Classification {item.id} · {labels[item.disposition]}</p><p>{item.reportable_cost_cents===null?'No reportable amount recorded':`Verified reportable cost: ${money(item.reportable_cost_cents)}`}</p><p className="break-words">{item.reference}</p><p className="text-xs text-slate-500">Reviewer {item.created_by} · {new Date(item.created_at).toLocaleString()}</p></article>):<p>No coverage classification recorded.</p>}</section>
}
