import { useEffect,useState } from 'react'
import { adminApiRequest } from '../../utils/api'
import { workforceButton,workforceInput } from './OnboardingWorkspace'
export default function EmployerTaxSettings(){
 const [futa,setFuta]=useState(''),[ui,setUi]=useState(''),[source,setSource]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 useEffect(()=>{let live=true;void adminApiRequest('/api/admin/payroll/employer-taxes').then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.message);if(live&&j.data){setFuta(String(j.data.futaRatePercent));setUi(String(j.data.mdUiRatePercent));setSource(j.data.source)}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[])
 return <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Employer unemployment taxes · 2026</h2><p className="mt-2 text-sm text-slate-600">Record the Maryland rate assigned in BEACON and the verified effective FUTA rate. These employer costs are included in payroll and QuickBooks totals and do not reduce employee net pay. Standard taxable wages are capped at $7,000 for FUTA and $8,500 for Maryland UI per employee per year.</p>
 <p className="mt-2 text-sm"><a href="https://www.irs.gov/publications/p15" target="_blank" rel="noreferrer" className="text-blue-700 underline">IRS FUTA guidance</a> · <a href="https://labor.maryland.gov/unemployment-insurance/employer-agent/tax-rate.shtml" target="_blank" rel="noreferrer" className="text-blue-700 underline">Maryland rate notice guidance</a></p>
 {error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}{notice?<p role="status" className="mt-3 text-sm text-emerald-700">{notice}</p>:null}
 <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await adminApiRequest('/api/admin/payroll/employer-taxes',{method:'PATCH',body:JSON.stringify({futaRatePercent:Number(futa),mdUiRatePercent:Number(ui),source,confirmed})});const j=await r.json();if(!r.ok)throw new Error(j.message);setNotice('Employer tax rates saved. Rebuild existing drafts before approval.')}catch(e){setError(e instanceof Error?e.message:'Unable to save employer rates')}finally{setBusy(false)}}}>
 <label className="text-sm font-bold">Effective FUTA rate (%)<input required type="number" min="0.6" max="6" step="0.01" value={futa} onChange={e=>setFuta(e.target.value)} className={workforceInput}/></label><label className="text-sm font-bold">Assigned Maryland UI rate (%)<input required type="number" min="0.3" max="7.5" step="0.01" value={ui} onChange={e=>setUi(e.target.value)} className={workforceInput}/></label>
 <label className="text-sm font-bold sm:col-span-2">Employer tax verification source<input required minLength={12} value={source} onChange={e=>setSource(e.target.value)} className={workforceInput} placeholder="Rate notice year/date, FUTA credit treatment, and reviewer"/></label>
 <label className="flex gap-2 text-sm sm:col-span-2"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified the 2026 assigned rates, FUTA credit eligibility, and standard taxable wages; no reimbursable-employer, exempt-wage, or successor-employer exception applies.</label><button disabled={busy||!confirmed} className={workforceButton}>Save employer tax rates</button>
 </form></section>
}
