import {useEffect,useState} from 'react'
import {workforceApi,type EmployeeScheduleNotice} from '../../utils/workforceApi'
import {workforceButton} from './OnboardingWorkspace'
export default function EmployeeScheduleNotices(){
 const [notices,setNotices]=useState<EmployeeScheduleNotice[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{let active=true;workforceApi.employeeScheduleNotices().then(data=>{if(active)setNotices(data)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to load notices')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">Pay schedule notices</h2><p className="mt-2 text-sm text-slate-600">Acknowledgment records receipt and does not waive wage rights.</p>{loading?<p className="mt-3">Loading notices…</p>:!notices.length&&!error?<p className="mt-3 text-sm">No pay schedule change notices.</p>:null}
 <div className="mt-3 space-y-3">{notices.map(n=>{const cancellation=!!n.cancelledAt,ack=cancellation?n.cancellationAcknowledgedAt:n.acknowledgedAt;return <article className="rounded-xl border border-slate-200 p-4" key={n.id}><h3 className="font-bold">{cancellation?'Cancelled schedule change':'Pay schedule change'} · {n.effectiveOn}</h3><p className="mt-2 text-sm">Announced frequency: {n.schedule.pay_frequency.toLowerCase()}. {n.schedule.pay_frequency==='SEMIMONTHLY'?`Scheduled paydays: ${n.schedule.semimonthly_first_day} and ${n.schedule.semimonthly_second_day} each month.`:`Reference period begins ${n.schedule.pay_period_anchor_start?.slice(0,10)}; payment is scheduled ${n.schedule.pay_period_payment_lag_days} calendar days after period end.`} Bank holidays and weekends move payment earlier.</p><p className="mt-2 text-sm">Notice delivered {n.noticeDeliveredOn}.</p>{cancellation?<p className="mt-2 text-sm">This announced change was cancelled. Cancellation notice delivered {n.cancellationNoticeDeliveredOn}. The cancelled schedule does not apply.</p>:null}{ack?<p className="mt-2 text-sm text-emerald-700">Receipt acknowledged {ack.slice(0,10)}.</p>:<button className={`${workforceButton} mt-3`} type="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await workforceApi.acknowledgeScheduleNotice(n.id,cancellation);setNotices(await workforceApi.employeeScheduleNotices());setMessage('Schedule notice receipt recorded.')}catch(e){setError(e instanceof Error?e.message:'Unable to acknowledge notice')}finally{setBusy(false)}}}>{cancellation?'Acknowledge schedule cancellation':'Acknowledge schedule change'}</button>}</article>})}</div>
 {error?<p role="alert" className="mt-3 text-red-700">{error}</p>:null}{message?<p role="status" className="mt-3 text-emerald-700">{message}</p>:null}</section>
}
