import {useEffect,useState} from 'react'
import {workforceApi,type SalaryNotice} from '../../utils/workforceApi'
import {workforceButton} from './OnboardingWorkspace'
export default function EmployeeSalaryNotices(){
 const [notices,setNotices]=useState<SalaryNotice[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{let active=true;workforceApi.employeeSalaryNotices().then(rows=>{if(active)setNotices(rows)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">Salary change notices</h2><p className="mt-2 text-sm text-slate-600">Acknowledgment records receipt of the notice and does not waive wage rights.</p>{loading?<p className="mt-3">Loading salary notices…</p>:!notices.length&&!error?<p className="mt-3 text-sm">No salary change notices.</p>:null}
 <div className="mt-3 space-y-3">{notices.map(n=>{const cancelled=!!n.cancelledAt,receipt=cancelled?n.cancellationAcknowledgedAt:n.acknowledgedAt;return <article key={n.id} className="rounded-xl border border-slate-200 p-4"><h3 className="font-bold">{cancelled?'Cancelled salary change':'Salary change'} · {n.effectiveOn}</h3><p className="mt-2 text-sm">Announced salary: {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n.annualSalaryCents/100)} annually · {n.jobTitle} · {n.classification==='NONEXEMPT'?'overtime eligible':'exempt'}.</p>{n.salaryWeeklyHours?<p className="mt-2 text-sm">Announced salary covers {n.salaryWeeklyHours} hours per week, with additional pay for hours beyond the agreement.</p>:null}{n.normalWorkweekMinutes?<p className="mt-2 text-sm">Announced normal workweek for sick leave: {n.normalWorkweekMinutes.map((v,i)=>v?`${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][i]} ${v/60}h`:null).filter(Boolean).join(' · ')}</p>:null}<p className="mt-2 text-sm">Written notice delivered {n.noticeDeliveredOn}.</p>{cancelled?<p className="mt-2 text-sm">This change was cancelled. Cancellation notice delivered {n.cancellationNoticeDeliveredOn}. The cancelled agreement does not take effect.</p>:null}{cancelled&&n.acknowledgedAt?<p className="mt-2 text-sm">Original change receipt acknowledged {n.acknowledgedAt.slice(0,10)}.</p>:null}{receipt?<p className="mt-2 text-sm text-emerald-700">{cancelled?'Cancellation receipt':'Change receipt'} acknowledged {receipt.slice(0,10)}.</p>:<button type="button" disabled={busy} className={`${workforceButton} mt-3`} onClick={async()=>{setBusy(true);setError('');try{await workforceApi.acknowledgeSalaryNotice(n.id,cancelled);setNotices(await workforceApi.employeeSalaryNotices());setMessage('Salary notice receipt recorded.')}catch(e){setError(e instanceof Error?e.message:'Unable to acknowledge salary notice')}finally{setBusy(false)}}}>{cancelled?'Acknowledge salary cancellation':'Acknowledge salary change'}</button>}</article>})}</div>
 {error?<p role="alert" className="mt-3 text-red-700">{error}</p>:null}{message?<p role="status" className="mt-3 text-emerald-700">{message}</p>:null}</section>
}
