import FederalRemittanceBankFields from './FederalRemittanceBankFields'
import {useCallback,useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Obligation={agency:string;key:string;quarter:number;dueOn:string;amountCents:number;reliable:boolean}
type History={id:string;agency:string;tax_quarter:number;settlement_date:string;amount_cents:number;reference:string;current:boolean}
type Model={earliestSettlementDate:string;issues:string[];obligations:Obligation[];history:History[]}
type Preview={status:string;issues:string[];fingerprint:string;amountCents:number;dueOn:string;late:boolean;identifierLast4:string|null;taxPeriodEnd:string|null}
const title=(agency:string)=>agency==='IRS_941'?'Form 941 taxes':'Federal unemployment (FUTA)'
const money=(n:number)=>(Number(n)/100).toLocaleString('en-US',{style:'currency',currency:'USD'})
export default function FederalRemittanceReview({year}:{year:number}){
 const [data,setData]=useState<Model|null>(null),[selection,setSelection]=useState(''),[settlementDate,setDate]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const request=useCallback(async(path:string,body?:unknown)=>{const response=await adminApiRequest(path,body?{method:'POST',body:JSON.stringify(body)}:undefined),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to review federal remittance.');return json.data},[])
 const revision=useRef(0)
 const invalidate=useCallback(()=>{revision.current++},[])
 const load=useCallback(async()=>{const current=++revision.current;const result=await request(`/api/admin/payroll/federal-remittance-review?year=${year}`) as Model;if(current===revision.current)setData(result);return result},[request,year])
 useEffect(()=>{const current=++revision.current;void request(`/api/admin/payroll/federal-remittance-review?year=${year}`).then((result:Model)=>{if(current===revision.current)setData(result)}).catch(e=>{if(current===revision.current)setError(e.message)});return invalidate},[request,year,invalidate])
 const obligation=data?.obligations.find(o=>`${o.agency}|${o.key}`===selection)
 const clear=()=>{setPreview(null);setConfirmed(false);setNotice('')}
 const review=async()=>{setBusy(true);setError('');clear();try{if(!obligation)throw new Error('Choose a federal deposit obligation.');setPreview(await request(`/api/admin/payroll/federal-remittance-preview?${new URLSearchParams({year:String(year),agency:obligation.agency,obligationKey:obligation.key,settlementDate})}`))}catch(e){setError(e instanceof Error?e.message:'Unable to prepare remittance.')}finally{setBusy(false)}}
 const save=async()=>{setBusy(true);setError('');try{if(!obligation||!preview)throw new Error('Refresh the remittance preview.');await request('/api/admin/payroll/federal-remittance-reviews',{year,agency:obligation.agency,obligationKey:obligation.key,settlementDate,fingerprint:preview.fingerprint,reference,confirmed});await load();setPreview(null);setReference('');setConfirmed(false);setNotice('Remittance review retained. No tax payment has been scheduled.')}catch(e){clear();setError(e instanceof Error?e.message:'Unable to retain remittance review.')}finally{setBusy(false)}}
 return <section aria-label="Federal remittance review" className="mt-6 space-y-3 rounded-xl border p-4"><h3 className="text-lg font-black">Federal remittance review</h3><p>Prepare and retain federal deposit instructions from finalized payroll. Bank transmission is not connected yet.</p>{error?<p role="alert" className="text-red-700">{error}</p>:null}{notice?<p role="status" className="text-emerald-800">{notice}</p>:null}
 <button type="button" disabled={busy} className="font-bold underline" onClick={()=>{setBusy(true);clear();setError('');void load().catch(e=>{setData(null);setError(e.message)}).finally(()=>setBusy(false))}}>Refresh remittance obligations</button>
 {data?.issues.length?<ul className="list-disc pl-5">{data.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:null}
 <fieldset disabled={busy} className="space-y-3"><label className="block">Federal deposit obligation<select className="block w-full rounded border p-2" value={selection} onChange={e=>{setSelection(e.target.value);clear();const o=data?.obligations.find(o=>`${o.agency}|${o.key}`===e.target.value);if(o&&data)setDate(o.dueOn>data.earliestSettlementDate?o.dueOn:data.earliestSettlementDate)}}><option value="">Choose an obligation</option>{data?.obligations.map(o=><option key={`${o.agency}|${o.key}`} value={`${o.agency}|${o.key}`}>{title(o.agency)} · Q{o.quarter} · {money(o.amountCents)} · Due {o.dueOn}</option>)}</select></label><label className="block">Planned tax settlement date<input type="date" className="block rounded border p-2" value={settlementDate} onChange={e=>{setDate(e.target.value);clear()}}/></label><button type="button" disabled={!obligation||!settlementDate} className="font-bold underline disabled:opacity-50" onClick={()=>void review()}>Preview federal remittance</button>
 {preview?<div className="space-y-2 rounded border p-3"><p className="font-bold">{money(preview.amountCents)} · Deposit due {preview.dueOn}</p>{preview.taxPeriodEnd?<p>Tax period ends {preview.taxPeriodEnd} · EIN ending {preview.identifierLast4}</p>:null}{preview.late?<p className="font-semibold text-amber-800">The planned date is after the deposit due date.</p>:null}{preview.issues.length?<ul className="list-disc pl-5">{preview.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:null}{preview.status==='READY_FOR_REVIEW'?<><label className="block">Federal remittance review reference<input className="block w-full rounded border p-2" maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the tax amount, tax period, settlement date and any lateness.</label><button type="button" disabled={!confirmed||reference.trim().length<12} className="rounded bg-slate-900 p-2 font-bold text-white disabled:opacity-50" onClick={()=>void save()}>Retain remittance review</button></>:null}</div>:null}</fieldset>
 {data?.history.length?<details><summary>Federal remittance review history</summary><ol className="space-y-2">{data.history.map(h=><li key={h.id} className="break-words">{title(h.agency)} · Q{h.tax_quarter} · {money(h.amount_cents)} · Planned {h.settlement_date.slice(0,10)} · {h.current?'Current review':'Needs refreshed review'}<p>{h.reference}</p>{h.current?<FederalRemittanceBankFields reviewId={h.id}/>:null}</li>)}</ol></details>:null}
 </section>
}
