import {useEffect,useState} from 'react'
import {workforceApi,type FederalDepositCalendarData,type TaxReconciliationData} from '../../utils/workforceApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value/100)
export default function FederalDepositCalendar({year,receipts}:{year:number;receipts?:TaxReconciliationData['deposits']}) {
 const [data,setData]=useState<FederalDepositCalendarData|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const [form,setForm]=useState({schedule:'MONTHLY',priorYearNextDay:false,source:'',confirmed:false})
 useEffect(()=>{let live=true;workforceApi.federalDepositCalendar(year).then(next=>{if(live){setData(next);if(next.config)setForm(f=>({...f,schedule:next.config!.schedule,priorYearNextDay:next.config!.prior_year_next_day,source:next.config!.source}))}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[year,receipts])
 return <section className="mt-6 rounded-xl border border-slate-200 p-4"><h3 className="text-lg font-black">Federal deposit calendar</h3><p className="mt-2 text-sm text-slate-600">Form 941 income tax, Social Security and Medicare deposits follow the verified schedule below. Deadlines use actual pay dates and DC legal holidays. The $100,000 next-day rule automatically takes priority. FUTA appears separately below. Maryland unemployment and withholding have separate calendars below.</p>
 {error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}{notice?<p role="status" className="mt-3 text-sm text-emerald-700">{notice}</p>:null}
 {data?.issues.map(issue=><p key={issue} className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{issue}</p>)}
 {year===2026?<form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{await workforceApi.saveFederalDepositSchedule({year,...form});setData(await workforceApi.federalDepositCalendar(year));setForm(f=>({...f,confirmed:false}));setNotice('Federal deposit schedule verified. Deadlines recalculated.')}catch(e){setError(e instanceof Error?e.message:'Unable to save schedule')}finally{setBusy(false)}}}>
 <label className="text-sm font-bold">Verified Form 941 deposit schedule<select className={workforceInput} value={form.schedule} onChange={e=>setForm(f=>({...f,schedule:e.target.value}))}><option value="MONTHLY">Monthly</option><option value="SEMIWEEKLY">Semiweekly</option></select></label>
 <label className="text-sm font-bold">Deposit schedule verification source<input className={workforceInput} required minLength={12} value={form.source} onChange={e=>setForm(f=>({...f,source:e.target.value}))} placeholder="Lookback review or IRS notice reference"/></label>
 <label className="flex items-start gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={form.priorYearNextDay} onChange={e=>setForm(f=>({...f,priorYearNextDay:e.target.checked}))}/>The $100,000 next-day rule applied in the prior year (requires semiweekly this year).</label>
 <label className="flex items-start gap-2 text-sm sm:col-span-2"><input type="checkbox" required checked={form.confirmed} onChange={e=>setForm(f=>({...f,confirmed:e.target.checked}))}/>I verified this Form 941 employer’s schedule, prior-year next-day status, and complete daily payroll tax history for this year.</label><button disabled={busy} className={workforceButton}>Verify federal deposit schedule</button>
 </form>:null}
 {data?.config?<p className="mt-3 text-xs text-slate-500">Verified {data.config.verified_at.slice(0,10)} · Effective schedule: {data.effectiveSchedule?.toLowerCase()}. Small-liability payment-with-return exceptions and deposit shortfall tolerances are not used to defer these dates.</p>:null}
 {data?.nextYearSemiweeklyRequired?<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm font-bold">The $100,000 rule triggered this year. Semiweekly deposits are also required next year; include this in next year’s schedule review.</p>:null}
 <p className="mt-3 text-xs text-slate-500">Recorded receipts are allocated to the earliest obligations within their tax quarter. This comparison does not prove agency allocation or acceptance. Provider submission cutoffs may be earlier than the legal due date.</p>
 <div className="mt-3 grid gap-3 lg:grid-cols-2">{data?.obligations.map(o=><article key={o.key} className="rounded-xl border border-slate-200 p-3 text-sm"><p className="font-bold">Federal deposit due {o.dueOn} · Q{o.quarter}</p><p className={data.reliable&&['OVERDUE','DUE_TODAY'].includes(o.status)?'font-bold text-red-700':'font-bold text-slate-700'}>{data.reliable?o.status.replaceAll('_',' '):'HISTORY REVIEW REQUIRED'}</p><p className="mt-1">Pay dates {o.firstPayDate} through {o.lastPayDate} · {o.rule==='NEXT_DAY_100K'?'$100,000 next-day rule':o.rule.toLowerCase()}</p><p>Liability {money(o.liabilityCents)} · Receipts {money(o.coveredCents)} · Remaining {money(o.balanceCents)}</p>{o.lateCoveredCents>0?<p className="text-amber-800">{money(o.lateCoveredCents)} matched to receipts dated after the deadline.</p>:null}</article>)}</div>
 {data?.reliable&&!data.obligations.length?<p className="mt-3 text-sm text-slate-500">No federal deposit obligations from finalized payroll yet.</p>:null}
 <div className="mt-6 border-t border-slate-200 pt-5"><h3 className="text-lg font-black">FUTA deposit calendar</h3><p className="mt-2 text-sm text-slate-600">Federal unemployment amounts of $500 or less may carry into the next quarter. Once the accumulated liability exceeds $500, the deposit is due after that quarter. Any remaining year-end amount must be paid by the Form 940 payment deadline.</p>
 {data?.futa.issues.map(issue=><p key={issue} className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{issue}</p>)}
 {data?<p className="mt-3 text-sm font-bold">Annual FUTA liability {money(data.futa.liabilityCents)} · Matched receipts {money(data.futa.coveredCents)} · Unapplied receipts {money(data.futa.unappliedCents)}</p>:null}
 <p className="mt-2 text-xs text-slate-500">FUTA is matched annually to the oldest liabilities, including amounts carried across quarters. Quarter tags on receipts remain visible in the history but do not prevent annual matching. Projections use finalized payroll so far and can change as more wages are paid.</p>
 <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data?.futa.quarters.map(q=><div key={q.quarter} className="rounded-lg bg-slate-50 p-3 text-sm"><p className="font-bold">Q{q.quarter} {q.closed?'closed':'projection'}</p><p>New tax {money(q.taxCents)}</p><p>Carryforward {money(q.carriedCents)}</p></div>)}</div>
 <div className="mt-3 grid gap-3 lg:grid-cols-2">{data?.futa.obligations.map(o=><article key={o.quarter} className="rounded-xl border border-slate-200 p-3 text-sm"><p className="font-bold">FUTA payment due {o.dueOn} · Q{o.fromQuarter}{o.fromQuarter!==o.quarter?`–Q${o.quarter}`:''}</p><p className={data.futa.reliable&&['OVERDUE','DUE_TODAY'].includes(o.status)?'font-bold text-red-700':'font-bold text-slate-700'}>{data.futa.reliable?o.status.replaceAll('_',' '):'HISTORY REVIEW REQUIRED'}{o.projected?' · Projection':''}</p><p className="mt-1">{o.rule==='YEAR_END_PAYMENT'?'Year-end amount: deposit or pay with Form 940.':'Quarterly electronic deposit required.'}</p><p>Liability {money(o.liabilityCents)} · Receipts {money(o.coveredCents)} · Remaining {money(o.balanceCents)}</p>{o.lateCoveredCents>0?<p className="text-amber-800">{money(o.lateCoveredCents)} matched to receipts dated after the deadline.</p>:null}</article>)}</div>
 {data?.futa.reliable&&!data.futa.obligations.length?<p className="mt-3 text-sm text-slate-500">No unpaid FUTA deposit obligations from finalized payroll.</p>:null}</div>
 </section>
}
