import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type History={revision:number;history:Array<{id:string;identifier_last4:string;created_by:string;created_at:string;status:string;employee_review:string|null}>}
const blank=()=>({identifier:'',marylandRegistrationNumber:'',legalName:'',firstName:'',middleName:'',lastName:'',suffix:'',line1:'',line2:'',city:'',state:'MD',postalCode:'',reference:''})
const inputClass='mt-1 block w-full rounded-lg border border-slate-300 p-2 font-normal'
export default function FilingIdentityForm({employeeId}:{employeeId?:number}){
 const [history,setHistory]=useState<History|null>(null),[form,setForm]=useState(blank),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const path=employeeId?`/api/admin/payroll/employees/${employeeId}/filing-identity`:'/api/admin/payroll/filing-identity'
 const title=employeeId?'Employee filing identity':'Employer filing identity'
 const load=async()=>{setBusy(true);setHistory(null);setForm(blank());setConfirmed(false);setError('');setMessage('');try{const response=await adminApiRequest(path),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to load filing identity.');setHistory(json.data)}catch(e){setError(e instanceof Error?e.message:'Unable to load filing identity.')}finally{setBusy(false)}}
 const change=(key:keyof ReturnType<typeof blank>,value:string)=>{setForm(old=>({...old,[key]:value}));setConfirmed(false);setMessage('')}
 const valid=history&&confirmed&&(employeeId||!form.marylandRegistrationNumber||(/^\d{8}$/.test(form.marylandRegistrationNumber)&&form.marylandRegistrationNumber!=='00000000'))&&/^\d{9}$/.test(form.identifier.replace(/[ -]/g,''))&&form.identifier.replace(/[ -]/g,'')!=='000000000'&&(employeeId?form.firstName.trim()&&form.lastName.trim():form.legalName.trim())&&form.line1.trim()&&form.city.trim()&&/^[A-Z]{2}$/.test(form.state)&&/^\d{5}(-\d{4})?$/.test(form.postalCode)&&form.reference.trim().length>=12
 const save=async()=>{if(!valid||!history)return;setBusy(true);setError('');setMessage('');try{
  const response=await adminApiRequest(path,{method:'POST',body:JSON.stringify({identifier:form.identifier,...(!employeeId?{marylandRegistrationNumber:form.marylandRegistrationNumber}:{}),legalName:form.legalName,firstName:form.firstName,middleName:form.middleName,lastName:form.lastName,suffix:form.suffix,address:{line1:form.line1,line2:form.line2,city:form.city,state:form.state,postalCode:form.postalCode,country:'US'},reference:form.reference,confirmed,expectedRevision:history.revision})}),json=await response.json()
  if(!response.ok){if(response.status===409){setHistory(null);setForm(blank());setConfirmed(false)}throw new Error(json.message||'Unable to save filing identity.')}
  setForm(blank());setConfirmed(false);await load();setMessage('Encrypted filing identity saved. Full details have been cleared from this form.')
 }catch(e){setError(e instanceof Error?e.message:'Unable to save filing identity.')}finally{setBusy(false)}}
 const field=(key:keyof ReturnType<typeof blank>,label:string,limit=120)=><label className="font-semibold">{label}<input autoComplete="off" maxLength={limit} value={form[key]} onChange={e=>change(key,e.target.value)} className={inputClass}/></label>
 return <section aria-label={title} className="space-y-3 rounded-xl border border-slate-200 bg-white p-4 text-sm"><h3 className="font-bold">{title}</h3><p>Store the legal identity and US mailing address used for tax documents. A correction creates a new retained revision. Full identifiers are encrypted and are not displayed in history.</p>
 <button type="button" disabled={busy} onClick={()=>void load()} className="rounded-lg border border-slate-300 px-3 py-2 font-bold disabled:opacity-50">{busy?'Working…':history?'Refresh filing identity':'Open filing identity'}</button>
 {error?<p role="alert" className="text-red-700">{error}</p>:null}{message?<p role="status" className="text-emerald-800">{message}</p>:null}
 {history?<><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2"><legend className="mb-2 font-bold">{history.revision?'Record a corrected identity':'Record filing identity'}</legend>
 <label className="font-semibold">{employeeId?'Full SSN':'Full EIN'}<input type="password" autoComplete="new-password" inputMode="numeric" maxLength={11} value={form.identifier} onChange={e=>change('identifier',e.target.value)} className={inputClass}/></label>
 {employeeId?<>{field('firstName','Legal first name')}{field('middleName','Legal middle name (optional)')}{field('lastName','Legal last name')}{field('suffix','Name suffix (optional)',20)}</>:field('legalName','Legal employer name')}
 {!employeeId?<label className="font-semibold">Maryland Central Registration Number<input type="password" autoComplete="new-password" inputMode="numeric" maxLength={8} value={form.marylandRegistrationNumber} onChange={e=>change('marylandRegistrationNumber',e.target.value)} className={inputClass}/><span className="block text-xs font-normal text-slate-600">Eight digits from your state registration record. You can save without it, but Maryland annual reporting requires this separate identifier.</span></label>:null}
 {field('line1','Mailing street address')}{field('line2','Address line 2 (optional)')}{field('city','Mailing city')}{field('state','Mailing state',2)}{field('postalCode','Mailing ZIP code',10)}
 <label className="font-semibold sm:col-span-2">Identity verification reference<textarea autoComplete="off" maxLength={2000} value={form.reference} onChange={e=>change('reference',e.target.value)} className={inputClass}/></label>
 <label className="flex items-start gap-2 sm:col-span-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked the full identifier, any state registration number, legal name and mailing address against the source referenced above.</label>
 <button type="button" disabled={!valid} onClick={()=>void save()} className="rounded-lg bg-slate-900 px-3 py-2 font-bold text-white disabled:opacity-50">Save encrypted filing identity</button></fieldset>
 <div className="space-y-2"><h4 className="font-bold">Identity revision history</h4>{history.history.length?history.history.map(row=><article key={row.id} className="rounded-lg bg-slate-50 p-3"><p>{row.status} · Revision {row.id} · Identifier ending {row.identifier_last4}</p>{employeeId?<p>Employee review: {row.employee_review==='CONFIRMED'?'Displayed details confirmed':row.employee_review==='CORRECTION_REQUESTED'?'Correction requested — contact employee':'Awaiting employee review'}</p>:null}<p className="text-xs text-slate-500">Reviewer {row.created_by} · {new Date(row.created_at).toLocaleString()}</p></article>):<p>No filing identity recorded.</p>}</div></>:null}</section>
}
