import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type History={revision:number;history:Array<{id:string;disposition:string;prior_year_w2_count:number|null;reference:string;created_by:string;created_at:string;status:string}>}
const labels:Record<string,string>={REPORT:'Report applicable coverage costs',SMALL_EMPLOYER_RELIEF:'Use small-employer transition relief',UNRESOLVED:'Determination unresolved'}
export default function HealthReporting(){
 const [history,setHistory]=useState<History|null>(null),[disposition,setDisposition]=useState(''),[count,setCount]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const clear=()=>{setDisposition('');setCount('');setReference('');setConfirmed(false)}
 const load=async()=>{setHistory(null);clear();setError('');setMessage('');setBusy(true);try{const response=await adminApiRequest('/api/admin/payroll/health-coverage-reporting?year=2026'),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to read reporting determination.');setHistory(json.data)}catch(e){setError(e instanceof Error?e.message:'Unable to read reporting determination.')}finally{setBusy(false)}}
 const numeric=count===''?null:/^\d+$/.test(count)?Number(count):NaN
 const valid=!!history&&!busy&&confirmed&&!!labels[disposition]&&(numeric===null||Number.isSafeInteger(numeric)&&numeric>=0&&numeric<=2147483647)&&(disposition!=='SMALL_EMPLOYER_RELIEF'||numeric!==null&&numeric<250)&&reference.trim().length>=12&&!Array.from(reference).some(c=>c.charCodeAt(0)<32||c.charCodeAt(0)===127)
 const save=async()=>{if(!valid||!history)return;setBusy(true);setError('');setMessage('');try{const response=await adminApiRequest('/api/admin/payroll/health-coverage-reporting',{method:'POST',body:JSON.stringify({year:2026,disposition,priorYearW2Count:numeric,reference,confirmed,expectedRevision:history.revision})}),json=await response.json();if(!response.ok){if(response.status===409){setHistory(null);clear()}throw new Error(json.message||'Unable to save reporting determination.')}await load();setMessage('Health-reporting determination saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save reporting determination.')}finally{setBusy(false)}}
 const input='mt-1 block w-full rounded-lg border border-slate-300 bg-white p-2 font-normal'
 return <section aria-label="Annual health-coverage reporting" className="space-y-3 rounded-xl border border-slate-200 bg-white p-4 text-sm"><h3 className="font-bold">Annual health-coverage reporting</h3><p>Determine the employer reporting approach for 2026. This does not determine individual coverage costs or issue tax forms.</p><button type="button" disabled={busy} onClick={()=>void load()} className="rounded-lg border border-slate-300 px-3 py-2 font-bold disabled:opacity-50">{busy?'Working…':history?'Refresh reporting determination':'Open reporting determination'}</button>
 {error?<p role="alert" className="text-red-700">{error}</p>:null}{message?<p role="status" className="text-emerald-800">{message}</p>:null}
 {history?<><fieldset disabled={busy} className="space-y-3"><label className="block font-semibold">Reporting determination<select value={disposition} onChange={e=>{setDisposition(e.target.value);setConfirmed(false)}} className={input}><option value="">Choose reviewed determination</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="block font-semibold">Forms W-2 required for 2025<input inputMode="numeric" value={count} maxLength={10} onChange={e=>{setCount(e.target.value);setConfirmed(false)}} className={input}/></label><p className="text-slate-600">Use the verified prior-year filing requirement, not current headcount. Small-employer relief requires fewer than 250. Otherwise this count may be left blank.</p><label className="block font-semibold">Reporting evidence reference<input value={reference} maxLength={2000} autoComplete="off" onChange={e=>{setReference(e.target.value);setConfirmed(false)}} className={input}/></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the determination and any prior-year count against the referenced evidence.</label><button type="button" disabled={!valid} onClick={()=>void save()} className="rounded-lg bg-slate-900 px-3 py-2 font-bold text-white disabled:opacity-50">Save reporting determination</button></fieldset><h4 className="font-bold">Determination history</h4>{history.history.length?history.history.map(item=><article key={item.id} className="space-y-1 rounded-lg bg-slate-50 p-3"><p>{item.status} · Revision {item.id} · {labels[item.disposition]}</p><p>2025 W-2 filing count: {item.prior_year_w2_count??'Not recorded'}</p><p className="break-words">{item.reference}</p><p className="text-xs text-slate-500">Reviewer {item.created_by} · {new Date(item.created_at).toLocaleString()}</p></article>):<p>No determination recorded.</p>}</>:null}</section>
}
