import {useCallback,useEffect,useId,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Review={disposition:string;reference:string;effectiveOn:string;effectiveThrough:string}
type Model={source:{fingerprint:string;issues:string[];employeeName?:string;selection?:{optionLabel:string;monthlyCents:number};authorization?:{signature:string;proposal?:{terms?:string}}};status:string;documentStorageReady?:boolean;history:{id:string;revision:number;review:Review;document_sha256?:string;document_pages?:number;created_at:string}[]}
type Upload={filename:string;contentBase64:string}
async function request(path:string,body?:string){const r=await adminApiRequest(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body}:undefined),b=await r.json();if(!r.ok||!b.success)throw Object.assign(new Error(b.message||'Unable to review health qualification.'),{status:r.status});return b.data as Model}
const planFindings=[['writtenPlanConfirmed','I reviewed the written Section 125 plan, its eligibility and election provisions, and the effective plan period.'],['eligibleBenefitsConfirmed','The selected pretax benefits are qualified accident/health insurance premiums under this plan; other benefit types and taxable coverage require separate treatment.'],['nondiscriminationConfirmed','I reviewed the applicable plan nondiscrimination requirements and retained supporting findings.']] as const
const employeeFindings=[['commonLawEmployeeConfirmed','I verified that this person is an eligible employee under the written cafeteria plan.'],['ownershipEligibleConfirmed','I reviewed ownership and attribution rules; this person is not an ineligible sole proprietor, partner or more-than-2% S corporation shareholder.'],['coverageEligibleConfirmed','I verified the tax eligibility of all covered persons and the selected accident/health insurance premiums.'],['electionRulesConfirmed','I verified the election timing and any permitted change against the written plan; this review does not replace the employee’s signed authorization.'],['nondiscriminationConfirmed','I reviewed any participant-specific nondiscrimination exceptions or adverse findings.']] as const
export default function HealthQualificationReview({planId,planName,employeeId}:{planId:string;planName:string;employeeId?:number|string}){
 const id=useId(),participant=employeeId!==undefined,findings=participant?employeeFindings:planFindings
 const path=participant?`/api/admin/payroll/employees/${employeeId}/health-qualification/${encodeURIComponent(planId)}`:`/api/admin/payroll/health-plan-qualification/${encodeURIComponent(planId)}`
 const [electionBasis,setElectionBasis]=useState(''),[electionDeadline,setElectionDeadline]=useState(''),[employeeExplanation,setEmployeeExplanation]=useState('')
 const [from,setFrom]=useState(''),[through,setThrough]=useState(''),[data,setData]=useState<Model|null>(null),[basis,setBasis]=useState<Model|null>(null),[decision,setDecision]=useState(''),[reference,setReference]=useState(''),[checks,setChecks]=useState<Record<string,boolean>>({}),[confirmed,setConfirmed]=useState(false),[file,setFile]=useState<Upload|null>(null),[busy,setBusy]=useState(false),[pending,setPending]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const read=useCallback(()=>request(`${path}?${new URLSearchParams({paymentDate:from})}`),[path,from]),loaded=!!data
 const stale=!!data&&!!basis&&(data.source.fingerprint!==basis.source.fingerprint||data.history[0]?.id!==basis.history[0]?.id)
 const resetChecks=()=>{setChecks({});setConfirmed(false);setNotice('')}
 const load=async()=>{setBusy(true);setError('');try{const next=await read();setData(next);setBasis(next);resetChecks()}catch(e){setError(e instanceof Error?e.message:'Unable to load qualification.')}finally{setBusy(false)}}
 useEffect(()=>{if(!loaded||busy)return;let live=true,inFlight=false;const timer=setInterval(()=>{if(inFlight)return;inFlight=true;void read().then(next=>{if(live){setData(next);setError('')}}).catch(()=>{if(live)setError('Qualification evidence could not refresh. Reload before saving.')}).finally(()=>{inFlight=false})},30000);return()=>{live=false;clearInterval(timer)}},[loaded,busy,read])
 const upload=async(f:File|undefined)=>{setFile(null);resetChecks();if(!f)return;if(f.size>5*1024*1024){setError('Choose a PDF up to 5 MB.');return}setBusy(true);setError('');try{const content=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('Unable to read the selected PDF.'));r.readAsDataURL(f)});setFile({filename:'Section-125-written-plan.pdf',contentBase64:content})}catch(e){setError(e instanceof Error?e.message:'Unable to read the PDF.')}finally{setBusy(false)}}
 const save=async()=>{if(!basis)return;setBusy(true);setError('');setNotice('');const body=pending||JSON.stringify({sourceFingerprint:basis.source.fingerprint,expectedRevision:basis.history[0]?.revision||0,requestKey:crypto.randomUUID(),effectiveOn:from,effectiveThrough:through,disposition:decision,reference,confirmed,...checks,...(participant&&decision==='ELIGIBLE'?{electionBasis,electionDeadline,employeeElectionExplanation:employeeExplanation}:{}),...(!participant&&decision==='QUALIFIED'?{classification:'SECTION125_ACCIDENT_HEALTH_PREMIUM',document:file}:{})});setPending(body)
  try{await request(path,body);setPending(null);resetChecks();setDecision('');setReference('');setFile(null);setNotice('Health qualification review retained. Payroll must recheck the current evidence.');const next=await read();setData(next);setBasis(next)}catch(e){setError(e instanceof Error?e.message:'Unable to save qualification.');if(e instanceof Error&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500){setPending(null);resetChecks();try{setData(await read())}catch{/* Preserve the review draft. */}}}finally{setBusy(false)}}
 const download=async(reviewId:string)=>{setBusy(true);setError('');try{const r=await adminApiRequest(`${path}/${reviewId}/document`);if(!r.ok)throw new Error('Unable to download the retained written plan.');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='Section-125-written-plan.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e instanceof Error?e.message:'Unable to download the written plan.')}finally{setBusy(false)}}
 const positive=decision===(participant?'ELIGIBLE':'QUALIFIED'),valid=!!decision&&!!from&&!!through&&through>=from&&reference.trim().length>=20&&confirmed&&(!positive||findings.every(([key])=>checks[key])&&!data?.source.issues.length&&(!participant||!!electionBasis&&!!electionDeadline&&electionDeadline<=from&&employeeExplanation.trim().length>=20)&&(participant||!!file&&data?.documentStorageReady===true))
 return <section aria-label={`${participant?'Employee':'Written-plan'} health qualification ${planName}`} className="my-4 min-w-0 space-y-3 rounded-xl border border-slate-300 bg-white p-3 text-sm">
  <h4 className="font-bold">{participant?'Employee pretax health eligibility':'Written Section 125 plan qualification'} · {planName}</h4>
  <p>{participant?'Review the employee’s eligibility, covered persons and election rules against the retained written plan and signed choices.':'Retain the written cafeteria plan PDF and supporting findings for the published pretax health insurance options.'}</p>
  <div className="grid gap-3 sm:grid-cols-2"><label className="block" htmlFor={`${id}-from`}>Qualification effective date<input id={`${id}-from`} type="date" value={from} disabled={busy||!!pending} onChange={e=>{setFrom(e.target.value);setData(null);setBasis(null);resetChecks();setError('')}} className="block w-full rounded border p-2"/></label><label className="block" htmlFor={`${id}-through`}>Qualification through date<input id={`${id}-through`} type="date" value={through} min={from} disabled={busy||!!pending} onChange={e=>{setThrough(e.target.value);resetChecks()}} className="block w-full rounded border p-2"/></label></div>
  <button type="button" disabled={!from||busy||!!pending} onClick={()=>void load()} className="rounded border px-3 py-2">Load health qualification</button>
  {error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}{pending?<button type="button" disabled={busy} onClick={()=>void save()} className="rounded border px-3 py-2">Retry original health review</button>:null}
  {data&&basis?<><p>Qualification status: {data.status.replaceAll('_',' ')}{data.source.employeeName?` · ${data.source.employeeName}`:''}</p>
   {data.source.issues.length?<ul role="alert" className="list-disc pl-5">{data.source.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:null}
   {!participant&&!data.documentStorageReady?<p role="alert">Secure document storage must be available to retain a written plan.</p>:null}
   {data.source.authorization?<details><summary>Read employee’s signed health deduction terms</summary><p>Signed by {data.source.authorization.signature}</p><p className="whitespace-pre-wrap break-words">{data.source.authorization.proposal?.terms||'Retained terms need reconciliation.'}</p></details>:null}
   {stale?<div role="alert"><p>Qualification evidence changed. Your draft is preserved; review the current evidence before saving.</p><button type="button" disabled={busy||!!pending} onClick={()=>{setBasis(data);resetChecks()}} className="rounded border px-3 py-2">Use current qualification evidence</button></div>:null}
   <fieldset disabled={busy||!!pending||stale||!!error} className="space-y-3"><legend className="font-bold">Administrator qualification review</legend>
    <label className="block">Health qualification decision<select aria-label="Health qualification decision" value={decision} onChange={e=>{setDecision(e.target.value);resetChecks()}} className="block w-full rounded border p-2"><option value="">Choose decision</option><option value={participant?'ELIGIBLE':'QUALIFIED'} disabled={!!data.source.issues.length}>{participant?'Eligible for pretax coverage':'Qualified health insurance plan'}</option><option value="SUSPENDED">Suspend pending further review</option></select></label>
    {participant&&positive?<div className="space-y-3"><label className="block">Permitted health election basis<select aria-label="Permitted health election basis" value={electionBasis} onChange={e=>{setElectionBasis(e.target.value);resetChecks()}} className="block w-full rounded border p-2"><option value="">Choose reviewed basis</option><option value="INITIAL_ENROLLMENT">Initial enrollment</option><option value="OPEN_ENROLLMENT">Open enrollment</option><option value="PERMITTED_CHANGE">Plan-permitted change</option></select></label><label className="block">Health election signing deadline<input type="date" value={electionDeadline} max={from} onChange={e=>{setElectionDeadline(e.target.value);resetChecks()}} className="block w-full rounded border p-2"/></label><label className="block">Employee-facing election explanation<textarea aria-label="Employee-facing election explanation" value={employeeExplanation} maxLength={2000} onChange={e=>{setEmployeeExplanation(e.target.value);resetChecks()}} className="block w-full rounded border p-2"/></label><p>The effective date above is the permitted salary-reduction start. Explain the applicable election window or permitted change using terms safe to show this employee.</p></div>:null}
    {!participant&&positive?<label className="block">Written plan and qualification evidence PDF<input type="file" accept="application/pdf,.pdf" onChange={e=>void upload(e.target.files?.[0])} className="block w-full min-w-0 py-2"/>{file?<span>PDF selected for encrypted retention.</span>:null}</label>:null}
    {positive?findings.map(([key,label])=><label key={key} className="flex items-start gap-2"><input type="checkbox" checked={!!checks[key]} onChange={e=>{setChecks({...checks,[key]:e.target.checked});setConfirmed(false)}}/><span>{label}</span></label>):null}
    <label className="block">Health qualification review reference<textarea aria-label="Health qualification review reference" value={reference} maxLength={2000} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2"/></label>
    <label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I confirm these dated findings and the supporting evidence for this qualification decision.</span></label>
    <button type="button" disabled={!valid} onClick={()=>void save()} className="rounded border px-3 py-2">Retain health qualification</button>
   </fieldset>
   {data.history.length?<details><summary>Health qualification history</summary>{data.history.map(row=><div key={row.id} className="my-2 break-words"><p>Revision {row.revision} · {row.review.disposition} · {row.review.effectiveOn} through {row.review.effectiveThrough} · {row.review.reference}</p>{!participant&&row.document_sha256?<button type="button" disabled={busy} onClick={()=>void download(row.id)} className="font-semibold underline">Download written plan · revision {row.revision} ({row.document_pages} {row.document_pages===1?'page':'pages'})</button>:null}</div>)}</details>:null}
  </>:null}
 </section>
}
