import {useRef,useState} from 'react'
import {payrollApi} from '../../utils/payrollApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100)
export default function HistoricalAllocationPreview({employeeId,paymentId,periods}:{employeeId:number;paymentId:number;periods:Array<Record<string,unknown>>}){
 const [period,setPeriod]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [reason,setReason]=useState(''),[sourceConfirmed,setSourceConfirmed]=useState(false),[confirmed,setConfirmed]=useState(false)
 const [saved,setSaved]=useState<number|null>(null),[history,setHistory]=useState<Awaited<ReturnType<typeof payrollApi.historicalAllocationHistory>>>([])
 const request=useRef({key:'',id:''})
 const reset=()=>{setResult(null);setSaved(null);setSourceConfirmed(false);setConfirmed(false)}
 const [result,setResult]=useState<Awaited<ReturnType<typeof payrollApi.previewHistoricalAllocation>>|null>(null)
 return <details className="mt-3 min-w-[240px] rounded-lg border p-3"><summary className="cursor-pointer font-bold">Preview imported workweeks</summary><p className="mt-2">Choose a period covering all imported work dates. Retain current earnings allocations for its workweeks in Payroll runs first.</p><form className="mt-3 space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');reset();try{setResult(await payrollApi.previewHistoricalAllocation(employeeId,paymentId,{payPeriodId:Number(period)}))}catch(error){setError(error instanceof Error?error.message:'Unable to preview allocation.')}finally{setBusy(false)}}}>
  <label className="block">Imported allocation review period<select aria-label="Imported allocation review period" required disabled={busy} className={workforceInput} value={period} onChange={e=>{setPeriod(e.target.value);reset();setError('')}}><option value="">Select period</option>{periods.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.period_start).slice(0,10)} through {String(p.period_end).slice(0,10)}</option>)}</select></label>
  <button disabled={busy||!period} className={workforceButton}>{busy?'Checking imported earnings…':'Calculate imported allocation'}</button>
 </form>{error?<p role="alert" className="mt-2 text-red-700">{error}</p>:null}{result?<div role="status" className="mt-3 space-y-2"><p className="font-bold">{saved?'Imported allocation review retained':'Draft imported allocation · not retained'}</p><p>Recorded gross: {money(result.source.grossCents)}</p>{result.weeks.map(w=><p key={w.week}>{w.week} · {(w.workedMinutes/60).toFixed(2)} hours · straight-time {money(w.straightTimePayCents)} · premium {money(w.premiumCents)}</p>)}<p>{saved?'Retained source review. Evidence must be revalidated before this counts as paid coverage.':result.reviewRequired}</p></div>:null}
 {result&&!saved?<form className="mt-3 space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const body={payPeriodId:Number(period),fingerprint:result.fingerprint,reason,sourceConfirmed,confirmed};const key=JSON.stringify(body);if(request.current.key!==key)request.current={key,id:crypto.randomUUID()};try{const receipt=await payrollApi.retainHistoricalAllocation(employeeId,paymentId,{...body,requestId:request.current.id});setSaved(receipt.id);setHistory(h=>[receipt,...h.filter(r=>r.id!==receipt.id)])}catch(error){setError(error instanceof Error?error.message:'Unable to retain imported allocation.')}finally{setBusy(false)}}}><fieldset disabled={busy} className="space-y-3">
 <label className="block">Imported allocation review reason<textarea required minLength={20} maxLength={2000} className={workforceInput} value={reason} onChange={e=>{setReason(e.target.value);setConfirmed(false)}}/></label>
 <label className="flex gap-2"><input type="checkbox" required checked={sourceConfirmed} onChange={e=>setSourceConfirmed(e.target.checked)}/>I verified that the source gross contains only these dated wages and premiums.</label>
 <label className="flex gap-2"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm this imported allocation and its supporting evidence.</label>
 <button className={workforceButton}>{busy?'Saving imported review…':'Retain imported allocation'}</button></fieldset></form>:null}
 <button type="button" disabled={busy} className={`${workforceButton} mt-3`} onClick={async()=>{setBusy(true);setError('');try{setHistory(await payrollApi.historicalAllocationHistory(employeeId,paymentId))}catch(error){setError(error instanceof Error?error.message:'Unable to load review history.')}finally{setBusy(false)}}}>Load imported review history</button>
 {history.map(row=><div key={row.id} className="mt-2 rounded border p-2"><p>Retained review #{row.id} · {new Date(row.reviewedAt).toLocaleString()}</p><p className="whitespace-normal">{row.reason}</p><p>Saved evidence record; current validity requires revalidation.</p></div>)}
 </details>
}
