import {useEffect,useRef,useState} from 'react'
import {workforceApi,type I9DifferentPreview,type I9DifferentDraftFacts} from '../../utils/workforceApi'
const style='mt-1 block w-full min-w-0 rounded border p-2'
const finalKeys=['attestationRead','signingAsExaminer','reviewedAllPages','representativeIdentityConfirmed']
export default function I9DifferentExamination({employeeId,taskId,preview,initials,method,selected,rowKeys,onSigned,onBusy,initialDraft,onDraft}:{employeeId:number;taskId:string|number;preview:I9DifferentPreview;initials:string;method:string;selected:Record<string,string[]>;rowKeys:string[];onSigned:()=>void;onBusy:(busy:boolean)=>void;initialDraft:I9DifferentDraftFacts;onDraft:(draft:I9DifferentDraftFacts)=>void}){
 const [fields,setFields]=useState<Record<string,string>>({examinedOn:preview.recordedOn,...initialDraft.fields}),[checks,setChecks]=useState<Record<string,boolean>>({}),[days,setDays]=useState<number[]>(initialDraft.days),[decisions,setDecisions]=useState<Record<string,Record<string,string>>>(initialDraft.decisions),[signature,setSignature]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{onDraft({fields,days,decisions})},[fields,days,decisions,onDraft])
 const pending=useRef<{payload:string;key:string}|null>(null)
 const selectionKey=JSON.stringify(selected)
 useEffect(()=>{setChecks({});setSignature('')},[selectionKey])
 const reset=()=>{setChecks(value=>Object.fromEntries(Object.entries(value).filter(([key])=>!finalKeys.includes(key))));setSignature('');setError('')}
 const text=(key:string,label:string,type='text')=><label className="block">{label}<input className={style} type={type} value={fields[key]||''} maxLength={2000} onChange={e=>{reset();setFields(value=>({...value,[key]:e.target.value}))}}/></label>
 const choose=(key:string,label:string)=><label className="block">{label}<select aria-label={label} className={style} value={fields[key]||''} onChange={e=>{reset();setFields(value=>({...value,[key]:e.target.value}))}}><option value="">Choose</option><option value="yes">Yes</option><option value="no">No</option></select></label>
 const check=(key:string,label:string,final=false)=><label className="flex items-start gap-2"><input type="checkbox" checked={!!checks[key]} onChange={e=>{if(!final)reset();setChecks(value=>({...value,[key]:e.target.checked}))}}/><span>{label}</span></label>
 const rowField=(row:string,key:string,label:string,options?:string[])=><label className="block">Document {row}: {label}{options?<select aria-label={`Document ${row}: ${label}`} className={style} value={decisions[row]?.[key]||''} onChange={e=>{reset();setDecisions(value=>({...value,[row]:{...value[row],[key]:e.target.value}}))}}><option value="">Choose</option>{options.map(value=><option key={value} value={value}>{value.replaceAll('_',' ').toLowerCase()}</option>)}</select>:<input className={style} type={['validUntil','followUpOn'].includes(key)?'date':'text'} value={decisions[row]?.[key]||''} maxLength={key==='formNotation'?1000:2000} onChange={e=>{reset();setDecisions(value=>({...value,[row]:{...value[row],[key]:e.target.value}}))}}/>}</label>
 const sign=async()=>{
  if(['physical','short','indefinite'].some(key=>!fields[key])){setError('Answer physical presence, short employment, and current authorization before signing.');return}
  const alternative=method==='ALTERNATIVE'?{...Object.fromEntries(['goodStanding','allSitesEnrolled','trainingComplete','consistentProcedure','copiesReceivedBeforeVideo','sameOriginalsPresented'].map(key=>[key,!!checks[key]])),liveVideoOn:fields.examinedOn,qualificationEvidence:fields.qualification||'',videoEvidence:fields.video||''}:null
  const examination={differentDocumentsConfirmed:!!checks.different,authorizationIndefinite:fields.indefinite==='yes',authorizationThrough:fields.authorizationThrough||'',authorizationEvidence:fields.authorizationEvidence||'',examination:{examinedOn:fields.examinedOn,examinerInitials:initials,identityEvidence:fields.identity||'',businessDays:days,closedDates:(fields.closures||'').split(',').map(v=>v.trim()).filter(Boolean),calendarConfirmed:!!checks.calendar,shortEmployment:fields.short==='yes',lateReason:fields.late||'',employeeChoseDocuments:!!checks.choice,section1Reviewed:!!checks.section1,documentsGenuineAndRelated:!!checks.genuine,physicalPresence:fields.physical==='yes',listBPhotoConfirmed:!!checks.photo,alternative,documents:rowKeys.map(row=>({rowKey:row,...decisions[row],copyIds:selected[row]||[],copiesComplete:!!checks[`${row}:complete`],accepted:!!checks[`${row}:accepted`],noFollowUpConfirmed:decisions[row]?.followUpKind==='NONE'&&!!checks[`${row}:none`]}))}}
  const body={reviewId:preview.reviewId,previewSha256:preview.previewSha256,signature,attestation:preview.attestation,...Object.fromEntries(finalKeys.map(key=>[key,!!checks[key]])),examination},payload=JSON.stringify(body)
  if(pending.current?.payload!==payload)pending.current={payload,key:crypto.randomUUID()}
  setBusy(true);onBusy(true);setError('')
  try{await workforceApi.signDifferent(employeeId,taskId,{...body,requestKey:pending.current.key});onSigned()}
  catch(e){setError(e instanceof Error?e.message:'Unable to confirm signing. Retry unchanged to recover the saved result.')}
  finally{setBusy(false);onBusy(false)}
 }
 return <section aria-label="Replacement examination and signing" className="min-w-0 space-y-3 rounded border p-2 sm:p-3"><h4 className="font-bold">Examine and certify replacement documents</h4><p>Signing resolves receipt rows {preview.receiptTasks.map(task=>`${task.rowKey} (due ${task.dueOn})`).join('; ')}. Review their retained evidence and the complete new document set.</p>{error?<p role="alert">{error}</p>:null}
 <fieldset disabled={busy} className="min-w-0 space-y-3">
 {text('examinedOn','Actual replacement examination date','date')}{text('identity','Replacement examiner identity and authority')}{choose('physical','Originals examined in the employee’s physical presence')}{choose('short','Employment lasts fewer than three business days')}
 <fieldset><legend>Employer business days</legend>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,index)=><label className="mr-3 inline-flex gap-1" key={day}><input type="checkbox" checked={days.includes(index)} onChange={e=>{reset();setDays(value=>e.target.checked?[...value,index]:value.filter(n=>n!==index))}}/>{day}</label>)}</fieldset>
 {text('closures','Employer closure dates (comma-separated YYYY-MM-DD)')}{check('calendar','I confirmed the employer business calendar')}{text('late','Replacement late-completion explanation (if needed)')}
 {choose('indefinite','Current employment authorization is indefinite')}{text('authorizationThrough','Current employment authorization expiration (if finite)','date')}{text('authorizationEvidence','Current employment authorization evidence')}
 {check('different','These are different acceptable documents replacing the receipt')}{check('choice','The employee chose the replacement documents')}{check('section1','I reviewed the current Section 1 and preparer certifications')}{check('genuine','The originals reasonably appear genuine and relate to this employee')}{check('photo','List B contains a photograph (required for an E-Verify employer)')}
 {method==='ALTERNATIVE'?<fieldset className="space-y-2"><legend>Alternative-procedure findings</legend>{check('goodStanding','Employer is currently in E-Verify good standing')}{check('allSitesEnrolled','All relevant hiring sites are enrolled')}{check('trainingComplete','Required examiner training is complete')}{check('consistentProcedure','The procedure is applied consistently without discrimination')}{check('copiesReceivedBeforeVideo','I examined copies before live video')}{check('sameOriginalsPresented','The same originals were presented during live video')}{text('qualification','Current alternative-procedure qualification evidence')}{text('video','Live-video examination evidence')}</fieldset>:null}
 {rowKeys.map(row=><fieldset key={row} className="min-w-0 space-y-2 rounded border p-2"><legend>Document {row} acceptance</legend><p>Selected copies: {(selected[row]||[]).length}</p>{check(`${row}:complete`,`Document ${row}: selected copies include every required side and page`)}{check(`${row}:accepted`,`Document ${row}: acceptable for the selected list or combination`)}{rowField(row,'acceptance','Acceptance',['STANDARD','EXTENSION','OTHER_ACCEPTABLE'])}{rowField(row,'ruleSource','Official rule URL')}{rowField(row,'ruleEvidence','Acceptance and follow-up evidence')}{rowField(row,'validUntil','Verified validity through')}{rowField(row,'formNotation','Exception notation already on the reviewed form')}{rowField(row,'followUpKind','Next action',['NONE','REVERIFICATION','OTHER'])}{rowField(row,'followUpOn','Next action date')}{decisions[row]?.followUpKind==='NONE'?check(`${row}:none`,`Document ${row}: no follow-up is required`):null}</fieldset>)}
 <blockquote className="whitespace-pre-wrap rounded bg-slate-50 p-3">{preview.attestation}</blockquote>
 {check('attestationRead','I read and agree to the replacement employer certification',true)}{check('signingAsExaminer','I am the examiner who performed this replacement examination',true)}{check('reviewedAllPages','I reviewed every packet and selected copy page',true)}{check('representativeIdentityConfirmed','My identity and authority as the named replacement examiner are confirmed',true)}
 <label className="block">Replacement examiner electronic signature<input className={style} value={signature} maxLength={200} onChange={e=>setSignature(e.target.value)}/></label>
 <button type="button" className="rounded border p-2" onClick={()=>void sign()}>Sign replacement certification</button>
 </fieldset>{busy?<p role="status">Retaining signed replacement certification…</p>:null}
 </section>
}
