import {useEffect,useRef,useState} from 'react'
import {workforceApi,type I9CopyList,type I9EmployerPreview} from '../../utils/workforceApi'
const input='mt-1 block w-full min-w-0 rounded border border-slate-300 p-2'
type Decision={copyIds:string[];copiesComplete:boolean;accepted:boolean;acceptance:string;ruleSource:string;ruleEvidence:string;validUntil:string;formNotation:string;followUpKind:string;followUpOn:string;noFollowUpConfirmed:boolean}
const emptyDecision=():Decision=>({copyIds:[],copiesComplete:false,accepted:false,acceptance:'',ruleSource:'',ruleEvidence:'',validUntil:'',formNotation:'',followUpKind:'',followUpOn:'',noFollowUpConfirmed:false})
function Check({label,value,change}:{label:string;value:boolean;change:(value:boolean)=>void}){return <label className="flex items-start gap-2 text-sm"><input type="checkbox" className="mt-1" checked={value} onChange={e=>change(e.target.checked)}/><span>{label}</span></label>}
export default function I9EmployerExamination({employeeId,taskId,cycle,preview,onSigned}:{employeeId:number;taskId:number;cycle:number;preview:I9EmployerPreview;onSigned:()=>Promise<void>}){
 const [copies,setCopies]=useState<I9CopyList|null>(null),[reload,setReload]=useState(0),[decisions,setDecisions]=useState<Record<string,Decision>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('')
 const [examinedOn,setExaminedOn]=useState(''),[initials,setInitials]=useState(''),[identity,setIdentity]=useState(''),[days,setDays]=useState<number[]>([]),[closures,setClosures]=useState(''),[short,setShort]=useState(''),[late,setLate]=useState(''),[signature,setSignature]=useState(''),[checks,setChecks]=useState<Record<string,boolean>>({}),[qualification,setQualification]=useState(''),[video,setVideo]=useState('')
 const pending=useRef<{payload:string;key:string}|null>(null)
 const {reviewId,previewSha256,examinationContext:context}=preview
 useEffect(()=>{let live=true;void workforceApi.i9EmployerCopies(employeeId,taskId,{onboardingCycle:cycle,reviewId,previewSha256}).then(value=>{if(live)setCopies(value)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[employeeId,taskId,cycle,reviewId,previewSha256,reload])
 const check=(key:string,label:string)=><Check key={key} label={label} value={!!checks[key]} change={value=>setChecks(old=>({...old,[key]:value}))}/>
 const update=(key:string,change:Partial<Decision>)=>setDecisions(old=>({...old,[key]:{...(old[key]||emptyDecision()),...change}}))
 const sign=async()=>{
  if(short===''){setError('Answer whether employment lasts fewer than three business days.');return}
  const examination={examinedOn,examinerInitials:initials,identityEvidence:identity,businessDays:days,closedDates:closures.split(/[\s,]+/).filter(Boolean),calendarConfirmed:!!checks.calendarConfirmed,shortEmployment:short==='yes',lateReason:late,employeeChoseDocuments:!!checks.employeeChoseDocuments,section1Reviewed:!!checks.section1Reviewed,documentsGenuineAndRelated:!!checks.documentsGenuineAndRelated,physicalPresence:!!checks.physicalPresence,listBPhotoConfirmed:!!checks.listBPhotoConfirmed,alternative:context.examinationMethod==='ALTERNATIVE'?{goodStanding:!!checks.goodStanding,allSitesEnrolled:!!checks.allSitesEnrolled,trainingComplete:!!checks.trainingComplete,consistentProcedure:!!checks.consistentProcedure,copiesReceivedBeforeVideo:!!checks.copiesReceivedBeforeVideo,sameOriginalsPresented:!!checks.sameOriginalsPresented,liveVideoOn:examinedOn,qualificationEvidence:qualification,videoEvidence:video}:null,documents:(copies?.documents||[]).map(row=>({rowKey:row.key,...(decisions[row.key]||emptyDecision())}))}
  const body={onboardingCycle:cycle,reviewId,previewSha256,signature,attestation:preview.attestation,attestationRead:!!checks.attestationRead,signingAsExaminer:!!checks.signingAsExaminer,representativeIdentityConfirmed:!!checks.representativeIdentityConfirmed,reviewedAllPages:!!checks.reviewedAllPages,examination},payload=JSON.stringify(body)
  if(pending.current?.payload!==payload)pending.current={payload,key:crypto.randomUUID()}
  setBusy(true);setError('')
  try{const result=await workforceApi.signI9Employer(employeeId,taskId,{...body,requestKey:pending.current.key});setReceipt(`Employer I-9 signed and retained at ${result.signedAt}.`);await onSigned()}
  catch(e){setError(e instanceof Error?e.message:'Unable to confirm employer signing. Retry unchanged to recover its receipt.')}
  finally{setBusy(false)}
 }
 if(receipt)return <section aria-label="Employer certification receipt"><p role="status">{receipt}</p>{error?<p role="alert">{error}</p>:null}<button type="button" className="underline" onClick={()=>void onSigned().catch(e=>setError(e.message))}>Refresh onboarding status</button></section>
 return <section aria-label="Employer examination and signature" className="min-w-0 space-y-3 rounded-xl border p-4">
  <h3 className="font-bold">Examine documents and certify Section 2</h3>
  <p className="text-sm">Named representative: {context.representativeNameAndTitle}. Hire date: {context.hireDate}. Offer accepted: {context.offerAcceptedOn}. The signature uses the actual server date (currently {context.today}).</p>
  <p className="text-sm">Complete this as the representative who performed the examination. Editing the employer draft requires a new preview and page review. Examination entries below are not saved until signing; keep this page open while completing them.</p>
  {error?<p role="alert">{error}</p>:null}
  <form onSubmit={e=>{e.preventDefault();void sign()}}><fieldset disabled={busy} className="min-w-0 space-y-4">
   <label className="block">Actual examination date<input required type="date" className={input} value={examinedOn} min={context.offerAcceptedOn} max={context.today} onChange={e=>setExaminedOn(e.target.value)}/></label>
   <label className="block">Examiner initials<input required maxLength={20} className={input} value={initials} onChange={e=>setInitials(e.target.value)}/></label>
   <label className="block">Examiner identity and authority evidence<textarea required minLength={12} maxLength={2000} className={input} value={identity} onChange={e=>setIdentity(e.target.value)}/></label>
   <fieldset className="space-y-2"><legend className="font-semibold">Employer business calendar</legend><div className="flex flex-wrap gap-3">{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,index)=><Check key={day} label={day} value={days.includes(index)} change={yes=>setDays(old=>yes?[...old,index].sort():old.filter(n=>n!==index))}/>)}</div><label className="block">Closure dates (YYYY-MM-DD, separated by commas)<textarea className={input} value={closures} onChange={e=>setClosures(e.target.value)}/></label>{check('calendarConfirmed','I confirm these are the actual business days and relevant closure dates.')}</fieldset>
   <label className="block">Employment lasts fewer than three business days<select required className={input} value={short} onChange={e=>setShort(e.target.value)}><option value="">Select an answer</option><option value="no">No</option><option value="yes">Yes</option></select></label>
   <label className="block">Late-completion explanation (required if signing after the deadline)<textarea maxLength={2000} className={input} value={late} onChange={e=>setLate(e.target.value)}/></label>
   {check('employeeChoseDocuments','The employee chose the acceptable document combination.')}{check('section1Reviewed','I reviewed the current employee Section 1 and every required preparer certification.')}{check('documentsGenuineAndRelated','The documents reasonably appear genuine and relate to this employee.')}
   {context.examinationMethod==='PHYSICAL'?check('physicalPresence','I physically examined the original documents in the employee’s presence.'):<fieldset className="space-y-2 rounded border p-3"><legend>Alternative procedure qualification and examination</legend>{check('goodStanding','The employer is currently an E-Verify participant in good standing.')}{check('allSitesEnrolled','Every hiring site using this procedure is enrolled.')}{check('trainingComplete','I completed the required E-Verify training.')}{check('consistentProcedure','The procedure is applied consistently and without discrimination.')}{check('copiesReceivedBeforeVideo','I received and examined all required document copies before live video.')}{check('sameOriginalsPresented','The employee presented these same original documents during live video on the examination date.')}<label className="block">Eligibility, site enrollment and training evidence<textarea required minLength={12} maxLength={2000} className={input} value={qualification} onChange={e=>setQualification(e.target.value)}/></label><label className="block">Live video examination evidence<textarea required minLength={12} maxLength={2000} className={input} value={video} onChange={e=>setVideo(e.target.value)}/></label></fieldset>}
   {context.eVerify&&context.documentChoice==='LIST_B_C'?check('listBPhotoConfirmed','The List B identity document contains a photograph.'):null}
   <button type="button" className="underline" onClick={()=>{setError('');setReload(n=>n+1)}}>Refresh copies available for certification</button>
   {copies?.documents.map(row=>{const d=decisions[row.key]||emptyDecision();return <fieldset key={row.key} className="min-w-0 space-y-3 rounded border p-3"><legend className="font-semibold">{row.label}: examination decision</legend>
    <p className="text-sm">Select the clear copies containing every required side/page. Display each selected copy above before signing.</p>
    {!row.copies.length?<p>No retained copies. Upload and review copies above, then refresh this list.</p>:row.copies.map((copy,index)=><Check key={copy.id} label={`Use ${row.label.toLowerCase()} copy ${index+1} (${copy.pageCount} page(s))`} value={d.copyIds.includes(String(copy.id))} change={yes=>update(row.key,{copyIds:yes?[...d.copyIds,String(copy.id)]:d.copyIds.filter(id=>id!==String(copy.id))})}/>)}
    <Check label="The selected copies are clear and include every required side/page." value={d.copiesComplete} change={copiesComplete=>update(row.key,{copiesComplete})}/><Check label="I determined this document is acceptable for the chosen list or combination." value={d.accepted} change={accepted=>update(row.key,{accepted})}/>
    <label className="block">Acceptance basis<select required className={input} value={d.acceptance} onChange={e=>update(row.key,{acceptance:e.target.value,validUntil:'',formNotation:'',ruleSource:'',ruleEvidence:''})}><option value="">Choose a basis</option><option value="STANDARD">Standard unexpired document</option><option value="RECEIPT">Acceptable receipt</option><option value="EXTENSION">Authorized extension</option><option value="OTHER_ACCEPTABLE">Other rule-supported acceptance</option></select></label>
    {d.acceptance&&d.acceptance!=='STANDARD'?<><label className="block">Validity through date<input type="date" className={input} value={d.validUntil} onChange={e=>update(row.key,{validUntil:e.target.value})}/></label><label className="block">Exact initialed and dated notation already on the reviewed form<textarea required maxLength={1000} className={input} value={d.formNotation} onChange={e=>update(row.key,{formNotation:e.target.value})}/></label></>:null}
    <label className="block">Required document follow-up<select required className={input} value={d.followUpKind} onChange={e=>update(row.key,{followUpKind:e.target.value,followUpOn:'',noFollowUpConfirmed:false})}><option value="">Choose a decision</option><option value="NONE">No follow-up required</option><option value="RECEIPT_REPLACEMENT">Receipt replacement</option><option value="REVERIFICATION">Employment authorization reverification</option><option value="OTHER">Other required follow-up</option></select></label>
    {d.followUpKind==='NONE'?<Check label="I verified that this document requires no follow-up." value={d.noFollowUpConfirmed} change={noFollowUpConfirmed=>update(row.key,{noFollowUpConfirmed})}/>:d.followUpKind?<label className="block">Follow-up due date<input required type="date" className={input} value={d.followUpOn} onChange={e=>update(row.key,{followUpOn:e.target.value})}/></label>:null}
    {(d.acceptance&&d.acceptance!=='STANDARD')||(d.followUpKind&&d.followUpKind!=='NONE')?<><label className="block">Official rule URL<input required type="url" className={input} value={d.ruleSource} onChange={e=>update(row.key,{ruleSource:e.target.value})}/></label><label className="block">Verified rule and acceptance evidence<textarea required minLength={12} maxLength={2000} className={input} value={d.ruleEvidence} onChange={e=>update(row.key,{ruleEvidence:e.target.value})}/></label></>:null}
   </fieldset>})}
   {context.eVerify?<p className="text-sm">Signing creates an open E-Verify case-review task. It does not create or resolve a case with E-Verify.</p>:null}
   <blockquote className="rounded bg-slate-50 p-3">{preview.attestation}</blockquote>
   {check('attestationRead','I read and agree to the employer certification above.')}{check('signingAsExaminer','I am the named representative who performed this examination.')}{check('representativeIdentityConfirmed','I confirm my identity and authority as the representative named on the reviewed form.')}{check('reviewedAllPages','I reviewed all four form pages, every preparer certificate and every selected document-copy page.')}
   <label className="block">Your employer electronic signature<input required maxLength={200} autoComplete="off" className={input} value={signature} onChange={e=>setSignature(e.target.value)}/></label>
   <button disabled={!copies?.documents.length} className="rounded bg-slate-950 px-3 py-2 font-bold text-white disabled:opacity-40">{busy?'Confirming employer certification…':'Sign and complete employer I-9'}</button>
  </fieldset></form>
 </section>
}
