import {useEffect,useRef,useState} from 'react'
import {workforceApi,type EVerifyHistory,type EVerifyResult} from '../../utils/workforceApi'
const input='mt-1 block w-full min-w-0 rounded border border-slate-300 p-2'
const outcomes=[['EMPLOYMENT_AUTHORIZED','Employment Authorized'],['PENDING_SSN','Pending SSN / case not created'],['NEEDS_MORE_TIME','E-Verify needs more time'],['MISMATCH','Mismatch'],['CASE_IN_CONTINUANCE','Case in continuance'],['REVIEW_UPDATE','Review and update data'],['CLOSE_AND_RESUBMIT','Close case and resubmit'],['FINAL_NONCONFIRMATION','Final nonconfirmation — disposition review required'],['OTHER_PENDING','Other unresolved result']]
export default function I9EVerifyResults({employeeId,taskId,onUpdated}:{employeeId:number;taskId:string|number;onUpdated:()=>void}){
 const [history,setHistory]=useState<EVerifyHistory|null>(null),[reload,setReload]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[outcome,setOutcome]=useState(''),[reference,setReference]=useState(''),[observed,setObserved]=useState(''),[closed,setClosed]=useState(''),[nextOn,setNextOn]=useState(''),[next,setNext]=useState(''),[note,setNote]=useState(''),[file,setFile]=useState<File|null>(null),[checks,setChecks]=useState<Record<string,boolean>>({})
 const pending=useRef<{payload:string;file:File;key:string}|null>(null)
 useEffect(()=>{let live=true;void workforceApi.eVerifyHistory(employeeId,taskId).then(data=>{if(live)setHistory(data)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[employeeId,taskId,reload])
 const invalidate=()=>setChecks({})
 const latest=history?.events[0]
 const save=async()=>{
  if(!history||!file||closed==='')return
  const result:EVerifyResult={outcome,caseReference:reference,observedOn:observed,caseClosed:closed==='yes',nextActionOn:nextOn,nextAction:next,evidenceNote:note,verifiedAgainstOfficialCase:!!checks.verifiedAgainstOfficialCase,employeeAndEmployerMatched:!!checks.employeeAndEmployerMatched,evidenceReviewed:!!checks.evidenceReviewed},body={expectedRevision:history.revision,result},payload=JSON.stringify(body)
  if(pending.current?.payload!==payload||pending.current?.file!==file)pending.current={payload,file,key:crypto.randomUUID()}
  setBusy(true);setError('');setNotice('')
  try{const saved=await workforceApi.recordEVerifyResult(employeeId,taskId,{...body,requestKey:pending.current.key},file);setNotice(saved.status==='COMPLETE'?'Authorized closure evidence retained. E-Verify follow-up completed.':'Result evidence retained. This follow-up remains in progress.');setChecks({});setReload(n=>n+1);onUpdated()}
  catch(e){setError(e instanceof Error?e.message:'Unable to confirm result recording. Retry unchanged to recover the receipt.')}
  finally{setBusy(false)}
 }
 return <section aria-label="E-Verify result evidence" className="min-w-0 space-y-3 rounded border p-3">
  <h5 className="font-bold">Record the reviewed E-Verify result</h5><p>This records evidence from your official case or pending-case records. It does not submit or change a case in E-Verify. Pending results do not automatically withhold earned pay or change employment status.</p>
  {error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}
  {latest?<div aria-label="Latest E-Verify follow-up" role="region" className="space-y-2 break-words rounded bg-slate-50 p-3"><p className="font-bold">Latest recorded result: {outcomes.find(([key])=>key===latest.result.outcome)?.[1]||latest.result.outcome}</p><p>Observed {latest.result.observedOn} · history revision {latest.revision}</p>{latest.result.nextAction?<><p className="font-semibold">Review by {latest.result.nextActionOn}</p><p className="whitespace-pre-wrap">{latest.result.nextAction}</p><p>This follow-up remains unresolved. The review date was supplied by the reviewing admin.</p></>:<p>Authorized closure evidence is retained. Review any later correction before relying on this result.</p>}</div>:null}
  <button type="button" className="underline" disabled={busy} onClick={()=>{setError('');setReload(n=>n+1)}}>Refresh E-Verify result history</button>
  {history?.events.map(event=><details key={event.id}><summary>Recorded result {event.revision}: {outcomes.find(([key])=>key===event.result.outcome)?.[1]||event.result.outcome} · {event.recordedAt}</summary><div className="space-y-1 break-words"><p>Case reference: {event.result.caseReference||'No case created'} · observed {event.result.observedOn} · closed: {event.result.caseClosed?'yes':'no'}</p><p className="whitespace-pre-wrap">{event.result.evidenceNote}</p>{event.result.nextAction?<p className="whitespace-pre-wrap">Next action by {event.result.nextActionOn}: {event.result.nextAction}</p>:null}<button type="button" className="underline" onClick={()=>void workforceApi.download(Number(event.documentId),event.filename,true).catch(e=>setError(e.message))}>Download E-Verify result evidence {event.revision}</button></div></details>)}
  <form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={busy||!history} className="min-w-0 space-y-3">
   <label className="block">Official case result<select required className={input} value={outcome} onChange={e=>{invalidate();setOutcome(e.target.value);setNext('');setNextOn('');setClosed('')}}><option value="">Select the reported result</option>{outcomes.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
   <label className="block">Official case reference<input required={outcome!=='PENDING_SSN'} maxLength={100} className={input} value={reference} onChange={e=>{invalidate();setReference(e.target.value)}}/></label>
   <label className="block">Date this result was observed<input required type="date" className={input} value={observed} onChange={e=>{invalidate();setObserved(e.target.value)}}/></label>
   <label className="block">Official case is closed<select required className={input} value={closed} onChange={e=>{invalidate();setClosed(e.target.value)}}><option value="">Select an answer</option><option value="yes">Yes</option><option value="no">No / case not created</option></select></label>
   {outcome&&outcome!=='EMPLOYMENT_AUTHORIZED'?<><p>Keep the follow-up open until the required disposition or replacement-case work is resolved.</p><label className="block">Next action review date<input required type="date" className={input} value={nextOn} onChange={e=>{invalidate();setNextOn(e.target.value)}}/></label><label className="block">Required next action<textarea required minLength={12} maxLength={2000} className={input} value={next} onChange={e=>{invalidate();setNext(e.target.value)}}/></label></>:null}
   <label className="block">Case evidence review note<textarea required minLength={12} maxLength={2000} className={input} value={note} onChange={e=>{invalidate();setNote(e.target.value)}}/></label>
   <label className="block">Reviewed case evidence PDF (up to 5 MB)<input required type="file" accept="application/pdf" className="block w-full min-w-0 max-w-full" onChange={e=>{invalidate();setFile(e.target.files?.[0]||null);pending.current=null}}/></label>
   {([['verifiedAgainstOfficialCase','I verified this result against official case or pending-case records.'],['employeeAndEmployerMatched','I confirmed these records match this employee and employer.'],['evidenceReviewed','I reviewed the attached evidence and confirmed it supports this result.']] as const).map(([key,label])=><label key={key} className="flex items-start gap-2"><input type="checkbox" checked={!!checks[key]} onChange={e=>setChecks(old=>({...old,[key]:e.target.checked}))}/><span>{label}</span></label>)}
   <button className="rounded bg-slate-950 px-3 py-2 font-bold text-white disabled:opacity-40">{busy?'Recording reviewed result…':'Retain E-Verify result evidence'}</button>
  </fieldset></form>
 </section>
}
