import {useEffect,useRef,useState} from 'react'
import {workforceApi,type PreparerRoster} from '../../utils/workforceApi'
export default function I9PreparerRoster({employeeId,taskId,cycle,onReview}:{employeeId:number;taskId:number;cycle:number;onReview:(value:{confirmed:boolean;fingerprint:string}|undefined)=>void}){
 const retry=useRef<Record<string,unknown>|null>(null)
 const [data,setData]=useState<PreparerRoster|null>(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[evidence,setEvidence]=useState(''),[confirmed,setConfirmed]=useState(false),[complete,setComplete]=useState(false),[link,setLink]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reload,setReload]=useState(0)
 useEffect(()=>{let live=true;void workforceApi.i9Preparers(employeeId,taskId,cycle).then(value=>{if(live){setData(value);setComplete(false);onReview(undefined)}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[employeeId,taskId,cycle,reload,onReview])
 const invite=async()=>{if(!data)return;setBusy(true);setError('');setLink('');try{const body=retry.current||{onboardingCycle:cycle,submissionId:data.submissionId,name,email,evidence,confirmed,requestKey:crypto.randomUUID()};retry.current=body;const row=await workforceApi.inviteI9Preparer(employeeId,taskId,body);retry.current=null;setLink(`${location.origin}/employee/payroll/preparer#access=${row.token}`);setName('');setEmail('');setEvidence('');setConfirmed(false);setReload(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'Unable to create invitation.')}finally{setBusy(false)}}
 const cancel=async(id:string)=>{setBusy(true);setError('');try{await workforceApi.cancelI9Preparer(employeeId,taskId,id,{onboardingCycle:cycle,reason});setReason('');setReload(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'Unable to cancel invitation.')}finally{setBusy(false)}}
 const active=data?.requests.filter(r=>!r.cancelledAt)||[],ready=active.length>0&&active.every(r=>r.signatureId),input='mt-1 block w-full rounded border border-slate-300 p-2'
 return <section aria-label="I-9 preparer roster" className="my-4 space-y-3 rounded-xl border p-4"><h3 className="font-bold">Preparer and translator certifications</h3><p className="text-sm">List every person who assisted with this employee’s Section 1. Each person signs a separate Supplement A using their own private link.</p>{error?<p role="alert">{error}</p>:null}
  <button type="button" disabled={busy} className="underline" onClick={()=>setReload(v=>v+1)}>Refresh preparer certifications</button>
  <ul>{data?.requests.map(r=><li key={r.id} className="my-2 rounded border p-2 text-sm">{r.name} · {r.email} · {r.cancelledAt?'Cancelled':r.signedAt?`Signed ${r.signedAt}`:`Awaiting signature; access expires ${r.expiresAt}`}{!r.cancelledAt&&!r.signedAt?<button type="button" disabled={busy||reason.trim().length<12} className="ml-2 underline" onClick={()=>void cancel(r.id)}>Cancel invitation for {r.name}</button>:null}</li>)}</ul>
  <label className="block text-sm">Cancellation reason (for an unsigned invitation)<input className={input} value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label>
  <form onSubmit={e=>{e.preventDefault();void invite()}}><fieldset disabled={busy||!data} className="space-y-3"><legend className="font-bold">Invite a preparer</legend><label className="block text-sm">Intended preparer name (first, optional middle initial, last)<input className={input} value={name} required maxLength={200} onChange={e=>{setName(e.target.value);retry.current=null}}/></label><label className="block text-sm">Preparer email<input type="email" className={input} value={email} required maxLength={254} onChange={e=>{setEmail(e.target.value);retry.current=null}}/></label><label className="block text-sm">Preparer identity and contact verification evidence<textarea className={input} value={evidence} required minLength={12} maxLength={2000} onChange={e=>{setEvidence(e.target.value);retry.current=null}}/></label><label className="block text-sm"><input type="checkbox" checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);retry.current=null}}/> I verified this intended recipient and that they assisted with this employee’s Section 1.</label><button disabled={!confirmed} className="rounded bg-slate-950 px-3 py-2 font-bold text-white disabled:opacity-40">Create private preparer invitation</button></fieldset></form>
  {link?<label className="block text-sm">Private preparer link (shown once)<input readOnly className={input} value={link}/><span>Share privately with the verified recipient. The link expires in 14 days; it is not emailed automatically.</span></label>:null}
  <label className="block text-sm"><input type="checkbox" disabled={!ready||busy} checked={complete} onChange={e=>{setComplete(e.target.checked);onReview(e.target.checked&&data?{confirmed:true,fingerprint:data.fingerprint}:undefined)}}/> I confirmed this list includes every preparer/translator and reviewed each signed certification with the employee’s Section 1.</label>
 </section>
}
