import {useCallback,useEffect,useRef,useState} from 'react'
import {i9PreparerApi,PREPARER_SESSION_KEY,type PreparerPacket,type PreparerPreview} from '../../utils/i9PreparerApi'
import W4PdfReview from './W4PdfReview'
const empty={firstName:'',lastName:'',middleInitial:'',address:'',city:'',state:'',postalCode:''}
const labels={firstName:'Preparer first name',lastName:'Preparer last name',middleInitial:'Preparer middle initial (optional)',address:'Preparer street address',city:'Preparer city or town',state:'Preparer state',postalCode:'Preparer ZIP code'}
export default function I9PreparerPortal(){
 const [token,setToken]=useState(()=>{const supplied=new URLSearchParams(location.hash.slice(1)).get('access');if(supplied){sessionStorage.setItem(PREPARER_SESSION_KEY,supplied);history.replaceState(null,'',location.pathname+location.search)}return sessionStorage.getItem(PREPARER_SESSION_KEY)||''})
 const [packet,setPacket]=useState<PreparerPacket|null>(null),[form,setForm]=useState(empty),[preview,setPreview]=useState<PreparerPreview|null>(null),[signature,setSignature]=useState(''),[confirmed,setConfirmed]=useState(false),[displayed,setDisplayed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const retry=useRef<Record<string,unknown>|null>(null)
 useEffect(()=>{let live=true;if(token)void i9PreparerApi.packet(token).then(data=>{if(live)setPacket(data)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[token])
 const change=(key:keyof typeof form,value:string)=>{setForm(f=>({...f,[key]:value}));setPreview(null);setSignature('');setConfirmed(false);setDisplayed(false);retry.current=null;setError('')}
 const prepare=async()=>{setBusy(true);setError('');setPreview(null);setDisplayed(false);setConfirmed(false);setSignature('');retry.current=null;try{setPreview(await i9PreparerApi.preview(token,form))}catch(e){setError(e instanceof Error?e.message:'Unable to prepare the supplement.')}finally{setBusy(false)}}
 const onDisplayed=useCallback(async()=>{if(preview){await i9PreparerApi.page(token,{reviewId:preview.reviewId,previewSha256:preview.previewSha256,displayed:true});setDisplayed(true)}},[preview,token])
 const sign=async()=>{if(!preview)return;setBusy(true);setError('');try{const body=retry.current||{reviewId:preview.reviewId,previewSha256:preview.previewSha256,signature,attestation:preview.attestation,attestationRead:confirmed,reviewed:displayed,signingAsPreparer:confirmed,requestKey:crypto.randomUUID()};retry.current=body;const receipt=await i9PreparerApi.sign(token,body);setPacket(p=>p?{...p,signature:{...receipt,documentId:''}}:p);setPreview(null);setForm(empty);setSignature('');retry.current=null}catch(e){setError(e instanceof Error?e.message:'Unable to sign the supplement.')}finally{setBusy(false)}}
 return <main className="min-h-screen bg-slate-100 p-4"><section aria-label="I-9 preparer certification" className="mx-auto max-w-2xl space-y-4 rounded-xl bg-white p-5 shadow">
  <h1 className="text-2xl font-bold">I-9 preparer / translator certification</h1>
  {error?<p role="alert" className="text-red-800">{error}</p>:null}
  {!token?<p>Open your private invitation from the hiring admin to complete your own certification.</p>:null}
  {packet?<><p>This invitation is for {packet.recipientName}, assisting {packet.employee.firstName} {packet.employee.middleInitial} {packet.employee.lastName}. Complete only your own certification. Each other preparer needs a separate invitation.</p>
   {packet.signature?<><p role="status">Your Supplement A was signed at {packet.signature.signedAt}. Confirmation {packet.signature.id}.</p><button type="button" className="font-bold underline" onClick={()=>void i9PreparerApi.download(token).catch(e=>setError(e.message))}>Download my signed Supplement A</button></>:!packet.current?<p>The employee’s Section 1 has changed. Ask the hiring admin for a current invitation.</p>:<>
   <form autoComplete="off" onSubmit={e=>{e.preventDefault();void prepare()}}><fieldset disabled={busy} className="space-y-3"><legend className="font-bold">Your identity and address</legend>{(Object.keys(labels) as Array<keyof typeof form>).map(key=><label key={key} className="block text-sm font-semibold">{labels[key]}<input autoComplete="off" required={key!=='middleInitial'} maxLength={key==='middleInitial'?1:key==='postalCode'?6:200} className="mt-1 block w-full rounded border border-slate-300 p-2" value={form[key]} onChange={e=>change(key,e.target.value)}/></label>)}<button className="rounded bg-slate-950 px-4 py-2 font-bold text-white">Prepare my Supplement A</button></fieldset></form>
   {preview?<><W4PdfReview formName="I-9 Supplement A" pageCount={1} pdfBase64={preview.pdfBase64} onDisplayed={onDisplayed} reviewTitle="Review your unsigned Supplement A"/><fieldset disabled={busy} className="space-y-3"><legend className="font-bold">Your preparer certification</legend><p>{preview.attestation}</p><label className="block"><input type="checkbox" checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);retry.current=null}}/> I am the intended preparer, reviewed this supplement, read this attestation and intend to sign my own certification electronically.</label><label className="block">Preparer electronic signature<input autoComplete="off" maxLength={200} className="mt-1 block w-full rounded border p-2" value={signature} onChange={e=>{setSignature(e.target.value);retry.current=null}}/></label><button type="button" disabled={!displayed||!confirmed||!signature.trim()} className="rounded bg-slate-950 px-4 py-2 font-bold text-white disabled:opacity-40" onClick={()=>void sign()}>Sign my Supplement A</button></fieldset></>:null}
   </>}
  </>:null}
  {token?<button type="button" disabled={busy} className="block underline" onClick={()=>{sessionStorage.removeItem(PREPARER_SESSION_KEY);setToken('');setPacket(null);setPreview(null);setForm(empty);setSignature('');retry.current=null}}>Close private preparer access on this browser</button>:null}
 </section></main>
}
