import {useEffect,useRef,useState} from 'react'
import {workforceApi,type I9QualificationState} from '../../utils/workforceApi'
const decisions=[['eVerifyEnrolled','Employer enrolled in E-Verify'],['goodStanding','Current E-Verify good standing'],['allSitesEnrolled','All covered hiring sites enrolled'],['trainingComplete','Required examiner training complete'],['consistentProcedure','Consistent, nondiscriminatory procedure']] as const
const input='mt-1 block w-full min-w-0 rounded border border-slate-300 p-2'
export default function I9QualificationSettings(){
 const [data,setData]=useState<I9QualificationState|null>(null),[form,setForm]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reload,setReload]=useState(0)
 const pending=useRef<{payload:string;key:string}|null>(null)
 useEffect(()=>{let live=true;setBusy(true);setError('');void workforceApi.i9Qualification().then(result=>{if(!live)return;setData(result);setForm({siteName:String(result.current?.findings.siteName||''),observedOn:result.today});pending.current=null}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setBusy(false)});return()=>{live=false}},[reload])
 const change=(key:string,value:string)=>{setForm(old=>({...old,[key]:value}));setNotice('')}
 const save=async()=>{if(!data)return;const findings={siteName:form.siteName,observedOn:form.observedOn,evidence:form.evidence,...Object.fromEntries(decisions.map(([key])=>[key,form[key]==='yes']))},body={findings,expectedRevision:data.revision},payload=JSON.stringify(body);if(pending.current?.payload!==payload)pending.current={payload,key:crypto.randomUUID()};setBusy(true);setError('');setNotice('');try{const result=await workforceApi.saveI9Qualification({...body,requestKey:pending.current.key});setData(result);pending.current=null;setNotice(`Qualification revision ${result.recordedRevision} retained. Prepare fresh document reviews after a change.`)}catch(e){setError(e instanceof Error?e.message:'Unable to confirm save. Retry unchanged or reload current history.')}finally{setBusy(false)}}
 return <section aria-label="Current I-9 employer qualification" className="mt-6 min-w-0 space-y-3 rounded border p-3"><h3 className="font-bold">Current I-9 employer and site qualification</h3><p>Record the current findings for this payroll facility and covered hiring sites. Changes preserve signed hiring evidence and require fresh follow-up reviews. These entries do not enroll an employer or verify an external account.</p>{error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}
 <button type="button" disabled={busy} className="underline" onClick={()=>{setNotice('');setReload(n=>n+1)}}>Reload qualification history (replaces unsaved entries)</button>
 <form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={busy||!data} className="min-w-0 space-y-3"><label className="block">Covered hiring site(s)<input className={input} required maxLength={200} value={form.siteName||''} onChange={e=>change('siteName',e.target.value)}/></label><label className="block">Qualification observed on<input className={input} type="date" required max={data?.today} value={form.observedOn||''} onChange={e=>change('observedOn',e.target.value)}/></label>
 {decisions.map(([key,label])=><label key={key} className="block">{label}<select aria-label={label} className={input} required value={form[key]||''} onChange={e=>change(key,e.target.value)}><option value="">Choose current finding…</option><option value="yes">Yes — verified</option><option value="no">No — not currently verified</option></select></label>)}
 <label className="block">Qualification evidence<textarea className={input} required minLength={12} maxLength={2000} value={form.evidence||''} onChange={e=>change('evidence',e.target.value)}/></label><button type="submit" className="rounded bg-slate-900 px-3 py-2 font-semibold text-white disabled:opacity-40" disabled={decisions.some(([key])=>!['yes','no'].includes(form[key]))}>Record current qualification</button></fieldset></form>
 <details><summary className="cursor-pointer font-semibold">Qualification history · revision {data?.revision||0}</summary>{data?.history.map(row=><article key={row.revision} className="my-3 space-y-2 rounded border p-2"><p>Revision {row.revision} · recorded {row.recordedAt} · observed {String(row.findings.observedOn)} · admin {row.actorUserId}</p><p className="break-words">{String(row.findings.siteName)}</p>{decisions.map(([key,label])=><p key={key}>{label}: {row.findings[key]===true?'Verified':'Not currently verified'}</p>)}<p className="whitespace-pre-wrap break-words">{String(row.findings.evidence)}</p></article>)}</details></section>
}
