import {useEffect,useRef,useState} from 'react'
import {workforceApi,type I9ReceiptPreview} from '../../utils/workforceApi'
import I9ReceiptCopies from './I9ReceiptCopies'
import I9ReceiptReviewPages from './I9ReceiptReviewPages'
const inputClass='block w-full min-w-0 rounded border p-2'
const yesNo=[['','Choose'],['yes','Yes'],['no','No']]
export default function I9ReceiptWorkspace({employeeId,taskId,signatureId,onUpdated}:{employeeId:number;taskId:string|number;signatureId:string|number;onUpdated:()=>void}){
 const [open,setOpen]=useState(false),[context,setContext]=useState<Awaited<ReturnType<typeof workforceApi.receiptContext>>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [form,setForm]=useState<Record<string,string>>({}),[facts,setFacts]=useState<Record<string,string>>({}),[checks,setChecks]=useState<Record<string,boolean>>({}),[signature,setSignature]=useState(''),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<I9ReceiptPreview|null>(null)
 const [draftState,setDraftState]=useState<Awaited<ReturnType<typeof workforceApi.receiptDraft>>|null>(null),[loading,setLoading]=useState(false),[notice,setNotice]=useState(''),[savedShape,setSavedShape]=useState('')
 const loadVersion=useRef(0)
 const saveRetry=useRef<{json:string;key:string}|null>(null)
 const retry=useRef<{json:string;key:string}|null>(null)
 const clearConsent=()=>{setChecks({});setSignature('');retry.current=null}
 const load=async()=>{
  const version=++loadVersion.current
  setLoading(true);setError('');setNotice('')
  try{const [value,draft]=await Promise.all([workforceApi.receiptContext(employeeId,taskId),workforceApi.receiptDraft(employeeId,taskId)])
   if(version!==loadVersion.current)return
   const nextForm={...(draft.draft?.form||{}),amendedOn:value.today},nextFacts={...(draft.draft?.facts||{}),examinedOn:draft.draft?.facts.examinedOn||value.today}
   setContext(value);setDraftState(draft);setForm(nextForm);setFacts(nextFacts);setSavedShape(JSON.stringify({form:nextForm,facts:nextFacts}));setPreview(null);setSelected([]);clearConsent();saveRetry.current=null;setNotice(draft.invalidated?'Source evidence changed. Start a fresh review.':draft.draft?'Your private unfinished receipt amendment was restored. Review and confirm everything again.':'')
  }catch(e){if(version===loadVersion.current)setError(e instanceof Error?e.message:'Unable to load receipt draft.')}finally{if(version===loadVersion.current)setLoading(false)}
 }
 useEffect(()=>{if(open)void load();return()=>{loadVersion.current++}},[employeeId,taskId,open])
 const save=async()=>{if(!draftState)return;setBusy(true);setError('');try{
  const draft={form,facts},body={draft,basisHash:draftState.basisHash,expectedRevision:draftState.revision},json=JSON.stringify(body)
  if(saveRetry.current?.json!==json)saveRetry.current={json,key:crypto.randomUUID()}
  const saved=await workforceApi.saveReceiptDraft(employeeId,taskId,{...body,requestKey:saveRetry.current.key});setDraftState(saved);setSavedShape(JSON.stringify(draft));setNotice('Unfinished receipt amendment saved securely for your admin account.');saveRetry.current=null
 }catch(e){setError(e instanceof Error?e.message:'Unable to save this draft.')}finally{setBusy(false)}}

 const editForm=(key:string,value:string)=>{setForm(f=>({...f,[key]:value}));setNotice('');setPreview(null);setSelected([]);clearConsent()}
 const editFact=(key:string,value:string)=>{setFacts(f=>({...f,[key]:value}));setNotice('');clearConsent()}
 const field=(key:string,label:string,type='text',required=false)=> <label key={key} className="block">{label}<input aria-label={label} className={inputClass} type={type} required={required} value={form[key]||''} onChange={e=>editForm(key,e.target.value)}/></label>
 const fact=(key:string,label:string,type='text')=><label key={key} className="block">{label}{type==='textarea'?<textarea aria-label={label} className={inputClass} value={facts[key]||''} onChange={e=>editFact(key,e.target.value)}/>:<input aria-label={label} className={inputClass} type={type} value={facts[key]||''} onChange={e=>editFact(key,e.target.value)}/>}</label>
 const choice=(key:string,label:string,options:string[][])=><label key={key} className="block">{label}<select aria-label={label} className={inputClass} value={facts[key]||''} onChange={e=>editFact(key,e.target.value)}>{options.map(([value,name])=><option key={value} value={value}>{name}</option>)}</select></label>
 const confirm=(key:string,label:string)=><label key={key} className="block"><input type="checkbox" checked={checks[key]===true} onChange={e=>{setChecks(c=>({...c,[key]:e.target.checked}));retry.current=null}}/> {label}</label>
 const prepare=async()=>{if(!context)return;setBusy(true);setError('');setPreview(null);clearConsent();try{setPreview(await workforceApi.receiptPreview(employeeId,taskId,{signatureId,answers:{sourceKind:context.sourceKind,rowKey:context.rowKey,replacementKind:'ACTUAL_REPLACEMENT',replacement:{title:form.title,issuingAuthority:form.issuingAuthority,number:form.number||'',expiresOn:form.expiresOn||''},examinerName:form.examinerName,initials:form.initials,amendedOn:form.amendedOn,explanation:form.explanation}}));setSelected([])}catch(e){setError(e instanceof Error?e.message:'Unable to prepare amendment.')}finally{setBusy(false)}}
 const sign=async()=>{if(!preview)return;setBusy(true);setError('');try{
  const bool=(key:string)=>facts[key]==='yes'?true:facts[key]==='no'?false:undefined
  const alternative=facts.examinationMethod==='ALTERNATIVE'?{...Object.fromEntries(['goodStanding','allSitesEnrolled','trainingComplete','consistentProcedure','copiesReceivedBeforeVideo','sameOriginalsPresented'].map(k=>[k,checks[k]===true])),liveVideoOn:facts.liveVideoOn,qualificationEvidence:facts.qualificationEvidence,videoEvidence:facts.videoEvidence}:null
  const examination={examinedOn:facts.examinedOn,identityEvidence:facts.identityEvidence,actualReplacementConfirmed:checks.actualReplacementConfirmed===true,receiptMatchEvidence:facts.receiptMatchEvidence,documentsGenuineAndRelated:checks.documentsGenuineAndRelated===true,copiesComplete:checks.copiesComplete===true,copyIds:selected,examinationMethod:facts.examinationMethod,physicalPresence:bool('physicalPresence'),alternative,acceptance:facts.acceptance,acceptanceSource:facts.acceptanceSource,acceptanceEvidence:facts.acceptanceEvidence,validUntil:facts.validUntil||'',authorizationIndefinite:bool('authorizationIndefinite'),authorizationThrough:facts.authorizationThrough||'',documentRequiresReverification:bool('documentRequiresReverification'),followUpKind:facts.followUpKind,followUpOn:facts.followUpOn||'',noFurtherFollowupConfirmed:bool('noFurtherFollowupConfirmed'),lateReason:facts.lateReason||''}
  const body={reviewId:preview.reviewId,previewSha256:preview.previewSha256,signature,attestation:preview.attestation,attestationRead:checks.attestationRead===true,signingAsExaminer:checks.signingAsExaminer===true,reviewedAllPages:checks.reviewedAllPages===true,representativeIdentityConfirmed:checks.representativeIdentityConfirmed===true,examination},json=JSON.stringify(body)
  if(retry.current?.json!==json)retry.current={json,key:crypto.randomUUID()}
  await workforceApi.signReceipt(employeeId,taskId,{...body,requestKey:retry.current.key});onUpdated()
 }catch(e){setError(e instanceof Error?e.message:'Unable to sign. Retry unchanged details to recover a saved result.')}finally{setBusy(false)}}
 return <section aria-label="Receipt replacement workspace" className="min-w-0 space-y-3">
 <button type="button" className="rounded border p-2" disabled={busy||loading} onClick={()=>{setOpen(v=>!v);setPreview(null);setSelected([]);setError('');clearConsent()}}>{open?'Hide receipt replacement':'Replace receipt with actual document'}</button>
 {open?<><p>Use the actual replacement for this receipt. If the employee presents different documentation, its separate correction process is required. Original signatures remain retained.</p>{error?<p role="alert" className="text-red-700">{error}</p>:null}{!context?<p>Loading current receipt record…</p>:<fieldset disabled={busy||loading} className="min-w-0 space-y-4">
 <div className="space-y-2"><button type="button" className="rounded border p-2" disabled={!draftState} onClick={()=>void save()}>Save unfinished receipt amendment</button> <button type="button" className="underline" onClick={()=>void load()}>Reload saved receipt amendment (replaces unsaved entries)</button>{notice?<p role="status">{notice}</p>:null}{savedShape&&savedShape!==JSON.stringify({form,facts})?<p>You have unsaved receipt entries or examination notes.</p>:null}{draftState?.savedAt?<p>Saved {draftState.savedAt} · revision {draftState.revision}</p>:null}</div>
 <p>Source: {context.sourceKind==='SECTION2'?'Section 2':'Supplement B'}, row {context.rowKey}. Receipt follow-up due {context.dueOn}.</p>
 {loading?<p role="status">Loading saved receipt entries…</p>:busy?<p role="status">Saving or preparing receipt evidence…</p>:null}
 <form className="space-y-3" onSubmit={e=>{e.preventDefault();void prepare()}}>
 <div className="grid gap-3 md:grid-cols-2">{field('title','Actual replacement document title','text',true)}{field('issuingAuthority','Replacement issuing authority','text',true)}{field('number','Replacement document number')}{field('expiresOn','Replacement expiration (if any)','date')}{field('examinerName','Receipt examiner full name','text',true)}{field('initials','Receipt examiner initials','text',true)}{field('amendedOn','Amendment date','date',true)}</div>
 <label className="block">Amendment explanation<textarea aria-label="Amendment explanation" className={inputClass} required maxLength={2000} value={form.explanation||''} onChange={e=>editForm('explanation',e.target.value)}/></label><button className="rounded border p-2" type="submit">Prepare receipt amendment</button></form>
 {preview?<div className="min-w-0 space-y-4"><I9ReceiptReviewPages {...{employeeId,taskId}} reviewId={preview.reviewId} previewSha256={preview.previewSha256} documentKey="source" pdfBase64={preview.source.pdfBase64} pageCount={preview.source.pageCount} title="Review source receipt form"/><I9ReceiptReviewPages {...{employeeId,taskId}} reviewId={preview.reviewId} previewSha256={preview.previewSha256} documentKey="amendment" pdfBase64={preview.pdfBase64} pageCount={preview.pageCount} title="Review receipt amendment"/>
 <I9ReceiptCopies key={preview.reviewId} {...{employeeId,taskId,selected}} reviewId={preview.reviewId} previewSha256={preview.previewSha256} onSelected={ids=>{setSelected(ids);clearConsent()}}/>
 <h4 className="font-bold">Receipt examiner findings</h4>{fact('examinedOn','Replacement examined on','date')}{fact('identityEvidence','Examiner identity and authority','textarea')}{fact('receiptMatchEvidence','How the actual document matches this receipt','textarea')}
 {choice('examinationMethod','Replacement examination method',[['','Choose'],['PHYSICAL','Physical examination'],['ALTERNATIVE','Authorized alternative procedure']])}{choice('physicalPresence','Original examined in employee’s physical presence',yesNo)}
 {facts.examinationMethod==='ALTERNATIVE'?<div className="space-y-2">{fact('liveVideoOn','Live-video examination date','date')}{fact('qualificationEvidence','Current employer qualification evidence','textarea')}{fact('videoEvidence','Live-video evidence','textarea')}{[['goodStanding','Employer is currently in E-Verify good standing'],['allSitesEnrolled','Every participating hiring site is enrolled'],['trainingComplete','Required examiner training is complete'],['consistentProcedure','Procedure is applied consistently without discrimination'],['copiesReceivedBeforeVideo','Copies were reviewed before the live video'],['sameOriginalsPresented','The same originals were presented during live video']].map(([key,label])=>confirm(key,label))}</div>:null}
 {choice('acceptance','Replacement document acceptance',[['','Choose'],['STANDARD','Standard unexpired document'],['EXTENSION','Applicable extension'],['OTHER_ACCEPTABLE','Other applicable acceptance rule']])}{fact('acceptanceSource','Official receipt acceptance rule URL','url')}{fact('acceptanceEvidence','Document acceptance and future-review evidence','textarea')}<p>For an exception, include its acceptance evidence in the amendment explanation before preparing the reviewed PDF.</p>{fact('validUntil','Verified document validity through (if any)','date')}
 {choice('authorizationIndefinite','Employment authorization has no expiration',yesNo)}{fact('authorizationThrough','Current authorization expiration (if any)','date')}{choice('documentRequiresReverification','This document requires reverification',yesNo)}{choice('followUpKind','Next receipt follow-up action',[['','Choose'],['NONE','No further follow-up'],['REVERIFICATION','Reverification'],['OTHER','Other required review']])}{fact('followUpOn','Next follow-up date (if required)','date')}{choice('noFurtherFollowupConfirmed','No further follow-up is required',yesNo)}{fact('lateReason','Late-completion explanation (if applicable)','textarea')}
 {confirm('actualReplacementConfirmed','This is the actual replacement for the identified receipt')}{confirm('documentsGenuineAndRelated','The originals reasonably appear genuine and relate to this employee')}{confirm('copiesComplete','The selected copies include every required side and page')}
 <blockquote className="rounded bg-slate-50 p-3">{preview.attestation}</blockquote>{confirm('attestationRead','I read and agree to the receipt certification')}{confirm('signingAsExaminer','I am the examiner who performed this review')}{confirm('reviewedAllPages','I reviewed every source, amendment and selected copy page')}{confirm('representativeIdentityConfirmed','My identity and authority as the named examiner are confirmed')}
 <label className="block">Receipt examiner electronic signature<input aria-label="Receipt examiner electronic signature" className={inputClass} value={signature} onChange={e=>{setSignature(e.target.value);retry.current=null}}/></label><button type="button" className="rounded border p-2" disabled={!signature.trim()} onClick={()=>void sign()}>Sign receipt amendment</button>
 </div>:null}</fieldset>}</>:null}
 </section>
}
