import {useEffect,useRef,useState} from 'react'
import {workforceApi,type I9SupplementPreview,type I9SupplementDraftState} from '../../utils/workforceApi'
import I9SupplementReviewPages from './I9SupplementReviewPages'
import I9SupplementCopies from './I9SupplementCopies'
const input='mt-1 block w-full min-w-0 rounded border border-slate-300 p-2'
const finalChecks=['attestationRead','signingAsExaminer','reviewedAllPages','representativeIdentityConfirmed']
function Field({label,value,onChange,type='text',required=false}:{label:string;value:string;onChange:(value:string)=>void;type?:string;required?:boolean}){return <label className="block">{label}{type==='textarea'?<textarea aria-label={label} className={input} value={value} required={required} onChange={e=>onChange(e.target.value)}/>:<input aria-label={label} className={input} type={type} value={value} required={required} onChange={e=>onChange(e.target.value)}/>}</label>}
export default function I9SupplementWorkspace({employeeId,taskId,signatureId,dueOn,onUpdated}:{employeeId:number;taskId:string|number;signatureId:string|number;dueOn:string;onUpdated:()=>void}){
 const [opened,setOpened]=useState(false),[form,setForm]=useState<Record<string,string>>({}),[facts,setFacts]=useState<Record<string,string>>({}),[checks,setChecks]=useState<Record<string,boolean>>({}),[signature,setSignature]=useState(''),[copyIds,setCopyIds]=useState<string[]>([]),[preview,setPreview]=useState<I9SupplementPreview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('')
 const [saved,setSaved]=useState<I9SupplementDraftState|null>(null),[draftReload,setDraftReload]=useState(0),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false)
 const savePending=useRef<{payload:string;key:string}|null>(null)
 useEffect(()=>{
  if(!opened)return
  let live=true;setBusy(true);setSaved(null);setError('');setNotice('')
  void workforceApi.supplementDraft(employeeId,taskId).then(value=>{if(!live)return;setSaved(value);setDirty(false);setForm(value.draft?.form||{});setFacts(value.draft?.facts||{});setPreview(null);setChecks({});setSignature('');setCopyIds([]);savePending.current=null}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setBusy(false)})
  return()=>{live=false}
 },[opened,employeeId,taskId,draftReload])
 const save=async()=>{
  if(!saved)return
  const body={draft:{form,facts},expectedRevision:saved.revision,basisHash:saved.basisHash},payload=JSON.stringify(body)
  if(savePending.current?.payload!==payload)savePending.current={payload,key:crypto.randomUUID()}
  setBusy(true);setError('');setNotice('')
  try{setSaved(await workforceApi.saveSupplementDraft(employeeId,taskId,{...body,requestKey:savePending.current.key}));savePending.current=null;setDirty(false);setNotice('Unfinished reverification saved securely for your admin account.')}catch(e){setError(e instanceof Error?e.message:'Unable to save. Retry unchanged or reload the latest draft.')}finally{setBusy(false)}
 }
 const pending=useRef<{payload:string;key:string}|null>(null)
 const invalidate=()=>{setChecks(old=>Object.fromEntries(Object.entries(old).filter(([key])=>!finalChecks.includes(key))));setSignature('')}
 const editForm=(key:string,value:string)=>{setDirty(true);setNotice('');setForm(old=>({...old,[key]:value}));setPreview(null);setChecks({});setSignature('');setCopyIds([])}
 const editFact=(key:string,value:string)=>{setDirty(true);setNotice('');setFacts(old=>({...old,[key]:value}));invalidate()}
 const check=(key:string,label:string)=><label key={key} className="flex items-start gap-2"><input className="mt-1" type="checkbox" checked={!!checks[key]} onChange={e=>{if(!finalChecks.includes(key))invalidate();setChecks(old=>({...old,[key]:e.target.checked}))}}/><span>{label}</span></label>
 const select=(label:string,key:string,options:Array<[string,string]>,values:Record<string,string>,change:(key:string,value:string)=>void)=><label className="block">{label}<select aria-label={label} className={input} required value={values[key]||''} onChange={e=>change(key,e.target.value)}><option value="">Choose…</option>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>
 const prepare=async()=>{setBusy(true);setError('');setPreview(null);setChecks({});setSignature('');setCopyIds([]);try{setPreview(await workforceApi.supplementPreview(employeeId,taskId,{signatureId,answers:{edition:'01/20/25',document:{list:form.list,title:form.title,number:form.number||'',expiresOn:form.expiresOn||''},representativeName:form.representativeName,newName:{firstName:form.firstName||'',lastName:form.lastName||'',middleInitial:form.middleInitial||''},additionalInformation:form.additionalInformation||'',examinationMethod:form.examinationMethod}}))}catch(e){setError(e instanceof Error?e.message:'Unable to prepare Supplement B.')}finally{setBusy(false)}}
 const sign=async()=>{
  if(!preview)return
  const examination={examinedOn:facts.examinedOn,examinerInitials:facts.examinerInitials,identityEvidence:facts.identityEvidence,reverificationRequired:!!checks.reverificationRequired,requirementSource:facts.requirementSource,requirementEvidence:facts.requirementEvidence,employeeChoseDocuments:!!checks.employeeChoseDocuments,currentAuthorizationReviewed:!!checks.currentAuthorizationReviewed,documentsGenuineAndRelated:!!checks.documentsGenuineAndRelated,copiesComplete:!!checks.copiesComplete,copyIds,physicalPresence:!!checks.physicalPresence,alternative:form.examinationMethod==='ALTERNATIVE'?{...Object.fromEntries(['goodStanding','allSitesEnrolled','trainingComplete','consistentProcedure','copiesReceivedBeforeVideo','sameOriginalsPresented'].map(key=>[key,!!checks[key]])),liveVideoOn:facts.examinedOn,qualificationEvidence:facts.qualificationEvidence,videoEvidence:facts.videoEvidence}:null,acceptance:facts.acceptance,acceptanceSource:facts.acceptanceSource,acceptanceEvidence:facts.acceptanceEvidence,validUntil:facts.validUntil||'',formNotation:facts.formNotation||'',authorizationIndefinite:facts.authorizationIndefinite==='yes',authorizationThrough:facts.authorizationThrough||'',followUpKind:facts.followUpKind,followUpOn:facts.followUpOn||'',noFurtherReverificationRequired:facts.noFurtherReverificationRequired==='yes',lateReason:facts.lateReason||'',nameChangeEvidence:facts.nameChangeEvidence||''}
  const body={reviewId:preview.reviewId,previewSha256:preview.previewSha256,signature,examination,attestation:preview.attestation,...Object.fromEntries(finalChecks.map(key=>[key,!!checks[key]]))},payload=JSON.stringify(body)
  if(pending.current?.payload!==payload)pending.current={payload,key:crypto.randomUUID()}
  setBusy(true);setError('');try{const result=await workforceApi.signSupplement(employeeId,taskId,{...body,requestKey:pending.current.key});setReceipt(`Supplement B signed and retained at ${result.signedAt}.${result.nextFollowup?` Next follow-up: ${result.nextFollowup.due_on}.`:' No further follow-up recorded.'}`);onUpdated()}catch(e){setError(e instanceof Error?e.message:'Unable to confirm signing. Retry unchanged to recover the receipt.')}finally{setBusy(false)}
 }
 if(!opened)return <button type="button" className="rounded border p-2 font-semibold" onClick={()=>setOpened(true)}>Complete reverification with Supplement B</button>
 if(receipt)return <p role="status">{receipt}</p>
 return <section aria-label="I-9 reverification workspace" className="min-w-0 space-y-4 rounded border p-4"><h4 className="font-bold">Complete reverification</h4><p>Follow-up due {dueOn}. Prepare the employee-chosen List A or C document, review the retained forms and copies, then sign as the examiner. A new preview requires a fresh page review.</p>{error?<p role="alert">{error}</p>:null}
 <p>Save unfinished entries before leaving. After resuming, prepare the form again, review its pages and copies, and enter new signing confirmations.</p>
 {dirty?<p role="status">You have unsaved form entries or examination notes.</p>:null}{notice?<p role="status">{notice}</p>:null}{saved?.savedAt?<p>Draft saved {saved.savedAt} · revision {saved.revision}</p>:null}{saved?.invalidated?<p role="status">The source I-9 changed. Previous draft entries are no longer current; prepare this follow-up from its current evidence.</p>:null}
 <div className="flex flex-wrap gap-3"><button type="button" disabled={busy||!saved} className="rounded border p-2 font-semibold disabled:opacity-40" onClick={()=>void save()}>Save unfinished reverification</button><button type="button" disabled={busy} className="underline" onClick={()=>setDraftReload(n=>n+1)}>Reload my saved reverification (replaces unsaved entries)</button></div>
 <form onSubmit={e=>{e.preventDefault();void prepare()}}><fieldset disabled={busy||!saved} className="min-w-0 space-y-3">
 {select('Document list','list',[['A','List A'],['C','List C']],form,editForm)}
 {([['title','Document title'],['number','Document number (if any)'],['expiresOn','Document expiration (if any)'],['representativeName','Examiner name on Supplement B'],['firstName','New first name (if changed)'],['lastName','New last name (if changed)'],['middleInitial','New middle initial (if changed)'],['additionalInformation','Initialed and dated form notation (if needed)']] as const).map(([key,label])=><Field key={key} label={label} value={form[key]||''} onChange={value=>editForm(key,value)} type={key==='expiresOn'?'date':key==='additionalInformation'?'textarea':'text'} required={['title','representativeName'].includes(key)}/>)}
 {select('Examination method','examinationMethod',[['PHYSICAL','Physical examination'],['ALTERNATIVE','DHS-authorized alternative procedure']],form,editForm)}
 <button type="submit" className="rounded bg-slate-900 px-3 py-2 font-semibold text-white">Prepare Supplement B for review</button></fieldset></form>
 {preview?<div key={preview.reviewId} className="min-w-0 space-y-4"><I9SupplementReviewPages employeeId={employeeId} taskId={taskId} reviewId={preview.reviewId} previewSha256={preview.previewSha256} documentKey="source" pdfBase64={preview.source.pdfBase64} pageCount={4} title="Original signed I-9"/>
 {preview.previousSupplements.map((prior,index)=><I9SupplementReviewPages key={prior.documentKey} employeeId={employeeId} taskId={taskId} reviewId={preview.reviewId} previewSha256={preview.previewSha256} documentKey={prior.documentKey} pdfBase64={prior.pdfBase64} pageCount={1} title={`Prior signed Supplement B ${index+1}`}/>)}
 {(preview.previousReceiptAmendments||[]).map((prior,index)=><I9SupplementReviewPages key={prior.documentKey} employeeId={employeeId} taskId={taskId} reviewId={preview.reviewId} previewSha256={preview.previewSha256} documentKey={prior.documentKey} pdfBase64={prior.pdfBase64} pageCount={prior.pageCount} title={`Prior signed receipt amendment ${index+1}`}/>)}
 <I9SupplementReviewPages employeeId={employeeId} taskId={taskId} reviewId={preview.reviewId} previewSha256={preview.previewSha256} documentKey="supplement" pdfBase64={preview.pdfBase64} pageCount={1} title="Supplement B to sign"/>
 <I9SupplementCopies employeeId={employeeId} taskId={taskId} reviewId={preview.reviewId} previewSha256={preview.previewSha256} selected={copyIds} onSelected={ids=>{setCopyIds(ids);invalidate();setChecks(old=>({...old,copiesComplete:false}))}}/>
 <form onSubmit={e=>{e.preventDefault();void sign()}}><fieldset disabled={busy} className="min-w-0 space-y-3"><h4 className="font-bold">Examination findings</h4>
 {([['examinedOn','Actual examination date','date'],['examinerInitials','Examiner initials','text'],['identityEvidence','Examiner identity and authority evidence','textarea'],['requirementSource','Official reverification rule URL','url'],['requirementEvidence','Employee-specific reason reverification is required','textarea']] as const).map(([key,label,type])=><Field key={key} label={label} type={type} required value={facts[key]||''} onChange={value=>editFact(key,value)}/>)}
 {check('reverificationRequired','This employee currently requires reverification and is not exempt.')}{check('employeeChoseDocuments','The employee chose their acceptable List A or C documentation.')}{check('currentAuthorizationReviewed','I reviewed current authorization and applicable automatic extensions.')}{check('documentsGenuineAndRelated','The original documents reasonably appear genuine and relate to this employee.')}{check('copiesComplete','The selected copies include every required side and page.')}
 {form.examinationMethod==='PHYSICAL'?check('physicalPresence','I examined the originals in the employee’s physical presence.'):<div className="space-y-3 rounded border p-3">{([['goodStanding','Current E-Verify good standing is verified.'],['allSitesEnrolled','Every hiring site using this procedure is enrolled.'],['trainingComplete','Required examiner training is complete.'],['consistentProcedure','The procedure is applied consistently and without discrimination.'],['copiesReceivedBeforeVideo','I reviewed copies before the live video examination.'],['sameOriginalsPresented','The same original documents were presented during live video.']] as const).map(([key,label])=>check(key,label))}<Field label="Current employer and site qualification evidence" type="textarea" required value={facts.qualificationEvidence||''} onChange={value=>editFact('qualificationEvidence',value)}/><Field label="Live-video examination evidence" type="textarea" required value={facts.videoEvidence||''} onChange={value=>editFact('videoEvidence',value)}/></div>}
 {select('Document acceptance','acceptance',[['STANDARD','Standard document'],['RECEIPT','Acceptable receipt'],['EXTENSION','Applicable extension'],['OTHER_ACCEPTABLE','Other acceptable exception']],facts,editFact)}
 {([['acceptanceSource','Official document-acceptance rule URL','url',true],['acceptanceEvidence','Document acceptance and future-review evidence','textarea',true],['validUntil','Document validity through (if applicable)','date',false],['formNotation','Exact exception notation on the reviewed form','textarea',false],['authorizationThrough','Current authorization expiration (unless indefinite)','date',false],['followUpOn','Next follow-up date (if required)','date',false],['lateReason','Late-completion explanation (if applicable)','textarea',false],['nameChangeEvidence','Name-change evidence (if applicable)','textarea',false]] as const).map(([key,label,type,required])=><Field key={key} label={label} type={type} required={required} value={facts[key]||''} onChange={value=>editFact(key,value)}/>)}
 {select('Is current authorization indefinite?','authorizationIndefinite',[['yes','Yes'],['no','No']],facts,editFact)}
 {select('Required next follow-up','followUpKind',[['REVERIFICATION','Reverification'],['RECEIPT_REPLACEMENT','Receipt replacement'],['OTHER','Other document follow-up'],['NONE','No further follow-up']],facts,editFact)}
 {select('Is no further reverification or document follow-up required?','noFurtherReverificationRequired',[['yes','Yes'],['no','No']],facts,editFact)}
 <blockquote className="rounded bg-slate-50 p-3">{preview.attestation}</blockquote>
 {check('attestationRead','I read and affirm the Supplement B certification.')}{check('signingAsExaminer','I am the representative who performed this examination.')}{check('reviewedAllPages','I reviewed every source, prior supplement, new supplement and selected copy page.')}{check('representativeIdentityConfirmed','My identity and authority as the named representative are confirmed.')}
 <Field label="Your examiner signature" required value={signature} onChange={setSignature}/><p>The signature records today’s actual date. It cannot be backdated.</p><button type="submit" disabled={!copyIds.length||finalChecks.some(key=>!checks[key])} className="rounded bg-slate-900 px-3 py-2 font-semibold text-white disabled:opacity-40">Sign and retain Supplement B</button>
 </fieldset></form></div>:null}
 </section>
}
