import OffCyclePtoPayment from './OffCyclePtoPayment'
import {useEffect,useState} from 'react'
import {payrollApi,type LeavePayoutPreview as Calculation,type LeavePayoutReservation} from '../../utils/payrollApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
export default function LeavePayoutPreview({employeeId,periods,onChanged,rehireOnboarding=false}:{rehireOnboarding?:boolean;employeeId:number;periods:Record<string,unknown>[];onChanged:()=>Promise<void>}){
 const [form,setForm]=useState({minutes:'',rate:'',policyReference:'',policyVerified:false,unusedVacationVerified:false}),[result,setResult]=useState<Calculation|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [paymentMode,setPaymentMode]=useState<'REGULAR'|'STANDALONE'>('REGULAR')
 const [requestKey,setRequestKey]=useState(()=>crypto.randomUUID()),[periodId,setPeriodId]=useState(''),[payouts,setPayouts]=useState<LeavePayoutReservation[]>([]),[reasons,setReasons]=useState<Record<string,string>>({}),[message,setMessage]=useState('')
 useEffect(()=>{let active=true;payrollApi.leavePayouts(employeeId).then(rows=>{if(active)setPayouts(rows)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[employeeId])
 const change=(key:keyof typeof form,value:string|boolean)=>{setForm(current=>({...current,[key]:value}));setResult(null);setError('');setMessage('')}
 return <section aria-label="Unused PTO payout" className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">Unused PTO payout</h2>{rehireOnboarding?<p className="mt-2 text-sm text-slate-600">During rehire onboarding, payouts may be reserved only against eligible earlier regular payroll periods. New-period and standalone payouts require activation.</p>:null}<p className="mt-2 text-sm text-slate-600">Review the vacation payout policy communicated at hiring and its applicable hourly payout rate. Salary alone does not establish that rate.</p><form className="mt-3 space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setResult(null);try{setResult(await payrollApi.previewLeavePayout(employeeId,{...form,leaveType:'PTO',minutes:Number(form.minutes),hourlyRateCents:Math.round(Number(form.rate)*100)}))}catch(e){setError(e instanceof Error?e.message:'Unable to calculate payout')}finally{setBusy(false)}}}><fieldset disabled={busy} className="space-y-3">
 <label className="block text-sm font-bold">PTO minutes to pay out<input required type="number" min="1" step="1" className={workforceInput} value={form.minutes} onChange={e=>change('minutes',e.target.value)}/></label>
 <p className="text-xs text-slate-600">60 minutes equals one hour. Enter exact minutes to include partial-hour balances.</p>
 <label className="block text-sm font-bold">Reviewed PTO payout rate ($/hour)<input required type="number" min="0.01" step="0.01" className={workforceInput} value={form.rate} onChange={e=>change('rate',e.target.value)}/></label>
 <label className="block text-sm font-bold">PTO payout policy evidence<textarea required minLength={20} className={workforceInput} value={form.policyReference} onChange={e=>change('policyReference',e.target.value)}/></label>
 <label className="flex gap-2 text-sm"><input required type="checkbox" checked={form.policyVerified} onChange={e=>change('policyVerified',e.target.checked)}/>I verified the communicated payout policy and applicable rate.</label>
 <label className="flex gap-2 text-sm"><input required type="checkbox" checked={form.unusedVacationVerified} onChange={e=>change('unusedVacationVerified',e.target.checked)}/>This pays unused vacation/PTO and is not an attendance bonus.</label>
 <button className={workforceButton}>Calculate PTO payout</button></fieldset></form>
 {error?<p role="alert" className="mt-3 text-red-700">{error}</p>:null}{result?<div role="status" className="mt-3 space-y-2 rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold">PTO payout: {(result.amountCents/100).toLocaleString('en-US',{style:'currency',currency:'USD'})}</p><p>Balance reviewed as of {result.asOfDate}, including future leave deductions.</p><p>{result.minutes/60} hours from {result.availableMinutes/60} available hours. Remaining after payout: {result.remainingMinutes/60} hours.</p><label className="block font-bold">PTO payment method<select disabled={busy} className={workforceInput} value={paymentMode} onChange={e=>{setPaymentMode(e.target.value as 'REGULAR'|'STANDALONE');setPeriodId('')}}><option value="REGULAR">Include in regular payroll</option><option value="STANDALONE" disabled={rehireOnboarding}>Separate payment, including after payroll closes</option></select></label><label className="block font-bold">PTO payout payroll period<select disabled={busy} className={workforceInput} value={periodId} onChange={e=>setPeriodId(e.target.value)}><option value="">Choose a processing period</option>{periods.filter(p=>paymentMode==='STANDALONE'?p.status!=='VOID':p.status==='OPEN').map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.period_start).slice(0,10)} through {String(p.period_end).slice(0,10)}</option>)}</select></label><button type="button" disabled={busy||!periodId} className={workforceButton} onClick={async()=>{setBusy(true);setError('');try{await payrollApi.reserveLeavePayout(employeeId,{...form,leaveType:'PTO',minutes:Number(form.minutes),hourlyRateCents:Math.round(Number(form.rate)*100),requestKey,paymentMode,payPeriodId:Number(periodId),fingerprint:result.fingerprint});setPayouts(await payrollApi.leavePayouts(employeeId));await onChanged();setRequestKey(crypto.randomUUID());setResult(null);setMessage('PTO reserved for payout. It is unavailable for other leave until paid or cancelled.')}catch(e){setError(e instanceof Error?e.message:'Unable to reserve payout')}finally{setBusy(false)}}}>Reserve PTO payout</button><p>{paymentMode==='STANDALONE'?'After reservation, create its standalone payroll below.':'The payout appears on the selected regular payroll.'} Finalizing payment deducts the reserved hours from the leave balance.</p></div>:null}
 {message?<p role="status" className="mt-3 text-sm text-emerald-700">{message}</p>:null}
 <div className="mt-4 space-y-3">{payouts.map(p=><article key={p.id} className="rounded-xl border border-slate-200 p-3 text-sm"><h3 className="font-bold">PTO payout #{p.id} · {(Number(p.amount_cents)/100).toLocaleString('en-US',{style:'currency',currency:'USD'})}</h3><p>{Number(p.minutes)/60} hours · {p.status}</p>{p.status==='RESERVED'&&p.payment_mode==='STANDALONE'&&!rehireOnboarding?<OffCyclePtoPayment employeeId={employeeId} payout={p} onChanged={onChanged}/>:null}{p.cancellation_reason?<p>{p.cancellation_reason}</p>:null}{p.status==='RESERVED'?<><label className="mt-2 block font-bold">Cancellation reason for payout {p.id}<input disabled={busy} className={workforceInput} value={reasons[p.id]||''} onChange={e=>setReasons(current=>({...current,[p.id]:e.target.value}))}/></label><button type="button" disabled={busy||(reasons[p.id]||'').trim().length<12} className={`${workforceButton} mt-2`} onClick={async()=>{setBusy(true);setError('');try{await payrollApi.cancelLeavePayout(employeeId,p.id,reasons[p.id]);setPayouts(await payrollApi.leavePayouts(employeeId));setResult(null);await onChanged();setMessage('PTO payout cancelled. Reserved hours are available again.')}catch(e){setError(e instanceof Error?e.message:'Unable to cancel payout')}finally{setBusy(false)}}}>Cancel PTO payout {p.id}</button></>:null}</article>)}</div>
 </section>
}
