import {useState} from 'react'
import {workforceApi,type FractionRecoveryPlan} from '../../utils/workforceApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
export default function LeaveFractionRecovery({employeeId,onChanged}:{employeeId:number;onChanged:()=>Promise<void>}){
 const [plan,setPlan]=useState<FractionRecoveryPlan|null>(null),[source,setSource]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">Recover historical leave fractions</h2><p className="mt-2 text-sm text-slate-600">Selected employee #{employeeId}. Review fractions discarded by older payroll calculations. Recovery credits whole minutes as a current-date restoration and carries the remaining fraction into future payroll. Finalized pay statements remain unchanged. Review the original policy and prior corrections before applying this additional leave adjustment.</p><button type="button" disabled={busy} className={`${workforceButton} mt-3`} onClick={async()=>{setBusy(true);setError('');setMessage('');setConfirmed(false);try{setPlan(await workforceApi.previewLeaveFractions(employeeId))}catch(e){setPlan(null);setError(e instanceof Error?e.message:'Unable to review fractions')}finally{setBusy(false)}}}>Preview historical leave fractions</button>
 {plan?<div className="mt-4 space-y-3"><p className="font-bold">Restore {plan.creditMinutes} whole minute{plan.creditMinutes===1?'':'s'} on {plan.effectiveOn}; carry forward {plan.remainder}/30 minute.</p><ul className="space-y-2 text-sm">{plan.items.map(i=><li key={i.runId}>Run #{i.runId} · {i.workedMinutes} worked minutes · {i.accruedMinutes} accrued minutes · recover {i.recoveredThirtieths}/30 minute</li>)}</ul><label className="block text-sm font-bold">Historical leave review reference<input className={workforceInput} value={source} onChange={e=>{setSource(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified these fractions were not previously restored and approve the recovery shown above.</label><button type="button" disabled={busy||!confirmed||source.trim().length<12} className={workforceButton} onClick={async()=>{setBusy(true);setError('');try{await workforceApi.applyLeaveFractions(employeeId,{source,confirmed,previewToken:plan.previewToken});setPlan(null);setConfirmed(false);await onChanged();setMessage('Historical leave fractions reconciled and audited.')}catch(e){setError(e instanceof Error?e.message:'Unable to apply recovery')}finally{setBusy(false)}}}>Apply leave fraction recovery</button></div>:null}
 {error?<p role="alert" className="mt-3 text-red-700">{error}</p>:null}{message?<p role="status" className="mt-3 text-emerald-700">{message}</p>:null}</section>
}
