import LeaveYearPolicy from './LeaveYearPolicy'
import {useState} from 'react'
import {workforceApi,type LeaveYearPlan} from '../../utils/workforceApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
const hours=(minutes:number)=>(minutes/60).toFixed(2)
export default function LeaveYearOpening({onChanged}:{onChanged:()=>Promise<void>}){
 const [form,setForm]=useState({year:new Date().getFullYear(),carryCapMinutes:2400,frontloadMinutes:2400,source:'',confirmed:false}),[plan,setPlan]=useState<LeaveYearPlan|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const change=(patch:Partial<typeof form>)=>{setForm(f=>({...f,...patch,confirmed:false}));setPlan(null);setMessage('')}
 return <><LeaveYearPolicy key={message}/><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">Open annual sick-leave year</h2><p className="mt-2 text-sm text-slate-600">Apply the published calendar-year policy before approving payroll in the new year. Accrual employees keep leave up to the carryover limit. Frontloaded employees’ unused balance is replaced by the new annual grant. Employees separated on January 1 retain their balance. Recorded employment periods determine eligibility for that opening year. Closed-year corrections must be recorded in the current year.</p>
 <div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-sm font-bold">Opening year<input type="number" min="2001" max={new Date().getFullYear()} className={workforceInput} value={form.year} onChange={e=>change({year:Number(e.target.value)})}/></label><label className="text-sm font-bold">Carryover limit in hours<input type="number" min="40" max="64" step="1" className={workforceInput} value={form.carryCapMinutes/60} onChange={e=>change({carryCapMinutes:Number(e.target.value)*60})}/></label><label className="text-sm font-bold">Annual frontload in hours<input type="number" min="40" max="64" step="1" className={workforceInput} value={form.frontloadMinutes/60} onChange={e=>change({frontloadMinutes:Number(e.target.value)*60})}/></label></div>
 <button type="button" disabled={busy} className={`${workforceButton} mt-3`} onClick={async()=>{setBusy(true);setError('');try{setPlan(await workforceApi.previewLeaveYear(form))}catch(e){setError(e instanceof Error?e.message:'Unable to preview annual leave')}finally{setBusy(false)}}}>Preview annual leave opening</button>
 {plan?<div className="mt-4 space-y-3">{plan.employees.map(e=><article key={e.id} className="rounded-xl border border-slate-200 p-3 text-sm"><p className="font-bold">{e.legal_first_name} {e.legal_last_name} · {e.sick_leave_policy.toLowerCase()}</p>{e.employed_at_opening===false?<p className="mt-1 text-slate-600">Separated on January 1: balance retained without a new grant.</p>:null}<p className="mt-1">Prior balance: {hours(e.balance)} hours · carryover adjustment: {hours(e.rolloverDelta)} hours · new grant: {hours(e.grantMinutes)} hours.</p><p className="mt-1 font-bold">January 1 opening balance: {hours(e.openingBalance)} hours</p></article>)}<label className="block text-sm font-bold">Published annual leave policy reference<input className={workforceInput} value={form.source} onChange={e=>setForm(f=>({...f,source:e.target.value}))}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.confirmed} onChange={e=>setForm(f=>({...f,confirmed:e.target.checked}))}/>I verified the published policy and each carryover reduction or replacement grant shown above.</label><button type="button" className={workforceButton} disabled={busy||!form.confirmed||form.source.trim().length<12} onClick={async()=>{setBusy(true);setError('');try{await workforceApi.applyLeaveYear({...form,previewToken:plan.previewToken});setPlan(null);setForm(f=>({...f,confirmed:false}));await onChanged();setMessage(`Leave year ${plan.year} opened and audited.`)}catch(e){setError(e instanceof Error?e.message:'Unable to open leave year')}finally{setBusy(false)}}}>Apply annual leave opening</button></div>:null}
 {error?<p role="alert" className="mt-3 text-red-700">{error}</p>:null}{message?<p role="status" className="mt-3 text-emerald-700">{message}</p>:null}</section></>
}
