import {useEffect,useState} from 'react'
import {workforceApi,type LeaveYearHistory} from '../../utils/workforceApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
export default function LeaveYearPolicy(){
 const nextYear=new Date().getFullYear()+1
 const [data,setData]=useState<LeaveYearHistory|null>(null),[form,setForm]=useState({enabled:false,firstYear:nextYear,carryCapMinutes:2400,frontloadMinutes:2400,source:'',confirmed:false}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{let active=true;workforceApi.leaveYearHistory().then(d=>{if(!active)return;setData(d);if(d.policy)setForm({enabled:d.policy.enabled,firstYear:Math.max(nextYear,d.policy.first_year),carryCapMinutes:d.policy.carry_cap_minutes,frontloadMinutes:d.policy.frontload_minutes,source:d.policy.source,confirmed:false})}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to load annual leave history')});return()=>{active=false}},[nextYear])
 return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">Recurring annual leave policy</h2><p className="mt-2 text-sm text-slate-600">When enabled, workforce automation opens each future calendar year using this policy. It applies the same carryover reductions and replacement frontload grants as manual opening, records the result below, and raises an alert if payroll or leave records need review.</p><p className="mt-2 text-sm font-bold">Saved automation: {data?.policy?.enabled?`enabled from ${data.policy.first_year}`:'disabled'}</p>
 <div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-sm font-bold">First automatic opening year<input type="number" min={nextYear} max="2200" className={workforceInput} value={form.firstYear} onChange={e=>setForm(f=>({...f,firstYear:Number(e.target.value),confirmed:false}))}/></label><label className="text-sm font-bold">Automatic carryover hours<input type="number" min="40" max="64" className={workforceInput} value={form.carryCapMinutes/60} onChange={e=>setForm(f=>({...f,carryCapMinutes:Number(e.target.value)*60,confirmed:false}))}/></label><label className="text-sm font-bold">Automatic frontload hours<input type="number" min="40" max="64" className={workforceInput} value={form.frontloadMinutes/60} onChange={e=>setForm(f=>({...f,frontloadMinutes:Number(e.target.value)*60,confirmed:false}))}/></label></div>
 <label className="mt-3 block text-sm font-bold">Recurring leave policy reference<input className={workforceInput} value={form.source} onChange={e=>setForm(f=>({...f,source:e.target.value,confirmed:false}))}/></label><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={e=>setForm(f=>({...f,enabled:e.target.checked,confirmed:false}))}/>Enable automatic annual leave opening</label><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={form.confirmed} onChange={e=>setForm(f=>({...f,confirmed:e.target.checked}))}/>I verified the published policy and authorize these settings for future annual openings.</label><button type="button" className={`${workforceButton} mt-3`} disabled={busy||!data||!form.confirmed||form.source.trim().length<12} onClick={async()=>{setBusy(true);setError('');try{await workforceApi.saveLeaveYearPolicy(form);setData(await workforceApi.leaveYearHistory());setForm(f=>({...f,confirmed:false}));setMessage('Recurring annual leave policy saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save annual leave policy')}finally{setBusy(false)}}}>Save recurring leave policy</button>
 <h3 className="mt-5 font-black">Annual opening history</h3>{data?.history.length?data.history.map(year=><details key={year.id} className="mt-2 rounded-xl border border-slate-200 p-3 text-sm"><summary className="cursor-pointer font-bold">Leave year {year.opening_year} · opened {year.created_at.slice(0,10)}</summary><p className="mt-2 break-words">Policy: {year.source}</p><ul className="mt-2 space-y-2">{year.employee_snapshot.map(e=><li key={e.id}>{e.legal_first_name} {e.legal_last_name} · prior {(e.balance/60).toFixed(2)} hours · adjustment {(e.rolloverDelta/60).toFixed(2)} hours · grant {(e.grantMinutes/60).toFixed(2)} hours · opening {(e.openingBalance/60).toFixed(2)} hours</li>)}</ul></details>):<p className="mt-2 text-sm text-slate-600">No recorded annual openings.</p>}
 {error?<p role="alert" className="mt-3 text-red-700">{error}</p>:null}{message?<p role="status" className="mt-3 text-emerald-700">{message}</p>:null}</section>
}
