import {useEffect,useState} from 'react'
import {workforceApi,type MarylandUiCalendarData,type TaxReconciliationData} from '../../utils/workforceApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value/100)
export default function MarylandUiCalendar({year,records}:{year:number;records:TaxReconciliationData|null}) {
 const [data,setData]=useState<MarylandUiCalendarData|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const [form,setForm]=useState({firstQuarter:1,lastQuarter:4,source:'',confirmed:false,standardScheduleConfirmed:false})
 useEffect(()=>{let live=true;workforceApi.marylandUiCalendar(year).then(next=>{if(live){setData(next);if(next.config)setForm(f=>({...f,firstQuarter:next.config!.first_quarter,lastQuarter:next.config!.last_quarter,source:next.config!.source}))}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[year,records])
 return <section className="mt-6 rounded-xl border border-slate-200 p-4"><h3 className="text-lg font-black">Maryland unemployment calendar</h3><p className="mt-2 text-sm text-slate-600">Track both the quarterly contribution payment and accepted wage report. Verify the account’s reporting quarters, including zero-wage quarters when a report is required.</p>
 {error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}{notice?<p role="status" className="mt-3 text-sm text-emerald-700">{notice}</p>:null}{data?.issues.map(issue=><p key={issue} className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{issue}</p>)}
 {year===2026?<form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{await workforceApi.saveMarylandUiReporting({year,...form});setData(await workforceApi.marylandUiCalendar(year));setForm(f=>({...f,confirmed:false,standardScheduleConfirmed:false}));setNotice('Maryland unemployment reporting verified. Deadlines recalculated.')}catch(e){setError(e instanceof Error?e.message:'Unable to save reporting setup')}finally{setBusy(false)}}}>
 <label className="text-sm font-bold">First required Maryland UI quarter<select className={workforceInput} value={form.firstQuarter} onChange={e=>setForm(f=>({...f,firstQuarter:Number(e.target.value)}))}>{[1,2,3,4].map(q=><option key={q} value={q}>Q{q}</option>)}</select></label>
 <label className="text-sm font-bold">Last required Maryland UI quarter<select className={workforceInput} value={form.lastQuarter} onChange={e=>setForm(f=>({...f,lastQuarter:Number(e.target.value)}))}>{[1,2,3,4].map(q=><option key={q} value={q}>Q{q}</option>)}</select></label>
 <label className="text-sm font-bold sm:col-span-2">Maryland UI account verification source<input className={workforceInput} required minLength={12} value={form.source} onChange={e=>setForm(f=>({...f,source:e.target.value}))} placeholder="BEACON registration or account reporting notice"/></label>
 <label className="flex items-start gap-2 text-sm sm:col-span-2"><input type="checkbox" required checked={form.confirmed} onChange={e=>setForm(f=>({...f,confirmed:e.target.checked}))}/>I verified these reporting quarters and complete wage and unemployment tax history.</label>
 <label className="flex items-start gap-2 text-sm sm:col-span-2"><input type="checkbox" required checked={form.standardScheduleConfirmed} onChange={e=>setForm(f=>({...f,standardScheduleConfirmed:e.target.checked}))}/>The standard contributory-employer schedule applies; no payment plan, agency extension or reimbursable-employer arrangement applies.</label><button disabled={busy} className={workforceButton}>Verify Maryland UI reporting</button>
 </form>:null}
 <p className="mt-3 text-xs text-slate-500">Use the deposit receipt and accepted filing forms above with Maryland unemployment / MD UI. Matching filing totals does not check every employee-level field or transmit a report to BEACON.</p>
 <div className="mt-3 grid gap-3 lg:grid-cols-2">{data?.quarters.map(q=><article key={q.quarter} className="rounded-xl border border-slate-200 p-3 text-sm"><p className="font-bold">Maryland UI Q{q.quarter} due {q.dueOn}</p><p>{q.start} through {q.end}{q.projected?' · Projection':''}</p><p className="mt-2">Payment: <strong>{data.reliable?q.paymentStatus.replaceAll('_',' '):'REVIEW REQUIRED'}</strong></p><p>Wage report: <strong>{data.reliable?q.filingStatus.replaceAll('_',' '):'REVIEW REQUIRED'}</strong></p><p className="mt-2">Gross wages {money(q.grossCents)} · Tax {money(q.liabilityCents)}</p><p>Receipts {money(q.coveredCents)} · Remaining {money(q.balanceCents)}</p>{q.filingReference?<p>Filing receipt: {q.filingReference}</p>:null}{q.lateCoveredCents>0?<p className="text-amber-800">{money(q.lateCoveredCents)} matched to payments after the deadline.</p>:null}</article>)}</div>
 </section>
}
