import {useEffect,useState} from 'react'
import {workforceApi,type MarylandWithholdingCalendarData,type TaxReconciliationData} from '../../utils/workforceApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value/100)
const months=Array.from({length:12},(_,i)=>i+1)
export default function MarylandWithholdingCalendar({year,records,onPrepare}:{year:number;records:TaxReconciliationData|null;onPrepare?:(period:MarylandWithholdingCalendarData['periods'][number])=>void}) {
 const [data,setData]=useState<MarylandWithholdingCalendarData|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const [form,setForm]=useState({schedule:'QUARTERLY',months:[1,4,7,10],source:'',confirmed:false,standardScheduleConfirmed:false})
 useEffect(()=>{let live=true;workforceApi.marylandWithholdingCalendar(year).then(next=>{if(live){setData(next);setError('');if(next.config)setForm(f=>({...f,...next.config!}))}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[year,records])
 return <section className="mt-6 rounded-xl border border-slate-200 p-4"><h3 className="text-lg font-black">Maryland withholding calendar</h3><p className="mt-2 text-sm text-slate-600">Verify the filing category assigned to this employer. Each MW506 or MW506M return and payment has its own status; the annual MW508 reconciliation is tracked separately.</p>
 {error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}{notice?<p role="status" className="mt-3 text-sm text-emerald-700">{notice}</p>:null}{data?.issues.map(issue=><p key={issue} className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{issue}</p>)}
 {year===2026?<form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{await workforceApi.saveMarylandWithholdingSchedule({year,...form});setData(await workforceApi.marylandWithholdingCalendar(year));setForm(f=>({...f,confirmed:false,standardScheduleConfirmed:false}));setNotice('Maryland withholding schedule verified.')}catch(e){setError(e instanceof Error?e.message:'Unable to save schedule')}finally{setBusy(false)}}}>
 <label className="text-sm font-bold">Maryland withholding filing category<select className={workforceInput} value={form.schedule} onChange={e=>{const schedule=e.target.value;setForm(f=>({...f,schedule,months:schedule==='ANNUAL'?[1]:schedule==='QUARTERLY'?[1,4,7,10]:months,confirmed:false,standardScheduleConfirmed:false}))}}>{['QUARTERLY','MONTHLY','ANNUAL','SEASONAL','ACCELERATED'].map(s=><option key={s} value={s}>{s}</option>)}</select></label>
 {form.schedule!=='ANNUAL'?<fieldset className="sm:col-span-2"><legend className="text-sm font-bold">Required Maryland withholding {form.schedule==='QUARTERLY'?'quarters':'months'}</legend><div className="mt-2 flex flex-wrap gap-3">{(form.schedule==='QUARTERLY'?[1,4,7,10]:months).map(m=><label key={m} className="flex gap-1 text-sm"><input type="checkbox" checked={form.months.includes(m)} onChange={e=>setForm(f=>({...f,months:e.target.checked?[...f.months,m].sort((a,b)=>a-b):f.months.filter(n=>n!==m),confirmed:false}))}/>{form.schedule==='QUARTERLY'?`Q${Math.ceil(m/3)}`:new Date(2026,m-1,1).toLocaleString('en-US',{month:'short'})}</label>)}</div></fieldset>:null}
 <label className="text-sm font-bold sm:col-span-2">Maryland withholding verification source<input className={workforceInput} required minLength={12} value={form.source} onChange={e=>setForm(f=>({...f,source:e.target.value}))} placeholder="Maryland Tax Connect account notice or approved seasonal schedule"/></label>
 <label className="flex items-start gap-2 text-sm sm:col-span-2"><input type="checkbox" required checked={form.confirmed} onChange={e=>setForm(f=>({...f,confirmed:e.target.checked}))}/>I verified the assigned category, required periods and complete payroll withholding history.</label>
 <label className="flex items-start gap-2 text-sm sm:col-span-2"><input type="checkbox" required checked={form.standardScheduleConfirmed} onChange={e=>setForm(f=>({...f,standardScheduleConfirmed:e.target.checked}))}/>These are the agency-approved reporting periods; standard deadlines apply without an extension or special arrangement.</label><button disabled={busy||!form.months.length} className={workforceButton}>Verify Maryland withholding schedule</button>
 </form>:null}
 <p className="mt-3 text-xs text-slate-500">Record Maryland withholding deposits and accepted MD MW506 / MD MW506M / MD MW508 filings above. Payment receipts match oldest liabilities within their recorded quarter; annual filers match across the year. Confirm allocation against the agency account. No funds or returns are transmitted here.</p>
 <div className="mt-3 grid gap-3 lg:grid-cols-2">{data?.periods.map(p=><article key={p.start} className="rounded-xl border border-slate-200 p-3 text-sm"><p className="font-bold">{p.formType==='MD_MW506M'?'MW506M':'MW506'} due {p.dueOn}</p>{p.reason?<p className="mt-1 text-xs text-slate-600">{p.reason==='THRESHOLD'?'$700 accumulation reached · three business days':p.reason==='MONTH_END'?'Remaining monthly withholding':'Monthly zero return'}</p>:null}<p>{p.start} through {p.end}{p.projected?' · Projection':''}</p><p className="mt-2">Payment: <strong>{data.reliable?p.paymentStatus.replaceAll('_',' '):'REVIEW REQUIRED'}</strong></p><p>Return: <strong>{data.reliable?p.filingStatus.replaceAll('_',' '):'REVIEW REQUIRED'}</strong></p><p className="mt-2">Gross wages {money(p.grossCents)} · Withholding {money(p.liabilityCents)}</p><p>Receipts {money(p.coveredCents)} · Remaining {money(p.balanceCents)}</p>{onPrepare?<button type="button" disabled={!data.reliable} className="mt-3 font-bold text-blue-700" onClick={()=>onPrepare(p)}>Prepare return comparison</button>:null}{p.filingReference?<p>Filing receipt: {p.filingReference}</p>:null}{p.lateCoveredCents>0?<p className="text-amber-800">{money(p.lateCoveredCents)} paid after the deadline.</p>:null}</article>)}</div>
 {data?.annual?<article className="mt-3 rounded-xl border border-slate-200 p-3 text-sm"><p className="font-bold">MW508 annual reconciliation due {data.annual.dueOn}</p><p>Return: <strong>{data.reliable?data.annual.filingStatus.replaceAll('_',' '):'REVIEW REQUIRED'}</strong></p>{data.annual.filingReference?<p>Filing receipt: {data.annual.filingReference}</p>:null}</article>:null}
 {data?.unappliedCents?<p className="mt-2 text-sm">Unmatched payment receipts: {money(data.unappliedCents)}</p>:null}
 </section>
}
