import {useEffect,useState} from 'react'
import {payrollApi,type OffCycleExpense} from '../../utils/payrollApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
export default function OffCycleReimbursement({onChanged}:{onChanged:()=>Promise<void>}){
 const [expenses,setExpenses]=useState<OffCycleExpense[]>([]),[selected,setSelected]=useState(''),[date,setDate]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const [preview,setPreview]=useState<{netPayCents:number;warnings:Array<{message:string}>}|null>(null)
 useEffect(()=>{let active=true;payrollApi.offCycleExpenses().then(rows=>{if(active)setExpenses(rows)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[])
 const expense=expenses.find(e=>e.id===selected)
 return <section aria-label="Off-cycle reimbursement" className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-xl font-black">Off-cycle reimbursement</h3><p className="text-sm text-slate-600">Pay an approved expense separately, including for a former employee. This creates an expense-only payroll for review and payment confirmation.</p><form className="space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{setPreview((await payrollApi.previewOffCycleExpense(selected,date)).preview)}catch(e){setError(e instanceof Error?e.message:'Unable to preview reimbursement')}finally{setBusy(false)}}}><fieldset disabled={busy} className="space-y-3"><label className="block text-sm font-bold">Approved expense<select required className={workforceInput} value={selected} onChange={e=>{setSelected(e.target.value);setPreview(null)}}><option value="">Choose an expense</option>{expenses.map(e=><option key={e.id} value={e.id}>{e.employee_name} · request {e.source_request_id} · ${(Number(e.amount_cents)/100).toFixed(2)}</option>)}</select></label><label className="block text-sm font-bold">Off-cycle payment date<input required type="date" className={workforceInput} value={date} onChange={e=>{setDate(e.target.value);setPreview(null)}}/></label><button className={workforceButton} disabled={!selected||!date}>Preview reimbursement</button></fieldset></form>{error?<p role="alert" className="text-red-700">{error}</p>:null}{preview&&expense?<div className="space-y-2 rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold">Reimbursement to pay: ${(preview.netPayCents/100).toFixed(2)}</p><p>No worked wages or leave accrual. Tax treatment comes from the approved expense review.</p>{preview.warnings.map((w,i)=><p key={i} className="text-red-700">{w.message}</p>)}<button type="button" disabled={busy} className={workforceButton} onClick={async()=>{setBusy(true);setError('');try{const run=await payrollApi.createOffCycleExpense(selected,expense.period.id,date);setPreview(null);setSelected('');setExpenses(await payrollApi.offCycleExpenses());await onChanged();setMessage(`Off-cycle run ${run.id} saved. Open it below to review and approve payment.`)}catch(e){setError(e instanceof Error?e.message:'Unable to save reimbursement payroll')}finally{setBusy(false)}}}>Save reimbursement draft</button></div>:null}{message?<p role="status" className="text-emerald-700">{message}</p>:null}</section>
}
