import OnboardingNextSteps from './OnboardingNextSteps'
import BenefitsDeductionAuthorization from './BenefitsDeductionAuthorization'
import EmployeeBenefitsChoice from './EmployeeBenefitsChoice'
import HiringBenefitsReview from './HiringBenefitsReview'
import EmployeeAcknowledgments from './EmployeeAcknowledgments'
import OnboardingHistory from './OnboardingHistory'
import { useCallback, useEffect, useId, useState } from 'react'
import { workforceApi, type Packet, type OnboardingTask, type BenefitsReview } from '../../utils/workforceApi'

export const workforceInput = 'mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900'
export const workforceButton = 'rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40'
const stableTerms=(value:unknown)=>JSON.stringify(value,(_key,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])):v)
const labels: Record<string, string> = { legalFirstName: 'Legal first name', legalLastName: 'Legal last name', address: 'Home street address', city: 'City', state: 'State', postalCode: 'ZIP code', phone: 'Phone', emergencyName: 'Emergency contact name', emergencyPhone: 'Emergency contact phone', emergencyRelationship: 'Relationship' }
const sources: Record<string, string> = { W4: 'https://www.irs.gov/pub/irs-pdf/fw4.pdf', STATE_WITHHOLDING: 'https://www.marylandcomptroller.gov/forms/current_forms/MW507.pdf', I9: 'https://www.uscis.gov/i-9' }
export default function OnboardingWorkspace({ employeeId, employmentStatus, onChanged }: { employeeId?: number; employmentStatus: string; onChanged: () => Promise<void> }) {
 const workspaceId=useId()
 const [data, setData] = useState<Packet | null>(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false)
 const load = useCallback(async () => { setData(await workforceApi.packet(employeeId)) }, [employeeId])
 useEffect(() => { let live = true; workforceApi.packet(employeeId).then(next => { if (live) setData(next) }).catch(e => { if (live) setError(e.message) }); return () => { live = false } }, [employeeId])
 const act = async (work: () => Promise<unknown>, message: string) => { setBusy(true); setError(''); setNotice(''); try { await work(); await load(); await onChanged(); setNotice(message) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save changes') } finally { setBusy(false) } }
 return <section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
  <div><h2 className="text-xl font-black text-slate-950">{employeeId ? 'Hiring checklist & review' : 'Complete your onboarding'}</h2><p className="mt-1 text-sm text-slate-600">Each submission is saved and reviewed by your hiring admin. Save progress on unfinished steps and return later. Only submitted steps are ready for admin review.</p></div>
  <button type="button" disabled={busy} className="text-left text-sm font-bold underline disabled:opacity-50" onClick={()=>void act(()=>Promise.resolve(), 'Checklist refreshed.')}>Refresh checklist</button>
  {error ? <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}
  {notice ? <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p> : null}
  {!data ? <p>Loading onboarding packet…</p> : <>
   <div className="rounded-xl bg-slate-50 p-4"><p className="font-bold">{data.readiness.complete} of {data.readiness.total} steps complete</p><progress aria-label="Onboarding progress" value={data.readiness.complete} max={data.readiness.total || 1} className="mt-2 h-3 w-full accent-red-600" />{data.readiness.ready ? <p className="mt-2 text-sm text-emerald-800">All required steps have been reviewed.</p> : <p className="mt-2 text-sm text-slate-600">Next: {data.readiness.blockers[0]}</p>}</div>
   <OnboardingNextSteps packet={data} admin={!!employeeId} workspaceId={workspaceId}/>
   {data.policy.firstDayInstructions ? <div className="rounded-xl bg-blue-50 p-4 text-sm"><h3 className="font-bold">Your first day</h3><p className="mt-2 whitespace-pre-wrap">{data.policy.firstDayInstructions}</p></div> : null}
   {data.policy.payrollProviderUrl ? <a href={data.policy.payrollProviderUrl} target="_blank" rel="noreferrer" className="inline-block font-bold text-blue-700 underline">Open secure payroll provider</a> : null}
   {data.tasks.map(task => <TaskStep key={`${task.id}-${task.status}-${task.task_key==='HANDBOOK'?JSON.stringify([data.policy.handbookText,data.policy.benefitsText]):task.task_key==='WAGE_NOTICE'?JSON.stringify(data.wageTerms):task.task_key==='PAY_REVIEW'?data.paySetup?.fingerprint:''}`} taskId={`${workspaceId}-task-${task.id}`} task={task} packet={data} employmentStatus={employmentStatus} employeeId={employeeId} busy={busy} act={act} />)}
   {employeeId && employmentStatus === 'ONBOARDING' ? <button type="button" disabled={busy || !data.readiness.ready} onClick={() => void act(() => workforceApi.activate(employeeId), 'Onboarding complete. Employee activated.')} className={workforceButton}>Complete onboarding & activate employee</button> : null}
  </>}
 </section>
}
function TaskStep({ taskId, task, packet, employeeId, busy, act, employmentStatus }: { taskId:string;employmentStatus:string;task: OnboardingTask; packet: Packet; employeeId?: number; busy: boolean; act: (work: () => Promise<unknown>, message: string) => Promise<void> }) {
 const [benefits,setBenefits]=useState<BenefitsReview>({...packet.benefitsReview,disposition:packet.benefitsReview?.disposition||'',effectiveOn:packet.benefitsReview?.effectiveOn||'',summary:packet.benefitsReview?.summary||'',confirmed:false,employerFundingConfirmed:false})
 const [form, setForm] = useState<Record<string, unknown>>(() => ((task.task_key === 'HANDBOOK' && (task.response?.terms !== (packet.policy.handbookText || '') || task.response?.benefitsTerms !== (packet.policy.benefitsText || ''))) || (task.task_key === 'WAGE_NOTICE' && Object.entries(packet.wageTerms || {}).some(([key,value]) => stableTerms((task.response?.terms as Record<string,unknown> | undefined)?.[key]) !== stableTerms(value)))) ? {...task.response, acknowledged:false} : task.response || {}), [reviewNote, setReviewNote] = useState('')
 const set = (key: string, value: unknown) => setForm(current => ({ ...current, [key]: value }))
 const acknowledgmentIssue = packet.reviewIssues?.find(issue=>Number(issue.taskId)===Number(task.id))
 const deductionPending=task.task_key==='PAY_REVIEW'&&packet.benefitsDeduction?.required&&packet.benefitsDeduction.status!=='CURRENT'
 const stalePay = task.task_key === 'PAY_REVIEW' && packet.paySetup?.status === 'NEEDS_REVIEW'
 const staleShift = task.task_key === 'FIRST_SHIFT' && packet.firstShift?.status === 'NEEDS_REVIEW'
 const done = !deductionPending && !stalePay && !acknowledgmentIssue && !staleShift && ['COMPLETE', 'NOT_APPLICABLE'].includes(task.status)
 const files = packet.documents.filter(d => Number(d.task_id) === Number(task.id))
 const canSubmit = !employeeId && task.owner === 'EMPLOYEE' && ['OPEN','SUBMITTED','CHANGES_REQUESTED'].includes(task.status)
 return <details id={taskId} className="rounded-xl border border-slate-200 p-4" open={task.status === 'CHANGES_REQUESTED' || (task.task_key === 'PROFILE' && !done)}>
  <summary className="cursor-pointer text-sm font-bold text-slate-900"><span>{task.title}</span><span className={`ml-3 inline-block rounded-full px-2 py-1 text-xs ${done ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-900'}`}>{stalePay||staleShift||acknowledgmentIssue?'REVIEW REQUIRED':deductionPending?'SIGNATURE REQUIRED':task.status.replaceAll('_', ' ')}</span><span className="ml-2 text-xs font-normal text-slate-500">{task.owner === 'ADMIN' ? 'Hiring admin' : 'Employee'} · due {String(task.due_date || '').slice(0, 10)}</span></summary>
  <p className="mt-3 text-sm leading-6 text-slate-600">{task.instructions}</p>
  {acknowledgmentIssue ? <p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-950">{acknowledgmentIssue.message}. {task.status==='COMPLETE'?(employeeId?'Request changes below to collect a fresh acknowledgment.':'Ask your hiring admin to reopen this step so you can review and acknowledge the revised terms.'):'Review the revised terms below before submitting again.'}</p>:null}
  {task.review_note ? <p className="mt-2 rounded-lg bg-blue-50 p-3 text-sm text-blue-900">Admin review: {task.review_note}</p> : null}
  {sources[task.task_key] ? <a className="mt-2 inline-block text-sm font-bold text-blue-700 underline" href={sources[task.task_key]} target="_blank" rel="noreferrer">Open official form</a> : null}
  {task.task_key==='PAY_REVIEW'&&packet.paySetup?<div className="mt-3 space-y-2 rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold">Employee pay setup: {packet.paySetup.status==='CURRENT'?'reviewed and current':packet.paySetup.status==='NEEDS_REVIEW'?'updated review required':'awaiting review'}</p><p>Tax elections: {packet.paySetup.taxYear?`${packet.paySetup.taxYear} recorded`:'not verified'}</p><p>Payment election: {packet.paySetup.paymentMethod?.replaceAll('_',' ').toLowerCase()||'not recorded'}</p>{packet.paySetup.issues.length?<ul className="list-inside list-disc">{packet.paySetup.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:<p>Recorded tax and payment settings are ready for admin verification.</p>}</div>:null}
  {task.task_key==='PAY_REVIEW'?<EmployeeBenefitsChoice key={`${packet.benefitsElection?.submissionId||''}-${packet.policy.benefitsText||''}`} saved={packet.benefitsElection||null} plans={packet.benefitPlans||[]} policy={packet.policy.benefitsText||''} cycle={task.onboarding_cycle} readOnly={!!employeeId||!['ACTIVE','ONBOARDING'].includes(employmentStatus)} busy={busy} act={act}/>:null}
  {task.task_key==='PAY_REVIEW'&&packet.benefitsDeduction?<BenefitsDeductionAuthorization key={`${packet.benefitsDeduction.proposal?.fingerprint||''}-${packet.benefitsDeduction.saved?.requestKey||''}-${packet.benefitsDeduction.status}`} data={packet.benefitsDeduction} cycle={task.onboarding_cycle} readOnly={!!employeeId||!['ACTIVE','ONBOARDING'].includes(employmentStatus)} busy={busy} act={act}/>:null}
  {task.task_key==='PAY_REVIEW'?<HiringBenefitsReview saved={packet.benefitsReview||null} value={benefits} onChange={employeeId?setBenefits:undefined} policy={packet.policy.benefitsText||''} current={packet.paySetup?.benefitsCurrent===true}/>:null}
  {task.task_key === 'FIRST_SHIFT' && packet.firstShift ? <div className="mt-3 space-y-2 rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold">First-shift handoff: {packet.firstShift.status==='CURRENT'?'review matches the current shift':packet.firstShift.status==='NEEDS_REVIEW'?'updated review required':packet.firstShift.status==='NOT_REQUIRED'?'exception recorded':'awaiting hiring admin review'}</p>{packet.firstShift.current?<><p>{new Date(packet.firstShift.current.start).toLocaleString('en-US',{timeZone:packet.firstShift.current.timezone})} through {new Date(packet.firstShift.current.end).toLocaleString('en-US',{timeZone:packet.firstShift.current.timezone})} ({packet.firstShift.current.timezone})</p><p>{packet.firstShift.current.location||'Location not entered'} · {packet.firstShift.current.activityType.toLowerCase()}</p>{packet.firstShift.current.notes?<p className="whitespace-pre-wrap">{packet.firstShift.current.notes}</p>:null}</>:<p>No eligible first shift. Your hiring admin must schedule it.</p>}{staleShift&&packet.firstShift.reviewed?<div className="mt-3 border-t border-slate-200 pt-3"><p className="font-bold">Previously reviewed shift</p><p>{new Date(packet.firstShift.reviewed.start).toLocaleString('en-US',{timeZone:packet.firstShift.reviewed.timezone})} through {new Date(packet.firstShift.reviewed.end).toLocaleString('en-US',{timeZone:packet.firstShift.reviewed.timezone})} ({packet.firstShift.reviewed.timezone})</p><p>{packet.firstShift.reviewed.location||'Location not entered'} · {packet.firstShift.reviewed.activityType.toLowerCase()}</p><p className="whitespace-pre-wrap">{packet.firstShift.reviewed.notes}</p></div>:null}</div>:null}
  {task.task_key === 'HANDBOOK' ? <div className="my-3 max-h-96 overflow-auto whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm">{packet.policy.handbookText || 'Your hiring admin has not published the handbook and leave policy yet.'}{packet.policy.benefitsText ? `\n\nBenefits\n${packet.policy.benefitsText}` : ''}</div> : null}
  {task.task_key === 'WAGE_NOTICE' && packet.wageTerms ? <div className="mt-3 space-y-2 rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold">Current hiring terms</p><p>{packet.wageTerms.jobTitle} · {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(packet.wageTerms.payType==='SALARY'?packet.wageTerms.annualSalaryCents:packet.wageTerms.hourlyRateCents)/100)} {packet.wageTerms.payType==='SALARY'?'per year':'per hour'}</p><p>Overtime classification: {packet.wageTerms.overtimeClassification==='NONEXEMPT'?'Overtime eligible':packet.wageTerms.overtimeClassification==='EXEMPT'?'Exempt':'Pending review'}</p><p>Hire date: {packet.wageTerms.hireDate.slice(0,10)} · {packet.wageTerms.location||'Work location pending'}</p><p>{packet.wageTerms.paySchedule}</p>{packet.wageTerms.salaryWeeklyHours?<p>Salary covers {packet.wageTerms.salaryWeeklyHours} hours per week. Additional hours up to 40 receive straight-time pay; overtime follows after 40.</p>:null}{packet.wageTerms.normalWorkweekMinutes?<p>Normal workweek for sick leave: {packet.wageTerms.normalWorkweekMinutes.map((v,i)=>v?`${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][i]} ${v/60}h`:null).filter(Boolean).join(' · ')}</p>:null}</div> : null}
  {employeeId && Object.keys(task.response || {}).filter(key=>key!=='firstShift'&&key!=='paySetup'&&key!=='benefitsReview'&&key!=='benefitsElection'&&key!=='benefitsDeductionAuthorization'&&key!=='benefitsDeductionWithdrawal'&&key!=='benefitsDeductionSupersededByFunding').length ? <dl className="my-3 space-y-2 rounded-xl bg-slate-50 p-3 text-sm">{Object.entries(task.response).filter(([key])=>key!=='firstShift'&&key!=='paySetup'&&key!=='benefitsReview'&&key!=='benefitsElection'&&key!=='benefitsDeductionAuthorization'&&key!=='benefitsDeductionWithdrawal'&&key!=='benefitsDeductionSupersededByFunding').map(([key, value]) => <div key={key}><dt className="font-bold">{labels[key] || key}</dt><dd className="break-words whitespace-pre-wrap">{typeof value === 'object' ? JSON.stringify(value, null, 2) : String(value)}</dd></div>)}</dl> : null}
  {files.length ? <ul className="my-3 space-y-2">{files.map(file => <li key={file.id}><button type="button" className="text-sm font-bold text-blue-700 underline" disabled={busy} onClick={() => void act(() => workforceApi.download(Number(file.id), file.filename, !!employeeId), 'Document downloaded.')}>{file.filename}</button></li>)}</ul> : null}
  {canSubmit ? <form className="mt-4 space-y-3" onSubmit={e => { e.preventDefault(); void act(() => workforceApi.submit(Number(task.id), {...form,onboardingCycle:task.onboarding_cycle,...(task.task_key==='WAGE_NOTICE'?{displayedWageTerms:packet.wageTerms}:task.task_key==='HANDBOOK'?{displayedHandbookTerms:{handbookText:packet.policy.handbookText||'',benefitsText:packet.policy.benefitsText||''}}:{})}), 'Step submitted for review.') }}>
   {task.task_key === 'PROFILE' ? <div className="grid gap-3 sm:grid-cols-2">{Object.entries(labels).map(([key, label]) => <label key={key} className="text-sm font-semibold">{label}<input required value={String(form[key] || '')} maxLength={1000} onChange={e => set(key, e.target.value)} className={workforceInput} /></label>)}</div> : null}
   {task.task_key === 'PAYMENT' ? <><label className="block text-sm font-semibold">Payment method<select required value={String(form.method || '')} onChange={e => set('method', e.target.value)} className={workforceInput}><option value="">Choose payment method</option><option value="CHECK">Paper check</option><option value="DIRECT_DEPOSIT">Direct deposit through payroll provider</option></select></label>{form.method === 'DIRECT_DEPOSIT' ? <label className="block text-sm font-semibold">Provider setup confirmation<input required value={String(form.reference || '')} onChange={e => set('reference', e.target.value)} className={workforceInput} placeholder="Confirmation reference, not bank numbers" /></label> : null}</> : null}
   {['HANDBOOK', 'WAGE_NOTICE'].includes(task.task_key) ? <><label className="block text-sm font-semibold">Your full name<input required value={String(form.signature || '')} onChange={e => set('signature', e.target.value)} className={workforceInput} /></label><label className="flex items-start gap-2 text-sm"><input required type="checkbox" checked={form.acknowledged === true} onChange={e => set('acknowledged', e.target.checked)} />I have read and acknowledge receipt of these terms. My typed name records this acknowledgment.</label></> : null}
   {['W4', 'STATE_WITHHOLDING', 'I9'].includes(task.task_key) ? <><label className="block text-sm font-semibold">Signed form (PDF, PNG or JPEG; up to 5 MB)<input type="file" accept="application/pdf,image/png,image/jpeg" disabled={busy || !packet.vaultReady} className={workforceInput} onChange={e => { const file = e.target.files?.[0]; if (file) void act(() => workforceApi.upload(Number(task.id), file, task.onboarding_cycle), 'Document securely uploaded. Submit the step when ready.') }} /></label>{!packet.vaultReady ? <p className="text-xs text-amber-800">Secure uploads require server configuration. Use the designated payroll provider and enter its receipt below.</p> : null}<label className="block text-sm font-semibold">Secure provider receipt (if completed with provider)<input value={String(form.reference || '')} onChange={e => set('reference', e.target.value)} className={workforceInput} placeholder="Receipt reference, not SSN or bank numbers" /></label></> : null}
   {task.task_key === 'AVAILABILITY' ? <label className="block text-sm font-semibold">Availability & first-day questions<textarea required rows={4} value={String(form.note || '')} onChange={e => set('note', e.target.value)} className={workforceInput} /></label> : null}
   {['OPEN','CHANGES_REQUESTED'].includes(task.status) ? <button type="button" disabled={busy} className={`${workforceButton} mr-2`} onClick={() => void act(() => workforceApi.saveDraft(Number(task.id), {...form,onboardingCycle:task.onboarding_cycle}), 'Draft saved. This step has not been submitted for review.')}>Save progress</button> : null}
   <button disabled={busy || (task.task_key === 'HANDBOOK' && !packet.policy.handbookText)} className={workforceButton}>{task.status === 'SUBMITTED' ? 'Update submission' : 'Submit for review'}</button>
  </form> : null}
  {employeeId ? <div className="mt-4 space-y-3"><label className="block text-sm font-semibold">Review evidence / instructions<textarea rows={2} value={reviewNote} onChange={e => setReviewNote(e.target.value)} className={workforceInput} placeholder="Verification performed, confirmation reference, or changes needed" /></label><div className="flex flex-wrap gap-2"><button disabled={busy || !reviewNote.trim() || (task.task_key==='PAY_REVIEW'&&(!!packet.paySetup?.issues.length||!benefits.disposition||!benefits.effectiveOn||benefits.summary.trim().length<10||(benefits.evidenceReference||'').trim().length<12||!benefits.confirmed||(benefits.disposition==='ENROLLED_EMPLOYER_FUNDED'&&!benefits.employerFundingConfirmed))) || (task.owner === 'EMPLOYEE' && task.status !== 'SUBMITTED')} type="button" className={workforceButton} onClick={() => void act(() => workforceApi.review(employeeId, Number(task.id), 'COMPLETE', reviewNote, task.onboarding_cycle,task.task_key==='PAY_REVIEW'?packet.paySetup?.fingerprint:undefined,task.task_key==='PAY_REVIEW'?benefits:undefined), 'Step reviewed and completed.')}>Verify & complete</button><button disabled={busy || !reviewNote.trim()} type="button" className={workforceButton} onClick={() => void act(() => workforceApi.review(employeeId, Number(task.id), 'CHANGES_REQUESTED', reviewNote, task.onboarding_cycle), 'Step reopened with review instructions.')}>Request changes</button>{!['PROFILE','W4','I9','I9_REVIEW','WAGE_NOTICE','PAYMENT','PAY_REVIEW'].includes(task.task_key) ? <button disabled={busy || !reviewNote.trim()} type="button" className={workforceButton} onClick={() => void act(() => workforceApi.review(employeeId, Number(task.id), 'NOT_APPLICABLE', reviewNote, task.onboarding_cycle), 'Exception recorded with supporting reason.')}>Record not applicable</button> : null}</div></div> : null}
 {!employeeId&&['WAGE_NOTICE','HANDBOOK'].includes(task.task_key)?<EmployeeAcknowledgments taskId={Number(task.id)}/>:null}
 {employeeId?<OnboardingHistory employeeId={employeeId} taskId={Number(task.id)}/>:null}
 </details>
}
