import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
import PaymentBatch from './PaymentBatch'
type Plan={fingerprint:string;paymentDate:string;status:string;issues:string[];totals:{directDepositCents:number;checkCents:number;zeroNetEmployees:number;totalCents:number};payments:Array<{employeeId:number;employeeName:string;method:string;amountCents:number}>}
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100)
export default function PaymentPlan({runId,finalized=false}:{runId:number;finalized?:boolean}){
 const [data,setData]=useState<Plan|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=async()=>{setData(null);setBusy(true);setError('');try{const response=await adminApiRequest(`/api/admin/payroll/runs/${runId}/payment-plan`),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to prepare payment plan.');setData(json.data)}catch(e){setError(e instanceof Error?e.message:'Unable to prepare payment plan.')}finally{setBusy(false)}}
 return <section aria-label="Payroll payment plan" className="space-y-3 rounded-xl border p-4"><h3 className="font-bold">Payroll payment plan</h3>{!finalized?<><p className="text-sm text-slate-600">Review the approved net pay by payment method. Preparing this plan does not send payments.</p><button type="button" disabled={busy} className="font-bold underline" onClick={()=>void load()}>Prepare payment plan</button></>:<p>Retained payment history and provider recovery for finalized payroll.</p>}{error?<p role="alert" className="text-red-700">{error}</p>:null}{data?<><p>{data.status==='NEEDS_REVIEW'?'Resolve payment setup issues.':'Ready for payment review.'} Approved date: {data.paymentDate}</p>{data.issues.length?<ul className="list-inside list-disc text-red-700">{data.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:null}<p>Direct deposit: {money(data.totals.directDepositCents)} · Checks: {money(data.totals.checkCents)} · Zero-net employees: {data.totals.zeroNetEmployees}</p><p className="font-bold">Total net pay: {money(data.totals.totalCents)}</p><ul>{data.payments.map(payment=><li key={payment.employeeId}>{payment.employeeName} · {payment.method.replaceAll('_',' ')} · {money(payment.amountCents)}</li>)}</ul></>:null}<PaymentBatch finalized={finalized} runId={runId} fingerprint={data?.fingerprint||null} ready={data?.status==='READY_FOR_PAYMENT_REVIEW'}/></section>
}
