import CheckStopCases from './CheckStopCases'
import CheckReceipts from './CheckReceipts'
import PaymentReplacementReview from './PaymentReplacementReview'
import SettlementPosting from './SettlementPosting'
import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Evidence={status:string;postingAvailable:boolean;issues:string[];totals:{withdrawalCents:number;returnedCents:number;netOutflowCents:number};events:Array<{key:string;employeeName:string;kind:string;sourceKind?:string;postedDate:string;amountCents:number;observationId:number}>}
const money=(cents:number)=>(cents/100).toLocaleString('en-US',{style:'currency',currency:'USD'})
export default function PaymentAccounting({runId}:{runId:number}){
 const [data,setData]=useState<Evidence|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=async()=>{setData(null);setBusy(true);setError('');try{const response=await adminApiRequest(`/api/admin/payroll/runs/${runId}/payment-accounting`),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to load bank reconciliation.');setData(json.data)}catch(e){setError(e instanceof Error?e.message:'Unable to load bank reconciliation.')}finally{setBusy(false)}}
 return <section aria-label="Payroll bank reconciliation" className="space-y-3 rounded border p-3"><h5 className="font-bold">Payroll bank reconciliation</h5><p>Compare original and replacement withdrawals and returned credits with your books. These movements do not create additional wages or taxes.</p><button type="button" disabled={busy} className="font-bold underline" onClick={()=>void load()}>Review bank movements</button>{error?<p role="alert" className="text-red-700">{error}</p>:null}{data?<><p role="status">{data.status.replaceAll('_',' ')}</p><dl className="space-y-1"><div><dt className="inline">Bank withdrawals: </dt><dd className="inline">{money(data.totals.withdrawalCents)}</dd></div><div><dt className="inline">Returned credits: </dt><dd className="inline">{money(data.totals.returnedCents)}</dd></div><div><dt className="inline">Net bank outflow: </dt><dd className="inline">{money(data.totals.netOutflowCents)}</dd></div></dl>{data.issues.length?<ul className="list-inside list-disc text-red-700">{data.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:null}<ul className="space-y-2">{data.events.map(event=><li key={event.key}>{event.employeeName} · {['REPLACEMENT','CHECK_REPLACEMENT'].includes(event.sourceKind||'')?'Replacement · ':event.sourceKind==='CHECK'?'Check · ':''}{event.kind==='RETURN'?'Returned credit':'Bank withdrawal'} · {event.postedDate} · {money(event.amountCents)}<p className="text-sm text-slate-600">Retained bank evidence {event.observationId}</p></li>)}</ul><p>Compare these movements with your payroll-clearing and bank accounts in QuickBooks. This review retains the distinction between bank activity and wage calculations.</p></>:null}<CheckReceipts runId={runId}/><CheckStopCases runId={runId}/><SettlementPosting runId={runId}/><PaymentReplacementReview runId={runId}/></section>
}
