import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type State={revision:number;status:string;paymentConnectionId:number;paymentMode:string|null;connection:{realmId:string;environment:string;generation:number;clearingAccountId:string|null}|null;history:Array<{id:string;reference:string;created_at:string;details:{bank:{id:string;name:string};clearing:{id:string;name:string}}}>}
export default function PaymentAccountingMapping({accounts}:{accounts:Array<{Id:string;FullyQualifiedName:string}>}){
 const [data,setData]=useState<State|null>(null),[bank,setBank]=useState(''),[clearing,setClearing]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const path='/api/admin/payroll/quickbooks/payment-mapping'
 const load=async()=>{setBusy(true);setData(null);setError('');setConfirmed(false);try{const response=await adminApiRequest(path),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to read settlement mapping.');setData(json.data);setBank(json.data.history[0]?.details.bank.id||'');setClearing(json.data.connection?.clearingAccountId||'')}catch(e){setError(e instanceof Error?e.message:'Unable to read settlement mapping.')}finally{setBusy(false)}}
 const save=async()=>{if(!data?.connection||!confirmed||busy)return;setBusy(true);setError('');setMessage('');try{const response=await adminApiRequest(path,{method:'POST',body:JSON.stringify({expectedRevision:data.revision,paymentConnectionId:data.paymentConnectionId,connectionGeneration:data.connection.generation,realmId:data.connection.realmId,environment:data.connection.environment,bankAccountId:bank,clearingAccountId:clearing,reference,confirmed:true})}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to save settlement mapping.');await load();setMessage('Bank and clearing mapping verified and retained.')}catch(e){setData(null);setError(e instanceof Error?e.message:'Unable to save settlement mapping.')}finally{setBusy(false);setConfirmed(false)}}
 return <section aria-label="Bank settlement mapping" className="mt-4 space-y-3 rounded border p-4"><h3 className="font-bold">Bank settlement mapping</h3><p>Connect payment withdrawals and returns to the correct QuickBooks bank and payroll-clearing liability accounts.</p><button type="button" disabled={busy} className="font-bold underline" onClick={()=>void load()}>Review settlement mapping</button>{error?<p role="alert" className="text-red-700">{error}</p>:null}{message?<p role="status">{message}</p>:null}{data?<><p>{data.status.replaceAll('_',' ')}</p>{!data.connection||data.paymentMode!=='LIVE'?<p>Connect QuickBooks and configure a live payroll payment connection before mapping bank movements.</p>:<><p>Company {data.connection.realmId} · {data.connection.environment} · Payment connection {data.paymentConnectionId}</p><p>Use “Load chart of accounts” above to load account choices.</p><fieldset disabled={busy} className="space-y-3"><legend className="font-bold">Verify settlement accounts</legend><label className="block">Settlement bank account<select className="block w-full rounded border p-2" value={bank} onChange={e=>{setBank(e.target.value);setConfirmed(false)}}><option value="">Select the payroll bank</option>{bank&&!accounts.some(a=>a.Id===bank)?<option value={bank}>Saved account {bank}</option>:null}{accounts.map(a=><option key={a.Id} value={a.Id}>{a.FullyQualifiedName}</option>)}</select></label><label className="block">Settlement clearing liability<select className="block w-full rounded border p-2" value={clearing} onChange={e=>{setClearing(e.target.value);setConfirmed(false)}}><option value="">Select the clearing liability</option>{clearing&&!accounts.some(a=>a.Id===clearing)?<option value={clearing}>Saved account {clearing}</option>:null}{accounts.map(a=><option key={a.Id} value={a.Id}>{a.FullyQualifiedName}</option>)}</select></label><label className="block">Settlement mapping review reference<input className="block w-full rounded border p-2" maxLength={500} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} /></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} />I verified that this bank account represents the payroll funding account and that the separate clearing liability matches the payroll journal.</label><button type="button" disabled={!confirmed||!/^\d+$/.test(bank)||!/^\d+$/.test(clearing)||reference.trim().length<12} className="rounded bg-slate-900 p-2 font-bold text-white disabled:opacity-50" onClick={()=>void save()}>Verify and save settlement mapping</button></fieldset></>}<ul className="space-y-2">{data.history.map(item=><li key={item.id}>Revision {item.id}: {item.details.bank.name} → {item.details.clearing.name}<p>{item.reference} · {new Date(item.created_at).toLocaleString()}</p></li>)}</ul></>:null}</section>
}
