import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Payment={employeeId:number;employeeName:string;amountCents:number;method:string}
export default function PaymentCloseout({runId,batch,onClosed}:{runId:number;batch:{check_deliveries?:Array<{employeeId:number;reference:string|null;ready:boolean;replacement?:{wageDate:string;replacementDate:string;method:string}|null}>;automatic_closeout?:{status:string;body:Record<string,unknown>}|null;id:string;fingerprint:string;plan:{paymentDate:string;payments:Payment[]};instructions:Array<{settlementStatus:string|null}>};onClosed:(message:string)=>Promise<void>}){
 const [reference,setReference]=useState(''),[checks,setChecks]=useState<Record<number,string>>({}),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const required=batch.plan.payments.filter(p=>p.method==='CHECK'),ready=batch.instructions.every(i=>i.settlementStatus==='BANK_POSTED')&&(batch.check_deliveries||[]).every(d=>d.ready&&!!d.reference)
 const checkReference=(id:number)=>(batch.check_deliveries||[]).find(d=>d.employeeId===id)?.reference??checks[id]??''
 const close=async(automatic=false)=>{
  if(busy||!confirmed||(!automatic&&!ready))return
  setBusy(true);setError('')
  try{
   const response=await adminApiRequest(`/api/admin/payroll/runs/${runId}/payment-closeout${automatic?'/automatic':''}`,{method:'POST',body:JSON.stringify({batchId:Number(batch.id),fingerprint:batch.fingerprint,paymentDate:batch.plan.paymentDate,reference,confirmed,checkPayments:required.map(p=>({employeeId:p.employeeId,amountCents:p.amountCents,paymentDate:batch.plan.paymentDate,reference:checkReference(p.employeeId)}))})}),json=await response.json()
   if(!response.ok)throw new Error(json.message||'Unable to close payroll.')
   await onClosed(automatic?'Automatic closeout scheduled.':json.data.quickbooksSync?.status==='FAILED'?'Payroll finalized. QuickBooks sync needs attention in Reports & QuickBooks.':'')
  }catch(e){setError(e instanceof Error?e.message:'Unable to close payroll.')}
  finally{setBusy(false);setConfirmed(false)}
 }
 const cancel=async()=>{if(busy)return;setBusy(true);setError('');try{const response=await adminApiRequest(`/api/admin/payroll/runs/${runId}/payment-closeout/automatic/cancel`,{method:'POST',body:JSON.stringify(batch.automatic_closeout?.body)}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to cancel automatic closeout.');await onClosed('Automatic closeout cancelled.')}catch(e){setError(e instanceof Error?e.message:'Unable to cancel automatic closeout.')}finally{setBusy(false)}}
 if(batch.automatic_closeout?.status==='SCHEDULED')return <section className="space-y-2 border-t pt-3"><p>Automatic closeout is scheduled. It waits for the approved payment date and current bank evidence.</p><button type="button" disabled={busy} className="underline" onClick={()=>void cancel()}>Cancel automatic closeout</button>{error?<p role="alert">{error}</p>:null}</section>
 return <fieldset disabled={busy} className="space-y-2 border-t pt-3"><legend className="font-bold">Close paid payroll</legend><p>Closeout creates employee statements and leave entries and runs configured QuickBooks sync. Recover bank evidence within 15 minutes of closing. Check records confirm delivery on {batch.plan.paymentDate}.</p>{batch.check_deliveries?.filter(d=>d.replacement).map(d=><p key={d.employeeId}>Confirmed replacement paid on {d.replacement!.replacementDate}. The reviewed original wage date remains {d.replacement!.wageDate}; closeout retains both records and creates no second wage payment.</p>)}{!ready?<p>Complete check handoffs and refresh payment evidence before closing.</p>:null}{required.map(p=><label className="block" key={p.employeeId}>Check delivery reference for {p.employeeName} · {(p.amountCents/100).toLocaleString('en-US',{style:'currency',currency:'USD'})}<input className="block w-full rounded border p-2" maxLength={200} readOnly={(batch.check_deliveries||[]).some(d=>d.employeeId===p.employeeId)} value={checkReference(p.employeeId)} onChange={e=>{setChecks({...checks,[p.employeeId]:e.target.value});setConfirmed(false)}} /></label>)}<label className="block">Payroll closeout reference<input className="block w-full rounded border p-2" maxLength={500} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} /></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm check deliveries and authorize closeout once bank evidence is verified for the approved payment date.</label>{error?<p role="alert" className="text-red-700">{error}</p>:null}<button type="button" disabled={!ready||!confirmed||reference.trim().length<12||required.some(p=>(checkReference(p.employeeId)).trim().length<4)} className="rounded bg-slate-900 p-2 font-bold text-white disabled:opacity-50" onClick={()=>void close()}>Finalize paid payroll</button>{batch.automatic_closeout?.status!=='CANCELLED'?<button type="button" disabled={!confirmed||reference.trim().length<12||required.some(p=>(checkReference(p.employeeId)).trim().length<4)} className="rounded border p-2 font-bold disabled:opacity-50" onClick={()=>void close(true)}>Close automatically when ready</button>:null}</fieldset>
}
