import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
export type SubmissionSchedule={status:string;submitAt:string;reference:string}
export default function PaymentSchedule({runId,batchId,instructionId,fingerprint,schedule,onSaved}:{runId:number;batchId:string;instructionId:string;fingerprint:string;schedule:SubmissionSchedule|null;onSaved:()=>Promise<void>}){
 const [when,setWhen]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const save=async(cancel=false)=>{if(busy||(!cancel&&!confirmed))return;setBusy(true);setError('');try{
  const response=await adminApiRequest(`/api/admin/payroll/runs/${runId}/payment-authorization/${batchId}/instructions/${instructionId}/schedule${cancel?'/cancel':''}`,{method:'POST',body:JSON.stringify({confirmed:true,fingerprint,...(!cancel?{submitAt:new Date(when).toISOString(),reference}:{})})}),json=await response.json()
  if(!response.ok)throw new Error(json.message||'Unable to save payment schedule.')
  await onSaved()
 }catch(e){setError(e instanceof Error?e.message:'Unable to save payment schedule.')}finally{setBusy(false);setConfirmed(false)}}
 return <div className="my-2 space-y-2 rounded border p-2">{schedule?<><p>Submission schedule: {schedule.status} · {new Date(schedule.submitAt).toLocaleString()} · {schedule.reference}</p>{schedule.status==='SCHEDULED'?<button type="button" disabled={busy} className="underline" onClick={()=>void save(true)}>Cancel scheduled submission</button>:null}</>:<details><summary>Schedule this employee payment</summary><p className="text-sm">Choose the provider submission time. Bank processing determines arrival; the approved payment date remains unchanged.</p><label className="block">Submission time (your device time)<input type="datetime-local" className="block w-full rounded border p-2" value={when} onChange={e=>{setWhen(e.target.value);setConfirmed(false)}}/></label><label className="block">Scheduling reference<input className="block w-full rounded border p-2" maxLength={500} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I authorize this employee’s displayed amount to be submitted at the selected time.</label><button type="button" disabled={busy||!confirmed||!when||reference.trim().length<12} className="rounded border p-2 font-bold disabled:opacity-50" onClick={()=>void save()}>Schedule employee payment</button></details>}{error?<p role="alert" className="text-red-700">{error}</p>:null}</div>
}
