import BankEnrollmentHistory from './BankEnrollmentHistory'
import {useEffect,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Destination={enrollment?:{status:string;accountType:string;accountLast4:string;attempts:number;linkedDestinationId:number}|null;revision:number;status:string;account?:{holderName:string;accountType:string;accountLast4:string;mode:string}}
export default function PaymentDestination({employeeId}:{employeeId:number}){
 const [loadKey,setLoadKey]=useState(0)
 const [data,setData]=useState<Destination|null>(null),[connectionId,setConnectionId]=useState(0),[accountId,setAccountId]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const path=`/api/admin/payroll/employees/${employeeId}/payment-destination`
 useEffect(()=>{let active=true;setData(null);setConnectionId(0);setConfirmed(false);setError('');Promise.all([adminApiRequest(path),adminApiRequest('/api/admin/payroll/payment-connection')]).then(async responses=>{const values=await Promise.all(responses.map(r=>r.json()));if(responses.some(r=>!r.ok))throw new Error('Unable to load employee payment setup.');if(active){setData(values[0].data);setConnectionId(values[1].data.revision)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to load payment setup.')});return()=>{active=false}},[path,loadKey])
 const save=async()=>{if(!data||!connectionId||!confirmed||busy)return;setBusy(true);setError('');setNotice('');try{const response=await adminApiRequest(path,{method:'POST',body:JSON.stringify({accountId,reference,confirmed,connectionId,expectedRevision:data.revision})}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to link payment account.');const read=await adminApiRequest(path),updated=await read.json();if(!read.ok)throw new Error('Account saved, but its current status could not be loaded. Refresh the employee.');setData(updated.data);setAccountId('');setReference('');setNotice('Provider account linked. Employee authorization is still required.')}catch(e){setData(null);setError(e instanceof Error?e.message:'Unable to link payment account.')}finally{setConfirmed(false);setBusy(false)}}
 return <section aria-label="Employee direct deposit account" className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Employee direct deposit account</h2><p className="text-sm text-slate-600">Employees can add and verify their bank account in Onboarding, then authorize wage deposits. You can also link an existing verified provider account after reviewing ownership evidence.</p>{error?<p role="alert" className="text-red-700">{error}</p>:null}{notice?<p role="status" className="text-emerald-800">{notice}</p>:null}
 <button type="button" disabled={busy} className="font-bold underline" onClick={()=>{setNotice('');setLoadKey(key=>key+1)}}>Refresh employee payment account</button>{data?<>{data.enrollment?<p>Employee bank enrollment: {data.enrollment.status.replaceAll('_',' ')} · {data.enrollment.accountType} ending {data.enrollment.accountLast4} · {data.enrollment.attempts} verification attempts{data.enrollment.linkedDestinationId?' · Account linked':''}</p>:<p>Employee has not started bank enrollment.</p>}<p>{data.status==='NOT_CONFIGURED'?'No provider account linked.':data.status==='CONNECTION_CHANGED'?'Employer connection changed. Verify and link the account again.':data.status==='EMPLOYEE_AUTHORIZATION_RECORDED'?'Employee authorization recorded · payment setup still requires review.':'Provider account linked · employee authorization required.'}</p>{data.account?<p>{data.account.holderName} · {data.account.accountType} ending {data.account.accountLast4} · {data.account.mode}</p>:null}{!connectionId?<p>Configure the employer payment connection in Employer setup first.</p>:null}<fieldset disabled={busy||!connectionId} className="space-y-3"><legend className="font-semibold">Link verified provider account</legend><label className="block">Employee provider account ID<input className="block w-full rounded border p-2" autoComplete="off" value={accountId} onChange={e=>{setAccountId(e.target.value);setConfirmed(false)}} /></label><label className="block">Account ownership review reference<input className="block w-full rounded border p-2" maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} /></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} />I reviewed the evidence linking this provider account to this employee.</label><button type="button" disabled={!confirmed||!accountId||reference.trim().length<12||busy} className="rounded bg-slate-900 px-4 py-2 font-bold text-white disabled:opacity-50" onClick={()=>void save()}>Link employee payment account</button></fieldset></>:null}<BankEnrollmentHistory key={employeeId} employeeId={employeeId} /></section>
}
