import {useEffect,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Check={id:string;status:string;reason:string;created_at:string}
type Connection={revision:number;status:string;vaultReady:boolean;verification:Check|null;verificationHistory:Check[];history:Array<{id:string;mode:string;status:string}>}
const empty={organizationId:'',originatingAccountId:'',apiKey:'',mode:'TEST',reference:''}
export default function PaymentConnection(){
 const [data,setData]=useState<Connection|null>(null),[form,setForm]=useState(empty),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=async()=>{setData(null);setConfirmed(false);setError('');try{const response=await adminApiRequest('/api/admin/payroll/payment-connection'),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to read payment configuration.');setData(json.data)}catch(e){setError(e instanceof Error?e.message:'Unable to read payment configuration.')}}
 useEffect(()=>{void load()},[])
 const change=(key:keyof typeof empty,value:string)=>{setForm(current=>({...current,[key]:value}));setConfirmed(false);setNotice('')}
 const save=async()=>{if(!data||!confirmed||busy)return;setBusy(true);setError('');setNotice('');try{const response=await adminApiRequest('/api/admin/payroll/payment-connection',{method:'POST',body:JSON.stringify({...form,expectedRevision:data.revision,confirmed})}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to save payment configuration.');setForm(empty);await load();setNotice('Payment configuration saved. Provider verification is still required.')}catch(e){setError(e instanceof Error?e.message:'Unable to save payment configuration.')}finally{setConfirmed(false);setForm(current=>({...current,apiKey:''}));setBusy(false)}}
 const verify=async()=>{if(!data?.revision||busy)return;setBusy(true);setError('');setNotice('');try{const response=await adminApiRequest('/api/admin/payroll/payment-connection/verify',{method:'POST',body:JSON.stringify({expectedRevision:data.revision})}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to verify payment configuration.');await load();setNotice(json.data.status==='VERIFIED'?'Funding account matched the saved configuration.':'Funding account verification needs attention.')}catch(e){setError(e instanceof Error?e.message:'Unable to verify payment configuration.');setData(null)}finally{setConfirmed(false);setBusy(false)}}
 return <section aria-label="Payroll payment connection" className="space-y-4 rounded-2xl border bg-white p-5">
  <h2 className="text-lg font-bold">Payroll payment connection</h2>
  <p className="text-sm text-slate-600">Configure Modern Treasury and the employer funding account. Saving credentials does not initiate payments. Submit authorized employee payments from an approved payroll run.</p>
  {error?<p role="alert" className="text-red-700">{error}</p>:null}{notice?<p role="status" className="text-emerald-800">{notice}</p>:null}
  <button type="button" disabled={busy} className="font-bold underline" onClick={()=>void load()}>Refresh payment connection</button>
  {data?<><p>{data.status==='NOT_CONFIGURED'?'No payment connection configured.':data.verification?.status==='VERIFIED'?'Configured · last funding account check passed.':'Configured · provider verification required.'}</p>{!data.vaultReady?<p role="alert">Encrypted storage must be configured on the server before saving credentials.</p>:null}
  {data.revision?<div className="space-y-2"><button type="button" disabled={busy||!data.vaultReady} className="font-bold underline disabled:opacity-50" onClick={()=>void verify()}>Verify funding account</button><p className="text-sm text-slate-600">Checks account access, USD currency and the saved environment. This does not verify available funds or authorize payroll.</p>{data.verification?<p>Last check: {data.verification.status} · {data.verification.reason.replaceAll('_',' ')} · {new Date(data.verification.created_at).toLocaleString()}</p>:null}{data.verificationHistory.length?<details><summary>Funding account check history</summary><ul>{data.verificationHistory.map(check=><li key={check.id}>{check.status} · {check.reason.replaceAll('_',' ')} · {new Date(check.created_at).toLocaleString()}</li>)}</ul></details>:null}</div>:null}
  <fieldset disabled={busy||!data.vaultReady} className="space-y-3"><legend className="font-semibold">Employer connection details</legend>
   <label className="block">Payment environment<select aria-label="Payment environment" className="block w-full rounded border p-2" value={form.mode} onChange={e=>change('mode',e.target.value)}><option value="TEST">Test</option><option value="LIVE">Live</option></select></label>
   <label className="block">Modern Treasury organization ID<input className="block w-full rounded border p-2" autoComplete="off" value={form.organizationId} onChange={e=>change('organizationId',e.target.value)} /></label>
   <label className="block">Employer funding account ID<input className="block w-full rounded border p-2" autoComplete="off" value={form.originatingAccountId} onChange={e=>change('originatingAccountId',e.target.value)} /></label>
   <label className="block">Modern Treasury API key<input type="password" autoComplete="new-password" maxLength={4096} className="block w-full rounded border p-2" value={form.apiKey} onChange={e=>change('apiKey',e.target.value)} /></label>
   <label className="block">Payment configuration reference<input maxLength={2000} className="block w-full rounded border p-2" value={form.reference} onChange={e=>change('reference',e.target.value)} /></label>
   <label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} />I verified the employer organization, funding account and environment.</label>
   <button type="button" disabled={!confirmed||!form.organizationId||!form.originatingAccountId||!form.apiKey||form.reference.trim().length<12||busy} className="rounded bg-slate-900 px-4 py-2 font-bold text-white disabled:opacity-50" onClick={()=>void save()}>Save payment connection</button>
  </fieldset>
  {data.history.length?<details><summary className="cursor-pointer font-semibold">Payment connection history</summary><ul>{data.history.map(row=><li key={row.id}>Revision {row.id} · {row.mode} · {row.status}</li>)}</ul></details>:null}</>:null}
 </section>
}
