import BenefitPlanCatalog from './BenefitPlanCatalog'
import { useState } from 'react'
import type { PayrollDashboard } from '../../utils/payrollApi'
import { workforceApi } from '../../utils/workforceApi'
import { workforceButton, workforceInput } from './OnboardingWorkspace'
export default function PayrollSettings({ settings, onChanged }: { settings: PayrollDashboard['settings']; onChanged: () => Promise<void> }) {
 const [form,setForm]=useState<Record<string,string>>({legalBusinessName:settings?.legalBusinessName||'',businessAddress:settings?.businessAddress||'',einStatus:settings?.einStatus||'MISSING',mdCrnStatus:settings?.mdCrnStatus||'MISSING',mdUiStatus:settings?.mdUiStatus||'MISSING',workersCompStatus:settings?.workersCompStatus||'MISSING',sickLeavePay:'UNPAID',...settings?.onboardingPolicy})
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const set=(key:string,value:string)=>setForm(current=>({...current,[key]:value}))
 return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Employer setup & onboarding materials</h2><p className="mt-2 text-sm text-slate-600">Publish the policies employees must read. Registration statuses reflect your verified accounts; they do not register or file with an agency.</p>{error?<p role="alert" className="mt-3 text-red-700">{error}</p>:null}{notice?<p role="status" className="mt-3 text-emerald-700">{notice}</p>:null}<form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await workforceApi.settings(form);await onChanged();setNotice('Employer setup saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save settings')}finally{setBusy(false)}}}>
 {([['legalBusinessName','Legal business name'],['businessAddress','Business address'],['businessPhone','Business telephone'],['payrollProviderUrl','Secure payroll provider URL']] as const).map(([key,label])=><label key={key} className="text-sm font-bold">{label}<input type={key==='payrollProviderUrl'?'url':'text'} required={['legalBusinessName','businessAddress'].includes(key)} value={form[key]||''} onChange={e=>set(key,e.target.value)} className={workforceInput}/></label>)}
 {([['einStatus','Federal EIN',['MISSING','OWNER_CONFIRMED','VERIFIED']],['mdCrnStatus','Maryland withholding account',['MISSING','APPLIED','ACTIVE']],['mdUiStatus','Maryland unemployment account',['MISSING','APPLIED','ACTIVE']],['workersCompStatus','Workers’ compensation',['MISSING','QUOTING','ACTIVE']]] as const).map(([key,label,choices])=><label key={key} className="text-sm font-bold">{label}<select value={form[key]} onChange={e=>set(key,e.target.value)} className={workforceInput}>{choices.map(value=><option key={value}>{value}</option>)}</select></label>)}
 {([['handbookText','Handbook & leave policy'],['benefitsText','Benefits eligibility & enrollment instructions'],['firstDayInstructions','First-day instructions & supervisor contact']] as const).map(([key,label])=><label key={key} className="text-sm font-bold sm:col-span-2">{label}<textarea rows={key==='handbookText'?8:4} value={form[key]||''} onChange={e=>set(key,e.target.value)} className={workforceInput}/></label>)}
 <label className="text-sm font-bold">Sick and safe leave pay policy<select value={form.sickLeavePay} onChange={e=>set('sickLeavePay',e.target.value)} className={workforceInput}><option value="UNPAID">Unpaid sick and safe leave</option><option value="PAID">Paid sick and safe leave</option></select></label><p className="text-xs text-slate-500">Choose the policy applicable to your workforce. Paid leave includes an allocation of hours by date and is excluded from overtime hours worked.</p>
 <button disabled={busy} className={workforceButton}>Save employer setup</button></form><BenefitPlanCatalog catalog={settings?.onboardingPolicy?.benefitCatalog||''} onChanged={onChanged}/></section>
}
