import {useCallback,useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Readiness={w2Provider?:{retained:number;pending:number;last_received_at:string|null;last_checked_at:string|null};runs?:Array<{id:number;source:string;status:string;started_at:string;finished_at:string|null;error_message:string|null}>;checkedAt:string;checks:Array<{key:string;title:string;configured:boolean;detail:string}>}
export default function PayrollServiceReadiness(){
 const request=useRef({revision:0})
 const [data,setData]=useState<Readiness|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=useCallback(async()=>{const current=++request.current.revision;setData(null);setBusy(true);setError('');try{const response=await adminApiRequest('/api/admin/payroll/service-readiness'),json=await response.json();if(!response.ok)throw new Error(json.message||'Could not check server setup');if(current===request.current.revision)setData(json.data)}catch(e){if(current===request.current.revision)setError(e instanceof Error?e.message:'Could not check server setup')}finally{if(current===request.current.revision)setBusy(false)}},[])
 useEffect(()=>{const token=request.current;void load();return()=>{token.revision++}},[load])
 return <section aria-label="Onboarding service setup" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
  <h2 className="text-xl font-black">Onboarding service setup</h2>
  <p className="mt-2 text-sm text-slate-600">Check server configuration before inviting employees. These checks do not send email or verify live delivery, stored documents or scheduled execution.</p>
  {error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}
  {data?<div className="mt-4 grid gap-3 sm:grid-cols-2">{data.checks.map(check=><div key={check.key} className="rounded-xl border border-slate-200 p-3 text-sm"><h3 className="font-bold">{check.title}</h3><p className={`mt-1 font-semibold ${check.configured?'text-emerald-700':'text-amber-800'}`}>{check.configured?'Settings present':'Setup needed'}</p><p className="mt-2 text-slate-600">{check.detail}</p></div>)}</div>:null}
  {data?<div className="mt-4 space-y-2 text-sm"><h3 className="font-bold">Recent payroll checks</h3>{!data.runs?.length?<p>No payroll check execution has been recorded yet.</p>:data.runs.map(run=><div key={run.id} className="rounded-xl border border-slate-200 p-3"><p className="font-semibold">{run.source==='SCHEDULED'?'Scheduled payroll checks':'Manual workforce checks'} · {run.status==='SUCCEEDED'?'Completed':run.status==='FAILED'?'Failed':'No completion recorded'}</p><p className="mt-1">Started {new Date(run.started_at).toLocaleString()}</p>{run.finished_at?<p>Finished {new Date(run.finished_at).toLocaleString()}</p>:null}{run.error_message?<p className="mt-2 text-red-700">{run.error_message}</p>:null}</div>)}</div>:null}
  {data?.w2Provider?<div className="mt-4 space-y-2 text-sm" aria-label="W-2 provider return activity"><h3 className="font-bold">W-2 provider return activity</h3><p>{data.w2Provider.retained} verified returns retained · {data.w2Provider.pending} pending reconciliation</p>{data.w2Provider.last_received_at?<p>Latest verified return: {new Date(data.w2Provider.last_received_at).toLocaleString()}</p>:<p>No verified provider return has been retained for this employer.</p>}{data.w2Provider.last_checked_at?<p>Latest reconciliation check: {new Date(data.w2Provider.last_checked_at).toLocaleString()}</p>:<p>No provider-return reconciliation check has been recorded.</p>}{data.w2Provider.pending>0?<p className="text-amber-900">Pending returns are checked automatically when reconciliation is enabled. Review payroll alerts and the employee’s W-2 publication if a return remains unresolved.</p>:null}<p>Return counts do not establish successful delivery of other notices. Review individual publications and paper follow-up evidence in Reports &amp; QuickBooks.</p></div>:null}
  <button type="button" disabled={busy} onClick={()=>void load()} className="mt-4 rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold disabled:opacity-50">{busy?'Checking setup…':'Refresh service setup'}</button>
 </section>
}
