import {useState} from 'react'
import {workforceApi} from '../../utils/workforceApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
export default function PayScheduleSetup({onChanged,currentFrequency,anchorStart,paymentLagDays}:{onChanged:()=>Promise<void>;currentFrequency:string;anchorStart?:string|null;paymentLagDays?:number|null}){
 const [form,setForm]=useState({frequency:currentFrequency,anchorStart:anchorStart||'',paymentLagDays:paymentLagDays??5,source:'',confirmed:false})
 const [periods,setPeriods]=useState<Array<{periodStart:string;periodEnd:string;payDate:string}>|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Payroll schedule setup</h2><p className="mt-2 text-sm text-slate-600">Current frequency: {currentFrequency.toLowerCase()}. Configure the schedule before the first payroll. Empty generated periods are replaced; existing runs or assigned reimbursements require a dated transition.</p>
 <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Payroll frequency<select className={workforceInput} value={form.frequency} onChange={e=>{setForm(f=>({...f,frequency:e.target.value,confirmed:false}));setPeriods(null)}}>{['SEMIMONTHLY','WEEKLY','BIWEEKLY'].map(value=><option key={value}>{value}</option>)}</select></label>
 {form.frequency!=='SEMIMONTHLY'?<><label className="text-sm font-bold">Reference period start<input type="date" className={workforceInput} value={form.anchorStart} onChange={e=>{setForm(f=>({...f,anchorStart:e.target.value,confirmed:false}));setPeriods(null)}}/></label><label className="text-sm font-bold">Calendar days after period end<input type="number" min="1" max="31" className={workforceInput} value={form.paymentLagDays} onChange={e=>{setForm(f=>({...f,paymentLagDays:Number(e.target.value),confirmed:false}));setPeriods(null)}}/></label></>:null}</div>
 <button type="button" disabled={busy} className={`${workforceButton} mt-3`} onClick={async()=>{setBusy(true);setError('');setMessage('');try{setPeriods((await workforceApi.previewPaySchedule(form)).periods)}catch(e){setError(e instanceof Error?e.message:'Unable to preview')}finally{setBusy(false)}}}>Preview pay schedule</button>
 {periods?<div className="mt-4"><p className="text-sm text-slate-600">Next three nominal payment months; weekends and bank holidays move payment earlier.</p><ul className="mt-2 space-y-1 text-sm">{periods.map(p=><li key={p.periodStart}>{p.periodStart} – {p.periodEnd} · pays {p.payDate}</li>)}</ul><label className="mt-3 block text-sm font-bold">Schedule policy or notice reference<input className={workforceInput} value={form.source} onChange={e=>setForm(f=>({...f,source:e.target.value}))}/></label><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={form.confirmed} onChange={e=>setForm(f=>({...f,confirmed:e.target.checked}))}/>I verified these dates against the published employee pay schedule.</label><button type="button" disabled={busy||!form.confirmed||form.source.trim().length<12} className={`${workforceButton} mt-3`} onClick={async()=>{setBusy(true);setError('');try{await workforceApi.configurePaySchedule(form);await onChanged();setMessage('Payroll schedule configured.');setPeriods(null);setForm(f=>({...f,confirmed:false}))}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}}>Save payroll schedule</button></div>:null}
 {error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}{message?<p role="status" className="mt-3 text-sm text-emerald-700">{message}</p>:null}
 </section>
}
