import ScheduleNoticeReceipts from './ScheduleNoticeReceipts'
import {useEffect,useState} from 'react'
import {workforceApi,type ScheduleTransitionPreview,type ScheduleVersion} from '../../utils/workforceApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
export default function PayScheduleTransition({onChanged}:{onChanged:()=>Promise<void>}){
 const [form,setForm]=useState({frequency:'WEEKLY',effectiveOn:'',paymentLagDays:5,source:'',noticeDeliveredOn:'',confirmed:false})
 const [preview,setPreview]=useState<ScheduleTransitionPreview|null>(null),[history,setHistory]=useState<ScheduleVersion[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{let active=true;workforceApi.payScheduleHistory().then(data=>{if(active)setHistory(data)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to load schedule history')});return()=>{active=false}},[])
 const change=(patch:Partial<typeof form>)=>{setForm(f=>({...f,...patch,confirmed:false}));setPreview(null);setMessage('')}
 return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Change an existing pay schedule</h2><p className="mt-2 text-sm text-slate-600">Start a future schedule after a complete current period. Earlier payroll stays in place. Future periods must be open and have no payroll runs or assigned reimbursements.</p>
 {history.length?<div className="mt-3"><h3 className="font-bold">Saved schedule history</h3><ul className="mt-2 space-y-2 text-sm">{history.map(v=><li key={v.id}>{v.effective_on} · {v.schedule_settings.pay_frequency.toLowerCase()}<span className="block break-words text-slate-600">{v.source}</span>{v.notice_delivered_on?<span className="block text-slate-600">Notice delivered {v.notice_delivered_on.slice(0,10)}</span>:null}{v.cancellation_notice_delivered_on?<span className="block text-slate-600">Cancellation notice delivered {v.cancellation_notice_delivered_on.slice(0,10)}</span>:null}{v.cancelled_at?<span className="block text-slate-600">Cancelled · {v.cancellation_source}</span>:null}{v.notice_delivered_on?<ScheduleNoticeReceipts versionId={v.id}/>:null}{v.can_cancel?<ScheduleCancellation version={v} onSaved={async()=>{setHistory(await workforceApi.payScheduleHistory());setPreview(null);await onChanged()}}/>:null}</li>)}</ul></div>:null}
 <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">New pay frequency<select className={workforceInput} value={form.frequency} onChange={e=>change({frequency:e.target.value})}>{['WEEKLY','BIWEEKLY','SEMIMONTHLY'].map(value=><option key={value}>{value}</option>)}</select></label><label className="text-sm font-bold">New schedule effective date<input type="date" className={workforceInput} value={form.effectiveOn} onChange={e=>change({effectiveOn:e.target.value})}/></label>{form.frequency!=='SEMIMONTHLY'?<label className="text-sm font-bold">New schedule payment lag in calendar days<input type="number" min="1" max="31" className={workforceInput} value={form.paymentLagDays} onChange={e=>change({paymentLagDays:Number(e.target.value)})}/></label>:null}</div>
 <button type="button" disabled={busy||!form.effectiveOn} className={`${workforceButton} mt-3`} onClick={async()=>{setBusy(true);setError('');setMessage('');try{setPreview(await workforceApi.previewScheduleTransition({...form,anchorStart:form.effectiveOn}))}catch(e){setError(e instanceof Error?e.message:'Unable to preview transition')}finally{setBusy(false)}}}>Preview schedule change</button>
 {preview?<div className="mt-4"><p className="text-sm text-slate-600">Last old period followed by the new schedule. {preview.replacedPeriodCount} unused future periods will be replaced. Bank holidays and weekends move payment earlier.</p><ul className="mt-2 space-y-1 text-sm">{preview.periods.map(p=><li key={p.periodStart}>{p.periodStart} – {p.periodEnd} · {p.frequency.toLowerCase()} · pays {p.payDate}</li>)}</ul><label className="mt-3 block text-sm font-bold">Schedule notice delivered on<input type="date" max={preview.noticeDeadline} className={workforceInput} value={form.noticeDeliveredOn} onChange={e=>setForm(f=>({...f,noticeDeliveredOn:e.target.value}))}/></label><p className="mt-1 text-sm text-slate-600">Notice deadline: {preview.noticeDeadline}. Enter the actual delivery date.</p><label className="mt-3 block text-sm font-bold">Employee schedule notice reference<input className={workforceInput} value={form.source} onChange={e=>setForm(f=>({...f,source:e.target.value}))}/></label><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={form.confirmed} onChange={e=>setForm(f=>({...f,confirmed:e.target.checked}))}/>I verified employee notice and the old and new payment dates.</label><button type="button" disabled={busy||!form.confirmed||!form.noticeDeliveredOn||form.source.trim().length<12} className={`${workforceButton} mt-3`} onClick={async()=>{setBusy(true);setError('');try{await workforceApi.saveScheduleTransition({...form,anchorStart:form.effectiveOn,previewToken:preview.previewToken});setPreview(null);setForm(f=>({...f,confirmed:false}));setHistory(await workforceApi.payScheduleHistory());await onChanged();setMessage('Dated payroll schedule change saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save transition')}finally{setBusy(false)}}}>Save dated schedule change</button></div>:null}
 {error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}{message?<p role="status" className="mt-3 text-sm text-emerald-700">{message}</p>:null}
 </section>
}

function ScheduleCancellation({version,onSaved}:{version:ScheduleVersion;onSaved:()=>Promise<void>}){
 const [preview,setPreview]=useState<ScheduleTransitionPreview|null>(null),[source,setSource]=useState(''),[noticeDeliveredOn,setNoticeDeliveredOn]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 return <details className="mt-2 rounded-lg border border-slate-200 p-3"><summary className="cursor-pointer font-bold">Cancel this future schedule change</summary><p className="mt-2 text-slate-600">Preview the restored schedule before confirming cancellation. Periods with payroll or assigned reimbursements cannot be replaced.</p><button type="button" className={`${workforceButton} mt-2`} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setPreview(await workforceApi.previewScheduleCancellation(version.id))}catch(e){setError(e instanceof Error?e.message:'Unable to preview cancellation')}finally{setBusy(false)}}}>Preview schedule cancellation</button>
 {preview?<div className="mt-3"><p>{preview.replacedPeriodCount} unused periods will be replaced.</p><ul className="mt-2 space-y-1">{preview.periods.map(p=><li key={p.periodStart}>{p.periodStart} – {p.periodEnd} · {p.frequency.toLowerCase()} · pays {p.payDate}</li>)}</ul><label className="mt-3 block font-bold">Cancellation notice delivered on<input type="date" className={workforceInput} max={preview.noticeDeadline} value={noticeDeliveredOn} onChange={e=>setNoticeDeliveredOn(e.target.value)}/></label><p className="mt-1 text-slate-600">Notice deadline: {preview.noticeDeadline}.</p><label className="mt-3 block font-bold">Cancellation notice delivery reference<input className={workforceInput} value={source} onChange={e=>setSource(e.target.value)}/></label><label className="mt-3 flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified delivery of the cancellation notice and the restored pay dates.</label><button type="button" disabled={busy||!confirmed||!noticeDeliveredOn||source.trim().length<12} className={`${workforceButton} mt-3`} onClick={async()=>{setBusy(true);setError('');try{await workforceApi.cancelScheduleTransition(version.id,{source,confirmed,noticeDeliveredOn,previewToken:preview.previewToken});await onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to cancel schedule')}finally{setBusy(false)}}}>Confirm schedule cancellation</button></div>:null}
 {error?<p role="alert" className="mt-2 text-red-700">{error}</p>:null}</details>
}
