import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Preview={timing?:{status:string;depositDate?:string;submissionAt?:string};amountCents:number;planName:string;withheldDate:string;destination:{holderName:string;accountLast4:string;mode:string};allocations:{ledgerId:string;employeeName:string;totalCents:number;participantMapping:{maskedIdentifiers:{providerPlanId:string;participantId:string}}}[];remainingRequirements:string[]}
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100)
export default function RetirementRemittancePreview({runId,planId,sourceFingerprint}:{runId:string;planId:string;sourceFingerprint:string}){
 const [preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),generation=useRef(0)
 useEffect(()=>{const invalidate=()=>{generation.current++};invalidate();setPreview(null);setError('');setBusy(false);return invalidate},[sourceFingerprint,runId,planId])
 return <section aria-label={`Retirement remittance preview ${runId} ${planId}`} className="space-y-2 border-t pt-3">
  <button type="button" disabled={busy} className="rounded border px-3 py-2" onClick={async()=>{const current=++generation.current;setBusy(true);setPreview(null);setError('');try{const r=await adminApiRequest(`/api/admin/payroll/runs/${runId}/retirement-remittance/preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({planId,sourceFingerprint})}),j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Unable to prepare remittance review.');if(current===generation.current)setPreview(j.data)}catch(e){if(current===generation.current)setError(e instanceof Error?e.message:'Unable to prepare remittance review.')}finally{if(current===generation.current)setBusy(false)}}}>Preview remittance for {planId}</button>
  {error?<p role="alert">{error}</p>:null}
  {preview?<div className="space-y-2 rounded border p-3"><h6 className="font-bold">{preview.planName} · Proposed remittance {money(preview.amountCents)}</h6><p>Withheld on {preview.withheldDate}</p><p>Contribution timing: {preview.timing?.status.replaceAll('_',' ')||'REVIEW REQUIRED'}</p>{preview.timing?.depositDate?<p>Reviewed deposit target: {preview.timing.depositDate} · Submission cutoff: {new Date(preview.timing.submissionAt!).toLocaleString()}</p>:null}<p>{preview.destination.holderName} · ending {preview.destination.accountLast4} · {preview.destination.mode}</p>{preview.allocations.map(a=><p key={a.ledgerId}>{a.employeeName}: {money(a.totalCents)} · Plan {a.participantMapping.maskedIdentifiers.providerPlanId} · Participant {a.participantMapping.maskedIdentifiers.participantId}</p>)}<p>No money or allocation file has been sent. This preview does not reserve contributions.</p><ul className="list-disc space-y-1 pl-5">{preview.remainingRequirements.map(item=><li key={item}>{item}</li>)}</ul></div>:null}
 </section>
}
