import RetirementSettlementRelease from './RetirementSettlementRelease'
import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Journal={id?:string;payload:{DocNumber:string;TxnDate:string;Line:{Amount:number;JournalEntryLineDetail:{PostingType:string;AccountRef:{value:string}}}[]};result?:{status:string;accountingVerified:boolean}|null}
type Preview={fingerprint:string;sourceJournalId:string;returnJournalId:string;realmId:string;environment:string;journals:Journal[]}
type Approval={id:string;cancelled_at:string|null;claimed:boolean;journals:Journal[];attempts:{id:string;status:string;message:string}[]}
async function request(path:string,body?:unknown){const response=await adminApiRequest(path,body===undefined?undefined:{method:'POST',body:JSON.stringify(body)}),result=await response.json();if(!response.ok||!result.success)throw Object.assign(new Error(result.message||'Unable to review replacement accounting.'),{status:response.status});return result.data}
function HistoryRow({row,onChanged}:{row:Approval;onChanged:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false)
 const act=async(cancel=false)=>{setBusy(true);setError('');try{await request(`/api/admin/payroll/retirement-replacement-settlement-authorizations/${row.id}/${cancel?'cancel':'post'}`,cancel?{confirmed:true,reference:reason}:{confirmed:true,action:'RECOVER'});setConfirmed(false);onChanged()}catch(e){setError(e instanceof Error?e.message:'Recover the retained accounting outcome.');onChanged()}finally{setBusy(false)}}
 return <article className="space-y-2 rounded border p-2">
  <p>Settlement approval: {row.cancelled_at?'CANCELLED':row.claimed?'CLAIMED':'AUTHORIZED — AWAITING AUTOMATIC POSTING'}</p>
  {row.journals.map(j=><p key={j.id}>Journal {j.payload.DocNumber}: {j.result?.status.replaceAll('_',' ')||'UNOBSERVED'} · Sources {j.result?.accountingVerified?'VERIFIED':'REQUIRE REVIEW'}</p>)}
  {row.attempts.length?<details><summary>Automatic replacement accounting attempts ({row.attempts.length})</summary>{row.attempts.map(a=><p key={a.id}>{a.status.replaceAll('_',' ')} · {a.message}</p>)}</details>:null}
  {error?<p role="alert">{error}</p>:null}
  {!row.cancelled_at?<fieldset disabled={busy} className="space-y-2">{row.claimed?<button type="button" className="rounded border px-3 py-2" onClick={()=>void act()}>Recover replacement journals</button>:<><label className="block">Replacement accounting cancellation reason<textarea className="block w-full rounded border p-2" value={reason} maxLength={2000} onChange={e=>{setReason(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Cancel this accounting approval before posting starts.</label><button type="button" className="rounded border px-3 py-2" disabled={!confirmed||reason.trim().length<20} onClick={()=>void act(true)}>Cancel replacement accounting approval</button></>}</fieldset>:null}
  {row.claimed&&!row.cancelled_at?<RetirementSettlementRelease replacement id={row.id} evidenceKey={JSON.stringify(row.journals)} onChanged={onChanged}/>:null}
 </article>
}
export default function RetirementReplacementSettlement({id}:{id:string}){
 const path=`/api/admin/payroll/retirement-replacement-authorizations/${id}`,[requested,setRequested]=useState(false),[revision,setRevision]=useState(0),[data,setData]=useState<Preview|null>(null),[rows,setRows]=useState<Approval[]|null>(null),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[retry,setRetry]=useState(false),[error,setError]=useState(''),[historyError,setHistoryError]=useState(''),pending=useRef<Record<string,unknown>|null>(null)
 useEffect(()=>{if(!requested)return;let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const value=await request(`${path}/settlement-authorizations`);if(live){setRows(value.history);setHistoryError('')}}catch(e){if(live){setRows(null);setHistoryError(e instanceof Error?e.message:'Unable to refresh accounting history.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[path,requested,revision])
 const preview=async()=>{setBusy(true);setData(null);setConfirmed(false);setError('');try{setData(await request(`${path}/settlement-preview`,{}));setRequested(true);setRevision(n=>n+1)}catch(e){setError(e instanceof Error?e.message:'Unable to verify accounting sources.')}finally{setBusy(false)}}
 const authorize=async()=>{setBusy(true);setError('');try{if(!pending.current){if(!data||!confirmed)throw new Error('Review the exact proposed journals first.');pending.current={confirmed:true,autoPost:true,outsideAccountingReviewed:true,fingerprint:data.fingerprint,reference,requestKey:crypto.randomUUID()}}await request(`${path}/settlement-authorizations`,pending.current);pending.current=null;setRetry(false);setData(null);setConfirmed(false);setRevision(n=>n+1)}catch(e){const status=e&&typeof e==='object'&&'status'in e?Number(e.status):0;if(status>=400&&status<500){pending.current=null;setData(null);setConfirmed(false)}setRetry(!!pending.current);setError(e instanceof Error?e.message:'Retry the original accounting approval.')}finally{setBusy(false)}}
 return <section aria-label={`Replacement settlement accounting ${id}`} className="space-y-2 rounded border p-2">
  <h6 className="font-bold">Replacement settlement accounting</h6>
  <p>Verify the payroll liability, original withdrawal and return journals, replacement withdrawal and reviewed QuickBooks accounts. Approved journals post automatically; unresolved outcomes recheck after five minutes and matched journals daily.</p>
  <button type="button" className="rounded border px-3 py-2" disabled={busy||retry} onClick={()=>void preview()}>Prepare replacement accounting preview</button>
  <button type="button" className="rounded border px-3 py-2" onClick={()=>{setRequested(true);setRevision(n=>n+1)}}>Refresh replacement accounting history</button>
  {error?<p role="alert">{error}</p>:null}{historyError?<p role="alert">{historyError} Automatic refresh will retry.</p>:null}
  {data?<><p>Payroll journal {data.sourceJournalId} · Return journal {data.returnJournalId} · Company {data.realmId} · {data.environment}</p>{data.journals.map(j=><article key={j.payload.DocNumber}><p>Replacement bank date: {j.payload.TxnDate}</p><p className="break-all">Proposed journal: {j.payload.DocNumber}</p>{j.payload.Line.map((l,i)=><p key={i}>{l.JournalEntryLineDetail.PostingType} account {l.JournalEntryLineDetail.AccountRef.value}: {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(l.Amount)}</p>)}</article>)}{rows&&!rows.some(r=>!r.cancelled_at)?<fieldset disabled={busy||retry} className="space-y-2"><label className="block">Replacement accounting review reference<textarea className="block w-full rounded border p-2" maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed these exact journals and outside accounting, found no duplicate entries, and authorize automatic posting.</label><button type="button" className="rounded border px-3 py-2" disabled={!confirmed||reference.trim().length<20} onClick={()=>void authorize()}>Authorize replacement accounting</button></fieldset>:null}</>:null}
  {retry?<button type="button" className="rounded border px-3 py-2" disabled={busy} onClick={()=>void authorize()}>Retry original replacement accounting approval</button>:null}
  {rows?.map(row=><HistoryRow key={row.id} row={row} onChanged={()=>setRevision(n=>n+1)}/>)}
 </section>
}
