import RetirementReplacementSettlement from './RetirementReplacementSettlement'
import RetirementReplacementAssessment from './RetirementReplacementAssessment'
import RetirementReceiptIntake from './RetirementReceiptIntake'
import './retirementReplacement.css'
import RetirementReceiptBinding from './RetirementReceiptBinding'
import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Row={id:string;bank_automatic:boolean|null;bank_attempts:{id:string;status:string;message:string;created_at:string}[];bank_claimed:boolean;bank_result:{status:string;settlementStatus?:string}|null;auto_process:boolean;file_automatic:boolean|null;file_attempts:{id:string;status:string;message:string;created_at:string}[];claimed:boolean;file_claimed:boolean;file_result:{status:string}|null;cancelled_at:string|null;cancellation_reference:string|null;preview:{fileName:string;amountCents:number;timing:{depositDate:string}}}
async function request(path:string,body?:unknown){const r=await adminApiRequest(path,body?{method:'POST',body:JSON.stringify(body)}:undefined),j=await r.json();if(!r.ok||!j.success)throw Object.assign(new Error(j.message||'Unable to retain replacement authorization.'),{status:r.status});return j.data}
function Cancel({id,onChanged}:{id:string;onChanged:()=>void}){
 const [reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const cancel=async()=>{setBusy(true);setError('');try{await request(`/api/admin/payroll/retirement-replacement-authorizations/${id}/cancel`,{confirmed:true,reference});onChanged()}catch(e){setError(e instanceof Error?e.message:'Retry cancellation with the original reason.')}finally{setBusy(false)}}
 return <fieldset disabled={busy} className="space-y-2">{error?<p role="alert">{error}</p>:null}<label className="block">Replacement cancellation reason<textarea className="block w-full rounded border p-2" maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm cancellation before replacement processing starts.</label><button type="button" disabled={!confirmed||reference.trim().length<20} onClick={()=>void cancel()} className="rounded border px-3 py-2">Cancel unstarted replacement</button></fieldset>
}
function Bank({row,onChanged}:{row:Row;onChanged:()=>void}){
 const [reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[uncertain,setUncertain]=useState(false)
 const recovery=row.bank_claimed||uncertain,ready=row.file_result?.status==='REMOTE_FILE_VERIFIED'
 useEffect(()=>setConfirmed(false),[row.bank_claimed,row.file_result?.status,row.bank_result?.status])
 const dispatch=async()=>{setBusy(true);setError('');try{await request(`/api/admin/payroll/retirement-replacement-authorizations/${row.id}/bank-dispatch`,{confirmed:true,action:recovery?'RECOVER':'SUBMIT',bankInstructionsReviewed:confirmed,outsideActivityReviewed:confirmed,reference});setUncertain(true);setConfirmed(false);onChanged()}catch(e){const status=e&&typeof e==='object'&&'status'in e?Number(e.status):0;if(!status||status>=500)setUncertain(true);setConfirmed(false);setError(e instanceof Error?e.message:'Recover the original replacement payment outcome.');onChanged()}finally{setBusy(false)}}
 return <fieldset disabled={busy} className="space-y-2 rounded border p-2"><legend>Replacement bank funding</legend><p>Bank payment: {row.bank_result?.status.replaceAll('_',' ')||'NOT STARTED'} · Settlement: {row.bank_result?.settlementStatus?.replaceAll('_',' ')||'UNVERIFIED'}</p><p>Bank settlement does not close participant receipts, accounting or the original return case.</p>{row.auto_process?<p>Automatic replacement funding is enabled after verified file delivery. Unresolved payments recheck after five minutes; matched bank settlements recheck daily.</p>:null}{row.bank_automatic?<p>Latest bank observation: automatic check</p>:null}{row.bank_attempts?.length?<details><summary>Automatic replacement bank attempts ({row.bank_attempts.length})</summary>{row.bank_attempts.map(attempt=><p key={attempt.id}>{new Date(attempt.created_at).toLocaleString()} · {attempt.status.replaceAll('_',' ')} · {attempt.message}</p>)}</details>:null}{error?<p role="alert">{error}</p>:null}{!recovery?<><label className="block">Replacement bank funding reference<textarea className="block w-full rounded border p-2" maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified separate replacement funding, no outside payment or provider debit, and authorize this bank payment.</label>{!ready?<p>Verify the delivered replacement allocation file before first funding.</p>:null}</>:null}<button type="button" disabled={!recovery&&(!ready||!confirmed||reference.trim().length<20)} onClick={()=>void dispatch()} className="rounded border px-3 py-2">{recovery?'Recover replacement bank payment':'Submit replacement bank payment'}</button></fieldset>
}
function Allocation({row,onChanged}:{row:Row;onChanged:()=>void}){
 const [reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[uncertain,setUncertain]=useState(false)
 const recovery=row.file_claimed||uncertain
 useEffect(()=>setConfirmed(false),[row.file_claimed,row.file_result?.status])
 const dispatch=async()=>{setBusy(true);setError('');try{await request(`/api/admin/payroll/retirement-replacement-authorizations/${row.id}/allocation-dispatch`,{confirmed:true,action:recovery?'RECOVER':'SUBMIT',outsideActivityReviewed:confirmed,reference});setUncertain(true);setConfirmed(false);onChanged()}catch(e){const status=e&&typeof e==='object'&&'status'in e?Number(e.status):0;if(!status||status>=500)setUncertain(true);setConfirmed(false);setError(e instanceof Error?e.message:'Recover the original file outcome before another action.');onChanged()}finally{setBusy(false)}}
 return <fieldset disabled={busy} className="space-y-2"><p>Allocation file: {row.file_result?.status.replaceAll('_',' ')||'NOT STARTED'}</p><p>File verification does not confirm participant credit or replacement funding.</p>{row.auto_process?<p>Automatic file processing is enabled. Eligible first uploads run on the next worker check; unresolved outcomes retry after five minutes and verified files recheck daily.</p>:null}{row.file_automatic?<p>Latest file observation: automatic check</p>:null}{row.file_attempts?.length?<details><summary>Automatic replacement file attempts ({row.file_attempts.length})</summary>{row.file_attempts.map(attempt=><p key={attempt.id}>{new Date(attempt.created_at).toLocaleString()} · {attempt.status.replaceAll('_',' ')} · {attempt.message}</p>)}</details>:null}{error?<p role="alert">{error}</p>:null}{!recovery?<><label className="block">Replacement allocation submission reference<textarea className="block w-full rounded border p-2" maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified that no outside replacement allocation was submitted and authorize this file upload.</label></>:null}<button type="button" disabled={!recovery&&(!confirmed||reference.trim().length<20)} onClick={()=>void dispatch()} className="rounded border px-3 py-2">{recovery?'Recover replacement allocation file':'Submit replacement allocation file'}</button></fieldset>
}
export default function RetirementReplacementAuthorizations({id,fingerprint,inputs,ready,onAuthorized,onLockChange}:{id:string;fingerprint:string|null;inputs:Record<string,unknown>;ready:boolean;onAuthorized:()=>void;onLockChange:(locked:boolean)=>void}){
 const path=`/api/admin/payroll/retirement-remittance-authorizations/${id}/replacement-authorizations`,[rows,setRows]=useState<Row[]|null>(null),[revision,setRevision]=useState(0),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[retry,setRetry]=useState(false),[error,setError]=useState(''),[readError,setReadError]=useState(''),pending=useRef<Record<string,unknown>|null>(null)
 useEffect(()=>{onLockChange(busy||retry)},[busy,retry,onLockChange])
 useEffect(()=>setConfirmed(false),[fingerprint,ready])
 useEffect(()=>{let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const data=await request(path);if(live){setRows(data.history);setReadError('')}}catch(e){if(live){setRows(null);setReadError(e instanceof Error?e.message:'Unable to read replacement history.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[path,revision])
 const authorize=async()=>{setBusy(true);setError('');try{if(!pending.current){if(!fingerprint||!confirmed||!ready)throw new Error('Verify current replacement instructions before authorization.');pending.current={fingerprint,inputs,confirmed:true,autoProcess:true,requestKey:crypto.randomUUID()}}await request(path,pending.current);pending.current=null;setRetry(false);setConfirmed(false);setRevision(n=>n+1);onAuthorized()}catch(e){if(e&&typeof e==='object'&&'status'in e&&Number(e.status)>=400&&Number(e.status)<500){pending.current=null;setConfirmed(false);onAuthorized()}setRetry(!!pending.current);setError(e instanceof Error?e.message:'Retry the original replacement approval.')}finally{setBusy(false)}}
 return <section aria-label={`Replacement authorization history ${id}`} className="payroll-replacement space-y-2 rounded border p-3"><h5 className="font-bold">Replacement authorization and history</h5><p>Authorization reserves this replacement. Review processing evidence before assuming that a file or funds were sent.</p><button type="button" className="rounded border px-3 py-2" onClick={()=>setRevision(n=>n+1)}>Refresh replacement history</button>{readError?<p role="alert">{readError} Automatic refresh will retry.</p>:null}{error?<p role="alert">{error}</p>:null}{fingerprint&&ready&&rows&&!rows.some(r=>!r.cancelled_at)?<fieldset disabled={busy||retry} className="space-y-2"><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I authorize automatic allocation-file delivery and replacement funding under these verified instructions.</label><button type="button" disabled={!confirmed} onClick={()=>void authorize()} className="rounded border px-3 py-2">Authorize replacement contribution</button></fieldset>:null}{retry?<button type="button" disabled={busy} onClick={()=>void authorize()} className="rounded border px-3 py-2">Retry original replacement authorization</button>:null}{rows?.map(row=><article key={row.id} className="space-y-2 rounded border p-2"><p>{row.cancelled_at?'CANCELLED':row.claimed?'PROCESSING CLAIMED':'AUTHORIZED — NOT STARTED'}</p><p className="break-words">{row.preview.fileName} · Deposit {row.preview.timing.depositDate}</p>{row.cancellation_reference?<p>Cancellation: {row.cancellation_reference}</p>:null}{!row.cancelled_at?<><RetirementReplacementAssessment key={row.id} id={row.id}/><RetirementReplacementSettlement key={`settlement-${row.id}`} id={row.id}/><Allocation row={row} onChanged={()=>setRevision(n=>n+1)}/><Bank row={row} onChanged={()=>setRevision(n=>n+1)}/>{row.file_claimed?<><RetirementReceiptBinding id={row.id} path={`/api/admin/payroll/retirement-replacement-authorizations/${row.id}/receipt-binding`}/><RetirementReceiptIntake id={row.id} path={`/api/admin/payroll/retirement-replacement-authorizations/${row.id}/receipts`}/></>:null}</>:null}{!row.cancelled_at&&!row.claimed?<Cancel id={row.id} onChanged={()=>setRevision(n=>n+1)}/>:null}</article>)}</section>
}
