import RetirementReceiptIntake from './RetirementReceiptIntake'
import RetirementReceiptBinding from './RetirementReceiptBinding'
import RetirementAllocationUnsentRelease from './RetirementAllocationUnsentRelease'
import RetirementDispatchSchedule from './RetirementDispatchSchedule'
import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Destination={host:string;port:number;deliveryDirectory:string}
type Row={unsent_release?:{id:string;reference:string;createdAt:string}|null;id:string;file_name:string;configuration_id:string;reference:string;claimed:boolean;cancelled:boolean;display_configuration:Destination;result:{status:string;recordkeeperAcceptance:string;automatic?:boolean;observedAt?:string;source?:string}|null}
type Data={configurationId:string|null;setupStatus:string;destination:Destination|null;parentCancelled:boolean;amountCents:number;history:Row[]}
async function request(path:string,body?:unknown){const r=await adminApiRequest(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),j=await r.json();if(!r.ok||!j.success)throw Object.assign(new Error(j.message||'Unable to review allocation delivery.'),{status:r.status});return j.data}
function DeliveryAction({path,row,onChanged}:{path:string;row:Row;onChanged:()=>void}){
 const [reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[outside,setOutside]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),pendingCancel=useRef<Record<string,unknown>|null>(null)
 const run=async(action:'CANCEL'|'SUBMIT'|'RECOVER')=>{setBusy(true);setError('');try{
  if(action==='CANCEL'){if(!pendingCancel.current)pendingCancel.current={reference,confirmed,requestKey:crypto.randomUUID()};await request(`${path}/${row.id}/cancel`,pendingCancel.current);pendingCancel.current=null}
  else await request(`${path}/${row.id}/dispatch`,{action,confirmed:true,reference,outsideActivityReviewed:outside})
 }catch(e){if(e&&typeof e==='object'&&'status'in e&&Number(e.status)>=400&&Number(e.status)<500)pendingCancel.current=null;setError(e instanceof Error?e.message:'Allocation outcome requires review.')}finally{setBusy(false);onChanged()}}
 return <div className="space-y-2">{error?<p role="alert">{error}</p>:null}{row.claimed?<><p>A delivery claim is retained. Recovery reads the original destination without uploading again. A missing file may already have been consumed by the recordkeeper.</p><button type="button" disabled={busy} onClick={()=>void run('RECOVER')} className="rounded border px-3 py-2">Recover allocation file delivery</button><RetirementAllocationUnsentRelease path={`${path}/${row.id}/release-unsent`} onChanged={onChanged}/></>:<><label className="block">Allocation delivery action reference<textarea disabled={busy||!!pendingCancel.current} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false);setOutside(false)}} maxLength={2000} className="block w-full rounded border p-2"/></label><label className="flex gap-2"><input type="checkbox" disabled={busy||!!pendingCancel.current} checked={outside} onChange={e=>setOutside(e.target.checked)}/>I rechecked that no external or duplicate allocation submission is pending for these deductions.</label><label className="flex gap-2"><input type="checkbox" disabled={busy||!!pendingCancel.current} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm the displayed allocation file action and reviewed evidence.</label><div className="flex flex-wrap gap-2"><button type="button" disabled={busy||!!pendingCancel.current||!confirmed||!outside||reference.trim().length<20} onClick={()=>void run('SUBMIT')} className="rounded border px-3 py-2">Submit authorized allocation file</button><button type="button" disabled={busy||!pendingCancel.current&&(!confirmed||reference.trim().length<20)} onClick={()=>void run('CANCEL')} className="rounded border px-3 py-2">{pendingCancel.current?'Retry allocation cancellation':'Cancel unsubmitted allocation file'}</button></div></>}<RetirementDispatchSchedule kind="FILE" targetId={row.id} onChanged={onChanged}/></div>
}
export default function RetirementAllocationDelivery({remittanceId,onChanged}:{remittanceId:string;onChanged:()=>void}){
 const path=`/api/admin/payroll/retirement-remittance-authorizations/${remittanceId}/allocation-delivery`
 const [requested,setRequested]=useState(false),[data,setData]=useState<Data|null>(null),[fileName,setFileName]=useState(`retirement_${remittanceId}.csv`),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[outside,setOutside]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[readError,setReadError]=useState(''),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0),pending=useRef<Record<string,unknown>|null>(null)
 useEffect(()=>{if(!requested)return;let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const j=await request(path);if(live){setData(j);setReadError('')}}catch(e){if(live){setData(null);setReadError(e instanceof Error?e.message:'Unable to load allocation history.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[path,requested,refresh])
 useEffect(()=>{setConfirmed(false);setOutside(false)},[data?.configurationId,data?.setupStatus])
 const changed=()=>{setRefresh(n=>n+1);onChanged()}
 const authorize=async(retry=false)=>{setBusy(true);setError('');try{
  if(!retry){if(!data||!confirmed||!outside)throw new Error('Review current allocation delivery evidence.');pending.current={configurationId:data.configurationId,fileName,reference,confirmed:true,outsideActivityReviewed:true,requestKey:crypto.randomUUID()}}
  await request(path,pending.current);pending.current=null;setConfirmed(false);setOutside(false);setMessage('Allocation authorization retained. Review history before submission.');changed()
 }catch(e){if(e&&typeof e==='object'&&'status'in e&&Number(e.status)>=400&&Number(e.status)<500)pending.current=null;setError(e instanceof Error?e.message:'Unable to authorize allocation delivery.')}finally{setBusy(false)}}
 const active=data?.history.some(row=>!row.cancelled)
 return <section aria-label={`Allocation file delivery ${remittanceId}`} className="space-y-3 border-t pt-3"><h6 className="font-bold">Recordkeeper allocation file</h6><p>Deliver the exact retained allocation separately from its bank payment. Remote file verification is not recordkeeper acceptance or participant posting. Claimed deliveries are checked automatically every five minutes while unresolved and daily after exact remote-file verification.</p><button type="button" disabled={busy} onClick={()=>{setRequested(true);setRefresh(n=>n+1)}} className="rounded border px-3 py-2">Load allocation delivery history</button>
 {readError?<p role="alert">{readError}</p>:null}{error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}
 {data?.parentCancelled?<p>The contribution authorization is cancelled. No new file can be submitted.</p>:data&&!active?<><p>Delivery setup: {data.setupStatus.replaceAll('_',' ')}</p>{data.destination?<p className="break-all">{data.destination.host}:{data.destination.port}{data.destination.deliveryDirectory}</p>:null}<p>Review the exact filename with the recordkeeper. A filename already retained for this employer cannot be reused for a different authorization.</p><fieldset disabled={busy||!!pending.current||data.setupStatus!=='VERIFIED'} className="space-y-2"><label className="block">Recordkeeper allocation filename<input value={fileName} onChange={e=>{setFileName(e.target.value);setConfirmed(false);setOutside(false)}} maxLength={124} className="block w-full rounded border p-2"/></label><label className="block">Allocation filename and delivery authorization reference<textarea value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false);setOutside(false)}} maxLength={2000} className="block w-full rounded border p-2"/></label><label className="flex gap-2"><input type="checkbox" checked={outside} onChange={e=>setOutside(e.target.checked)}/>I verified no external allocation file or duplicate instruction exists for these exact deductions.</label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I authorize the retained allocation bytes, reviewed filename and displayed SFTP destination.</label><button type="button" disabled={!confirmed||!outside||reference.trim().length<20} onClick={()=>void authorize()} className="rounded border px-3 py-2">Authorize allocation file delivery</button></fieldset></>:null}
 {pending.current?<button type="button" disabled={busy} onClick={()=>void authorize(true)} className="rounded border px-3 py-2">Retry original allocation authorization</button>:null}
 {data?.history.map(row=><article key={row.id} aria-label={`Allocation delivery ${row.id}`} className="space-y-2 rounded border p-3"><p className="break-all font-bold">{row.file_name} · {row.cancelled?'CANCELLED':row.claimed?'CLAIMED':'AUTHORIZED NOT SENT'}</p><p className="break-all">{row.display_configuration.host}:{row.display_configuration.port}{row.display_configuration.deliveryDirectory}</p><p>{row.reference}</p>{row.unsent_release?<p>Verified unsent release · {new Date(row.unsent_release.createdAt).toLocaleString()} · {row.unsent_release.reference}</p>:null}{row.result?<><p>File outcome: {row.result.status.replaceAll('_',' ')}</p><p>{row.result.automatic?(row.result.source==='SUBMISSION'?'Automatic submission':'Automatic check'):'Admin check'}{row.result.observedAt?` · ${new Date(row.result.observedAt).toLocaleString()}`:''}</p></>:null}<p>Review receipt outcomes to establish provider acceptance and participant posting.</p>{row.claimed?<><RetirementReceiptBinding path={`${path}/${row.id}/receipt-binding`} id={row.id}/><RetirementReceiptIntake path={`${path}/${row.id}/receipts`} id={row.id}/></>:null}{!row.cancelled&&!data.parentCancelled?<DeliveryAction path={path} row={row} onChanged={changed}/>:null}</article>)}
 </section>
}
