import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Summary={status:string;decision:string;authorizedCents?:number;reportedCents?:number;postedCents?:number;rejectedCents?:number;participantCount?:number;reversedAllocationCents?:number}
type Row={automatic:boolean;id:string;binding_id:string;summary:Summary;created_at:string}
type Data={bindingStatus:string;bindingId:string|null;history:Row[]}
async function request(path:string,body?:unknown){const r=await adminApiRequest(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),j=await r.json();if(!r.ok||!j.success)throw Object.assign(new Error(j.message||'Unable to load receipt outcomes.'),{status:r.status});return j.data}
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100)
export default function RetirementReceiptIntake({path,id}:{path:string;id:string}){
 const [requested,setRequested]=useState(false),[data,setData]=useState<Data|null>(null),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[readError,setReadError]=useState(''),[message,setMessage]=useState(''),pending=useRef<Record<string,unknown>|null>(null)
 useEffect(()=>{if(!requested)return;let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const next=await request(path);if(live){setData(next);setReadError('')}}catch(e){if(live){setData(null);setReadError(e instanceof Error?e.message:'Unable to read receipt history.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[path,requested,refresh])
 useEffect(()=>setConfirmed(false),[data?.bindingId,data?.bindingStatus])
 const check=async()=>{setBusy(true);setError('');try{if(!pending.current){if(!confirmed||data?.bindingStatus!=='BOUND'||!data.bindingId)throw new Error('Review the current receipt location before checking.');pending.current={bindingId:data.bindingId,requestKey:crypto.randomUUID(),confirmed:true}}await request(path,pending.current);pending.current=null;setConfirmed(false);setMessage('Receipt check retained.');setRefresh(n=>n+1)}catch(e){if(e&&typeof e==='object'&&'status'in e&&Number(e.status)>=400&&Number(e.status)<500)pending.current=null;setError(e instanceof Error?e.message:'Retry the original receipt check.')}finally{setBusy(false)}}
 return <section aria-label={`Retirement receipt outcomes ${id}`} className="space-y-2 rounded border p-3"><p className="font-bold">Recordkeeper receipt outcomes</p><p>Check the reviewed receipt location for provider acceptance and participant posting. Bank settlement and full contribution reconciliation require separate evidence. Reviewed locations are checked automatically every five minutes while unresolved and daily after full posting.</p><button type="button" disabled={busy} onClick={()=>{setRequested(true);setRefresh(n=>n+1)}} className="rounded border px-3 py-2">Load receipt outcome history</button>{readError?<p role="alert">{readError}</p>:null}{error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}{data?<><p>Current receipt location: {data.bindingStatus.replaceAll('_',' ')}</p>{data.bindingStatus!=='BOUND'?<p>Review the receipt location before checking. Retained outcomes below are historical evidence.</p>:null}<fieldset disabled={busy||!!pending.current||data.bindingStatus!=='BOUND'} className="space-y-2"><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm retrieval from the reviewed receipt location.</label><button type="button" disabled={!confirmed} onClick={()=>void check()} className="rounded border px-3 py-2">Check recordkeeper receipt</button></fieldset>{!data.history.length?<p>No receipt checks retained. Provider acceptance and participant posting remain unverified.</p>:null}{data.history.map((row,index)=><article key={row.id} className="space-y-1 rounded border p-2"><p>{index===0?'Latest retained receipt':'Earlier receipt'}: {row.summary.status.replaceAll('_',' ')}</p><p>{row.automatic?'Automatic check':'Admin check'} · {new Date(row.created_at).toLocaleString()}</p>{row.binding_id!==data.bindingId?<p>Uses an earlier receipt location revision.</p>:null}{row.summary.decision==='RECONCILED'?<p>Provider-reported amounts: authorized {money(row.summary.authorizedCents||0)} · reported {money(row.summary.reportedCents||0)} · posted {money(row.summary.postedCents||0)} · rejected {money(row.summary.rejectedCents||0)} · participants {row.summary.participantCount}</p>:<p>This check does not establish current participant posting. Review the receipt evidence before resolving the contribution.</p>}{row.summary.decision==='RECONCILED'&&row.summary.reversedAllocationCents!==undefined?<p>Provider-reported reversed allocations: {money(row.summary.reversedAllocationCents)}. Replacement funding remains separate.</p>:null}</article>)}</>:null}{pending.current?<button type="button" disabled={busy} onClick={()=>void check()} className="rounded border px-3 py-2">Retry original receipt check</button>:null}</section>
}
