import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Policy={effectiveOn:string;disposition:string;reference:string;depositBusinessDays?:number;providerLeadBusinessDays?:number;cutoffTime?:string}
type Row={id:string;revision:number;policy:Policy;currentPlan:boolean}
type Data={planRevisionId:string;history:Row[]}
export default function RetirementTiming({planId}:{planId:string}){
 const path=`/api/admin/payroll/retirement-plans/${encodeURIComponent(planId)}/timing`
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState({effectiveOn:'',disposition:'REVIEWED',depositBusinessDays:'',providerLeadBusinessDays:'',cutoffTime:'',reference:''}),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0),pending=useRef<Record<string,unknown>|null>(null)
 const currentRevision=data?.history[0]?.revision||0
 useEffect(()=>{let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const r=await adminApiRequest(path),j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Unable to load contribution timing.');if(live){setData(j.data);setError('')}}catch(e){if(live){setData(null);setError(e instanceof Error?e.message:'Unable to load contribution timing.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[path,refresh])
 useEffect(()=>{setConfirmed(false)},[data?.planRevisionId,currentRevision])
 const save=async(retry=false)=>{setBusy(true);setError('');try{
  if(!retry){if(!data||!confirmed)throw new Error('Review and confirm current timing evidence.');pending.current={planRevisionId:data.planRevisionId,expectedRevision:currentRevision,requestKey:crypto.randomUUID(),policy:{...form,depositBusinessDays:form.depositBusinessDays===''?null:Number(form.depositBusinessDays),providerLeadBusinessDays:form.providerLeadBusinessDays===''?null:Number(form.providerLeadBusinessDays),confirmed:true,earliestConfirmed:true,calendarConfirmed:true}}}
  const r=await adminApiRequest(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(pending.current)}),j=await r.json();if(!r.ok||!j.success)throw Object.assign(new Error(j.message||'Unable to retain timing review.'),{status:r.status})
  pending.current=null;setConfirmed(false);setMessage('Contribution timing review retained. Dates refresh automatically; delivery remains unverified.');setRefresh(n=>n+1)
 }catch(e){if(e&&typeof e==='object'&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500)pending.current=null;setError(e instanceof Error?e.message:'Unable to retain timing review.')}finally{setBusy(false)}}
 return <section aria-label={`Retirement contribution timing ${planId}`} className="space-y-3 rounded-xl border p-4"><h4 className="font-bold">Contribution timing · {planId}</h4><p>Record the actual earliest reasonably segregable deposit timing and provider lead time. Seven business days is not a universal deadline. This calendar creates operational targets, not proof of legal compliance or deposit.</p><p>Business days use the Federal Reserve bank calendar; cutoff times use America/New_York. Confirm these match the employer and provider. Special closures and unsupported timing require separate review.</p>
 {error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}
 <form className="space-y-3" onSubmit={e=>{e.preventDefault();void save()}} onChange={()=>{setConfirmed(false);setMessage('')}}>
 <fieldset className="space-y-3" disabled={!data||busy||!!pending.current}>
 <label className="block">Timing applies to withholding from<input type="date" required value={form.effectiveOn} onChange={e=>setForm({...form,effectiveOn:e.target.value})} className="block w-full rounded border p-2"/></label>
 <label className="block">Timing disposition<select value={form.disposition} onChange={e=>setForm({...form,disposition:e.target.value})} className="block w-full rounded border p-2"><option value="REVIEWED">Reviewed timing</option><option value="SUSPENDED">Suspend timing reliance</option></select></label>
 {form.disposition==='REVIEWED'?<>{([['depositBusinessDays','Bank business days from withholding to earliest deposit'],['providerLeadBusinessDays','Provider bank business days before deposit']] as const).map(([key,label])=><label key={key} className="block">{label}<input type="number" required min="0" max="10" step="1" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="block w-full rounded border p-2"/></label>)}<label className="block">Provider submission cutoff (New York time)<input type="time" required value={form.cutoffTime} onChange={e=>setForm({...form,cutoffTime:e.target.value})} className="block w-full rounded border p-2"/></label></>:null}
 <label className="block">Employer capacity and provider timing evidence<textarea required minLength={20} maxLength={2000} value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} className="block w-full rounded border p-2"/></label>
 </fieldset>
 <label className="flex gap-2"><input type="checkbox" disabled={!data||busy||!!pending.current} checked={confirmed} onChange={e=>{e.stopPropagation();setConfirmed(e.target.checked)}}/>I reviewed actual segregation capacity, provider receipt lead time and calendar applicability, or the reason to suspend reliance.</label>
 <button disabled={!confirmed||busy||!!pending.current} className="rounded border px-3 py-2">Retain contribution timing</button></form>
 {pending.current?<button type="button" disabled={busy} onClick={()=>void save(true)} className="rounded border px-3 py-2">Retry original timing review</button>:null}
 {data?.history.map(row=><article key={row.id} className="space-y-1 rounded border p-3"><p className="font-bold">Timing revision {row.revision} · {row.policy.disposition}{!row.currentPlan?' · Plan changed':''}</p><p>Withholding from {row.policy.effectiveOn}</p>{row.policy.disposition==='REVIEWED'?<p>Deposit: {row.policy.depositBusinessDays} bank business days after withholding. Submit {row.policy.providerLeadBusinessDays} bank business days earlier by {row.policy.cutoffTime} America/New_York.</p>:null}<p className="whitespace-pre-wrap break-words">{row.policy.reference}</p></article>)}
 </section>
}
