import RetirementReturnAccounting from './RetirementReturnAccounting'
import RetirementBankUnsentRelease from './RetirementBankUnsentRelease'
import RetirementDispatchSchedule from './RetirementDispatchSchedule'
import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
export default function RetirementBankDispatch({id,claimed,result,onChanged}:{id:string;claimed:boolean;result:{status:string;returnEvidenceStatus?:string;returnEvidence?:{amountCents:number;postedDate:string;code:string|null}|null;settlementStatus?:string;dateMatches?:boolean}|null;onChanged:()=>void}){
 const [reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[outside,setOutside]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const act=async()=>{setBusy(true);setError('');try{const r=await adminApiRequest(`/api/admin/payroll/retirement-remittance-authorizations/${id}/dispatch`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:claimed?'RECOVER':'SUBMIT',confirmed:true,bankInstructionsReviewed:confirmed,outsideActivityReviewed:outside,reference})}),j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Bank outcome requires recovery.');setConfirmed(false);setOutside(false)}catch(e){setError(e instanceof Error?e.message:'Bank outcome requires recovery.')}finally{setBusy(false);onChanged()}}
 return <section aria-label={`Retirement bank payment ${id}`} className="space-y-3 border-t pt-3"><h6 className="font-bold">Bank payment</h6>{result?<p>Provider status: {result.status.replaceAll('_',' ')} · Bank settlement: {result.settlementStatus?.replaceAll('_',' ')||'UNVERIFIED'}</p>:null}{result?.status==='RETURNED'?<div className="rounded border p-2"><p>Returned funds: {result.returnEvidenceStatus?.replaceAll('_',' ')||'UNVERIFIED'}</p>{result.returnEvidenceStatus==='BANK_CREDIT_POSTED'&&result.returnEvidence?<p>Verified bank credit: {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(result.returnEvidence.amountCents/100)} · Posted {result.returnEvidence.postedDate}{result.returnEvidence.code?` · ${result.returnEvidence.code}`:''}</p>:null}<p>Returned funds require accounting and contribution resolution before any replacement.</p></div>:null}{result?.dateMatches===false?<p role="alert">The provider effective date differs from the authorized date. Review the bank instruction.</p>:null}<p>Bank payment does not submit the allocation file or prove recordkeeper receipt. Review contribution reconciliation for recordkeeper and participant evidence.</p>{error?<p role="alert">{error}</p>:null}
 {!claimed?<><label className="block">Trustee bank-credit and allocation workflow reference<textarea disabled={busy} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false);setOutside(false)}} maxLength={2000} className="block w-full rounded border p-2"/></label><label className="flex gap-2"><input type="checkbox" disabled={busy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified that this plan accepts an employer-originated ACH CCD credit without additional addenda, and that separate allocation handling will not trigger another debit. I reviewed the allocation delivery requirements.</label><label className="flex gap-2"><input type="checkbox" disabled={busy} checked={outside} onChange={e=>setOutside(e.target.checked)}/>I rechecked that no outside payment, pending funds instruction or duplicate allocation submission exists for these deductions.</label><button type="button" disabled={busy||!confirmed||!outside||reference.trim().length<20} onClick={()=>void act()} className="rounded border px-3 py-2">Submit authorized retirement bank payment</button></>:<><p>Dispatch processing has started. Recovery checks the existing instruction and never submits a replacement. Automatic checks run every five minutes, or daily after matching bank settlement.</p><button type="button" disabled={busy} onClick={()=>void act()} className="rounded border px-3 py-2">Recover retirement bank payment</button><RetirementBankUnsentRelease path={`/api/admin/payroll/retirement-remittance-authorizations/${id}/release-unsent`} onChanged={onChanged}/></>}
 {claimed?<RetirementReturnAccounting key={id} id={id} evidenceKey={JSON.stringify(result)}/>:null}
 <RetirementDispatchSchedule kind="BANK" targetId={id} onChanged={onChanged}/>
 </section>
}
