import RetirementReplacementPreview from './RetirementReplacementPreview'
import RetirementContributionHistory from './RetirementContributionHistory'
import RetirementSettlementPreview from './RetirementSettlementPreview'
import {useEffect,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Data={status:string;payrollStatus:string;bankStatus:string;receiptStatus:string;accountingStatus:string;returnAccountingStatus:string;reversedAllocationCents:number|null;replacementReviewStatus:string;returnReviewRequired:boolean;amountCents:number;postedCents:number|null;bankCheckedAt:string|null;receiptCheckedAt:string|null;issues:string[]}
export default function RetirementContributionAssessment({id}:{id:string}){
 const [requested,setRequested]=useState(false),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0)
 useEffect(()=>{if(!requested)return;let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const r=await adminApiRequest(`/api/admin/payroll/retirement-remittance-authorizations/${id}/assessment`),j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Unable to assess contribution.');if(live){setData(j.data);setError('')}}catch(e){if(live){setData(null);setError(e instanceof Error?e.message:'Unable to assess contribution.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[id,requested,refresh])
 return <section aria-label={`Contribution reconciliation ${id}`} className="space-y-2 rounded border p-3"><p className="font-bold">Contribution reconciliation</p><p>Compare retained payroll, bank withdrawal and participant posting evidence. Reconciliation requires matching delivery and accounting evidence.</p><button type="button" onClick={()=>{setRequested(true);setRefresh(n=>n+1)}} className="rounded border px-3 py-2">Review contribution reconciliation</button>{error?<p role="alert">{error} Automatic refresh will retry.</p>:null}{data?<><p>Assessment: {data.status.replaceAll('_',' ')}</p><p>Payroll: {data.payrollStatus.replaceAll('_',' ')} · Bank: {data.bankStatus.replaceAll('_',' ')} · Participants: {data.receiptStatus.replaceAll('_',' ')}</p><p>Settlement accounting: {data.accountingStatus.replaceAll('_',' ')}</p>{data.returnAccountingStatus!=='NOT_REQUIRED'?<p>Returned-credit accounting: {data.returnAccountingStatus.replaceAll('_',' ')}</p>:null}{data.reversedAllocationCents!==null?<p>Confirmed reversed allocations: {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(data.reversedAllocationCents/100)}</p>:null}{data.replacementReviewStatus!=='NOT_APPLICABLE'?<p>Replacement review: {data.replacementReviewStatus.replaceAll('_',' ')}. A separate approval and reviewed recordkeeper instructions are required before sending new funds.</p>:null}{data.bankCheckedAt?<p>Bank checked: {new Date(data.bankCheckedAt).toLocaleString()}</p>:null}{data.receiptCheckedAt?<p>Receipt checked: {new Date(data.receiptCheckedAt).toLocaleString()}</p>:null}<ul className="list-disc space-y-1 pl-5">{data.issues.map(issue=><li key={issue}>{issue}</li>)}</ul></>:null}{requested?<RetirementContributionHistory key={id} id={id}/>:null}<RetirementReplacementPreview id={id} needed={!!data?.returnReviewRequired} ready={data?.replacementReviewStatus==='EVIDENCE_READY'} evidenceKey={JSON.stringify(data)}/><RetirementSettlementPreview id={id}/></section>
}
