import RetirementDestinationSuspension from './RetirementDestinationSuspension'
import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Account={holderName:string;accountType:string;accountLast4:string;mode:string}
type History={suspension:{id:string;reference:string}|null;id:string;revision:number;current:boolean;planCurrent:boolean;connectionCurrent:boolean;masked_destination:Account;reference:string;verification:{status:string;createdAt:string;automatic:boolean}|null}
type Data={planRevisionId:string;planName:string;providerName:string;connectionRevision:number;vaultReady:boolean;history:History[]}
type Preview={fingerprint:string;previousId:string|null;account:Account}
export default function RetirementDestination({planId}:{planId:string}){
 const path=`/api/admin/payroll/retirement-plans/${encodeURIComponent(planId)}/destination`
 const [data,setData]=useState<Data|null>(null),[accountId,setAccountId]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0)
 const pending=useRef<Record<string,unknown>|null>(null)
 const request=async(url:string,body?:unknown)=>{const r=await adminApiRequest(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),j=await r.json();if(!r.ok||!j.success)throw Object.assign(new Error(j.message||'Unable to review retirement destination.'),{status:r.status});return j.data}
 useEffect(()=>{let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const r=await adminApiRequest(path),j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Unable to load retirement destination.');if(live){setData(j.data);setError('')}}catch(e){if(live){setData(null);setError(e instanceof Error?e.message:'Unable to load retirement destination.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[path,refresh])
 const currentDestinationId=data?.history[0]?.id,currentSuspensionId=data?.history[0]?.suspension?.id
 useEffect(()=>{setPreview(null);setConfirmed(false)},[data?.planRevisionId,data?.connectionRevision,currentDestinationId,currentSuspensionId])
 const save=async(retry=false)=>{setBusy(true);setError('');try{
  if(!retry){if(!data||!preview||!confirmed)throw new Error('Preview and confirm current destination details.');pending.current={accountId,planRevisionId:data.planRevisionId,connectionRevision:data.connectionRevision,previousId:preview.previousId,fingerprint:preview.fingerprint,reference,confirmed:true,requestKey:crypto.randomUUID()}}
  await request(path,pending.current);pending.current=null;setPreview(null);setConfirmed(false);setMessage('Retirement destination review saved. No contribution was transmitted.');setRefresh(n=>n+1)
 }catch(e){if(e&&typeof e==='object'&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500)pending.current=null;setError(e instanceof Error?e.message:'Unable to save retirement destination.')}finally{setBusy(false)}}
 return <section aria-label={`Retirement remittance destination ${planId}`} className="space-y-3 rounded-xl border p-4">
  <h4 className="font-bold">Retirement remittance destination · {data?.planName||planId}</h4>
  <p>Review the trustee or authorized collection account for this plan. Account verification does not confirm participant enrollment, allocation instructions or contribution delivery.</p>
  {error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}
  {data?<><p>Recordkeeper: {data.providerName}</p><p>Verified destinations are checked daily. Unavailable or changed accounts and setup changes are checked every five minutes. Suspended destinations remain stopped.</p>{!data.connectionRevision?<p>Configure the employer payment connection before previewing a destination.</p>:null}{!data.vaultReady?<p>Encrypted document storage must be configured before saving destination details.</p>:null}
  <form aria-label={`Review retirement destination ${planId}`} className="space-y-3" onChange={()=>{setPreview(null);setConfirmed(false);setMessage('')}} onSubmit={e=>{e.preventDefault();void save()}}>
   <fieldset disabled={busy||!!pending.current} className="space-y-3">
    <label className="block font-bold">Provider business account identifier<input required value={accountId} onChange={e=>setAccountId(e.target.value)} className="mt-1 block w-full rounded border p-2"/></label>
    <button type="button" disabled={!data.connectionRevision||!accountId} className="rounded border px-3 py-2" onClick={async()=>{setBusy(true);setError('');setPreview(null);try{setPreview(await request(`${path}/preview`,{accountId,planRevisionId:data.planRevisionId,connectionRevision:data.connectionRevision}))}catch(e){setError(e instanceof Error?e.message:'Unable to preview destination.')}finally{setBusy(false)}}}>Preview retirement destination</button>
   </fieldset>
  </form>
  {preview?<div className="space-y-3 rounded border p-3"><p>{preview.account.holderName} · {preview.account.accountType} ending {preview.account.accountLast4} · {preview.account.mode}</p><label className="block font-bold">Trustee payment-instruction reference<input minLength={20} maxLength={2000} disabled={busy||!!pending.current} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} className="mt-1 block w-full rounded border p-2"/></label><label className="flex gap-2"><input type="checkbox" disabled={busy||!!pending.current} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I independently verified that this destination is authorized to receive this plan’s contributions using trustee-issued instructions.</label><button type="button" disabled={busy||!!pending.current||!confirmed||reference.trim().length<20||!data.vaultReady} onClick={()=>void save()} className="rounded border px-3 py-2">Save retirement destination review</button></div>:null}
  {data.history.map(row=><article key={row.id} className="space-y-2 rounded border p-3"><h5 className="font-bold">Destination revision {row.revision}{row.current?' · Current':''}</h5><p>{row.masked_destination.holderName} · ending {row.masked_destination.accountLast4} · {row.masked_destination.mode}</p><p>{row.suspension?'Destination suspended':!row.planCurrent?'Plan changed — review destination again':!row.connectionCurrent?'Funding connection changed — review destination again':`Last ${row.verification?.automatic?'automatic account':'account'} check: ${row.verification?.status||'UNVERIFIED'}`}</p><p className="break-words">{row.reference}</p>{row.verification?<p>Checked {new Date(row.verification.createdAt).toLocaleString()}</p>:null}{row.current&&!row.suspension?<button type="button" disabled={busy} className="rounded border px-3 py-2" onClick={async()=>{setBusy(true);setError('');try{const check=await request(`${path}/${row.id}/verify`,{});setPreview(null);setConfirmed(false);setMessage(`Destination account check: ${check.status}`);setRefresh(n=>n+1)}catch(e){setError(e instanceof Error?e.message:'Unable to recheck destination.')}finally{setBusy(false)}}}>Recheck retirement destination</button>:null}{row.current?<RetirementDestinationSuspension path={`${path}/${row.id}`} suspension={row.suspension} onChanged={()=>{setPreview(null);setConfirmed(false);setRefresh(n=>n+1)}}/>:row.suspension?<p>{row.suspension.reference}</p>:null}</article>)}
  </>:null}
  {pending.current?<button type="button" disabled={busy} className="rounded border px-3 py-2" onClick={()=>void save(true)}>Retry original destination review</button>:null}
 </section>
}
