import RetirementContributionAssessment from './RetirementContributionAssessment'
import RetirementAllocationDelivery from './RetirementAllocationDelivery'
import RetirementBankDispatch from './RetirementBankDispatch'
import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Preview={authorizationWindowOpen:boolean;fingerprint:string;amountCents:number;planName:string;withheldDate:string;destination:{holderName:string;accountLast4:string};timing:{depositDate?:string;submissionAt?:string;status:string}}
type Authorization={bank_unsent_release?:{id:string;reference:string;createdAt:string}|null;allocation_claimed:boolean;bank_result:{status:string;returnEvidenceStatus?:string;returnEvidence?:{amountCents:number;postedDate:string;code:string|null}|null;settlementStatus?:string;dateMatches?:boolean}|null;id:string;plan_id:string;amount_cents:number;sourceCurrent:boolean;status:string;claimed:boolean;cancelled_at:string|null;cancellation_reference:string|null;reference:string;basis:Preview}
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100)
async function request(path:string,body?:unknown){const r=await adminApiRequest(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),j=await r.json();if(!r.ok||!j.success)throw Object.assign(new Error(j.message||'Unable to review retirement remittance authorization.'),{status:r.status});return j.data}
function Cancellation({id,onChanged}:{id:string;onChanged:()=>void}){
 const [reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),pending=useRef<Record<string,unknown>|null>(null)
 const cancel=async()=>{setBusy(true);setError('');try{if(!pending.current)pending.current={reference,confirmed,requestKey:crypto.randomUUID()};await request(`/api/admin/payroll/retirement-remittance-authorizations/${id}/cancel`,pending.current);pending.current=null;onChanged()}catch(e){if(e&&typeof e==='object'&&'status'in e&&Number(e.status)>=400&&Number(e.status)<500)pending.current=null;setError(e instanceof Error?e.message:'Unable to cancel remittance.')}finally{setBusy(false)}}
 return <div className="space-y-2"><p>Cancellation releases this internal reservation. It cannot recall an instruction already claimed for dispatch.</p>{error?<p role="alert">{error}</p>:null}<label className="block">Remittance cancellation reference<textarea disabled={busy||!!pending.current} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} className="block w-full rounded border p-2"/></label><label className="flex gap-2"><input type="checkbox" disabled={busy||!!pending.current} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed cancellation of this unsubmitted contribution authorization.</label><button type="button" disabled={busy||(!pending.current&&(!confirmed||reference.trim().length<20))} onClick={()=>void cancel()} className="rounded border px-3 py-2">{pending.current?'Retry original remittance cancellation':'Cancel remittance authorization'}</button></div>
}
export default function RetirementRemittanceAuthorization({runId,planId,sourceFingerprint,preview}:{runId:string;planId:string;sourceFingerprint:string;preview:Preview|null}){
 const path=`/api/admin/payroll/runs/${runId}/retirement-remittance-authorizations`
 const [rows,setRows]=useState<Authorization[]|null>(null),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[outside,setOutside]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[readError,setReadError]=useState(''),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0),pending=useRef<Record<string,unknown>|null>(null)
 useEffect(()=>{let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const j=await request(path);if(live){setRows(j.history.filter((r:Authorization)=>r.plan_id===planId));setReadError('')}}catch(e){if(live){setRows(null);setReadError(e instanceof Error?e.message:'Unable to read remittance history.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[path,planId,refresh])
 useEffect(()=>{setConfirmed(false);setOutside(false)},[sourceFingerprint,preview?.fingerprint])
 const active=rows?.some(r=>!r.cancelled_at)
 const authorize=async(retry=false)=>{setBusy(true);setError('');try{
  if(!retry){if(!preview||!confirmed||!outside)throw new Error('Review the current allocation file and outside contribution activity.');pending.current={planId,sourceFingerprint,fileFingerprint:preview.fingerprint,amountCents:preview.amountCents,reference,confirmed:true,outsideActivityReviewed:true,requestKey:crypto.randomUUID()}}
  const result=await request(path,pending.current);pending.current=null;setConfirmed(false);setOutside(false);setMessage(result.cancelled?'The original authorization is retained as cancelled. No reservation was restored.':'Remittance authorization retained. Contributions are reserved; nothing has been sent.');setRefresh(n=>n+1)
 }catch(e){if(e&&typeof e==='object'&&'status'in e&&Number(e.status)>=400&&Number(e.status)<500)pending.current=null;setError(e instanceof Error?e.message:'Unable to authorize remittance.')}finally{setBusy(false)}}
 return <section aria-label={`Retirement remittance authorization ${runId} ${planId}`} className="space-y-3 border-t pt-3"><h6 className="font-bold">Contribution remittance authorization</h6><p>Approve the exact reviewed allocation and contribution amount. Authorization reserves these deductions internally; bank submission is a separate action.</p>{readError?<p role="alert">{readError} Automatic refresh will retry.</p>:null}{error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}
 {preview&&!active?<div className="space-y-3"><p>{preview.planName} · {money(preview.amountCents)} · Withheld {preview.withheldDate}</p><p>{preview.destination.holderName} · ending {preview.destination.accountLast4}</p><p>Deposit target {preview.timing.depositDate} · Submit before {preview.timing.submissionAt?new Date(preview.timing.submissionAt).toLocaleString():'timing review required'}</p>{!preview.authorizationWindowOpen?<p>The reviewed submission window is unavailable. Resolve timing before authorization.</p>:null}<fieldset disabled={busy||!!pending.current||rows===null||!preview.authorizationWindowOpen} className="space-y-3"><label className="block">Outside activity and authorization review reference<textarea value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false);setOutside(false)}} maxLength={2000} className="block w-full rounded border p-2"/></label><label className="flex gap-2"><input type="checkbox" checked={outside} onChange={e=>setOutside(e.target.checked)}/>I verified that these exact payroll deductions have no outside contributions, pending funds instructions or duplicate allocation submissions, including any downloaded files.</label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I authorize this exact contribution amount, destination, allocation file and reviewed timing.</label><button type="button" disabled={!confirmed||!outside||reference.trim().length<20} onClick={()=>void authorize()} className="rounded border px-3 py-2">Authorize contribution remittance</button></fieldset></div>:!active?<p>Prepare the current allocation file above before authorizing remittance.</p>:null}
 {pending.current?<button type="button" disabled={busy} onClick={()=>void authorize(true)} className="rounded border px-3 py-2">Retry original remittance authorization</button>:null}
 {rows?.map(row=><article key={row.id} className="space-y-2 rounded border p-3"><p className="font-bold">{money(row.amount_cents)} · {row.status.replaceAll('_',' ')}</p><p>{row.basis.destination.holderName} · ending {row.basis.destination.accountLast4} · Deposit target {row.basis.timing.depositDate}</p>{!row.cancelled_at&&!row.claimed&&!row.allocation_claimed?<p>{row.sourceCurrent?'Retained payroll and setup sources match. Fresh provider checks are still required before dispatch.':'Retained sources changed or timing requires review. This reservation remains held until resolved or cancelled.'}</p>:null}<p className="whitespace-pre-wrap break-words">{row.reference}</p>{row.bank_unsent_release?<p>Verified unsent bank release · {new Date(row.bank_unsent_release.createdAt).toLocaleString()} · {row.bank_unsent_release.reference}</p>:null}{row.cancelled_at?<p>Cancelled {new Date(row.cancelled_at).toLocaleString()} · {row.cancellation_reference}</p>:!row.claimed&&!row.allocation_claimed?<Cancellation id={row.id} onChanged={()=>setRefresh(n=>n+1)}/>:<p>Dispatch claim retained. Resolve its outcome before any replacement.</p>}{!row.cancelled_at?<RetirementBankDispatch id={row.id} claimed={row.claimed} result={row.bank_result} onChanged={()=>setRefresh(n=>n+1)}/>:null}{!row.cancelled_at?<><RetirementAllocationDelivery remittanceId={row.id} onChanged={()=>setRefresh(n=>n+1)}/><RetirementContributionAssessment id={row.id}/></>:null}</article>)}
 </section>
}
