import {useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
export default function RetirementDestinationSuspension({path,suspension,onChanged}:{path:string;suspension:{id:string;reference:string}|null;onChanged:()=>void}){
 const [reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),pending=useRef<{reference:string;confirmed:true;requestKey:string}|null>(null)
 const save=async(retry=false)=>{setBusy(true);setError('');try{if(!retry)pending.current={reference,confirmed:true,requestKey:crypto.randomUUID()};const r=await adminApiRequest(`${path}/suspend`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(pending.current)}),j=await r.json();if(!r.ok||!j.success){if(r.status>=400&&r.status<500)pending.current=null;throw new Error(j.message||'Unable to suspend retirement destination.')}pending.current=null;setConfirmed(false);onChanged()}catch(e){setError(e instanceof Error?e.message:'Unable to suspend retirement destination.')}finally{setBusy(false)}}
 return <section aria-label="Retirement destination suspension" className="space-y-2 border-t pt-3">
  {suspension?<><p role="status" className="font-bold">Destination suspended</p><p>{suspension.reference}</p><p>Retain a new independently reviewed destination to resume remittance preparation.</p></>:<><p>Suspension blocks new remittance preparation using this destination. It does not recall a payment or change participant enrollment.</p><label className="block">Destination suspension reason<input maxLength={2000} disabled={busy||!!pending.current} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} className="mt-1 block w-full rounded border p-2"/></label><label className="flex gap-2"><input type="checkbox" disabled={busy||!!pending.current} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the reason to stop using this retirement destination.</label><button type="button" disabled={busy||!!pending.current||!confirmed||reference.trim().length<20} className="rounded border px-3 py-2" onClick={()=>void save()}>Suspend retirement destination</button></>}
  {error?<p role="alert">{error}</p>:null}{pending.current?<button type="button" disabled={busy} className="rounded border px-3 py-2" onClick={()=>void save(true)}>Retry original destination suspension</button>:null}
 </section>
}
