import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
const fields=[['providerPlanId','Recordkeeper plan identifier'],['participantId','Participant identifier'],['withheldDate','Withholding date'],['ordinaryPretaxCents','Ordinary pretax'],['ordinaryRothCents','Ordinary Roth'],['catchUpPretaxCents','Pretax catch-up'],['catchUpRothCents','Roth catch-up'],['totalCents','Employee total']]
type Column={field:string;header:string}
type Format={disposition:string;reference:string;columns?:Column[];amountFormat?:string;dateFormat?:string;includeHeader?:boolean}
type Data={planRevisionId:string;history:{id:string;revision:number;format:Format;currentPlan:boolean}[]}
export default function RetirementAllocationFormat({planId}:{planId:string}){
 const path=`/api/admin/payroll/retirement-plans/${encodeURIComponent(planId)}/allocation-format`
 const [data,setData]=useState<Data|null>(null),[columns,setColumns]=useState<Column[]>(()=>fields.map(([field])=>({field,header:''}))),[disposition,setDisposition]=useState('VERIFIED'),[amount,setAmount]=useState(''),[date,setDate]=useState(''),[header,setHeader]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0),pending=useRef<Record<string,unknown>|null>(null)
 const revision=data?.history[0]?.revision||0
 useEffect(()=>{let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const r=await adminApiRequest(path),j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Unable to load allocation format.');if(live){setData(j.data);setError('')}}catch(e){if(live){setData(null);setError(e instanceof Error?e.message:'Unable to load allocation format.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[path,refresh])
 useEffect(()=>{setConfirmed(false)},[data?.planRevisionId,revision])
 const save=async(retry=false)=>{setBusy(true);setError('');try{
  if(!retry){if(!data||!confirmed)throw new Error('Review and confirm the current recordkeeper format.');pending.current={planRevisionId:data.planRevisionId,expectedRevision:revision,requestKey:crypto.randomUUID(),format:{disposition,reference,columns,amountFormat:amount,dateFormat:date,includeHeader:header==='YES'?true:header==='NO'?false:null,confirmed:true}}}
  const r=await adminApiRequest(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(pending.current)}),j=await r.json();if(!r.ok||!j.success)throw Object.assign(new Error(j.message||'Unable to retain allocation format.'),{status:r.status})
  pending.current=null;setConfirmed(false);setMessage('Recordkeeper allocation format retained. Provider acceptance and delivery remain unverified.');setRefresh(n=>n+1)
 }catch(e){if(e&&typeof e==='object'&&'status' in e&&Number(e.status)>=400&&Number(e.status)<500)pending.current=null;setError(e instanceof Error?e.message:'Unable to retain allocation format.')}finally{setBusy(false)}}
 const move=(index:number,step:number)=>{setColumns(old=>{const next=[...old];[next[index],next[index+step]]=[next[index+step],next[index]];return next});setConfirmed(false)}
 return <section aria-label={`Recordkeeper allocation format ${planId}`} className="space-y-3 rounded-xl border p-4"><h4 className="font-bold">Recordkeeper allocation format · {planId}</h4><p>Match the recordkeeper’s actual specification for one employee per row with separate ordinary pretax, Roth and catch-up amounts. This supports eight-column UTF-8 comma-separated files. A different required structure needs an additional adapter.</p>
 {error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}
 <form className="space-y-3" onSubmit={e=>{e.preventDefault();void save()}} onChange={()=>{setConfirmed(false);setMessage('')}}><fieldset disabled={!data||busy||!!pending.current} className="space-y-3">
 <label className="block">Allocation format disposition<select value={disposition} onChange={e=>setDisposition(e.target.value)} className="block w-full rounded border p-2"><option value="VERIFIED">Reviewed format</option><option value="SUSPENDED">Suspend format</option></select></label>
 {disposition==='VERIFIED'?<><label className="block">Recordkeeper amount representation<select required value={amount} onChange={e=>setAmount(e.target.value)} className="block w-full rounded border p-2"><option value="">Select verified format</option><option value="CENTS">Integer cents</option><option value="DOLLARS">Dollars with two decimals</option></select></label><label className="block">Recordkeeper date representation<select required value={date} onChange={e=>setDate(e.target.value)} className="block w-full rounded border p-2"><option value="">Select verified format</option><option value="ISO">YYYY-MM-DD</option><option value="US">MM/DD/YYYY</option></select></label><label className="block">Include column headers<select required value={header} onChange={e=>setHeader(e.target.value)} className="block w-full rounded border p-2"><option value="">Select verified requirement</option><option value="YES">Yes</option><option value="NO">No</option></select></label>
 {columns.map((c,index)=>{const label=fields.find(([field])=>field===c.field)![1];return <div key={c.field} className="space-y-2 rounded border p-2"><label className="block">{label} column header<input required maxLength={80} value={c.header} onChange={e=>setColumns(old=>old.map(x=>x.field===c.field?{...x,header:e.target.value}:x))} className="block w-full rounded border p-2"/></label><div className="flex gap-2"><span>Column {index+1}</span><button type="button" disabled={index===0} aria-label={`Move ${label} up`} onClick={()=>move(index,-1)} className="rounded border px-2">Up</button><button type="button" disabled={index===columns.length-1} aria-label={`Move ${label} down`} onClick={()=>move(index,1)} className="rounded border px-2">Down</button></div></div>})}</>:null}
 <label className="block">Recordkeeper specification and verification reference<textarea required minLength={20} maxLength={2000} value={reference} onChange={e=>setReference(e.target.value)} className="block w-full rounded border p-2"/></label></fieldset>
 <label className="flex gap-2"><input type="checkbox" disabled={!data||busy||!!pending.current} checked={confirmed} onChange={e=>{e.stopPropagation();setConfirmed(e.target.checked)}}/>I verified the exact columns, formats and file acceptance requirements with the recordkeeper, or reviewed the reason to suspend this format.</label><button disabled={!confirmed||busy||!!pending.current} className="rounded border px-3 py-2">Retain allocation format</button></form>
 {pending.current?<button type="button" disabled={busy} onClick={()=>void save(true)} className="rounded border px-3 py-2">Retry original allocation format</button>:null}
 {data?.history.map(row=><article key={row.id} className="space-y-1 rounded border p-3"><p className="font-bold">Allocation format revision {row.revision} · {row.format.disposition}{!row.currentPlan?' · Plan changed':''}</p><p className="break-words">{row.format.columns?.map(c=>c.header).join(' → ')}</p>{row.format.columns?<p>{row.format.amountFormat} · {row.format.dateFormat} · {row.format.includeHeader?'Headers included':'No header row'}</p>:null}<p className="whitespace-pre-wrap break-words">{row.format.reference}</p></article>)}
 </section>
}
