import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Row={id:string;revision:number;disposition:string;contract_id:string;directory:string;file_name:string;reference:string;created_at:string}
type Contract={id:string;revision:number;reference:string;contract:{columns:{field:string;header:string}[];statusValues:Record<string,string>}}
type Data={status:string;claimed:boolean;cancelled:boolean;planDisposition:string|null;originalFileName:string;host:string;port:number;contracts:Contract[];history:Row[]}
async function request(path:string,body?:unknown){const r=await adminApiRequest(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),j=await r.json();if(!r.ok||!j.success)throw Object.assign(new Error(j.message||'Unable to retain receipt location.'),{status:r.status});return j.data}
export default function RetirementReceiptBinding({path,id}:{path:string;id:string}){
 const [requested,setRequested]=useState(false),[data,setData]=useState<Data|null>(null),[refresh,setRefresh]=useState(0),[action,setAction]=useState('REVIEW'),[contractId,setContractId]=useState(''),[directory,setDirectory]=useState(''),[fileName,setFileName]=useState(''),[reference,setReference]=useState(''),[original,setOriginal]=useState(false),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[readError,setReadError]=useState(''),[message,setMessage]=useState(''),pending=useRef<Record<string,unknown>|null>(null)
 const revision=data?.history[0]?.revision||0,reset=()=>{setOriginal(false);setConfirmed(false)}
 useEffect(()=>{if(!requested)return;let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const next=await request(path);if(live){setData(next);setReadError('')}}catch(e){if(live){setData(null);setReadError(e instanceof Error?e.message:'Unable to read receipt history.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[path,requested,refresh])
 useEffect(()=>{setOriginal(false);setConfirmed(false)},[revision,data?.planDisposition,data?.cancelled,data?.claimed])
 const save=async()=>{setBusy(true);setError('');try{if(!pending.current){if(!data||!confirmed)throw new Error('Review the current receipt binding.');pending.current={action,expectedRevision:revision,requestKey:crypto.randomUUID(),reference,confirmed,...(action==='REVIEW'?{contractId,directory,fileName,originalFileReviewed:original}:{})}}await request(path,pending.current);pending.current=null;reset();setMessage('Receipt location action retained. No receipt has been read by this action.');setRefresh(n=>n+1)}catch(e){if(e&&typeof e==='object'&&'status'in e&&Number(e.status)>=400&&Number(e.status)<500)pending.current=null;setError(e instanceof Error?e.message:'Receipt binding requires retry.')}finally{setBusy(false)}}
 const edit=(row:Row)=>{setAction('REVIEW');setContractId(row.contract_id);setDirectory(row.directory);setFileName(row.file_name);setReference(row.reference);reset()}
 return <section aria-label={`Retirement receipt location ${id}`} className="space-y-2 rounded border p-3"><p className="font-bold">Recordkeeper receipt location</p><p>Bind the provider’s exact receipt path and interpretation contract to this claimed allocation. Historical file identities and server credentials stay with the original delivery. Location review does not prove acceptance or participant posting.</p><button type="button" disabled={busy} onClick={()=>{setRequested(true);setRefresh(n=>n+1)}} className="rounded border px-3 py-2">Load receipt location history</button>{readError?<p role="alert">{readError}</p>:null}{error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}
 {data?<><p>Receipt location: {data.status.replaceAll('_',' ')} · revision {revision}</p><p className="break-all">Original allocation: {data.originalFileName} · Server {data.host}:{data.port}</p>{!data.contracts.length?<p>Review a receipt contract matching this original plan and allocation format in employer setup.</p>:null}{data.planDisposition==='SUSPENDED'?<p>Receipt interpretation is suspended for this plan. Retain a reviewed contract before binding a new location.</p>:null}<label className="block">Receipt location action<select disabled={busy||!!pending.current} value={action} onChange={e=>{setAction(e.target.value);reset()}} className="block max-w-full rounded border p-2"><option value="REVIEW">Review receipt location</option><option value="SUSPEND">Suspend receipt location</option></select></label>
 <fieldset disabled={busy||!!pending.current||action==='REVIEW'&&(data.cancelled||!data.claimed||data.planDisposition==='SUSPENDED')} className="space-y-2">{action==='REVIEW'?<><label className="block">Retained receipt interpretation contract<select value={contractId} onChange={e=>{setContractId(e.target.value);reset()}} className="block max-w-full rounded border p-2"><option value="">Choose a reviewed contract</option>{data.contracts.map(c=><option key={c.id} value={c.id}>Receipt contract revision {c.revision}</option>)}</select></label><label className="block">Receipt directory<input value={directory} onChange={e=>{setDirectory(e.target.value);reset()}} maxLength={512} className="block w-full rounded border p-2"/></label><label className="block">Receipt CSV filename<input value={fileName} onChange={e=>{setFileName(e.target.value);reset()}} maxLength={124} className="block w-full rounded border p-2"/></label><p>Use the actual provider receipt directory outside allocation staging and its exact CSV filename.</p></>:<p>Suspension preserves the original location and contract. It does not cancel a bank or file instruction.</p>}
 <label className="block">Receipt location review reference<textarea value={reference} onChange={e=>{setReference(e.target.value);reset()}} maxLength={2000} className="block w-full rounded border p-2"/></label>{action==='REVIEW'?<label className="flex gap-2"><input type="checkbox" checked={original} onChange={e=>{setOriginal(e.target.checked);setConfirmed(false)}}/>I verified this receipt path and retained contract refer to the exact original allocation file and its participant amounts.</label>:null}<label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm this receipt location action and reviewed evidence.</label><button type="button" disabled={!confirmed||reference.trim().length<20||action==='REVIEW'&&(!original||!contractId||!directory||!fileName)} onClick={()=>void save()} className="rounded border px-3 py-2">{action==='REVIEW'?'Save receipt location':'Suspend receipt location'}</button></fieldset>
 {data.contracts.map(c=><details key={c.id} className="rounded border p-2"><summary>Interpretation contract revision {c.revision}</summary><p className="break-words">{c.reference}</p><p className="break-words">{c.contract.columns.map(column=>column.header).join(' · ')}</p>{Object.entries(c.contract.statusValues).map(([status,value])=><p key={status}>{status}: {value}</p>)}</details>)}</>:null}
 {pending.current?<button type="button" disabled={busy} onClick={()=>void save()} className="rounded border px-3 py-2">Retry original receipt location action</button>:null}
 {data?.history.map(row=><details key={row.id} className="rounded border p-2"><summary>Location revision {row.revision} · {row.disposition}</summary><p>{new Date(row.created_at).toLocaleString()}</p><p className="break-all">{row.directory}/{row.file_name}</p><p className="break-words">{row.reference}</p><button type="button" disabled={busy||!!pending.current} onClick={()=>edit(row)} className="rounded border px-3 py-2">Edit from location revision {row.revision}</button></details>)}
 </section>
}
