import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Review={disposition:string;eligibleOn:string|null;methods:string[];reference:string;employeeExplanation:string}
type Data={source:{fingerprint:string;onboardingCycle:number;hireDate:string;planEffectiveOn:string};currentStatus:string;history:{id:string;revision:number;onboarding_cycle:number;review:Review;created_at:string}[]}
const inputClass='mt-1 block w-full rounded-lg border border-slate-300 p-2'
const request=async(url:string,body?:unknown)=>{const response=await adminApiRequest(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),json=await response.json();if(!response.ok||!json.success)throw new Error(json.message||'Unable to load retirement eligibility.');return json.data}
export default function RetirementEligibility({employeeId}:{employeeId:number}){
 const [plans,setPlans]=useState<{planId:string;plan:{name:string}}[]>([]),[planId,setPlanId]=useState(''),[data,setData]=useState<Data|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[refreshIssue,setRefreshIssue]=useState('')
 const [disposition,setDisposition]=useState(''),[date,setDate]=useState(''),[methods,setMethods]=useState<string[]>([]),[reference,setReference]=useState(''),[explanation,setExplanation]=useState(''),[confirmed,setConfirmed]=useState(false)
 const [basis,setBasis]=useState<{fingerprint:string;revision:number}|null>(null),pending=useRef<{body:string;key:string}|null>(null)
 const path=`/api/admin/payroll/employees/${employeeId}/retirement-eligibility/${encodeURIComponent(planId)}`
 const selectBasis=(next:Data)=>{setBasis({fingerprint:next.source.fingerprint,revision:next.history[0]?.revision||0});setConfirmed(false);pending.current=null}
 useEffect(()=>{
  if(!planId||busy)return;let live=true,inFlight=false
  const read=async()=>{if(inFlight)return;inFlight=true;try{const next=await request(path) as Data;if(live){setData(next);setLoaded(true);setRefreshIssue('')}}catch(e){if(live)setRefreshIssue(e instanceof Error?e.message:'Unable to refresh eligibility.')}finally{inFlight=false}}
  void read();const timer=setInterval(()=>void read(),30000)
  return()=>{live=false;clearInterval(timer)}
 },[path,planId,busy])
 const loadPlans=async()=>{setBusy(true);setError('');try{const result=await request('/api/admin/payroll/retirement-plans');setPlans(result.history.filter((row:{planId:string},index:number,rows:{planId:string}[])=>rows.findIndex(candidate=>candidate.planId===row.planId)===index));setMessage(result.history.length?'':'Retain a retirement plan in Employer setup first.')}catch(e){setError(e instanceof Error?e.message:'Unable to load plans.')}finally{setBusy(false)}}
 const stale=!basis||!data||basis.fingerprint!==data.source.fingerprint||basis.revision!==(data.history[0]?.revision||0)
 const save=async(retry=false)=>{if(!basis&&!retry)return;setBusy(true);setError('');setMessage('');try{
  const value=retry&&pending.current?JSON.parse(pending.current.body):{sourceFingerprint:basis?.fingerprint,expectedRevision:basis?.revision,confirmed,disposition,eligibleOn:disposition==='ELIGIBLE'?date:null,methods:disposition==='ELIGIBLE'?methods:[],reference,employeeExplanation:explanation},body=JSON.stringify(value)
  if(pending.current?.body!==body)pending.current={body,key:crypto.randomUUID()}
  await request(path,{...value,requestKey:pending.current.key});const next=await request(path) as Data;setData(next);selectBasis(next);setMessage('Eligibility review retained. Employee elections and payroll processing require their separate steps.')
 }catch(e){setError(e instanceof Error?e.message:'Unable to retain eligibility.')}finally{setBusy(false)}}
 return <section aria-label="Retirement participant eligibility" className="space-y-3 rounded-xl border bg-white p-4 text-sm"><h3 className="font-bold">Retirement participant eligibility</h3><p>Review actual plan entry and service requirements for this employee. Eligibility alone does not enroll the employee or deduct contributions.</p><button type="button" disabled={busy} onClick={()=>void loadPlans()} className="rounded border px-3 py-2">Load retirement plans</button>{error?<p role="alert">{error}</p>:null}{refreshIssue?<p role="alert">{refreshIssue}</p>:null}{message?<p role="status">{message}</p>:null}
 {plans.length?<label>Participant retirement plan<select className={inputClass} disabled={busy} value={planId} onChange={e=>{setPlanId(e.target.value);setData(null);setLoaded(false);setBasis(null);setConfirmed(false);setDisposition('');setDate('');setMethods([]);setReference('');setExplanation('');setMessage('');pending.current=null}}><option value="">Select a reviewed plan</option>{plans.map(plan=><option key={plan.planId} value={plan.planId}>{plan.plan.name}</option>)}</select></label>:null}
 {loaded&&data?<><p>Current review: {data.currentStatus.replaceAll('_',' ')} · Employment cycle {data.source.onboardingCycle}</p><button type="button" disabled={busy||!!refreshIssue} onClick={()=>selectBasis(data)} className="rounded border px-3 py-2">Review current eligibility evidence</button>{stale?<p>The plan or eligibility history requires a fresh review. Your draft is preserved; select current evidence before saving.</p>:null}
 <fieldset disabled={busy||stale||!!refreshIssue} className="space-y-3"><legend className="font-bold">Participant review</legend><label>Eligibility determination<select value={disposition} onChange={e=>{setDisposition(e.target.value);setConfirmed(false)}} className={inputClass}><option value="">Review eligibility</option><option value="ELIGIBLE">Eligible</option><option value="NOT_ELIGIBLE">Not eligible</option><option value="REVIEW_REQUIRED">Requires further review</option></select></label>
 {disposition==='ELIGIBLE'?<><label>Eligible plan entry date<input type="date" className={inputClass} value={date} onChange={e=>{setDate(e.target.value);setConfirmed(false)}}/></label>{[['PERCENTAGE','Percentage of eligible compensation'],['FIXED_PER_REGULAR_PAY','Fixed amount per regular payroll']].map(([key,label])=><label key={key} className="flex gap-2"><input type="checkbox" checked={methods.includes(key)} onChange={e=>{setMethods(current=>e.target.checked?[...current,key]:current.filter(value=>value!==key));setConfirmed(false)}}/>{label}</label>)}</>:null}
 <label className="block">Eligibility verification reference<textarea className={inputClass} maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="block">Eligibility explanation for employee<textarea className={inputClass} maxLength={2000} value={explanation} onChange={e=>{setExplanation(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified this employee’s service, entry date and permitted election methods against the plan.</label><button type="button" disabled={!confirmed} onClick={()=>void save()} className="rounded border px-3 py-2 font-bold">Retain participant eligibility</button></fieldset>
 {pending.current?<button type="button" disabled={busy} onClick={()=>void save(true)} className="rounded border px-3 py-2">Retry original eligibility review</button>:null}
 {data.history.map(row=><details key={row.id} className="rounded border p-3"><summary>Eligibility revision {row.revision} · Cycle {row.onboarding_cycle} · {row.review.disposition.replaceAll('_',' ')}</summary><p>{row.review.eligibleOn||'No confirmed entry date'}</p><p className="break-words">{row.review.employeeExplanation}</p><p className="break-words">{row.review.reference}</p><p>{new Date(row.created_at).toLocaleString()}</p></details>)}</>:null}</section>
}
