import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Row={id:string;submit_at:string;cutoff:string;reference:string;cancelled_at:string|null;cancellation_reference:string|null;attempt:{status:string;at:string}|null}
type Data={target:{claimed:boolean;cancelled:boolean;cutoff:string};history:Row[]}
async function request(path:string,body?:unknown){const r=await adminApiRequest(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),j=await r.json();if(!r.ok||!j.success)throw Object.assign(new Error(j.message||'Unable to retain retirement schedule.'),{status:r.status});return j.data}
export default function RetirementDispatchSchedule({kind,targetId,onChanged}:{kind:'BANK'|'FILE';targetId:string;onChanged:()=>void}){
 const path=`/api/admin/payroll/retirement-dispatch-schedules/${kind}/${targetId}`,label=kind==='BANK'?'bank payment':'allocation file'
 const [requested,setRequested]=useState(false),[data,setData]=useState<Data|null>(null),[refresh,setRefresh]=useState(0),[submitAt,setSubmitAt]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[outside,setOutside]=useState(false),[bank,setBank]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[readError,setReadError]=useState(''),[message,setMessage]=useState('')
 const pending=useRef<{path:string;body:Record<string,unknown>}|null>(null)
 useEffect(()=>{if(!requested)return;let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const next=await request(path);if(live){setData(next);setReadError('')}}catch(e){if(live){setData(null);setReadError(e instanceof Error?e.message:'Unable to read schedule history.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[path,requested,refresh])
 const active=data?.history.find(r=>!r.cancelled_at),editable=data&&!data.target.claimed&&!data.target.cancelled
 const resetReview=()=>{setConfirmed(false);setOutside(false);setBank(false)}
 const save=async(cancelId?:string)=>{setBusy(true);setError('');try{
  if(!pending.current){if(cancelId)pending.current={path:`${path}/${cancelId}/cancel`,body:{reference,confirmed}};else{if(!submitAt||!Number.isFinite(Date.parse(submitAt)))throw new Error('Choose the submission date and time.');pending.current={path,body:{submitAt:new Date(submitAt).toISOString(),reference,confirmed,outsideActivityReviewed:outside,bankInstructionsReviewed:bank,requestKey:crypto.randomUUID()}}}}
  const result=await request(pending.current.path,pending.current.body);pending.current=null;resetReview();setMessage(result.cancelled?'Original schedule remains cancelled.':'Schedule action retained. Review the history below.');setRefresh(n=>n+1);onChanged()
 }catch(e){if(e&&typeof e==='object'&&'status'in e&&Number(e.status)>=400&&Number(e.status)<500)pending.current=null;setError(e instanceof Error?e.message:'Schedule action requires review.')}finally{setBusy(false)}}
 return <section aria-label={`Retirement ${label} schedule ${targetId}`} className="space-y-2 rounded border p-3"><p className="font-bold">Automatic {label} submission</p><button type="button" disabled={busy} onClick={()=>{setRequested(true);setRefresh(n=>n+1)}} className="rounded border px-3 py-2">Load {label} schedule</button>
 {readError?<p role="alert">{readError} Automatic refresh will retry.</p>:null}{error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}
 {data?<><p>Submission cutoff: {new Date(data.target.cutoff).toLocaleString()}. The worker checks due schedules every minute and revalidates current evidence before sending. Blocked attempts retry before the cutoff; expired schedules require review.</p>{active&&!data.target.claimed&&!data.target.cancelled?<p>A schedule is retained. Cancel it before changing the time or submitting manually.</p>:null}{data.target.claimed?<p>Dispatch is claimed. Use the delivery history to recover its outcome.</p>:null}{data.target.cancelled?<p>The authorization is cancelled.</p>:null}</>:null}
 {editable?<fieldset disabled={busy||!!pending.current} className="space-y-2">{!active?<><label className="block">Scheduled {label} submission time<input type="datetime-local" value={submitAt} onChange={e=>{setSubmitAt(e.target.value);resetReview()}} className="block max-w-full rounded border p-2"/></label><p>Time zone: {Intl.DateTimeFormat().resolvedOptions().timeZone}. Choose at least one minute ahead and five minutes before the cutoff.</p></>:null}
 <label className="block">{label} schedule review reference<textarea value={reference} onChange={e=>{setReference(e.target.value);resetReview()}} maxLength={2000} className="block w-full rounded border p-2"/></label>
 {!active?<><label className="flex gap-2"><input type="checkbox" checked={outside} onChange={e=>setOutside(e.target.checked)}/>I reviewed that no outside or duplicate instruction exists and will cancel this schedule before arranging another submission.</label>{kind==='BANK'?<label className="flex gap-2"><input type="checkbox" checked={bank} onChange={e=>setBank(e.target.checked)}/>I verified the trustee accepts ACH CCD without additional addenda and separate allocation delivery will not trigger another debit.</label>:null}</>:null}
 <label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm this {label} schedule action and retained review.</label>
 <button type="button" disabled={!confirmed||reference.trim().length<20||!active&&(!submitAt||!outside||kind==='BANK'&&!bank)} onClick={()=>void save(active?.id)} className="rounded border px-3 py-2">{active?`Cancel ${label} schedule`:`Schedule ${label} submission`}</button></fieldset>:null}
 {pending.current?<button type="button" disabled={busy} onClick={()=>void save()} className="rounded border px-3 py-2">Retry original {label} schedule action</button>:null}
 {data?.history.map(row=><article key={row.id} className="space-y-1 border-t pt-2"><p>{new Date(row.submit_at).toLocaleString()} · {row.cancelled_at?'CANCELLED':row.attempt?.status||'SCHEDULED'}</p><p className="whitespace-pre-wrap break-words">{row.reference}</p>{row.attempt?<p>Last attempt: {new Date(row.attempt.at).toLocaleString()}</p>:null}{row.cancelled_at?<p>Cancelled {new Date(row.cancelled_at).toLocaleString()} · {row.cancellation_reference}</p>:null}</article>)}
 </section>
}
