import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
const amounts=[['priorYearSponsorFicaWagesCents','Prior-year plan-sponsor FICA wages'],['externalOrdinaryDeferralsCents','All aggregated external ordinary deferrals'],['externalCatchUpDeferralsCents','All aggregated external catch-up deferrals'],['externalPlanOrdinaryDeferralsCents','This plan’s external ordinary deferrals'],['externalPlanCatchUpDeferralsCents','This plan’s external catch-up deferrals'],['externalAnnualAdditionsCents','External annual additions for the employer limit group'],['externalPlanCompensationCents','External compensation under this plan’s definition'],['external415CompensationCents','External compensation under the annual-additions definition']] as const
const references=[['ageReference','Age verification reference'],['aggregationReference','Employer and plan aggregation review'],['balanceReference','External balance evidence'],['participantLimitReference','Participant-specific limit review'],['compensationReference','Compensation definitions and cap review']] as const
const caps=[['participantOrdinaryCapCents','Additional participant ordinary cap'],['participantCatchUpCapCents','Additional participant catch-up cap']] as const
const inputClass='mt-1 block w-full rounded-lg border border-slate-300 p-2'
type History={id:string;revision:number;facts:Record<string,string|number|null>;created_at:string}
type Data={planRevisionId:string;planName:string;status:string;history:History[]}
const request=async(path:string,body?:unknown)=>{const r=await adminApiRequest(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),json=await r.json();if(!r.ok||!json.success)throw new Error(json.message||'Unable to read annual retirement sources.');return json.data}
const cents=(value:string)=>{if(!/^\d+(\.\d{1,2})?$/.test(value||''))throw new Error('Review every dollar amount; blank is not zero. Use no more than two decimals.');const [whole,fraction='']=value.split('.'),n=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(n))throw new Error('Annual amount is too large.');return n}
export default function RetirementAnnualSources({employeeId}:{employeeId:number}){
 const [plans,setPlans]=useState<{planId:string;plan:{name:string}}[]>([]),[planId,setPlanId]=useState(''),[data,setData]=useState<Data|null>(null),[basis,setBasis]=useState<{planRevisionId:string;expectedRevision:number}|null>(null),[form,setForm]=useState<Record<string,string>>({}),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[readIssue,setReadIssue]=useState(''),[message,setMessage]=useState(''),pending=useRef<{body:string;key:string}|null>(null)
 const path=`/api/admin/payroll/employees/${employeeId}/retirement-annual-sources/${encodeURIComponent(planId)}`
 const set=(key:string,value:string)=>{setForm(current=>({...current,[key]:value}));setConfirmed(false)}
 useEffect(()=>{if(!planId||busy)return;let live=true,inFlight=false;const read=async()=>{if(inFlight)return;inFlight=true;try{const next=await request(path);if(live){setData(next);setReadIssue('')}}catch(e){if(live)setReadIssue(e instanceof Error?e.message:'Unable to refresh annual sources.')}finally{inFlight=false}};void read();const timer=setInterval(()=>void read(),30000);return()=>{live=false;clearInterval(timer)}},[path,planId,busy])
 const load=async()=>{setBusy(true);setError('');try{const result=await request('/api/admin/payroll/retirement-plans');setPlans(result.history.filter((row:{planId:string},i:number,rows:{planId:string}[])=>rows.findIndex(other=>other.planId===row.planId)===i));if(!result.history.length)setMessage('Retain a retirement plan in Employer setup first.')}catch(e){setError(e instanceof Error?e.message:'Unable to load plans.')}finally{setBusy(false)}}
 const begin=()=>{if(!data)return;setBasis({planRevisionId:data.planRevisionId,expectedRevision:data.history[0]?.revision||0});setConfirmed(false);setError('');setMessage('');pending.current=null}
 const copy=(row:History)=>{const values:Record<string,string>={};for(const [key,value] of Object.entries(row.facts))if(value!==null)values[key]=String(value);for(const [key] of amounts)values[key]=String(Number(row.facts[key])/100);for(const [key] of caps){values[`${key}-mode`]=row.facts[key]===null?'NONE':'LIMIT';values[key]=row.facts[key]===null?'':String(Number(row.facts[key])/100)}setForm(values);setConfirmed(false)}
 const stale=!basis||basis.planRevisionId!==data?.planRevisionId||basis.expectedRevision!==(data?.history[0]?.revision||0)
 const save=async(retry=false)=>{setBusy(true);setError('');setMessage('');try{
  const value=retry&&pending.current?JSON.parse(pending.current.body):{...basis,facts:{taxYear:2026,asOfDate:form.asOfDate,ageAtYearEnd:form.ageAtYearEnd?.trim()?Number(form.ageAtYearEnd):null,confirmed,compensationCapTreatment:form.compensationCapTreatment,...Object.fromEntries(amounts.map(([key])=>[key,cents(form[key])])),...Object.fromEntries(references.map(([key])=>[key,form[key]])),...Object.fromEntries(caps.map(([key])=>[key,form[`${key}-mode`]==='NONE'?null:form[`${key}-mode`]==='LIMIT'?cents(form[key]):undefined]))}},body=JSON.stringify(value)
  if(pending.current?.body!==body)pending.current={body,key:crypto.randomUUID()}
  await request(path,{...value,requestKey:pending.current.key});const next=await request(path) as Data;setData(next);setBasis({planRevisionId:next.planRevisionId,expectedRevision:next.history[0]?.revision||0});pending.current=null;setConfirmed(false);setMessage('Annual source review retained. Contribution calculations and payroll processing remain separate.')
 }catch(e){setError(e instanceof Error?e.message:'Unable to retain annual sources.')}finally{setBusy(false)}}
 return <section aria-label="Retirement annual sources" className="space-y-3 rounded-xl border bg-white p-4 text-sm"><h3 className="font-bold">Retirement annual sources · 2026</h3><p>Retain verified external contributions and compensation, excluding all amounts processed by this application. Zero requires verification. Ordinary deferrals aggregate across applicable plans; annual additions use the reviewed employer/related-employer group and exclude catch-up. This review does not reset on rehire.</p><button type="button" disabled={busy} onClick={()=>void load()} className="rounded border px-3 py-2">Load annual-source plans</button>{error?<p role="alert">{error}</p>:null}{readIssue?<p role="alert">{readIssue} Automatic refresh will retry.</p>:null}{message?<p role="status">{message}</p>:null}
 {plans.length?<label className="block">Annual-source retirement plan<select className={inputClass} disabled={busy} value={planId} onChange={e=>{setPlanId(e.target.value);setData(null);setBasis(null);setForm({});setConfirmed(false);pending.current=null;setError('');setMessage('')}}><option value="">Select a plan</option>{plans.map(plan=><option key={plan.planId} value={plan.planId}>{plan.plan.name}</option>)}</select></label>:null}
 {data?<><p>Current evidence: {data.status.replaceAll('_',' ')}</p><button type="button" disabled={busy||!!readIssue} onClick={begin} className="rounded border px-3 py-2">Review current annual-source basis</button>{stale?<p>Your draft is preserved. Review the current plan and source history before retaining a new revision.</p>:null}<fieldset disabled={busy||stale||!!readIssue} className="grid gap-3 sm:grid-cols-2"><legend className="font-bold">Reviewed annual inputs</legend><label>Annual evidence as-of date<input type="date" value={form.asOfDate||''} onChange={e=>set('asOfDate',e.target.value)} className={inputClass}/></label><label>Age attained at year end<input type="number" min="0" max="120" value={form.ageAtYearEnd||''} onChange={e=>set('ageAtYearEnd',e.target.value)} className={inputClass}/></label>
 {amounts.map(([key,label])=><label key={key}>{label} ($)<input inputMode="decimal" value={form[key]||''} onChange={e=>set(key,e.target.value)} className={inputClass}/></label>)}
 {caps.map(([key,label])=><label key={key}>{label}<select value={form[`${key}-mode`]||''} onChange={e=>set(`${key}-mode`,e.target.value)} className={inputClass}><option value="">Review applicable limit</option><option value="NONE">No additional participant cap</option><option value="LIMIT">Reviewed annual dollar cap</option></select>{form[`${key}-mode`]==='LIMIT'?<input aria-label={`${label} ($)`} inputMode="decimal" value={form[key]||''} onChange={e=>set(key,e.target.value)} className={inputClass}/>:null}</label>)}
 <label className="sm:col-span-2">Plan treatment after annual compensation limit<select value={form.compensationCapTreatment||''} onChange={e=>set('compensationCapTreatment',e.target.value)} className={inputClass}><option value="">Review actual plan terms</option><option value="FIRST_COMPENSATION_LIMIT">Stop deferrals after the first compensation limit</option><option value="DEFERRALS_CONTINUE">Deferrals can continue under the reviewed plan terms</option></select></label>{references.map(([key,label])=><label key={key} className="sm:col-span-2">{label}<textarea maxLength={2000} value={form[key]||''} onChange={e=>set(key,e.target.value)} className={inputClass}/></label>)}<label className="flex gap-2 sm:col-span-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified the year, age, aggregation, external balances, applicable limits and compensation definitions. External totals exclude this application’s payroll.</label><button type="button" disabled={!confirmed} onClick={()=>void save()} className="rounded border px-3 py-2 font-bold">Retain annual retirement sources</button></fieldset>{pending.current?<button type="button" disabled={busy} onClick={()=>void save(true)} className="rounded border px-3 py-2">Retry original annual-source review</button>:null}
 {data.history.map(row=><details key={row.id} className="rounded border p-3"><summary>Annual source revision {row.revision} · {row.facts.asOfDate}</summary><p>Age at year end: {row.facts.ageAtYearEnd}</p>{caps.map(([key,label])=><p key={key}>{label}: {row.facts[key]===null?'No additional cap':`$${(Number(row.facts[key])/100).toFixed(2)}`}</p>)}<p>Compensation cap treatment: {String(row.facts.compensationCapTreatment).replaceAll('_',' ')}</p>{amounts.map(([key,label])=><p key={key}>{label}: ${(Number(row.facts[key])/100).toFixed(2)}</p>)}{references.map(([key,label])=><p key={key} className="whitespace-pre-wrap break-words">{label}: {row.facts[key]}</p>)}<button type="button" disabled={busy} onClick={()=>copy(row)} className="rounded border px-3 py-2">Copy retained annual inputs into draft</button></details>)}</>:null}</section>
}
