import {useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Preview={eligible:boolean;reasons:string[];fingerprint:string;remoteStatus:string;observationCount:number}
async function request(path:string,body:unknown){const r=await adminApiRequest(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok||!j.success)throw Object.assign(new Error(j.message||'Unable to review unsent bank.'),{status:r.status});return j.data}
export default function RetirementBankUnsentRelease({path,onChanged}:{path:string;onChanged:()=>void}){
 const [preview,setPreview]=useState<Preview|null>(null),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[outside,setOutside]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),pending=useRef<Record<string,unknown>|null>(null)
 const load=async()=>{setBusy(true);setError('');setPreview(null);setConfirmed(false);setOutside(false);try{setPreview(await request(path+'/preview',{}))}catch(e){setError(e instanceof Error?e.message:'Unable to verify original bank evidence.')}finally{setBusy(false)}}
 const release=async()=>{setBusy(true);setError('');try{if(!pending.current){if(!preview?.eligible)throw new Error('Preview current bank non-send evidence first.');pending.current={fingerprint:preview.fingerprint,reference,confirmed,outsideActivityReviewed:outside,requestKey:crypto.randomUUID()}}await request(path,pending.current);pending.current=null;setPreview(null);setConfirmed(false);setOutside(false);onChanged()}catch(e){if(e&&typeof e==='object'&&'status'in e&&Number(e.status)>=400&&Number(e.status)<500){pending.current=null;setPreview(null);setConfirmed(false);setOutside(false)}setError(e instanceof Error?e.message:'Release requires review.')}finally{setBusy(false)}}
 return <section aria-label="Unsent bank release" className="space-y-2 rounded border p-3"><p className="font-bold">Release a verified unsent bank instruction</p><p>Release requires explicit proof that no payment creation was attempted and a fresh lookup of the original instruction. Missing payments after uncertain sends do not qualify. All allocation claims must also be resolved as unsent. Release cancels the contribution reservation; any replacement requires a new current remittance authorization.</p><button type="button" disabled={busy||!!pending.current} onClick={()=>void load()} className="rounded border px-3 py-2">Preview unsent bank release</button>{error?<p role="alert">{error}</p>:null}
 {preview?<><p>{preview.eligible?'Eligible for reviewed release':'Release requires reconciliation'} · {preview.observationCount} retained observations · {preview.remoteStatus.replaceAll('_',' ')}</p>{preview.reasons.map(reason=><p key={reason}>{reason}</p>)}</>:null}
 {preview?.eligible?<fieldset disabled={busy||!!pending.current} className="space-y-2"><label className="block">Unsent bank release reference<textarea value={reference} maxLength={2000} onChange={e=>{setReference(e.target.value);setConfirmed(false);setOutside(false)}} className="block w-full rounded border p-2"/></label><label className="flex gap-2"><input type="checkbox" checked={outside} onChange={e=>setOutside(e.target.checked)}/>I independently verified no outside contribution payment, allocation delivery or pending duplicate instruction exists.</label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm release of this verified unsent bank instruction and contribution reservation.</label><button type="button" disabled={!confirmed||!outside||reference.trim().length<20} onClick={()=>void release()} className="rounded border px-3 py-2">Release verified unsent bank</button></fieldset>:null}
 {pending.current?<button type="button" disabled={busy} onClick={()=>void release()} className="rounded border px-3 py-2">Retry original unsent bank release</button>:null}
 </section>
}
