import RetirementReturnRelease from './RetirementReturnRelease'
import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Preview={fingerprint:string;realmId:string;environment:string;payload:{TxnDate:string;DocNumber:string;Line:{Amount:number;JournalEntryLineDetail:{PostingType:string;AccountRef:{value:string}}}[]}}
type Row={release:{reference:string;created_at:string}|null;id:string;reference:string;cancelled_at:string|null;cancellation_reference:string|null;claimed:boolean;journal:{result:{status:string;accountingVerified:boolean}|null}|null;attempts:{id:string;status:string;message:string;created_at:string}[]}
async function request(path:string,body?:unknown){const r=await adminApiRequest(path,body?{method:'POST',body:JSON.stringify(body)}:undefined),j=await r.json();if(!r.ok||!j.success)throw Object.assign(new Error(j.message||'Unable to update return accounting.'),{status:r.status});return j.data}
function Actions({row,onChanged}:{row:Row;onChanged:()=>void}){
 const [reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const act=async(cancel=false)=>{setBusy(true);setError('');try{await request(`/api/admin/payroll/retirement-return-authorizations/${row.id}/${cancel?'cancel':'post'}`,cancel?{confirmed:true,reference:reason}:{confirmed:true,action:row.claimed?'RECOVER':'POST'});setConfirmed(false)}catch(e){setError(e instanceof Error?e.message:'Review return accounting.')}finally{setBusy(false);onChanged()}}
 return <div className="space-y-2">{error?<p role="alert">{error}</p>:null}{row.claimed?<><button type="button" disabled={busy} onClick={()=>void act()} className="rounded border px-3 py-2">Recover retirement return journal</button><RetirementReturnRelease id={row.id} evidenceKey={JSON.stringify(row.journal)} onChanged={onChanged}/></>:<><label className="flex gap-2"><input type="checkbox" disabled={busy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm the selected return accounting action.</label><button type="button" disabled={busy||!confirmed} onClick={()=>void act()} className="rounded border px-3 py-2">Post approved retirement return</button><label className="block">Return approval cancellation reason<textarea className="block w-full rounded border p-2" maxLength={2000} disabled={busy} value={reason} onChange={e=>{setReason(e.target.value);setConfirmed(false)}}/></label><button type="button" disabled={busy||!confirmed||reason.trim().length<12} onClick={()=>void act(true)} className="rounded border px-3 py-2">Cancel unstarted return approval</button></>}</div>
}
export default function RetirementReturnAccounting({id,evidenceKey}:{id:string;evidenceKey:string}){
 const path=`/api/admin/payroll/retirement-remittance-authorizations/${id}`,[preview,setPreview]=useState<Preview|null>(null),[rows,setRows]=useState<Row[]|null>(null),[requested,setRequested]=useState(false),[refresh,setRefresh]=useState(0),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[readError,setReadError]=useState(''),[retry,setRetry]=useState(false),pending=useRef<Record<string,unknown>|null>(null)
 useEffect(()=>{if(!pending.current){setPreview(null);setConfirmed(false)}},[evidenceKey])
 useEffect(()=>{if(!requested)return;let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const data=await request(path+'/return-authorizations');if(live){setRows(data.history);setReadError('')}}catch(e){if(live){setRows(null);setReadError(e instanceof Error?e.message:'Unable to read return history.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[path,requested,refresh])
 const loadPreview=async()=>{setBusy(true);setPreview(null);setConfirmed(false);setError('');try{setPreview(await request(path+'/return-preview',{}));setRequested(true);setRefresh(n=>n+1)}catch(e){setError(e instanceof Error?e.message:'Unable to prepare return accounting.')}finally{setBusy(false)}}
 const approve=async()=>{setBusy(true);setError('');try{if(!pending.current){if(!preview||!confirmed)throw new Error('Review the current return journal.');pending.current={fingerprint:preview.fingerprint,reference,confirmed:true,autoPost:true,outsideAccountingReviewed:true,requestKey:crypto.randomUUID()}}await request(path+'/return-authorizations',pending.current);pending.current=null;setRetry(false);setConfirmed(false);setRefresh(n=>n+1)}catch(e){if(e&&typeof e==='object'&&'status'in e&&Number(e.status)>=400&&Number(e.status)<500){pending.current=null;setPreview(null);setConfirmed(false)}setRetry(!!pending.current);setError(e instanceof Error?e.message:'Retry the original return approval.')}finally{setBusy(false)}}
 return <section aria-label={`Retirement return accounting ${id}`} className="space-y-2 rounded border p-3">
 <h4 className="font-bold">Returned payment accounting</h4><p>Verify the original withdrawals and journals before restoring the liability for a returned credit. Approved journals process automatically; unresolved outcomes retry after five minutes and matching journals recheck daily. This does not send a replacement contribution.</p>
 <div className="flex flex-wrap gap-2"><button type="button" disabled={busy||retry} className="rounded border px-3 py-2" onClick={()=>void loadPreview()}>Prepare retirement return preview</button><button type="button" className="rounded border px-3 py-2" onClick={()=>{setRequested(true);setRefresh(n=>n+1)}}>Load retirement return history</button></div>
 {error?<p role="alert">{error}</p>:null}{readError?<p role="alert">{readError} Automatic refresh will retry.</p>:null}
 {preview?<div className="space-y-1 rounded border p-2"><p>Company {preview.realmId} · {preview.environment} · Credit date {preview.payload.TxnDate}</p><p className="break-all">Proposed journal: {preview.payload.DocNumber}</p>{preview.payload.Line.map((l,i)=><p key={i}>{l.JournalEntryLineDetail.PostingType} account {l.JournalEntryLineDetail.AccountRef.value}: {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(l.Amount)}</p>)}</div>:null}
 {preview&&rows&&!rows.some(r=>!r.cancelled_at)?<fieldset disabled={busy||retry} className="space-y-2"><label className="block">Retirement return approval reference<textarea className="block w-full rounded border p-2" maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I approve automatic posting of this exact return journal and verified no duplicate outside accounting exists.</label><button type="button" disabled={!confirmed||reference.trim().length<12} className="rounded border px-3 py-2" onClick={()=>void approve()}>Authorize retirement return accounting</button></fieldset>:null}
 {retry?<button type="button" disabled={busy} className="rounded border px-3 py-2" onClick={()=>void approve()}>Retry original retirement return approval</button>:null}
 {rows?.map(row=><article key={row.id} className="space-y-2 rounded border p-2"><p>{row.cancelled_at?'CANCELLED':row.claimed?'CLAIMED':'AUTHORIZED'} · {row.reference}</p>{row.release?<p>Verified unsent return accounting release · {new Date(row.release.created_at).toLocaleString()} · {row.release.reference}</p>:null}{row.cancellation_reference?<p>Cancellation: {row.cancellation_reference}</p>:null}{row.journal?<><p>Return journal: {row.journal.result?.status.replaceAll('_',' ')||'UNVERIFIED'}</p><p>Source verification: {row.journal.result?.accountingVerified?'MATCHED':'REVIEW REQUIRED'}</p></>:null}{row.attempts.map(a=><p key={a.id}>Automatic return processing: {a.status.replaceAll('_',' ')} · {new Date(a.created_at).toLocaleString()} · {a.message}</p>)}{!row.cancelled_at?<Actions row={row} onChanged={()=>setRefresh(n=>n+1)}/>:null}</article>)}
 </section>
}
