import RetirementSettlementAuthorization from './RetirementSettlementAuthorization'
import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Preview={fingerprint:string;sourceJournalId:string;realmId:string;environment:string;journals:{payload:{TxnDate:string;DocNumber:string;Line:{Amount:number;JournalEntryLineDetail:{PostingType:string;AccountRef:{value:string}}}[]}}[]}
export default function RetirementSettlementPreview({id}:{id:string}){
 const [data,setData]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=async()=>{setBusy(true);setData(null);setError('');try{const r=await adminApiRequest(`/api/admin/payroll/retirement-remittance-authorizations/${id}/settlement-preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Unable to prepare settlement accounting.');setData(j.data)}catch(e){setError(e instanceof Error?e.message:'Unable to verify settlement evidence.')}finally{setBusy(false)}}
 return <section aria-label={`Retirement settlement preview ${id}`} className="space-y-2 rounded border p-3"><p className="font-bold">Retirement settlement accounting</p><p>Verify the original payroll journal, current bank withdrawals and reviewed accounts. This preview does not authorize or post a journal; later posting requires fresh verification.</p><button type="button" disabled={busy} onClick={()=>void load()} className="rounded border px-3 py-2">Prepare retirement settlement preview</button>{error?<p role="alert">{error}</p>:null}{data?<><p>Verified payroll journal {data.sourceJournalId} · Company {data.realmId} · {data.environment}</p>{data.journals.map(j=><article key={j.payload.DocNumber} className="space-y-1 rounded border p-2"><p>Bank posting date: {j.payload.TxnDate}</p><p className="break-all">Proposed journal: {j.payload.DocNumber}</p>{j.payload.Line.map((l,i)=><p key={i}>{l.JournalEntryLineDetail.PostingType} account {l.JournalEntryLineDetail.AccountRef.value}: {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(l.Amount)}</p>)}</article>)}</>:null}<RetirementSettlementAuthorization id={id} fingerprint={data?.fingerprint}/></section>
}
