import RetirementSettlementRelease from './RetirementSettlementRelease'
import {useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Row={release:{created_at:string;reference:string}|null;attempts:{id:string;status:string;message:string;created_at:string}[];id:string;claimed:boolean;cancelled_at:string|null;reference:string;journals:{id:string;result:{status:string;journalId?:string}|null}[]}
async function request(path:string,body?:unknown){const r=await adminApiRequest(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),j=await r.json();if(!r.ok||!j.success)throw Object.assign(new Error(j.message||'Unable to retain settlement action.'),{status:r.status});return j.data}
function Actions({row,onChanged}:{row:Row;onChanged:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false)
 const act=async(cancel=false)=>{setBusy(true);setError('');try{await request(`/api/admin/payroll/retirement-settlement-authorizations/${row.id}/${cancel?'cancel':'post'}`,cancel?{reference,confirmed:true}:{action:row.claimed?'RECOVER':'POST',confirmed:true});setConfirmed(false)}catch(e){setError(e instanceof Error?e.message:'Review settlement history.')}finally{setBusy(false);onChanged()}}
 return <div className="space-y-2">{error?<p role="alert">{error}</p>:null}{row.claimed?<button type="button" disabled={busy} onClick={()=>void act()} className="rounded border px-3 py-2">Recover retirement settlement journals</button>:<><label className="flex gap-2"><input type="checkbox" disabled={busy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm the retained retirement settlement posting action.</label><button type="button" disabled={busy||!confirmed} onClick={()=>void act()} className="rounded border px-3 py-2">Post authorized retirement settlement</button><label className="block">Settlement cancellation reason<textarea disabled={busy} value={reference} onChange={e=>setReference(e.target.value)} className="block w-full rounded border p-2" maxLength={2000}/></label><button type="button" disabled={busy||!confirmed||reference.trim().length<12} onClick={()=>void act(true)} className="rounded border px-3 py-2">Cancel unstarted retirement settlement</button></>}</div>
}
export default function RetirementSettlementAuthorization({id,fingerprint}:{id:string;fingerprint?:string}){
 const path=`/api/admin/payroll/retirement-remittance-authorizations/${id}/settlement-authorizations`,[requested,setRequested]=useState(false),[rows,setRows]=useState<Row[]|null>(null),[refresh,setRefresh]=useState(0),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[readError,setReadError]=useState(''),pending=useRef<Record<string,unknown>|null>(null)
 useEffect(()=>setConfirmed(false),[fingerprint])
 useEffect(()=>{if(!requested)return;let live=true,inFlight=false;const load=async()=>{if(inFlight)return;inFlight=true;try{const data=await request(path);if(live){setRows(data.history);setReadError('')}}catch(e){if(live){setRows(null);setReadError(e instanceof Error?e.message:'Unable to read settlement history.')}}finally{inFlight=false}};void load();const timer=setInterval(()=>void load(),30000);return()=>{live=false;clearInterval(timer)}},[path,refresh,requested])
 const save=async()=>{setBusy(true);setError('');try{if(!pending.current){if(!fingerprint||!confirmed)throw new Error('Review the current settlement preview.');pending.current={fingerprint,reference,confirmed:true,autoPost:true,requestKey:crypto.randomUUID()}}await request(path,pending.current);pending.current=null;setConfirmed(false);setRefresh(n=>n+1)}catch(e){if(e&&typeof e==='object'&&'status'in e&&Number(e.status)>=400&&Number(e.status)<500)pending.current=null;setError(e instanceof Error?e.message:'Retry original settlement authorization.')}finally{setBusy(false)}}
 return <section aria-label={`Retirement settlement authorization ${id}`} className="space-y-2 border-t pt-3"><p className="font-bold">Settlement authorization and history</p><p>Approved settlements process automatically. Unresolved attempts retry after five minutes; matching journals are checked daily. Recovery never creates a replacement journal.</p><button type="button" disabled={busy} onClick={()=>{setRequested(true);setRefresh(n=>n+1)}} className="rounded border px-3 py-2">Load retirement settlement history</button>{readError?<p role="alert">{readError}</p>:null}{error?<p role="alert">{error}</p>:null}{rows&&!rows.some(r=>!r.cancelled_at)?<fieldset disabled={busy||!!pending.current||!fingerprint} className="space-y-2"><label className="block">Retirement settlement approval reference<textarea value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} maxLength={2000} className="block w-full rounded border p-2"/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I approve the exact proposed journals and verified no duplicate outside settlement accounting exists.</label><button type="button" disabled={!confirmed||reference.trim().length<12} onClick={()=>void save()} className="rounded border px-3 py-2">Authorize retirement settlement</button></fieldset>:null}{pending.current?<button type="button" disabled={busy} onClick={()=>void save()} className="rounded border px-3 py-2">Retry original retirement settlement approval</button>:null}{rows?.map(row=><article key={row.id} className="space-y-2 rounded border p-2"><p>{row.cancelled_at?'CANCELLED':row.claimed?'CLAIMED':'AUTHORIZED'} · {row.reference}</p>{row.attempts.map(attempt=><p key={attempt.id}>Automatic processing: {attempt.status.replaceAll('_',' ')} · {new Date(attempt.created_at).toLocaleString()} · {attempt.message}</p>)}{row.journals.map(j=><p key={j.id}>Journal outcome: {j.result?.status.replaceAll('_',' ')||'UNVERIFIED'}{j.result?.journalId?` · QuickBooks ${j.result.journalId}`:''}</p>)}{row.release?<p>Unsent release retained · {new Date(row.release.created_at).toLocaleString()} · {row.release.reference}</p>:null}{!row.cancelled_at?<><Actions row={row} onChanged={()=>setRefresh(n=>n+1)}/>{row.claimed?<RetirementSettlementRelease id={row.id} evidenceKey={JSON.stringify(row.journals)} onChanged={()=>setRefresh(n=>n+1)}/>:null}</>:null}</article>)}</section>
}
