import './retirementWorkspace.css'
import RetirementSettlementMapping from './RetirementSettlementMapping'
import RetirementReceiptContract from './RetirementReceiptContract'
import RetirementSftpSetup from './RetirementSftpSetup'
import RetirementAllocationFormat from './RetirementAllocationFormat'
import RetirementTiming from './RetirementTiming'
import RetirementDestination from './RetirementDestination'
import RetirementRemittanceSources from './RetirementRemittanceSources'
import RetirementProcessingReview from './RetirementProcessingReview'
import {useCallback,useEffect,useRef,useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type UnusedPto={inServiceDeferrals:string;postSeveranceDeferrals:string;postSeverance415:string;limitationYear:string;terms:string}
type Plan={unusedPto?:UnusedPto;planId:string;name:string;providerName:string;effectiveOn:string;planReference:string;eligibilityTerms:string;compensationTerms:string;employeeTerms:string;reviewReference:string;allowsPretax:boolean;allowsRoth:boolean;allowsCatchUp:boolean;allowsHigherCatchUp:boolean;automaticEnrollment:string;automaticEnrollmentTerms?:string;employerContributions:string;employerContributionTerms?:string;compensation:Record<string,boolean>;planOrdinaryDeferralLimitCents:number|null;planCatchUpLimitCents:number|null}
type Revision={id:string;planId:string;revision:number;effectiveOn:string;plan:Plan;createdAt:string}
const flags=[['allowsPretax','Pretax deferrals'],['allowsRoth','Roth deferrals'],['allowsCatchUp','Catch-up contributions'],['allowsHigherCatchUp','Higher age-based catch-up']] as const
const compensation=[['REGULAR','Regular wages'],['OVERTIME','Overtime wages'],['BONUS','Bonuses'],['PAID_LEAVE','Paid leave']] as const
const ptoTreatments=[['inServiceDeferrals','Unused PTO deferrals while employed'],['postSeveranceDeferrals','Unused PTO deferrals after employment ends'],['postSeverance415','Post-employment unused PTO in section 415 compensation']] as const
const ptoLabels:Record<string,string>={INCLUDED:'Included',EXCLUDED:'Excluded',REVIEW_REQUIRED:'Requires further review',CALENDAR_YEAR:'Calendar year',NON_CALENDAR_YEAR:'Non-calendar year'}
const texts=[['planId','Retirement plan identifier'],['name','Retirement plan name'],['providerName','Retirement recordkeeper'],['planReference','Retained plan document reference']] as const
const terms=[['eligibilityTerms','Eligibility and entry-date terms'],['compensationTerms','Eligible compensation definition'],['employeeTerms','Employee election and withdrawal terms'],['reviewReference','Administrator review reference']] as const
const inputClass='mt-1 block w-full rounded-lg border border-slate-300 p-2'
// Plan review history is distinct from participant eligibility and execution.
export default function RetirementPlanSetup(){
 const [history,setHistory]=useState<Revision[]>([]),[requested,setRequested]=useState(false),[loaded,setLoaded]=useState(false),[form,setForm]=useState<Record<string,string>>({}),[expected,setExpected]=useState(0),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refreshIssue,setRefreshIssue]=useState(''),[message,setMessage]=useState(''),pending=useRef<{body:string;key:string}|null>(null)
 const read=useCallback(async()=>{const response=await adminApiRequest('/api/admin/payroll/retirement-plans'),body=await response.json();if(!response.ok||!body.success)throw new Error(body.message||'Unable to load retirement plans.');return body.data.history as Revision[]},[])
 useEffect(()=>{if(!requested||busy)return;let live=true,inFlight=false;const timer=setInterval(()=>{if(inFlight)return;inFlight=true;void read().then(rows=>{if(live){setHistory(rows);setLoaded(true);setRefreshIssue('')}}).catch(()=>{if(live)setRefreshIssue('Plan history could not refresh. Automatic refresh will retry.')}).finally(()=>{inFlight=false})},30000);return()=>{live=false;clearInterval(timer)}},[requested,busy,read])
 const load=async()=>{setRequested(true);setBusy(true);setError('');try{setHistory(await read());setLoaded(true);setRefreshIssue('')}catch(e){setRefreshIssue(e instanceof Error?e.message:'Unable to load retirement plans.')}finally{setBusy(false)}}
 const set=(key:string,value:string)=>{setForm(current=>({...current,[key]:value}));setConfirmed(false);if(key==='planId')setExpected(0)}
 const edit=(row:Revision)=>{const values:Record<string,string>={};for(const [key,value] of Object.entries(row.plan)){if(typeof value==='string'||typeof value==='boolean')values[key]=String(value)}if(row.plan.unusedPto){values['pto-review']='REVIEWED';for(const [key,value] of Object.entries(row.plan.unusedPto))values[`pto-${key}`]=value}for(const [key,value] of Object.entries(row.plan.compensation))values[`comp-${key}`]=String(value);for(const key of ['planOrdinaryDeferralLimitCents','planCatchUpLimitCents'] as const){values[`${key}-mode`]=row.plan[key]===null?'NONE':'LIMIT';values[key]=row.plan[key]===null?'':String(row.plan[key]/100)}setForm(values);setExpected(row.revision);setConfirmed(false);setMessage('');setError('');pending.current=null}
 const current=history.find(row=>row.planId===form.planId),stale=(current?.revision||0)!==expected
 const cap=(key:string)=>form[`${key}-mode`]==='NONE'?null:form[`${key}-mode`]==='LIMIT'&&form[key]?.trim()?Math.round(Number(form[key])*100):undefined
 const save=async(retry=false)=>{setBusy(true);setError('');setMessage('');try{
  const plan={...form,...(form['pto-review']==='REVIEWED'?{unusedPto:Object.fromEntries(['inServiceDeferrals','postSeveranceDeferrals','postSeverance415','limitationYear','terms'].map(key=>[key,form[`pto-${key}`]||'']))}:{}),taxYear:2026,planType:'STANDARD_401K',confirmed,...Object.fromEntries(flags.map(([key])=>[key,form[key]==='true'?true:form[key]==='false'?false:null])),compensation:Object.fromEntries(compensation.map(([key])=>[key,form[`comp-${key}`]==='true'?true:form[`comp-${key}`]==='false'?false:null])),planOrdinaryDeferralLimitCents:cap('planOrdinaryDeferralLimitCents'),planCatchUpLimitCents:form.allowsCatchUp==='false'?0:cap('planCatchUpLimitCents')},input=retry&&pending.current?JSON.parse(pending.current.body):{plan,expectedRevision:expected},serialized=JSON.stringify(input)
  if(pending.current?.body!==serialized)pending.current={body:serialized,key:crypto.randomUUID()}
  const response=await adminApiRequest('/api/admin/payroll/retirement-plans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,requestKey:pending.current.key})}),body=await response.json();if(!response.ok||!body.success)throw new Error(body.message||'Unable to retain retirement plan review.')
  const rows=await read();setHistory(rows);setExpected(rows.find(row=>row.planId===form.planId)?.revision||0);setConfirmed(false);setMessage('Plan review retained. This does not activate payroll deductions or provider remittance.');pending.current=null
 }catch(e){setError(e instanceof Error?e.message:'Unable to retain retirement plan review.')}finally{setBusy(false)}}
 return <section aria-label="Retirement plan setup" className="payroll-retirement-workspace space-y-4 text-sm"><p>Retain actual 2026 standard 401(k) plan terms before participant setup. A plan review does not establish legal adoption, activate deductions or transmit contributions.</p><button type="button" disabled={busy} onClick={()=>void load()} className="rounded border px-3 py-2 font-bold">Load retirement plan history</button>{error?<p role="alert">{error}</p>:null}{refreshIssue?<p role="alert">{refreshIssue}</p>:null}{message?<p role="status">{message}</p>:null}{pending.current?<button type="button" disabled={busy} onClick={()=>void save(true)} className="rounded border px-3 py-2 font-bold">Retry the original plan review</button>:null}
 {loaded?<><RetirementRemittanceSources/>{[...new Set(history.map(row=>row.planId))].map(planId=><div key={planId} className="space-y-3"><RetirementProcessingReview planId={planId}/><RetirementDestination planId={planId}/><RetirementTiming planId={planId}/><RetirementAllocationFormat planId={planId}/><RetirementSftpSetup planId={planId}/><RetirementReceiptContract planId={planId}/><RetirementSettlementMapping planId={planId}/></div>)}<div className="space-y-2">{history.map(row=><details key={row.id} className="rounded border p-3"><summary className="font-bold">{row.plan.name} · Revision {row.revision} · Effective {row.effectiveOn}</summary><p>{row.plan.providerName} · {new Date(row.createdAt).toLocaleString()}</p>{terms.map(([key,label])=><p key={key} className="whitespace-pre-wrap break-words"><strong>{label}:</strong> {row.plan[key]}</p>)}{row.plan.unusedPto?<div className="mt-2 space-y-1">{ptoTreatments.map(([key,label])=><p key={key}><strong>{label}:</strong> {ptoLabels[row.plan.unusedPto![key]]}</p>)}<p><strong>Plan limitation year:</strong> {ptoLabels[row.plan.unusedPto.limitationYear]}</p><p className="whitespace-pre-wrap break-words"><strong>Unused PTO plan terms:</strong> {row.plan.unusedPto.terms}</p></div>:<p>Unused PTO payout terms have not been reviewed.</p>}<button type="button" disabled={busy} onClick={()=>edit(row)} className="mt-2 rounded border px-3 py-2">Edit from this retained revision</button></details>)}</div>
 <button type="button" disabled={busy} onClick={()=>{setForm({});setExpected(0);setConfirmed(false);pending.current=null}} className="rounded border px-3 py-2">Start a new plan review</button>{stale?<p role="alert">A newer plan revision is retained. Your draft is preserved; review and select the latest retained revision before saving.</p>:null}
 <fieldset disabled={busy||stale||!!refreshIssue} className="grid gap-3 sm:grid-cols-2"><legend className="font-bold">Reviewed plan configuration</legend>{texts.map(([key,label])=><label key={key}>{label}<input value={form[key]||''} onChange={e=>set(key,e.target.value)} maxLength={key==='planReference'?2000:200} className={inputClass}/></label>)}<label>Plan effective date<input type="date" value={form.effectiveOn||''} onChange={e=>set('effectiveOn',e.target.value)} className={inputClass}/></label>
 {flags.map(([key,label])=><label key={key}>{label}<select value={form[key]||''} onChange={e=>set(key,e.target.value)} className={inputClass}><option value="">Review plan terms</option><option value="true">Permitted</option><option value="false">Not permitted</option></select></label>)}{compensation.map(([key,label])=><label key={key}>{label} in plan compensation<select value={form[`comp-${key}`]||''} onChange={e=>set(`comp-${key}`,e.target.value)} className={inputClass}><option value="">Review definition</option><option value="true">Included</option><option value="false">Excluded</option></select></label>)}
 <div className="space-y-3 rounded-lg border p-3 sm:col-span-2"><p className="font-bold">Unused PTO payouts</p><p>Review cashout terms separately from paid leave taken. Post-employment payouts also require payment timing and leave eligibility evidence before processing.</p><label className="block">Unused PTO payout terms<select value={form['pto-review']||'UNREVIEWED'} onChange={e=>set('pto-review',e.target.value)} className={inputClass}><option value="UNREVIEWED">Not yet reviewed</option><option value="REVIEWED">Record plan terms and unresolved items</option></select></label>{form['pto-review']==='REVIEWED'?<>{ptoTreatments.map(([key,label])=><label className="block" key={key}>{label}<select value={form[`pto-${key}`]||''} onChange={e=>set(`pto-${key}`,e.target.value)} className={inputClass}><option value="">Review plan treatment</option>{['INCLUDED','EXCLUDED','REVIEW_REQUIRED'].map(value=><option key={value} value={value}>{ptoLabels[value]}</option>)}</select></label>)}<label className="block">Plan limitation year<select value={form['pto-limitationYear']||''} onChange={e=>set('pto-limitationYear',e.target.value)} className={inputClass}><option value="">Review plan year</option>{['CALENDAR_YEAR','NON_CALENDAR_YEAR','REVIEW_REQUIRED'].map(value=><option key={value} value={value}>{ptoLabels[value]}</option>)}</select></label><label className="block">Unused PTO plan terms and document reference<textarea value={form['pto-terms']||''} onChange={e=>set('pto-terms',e.target.value)} maxLength={4000} rows={3} className={inputClass}/></label></>:null}</div>
 <label>Automatic enrollment applicability<select value={form.automaticEnrollment||''} onChange={e=>set('automaticEnrollment',e.target.value)} className={inputClass}><option value="">Review applicability</option><option value="NOT_APPLICABLE">Not applicable</option><option value="APPLICABLE">Applicable</option><option value="UNRESOLVED">Requires further review</option></select></label><label>Employer contributions<select value={form.employerContributions||''} onChange={e=>set('employerContributions',e.target.value)} className={inputClass}><option value="">Review contribution terms</option>{['NONE','MATCH','NONELECTIVE','MATCH_AND_NONELECTIVE','UNRESOLVED'].map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label>
 {(['planOrdinaryDeferralLimitCents','planCatchUpLimitCents'] as const).filter(key=>key!=='planCatchUpLimitCents'||form.allowsCatchUp!=='false').map(key=><label key={key}>{key==='planOrdinaryDeferralLimitCents'?'Additional ordinary deferral dollar cap':'Plan catch-up dollar cap'}<select value={form[`${key}-mode`]||''} onChange={e=>set(`${key}-mode`,e.target.value)} className={inputClass}><option value="">Review plan cap</option><option value="NONE">No additional plan dollar cap</option><option value="LIMIT">Reviewed annual dollar cap</option></select>{form[`${key}-mode`]==='LIMIT'?<input aria-label={`${key==='planOrdinaryDeferralLimitCents'?'Ordinary':'Catch-up'} annual plan cap ($)`} type="number" min="0" step="0.01" value={form[key]||''} onChange={e=>set(key,e.target.value)} className={inputClass}/>:null}</label>)}
 {[...terms,...(form.automaticEnrollment&&form.automaticEnrollment!=='NOT_APPLICABLE'?[['automaticEnrollmentTerms','Automatic enrollment terms / review']] as const:[]),...(form.employerContributions&&form.employerContributions!=='NONE'?[['employerContributionTerms','Employer contribution formula / review']] as const:[])].map(([key,label])=><label key={key} className="sm:col-span-2">{label}<textarea value={form[key]||''} onChange={e=>set(key,e.target.value)} maxLength={key==='reviewReference'?2000:4000} rows={3} className={inputClass}/></label>)}<label className="flex items-start gap-2 sm:col-span-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I reviewed these plan terms and retained supporting evidence. Unresolved features require further implementation and review.</span></label><button type="button" disabled={!confirmed} onClick={()=>void save()} className="rounded border px-3 py-2 font-bold">Retain retirement plan review</button></fieldset></>:null}</section>
}
