import SalaryChangeCancellation from './SalaryChangeCancellation'
import {useEffect,useState} from 'react'
import {payrollApi,type PayrollEmployee} from '../../utils/payrollApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'

export default function SalaryReview({employee,onChanged,onOfferChange}:{employee:PayrollEmployee;onChanged:()=>Promise<void>;onOfferChange?:(body:Record<string,unknown>)=>Promise<void>}){
 const [scheduled,setScheduled]=useState(false),[history,setHistory]=useState<Awaited<ReturnType<typeof payrollApi.salaryChanges>>>([])
 useEffect(()=>{payrollApi.salaryChanges(employee.id).then(setHistory).catch(e=>setError(e instanceof Error?e.message:'Unable to load salary history'))},[employee.id])
 const saved=employee.salaryReview
 const [normalHours,setNormalHours]=useState((saved?.normalWorkweekMinutes||[0,480,480,480,480,480,0]).map(v=>String(v/60)))
 const [form,setForm]=useState({effectiveOn:'',noticeDeliveredOn:'',noticeReference:'',reason:'',noticeConfirmed:false,annualSalary:String(Number(employee.annualSalaryCents)/100),jobTitle:saved?.jobTitle||employee.jobTitle,classification:saved?.classification||'NONEXEMPT',category:saved?.category==='NONE'?'ADMINISTRATIVE':saved?.category||'ADMINISTRATIVE',source:saved?.source||'',dutiesEvidence:saved?.dutiesEvidence||'',salaryBasisVerified:false,dutiesVerified:false,stateRulesVerified:false,confirmed:false,fixedHoursVerified:false,standardWeeklyHours:String(saved?.classification==='NONEXEMPT'?saved.standardWeeklyHours:40),minimumWageVerified:false,minimumWage:String(Number(saved?.minimumWageCents||1500)/100)})
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const change=(key:keyof typeof form,value:string|boolean)=>setForm(current=>({...current,[key]:value,confirmed:false}))
 return <section className="rounded-2xl border border-slate-200 bg-white p-5">
  <h2 className="text-xl font-black">{onOfferChange?'Review new salary offer':'Salary classification review'}</h2>
  <p className="mt-2 text-sm text-slate-600">{employee.legalFirstName} {employee.legalLastName} · {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(employee.annualSalaryCents)/100)} annually. Salary alone does not establish an overtime exemption. Review the actual duties and salary agreement.</p>
  {saved?<p className="mt-2 text-sm">Recorded classification: {saved.classification} · reviewed {saved.verifiedAt?.slice(0,10)}</p>:null}
  {['ACTIVE','LEAVE'].includes(employee.employmentStatus)?<button type="button" className={`${workforceButton} mt-3`} onClick={()=>{setScheduled(!scheduled);setForm(current=>({...current,confirmed:false,noticeConfirmed:false}))}}>{scheduled?'Return to classification review':'Schedule a dated salary change'}</button>:null}
  {history.length?<div className="mt-3 space-y-1 text-sm"><h3 className="font-bold">Salary history</h3>{history.map(row=><div key={row.id}><p>{row.effective_on.slice(0,10)} · {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(row.annual_salary_cents)/100)} annually{row.cancelled_at?' · cancelled':''}</p><p className="text-slate-600">{row.reason}</p>{row.notice_delivered_on?<p className="text-slate-600">Written notice: {row.notice_delivered_on.slice(0,10)} · {row.notice_reference}</p>:null}{row.cancelled_at?<p className="text-slate-600">Cancellation: {row.cancellation_reason} · notice {row.cancellation_notice_delivered_on?.slice(0,10)} · {row.cancellation_notice_reference}</p>:null}{row.notice_delivered_on?<p className="text-slate-600">Employee receipt: {row.acknowledged_at?row.acknowledged_at.slice(0,10):'pending'}{row.cancelled_at?` · cancellation receipt: ${row.cancellation_acknowledged_at?.slice(0,10)||'pending'}`:''}</p>:null}{row.canCancel?<SalaryChangeCancellation employeeId={employee.id} changeId={row.id} effectiveOn={row.effective_on.slice(0,10)} onChanged={async()=>{setHistory(await payrollApi.salaryChanges(employee.id));await onChanged()}}/>:null}</div>)}</div>:null}
  <form className="mt-4 space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{const body={...form,employmentStart:employee.hireDate.slice(0,10),standardWeeklyHours:Number(form.standardWeeklyHours),...(form.classification==='EXEMPT'?{normalWorkweekMinutes:normalHours.map(v=>Number(v)*60)}:{}),annualSalaryCents:Math.round(Number(form.annualSalary)*100),minimumWageCents:Math.round(Number(form.minimumWage)*100)};if(onOfferChange){await onOfferChange(body)}else if(scheduled){await payrollApi.scheduleSalaryChange(employee.id,body);setHistory(await payrollApi.salaryChanges(employee.id))}else {await payrollApi.saveSalaryReview(employee.id,body);setHistory(await payrollApi.salaryChanges(employee.id))}await onChanged();setForm(current=>({...current,confirmed:false}));setMessage(scheduled?'Salary change scheduled and audited. Earlier payroll retains its original salary.':'Salary classification saved and audited. Complete the remaining pay setup review in onboarding.')}catch(e){setError(e instanceof Error?e.message:'Unable to save classification')}finally{setBusy(false)}}}>
   {scheduled?<div className="space-y-3"><h3 className="font-bold">Future salary change</h3><p className="text-sm text-slate-600">Generate the future payroll calendar first, then choose an open pay-period start. Nonexempt changes must also begin a workweek. Repeat the classification review below for the new salary.</p><label className="block text-sm font-bold">Salary effective date<input required type="date" className={workforceInput} value={form.effectiveOn} onChange={e=>change('effectiveOn',e.target.value)}/></label><label className="block text-sm font-bold">Salary notice delivered on<input required type="date" className={workforceInput} value={form.noticeDeliveredOn} onChange={e=>change('noticeDeliveredOn',e.target.value)}/></label><label className="block text-sm font-bold">Salary notice delivery reference<input required minLength={12} className={workforceInput} value={form.noticeReference} onChange={e=>change('noticeReference',e.target.value)}/></label><label className="block text-sm font-bold">Salary change reason<input required minLength={12} className={workforceInput} value={form.reason} onChange={e=>change('reason',e.target.value)}/></label><label className="flex gap-2 text-sm"><input required type="checkbox" checked={form.noticeConfirmed} onChange={e=>change('noticeConfirmed',e.target.checked)}/>I confirm written notice was delivered on the recorded date.</label></div>:null}
   <label className="block text-sm font-bold">Reviewed annual salary ($)<input required disabled={!scheduled&&employee.employmentStatus!=='ONBOARDING'} type="number" min="0.01" step="0.01" className={workforceInput} value={form.annualSalary} onChange={e=>change('annualSalary',e.target.value)}/></label>
   {!scheduled?<p className="text-sm text-slate-600">During onboarding, correct the offer amount here and repeat this review. Changes to salary, title or classification require a fresh employee wage acknowledgment. Rehire agreements take effect on the new hire date and retain earlier salary history.</p>:null}
   <label className="block text-sm font-bold">Reviewed job title<input required className={workforceInput} value={form.jobTitle} onChange={e=>change('jobTitle',e.target.value)}/></label>
   <label className="block text-sm font-bold">Overtime classification<select className={workforceInput} value={form.classification} onChange={e=>change('classification',e.target.value)}><option value="NONEXEMPT">Nonexempt — overtime eligible</option><option value="EXEMPT">Exempt — verified duties and salary basis</option></select></label>
   {form.classification==='EXEMPT'?<>
    <label className="block text-sm font-bold">Exemption category<select className={workforceInput} value={form.category} onChange={e=>change('category',e.target.value)}><option value="EXECUTIVE">Executive</option><option value="ADMINISTRATIVE">Administrative</option><option value="LEARNED_PROFESSIONAL">Learned professional</option><option value="CREATIVE_PROFESSIONAL">Creative professional</option></select></label>
    <p className="text-sm text-slate-600">Standard Maryland review requires at least $684 per week ($35,568 annualized), a qualifying salary basis and qualifying duties. <a className="underline" href="https://www.labor.maryland.gov/labor/wagepay/wpsalaried.shtml" target="_blank" rel="noreferrer">Maryland exemption guidance</a></p>
    <fieldset className="rounded-xl border border-slate-200 p-3"><legend className="text-sm font-bold">Normal workweek for sick leave</legend><p className="text-sm text-slate-600">Record the normal daily hours used for leave accrual. Use the shorter normal week when below 40 hours; otherwise allocate 40 hours across the normal workdays. This does not reduce salary or the exemption salary threshold.</p><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((label,i)=><label key={label} className="block text-sm font-bold">{label} leave-basis hours<input required type="number" min="0" max="24" step="0.25" className={workforceInput} value={normalHours[i]} onChange={e=>{setNormalHours(current=>current.map((v,index)=>index===i?e.target.value:v));setForm(current=>({...current,confirmed:false}))}}/></label>)}</div><p className="mt-2 text-sm font-bold">Weekly leave basis: {normalHours.reduce((sum,v)=>sum+Number(v),0)} hours (maximum 40)</p></fieldset>
    <label className="block text-sm font-bold">Duties assessment<textarea required minLength={40} rows={3} className={workforceInput} value={form.dutiesEvidence} onChange={e=>change('dutiesEvidence',e.target.value)}/></label>
    {([['salaryBasisVerified','I verified the salary basis agreement and permitted deduction rules.'],['dutiesVerified','I verified the actual duties meet the selected exemption test.'],['stateRulesVerified','I verified applicable Maryland exemption requirements.']] as const).map(([key,label])=><label key={key} className="flex gap-2 text-sm"><input type="checkbox" checked={form[key]} onChange={e=>change(key,e.target.checked)}/>{label}</label>)}
   </>:<div className="space-y-3"><p className="text-sm text-slate-600">Fixed salary covers the agreed weekly hours. Additional work up to 40 hours receives straight-time pay; work beyond 40 receives additional time-and-a-half; paid leave is included in the base salary. Verify local minimum wages for every work location.</p><label className="block text-sm font-bold">Weekly hours covered by salary<input required type="number" min="0.25" max="40" step="0.25" className={workforceInput} value={form.standardWeeklyHours} onChange={e=>change('standardWeeklyHours',e.target.value)}/></label><label className="block text-sm font-bold">Applicable minimum wage ($/hour)<input required type="number" min="15" step="0.01" className={workforceInput} value={form.minimumWage} onChange={e=>change('minimumWage',e.target.value)}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.fixedHoursVerified} onChange={e=>change('fixedHoursVerified',e.target.checked)}/>I verified the salary agreement covers a fixed {form.standardWeeklyHours}-hour workweek.</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.minimumWageVerified} onChange={e=>change('minimumWageVerified',e.target.checked)}/>I verified the applicable state and local minimum wage for this employee.</label></div>}
   <label className="block text-sm font-bold">Classification evidence reference<textarea required minLength={20} rows={2} className={workforceInput} value={form.source} onChange={e=>change('source',e.target.value)}/></label>
   <label className="flex gap-2 text-sm"><input type="checkbox" checked={form.confirmed} onChange={e=>setForm(current=>({...current,confirmed:e.target.checked}))}/>I confirm this classification and its supporting evidence.</label>
   <button disabled={busy||!form.confirmed} className={workforceButton}>{onOfferChange?'Change offer to salary':scheduled?'Schedule reviewed salary change':'Save salary classification'}</button>
  </form>
  {error?<p role="alert" className="mt-3 text-red-700">{error}</p>:null}{message?<p role="status" className="mt-3 text-emerald-700">{message}</p>:null}
 </section>
}
