import AuthorizedSettlementReview from './AuthorizedSettlementReview'
type Row=Record<string,unknown>
const money=(value:unknown)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value||0)/100)
export default function SplitCompensationReview({snapshot}:{snapshot:unknown}){
 const employees=snapshot&&typeof snapshot==='object'?(snapshot as Row).employees:null
 const rows:Row[]=Array.isArray(employees)?employees.filter((row):row is Row=>!!row&&typeof row==='object'&&Array.isArray(row.splitCompensation)&&row.splitCompensation.length>0):[]
 if(!rows.length)return <AuthorizedSettlementReview snapshot={snapshot}/>
 return <><AuthorizedSettlementReview snapshot={snapshot}/><section aria-label="Pay by employment agreement" className="mt-4 space-y-3"><h4 className="font-black">Pay by employment agreement</h4><p className="text-sm text-slate-600">Earnings from each hiring period are combined for one tax calculation. Paid leave within a salary agreement is included in salary.</p>{rows.map((row,index)=><article key={String(row.employeeId??index)} className="space-y-3 rounded-xl border border-slate-200 p-4 text-sm"><p className="font-bold">{String(row.employeeName||'Employment earnings')}</p>{(row.splitCompensation as Row[]).map(portion=>{const salary=portion.salaryCalculation as Row|null;const rates=Array.isArray(portion.rateBreakdown)?portion.rateBreakdown as Row[]:[];return <div key={String(portion.employmentStart)} className="border-t border-slate-200 pt-3"><p className="font-bold">{portion.payType==='SALARY'?'Salary':'Hourly'} · {String(portion.start)} through {String(portion.end)}</p><p className="mt-1">Regular wages: {money(portion.regularPayCents)} · Overtime: {money(portion.overtimePayCents)}</p>{salary?<><p className="mt-1">{money(salary.annualSalaryCents)} annually ÷ {Number(salary.periodsPerYear)} pay periods. Full scheduled salary is preserved.</p>{salary.classification==='NONEXEMPT'?<p className="mt-1">Salary covers {Number(salary.standardWeeklyHours)||40} hours per week. Additional straight-time pay: {money(salary.extraStraightTimePayCents)}.</p>:null}</>:rates.map((rate,i)=><p key={i} className="mt-1">{money(rate.hourlyRateCents)}/hour · {(Number(rate.regularMinutes)/60).toFixed(2)} regular hours · {(Number(rate.overtimeMinutes)/60).toFixed(2)} overtime hours</p>)}{Number(portion.paidLeavePayCents)>0?<p className="mt-1">Additional paid leave: {money(portion.paidLeavePayCents)}</p>:null}</div>})}</article>)}</section></>
}
