import MarylandAdditionalAgreement from './MarylandAdditionalAgreement'
import { useEffect, useState } from 'react'
import { adminApiRequest } from '../../utils/api'
import { workforceButton, workforceInput } from './OnboardingWorkspace'
type Elections={federal:{filingStatus:string;multipleJobs:boolean;exempt:boolean;creditsCents:number;otherIncomeCents:number;deductionsCents:number;extraWithholdingCents:number};maryland:{filingStatus:string;exemptions:number;localRate:number;extraWithholdingCents:number;exempt:boolean}}
const defaults:Elections={federal:{filingStatus:'SINGLE',multipleJobs:false,exempt:false,creditsCents:0,otherIncomeCents:0,deductionsCents:0,extraWithholdingCents:0},maryland:{filingStatus:'SINGLE',exemptions:0,localRate:3.2,extraWithholdingCents:0,exempt:false}}
export default function TaxElectionSettings({employeeId}:{employeeId:number}) {
 const [agreementRefresh,setAgreementRefresh]=useState(0)
 const [elections,setElections]=useState<Elections>(defaults),[source,setSource]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 useEffect(()=>{let live=true;void adminApiRequest(`/api/admin/payroll/employees/${employeeId}/tax-elections`).then(async res=>{const json=await res.json();if(!res.ok)throw new Error(json.message);if(live&&json.data.election){setElections(json.data.election.elections);setSource(json.data.election.source_note)}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[employeeId])
 return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Automatic withholding · 2026</h2><p className="mt-2 text-sm text-slate-600">Record values from the reviewed W-4 and MW507. Automatic calculation supports Maryland-resident weekly, biweekly and semimonthly payroll using the verified 3.20% local table. Other local rates, nonresident cases, lock-in letters, supplemental bonuses, and pretax deductions use the payroll run’s separately verified withholding process.</p><div className="mt-2 flex flex-wrap gap-3 text-sm"><a className="font-bold text-blue-700 underline" href="https://www.irs.gov/publications/p15t" target="_blank" rel="noreferrer">IRS 2026 tables</a><a className="font-bold text-blue-700 underline" href="https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/withholding/2026/withholding-guide.pdf" target="_blank" rel="noreferrer">Maryland 2026 guide</a></div>
 {error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}{notice?<p role="status" className="mt-3 text-sm text-emerald-700">{notice}</p>:null}
 <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const res=await adminApiRequest(`/api/admin/payroll/employees/${employeeId}/tax-elections`,{method:'PATCH',body:JSON.stringify({...elections,sourceNote:source,confirmed})});const json=await res.json();if(!res.ok)throw new Error(json.message);setAgreementRefresh(value=>value+1);setNotice('Verified elections saved. New payroll drafts calculate withholding automatically.')}catch(e){setError(e instanceof Error?e.message:'Unable to save tax elections')}finally{setBusy(false)}}}>
 <label className="text-sm font-bold">W-4 filing status<select value={elections.federal.filingStatus} onChange={e=>setElections({...elections,federal:{...elections.federal,filingStatus:e.target.value}})} className={workforceInput}><option value="SINGLE">Single / married filing separately</option><option value="MARRIED">Married filing jointly</option><option value="HEAD_OF_HOUSEHOLD">Head of household</option></select></label>
 <label className="text-sm font-bold">MW507 filing status<select value={elections.maryland.filingStatus} onChange={e=>setElections({...elections,maryland:{...elections.maryland,filingStatus:e.target.value}})} className={workforceInput}><option value="SINGLE">Single / married separately / dependent</option><option value="JOINT">Married jointly / head of household</option></select></label>
 {([['creditsCents','W-4 Step 3 annual credits ($)'],['otherIncomeCents','W-4 Step 4(a) annual other income ($)'],['deductionsCents','W-4 Step 4(b) annual deductions ($)'],['extraWithholdingCents','W-4 Step 4(c) extra per paycheck ($)']] as const).map(([key,label])=><label key={key} className="text-sm font-bold">{label}<input required type="number" min="0" step="0.01" value={elections.federal[key]/100} onChange={e=>setElections({...elections,federal:{...elections.federal,[key]:Math.round(Number(e.target.value)*100)}})} className={workforceInput}/></label>)}
 <label className="text-sm font-bold">MW507 exemptions<input required type="number" min="0" max="99" step="1" value={elections.maryland.exemptions} onChange={e=>setElections({...elections,maryland:{...elections.maryland,exemptions:Number(e.target.value)}})} className={workforceInput}/></label><label className="text-sm font-bold">MW507 additional per pay period ($)<input required type="number" min="0" step="0.01" value={elections.maryland.extraWithholdingCents/100} onChange={e=>setElections({...elections,maryland:{...elections.maryland,extraWithholdingCents:Math.round(Number(e.target.value)*100)}})} className={workforceInput}/></label>
 <label className="flex gap-2 text-sm"><input type="checkbox" checked={elections.federal.multipleJobs} onChange={e=>setElections({...elections,federal:{...elections.federal,multipleJobs:e.target.checked}})}/>W-4 Step 2 checkbox is checked</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={elections.federal.exempt} onChange={e=>setElections({...elections,federal:{...elections.federal,exempt:e.target.checked}})}/>W-4 claims exemption for 2026</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={elections.maryland.exempt} onChange={e=>setElections({...elections,maryland:{...elections.maryland,exempt:e.target.checked}})}/>MW507 claims a verified exemption</label>
 <label className="text-sm font-bold sm:col-span-2">Verification source<input required minLength={12} value={source} onChange={e=>setSource(e.target.value)} className={workforceInput} placeholder="Signed forms, dates, reviewer, and residence/local-rate confirmation"/></label><label className="flex gap-2 text-sm sm:col-span-2"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified these values against signed forms, confirmed the 3.20% local table applies, and confirmed no nonresident or IRS lock-in exception applies.</label><button disabled={busy||!confirmed} className={workforceButton}>Save verified tax elections</button></form><MarylandAdditionalAgreement employeeId={employeeId} refresh={agreementRefresh}/></section>
}
