import FederalRemittanceReview from './FederalRemittanceReview'
import MarylandWithholdingCalendar from './MarylandWithholdingCalendar'
import MarylandUiCalendar from './MarylandUiCalendar'
import FederalDepositCalendar from './FederalDepositCalendar'
import { useCallback, useEffect, useState } from 'react'
import { workforceApi, type TaxReconciliationData } from '../../utils/workforceApi'
import { workforceButton, workforceInput } from './OnboardingWorkspace'
const labels:Record<string,string>={IRS_941:'Federal income tax, Social Security & Medicare',IRS_FUTA:'Federal unemployment (FUTA)',MD_WITHHOLDING:'Maryland withholding',MD_UI:'Maryland unemployment'}
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value)/100)
const date=(value:string)=>value.slice(0,10)
export default function TaxReconciliation() {
 const [year,setYear]=useState(new Date().getFullYear()),[data,setData]=useState<TaxReconciliationData|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const [deposit,setDeposit]=useState({agency:'IRS_941',quarter:'1',paidOn:'',amount:'',reference:'',notes:'',confirmed:false})
 const [filing,setFiling]=useState({formType:'IRS_941',periodStart:'',periodEnd:'',filedOn:'',wages:'',tax:'',reference:'',notes:'',confirmed:false})
 const [filingCorrections,setFilingCorrections]=useState<Record<number,{reason:string;confirmed:boolean}>>({})
 const [voidReasons,setVoidReasons]=useState<Record<number,string>>({})
 const load=useCallback(async()=>{setData(null);setData(await workforceApi.taxReconciliation(year))},[year])
 useEffect(()=>{let live=true;workforceApi.taxReconciliation(year).then(next=>{if(live)setData(next)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[year])
 const act=async(work:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');setNotice('');try{await work();await load();setNotice(message)}catch(e){setError(e instanceof Error?e.message:'Unable to save tax record')}finally{setBusy(false)}}
 return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">Tax deposits & filing reconciliation</h2><label className="text-sm font-bold">Tax year<select className={workforceInput} disabled={busy} value={year} onChange={e=>{const next=Number(e.target.value);if(next!==year&&Number.isInteger(next)&&next>=2000&&next<=2200){setYear(next);setData(null);setError('');setNotice('');setDeposit(d=>({...d,amount:'',reference:'',confirmed:false}));setFiling(f=>({...f,periodStart:'',periodEnd:'',wages:'',tax:'',reference:'',confirmed:false}))}}}>{Array.from({length:201},(_,i)=>2000+i).map(y=><option key={y} value={y}>{y}</option>)}</select></label></div><p className="mt-2 text-sm text-slate-600">Finalized payroll supplies the liability totals below. Record actual agency deposits and accepted returns to reconcile them. Recording a receipt here does not send funds or file a return.</p>
 {error?<p role="alert" className="mt-3 text-red-700">{error}</p>:null}{notice?<p role="status" className="mt-3 text-emerald-700">{notice}</p>:null}
 {data?.legacyPayments?<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{data.legacyPayments} historical payments need separate tax review. These totals cover finalized payroll runs; review historical tax records before reconciling the year.</p>:null}
 <button type="button" disabled={busy} className={`${workforceButton} mt-3`} onClick={()=>void act(async()=>{},'Tax reconciliation refreshed.')}>Refresh tax reconciliation</button>
 {!data?<p className="mt-4 text-sm">{error?'Tax reconciliation is unavailable. Resolve the reported issue and refresh.':'Loading tax reconciliation…'}</p>:<div className="mt-5 grid gap-4 lg:grid-cols-2">{data.quarters.map(q=><article key={q.quarter} className="rounded-xl border border-slate-200 p-4"><h3 className="font-black">Q{q.quarter} · {q.start} through {q.end}</h3><p className="mt-1 text-sm text-slate-500">Gross wages {money(q.grossCents)} · {q.employeeCount} employees</p><div className="mt-2 flex flex-wrap gap-3">{['IRS_941','MD_UI'].map(form=><button key={form} type="button" disabled={busy} className="text-xs font-bold text-blue-700" onClick={()=>setFiling(f=>({...f,formType:form,periodStart:q.start,periodEnd:q.end,wages:(q.grossCents/100).toFixed(2),tax:((q.agencies.find(a=>a.agency===form)?.liabilityCents||0)/100).toFixed(2),reference:'',confirmed:false}))}>Prepare {form.replaceAll('_',' ')} comparison</button>)}</div><div className="mt-3 space-y-3">{q.agencies.map(a=><div key={a.agency} className="border-t border-slate-100 pt-3 text-sm"><p className="font-bold">{labels[a.agency]}</p><p>Liability {money(a.liabilityCents)} · Deposits {money(a.depositedCents)}</p><p className={a.balanceCents>0?'font-bold text-amber-800':'font-bold text-emerald-700'}>{a.balanceCents<0?'Credit recorded':a.balanceCents===0?'Balanced':'Unpaid balance'}: {money(Math.abs(a.balanceCents))}</p>{a.balanceCents>0?<button className="mt-1 text-sm font-bold text-blue-700" type="button" disabled={busy} onClick={()=>setDeposit(d=>({...d,agency:a.agency,quarter:String(q.quarter),amount:(a.balanceCents/100).toFixed(2)}))}>Use balance for deposit receipt</button>:null}</div>)}</div></article>)}</div>}
 <div className="mt-6 grid gap-6 xl:grid-cols-2"><form className="space-y-3 rounded-xl bg-slate-50 p-4" onSubmit={e=>{e.preventDefault();void act(async()=>{await workforceApi.recordTaxDeposit({...deposit,year,quarter:Number(deposit.quarter),amountCents:Math.round(Number(deposit.amount)*100)});setDeposit(d=>({...d,amount:'',reference:'',confirmed:false}))},'Agency deposit receipt recorded. Balances updated.')}}><h3 className="text-lg font-black">Record tax deposit receipt</h3>
 <label className="block text-sm font-bold">Tax agency / account<select className={workforceInput} value={deposit.agency} onChange={e=>setDeposit(d=>({...d,agency:e.target.value}))}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 <label className="block text-sm font-bold">Tax quarter<select className={workforceInput} value={deposit.quarter} onChange={e=>setDeposit(d=>({...d,quarter:e.target.value}))}>{[1,2,3,4].map(q=><option key={q} value={q}>Q{q} {year}</option>)}</select></label>
 {([['paidOn','Deposit payment date','date'],['amount','Deposit amount ($)','number'],['reference','Deposit confirmation reference','text'],['notes','Deposit notes','text']] as const).map(([key,label,type])=><label key={key} className="block text-sm font-bold">{label}<input className={workforceInput} required={key!=='notes'} type={type} min={type==='number'?'0.01':undefined} step={type==='number'?'0.01':undefined} value={deposit[key]} onChange={e=>setDeposit(d=>({...d,[key]:e.target.value}))}/></label>)}
 <label className="flex gap-2 text-sm"><input type="checkbox" required checked={deposit.confirmed} onChange={e=>setDeposit(d=>({...d,confirmed:e.target.checked}))}/>I verified this deposit succeeded against the bank or agency receipt.</label><button disabled={busy} className={workforceButton}>Record deposit receipt</button></form>
 <form id="payroll-tax-filing-form" className="space-y-3 rounded-xl bg-slate-50 p-4" onSubmit={e=>{e.preventDefault();void act(async()=>{await workforceApi.recordTaxFiling({...filing,reportedWagesCents:Math.round(Number(filing.wages)*100),reportedTaxCents:Math.round(Number(filing.tax)*100)});setFiling(f=>({...f,reference:'',confirmed:false}))},'Accepted filing recorded with a payroll snapshot. Review its comparison below.')}}><h3 className="text-lg font-black">Record accepted tax filing</h3><p className="text-xs text-slate-600">Enter gross payroll wages and tax control totals from the accepted return. For W-2/W-3, use federal income tax plus employee Social Security and Medicare withheld. A matched comparison checks these totals, not every box on the return.</p>
 <label className="block text-sm font-bold">Tax form<select className={workforceInput} value={filing.formType} onChange={e=>setFiling(f=>({...f,formType:e.target.value}))}>{['IRS_941','IRS_940','MD_MW506','MD_MW506M','MD_MW508','MD_UI','W2_W3'].map(form=><option key={form} value={form}>{form.replaceAll('_',' ')}</option>)}</select></label>
 {([['periodStart','Filing period start','date'],['periodEnd','Filing period end','date'],['filedOn','Agency accepted date','date'],['wages','Reported gross wages ($)','number'],['tax','Reported tax control total ($)','number'],['reference','Filing acceptance reference','text'],['notes','Filing notes','text']] as const).map(([key,label,type])=><label key={key} className="block text-sm font-bold">{label}<input className={workforceInput} required={key!=='notes'} type={type} min={type==='number'?'0':undefined} step={type==='number'?'0.01':undefined} value={filing[key]} onChange={e=>setFiling(f=>({...f,[key]:e.target.value}))}/></label>)}
 <label className="flex gap-2 text-sm"><input type="checkbox" required checked={filing.confirmed} onChange={e=>setFiling(f=>({...f,confirmed:e.target.checked}))}/>I verified agency acceptance and transcribed the return totals.</label><button disabled={busy||!data} className={workforceButton}>Record accepted filing</button></form></div>
 {data?<><FederalDepositCalendar key={year} year={year} receipts={data?.deposits}/>
 <MarylandWithholdingCalendar key={`md-withholding-${year}`} year={year} records={data} onPrepare={p=>{setFiling(f=>({...f,formType:p.formType||'MD_MW506',periodStart:p.start,periodEnd:p.end,wages:(p.grossCents/100).toFixed(2),tax:(p.liabilityCents/100).toFixed(2),filedOn:'',reference:'',notes:'',confirmed:false}));document.getElementById('payroll-tax-filing-form')?.scrollIntoView({behavior:'smooth',block:'start'})}}/>
 <MarylandUiCalendar key={`md-ui-${year}`} year={year} records={data}/></>:null}
 <FederalRemittanceReview key={`remittance-${year}`} year={year}/>
 <h3 className="mt-6 text-lg font-black">Deposit history</h3><div className="mt-3 space-y-3">{data?.deposits.map(d=><article key={d.id} className="rounded-xl border border-slate-200 p-3 text-sm"><p className="font-bold">{labels[d.agency]} · Q{d.tax_quarter} · {money(d.amount_cents)} · {d.status}</p><p>{date(d.paid_on)} · {d.reference}</p>{d.status==='RECORDED'?<div className="mt-2 flex flex-wrap gap-2"><input aria-label={`Reason to void deposit ${d.reference}`} className={workforceInput} placeholder="Reason to void an incorrect receipt" value={voidReasons[d.id]||''} onChange={e=>setVoidReasons(r=>({...r,[d.id]:e.target.value}))}/><button type="button" disabled={busy||(voidReasons[d.id]||'').trim().length<12} className="font-bold text-red-700" onClick={()=>void act(()=>workforceApi.voidTaxDeposit(d.id,voidReasons[d.id]),'Deposit receipt voided; audit history retained.')}>Void recorded deposit</button></div>:<p>{d.void_reason}</p>}</article>)}</div>
 <h3 className="mt-6 text-lg font-black">Filing history & comparisons</h3><div className="mt-3 space-y-3">{data?.filings.map(f=><article key={f.id} className="rounded-xl border border-slate-200 p-3 text-sm"><p className="font-bold">{f.form_type.replaceAll('_',' ')} · {date(f.period_start)} through {date(f.period_end)}</p><p className={f.status==='MATCHED'?'font-bold text-emerald-700':'font-bold text-amber-800'}>{f.status.replaceAll('_',' ')}</p><p>Accepted {date(f.filed_on)} · {f.reference}</p><p>Reported wages {money(f.reported_wages_cents)} / current {money(f.currentWagesCents)} · Reported tax {money(f.reported_tax_cents)} / current {money(f.currentTaxCents)}</p>{f.status==='VOID'?<p className="mt-2 text-slate-600">Local receipt voided: {f.void_reason}</p>:<details className="mt-3"><summary className="cursor-pointer font-bold text-slate-700">Correct this filing receipt</summary><p className="mt-2 text-xs text-slate-600">Use this for an incorrectly entered local record. An accepted agency return must be corrected with the agency; this action does not amend or cancel it.</p><label className="mt-2 block text-sm">Receipt correction reason<input className={workforceInput} value={filingCorrections[f.id]?.reason||''} onChange={e=>setFilingCorrections(v=>({...v,[f.id]:{reason:e.target.value,confirmed:v[f.id]?.confirmed||false}}))}/></label><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={filingCorrections[f.id]?.confirmed||false} onChange={e=>setFilingCorrections(v=>({...v,[f.id]:{reason:v[f.id]?.reason||'',confirmed:e.target.checked}}))}/>I am correcting only the local receipt record.</label><button type="button" disabled={busy||!filingCorrections[f.id]?.confirmed||(filingCorrections[f.id]?.reason||'').trim().length<12} className="mt-2 font-bold text-red-700" onClick={()=>void act(()=>workforceApi.voidTaxFiling(f.id,filingCorrections[f.id].reason,filingCorrections[f.id].confirmed),'Local filing receipt voided. Agency returns are unchanged; filing reminders recalculated.')}>Void local filing receipt</button></details>}</article>)}</div>
 </section>
}
