import TimeCorrectionCalculation from './TimeCorrectionCalculation'
import {useRef,useState} from 'react'
import {workforceApi} from '../../utils/workforceApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
const money=(v:unknown)=>(Number(v)/100).toLocaleString('en-US',{style:'currency',currency:'USD'})
export default function TimeCorrectionImpact({requestId}:{requestId:number}){
 const [reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[saved,setSaved]=useState<number|null>(null)
 const reference=useRef({key:'',id:''})
 const [data,setData]=useState<Awaited<ReturnType<typeof workforceApi.timeCorrectionImpact>>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 return <div className="mt-3 space-y-2 rounded-lg border p-3"><button type="button" className={workforceButton} disabled={busy} onClick={async()=>{setBusy(true);setError('');setData(null);setSaved(null);setConfirmed(false);try{setData(await workforceApi.timeCorrectionImpact(requestId))}catch(e){setError(e instanceof Error?e.message:'Unable to review payroll impact.')}finally{setBusy(false)}}}>{busy?'Checking payroll impact…':'Review payroll impact'}</button>
 {error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}
 {data?<div role="status" className="space-y-2 text-sm"><p className="font-bold">{data.status==='PAYROLL_CORRECTION_REQUIRED'?'Payroll correction required':'Timesheet review applies'}</p><p>Proposed work: {(data.proposed.workedMinutes/60).toFixed(2)} hours. This review does not change time or payments.</p>{data.scopes.map(s=><p key={`${s.first}-${s.last}`}>Affected workweeks: {s.first} through {s.last}</p>)}{data.runs.map(r=><p key={String(r.id)}>Run #{String(r.id)} · {String(r.status).toLowerCase()} · {String(r.period_start).slice(0,10)} through {String(r.period_end).slice(0,10)} · recorded gross {money(Number(r.regular_pay_cents)+Number(r.overtime_pay_cents)+Number(r.other_taxable_pay_cents))}</p>)}{data.historicalPayments.map(p=><p key={String(p.id)}>Imported payment #{String(p.id)} · {String(p.period_start).slice(0,10)} through {String(p.period_end).slice(0,10)} · recorded gross {money(p.gross_amount_cents)}</p>)}<p>{data.status==='PAYROLL_CORRECTION_REQUIRED'?'These payments need a correction calculation before this request can be resolved. Original paid time remains protected.':'No committed payments were found in the affected workweeks. Normal request and timesheet review still apply.'}</p></div>:null}
 {data?.status==='PAYROLL_CORRECTION_REQUIRED'&&!saved?<form className="space-y-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const body={fingerprint:data.fingerprint,reason,confirmed};const key=JSON.stringify(body);if(reference.current.key!==key)reference.current={key,id:crypto.randomUUID()};try{const result=await workforceApi.retainCorrectionImpact(requestId,{...body,requestKey:reference.current.id});setSaved(result.id)}catch(e){setError(e instanceof Error?e.message:'Unable to retain review.')}finally{setBusy(false)}}}><fieldset disabled={busy} className="space-y-2"><label className="block text-sm">Correction review reason<textarea required minLength={20} maxLength={2000} className={workforceInput} value={reason} onChange={e=>{setReason(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2 text-sm"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the affected payments and proposed correction.</label><button className={workforceButton}>Retain correction review</button></fieldset></form>:null}
 {saved?<p role="status" className="text-sm font-bold">Correction impact review #{saved} retained. Calculation and resolution are still required.</p>:null}
 {data?.status==='PAYROLL_CORRECTION_REQUIRED'?<TimeCorrectionCalculation key={`${requestId}/${data.fingerprint}/${saved}`} requestId={requestId}/>:null}
 {data?.reviews.map(r=><div key={r.id} className="rounded border p-2 text-sm"><p>Review #{r.id} · {r.status==='CURRENT'?'matches current impact':'needs fresh evidence'} · {new Date(r.reviewedAt).toLocaleDateString()}</p><p>{r.reason}</p></div>)}
 </div>
}
