import CorrectionWorkweekAmounts from './CorrectionWorkweekAmounts'
import CorrectionAuthorizationHistory from './CorrectionAuthorizationHistory'
import CorrectionPaymentPreview from './CorrectionPaymentPreview'
import {useRef,useState} from 'react'
import {workforceApi} from '../../utils/workforceApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
const money=(v:number)=>(v/100).toLocaleString('en-US',{style:'currency',currency:'USD'})
export default function TimeCorrectionCalculation({requestId}:{requestId:number}){
 const [data,setData]=useState<Awaited<ReturnType<typeof workforceApi.correctionCalculation>>|null>(null)
 const reference=useRef({key:'',id:''})
 const [reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[saved,setSaved]=useState<number|null>(null)
 const [history,setHistory]=useState<Awaited<ReturnType<typeof workforceApi.correctionCalculations>>|null>(null)
 const [busy,setBusy]=useState(false),[error,setError]=useState('')
 return <div className="space-y-2 rounded border p-3 text-sm">
  <button type="button" disabled={busy} className={workforceButton} onClick={async()=>{setBusy(true);setError('');setData(null);setSaved(null);setConfirmed(false);try{setData(await workforceApi.correctionCalculation(requestId))}catch(e){setError(e instanceof Error?e.message:'Unable to calculate correction.')}finally{setBusy(false)}}}>{busy?'Calculating…':'Calculate correction wages'}</button>
  {error?<p role="alert" className="text-red-700">{error}</p>:null}
  {data?<div role="status" className="space-y-2"><p className="font-bold">Worked wage difference: {money(data.workedWagesDifferenceCents)}</p>{data.runs.map(r=><div key={r.runId}><p>Run #{r.runId} · {r.status.toLowerCase()} · {r.periodStart} through {r.periodEnd}</p><p>Regular hours: {(r.before.regularMinutes/60).toFixed(2)} → {(r.after.regularMinutes/60).toFixed(2)}. Overtime hours: {(r.before.overtimeMinutes/60).toFixed(2)} → {(r.after.overtimeMinutes/60).toFixed(2)}.</p><p>Wage change: {money(r.delta.workedWagesCents)}</p><CorrectionWorkweekAmounts amounts={r}/></div>)}{data.leave.status==='LEAVE_DIFFERENCE_CALCULATED'?<div><p className="font-bold">Sick-leave credit difference: {data.leave.creditDifferenceMinutes} minutes</p>{data.leave.items?.map(item=><p key={item.runId}>Run #{item.runId}: {item.accruedMinutesBefore} → {item.accruedMinutesAfter} earned minutes</p>)}<p>Ending fractional carry: {data.leave.finalRemainder}/30 minute. No leave adjustment has been applied.</p></div>:<p>Leave reconciliation required: {data.leave.issue}</p>}<p>This is a wage calculation preview. Taxes, leave adjustments and payment or recovery still require resolution. Original records remain unchanged.</p></div>:null}
  {data&&!saved?<form className="space-y-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const body={fingerprint:data.fingerprint,reason,confirmed},key=JSON.stringify(body);if(reference.current.key!==key)reference.current={key,id:crypto.randomUUID()};try{const r=await workforceApi.retainCorrectionCalculation(requestId,{...body,requestKey:reference.current.id});setSaved(r.id);setHistory(null)}catch(e){setError(e instanceof Error?e.message:'Unable to retain calculation.')}finally{setBusy(false)}}}><fieldset disabled={busy} className="space-y-2"><label className="block">Calculation retention reason<textarea className={workforceInput} required minLength={20} maxLength={2000} value={reason} onChange={e=>{setReason(e.target.value);setConfirmed(false)}}/></label><label className="flex gap-2"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the wage difference and its original payroll evidence.</label><button className={workforceButton}>Retain wage calculation</button></fieldset></form>:null}
  {saved?<p role="status">Wage calculation #{saved} retained. Settlement is still required.</p>:null}
  <button type="button" disabled={busy} className={workforceButton} onClick={async()=>{setBusy(true);setError('');setHistory(null);try{setHistory(await workforceApi.correctionCalculations(requestId))}catch(e){setError(e instanceof Error?e.message:'Unable to load calculations.')}finally{setBusy(false)}}}>Load retained calculations</button>
  {history?.length===0?<p>No retained wage calculations.</p>:null}
  {history?.map(r=><div key={r.id} className="rounded border p-2"><p>Calculation #{r.id} · {r.status==='CURRENT'?'matches current wage evidence':'needs fresh wage evidence'} · {money(r.calculation.workedWagesDifferenceCents)}</p><p>{r.reason}</p>{r.calculation.leave?<p>{r.calculation.leave.status==='LEAVE_DIFFERENCE_CALCULATED'?`Retained sick-leave difference: ${r.calculation.leave.creditDifferenceMinutes} minutes (not applied).`:`Retained leave review: ${r.calculation.leave.issue}`}</p>:null}<p>{new Date(r.retainedAt).toLocaleString()}</p><details><summary className="cursor-pointer font-semibold">Retained wage evidence</summary>{r.calculation.runs.map(run=><div key={run.runId} className="mt-2"><p>Run #{run.runId} · {run.periodStart} through {run.periodEnd}</p><p>Original: {(run.before.regularMinutes/60).toFixed(2)} regular hours and {(run.before.overtimeMinutes/60).toFixed(2)} overtime hours · {money(run.before.regularPayCents+run.before.overtimePayCents)}</p><p>Proposed: {(run.after.regularMinutes/60).toFixed(2)} regular hours and {(run.after.overtimeMinutes/60).toFixed(2)} overtime hours · {money(run.after.regularPayCents+run.after.overtimePayCents)}</p><CorrectionWorkweekAmounts amounts={run}/></div>)}</details>{r.issue?<p>{r.issue}</p>:null}{r.status==='CURRENT'?<CorrectionPaymentPreview requestId={requestId} calculationId={r.id}/>:null}</div>)}
 <CorrectionAuthorizationHistory requestId={requestId}/>
 </div>
}
