import W2Publication from './W2Publication'
import W2Furnishing from './W2Furnishing'
import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
export type W2ApprovalHistory={id:string;reference:string;created_by:string;created_at:string;status:string}
export default function W2Approval({employeeId,fingerprint,history,onSaved}:{employeeId:number;fingerprint:string|null;history:W2ApprovalHistory[];onSaved:()=>Promise<void>}){
 const [reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[stale,setStale]=useState(false),[error,setError]=useState('')
 const [downloading,setDownloading]=useState<string|null>(null)
 const download=async(id:string)=>{if(downloading)return;setDownloading(id);setError('');try{const response=await adminApiRequest(`/api/admin/payroll/employees/${employeeId}/w2-approval/${id}/pdf`);if(!response.ok){const json=await response.json();throw new Error(json.message||'Unable to download employee copies.')}const url=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=url;link.download=`w2-2026-employee-${employeeId}-approval-${id}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e instanceof Error?e.message:'Unable to download employee copies.')}finally{setDownloading(null)}}
 const valid=!!fingerprint&&!busy&&!stale&&confirmed&&reference.trim().length>=12&&!Array.from(reference).some(c=>c.charCodeAt(0)<32||c.charCodeAt(0)===127)
 const save=async()=>{if(!valid)return;setBusy(true);setError('');try{const response=await adminApiRequest(`/api/admin/payroll/employees/${employeeId}/w2-approval`,{method:'POST',body:JSON.stringify({year:2026,draftFingerprint:fingerprint,expectedRevision:Number(history[0]?.id||0),reference,confirmed})}),json=await response.json();if(!response.ok){if(response.status===409){setStale(true);setConfirmed(false)}throw new Error(json.message||'Unable to retain W-2 approval.')}await onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to retain W-2 approval.')}finally{setBusy(false)}}
 return <section aria-label="W-2 approval" className="space-y-3 border-t border-slate-200 pt-3"><h5 className="font-bold">W-2 approval</h5><p>Approve the reviewed draft above and retain its form data securely. Approval does not deliver the form or transmit it to an agency.</p>{error?<p role="alert" className="text-red-700">{error}</p>:null}{fingerprint?<fieldset disabled={busy||stale} className="space-y-3"><label className="block font-semibold">W-2 approval evidence<input autoComplete="off" maxLength={2000} value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}} className="mt-1 block w-full rounded-lg border border-slate-300 p-2 font-normal"/></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the W-2 draft boxes, filing identities and supporting classifications and approve this form data.</label><button type="button" disabled={!valid} onClick={()=>void save()} className="rounded-lg bg-slate-900 px-3 py-2 font-bold text-white disabled:opacity-50">Approve and retain W-2</button></fieldset>:<p className="text-amber-900">Resolve the draft review requirements before approval.</p>}{stale?<p className="text-amber-900">Refresh annual preparation before approving again.</p>:null}<h6 className="font-bold">W-2 approval history</h6><p>The first download retains an encrypted packet; later downloads return that same PDF. Copies contain full filing identifiers from that approval. Historical copies may be stale. Downloading does not record employee delivery or agency filing.</p>{history.length?history.map(item=><article key={item.id} className="space-y-1 rounded-lg bg-slate-50 p-3"><p>{item.status} · W-2 approval {item.id}</p><p className="break-words">{item.reference}</p><p className="text-xs text-slate-500">Reviewer {item.created_by} · {new Date(item.created_at).toLocaleString()}</p><button type="button" disabled={downloading!==null} onClick={()=>void download(item.id)} className="font-bold underline disabled:opacity-50">{downloading===item.id?'Preparing employee copies…':'Download approved employee copies'}</button><W2Furnishing employeeId={employeeId} approvalId={item.id}/><W2Publication employeeId={employeeId} approvalId={item.id}/></article>):<p>No W-2 approval retained.</p>}</section>
}
