import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
export default function W2NoticeReturn({employeeId,approvalId,attempts,onSaved}:{employeeId:number;approvalId:string;attempts:Array<{id:string;outcome:string|null;return_id?:string|null}>;onSaved:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[attemptId,setAttemptId]=useState(''),[returnedAt,setReturnedAt]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const eligible=attempts.filter(a=>!a.return_id&&[null,'UNCERTAIN','SMTP_ACCEPTED'].includes(a.outcome))
 if(!eligible.length)return null
 if(!open)return <button type="button" className="font-bold underline" onClick={()=>setOpen(true)}>Record an electronic return</button>
 const valid=attemptId&&returnedAt&&reference.trim().length>=12&&confirmed&&!busy
 const save=async()=>{if(!valid)return;setBusy(true);setError('');try{const response=await adminApiRequest(`/api/admin/payroll/employees/${employeeId}/w2-approval/${approvalId}/notice-return`,{method:'POST',body:JSON.stringify({attemptId:Number(attemptId),returnedAt:new Date(returnedAt).toISOString(),reference,confirmed,expectedRevision:0})}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to record return.');await onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to record return.');setConfirmed(false)}finally{setBusy(false)}}
 return <fieldset disabled={busy} aria-label="Record electronic notice return" className="space-y-3 rounded border p-3"><legend className="font-bold">Electronic notice returned</legend><p>Record a return received outside the automated mail log. Select the actual send attempt and retain a reference to the return evidence.</p>{error?<p role="alert" className="text-red-700">{error}</p>:null}<label className="block">Returned notice attempt<select aria-label="Returned notice attempt" className="block w-full rounded border p-2" value={attemptId} onChange={e=>{setAttemptId(e.target.value);setConfirmed(false)}}><option value="">Choose an attempt</option>{eligible.map(a=><option key={a.id} value={a.id}>Attempt {a.id}</option>)}</select></label><label className="block">Actual electronic return time (your local time)<input type="datetime-local" step="1" className="block w-full rounded border p-2" value={returnedAt} onChange={e=>{setReturnedAt(e.target.value);setConfirmed(false)}}/></label><label className="block">Electronic return evidence reference<input maxLength={2000} autoComplete="off" className="block w-full rounded border p-2" value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified this notice attempt was returned undeliverable at the recorded time and retained the evidence.</label><div className="flex gap-3"><button type="button" disabled={!valid} className="rounded bg-slate-900 p-2 font-bold text-white disabled:opacity-50" onClick={()=>void save()}>Save electronic return</button><button type="button" className="font-bold underline" onClick={()=>{setOpen(false);setConfirmed(false);setError('')}}>Cancel return entry</button></div></fieldset>
}
