import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Attempt={cycle_revision?:string|number;id:string;return_id?:string|null;correction_id?:string|null;return_source:string|null;original_return_source?:string|null;is_retracted?:boolean;provider_event_id?:string|null;returned_at:string|null}
export default function W2ReturnRecordAgain({employeeId,approvalId,attempts,onSaved}:{employeeId:number;approvalId:string;attempts:Attempt[];onSaved:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState(''),[returnedAt,setReturnedAt]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const eligible=attempts.filter(a=>a.return_id&&a.return_source==='ADMIN'&&a.original_return_source==='ADMIN'&&a.is_retracted&&!a.provider_event_id),attempt=eligible.find(a=>a.id===selected)
 if(!eligible.length)return null
 if(!open)return <button type="button" className="block font-bold underline" onClick={()=>setOpen(true)}>Record new return after retraction</button>
 const valid=attempt&&returnedAt&&reference.trim().length>=12&&confirmed&&!busy
 const save=async()=>{if(!valid||!attempt)return;setBusy(true);setError('');try{const response=await adminApiRequest(`/api/admin/payroll/employees/${employeeId}/w2-approval/${approvalId}/notice-return-again`,{method:'POST',body:JSON.stringify({returnId:Number(attempt.return_id),expectedRevision:Number(attempt.correction_id||0),expectedCycleRevision:Number(attempt.cycle_revision||0),reference,confirmed,returnedAt:new Date(returnedAt).toISOString()})}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to record new return.');await onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to record new return.');setConfirmed(false)}finally{setBusy(false)}}
 return <fieldset disabled={busy} aria-label="Record new return after retraction" className="space-y-3 rounded border p-3"><legend className="font-bold">Record new return after retraction</legend><p>Record newly reviewed return evidence for this same notice attempt. This reopens paper follow-up from the actual return time. Earlier entries and retractions remain in history; verified provider returns take precedence.</p>{error?<p role="alert" className="text-red-700">{error}</p>:null}<label className="block">Retracted notice attempt<select aria-label="Retracted notice attempt" className="block w-full rounded border p-2" value={selected} onChange={e=>{setSelected(e.target.value);setConfirmed(false)}}><option value="">Choose a retracted return</option>{eligible.map(a=><option key={a.id} value={a.id}>Attempt {a.id}</option>)}</select></label>{attempt?<p>Previously recorded return: {new Date(attempt.returned_at!).toLocaleString()}</p>:null}<label className="block">New return time (your local time)<input type="datetime-local" step="1" className="block w-full rounded border p-2" value={returnedAt} onChange={e=>{setReturnedAt(e.target.value);setConfirmed(false)}}/></label><label className="block">New return evidence reference<input maxLength={2000} className="block w-full rounded border p-2" value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the earlier retraction and new evidence and confirm this notice was returned at the stated time.</label><div className="flex gap-3"><button type="button" disabled={!valid} className="rounded bg-slate-900 p-2 font-bold text-white disabled:opacity-50" onClick={()=>void save()}>Save new return evidence</button><button type="button" className="font-bold underline" onClick={()=>{setOpen(false);setConfirmed(false);setError('')}}>Cancel new return</button></div></fieldset>
}
