import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Attempt={cycle_revision?:string|number;is_retracted?:boolean;id:string;return_id?:string|null;correction_id?:string|null;returned_at:string|null;provider_event_id?:string|null;provider_returned_at?:string|null}
export default function W2ReturnCorrection({employeeId,approvalId,attempts,onSaved}:{employeeId:number;approvalId:string;attempts:Attempt[];onSaved:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState(''),[returnedAt,setReturnedAt]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const eligible=attempts.filter(a=>a.return_id&&!a.is_retracted),attempt=eligible.find(a=>a.id===selected)
 if(!eligible.length)return null
 if(!open)return <button type="button" className="block font-bold underline" onClick={()=>setOpen(true)}>Correct electronic return evidence</button>
 const valid=attempt&&(attempt.provider_event_id||returnedAt)&&reference.trim().length>=12&&confirmed&&!busy
 const save=async()=>{if(!valid||!attempt)return;setBusy(true);setError('');try{const response=await adminApiRequest(`/api/admin/payroll/employees/${employeeId}/w2-approval/${approvalId}/notice-return-correction`,{method:'POST',body:JSON.stringify({returnId:Number(attempt.return_id),expectedRevision:Number(attempt.correction_id||0),expectedCycleRevision:Number(attempt.cycle_revision||0),providerEventId:attempt.provider_event_id||null,returnedAt:attempt.provider_event_id?undefined:new Date(returnedAt).toISOString(),reference,confirmed})}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to correct return evidence.');await onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to correct return evidence.');setConfirmed(false)}finally{setBusy(false)}}
 return <fieldset disabled={busy} aria-label="Correct electronic return evidence" className="space-y-3 rounded border p-3"><legend className="font-bold">Correct electronic return evidence</legend><p>The original record stays in history. This updates the return time and paper follow-up target; it does not withdraw the return or establish successful delivery.</p>{error?<p role="alert" className="text-red-700">{error}</p>:null}<label className="block">Return to correct<select aria-label="Return to correct" className="block w-full rounded border p-2" value={selected} onChange={e=>{setSelected(e.target.value);setConfirmed(false);setReturnedAt('')}}><option value="">Choose a returned attempt</option>{eligible.map(a=><option key={a.id} value={a.id}>Attempt {a.id}</option>)}</select></label>{attempt?<p>Current return time: {new Date(attempt.returned_at!).toLocaleString()}</p>:null}{attempt?.provider_event_id?<p>Earliest signed provider return: {attempt.provider_returned_at?new Date(attempt.provider_returned_at).toLocaleString():'Unavailable'}. This time will replace the current return time and resolve matching provider evidence.</p>:<label className="block">Corrected return time (your local time)<input type="datetime-local" step="1" className="block w-full rounded border p-2" value={returnedAt} onChange={e=>{setReturnedAt(e.target.value);setConfirmed(false)}}/></label>}<label className="block">Correction evidence reference<input maxLength={2000} className="block w-full rounded border p-2" value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the original return and supporting evidence and confirm this corrected return time.</label><div className="flex gap-3"><button type="button" disabled={!valid} className="rounded bg-slate-900 p-2 font-bold text-white disabled:opacity-50" onClick={()=>void save()}>Save return correction</button><button type="button" className="font-bold underline" onClick={()=>{setOpen(false);setConfirmed(false);setError('')}}>Cancel correction</button></div></fieldset>
}
