import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
export type ReturnResolutionData={history:{id:string;replacement_packet_id:string;replacement_event_id:string;reference:string;status:string}[];candidates:{packet_id:string;approval_id:string;event_id:string;event_type:string;occurred_at:string}[]}
export default function W2ReturnResolution({employeeId,approvalId,returnEventId,data,onSaved}:{employeeId:number;approvalId:string;returnEventId:string;data:ReturnResolutionData;onSaved:()=>Promise<void>}){
 const [selected,setSelected]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[stale,setStale]=useState(false),[error,setError]=useState('')
 const candidate=data.candidates.find(c=>c.event_id===selected),valid=!!candidate&&reference.trim().length>=12&&confirmed&&!busy&&!stale&&!Array.from(reference).some(c=>c.charCodeAt(0)<32||c.charCodeAt(0)===127)
 const save=async()=>{if(!valid||!candidate)return;setBusy(true);setError('');try{const response=await adminApiRequest(`/api/admin/payroll/employees/${employeeId}/w2-approval/${approvalId}/return-resolution`,{method:'POST',body:JSON.stringify({returnEventId:Number(returnEventId),replacementPacketId:Number(candidate.packet_id),replacementEventId:Number(candidate.event_id),reference,confirmed,expectedRevision:Number(data.history[0]?.id||0)})}),json=await response.json();if(!response.ok){if(response.status===409)setStale(true);throw new Error(json.message||'Unable to link replacement furnishing.')}await onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to link replacement furnishing.');setConfirmed(false)}finally{setBusy(false)}}
 return <section aria-label="Replacement furnishing" className="space-y-3 border-t border-slate-300 pt-3"><h6 className="font-bold">Resolve with a replacement packet</h6><p>Link a newer approval’s actual mailing or hand delivery for this employee and tax year. This records delivery follow-up; it does not correct a tax form or certify agency acceptance.</p>{error?<p role="alert" className="text-red-700">{error}</p>:null}{stale?<p>Reload furnishing before linking again.</p>:null}{data.candidates.length?<fieldset disabled={busy||stale} className="space-y-3"><label className="block">Replacement furnishing evidence<select aria-label="Replacement furnishing evidence" className="block w-full rounded border p-2" value={selected} onChange={e=>{setSelected(e.target.value);setConfirmed(false)}}><option value="">Choose recorded furnishing</option>{data.candidates.map(c=><option key={c.event_id} value={c.event_id}>Packet {c.packet_id} · approval {c.approval_id} · {c.event_type==='PAPER_MAILED'?'mailed':'hand delivered'} · {new Date(c.occurred_at).toLocaleString()}</option>)}</select></label><label className="block">Replacement verification reference<input autoComplete="off" maxLength={2000} className="block w-full rounded border p-2" value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified that this replacement packet’s furnishing addresses the returned packet and that any required form corrections were handled separately.</label><button type="button" disabled={!valid} className="rounded bg-slate-900 px-3 py-2 font-bold text-white disabled:opacity-50" onClick={()=>void save()}>Link replacement furnishing</button></fieldset>:<p>No eligible replacement furnishing is recorded. Prepare and furnish a newer approved packet, then reload this history.</p>}{data.history.map(row=><article key={row.id} className="rounded border border-slate-300 p-2"><p>{row.status} · Replacement packet {row.replacement_packet_id}, event {row.replacement_event_id}</p><p className="break-words">{row.reference}</p></article>)}</section>
}
