import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Attempt={cycle_revision?:string|number;id:string;return_id?:string|null;correction_id?:string|null;return_source:string|null;original_return_source?:string|null;is_retracted?:boolean;provider_event_id?:string|null;returned_at:string|null}
export default function W2ReturnRetraction({employeeId,approvalId,attempts,onSaved}:{employeeId:number;approvalId:string;attempts:Attempt[];onSaved:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const eligible=attempts.filter(a=>a.return_id&&a.return_source==='ADMIN'&&a.original_return_source==='ADMIN'&&!a.is_retracted&&!a.provider_event_id),attempt=eligible.find(a=>a.id===selected)
 if(!eligible.length)return null
 if(!open)return <button type="button" className="block font-bold underline" onClick={()=>setOpen(true)}>Retract mistaken manual return</button>
 const valid=attempt&&reference.trim().length>=12&&confirmed&&!busy
 const save=async()=>{if(!valid||!attempt)return;setBusy(true);setError('');try{const response=await adminApiRequest(`/api/admin/payroll/employees/${employeeId}/w2-approval/${approvalId}/notice-return-retraction`,{method:'POST',body:JSON.stringify({returnId:Number(attempt.return_id),expectedRevision:Number(attempt.correction_id||0),expectedCycleRevision:Number(attempt.cycle_revision||0),reference,confirmed})}),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to retract manual return.');await onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to retract manual return.');setConfirmed(false)}finally{setBusy(false)}}
 return <fieldset disabled={busy} aria-label="Retract mistaken manual return" className="space-y-3 rounded border p-3"><legend className="font-bold">Retract mistaken manual return</legend><p>Use this only when the manual return entry was incorrect. Earlier send evidence determines the notice status afterward. This does not prove delivery or remove history. A later verified provider return reopens follow-up.</p>{error?<p role="alert" className="text-red-700">{error}</p>:null}<label className="block">Mistaken return attempt<select aria-label="Mistaken return attempt" className="block w-full rounded border p-2" value={selected} onChange={e=>{setSelected(e.target.value);setConfirmed(false)}}><option value="">Choose a manual return</option>{eligible.map(a=><option key={a.id} value={a.id}>Attempt {a.id}</option>)}</select></label>{attempt?<p>Recorded return: {new Date(attempt.returned_at!).toLocaleString()}</p>:null}<label className="block">Retraction evidence reference<input maxLength={2000} className="block w-full rounded border p-2" value={reference} onChange={e=>{setReference(e.target.value);setConfirmed(false)}}/></label><label className="flex items-start gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified this manual return was entered in error and retained evidence supporting its retraction.</label><div className="flex gap-3"><button type="button" disabled={!valid} className="rounded bg-slate-900 p-2 font-bold text-white disabled:opacity-50" onClick={()=>void save()}>Confirm manual return retraction</button><button type="button" className="font-bold underline" onClick={()=>{setOpen(false);setConfirmed(false);setError('')}}>Cancel retraction</button></div></fieldset>
}
