import WorkweekAllocationApproval from './WorkweekAllocationApproval'
import {useEffect,useRef,useState} from 'react'
import {payrollApi,type ReviewedWorkweekAllocation} from '../../utils/payrollApi'
import {workforceButton,workforceInput} from './OnboardingWorkspace'
type Agreement={employmentStart:string;payType:string}
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100)
export default function WorkweekAllocationPreview({employeeId,payPeriodId,week,agreements}:{employeeId:number;payPeriodId:number;week:string;agreements:Agreement[]}){
 const [values,setValues]=useState(()=>agreements.filter(a=>a.payType==='SALARY').map(a=>({employmentStart:a.employmentStart,amount:'',source:''})))
 const [result,setResult]=useState<Awaited<ReturnType<typeof payrollApi.previewWorkweekAllocation>>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [records,setRecords]=useState<ReviewedWorkweekAllocation[]>([]),[historyError,setHistoryError]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{let active=true;payrollApi.workweekAllocations(employeeId).then(next=>{if(active)setRecords(current=>[...new Map([...next.filter(r=>r.week===week),...current].map(r=>[r.id,r])).values()].sort((a,b)=>b.id-a.id))}).catch(e=>{if(active)setHistoryError(e instanceof Error?e.message:'Unable to load retained reviews')});return()=>{active=false}},[employeeId,week])
 const revision=useRef(0)
 const change=(index:number,key:'amount'|'source',value:string)=>{revision.current++;setValues(current=>current.map((row,i)=>i===index?{...row,[key]:value}:row));setResult(null);setError('');setMessage('')}
 return <details className="rounded-xl border border-amber-300 bg-white p-3"><summary className="cursor-pointer font-bold">Preview salary allocation</summary><p className="mt-3">Enter the straight-time salary earnings assigned to this workweek and document the allocation. Hours and hourly earnings come from current records. The salary amount includes its paid leave. Leave is valued at the dated normal rate and separated from salary before the remaining earnings are divided among worked time; the overtime premium is divided among overtime minutes. Fractional cents go to the largest remainders, with earlier entries breaking ties.</p><form className="mt-3 space-y-3" onSubmit={async e=>{e.preventDefault();const submitted=revision.current;setBusy(true);setError('');setResult(null);setMessage('');try{const next=await payrollApi.previewWorkweekAllocation(employeeId,{payPeriodId,week,salaryAllocations:values.map(v=>({employmentStart:v.employmentStart,earningsCents:Math.round(Number(v.amount)*100),source:v.source}))});if(revision.current===submitted)setResult(next)}catch(e){if(revision.current===submitted)setError(e instanceof Error?e.message:'Unable to preview allocation')}finally{setBusy(false)}}}>
 {values.map((row,index)=><fieldset disabled={busy} key={row.employmentStart} className="space-y-2"><legend className="font-bold">Salary hire starting {row.employmentStart}</legend><label className="block">Straight-time salary assigned to week ($)<input required type="number" min="0" step="0.01" className={workforceInput} value={row.amount} onChange={e=>change(index,'amount',e.target.value)}/></label><label className="block">Salary allocation evidence<textarea required minLength={20} maxLength={2000} rows={3} className={workforceInput} value={row.source} onChange={e=>change(index,'source',e.target.value)}/></label></fieldset>)}
 <button disabled={busy} className={workforceButton}>{busy?'Calculating…':'Calculate workweek allocation'}</button></form>
 {error?<p role="alert" className="mt-3 text-red-700">{error}</p>:null}
 {message?<p role="status" className="mt-3 font-bold text-emerald-800">{message}</p>:null}
 {result?<div role="status" className="mt-3 space-y-2 rounded-lg bg-slate-50 p-3"><p className="font-bold">Draft allocation · not saved or applied to payroll</p><p>Worked hours: {(result.calculation.workedMinutes/60).toFixed(2)}</p><p>Straight-time earnings: {money(result.calculation.straightTimePayCents)}</p><p>Regular rate: {result.calculation.workedMinutes?`${money(Number(result.calculation.regularRateNumerator)/Number(result.calculation.regularRateDenominator))}/hour`:'No worked hours'}</p><p>Full-week overtime premium: {money(result.calculation.overtimePremiumCents)}</p><div className="space-y-1 border-t pt-2"><p className="font-bold">Dated earnings shares</p>{result.coverage.entries.map(entry=><p key={`${entry.id}-${entry.workDate}`}>{entry.workDate} · {(entry.minutes/60).toFixed(2)} hours · straight-time {money(entry.straightTimePayCents)} · premium {money(entry.premiumCents)}</p>)}</div>{result.paidLeave.length?<div className="space-y-1 border-t pt-2"><p className="font-bold">Approved leave evidence</p>{result.paidLeave.map(leave=><p key={leave.id}>{leave.leaveDate} · {(leave.minutes/60).toFixed(2)} leave hours · {leave.includedInSalary?'recorded as included in salary':'recorded as additional hourly leave pay'}</p>)}<p>Leave included in salary: {money(result.leaveEarnings.salaryIncludedCents)} · additional hourly leave: {money(result.leaveEarnings.hourlyAdditionalCents)}</p><p>Leave hours are separate from worked hours. Current settlement authorization and matching payment history are required before payment.</p></div>:null}<p className="text-slate-600">The displayed rate is rounded; calculation uses the exact rate. Prior premiums have not been deducted. {result.reviewRequired}</p></div>:null}
 {result?<WorkweekAllocationApproval key={result.fingerprint} employeeId={employeeId} onBusy={setBusy} body={{payPeriodId,week,fingerprint:result.fingerprint,salaryAllocations:values.map(v=>({employmentStart:v.employmentStart,earningsCents:Math.round(Number(v.amount)*100),source:v.source}))}} onSaved={saved=>{setRecords(current=>[saved,...current.filter(r=>r.id!==saved.id)]);setResult(null);setMessage('Allocation review saved. Settlement still requires fresh evidence and payment reconciliation.')}}/>:null}
 <div className="mt-3 space-y-2"><h5 className="font-bold">Retained allocation reviews</h5>{historyError?<p role="alert" className="text-red-700">{historyError}</p>:records.length?records.map(record=><div key={record.id} className="rounded-lg border border-slate-200 p-3"><p>Review #{record.id} · {record.reviewedAt.slice(0,10)}</p><p>{record.reason}</p><p>Straight-time earnings: {money(record.calculation.straightTimePayCents)} · full-week premium: {money(record.calculation.overtimePremiumCents)}</p><p className="text-slate-600">{record.reviewRequired}</p></div>):<p>No retained reviews for this workweek.</p>}</div>
 </details>
}
