import W2Approval,{type W2ApprovalHistory} from './W2Approval'
import W2DraftPreview,{type W2Draft} from './W2DraftPreview'
import CompensationApplicability,{type ApplicabilityHistory} from './CompensationApplicability'
import EmployeeHealthClassification,{type HealthClassificationHistory} from './EmployeeHealthClassification'
import AnnualInputReview,{type AnnualReviewHistory} from './AnnualInputReview'
import {useState} from 'react'
import {adminApiRequest} from '../../utils/api'
type Identity={revision:number|null;identifierLast4?:string;marylandRegistrationLast4?:string|null;legalName?:string;address?:{line1:string;line2?:string;city:string;state:string;postalCode:string};issue:string|null}
type BenefitContribution={paymentDate:string;month:string;planId:string;planName:string;optionId:string;optionLabel:string;employeeContribution:string;taxTreatment:string;runId:number;authorizationFingerprint:string}
type Employee={w2ApprovalHistory:W2ApprovalHistory[];w2Draft:W2Draft;compensationApplicabilityHistory:ApplicabilityHistory[];healthClassificationHistory:HealthClassificationHistory[];sourceFingerprint:string;inputReviewHistory:AnnualReviewHistory[];employeeId:number;employeeNumber:string;employeeName:string;filingIdentity:Identity;employeeIdentityReview:string;finalizedRunCount:number;runIds:number[];importedPaymentCount:number;wageInputs:Record<string,string|null>;withholding:Record<string,string|null>;benefitContributions:BenefitContribution[]|null;benefitReportingNotice:string;reviewedQualifiedOvertime:string|null;issues:string[];sourceStatus:string}
type Preparation={compensationCategories:Record<string,string>;healthCoverageReporting:{revision:number;history:Array<{id:string;disposition:string}>};year:number;employer:Identity;employees:Employee[];remainingRequirements:string[];notice:string}
const amount=(value:string|null)=>value===null?'Unavailable':`$${value}`
function FilingDetails({identity}:{identity:Identity}){return identity.issue?<p className="text-amber-900">{identity.issue}</p>:<div className="space-y-1"><p className="font-semibold">{identity.legalName}</p><p>{identity.address?.line1}{identity.address?.line2?`, ${identity.address.line2}`:''}</p><p>{identity.address?.city}, {identity.address?.state} {identity.address?.postalCode}</p><p>Identifier ending {identity.identifierLast4} · Revision {identity.revision}</p></div>}
export default function YearEndPreparation(){
 const [data,setData]=useState<Preparation|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=async()=>{setData(null);setError('');setMessage('');setBusy(true);try{const response=await adminApiRequest('/api/admin/payroll/reports/year-end-preparation?year=2026'),json=await response.json();if(!response.ok)throw new Error(json.message||'Unable to prepare annual payroll.');setData(json.data)}catch(e){setError(e instanceof Error?e.message:'Unable to prepare annual payroll.')}finally{setBusy(false)}}
 return <section aria-label="Year-end payroll preparation" className="space-y-3 rounded-xl border border-slate-200 bg-white p-5 text-sm"><h3 className="text-lg font-bold">Year-end payroll preparation</h3><p>Payment year 2026. Review annual inputs and outstanding source issues before preparing tax forms.</p><button type="button" disabled={busy} onClick={()=>void load()} className="rounded-lg border border-slate-300 px-3 py-2 font-bold disabled:opacity-50">{busy?'Preparing annual inputs…':'Prepare 2026 payroll inputs'}</button>
 {message?<p role="status" className="text-emerald-800">{message}</p>:null}
 {error?<p role="alert" className="text-red-700">{error}</p>:null}
 {data?<><p>{data.notice}</p><div className="rounded-lg bg-amber-50 p-3"><p className="font-bold">Annual review and employee furnishing</p><ul className="list-disc pl-5">{data.remainingRequirements.map(item=><li key={item}>{item}</li>)}</ul></div>
 <div className="rounded-lg bg-slate-50 p-3"><h4 className="mb-2 font-bold">Employer filing identity</h4><FilingDetails identity={data.employer}/>{!data.employer.issue?<p className="mt-2">{data.employer.marylandRegistrationLast4?`Maryland registration ending ${data.employer.marylandRegistrationLast4}`:'Maryland Central Registration Number missing — update employer filing identity.'}</p>:null}</div>
 {!data.employees.length?<p>No finalized or imported employee payments in 2026.</p>:null}
 {data.employees.map(employee=><article key={employee.employeeId} className="space-y-3 rounded-lg border border-slate-200 p-3"><h4 className="font-bold">{employee.employeeName} · {employee.employeeNumber}</h4><p className={employee.sourceStatus==='READY_FOR_REVIEW'?'text-emerald-800':'text-amber-900'}>{employee.sourceStatus==='READY_FOR_REVIEW'?'Retained inputs reconcile — review before form preparation.':'Source reconciliation required.'}</p><FilingDetails identity={employee.filingIdentity}/><p>Employee identity review: {employee.employeeIdentityReview==='CONFIRMED'?'Displayed details confirmed':employee.employeeIdentityReview==='CORRECTION_REQUESTED'?'Correction requested':'Not yet reviewed by employee'}</p><p>{employee.finalizedRunCount} finalized payments · {employee.importedPaymentCount} imported payments</p><p className="break-words">Payroll runs: {employee.runIds.join(', ')||'None'}</p>
 <dl className="space-y-1">{[['federal','Federal'],['maryland','Maryland'],['socialSecurity','Social Security'],['medicare','Medicare']].map(([key,label])=><div key={key}><dt className="inline">{label} wage input: </dt><dd className="inline font-semibold">{amount(employee.wageInputs[key])}</dd></div>)}{[['federal','Federal'],['maryland','Maryland'],['socialSecurity','Social Security'],['medicare','Medicare'],['additionalMedicare','Additional Medicare'],['combinedMedicare','Combined Medicare (W-2 box 6 input)']].map(([key,label])=><div key={key}><dt className="inline">{label} withholding: </dt><dd className="inline font-semibold">{amount(employee.withholding[key])}</dd></div>)}<div><dt className="inline">Reviewed qualified overtime: </dt><dd className="inline font-semibold">{amount(employee.reviewedQualifiedOvertime)}</dd></div></dl>
 <div className="space-y-2 rounded-lg bg-slate-50 p-3"><h5 className="font-bold">Employee benefit contributions</h5><p>{employee.benefitReportingNotice}</p>{employee.benefitContributions===null?<p className="text-amber-900">Contributions unavailable — reconcile retained payroll evidence.</p>:employee.benefitContributions.length?employee.benefitContributions.map((item,index)=><p key={index}>{item.month} · {item.planName} — {item.optionLabel}: <strong>{amount(item.employeeContribution)}</strong> ({item.taxTreatment.toLowerCase()}) · Paid {item.paymentDate} · Payroll {item.runId}</p>):<p>No retained employee benefit deductions in this payment year.</p>}</div>
 {employee.issues.length?<ul className="list-disc space-y-1 pl-5 text-amber-900">{employee.issues.map((issue,index)=><li key={index}>{issue}</li>)}</ul>:null}<CompensationApplicability key={`compensation:${employee.sourceFingerprint}:${employee.compensationApplicabilityHistory[0]?.id||0}`} employeeId={employee.employeeId} sourceFingerprint={employee.sourceFingerprint} ready={employee.sourceStatus==='READY_FOR_REVIEW'} categories={data.compensationCategories} history={employee.compensationApplicabilityHistory} onSaved={async()=>{await load();setMessage('Compensation applicability saved.')}}/><EmployeeHealthClassification key={`health:${employee.sourceFingerprint}:${data.healthCoverageReporting.revision}:${employee.healthClassificationHistory[0]?.id||0}`} employeeId={employee.employeeId} sourceFingerprint={employee.sourceFingerprint} ready={employee.sourceStatus==='READY_FOR_REVIEW'} determination={data.healthCoverageReporting.history[0]} history={employee.healthClassificationHistory} onSaved={async()=>{await load();setMessage('Coverage classification saved.')}}/><AnnualInputReview key={`${employee.sourceFingerprint}:${employee.inputReviewHistory[0]?.id||0}`} employeeId={employee.employeeId} sourceFingerprint={employee.sourceFingerprint} ready={employee.sourceStatus==='READY_FOR_REVIEW'} history={employee.inputReviewHistory} onSaved={async()=>{await load();setMessage('Annual input review saved.')}}/><W2DraftPreview draft={employee.w2Draft}/><W2Approval key={`approval:${employee.w2Draft.fingerprint}:${employee.w2ApprovalHistory[0]?.id||0}`} employeeId={employee.employeeId} fingerprint={employee.w2Draft.fingerprint} history={employee.w2ApprovalHistory} onSaved={async()=>{await load();setMessage('W-2 approval retained.')}}/></article>)}
 </>:null}</section>
}
