"""OR-05 is individually authored from its release/retrieval learning objective.

OR-04 supplies only the exact familiar strength mechanics and explicit doses.
Purpose, sequencing, throwing choices, preparation, clocks and carryover are new
decisions for this lesson. This file does not generate any future workout.
"""
import copy
import json
from session_tools import AGES, MODES, ROOT, dose, save

def main_sets(mode):
    return (2 if mode.endswith('_L') else 3) if mode.startswith('standard') else (1 if mode.endswith('_L') else 2)

def task(route, key, mode):
    n = main_sets(mode) if key == 'E1' else 1
    rest = 20 if key == 'P1' else 60
    if route == 'standing':
        phases = [('settle', 2), ('quiet_standing', 2), ('reset', 6)]
        variant = 'Quiet Bilateral Standing — no-step orientation teaching task'
        effort = 'Bodyweight, minimal effort; arms relaxed, knees unlocked, no deliberate lowering. Follow the position/stop instruction without a ball.'
        throws = reaches = holds = 0
    elif route == 'reach':
        phases = [('chest_start', 2), ('comfortable_forward_reach', 2), ('return_to_chest', 2), ('relax_reset', 4)]
        variant = 'Unloaded Chest-Start Reach and Return — stationary bilateral teaching task'
        effort = 'Unloaded, easy 1–2/10; one comfortable bilateral forward reach and return. Both feet stay planted, no dip, arch, step, jump or forced end range.'
        throws = holds = 0; reaches = 1
    elif route == 'hold':
        phases = ([('floor_pickup_to_chest', 5), ('comfortable_chest_hold', 5), ('carry_one_metre_out_and_back', 4), ('controlled_floor_setdown', 6), ('exit_queue_reset', 4)] if key == 'P2' else
                  [('rack_pickup_to_chest', 2), ('comfortable_chest_hold', 3), ('controlled_setdown', 3), ('reset', 2)])
        variant = 'Ball Chest-Start Hold and Floor Handling — no-release teaching task' if key == 'P2' else 'Ball Chest-Start Hold and Rack Set-Down — no-release practice'
        effort = 'Very light soft low-rebound medicine ball, easy 1–2/10. Planning reference 0.5 kg and 18 cm diameter, only if comfortable handling and actual behavior fit. Record actual type, kg, diameter and rebound; no age-based heavier ball.'
        throws = reaches = 0; holds = 1
    else:
        assert route == 'throw' and key == 'E1'
        phases = [('rack_pickup_chest_setup', 2), ('ready_and_known_permission', 2), ('single_forward_release', 1), ('stable_followthrough', 3), ('wait_at_line', 2)]
        variant = 'Stationary Two-Hand Chest Pass to Open Contained Lane — proposed teaching variation'
        effort = 'Very light soft low-rebound medicine ball; planning 0.5 kg / 18 cm only when actual fit and behavior qualify. Smooth quick release at easy teaching intent about 3/10; no maximal throw, distance score or slow heavy push. Hold the same ball and intent across attempts.'
        throws = 1; reaches = holds = 0
    active = sum(s for _, s in phases)
    d = dose(variant, n, reps=1, tempo_s=active, effort=effort, rest_s=rest,
             notes='One whole counted action per set. Phase times are coaching envelopes, not a demand to rush. P2 never releases a ball; E1 attempts, including faults, use their listed opportunity. No bonus trials.')
    d.update(active_s=active, throws_per_set=throws, unloaded_reach_cycles_per_set=reaches,
             ball_holds_per_set=holds, floor_pickups_per_set=(1 if (route=='hold' and key=='P2') or throws else 0), floor_setdowns_per_set=1 if route=='hold' and key=='P2' else 0, loaded_carry_m_model=2 if route=='hold' and key=='P2' else (6 if throws else 0), hold_duration_s=(5 if key == 'P2' else 3) if holds else 0,
             intentional_jumps_per_set=0, running_target_m=0, retrieval_window_s=15 if throws else 0,
             execution_segments=[{'name':name,'seconds':sec} for name,sec in phases])
    return d

def exercise(key, name, mapping, purpose, execution, cues, errors, rationale, metadata, route, competency, progression, continuity):
    return dict(key=key, name=name, component='Prepare & Access' if key.startswith('P') else 'Explosiveness', mapping=mapping,
                set_purpose=purpose, execution=execution, cues=cues, errors=errors, rationale=rationale, metadata=metadata,
                age_prescriptions={a:{m:task(route,key,m) for m in MODES} for a in AGES}, competency=competency,
                progression=progression, continuity=continuity)

exercises = [
exercise('P1', 'Organize the unloaded chest-start position', 'CHEST-REACH-TEACH; separate quiet-standing option',
 'One unloaded reach/return cycle rehearses the stable trunk and comfortable arm path used in the upcoming chest release. It introduces vocabulary for upper-body setup; it does not assess pressing strength or rowing skill.',
 'Remain in the personal bay. Feet comfortably apart and planted, knees unlocked. Set hands comfortably at chest level for 2 s, reach both arms forward for 2 s, return for 2 s, relax/reset for 4 s. No ball, preload, forced shoulder position or lower-body movement.',
 'Feet still; comfortable chest start; reach forward; return and relax.',
 'Arching, shrugging, forcing elbow lock, dipping to create momentum, adding repetitions while watching another group, or treating this as a push-up/row pass.',
 'A small unloaded position rehearsal directly prepares the chosen throw. It avoids adding overhead or rotational demands. It precedes the more specific grip/setup rehearsal; actual push and pull positions are taught in their own Strength blocks.',
 'Method: one observed position rehearsal. Tenets: Strength / Body Control; integrated coordination. Pattern: bilateral reach. Equipment: personal bay. Local teaching record, not a released profile.', 'reach',
 'All ages require comfortable standing and the assigned unloaded reach. A first visitor may learn this single counted action after demonstration. If upper-body reach is unavailable but standing is comfortable, use the explicit 10 s quiet-standing route. That route gives no arm-path evidence. Experienced athletes keep the small dose and actual comfortable range.',
 'Hold the comfortable range and easy effort. Stop/reduce the affected action for pain, loss of control or inability to follow the cue; age and date do not authorize a harder variant.',
 'Actual OR-01/04 or direct equivalent trunk/conduct record → one specific unloaded chest-start rehearsal → P2 handling and E1 first release only when their separate readiness is present.'),
exercise('P2', 'Hold, wait and put the ball down on instruction', 'BALL-HOLD-TEACH; unloaded/standing options are separate tasks',
 'One counted no-release handling set adds the actual implement and known instruction to a stable position. It teaches grip, waiting, comfortable floor pickup/set-down and a short controlled carry without hiding an extra throw or separate assessment inside preparation.',
 'Begin with the ball resting on a marked floor spot behind the throw line. After demonstration, use a comfortable bilateral hip/knee bend to pick it up to chest level over 5 s, hold comfortably for 5 s, walk 1 m out and 1 m back in the marked personal handling area over 4 s (2 s walking plus 2 s turning), set the ball back on its original floor spot over 6 s, then exit/reset over 4 s. The ball stays in two hands until set-down. This counted handling loop includes floor access and 2 m loaded carry; no throw, catch, loaded push-out, extra trial, or passing to a child. Do not force a floor reach that is unavailable or hurry the turn; stop the action and let the coach manage the implement if needed.',
 'Two hands; feet still; wait with the ball; set it down gently.',
 'Releasing on a setup cue, dropping the ball, prolonged unsupported waiting, forcing grip on a large implement, holding breath, or awarding a throwing/cue-speed pass.',
 'This is the progressive rehearsal of task setup and permission. A complete release/retrieval cycle for all 15 new athletes does not fit the 180 s target budget. The first actual release is therefore the first counted E1 attempt after full demonstration. This detailed revision preserves the objective and adds no third preparation drill.',
 'Method: observed implement setup and inhibition of an unrequested action. Tenets: Body Control / Strength; integrated equipment conduct and attention. Pattern: bilateral static chest hold. Equipment: declared soft medicine ball and stable rack.', 'hold',
 'First-visit handling is taught within this counted set after the coach has selected a plausible comfortable implement by size and prior information. This set provides the actual fit/handling observation; no prior successful ball hold is invented. If grip or position is unsuitable, set down with coach management and end the action; select a separately eligible unloaded or standing route for later work. Record partial handling, not a pass. No more ball trials are added.',
 'A comfortable controlled floor pickup, hold, short carry and set-down plus an eligible unloaded projection and understood conduct permits instruction of the first counted E1 release and its longer retrieval route. It does not establish repeatable throwing, retrieval, reaction or main-entry competence. Keep the actual ball and position; do not increase mass within the visit.',
 'Actual OR-01/04 equipment and upper-body setup evidence → one counted ball-start hold with no release → E1 teaches the known release/retrieval; OR-09 later keeps the actual mastered implement and changes cue interpretation only.'),
exercise('E1', 'Release once on the known cue, then retrieve together', 'CHEST-PASS-TEACH; related to Medicine Ball Chest Pass, exact open-lane stationary profile unverified',
 'Each listed single-throw set has the same purpose: connect a controlled bilateral chest release to one clear early permission cue and then practice the shared retrieval rule. D uses 3 standard / 2 compressed opportunities; L uses 2 / 1, for all ages. This is a low-dose participation lesson in the Explosiveness window, not a maximal power assessment. The first attempt is the counted instructional observation.',
 'Use the same comfortable bilateral stance and declared ball, feet planted, ribs over pelvis. Ball begins at chest, elbows comfortable. Coach names the athlete, confirms the empty contained lane, then says “Ready … throw.” Project the ball forward with two hands in one smooth quick action; no squat/dip preload, step, jump, rotation or overhead action. Finish balanced at the line and wait. One athlete releases at a time across all lanes. When all three balls are stopped, the coach shuts down all releases and says “Retrieve.” Each owner walks to their own ball, picks it up, carries it back and racks it; no return throw or catch. Reset behind the queue line before any later release.',
 'Your lane; wait for your name and throw cue; send it forward; stay at the line; retrieve only together; carry it back.',
 'Throwing on another athlete’s cue, chasing a ball before all-clear, rapid partner exchange, adding a step/dip, throwing toward people, arching, choosing a heavier ball to reach a target, or treating a known permission cue as a measured reaction test.',
 'Stationary two-hand projection isolates release discipline with little added lower-body impact after OR-02/03/04. A wall-return task changes rebound and preload requirements; an overhead or rotational throw changes mechanics; partner catching adds receiving skill. They are not silent substitutes. Single releases allow both coaches to observe. Long between-round rest protects attention and release quality; Strength then leads with matched push/pull teaching without extra sets.',
 'Method: repeated single observed teaching attempts with complete reset. Tenets: Strength / Body Control; coordination, perception and equipment conduct integrated. Pattern: bilateral horizontal projection. Physiology: low-volume release practice; no output gain claimed. Equipment: inspected ball, rack and contained open lane.', 'throw',
 'For every age, entry to the first taught throw needs comfortable actual grip/chest setup, floor pickup/set-down and ordinary carrying, comfortable unloaded forward arm path, understood individual release and group retrieval rules, and physically verified containment/supervision. Prior successful throwing or a floor push-up is not required solely by an unused library variant. Unknown handling stays on P2-style instruction/no-release work until established; no-release completion supplies no throw pass. Older/experienced athletes retain the same teaching dose and actual ball; those already repeatable may use direct domain checks rather than attend four weeks.',
 'Advance toward a repeatable recorded stable-throw and early-release result only when actual attempts show controlled direction, unchanged stance, waiting and retrieval without extra physical prompting, with comfortable response. A few planned attempts are not an automatic pass: retain emerging/unobserved status when evidence is insufficient. Hold the variation and output. Stop all lanes for an unsafe release, moving ball, intrusion or lost cue control; never add a make-up attempt. Pain ends the affected physical task and informs the appropriate professional/coach decision.',
 'Actual OR-01/04 conduct and upper-body readiness, plus separately established throwing history when available → first or retained stable single release/retrieval under one known early cue → OR-09 may add go/no-go only to the actual repeatable movement at retained ball/stance/direction/intent; OR-13 retains the passed throw/cue route if travel/redirect is unavailable. No jumping, braking, go/no-go or cutting credit follows from this lesson.')]

prior = json.loads((ROOT/'instructional_on_ramp/week_01/or_04.json').read_text())
old = {e['key']:e for e in prior['exercises']}
strength_specs = [
 ('S1','S3','Teach stable pressing setup','push','A single supported pressing set makes hand placement, body line, comfortable range and controlled finish visible after the throw lesson. The first listed repetition is the counted observation; this is upper-body instruction, not additional throw output.'),
 ('S2','S4','Teach supported pulling and safe side change','pull','One combined both-side set teaches bench contacts, dumbbell handling and controlled side change. It complements pressing through a distinct pulling action while preserving equal teaching time; it is not a claim that equal reps balance every shoulder demand.'),
 ('S3','S1','Retain the familiar bilateral squat','knee','One small supporting squat set retains an actual owned knee pattern after the earlier landing/braking/running lessons. It introduces no new impact, stance or load challenge.'),
 ('S4','S2','Retain the familiar hip hinge','hip','One small supporting hinge set keeps the useful hip anchor while release and upper-body instruction receive today’s attention. It does not add a second hip set merely because an earlier standard lesson allowed one.'),
 ('S5','S5','Retain trunk control with small heel taps','brace','One controlled alternating heel-tap set practices trunk position during an independently eligible small limb movement. It supports general full-body control without adding another pressing or throwing set.')]
for key, source, name, role, purpose in strength_specs:
    e = copy.deepcopy(old[source]);e.update(key=key,name=name,set_purpose=purpose)
    e['rationale'] = ('Teach push and pull separately in that order, with equal 8 min standard / 5 min compressed blocks. There is no superset, equipment race or simultaneous independent new station work. Rest and setup belong inside the block. ' if role in ['push','pull'] else
                      'After the upper-body teaching, use a familiar supporting role: knee and hip each 4 min standard / 3 min compressed, then brace 6 / 4 min. The shorter lower-body slots retain one simple observed set with explicit setup and rest. ')+ 'Keep the actual eligible mechanics, load and range. Compatible prior one-set work remains one; compatible prior two-set work is deliberately reduced. Different age alone creates no heavier load or extra set.'
    e['progression'] = 'Retain the actual compatible setup, load, range and listed tempo. Teach an unknown setup within its block and count the first repetition. Reduce to the listed L dose or an independently eligible replacement when current response warrants it; stop an unsuitable action. Throwing success never authorizes heavier pressing/pulling, and shoulder response may require deferral of either role. No missed work is owed.'
    e['continuity'] = f'Actual OR-01/02/03/04 or direct equivalent {role} dose, setup and response → one explicit compatible set today (retain one or deliberately reduce two) → OR-09/13 retain actual stable strength while their named cue variable changes; OR-06 retains or changes its own landing/hip anchor independently. Unknown or omitted history is not replaced by the planned D dose.'
    exercises.append(e)

session = dict(
 id='OR-05',title='Release on cue and retrieve safely',stage_label='Separate instructional session · Week 1, Day 5 · individually authored',
 status_note='Written athletic prescription pending independent review. Facility execution, current canonical approval, individual readiness and the separate 30 min tumbling prescription remain unverified. Local keys identify source/teaching records, not live released profiles.',
 brief='Teach one known release cue through a stable two-hand chest throw, then teach safe collective retrieval and organized push/pull stations. Preserve familiar knee, hip and brace practice at one set each. The main quality is controlled participation in a release-and-reset task; no reaction-time, distance or maximal-output result is promised. Prepare & Access rehearses position/handling; Explosiveness teaches the counted release; Strength prioritizes upper-body setup; the final window records what was actually learned and prepares the separate handoff.',
 quality_target='The athlete waits for their own clear release instruction, sends the implement forward within the inspected lane, stays behind the line until global all-clear, retrieves and racks without a return throw, and follows the selected push/pull setup. Record which actions were repeatable, emerging, modified or unobserved; do not infer a pass from attendance.',
 continuity='Actual relevant OR-01 conduct and OR-04 upper-body/strength response or direct equivalent → OR-05 known release plus retrieval at retained simple lower-body demand → OR-09 go/no-go only after stable throw and known release are repeatable, then OR-13 only the independently passed cue/movement branch. Adjacent OR-06’s landing/hip work has its own prior OR-02 evidence and current recovery gate. The five offered weekdays are choices, not five compulsory training exposures or prerequisite attendance.',
 audience='All three age bands have complete D and L prescriptions below. Ages 12–14 are the reference, not beginners. D is the planned teaching opportunity count; L reduces opportunities/repetitions while retaining the exact eligible task. The same modest throwing dose across ages reflects the lesson’s learning objective, not identical ability. Current experience, coordination, growth-related changes, sport load, fatigue, restrictions and actual exposure determine the route. A continuing athlete with the required competencies can enter the relevant main variation directly.',
 readiness='Review actual recent lower-body and shoulder/wrist/grip work, including sport and tumbling, plus present comfort, attention and conduct. Select throwing and each strength role independently. A landing or running gap does not itself prohibit a separately eligible throw; standing or ball holding does not qualify a throw. P1/P2 listed actions provide counted observations, with no hidden warm-up throws, fit trials or correction repetitions. A quiet-standing P1 selected for an arm-path gap cannot authorize later reach/throw without independent evidence. First visitors can learn the simple position/handling sequence here; unresolved inability to understand release/retrieval keeps all releases coach-managed or deferred. A smaller dose never overrides a restriction.',
 equipment_space='PLANNING ONLY: 15 athletes, 2 qualified coaches, 3 parallel throw lanes, each 3 m wide × 6 m protected forward length, with additional 1 m side buffer between lanes, a rear queue/set-up area and unobstructed coach access. No athlete waits in a target lane. A broad optional first-landing reference band 1–3 m ahead helps explain forward direction; it is not a distance requirement, floor slam target or score. The ball follows a natural forward arc and lands by gravity. Lane perimeter/soft containment must stop the actual ball without hazardous rebound, crossing into a neighbor, or contact with a person; six metres is a planning test, not a guaranteed containment distance. Before use the coaches inspect actual ball behavior and the complete retrieval route. If containment is not verified, use a no-release task, not an improvised wall or partner throw. Three intact soft low-rebound medicine balls, one per active lane, and three stable racks at comfortable hand height for E1 are required; P2 uses three marked floor-ball spots with a clear 1 m out-and-back carrying space behind the throw line; size/type/mass may differ by actual athlete fit. Reference 0.5 kg / 18 cm is a proposed equipment test point, not a uniform mandatory load. Actual values must be recorded and replacements inspected; no automatic heavier age tier. The standardized preparation retains 15 personal 3 × 3 m bays. Strength requires five suitable high pressing surfaces (90 cm reference only), five suitable benches and five manageable dumbbells for rows, five mats; supports can be reused sequentially if each purpose fits and the transition is verified. Breathing alternative needs five lower-leg supports; suspension alternative needs five independently verified secure anchors. Quantity, dimensions, sightlines and equipment fit remain unverified.',
 coaching_flow='Use a fixed athlete order 0–14. P1 has three groups of five in their own bays; coaches observe two/three athletes. P2 has five triads, one per lane, with both coaches supervising the simple no-release action. The main has one release at a time across all lanes, so both coaches can observe the new skill. Three owners retrieve together only after all lanes are shut; one coach watches the lane group and one watches queues/racks and restarts. Waiting athletes rest/observe without a ball. Returning from a throw is controlled walking, never another exercise. Strength is sequential whole-group teaching with three waves of five; the two coaches divide each wave two/three. If actual attention or unfamiliarity requires one-to-one instruction, delay/omit later opportunities rather than pretending this group model still fits.',
 clock=[['Prepare & Access','0–15; 12 min instructional base + 3 min targets','0–10; 7 min instructional base + 3 min targets'],['Explosiveness / release and retrieval','15–45','10–35'],['Strength / push-pull teaching and retained support','45–75','35–55'],['Recovery, reflection and handoff','75–90','55–60'],['Separate Body Control / Tumbling','90–120; separate 30 min','60–90; separate 30 min']],
 time_rules='Listed starts are earliest opportunities. Demonstration, grip/setup, all-clear, pickup, walking retrieval, racking, recovery, water and transfers count inside their windows. Never hurry an athlete or retrieve a moving ball to meet the model. A delay consumes remaining slack and removes a later uncompleted opportunity if needed. Faults and partial attempts count physically; no replacement set or catch-up debt follows. Start the next component on time with less work if necessary.',
 preparation_profiles=['or01_full','or01_compact'],
 preparation_note='Use the full reviewed instructional base below, preserving its recognizable sequence, basic no-flight options and concluding hinge/squat checks. The profile names refer to the shared base, not compulsory OR-01 attendance. Add exactly P1 and P2 below, using 40 + 140 = 180 s. The detailed P2 is a progressive rehearsal of implement setup/permission without release; the outline’s actual preparation throw moves into the first already counted E1 opportunity because safe first-visit retrieval does not fit the target clock.',
 exercises=exercises,
 timing_narrative='''**Two preparation targets, exactly 180 s.** P1: 10 s explanation while athletes remain in their bays, then groups of five start at 10/20/30 s; each one-cycle reach or standing alternative uses 10 s. It ends at 40 s. P2: first 20 s gather from bays to rear queues and demonstrate handling (planning 10 s each), then five triads start at 20/44/68/92/116 s within its 140 s budget. Each no-release handling action uses 24 s: floor pickup 5 s, chest hold 5 s, 1 m out-and-back carry 4 s (2 s walking + 2 s turning), floor set-down 6 s, exit 4 s; last triad ends at 140 s. Unloaded/standing options take 10 s inside the same slot, with quiet observation for the remainder. No athlete is asked to throw here. P1 has at least 20 s recovery; fixed-order P1→P2 recovery is at least 40 s. More instruction or a slower transfer reduces the remaining action count; do not remove the standardized base.

**Main lesson.** Main-relative 0–240 s is demonstration of the exact throw, the single known cue, stopped-ball check, shutdown/retrieval and racks, plus confirming the recorded route and water. Coach demonstration is not an athlete practice throw. No warm-up toss or test pickup by athletes is hidden here. Five triads use one minute each. Within each triad, athlete A works at 0–10 s, B at 10–20 s and C at 20–30 s. Each throw action includes pickup/chest setup 2 s, ready/permission 2 s, one release 1 s, follow-through 3 s, wait 2 s. At 30–35 s, both coaches confirm every ball has stopped and all lanes are shut. At 35–50 s, the three owners retrieve their own stopped ball and carry it back; 50–60 s is rack/queue reset. Nobody throws during retrieval. The 15 s retrieval envelope covers up to 6 m outward + 6 m return at ordinary walking pace and the pickup; actual slower movement or a more distant ball delays the restart. An out-of-lane ball closes all lanes and is recovered only after shutdown under coach management. Use no later replacement throw.

**Round schedule and recovery.** Standard D rounds start main-relative 240/720/1200 s; standard L uses 240/720 only. Compressed D uses 240/720; compressed L uses 240 only. Triad offsets are 0/60/120/180/240 s; round clearance is 300 s after its start. The last standard D round clears at 1500 s (session 40:00), leaving 5 min before Strength. Compressed D clears at 1020 s (session 27:00), leaving 8 min. Athletes keep their same triad/lane order. Same-athlete release slots are 480 s apart; even conservatively counting the whole triad through reset leaves at least 420 s recovery, exceeding the 60 s minimum. The last P2 handling slot ends before the main begins, and the earliest E1 starts four minutes into the main; no throw is layered immediately onto handling. Non-release alternatives use one explicit action in their 10 s slot and remain behind the line during unused retrieval time. All empty slots are rest/observation, not extra attempts. Transfer includes ball/rack management and strength setup.

**Strength.** Standard: push 45–53, pull 53–61, knee 61–65, hip 65–69, brace 69–75. Push/pull each reserve 120 s demonstration/setup; groups start at 120/240/360 s within their 480 s block. Knee/hip each reserve 60 s, groups at 60/120/180 s within 240 s. Brace reserves 90 s, groups at 90/165/240 s within 360 s. Compressed: push 35–40, pull 40–45, knee 45–48, hip 48–51, brace 51–55. Push/pull reserve 90 s, groups at 90/165/240 s within 300 s. Knee/hip reserve 60 s, groups at 60/95/130 s within 180 s. Brace reserves 60 s, groups at 60/120/180 s within 240 s. One set per role, never a circuit or superset. Longest bouts are push 17 s, both-side row 52 s, squat 25 s, hinge 21 s, heel taps 26 s; breathing replacement is 40 s plus 15 s quiet recovery. The longest compact pull ends at 292 s, within 300; final breathing recovery ends at 235 s, within 240. Fixed groups preserve at least 60 s between adjacent strength roles. The last standard throw-to-first-push gap is at least 420 s even using the latest group’s full clearance and the earliest push start; actual same-athlete recovery is longer. Fatigue or symptoms may still require fewer actions.''',
 alternatives='''**Main routes are independent of D/L volume.** For each of ages 9–11, 12–14 and 15–18, the four possible E1 routes use D 3 standard / 2 compressed sets or L 2 / 1, each with at least 60 s recovery: (1) one stationary chest throw as listed; (2) one no-release ball action, 2 s rack pickup/chest setup + 3 s comfortable hold + 3 s set-down + 2 s reset = 10 s; (3) one unloaded reach/return cycle, 2 s chest setup + 2 s reach + 2 s retract + 4 s relax = 10 s; (4) one quiet-standing orientation, 2 s settle + 2 s comfortable standing + 6 s reset = 10 s. Ball holding uses the same independently comfortable declared ball at easy 1–2/10; reach is unloaded easy 1–2/10; standing is minimal effort. All keep feet planted, no dip or jump. Each replaces its listed opportunity; none is added. No-release work records zero throws and no release/retrieval pass. If no physical route is appropriate, defer the domain and record zero completed work. A no-release route is an instructional fallback, not an equivalent explosive training stimulus.

**P1 alternatives for every age and mode:** one 10 s unloaded cycle as listed, or one 10 s quiet-standing orientation, with 20 s recovery. **P2 alternatives for every age and mode:** one 24 s floor-pickup/ball-start/2 m carry/floor-set-down handling set as listed (one 5 s hold), or one 10 s unloaded reach/return cycle, or one 10 s quiet-standing orientation inside the same 24 s group slot, with 60 s recovery. P2 has zero releases on every route. A throwing E1 requires comfortable floor pickup/set-down and ordinary carrying from the counted P2 or a direct equivalent; its first full retrieval after shutdown is still a counted observation, not an assumed passed 6 m route. An E1 rack-hold needs its own comfortable actual handling. A throwing E1 or ball-hold E1 requires actual comfortable P2 handling or a directly documented equivalent, and throwing also requires the independent unloaded arm path and conduct. P2 unloaded/standing cannot manufacture handling evidence. A P1 standing choice due to unknown upper-body tolerance requires separate evidence before P2 reach/hold or a throwing E1; route names do not grant prerequisites.

**Ball does not fit or containment is unavailable:** use a separately eligible no-release/unloaded route and record the missing throw exposure. Do not silently replace with a heavy slam ball, overhead throw, wall rebound, partner catch, moving pass or floor support drill. The 0.5 kg / 18 cm reference is not a minimum: record an actually manageable lighter/smaller inspected implement if available; if a suitable implement is absent, use no-ball work. Any change of ball requires a fresh comfortable handling observation within a listed opportunity and its actual properties in the record. It creates no additional trial.

**Supported breathing replaces S5:** all ages and modes 1 × 4 comfortable breaths, nominal 2 s in / 3 s out without holds or forced depth. Calves/heels fully supported, both arms reaching comfortably, no heel pull or hip lift. Twenty seconds total setup/exit makes 40 s; allow 15 s quiet recovery. Five verified lower-leg supports are required. This observes supported position/breathing, not heel-tap moving-limb competence; shoulder reach tolerance remains its own gate.

**Already qualified suspension pull replaces S2:** secure verified anchors; approximately 70° body angle to floor, actual angle recorded. All ages D 1 × 4 bilateral reps, L 1 × 3; 2 s lower / 1 s pull, at least 5 good reps in reserve, 5 s handling, 60 s recovery. It replaces the bench-row set and requires its own grip, body-line and anchor readiness. Missing bench fit does not establish suspension readiness. If neither pull is suitable, defer that role. Pressing likewise needs a suitable actual stable surface; an unavailable surface is not permission for unqualified floor push-ups.''',
 workload_narrative='''The shared instructional base retains its explicit no-flight preparation counts. P1 adds one unloaded bilateral reach/return or zero reaches on the standing route. P2 adds one no-release ball-handling set with 5 s hold, one floor pickup/set-down and 2 m loaded carry, one unloaded cycle or one standing orientation. All P2 routes have zero throws. E1 adds exactly 3 / 2 / 2 / 1 planned throws for standard D / standard L / compressed D / compressed L on the throwing route, for every age. E1 ball-hold routes instead add that many 3 s holds; reach routes add that many unloaded cycles; standing gives neither. Count faults and partial actions as actual work rather than assuming the whole planned route occurred. Planned throw distance is not an athlete result; actual flight/landing/retrieval distance is recorded. Each actual owner retrieval adds a floor pickup and the actual carried return distance; E1 rack pickup/set-down and P2 floor handling are recorded separately from strength repetitions. Upper-body throws, static holding and presses remain separate measures rather than one invented fatigue score.

This lesson adds zero intentional jumping, running or high-intent maximal throws outside the base. Ordinary walking and retrieval still create contacts; exact contact and return-distance counts remain unknown until observed. Lower-impact does not mean no physical demand. Actual recent OR-02 landing, OR-03 braking/stance and OR-04 running/strength response may select L, modify individual roles or defer them. No attendance pattern creates make-up work.

Five Strength sets: one push, one both-side pull, one knee, one hip, one brace. D push/knee/hip has 3 reps for 9–11 and 4 for 12–14/15–18; L 2/3/3. Push uses 3 s per rep + 5 s setup; knee 5 s + 5 s setup; hip 4 s + 5 s setup. Bench row has D 4 each side, L 2 each, at 4 s per rep + 10 s side change + 10 s handling. Heel taps have D 2 each, L 1 each, at 4 s + 10 s setup. Alternatives replace one set. Retain the actual compatible one-set dose or deliberately reduce a compatible two-set history. The offered D dose is a ceiling, not permission to increase a smaller actual recent dose automatically; use the explicit L route when it matches the current smaller prescription, or record a smaller completed/modified dose and its reason. No physical finisher adds hidden volume.''',
 final_tumbling='''Standard 75–78 water/readiness, 78–84 athlete/coach discussion of who may release and when retrieval starts, 84–88 record actual competency and the next module/main-entry decision, 88–90 transfer. Compressed 55–57 water/readiness, 57–60 record and handoff. All ages add zero physical sets here; no throwing game or penalty exercise.

The separate 30 min Body Control / Tumbling prescription remains UNRESOLVED: exact approved content, age/skill doses, mats and staffing are not supplied. Handoff actual throw/hold/reach, push/pull/support, brace, grip and shoulder/wrist response, attention and all recent lower-body work. The separate coach independently checks eligible support/orientation and actual fatigue before selecting content. A throwing or high-incline press observation does not establish floor support or inversion readiness. This handoff is not a completed tumbling prescription.''',
 coach_record='Record the actual prior relevant exposures and response; chosen base/P1/P2/E1 and support routes; ball type, mass, diameter and observed rebound; actual containment, retrieval route, surface heights, dumbbell load and coach assignment; every release, hold, reach and faulty/partial attempt; strength reps/sides and response; and cue waiting/retrieval behavior. Separate unobserved, needs_instruction, emerging, repeatable, modified and restricted status by domain. Stable-throw handling/stance/direction/retrieval/conduct and the early known release rule must each be repeatable before the corresponding main JUMP-T/REACT-T route. No rule here qualifies go/no-go, landing or cutting. OR-09 changes only cue interpretation at the actual retained task; OR-13 uses only its independently passed movement branch. The Week 1 review follows before OR-06 is authored.',
 review_status='PENDING independent written programming review, deterministic age/mode/route/recovery/handling checks and saved daily ledgers. No numeric schedule proves facility delivery, athlete outcomes, current canonical approval or the separate tumbling prescription.')

session['mapping_refs'] = {'P1':'CHEST-REACH-TEACH','P2':'BALL-HOLD-TEACH','E1':'CHEST-PASS-TEACH','S1':'INCLINE-PUSH','S2':'SUPPORTED-ROW','S3':'SQUAT-BW','S4':'HINGE-BW','S5':'HEEL-TAP'}
session['outline_ref'] = {'path':'instructional_on_ramp/instructional_map.json','id':'OR-05','prior':['OR-01','OR-04'],'next':['OR-09','OR-13']}
session['outline_reconciliation'] = {'P2':'Replace preparation release with progressive implement-setup/permission rehearsal without release; first actual release is already counted E1 set 1. Newcomer retrieval teaching cannot fit in 180 target seconds. Preserve primary release/retrieval objective.', 'unchanged':'Known cue only; stable position; push/pull teaching with familiar knee/hip/brace; no new lower impact, separate tumbling.'}
session['preparation_routes'] = {key:{route:{'mapping_ref':{'reach':'CHEST-REACH-TEACH','hold':'BALL-HOLD-TEACH','standing':'BILATERAL-STAND-TEACH'}[route],
    'age_prescriptions':{a:{m:task(route,key,m) for m in MODES} for a in AGES}}
    for route in (['reach','standing'] if key=='P1' else ['hold','reach','standing'])} for key in ['P1','P2']}
session['primary_routes'] = {route:{'mapping_ref':{'throw':'CHEST-PASS-TEACH','hold':'BALL-HOLD-TEACH','reach':'CHEST-REACH-TEACH','standing':'BILATERAL-STAND-TEACH'}[route],
    'allowed_modes':list(MODES),'requires_actual_ball_handling':route in ['throw','hold'],'requires_actual_floor_access_and_carry':route=='throw',
    'requires_unloaded_arm_path':route in ['throw','reach'],'requires_verified_containment_and_retrieval':route=='throw',
    'grants_throw_observation':route=='throw','grants_go_no_go':False,'grants_reactive_cut':False,
    'age_prescriptions':{a:{m:task(route,'E1',m) for m in MODES} for a in AGES}} for route in ['throw','hold','reach','standing']}
session['alternative_doses'] = copy.deepcopy(prior['alternative_doses'])
session['alternative_doses']['suspension_pull']['replaces']='S2'
session['route_policy'] = {'P2_release_count':0,'P1_standing_does_not_grant_arm_path':True,'P2_no_ball_does_not_grant_handling':True,
    'first_throw_requires_prior_successful_throw':False,'first_throw_requires_actual_handling_arm_path_and_conduct':True,
    'direct_equivalent_evidence_permitted':True,'within_visit_ball_mass_increase':False,'extra_fit_or_corrective_trials':False,
    'missing_evidence':'retain independently eligible instruction route or defer; no completed result assumed','actual_history':None}
session['timing_model'] = {'athletes':15,'coaches_assumed':2,'lanes_assumed':3,
    'targets':{'P1':{'budget_s':40,'demo_s':10,'group_size':5,'starts_s':[10,20,30]},
               'P2':{'budget_s':140,'gather_s':10,'demo_s':10,'group_size':3,'starts_s':[20,44,68,92,116]}},
    'primary':{'group_size':3,'triad_offsets_s':[0,60,120,180,240],'athlete_slots_s':[0,10,20],
               'triad_phases':[{'name':'individual_actions','start_s':0,'end_s':30},{'name':'stopped_ball_shutdown_check','start_s':30,'end_s':35},
                               {'name':'all_clear_retrieval','start_s':35,'end_s':50},{'name':'rack_queue_reset','start_s':50,'end_s':60}],
               'all_lanes_closed_during_retrieval':True,'max_simultaneous_releases':1,'between_round_minimum_recovery_s':60,
               'standard':{'block_start_s':900,'rounds_relative_s':[240,720,1200],'block_end_s':2700},
               'compressed':{'block_start_s':600,'rounds_relative_s':[240,720],'block_end_s':2100}},
    'strength':{}}
for booking,budgets,starts in [('standard',[480,480,240,240,360],[[120,240,360],[120,240,360],[60,120,180],[60,120,180],[90,165,240]]),
                              ('compressed',[300,300,180,180,240],[[90,165,240],[90,165,240],[60,95,130],[60,95,130],[60,120,180]])]:
    session['timing_model']['strength'][booking] = {'block_start_s':2700 if booking=='standard' else 2100,
        'block_end_s':4500 if booking=='standard' else 3300,'tasks':[{'key':f'S{i+1}','budget_s':b,'demo_s':st[0],'group_starts_by_set_s':[st]} for i,(b,st) in enumerate(zip(budgets,starts))]}
session['geometry'] = {'actual_verified':False,'planning_lane_width_m':3,'planning_protected_length_m':6,'side_buffer_m':1,
    'first_landing_reference_m':[1,3],'distance_is_score':False,'requires_actual_ball_containment_inspection':True,
    'target_people':False,'wall_return':False,'catching':False,'retrieval_max_outbound_m_model':6,'retrieval_max_return_m_model':6,
    'retrieval_walk_and_pickup_budget_s':15,'throwing_during_retrieval':False,'coach_sightlines_verified':False,
    'planning_ball_mass_kg':0.5,'planning_ball_diameter_cm':18,'ball_reference_is_mandatory':False,'actual_ball_properties':None}
session['history_policy'] = {'strength_sets_per_role':1,'prior_one_set':'retain actual compatible one-set setup/dose; D is not automatic rep increase',
    'prior_two_sets':'explicitly reduce to one supporting set','unknown':'teach one small counted set; no invented two-set baseline',
    'recent_OR02_OR03_OR04_response':'select current independently eligible route/L dose or defer, accounting for lower-body and shoulder/support work','actual_history':None}
session['release_status'] = {'athletic_prescription_complete':True,'programming_review_pass':False,'operational_release_verified':False,'separate_tumbling_prescription_complete':False}
session['timing_narrative'] += '\n\n**Immediate shutdown overrides the schedule.** Waiting athletes leave their balls parked until their own named setup instruction. A premature release, escaped or still-moving ball, person entering a lane, or lost conduct stops the next A/B/C action immediately; the planned 30–35 s check is an additional confirmation, not permission to continue until then. Cancel the unreleased actions until all lanes are clear. The remaining scheduled opportunities may be omitted; no replacement is added. First-throw technique and cue meaning are demonstrated verbally/visually during the initial 240 s; the 10 s slot holds the listed physical action, not a hidden second lesson or extra rehearsal. More explanation consumes slack and delays that action.'
session['timing_model']['primary']['immediate_fault_shutdown']=True
session['timing_model']['primary']['waiting_balls_parked']=True
session['timing_model']['primary']['athlete_specific_permission']=True
session['timing_model']['primary']['retrieval_segments']=[{'name':'walk_outbound','seconds':6,'distance_m_cap':6},{'name':'controlled_pickup','seconds':3},{'name':'carry_walk_return','seconds':6,'distance_m_cap':6}]
session['timing_model']['primary']['rack_queue_segments']=[{'name':'controlled_rack_setdown','seconds':5},{'name':'clear_start_and_rejoin_queue','seconds':5}]
session['timing_narrative'] += ' The 15 s retrieval model is 6 s ordinary outward walking (up to 6 m), 3 s controlled pickup, 6 s ordinary walking carry back (up to 6 m). The following 10 s reset is 5 s controlled rack set-down plus 5 s clearing the start/rejoining the rear queue. These are separate physical actions and planning allowances; no forced walking pace or guaranteed ball travel is implied. Longer actual pickup/return requires a later restart.'
exercises[0]['execution'] += ' Use relaxed open hands with palms facing forward and fingers comfortably upward, as if supporting the back/sides of a small ball. Keep wrists comfortable and elbows below shoulder height without pinning them to the ribs. Reach only through a comfortable owned range; record any adapted orientation.'
for e in exercises[1:3]:
    e['execution'] += ' Use both palms/finger pads on the rear-side surfaces of the ball, thumbs comfortably behind it and fingers spread enough for a secure grip; no forced thumb shape or joint angle. Keep wrists comfortable and elbows below shoulder height. Ball rests in the hands at chest level, not squeezed against the throat. Declare the individually fitting contact and retain it across P2/E1; a ball requiring painful wrist position or an insecure spread is unsuitable.'
exercises[1]['cues']='Reach the floor comfortably before taking the ball; two hands; stand still for the hold; walk and turn on instruction; return and set down gently.'
exercises[1]['metadata']='Method: observed floor handling and waiting instruction. Tenets: Body Control / Strength; equipment conduct and attention integrated. Pattern: one floor pickup, chest hold, short walking carry/turn and floor set-down. Equipment: declared soft medicine ball, marked original floor spot and a separate unobstructed 1 m out-and-back path per lane; no shared crossing.'
exercises[1]['competency'] += ' Comfortable ordinary walking/turning is required for the carry. Comfortable unloaded floor access is independently established or observed during the initial reach of this same counted P2 pickup before accepting the ball load. An owned partial-range hinge/squat does not establish floor access. If that initial reach is unavailable or uncomfortable, do not lift: end the assigned action, have the coach manage the ball and use a separately eligible no-ball task later. This is one counted pickup opportunity, not an extra screening repetition; the 5 s envelope may be delayed for instruction.'
session['stage_label']='Separate instructional session · Week 1, Day 5 · individually authored · written athletic design reviewed'
session['status_note']='Independent written athletic programming review passed. The companion results record 1,152 conditional numeric scenarios and 35 rejecting probes. Current canonical approval, actual facility execution, individual readiness and the precise separate 30 min tumbling prescription remain unverified; planned work is not an athlete result.'
session['review_status']='Independent critic PASS for the complete written athletic lesson after preparation/source, first-visit handling, floor retrieval, grip/contact and immediate-shutdown corrections. Independent numeric verifier PASS: 1,152 conditional scenarios, 35 rejecting probes, eight progression rows and separate workload ledger. See or_05_review.md and or_05_check_results.json for scope and current fingerprints. This does not certify actual delivery, current canonical release or a complete separate tumbling prescription.'
session['release_status']['programming_review_pass']=True
if __name__ == '__main__':
    save(session,'instructional_on_ramp/week_01/or_05')
