import test from 'node:test'
import assert from 'node:assert/strict'
import {createHarness} from '../testing/harness.js'
import {runWorkforceAutomation} from '../workforceAutomation.js'
test('pay review requires current verified elections and payment setup and reopens readiness after changes',{skip:!process.env.PAYROLL_TEST_DATABASE_URL},async t=>{
 const h=await createHarness();t.after(()=>h.close())
 const api=async(path,body,status=200,method=body===undefined?'GET':'POST')=>{const r=await fetch(`${h.url}/api/admin/payroll${path}`,{method,headers:{Authorization:'Bearer payroll-test-admin','Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json();assert.equal(r.status,status,JSON.stringify(j));return j.data}
 const e=await api('/employees',{employeeNumber:'PAY-SETUP-REVIEW',legalFirstName:'Pay',legalLastName:'Setup',hireDate:'2026-08-03',hourlyRateCents:2500},201)
 const packet=()=>api(`/employees/${e.id}/onboarding`)
 const task=(await packet()).tasks.find(t=>t.task_key==='PAY_REVIEW')
 const review=(fingerprint,status=200)=>api(`/employees/${e.id}/onboarding/${task.id}/review`,{status:'COMPLETE',note:'Reviewed employee tax, payment and benefit settings',benefitsReview:{disposition:'NOT_OFFERED',effectiveOn:'2026-08-03',summary:'No employer benefit plan is offered for this synthetic hire.',evidenceReference:'Synthetic employer offering review',confirmed:true},paySetupFingerprint:fingerprint},status)
 assert.equal((await packet()).paySetup.issues.length,4)
 await review((await packet()).paySetup.fingerprint,409)
 await h.pool.query("UPDATE payroll_employee SET w4_status='COMPLETE',state_withholding_status='COMPLETE' WHERE id=$1",[e.id])
 await h.pool.query("UPDATE payroll_onboarding_task SET status='COMPLETE',response='{\"method\":\"CHECK\"}' WHERE employee_id=$1 AND task_key='PAYMENT'",[e.id])
 const elections={confirmed:true,sourceNote:'Synthetic verified signed hiring tax forms',federal:{filingStatus:'SINGLE'},maryland:{filingStatus:'SINGLE',localRate:3.2,exemptions:1}}
 await api(`/employees/${e.id}/tax-elections`,elections,200,'PATCH')
 let current=await packet();assert.deepEqual(current.paySetup.issues,[])
 await api(`/employees/${e.id}/onboarding/${task.id}/review`,{status:'COMPLETE',note:'Review missing the benefits disposition',paySetupFingerprint:current.paySetup.fingerprint},400)
 await review('outdated',409);await review(current.paySetup.fingerprint)
 current=await packet();assert.equal(current.paySetup.status,'CURRENT');assert.equal(current.paySetup.taxYear,2026)
 const saved=(await h.pool.query('SELECT response FROM payroll_onboarding_task WHERE id=$1',[task.id])).rows[0].response
 assert.equal(saved.paySetup.basis.taxElection.elections.federal.extraWithholdingCents,0)
 await api(`/employees/${e.id}/tax-elections`,{...elections,federal:{filingStatus:'SINGLE',extraWithholdingCents:1000}},200,'PATCH')
 const changed=await packet();assert.equal(changed.paySetup.status,'NEEDS_REVIEW')
 assert.ok(changed.readiness.blockers.includes('Review the current employee pay setup'))
 assert.equal(changed.readiness.complete,current.readiness.complete-1)
 await review(current.paySetup.fingerprint,409)
 await runWorkforceAutomation(h.pool,1,{sync:false,now:new Date('2026-08-03T12:00Z')})
 const alert=()=>h.pool.query('SELECT status FROM payroll_alert WHERE facility_id=1 AND dedupe_key=$1',[`pay-setup-review-${e.id}`])
 assert.equal((await alert()).rows[0].status,'OPEN')
 await review(changed.paySetup.fingerprint)
 await runWorkforceAutomation(h.pool,1,{sync:false,now:new Date('2026-08-03T12:00Z')})
 assert.equal((await alert()).rows[0].status,'DISMISSED')
 await api('/settings',{benefitsText:'Updated benefits policy for this employer'},200,'PATCH')
 const policyChanged=await packet();assert.equal(policyChanged.paySetup.status,'NEEDS_REVIEW');assert.equal(policyChanged.paySetup.benefitsCurrent,false)
 await review(policyChanged.paySetup.fingerprint)
 assert.equal((await packet()).paySetup.benefitsCurrent,true)
 await h.pool.query("UPDATE payroll_employee SET work_state='VA' WHERE id=$1",[e.id])
 assert.ok((await packet()).paySetup.issues.length)
 await review((await packet()).paySetup.fingerprint,409)
 const history=await api(`/employees/${e.id}/onboarding/${task.id}/history`)
 assert.ok(history.some(r=>r.snapshot.response.paySetup?.fingerprint===saved.paySetup.fingerprint))
 assert.ok(history.some(r=>r.snapshot.response.benefitsReview?.policyTerms===saved.benefitsReview.policyTerms&&r.snapshot.response.benefitsReview?.evidenceReference===saved.benefitsReview.evidenceReference))
 await h.pool.query("UPDATE payroll_employee SET direct_deposit_status='ACTIVE' WHERE id=$1",[e.id])
 await h.pool.query("UPDATE payroll_onboarding_task SET response='{\"method\":\"DIRECT_DEPOSIT\"}' WHERE employee_id=$1 AND task_key='PAYMENT'",[e.id])
 const deposit=await packet();assert.equal(deposit.paySetup.paymentReadiness.status,'NO_CONNECTION');assert.ok(deposit.paySetup.issues.includes('Configure the employer payment connection.'))
 await review(deposit.paySetup.fingerprint,409)
 const paymentTask=deposit.tasks.find(task=>task.task_key==='PAYMENT')
 await h.pool.query("UPDATE payroll_onboarding_task SET status='SUBMITTED',response='{\"method\":\"DIRECT_DEPOSIT\",\"reference\":\"Synthetic signed provider authorization receipt\"}' WHERE id=$1",[paymentTask.id])
 await api(`/employees/${e.id}/onboarding/${paymentTask.id}/review`,{status:'COMPLETE',note:'Reviewed the employee payment-method election'},200)
 assert.equal((await h.pool.query('SELECT direct_deposit_status FROM payroll_employee WHERE id=$1',[e.id])).rows[0].direct_deposit_status,'INVITED')
})
