import test from 'node:test'
import assert from 'node:assert/strict'
import {buildEmployeePreview} from '../payrollEngine.js'
import {reconcileSupplementalPayments} from '../supplementalPaymentHistory.js'
test('supplemental history subtracts only the retained health allocation from annual bonus wages',()=>{
 const health125={version:1,classification:'SECTION125_ACCIDENT_HEALTH_PREMIUM',items:[{planId:'medical',optionId:'family',deductionCents:12500,annualBonusDeductionCents:2500,qualificationFingerprint:'a'.repeat(64),authorizationFingerprint:'b'.repeat(64)}]}
 const frozen=buildEmployeePreview({employee:{id:1,payType:'HOURLY',hourlyRateCents:25000,workState:'MD',residenceState:'MD',w4Status:'COMPLETE',stateWithholdingStatus:'COMPLETE'},entries:[{clockIn:'2026-09-09T12:00:00Z',clockOut:'2026-09-09T20:00:00Z',unpaidBreakMinutes:0,status:'APPROVED'}],adjustments:[{kind:'BONUS',name:'Annual bonus',amountCents:50000,taxTreatmentVerified:true,bonusReview:{classification:'DISCRETIONARY',paymentType:'ANNUAL_LUMP_SUM',verifiedAt:'2026-09-16T16:00:00Z'}}],taxElection:{verified:true,federal:{filingStatus:'SINGLE'},maryland:{filingStatus:'SINGLE',localRate:3.2,exemptions:1}},employerTaxConfig:{year:2026,verified:true,futaRatePercent:.6,mdUiRatePercent:2.6},health125,ytdTaxWages:{socialSecurityWagesCents:0,medicareWagesCents:0,futaWagesCents:0,marylandUnemploymentWagesCents:0}})
 const row={run_id:1,employee_id:1,status:'FINALIZED',run_kind:'REGULAR',payment_date:'2026-09-18',payment_confirmation_reference:'SYNTHETIC-PAID-HEALTH',withholding_verified_at:'2026-09-18T12:00:00Z',regular_pay_cents:frozen.regularPayCents,overtime_pay_cents:frozen.overtimePayCents,other_taxable_pay_cents:frozen.otherTaxablePayCents,pretax_deduction_cents:frozen.pretaxDeductionCents,federal_income_tax_cents:frozen.federalIncomeTaxCents,state_income_tax_cents:frozen.stateIncomeTaxCents,calculation_snapshot:{employees:[frozen]},statement_snapshot:{incomeTaxWageBasis:structuredClone(frozen.incomeTaxWageBasis)}}
 const result=reconcileSupplementalPayments([row],'2026-10-01')
 assert.equal(result.reconciled,true,JSON.stringify(result.issues));assert.equal(result.ytdSupplementalCents,47500)
 assert.equal(result.evidence[0].healthSupplementalPretaxCents,2500);assert.equal(result.evidence[0].incomeTaxGrossCents,237500);assert.equal(result.regularWithholdingVerified,false)
 for(const mutate of [r=>r.pretax_deduction_cents++,r=>{delete r.statement_snapshot.incomeTaxWageBasis},r=>r.calculation_snapshot.employees[0].health125.annualBonusDeductionCents++,r=>r.calculation_snapshot.employees[0].payItems.find(i=>i.kind==='HEALTH_SECTION125_PRETAX').amountCents++]){const invalid=structuredClone(row);mutate(invalid);assert.equal(reconcileSupplementalPayments([invalid],'2026-10-01').reconciled,false)}
})
