import { useEffect, useId, useRef, useState, type KeyboardEvent, type ReactNode } from 'react'
import { Activity, ArrowDownUp, ArrowRight, ArrowUp, ArrowUpRight, Check, ChevronLeft, ChevronRight, Clock3, Footprints, Info, Layers, LayoutGrid, Move, MoveHorizontal, Package, RotateCw, Sparkles, Target, X, Zap } from 'lucide-react'
import { ACCELERATOR_PHASES, ACCELERATOR_PROGRAMS, EQUIPMENT_NOTES, getAcceleratorSessions, type AcceleratorExercise, type AcceleratorPhase, type AcceleratorProgramId, type AcceleratorSession } from '../../coach/athleticismAccelerator'

const PROGRAM_ICONS = { endurance: Activity, speed: Zap, horizontal: MoveHorizontal, vertical: ArrowUp, rebound: ArrowDownUp, mobility: Move, reactive: Sparkles, upper: RotateCw, lower: Footprints }
const FOCUS_RING = 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-vortex-red focus-visible:ring-offset-2'
type Detail = { title: string; eyebrow?: string; content: ReactNode }
const timeLabel = (session: AcceleratorSession) => session.minutes ? `${session.minutes.join('–')} min + preparation` : 'Timing & delivery'

export default function AthleticismAcceleratorPanel() {
  const [programId, setProgramId] = useState<AcceleratorProgramId | null>(null)
  const [classIndex, setClassIndex] = useState(0)
  const [phase, setPhase] = useState<AcceleratorPhase>('E')
  const [detail, setDetail] = useState<Detail | null>(null)
  const selectedProgram = ACCELERATOR_PROGRAMS.find((program) => program.id === programId)
  const sessions = selectedProgram ? getAcceleratorSessions(selectedProgram.id) : []
  const session = sessions[classIndex]
  useEffect(() => { setClassIndex(0); setPhase('E'); setDetail(null) }, [programId])
  const selectClass = (index: number) => { setClassIndex(index); setDetail(null) }

  return <div className="space-y-5 pb-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[0.18em] text-gray-500">Session Design</p><h2 className="text-2xl font-bold tracking-tight text-gray-950">Athleticism Accelerator</h2>{!selectedProgram && <p className="mt-1 text-sm text-gray-500">A clear plan. A focused session.</p>}</div>{!selectedProgram && <span className="rounded-full border border-gray-200 bg-white px-3 py-1.5 text-xs font-medium text-gray-600">9 programs · 12wk</span>}</header>
    {!selectedProgram ? <ProgramCards onSelect={setProgramId} /> : <>
      <ProgramTabs selected={selectedProgram.id} onSelect={setProgramId} />
      <div role="tabpanel" id={`accelerator-panel-${programId}`} aria-labelledby={`accelerator-tab-${programId}`}>
        <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-bold text-gray-950">{selectedProgram.title} <span className="font-normal text-gray-400">12wk</span></h3><p className="mt-1 text-xs text-gray-500">12 class exposures · Ages 12–14 · Coach-led</p></div><button type="button" className={`flex items-center gap-2 rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 ${FOCUS_RING}`} onClick={() => setDetail({ title: 'The 12-class plan', eyebrow: selectedProgram.title, content: <PlanOverview sessions={sessions} selected={classIndex} onSelect={selectClass} /> })}><Layers className="h-4 w-4" /> Plan overview</button></div>
        <ClassSelector sessions={sessions} selected={classIndex} onSelect={selectClass} />
        <section className="mt-4 overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm" aria-label={`Class ${session.n} workout`}><div className="border-b border-gray-100 bg-gradient-to-r from-red-50/70 to-white px-4 py-4 sm:px-5"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2.5"><span className="rounded-md bg-vortex-red px-2 py-1 text-[11px] font-bold uppercase tracking-wide text-white">Class {session.n}</span><h4 className="font-bold text-gray-950">{session.title}</h4></div><button type="button" className={`flex items-center gap-1.5 rounded text-xs text-gray-600 hover:text-vortex-red ${FOCUS_RING}`} onClick={() => setDetail({ title: 'Timing & delivery', content: <DeliveryNotes session={session} /> })}><Clock3 className="h-3.5 w-3.5" /> {timeLabel(session)} <Info className="h-3.5 w-3.5" /></button></div><p className="mt-2 text-sm leading-relaxed text-gray-600">{session.effort}</p></div>
          <div className="grid xl:grid-cols-[minmax(0,1fr)_240px]"><aside className="border-b border-gray-100 bg-gray-50/60 p-4 xl:order-2 xl:border-b-0 xl:border-l" aria-label="Equipment for the day"><h5 className="mb-3 flex items-center gap-2 text-sm font-bold text-gray-900"><Package className="h-4 w-4 text-vortex-red" /> Equipment for the day</h5><ul className="flex flex-wrap gap-2 xl:flex-col">{session.equipment.length ? session.equipment.map((item) => <li key={item} className="flex items-center gap-2 rounded-lg border border-gray-200/80 bg-white px-2.5 py-2 text-xs font-medium text-gray-700"><Check className="h-3.5 w-3.5 shrink-0 text-gray-400" /> {item}</li>) : <li className="flex items-center gap-2 rounded-lg border border-gray-200/80 bg-white px-2.5 py-2 text-xs font-medium text-gray-700"><Check className="h-3.5 w-3.5 shrink-0 text-gray-400" /> Bodyweight</li>}<li className="flex items-center gap-2 rounded-lg border border-gray-200/80 bg-white px-2.5 py-2 text-xs font-medium text-gray-700"><Target className="h-3.5 w-3.5 shrink-0 text-gray-400" /> Clear working space</li></ul><button type="button" className={`mt-3 flex items-center gap-1.5 rounded text-xs font-semibold text-vortex-red hover:underline ${FOCUS_RING}`} onClick={() => setDetail({ title: 'Equipment & station setup', eyebrow: `Class ${session.n}`, content: <EquipmentNotes session={session} /> })}>Setup & substitutions <ArrowUpRight className="h-3.5 w-3.5" /></button><div className="mt-4 hidden border-t border-gray-200 pt-4 xl:block"><p className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Today’s plan</p><div className="mt-2 flex gap-5"><div><p className="text-xl font-bold tabular-nums text-gray-900">14</p><p className="text-[11px] text-gray-500">exercises</p></div><div><p className="text-xl font-bold tabular-nums text-gray-900">6</p><p className="text-[11px] text-gray-500">primary lifts</p></div></div></div></aside>
            <div className="min-w-0 p-4 sm:p-5"><PhaseSelector selected={phase} onSelect={setPhase} /><div role="tabpanel" id={`accelerator-phase-panel-${phase}`} aria-labelledby={`accelerator-phase-${phase}`} className="mt-4">{phase === 'prepare' ? <PreparationView session={session} /> : <><PhaseBrief phase={phase} /><div className="mt-3 divide-y divide-gray-100">{session.exercises.filter((exercise) => exercise.id.startsWith(phase)).map((exercise, index) => <ExerciseRow key={exercise.id} exercise={exercise} anchor={index === 0 && phase !== 'S'} onOpen={() => setDetail({ title: exercise.name, eyebrow: `Class ${session.n} · ${exercise.id}`, content: <ExerciseNotes exercise={exercise} /> })} />)}</div><div className="mt-3 flex flex-wrap items-center justify-between gap-3 border-t border-gray-100 pt-3"><button type="button" className={`flex items-center gap-1.5 rounded text-xs font-medium text-gray-500 hover:text-vortex-red ${FOCUS_RING}`} onClick={() => setDetail({ title: 'Coaching considerations', eyebrow: `Class ${session.n}`, content: <CoachingNotes session={session} /> })}><Info className="h-3.5 w-3.5" /> Quality, scaling & readiness</button>{phase !== 'P' && <button type="button" className={`flex items-center gap-1 rounded text-xs font-semibold text-vortex-red ${FOCUS_RING}`} onClick={() => setPhase(phase === 'E' ? 'S' : 'P')}>Next: {phase === 'E' ? 'Resilience' : 'Primary strength'} <ChevronRight className="h-4 w-4" /></button>}</div></>}</div></div>
          </div></section>
      </div>
    </>}{detail && <DetailDialog detail={detail} onClose={() => setDetail(null)} />}
  </div>
}

function ProgramCards({ onSelect }: { onSelect: (id: AcceleratorProgramId) => void }) { return <><div className="relative overflow-hidden rounded-2xl bg-gray-950 px-5 py-6 text-white sm:px-6"><p className="relative text-[11px] font-bold uppercase tracking-[0.18em] text-red-300">Built around the workout</p><h3 className="relative mt-2 text-xl font-semibold">Choose a quality. See the day’s plan.</h3><p className="relative mt-2 max-w-xl text-sm text-gray-300">Equipment, exercise doses, and recovery in one view. Open coaching notes when you need more.</p></div><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold text-gray-800">Your program collection</h3><p className="text-xs text-gray-500">Nine completed 12-week plans</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{ACCELERATOR_PROGRAMS.map((program) => { const Icon = PROGRAM_ICONS[program.icon]; return <button key={program.id} type="button" onClick={() => onSelect(program.id)} aria-label={`${program.title} 12wk`} className={`group flex flex-col rounded-xl border border-gray-200 bg-white p-4 text-left transition hover:border-vortex-red hover:shadow-sm ${FOCUS_RING}`}><div className="mb-4 flex w-full items-center justify-between gap-3"><span className="rounded-xl bg-gray-100 p-2.5 text-gray-600"><Icon className="h-5 w-5" /></span><span className="text-[10px] font-bold uppercase tracking-wider text-vortex-red">View 12 classes</span></div><h4 className="text-base font-bold text-gray-950">{program.title} <span className="whitespace-nowrap text-sm font-medium text-gray-400">12wk</span></h4><p className="mt-1 text-xs leading-relaxed text-gray-500">{program.description}</p><div className="mt-4 flex w-full items-center justify-between border-t border-gray-200/70 pt-3 text-xs"><span className="font-semibold text-vortex-red">Open workout plan</span><ArrowRight className="h-4 w-4 text-gray-400 transition-transform group-hover:translate-x-1 group-hover:text-vortex-red" /></div></button> })}</div></> }
function moveTab(event: KeyboardEvent<HTMLDivElement>) { const tabs = Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('[role="tab"]')); const index = tabs.indexOf(document.activeElement as HTMLButtonElement); const next = event.key === 'ArrowRight' ? (index + 1) % tabs.length : event.key === 'ArrowLeft' ? (index - 1 + tabs.length) % tabs.length : event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : null; if (next === null) return; event.preventDefault(); tabs[next].focus(); tabs[next].click() }
function ProgramTabs({ selected, onSelect }: { selected: AcceleratorProgramId; onSelect: (id: AcceleratorProgramId | null) => void }) { return <div className="flex min-w-0 gap-3 border-b border-gray-200 pb-2"><button type="button" onClick={() => onSelect(null)} aria-label="All programs" className={`shrink-0 self-start rounded-lg border border-gray-200 bg-white p-2.5 text-gray-600 hover:text-vortex-red ${FOCUS_RING}`}><LayoutGrid className="h-4 w-4" /></button><div role="tablist" aria-label="Accelerator programs" onKeyDown={moveTab} className="flex min-w-0 gap-1 overflow-x-auto pb-1">{ACCELERATOR_PROGRAMS.map((program) => <button key={program.id} type="button" role="tab" id={`accelerator-tab-${program.id}`} aria-controls={`accelerator-panel-${program.id}`} aria-selected={selected === program.id} tabIndex={selected === program.id ? 0 : -1} onClick={() => onSelect(program.id)} className={`shrink-0 rounded-lg px-3 py-2.5 text-xs font-semibold ${FOCUS_RING} ${selected === program.id ? 'bg-gray-950 text-white' : 'text-gray-500 hover:bg-gray-100 hover:text-gray-900'}`}>{program.title} <span className="text-gray-400">12wk</span></button>)}</div></div> }
function ClassSelector({ sessions, selected, onSelect }: { sessions: AcceleratorSession[]; selected: number; onSelect: (index: number) => void }) { return <div className="rounded-xl border border-gray-200 bg-white px-3 py-3"><div className="mb-2 flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Select a class</p><div className="flex items-center gap-3"><span className="text-[11px] tabular-nums text-gray-500">{selected + 1} of 12</span><button type="button" aria-label="Previous class" disabled={selected === 0} onClick={() => onSelect(selected - 1)} className={`rounded p-1 text-gray-600 disabled:opacity-25 ${FOCUS_RING}`}><ChevronLeft className="h-4 w-4" /></button><button type="button" aria-label="Next class" disabled={selected === 11} onClick={() => onSelect(selected + 1)} className={`rounded p-1 text-gray-600 disabled:opacity-25 ${FOCUS_RING}`}><ChevronRight className="h-4 w-4" /></button></div></div><div className="grid grid-cols-6 gap-1.5 sm:grid-cols-12">{sessions.map((item, index) => <button key={item.n} type="button" aria-label={`Class ${item.n}: ${item.title}`} aria-pressed={selected === index} onClick={() => onSelect(index)} className={`rounded-md py-2 text-sm font-semibold tabular-nums ${FOCUS_RING} ${selected === index ? 'bg-vortex-red text-white shadow-sm' : 'bg-gray-50 text-gray-500 hover:bg-red-50 hover:text-vortex-red'}`}>{String(item.n).padStart(2, '0')}</button>)}</div></div> }
function PhaseSelector({ selected, onSelect }: { selected: AcceleratorPhase; onSelect: (phase: AcceleratorPhase) => void }) { return <div role="tablist" aria-label="Workout phases" onKeyDown={moveTab} className="grid grid-cols-2 gap-1 rounded-lg bg-gray-100 p-1 sm:grid-cols-4">{ACCELERATOR_PHASES.map((item, index) => <button key={item.id} type="button" role="tab" id={`accelerator-phase-${item.id}`} aria-controls={`accelerator-phase-panel-${item.id}`} aria-selected={selected === item.id} onClick={() => onSelect(item.id)} className={`rounded-md px-2 py-2 text-left ${FOCUS_RING} ${selected === item.id ? 'bg-white shadow-sm' : 'hover:bg-white/60'}`}><span className={`block text-xs font-bold ${selected === item.id ? 'text-vortex-red' : 'text-gray-600'}`}>{index + 1}. {item.title}</span><span className="mt-1 block text-[10px] text-gray-500">{item.subtitle}</span></button>)}</div> }
function PhaseBrief({ phase }: { phase: AcceleratorPhase }) { const notes = phase === 'E' ? 'Use fast, purposeful efforts. Follow the prescribed recovery and preserve technique.' : phase === 'S' ? 'Keep work light and controlled. The goal is resilience, not fatigue.' : 'Leave 2–3 clean reps in reserve and use the prescribed load-preparation sets.'; return <div className="rounded-lg bg-gray-50 px-3 py-2.5 text-xs leading-relaxed text-gray-600">{notes}</div> }
function ExerciseRow({ exercise, anchor, onOpen }: { exercise: AcceleratorExercise; anchor: boolean; onOpen: () => void }) { return <div className="flex items-start gap-3 py-2.5"><span className={`mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg text-[10px] font-bold ${anchor ? 'bg-red-50 text-vortex-red' : 'bg-gray-100 text-gray-500'}`}>{exercise.id}</span><div className="grid min-w-0 flex-1 grid-cols-[minmax(0,1fr)_24px] gap-x-2 gap-y-1.5 sm:grid-cols-[minmax(0,1fr)_190px_24px]"><div className="min-w-0"><button type="button" onClick={onOpen} className={`rounded text-left text-sm font-semibold leading-snug text-gray-900 hover:text-vortex-red ${FOCUS_RING}`}>{exercise.name}</button><p className="mt-1 text-[11px] text-gray-500">{exercise.equipment.join(' · ')}{anchor ? ' · Main focus' : ''}</p></div><button type="button" onClick={onOpen} aria-label={`Coaching notes for ${exercise.name}`} className={`col-start-2 row-start-1 self-start rounded p-1 text-gray-400 hover:bg-red-50 hover:text-vortex-red sm:col-start-3 ${FOCUS_RING}`}><Info className="h-4 w-4" /></button><div className="col-start-1 row-start-2 flex flex-wrap items-center gap-x-3 gap-y-1 sm:col-start-2 sm:row-start-1 sm:block"><span className="inline-block rounded bg-gray-100 px-2 py-1 text-xs font-semibold text-gray-800">{exercise.prescription}</span><span className="flex items-start gap-1 text-[11px] text-gray-500 sm:mt-1"><Clock3 className="mt-0.5 h-3 w-3 shrink-0" /> {exercise.rest}</span></div></div></div> }
function PreparationView({ session }: { session: AcceleratorSession }) { return <div className="rounded-xl border border-dashed border-gray-200 px-4 py-6"><Activity className="mb-3 h-6 w-6 text-vortex-red" /><h5 className="font-semibold text-gray-900">Access & Prepare 1</h5><p className="mt-2 text-sm leading-relaxed text-gray-600">{session.preparation || 'Complete the existing predetermined sequence before explosive work.'}</p></div> }
function Note({ title, children }: { title: string; children: ReactNode }) { return <section><h4 className="mb-2 text-xs font-bold uppercase tracking-wide text-gray-500">{title}</h4><div className="text-sm leading-relaxed text-gray-700">{children}</div></section> }
function ExerciseNotes({ exercise }: { exercise: AcceleratorExercise }) { return <div className="space-y-5"><div className="rounded-xl bg-gray-50 p-4"><p className="font-semibold text-gray-900">{exercise.dose}</p><p className="mt-1 text-xs text-gray-500">Recovery: {exercise.rest}</p></div><Note title="Why this exercise"><p>{exercise.purpose}</p></Note><Note title="Execution & scaling"><p>{exercise.instruction}</p></Note><p className="border-t border-gray-100 pt-3 text-xs leading-relaxed text-gray-400">Written prescription: {exercise.sourceName}</p></div> }
function EquipmentNotes({ session }: { session: AcceleratorSession }) { return <div className="space-y-5"><Note title="Bring for this class"><ul className="space-y-2">{session.equipment.length ? session.equipment.map((item) => <li key={item}><strong>{item}.</strong> {EQUIPMENT_NOTES[item] ?? 'Confirm safe, usable equipment before delivery.'}</li>) : <li><strong>Bodyweight.</strong> Confirm sufficient clear space for each drill.</li>}</ul></Note><Note title="Station setup"><p>Confirm clear working space, stable surfaces and secure anchors before athletes begin. Follow each exercise’s written clearance and substitution conditions.</p></Note><Note title="Group setup"><p>Equipment quantities depend on group size and supervised waves. Add any equipment required by the existing Access & Prepare 1 sequence.</p></Note></div> }
function DeliveryNotes({ session }: { session: AcceleratorSession }) { return <div className="space-y-5"><Note title={session.minutes ? `${session.minutes.join('–')} minutes of prescribed work` : 'Timing to confirm'}><p>{session.delivery || 'Use the written prescription to set the session timing. Add the actual Access & Prepare 1 duration and group queues while preserving prescribed recovery.'}</p></Note><Note title="Session order"><p>Access & Prepare 1 → 6 explosive exercises → 2 light resilience exercises → 6 primary-strength exercises.</p></Note><Note title="Schedule by readiness"><p>The collection contains 12 numbered class exposures, not 12 consecutive days. Review actual training, technique and recovery before selecting the next class.</p></Note></div> }
function CoachingNotes({ session }: { session: AcceleratorSession }) { return <div className="space-y-5">{session.quality && <Note title="Today’s quality marker"><p>{session.quality}</p></Note>}<Note title="Class-specific intent"><p>{session.explosiveNotes}</p></Note><Note title="Adjust within the dose"><p>On a technical miss, stop, recover and adjust the remaining scheduled attempts. Stop for pain or loss of control. Do not add attempts to replace misses.</p></Note><Note title="Readiness & progression"><p>Advance one variable only when actual execution and recovery support it; otherwise hold or regress.</p></Note></div> }
function PlanOverview({ sessions, selected, onSelect }: { sessions: AcceleratorSession[]; selected: number; onSelect: (index: number) => void }) { return <div><p className="mb-4 text-sm leading-relaxed text-gray-500">Twelve exposures, selected by athlete readiness. Choose a class to open its daily plan.</p><div className="space-y-2">{sessions.map((item, index) => <button key={item.n} type="button" onClick={() => onSelect(index)} className={`flex w-full items-center gap-3 rounded-lg border p-3 text-left ${FOCUS_RING} ${selected === index ? 'border-red-200 bg-red-50' : 'border-gray-100 hover:bg-gray-50'}`}><span className="text-sm font-bold tabular-nums text-vortex-red">{String(item.n).padStart(2, '0')}</span><span className="flex-1"><span className="block text-sm font-semibold text-gray-900">{item.title}</span><span className="mt-0.5 block text-xs leading-relaxed text-gray-500">{item.effort}</span></span><ChevronRight className="h-4 w-4 shrink-0 text-gray-400" /></button>)}</div></div> }
function DetailDialog({ detail, onClose }: { detail: Detail; onClose: () => void }) { const dialog = useRef<HTMLDialogElement>(null); const titleId = useId(); useEffect(() => { const element = dialog.current; const focus = document.activeElement instanceof HTMLElement ? document.activeElement : null; element?.showModal(); return () => { element?.close(); focus?.focus({ preventScroll: true }) } }, []); return <dialog ref={dialog} aria-labelledby={titleId} onCancel={(event) => { event.preventDefault(); onClose() }} onKeyDown={(event) => { if (event.key === 'Tab') { event.preventDefault(); dialog.current?.querySelector<HTMLButtonElement>('button')?.focus() } }} className="m-auto max-h-[85dvh] w-[calc(100%-2rem)] max-w-xl overflow-y-auto rounded-2xl border-0 bg-white p-0 text-gray-900 shadow-2xl backdrop:bg-gray-950/50"><header className="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-gray-100 bg-white p-5"><div>{detail.eyebrow && <p className="mb-1 text-[10px] font-bold uppercase tracking-wider text-vortex-red">{detail.eyebrow}</p>}<h3 id={titleId} className="text-lg font-bold leading-snug">{detail.title}</h3></div><button type="button" autoFocus onClick={onClose} aria-label="Close details" className={`shrink-0 rounded-lg p-1.5 text-gray-500 hover:bg-gray-100 ${FOCUS_RING}`}><X className="h-5 w-5" /></button></header><div className="p-5">{detail.content}</div></dialog> }
