"""Authoring source for the Stage 2 outline, not a workout generator.

The 60 briefs below are individually authored programming decisions. This script
only rotates their offered weekdays, resolves references, and renders the saved
outline/ledgers. It must never generate detailed sessions or completed athlete data.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION = "2.0"
ORDER = ["ACC", "JUMP", "BRAKE", "RUN", "REACT"]

# Per brief: objective; observable target; explosive decision; strength decision;
# rationale. Entries are in family order; offering order rotates each week.
BRIEFS = [
  [
    ["Carry the established short acceleration into this block.", "Reproduce the familiar start and run through the endpoint with a controlled runoff; record comparable efforts without chasing a best time.", "Retain the known start, distance and recovered-attempt dose; calibrate only uncertain conditions.", "Retain the last productive knee-pattern variation, working dose and effort; the latest light review is context, not the sole baseline.", "A usable opening comparison and productive familiar work preserve continuity while revealing changed readiness."],
    ["Reproduce useful jump output and a controlled landing at the established level.", "Land the selected jump in balance without an extra recovery step; an established rebound athlete also keeps repeatable rhythm.", "Retain the qualified jump-and-stick or established low-rebound task; use a familiar throw as complementary upper-body output.", "Retain the established hinge variation and comfortable range; knee, push, pull and brace roles remain complementary.", "Jump expression and hip-pattern strength can both continue; a block boundary alone does not justify changing either task."],
    ["Carry forward controlled braking and a familiar planned redirection.", "Enter at the recorded approach, organize braking before the plant and exit in the intended direction without a balance rescue.", "Retain the athlete's qualified approach and cut; a controlled stop remains the entry route.", "Retain familiar unilateral support and range; observe both sides without forcing equal load when competency differs.", "The initial brake observation establishes a comparable task while preserving meaningful single-leg work."],
    ["Establish comparable upright running output in a verified runway, or a separately identified short-start baseline.", "RUN-U: repeat the established buildup and upright zone without reaching or straining. RUN-S: repeat a short acceleration and safe stop; do not score it as upright speed.", "Choose RUN-U only after runway verification; hold the known running task. If unavailable, select RUN-S and open its own comparison history.", "Retain balanced lower-body work with a modest lead knee-pattern role; retain push, pull and brace without a load test.", "A stable setup is necessary for useful comparison; the facility branch changes the delivered outcome and must remain visible."],
    ["Retain a familiar cue-response task while keeping movement under control.", "Attend to the agreed cue, choose the correct safe path and stop under control; a planned path is acceptable when cue quality breaks down.", "Use the already mastered cue set and approach; keep a familiar throw complementary rather than adding extra running rounds.", "Retain productive push/pull work with small knee/hip and brace roles; preserve shoulder and wrist readiness for tumbling.", "Decision quality can be trained from the opening week without making every continuing athlete relearn a simple start."],
  ],
  [
    ["Repeat acceleration quality while developing the retained knee-pattern lift.", "Keep starts and stopping comparable to the prior ACC exposure; finish the strength work with the intended reserve and the same usable range.", "Hold start, distance, attempts and recovery conditions so strength is the only candidate dose change.", "If the last productive knee exposure met its criterion and recovery is adequate, select one smallest practical load step; otherwise hold. Do not also add repetitions.", "Stable sprint work lets a justified strength change fit without simultaneously raising running stress."],
    ["Make takeoff and landing output more repeatable.", "Use the same takeoff and landing arrangement across recorded attempts; end a series when control requires an extra hop or catch.", "Hold jump/throw dose, implement and complexity; improve consistency through one concise cue.", "Hold the hinge dose and load; use the same controlled range while the coach compares repeatability.", "Reducing avoidable variation is useful progression even when no load or contact count rises."],
    ["Refine braking position before asking for a faster approach.", "Brake before the chosen marker and settle into the intended plant without last-step reaching or trunk collapse.", "Hold approach speed, direction and attempts; improve where and how braking begins.", "For an athlete whose unilateral range is restricted by control, extend only comfortable controlled range; otherwise retain the productive range/load.", "Better control of the same task earns later approach demand; depth and speed do not need to increase together."],
    ["Repeat the selected running branch under reproducible conditions.", "RUN-U: maintain rhythm through the same upright zone. RUN-S: reproduce the same short start; record surface, distance and observation method.", "Hold branch, running distance, effort category and recovery; refine one rhythm cue without extra attempts.", "Retain balanced lower-body dose; allow a push OR pull repetition adjustment only if that anchor's own prior work and time budget support it.", "The running comparison remains interpretable while an independent upper-body anchor can develop at a recoverable dose."],
    ["Improve response accuracy without adding more choices.", "Use the agreed signal consistently and commit to the correct known path while keeping the stopping space clear.", "Keep cue choices, approach and attempts fixed; coach signal consistency and athlete attention.", "Retain upper-body loads and small lower-body roles; improve bracing and controlled repetitions at the same effort target.", "Reliable information and movement are necessary before the later plan changes when the cue arrives."],
  ],
  [
    ["Extend a qualified acceleration task while retaining the familiar start.", "Maintain purposeful projection and a controlled runoff through the selected longer segment; use the old distance if posture or stopping deteriorates.", "For ready athletes, increase only the acceleration distance within verified space; retain attempt count and full recovery. Others keep the prior distance.", "Hold knee-pattern load and working dose to make room for the running-distance change; complementary work stays modest.", "One longer acceleration demand develops continuation of force application without a simultaneous strength or density increase."],
    ["Develop the retained hinge while preserving jump output.", "Keep jump landing/rhythm quality at the prior setup; hinge repetitions remain controlled through the same range at the intended reserve.", "Hold jump and throw setup, contacts, attempts and rest.", "Where the hinge anchor has met its criterion, add a small planned repetition step at the same load; hold other strength variables.", "This exposure emphasizes force development while protecting the explosive comparison from extra impact."],
    ["Apply established braking positions from a slightly more demanding approach.", "Organize braking before the plant and keep the familiar exit line as approach demand rises; reduce approach if balance or spacing fails.", "For qualified athletes, raise approach speed only; retain direction, decision certainty and attempt count. Others retain the controlled approach.", "Hold unilateral range, load and dose; lower-body support must not become another new stressor.", "A faster approach is meaningful only when the athlete can absorb it; it does not also unlock a sharper cut."],
    ["Express relaxed running intent in the established branch.", "RUN-U: sustain the known upright action at a purposeful effort without overstriding. RUN-S: accelerate decisively over the known short distance and stop safely.", "If quality is repeatable, raise intended running effort within the qualified task; hold distance and attempts and allow longer recovery if needed.", "Retain strength variations and doses; remove optional lower-body work if the running effort is unusually demanding.", "Intent rather than density is the chosen running change, and strength supports recovery for it."],
    ["Respond to a slightly later familiar cue without losing the known movement solution.", "Make the correct choice and maintain control with the revised signal timing; return to the earlier cue when stopping becomes rushed.", "Change cue timing only for qualified athletes; retain cue choices, approach speed, distance and attempts.", "Hold push/pull load and dose; retain small knee/hip and brace exposure without a harder finisher.", "Later information develops the perception-action task without disguising extra physical workload as agility."],
  ],
  [
    ["Review acceleration retention under the original comparison conditions.", "Complete comparable familiar starts with controlled runoff; interpret output alongside surface, timing method, readiness and the prior productive record.", "Return to the recorded comparison distance if Week 3 extended it; assessment attempts replace training attempts. Remove nonessential running if recovery needs it.", "Observe the retained knee lift at a familiar submaximal effort; reduce nonessential sets when needed, retaining the productive-dose record for carryover.", "A consolidation window distinguishes useful change from a changed test and avoids making the review an extra workout."],
    ["Review jump consistency and hinge response without an impact peak.", "Compare the same jump task and landing standard with the opening record; note hinge range, control and effort at a familiar load.", "Use the familiar comparison jump; reduce redundant jump/throw attempts when needed and keep rest intact.", "Review a familiar hinge exposure; use fewer nonessential sets if readiness or the prior three weeks warrant it.", "Reviewing output and tolerance preserves a known anchor while allowing recovery before the next emphasis."],
    ["Verify the established braking solution and select the next appropriate demand.", "Perform the recorded approach/direction in balance; identify whether the limitation is approach tolerance, plant position or cue handling.", "Use the comparable planned approach; no new angle or faster approach during the review. Observation replaces equivalent training work.", "Review unilateral control at the established range; hold or reduce work based on recovery rather than forcing a symmetry score.", "The next progression needs a specific limiting factor, not an automatic harder cut for the whole group."],
    ["Review the running branch with an honest comparison boundary.", "RUN-U and RUN-S results remain in separate records; compare only matching setup, effort category and measurement conditions.", "Retain the comparison task; omit surplus efforts if needed. A branch change requires a new baseline, not a claimed speed gain.", "Hold balanced strength at familiar effort or reduce nonessential sets; collect control/effort observations without a maximum test.", "Comparable evidence and lower competing workload make the review useful for the following force/redirection period."],
    ["Verify cue-response reliability before expanding the problem.", "Correct responses and controlled exits remain repeatable under the familiar cue protocol; errors are described rather than converted into punishment work.", "Use the familiar cue task; compare accuracy and control before speed. Keep throw exposure small or omit surplus throws for recovery.", "Review push/pull control and shoulder tolerance at established effort; reduce extra upper-body sets when tumbling or sport demands it.", "The review identifies whether the next emphasis should develop the movement, the cue task or simple consistency."],
  ],
  [
    ["Carry acceleration forward while restoring a productive knee-strength emphasis.", "Recover the established start quality and complete the selected knee-pattern work at its intended reserve after the review week.", "Retain the current qualified acceleration distance and task; a review reduction does not require compensating attempts.", "Restore the last tolerated productive knee dose if recovered; retain load/variation and do not also add a new load step.", "Returning from a review dose is already a workload change and supports the next force-development period."],
    ["Apply jump output to a justified directional emphasis.", "For a lateral candidate, take off and land within a controllable line; retain the familiar jump direction when lateral landing competency is absent.", "If the needs review justifies it, change jump direction only and establish its own baseline; otherwise retain the productive jump anchor. Throw dose stays familiar.", "Hold hinge load and dose while observing response to the jump direction; no simultaneous eccentric-overload addition.", "Direction changes serve an identified redirection need and are not a mandatory replacement of a productive jump."],
    ["Develop force absorption in the established planned cut.", "Accept the prescribed approach through controlled hip/knee action and leave the plant in balance without rushing the exit.", "Hold approach, direction and attempts; emphasize organized absorption and a deliberate reacceleration.", "For ready athletes, choose one small unilateral repetition increase at the same load/range; others hold. Keep complementary lower-body work small.", "The cut remains measurable while unilateral strength receives the selected development change."],
    ["Restore productive running exposure after review without adding a new task.", "Reproduce the established RUN-U or RUN-S action with purposeful effort and sufficient recovery on every selected effort.", "If the review reduced work and readiness permits, restore the last productive attempt dose; hold branch, distance and effort target.", "Retain a recoverable balanced strength dose; do not restore running volume and progress lower-body loading in the same visit.", "Restoration provides useful running exposure while leaving capacity for the week's redirection emphasis."],
    ["Repeat the known cue problem with more consistent movement organization.", "The athlete recognizes the same cue set and controls the first movement and stop without an unnecessary feint or extra step.", "Hold physical dose and choice count; focus on the identified response error from the review. Familiar throws remain complementary.", "Restore the last productive upper-body dose if the review was lighter; retain load and small lower-body roles.", "Meaningful practice can improve decisions without a new reactive drill or increased running stress."],
  ],
    [
    ["Develop the retained knee lift while preserving short acceleration output.", "Starts remain crisp at the familiar distance; the selected lift retains range and technique at the intended effort after a justified load change.", "Hold acceleration distance, approach, efforts and rest; stop chasing output if the athlete is not recovered.", "Allow one smallest practical knee-load step only after the restored productive dose was tolerated; otherwise hold without adding repetitions.", "A single force-development change is easier to evaluate against stable explosive work."],
    ["Make the selected jump direction repeatable and develop the hip anchor.", "Repeat the qualified landing line and balance; hinge work preserves trunk organization and the same comfortable range.", "Hold jump direction, contact dose and rebound demand; use throw quality as a complementary observation.", "If the hinge's actual prior work qualifies, choose one small load adjustment; otherwise hold. Keep repetitions and range unchanged.", "Stable impact exposure leaves room for one justified hip-strength change rather than two concurrent progressions."],
    ["Increase the approach demand of a proven redirection.", "Arrive with enough braking organization to leave on the known line; return to the prior approach when the plant becomes a uncontrolled catch.", "Raise only approach speed for ready athletes; retain cut angle, decision certainty, attempts and rest adequacy.", "Hold unilateral load, range and repetitions; retain useful push/pull/brace work without added leg fatigue.", "The faster approach makes braking more demanding, so lower-body strength holds this visit."],
    ["Refine upright speed expression or the selected short-start branch at a stable dose.", "RUN-U: consistent posture and rhythm through the zone. RUN-S: consistent first steps and controlled runoff; neither branch is progressed by rushing recovery.", "Hold branch, effort category, distance and attempts; improve one execution feature from the previous observation.", "Select one upper-body anchor for a small load step if qualified; retain the other anchors and lower-body dose.", "Running quality can improve through repeatable practice while a separate strength need receives the dose change."],
    ["Expand a qualified response task by one meaningful choice.", "Recognize the added safe option and choose a controlled path; use the prior choice set if errors compromise movement or spacing.", "Add one relevant cue option only when basic choices are reliable; hold cue timing, approach speed, distance and attempts.", "Hold upper-body loads and all strength doses; keep throwing at its familiar task and volume.", "A larger decision set is already a progression and does not justify faster approaches or extra rounds."],
  ],
  [
    ["Improve acceleration consistency while consolidating the developed knee load.", "Maintain the intended start action across comparable efforts and complete the known lift with the same range and reserve.", "Hold all running dose variables; use the athlete's limiting cue and full recovery to reduce inconsistency.", "Retain the currently productive knee load and repetitions; do not increase load merely because last week succeeded.", "A stable exposure tests whether the recent strength and sprint work is recoverable and repeatable."],
    ["Introduce a linked rebound only where landing and rhythm prerequisites already exist.", "An eligible rebound remains low, coordinated and controlled at exit; a jump-and-stick athlete repeats a balanced landing instead.", "For qualified athletes with a reason to link contacts, replace selected isolated efforts with a brief linked task; keep total demanding contacts no greater and do not raise height/distance.", "Hold hinge dose and load; reduce nonessential lower-body work if the new contact organization changes tolerance.", "Rebound organization is a conditional task change, not permission to add contacts or force every athlete off a useful stick landing."],
    ["Use retained braking to leave the plant with purposeful reacceleration.", "Brake early enough to exit on the known line without a stutter or a rushed uncontrolled plant.", "Hold approach and cut angle; improve exit intent without extending the exit distance or adding attempts.", "Hold unilateral dose/load and use the established range; no extra eccentric lowering block is added.", "The objective is a better transition within the same task rather than a longer, more fatiguing shuttle."],
    ["Sustain the established running quality when the athlete is ready for its familiar productive dose.", "RUN-U: the final selected effort keeps the earlier rhythm. RUN-S: short-start mechanics and stopping remain comparable across efforts.", "Retain branch and full recovery; if previous reduced work is now tolerated, restore only the productive attempts, otherwise hold or reduce.", "Hold strength loads; choose modest lower-body support so running quality and upcoming review are protected.", "The athlete demonstrates tolerable consistency without converting speed practice into repeated-sprint conditioning."],
    ["Keep decision quality while developing the familiar upper-body anchors.", "The established cue task stays accurate and controlled; push/pull repetitions meet the same range, control and effort standard.", "Hold the current qualified cue task and physical dose; no new choice or later signal this visit.", "Choose one small repetition step in push OR pull if its prior response supports it; hold the other anchor and external load.", "Separating the strength change from a cue-task change makes the response interpretable and protects coordination."],
  ],
  [
    ["Review acceleration and knee-strength response before adding application demands.", "Compare matching start/distance conditions and familiar submaximal lift control; document what is repeatable, not only the best result.", "Use the retained comparison sprint; assessment replaces equivalent attempts and redundant work can be reduced.", "Observe familiar knee work at known effort; retain or reduce nonessential sets using actual recovery and sport load.", "The review informs whether the next period should apply current capacity or continue developing it."],
    ["Review the current jump branch and preserve a bridge to the original anchor.", "Record the exact direction and isolated/rebound version; compare like with like and distinguish skill change from output change.", "Use one suitable comparison task; any original-anchor check replaces other contacts, never adds an uncounted second jump workout.", "Review hinge control and effort at familiar load; lower surplus work if the preceding contact change or sport demands recovery.", "Branch-specific records prevent a harder-looking jump from being mistaken for evidence of greater output."],
    ["Verify braking at the qualified approach before adding uncertainty.", "Complete the familiar approach and cut with predictable plant control; specify whether a cue task is eligible or a planned cut remains most useful.", "Hold approach and angle; use a small comparable observation inside the existing work and reduce surplus attempts when appropriate.", "Review familiar unilateral control; do not test a maximal load or add a novel balance challenge.", "Readiness for uncertainty is task-specific and cannot be inferred from the calendar reaching the last period."],
    ["Review running consistency within the selected facility branch.", "Keep buildup, zone or short-start distance, rest and scoring conditions comparable; flag any changed setup.", "Retain the known running test and trim surplus efforts when needed; no compulsory peak sprint is added.", "Hold or reduce familiar strength dose; compare useful control/effort rather than maximal load.", "This review protects an honest speed record and room for recovery before application work."],
    ["Review the expanded cue task and upper-body tolerance.", "Choose accurately and maintain the known movement solution; record whether errors arise from the cue rule, attention or physical control.", "Use the qualified cue set at its known approach; remove redundant throws/runs for recovery instead of adding a competition finisher.", "Review push/pull quality at familiar effort; reduce extra shoulder loading when separate tumbling requires it.", "The next application choice follows a clear limitation and does not reward fatigue-driven mistakes with more work."],
  ],
  [
    ["Apply established acceleration to a relevant start cue without changing the sprint problem.", "React to the agreed release cue and reproduce the known acceleration path and stop; use a self-paced start if cue handling degrades the run.", "Choose one change: if useful and qualified, change start cue while holding the current recoverable strength dose; OR retain the cue while restoring a justified knee dose. Retain start position, distance, attempts and rest in both routes.", "If the cue changes, hold the current recoverable knee dose. If knee-dose restoration is the selected change, retain the familiar cue and restore only the last tolerated productive dose, with no load progression. Reconsider the deferred change at the next ACC exposure using actual response.", "A cue change and post-review restoration are distinct changes; selecting one preserves the week's single-change design."],
    ["Express useful jump output while keeping the selected landing task familiar.", "Produce purposeful takeoff and meet the existing landing or rebound-exit standard; compare the same branch rather than chasing distance at any cost.", "Hold jump version, contact dose and familiar effort target; retain purposeful quality intent with adequate rest. Throw selection remains familiar.", "Restore a tolerated productive hinge dose if appropriate after review; hold load and do not pair restoration with added jump demand.", "Application retains purposeful effort in a familiar jump; hinge-dose restoration is the only candidate workload change."],
    ["Use a simple cue with an established brake-and-exit solution.", "Recognize the cue early enough to brake and leave in balance; planned direction remains available when cue readiness is absent.", "For qualified athletes, replace some planned attempts with one simple direction cue while keeping approach speed, angles and total attempts unchanged.", "Hold unilateral dose, load and range; maintain upper-body and brace support.", "Information uncertainty is the chosen change; approach force and strength loading must remain stable."],
    ["Express the qualified running action under consistent observation.", "RUN-U: relaxed purposeful action through the zone. RUN-S: purposeful short acceleration; use the same recorded branch and comparison setup.", "Restore the known productive running dose if review reduced it and readiness supports it; hold distance and task complexity.", "Hold balanced strength load and dose; omit optional lower-body work when restoring running exposure is the main change.", "Application begins from established capacity and recorded conditions rather than a compulsory new test."],
    ["Apply the known cue task to an opponent's constrained movement.", "Read the defined partner action and choose a safe known path while respecting lane boundaries and controlled stopping.", "For eligible athletes, change the information source to a predictable constrained partner; hold paths, approach, attempts and recovery. Otherwise retain the coach cue.", "Hold the current recoverable upper-body and supporting strength doses while the information source changes; defer any post-review restoration to a later appropriate exposure. Lower-body and brace roles stay modest.", "A partner supplies more relevant information only when rules and space keep the task learnable and measurable; strength restoration is not stacked onto that change."],
  ],
  [
    ["Develop the retained acceleration or knee anchor from the previous ACC decision.", "Meet the qualified cue/start and stop standards; knee work retains range and effort quality under any selected strength change.", "First revisit the deferred Day 43 choice: if a cue change is still useful and qualified, select it alone and hold strength dose. Otherwise hold cue, start, distance and attempts while considering the knee decision.", "If a deferred cue change is selected, hold the knee dose. Otherwise choose one justified knee variable from the actual record—small load OR repetition change—or hold if speed/sport is the priority. Never add both a deferred task change and a new strength progression.", "The next relevant exposure resolves the previous choice from actual response; a deferred progression is an option, not accumulated debt."],
    ["Repeat explosive output while retaining the force base.", "The selected jump/throw setup produces consistent coordinated efforts and controlled landings without escalating the task after one best attempt.", "Hold jump/throw versions, contacts, implement and rest; refine output consistency.", "Hold the established hinge load, range and dose; retain complementary work at a recoverable level.", "A consolidation exposure inside the application period protects both output and force capacity."],
    ["Improve the execution of the qualified cue-and-cut task.", "Maintain the planned braking organization after the cue and exit on the intended line; separate wrong choices from uncontrolled plants.", "Hold information rule, approach and attempts; improve cue recognition and movement execution without adding a sharper angle.", "Retain unilateral work at familiar dose; choose easier support if recent sport or tumbling affects control.", "Mastery of the same uncertainty is useful progress before any additional decision pressure."],
    ["Preserve running exposure while allowing an independent upper-body progression.", "RUN-U/RUN-S quality remains consistent with the prior branch; the chosen upper-body task keeps range and the intended reserve.", "Hold branch, distance, effort category, attempts and rest.", "Progress one upper-body anchor by a small load OR repetition change if warranted by its completed record; hold lower-body and other upper-body doses.", "Independent strength development can continue without increasing every running variable late in the block."],
    ["Respond later to the established information source while retaining safe paths.", "Commit to a correct known path with a controlled stop despite the later signal; return to earlier information when a safe solution is lost.", "For qualified athletes, change cue timing only; keep partner rules or cue set, approach speed, choices and attempts fixed.", "Hold all strength loads/doses; preserve shoulder tolerance and reduce optional throwing if the cue work requires more attention.", "Later information is sufficient progression; added speed, rounds and loading would obscure the intended change."],
  ],
  [
    ["Produce representative acceleration efforts before the final comparison window.", "Repeat known starts with purposeful effort and controlled stopping; stop surplus efforts when quality is below the athlete's normal level.", "Hold the known task and recovery; retain or trim nonessential attempts according to recovery, without rehearsing repeated maximal tests.", "Retain useful knee strength at established effort; reduce nonessential sets if sport or fatigue would compromise the upcoming comparison.", "Maintaining intensity of appropriate effort with manageable volume preserves readiness for a meaningful review."],
    ["Express a stable jump branch and arrive ready for its final review.", "Land or finish the rebound in control on representative efforts; the comparison task stays recognizable.", "Retain jump/throw setup; omit redundant efforts when needed rather than introduce a new direction or implement.", "Retain familiar hinge loading with enough reserve; reduce optional lower-body volume when impact or sport exposure is high.", "The next review needs a recovered athlete and a known task, not last-minute novelty."],
    ["Consolidate controlled braking and redirection at the athlete's useful level.", "Repeat the qualified planned or cue task without rushed planting; choose the simplest version that still serves the athlete's current need.", "Hold approach, direction and cue rule; trim surplus attempts when readiness requires it.", "Retain familiar unilateral control and load; reduce unnecessary sets to protect the following comparison window.", "The aim is a reliable skill under tolerable loading, not the hardest available cut before the block ends."],
    ["Keep running quality available while protecting the final observation.", "RUN-U or RUN-S action remains purposeful and coordinated; quality is judged against the athlete's normal familiar task.", "Retain the branch and recovery; reduce surplus efforts when needed. No longer test zone or extra shuttle is introduced.", "Keep balanced strength familiar and submaximal; remove optional work if it competes with running recovery.", "Useful exposure can be retained without accumulating fatigue merely to fill a late-block training slot."],
    ["Demonstrate a reliable response task with manageable total demand.", "Recognize the established information and finish each selected movement in control; explain the rule accurately without a long pre-rehearsal.", "Hold the qualified cue/partner protocol and physical task; reduce redundant runs/throws if sport or tumbling requires freshness.", "Retain push/pull and full-body support at familiar effort; reduce surplus sets rather than test maximum capacity.", "Reliable participation and movement are the carryover priority, so optional competitive volume is unnecessary."],
  ],
  [
    ["Record acceleration and knee-strength carryover for the next block.", "Compare the same sprint conditions and a familiar submaximal knee exposure; document actual work, response and the next conditional choice.", "Use the recorded comparison task; count observations inside the selected attempts. No obligatory personal best or bonus efforts.", "Use a recoverable familiar knee dose for observation; preserve both the recent productive prescription and this review dose in the handoff.", "The next block should start from demonstrated capacity and recovery, not from a single best effort or a reduced review dose alone."],
    ["Record the useful jump/hinge branch and its next development decision.", "Compare matching jump conditions and familiar hinge control/effort; record why to retain the branch or choose an alternative next block.", "Use the relevant comparison jump; any original-anchor check replaces other contacts. Keep throw work familiar and bounded.", "Observe familiar hinge work without a maximal test; retain the productive-dose record alongside the current review work.", "The handoff preserves useful force and landing competencies rather than restarting all jump and hinge instruction."],
    ["Record the qualified braking level and the next justified redirection demand.", "Document approach, direction, cue status, control and actual response so another coach can reproduce the current task.", "Review the known planned or cue task at a comparable approach; no new angle, speed or uncertainty is introduced for graduation.", "Observe familiar unilateral range and effort; record each side and any current restriction without fabricating readiness clearance.", "A precise qualified task is a usable starting point for the next block and for any targeted remediation."],
    ["Close the running record with a branch-specific comparison and next-block plan.", "Document RUN-U runway/setup or RUN-S short-start setup, actual output/quality, conditions and recovery; unknown measures stay unknown.", "Use the retained comparison task with full recovery; a changed facility requires a new baseline rather than cross-branch improvement claims.", "Observe recoverable balanced strength; preserve each anchor's most recent productive and review doses for the next coach.", "The next program inherits a credible running history and known strength capacity, not a calendar-based reset."],
    ["Carry a reproducible response task and full-body strength record into the next block.", "Record cue/partner rules, choices, movement control, actual upper-body work and recovery; select a retain/develop/remediate decision by domain.", "Review the known qualified task; reduce surplus running/throwing and avoid a fatigue-based final competition.", "Observe familiar push/pull effort and retain small lower-body/brace work; preserve productive-dose and latest-review records separately.", "The handoff joins decision skill, force capacity and participation readiness without treating twelve weeks as automatic mastery."],
  ],
]

WEEKS = [
 ("Continue and calibrate", "Carry useful prior-block work into productive training; standardize observations without a beginner reset.", "Retain established doses and variants; calibrate only uncertainty.", "Comparable opening observations replace some work; actual prior-block history is required for individual continuation."),
 ("Repeat and refine", "Make execution repeatable while allowing a single justified strength or range change.", "Stabilize explosive tasks; selected strength changes remain anchor-specific.", "Record cue effects, usable range and reserve; judge repeatability rather than best-only output."),
 ("Develop one demand", "Develop a selected distance, approach, intent, hinge dose or signal-timing demand from demonstrated prerequisites.", "One planned dose/task variable per lead change; preserve recovery and complementary work.", "Check response after each changed exposure and against adjacent sport/tumbling; hold when only partly ready."),
 ("Review and consolidate", "Compare known tasks and identify what to retain or develop in the next emphasis period.", "Comparable observation, retention or justified reduction; no forced universal deload.", "Review work replaces training work; record productive dose separately from a lighter review dose."),
 ("Restore and direct force", "Resume productive doses after review and apply an identified force/redirection need.", "Restoration is a change; directional variation requires a reason and its own baseline.", "Check tolerance to restored workload and any newly chosen direction before adding further demand."),
 ("Develop force or information", "Develop a selected strength, approach or cue-choice demand while retaining complementary output.", "No simultaneous growth of approach speed, decision difficulty, impact dose and strength load.", "Record the limiting factor and actual response; alternate developmental and lighter routes for frequent attendance."),
 ("Make development repeatable", "Consolidate useful loads and redirection; conditionally organize linked contacts without increasing impact volume.", "Repeatability leads; a rebound branch requires landing/rhythm competence and no contact increase.", "Review fatigue across actual visits and sport, including grip/shoulder demands before tumbling."),
 ("Verify readiness to apply", "Review like-for-like output and establish eligibility for selected application tasks.", "Retention, comparison or recovery; a later phase does not confer cue/rebound eligibility.", "Review each current branch and record whether continued simple practice is the best next step."),
 ("Apply established capacity", "Apply known movement to justified start cues, directions or constrained partner information.", "One information/task change or restoration; maintain strength foundations.", "Record whether the added information improves a useful task without degrading control or spacing."),
 ("Refine the useful application", "Improve an established application or one strength anchor according to the athlete's remaining need.", "Do not escalate all tasks because the block is nearing completion.", "Separate response errors from movement errors; preserve the same comparison conditions."),
 ("Retain output and readiness", "Repeat representative work while managing fatigue ahead of the final review and current sport demands.", "Hold useful effort/skill; reduce surplus work when justified, without a compulsory taper.", "No last-minute novel tasks or hidden test rehearsals; identify records needed for the handoff."),
 ("Verify and carry forward", "Document current competencies, productive doses, review response and a conditional next-block plan.", "Compare familiar tasks and preserve useful anchors; no compulsory maximum test or beginner restart.", "Record both recent productive and latest review work, actual attendance and sport context; make up missed observations within later normal visits."),
]

if __name__ == "__main__":
    from render_main_outline import build
    build(ROOT, VERSION, ORDER, BRIEFS, WEEKS)
