import { useCallback, useEffect, useState } from 'react'
import { adminApiRequest } from '../../../utils/api'

interface MissedClass { id:number; missed_on:string; class_name:string|null; reason:string|null; approval_status:'pending'|'approved'|'declined'; approval_note:string|null }

export default function MemberMissedClassesTab({ memberId }: { memberId:number }) {
  const [rows,setRows]=useState<MissedClass[]>([]); const [date,setDate]=useState(''); const [reason,setReason]=useState(''); const [status,setStatus]=useState('pending'); const [note,setNote]=useState(''); const [error,setError]=useState<string|null>(null)
  const load=useCallback(async()=>{const r=await adminApiRequest(`/api/admin/members/${memberId}/missed-classes`); const b=await r.json(); if(!r.ok) throw new Error(b.message); setRows(b.data||[])},[memberId])
  useEffect(()=>{void load().catch(e=>setError(e.message))},[load])
  const save=async()=>{setError(null); const r=await adminApiRequest(`/api/admin/members/${memberId}/missed-classes`,{method:'POST',body:JSON.stringify({missedOn:date,reason,approvalStatus:status,approvalNote:note})}); const b=await r.json(); if(!r.ok){setError(b.message);return} setDate('');setReason('');setNote('');await load()}
  const review=async(id:number,approvalStatus:'approved'|'declined')=>{const approvalNote=window.prompt(`Required note for ${approvalStatus}:`);if(!approvalNote?.trim())return;const r=await adminApiRequest(`/api/admin/members/${memberId}/missed-classes/${id}`,{method:'PATCH',body:JSON.stringify({approvalStatus,approvalNote})});const b=await r.json();if(!r.ok){setError(b.message);return}await load()}
  return <div className="space-y-4"><div className="rounded-xl border bg-white p-4 space-y-3"><h4 className="font-semibold">Record missed class</h4><div className="grid gap-3 md:grid-cols-2"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-lg border px-3 py-2"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border px-3 py-2"><option value="pending">Pending approval</option><option value="approved">Approved absence</option><option value="declined">Not approved</option></select><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason or context" className="rounded-lg border px-3 py-2"/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Approval note" className="rounded-lg border px-3 py-2"/></div><button type="button" disabled={!date} onClick={()=>void save()} className="rounded-lg bg-gray-900 px-3 py-2 text-sm text-white disabled:opacity-50">Record missed class</button>{error&&<p className="text-sm text-red-700">{error}</p>}</div><div className="divide-y rounded-xl border bg-white">{rows.map(r=><div key={r.id} className="p-3 text-sm"><div className="flex justify-between gap-3"><strong>{new Date(r.missed_on).toLocaleDateString()} · {r.class_name||'Class'}</strong><span className={r.approval_status==='approved'?'text-green-700':r.approval_status==='declined'?'text-red-700':'text-amber-700'}>{r.approval_status}</span></div>{r.reason&&<p>{r.reason}</p>}{r.approval_note&&<p className="text-gray-500">{r.approval_note}</p>}{r.approval_status==='pending'&&<div className="mt-2 flex gap-2"><button onClick={()=>void review(r.id,'approved')} className="rounded border px-2 py-1 text-green-700">Approve</button><button onClick={()=>void review(r.id,'declined')} className="rounded border px-2 py-1 text-red-700">Decline</button></div>}</div>)}{!rows.length&&<p className="p-3 text-sm text-gray-500">No missed classes recorded.</p>}</div></div>
}
